### PR TITLE
Require python2-matplotlib >= 1.5.2 on RHEL 7

### LINKED ISSUE #16873: Incorrectly rendered latex formulae in VSI with matplotlib < 1.3
### Expected behavior

Equations should be displayed as expected.
### Actual behavior

On RHEL7:
vsi-latex-rhel7

while on Ubuntu with mpl v1.3.1:
vsi-latex-ubuntu
### Steps to reproduce the behavior

This will not produce the above picture but a simplified version that demonstrates the same error.

Run the following script:

``` python
CreateSimulationWorkspace(Instrument='mari', BinParams='-90,0.01,100', OutputWorkspace='mari')
AddSampleLog(Workspace='mari', LogName='ei', LogText='90.1', LogType='Number')
ConvertToMD(InputWorkspace='mari', QDimensions='Q3D', OutputWorkspace='mdws')
```

and open the `mdws` in the VSI. On RHEL 7 you notice that the superscript is not drawn correctly. It should be a -1 but instead a symbol is drawn.
### Platforms affected

I think this just affects those platforms with mpl < 1.3: RHEL 6, RHEL 7

I tried upgrading matplotlib with pip using `pip install --user --upgrade --no-deps matplotlib`, which installs it in the user's home directory. The equations are then rendered correctly.

### PR DESCRIPTION
**Pull request by martyngigg**
Places a minimum requirement of matplotlib >= 1.5.2 on the RHEL 7 rpm. The rpms were built on the [mantid copr](https://copr.fedorainfracloud.org/coprs/mantid/mantid/) and are also in the ISIS repository.

**To test:**

Build a package on RHEL 7 and verify it requires `python2-matplotlib >= 1.5.2`

Fixes #16873

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@stuartcampbell Would you have anytime to review this?

**Comment by stuartcampbell** [comment]
@martyngigg Sorry - I didn't see the notification.  

I might be just missing it, but I can't see where we are requiring the newer version ?

**Comment by martyngigg** [comment]
@stuartcampbell No problem. It's not particular urgent I just wanted to get it out of the way

**Comment by stuartcampbell** [comment]
Looks ok, I just want to check what happens to the installed 'old' versions when matplotlib updates as will be done when `mantidnightly` updates.

**Comment by martyngigg** [comment]
@stuartcampbell I know you must be busy at the moment but did you get a chance to verify this?

**Comment by stuartcampbell** [comment]
I think it looks good... Don't have access to a PC to test this at the moment but I say :shipit:

**Comment by martyngigg** [comment]
Thanks!

**Pull request merged**
