### PR TITLE
Add default peak function setting to EngDiff UI

### LINKED ISSUE #31490: Automatically set default peak function to BackToBackExponential in EngDiff UI
There are many back-to-back expontnial based models in mantid, however the BackToBackExponential function is the most suitable for ENGIN-X and the instrument scientist want this to be set as the default peak function in the Eng Digg UI fitting tab. This will mean users do not get confused between similarly named functions and don't have to open the mantid general settings,

### PR DESCRIPTION
**Pull request by RichardWaiteSTFC**
**Description of work.**
Added setting for default peak function in the EngDiff UI. This presents the user with a drop-down box of a few relevant functions (the users can still select from the full list in the interactive tool when the fit property browser is open, but the aim of this is to not overwhelm the user with similarly named functions - in particular the back-to-back exponential based ones).

The default peak function has been set to BackToBackExponential for which coefficients have been refined for ENGIN-X (stored in the parameters.xml file). The default peak is set when the fitbrowser is init (and it retrieves this from the UI settigns), this means even if you change the default peak in the config settings after opening the UI, the default peak func is reset to whatever is in the UI settings when you open the interactive menu to add a peak - this is deliberate! This is done so that choice of peak function in other plots etc. outside the UI don't change the defualt peak in the UI.

**To test:**
(1) In the main workbench settings, set the peak function to a `Gaussian` (File > Settings >Fitting > Default peak shape)
(2) Open the EngDiff UI (Interfaces > Diffraction > Engineering Diffraction)
(3) Open the workbench settings and check the default peak shape is now `BackToBackExponential`
(4) Go to the fitting tab, load in some focussed data (to make focussed data follow the instructions in Test 1 here https://developer.mantidproject.org/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.html or get the data from PR #29726)
(5) Plot the data  and open the fitting tab and add a peak - it should be a `BackToBackExponential`
(6) Open the UI settings again and change the peak function to  `Lorentzian` - this shouldn't update the peak function in the open UI - you can confirm this by adding another peak, it should still be a `BackToBackExponential`
(7) Close the UI and check that the peak function in the workbench settings is still a `BackToBackExponential`
(8) Open the EngDiff UI, check the UI settings has a default peak of `Lorentzian` (i.e. it remembers what was set in step 6), check the peak function in the main workbench is now a `Lorentzian`.
(9) Change default peak in the main workbench settings to `Gaussian`
(10) Repeat steps 4-5 - this time the peak added should be `Lorentzian` (i.e. the first peak added will always be the default peak in the UI settings)

Fixes #31490

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Harrietbrown** [comment]
An issue I see with this is that it alters the main workbench settings without informing the users, and does not change them back after it closes. so a mistaken opening of the interface can change a users default peak.
It would be better if it kept this setting only to the EngDiff interface or that it cahnges the settings back when the interface is closed.

**Comment by RichardWaiteSTFC** [comment]
> An issue I see with this is that it alters the main workbench settings without informing the users, and does not change them back after it closes. so a mistaken opening of the interface can change a users default peak.
> It would be better if it kept this setting only to the EngDiff interface or that it cahnges the settings back when the interface is closed.

Yep good spot, I'll try and reset it on closing the UI

**Comment by RichardWaiteSTFC** [comment]
@Harrietbrown if you get a chance could you re-review this please, thanks!

**Comment by Harrietbrown** [comment]
Is there ny way we could make it so that the changes to the default peak type in the UI settings could take effect without having to close and open the interface again? so that if I chaged the peak type to lorenzian the next peak I add qwould be Lorenzian instead of what the previous default was.

**Comment by RichardWaiteSTFC** [comment]
> Is there ny way we could make it so that the changes to the default peak type in the UI settings could take effect without having to close and open the interface again? so that if I chaged the peak type to lorenzian the next peak I add qwould be Lorenzian instead of what the previous default was.

Sorry, I'm not sure what you mean. Are you asking is it possible to change the peak type to e.g. Lorentzian in the UI settings and for that to be the default peak type in the UI?

**Comment by Harrietbrown** [comment]
> > Is there ny way we could make it so that the changes to the default peak type in the UI settings could take effect without having to close and open the interface again? so that if I chaged the peak type to lorenzian the next peak I add qwould be Lorenzian instead of what the previous default was.
> 
> Sorry, I'm not sure what you mean. Are you asking is it possible to change the peak type to e.g. Lorentzian in the UI settings and for that to be the default peak type in the UI?

Yes exactly.

**Comment by RichardWaiteSTFC** [comment]
> > > Is there ny way we could make it so that the changes to the default peak type in the UI settings could take effect without having to close and open the interface again? so that if I chaged the peak type to lorenzian the next peak I add qwould be Lorenzian instead of what the previous default was.
> > 
> > 
> > Sorry, I'm not sure what you mean. Are you asking is it possible to change the peak type to e.g. Lorentzian in the UI settings and for that to be the default peak type in the UI?
> 
> Yes exactly.

OK - so if I understand correctly this is the way I originally had it in old (now closed) PR #31502 but to do it I had to change the behaviour of the fitbrowser (those changes I put in a separate PR #31509 - also closed). 
So I could change the config (i.e. the workbench-wide) settigns when the default peak is chosen in the EngDiff UI settings, but the fitbroswer/interactive tool of the fitbrowser would reset that peak with whatever the default peak was when it was initialised (which is done on opening the EngDiff interface) when the user tight-clicks on the plot. The interactive-tool gets out of sync with the default peak in the config/workbench wide settings, I had a PR up to fix that (see #31509 for more details) but it would have changed the default behaviour - specifically it wouldn't have been possible to have multiple plots open with different peak shapes as default. It was decided not to do this.
In practice the EngDiff users will not be changing peak shapes much anyway, so this lighter-touch solution was preferable because it didn't impact the rest of workbench.

**Comment by Harrietbrown** [comment]
> > > > Is there ny way we could make it so that the changes to the default peak type in the UI settings could take effect without having to close and open the interface again? so that if I chaged the peak type to lorenzian the next peak I add qwould be Lorenzian instead of what the previous default was.
> > > 
> > > 
> > > Sorry, I'm not sure what you mean. Are you asking is it possible to change the peak type to e.g. Lorentzian in the UI settings and for that to be the default peak type in the UI?
> > 
> > 
> > Yes exactly.
> 
> OK - so if I understand correctly this is the way I originally had it in old (now closed) PR #31502 but to do it I had to change the behaviour of the fitbrowser (those changes I put in a separate PR #31509 - also closed).
> So I could change the config (i.e. the workbench-wide) settigns when the default peak is chosen in the EngDiff UI settings, but the fitbroswer/interactive tool of the fitbrowser would reset that peak with whatever the default peak was when it was initialised (which is done on opening the EngDiff interface) when the user tight-clicks on the plot. The interactive-tool gets out of sync with the default peak in the config/workbench wide settings. I had a PR up to fix that (see #31509 for more details - essentially I always got the peak function from the settings in the interactive tool) but it would have changed the default behaviour - specifically it wouldn't have been possible to have multiple plots open with different peak shapes as the current function to add. So it was decided not to make the above changes.
> In practice the EngDiff users will not be changing peak shapes much anyway, so this lighter-touch solution was preferable because it didn't impact the rest of workbench.

That sounds reasonable. if you resolve the conflicts I'll give it a final review.

**Comment by RichardWaiteSTFC** [comment]
> That sounds reasonable. if you resolve the conflicts I'll give it a final review.

Thanks, I have just fixed the merge conflict in the release notes.

**Review by Harrietbrown — APPROVED** [review]
Good job, the settings reset when the GUI is closed now so it won't interfere with anything else.

**Comment by martyngigg** [comment]
Can I just query the change to the global default? I agree with Harriet that having things change behind the scenes is not a good experience for users so I'm glad it resets back.
My question though is whether it needs to even touch the global default?

**Comment by RichardWaiteSTFC** [comment]
> Can I just query the change to the global default? I agree with Harriet that having things change behind the scenes is not a good experience for users so I'm glad it resets back.
> My question though is whether it needs to even touch the global default?

It should be noted that the default peak in the global settings is only overwritten if someone actually loads in data and adds a peak in the fitting tab of the UI (just opening the UI doesn't change the peak type) - i.e. we can reasonably the user is an EngDiff user! EngDiff users will do all their peak fitting inside the UI (that is the point of the fitting tab in the UI) so I don't think it is likely someone will be trying to fit a peak in an external plot (and even if they are they'll be doing it with the same data so will likely want to use that peak anyway and they'll probably be more expert at mantid and be familiar with changing peak function). 

To address your point about doing it without changing the settings, adding a peak in the interactive tool will change the global settings as in any plot (as an aside the default peak type is perhaps misleadingly named - it should probably be called the current peak type! In that respect it's quite an unusual global setting).  
This is done here (which eventually calls SetDefaultPeakType in FitPropertyBrowser.cpp)
https://github.com/mantidproject/mantid/blob/465ed823cb07a8aa3cad4520a37c80a1ee25649e/qt/python/mantidqt/widgets/fitpropertybrowser/interactive_tool.py#L211
this is actually what I wanted because then if the default peak type is changed in the global settings it will be overwritten when you add a peak in the UI . If you're concerned I could overload this function in a EngDiff specific `interactive_tool` - I think just removing the above line would break the normal peak function selection/adding - i.e. I think it depends on it being overwritten because the code that interprets the mouse click and adds a peak doesn't know about the function, just returns fwhm, center etc.
https://github.com/mantidproject/mantid/blob/465ed823cb07a8aa3cad4520a37c80a1ee25649e/qt/python/mantidqt/widgets/fitpropertybrowser/interactive_tool.py#L260
but it might be possible to get it to work - I can try this if you like.

**Comment by RichardWaiteSTFC** [comment]
If you comment out 
https://github.com/mantidproject/mantid/blob/465ed823cb07a8aa3cad4520a37c80a1ee25649e/qt/python/mantidqt/widgets/fitpropertybrowser/interactive_tool.py#L211
when you change function in the interactive tool it and add a peak, it adds the original peak type - i.e. the user can no longer change the peak function in the interactive tool (and as noted in #31509, updating the peak function in the settings won't update it in the fitbrowser either).
Instead of commenting the above, if I comment this line in the cpp class
https://github.com/mantidproject/mantid/blob/68807241aa3f38cb10850c8cf7262977238b0ec2/qt/widgets/common/src/FitPropertyBrowser.cpp#L1045
In this case it does work - i.e. I can change the default peak without affecting the global settings - so I would need a EngDiff UI browser that inherits from FitProertyBrowser.cpp and overwrites `setDefaultPeakType`.
At this point I think it's worth asking is this worth it, and is the behaviour what the users would expect? As I say above the default peak type is an unusual setting that users are used to overwriting in a session - I think those familiar with mantid would expect the peak they see in the UI to carry over between sessions (and outside the UI). Those unfamiliar with mantid will probably only ever use the UI and never even learn about the global setting.

**Comment by martyngigg** [comment]
As discussed offline, we'll generate task for the core team to improve how this default/current setting is worked with so that the fit browser is not affecting global settings without being explicit about it.

We'll merge this and the improvement task will be worked on before the next release.

**Comment by RichardWaiteSTFC** [comment]
Have made issue relating to default peak function behaviour
https://github.com/mantidproject/mantid/issues/31930

**Pull request merged**
