### PR TITLE
Engineering Diffraction GUI can load and plot multiple runs

### LINKED ISSUE #21082: Engineering Diffraction GUI - Fitting tab should support loading multiple runs
The fitting tab in the ED GUI currently only allows the user to load one run at a time. The user should be able to load a range of runs and select which to fit from the list box at the side of the plot

### PR DESCRIPTION
**Pull request by josephframsay**
Loading and plotting multiple focused runs in the fitting tab of the ED GUI has been implemented. In order to achieve this, work was started on implementing an explicit model (as opposed to essentially using the ADS) for the fitting tab.

Note: the fitting tab is a work in progress. Attempting to do a fit will probably crash Mantid, and some of the code is a little rough around the edges as I haven't yet moved all the model-ly stuff into the model

**To test:**
[Re-enable the GUI](https://github.com/mantidproject/mantid/commit/8011de68c96312cf2ccf746ac34c8d433a07534e) and build.

Some sample data is [here](https://github.com/mantidproject/mantid/files/1460806/ENGINX_focused_runs.zip).

Open the ED GUI (Interfaces > Diffraction > Engineering Diffraction) and go to the fitting tab. Click the first Browse button and select all (or some combination of) the attached files, then hit Load. The loaded workspaces should appear in the list next to the plot, labelled with run number and bank number. Clicking on these should plot the corresponding workspace. Try and break things, and also try renaming the files for run 277208 and seeing if the load still works.

Partially fixes #21082 

**Release Notes** 

The change isn't complete, so shouldn't go in the release notes. I'll add it once fitting is wired up

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by ElliotAOram — CHANGES_REQUESTED** [review]
If you attempt to load a an invalid file (e.g. write `-1` in the `FocusedRun #:` field and click load) MantidPlot crashes.
Probably just needs some validation on this input field.

**Review by ElliotAOram — APPROVED** [review]
New changes ensure that the file can be found and handle the exception nicely if it can't. All good to go!

**Review by martyngigg — CHANGES_REQUESTED** [review]
@josephframsay I suspect you may have started this branch before the recent merge with the changes to CMake Qt layout.

Essentially the `qt/scientific_interfaces/test/CMakeLists.txt` should no longer exist and the test files should be added in the main `qt/scientific_interfaces/CMakeLists.txt`

Could you make those changes, please?

**Review by martyngigg — APPROVED** [review]
Thanks, @josephframsay .

**Pull request merged**
