### PR TITLE
Tidy up diffraction release notes for 5.0

### LINKED ISSUE #28237: Neaten up release notes for Diffraction
- Add screenshots
- Expand out one line descriptions for significant features
- Rearrange to make sense

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

Tidied up the diffraction release notes for release 5.0. Added a couple of screenshots, expanded on some items, removed imaging headings and removed some duplicates

**To test:**

Read release notes either in GitHub or in nightly build

Fixes #28237.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by RichardWaiteSTFC — DISMISSED** [review]
There are probably two bug fixes relating to the IntegrateEllipsoids, would it be possible to either add
"- IntegrateEllipsoids and IntegrateEllipsoidsTwoStep now return the correct error on the integrated intensity of non Event mode data"
Or combine the above with the other bug fix that is already there

**Review by DanielMurphy22 — CHANGES_REQUESTED** [review]
Really small nit-picks: 
- a**n** parameter on line 29 ; an -> a
- IndexPeaksWith**s**atellites on line 57 ; s -> S

Otherwise great structure and good images! Checked all links work.

**Review by DanielMurphy22 — APPROVED** [review]
All good, builds should pass as they did before the typos were fixed!

**Comment by martyngigg** [comment]
Docs build as passed. Not waiting for others.

**Pull request merged**
