### PR TITLE
Use Rename with Monitors  in reduction

### LINKED ISSUE #14102: Deploy changes introduced by #14022 and #14071 to ISIS reduction
This ticket is part of #13980 and indents to simplify framework to make main changes, requested there. 

Depends on #14022 and #14071 to be completed.

### PR DESCRIPTION
**Pull request by abuts**
Part of #13980, fixes #14102 

Its small changes to ISIS direct inelastic reduction, deploying RenameWorkspace algorithm changes. Unit and system tests are passing, so these changes have not broke anything. 
Changes are internal so no release notes are necessary. 

As the meaningful changes are minor, I used these opportunity to dramatically decrease pylint count.

### CODE REVIEW

**Comment by peterfpeterson** [comment]
There is a nice implementation of the change to `RenameWorkspace`. However, there is a ton of completely unrelated pylint changes. Most of those are telling pylint to ignore the issues. It would be much better if the two sets of changes were separated.

**Comment by abuts** [comment]
Yes, git is much more confusing then track was. There are file last commits here  (starting from 3ff4e0c) , not thirty as git suggests, and all other commits should go as they are actually already in master.  PR-s do not support subsequent branches nicely. 

And 3ff4e0c is already extract of various python changes from other branch which I have divided for clarity.  Majority of these changes were pylint and only some were related to deploying RenameMonitors. All other changes are minor and to fix the code. 
as there were plenty of pylint there already, it was worth to add more.

In theory it would be better to split it into pylint and essence but It would be too much efforts as 3ff4e0c already have a lot of pylin. The essential changes are minor and unit tested, so this ticket can be accepted as mainly pylint.

**Comment by FedeMPouzols** [comment]
All the commits from the previous branch(es) that this one follows on are shown here, but only the last 5 are new. The way github shows it is a bit messy but you can still more or less guess it by looking at the issue number in the commit messages (14102).

- I see the point in pylint-disabling issues like `too-many-instance-attributes`, `max-attributes` or `too-few-public-methods`. We should maybe reconsider the limits that we have in our `pylint.cfg`.
- Maybe you could avoid the disable of `unused-variable` when you need to return multiple variables from `GetEi` and other functions by using the "throw away" variable (`_`). Although there's also the consideration that having an explicit variable name can make those lines more readable.
- The `disable=bare-except` doesn't look good. Should that be a RuntimeError, or can any other more arcane exception happen there?

Anyway, this uses the new RenameWorkspace option and works well so it is ready to be merged. @abuts let me know if you want to make changes to the pylint disables or otherwise merge as it is.

**Comment by abuts** [comment]
@FedeMPouzols  Thank you for this review. Pylint complains about Exception too. (Exception too wide). In addition to that, as I understand, Exception is deprecated in Python 2.7 where it becomes RuntimeError but we still use 2.6 in RHEL6. This is why I am keeping this kind of exception in the places where an exception may be thrown from C++ code.

 As the code works as it is and it can be subtle differences in some circumstances when exception is thrown and I am not sure all these cases are covered by tests I would rather leave it alone. Each time working with code I am thinking of modifying these places, but it should be done very carefully and on case by case basis. 

The errors may arise otherwise that is very difficult to find. Better to leave this alone for the time being.

**Pull request merged**
