### PR TITLE
Make VSI popups modal

### LINKED ISSUE #18733: Make VSI popups Modal
Spotted by Jon Taylor

### Expected behavior
Dialogs on the VSI should be able to come in front of the main VSI window

### Actual behavior
They are hidden behind

### Steps to reproduce the behavior
Open VSI and click something that generates a dialog. For example, setting the rotation point.

### Platforms affected
OSX

### PR DESCRIPTION
**Pull request by samueljackson92**
**To test:**

Reproduce instructions in the ticket. Check that all but edit button next to the "Axis Aligned" checkbox are now modal. That specific one cannot be fixed quickly before 3.9 release.

Fixes #18733.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AntonPiccardoSelg** [comment]
Opened an MD Workspace and tried all buttons I could find. I tested this on Windows 7 and, strangely, even the window where @samueljackson92  saw a problem seems to be fine.

Please :shipit:

**Comment by samueljackson92** [comment]
@AntonPiccardoSelg That is good to know the changes are valid on windows, but actually this is an OSX bug. Apologies I should have attached someone with mac access as reviewer. II've added @OwenArnold to review also.

**Comment by OwenArnold** [comment]
I should be able to take a look at this later on today.

**Comment by AntonPiccardoSelg** [comment]
@OwenArnold I kicked off a rebuild of the PR on the build servers. I will grab the installer and test it on our mac-mini. That should be sufficient.

**Comment by OwenArnold** [comment]
I haven't looked at the code, but somehow the z ordering has been hard-coded. So it's not possible, for example, to get the MantidPlot window to the front even if you select it. More seriously (possibly unrelated to this) Hitting `Pick Mode` crashes the VSI with the following trace.

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libvtkpqCore-pv5.2.1.dylib    	0x000000011adb2004 pqProxy::getProxy() const + 4
1   libMantidVatesSimpleGuiViewWidgets.dylib	0x000000011a576822 Mantid::Vates::SimpleGui::ViewBase::onParallelProjection(bool) + 50
2   QtCore                        	0x0000000104fbdc05 QMetaObject::activate(QObject*, QMetaObject const*, int, void**) + 2207
3   QtGui                         	0x00000001049c5e24 QAbstractButton::toggled(bool) + 64
4   QtGui                         	0x0000000104772893 QAbstractButton::setChecked(bool) + 269
5   QtCore                        	0x0000000104fbdc05 QMetaObject::activate(QObject*, QMetaObject const*, int, void**) + 2207
6   libMantidVatesSimpleGuiViewWidgets.dylib	0x000000011a57a6b0 Mantid::Vates::SimpleGui::SplatterPlotView::toggleOrthographicProjection(bool) + 64
7   libMantidVatesSimpleGuiViewWidgets.dylib	0x000000011a57176c Mantid::Vates::SimpleGui::SplatterPlotView::onPickModeToggled(bool) + 204
8   QtCore                        	0x0000000104fbdc05 QMetaObject::activate(QObject*, QMetaObject const*, int, void**) + 2207
9   QtGui                         	0x00000001049c5e24 QAbstractButton::toggled(bool) + 64
10  QtGui                         	0x0000000104772893 QAbstractButton::setChecked(bool) + 269
```

**Comment by martyngigg** [comment]
@OwenArnold The crash has been fixed in #18756.

The code changes suggest that dialogs have been made modal and that would mean that they are always on top and force you to interact with them. I don't know if this is the desired behaviour?

**Comment by martyngigg** [comment]
I'm not that happy with these changes system wide as they're not required on the other operating systems. As a short-term fix I suggest we wrap the `setModal(true)` in `#ifdef __APPLE__` and look at a better fix next development cycle.

@OwenArnold @AntonPiccardoSelg Does that seem okay?

**Comment by martyngigg** [comment]
@OwenArnold @AntonPiccardoSelg This probably needs retesting now.

**Comment by AntonPiccardoSelg** [comment]
Tested on Ubuntu. The pop up windows are on top. The VSI itself can be placed behind MantidPlot. Seems all fine to me. 

@OwenArnold @peterfpeterson @AndreiSavici Could someone with a Mac check this on OSX. Thanks

**Comment by rosswhitfield** [comment]
Tested this on OSX. LGTM :shipit:

**Pull request merged**
