### PR TITLE
Ship PyCifRW on Windows

### PR DESCRIPTION
**Pull request by martyngigg**
Updates the sha1 for the third party libraries to include PyCifRW.

**To test:**

The `LoadCIFTest` should run on the system after this merge.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

Includes PyCifRW Python package

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
This works well for me. I built Mantid with MSVC 2015 and now I can use LoadCIF out of the box. It by the way handles syntax/logic errors gracefully and giving informative messages. The unit test also runs correctly. 

:shipit:

Gatekeeper: note this should get included in `release-v3.7` but the base for this PR is master.

**Comment by martyngigg** [comment]
@FedeMPouzols: I also managed to actually base the branch of `master` so we shouldn't just merge it straight to the release branch.  We can cherry-pick the commit after it is merged to `master` though.

**Comment by FedeMPouzols** [comment]
I see: https://github.com/mantidproject/mantid/compare/release-v3.7...bundle-pycifrw-win

**Comment by peterfpeterson** [comment]
I `cherry-pick`ed into `release-v3.7` and `merge`d into `master`.

**Comment by martyngigg** [comment]
Thanks!

**Pull request merged**
