### PR TITLE
Add option to fit and subtract prompt pulse in HRPD data reduction

### LINKED ISSUE #37528: Test prompt pulse fitting/subtraction on other HRPD data
**Is your feature request related to a problem? Please describe.**
Prompt pulse fitting and subtraction has been shown to improve the peak intensities that overlap the prompt pulse  in silicon data relative to the existing masking method.

**Describe the solution you'd like**
Test it out on other data
•	Melamine:
A coherent scatterer with a busy diffraction pattern. Cycle 23/1, run 81019

•	Melamine with sample environment:
As above, but with a large S/E background and in both short and long TOF windows. Cycle 23/1, run 81020 (30-130) and 81023 (100-200).
 
•	Methyl_acetate:
A very strong coherent scatterer. Cycle 23/2, run 81301 (30-130) and 81300 (100-200).

•	NOBF4:
Weak coherent scatterer. Cycle 23/2, run 81102 (30-130).

•	TbPO4:
Weak coherent scatterer. Cycle 23/2, run 81050 (30-130)

•	CuSO4.5H2O:
Low symmetry incoherent scatterer. Cycle 23/4, run 81877.

### PR DESCRIPTION
**Pull request by RichardWaiteSTFC**
### Description of work

Add option to fit and subtract prompt pulse in HRPD data reduction.

~~Must be merged after #37800~~

Fixes #37528 

**Report to:** HRPD scientists

### To test:

(1) Test the new method

```
from isis_powder import hrpd

ws= Load(Filename=r'HRP81780.nxs', OutputWorkspace='HRP81780')

config_file_path = r"C:\Users\xhg73778\Desktop\hrpd\hrpd_config.yaml"
hrpd = hrpd.HRPD(config_file=config_file_path) 

ws_subtr = CloneWorkspace(InputWorkspace=ws, OutputWorkspace=ws.name() + "_subtr")
hrpd._subtract_prompt_pulses(ws_subtr)

# focus data
CreateGroupingWorkspace(InputWorkspace=ws, GroupNames='bank_bsk', OutputWorkspace='grp')
for this_ws in [ws, ws_subtr]:
    ApplyDiffCal(this_ws, CalibrationFile=r"C:\Users\xhg73778\Desktop\hrpd\calibration\Cycle_23_2\HRPD_2023_offsets.cal")
    ws_d = ConvertUnits(InputWorkspace=this_ws, OutputWorkspace=this_ws.name() + '_d', Target='dSpacing')
    ws_d = Rebunch(InputWorkspace=ws_d, OutputWorkspace=ws_d.name(), NBunch=3)
    DiffractionFocussing(InputWorkspace=ws_d, GroupingWorkspace="grp", OutputWorkspace=ws_d.name() + '_foc')
    
```
(2) Plot focussed data - prompt pulses at every ~20ms should be subtracted

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by sf1919** [comment]
@RichardWaiteSTFC  - This is a victim of changes to pre-commit. See https://github.com/mantidproject/mantid/pull/37960#pullrequestreview-2298555084 for details of the changes that went in and see if you need to modify any of your files as a result and push a new commit.

**Review by MohamedAlmaki — COMMENTED** [review]
I've tested the script locally and it is working as expected. I think in general the code looks good but I feel like `_subtract_prompt_pulses` is a little bit long and has some readability issues. I think it is better to refactor it into smaller functions if possible or maybe the logic is really correlated. Happy to approve now and maybe you could open a new issue for refactoring it in the future

**Comment by RichardWaiteSTFC** [comment]
> I've tested the script locally and it is working as expected. I think in general the code looks good but I feel like `_subtract_prompt_pulses` is a little bit long and has some readability issues. I think it is better to refactor it into smaller functions if possible or maybe the logic is really correlated. Happy to approve now and maybe you could open a new issue for refactoring it in the future

Yeh I see that, it could be refactored to reduce the size a bit. I guess this is still a work in progress and I'm trying to make it easy for HRPD to try this new feature atm - it would be good to get it into the release. But if it has to wait that's fine, I'd rather do that than break it with a rushed refactor - that would defeat the point!

**Comment by RichardWaiteSTFC** [comment]
As discussed offline with @sf1919 and @MohamedAlmaki - have raised a maintenance issue #37969 to tidy up

**Comment by MohamedAlmaki** [comment]
Thanks for raising the issue.  Just waiting for the tests and I will approve

**Comment by RichardWaiteSTFC** [comment]
> Thanks for raising the issue. Just waiting for the tests and I will approve

It might be better to approve if you're happy @MohamedAlmaki then gatekeepers can merge if tests pass

**Review by MohamedAlmaki — APPROVED** [review]
Thanks for the changes, happy to approve

**Pull request merged**
