### PR TITLE
Fix apply corrections for diffraction

### LINKED ISSUE #12992: Apply Corrections UI fails for diffraction
The algorithm works but the ConvertUnits algorithm in the UI fails as diffraction data does not have an efixed value.

It should not even be trying to set it as the Emode in this case is Elastic.

### PR DESCRIPTION
**Pull request by DanNixon**
Fixes #12992.

Note that this includes changes from #12993 which must be merged first.

To test:
- Open Indirect > Corrections > Apply Corrections
- Enable use can
- Spectroscopy:
  - Sample: `irs26176_graphite002_red`
  - Container: `irs26173_graphite002_red`
  - Run
- Diffraction:
  - Sample: `irs26176_diffspec_red`
  - Container: `irs26173_diffspec_red`
  - Run

Release notes updates [here](http://www.mantidproject.org/index.php?title=Release_Notes_3_5_Indirect_Inelastic&diff=24352&oldid=24350).

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
@DanNixon : just to make sure, this branch includes a few commits from several other branches. Is that ok? If yes, then I'll check and merge this in a bit later.

**Comment by DanNixon** [comment]
They are all in master already so I think this should be fine.

I've seen this happen before but can't remember the exact cause of it.

**Comment by FedeMPouzols** [comment]
@DanNixon : it works well for me with `irs26176_graphite002_red` and `irs26173_graphite002_red`. Did you mean different files for spectroscopy/diffraction?

**Comment by DanNixon** [comment]
@FedeMPouzols I certainly did.

Updated the instructions.

**Comment by FedeMPouzols** [comment]
It works smoothly with the `diffspec` data as well. All seems good.

**Pull request merged**
