### PR TITLE
Update Notebook docs

### PR DESCRIPTION
**Pull request by DanielMurphy22**
**Description of work.**

Update the docs to allow importing mantid in python on the commandline and running a notebook. Mantidpython and mantidnotebook currently work only on Windows for the upcoming 6.5 release but the intention is to remove them both in the next release. Either way, these instructions should serve linux and OSX users now and all users in the future!

**To test:**

Follow the instructions in the docs page to test that you can import mantid in python and open a notebook. The page has a link to an example notebook, but you may find it easier to rename the notebook file after download to not have spaces!
Mention what OS you tested on.

refs https://github.com/mantidproject/mantid/issues/34388
removal of mantidpython and notebook are in another PR: https://github.com/mantidproject/mantid/pull/34406

*This does not require release notes* because **docs update**
If you add release notes please save them as a separate file using the Issue or PR number as the file name. Check the file is located in the correct directory for your note(s).

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by robertapplin** [comment]
Just writiing this in a comment to document it. I have tried doing:
```
/opt/mantidworkbenchunstable/bin/python -m notebook "/home/mlc47243/Downloads/Introduction to using Mantid with IPython Notebook.ipynb"
```
but I get a 'file not found' problem in the browser for a temporary file. I have checked and this temporary file DOES exist.
image


When I then copy and paste the jupyter link into my browser, it works as expected

**Comment by DanielMurphy22** [comment]
This problem is detailed [here](https://askubuntu.com/questions/1404330/after-updating-to-ubuntu-22-04-i-am-no-longer-able-to-access-jupyter-notebook) and may be resolved by using Chrome.

**Comment by robertapplin** [comment]
> This problem is detailed [here](https://askubuntu.com/questions/1404330/after-updating-to-ubuntu-22-04-i-am-no-longer-able-to-access-jupyter-notebook) and may be resolved by using Chrome.

I can confirm that switching to google chrome causes this to work :+1:

**Review by robertapplin — APPROVED** [review]
Nice work the instructions are working for me now! Also Daniel has made sure they work on windows and macOS. I think a separate issue for the errors when running the code inside the jupyter notebook makes sense

**Pull request merged**
