### PR TITLE
Cost function PDF and acceptance rate included

### PR DESCRIPTION
**Pull request by DiegoMonserrat**
FABADA minimizer: cost function PDF and acceptance rate included

[#11032](http://trac.mantidproject.org/mantid/ticket/11032)

### CODE REVIEW

**Comment by DiegoMonserrat** [comment]
To test:

There are new properties: acceptance rate and Steps between values. Chage them for checking everything it is ok.

Solved the problem with the constraints.

**Comment by eXeC64** [comment]
Jenkins, test this please.

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please.

**Comment by FedeMPouzols** [comment]
In the last build the unit test CurveFittingTest.FABADAMinimizer failed (check the fedora20 configuration, the other ones failed because of the git checkout issue).

**Comment by FedeMPouzols** [comment]
I've added the label "In Progess", as some works seems to be needed to fix a test. This is just to have a clear indication of which pull requests are ready for testing and which ones are not.

**Pull request closed without merging**
