### PR TITLE
Hide warning about seperate thread in matplotlib 3.5.1

### PR DESCRIPTION
**Pull request by Pasarus**
**Description of work.**
Hide a warning that matplotlib throws out, that is not useful in the context of mantid for executing matplotlib creation on separate threads. We handle this on the backend so we are suppressing this warning.

**To test:**
- Using an up to date matplotlib (3.5.1 and up)
- Run `plt.figure()` in a script window and ensure there is no error message.

*There is no associated issue.* Discovered, and fixed during work on #33540 but decided to split out due to it's potentially volatile nature

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by thomashampson** [comment]
For some reason I'm still seeing the warning when running this from the script editor:
```
import matplotlib.pyplot as plt

plt.figure()

```

**Comment by Pasarus** [comment]
This is ready for review again

**Review by thomashampson — APPROVED** [review]
Working now.

**Review by thomashampson — CHANGES_REQUESTED** [review]
I found another instance of the warning when you run the `SavePlot1D` algorithm.

**Review by thomashampson — APPROVED** [review]
My mistake, the warning **is** hidden when running the algorithm.

**Pull request merged**
