### PR TITLE
Fix slice viewer crash for elliptical peaks

### LINKED ISSUE #16508: MantidPlot crashes adding PeaksWorkspace to SliceViewer
### Expected behavior
No crash

### Actual behavior
Nightly crashes when a PeaksWorkspace is dragged into SliceViewer.  This only happens when the peaks are integrated with IntegrateEllipsoids.  This has also happened using the Peak button.

### Steps to reproduce the behavior
Use event file from system tests
```python
Load(Filename='TOPAZ_3132_event.nxs', OutputWorkspace='TOPAZ_3132_event', LoadMonitors=True)
ConvertToMD(InputWorkspace='TOPAZ_3132_event', QDimensions='Q3D', dEAnalysisMode='Elastic', Q3DFrames='Q_sample', LorentzCorrection=True, OutputWorkspace='TOPAZ_3132_md', MinValues='-25,-25,-25', MaxValues='25,25,25', SplitInto='2', SplitThreshold=50, MaxRecursionDepth=13, MinRecursionDepth=7)
FindPeaksMD(InputWorkspace='TOPAZ_3132_md', PeakDistanceThreshold=0.37680000000000002, MaxPeaks=250, DensityThresholdFactor=100, OutputWorkspace='TOPAZ_3132_peaks')
FindUBUsingFFT(PeaksWorkspace='TOPAZ_3132_peaks', MinD=3, MaxD=15, Tolerance=0.12)
CopySample(InputWorkspace='TOPAZ_3132_peaks', OutputWorkspace='TOPAZ_3132_event', CopyName=False, CopyMaterial=False, CopyEnvironment=False, CopyShape=False)
IndexPeaks(PeaksWorkspace='TOPAZ_3132_peaks', Tolerance=0.12)
IntegrateEllipsoids(InputWorkspace='TOPAZ_3132_event', PeaksWorkspace='TOPAZ_3132_peaks', RegionRadius=0.25, SpecifySize=True, PeakSize=0.14000000000000001, BackgroundInnerSize=0.151, BackgroundOuterSize=0.18099999999999999, OutputWorkspace='TOPAZ_3132_peaks')
```
Show SliceViewer with md file and then drag peaks file into SliceViewer

### Platforms affected
Only tried on Rhel7

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
The slice viewer crashed when adding elliptical peak workspaces.

The reason for this was that peaks were marked as visible although they didn't intersect the cut plane. The reason for this is that the `FindPeaks` agorithm is provided with an effictive radius to find visible peaks. In reality this effective radius can be much larger than the actual radii of a peak which was marked visible. In this case the program expected to plot an ellipsoid although there was no interesection. Now we have a check for this in place.

**To test:**

Run the following script (you need to the SystemTest Data in your Mantid path)

``` python
Load(Filename='TOPAZ_3132_event.nxs', OutputWorkspace='TOPAZ_3132_event', LoadMonitors=True)
ConvertToMD(InputWorkspace='TOPAZ_3132_event', QDimensions='Q3D', dEAnalysisMode='Elastic', Q3DFrames='Q_sample', LorentzCorrection=True, OutputWorkspace='TOPAZ_3132_md', MinValues='-25,-25,-25', MaxValues='25,25,25', SplitInto='2', SplitThreshold=50, MaxRecursionDepth=13, MinRecursionDepth=7)
FindPeaksMD(InputWorkspace='TOPAZ_3132_md', PeakDistanceThreshold=0.37680000000000002, MaxPeaks=250, DensityThresholdFactor=100, OutputWorkspace='TOPAZ_3132_peaks')
FindUBUsingFFT(PeaksWorkspace='TOPAZ_3132_peaks', MinD=3, MaxD=15, Tolerance=0.12)
CopySample(InputWorkspace='TOPAZ_3132_peaks', OutputWorkspace='TOPAZ_3132_event', CopyName=False, CopyMaterial=False, CopyEnvironment=False, CopyShape=False)
IndexPeaks(PeaksWorkspace='TOPAZ_3132_peaks', Tolerance=0.12)
IntegrateEllipsoids(InputWorkspace='TOPAZ_3132_event', PeaksWorkspace='TOPAZ_3132_peaks', RegionRadius=0.25, SpecifySize=True, PeakSize=0.14000000000000001, BackgroundInnerSize=0.151, BackgroundOuterSize=0.18099999999999999, OutputWorkspace='TOPAZ_3132_peaks')
# End of script
```
- Open the MD workspace in the slice viewer.
- Drag the peaks workspace into the slice viewer
  - Confirm that there is no crash
- Slect peaks from the peak workspace. 
  - Confirm that there is no crash
-  Zoom out and pan around
  - Confirm that you can see multiple peaks (you might have to play around a bit to see this)

Fixes #16508 
_Does not need to be in the release notes._
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
I've added an "end of script" comment to the script to enable the whole script be selected in Windows internet explorer for cut and paste.

**Comment by KarlPalmen** [comment]
Test shows bug is fixed and I've been able to select peaks at first and the peak is shown with its ellipse I later got several peaks shown with their ellipses. Later after playing around selecting peak did not show a peak with its ellipse. I'm not sure whether this is the result of bad use of slice viewer or a new bug. So I'd like someone who is an expert in use of slice viewer and peaks to verify normal functionality is preserved.

**Comment by AntonPiccardoSelg** [comment]
@KarlPalmen  I don't see this behaviour after playing around with the SliceViewer. When I select a peak from the peaks table, then the peak and the ellipse are displayed.

**Comment by KarlPalmen** [comment]
A second run did not produce the failure to display a selected peak after playing around.

**Comment by VickieLynch** [comment]
No crashes now and unintegrated peaks are marked with X.  :shipit:

**Pull request merged**
