### PR TITLE
Muon Analysis: adapt paths for "load current" to platform

### LINKED ISSUE #10329: Make 'load current' work for linux and mac also
This issue was originally [TRAC 9486](http://trac.mantidproject.org/mantid/ticket/9486)

It was noticed during testing of http://trac.mantidproject.org/mantid/ticket/9417 that 'load current' in fact have hardcoded paths for Windows, which means this functionality currently only works for Windows.

No Muon user have ever complained about this, hence interested they all appear to be windows users!

However, Jay showed me code in std::string CatalogInfo::transformArchivePath(std::string &path) that demonstrate how to make this work for linux and mac also using the path information in facilities.xml

    `<filelocation>`
      `<prefix regex="\\\\isis\\inst\$\\Instruments\$">``</prefix>`
      `<windows replacement="">``</windows>`
      `<linux replacement="/archive">``</linux>`
      `<mac replacement="/archive">``</mac>`
    `</filelocation>`

This ticket is to do something similar here for MuonAnalysis

### PR DESCRIPTION
**Pull request by tom-perkins**
Resolves #10329 

Convert the hard-coded Windows paths to the current data into paths adapted for the current platform.

This is done using the existing method on ICatalogInfo, hence no test has been added since this method is already tested in CatalogInfoTest.

Verified that it still works on Windows, however **testing this PR will require a Linux or Mac system**

(to test: launch MuonAnalysis interface on Linux/Mac and verify that clicking "Load current" correctly loads the current data for the selected instrument)

### CODE REVIEW

**Comment by tom-perkins** [comment]
Noticed while testing this that the current CHRONUS run loads fine, but fails to plot because there is an apostrophe in the title. This is a separate issue to the present one and I've raised #14460 about it.

**Comment by tom-perkins** [comment]
Data from ARGUS (at ISIS) was failing to load with the hardcoded path pointing to `ndw828`. It seems the data is now stored in the same way as the other instruments, so removed the special case for ARGUS and load in the same way as the rest. Tested Load Current with this and it loaded the most recent data set (on Windows).

**Comment by MikeHart85** [comment]
Testing this on Linux (Ubuntu 14.04), it does not appear to work correctly.

When I click the "Load Current" button with the MUSR instrument selected, for example, `MuonAnalysis::runLoadCurrent()` attempts to access two files: `\\MUSR\data\autorun.run` and `\\MUSR\data\MUSRauto_A.tmp`. Both paths are passed through `MuonAnalysisHelper::localisePath()`, but all that changes is that all backslashes are replaced by forward slashes. 

While a path that starts with two backslashes provides access to files on a smb share on Windows, paths starting with two forward (or backward) slashes do not have any particular meaning on Linux. The smb share would have to either first be mounted to a directory using [CIFS](https://wiki.samba.org/index.php/LinuxCIFS_utils) or the files downloaded using some other means. 

The `catalogInfo.transformArchivePath()` call also tries to replace  `\\isis\inst$` with `/archive`, based on the `m_catalogPrefix` and `m_linuxPrefix` members of catalogInfo, but this does nothing since the passed in paths don't contain that string. But if the replacement did succeed, it would be trying to access a local file in the `/archive` directory (which implies the file needs to be downloaded to that directory first). There exists a `CatalogDownloadDataFiles` algorithm which can be invoked via the `CatalogHelper` class to download datafiles. 

Perhaps this would be the way to make it work on Linux/Mac? I don't know the Catalog system well enough to be sure.

**Comment by tom-perkins** [comment]
On further investigation, this does not use the `\\isis\inst$\Instruments$\NDX...` catalog path that is mounted under `/archive` on Linux/Mac. Rather, the data is on an SMB share named after the machine, e.g. `\\MUSR\data`.
This means most of the commits in this pull request are unnecessary (the ones to do with the catalog) and instead what needs to be done is to mount the network share.

Therefore opening a new PR in #14491, and closing this pull request un-merged - otherwise this would lead to a really confusing commit history!

**Pull request closed without merging**
