### PR TITLE
Fix QtSupport warnings for group 4

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
This is group 4 of #16128.

This fixes the Qt3Support warnings for group 4.
## To test:

Review the code.

The changes in this PR have touched many areas of MantidPlot.  Below is a list of items which should be checked. Areas that need thorough testing:
- Marker in Graphs (I think that is the cursor)
- Interface Menu
  - Check that it opens and that the options and sub options are there
- Window Menu
  - Check that it opens and that the options and sub options are there
- File Menu
  - check especially the recent files and projects
- Matrix Menu
  - Check that it opens and that the options and sub options are there
  - You need to create a Matrix and have it in focus to see it
- Analysis Menu
  - Check that it opens and that the options and sub options are there
  - I think you need to set "Enable QtiPlot fitting" in Preferences->Fitting to see this; you also need to have a plot/matrix/ in focus
- Copy and paste in Note; 
- Draw an arrow in plot
  - There is an option in the menu bar which should be enabled for plots

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [ ] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by shahrozahmed1** [comment]
Everything thing seems to be working fine other than just the interface menu .. 

interfacenotdisplayed

**Comment by shahrozahmed1** [comment]
Not sure if it is related to this PR but `Recent Projects` doesn't seem to open sub-menu.. however I have seen this happen before as well.

focusnotworking

**Comment by AntonPiccardoSelg** [comment]
@shahrozahmed1 Ok, will have a look

**Comment by shahrozahmed1** [comment]
I also seem to be getting this warning regularly
```
QObject::connect: Incompatible sender/receiver arguments
        QAction::triggered(bool) --> ApplicationWindow::windowsMenuActivated(int)
```

**Comment by AntonPiccardoSelg** [comment]
@shahrozahmed1 The issue of the missing interface names and the bad sender-slot connection should be fixed.

**Comment by shahrozahmed1** [comment]
This looks good now, the Interface menu now being displayed and `sender-slot` connection warning has been fixed. Once the build pass, :shipit:

**Pull request merged**
