### PR TITLE
New LeanElasticPeaksWorkspace class

### PR DESCRIPTION
**Pull request by rosswhitfield**
**Description of work.**

Follow on to #30812. Add the new Peak Workspace for LeanElasticPeak

**To test:**

```python
from mantid.simpleapi import *
from mantid.dataobjects import PeaksWorkspace, LeanElasticPeaksWorkspace

p=WorkspaceFactory.createPeaks('LeanElasticPeaksWorkspace')

print(isinstance(p, PeaksWorkspace))
print(isinstance(p, LeanElasticPeaksWorkspace))

p.addPeak(p.createPeakQSample(( 1, 0, 0)))
p.addPeak(p.createPeakQSample(( 0, 1, 0)))
p.addPeak(p.createPeakQSample(( 0, 0, 1)))
p.addPeak(p.createPeakQSample((-1, 0, 0)))
p.addPeak(p.createPeakQSample(( 0,-1, 0)))
p.addPeak(p.createPeakQSample(( 0, 0,-1)))

AnalysisDataService.addOrReplace('p',p)

SetUB(p)

p.addPeak(p.createPeakHKL((1,0,0)))
p.addPeak(p.createPeakHKL((0,-100,0)))
p.addPeak(p.createPeakHKL((-1,-1,-1)))

peak = p.createPeakHKL((1,1,1))
peak.setWavelength(1.5)
peak.setIntensity(100)
peak.setSigmaIntensity(10)
peak.setBinCount(50)
peak.setRunNumber(12345)
peak.setAbsorptionWeightedPathLength(1.1)
peak.setPeakNumber(99)
p.addPeak(peak)
```

After which you should be able to view the workspace in the workbench.

---

Updates for later PR's
* Once this is in a usable state all the documentation will be updated to reflect on how to use the new LeanElasticPeak.
* customize the columns for this _table workspace_, _i.e._ remove TOF, etc
* Add ability to save and load from nexus
* Make algorithms be able to use the LeanElasticPeaksWorkspace

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by jmborr** [comment]
can you write a unit test suite for `LeanElasticPeakColumn`?

**Comment by jmborr** [comment]
Looks like most of the code in  `LeanElasticPeakColumn` is a duplicate of `PeakColumn`. I was wondering why you didn't derive these two classes from a `BasePeakColumn` class, as you did with the Peaks objects.

**Comment by jmborr** [comment]
If `BasePeakColumn` is a template class, then I think you could  derive 
```
class LeanElasticPeakColumn : public BasePeakColumn<LeanElasticPeak>
class PeakColumn : public BasePeakColumn<Peak>
```

**Comment by rosswhitfield** [comment]
Because this was to just get something working.  LeanElasticPeakColumn will change as part of SCD197 and only after that will I know how much is in common, I can include refactoring of all the PeakColumn stuff as part of SCD197.

**Comment by jmborr** [comment]
If the relation between `QLab`  and `Qsample` [is the goniometer matrix](https://github.com/mantidproject/mantid/blob/master/Framework/DataObjects/src/Peak.cpp#L448), why not implementing method `LeanElasticPeak::getQLabFrame` using `LeanElasticPeak.m_Qsample` and `BasePeak.m_GoniometerMatrix`?

**Review by jmborr — CHANGES_REQUESTED** [review]
Release notes for the new workspace, and some very minor comments

**Comment by rosswhitfield** [comment]
I think I have addressed most things.

> If the relation between `QLab` and `Qsample` [is the goniometer matrix](https://github.com/mantidproject/mantid/blob/master/Framework/DataObjects/src/Peak.cpp#L448), why not implementing method `LeanElasticPeak::getQLabFrame` using `LeanElasticPeak.m_Qsample` and `BasePeak.m_GoniometerMatrix`?

:confused: That is how [`LeanElasticPeak::getQLabFrame`](https://github.com/mantidproject/mantid/blob/ce16b4453596f441a7e4f04c47d9c71ec3b34fed/Framework/DataObjects/src/LeanElasticPeak.cpp#L199) is implemented unless you are referring to something in the LeanElasticPeaksWorkspace?

> Release notes for the new workspace, and some very minor comments

I am going to wait until LeanElasticPeak and LeanElasticPeaksWorkpace are in a usable state before adding release notes, there is a task for that [SCD241](https://code.ornl.gov/sns-hfir-scse/diffraction/single-crystal/single-crystal-diffraction/-/issues/241). 

The release notes for all this will not just be one line but probably a paragraph explaining all this. If I were to add it to the release notes now it will be a line stating there is a new workspace that you can't use.

**Comment by jmborr** [comment]
>  That is how [`LeanElasticPeak::getQLabFrame`](https://github.com/mantidproject/mantid/blob/ce16b4453596f441a7e4f04c47d9c71ec3b34fed/Framework/DataObjects/src/LeanElasticPeak.cpp#L199) is implemented unless you are referring to something in the LeanElasticPeaksWorkspace?

Ouch! How do I missed that !? :facepalm:

**Review by jmborr — APPROVED** [review]

**Pull request merged**
