### PR TITLE
Disable the failing part of the test (CrystalFieldTest, rhel6)

### LINKED ISSUE #15822: Disable randomly failing tests.
3 CrystalFieldTests randomly fail on rhel6. I cannot reproduce it on a VM so it's very difficult to fix. The code is expected to be run by users mainly on windows.

### PR DESCRIPTION
**Pull request by mantid-roman**
Disabled the tests.

**To test:**

Check that rhel6 doesn't fail.

Fixes #15822.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
Hides for now this strange and hard to reproduce issue. I've seen those asserts failing on some machines but passing on other machines for unclear reasons.

One mergeMD system test failed for unrelated reasons. I've anyway removed the leftover files and restarted the rhel7+system tests build. But I think we don't need to wait for that.

:shipit:

**Comment by martyngigg** [comment]
Can we hold off merging this. I think I have found the reason for the failures but I need to check a bit more.

**Comment by martyngigg** [comment]
The fix for this problem is in #15834 so I think we can close this pull request without merging.

**Comment by FedeMPouzols** [comment]
Great! Let's close this one then?

**Pull request closed without merging**
