### PR TITLE
Results  table fix for muon analysis 1

### LINKED ISSUE #26120: Muon Analysis 1 results table
### Expected behavior
Results table in muon analysis 1 should output table of log values, converting the type into a string as needed

### Actual behavior
When creating table using sample_temp or run_number, mantidplot returns a type mismatch error

### Steps to reproduce the behavior
1. Open mantidplot
1. Open muon analysis
1. Load EMU 20918
1. Go to Data Analysis tab
1. Add a flat background and Abragam to fitting browser
1. Fit
1. In runs load EMU 20918-20
1. Without changing any settings use Fit again
1. Go to results table
1. Check run_number and sample_temp, and check both fitting results
1. Create Table

### Platforms affected
Tested on windows.

### PR DESCRIPTION
**Pull request by AnthonyLim23**
Fixes a bug in muon analysis results table that causes the table to fail if the column values are a mix of ranges and values.

**To test:**

Open mantidplot
Open muon analysis
Load EMU 20918
Go to Data Analysis tab
Add a flat background to fitting browser
Fit
Go to results table
Check run_number and sample_temp, and check both fitting results
Create Table
You should be able to plot sample_temp and the flat background value
Go back to the data analysis tab
In runs load EMU 20918-20
Without changing any settings use Fit again
Go to results table
Check run_number and sample_temp, and check both fitting results
Create Table
Fixes #26120. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Pasarus** [comment]
I don't believe this works, I may be wrong.

When attempting to plot sample_temp with this table:
image

I get an Error:
image

**Review by Pasarus — CHANGES_REQUESTED** [review]
Code looks good but it doesn't seem like it works right now, maybe I did something wrong.

**Comment by AnthonyLim23** [comment]
ah when plotting from a table you need to highlight the columns you want to plot

**Review by Pasarus — APPROVED** [review]
Works well!

**Pull request merged**
