### PR TITLE
fixed OSX failing doc test (muon)

### PR DESCRIPTION
**Pull request by AnthonyLim23**
An OSX doc test was failing so it has been updated. 

**Release Notes** 

Does not need to be in release notes
---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@keeeto @OwenArnold Would either of you have time to verify that this fixes the doc test build?

**Comment by keeeto** [comment]
I can do - @AnthonyLim23 gave me the relevant script, so it should be fine for me to do.

**Comment by AnthonyLim23** [comment]
if you build the docs you can then copy and paste the last doc test from CalMuonDetectorPhases (that way we know it is exactly the same)

**Comment by keeeto** [comment]
This works and produces the same output as the documentation.

**Review by keeeto — APPROVED** [review]
This works on OSX.

**Pull request merged**
