### PR TITLE
Cache Beamline in InstrumentDefinitionParser

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

In the `LoadNexusProcessed` case instrument loading is performed by [ExperimentInfo](https://github.com/mantidproject/mantid/blob/master/Framework/API/src/ExperimentInfo.cpp#L1432) and this was missing the line to cache Beamline objects in the instrument that was added to the IDS. This caused a new Beamline object to be created for each workspace. For WISH, in the case where they loaded a single spectrum from a process file, this adds 200MB to each workspace and hits the memory limit on the 32GB VMs much quicker than it should.

These changes move the caching to the `InstrumentDefinitionParser` so that the client of that code does not have to remember to call this method. 

**To test:**

The following script demonstrates the problem. On `master` the memory usage goes up with each loop but after this fix the memory usage stays roughly constant.

```python
from __future__ import print_function
from mantid.simpleapi import *

MB = 1024*1024

def display_memory_usage():
    import psutil
    proc = psutil.Process()
    usage = proc.memory_info().rss/MB
    print("Mem Usage: {} MiB".format(usage))
    return usage


filename = 'ExternalData/Testing/Data/SystemTest/WishAnalysis.nxs'

for i in range(3):
    Load(filename, LoadHistory=False, OutputWorkspace='out-'+str(i))
    display_memory_usage()

raw_input("Press a key to exit")
```

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by OwenArnold** [comment]
Code changes look good, just waiting on build to confirm memory footprint constant. We discussed tracking memory as part of performance tests. Any thoughts more along these lines, or something for the dev meeting?

**Review by OwenArnold — APPROVED** [review]

**Comment by SimonHeybrock** [comment]
Are we creating a loophole here, rereading the code comment:
> Note that this is only possible since the tree in `instrument` will not be modified once we add it to the IDS.

There are other uses of `parseXML` in the codebase, which will potentially not insert into the IDS directly. Can we end up with a bad state of `DetectorInfo` and `ComponentInfo` in those cases?

Should the code block doing the `parseXML` call and the IDS insertion that is common between `ExperimentInfo` and `LoadInstrument` be moved to a shared function instead, such that `parseXML` is untouched?

**Comment by martyngigg** [comment]
@SimonHeybrock I see your point. I noticed though that the `NexusGeometryParser` does the cache call inside the parser and not outside. Do you happen to know the reason for the descrepancy?

**Comment by OwenArnold** [comment]
I agree with @SimonHeybrock on this. I hadn't originally considered that problem, but I think he's right, this could end up costing time + memory elsewhere in the codebase. Given the proximity to the release, I would suggest the minimal changes anyway.

**Comment by SimonHeybrock** [comment]
@OwenArnold SHould be able to answer the `NexusGeometryParser` bit, since he is the main author, I believe.

**Comment by SimonHeybrock** [comment]
@OwenArnold This is not a concern about costing time + memory, but about correctness.

**Comment by martyngigg** [comment]
I'm going to have to defer to you guys as to whether there is a potential for corruption of `DetectorInfo` & `ComponentInfo`. For the release would it be better to put the `parseTreeAndCacheBeamline` call in `ExperimentInfo` so we know it will only affect that case? On `master` I could then refactor to share the code that uses the XML parser?

**Comment by SimonHeybrock** [comment]
> For the release would it be better to put the parseTreeAndCacheBeamline call in ExperimentInfo so we know it will only affect that case? 

Yes, I think I'd recommend that for now.

**Comment by OwenArnold** [comment]
@martyngigg `NexusGeometryParser`, which returns a `const Instrument` shared_ptr so the mutable method is called before returning the const object. This is not the case with the `InstrumentDefinitionParser::parseXML`

**Comment by martyngigg** [comment]
Thanks both for the feedback. I've updated the changes to just cache the Beamline in `ExperimentInfo` for the release fix.

**Review by OwenArnold — APPROVED** [review]

**Review by SimonHeybrock — APPROVED** [review]

**Comment by martyngigg** [comment]
@mantidproject/gatekeepers I'd appreciate this getting into the nightly tonight if possible.

**Pull request merged**
