### PR TITLE
Fix ILLDetectorEfficiencyCorUser from being skipped on system test package builds

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

In recent [system builds](https://builds.mantidproject.org/view/Master%20Pipeline/job/master_systemtests-rhel7/953/console) it was noticed that the `ILLDetectorEfficiencyCorUser` were being skipped due to an import error. This was due to #26418 and the requirement of `testhelpers` being accessible. When running from a developers build this package is available but when running from the package it is not so this error went undetected.

This work fixes the problem with loading the test modules and also adds code to fail early if all test modules cannot be loaded in an attempt to mitigate this in the future.

**To test:**

Simulate a package build by:
* `rm -fr bin/testhelpers`
* `rm bin/mantid.egg-link`

and try to run `./systemtest -R ILLDetectorEfficiencyCorUser` before merging this fix. The tests will say the ILL ones are skipped due to errors.

Merge this change and the `./systemtest` command should now fail early with better errors.

*This does not require release notes* because **as it is a developer change.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gemmaguest** [comment]
@martyngigg There are conflicts now

**Comment by martyngigg** [comment]
@gemmaguest Thanks. I've rebased and git on the command line was able to sort it out on its own apparently.

**Review by gemmaguest — APPROVED** [review]
Looks good to me. The tests are no longer skipped.

**Comment by martyngigg** [comment]
@mantidproject/gatekeepers This has been approved for a while. Any chance of getting it merged?

**Pull request merged**
