### PR TITLE
Fix instrument view crash

### LINKED ISSUE #25195: Instrument View Crash
### Expected behavior
Not crashing

### Actual behavior
Crashing

### Steps to reproduce the behavior
- Load INTER00013460 (Can be found in UnitTest data)
- Open instrumentview

### Platforms affected
Ubuntu 18.04

```
********* UNHANDLED EXCEPTION *********
  what(): Unable to normalize a zero length vector.

Backtrace:
 /home/sam/Builds/mantid1/bin/libMantidAPI.so(+0x34c931) [0x7fd551ff9931]
 /home/sam/Builds/mantid1/bin/libMantidAPI.so(+0x34ca55) [0x7fd551ff9a55]
 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92a06) [0x7fd5597b2a06]
 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92a41) [0x7fd5597b2a41]
 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92c74) [0x7fd5597b2c74]
 /home/sam/Builds/mantid1/bin/libMantidKernel.so(_ZN6Mantid6Kernel3V3D9normalizeEv+0x72) [0x7fd55af25dea]
 /home/sam/Builds/mantid1/bin/libMantidQtWidgetsInstrumentViewQt5.so(+0x82fef) [0x7fd4cdcc2fef]
 /home/sam/Builds/mantid1/bin/libMantidQtWidgetsInstrumentViewQt5.so(+0x83446) [0x7fd4cdcc3446]
 /home/sam/Builds/mantid1/bin/libMantidQtWidgetsInstrumentViewQt5.so(_ZN8MantidQt13MantidWidgets20BankRenderingHelpers21renderRectangularBankERKN6Mantid8Geometry13ComponentInfoEm+0x30f) [0x7fd4cdcc5401]
 /home/sam/Builds/mantid1/bin/libMantidQtWidgetsInstrumentViewQt5.so(_ZN8MantidQt13MantidWidgets18InstrumentRenderer19drawRectangularBankEmb+0x2cc) [0x7fd4cdd3632e]
 /home/sam/Builds/mantid1/bin/libMantidQtWidgetsInstrumentViewQt5.so(_ZN8MantidQt13MantidWidgets18InstrumentRenderer4drawERKSt6vectorIbSaIbEEbb+0x159) [0x7fd4cdd3593b]
 /home/sam/Builds/mantid1/bin/libMantidQtWidgetsInstrumentViewQt5.so(_ZN8MantidQt13MantidWidgets18InstrumentRenderer16renderInstrumentERKSt6vectorIbSaIbEEbb+0x18a) [0x7fd4cdd35652]
 /home/sam/Builds/mantid1/bin/libMantidQtWidgetsInstrumentViewQt5.so(_ZNK8MantidQt13MantidWidgets15InstrumentActor4drawEb+0x4c) [0x7fd4cdcd66f6]
 /home/sam/Builds/mantid1/bin/libMantidQtWidgetsInstrumentViewQt5.so(+0x112356) [0x7fd4cdd52356]
 /home/sam/Builds/mantid1/bin/libMantidQtWidgetsInstrumentViewQt5.so(_ZNK8MantidQt13MantidWidgets17ProjectionSurface4drawEPNS0_14MantidGLWidgetEb+0xe0) [0x7fd4cdd55dd0]
 /home/sam/Builds/mantid1/bin/libMantidQtWidgetsInstrumentViewQt5.so(_ZNK8MantidQt13MantidWidgets17ProjectionSurface4drawEPNS0_14MantidGLWidgetE+0x6a) [0x7fd4cdd55cb0]
 /home/sam/Builds/mantid1/bin/libMantidQtWidgetsInstrumentViewQt5.so(+0xfea22) [0x7fd4cdd3ea22]
 /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0x1f8) [0x7fd539a0d038]
 /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c) [0x7fd5399ce82c]
 /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x2a4) [0x7fd5399d60f4]
 /usr/lib/python2.7/dist-packages/PyQt5/QtWidgets.x86_64-linux-gnu.so(+0x3a9b4e) [0x7fd53a46ab4e]
 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x118) [0x7fd548a8b9a8]
 /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN14QWidgetPrivate14sendPaintEventERK7QRegion+0x3a) [0x7fd539a0618a]
 /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore+0x56a) [0x7fd539a0674a]
 /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN14QWidgetPrivate11repaint_sysERK7QRegion+0x15b) [0x7fd5399dbf4b]
 /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1afd2e) [0x7fd539a29d2e]
 /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1b064d) [0x7fd539a2a64d]
 /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c) [0x7fd5399ce82c]
 /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x2a4) [0x7fd5399d60f4]
 /usr/lib/python2.7/dist-packages/PyQt5/QtWidgets.x86_64-linux-gnu.so(+0x3a9b4e) [0x7fd53a46ab4e]
 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x118) [0x7fd548a8b9a8]
 /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate18processExposeEventEPN29QWindowSystemInterfacePrivate11ExposeEventE+0xcf) [0x7fd5461aa43f]```

### PR DESCRIPTION
**Pull request by mantid-roman**
**Description of work.**
Catch error and display a warning.

**To test:**
Open instrument view for INTER00013460

Fixes #25195 #25104

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by vreimund — DISMISSED** [review]
This does not work for FIGARO (using `LoadEmptyInstrument`)
Instrument will not show.

```
QGLContext::makeCurrent(): Failed.
X Error: GLXBadContext 169
  Extension:    154 (Uknown extension)
  Minor opcode: 5 (Unknown request)
  Resource id:  0x5e00117
QGLContext::makeCurrent(): Failed.
X Error: GLXBadContext 169
  Extension:    154 (Uknown extension)
  Minor opcode: 5 (Unknown request)
  Resource id:  0x5e00117
QGLContext::makeCurrent(): Failed.
X Error: GLXBadDrawable 171
  Extension:    154 (Uknown extension)
  Minor opcode: 11 (Unknown request)
  Resource id:  0x5e0011e
X Error: GLXBadContext 169
  Extension:    154 (Uknown extension)
  Minor opcode: 5 (Unknown request)
  Resource id:  0x5e00117
QGLContext::makeCurrent(): Failed.
X Error: GLXBadContext 169
  Extension:    154 (Uknown extension)
  Minor opcode: 5 (Unknown request)
  Resource id:  0x5e00117
QGLContext::makeCurrent(): Failed.
X Error: GLXBadContext 169
  Extension:    154 (Uknown extension)
  Minor opcode: 5 (Unknown request)
  Resource id:  0x5e00117
QGLContext::makeCurrent(): Failed.
X Error: GLXBadDrawable 171
  Extension:    154 (Uknown extension)
  Minor opcode: 11 (Unknown request)
  Resource id:  0x5e0011e

```

**Comment by reimundILL** [comment]
Does not work for INTER and D17 as well, same problem.

Workbench: crashes for INTER (`LoadEmptyInstrument`)

**Comment by reimundILL** [comment]
I am on Ubuntu 16.04. On Monday, I could not build Mantid anymore since dependencies were missing (Poco, NeXus, ... presumably many). I installed `mantid-developer_1.4.0_all`.
I tested https://github.com/mantidproject/mantid/pull/25109 successfully before Monday. But now, this solution does not work for me neither.
OpenGL is enabled. Maybe this fix is valid but something more general is broken (some dependency missing?).
Any ideas?

**Comment by mantid-roman** [comment]
Sorry I cannot help with that. Post a question on slack.

**Comment by gvardany** [comment]
This fixes the problem for D17 and Figaro. Also INTER shows up fine, but with the warnings logged:
```
BankRenderingHelpers-[Warning] Cannot display rectangular detector bank linear-detector
BankRenderingHelpers-[Warning] Detector step in x direction is zero.
```
Is this expected?

**Comment by mantid-roman** [comment]
@gvardany I assumed that it's because of how the instrument is defined and I would expect this warning to show. But I'll double-check and have a look at the IDF to see if it has any obvious errors.

**Comment by martyngigg** [comment]
Should #25104 be added to the fixes list for this PR?

**Comment by mantid-roman** [comment]
There is a confusion in the definitions of rectangular detectors (pixels). Some instruments have the Z axis as vertical (top-bottom) others the Y. The documentation says it's the Y, the code seems to assume it's the X. INTER definition agrees with the documentation but drawing fails. It looks as if D17 and FIGARO have errors in their definitions: the x's should have 3 equal values and one different but they have two pairs of equal numbers. And because of that the detectors show in the instrument view.

**Comment by martyngigg** [comment]
So can we accept this as the fix and then fix the IDFs separately?

**Comment by martyngigg** [comment]
@gvardany Are you okay with accepting this? If so could you mark it approved?

**Review by martyngigg — APPROVED** [review]
Approved. Broken IDFs will be fixed in another issue and will get pushed out to master anyway.

**Comment by gvardany** [comment]
Yes, apparently the definition of the cuboid pixel in our IDFs is [wrong](https://github.com/mantidproject/mantid/blob/master/instrument/D17_Definition.xml#L103) .
The `left-front-bottom-point` and `left-front-top-point` should have only `y` different.

**Review by gvardany — APPROVED** [review]

**Pull request merged**
