### PR TITLE
ChecksumHelper: Only convert CRLF to LF and not plain CR

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Git only converts CRLF to LF and not CR so to produce
the same SHA as git we must do the same.

**To test:**

Code review. Check new tests are sensible.

*There is no associated issue.*

*This does not require release notes* because **it is an internal change.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DavidFair — COMMENTED** [review]
I'm a bit confused since 

mac version:
    const std::string data = "ChecksumHelperTest_"
                             "testGitSha1FromFileWithLinuxLineEndings\rTest "
                             "this string out for size\r in a file";

linux version:
    const std::string data = "ChecksumHelperTest_"
                             "testGitSha1FromFileWithLinuxLineEndings\nTest "
                             "this string out for size\n in a file";

But the sha sum for both are different, doesn't this defeat the point of this PR?
7e78655a4e48aa2fbd4a3f1aec4043009e342e31
7b7e77332c1610df14fd26476d1601a22a34f11f

**Comment by martyngigg** [comment]
@DavidFair That's actually how it should be. The current code changes either `\r\n` or single `\r`, using the PERL `\R` syntax, to `\n` but `git` itself only changes `\r\n` and not bare `\r` so if I just have `\r` then there should be no transformation of line endings and I would expect a different SHA1 for the content than the Linux version.

It can be checked if we use `git hash-object` on the files. I commented out the file deletion and then:
```sh
$ cat bin/Testing/ChecksumHelperTest_testGitSha1FromFileWithLinuxLineEndings.txt | git hash-object --stdin  
7e78655a4e48aa2fbd4a3f1aec4043009e342e31
$ cat bin/Testing/ChecksumHelperTest_testGitSha1FromFileWithOldStyleMacLineEndings.txt | git hash-object --stdin 
7b7e77332c1610df14fd26476d1601a22a34f11f
```

which is what we want I think as we need to match what git does.

**Comment by DavidFair** [comment]
Ahh I see, so funnily enough I would have written the same bug in since I assumed CR->LF in git and it just handled a single line ending

**Review by DavidFair — APPROVED** [review]
I'm happy with these tests and they pass locally too, lets :shipit:

**Comment by martyngigg** [comment]
Yes it's taken us many years to notice it!

**Pull request merged**
