### PR TITLE
Serialise the spectrum viewer

### LINKED ISSUE #16963: Serialise the spectrum viewer
This is a sub issue of #15602.

The spectrum viewer is not currently serialised to the mantid project file.

### PR DESCRIPTION
**Pull request by samueljackson92**
**This should not be merged before the PR for #16961**

This PR allows the spectrum viewer to serialise it's state to a Mantid project file

**To test:**
Saving to a Mantid project with a spectrum viewer window open should now save the state of the spectrum viewer to file as well. Best way to test is to play around and ensure all the options are correctly saved and reapplied. Some specific things to test:
- Multiple workspaces open on the interface
- Min/max range
- Slider values
- Colormaps (both from file and preexisting)
- EMode/Fixed
- Selected points on the spectrogram and vertical/horizontal 1D plots.

See if you can spot anything I've missed.

Fixes #16963.

For release notes see issue #17109.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DavidFair** [comment]
Review pending #17317 being ready to merge

**Comment by samueljackson92** [comment]
@DavidFair This can still be tested, just not merged, while the other issue is pending as this is a complete separate interface from the slice viewer. It is only the movement of some common code which makes this dependant on the other issue.

**Comment by DavidFair** [comment]
Using `ENGINX00251424.nxs` which can be found at `\\olympic\babylon5\Public\David Fairbrother\spectrumViewer` I had the following tests fail:

- The display is corrupted on load - (If you resize the window the repaint event causes it to resolve itself)
- If the user closes with two instrument displays open only one loads back in
- X min and X max and stepping are not preserved on load
- Cursor tracking doesn't preserve tick status
- Colour map selection isn't preserved - Built in and Loaded
- Vertical and/or Horizontal scroll bars aren't saved

**Comment by DavidFair** [comment]
Everything looks good - I'll give it a final look over once #17317 is merged but I am happy to ship this

**Comment by DavidFair** [comment]
Once the final few system tests complete :shipit:

**Pull request merged**
