### PR TITLE
Muon analysis sequential fit: set file finder to correct instrument

### LINKED ISSUE #15223: Muon Analysis: sequential fit uses wrong 'default' instrument
Reported during beta test period for release 3.6

The sequential fit dialog in the Muon Analysis interface uses the default instrument set in Mantid rather than the one selected in the dropdown box on the front tab of the interface. 

For example, if system default instrument is HiFi but you open the interface and set the dropdown box to MuSR, then type "17295-17300" into the sequential fit dialog, it loads these runs from HiFi rather than MuSR.

Change the instrument the sequential fit dialog looks at to match the one selected in the dropdown list on the front of the interface.

I've verified this was the case in 3.5.1, so this is a bug that's always been there rather than something that's been broken in this release.

### PR DESCRIPTION
**Pull request by tom-perkins**
resolves #15223

This is the sibling of #15224 for merging into the release branch

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
Not sure why pylint fails...

**Comment by tom-perkins** [comment]
One of the pylint errors in `ExportSampleLogsToCSVFile.py` was fixed in `master`, but not in the release branch (the FIXME [on this line](https://github.com/mantidproject/mantid/blob/release-v3.6.0/Framework/PythonInterface/plugins/algorithms/ExportSampleLogsToCSVFile.py#L331) was removed, see #15092 ). 

I think that now pylint has got used to the error count going down it doesn't like the same error reappearing - there must be one pylint threshold for all builds, whether on `master` or the release branch?

**Comment by raquelalvarezbanos** [comment]
Oh I see... I assume there is nothing we can do about it... @martyngigg just to make sure, can I merge this PR into the release branch?

**Comment by martyngigg** [comment]
@raquelalvarezbanos: @tom-perkins is correct, it's the slightly odd way we have to interpret the `pylint` errors at the moment given they are not at 0 in master.

As the changes only affected C++ code then it's safe to ignore and merge.

**Comment by raquelalvarezbanos** [comment]
Thanks @martyngigg 

Re-tested just in case, works as expected.

**Pull request merged**
