### PR TITLE
Reduce memory consumption in Histogram performance test by another 2x

### PR DESCRIPTION
**Pull request by SimonHeybrock**
See https://github.com/mantidproject/mantid/pull/17514. The performance test build server has 3.6 GB RAM. Previously we got very close to this and the test ran extremely slow. Reducing this by 2x should bring the memory consumption below 2 GB.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by LamarMoore** [comment]
:shipit:

**Comment by FedeMPouzols** [comment]
Looks good again. Let's see how fast/slow is the `performancetests` machine with ~2GB memory consumption. After this we could add a note on memory consumption on the [wiki page](http://www.mantidproject.org/Writing_Performance_Tests) (although there will be the usual issues with outdated figures over time).

**Comment by SimonHeybrock** [comment]
@FedeMPouzols I am also getting into contact with or hardware group, to see if we can get a better build server. Not sure though, since they use VMs for everything, and that might not work so well for performance tests...

**Comment by SimonHeybrock** [comment]
@FedeMPouzols Went down from 108 seconds to 2.3 seconds :)

**Pull request merged**
