### PR TITLE
Fix bug in ass calculation in PaalmanPingsMonteCarloAbsorption

### LINKED ISSUE #30888: ass calculation doesn't look right in PaalmanPingsMonteCarloAbsorption for preset shape
I was having a look through the code in PaalmanPingsMonteCarloAbsorption a few days ago while fixing the seg fault in #30779  and I noticed the code for the ass calculation doesn't look correct. The calculation should return a result for scattering in the sample only and absorption in the sample only so it needs to be run without the container shape being present. It looks like it's being run with whatever shapes were in the input workspace ie if a container was present it will still be present in the ass calculation

I haven't actually debugged this or run it so raising the issue on code review only

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

The container shape was previously still present in the ass calculation when run using shapes already present on the input workspace. This would have affected the attenuation even if no scatter points were generated in the container.

Fix this by taking a copy of the sample and container shape at the start of the algorithm and then swap them in as required

Doing this required some methods on the API::Sample class to be exposed to Python. This included one (setEnvironment) that previously took a unique_ptr as a parameter. I don't think you can expose a method that has a unique_ptr parameter using boost python so I've changed this to be a shared_ptr. Any performance hit from using shared_ptr rather than unique_ptr will be small and this is better than copying the environment object which is what would otherwise be required

**To test:**

Run this script:

```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

testws = CreateWorkspace([1.0,2.0,3.0],[4.0,4.0,4.0],UnitX="Wavelength")
EditInstrumentGeometry(Workspace=testws, PrimaryFlightPath=10.0, L2=1.0, Polar=1.0)
SetSample(testws,
        Geometry={'Shape': 'FlatPlate', 'Height': 4.0,
                  'Width': 2.0, 'Thick': 1.0,
                  'Center': [0.,0.,0.]},
        Material={'ChemicalFormula': 'Al',
                  'NumberDensity': 0.05},
        ContainerGeometry={'Shape': 'FlatPlateHolder', 'Height': 4.0,
                  'Width': 2.0, 'Thick': 1.0, 'FrontThick': 0.3, 'BackThick': 0.4,
                  'Center': [0.,0.,0.]},
        ContainerMaterial={'ChemicalFormula': 'Al',
                  'NumberDensity': 0.01})
SetBeam(InputWorkspace=testws,Geometry={'Shape': 'Slit', 'Width': 3.0, 'Height': 6.75})
abs = PaalmanPingsMonteCarloAbsorption(InputWorkspace=testws,EventsPerPoint=100)
```

...and observe that all four results in the "abs" workspace group are different. Previously the "ass" and "assc" results were the same

Fixes #30888.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by gvardany — COMMENTED** [review]
The code looks fine. Could you change the script in the description to not use Polaris, so I can run? Now that the preset shape is finally fixed, could you add a unit test for that?

**Comment by DannyHindson** [comment]
> The code looks fine. Could you change the script in the description to not use Polaris, so I can run? Now that the preset shape is finally fixed, could you add a unit test for that?

Strange these abs corr scripts where I used Polaris hang for you. For me it takes ~30 secs for the Polaris instrument definition to load so not massively quick but doesn't hang. Anyway I've just updated the script to remove the Polaris part. Re the unit tests - there are already two unit tests in the PaalmanPingsMonteCarloAbsorptionTest suite which cover the preset shape option. There's no system test though so I assume that's what you mean?

**Comment by gvardany** [comment]
> > The code looks fine. Could you change the script in the description to not use Polaris, so I can run? Now that the preset shape is finally fixed, could you add a unit test for that?
> 
> Strange these abs corr scripts where I used Polaris hang for you. For me it takes ~30 secs for the Polaris instrument definition to load so not massively quick but doesn't hang. Anyway I've just updated the script to remove the Polaris part. Re the unit tests - there are already two unit tests in the PaalmanPingsMonteCarloAbsorptionTest suite which cover the preset shape option. There's no system test though so I assume that's what you mean?

Exactly, you are correcting a bug, but no test fails, it means it wasn't covered. The unit tests do not check the output, just their shape and form. I think after this we can consider the algorithm stable, so we should add proper system tests, and not only for the preset shape. However, this can be done as a maintenance task after the release.

**Comment by gvardany** [comment]
Ignore my previous comment, I didn't realise we already have system tests, thanks for adding a new one for the preset case.

**Comment by gvardany** [comment]
Running the script you provided, the `assc` is now lower than `ass`, which is correct. However, `ascs`=`accs`. Is this an accident? Can you double check those two?

**Comment by DannyHindson** [comment]
> Running the script you provided, the `assc` is now lower than `ass`, which is correct. However, `assc`=`acsc`. Is this an accident? Can you double check those two?

I've had a look at this. For me assc and acsc are close but they're not exactly the same. I ran the following script which is the same calculation but using the "in built" shape definition inside PPMCAbs:
```
abs2 = PaalmanPingsMonteCarloAbsorption(InputWorkspace=testws,Shape='FlatPlate',
         EventsPerPoint=100, Height=4.0,
         SampleThickness=1.0,SampleWidth=2.0,SampleCenter=0.,
         SampleChemicalFormula='Al',
         SampleDensityType="Number Density",
         SampleDensity=0.05,
         ContainerFrontThickness=0.3, ContainerBackThickness=0.4,
         ContainerChemicalFormula='Al',
         ContainerDensityType="Number Density",
         ContainerDensity=0.01)
```
...and the results for all four components match the outputs from the test script for this PR ie assc and acsc are v close. I also ran the calculation above on an older Mantid nightly build and it also gave v similar results. 

I think the results are quite close because the Polar angle of 1.0 that I set up for the single detector\spectrum in the EditInstrumentGeometry line is actually in units of degrees. If I change this to 45.0 then assc and acsc are more different.

So I think it's all OK?

**Comment by gvardany** [comment]
> > Running the script you provided, the `assc` is now lower than `ass`, which is correct. However, `assc`=`acsc`. Is this an accident? Can you double check those two?
> 
> I've had a look at this. For me assc and acsc are close but they're not exactly the same. I ran the following script which is the same calculation but using the "in built" shape definition inside PPMCAbs:
> 
> ```
> abs2 = PaalmanPingsMonteCarloAbsorption(InputWorkspace=testws,Shape='FlatPlate',
>          EventsPerPoint=100, Height=4.0,
>          SampleThickness=1.0,SampleWidth=2.0,SampleCenter=0.,
>          SampleChemicalFormula='Al',
>          SampleDensityType="Number Density",
>          SampleDensity=0.05,
>          ContainerFrontThickness=0.3, ContainerBackThickness=0.4,
>          ContainerChemicalFormula='Al',
>          ContainerDensityType="Number Density",
>          ContainerDensity=0.01)
> ```
> 
> ...and the results for all four components match the outputs from the test script for this PR ie assc and acsc are v close. I also ran the calculation above on an older Mantid nightly build and it also gave v similar results.
> 
> I think the results are quite close because the Polar angle of 1.0 that I set up for the single detector\spectrum in the EditInstrumentGeometry line is actually in units of degrees. If I change this to 45.0 then assc and acsc are more different.
> 
> So I think it's all OK?

In that case yes. I think this could be also because the container doesn't scatter much.

**Review by gvardany — APPROVED** [review]

**Pull request merged**
