### PR TITLE
Add Coverage Timeout Options to buildscript

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**
- Breaks up some of the build script into modular form
- Adds coverage timeout
- Move static analysis too, just to display how modules work

Currently our coverage jobs are failing as the 300 second timeout is too low in debug mode. As they are run nightly we can bump the time to 1200 seconds (20 minutes per test) and see if the build servers have enough time.

In the long-term I hope to move more out of our big buildscript and into individual modules we use for maintainability.

**To test:**
- cd to Mantid directory
- `export WORKSPACE=$(pwd)`
- `export JOB_NAME=coverage_debu`
- Run `buildconfig/Jenkins/buildscript`
- This will fail trying to build (number of threads is not specified), check that in `*source_dir*/build` that coverage is on
- `export JOB_NAME=address`
- Re-run `buildconfig/Jenkins/buildscript`
- Again this will fail, check that coverage is off, but USE_SANITIZER is set to address with the build mode on RelWithDebInfo

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@Pasarus It's worth you being aware of this.

**Comment by Pasarus** [comment]
I am, I appreciate the note, David and I spoke and I implemented something similar as a CMake Preset for the re-designed buildscript I am writing.

**Review by martyngigg — COMMENTED** [review]
Can I just check. The error I see running the first few steps to check coverage is:
```
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so
CMake Error at buildconfig/CMake/Coverage.cmake:69 (message):
  coverage: Code coverage results with an optimised (non-Debug) build may be
  misleading!
Call Stack (most recent call first):
  CMakeLists.txt:107 (coverage_turn_on)


-- Configuring incomplete, errors occurred!
See also "/home/mgigg/Code/mantidproject/mantid-nightly/build/CMakeFiles/CMakeOutput.log".
See also "/home/mgigg/Code/mantidproject/mantid-nightly/build/CMakeFiles/CMakeError.log".
buildconfig/Jenkins/buildscript: line 380: BUILD_THREADS: parameter null or not set
```

Is the part about the optimised build expected?

**Review by martyngigg — COMMENTED** [review]
For the `address` build, cmake completes I see that coverage is indeed off as expected. I needed to call it as `CC=gcc-8 CXX=g++-8 buildconfig/Jenkins/buildscript` to use gcc 8 on Ubuntu

**Comment by DavidFair** [comment]
> For the `address` build, cmake completes I see that coverage is indeed off as expected. I needed to call it as `CC=gcc-8 CXX=g++-8 buildconfig/Jenkins/buildscript` to use gcc 8 on Ubuntu

This uses the native gcov, so if they system default is GCC-8 it will try to use that associated gcov version

Also I'm happy to defer / close this PR instead of Sam's implementation

**Comment by martyngigg** [comment]
@DavidFair To save confusion I'll close this then if that's okay?

**Pull request closed without merging**
