### PR TITLE
Algorithms return namedtuple

### LINKED ISSUE #18791: In python algorithms should return `namedtuple` instead of `tuple`
Many algorithms have more than one output property. When one uses them in python, it's not explicit what those properties are. For example `print GetEi(w)` might yield something like `(3.0, 0.0, 0, 61.77080180287334)`. If I assign this value to a variable, say `result`, I would need to know later that `Ei=result[0]`, and `t0=result[3]`, and I would need to look into the documentation of `GetEi` to check what are the other two parameters.
If we used `namedtuple` objects, `result` would be something like `GetEi_returns(IncidentEnergy=3.0, FirstMonitorPeak=0.0, FirstMonitorIndex=0, Tzero=61.77080180287334)`. One can access `Ei` as `result[0]`, compatible with the current scripts, or as `result.IncidentEnergy`

### PR DESCRIPTION
**Pull request by AndreiSavici**
Algorithms now return named tuples instead of tuples.

**To test:**
1. All unit tests and system tests should pass. The only difference is that if you have more than one output property, and you store those in a `result`, the type of `result` is not a tuple. But `isinstance(result,tuple)` returns `True`
2. Run something like this
```
w=Load('CNCS_7860')
dgs1=DgsReduction(SampleInputWorkspace=w,SampleInputMonitorWorkspace=w)
dgs2,params=DgsReduction(SampleInputWorkspace=w,SampleInputMonitorWorkspace=w)
result=GetEi(w)
print(result)
print(result[0])
print(result.IncidentEnergy)
```

This would yield
```
GetEi_returns(IncidentEnergy=3.0, FirstMonitorPeak=0.0, FirstMonitorIndex=0, Tzero=61.77080180287334)
3.0
3.0
```
In addition, you should have 3 workspaces, named `w`,`dgs1`, and `dgs2`

Fixes #18791.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by peterfpeterson — APPROVED** [review]

**Comment by peterfpeterson** [comment]
I'm adding @rosswhitfield and @martyngigg to look this over just to make sure that it is a reasonable change.

**Comment by rosswhitfield** [comment]
While this works with python 3 and all the unit tests pass I'm seeing a lot of new deprecation warnings from this
```
/home/rwp/mantid/Release/py3/bin/mantid/simpleapi.py:571: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  argspec = inspect.getargspec(func)
Traceback (most recent call last):
  File "<string>", line 61, in _ScopeInspector_GetFunctionAttributes
  File "/home/rwp/mantid/Release/py3/bin/mantid/simpleapi.py", line 571, in _get_function_spec
    argspec = inspect.getargspec(func)
  File "/usr/lib/python3.6/inspect.py", line 1045, in getargspec
    raise ValueError("Function has keyword-only parameters or annotations"
ValueError: Function has keyword-only parameters or annotations, use getfullargspec() API which can support them
Traceback (most recent call last):
  File "<string>", line 61, in _ScopeInspector_GetFunctionAttributes
  File "/home/rwp/mantid/Release/py3/bin/mantid/simpleapi.py", line 571, in _get_function_spec
    argspec = inspect.getargspec(func)
  File "/usr/lib/python3.6/inspect.py", line 1045, in getargspec
    raise ValueError("Function has keyword-only parameters or annotations"
ValueError: Function has keyword-only parameters or annotations, use getfullargspec() API which can support them
Traceback (most recent call last):
  File "<string>", line 61, in _ScopeInspector_GetFunctionAttributes
  File "/home/rwp/mantid/Release/py3/bin/mantid/simpleapi.py", line 571, in _get_function_spec
    argspec = inspect.getargspec(func)
  File "/usr/lib/python3.6/inspect.py", line 1045, in getargspec
    raise ValueError("Function has keyword-only parameters or annotations"
ValueError: Function has keyword-only parameters or annotations, use getfullargspec() API which can support them
```

**Comment by AndreiSavici** [comment]
I'll test if `getfullagspec` works instead of `getargspec` for python2 and python3

**Review by rosswhitfield — APPROVED** [review]
:+1: Works for me now.

**Comment by peterfpeterson** [comment]
:shipit:

**Review by martyngigg — APPROVED** [review]
The changes look good to me. It's great this can remain backwards compatible.

**Comment by peterfpeterson** [comment]
:shipit:

**Pull request merged**
