### PR TITLE
LoadVesuvio read 2 and 3 period data

### LINKED ISSUE #14735: Amendments to LoadVesuvio
The LoadVesuvio algorithm should be amended to work with 2 and 3 foil-in foil-out cycles in addition to the usual operation using 6 cycles.

### PR DESCRIPTION
**Pull request by ElliotAOram**
Fixes #14735
- 2 and 3 period data should now be successfully read and processed by LoadVesuvio
- The normalisation window has been change for back scattering to `600-700` from `410-430`
- Tests have been updated for the normalisation change but no new test cases can be added due to not having appropriate data at this time #14924 
# To Test
- Ensure the tests pass and the updates cover the changes made here
- Test LoadVesuvio with 2 and 3 period data to ensure correctness
  - 3 period = `20598`
  - 2 period = `21298-21302`

### CODE REVIEW

**Comment by martyngigg** [comment]
Code review done and I'm happy with the changes.

**Comment by martyngigg** [comment]
I used the following script to test out various scenarios:
```python
BACKWARD = '3-134'
FORWARD = '135-198'

##### 3 period ######
run = 20598

# single diff
three_back_single_no_sum = LoadVesuvio(Filename=str(run), SpectrumList=BACKWARD, Mode='SingleDifference', SumSpectra=False)
three_back_single_summed = LoadVesuvio(Filename=str(run), SpectrumList=BACKWARD, Mode='SingleDifference', SumSpectra=True)
# fails - 'SpectraToFoilPeriodMap' object has no attribute '_odd_even'
#three_fwd_single_no_sum = LoadVesuvio(Filename=str(run), SpectrumList=FORWARD, Mode='SingleDifference', SumSpectra=False)
# fails - 'SpectraToFoilPeriodMap' object has no attribute '_odd_even'
#three_fwd_single_summed = LoadVesuvio(Filename=str(run), SpectrumList=FORWARD, Mode='SingleDifference', SumSpectra=True)

# double diff
three_back_double_no_sum = LoadVesuvio(Filename=str(run), SpectrumList=BACKWARD, Mode='DoubleDifference', SumSpectra=False)
three_back_double_summed = LoadVesuvio(Filename=str(run), SpectrumList=BACKWARD, Mode='DoubleDifference', SumSpectra=True)
# fails as expected
#three_fwd_double_no_sum = LoadVesuvio(Filename=str(run), SpectrumList=FORWARD, Mode='DoubleDifference', SumSpectra=False)
# fails as expected
#three_fwd_double_summed = LoadVesuvio(Filename=str(run), SpectrumList=FORWARD, Mode='DoubleDifference', SumSpectra=True)

# thick diff
three_back_thick_no_sum = LoadVesuvio(Filename=str(run), SpectrumList=BACKWARD, Mode='ThickDifference', SumSpectra=False)
three_back_thick_summed = LoadVesuvio(Filename=str(run), SpectrumList=BACKWARD, Mode='ThickDifference', SumSpectra=True)
# fails - 'SpectraToFoilPeriodMap' object has no attribute '_odd_even'
#three_fwd_thick_no_sum = LoadVesuvio(Filename=str(run), SpectrumList=FORWARD, Mode='ThickDifference', SumSpectra=False)
# fails - 'SpectraToFoilPeriodMap' object has no attribute '_odd_even'
#three_fwd_thick_summed = LoadVesuvio(Filename=str(run), SpectrumList=FORWARD, Mode='ThickDifference', SumSpectra=True)

##### 2 period ######
run = '21298-21302'

# single diff
two_back_single_no_sum = LoadVesuvio(Filename=str(run), SpectrumList=BACKWARD, Mode='SingleDifference', SumSpectra=False)
two_back_single_summed = LoadVesuvio(Filename=str(run), SpectrumList=BACKWARD, Mode='SingleDifference', SumSpectra=True)
two_fwd_single_no_sum = LoadVesuvio(Filename=str(run), SpectrumList=FORWARD, Mode='SingleDifference', SumSpectra=False)
two_fwd_single_summed = LoadVesuvio(Filename=str(run), SpectrumList=FORWARD, Mode='SingleDifference', SumSpectra=True)

# double diff - 
# needs a better error message
two_back_double_no_sum = LoadVesuvio(Filename=str(run), SpectrumList=BACKWARD, Mode='DoubleDifference', SumSpectra=False)
# needs a better error message
two_back_double_summed = LoadVesuvio(Filename=str(run), SpectrumList=BACKWARD, Mode='DoubleDifference', SumSpectra=True)
# fails as expected
two_fwd_double_no_sum = LoadVesuvio(Filename=str(run), SpectrumList=FORWARD, Mode='DoubleDifference', SumSpectra=False)
# fails as expected
two_fwd_double_summed = LoadVesuvio(Filename=str(run), SpectrumList=FORWARD, Mode='DoubleDifference', SumSpectra=True)

# thick diff
# needs a better error message
two_back_thick_no_sum = LoadVesuvio(Filename=str(run), SpectrumList=BACKWARD, Mode='ThickDifference', SumSpectra=False)
# needs a better error message
two_back_thick_summed = LoadVesuvio(Filename=str(run), SpectrumList=BACKWARD, Mode='ThickDifference', SumSpectra=True)
# needs a better error message
two_fwd_thick_no_sum = LoadVesuvio(Filename=str(run), SpectrumList=FORWARD, Mode='ThickDifference', SumSpectra=False)
# needs a better error message
two_fwd_thick_summed = LoadVesuvio(Filename=str(run), SpectrumList=FORWARD, Mode='ThickDifference', SumSpectra=True)

##### Misc ########
# mix forward backward fails as expected
# LoadVesuvio(Filename=str(run), SpectrumList='134,135', Mode='DoubleDifference', SumSpectra=False)
```

@ElliotAOram This seems like it is mostly there. I think we just need some better error checking to improve the messages that the user would see in the cases where we know that things are not possible. I'm not sure what is wrong with the "3 period, forward spectra case", should this not be allowed?

**Comment by ElliotAOram** [comment]
@martyngigg I've made those changes and added validation for all the non possible cases. Giovanni has very kindly filled in this validation table (and provided a bit of extra information along side it) which has made everything much clearer.
image

**Comment by martyngigg** [comment]
@ElliotAOram That's great - a very nice thing to have. I feel like we should keep this information somewhere. How about translating this information to the `LoadVesuvio` documentation page?

**Comment by ElliotAOram** [comment]
@martyngigg good idea. I'll add this to the documentation and fix the pylint error!

**Comment by martyngigg** [comment]
The code changes look sensible and the test script now gives better error messages for the failure cases.

I like the documentation updates - it's a good reminder of the set up.

**Pull request merged**
