### PR TITLE
Integrate a FitPropertyBrowser and a DisplayCurveFit in the BackgroundRemover interface

### LINKED ISSUE #15429: Integrate a FitPropertyBrowser and a DisplayCurveFit in the BackgroundRemover interface
Implement a minimum functionality in the BackgroundRemover subinterface of the DynamicPDF interface: a FitPropertyBrowser and a DisplayCurveFit widgets, with signal/slot connections:

junk

In this "first round" we will leave the default menus (Fit, Display, and Setup) as well as default options for these menus. Also default properties (number-of-iterations, minimizer,...). These defaults are defined in the FitPropertyBrowser widget.

### PR DESCRIPTION
**Pull request by jmborr**
A minimum functionality for the background remover interface of the DynamicPDF project is now in place.

**To test:**,

Open the interface (Interfaces-->DynamicPDF-->Dynamic PDF Background Remover), then Load the attached S(Q,E), ([data.zip](https://github.com/mantidproject/mantid/files/222860/data.zip) ) then try do fits for some energy cuts. The idea is to find instances where the interface will segfault, or popup error messages, and also to get feedback on usability for future Github issues.

(Note: the interface as is now will be evaluated by a friendly external user to get feedback. Thus it needs to be available in the nightly version of mantid)

Fixes #15429

**RELEASE NOTES**
_Does not need to be in the release notes._  Prior to release, the interface will be improved by implementing the feedback from this tester and the friendly user. Afterwards, release notes will be inserted.

interface_snapshot

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
@jmborr : this PR has a couple of doxygen warnings. The windows build failed because the class `DPDFFitOptionsBrowser` is not dll-exported correctly. I think it needs `MANTIDQT_CUSTOMINTERFACES_DLL`. I see you used `EXPORT_OPT_MANTIDQT_MANTIDWIDGETS` but I wonder where did that macro come from? I cannot find it anywhere in the sources.

**Comment by jmborr** [comment]
@FedeMPouzols Thanks for pointing out the DLL error

**Comment by jmborr** [comment]
@FedeMPouzols @FedeMPouzols I'm scratching my head with the [doxygen warnings](http://builds.mantidproject.org/job/pull_requests-doxygen/5845/warnings18Result/). All of them are located in WorkspaceObserver.cpp and complaing that the methods are not declared or defined, yet the header file (WorkspaceObserver.h) is included in the source! It seems like doxygen is not parsing the header file ?!?

**Comment by FedeMPouzols** [comment]
@jmborr : It seems that doxygen is getting confused with `Q_DECLARE_METATYPE`?
Do you need that in WorkspaceObserver.h? It will be visible to many other classes besides your new ones.

**Comment by jmborr** [comment]
@FedeMPouzols How did you reach that conclusion regarding Q_DECLARE_METATYPE? I'd like to know so that I can identify myself this kind of problem in the future
The sad thing is that I only fixed some typos in comments of WorkspaceObserver.h(cpp) in the course of reading the file. I didn't changed the source code at all ! :disappointed:
As far I as understand, the Q_DECLARE_METATYPE declarations are there so that later one can save std::string objects as QVariants. However, I don't know why they must be declared at the top namespace, maybe because all other Qt objects also reside at the top namespace? Lamar introduced these lines fairly [recently](https://github.com/mantidproject/mantid/commit/ff76f648da7486eb339b7156fcaf5241470a4c64) and he may know.

**Comment by FedeMPouzols** [comment]
Ah sorry, my bad. I read too quickly and thought that the `Q_DECLARE_METATYPE` line was new. It's the only change in WorkspaceObserver so I'd first check that. Could it be that the `//` line comment is confusing doxygen? `Q_DECLARE_METATYPE` seems to be defined as a multi-line macro.

**Comment by jmborr** [comment]
@FedeMPouzols @shahrozahmed1 Miracle, finally the tests passed. the comment line next to Q_DECLARE_METATYPE was unkind to doxygen.

**Comment by shahrozahmed1** [comment]
capture
@jmborr for some reason the bottom graph is not being displayed on the interface for me, might be because I'm using windows?

**Comment by jmborr** [comment]
@shahrozahmed1 This is an issue that it's present also in Linux. The bottom graph starts "minimized" but you can see it by moving upwards the slider at the bottom:
junk

**Comment by shahrozahmed1** [comment]
@jmborr I manage to find the slider after few attempts, is it not possible to make the slider visible on the Interface?

**Comment by shahrozahmed1** [comment]
workingprcapture

Otherwise everything else looks good, the GUI contains lots of features, `Built-in` combo-box feature stands out, definitely would come in handy. Some features are not functioning yet such as `clear` button and `Custom` combo-box on top of the interface but its still early days for this GUI so can be looked at in future github issues..

**Comment by FedeMPouzols** [comment]
@jmborr, @shahrozahmed1: if that slider is a `QSplitter` you might be able to force a size ratio between them by giving explicit size hints, with code like this: https://github.com/mantidproject/mantid/blob/master/MantidQt/CustomInterfaces/src/Tomography/TomographyIfaceViewQtGUI.cpp#L321-L332. I've always found it very hard to make `QSplitter`s behave with default settings or just initial property values.

**Comment by jmborr** [comment]
@FedeMPouzols I'm going to take a look to the link, thanks!

**Comment by jmborr** [comment]
@shahrozahmed1 Yes, there features missing that will be implemented in future GitHub issues. Nevertheless I wanted this out in MantidNightly so that my "friendly user" collaborator can start trying it out so that I get some feedback.

**Comment by shahrozahmed1** [comment]
@jmborr This works well for me now, the graph on the bottom also fits well in to the interface now.
 :shipit:

**Comment by jmborr** [comment]
Thank you for taking the time to review :carousel_horse:

**Pull request merged**
