### PR TITLE
Minor change to the theta width calculation in ReflectometryTransform

### PR DESCRIPTION
**Pull request by gemmaguest**
**Report to:** Max at ISIS

Scientists requested to change the calculation of theta widths in ReflectometryTransform (used by ConvertToReflectometryQ) because the original calculation did not seem to make sense. The difference should be very small - in fact there is no change in the unit test results to 1e-9.

This PR also does some tidying of variable names to make it clear that we are using twoTheta rather than theta (see also #29764)

**To test:**

Check that `ConvertToReflectometryQ` (which uses ReflectometryTransform) runs ok and produces sensible output, e.g. the example in the following script contains a bragg sheet, which displays as a vertical line when correctly converted to QxQz. Slight errors would cause this line to go off vertical.

```
name = "POLREF4699"

PIX=1.1E-3 #m
SC=75
avgDB=29
Load(Filename=name,OutputWorkspace=name)

ConvertUnits(InputWorkspace=name,OutputWorkspace=name,Target="Wavelength",AlignBins="1")
CropWorkspace(InputWorkspace=name,OutputWorkspace='Io',XMin=0.8,XMax=14.5,StartWorkspaceIndex=2,EndWorkspaceIndex=2)                                                                              
CropWorkspace(InputWorkspace=name,OutputWorkspace='D',XMin=0.8,XMax=14.5,StartWorkspaceIndex=3)
Divide(LHSWorkspace='D',RHSWorkspace='Io',OutputWorkspace='I', AllowDifferentNumberSpectra='1',ClearRHSWorkspace='1')
MoveInstrumentComponent(Workspace='I',ComponentName="lineardetector",X=0,Y=0,Z=-PIX*( (SC-avgDB)/2.0 +avgDB) )
ConvertSpectrumAxis(InputWorkspace='I',OutputWorkspace='SignedTheta_vs_Wavelength',Target='signed_theta')
QxQy, _QxQy_vertexes = ConvertToReflectometryQ(InputWorkspace='SignedTheta_vs_Wavelength',
    #OutputAsMDWorkspace=False,
    OutputDimensions='Q (lab frame)', Extents='-0.0005,0.0005,0,0.12')
```

image

Refs #20327

*This does not require release notes* because **the difference in the results is negligible**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@gemmaguest Do you have the script that produced that plot?

**Comment by gemmaguest** [comment]
> 
> 
> @gemmaguest Do you have the script that produced that plot?

@martyngigg Doh, sorry, forgot to paste it. I've updated the comment with the script.

**Comment by martyngigg** [comment]
> > @gemmaguest Do you have the script that produced that plot?
> 
> @martyngigg Doh, sorry, forgot to paste it. I've updated the comment with the script.

Thanks!

**Review by martyngigg — APPROVED** [review]
Looks good. Improved variable namings and if there is general consensus that this calculation is preferred but the results are not really noticible then it makes sense to go with that.

**Pull request merged**
