### PR TITLE
 Remove old ISIS Reflectometry GUI

### LINKED ISSUE #18674: Ensure new GUI meets scientists' requirements so the old GUI can be removed
When scientists are happy with the new GUI, remove the old one.

The work required for the new GUI to satisfy scientists' requirements comprises:

- [x] Complete the priority fixes/additions detailed on #21167
- [x] Agree with scientists a date/release (vX) when the old GUI will be removed
- [x] Add a warning to the old GUI that it is deprecated and will be removed by said date #21103
- [ ] Remove the old GUI (vX)

### PR DESCRIPTION
**Pull request by giovannidisiena**
**Description of work.**
The old ISIS Reflectometry GUI has been removed.

**To test:**
Check that the GUI is not in MantidPlot and no warnings are shown.

Resolves #18674 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by giovannidisiena** [comment]
@gemmaguest I have removed the old GUI but not entirely sure how it is tied to `DataProcessorUI` etc and whether they too could/should be removed. Release notes to follow when this is clarified.

**Review by gemmaguest — CHANGES_REQUESTED** [review]
Looks good and all signs of the old GUI are gone :+1:. Just one thing - the `scripts/Interface/ui/batchwidget/` directory relates to a separate test interface (`BatchWidgetInterface`), so this should not be removed. That test interface is actually broken but that's a separate problem - I've raised issue #27971 for it.

**Comment by giovannidisiena** [comment]
@gemmaguest that should be resolved now :+1:

**Review by gemmaguest — APPROVED** [review]
Looks good now :+1:

**Pull request merged**
