### PR TITLE
Fix plotting of elliptical bg shell in sliceviewer

### LINKED ISSUE #29087: Workbench sliceviewer ellipsoid background shell not plotted correctly
The inner radius of the ellipsoid background shell is not plotted correctly in workbench sliceviewer. A comparison of mantidplot (left) and workbench (right) is shown below

image

MantidPlot is displaying an background inner radius very similar to the peak radius as it should be, but the workbench sliceviewer displays a much larger inner radius.

The spherical peakshape is plotted correctly in workbench.

### Platforms affected
workbench

### PR DESCRIPTION
**Pull request by RichardWaiteSTFC**
**Description of work.**

The elliptical shell is created by an affine transformation of a unit circle - therefore the inner radius for the shell (before transform) needs to be determined from fractional thickness of shell (relative to outer background radius) not the absolute thickness (defined as the difference between the major radii of the inner and outer background ellipsoids).

**To test:**

Follow instructions in original issue (feel free to delete all but a couple of peaks to speed this up). In IntegratePeaksMD the background inner radius is equal to the peak radius, which should now be the case for the elliptical shell plotted in sliceviewer (i.e. the inner radius of the shell should coincide with the dashed red line of the peak ellipse).

image

Fixes #29087 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by rosswhitfield** [comment]
An issue that is probably unrelated to this, the same ellipsoid peak shape gets plotted regardless of which axis you have selected in sliceviewer, changing the X, Y and transposing make no difference in what is drawn.

**Comment by RichardWaiteSTFC** [comment]
> An issue that is probably unrelated to this, the same ellipsoid peak shape gets plotted regardless of which axis you have selected in sliceviewer, changing the X, Y and transposing make no difference in what is drawn.

Thanks for this, I will look into it. Does the data change when X and Y are swapped - if not this was an issue that has recently been fixed by PR #30336

**Comment by rosswhitfield** [comment]
> Thanks for this, I will look into it. Does the data change when X and Y are swapped - if not this was an issue that has recently been fixed by PR #30336

Yeah, it looks like those changes are in this branch.

**Comment by RichardWaiteSTFC** [comment]
I don't think this is relevant to this PR, but have created an issue for it #30433 that I have assigned to milestone 6.0

**Review by rosswhitfield — APPROVED** [review]

**Pull request merged**
