### PR TITLE
LET modifications for cycle 2015/1

### PR DESCRIPTION
**Pull request by abuts**
this address ticket http://trac.mantidproject.org/mantid/ticket/11292

### CODE REVIEW

**Comment by abuts** [comment]
These are trivial changes, reflecting changes in LET configuration for cycle 2015/1
They can be safely merged as soon as system test which verifies IDF correctness passes,

**Comment by AndreiSavici** [comment]
Is ISIS_LETReduction.py supposed to be a systemtest? Then why have hardcoded paths to c or d drives? If not, why is it in systemtests?

**Comment by abuts** [comment]
ISIS_LETREduction.py is a sample of reduction run. It is also part of the system test  ISISDirectInelastic. This test instantiates classes from ISISLETReduction with its own settings and runs them as a system test. 

As sample reduction run it runs from Mantid and user expected to change harcorded path to the one suitable for his machine.

**Comment by abuts** [comment]
While the commit have not been closed, I use this opportunity to fix minor bug, identified while running reduction from web services.

**Pull request merged**
