### PR TITLE
Improve saveplot1dasjson

### LINKED ISSUE #13572: Improvements to SavePlot1DAsJson
There are some small changes:

1. For the units, use the result of `axis.symbol().latex()` or fall through to `axis.symbol()` if it generates an exception. This should give proper mark-up for Angstroms.
1. If the units are empty, don't include the parenthesis (e.g. `Spectrum ()` should be `Spectrum`)
1. The `PlotName` property doesn't belong. Please remove it.
1. The title for each spectrum should be the workspace title and the spectrum number. `"%s - spectrum %d" % (workspace.getTitle(), workspace.getSpectrum(wksp_index).getSpectrumNo())`
1. The labels for the various spectra should be unique. A useful setting would be `"%s_spectrum_%d" % (workspace.getName(), workspace.getSpectrum(wksp_index).getSpectrumNo())` (negotiable).
1. There needs to be an additional argument, `MainOutputSpectrum`, to select a spectrum to label as `main_output`. This is required by the live monitor so it can select which spectrum to plot. This should default to the first spectrum if it is not set by the user. `Property.EMPTY_INT` and `self.isEmpty` will probably be helpful in implementing this.

This is a follow on to #10234.

### PR DESCRIPTION
**Pull request by yxqd**
This fixes #13572

### CODE REVIEW

**Comment by martyngigg** [comment]
Could you please provide assign some a labels and milestones to the pull request?

Also, could you edit the original comment to follow the guidelines at http://www.mantidproject.org/Git_Workflow#Pull_Requests

**Comment by mdoucet** [comment]
- We need an option to append to an existing json file.
- The axis info is incomplete:
```
"axes": {"xunit": "\\AA^{-1}", "xlabel": "q", "yunit": "", "ylabel": "Spectrum"}
```

`yunit` and `ylabel` should be filled out when it's available. You may want to use workspace.YUnitLabel().

**Comment by yxqd** [comment]
The y axis info was already transferred to the dictionary by workspace.getAxis(1).getUnit() and then .caption() (label) and .symbol().latex() (unit). 

I suggest opening a new ticket for the "append" functionality.

**Comment by yxqd** [comment]
Mathieu showed that ws.YUnitLabel() returns "1/cm" while ws.getAxis(1).getUnit().symbol() returns an empty string for a I_q curve saved in a workspace xml file. Is that a bug or feature? For now I will use YUnitLabel().

**Comment by peterfpeterson** [comment]
The RHEL7 failure is unrelated

**Comment by mdoucet** [comment]
It works, but #13962 needs to get done for this new algorithm to be useful.

**Pull request merged**
