### PR TITLE
Indirect - CorrectionsTabs - Error handling in the case of a WorkspaceGroup being provided

### LINKED ISSUE #21157: CalculatePaalmanPings GUI crash
The GUI tab crashes if a file containing a workspace group is supplied.

Steps to reproduce:
1. Navigate to Interfaces->Indirect->Corrections->CalculatePaalmanPings Tab.
2. Choose the attached nexus file in the first input file field. (first rename it to get rid of '.zip')
3. Count to 5 -> 💣 

The problem is that it tries to get the instrument from the group workspace directly.

[16658_166445_red.nxs.zip](https://github.com/mantidproject/mantid/files/1457331/16658_166445_red.nxs.zip)

### PR DESCRIPTION
**Pull request by brandonhewer**
~~**Must be merged after #21333**~~

Currently, in the Interfaces > Indirect > Corrections tabs, attempting to supply a WorkspaceGroup to the sample/container input fields, provides no informative error message. Upon clicking the 'Run' button in these interfaces, prior to supplying a WorkspaceGroup, Mantid will currently crash.

This PR adds correct error handling, in the circumstance in which a WorkspaceGroup, or any invalid workspace type is provided to the input fields of the Indirect CorrectionsTabs.

A message box will be displayed, when the invalid workspace type is first selected:
corr_err_message

Along with a message output in the log:
corr_err_log

This PR also improves the error message when the 'Run' button is clicked and a workspace of an invalid type, occupies the sample/container input field:
corr_err_message_run

**To test:**
1. Navigate to Interfaces > Indirect > Corrections.
2. For each tab in the Indirect Corrections interface:
    1. Supply the provided `sample_group_red.nxs` file into the sample field.
    2. Ensure an error message, similar to the one shown above, is displayed and a warning is output to the log.
    3. Click the 'Run' button.
    4. Ensure an error message, similar to the one shown above, is displayed, which includes a line about the sample input not being of the correct type.
    5. If there is a container field, supply the provided `container_group_red.nxs` file into the container field.
    6. In the 'ContainerSubtraction' interface, the same error message received when providing the sample group, should be produced. Otherwise, no error should be produced.
    7. Click the 'Run' button.
    8. Ensure an error message, similar to the one shown above, is displayed, which includes both a line about the sample input not being of the correct type and the same for the container input.

**Test Files:**
[group_test_files.zip](https://github.com/mantidproject/mantid/files/1552406/group_test_files.zip)

Fixes #21157. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gvardany** [comment]
@brandonhewer This has developed a conflict.

**Review by gvardany — CHANGES_REQUESTED** [review]
The error handling seems fine, except I wonder if we should put also the reason of the error in the pop-up message instead of the log behind? This would make it more user friendly. If not at least the log level should be set to error, since it is a blocking issue. 
My only concern is that validation seems to take too long, and in fact, when you browse the file, and immediately click Run, it still crashes. Could you investigate disabling the Run button, while the validation is in progress?

**Comment by brandonhewer** [comment]
@gvardany I agree that showing a message box would be more appropriate here and the extra message you've pointed out, would be very useful here.

On the topic of the issue with the Run button - I've come across this problem before and included it on the MSG board backlog. This issue appears to be universal across Indirect tabs, so I'll create a new issue for this.

**Comment by gvardany** [comment]
I agree the run button issue can be fixed in a separate PR.

**Review by gvardany — APPROVED** [review]

**Pull request merged**
