### PR TITLE
Extended cow_ptr to be more like shared_ptr, in particular added support for NULL cow_ptr.

### LINKED ISSUE #15844: Add support for NULL cow_ptr.
For holding optional resources, and for making the semantics equivalent to `shared_ptr` and `unique_ptr`, `Kernel::cow_ptr` should be able to be equal to `nullptr`.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Extended cow_ptr to be more like shared_ptr, in particular added support for NULL cow_ptr. A few (related) missing interface functions from `shared_ptr` were also added to make the interfaces more similar.

**To test:**

Code review.

Fixes #15844.

No release notes

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by OwenArnold** [comment]
@SimonHeybrock This all looks good. I have some slight reservations regarding the forwarding of methods belonging to the `shared_ptr` regarding uniqueness and instance counts. Looking at the original code, the author had gone through some trouble to hide the `smart_ptr` behind the `cow_ptr`.

**Comment by SimonHeybrock** [comment]
@OwenArnold Yes, you may be right. On the other hand at the time this class was created `shared_ptr` and `unique_ptr` were maybe not so prevalent. Now everyone is familiar with these, so I thought a more uniform interface would actually be easier?

I think you are right and I should definitely remove `get()`, since it is dangerous. I would suggest keeping `unique` and `use_count`, but if you feel otherwise I can remove them as well.

**Comment by OwenArnold** [comment]
@SimonHeybrock, my concern with the `unique` and `use_count` is that the client should never have to access those things. If there was a decision to replace the internals of `cow_ptr` with another type of smart pointer, it maybe impossible to keep providing the `use_count` and `unique` methods.

However, I'm not strongly adversed to having these methods, because I think it's unlikely that a different smart pointer type would be provided.

**Comment by SimonHeybrock** [comment]
@OwenArnold I thought they might be useful in `MatrixWorkspace`, to determine whether `X` is shared, etc.

**Comment by OwenArnold** [comment]
@SimonHeybrock. OK lets leave those methods in then.

**Comment by OwenArnold** [comment]
:shipit:

**Pull request merged**
