### PR TITLE
Added external data support to mantid

### PR DESCRIPTION
**Pull request by martyngigg**
Fixes issue [#10869](http://trac.mantidproject.org/mantid/ticket/10869)

### CODE REVIEW

**Comment by martyngigg** [comment]
jenkins retest this please

**Comment by martyngigg** [comment]
jenkins, retest this please

**Comment by martyngigg** [comment]
jenkins, retest this please

**Comment by rosswhitfield** [comment]
Can `StandardTestData` be not a target of all? So it will only get the data when any unit tests are built.

**Comment by peterfpeterson** [comment]
The failed builds are because `focussed.nxs` is required by `LoadNexusProcessedTest` and not in the new system. Otherwise I like it too. :+1:

**Comment by martyngigg** [comment]
@rosswhitfield That's a good idea, I'll exclude it.
@peterfpeterson The builds have checked out the wrong point for some reason so don't seem to have all of the file changes I made. I'll have a look

**Comment by martyngigg** [comment]
Jenkins, retest this please

**Comment by martyngigg** [comment]
Jenkins, retest this please

**Comment by martyngigg** [comment]
Jenkins, retest this please

**Comment by martyngigg** [comment]
Jenkins, retest this please

**Comment by martyngigg** [comment]
Jenkins, retest this please

**Comment by martyngigg** [comment]
Jenkins, retest this please

**Comment by peterfpeterson** [comment]
The exclude from all works and everything seems fine on FC20.

**Comment by mantid-roman** [comment]
Windows build OK

**Comment by quantumsteve** [comment]
works on mac

**Comment by peterfpeterson** [comment]
I say :shipit: !

**Comment by martyngigg** [comment]
@peterfpeterson want to do the honours?

**Comment by OwenArnold** [comment]
Looks good.

**Pull request merged**
