### PR TITLE
Prevent close of InstrumentWidget on ALFView

### LINKED ISSUE #34663: Deleting the workspace loaded into ALFView will close the InstrumentWidget

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR fixes a bug where the InstrumentWidget used on the ALFView interface would be closed when the loaded workspace was deleted from the ADS. This made the interface unusable and you would need to close and reopen the interface.

**To test:**
1. Load ALF82301 into ALFView
image

3. Clear the ADS

5. The ALFInstrumentView should go blank (i.e. an empty ALF instrument is loaded into the interface)
image

7. Try loading a dataset again and see that the instrument view is populated with data again.

Fixes #34663

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by robertapplin** [comment]
> When deleting the workspace from the ADS, the instrument widget remains open on an empty instrument. But it also creates a new workspace in the ADS (that correspond to the empty instrument) with the same name as the previous one. From the user's perspective it looks like the workspace cannot be deleted from the ADS.
> 
> Would it be possible to keep the instrument widget opened on a "unregistered" empty workspace ?

I agree this would be far better, however the InstrumentWidget is currently very dependent on the workspace existing in the ADS. Whenever the InstrumentActor is reset, it is provided a new workspace name, which assumes it corresponds to an ADS workspace. If the workspace is deleted, I can keep the InstrumentWidget open, but the InstrumentDisplay will not update to show an empty instrument unless I load a workspace to override the previously deleted workspace.

I think it might be a big job to try and decouple the instrument widget from the ADS, and so I went with a compromise in this PR. Would it be useful to open a separate maintenance issue to make the instrument widget more decoupled in the future? 

What do others think? @martyngigg @peterfpeterson @thomashampson

**Comment by peterfpeterson** [comment]
I thought the current behavior was to close the instrument widget when the workspace was deleted. I remember @zjmorgan being involved in similar discussions before.

**Comment by zjmorgan** [comment]
> I thought the current behavior was to close the instrument widget when the workspace was deleted. I remember @zjmorgan being involved in similar discussions before.

That wasn't me

**Comment by gui-co** [comment]
> I think it might be a big job to try and decouple the instrument widget from the ADS

Ok, I understand. As we mentioned this during our discussions at ISIS last month, I thought it had already been implemented.

If the current behavior is fine with you and your users, we can keep it that way. Let me know.

**Comment by robertapplin** [comment]
> > I think it might be a big job to try and decouple the instrument widget from the ADS
> 
> Ok, I understand. As we mentioned this during our discussions at ISIS last month, I thought it had already been implemented.
> 
> If the current behavior is fine with you and your users, we can keep it that way. Let me know.

I believe the `InstrumentDisplay` which is held by the `InstrumentWidget` has been decoupled from the ADS, but there is still more work to do. Yes the current behaviour is fine with the users.

I've created a maintenance issue here https://github.com/mantidproject/mantid/issues/34821

**Review by gui-co — APPROVED** [review]
Thanks for you answer and the maintenance issue.

Apart from my previous comment, the code looks good and works as expected.

**Pull request merged**
