### PR TITLE
Update ADARA files with latest version

### LINKED ISSUE #13200: Update LiveListener code for new ADARA packets
Two ADARA packet types (Banked Event and Beam Monitor Event) have been bumped from version 0 to version 1.  The LiveListener class needs to be able to accept both versions of these packets

### PR DESCRIPTION
**Pull request by rgmiller**
Import the latest ADARA files over from the ADARA git repo and make the
necessary mods to work with the Mantid code.  Specifically, we needed
the updated parser and new packet types.

Also fixed a pretty serious bug in the handling of the annotation
packets.

This code seems to work with old ADARA data, but I still need to test it
against an ADARA stream that includes the new packet types.

Fixes #13200

### CODE REVIEW

**Comment by rgmiller** [comment]
Testing:  Testing the LiveListener code is tricky.  The easiest way would be to compile MantidPlot and then start listening to one of the normal beamline SMS servers.  Unfortunately, since there's no neutrons right now, that won't tell you much.  As a fallback, you can use ncat to replay a previously recorded stream.  (Contact Jim Kohl or myself if you don't have one.)

**Comment by AndreiSavici** [comment]
I have problems building Mantid on RHEL7 (analysis), so I cannot test this ticket

**Comment by stuartcampbell** [comment]
@AndreiSavici So won't I have the same problems on RHEL7 (analysis) ?

**Comment by stuartcampbell** [comment]
As this currently doesn't work anyway - there shouldn't be too much issue just merging this.

**Pull request merged**
