### PR TITLE
Add Qt5 build of instrument view and add to workbench

### LINKED ISSUE #20240: Convert instrument view miniplot to matplotlib
As part of the the preparation work for the new workbench we need to convert the miniplot within the instrument view to be a matplotlib-based widget in C++.

This will involve writing a small set of classes in C++ to wrap `matplotlib` and shield developers from the intricacies of dealing with the Python C api.

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Adds a Qt5 build of the instrument library where the colorbar and miniplot are powered by matplotlib and not Qwt. A python wrapper package has been defined `mantidqt.widgets` and used to show the instrument view from the workspace context menu in the workbench.

**To test:**

The instrument view can be tested standalone from Python:

```python
from mantidqt.widgets.instrumentview.view import InstrumentWidget
import mantid.simpleapi as sapi
from qtpy.QtWidgets import QApplication

ws = sapi.Load("ExternalData/Testing/Data/DocTest/SXD23767.raw")
peaks = sapi.Load("ExternalData/Testing/Data/DocTest/SXD23767.peaks")

app = QApplication([])
w = InstrumentWidget(ws.name())
w.overlay(peaks.name())
w.show()
app.exec_()
```
The data paths assume running in the build directory with the test data targets built.

To test in the workbench, start the workbench, load a workspace and right click to show the context menu. Click "Show Instrument".

Fixes #20240 

*This does not require release notes* because it is part of the workbench as will be announced separately.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by rosswhitfield** [comment]
Changing the colour scale, either the limits or type (Log/Power) causes a segfault with python 3 on Ubuntu 18.04. It works with python 2.

**Comment by martyngigg** [comment]
Hmm. I had it segfaulting too but I thought the recent fixes had addresses that. I will have another look.

I must admit I had not touched the masking so had not checked it. I'll see what Qt5 has changed.

**Comment by rosswhitfield** [comment]
I can't get python 2 to segfault anymore but I still get all the same segfaults with python 3. :confused: 

And a new thing I found, set the colorbar to `Power` and range from -1 to 1, the colorbar disappears and you get the following warning. :grin: 
```
/usr/lib/python2.7/dist-packages/matplotlib/colorbar.py:891: RuntimeWarning: invalid value encountered in true_divide
  z = np.take(y, i0) + (xn - np.take(b, i0)) * dy / db
```

**Comment by martyngigg** [comment]
@rosswhitfield Thanks for checking out the Python 3 build. I think I actually have fixed those segfaults now :) :pray: 

I'll take a look at the weird behaviour of the scale change. It certainly shouldn't disappear!

**Comment by rosswhitfield** [comment]
It works in python 3 now. :tada: 

One more thing I found, changing the colormap updates the figure by not colorbar.

**Comment by martyngigg** [comment]
@rosswhitfield I should have fixed those last 2 bugs now :)

**Comment by rosswhitfield** [comment]
Yes they work now... for python 2. Python 3 is back to segfaulting as before.

**Comment by martyngigg** [comment]
@rosswhitfield Thanks for the test. Another GIL missing somewhere! I wish I could think of a way to duplicate this in the unit tests. Maybe I need to write some python-based unit tests...

**Comment by martyngigg** [comment]
Python 3 should be working again now.

**Review by rosswhitfield — APPROVED** [review]
It all works now. :+1: 

One small request, although it can wait until later, on the `Pick` tab collapsing the `Selection` section causes the `Tool` label to expand, unlike in mantidplot where the plot is expanded, can this be changed? :wink:

**Pull request merged**
