### PR TITLE
Label groups with run title in Reflectometry (Polref) GUI

### LINKED ISSUE #17817: Label groups with run title
In the Reflectometry (Polref) GUI, when we transfer runs group names should be populated with run title, for instance "S1 bilayer T=37C D2O".

This is part of the set of improvements to the interface, hence related to the road map issue https://github.com/mantidproject/mantid/issues/15565

### PR DESCRIPTION
**Pull request by raquelalvarezbanos**
When runs are transferred to the processing table, the group should include a description. There are two "strategies" to transfer runs, `Measurement` and `Description`, which can be selected using the combo box next to the `Search` button. Changes in this PR apply to both cases.

**To test:**

- Check code changes. I had to modify `LoadNexusLogs` so that `run_title` is added to the workspace.
- Functional testing: I think the best way to test the changes is by comparing results to the master branch:
  - Measurement strategy:
    - Open MantidPlot -> Interfaces -> Reflectometry -> ISIS Reflectometry (Polref)
    - Select `POLREF` in the instrument combo box. Select `Measurement` strategy.
    - Enter `1520249` and use your user ID and password to log in to the catalog. The table on the left will be populated with some runs. Select all of them and click on `Transfer`, runs will appear on the table on the right. On the master branch there will be an integer number associated with each group. On this branch the integer number should be followed by a description.
    - Expand each group and check that they contain the same run numbers and angles as on the master branch.
  - Legacy strategy:
    - Repeat the same steps but selecting `Description` strategy (on the master branch you may need to close and re-open the interface due to a known bug I have fixed on this branch). This time, integer numbers should not appear, only group information.
    - Expand groups and check that they contain the same run numbers and angles as the master branch (note that because group title does not include the integer number, groups will have been transferred in a different order)

Fixes #17817 

**Release notes** were updated.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
Commits from @PranavBahuguna come from branch `17897_reflectometry_polref_docs_update`, which I merged into this one.

**Comment by PranavBahuguna** [comment]
On reviewing the PR, I have found the following:

- The code itself appears fine with no glaring issues and is well documented.
- Following the functional tests for measurement strategy produces all the expected results.
- Following the functional tests for description strategy also produces all the expected results.

One bug I found (unrelated to this issue however) is that searching with `Description` strategy, switching to `Measurement` (without searching for runs) and attempting to transfer runs throws an unexpected exception as it tries to open the first run. Doing the reverse (search with `Measurement`, switch to `Description` then transfer) does not throw such an exception. This is not related to your changes however and does not need addressing in this issue.

Once merge conflicts are fixed, I believe its good to go.

**Comment by raquelalvarezbanos** [comment]
Thanks for testing @PranavBahuguna. Regarding the bug you found, could you create an issue to fix it?

**Comment by PranavBahuguna** [comment]
:shipit:

**Pull request merged**
