### PR TITLE
Move VSI to ParaView v5.0.0-RC1

### LINKED ISSUE #14417: Migrate VSI to ParaView 4.4
Move the VSI to build on ParaView 4.4

### PR DESCRIPTION
**Pull request by quantumsteve**
This Fixes #14417.

This updates the VSI to use [ParaView v5.0.0-RC1](http://kitware.com/blog/home/post/998). Substantial changes were made to the [color/opacity presets](http://www.kitware.com/blog/home/post/901). I also added the [Viridis colormap](http://www.kitware.com/blog/home/post/932) as an optional default.

[Release notes](http://www.mantidproject.org/index.php?title=ReleaseNotes_3_6_UI_Changes&diff=25610&oldid=25595) 

Testing: This should be tested on all supported platforms. Load and view data in the VSI, and check the behavior when changing the colormaps, enabling/disabling log scaling, and switching views.
- [X] OSX - @OwenArnold 
- [x] RHEL6 - @AndreiSavici
- [x] RHEL7 - @AndreiSavici
- [x] Ubuntu - @picatess
- [x] Windows -  @picatess
- [X] Fedora 23 - @peterfpeterson
- [x] Arch Linux - @rosswhitfield

### CODE REVIEW

**Comment by rosswhitfield** [comment]
RHEL7 doesn't work. I get `Could not open library /opt/mantidunstable/pvplugins//libMantidVatesSimpleGuiViewWidgets.so: libvtkpqApplicationComponents-pv5.0.so.1: cannot open shared object file: No such file or directory`

**Comment by picatess** [comment]
@quantumsteve  I started testing on Ubuntu. It seems that all color maps are Cool To Warm
screenshot from 2015-11-23 09 01 54

**Comment by AndreiSavici** [comment]
Works on Ubuntu 15.10, and I see all color maps
screenshot from 2015-11-23 11-00-17

**Comment by quantumsteve** [comment]
@picatess I can reproduce your issue on Ubuntu 15.04. The easiest workaround is to change your `JSONCPP_LIBRARY` to `${ParaView_DIR}/lib/libvtkjsoncpp-pv5.0.so`.

**Comment by quantumsteve** [comment]
@picatess @AndreiSavici I changed the linking in VATES-related libraries from `${JSONCPP_LIBRARIES}` to `${vtkjsoncpp_LIBRARIES}`. This should correct the colormap issue.

**Comment by rosswhitfield** [comment]
The only way I can get this to work on my system is to build paraview with `VTK_USE_SYSTEM_JSONCPP=ON`. Else it just segfaults when I try to access things like `Color Preset`

**Comment by quantumsteve** [comment]
@stuartcampbell is backporting jsoncpp 0.10.5 for Ubuntu 14.04+, Fedora 22&23, and RHEL 6 & 7.

**Comment by quantumsteve** [comment]
I believe one of the other mantid libraries is bringing in the system `libjsoncpp.so` through `LINK_PUBLIC`, but haven't tracked down which one. I think the better and more robust fix is to backport jsoncpp and use that library for both mantid and ParaView.

**Comment by quantumsteve** [comment]
@rosswhitfield found that the new colormaps are being added to `~/.config/Mantid/MantidPlot-UserSettings.json` each time we use the VSI. I think the issue occurs around [here](https://github.com/Kitware/ParaView/blob/master/ParaViewCore/ServerManager/Rendering/vtkSMTransferFunctionPresets.cxx#L63), though haven't followed it back far enough to properly fix the issue.

**Comment by stuartcampbell** [comment]
@quantumsteve I have done jsoncpp for RHEL and Fedora - didn't realise that I was doing ubuntu!

**Comment by quantumsteve** [comment]
I think commit ae889d9 fixes the issue with colormaps being imported more than once. If you previously used this branch, please delete the file `~/.config/Mantid/MantidPlot-UserSettings.json` before testing.

**Comment by quantumsteve** [comment]
Testing requires jsoncpp > 0.7.0. This should already be the case for Windows, OS X and Ubuntu 15.10. [RPMS are available](https://copr.fedoraproject.org/coprs/mantid/mantid/build/142136/) for Fedora and RHEL. @martyngigg will backport jsoncpp for Ubuntu 14.04.

**Comment by martyngigg** [comment]
We need to make sure we add the minimum versions for jsoncpp to the rpm/deb dependencies + the `FindJSON.cmake` so that developers get warned early

**Comment by quantumsteve** [comment]
@martyngigg done in commits `e333b9a` and `69f2348`.

**Comment by OwenArnold** [comment]
Looks good to me on OSX

**Comment by AndreiSavici** [comment]
The mantidunstable rpm installed a newer jsoncpp version on RHEL7.

Also, Ubuntu 15.10 seems to be working. I did not test on 14.04

**Comment by quantumsteve** [comment]
I created a separate, nonblocking issue to address a windows-only slowdown while switching views.
https://github.com/mantidproject/mantid/issues/14713

**Comment by peterfpeterson** [comment]
An update on this. ORNL is currently waiting for some changes to our analysis cluster that gets headless servers to start-x and not kill it. This is required for the virtualgl solution we are planning on for this to work.

**Pull request merged**
