### PR TITLE
Fix binary op/ sliceviewer deadlock

### LINKED ISSUE #33997: Crash when running python script and overwriting a workspace
**Describe the bug**
Mantid will crash when running the below script for a second time after opening a workspace in SliceViewer.

See this detailed comment from Gemma https://github.com/mantidproject/mantid/pull/33968#issuecomment-1141085907

**To Reproduce**
- Run the script below.
- Open sliceviewer on `ws` then re-run the whole script. This gave me a deadlock.

```
ws = CreateMDWorkspace(Dimensions='3', 
                       EventType='MDEvent', 
                       Extents='-10,10,-5,5,-1,1', 
                       Names='Q_lab_x,Q_lab_y,Q_lab_z', 
                       Units='1\A,1\A,1\A')
FakeMDEventData(ws, UniformParams="1000000")
ws = ws*10
```

**Expected behavior**
There should be no crash

**Platform/Version (please complete the following information):**
 - OS: [e.g. Windows, RHEL 7, Ubuntu, macOS]
 - OS Version:
 - Mantid Version [e.g. 6.0.0]

### PR DESCRIPTION
**Pull request by MialLewis**
**Description of work.**
This PR fixes a deadlock revealed (but not caused by) the changes made as part of #33968.

It was ultimately caused by an interaction between the binary operator (and a lack of release of the GIL), and sliceviewer refresh. More detail included at the bottom of this PR if interested.

As a result of this PR, binary operator now releases the GIL.

**To test:**
See instructions in #33968.

In addition, run the following script, open sliceviewer, run the script again.
`ws = CreateSampleWorkspace()
for i in range(20):
    print(i)
    ws = ws*10`

Fixes #33997

Addendum:
The deadlock functioned in the following way, with sliceviewer (SV) open on a workspace, **ws**, looping through n binary operations:
- Binary Operation (BO) performed on ws (_BO takes the GIL_, **write locks the workspace**)
- BO finished ( _BO leaves the GIL upon finish_, **removes lock**)
- SV refresh is initiated following BO (_SV takes the GIL_, **read locks the workspace**, _SV leaves the GIL to allow for:_ )
- As part of refresh, SV initiates a integration algorithm (Int.) (_Int. takes the GIL_ and _Int. leaves the GIL upon finish_)
-  Binary Operation (BO) initiated on ws (_BO takes the GIL_, **write locks the workspace**) - IS FORCED TO WAIT FOR THE READLOCK FROM SV REFRESH.
- As part of refresh, SV initiates another integration alg (2nd of 5) - IS FORCED TO WAIT FOR THE GIL, AS NOT RELASED BY BO. REFRESH CANNOT FINISH, CAUSING DEADLOCK.

This does not require release notes because it fixes a bug revealed by a recently merged PR, which users have not yet been exposed to.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by robertapplin** [comment]
This fix works from my windows conda build, but I still get the deadlock for a non-conda build using this script:
```
ws = CreateMDWorkspace(Dimensions='3', 
                       EventType='MDEvent', 
                       Extents='-10,10,-5,5,-1,1', 
                       Names='Q_lab_x,Q_lab_y,Q_lab_z', 
                       Units='1\A,1\A,1\A')
FakeMDEventData(ws, UniformParams="1000000")
ws = ws*10
```

**Comment by MialLewis** [comment]
As a note, the current state of this issue is the following:

- Deadlock caused by interaction between integration alg and binary op alg is fixed for conda and non-conda builds.
- There is still a deadlock caused by interaction between binMD alg and binary op alg on non-conda builds, though fixed on conda.
- A new deadlock caused by interaction between binMD alg and FakeMDEventData alg has been found on conda and non-conda builds.

**Comment by MialLewis** [comment]
@robertapplin After discussing this with @gemmaguest, I think its worth merging this PR as it solves one of the deadlocks on Conda builds (which the packages are moving forwards). Perhaps we keep the issue open as there is still more to be done.

**Review by robertapplin — APPROVED** [review]
Sounds good, happy to approve in that case 👍

**Pull request merged**
