### PR TITLE
Add workarounds for MSVC with update 3

### PR DESCRIPTION
**Pull request by martyngigg**
Applies a workaround to the python interface in order to circumvent a suspected bug with VS2015 and update 3.

**To test:**

Apply update 3 and check it compiles and the python tests run.

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@ElliotAOram Nice catch with those `.orig` files - I've removed them now.

**Comment by ElliotAOram** [comment]
@martyngigg I'll just check that the tests pass locally then we should be good to go!

**Comment by ElliotAOram** [comment]
All tests pass locally with the exception of `SliceViewerPythonInterfaceTest` which (given that it has been failing on the master debug build for some time) I am happy to assume this is a failure with the test in Debug and not related to these changes. Everything else looks good and appears to work with MSVC Update 3 :shipit:

**Comment by FedeMPouzols** [comment]
Yes, there is some issues in the algorithms run in `SliceViewerPythonInterfaceTest` in debug mode. That failure has been there for a while.

**Pull request merged**
