### PR TITLE
Change minimum TOF for topaz in interface

### LINKED ISSUE #17649: SCD interface minimum TOF
TOPAZ requests minimum change from 1000 to 500.

### PR DESCRIPTION
**Pull request by VickieLynch**
Description of work.
Miniimum TOF for TOPAZ changed from 1000 to 500.  They need this to remove TOF=0 from data.
**To test:**

Fixes #17649

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AndreiSavici** [comment]
Trivial change. :shipit:

**Comment by SimonHeybrock** [comment]
This has base branch `master`, but is marked as release 3.8?

**Comment by VickieLynch** [comment]
See #17668 from branch 3.8

**Comment by SimonHeybrock** [comment]
@VickieLynch Ok!
Note that github has a new feature since recently: When you click the edit button for the title, you can change the base branch without creating a new PR.

**Pull request closed without merging**
