### PR TITLE
Disabled model fitting in muon analysis for release

### PR DESCRIPTION
**Pull request by AnthonyLim23**
**Description of work.**

We have disabled the model analysis tab as it was causing a significant slow down in the processing of the GUI. It will be enabled at a later date.

**To test:**
Open Muon Analysis
Check that you cannot see the "model fitting tab"
Check in the plot window the combo box on the top does not have the "model data" option
Load MUSR 62260-5
Go to the fitting tab
Change the fitting type to "TF Asymmetry" 
Tick simultaneous 
Add a "StandardSC" function
Set "sigma", "FieldSC", "FieldBG" to global
Go to the sequential fitting tab
Press the "sequential fit all" button
Go to the results tab
Click "output results"
It wont be slow

*There is no associated issue.*

Removed from release notes

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
lets hold off on approving this until after we have spoken to Aidy (Friday)

**Comment by robertapplin** [comment]
If we generate the parameter combinations on-the-fly then we can avoid this slowdown. It shouldn't be a complicated change, I'll look into it this morning

**Comment by AnthonyLim23** [comment]
users are happy with this solution

**Review by sf1919 — CHANGES_REQUESTED** [review]
The tests work as expected and it does seem slightly quicker. Looking at the code the changes seems sensible to remove the model fitting tab temporarily.

Thank you for removing the release note. Would it make sense to all get rid of the model_fitting_tab.PNG file as future changes may render the image obsolete? There seems little point having it on the system at all at present.

**Comment by AnthonyLim23** [comment]
Lets keep them for now. We can just overwrite them later

**Review by sf1919 — APPROVED** [review]

**Comment by martyngigg** [comment]
Thanks for getting this done and through. Can we try and capture Aidy's use case for this in the manual testing? His example took ~10 mins once the results table button was clicked to the interface being released allowing him to do anything.

**Pull request merged**
