### PR TITLE
Adds CheckForMask option + testing for DiffractionFocussing

### LINKED ISSUE #22602: AlignAndFocusPowder produces wrong number of spectra
**Original reporter:** @marshallmcdonnell 

While processing NOMAD data it was discovered that the reduction produced a different number of output spectra if all of the spectra for a single focussed group are masked. This should be converted to a unit test in the process of fixing it.

### Steps to reproduce the behavior

```python
# Create a sample workspace
ws = CreateSampleWorkspace(WorkspaceType="Event", Function="Powder Diffraction", NumBanks=10)

# Create the grouping based on banks
grouping_ws, spectra_count, group_count = CreateGroupingWorkspace(InputWorkspace=ws,GroupDetectorsBy="bank")

# Create map of { 'Group #' : 'List of detector ids' }
group2udets = dict()
for i, gid_array in enumerate(grouping_ws.extractY()):
    gid = gid_array[0]
    if gid not in group2udets:
        group2udets[gid] = list()
    group2udets[gid].append(i)

print("Number of groups: %d" % group_count)

# Focus using the grouping
focussed_ws = DiffractionFocussing(InputWorkspace=ws, GroupingWorkspace=grouping_ws)
print("Number of spectra (Focussed): %d" % focussed_ws.getNumberHistograms())

# Mask an entire Group
mask_group_id = 1
mask_wksp_id_list = group2udets[mask_group_id]
MaskDetectors(Workspace=ws, WorkspaceIndexList=mask_wksp_id_list)

# Focussing the mask + grouping
masked_focussed_ws = DiffractionFocussing(InputWorkspace=ws, GroupingWorkspace=grouping_ws)
print("Number of spectra (Masked + Focussed): %d" % masked_focussed_ws.getNumberHistograms())
```
Output:
```shell
Number of groups: 10
Number of spectra (Focussed): 10
Number of spectra (Masked + Focussed): 9
```

### PR DESCRIPTION
**Pull request by marshallmcdonnell**
This adds a `CheckForMask` option to `DiffractionFocussing` that, when set to false, will ensure the number of histograms returned from the `OutputWorkspace` == number of histograms in the grouping scheme.

If an entire group of detectors in a group of the grouping scheme are masked, the current behavior is to not include this focussed histogram in the `OutputWorkspace`. Sometimes, this is undesired. `CheckForMask` allows this to be optional, with the default of `CheckForMask=True` to keep the old behaviour as a default.

The tests for DiffractionFocussing2 in `Framework/Algorithms/test/DiffractionFocussing2Test.h ` have been extended to test for this additional option. Also, the documentation has an extra explanation for the CheckForMask option.

**To test:**

Run the unit tests:
ctest -j2 -R AlgorithmsTest_DiffractionFocussing2

Also, you can run this test script and check output:
```
from __future__ import print_function
from mantid.simpleapi import *

# Create a sample workspace
ws = CreateSampleWorkspace(WorkspaceType="Event", Function="Powder Diffraction", XUnit="dSpacing", NumBanks=10)

# Group Detectors by the 6 Banks
##grouping_ws, spectra_count, group_count = CreateGroupingWorkspace(InstrumentName="NOMAD",GroupDetectorsBy="Group")
grouping_ws, spectra_count, group_count = CreateGroupingWorkspace(InputWorkspace=ws,GroupDetectorsBy="bank")

# Create map of { 'Group #' : 'List of detector ids' }
group2udets = dict()
for i, gid_array in enumerate(grouping_ws.extractY()):
    gid = gid_array[0]
    if gid not in group2udets:
        group2udets[gid] = list()                                                                     
    group2udets[gid].append(i)

print("Number of groups: %d" % group_count)

# Focus using the grouping
focussed_ws = DiffractionFocussing(InputWorkspace=ws, GroupingWorkspace=grouping_ws)
print("Number of spectra (Focussed): %d" % focussed_ws.getNumberHistograms())

# Mask an entire Group
mask_group_id = 1
mask_wksp_id_list = group2udets[mask_group_id]
MaskDetectors(Workspace=ws, WorkspaceIndexList=mask_wksp_id_list)

# Focus using the mask + grouping
masked_focussed_ws = DiffractionFocussing(InputWorkspace=ws,
                                          GroupingWorkspace=grouping_ws)
print("Number of spectra (Masked + Focussed): %d" % masked_focussed_ws.getNumberHistograms())

# Focus using the mask + grouping but with CheckForMask == False
masked_focussed_ws2 = DiffractionFocussing(InputWorkspace=ws,
                                           GroupingWorkspace=grouping_ws,
                                           CheckForMask=False)
print("Number of spectra (Masked + Focussed w/o Mask Check): %d" % masked_focussed_ws2.getNumberHistograms())
```

Output:
```
Number of groups: 10
Number of spectra (Focussed): 10
Number of spectra (Masked + Focussed): 9
Number of spectra (Masked + Focussed w/o Mask Check): 10
```

Fixes #22602 

Does this update require release notes?
- [x] Yes
- [ ] No

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by marshallmcdonnell** [comment]
The System Tests are failing at the PDCalibrationTest with segmentation fault. These changes are unrelated.

This issue is already reported in #22603

**Review by peterfpeterson — CHANGES_REQUESTED** [review]
The additional tests are quite helpful in fixing this behavior, but I think that the additional parameter is the wrong solution. While it is frequently useful to keep old behavior, I believe that you happened to stumble across a case that hadn't been properly characterized before.

Instead of an additional parameter, the code for calculating the group numbers should be modified to **always** create the same number of output spectra, but skip over spectra that have been masked.

**Comment by NickDraper** [comment]
@peterfpeterson @marshallmcdonnell This PR has been stuck since June, could the two of you decide how best to get it moving again?

**Comment by marshallmcdonnell** [comment]
Sorry, @NickDraper  for the delay on this. I'll close this until I or someone else can work on this again.

**Pull request closed without merging**
