### PR TITLE
Add GUI to partially save a Mantid project

### LINKED ISSUE #17969: Partial Project Serialisation GUI
This is a sub issue of #15602.

Provide a way for users to choose what workspaces they wish to save out. This should also show what graphs/plots/interfaces will also be saved and not saved.

### PR DESCRIPTION
**Pull request by samueljackson92**
This adds a new GUI window to let the user choose what workspaces and associated window to save to a project file.

**To test:**
Clicking Save Project/Save Project As should work similarly to before, but you should now be shown an interface that allows you to select which workspaces you want to save as part of the project.

Please be ensure to check edge cases such as:
 - Windows belonging to multiple workspaces
 - Workspace groups
 - Complicated interfaces: slice viewer, VSI, spectrum viewer...

This should also be tested on multiple platforms to ensure consistency

Fixes #17969 .

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
I am seeing something weird on Ubuntu:

- I load run INTER00038416 from the algorithm dialog
- I save the project by browsing to a directory and entering a name for the project
- I restart MantidPlot
- When I try to load the saved project, Mantid opens the Load dialog but not the workspace.

**Comment by samueljackson92** [comment]
@raquelalvarezbanos 
>I am seeing something weird on Ubuntu:
> - I load run INTER00038416 from the algorithm dialog
> - I save the project by browsing to a directory and entering a name for the project
> - I restart MantidPlot
> - When I try to load the saved project, Mantid opens the Load dialog but not the workspace.
>Have you seen this?

No. I shall take a look at this. 

>  I see that in the directory where I am saving the project (i.e. where I am saving the *.mantid file) it also saves the nexus file as a separate file. Is this what it should do?

That is correct and this is how it should work. It saves all workspaces to the project folder.

**Comment by raquelalvarezbanos** [comment]
Tried the following (Ubuntu):

- Plots belonging to multiple workspaces: when restarting Mantid and opening the previously saved project I only get the "Load" dialog.
- Workspace groups: the same happens
- Complicated interfaces: the same again...

I can show you what I am doing when you get back.

**Comment by raquelalvarezbanos** [comment]
Yes, it works. It was me not loading the project properly. I've tested:

- Multiple workspaces from different datasets
- Plots
- Workspace groups
- Spectrum viewer
- Slice viewer

I still have to review the code.

**Comment by NickDraper** [comment]
Last change was rst only builds cancelled to save resources, previous builds passed

**Comment by NickDraper** [comment]
Loaded and saved various partial projects successfully on windows.

So:
- Mac - developed on
- Linux - tested by Raquel
- Windows - Tested by me

I think it is good to go.
:shipit:

**Comment by martyngigg** [comment]
Not waiting for system tests as these were GUI-only changes.

**Pull request merged**
