### PR TITLE
Replace uses of deprecated `CheckWorkspacesMatch` with `CompareWorkspaces`

### LINKED ISSUE #17704: Replace  `CheckWorkspacesMatch` calls with `CompareWorkspaces` .
Replace the calls to deprecated `CheckWorkspacesMatch` algorithm to `CompareWorkspaces`.

### PR DESCRIPTION
**Pull request by gvardany**
See the title.

**To test:**

1. Make sure I have not missed any other appropriate occurrence of `CheckWorkspacesMatch`.
2. Pick a system test that uses built-in validation with `validate` method. Introduce a change in the test, such that it should fail. Run and make sure it fails.

Fixes #17704.

Does not need to be in the release notes.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by PranavBahuguna** [comment]
For  `PolarizationCorrectionTest::test_run_PNR_unity()`, there is still one instance of `CheckWorkspacesMatch` being used on line 207.

Other than that, I cannot find any other instances.

**Comment by gvardany** [comment]
Good catch 👍 , fixed.

**Comment by PranavBahuguna** [comment]
Looks good, :shipit: once checks pass.

**Comment by gvardany** [comment]
Do not merge yet, need to check something else.

**Comment by gvardany** [comment]
@PranavBahuguna Could you check also the 2nd point?

**Comment by martyngigg** [comment]
I've moved this back to 3.10 as it's really a maintenance thing.

**Comment by martyngigg** [comment]
@gvardany Are there still things that need to be done here?

**Comment by gvardany** [comment]
Not really, just would be nice to double check the 2nd point in *to test*. I think the change in the system test base class is rather critical.

**Comment by martyngigg** [comment]
@PranavBahuguna Could you pick up on @gvardany final testing point here?

**Comment by PranavBahuguna** [comment]
I've checked the last testing point now - it produces the expected results as described.

**Pull request merged**
