### PR TITLE
New algorithm DirectILLTubeBackground

### LINKED ISSUE #22224: DirectILLCollectData: background subtraction doesn't work for IN5
The background counts for the pixels of IN5 are so small that the flat background is always zero. When the pixels get summed in `DirectILLReduction`, however, the background becomes significant. There should be a way to deal with the backgrounds, nevertheless, for example calculating the background for pixels grouped per tube.

### PR DESCRIPTION
**Pull request by soininen**
**Description of work.**

This PR introduces a new algorithm `DirectILLTubeBackground` which calculates a polynomial background over individual components such as PSD tubes of instruments like IN5 at ILL.

**Report to:** [nobody].

**To test:**

The following script uses some unit test data to calculate the backgrounds for a IN5 workspace:
```python
ws = Load('ILL/IN5/104007.nxs')
ws = ExtractMonitors(ws, DetectorWorkspace='yes-please', StoreInADS=False)
# The instrument definitions directory should be in the data search directories
mask = LoadMask('IN5',  'masks/IN5_Mask.xml')
epps = FindEPP(ws)
bkg = DirectILLTubeBackground(ws, EPPWorkspace=epps,
    DiagnosticsWorkspace=mask,  # optional
    #Components='tube_1, tube_222',  # Uncomment to overwrite the IPF
    #Degree=0 ,
    #NonBkgRegionInSigmas=6.
)
```

You can visualize the backgrounds by plotting any of the bins of the `'bkg'` workspace.

Try out changing the property values. Can you break the algorithm? If you know any other instrument whose data files could be processed by `DirectILLTubeBackground`, please try them out as well.

Fixes #22224. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by mantid-roman** [comment]
I have this error:
```
RuntimeError: Could not find 'components-for-backgrounds' in instrument parameters file. Component names must be given using the 'Components' property.
```

**Comment by soininen** [comment]
@mantid-roman Could you wipe the instrument cache (in `~/.mantid/instruments` on Linux systems) and try again? I think Mantid could be picking up wrong the IPFs, not the ones updated in this PR.

**Comment by mantid-roman** [comment]
How can you judge the quality of the fits? How do you decide what polynomial degree to use?

**Comment by soininen** [comment]
@mantid-roman That is a good question. I have a feeling that most users will be happy with the default 0th degree; I'm unsure if there is any reason to ever go above 2nd degree.

For some additional validation I have used the following script:
```python
import numpy as np
DirectILLCollectData('ILL/IN5/104007.nxs', OutputWorkspace='ws', OutputEPPWorkspace='epps')
ws = mtd['ws']
epps = mtd['epps']

# Build a comparison workspace
nBins = ws.blocksize()
peakPositions = np.array(epps.column('PeakCentre'))
peakSigmas = np.array(epps.column('Sigma'))
exclusionBegins = peakPositions - peakSigmas * 6.  # Default width in DirectILLTubeBackground
exclusionEnds = peakPositions + peakSigmas * 6.
left = Integration(ws, RangeUpperList=exclusionBegins, StoreInADS=False)
right = Integration(ws, RangeLowerList=exclusionEnds, StoreInADS=False)
# Manually average left and right 
mean = left + right
binBegins = np.empty(len(exclusionBegins))
binEnds = np.empty(len(exclusionEnds))
for i in range(mean.getNumberHistograms()):
    binBegins[i] = ws.binIndexOf(exclusionBegins[i])
    binEnds[i] = ws.binIndexOf(exclusionEnds[i])
    Ys = mean.dataY(i)
    Ys /= nBins - (binEnds[i] - binBegins[i])
# Average 'mean' over tubes
nSpectra = mean.getNumberHistograms()
nTubes = 384
nPixelsInTube = nSpectra / nTubes
Ys = mean.extractY()
means = np.empty(nSpectra)
for i in range(nTubes):
    begin = i * nPixelsInTube
    end = begin + nPixelsInTube
    means[begin:end] = np.mean(Ys[begin:end, 0])
Xs = np.tile(mean.readX(0), nSpectra)
mean_mean = CreateWorkspace(Xs, means, NSpec=nSpectra, ParentWorkspace=ws)

# Run the real thing
bkgs = DirectILLTubeBackground(ws, epps)
```

The zeroth degree fit stored in `bkgs` should correspond to the tube averages in `mean_mean`. For higher degree polynomials, I've been judging the background by eye between `bkgs` and `mean`, but it is not really quantitative, and plotting the large datasets is painful.

For higher-degree background fits one would want to apply a mask because of the dead pixels at the tube ends. This can be done the following way:
```python
DirectILLCollectData('ILL/IN5/104007.nxs', OutputWorkspace='ws', OutputEPPWorkspace='epps')
DirectILLDiagnostics('ws', OutputWorkspace='mask')
bkgs_higher_degree = DirectILLTubeBackground('ws', 'epps', Degree=2, DiagnosticsWorkspace='mask')
```

For a really quantitative comparison, one would probably want to fill the input workspace with some known numbers. Maybe you have any good ideas?

**Review by mantid-roman — APPROVED** [review]

**Comment by martyngigg** [comment]
@soininen It looks like the system test has detected an invalid file for `IN4_Parameters.xml`

**Pull request merged**
