### PR TITLE
Fix inheritance on ISIS indirect inelastic system tests

### LINKED ISSUE #30574: Indirect System tests not running
### Description
It appears that some of the critical indirect system tests are not being run when I look at the `rhel + system tests` builds. The ones I have identified to not be running are:
- ISISIndirectInelastic
- ISISIndirectBayesTest

There might be other tests not being run. This needs to be investigated and fixed.

For reference, it appears ISISDirectInelastic **is** running as expected.

### PR DESCRIPTION
**Pull request by Harrietbrown**
**Description of work.**

This PR fixes some system tests that are not running in rhel + system tests

**To test:**

Check Jenkins rhel + system tests is running ISISIndirectInelastic and ISISIndirectBayesTest

Fixes #30574

*This does not require release notes* because **It is a change to system tests**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by robertapplin — CHANGES_REQUESTED** [review]
Thanks for taking a look at this. It looks like some of the system tests now appear to be running, good job! However there are still some tests in ISISIndirectInelastic not being run. For example the tests derived from the `ISISIndirectInelasticResolution` class. There might be others as well.

**Comment by robertapplin** [comment]
Do we know what was causing the test failures?

**Comment by Harrietbrown** [comment]
There were some outdated refference files

**Review by robertapplin — APPROVED** [review]
Sorry, what I meant was whether we know what changes have been made so that the reference files are now different. Elwin, Msd, Iqt, IqtFit seem to be working fine however so I am happy with this change to the reference files

**Comment by Harrietbrown** [comment]
I compared the two outputs, the difference could only be seen by taking the difference, (>0.1%) I don;t know how long these tests have not been running, if they ever did run at all. so I can;t say what the difference is,

**Comment by robertapplin** [comment]
I think the problem was introduced in this commit 11 months ago https://github.com/mantidproject/mantid/commit/8c49d8b3850d91eaf471fc40c24ffa5d8449820a . For Elwin I think this could have caused a change #29549

**Pull request merged**
