### PR TITLE
Enable component-specific corrections in DetectorEfficiencyCorUser

### LINKED ISSUE #17352: `DetectorEfficiencyCorUser`: component specific correction & improved formula evaluation
Currently, the `DetectorEfficiencyCorUser` algorithm uses a single efficiency correction formula for the entire instrument. However, instruments such as IN4 at ILL would need the formula to be component specific. Also, the correction formula currently depends only on the incident energy. This should be extended to other variables, such as the angle between the detector axis and neutron's flight path.

### PR DESCRIPTION
**Pull request by soininen**
This PR makes the [`DetectorEfficiencyCorUser`](http://docs.mantidproject.org/nightly/algorithms/DetectorEfficiencyCorUser-v1.html) algorithm to recursively check the efficiency correction formula for each detector separately enabling component-specific formulas. This is useful for instrument such as IN4 at ILL where there are different types of detectors present.

**To test:**

Replace the IN4_Parameters.xml file with this one:
```
<?xml version="1.0" encoding="UTF-8" ?>
<parameter-file instrument="IN4" valid-from="2012-10-01T00:00:00">

	<component-link name="IN4">

		<parameter name="deltaE-mode" type="string">
			<value val="direct" />
		</parameter>

		<!-- Distance between sample and equatorial line of the detector. Mandatory 
			if you want to correct the flight paths. -->
		<parameter name="l2" type="string">
			<value val="2.0" />
		</parameter>

	</component-link>

	<component-link name="wide_angle">
		<!-- formula for Detector efficiency calculation. Algorithm: DetectorEfficiencyCorUser 
			See http://muparser.sourceforge.net/mup_features.html#idDef2 for available 
			operators -->
		<parameter name="formula_eff" type="string">
			<value val="0.951*exp(-0.0887/sqrt(e))*(1-exp(-5.597/sqrt(e)))" />
		</parameter>
	</component-link>

	<component-link name="rosace">
		<!-- formula for Detector efficiency calculation. Algorithm: DetectorEfficiencyCorUser 
			See http://muparser.sourceforge.net/mup_features.html#idDef2 for available 
			operators -->
		<parameter name="formula_eff" type="string">
			<value val="1-exp(-6.1343/sqrt(e))" />
		</parameter>
	</component-link>

</parameter-file>
```
Set log level to debug, change the `<mantid build directory>` to whatever pleases you in the script below, and run:
```python
# Vanadium reduction
Load(
    Filename='<mantid build directory>/ExternalData/Testing/Data/UnitTest/ILL/IN4/084446.nxs',
    OutputWorkspace='raw',
)

# The correction formula is not defined for the monitor.
ExtractMonitors(
    InputWorkspace='raw',
    DetectorWorkspace='raw',
)

# ILL specific fix for TOF axis.
CorrectTOFAxis(
    InputWorkspace='raw',
    OutputWorkspace='raw',
    ElasticBinIndex=175,
    L2=2.0
)

ConvertUnits(
    InputWorkspace='raw',
    OutputWorkspace='inDeltaE',
    Target='DeltaE',
    EMode='Direct'
)

DetectorEfficiencyCorUser(
    InputWorkspace='inDeltaE',
    OutputWorkspace='corrected'
)
```

Observe in the log output, that the two formulas in the new IPF are used for the 'wide_angle' detectors (workspace indices 0-299) and 'rosace' (300-396).

Fixes #17352.

**Release Notes** 

Release notes were updated accordingly.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [x] Are the unit tests small and test the class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] Do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
Hmm, I just ran the code and got this, the formulae look the same

```
Found formula for workspace index 0: 0.951*exp(-0.0887/sqrt(e))*(1.0-exp(-5.597/sqrt(e)))
Found formula for workspace index 347: 0.951*exp(-0.0887/sqrt(e))*(1.0-exp(-5.597/sqrt(e)))
Found formula for workspace index 299: 0.951*exp(-0.0887/sqrt(e))*(1.0-exp(-5.597/sqrt(e)))
```

**Comment by NickDraper** [comment]
Then I spotted that this PR does not include a change to the IN4 parameter file, and looking at the one on my PC, it only has one formula.

I added this 
``` xml
	<component-link name="rosace">

		
		<!-- formula for Detector efficiency calculation. Algorithm: DetectorEfficiencyCorUser 
			See http://muparser.sourceforge.net/mup_features.html#idDef2 for available 
			operators -->
		<parameter name="formula_eff" type="string">
			<value val="999999999999*e" />
		</parameter>

	</component-link>
```

and then the log entries looked better

```
Found formula for workspace index 20: 0.951*exp(-0.0887/sqrt(e))*(1.0-exp(-5.597/sqrt(e)))
Found formula for workspace index 344: 999999999999*e
```

**Comment by NickDraper** [comment]
The code change in this PR is good, but be aware that at present this will not change anything for IN$ without a change to the parameters file.

I've not included my testing change into this PR.

**Review by NickDraper — APPROVED** [review]

**Comment by soininen** [comment]
@NickDraper: I'll add a new efficiency correction formula for IN4 now that this PR is merged, see issue #20459. Just wanted to keep the changes to this algorithm and some random IDFs separate.

**Pull request merged**
