### PR TITLE
Fix plot script generation for Bin plots

### LINKED ISSUE #30139: Workbench Plot - Script to file produces different results to plotting bins
**Original reporter:** ISIS/Diego (SANS)

### Expected behavior
Plotting from "Show Data" should produce the same result as a plot script 

### Actual behavior
The results are vastly different

### Steps to reproduce the behavior
- Open the following file: [example.nxs.zip](https://github.com/mantidproject/mantid/files/5672809/example.nxs.zip)
- Click Show Data
- In `Y Values` scroll across to a column with data (e.g. 74)
- Right click the column and do Plot Bins + Errors, this appears to be correct
- Save Script to File / Script to Clipboard
- Run opened script , the resulting values are completely incorrect causing the various axes to also overlay incorrectly too.

image

### Platforms affected
All (tested on RHEL / Windows)

### PR DESCRIPTION
**Pull request by StephenSmith25**
**Description of work.**
This PR fixes the plot script generation for figures constructed from a particular bin.

**To test:**
- Load some data
- Right-click and click show data
- Click on a column of the data
- Right click and do plot bin (with and without errors)
- Generate the plot script
- **You'll have to close the old figure as we recreate the script with the same `num` argument, meaning the figure from the script will overwrite the existing one. This is how the script generation has always functioned, so wondering whether we should change it..**
- Run the script
- Open the figure you created directly from the figure
- Compare the two, they should match
- Check existing functionality works

Fixes #30139 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Harrietbrown** [comment]
There is an issue I have found here when you combine a plot of a single bin (as in your example) and a spectra overplotted. the coppied script only plots the bin, I expect this is an unlikly senario but could it be addressed?

**Comment by StephenSmith25** [comment]
Thanks for testing it. Could you help me out on the steps to reproduce this, at the moment I’m doing this:

1) Show data and right clicking a column of the data and plotting it
2) Right clicking the workspace and clicking overplot spectra

I'm not sure this produces a valid plot as the axis on the plots are not compatible (as one is in time and the other is spectrum). Or are you referring to something else?

**Comment by Harrietbrown** [comment]
Those steps are right, the plot can be created without raising an error.

**Comment by StephenSmith25** [comment]
Do you think there should be a warning if a user tries to overplot on a plot with a differing axis type?

**Comment by Harrietbrown** [comment]
Yes, at least something in the log, We probably don't need the project recovery ro work for them, at least not within the scope of this PR but a warning would be good

**Comment by StephenSmith25** [comment]
I think this feels out of the scope here, as this is just generating the plot scripts. That issue is with the 'overplotting' functionality, which depends on a 'can_overplot' method to determine whether it is possible to overplot a spectrum plot onto the current figure. Can I create a new issue for this?

**Comment by Harrietbrown** [comment]
Create an issue for the overplotting problem. This PR is good to go

**Review by Harrietbrown — APPROVED** [review]
The script generated plots are identical to those generated through the data interface. Good Job.

**Pull request merged**
