### PR TITLE
Speed up workbench preview plots

### LINKED ISSUE #28194: Workbench is a bit slow
This is initially just an investigation. 

Indirect has been slow.

James (moun) has also said workbench is slow:
```
Workbench is really slow with anything using the ADS. For example the Muon Analysis interface when loading more than one run at a time. (ALC is less affected) Also as an example my script “Create2DALCMap” (from the script muon/Create2DALCMap.py in the Repository). Run it with parameters:
                FirstFile=//hifi/data/hifi00166860.nxs
                NumberOfRuns=121
                StartTime=0.1
                EndTime=10
                NBunch=20
                LogSelection=Field_Main_Target
                OutputWorkspace=ChooseAWorkspaceName
On Plot it takes 37.42 seconds (my desktop PC, mostly dominated by loading the files). On Workbench it takes 4m 17s: nearly 7 times slower! Workbench with the Progress bar hidden: 4m 21.3s (the same within error).
```

### PR DESCRIPTION
**Pull request by Matthew-Andrew**
**Description of work.**

On workbench if you had any of the C++ interfaces open changes the ADS could take a long time. This was at least partially becuase preview plot was replotting far more than neccecary. This updates the ADSwatchers in preview plot so that it only replots if a relevant workspace changes.

**To test:**
See the discussion in #28194 for how to test this issue.

Fixes #28194  

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — CHANGES_REQUESTED** [review]
For the ILL example provided by @gvardany in the associated issue the reduction time has improved by ~80% (38s vs 6s).

The nice thing about these changes it that they will help anything that currently uses a preview plot.

I think we should mention this in the MSG release notes as it's potentially a deal-breaker for people using Workbench.

**Comment by Mantid-Matthew** [comment]
I'm just about to tidy up all the release notes for MSG during this issue #28238 . So I'll add a bit about this there to avoid conflicting with myself.

**Review by martyngigg — APPROVED** [review]

**Comment by martyngigg** [comment]
@gvardany This should improve things a lot for you.

**Comment by gvardany** [comment]
For me it was ~17 sec through interface vs ~3.5 sec as a script (both on workbench). While it did improve massively, there must be other problems still. Btw, I am getting Qt errors on the terminal when clicking Run on the interface, but this is probably unrelated:
```
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
```

**Comment by martyngigg** [comment]
I agree I don't think this solves the whole problem but I think it is as much as we can do safely for this release.

@Mantid-Matthew Have you seen those warnings? I think they are unrelated but it would be good to clean them up for 5.1.

**Comment by martyngigg** [comment]
@Mantid-Matthew Could you open a further issue for next release to investigate the differnce in speed between the interface and same thing in a script?

**Comment by Mantid-Matthew** [comment]
I have seen those warnings and once spent a while trying to track them down. I think I eventually found they were coming out of some Qt code rather than our code at which point I stopped.

I agree there is still some speed issues with the interface on workbench. Profiling and working out what is going on here is my first issue next release.

**Pull request merged**
