### PR TITLE
Ensure unit tests pass when only workbench and qt5 is built

### LINKED ISSUE #29390: Ensure UnitTests pass when only workbench and Qt5 is built
This is part of the umbrella issue of: #28650 

Need to be able to build mantid with `-DENABLE_MANTIDPLOT=OFF` in cmake.

Known tests to fail and requiring fixes are as follows:
- [x] python.scripts.pythonTSVTest.pythonTSVTest
- [x] python.EngineeringDiffraction.test_settings_presenter.test_settings_presenter
- [x] python.EngineeringDiffraction.test_calib_presenter.test_calib_presenter
- [x] python.EngineeringDiffraction.test_data_presenter.test_data_presenter
- [x] python.EngineeringDiffraction.test_focus_presenter.test_focus_presenter

### PR DESCRIPTION
**Pull request by Pasarus**
**Description of work.**
Built mantid without Qt4 and MantidPlot using `-DENABLE_MANTIDPLOT=OFF` in CMake. Run tests and made sure they all passed.

**To test:**
Just code review

Fixes #29390  

Behind the scenes maintenance, not user facing.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by AndreiSavici — CHANGES_REQUESTED** [review]
I run the test on Ubuntu 20.04. The `PythonTOFTOFReduction.TOFTOFGUITest.TOFTOFGUITest` has the same issue. add the lines in CMakeLists.txt to scripts/test/TOFTOF/CMakeLists.txt as well

**Comment by AndreiSavici** [comment]
**This is just a note, so feel free to ignore**
Even with the suggested change, the following tests are failing on Ubuntu 20.04:
```
99% tests passed, 16 tests failed out of 2284

Total Test time (real) = 1344.41 sec

The following tests FAILED:
	1852 - MantidQtWidgetsCommonTestQt5_FindFilesThreadPoolManagerTest (Failed)
	1853 - MantidQtWidgetsCommonTestQt5_FindFilesWorkerTest (Failed)
	1870 - MantidQtWidgetsCommonTestQt5_SipTest (Failed)
	1925 - mantidqt_qt5.test_execution.test_execution (Failed)
	1930 - mantidqt_qt5.test_multifileinterpreter_view.test_multifileinterpreter_view (Failed)
	1932 - mantidqt_qt5.test_codeeditor_tab_view.test_codeeditor_tab_view (Failed)
	1935 - mantidqt_qt5.test_instrumentview_view.test_instrumentview_view (Failed)
	1943 - mantidqt_qt5.test_samplelogs_view.test_samplelogs_view (Failed)
	1969 - mantidqt_qt5.test_matrixworkspacedisplay_view.test_matrixworkspacedisplay_view (Failed)
	1976 - mantidqt_qt5.test_tableworkspacedisplay_view.test_tableworkspacedisplay_view (Failed)
	2035 - workbench.test_settings_view.test_settings_view (Failed)
	2137 - python.MuonQt5.loadrun_presenter_single_file_test.loadrun_presenter_single_file_test (Failed)
	2138 - python.MuonQt5.loadrun_presenter_multiple_file_test.loadrun_presenter_multiple_file_test (Failed)
	2141 - python.MuonQt5.loadfile_presenter_multiple_file_test.loadfile_presenter_multiple_file_test (Failed)
	2143 - python.MuonQt5.loadrun_presenter_increment_decrement_test.loadrun_presenter_increment_decrement_test (Failed)
	2145 - python.MuonQt5.loadwidget_presenter_test.loadwidget_presenter_test (Failed)

```
Might be something different

**Comment by Pasarus** [comment]
I think I should make a Ubuntu 20.04 VM and build mantid there, to fix these issues, will update this PR when I have all of them building properly.

**Comment by AndreiSavici** [comment]
Many of the failing tests seem te be related to failure of closing widgets

**Comment by Pasarus** [comment]
I ran it on an ubuntu 20.04 VM and I get 22 failures:

```
	1416 - CurveFittingTest_FitPowderDiffPeaksTest (Failed)
	1852 - MantidQtWidgetsCommonTestQt5_FindFilesThreadPoolManagerTest (Failed)
	1853 - MantidQtWidgetsCommonTestQt5_FindFilesWorkerTest (Failed)
	1870 - MantidQtWidgetsCommonTestQt5_SipTest (Failed)
	1912 - mantidqt_qt5.test_fitpropertybrowser.test_fitpropertybrowser (Failed)
	1925 - mantidqt_qt5.test_execution.test_execution (Failed)
	1930 - mantidqt_qt5.test_multifileinterpreter_view.test_multifileinterpreter_view (Failed)
	1932 - mantidqt_qt5.test_codeeditor_tab_view.test_codeeditor_tab_view (Failed)
	1935 - mantidqt_qt5.test_instrumentview_view.test_instrumentview_view (Failed)
	1938 - mantidqt_qt5.test_curvestabwidgetpresenter.test_curvestabwidgetpresenter (Failed)
	1940 - mantidqt_qt5.test_apply_all_properties.test_apply_all_properties (Failed)
	1942 - mantidqt_qt5.test_plotconfigdialogpresenter.test_plotconfigdialogpresenter (Failed)
	1943 - mantidqt_qt5.test_samplelogs_view.test_samplelogs_view (Failed)
	1969 - mantidqt_qt5.test_matrixworkspacedisplay_view.test_matrixworkspacedisplay_view (Failed)
	1976 - mantidqt_qt5.test_tableworkspacedisplay_view.test_tableworkspacedisplay_view (Failed)
	2035 - workbench.test_settings_view.test_settings_view (Failed)
	2137 - python.MuonQt5.loadrun_presenter_single_file_test.loadrun_presenter_single_file_test (Failed)
	2138 - python.MuonQt5.loadrun_presenter_multiple_file_test.loadrun_presenter_multiple_file_test (Failed)
	2141 - python.MuonQt5.loadfile_presenter_multiple_file_test.loadfile_presenter_multiple_file_test (Failed)
	2143 - python.MuonQt5.loadrun_presenter_increment_decrement_test.loadrun_presenter_increment_decrement_test (Failed)
	2145 - python.MuonQt5.loadwidget_presenter_test.loadwidget_presenter_test (Failed)
	2263 - PythonTOFTOFReduction.TOFTOFGUITest.TOFTOFGUITest (Failed)

```

**Comment by AndreiSavici** [comment]
Modifying the scripts/test/TOFTOF/CMakeLists.txt as suggested will fix the last test

**Comment by AndreiSavici** [comment]
Here is a weird observation, that might help point out where the error is. Running the `mantidqt_qt5.test_codeeditor_tab_view.test_codeeditor_tab_view` test yields
```
Traceback (most recent call last):
  File "/home/3y9/Mantid/mantid/qt/python/mantidqt/widgets/codeeditor/tab_widget/test/test_codeeditor_tab_view.py", line 51, in test_deleted_on_close
    self.assert_widget_not_present(CodeEditorTabWidget.__name__)
  File "/home/3y9/Mantid/mantid/qt/python/mantidqt/utils/qt/testing/qt_widget_finder.py", line 34, in assert_widget_not_present
    self.assertEqual(0, len(all),
AssertionError: 0 != 1 : Widgets with name 'CodeEditorTabWidget' are present in the QApplication. Something has not been deleted: [<mantidqt.widgets.codeeditor.tab_widget.codeeditor_tab_view.CodeEditorTabWidget object at 0x7f6dcba4f1f0>]
```
I've noticed that the other test passed, so I've replicated the first test. That one passes as well. So if I comment the assert statements in the first test, but I keep them in the clone, the test is OK

```python
@start_qapplication
class CodeEditorTabWidgetTest(unittest.TestCase, QtWidgetFinder, QtAssertionsHelper):

    def test_deleted_on_close(self):
        mock_mfp = MockMultiFileInterpreter()
        view = CodeEditorTabWidget(mock_mfp)
        self.assert_widget_created()

        view.close()

        QApplication.processEvents()
        #self.assert_widget_not_present(CodeEditorTabWidget.__name__)

        # closing our local mock should leave the QApplication without any widgets
        mock_mfp.close()
        QApplication.processEvents()
        #self.assert_no_toplevel_widgets()

    def test_deleted_on_close1(self):
        mock_mfp = MockMultiFileInterpreter()
        view = CodeEditorTabWidget(mock_mfp)
        self.assert_widget_created()

        view.close()

        QApplication.processEvents()
        self.assert_widget_not_present(CodeEditorTabWidget.__name__)

        # closing our local mock should leave the QApplication without any widgets
        mock_mfp.close()
        QApplication.processEvents()
        self.assert_no_toplevel_widgets()
```

**Comment by Pasarus** [comment]
Please do not review yet I have a fair few more tests that need to be looked at

**Comment by Pasarus** [comment]
1416 - CurveFittingTest_FitPowderDiffPeaksTest (Failed)
	1858 - MantidQtWidgetsCommonTestQt5_InterfaceManagerTest (Failed)
	1893 - mantidqt_qt5.test_algorithm_dialog.test_algorithm_dialog (Failed)
	1922 - mantidqt_qt5.test_algorithmselector.test_algorithmselector (Failed)
	2005 - MantidQtScientificInterfacesTestQt5_DecoderTest (Failed)
	2024 - workbench.test_plothelppages.test_plothelppages (Failed)
	2026 - workbench.test_exception_handler.test_exception_handler (Failed)
	2263 - PythonTOFTOFReduction.TOFTOFGUITest.TOFTOFGUITest (Failed)

Remaining failed tests (TOFTOF has just not been fixed yet, will get around to it.)

**Comment by Pasarus** [comment]
@AndreiSavici Would you be able to see if all tests pass on your Ubuntu 20.04 build?

**Review by AndreiSavici — APPROVED** [review]
Works in Ubuntu 20.04. All tests pass. When I run all tests, `workbench.test_projectrecovery.test_projectrecovery` failed, so I run just that test and it passes. We must keep an eye on that

**Pull request merged**
