### PR TITLE
Minor change: Deprecated TOFTOFMergeRuns algorithm

### LINKED ISSUE #20648: Deprecate TOFTOFMergeRuns
The TOFTOF data reduction workflow has been changed to use MergeRuns (PR #20635) and TOFTOFMergeRuns  can be deprecated in 3.12 and removed in one of the later releases.

The following should be done:
1. Warning in the documentation, that algorithm is deprecated and MergeRuns should be used instead.
2. The same warning in the `PyExec` method.
3. The MergeRuns unit test that uses TOFTOFMergeRuns algorithm should be updated.

milestone: 3.12

### PR DESCRIPTION
**Pull request by JoachimCoenen**
**Description of work.**

Deprecated TOFTOFMergeRuns algorithm

**To test:**

 TOFTOFMergeRuns algorithm appears as deprecated in docs

Fixes #20648. 

Does this update require release notes?
- [ ] Yes
- [ ] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by reimundILL** [comment]
`TOFTOFMergeRuns` calls `MergeRuns` and customizes several `SampleLogs`.
It would be good to investigate the direct use of `MergeRuns` for your data:

Taking the usage example and running `MergeRuns` with no options, data match  (I used `CompareWorkspaces`, but attention, `CompareWorkspaces` crashes Mantid when enabling `CheckSample` (it's worth to open an issue)).

`SampleLogs` look different as expected:

`TOFTOFMergeRuns`:

mr1

`MergeRuns`: 

mr2

Note that the `temperature` field lost its unit as well as duration (!).
But you can see the `Mean` value in the `Log Statistics`. I think this applies to monitor counts and duration as well.
Further, `run_start` and `run_end` (string) as well as `run_number` differ.
In my opinion, `MergeRuns` should not concatenate strings but should do like `TOFTOFMergeRuns` and return a list of strings.

Is this enough motivation to keep `TOFTOFMergeRuns`? I would opt to fix `MergeRuns` units and string lists and do the `start_time`, `end_time` string modification where needed separately or even add this behaviour to `MergeRuns`.

Some general remarks concerning the documentation: `TOFTOFMergeRuns` second table has an empty second column. `MergeRuns` tool tips do not show the full documentation.

**Review by vreimund — APPROVED** [review]
Deprecating `TOFTOFMergeRuns` is ok

**Comment by ianbush** [comment]
For a clearer warning on the algorithm you can do something like shown here:
https://raw.githubusercontent.com/mantidproject/mantid/master/docs/source/algorithms/VesuvioDiffractionReduction-v1.rst - though if you are happy with how this appears it is fine as is.

Can you add a note to the release notes saying this is deprecated? Also please set the labels and milestones, particularly as we are close to the code freeze.

**Comment by JoachimCoenen** [comment]
I don't have the permissions to set any labels or milestones. Can you (or someone else) do that for me please?

**Comment by ianbush** [comment]
Ah, I forgot you could not add them, I've added them on (assuming for this release). I'll merge this once the doc tests give the :+1: .

**Comment by mganeva** [comment]
@reimundILL We have replaced TOFTOFMergeRuns with the MergeRuns algorithm in our data reduction workflow about a year ago. TOFTOFMergeRuns is not used any more.

**Pull request merged**
