### PR TITLE
Conda-buildscript shanum fixes for mambaforge download

### PR DESCRIPTION
**Pull request by Pasarus**
**Description of work.**
After mambaforge's version progressed beyond 4.11.0 it exposed an issue with our URL for downloading.

**To test:**
Run the conda-buildscript on one OS locally using the correct script for your os:

- `mantid_source/buildconfig/Jenkins/Conda/conda-buildscript ~/work_dir linux-ci`
- `mantid_source/buildconfig/Jenkins/Conda/conda-buildscript ~/work_dir osx`
- `mantid_source/buildconfig/Jenkins/Conda/conda-buildscript ~/work_dir win`

If it runs for 1 minute then you cancel it and it should be fine.

*There is no associated issue.*

*This does not require release notes* because **Not user-facing**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — CHANGES_REQUESTED** [review]
So this doesn't quite work properly for me on Mac.

On Mac if I run `uname` the I get `Darwin` and not `MacOSX` so the download URL for macOS is invalid and the sha checksum fails. It looks like Conda just hardcodes `MacOSX` in their [creation script](https://github.com/conda-forge/miniforge/blob/30dffc03ac395f417dbdffe1a5c3355cfbda9880/build_miniforge_osx.sh#L11) rather than pulling it from a command.

**Comment by Pasarus** [comment]
Ah it used to work as they provided a `Darwin` named MacOS version for `latest` package and no version number, but not for packages with version numbers. I will add a hardcode for each platform now. Good catch! Fixed.

**Review by martyngigg — APPROVED** [review]
Confirmed this now works as expected.

**Comment by Pasarus** [comment]
@mantidproject/gatekeepers Could we get this merged? It fixes something, that stops us deploying our nightly conda builds

**Pull request merged**
