### PR TITLE
fix crash on convFit when showing full function

### LINKED ISSUE #31169: IndirectDataAnalysis crashes when showing full function on InmutableConvolutionFunction
In the indirect data analysis convfit tab if you set the function as one of the InmutableConvolutionFunction and then change it to show the full function it causes the interface to crash.

### PR DESCRIPTION
**Pull request by Harrietbrown**
**Description of work.**

This PR fixes a bug that caused a crash when you set the function as one of the InmutableConvolutionFunctions and then change it to show the full function.

**Report to:** Spencer Howells

**To test:**

1. Open Indirect data analysis
2. go to convtab
3. choose IsoRotDiff as the function
4. change to show full function and make sure it does not crash
5. try with DiffSphere and and DiffRotDiscreteCircle and amke sure they do not crash.

Fixes #31169

*This does not require release notes* because these functions were added in this release

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by SpencerHowells** [comment]
@Harrietbrown Could you put the Function menu in order please. Eg IsoRotDiff, ElasticIsoRotDiff, InelasticIsoRotDiff and the same for the others.

**Comment by Harrietbrown** [comment]
@SpencerHowells ElasticIsoRotDiff and InelasticIsoRotDiff are not currently in convfit, would you like them added? they havn't been mentioned before

**Comment by SpencerHowells** [comment]
@Harrietbrown Yes please

**Comment by Harrietbrown** [comment]
@SpencerHowells I'll make an issue to add them.

**Comment by martyngigg** [comment]
@DavidFair Would you still have time to review this or should be drop it to the pool?

**Comment by DavidFair** [comment]
Weird I can't reproduce it either? I've done a clean build which seemingly resolved the issue so I'm suspecting something left over from not building for 3 months

**Review by DavidFair — APPROVED** [review]
LGTM and fixes the crash locally, lets :shipit:

**Pull request merged**
