### PR TITLE
Fix Lambda min and Lambda max in old Reflectometry GUI

### LINKED ISSUE #15131: Fix LambdaMin and LambdaMax in the old Reflectometry GUI
This was reported by Mario. He spoke to Max and they agreed there is no reason why `+1` is added to `LambdaMin` and `-2` is subtracted from `LambdaMax` (see [here](https://github.com/mantidproject/mantid/blob/master/scripts/Interface/ui/reflectometer/refl_gui.py#L1055-L1058))

This is noted in the parameter files for INTER/CRIST/POLREF/SURF, so we should remove the corresponding comments from those files. See as an example `SURF_Parameters.xml`:

```
  <!-- In the old Reflectometry UI, LambdaMin's value has 1 added to it.
       In the new Reflectometry UI, this adjustment is NOT made. -->
  <parameter name="LambdaMin">
    <value val="0.5"/>
  </parameter>

  <!-- In the old Reflectometry UI, LambdaMax's value has 2 subtracted from it.
       In the new Reflectometry UI, this adjustment is NOT made. -->
  <parameter name="LambdaMax">
    <value val="7.0"/>
  </parameter>
```

Also, review [this](https://github.com/mantidproject/mantid/blob/master/scripts/Interface/ui/reflectometer/refl_gui.py#L792-L793) line and ensure it makes sense.

### PR DESCRIPTION
**Pull request by MattKing06**
**Code Review**
- Make sure that there is no more addition to the Wavelength min and max that are retrieved from the IDFs of the reflectometry instruments.
- Make sure the comments that mentioned the addition of constants are now removed
- Make sure all other code changes make sense and are clean.

**Tester** 
- Make sure that your managed data directory is able to use the data archive
- Open the reflectometry interface `Interfaces > Reflectometry > ISIS Reflectometry`
- Change the processing instrument to `SURF`
- Insert this information into the processing table:
- `Run(s):` 114150, `trans1:`114147
- Click `Process`
- Ensure that the `qmin_1` entry is populated with a value close to 0.048
- Ensure that the `qmax_1` entry is populated with a value close to 0.7
- Ensure that the `angle 1` entry is populated with a value of 1.5

**Release Notes** [here](http://www.mantidproject.org/Release_Notes_3_7_Reflectometry#ISIS_Reflectometry)

Fixes #15131

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
Works as described: `qmin1` and `qmax1` are populated according to `Q = 4 * pi / lambda * sin(theta)`, and `lambda` values used are those read from the parameter file (addition constants were removed). Please @MattKing06 don't forget to update the release notes.

**Comment by MattKing06** [comment]
@raquelalvarezbanos I have added the fix to release notes now, the link to which can be found in the PR description

**Comment by raquelalvarezbanos** [comment]
Thanks!

:shipit:

**Comment by FedeMPouzols** [comment]
Looks good. Could the testing steps given in this PR be integrated as a system test or similar? If so, I'd suggest adding as a regression test, to keep this fix in good shape from now onwards.
@raquelalvarezbanos , @MattKing06 : note that for these older PRs (before you get the checklist as first automatic comment) you don't need to go through the :shipit: process.

**Pull request merged**
