### PR TITLE
Serialise the slice viewer

### LINKED ISSUE #16960: Fix issues with MultiLayer serialisation
This issue is a sub issue of #15602.

There are several known serialisation issues with MultiLayer windows. 

- [x] 1D plot with a single spectrum plotted appears on original monitor (yet was positioned on second).
- [x] 1D plot with resized window appears back at the expanded size, but the bottom of the plot is cut off.
- [x] 1D plot with an arrow makes the arrow disappear when reloaded.
- [x] Waterfall plot and styling retained, but the options on the top of the plot are lost.
- [x] 2D plot with log colour axis is not retained when the plot is reloaded
- [x] 2D plot with custom colour map does not restore the custom colour map.
- [x] 2D plot if colour bar is hidden it will reappear after being loaded.
- [x] 2D plot with arrow is reloaded, but is in wrong location

### LINKED ISSUE #16961: Serialise the slice viewer
This is a sub issue of #15602.

The state of the slice viewer is not saved at all when creating a Mantid project file. We should at least add the ability to save what file is currently being shown in the window and reopen it on project load.

### PR DESCRIPTION
**Pull request by samueljackson92**
This is a sub issue of #15602 .

This serialises the slice viewer to a Mantid project file. 

**To test:**
The state of the slice viewer should now be correctly saved to a Mantid project file. This should include things such as:
- The window geometry
- The workspace being viewed
- All of the options (selected dimensions, slice points, thickness rebinning parameters etc.)
- The state of the line viewer (and the line overlay)
- The state of the peaks viewer (and peak overlays)
- Anything else you'd expect that I may have missed. (Please be thorough and picky)

Fixes #16961 .

For release notes see #17109.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DimitarTasev** [comment]
Bugs:

- [ ] Doesn't load Axes state, seems to revert to default
- [ ] Doesn't load `Norm=`
- [ ] **If 1D line draw is open/clicked Mantid crashes**
- [ ] If multiple Slice Viewer windows are open only one of them is loaded back (it seems to be the Slice Viewer window that was open **first**)
- [ ] Corrupts an already open window of Slice Viewer from the same workspace IF the axes have been changed in the following workflow:
- load one workspace into project (I used MAR11060)
- open slice viewer
- change Axes
- save project to file 1
- save project to file 2
- load file 1
- original slice viewer will be corrupted, new slice viewer will not have the correct settings and will also be corrupted 

For the corrupting one it just seems to be loading the values for wrong axis, as their state was changed, but not loaded properly which is the first bug on the list, so it's loading the values correctly, but it hasn't set the correct axis view), and clicking zoom out fixes it

**Comment by samueljackson92** [comment]
@DimitarTasev I've addressed these as follows:
 - Axes state was being overwritten. This should now be fixed
 - The ```norm``` option seems to be working for me, as I demonstrated. If you can reproduce please show me how?
- Multiple slice viewer windows should now be loaded
- The issue is actually more to do with the workspace being overwritten and reset in the ADS and is not due to serialisation. We can maybe do something more intelligent here, but that is not for this issue.

**Comment by samueljackson92** [comment]
@DimitarTasev Ok. Try testing again. All should be fixed. (hopefully).

**Comment by DimitarTasev** [comment]
The issues were addressed, the slice viewer is now correctly saved and loaded. Code follows the coding standards and is of good quality :shipit:

**Pull request merged**
