### PR TITLE
 Add warning for 2D reduction with merge

### LINKED ISSUE #16709: Disable 2D reduction with Merge flag for ISIS SANS
Users are able to select a 2D reduction while also selecting a merged reduction, ie a reduction of the HAB and the LAB which is then merge. This is currently not supported in Mantid. 

Disable the 2D Reduction + Merge scenario.

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Fixes #16709.

A warning should be displayed when the user intends to perform a 2D reduction while having the merge mechanism selected.

**To test:**

The test files can be found here: \olympic\Babylon5\Scratch\Anton\Testing\16712_add_2d_reduction_with_merge_warning
1. Open the ISIS SANS GUI
2. Set the isntrument to SANS2DTUBES
3. Load the user file: USER_SANS2D_154E_2p4_4m_M3_Xpress_8mm_SampleChanger
4. Load the sample scatter file: SANS2D00034484.nxs
5. On the Reduction Settings Tab under Detector->Detector bank select "merged"
6. On the Run Numbers Tab press "Reduce 2D"
   - Confirm that a warning pops up regarding the the incompatibility of a 2D reduction with the merged flag

_Does not need to be in the release notes. Small change_

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by MattKing06** [comment]
After performing the functional text I see the warning when attempting to do a 2D reduction with merged detector banks and subsequently, the reduction will not be performed. :+1: 

Is there any way that a regression test can be put in place to make sure that a 2D reduction cannot be perfomed when detector banks are merged? Otherwise, this PR fixes the issue so we can :shipit:

**Comment by FedeMPouzols** [comment]
I guess that this is not anymore "In progress", or is there anything else to check before merging?

**Comment by AntonPiccardoSelg** [comment]
@MattKing06 The SANS logic and eventually the GUI are currently being rewritten, hence it is not really necessary to have a test for this. Also the changes are currently on the GUI side, where regresseion testing is quite difficult to perform. For this version of the SANS reduction I don't think that we add much value by providing a test.

**Comment by FedeMPouzols** [comment]
Yes, without a better separation of logic and GUI stuff it wouldn't be easy/feasible to add a regression test. As this adds a check in a method that was already being used to perform other checks it should be fine as far as reasonably possible.

**Pull request merged**
