### PR TITLE
Avoid division by 0 in MD error propagation

### LINKED ISSUE #16077: Error propagation incorrect in DivideMD, MultiplyMD
### Expected behavior
I have two MD histogram workspaces, `a` and `b`, and I want to look at `a/b`
If I have a point in my LHSWorkspace where the signal and the error squared are 0, I expect that the error squared is 0. 

### Actual behavior
In the current implementation I get a `NaN`

### Steps to reproduce the behavior
```
d=CreateMDHistoWorkspace(SignalInput='0', ErrorInput='0', Dimensionality=1, Extents='0,1', NumberOfBins='1', Names='d1', Units='x')
n=CreateMDHistoWorkspace(SignalInput='1', ErrorInput='0', Dimensionality=1, Extents='0,1', NumberOfBins='1', Names='d1', Units='x')
out=d/n
print out.getErrorSquaredArray()
```
### Platforms affected
All

### Notes:
 - The same behavior was fixed  for `Divide` algorithm in 2010. See comments in [Divide.cpp, lines 47-50] (https://github.com/mantidproject/mantid/blob/master/Framework/Algorithms/src/Divide.cpp#L47-L50)
 - MultiplyMD has the same problem

### PR DESCRIPTION
**Pull request by AndreiSavici**
Explicitly perform operations to avoid division by 0. 

**To test:**

Make sure all unit test, system tests, and doc tests that use multiplication and division of MD workspaces are OK.

The following script should yield `[0.]`. The same if you replace division by multiplication. (The current version returns NaN)

```
d=CreateMDHistoWorkspace(SignalInput='0', ErrorInput='0', Dimensionality=1, Extents='0,1', NumberOfBins='1', Names='d1', Units='x')
n=CreateMDHistoWorkspace(SignalInput='1', ErrorInput='0', Dimensionality=1, Extents='0,1', NumberOfBins='1', Names='d1', Units='x')
out=d/n
print out.getErrorSquaredArray()
```

Fixes #16077.

_Does not need to be in the release notes._

**NOTE** 
The branch is based on release-v3.7, but it should be merged in both the release and master

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by peterfpeterson** [comment]
The code does what it is supposed to, but I want to confirm that the equations are right.

**Comment by peterfpeterson** [comment]
I checked that the math is done correctly. :shipit:

**Comment by martyngigg** [comment]
Is the milestone correct? It says `3.7` but the target branch is `master`.

**Comment by martyngigg** [comment]
:+1:

**Pull request merged**
