### PR TITLE
Fix problem auto populating the full calibration setting on Engineering UI

### LINKED ISSUE #32163: Full calibration setting in engineering diffraction UI settings not auto-populated
The following setting should be auto-populated for a user opening the engineering diffraction UI for the first time but it seems to be blank for some users:

image

It's a bit hard to test because once you've manually filled it in, that path gets remembered so for people working on this regularly it's not so obvious

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

The logic to apply a default value to the Full Calibration path inside the Settings screen of the engineering diffraction UI wasn't working. The code was expecting None for the full calibration setting before applying the default. In the absence of a value for this setting the code was actually returning a blank string

Also adjusted the previous behaviour where if any of the settings were invalid they all got overwritten with a default set. The logic now applies the defaults per setting and leaves any other valid settings in place

**To test:**

1. Open up the mantidworkbench.ini file. This will be in your user area eg C:\Users\<fed id>\AppData\Roaming\mantidproject on Windows
2. Delete these settings from the [CustomInterfaces] section: 
- EngineeringDiffraction2\sort_ascending
- EngineeringDiffraction2\save_location
- EngineeringDiffraction2\primary_log
- EngineeringDiffraction2\full_calibration
- EngineeringDiffraction2\logs
- EngineeringDiffraction2\recalc_vanadium

...and put a nonsense value in for this one:
- EngineeringDiffraction2\default_peak (supposed to be a valid peak type)

2. Open up workbench
3. Open up the Engineering diffraction UI from the Interfaces, Diffraction menu
4. Open up the settings dialog
5. Observe that default values have been populated for the settings listed in step 1. In particular the full calibration path setting should have an absolute path ending in scripts\Engineering\calib\ENGINX_full_instrument_calibration_193749.nxs

Fixes #32163. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DanielMurphy22 — COMMENTED** [review]
In Mantid 6.1.0 I seem to be able to run a successful calibration with my full calibration path empty. Has this become a requirement for calibration since the last release? 

Testing master on MacOS and Ubuntu, after emptying the values in mantidproject.ini they seem to pick a correct fullcalibrationpath. master did however fail the test added in this PR. 
I'm just building on Windows to check I see and then don't see the problem there!

As this ones a little niggly, I think the real test will be manual testing which we should make sure is someone as far removed and new to EngDiff as possible!

**Review by DanielMurphy22 — DISMISSED** [review]
This worked for me on Windows!

**Comment by DanielMurphy22** [comment]
I have now tested to specific case of only clearing out the full calibration and it is not correctly populated on master, but with this PR it is! So this does work well for me on all platforms!

**Review by DavidFair — DISMISSED** [review]

**Comment by DavidFair** [comment]
> @DannyHindson There are conflicts

Sorry Gemma, I only saw your review/comment after I hit auto-merge :disappointed: 
I've fixed the merge conflict as it was only in the release notes

**Review by DavidFair — APPROVED** [review]

**Pull request merged**
