### PR TITLE
Indirect Corrections output workspace naming convention

### LINKED ISSUE #14144: ContainerSubtraction/Apply PaalmanPings change output name
The output name needs to end in _red in order to work with other programs in Mantid. Furthermore, the output should not include a duplicate of the instrument name:

Current ends with - `_Corrected_IRS26174`
Should end with - `_Corrected_26174_red`

This change needs to be done in:
* [x] ApplyPaalmanPings
* [x] ContianerSubtraction

### PR DESCRIPTION
**Pull request by ElliotAOram**
Fixes #14144 

The naming convention of files produced in the ContainerSubtraction and ApplyPaalmanPings tabs have been updated.

**All files are available from `\\olympic\Babylon5\Public\ElliotOram\Corrections\correction_set`**
# To Test (ContainerSubtraction)
- Open ContainerSubtraction (Interfaces > Indirect > Corrections > ContainerSubtraction)
- Add the Sample (`IRS26176`) and the Container (`IRS26174`)
- Run
- Ensure output workspace is called `IRS26176_graphite002_Subtract_26174_red`
# To Test (ApplyPaalmanPings)
- Open ApplyPaalmanPings (Interfaces > Indirect > Corrections > ContainerSubtraction)
- Add Input file (`IRS26176`), 
- Ensure Geometry is set to Flat Plate (to match the corrections file
- Check `Use Can` and add the Can file (`IRS26174`)
- Check `Use Corrections` and add the Correction file (File ending in flt_abs.nxs)
- Run with `Use Can` **and** `Use Corrections`:
  - OutputWorkspace = `IRS26176_graphite002_flt_Corrected_26174_red`
- Run with **ONLY** `Use Can` (uncheck `Use Corrections`):
  - OutputWorkspace = `IRS26176_grpahite002_Subtract_26174_red`
- Run with **ONLY** `Use Corrections` (uncheck `Use Can`):
  - OutputWorkspace = `IRS26176_graphite002_flt_Corrected_red`
- It should not be possible to run without either and you should be stopped by validation.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
The ApplyPaalman Pings part did not run successfully, but the first and possibly the second part produced a correctly named workspace. The third part (corrections only) did not produce a workspace of its required name.

**Comment by ElliotAOram** [comment]
Thanks @KarlPalmen I will take a look at this.

**Comment by KarlPalmen** [comment]
I don't think the corrections only produced any workspace.

**Comment by ElliotAOram** [comment]
Below is the output I get from running with only corrections. It seems to create the workspace `IRS26176_graphite002_flt_Corrected_red` in the ADS

image

Would you mind running this again to make sure then I'll happily take a look into possible causes for this if it's still not be created. Thanks

**Comment by KarlPalmen** [comment]
I tried it again and it worked this time. I'll treat yesterday's problems as a separate issue, if they reoccur. This may be because I ran ContainerSubtraction first and did not delete its workspaces before running AddPaalmanPings.

**Comment by ElliotAOram** [comment]
Okay, thanks Karl. I'll keep an eye on this and see if I can reproduce it.

**Pull request merged**
