### PR TITLE
Remove Confusion from SaveNISTDAT example 

### PR DESCRIPTION
**Pull request by DanielMurphy22**
**Description of work.**
Updated the SaveNISTDAT-v1.rst to prevent confusion over whether the files output from this algorithm can be reloaded. Also changed the data file used as the old one was no longer in the UsageData folder linked. The new one is from the TrainingCourseData so a link to that has been added.

**To test:**
Check the additions to the example are sensible.
Build docs.html if you wish.

*There is no associated issue.*

*This does not require release notes* because **documentation change**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Mantid-Matthew** [comment]
@DanielMurphy22 This seems to be failing it's doctests currently

**Comment by DanielMurphy22** [comment]
@Mantid-Matthew I've reverted to the old example file and just the comment has passed the tests

**Comment by Mantid-Matthew** [comment]
@DanielMurphy22 Could we remove the UsageData include if it no longer contains the neccecary file as seems less confusing not to link to any data at all in this case.

**Comment by DanielMurphy22** [comment]
Yes that is why I had tried to replace the data file in the first place.
Thanks, this is a sensible change to remove this link.

**Comment by DanielMurphy22** [comment]
I'm going to try to upload the replacement file to the Usagedata which is possibly the best solution

**Comment by DanielMurphy22** [comment]
I've added the link back in as the saveNISTDAT_data.nxs file was already in the DocTest data file and had just been removed from the usagedata so this was the simplest thing to do. This file is now in the UsageData

**Review by Matthew-Andrew — APPROVED** [review]
Looks good :+1:

**Pull request merged**
