### PR TITLE
Fix poco 1.6.0 warnings

### PR DESCRIPTION
**Pull request by quantumsteve**
Both Poco/Platform_POSIX.h and Code/Mantid/Framework/Kernel/inc/MantidKernel/WarningSuppressions.h define the macros GCC_DIAG_ON(x) and GCC_DIAG_OFF(x). The compiler warnings can be suppressed by undefining both macros before they are defined in WarningSuppressions.h.

testing: review changes and check tests. Testing on a machine with poco 1.6.0 installed is not necessary.

http://trac.mantidproject.org/mantid/ticket/10977

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
Oddly enough the last build failed on a couple of platforms because of the git-checkout issue again. The same checkout command worked well on the other platforms.

**Comment by FedeMPouzols** [comment]
Well the changes are obviously fine but just to make sure I'm going to try with a 'retest this please'. Not sure if it will work when I write it...

**Comment by FedeMPouzols** [comment]
retest this please

**Comment by eXeC64** [comment]
retest this please

**Comment by FedeMPouzols** [comment]
Thanks Harry for re-starting the build. For some reason the bug in the Jenkins plugin really likes this pull request. It failed again on 3 platforms!

**Comment by quantumsteve** [comment]
retest this please

**Comment by FedeMPouzols** [comment]
All looks good and the builds went through at last.

**Pull request merged**
