### PR TITLE
Add options dialog to Reflectometry GUI [PART 5]

### LINKED ISSUE #26533: Add Options and SlitCalculator for reflectometry GUI
The ISIS Reflectometry GUI used to have a menu option to open an options dialog and slit calculator. This should be re-added.

## Options dialog
This depends on PR #26835, which has done the work to add the Tools menu and an outline notification function and test for the presenter (see the TODOs in the code from that PR). You can apply this patch to add the Options dialog into the Tools menu and to connect the slot in the view:  [0001-Revert-Remove-Options-Dialog-from-the-menu.zip](https://github.com/mantidproject/mantid/files/3630680/0001-Revert-Remove-Options-Dialog-from-the-menu.zip)

Then the main remaining task is to implement the new Options dialog.

The dialog allows control of:
- the precision shown in the table
- whether warnings should be shown for:
  - table changes will be lost
  - you're about to process only a subset of a group
  - you're about to process all rows in the table

The warnings above should also be added (the only one currently implemented is to warn on losing table changes when starting autoprocessing, but we should also warn when closing the GUI)

~~There is potentially a bug where AutoProcess does not ask you if it is ok to overwrite a single group and row as that is effectively an "empty" table~~ - no longer a problem.

- [x] We can largely copy the layout from `DataProcessorOptionsDialog.ui` but the old dialog is too tied to the data processor to be  useful. 
- [x] The new dialog should be owned by `MainWindow`, with communication via presenters.
- [x] We'll need to load settings when the reflectometry interface is opened (i.e. when the dialog is constructed), similarly to `QDataProcessorWidget::loadSettings`, and save them when requested from the dialog.

### Slit Calculator
PR #26835

Note that this requires the current instrument, which should be synced across tabs, hence the dependency on #26536. The existing slit calculator dialog can be used so we just need to add a menu option and notifications to open it. Note that it also needs to be updated after the instrument changes.

### PR DESCRIPTION
**Pull request by giovannidisiena**
**Description of work.**
This PR is **5** of **6**.

The RoundPrecision widget has been implemented.

**To test:**
Complete a code review and check that the table precision is displayed as expected (e.g. default value if unchecked, user-specified value if checked, default value if unchecked again, etc). Full manual testing instructions will follow when subsequent PRs are merged.

Partially resolves #26533

*This does not require release notes* because **they will be added in a subsequent PR**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gemmaguest** [comment]
The change to the precision only takes effect after I process a row. Is this intentional?
- If I type in a value it includes the number of decimal places I type but they will be clipped/padded after processing. I think it would be clearer if they were updated straight away but I don't think this is a big issue.
- If I change the setting in the Options dialog it does not affect what is shown in the table until a row is processed/reprocessed. I think this is a bit more confusing but is something we could fix in a future PR.

**Comment by giovannidisiena** [comment]
> The change to the precision only takes effect after I process a row. Is this intentional?
> 
> * If I type in a value it includes the number of decimal places I type but they will be clipped/padded after processing. I think it would be clearer if they were updated straight away but I don't think this is a big issue.
> * If I change the setting in the Options dialog it does not affect what is shown in the table until a row is processed/reprocessed. I think this is a bit more confusing but is something we could fix in a future PR.

@gemmaguest yes, at least I am aware of this behaviour, but I agree that it may not be the clearest and could possibly do with a bit more attention in future.

**Comment by gemmaguest** [comment]
Doctest failure is unrelated

**Comment by gemmaguest** [comment]
Doctest failure is still unrelated

**Review by gemmaguest — APPROVED** [review]
Code looks fine and this functions as expected aside from the notes already made. It is an improvement on existing behaviour so is good to go in :+1:

**Comment by gemmaguest** [comment]
I've changed the base to the part 1 branch because I've already merged part 4 into that branch. I'll base everything off that branch from now.

**Pull request merged**
