### PR TITLE
 muon analysis 1 - fix TFAsymm mode

### LINKED ISSUE #25896: TF Asymm mode in muon analysis 1 broken
In muon analysis 1 TF Asymm mode is broken.

For single fitting the browser is not updating correctly - nor is the workspace

For multi fit the workspace is not updating correctly and the globals are not preserved.

### PR DESCRIPTION
**Pull request by AnthonyLim23**
**Description of work.**
TF asymmetry mode in muon analysis was crashing. This fixes it. 

**To test:**
Open Muon Analysis (the old one)
Load MUSR62260
Go to setting make sure `enable multiple fitting` is unticked
Go to data analysis
Add a `GaussOsc` function and set `Frequency` to `1..3`
Do a fit
Tick `TFAsymmetry mode` in the settings table
The plot will change (will now average a non zero value)
Do a fit
Untick  `TFAsymmetry mode`
You should just have the `GaussOsc` function
Add a `FlatBackground` and do a fit
The value of the `FlatBackground` should be less than the error

Open Muon Analysis (the old one)
Load MUSR62260
Go to setting make sure `enable multiple fitting` is ticked
Go to data analysis
Add a `GaussOsc` function and set `Frequency` to `1..3`
Click the global boxes for `Frequency` and `Sigma`
Do a fit
Tick `TFAsymmetry mode` in the settings table
The plot will change (will now average a non zero value)
`Frequency` and `Sigma` should still be global (will be inside a function of the form N(1+f)+A*exp )
Do a fit
Untick  `TFAsymmetry mode`
You should just have the `GaussOsc` function with the globals
Add a `FlatBackground`
Click the global boxes for `Frequency` and `Sigma`
Do a fit
The value of the `FlatBackground` should be less than the error

Fixes #25896. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by dtasev — CHANGES_REQUESTED** [review]
#### Testing the first instructions
> - Untick TFAsymmetry mode
> - You should just have the GaussOsc function

I have more than just f0-GausOsc:
- `f0-GausOsc` (added by me from previous steps)
- `f0-ProductFunction`
- `f1-ExpDecayMuon`
- This was appended as well: `f0-GausOsc` (so it appears twice in the functions)

It seems unchecking appends whatever was present originally, thus duplicating the functions before ticking (but doesn't seem to clear the added ones)

#### Testing the second instructions
Worked OK.

#### Bonus bug
1. Load MUSR62260
2. Go to Data Analysis
3. Delete all workspaces
4. MantidPlot hard crashes

**Comment by AnthonyLim23** [comment]
@DTasev are you sure, that was the original behaviour? 

The bonus bug is a known issue. We ignore it.

**Comment by AnthonyLim23** [comment]
sorry about that, fixed now

**Review by dtasev — CHANGES_REQUESTED** [review]
It correctly adds the new functions and moves `GausOsc` now, and then removes them when unchecked, however I get duplicated `Type` and `NumDeriv` - I think the `FitPropertyBrowser::clear();` adds them, even though they are already added by something else. (This might be a `FitPropertyBrowser` bug) Any ideas why this duplication might happen?

To replicate:
- Add `GausOsc`
- Check and uncheck TF Asymmetry Mode
- There will be 2 `Type` and `NumDeriv` rows

**Comment by AnthonyLim23** [comment]
I noticed this too. I asked @mantid-roman and he is not sure either.

**Comment by DTasev** [comment]
Should this be moved to a separate issue then? I'm happy to approve the PR if so

**Comment by AnthonyLim23** [comment]
probably, I feel like it will be a rabbit hole.

**Comment by AnthonyLim23** [comment]
#26118 is the issue. Is this ok to go then?

**Review by dtasev — APPROVED** [review]
Looks good, issue found will be addressed in future work, relevant issue is https://github.com/mantidproject/mantid/issues/26118

**Pull request merged**
