### PR TITLE
Fix finalization of algorithms when running processGroups()

### LINKED ISSUE #11361: Algorithms on workspace groups do not complete successfully
This issue was originally [TRAC 10519](http://trac.mantidproject.org/mantid/ticket/10519)

Original Reporter: John Hill

This ticket is blocks :  [TRAC10695](http://trac.mantidproject.org/mantid/ticket/10695)

When running an algorithm on a workspace group the progress report doesn't complete which causes Mantid to freeze when trying to shut down.

### LINKED ISSUE #11537: SaveNXTomoTest - Uncomment test assertions
This issue was originally [TRAC 10695](http://trac.mantidproject.org/mantid/ticket/10695)

Original Reporter: John Hill

This ticket is blocked by : 
 - [ ] [TRAC10519](http://trac.mantidproject.org/mantid/ticket/10519)

This ticket is blocks :  [TRAC11041](http://trac.mantidproject.org/mantid/ticket/11041)

Assertions commented out in SaveNXTomoTest.h to stop unit test failing due to http://trac.mantidproject.org/mantid/ticket/10519.

Lines: 105 and 153

 - - - - 
Keywords: IMAT

### PR DESCRIPTION
**Pull request by FedeMPouzols**
Fixes the finalization of algorithms when running `processGroups()`. `Algorithm::execute()` was not fully finalizing algorithms when running on groups (`processGroups()`). Then several algorithms were doing things like this at the end of their redefinition of `processGroups()`: 

```
// Store output workspace in AnalysisDataService
if (!isChild())
  this->store();

setExecuted(true);
notificationCenter().postNotification(
   new FinishedNotification(this, this->isExecuted()));
```

Other algorithms, line `SaveNXTomo` were not setting the executed flag and not sending the `FinishedNotification` so they wouldn't finalize correctly. The changes here make sure that those finalization steps are done by `Algorithm::execute()` as when running the normal `exec()`.

**To test:**

- Review code changes and see if you like the solution used here.
- All tests should pass and algorithms that process groups should still work well.

To see the problem raised by #11361 and #11537 you can run something similar to the [SaveNXTomo doc example](http://docs.mantidproject.org/v3.5.1/algorithms/SaveNXTomo-v1.html):

```
LoadFITS('FITS_small_01.fits', OutputWorkspace='reconstruction')
LoadFITS('FITS_small_02.fits', OutputWorkspace='reconstruction')
SaveNXTomo(InputWorkspaces='reconstruction', Filename='input_rec')
```

If you run this before the changes in this branch, the algorithm runs but it doesn't finish (in the sense of sending a `FinishedNotification`). In the original issue description the progress bar didn't move. That was fixed recently. The current behavior is that the progress bar reaches 100% and freezes there. Then, if you try to close Mantid it will not close but stay "shutting down..." as it waits for SaveNXTomo to finish.

Fixes #11361.
Also fixes #11537

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
@NickDraper: your eyes would be very much appreciated here to make sure that this is consistent with how algorithms are supposed to work.

**Comment by peterfpeterson** [comment]
I reviewed the changes and they look reasonable. :shipit:

**Comment by SimonHeybrock** [comment]
@FedeMPouzols There is one more algorithm that has that code block with `this->store();`: `SaveDiffFittingAscii`. It is inside a `try/catch` block, but maybe it can still be removed?

**Comment by FedeMPouzols** [comment]
Oh yes, good catch. That's a new one since this was done. I'll update it.

**Comment by peterfpeterson** [comment]
Don't :squirrel: until @SimonHeybrock's comment is taken care of.

**Comment by FedeMPouzols** [comment]
The last commit fixes `SaveDiffFittingAscii()` so this is hopefully ready for a squirrel now.

**Comment by SimonHeybrock** [comment]
Squirrel? :sheep:-it!

LGTM :shipit:, once Jenkins gives his ok.

**Pull request merged**
