### PR TITLE
Fix IDF display in ISIS SANS Gui when using batch reduction

### LINKED ISSUE #19537: IDF display in ISIS SANS is not updated when using batch file mode
The IDF display in ISIS SANS is not updated when using batch file mode. It displays the wrong IDF, but it uses the correct one

### Steps to reproduce the behavior

1. Open ISIS SANS GUI
2. Select LOQ
3. Open a recent batch file
4. Confirm that an old IDF is displayed 

### Platforms affected
All

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Fixes #19537

The current IDF path display was not updated when running the reduction in batch mode. Now it does

### To test:

Please find sample data here: smb://olympic/babylon5/Scratch/Anton/SteveFiles
Make sure that the data is added to your Mantid path.

##### Test that when running new data in batch mode the correct IDF is displayed

1. Open the ISIS SANS GUI and select LOQ as the instrument
2. Load the user file: `USER_LOQ_171B_M4_Alexander_8mm_Changer_MAIN.txt`
  * Confirm that the IDF display on the top of the run tab is set to: `LOQ_Definition_20020226-.xml`
4. Switch to batch mode operation and load the file: `batch_mode_reduction.csv`
5. Press `1D Reduce`
  * Confirm that the IDF display on the top of the run tab is set to:  `LOQ_Definition_20151016.xml` . This is the correct IDF that should be displayed when reducing that particular data set.

### Rlease notes

The release notes can be found [here](/mantidproject/mantid/commit/2585b4e391d9ba06a3a1959f0738396ae62f154d)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@AntonPiccardoSelg Did you mean to attach some data here?

**Comment by AntonPiccardoSelg** [comment]
@martyngigg yes, completely forgot about that.

**Comment by AntonPiccardoSelg** [comment]
@martyngigg I think I have found a bug. I set the branch to be in progress. I will let you know when that is resolved.

**Comment by AntonPiccardoSelg** [comment]
@martyngigg The bug has been resolved.

**Comment by martyngigg** [comment]
During testing we uncovered that on Linux you need to set `filefinder.casesensitive=Off` in order for the file finding to work correctly. This is a "bug" that has always been there and was not introduced here. On Windows file finding is always case insensitive so this was never spotted.

In order not to disturb the existing code in light of users only using Windows it will not be fixed in this PR. @AntonPiccardoSelg Can you open an issue to address that in the future?

**Comment by martyngigg** [comment]
Please :shipit:

**Comment by AntonPiccardoSelg** [comment]
The issue for the `filefinder.casesensitive=Off` is #19589

**Pull request merged**
