### PR TITLE
Fix problem with spectrum axis when panning on colour fill plots

### LINKED ISSUE #30677: Sliceviewer unzoom to box on 2D data
<!-- If the issue was raised by a user they should be named here.
**Original reporter:** @MathieuTillet https://github.com/mantidproject/mantid/issues/30653#issuecomment-776537062

### Expected behavior
Zoom out on sliceviewer, by right-clicking and dragging to some box size, should work with no errors.
### Actual behavior
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/cbook/__init__.py", line 388, in process
    proxy(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/cbook/__init__.py", line 228, in __call__
    return mtd(*args, **kwargs)
  File "/opt/Mantid/lib/mantidqt/widgets/sliceviewer/cursor.py", line 65, in on_mouse_move
    self.on_cursor_at(xdata, ydata)
  File "/opt/Mantid/lib/mantidqt/widgets/sliceviewer/imageinfowidget.py", line 66, in _on_cursor_at_axesimage
    self._widget.cursorAt(xdata, ydata, arr[i, j])
RuntimeError: indexOfValue - value out of range
```
I suspect the error message is only seen on Ubbuntu as it's Matplotlib version is behind Windows+MacOS.

### Steps to reproduce the behavior
- Load some 2D data (not MD data!), such as `Training_Exercise3a_SNS.nxs` from the TrainingCourseData.
- Open Sliceviewer.
- Zoom out of the plotted image by right-clicking and dragging out to a box. (like how you would zoom in on a region, but instead right-clicking)
### Platforms affected
Ubuntu, probably all Linux, found on release candidate for 6.0

### LINKED ISSUE #31266: Sliceviewer spectrum axis does not zoom or pan correctly.
### Expected behavior
The 2D plot data should pan and zoom consistently with the axis limits, i.e. the data on the plot should be in the correct position relative to the axes.

### Actual behavior
When panning, the plot data is stretched and compressed in the spectrum axis direction. When zooming, the plot data does not zoom consistently with the spectrum axis range. The time-of-flight axis appears to be fine.

### Steps to reproduce the behavior
- Load a file, e.g. MAR11060.raw from the training course data.
- Open the slice viewer.
- Select the "pan axes" tool.
- Drag the plot upwards.
You will see that the data is stretched and that data is left in negative spectrum space. Hovering the cursor over these negative spectrum values will throw runtime errors, as mentioned in #30677 (related issue).

### Platforms affected
Seen on both windows and linux in Mantid Workbench v6.0 and above.

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

When panning along the spectrum axis on a colour fill plot the data was being stretched instead of panning. If you now pan beyond the spectrum axis limits (eg to negative spectrum values) you see white\blank which is the same as happens if you pan beyond the x axis limits

**To test:**

See test on the linked issue

Fixes #31266, fixes #30677

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by thomashampson — APPROVED** [review]
Confirm that this PR resolves the issue. This bug was also the cause of #30677, so I've linked that issue to this PR.

**Comment by gvardany** [comment]
I merged this to master, but was it intended to release-next?

**Comment by DannyHindson** [comment]
@gvardany - Actually, yes it was intended for release-next. I must have put the wrong branch on the PR sorry. Do we need another PR to get it into release-next or is there anything you can do from your end to merge it into there?

**Comment by gvardany** [comment]
I think you should open another PR.

**Pull request merged**
