### PR TITLE
Minor changes to the QE coverage planning tool 

### LINKED ISSUE #15039: Minor changes to powder planning tool
In issue #14883, a pllaning tool for |Q|,E coverage was created, for direct and indirect spectrometry. Here are some small problems:

1. One should be able to find it in the Interfaces->Direct and Interfaces->Indirect instead of Interfaces->Utility. I think this can be done by adding it twice in Framework/Properties/Mantid.properties.template

2. In the indirect tab there is an Emax option, but there is no Emin for direct. 

3. There are some numbers in calcQE that should be defined as mass of the neutron, Plank's constant, etc. An even more elegant solution it would be to use scipy.constants module

### PR DESCRIPTION
**Pull request by shahrozahmed1**
Fixes #15039 

The Indirect and Direct planning tool required to be moved to Interface->Direct category and Interface->Indirect category. However it is mentioned in the issue that this is not possible as it cannot be added to both categories.
The interface now includes an Emin text field for direct, similar to Emax text-field in indirect tab.
The numbers in calcQE have been defined as mass of the neutron, Plank's constant, etc. 

_Most of these implementations were made by @mducle_

**To test:**

`Interface -> Utility -> QECoverage`

Emin text-field with default value of `-10`
When plot is clicked, check that the graph scale readjust itself and `y-axis` starts from `-10`
- Would be good idea to try this out with few negative values and see if interface handles it well

When on Direct Tab `HYSPEC` is selected,
- The default value of `s2` is set to `30` always

Check that other functionality has not been effected on the interface.

@AndreiSavici there have been some calculations updates made by @mducle, maybe it would be a good idea if you could go over them and see if they are working as they should.

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

refs #15039

### CODE REVIEW

**Comment by mducle** [comment]
Thanks for putting this in! 

Sorry, I kind of got sidetracked with other stuff and forgot to make a pull request. 

Regarding putting the interface into Direct/Indirect rather than Utility - we can just split the tabs into two different interfaces. Or just leave it as it is, but moved to the Direct category. Or split the tabs but put them into Direct/DGSPlanner and Indirect/Tools (although Indirect/Tools is written in C, so it would be a bit of pain to transfer the code over).

**Comment by shahrozahmed1** [comment]
@mducle After speaking to @AndreiSavici, I was suggested to leave the leave the GUI in the `Utility` category for now, however splitting the tabs does sound good too.

**Comment by AndreiSavici** [comment]
Minor things that should be addressed before we merge this branch:
- [ ] Documentation should describe Emin and Emax
- [ ] Handle empty strings for Emin, Ei in a nice manner
- [ ] Handle Ei=25, Emin=100 type of inputs
- [ ] Explain what negative Ei means (I have no idea - it seems nonsensical to me. I would remove this option)
- [ ] The documentation should contain the formula or reference to how the output is computed. I would put two equations: `hbar^2 Q^2 / (2 m_n) = E_f+ E_i - 2 sqrt(E_i*E_f) * cos (scattering angle)` and `DeltaE = E_i-E_f`. Then say that we solve the system for a known E_i for direct geometry, or for a known E_f for indirect

**Comment by AndreiSavici** [comment]
Seems to be working fine in most cases. 
One small problem in the indirect tab, if Emax for IRIS PG002 is -10, there is no plot, and the only message shown is in the MantidPlot log window
```
__main__:30: RuntimeWarning: invalid value encountered in sqrt
__main__:35: RuntimeWarning: invalid value encountered in sqrt
```
This message apears only once
For the indirect tab, if you don't put a value for Emax, you get a sensible default. For the direct tab, when you don't put a value for Emin, you get an error message in the message box. A good default value would be -Ei/2 There is a value error in the log window which does not make sense
```
 File "<Interface>", line 313, in onClickDirectPlot
ValueError: -----------------------------------------------------------------------------------
Error: Invalid input Ei. This must be a number or a comma-separated list of numbers
-----------------------------------------------------------------------------------
```
Also, add release notes in  mantid/docs/source/release/v3.7.0/direct_inelastic.rst and  mantid/docs/source/release/v3.7.0/indirect_inelastic.rst

**Comment by AndreiSavici** [comment]
Works now. :shipit:

**Comment by mducle** [comment]
Thanks @shahrozahmed1! Sorry I wasn't too helpful with the last few issues...

**Pull request merged**
