### PR TITLE
muon GUI vanishing data

### LINKED ISSUE #35125: Vanishing muon data
When working in the muon analysis GUI it is possible to make all of the data vanish. There is no way to get it back.

**To Reproduce**
- Open muon analysis
- Select MUSR for the instrument
- Put `62249, 62251` into the run box and press enter
- Data loads, you will see a nice plot
- Click the co-add button
- The data will vanish.

-

**Expected behavior**
The co-added data will appear

### PR DESCRIPTION
**Pull request by AnthonyLim23**
**Description of work.**

In the muon GUI's it was possible to create a situation where the data would not appear in the GUI. In fact it was not even calculated. This PR fixes the issue. The bug occurred when co-adding non-consecutive runs and was due to a split of the run string.

**To test:**

Open muon analysis
Set the instrument to MUSR

**Checking simultaneous loading**
In the run bar enter `62251`
A single plot should appear (the label will have the run number)

In the run bar enter `62251, 62253`
Two plots should appear (the labels will have the respective run numbers)

In the run bar enter `62251-62253`
Three plots should appear (the labels will have the respective run numbers)

**Checking co-add**
Tick the co-add button
Now there will be one plot and the label will have "62251-62253" in the name

In the run bar enter `62251`
A single plot should appear (the label will have the run number)

In the run bar enter `62251, 62253`
A single plot should appear (the label will have "62251,62253" in the name)

**Checking simultaneous loading for multiperiod**
Change the instrument to HIFI
In the run bar enter `84447`
Four plots should appear (the label will have the run number)

In the run bar enter `84447, 84449`
Eight plots should appear (the labels will have the respective run numbers)

In the run bar enter `84447-9`
12 plots should appear (the labels will have the respective run numbers)

**Checking co-add with multiperiod**
Tick the co-add button
Now there will be four plots and the labels will have "84447-84449" in the name

In the run bar enter `84447`
Four plots should appear (the label will have the run number)

In the run bar enter `84447, 84449`
Four plots should appear (the label will have "84447, 84449" in the name)

Fixes #35125 . 

Added a release note

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by rbauststfc — COMMENTED** [review]
This code change looks good and all the test cases now work as expected.

I noticed one thing while testing - if I enter `62249, ` as a run then it causes the below error to be thrown:


> Traceback (most recent call last):
>   File "c:\repos\mantid\qt\python\mantidqtinterfaces\mantidqtinterfaces\Muon\GUI\Common\load_run_widget\load_run_presenter.py", line 117, in handle_run_changed_by_user
>     self.run_list = run_utils.run_string_to_list(run_string)
>   File "c:\repos\mantid\qt\python\mantidqtinterfaces\mantidqtinterfaces\Muon\GUI\Common\utilities\run_string_utils.py", line 103, in run_string_to_list
>     range_max = int(range_max)
> ValueError: invalid literal for int() with base 10: ''

Mantid doesn't crash, but you get the message that asks the user to decide whether to continue or not. This is a pre-existing issue that isn't introduced by this PR, though, so I'd be happy to approve this and the bug can be raised as a separate issue if preferred (assuming there isn't an issue for it already)?

**Comment by AnthonyLim23** [comment]
Thats a new bug, thank you for spotting it

**Comment by AnthonyLim23** [comment]
I cannot reproduce it, for me it just removes the trailing comma. Could you please send me a full list of steps?

**Comment by rbauststfc** [comment]
So these are the steps I'm following:

- Open muon analysis
- Select MUSR for the instrument
- Put `62249, ` into the run box and press enter

Note that it seems you have to add a space after the trailing comma to get the error, otherwise it does just remove the trailing comma.

**Comment by AnthonyLim23** [comment]
Just looked and this bug is in main, so will look at it in a different PR. I have made an issue for it https://github.com/mantidproject/mantid/issues/35153

**Review by rbauststfc — APPROVED** [review]

**Pull request merged**
