### PR TITLE
Update GUI to use user inputted values if applicable.

### LINKED ISSUE #24647: Ensure that user input values are used in new GUI
Currently the user input values from the home tab are not used in subsequent calculations as the default values from file are used instead.

### PR DESCRIPTION
**Pull request by Matthew-Andrew**
**Description of work.**

Currently the new Muon GUI uses the values for timezero, first good time and deadtimetable stored in the file and ignores and selection made by the user in the GUI. This PR updates the GUI to use these user inputted values if applicable.

**Report to:** Anthony

**To test:**

Review the code and try out the options on the home tab for updating the values. Check that values of the outputed groups change. Note that currently you need to manually click update all to propogate these changes.

Fixes #24647 

*This does not require release notes* because the new GUI is not yet user facing

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
does this also work for rebin?

**Comment by Mantid-Matthew** [comment]
The arguments put into Rebin are passed to the MuonPreProcess algorithm but still need to investigate exactly what they do so I would say no for now. Sorting out Rebin is on the list to do.

**Comment by AnthonyLim23** [comment]
if you open the GUI and load some EMU data. Then select deadtime from another EMU file, click update. 

Change the instrument to HIFI and load some data. Then select from table workspace for the dead time and pick the EMU one. Click update - lots of errors in the logger.

**Review by AnthonyLim23 — APPROVED** [review]
looks good

**Pull request merged**
