### PR TITLE
Adding copy and paste functionality

### LINKED ISSUE #23022: Update sans GUI to use JobTreeView
The JobTreeView is now finished so should be put into the SANS GUI.

### PR DESCRIPTION
**Pull request by Matthew-Andrew**
**Description of work.**
This PR adds copy and paste functionality to the new table. It should be merged and ideally reviewed after ~~#23139~~

**To test:**
* Attempt to copy and paste rows around.

Fixes #23022 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gemmaguest** [comment]
One odd thing I've noticed is that multi-period columns get re-enabled on a paste operation if any of the columns contain data e.g.:
- enable multi-period
- enter something in the `ssp` column
- disable multi-period and the `ssp` column disappears
- copy and paste the row and the multi-period columns re-appear, even though multi-period is still unchecked

**Review by gemmaguest — CHANGES_REQUESTED** [review]
Code changes look good :+1:. Just the things in my previous comment to investigate.

**Comment by Mantid-Matthew** [comment]
Thanks for the thorough testing I'll try to address all the comments below:

**Hidden Columns**
I think it is correct that pasting in some data which contains data in a hidden column reveals the hidden columns. The fact the check-box does not update is not however. I have updated things so the checkbox should now be in syn with the table. 

**Tabbing and Column Widths**
These were both I think a symptom of how I had implemented the removeAllRows function. The way this was working was to clear the table including all headings and then remake the table. This reset the column widths and also seems to cause an issue with the tabbing. I have updated the implementation of removeAllRows so that it instead cycles through the rows removing them one by one. You are left with one empty row at the end currently due to the deleting the last row issue. This may be fixable by fiddling around with selections but seemed safer to leave like this.

**Deleting last row**
It is now impossible to delete the last row. If you try you are left with an empty but still existing row. As you no longer hit the exception this should have resolved the other issue here as well.

I have also merged in a branch where I added some icons buttons as I was halfway through the deleting last row problem on that branch already. This branch does the following:

Adds the icons to interact with the table these icons are
* Insert row
* Remove row (Same as delete)
* Copy rows (same as Ctrl C)
* Cut rows
* Paste rows (same as Ctrl V)
* Clear row

It also removes the file and edit menus which are currently empty and potentially unneeded.

**Comment by Mantid-Matthew** [comment]
There is also an issue with the currently selected cell changing to the top left whenever you do an operation. I think this could be fixed using the setCurrentIndex method which JobTreeView inherits from QTreeView but as the issue is minor am slightly hesitant to go digging around.

**Review by gemmaguest — APPROVED** [review]

**Pull request merged**
