### PR TITLE
IndirectDiffraction - Post Plot & Save

### LINKED ISSUE #17024: Indirect Diffraction - Post execution plotting  and saving
Indirect Interfaces should be able to plot and save after the algorithm is run by clicking a plot and save button rather than having to specify plot and save options before the interface is executed.

This issue should cover the post plotting and saving implementation for the `Indirect > Diffraction` interface

* [x] Indirect Diffraction *(I think these are all the same plot/save formats and are dealt with by a single widget)*

### PR DESCRIPTION
**Pull request by louisemccann**
The plotting and saving of the results workspace has been changed to after the execution of the algorithm for the Indirect Diffraction interface.

**To test:**

Check each plot option plots a suitable graph and that the appropriate workspaces have been saved in your save directory.
Test for instruments IRIS and OSIRIS
\olympic\babylon5\Public\Louise McCann\Diffraction

Fixes #17024.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
Everything seems to be working, plots are correctly shown and workspaces saved in the different formats.

The only problem I noticed is when the workspace to save does not exist. In that case I get an unexpected exception.

**Comment by raquelalvarezbanos** [comment]
Tested again:

- IRIS: OK both save and plot
- OSIRIS: OK both save and plot

However, I noticed the following issue:
- Select "OSIRIS"
- In "Reflection", select "diffonly"
- Select runs 89812-89817
- Calibration file: "osiris_041_RES10.cal"
- Vanadium runs: 89757-89761
- Hit "Run", Mantid crashes

@louisemccann I don't think this is related with these changes. In fact, I have tried the same on a different branch and Mantid also crashed. Therefore I would say this should be fixed in a separate issue, but let me know if you prefer fixing it here.

**Comment by louisemccann** [comment]
@raquelalvarezbanos I will look into this as a separate issue

**Comment by raquelalvarezbanos** [comment]
:shipit:

**Pull request merged**
