### PR TITLE
Clean up mismatch filename

### PR DESCRIPTION
**Pull request by ajjackson**
**Description of work**

**Purpose of work**
Systemtest mismatch filenames are currently garbled and repeat themselves. See e.g. the Artifacts of this run https://builds.mantidproject.org/job/pull_requests-conda-linux/4241/

This also makes the filename inconsistent with the printed message "Saving mismatch to ..."

**Summary of work**
Removed some redundant parts of the output filename argument, so it is consistent with printed message

**Further detail of work**
This does not solve my remaining problem with systemtest mismatch files: I can no longer find the generated files! They used to appear in build/Testing/Systemtests/scripts, but lately have not been showing up....

I would strongly prefer that the user message prints the full absolute path of the generated file, but I don't know enough about how Mantid paths and SaveNexus work to implement this.

**To test:**

Fail a systemtest. Look at the name of the generated mismatch file (if you can find it). Compare before/after this change.

This might not require release notes as it doesn't affect regular users. Still, it fixes a regression so maybe wouldn't hurt.

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by ajjackson** [comment]
`config["defaultsave.directory"]` evaluates to '/home/adam/Desktop/tmp' but no mismatch files are appearing there.

**Comment by robertapplin** [comment]
> `config["defaultsave.directory"]` evaluates to '/home/adam/Desktop/tmp' but no mismatch files are appearing there.

In the systemtesting.py file, if you change the `SaveNexus` line to use the default save directory, do the mismatch files appear? i.e.

```
SaveNexus(InputWorkspace=valNames[0], Filename=config["defaultsave.directory"] + "/" + mismatchName)
```

**Comment by ajjackson** [comment]
If I edit the code to

```python
            if mismatchName:
                mismatchName = self.__class__.__name__ + mismatchName + "-mismatch.nxs"
            else:
                mismatchName = self.__class__.__name__ + "-mismatch.nxs"
                full_mismatch_path = (
                    pathlib.Path(config["defaultsave.directory"]) / mismatchName
                    )
            print(f'Saving mismatch to "{full_mismatch_path}"')
            SaveNexus(InputWorkspace=valNames[0],
                      Filename=str(full_mismatch_path))

            if full_mismatch_path.exists():
                raise Exception("yes it is there")
            else:
                raise Exception("not it is not")
```

then I get the exception "yes it is there" and the summary message
```
Saving mismatch to "/home/adam/opt/mantid-build/Testing/SystemTests/scripts/AbinsCRYSTAL2D-mismatch.nxs"
```

but if I go looking for it the file is not there.

If I change the above so that `full_mismatch_path` is `pathlib.Path('/home/adam/Desktop/tmp') / mismatchName`
then the mismatch file is succesfully written to that location.

If I create an empty mismatch file in Testing/SystemTests/scripts with `touch`, then run the failing systemtest,  it is removed from the directory.

From this I conclude that:
- `config["defaultsave.directory"]` is modified when running the systemtest script
- on my system it is set to *Testing/SystemTests/scripts/*
- SaveNexus is behaving correctly and writes a mismatch file to wherever it is pointed
- after tests are finished, *Testing/SystemTests/scripts/* is cleaned up, deleting my mismatch files

**Comment by robertapplin** [comment]
> From this I conclude that:
> 
> * `config["defaultsave.directory"]` is modified when running the systemtest script
> * on my system it is set to _Testing/SystemTests/scripts/_
> * SaveNexus is behaving correctly and writes a mismatch file to wherever it is pointed
> * after tests are finished, _Testing/SystemTests/scripts/_ is cleaned up, deleting my mismatch files

That is strange, this option suggestions that the mismatch files shouldn't be cleaned up unless the `--clean` flag is provided
https://github.com/mantidproject/mantid/blob/9dacd7c4fbfd82b365c72eefd6ea8ae72f7406b1/Testing/SystemTests/scripts/runSystemTests.py#L87

Have you tried supplying a different `--savedir` to see if the files still get cleaned up in a completely separate directory?
https://github.com/mantidproject/mantid/blob/9dacd7c4fbfd82b365c72eefd6ea8ae72f7406b1/Testing/SystemTests/scripts/runSystemTests.py#L98

**Review by RichardWaiteSTFC — APPROVED** [review]
This works for me, I see the mismatch file with a clearer name so I'm approving - is that OK @robertapplin? My save directory does indeed get changed when I run a systems test but it doesn't get cleared...

**Pull request merged**
