### PR TITLE
Minor fixes for isis single-crystal reduction class

### PR DESCRIPTION
**Pull request by RichardWaiteSTFC**
**Description of work**
Fixed a few bugs in the single-crystal reduction classes

- ISIS single crystal reduction classes now set UB before attempting to transform data to HKL using ``convert_to_MD`` method
- Fixed bug in ISIS single crystal reduction classes where UB was not set on combined peak table when saving using ``save_all_peaks`` method.
- Fixed bug in ISIS single crystal reduction classes when defining multiple goniometer angles in ``process_data`` method with a sequence (i.e. not using the motor name string)
- ISIS single crystal reduction class for SXD now supports defining a file extension when loading data (previously available for WISH class - in both cases the argument to ``load_run`` has been renamed to ``file_ext``)

**To test:**

Unit tests should cover it but you can run some of these snippets

(1) Test file extension argument (check workspace history to confirm)
```
sxd = SXD()
wsname = sxd.load_run(32863, file_ext=".nxs")
```
(2) Test goniometer can be set with sequences (i.e. this executes without error)
```
sxd = SXD(vanadium_runno=32857, empty_runno=32856, detcal_path=r"\\olympic\Babylon5\Public\RWaite\SXD_demo\SXD32863_peaks_detcal.xml")
sxd.process_vanadium()
sxd.set_goniometer_axes([0,1,0,1])  # ccw rotation around vertical
runs = range(32863,32865)
sxd.process_data(runs, [-150, -145])
```
(3) Test UB is copied from peaks workspace (i.e. this executes without error)
```
ws = sxd.get_ws(runs[0])
peaks = sxd.find_sx_peaks(ws,  nstd=8)
FindUBUsingFFT(PeaksWorkspace=peaks, MinD=1, MaxD=10)
sxd.set_peaks(runs[0], peaks)
sxd.convert_to_MD(run, frame="HKL")
```

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by RichardWaiteSTFC** [comment]
Build from package here https://builds.mantidproject.org/job/build_packages_from_branch/563/

**Review by MohamedAlmaki — COMMENTED** [review]
In the last script, is the value of `run` 32863? Also, should I run this script after the second one? I assumed `runs` were from the previous script

**Comment by RichardWaiteSTFC** [comment]
> In the last script, is the value of `run` 32863? Also, should I run this script after the second one? I assumed `runs` were from the previous script

Yep that's correct - you should be able to run these code snippets sequentially - let me know if you see anything unexpected!

**Review by MohamedAlmaki — APPROVED** [review]
Looks fine, works as expected

**Pull request merged**
