### PR TITLE
Algorithms with optional workspace output properties can not run on group workspaces 

### LINKED ISSUE #21319: Algorithms with optional workspace output properties can not run on group workspaces
Algorithms should run on group workspaces by running on each group workspace one-by-one. However, if there is an optional output workspace problems arise, as `Algorithm` attempts to create a new group workspace with no name.

To test this out try running `NormaliseToMonitor` on a group workspace. With `NormFactorWS` set everything works as expected. Without `NormFactorWS` left blank an empty group workspace for the output is created (it seems Mantid gives up part way through).

### LINKED ISSUE #21348: Issue with temporary names for optional output workspaces of child algorithms
If an algorithm having an optional output workspace is run as child without the optional output, it is still produced with a temporary name.
The temporary name is generated to be able to replay the unrolled history, however a check whether the optional property is set is probably missing somewhere.

**Steps to reproduce**:
1. Set the mantid setting to show the invisible workspaces
2. Create this fake algorithm.

```
class FakeAlgo(PythonAlgorithm):

    def category(self):
        return 'Test'

    def name(self):
        return 'FakeAlgo'

    def PyInit(self):
        self.declareProperty(MultipleFileProperty('Filename'), doc='List of input files')
        self.declareProperty(WorkspaceProperty('OutputWorkspace', '', direction=Direction.Output),
                             doc='Output workspace or workspace group.')
    def PyExec(self):
        filename = self.getPropertyValue('Filename')
        ws = self.getPropertyValue('OutputWorkspace')
        LoadMuonNexus(Filename=filename, OutputWorkspace=ws)
        # LoadMuonNexus(Filename=filename, OutputWorkspace=ws, DeadTimeTable='', DetectorGroupingTable='')
        self.setProperty('OutputWorkspace', mtd[ws])

AlgorithmFactory.subscribe(FakeAlgo)

```

3. Run it for this file in unit tests
```
FakeAlgo(Filename='MUSR00022725.nxs')
```
4. See that along with the desired output, there are dangling table workspaces with __TMP... name.

5. Comment out the line with `LoadMuonNexus` and uncomment the next line, where the names of the optional outputs are explicitly set to empty.

6. Run again, and there is no table left over.

### PR DESCRIPTION
**Pull request by ianbush**
Allow algorithms with optional output workspace properties to be run over group workspaces. Try running the script below on `master` to see the issues with this.

There are 3 changes to make this work:
1. If an output workspace property is optional and not set do not try and create an output workspace.
1. If an output workspace property is optional and not set do not try and set a name for the property when running the child algorithms.
1. Child algorithms can be run without adding a temporary workspace name. This is the desired  behaviour when running over a group workspace.

**To test:**

Try this script before and after the changes.

```python
CreateSampleWorkspace(OutputWorkspace='test1', NumMonitors=1)
CreateSampleWorkspace(OutputWorkspace='test2', NumMonitors=1)
GroupWorkspaces(InputWorkspaces='test1, test2', OutputWorkspace='grouped')
NormaliseToMonitor(InputWorkspace='grouped', OutputWorkspace='normalised', MonitorID=300)
```

Fixes #21319, fixes #21348 .

**Release Notes** 
*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — DISMISSED** [review]
The changes all appear logical and well targeted.

It's a shame we have to add another loop with a set of `dynamic_cast`s but given the current structure this is the only way. Any reorganisation of that code is outside of the scope of this PR.

I tried variants of the script: including the optional workspace and without, changing the group size and rerunning without deletion, removing the optional output again. All appear to function as expected.

**Comment by ianbush** [comment]
I'm just marking this as in progress - there is potentially a better fix for this that will also solve #21348.

**Comment by ianbush** [comment]
@martyngigg System tests are passing so this should be ready to test again. As well as checking the original test there is a test described in #21348 to test the related issue, of creating output workspaces that were not requested.

**Comment by martyngigg** [comment]
@ianbush Thanks. The changes definitely look cleaner. It's nice to avoid that extra argument to `createChildAlgorithm` - I'd forgotten about the `isOptional` check and I wrote it!

I'll just give it a test drive.

**Review by martyngigg — APPROVED** [review]
Looks good now. The changes make sense and plug a hole in the optional workspace logic.

**Comment by ianbush** [comment]
@mantidproject/gatekeepers Is it possible to get this merged? A couple of things are depending on it.

**Pull request merged**
