### PR TITLE
Fix most out-of-bounds reads in MDHistoWorkspace

### LINKED ISSUE #15885: Out of bounds read by MDHistoWorkspaceIterator?
Found this by chance with address sanitizer (use `cmake -DCMAKE_CXX_FLAGS=-fsanitize=address` and run `MDAlgorithmsTest`):

In `DataObjects/src/MDHistoWorkspaceIterator.cpp:324`:
```cpp
    do {
      m_pos++;
    } while (m_skippingPolicy->keepGoing() && m_pos < m_max);
```
Since the left argument of `&&` is evaluated first, this seems to read beyond the bounds of `bool *m_masks;` in `MDHistoWorkspace`?

Check if you can reproduce this. If so, the fix should be simple (just swap the arguments of `&&`). Also check if there are other similar problems in nearby code.

### PR DESCRIPTION
**Pull request by quantumsteve**
Description of work.

This fixes one cause of out-of-bounds reads on the `m_masks` arrays in an MDHistoWorkspace. The number of points in each dimension is one larger than the number of cells, so the index may be larger than the `m_masks` array. Therefore one should check the index before calling `m_skippingPolicy->keepGoing()`.

**To test:**
- Apply this patch to `master`, then build and run the unit tests. You should get the list of 22 failing tests in #16583.
- Apply the same patch to this branch and run the unit tests. I only see three failing tests.

```
The following tests FAILED:
    1325 - MDAlgorithmsTest_CompactMDTest (Failed)
    1401 - MDAlgorithmsTest_ReplicateMDTest (Failed)
    1522 - SliceViewerMantidPlotTest_SliceViewerPythonInterfaceTest (Failed)
Errors while running CTest
```

Fixes #15885.

_Does not need to be in the release notes._

I'll add release notes and an assert [here](https://github.com/mantidproject/mantid/blob/f80f287c32cc86c3ef188cd2e918a29fe45b8a50/Framework/DataObjects/inc/MantidDataObjects/MDHistoWorkspace.h#L237) once all issues raised in #16583 have been resolved.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@quantumsteve Did you mean to attach a patch to this PR?

**Comment by quantumsteve** [comment]
@martyngigg  https://github.com/mantidproject/mantid/files/314896/ReplicateMD_out_of_range.txt

**Comment by martyngigg** [comment]
Thanks.

**Comment by martyngigg** [comment]
The code changes are sensible for avoiding the out-of-bounds access.

Confirmed that with the patch only those tests specified fail.

:shipit:

**Pull request merged**
