### PR TITLE
Indirect - Vesuvio - Add 'LoadLogFiles' property to 'LoadVesuvio' and associated flag to Vesuvio driver script

### LINKED ISSUE #21305: Indirect - VESUVIO - Provide option for disabling loading sample log files
Currently, the LoadVesuvio algorithm and by extension the Vesuvio driver script, do not provide an option for disabling loading the sample log files.

A 'LoadLogFiles' property should be added to the LoadVesuvio algorithm, and a flag should be made available in the Vesuvio driver script.

### PR DESCRIPTION
**Pull request by brandonhewer**
Currently, the 'LoadVesuvio' algorithm (and by extension the Vesuvio driver script), does not provide the option to disable loading the log files.

This PR adds a 'LoadLogFiles' boolean property to the 'LoadVesuvio' algorithm, which can be used to disable loading the log files when calling 'LoadVesuvio'. A 'load_log_files' flag has also been added to the driver script.

**To test:**
1. Run the supplied script within Mantid.
2. Open the sample logs of the sample runs workspace (\*\_tof workspace).
2. Ensure that the sample logs contains data from the log files.
3. In the supplied script, change the 'load_log_files' flag from True to False.
4. Run the script.
5. Open the sample logs of the sample runs workspace (\*\_tof workspace).
6. Ensure that the sample logs contains data from the log files.

**Test Files:**
[test_script.zip](https://github.com/mantidproject/mantid/files/1551388/test_script.zip)

Fixes #21305. 

**Release Notes** 
Changes have been added to the release notes

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by josephframsay — COMMENTED** [review]
Code quality of the changes is nice. Unfortunately when I run the script, I get `RuntimeError: [Errno 2] No such file or directory: 'Indium_post_moderator_calib_1Mar_3Bragg_L0_iter_2_IP.dat'`. Is there some data that should have been supplied in the zip file as well?

Also, should this go in the release notes? It seems like a change your users would probably be interested in...

**Comment by brandonhewer** [comment]
@josephframsay Yes to both of those points 👍, I'll add the ipf to the zip file and update the release notes

**Comment by josephframsay** [comment]
Unfortunately I now get what looks like a `KeyError` when I run the script. The output is as follows:
```
=== Iteration 1 out of a possible 2
RuntimeError: 'f0.Scaling'
  at line 336 in 'C:/Users/jxl54435/mantid-rel/Framework/PythonInterface/plugins/algorithms\VesuvioCorrections.py'
  caused by line 459 in 'C:/Users/jxl54435/mantid-rel/Framework/PythonInterface/plugins/algorithms\VesuvioCorrections.py'
  caused by line 70 in 'C:/Users/jxl54435/mantid-rel/scripts/Inelastic\vesuvio\base.py'
  at line 169 in 'C:/Users/jxl54435/Downloads/test_script/user_script_simplified_output_modified.py'
  caused by line 81 in 'C:/Users/jxl54435/mantid-rel/scripts/Inelastic\vesuvio\commands.py'
  caused by line 129 in 'C:/Users/jxl54435/mantid-rel/scripts/Inelastic\vesuvio\commands.py'
  caused by line 256 in 'C:/Users/jxl54435/mantid-rel/scripts/Inelastic\vesuvio\commands.py'
  caused by line 1051 in 'C:\Users\jxl54435\mantid-relbuild\bin\Release\mantid\simpleapi.py'
```
Could I be missing some config files, or anything like that?

**Comment by josephframsay** [comment]
Should the bug fix be put into the release notes as well?

**Comment by brandonhewer** [comment]
@josephframsay Release notes updated

**Review by josephframsay — APPROVED** [review]
Changes are good quality and the manual tests work as expected

**Pull request merged**
