### PR TITLE
Require and package boost-serialization.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
`boost::serialization` is used in https://github.com/mantidproject/mantid/pull/19280 to enable unit-testing of code that uses MPI calls *without an actual MPI build* in an easy manner.

This PR adds the library to the OSX and Linux packages. For Windows see https://github.com/mantidproject/thirdparty-msvc2015/pull/19 and https://github.com/mantidproject/mantid/pull/19277 (done).

**To test:**

- Check if this works and packages correctly on OSX and Linux.

No issue.
No release notes.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@SimonHeybrock mantidproject/thirdparty-msvc2015#20 has been merged so the serialization library is available on Windows too.

For Windows there are 2 places that need updating:
* https://github.com/mantidproject/mantid/blob/master/buildconfig/CMake/WindowsNSIS.cmake#L44 with the list of libraries
* https://github.com/mantidproject/mantid/blob/master/buildconfig/CMake/Bootstrap.cmake#L13 with an updated `SHA` of `00a89211af3e581e99a42a2686bb94ead3b45463` to pull down the new libraries

**Comment by SimonHeybrock** [comment]
@martyngigg Thanks! What is the right way to check whether this works, and is packaged correctly?

**Comment by martyngigg** [comment]
@SimonHeybrock We should ask a developer on each platform to build the package and make sure it installs and starts.

**Comment by SimonHeybrock** [comment]
@martyngigg Ok, I can ask Owen and Lamar, then we would be covering Ubuntu, OSX, and Windows. Is only RHEL missing from this list?

**Comment by martyngigg** [comment]
@SimonHeybrock Yes. That would be best covered by someone at SNS

**Comment by SimonHeybrock** [comment]
I made the builds servers build packages, seems to work on all platforms.

Downloaded, installed, and launched:
- Ubuntu 16.04: `gdebi` fails with `Dependency is not satisfiable: librdkafka++1`
- OSX: :white_check_mark:

**Comment by LamarMoore** [comment]
Tested package install on my windows machine. Looks good.

**Comment by martyngigg** [comment]
@matthew-d-jones Was the `rdkafaka` dependency not added to debian package list?

**Comment by SimonHeybrock** [comment]
`rdkafka` is fine, it is just me not knowing what I am doing :)

Ubutnu 16.04: :white_check_mark: 

Do we need to test RHEL separately? Building the package worked on the build server.

**Comment by matthew-d-jones** [comment]
@martyngigg 
Should be fine : https://github.com/mantidproject/mantid/pull/19328/files

**Comment by martyngigg** [comment]
@SimonHeybrock I have a CentOS 7 VM that I can test it on for completeness.

**Comment by martyngigg** [comment]
Looks good on Cent OS 7 too so I say :shipit:

**Pull request merged**
