### PR TITLE
Add output composite members option to Iqt

### LINKED ISSUE #31705: Implement output individual function fits in other QENS Fitting tabs
**Original reporter:** @SpencerHowells

In the Convolution tab in QENS Fitting there is an option to Output Composite Members. This option should be available in other tabs. This option also is disabled when the fitting type is made simultainious and should be made to work for that case.

The Output Composite Members is found in the Fit Options Browser (below the Function Browser)

**Acceptance Criteria**
- [ ] Its possible to use the Output Composite Members on  I(Q, t) tab

### PR DESCRIPTION
**Pull request by MohamedAlmaki**
### Description of work
This PR adds `Output Composite Members` to the IQT fitting tab. 
#### Summary of work

Fixes #31705. 

### To test:
1. Go to `Interfaces->Inelastic->I(Q, T)`
2. Click `Add Workspace` and add [irs26176_graphite002_iqt.zip](https://github.com/user-attachments/files/16331874/irs26176_graphite002_iqt.zip)
3. Set the indices from 0-5
4. Add two Expontatials 
5. Click `Run`
6. Plot the output workspaces spectra suffixed with `_Workspace` and check that they have `Data`, `Calc` and `Diff` labels
7. Go back to the interface and mark `Output Composite Members` located at the end of the property browser
8. Plot the output workspaces spectra suffixed with `_Workspace` and check that they have now extra two`ExpDecay` labels

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by GuiMacielPereira — CHANGES_REQUESTED** [review]
Followed through the instructions and when the `Composite Members` box is checked, two new functions appear in the output workspaces. The code is good.

The only thing that I noticed was two ways to crash mantid whithin the IQt interface, so a separate issue should be created for these crashes:

- In the IQt interface, add an exponential and set the lifetime to negative. Mantid crashes with segfault
- If you do a fit and then delete the workspaces and try to do the exact same fit, Mantid crashes again

@MohamedAlmaki can you check these crashes happen for you as well?

**Comment by MohamedAlmaki** [comment]
> In the IQt interface, add an exponential and set the lifetime to negative. Mantid crashes with segfault

I was able to reproduce this but I got an error dialogue instead of a crash 

> If you do a fit and then delete the workspaces and try to do the exact same fit, Mantid crashes again

Do you mean delete the workspaces in the workspace window or the table view?

**Comment by GuiMacielPereira** [comment]
> Do you mean delete the workspaces in the workspace window or the table view?

I meant Mantid's workspace window, outside the iqt interface

**Comment by MohamedAlmaki** [comment]
> I meant Mantid's workspace window, outside the iqt interface

I got an execution error. Do you get a mantid crash with an error report dialogue? I just got errors in the log in both cases

**Review by GuiMacielPereira — APPROVED** [review]

**Pull request merged**
