### PR TITLE
Add default peak function setting to EngDiff UI

### LINKED ISSUE #31490: Automatically set default peak function to BackToBackExponential in EngDiff UI
There are many back-to-back expontnial based models in mantid, however the BackToBackExponential function is the most suitable for ENGIN-X and the instrument scientist want this to be set as the default peak function in the Eng Digg UI fitting tab. This will mean users do not get confused between similarly named functions and don't have to open the mantid general settings,

### PR DESCRIPTION
**Pull request by RichardWaiteSTFC**
**Description of work.**
Added setting for default peak function in the EngDiff UI. This presents the user with a drop-down box of a few relevant functions (the users can still select from the full list in the interactive tool when the fit property browser is open, but the aim of this is to not overwhelm the user with similarly named functions - in particular the back-to-back exponential based ones). The default peak function has been set to BackToBackExponential for which coefficients have been refined for ENGIN-X (stored in the parameters.xml file). The default peak will be overwritten with the last used supported peak type.

**To test:**
(1) In the main workbench settings, set the peak function to a Gaussian (File > Settings >Fitting > Default peak shape)
(2) Open the EngDiff UI (Interfaces > Diffraction > Engineering Diffraction)
(3) Open the workbench settings and check the default peak shape is now BackToBackExponential
(4) Open the UI settings (cog on bottom left) and change the peak function to something else (e.g. Lorentzian) and click OK
(5) Open the workbench settings and check the default peak shape is now whatever you selected.
(6) Go to the fitting tab, load in some focussed data (to make focussed data follow the instructions in Test 1 here https://developer.mantidproject.org/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.html)
(7) Plot the data
(8) Open the fit browser (Fit button on toolbar), right-click on the plot and select peak type - change the peak to a valid one - i.e. one of the functions in the drop-down list of the UI settings (e.g. back to BackToBackExponential)
(9) When you open the UI settings again the peak function should be whatever was chosen
(10) Change the peak function in the UI settings and add a peak to the plotted data, it should add the correct function.
(11) Repeat step (8-9) but choose an invalid peak function (e.g. IkedaCarpenterPV), when you open the UI settings it should be set to the last peak selected in the settings.

To-Do
- Add release notes
- Update UI docs

Fixes #31490

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DavidFair** [comment]
I just wanted to ask, is this meant to be targetting 6.1? As I don't feel (from a gatekeeper POV) in my opinion this will make it into release for the following reasons:

- Appears to be a new feature rather than a bug fix when were significantly past our release freeze for 6.1
- Has the risk of introducing new bugs that might delay a release or require a subsequent patch release
- Will require manual testing to validate this feature works and doesn't regress anything else
- Will be up for review/merge optimistically during the final release week (24th-28th March) where the risk/rewards of changes get stricter and tend to need justifying on a case-by-case basis (especially towards the end of the week)

Obviously, I'm happy for you to disagree but it's more getting the justification for this release if were targetting it. As I suspect other gatekeepers / reviewers will have similar concerns

**Comment by RichardWaiteSTFC** [comment]
No all valid points! I picked the wrong milestone (and I also need to change branch) - the issue fixed has milestone 6.2 S1! I split this into two parts, I do think it would be good to merge the first part (PR #31509) this release as it is what I consider to be a bug fix - though feel free to disagree (I'm happy to change #31509 as well if it's too risky).

**Comment by DavidFair** [comment]
I'm completely happy with #31509 as it's small, easy to test and fixes a genuine problem

I thought I'd just double check before someone reviewed this as a priority to get into release :smile:

**Comment by RichardWaiteSTFC** [comment]
Closing this PR as have found a superior way to do this in PR #31748 that doesn't require a change to the mantid fitpropertybroswer behaviour (and actually works better).

**Pull request closed without merging**
