### PR TITLE
D2B add new IPF and IDF for cycle 183

### PR DESCRIPTION
**Pull request by gvardany**
**Description of work.**
This adds new IPF and IDF for D2B corresponding to the cycle 183 that started Sep 3.

**Report to:** G. Cuello. 

**To test:**

Check that the `valid-from` dates are set to `2018-09-01`, which should match the suffixes of the file names.

*There is no associated issue.* 

*This does not require release notes, it is a periodic update that is done about twice a year.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by vreimund — APPROVED** [review]

**Review by peterfpeterson — CHANGES_REQUESTED** [review]
All of the D2B instrument definitions are valid to `2100-01-31`. That's a mistake
```sh
$ grep valid-to D2B_*
D2B_Definition_2018-03-01.xml:valid-to="2100-01-31 23:59:59" last-modified="2018-03-20 14:05:02">
D2B_Definition_2018-05-01.xml:valid-to="2100-01-31 23:59:59" last-modified="2018-03-20 14:05:02">
D2B_Definition.xml:valid-to="2100-01-31 23:59:59" last-modified="2017-09-07 15:10:50">
```

**Comment by gvardany** [comment]
Assuming `valid-to` is optional, and given that the unit test file is from 2015, when none of the IDFs is valid, but `D2B_Definition.xml`, I can't explain this:
```
print ExperimentInfo.getInstrumentFilename("D2B", "2015-01-01 00:00:00")
/Users/vardanyan/mantid/instrument/D2B_Definition_2018-09-01.xml
```

**Comment by gvardany** [comment]
Seems I've found the problem. [ Documentation](http://docs.mantidproject.org/nightly/concepts/InstrumentDefinitionFile.html#top-level-instrument) says:

> valid-from is compulsory and is the date from which the IDF is valid from (+). This date must be larger than or equal to 1900-01-31 23:59:01

Whereas in my IDF it was `1900-01-31 00:00:00`.

**Comment by gvardany** [comment]
@peterfpeterson Is this good to go now?

**Review by peterfpeterson — APPROVED** [review]

**Pull request merged**
