### PR TITLE
Plot Normalization controlled from python.

### LINKED ISSUE #13751: Python plot commands: normalization (by bin width) cannot be controlled
It was noticed in the last training course that you cannot change the normalization option with `plotSpectrum` and `plotBin` from python.

This can be changed in the GUI by right clicking on a plot, then selecting Normalization (None / Bin Width). There is a settings entry for this which is saved in the Mantid properties file and handled by the config service: `graph1d.autodistribution=On/Off`. You can change it in View->Prefernces->2D Plots->Options->"Normalize histogram to bin width"

If you change it from python with `config['graph1d.autodistribution']=On/Off` that doesn't seem to have any effect.

What is missing: Several of the `plot1D()` methods in [MantidUI.cpp](https://github.com/mantidproject/mantid/blob/master/Code/Mantid/MantidPlot/src/Mantid/MantidUI.cpp) were extended with a new parameter `distr` when this normalization option was introduced, but the plot1D that is exposed to pyhton in [qti.sip](https://github.com/mantidproject/mantid/blob/master/Code/Mantid/MantidPlot/src/qti.sip) (where the first param is a QStringList) does not take any parameter for this and just uses `MantidQt::DistributionDefault`.

Two alternatives come to mind if we want to provide control over this normalization option from python:
- Add the `distr` or similar parameter to the plot1D that is exposed to python, and then add it to the python plotSpectrum and plotBin methods in [pymantidplot](https://github.com/mantidproject/mantid/blob/master/Code/Mantid/MantidPlot/pymantidplot/__init__.py).
- Add a python command to change the normalization settings / make `config['graph1d.autodistribution=On/Off']` do that.

The 1st alternative looks in principle more consistent with how we handle other plot options.

If this is added it would be good to add a keyword argument to the pyplot interface as well.

### PR DESCRIPTION
**Pull request by LamarMoore**
Resolves #13751 
- [x] The [release notes](http://www.mantidproject.org/ReleaseNotes_3_6_Framework_Changes#Python) have been updated.
  ## Changes

Added the ability control plot normalization from python. A distribution keyword argument has been added to the python plotSpectrum function and the function exposed to qti.sip has been modified to reflect this change.
## Testing

Code Review and run the following script (compare with doing this by hand):

``` python
ws = Load(Filename="MUSR00022725.nxs")
plotSpectrum(source="ws", indices= 0, distribution=DistrFlag.DistrTrue)
plotSpectrum(source="ws", indices= 0, distribution=DistrFlag.DistrFalse)
```

### CODE REVIEW

**Comment by LamarMoore** [comment]
plotBin does not allow users to select normalization. This is unnecessary and misleading to the user so I will remove it.

**Comment by rosswhitfield** [comment]
This is causing the RHEL6 builds to get stuck during compiling, they sit around for hours not advancing and need to be manually killed. I did a **clean** rebuild to see if it fixes the problem.

**Comment by picatess** [comment]
@LamarMoore  You test script does not run.  `DistributionFlag` does not seem to be exposed in Python

**Comment by picatess** [comment]
Code looks fine. The example works and produces a graph with bin widht normalization enabled and a graph where it is disabled. Same as doing it by hand. Happy to merge.

**Pull request merged**
