### PR TITLE
Add directions on getting errors from fit

### PR DESCRIPTION
**Pull request by keeeto**
**Description of work.**

**Report to:** James Lord

**To test:**

Build the html docs and check that the section **Errors** in `concepts/FitFunctionsInPython.html` makes sense.

Fixes fourum post http://forum.mantidproject.org/t/error-values-from-a-fit/457/2.
*There is no associated issue.*

*This does not require release notes* because it is documentation.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by mantid-roman** [comment]
`p.getError('A1')` should also work. I think this should be mentioned as people prefer to use parameter names.

**Review by mantid-roman — CHANGES_REQUESTED** [review]

**Review by mantid-roman — APPROVED** [review]

**Comment by peterfpeterson** [comment]
I know calling them "errors" is common, but I'd rather we refer to it as uncertainties or standard deviations.

**Comment by keeeto** [comment]
Yes, uncertainties is a less loaded term, I have no strong feelings either way. What would a user be looking for when searching the documentation/randomly typing potential method names? If we do decide to change the docs, should we also change the method name?

**Comment by keeeto** [comment]
Well if I'd looked properly I'd have seen this was merged before the comment. Post-merge github comment sections seem like a fitting forum for lamenting the state of things that are impossible change. The medium is the message.

**Pull request merged**
