### PR TITLE
Update available fit functions on Function Q interface according to data

### LINKED ISSUE #37671: EISF and Width functions are all available after removing last Width or EISF
**Reported by:** Spencer

**Description**
All the fit functions in the Function(Q) tab of QENS Fitting are available after adding a width and an EISF, and then removing one of these spectra. We should expect that the function list dynamically updates when the last EISF or the last width has been removed.

**Steps to reproduce**
1. Open Inelastic QENS Fitting
2. Go to Function(Q) tab
3. Load the following dataset
4. Add an EISF and Width spectra
5. All functions should be available
6. Remove the EISF
7. All functions are still available. Only the functions for Width should be available
8. The same is the case if you keep EISF and remove the Width spectra.

### PR DESCRIPTION
**Pull request by adriazalvarez**
### Description of work
Fixes the issue described in #37671 . Whenever new data is added to  the data table in the Function (Q) tab of the QENS Fitting interface, the list of available fit functions in the fit property browser should be updated dynamically to show which functions are available to fit according to the data on the table. This should be updated also whenever data is removed from the table. 

#### Summary of work
In order to add this feature, I have added a virtual function to the FitDataPresenter class that is redefined in the derived classes (in this case `FunctionQDataPresenter`) and that updates the available functions list from the remove handle in the `FitTab` class when the signal for removing data is sent. 
I have refactored the function `chooseFunctionQFunctions` on the `FunctionQDataPresenter` to be able to update properly when data is removed from the table (it was only implemented for added data). 

Fixes #37671 . 

### To test:
Follow the test instructions of #37671, making sure now that the available functions are updated appropiately (the available functions for `EISF` data all start with the prefix `EISF`). 

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by MohamedAlmaki — CHANGES_REQUESTED** [review]
When adding both width and ESIF spectra and then deleting the ESIF spectra, the fit functions remain as "all" instead of just the "Width" functions. However, deleting the width spectra works fine and the functions are updated with just "ESIF" functions. Also, adding just "Width" spectra works fine and updates the function list with just the "Width" list

**Comment by robertapplin** [comment]
Thanks for testing this @MohamedAlmaki. It should be ready for another look!

**Comment by MohamedAlmaki** [comment]
Thanks for the changes, it works as expected now. I will approve once the CI is green, I think these failures are unrelated the PR

**Comment by MohamedAlmaki** [comment]
@robertapplin there is a minor sign warning issue, could you please fix it

**Comment by thomashampson** [comment]
disabled auto-merge so this doesn't miss out on getting in to `release-next`

**Review by MohamedAlmaki — DISMISSED** [review]
Happy to approve, thanks for the changes

**Review by MohamedAlmaki — APPROVED** [review]

**Pull request merged**
