### PR TITLE
clang-tidy: modernize-use-default

### LINKED ISSUE #12925: Finalize cleanup of copy and assigment constructors of Workspace and derived classes
The cleanup in #12917 cannot be completed with the current compilers versions (VS2012 and maybe also the old gcc on RHEL6), since they do not understand the `default` keyword.

The following needs to be done: In cases where the compiler-generated version of a copy constructor is correct, the manual implementation must be removed, and the copy constructor declared with `= default`. Why? It reduces the risk for bugs.
Similarly the assignment operator, which is not implemented right now could also be declared `= default`, if desired, otherwise as `= delete`.
For example:

```cxx
Workspace(const Workspace &other) = default;
Workspace &operator=(const Workspace &other) = default;
```

The following classes are affected (please verify!):
- `Workspace`
- `IMDWorkspace`
- `RebinnedOutput`
- `SpecialWorkspace2D`
- `MaskWorkspace`
- `GroupingWorkspace`
- `OffsetsWorkspace`
- put `IMDEventWorkspace() = default;`
- (WIP)

The following classes are *not* affected (the copy constructor actually *needs* a manual implementation):
- (WIP)

`MDEventWorkspace` needs to define a proper protected `operator=` (either no definition, or a correct one). The Windows build seems to have trouble with the template and complains that there is no definition (generates a warning, not an error) if we write this:
```cxx
  /// Protected copy assignment operator. Assignment not implemented.
  MDEventWorkspace<MDE, nd> &operator=(const MDEventWorkspace<MDE, nd> &other);
```
As a temporary workaround there is a definition that throws an error.

### PR DESCRIPTION
**Pull request by quantumsteve**
This fixes #12925.

This uses clang-tidy's modernize-use-default tool to replace default bodies of special member functions with `= default;`. I then did quite a bit of cleanup, specifically moving `= default;` into the header` and deleting these member function when they would otherwise by generated by the compiler.

code review: There are a number of classes with private virtual destructors. Double-check I didn't delete any of those, potentially making the destructor public.

testing: If there are missing symbols, the build should fail. I'm not sure how great our test coverage of constructors is. 

Gatekeepers: This PR doesn't handle incremental builds well.The master-incremental pipeline may temporarily fail after this is merged.

### CODE REVIEW

**Comment by quantumsteve** [comment]
@SimonHeybrock While I still plan to do more work on this branch and double-check my changes before it is ready to be merged, I would appreciate your comments and suggestions anytime.

**Comment by SimonHeybrock** [comment]
Looking for a good diff tool for reviewing this...

**Comment by SimonHeybrock** [comment]
Ok, not sure how we are going to discuss all this, I'll just start writing some things here, but maybe we can find a better way:

Algorithm.h `class CancelException`: initialize `outMessage` directly where it is defined, can then remove all constructors and assignment operators.

**Comment by SimonHeybrock** [comment]
AlgorithmHasProperty.h:
- remove useless(?) declaration of default constructor

**Comment by SimonHeybrock** [comment]
The comment about moving deleted copy/assignment to public and removing the doxygen comments goes for all classes, I will not comment on this explicitly anymore.

**Comment by SimonHeybrock** [comment]
Are the macros in `ClassMacros.h` still useful? Now with `default` and `delete` it would maybe be more obvious to just put that directly?

**Comment by SimonHeybrock** [comment]
FunctionFactory.h: You removed the private destructor, whereas in other singletons you made it `=default`.

FunctionParameterDecorator.h: Can remove default constructor?

**Comment by SimonHeybrock** [comment]
HistoryItem.h: You removed a virtual destructor!

**Comment by SimonHeybrock** [comment]
IConstraint.h:
- can remove default constructor?
- Attention: the base class `ParameterReference` does not have a virtual destructor. As far as I can see there is no case where we delete a child class instance via this first base class, so it is probably fine, but a bit dangerous maybe?

**Comment by SimonHeybrock** [comment]
Your changes also seem to deal with #12925. :+1:

**Comment by SimonHeybrock** [comment]
IFunctionWithLocation.h: remove destructor? You removed it in another file where it had the same comment, maybe that warning is now obsolete?

**Comment by SimonHeybrock** [comment]
IPeaksWorkspace.h: can make copy constructor default.

**Comment by SimonHeybrock** [comment]
SingleValueParameterParser.h:
- move copy constructor inside class body?
- there is a destructor at the very bottom of the file that can also be defaulted (or removed, actually)

**Comment by SimonHeybrock** [comment]
CatalogFactory.h: default the default constructor?

**Comment by SimonHeybrock** [comment]
IMDHistoWorkspace: can default the constructor?

**Comment by SimonHeybrock** [comment]
ImplicitFunctionParserFactory.cpp: Why was the dynamic cast with the Poco stuff removed? Is this a merging issues?

**Comment by SimonHeybrock** [comment]
LiveListenerFactoryImpl: default constructor?
LogManager: default constructor? You defaulted the copy, do some with assignment!

**Comment by SimonHeybrock** [comment]
Run.h: probably can remove all constructors/assignments.

**Comment by SimonHeybrock** [comment]
TransformScaleFactoryImpl: constructor.
Workspace: constructor.

(Note: API directory done)

**Comment by SimonHeybrock** [comment]
CalculateTransmission.cpp: another merge issue with casting changes?

**Comment by SimonHeybrock** [comment]
MayersSampleCorrectionStrategy: move defaulted destructor to header.

**Comment by SimonHeybrock** [comment]
Note: Algorithms directory done.

**Comment by SimonHeybrock** [comment]
PeakClusterProjection.h: delete copy and assign.

**Comment by SimonHeybrock** [comment]
Merging issue in GoniometerAnglesFromPhiRotation.cpp

**Comment by SimonHeybrock** [comment]
HardThresholdBackground: default copy and assignment?

**Comment by SimonHeybrock** [comment]
IkedaCarpenterPV: constructor.
ProductFunction: constructor.

**Comment by SimonHeybrock** [comment]
Merge issue in LeBailFit.cpp.

**Comment by SimonHeybrock** [comment]
FlatBackground: constructor.
ThermalNeutronBk2BkExpAlpha: constructor.
ThermalNeutronBk2BkExpBeta: constructor.
ThermalNeutronBk2BkExpSigma: constructor.
ThermalNeutronDtoTOFFunction: constructor.

**Comment by SimonHeybrock** [comment]
Events.h: You made the TofEvent destructor virtual, but these classes to not seem to be used polymorphically?

**Comment by SimonHeybrock** [comment]
MDBin.h: remove destructor?
MDDimensionStats.h: remove destructor?
MDGridBox: remove destructor?

**Comment by SimonHeybrock** [comment]
Merging issue:
EventList.cpp
FractionalRebinning.cpp?

**Comment by SimonHeybrock** [comment]
GroupingWorkspace: constructor
Histogram1D: constructor
MaskWorkspace: constructor
NoShape: constructor
OffsetsWorkspace: constructor

**Comment by SimonHeybrock** [comment]
CenteringGroupCreatorImpl: public destructor not necessary?
ConcretePeakTransformFactory: constructor not necessary?
CrystalStructure: public destructor not necessary?

**Comment by SimonHeybrock** [comment]
There are a few classes like PeakTranformQSample that have a clone method. You deleted the public copy/assignment (ok), but I guess it might make more sense to have them private (i.e., that was a problem in the existing implementation)?

**Comment by SimonHeybrock** [comment]
PointGroupGenerator: remove destructor.
ReflectionCondition: remove constructor.
ReflectionGenerator: remove destructor.
StructureFactorCalculator: remove constructor.
SymmetryElementFactory: remove constructors in several child classes.
SymmetryOperationSymbolParser: remove destructor
ICopAssembly: remove constructor, and why is assignment private/deleted but copy is public (implicit)?
XMLInstrumentParameter: remove destructor.

**Comment by SimonHeybrock** [comment]
MDHistoDimensionBuilder: remove destructor.
BnId: remove destructor.
Line: remove destructor?
Surce: should assignment op. be declared `= delete`, or implemented via the copy?

**Comment by SimonHeybrock** [comment]
Merging issue:
IndexingUtils.cpp
Instrument.cpp

**Comment by SimonHeybrock** [comment]
Object.cpp: destructor in source (remove?)
RuleItems.cpp: `Union` and `CompGrp` default constructors can be made `= default`?

**Comment by SimonHeybrock** [comment]
Why was the test in QuadrilateralTest.h removed?

**Comment by SimonHeybrock** [comment]
CatalogSearchParam: remove destructor
CErrorHandling: remove constructor and destructor
SessionException: remove destructor
ICATPortBindingProxy: destructor in cpp? (twice)
ArrayProperty: remove copy and destructor?

**Comment by SimonHeybrock** [comment]
Not sure I understand Chainable.h: destructor is `= 0`, but then declared default below?

**Comment by SimonHeybrock** [comment]
IPropertySettings: remove constructor?
IValidator: remove constructor?
AbstractInstantiator/Instantiator: remove constructors?

**Comment by SimonHeybrock** [comment]
brute.cpp, ANNbruteForce: destructor

Merging issue in MagneticIon.cpp and Matrix.cpp and NetworkProxyOSX.cpp and TimeSeriesProperty.cpp

ChebyshevPolyFit: destructor
UnitFactoryImpl: remove constructor?

Note: Kernel done (`git difftool is working alphabetically through directories).

**Comment by SimonHeybrock** [comment]
Merge issue:

ADARAPackets.cpp
ISISHistoDataListener.cpp

**Comment by SimonHeybrock** [comment]
Integrate3DEvents: remove destructor.
ModeratorChopperResolution: remove destructor.
Vector3DParameterParser: remove constructor and destructor

**Comment by SimonHeybrock** [comment]
InputHistoryImpl: default destructor?

**Comment by SimonHeybrock** [comment]
StandardView: Check for `hasActiveSource` removed... merge issue?

**Comment by SimonHeybrock** [comment]
So, that's it. This is all moving in a very good direction.

Maybe next time we do this we split it up by module? That would make reviewing and merging easier.

**Comment by quantumsteve** [comment]
I fixed the with OS X warning in PR #15405.

**Comment by quantumsteve** [comment]
In Surface.h, I set the assignment op. to address `= default to fix a build error on Windows.

**Comment by SimonHeybrock** [comment]
Note: I incrementally reviewed the changes since the first review up until here.

**Comment by SimonHeybrock** [comment]
> I removed the consts so that I could use the implicit copy assignment operator in Framework/API/inc/MantidAPI/LogManager.h. Should I revert both changes?

No, that is fine, I was just wondering because I did not get the context from the diff.

**Pull request merged**
