### PR TITLE
Fix parameter map segfault

### PR DESCRIPTION
**Pull request by eXeC64**
This is for trac ticket [#11749](http://trac.mantidproject.org/mantid/ticket/11749)

Running this script crashes mantid (data available from `babylon/Owen Arnold/for_harry`)

``` python
mat_ws = Load(Filename='MAP05935_ei34.nxspe')
LoadInstrument(mat_ws, InstrumentName='MAPS')
SaveNexusProcessed(mat_ws, Filename="this_will_crash.nxs")
```

The reason for the crash was because `ExperimentInfo::m_parmap` was being filled with parameters by `LoadNXSPE`, and then having its instrument changed to a non-parameterised instrument. The workspace was moving from being parameterised to non-parameterised. The problem is `m_parmap` was not being cleared, which was keeping many raw pointers to freed components. These were then read from when trying to save the nexus file, resulting in a segfault.

**Testing**:
This pull request is marked as `core`, as it affects ExperimentInfo's parameter map directly, and we are very close to release. You should be absolutely certain that this does not break any existing functionality before merging.

### CODE REVIEW

**Comment by eXeC64** [comment]
The reason the system test was segfaulting was because it fetched const reference to the parameter map and *then* performed setInstrument, which replaces the internal parameter map pointer. The reference is then to freed memory, which is not good™. The easy fix in this case is just to get the reference after, but it's a very easy mistake to make again.

We should have a good think about what we return from `instrumentParameters` to prevent this happening again, as it's a nasty error that's not immediately obvious. My first reaction is to instead have `instrumentParameters` return a `ParameterMap_const_sptr&`, so that the reference stays up to date if the internal parameter map changes.

**Comment by eXeC64** [comment]
The windows build failure is unrelated. `isis-ndw1185` is playing up.

**Comment by OwenArnold** [comment]
As this is Core and as it's a little tricky to get into the state where this becomes an issue so close to the release. I'm moving this to 3.5.

**Comment by eXeC64** [comment]
@mantid-roman 
[This](https://github.com/mantidproject/mantid/blob/11749_segfault_in_parametermap_asstring/Code/Mantid/Framework/API/src/ExperimentInfo.cpp#L167-L191) is the currently problematic area.

If you set the instrument after fetching this reference you have a reference to freed memory, causing a crash when used.

This originally comes in in 5e030f1

Do you know why this needs to be copy-on-write? See [this comment](https://github.com/mantidproject/mantid/pull/751#issuecomment-102070166) for my suggestion for resolving this. Returning a reference to the shared pointer means that our reference keeps pointing to the right thing if the shared pointer changes.

**Pull request merged**
