### PR TITLE
speed wand2 reduction for event filtering mode

### PR DESCRIPTION
**Pull request by Kvieta1990**
This is a companion PR to [https://github.com/mantidproject/mantid/pull/34754](https://github.com/mantidproject/mantid/pull/34754).

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by sf1919** [comment]
This one keeps failing on cppcheck because it's looking for a missing file. I think perhaps #34685 which adds the file needs to be cherry picked into the ornl-next branch? @peterfpeterson

**Comment by Kvieta1990** [comment]
@sf1919 It seems that the cppcheck has passed. weird... but `conda osx` and two other relevant tests keep failing complaining about workbench plot stuff which I don't think this pr has something to do with. don't understand those errors and I cannot see why another pr was passing on this.

**Comment by sf1919** [comment]
the plotscriptgenerator tests it keeps failing seem to have something to do with the `axes.py` file. This was last updated by commit #34207 which went into main recently. Could this be affecting your PR?

**Comment by Kvieta1990** [comment]
> the plotscriptgenerator tests it keeps failing seem to have something to do with the `axes.py` file. This was last updated by commit #34207 which went into main recently. Could this be affecting your PR?

That is a bit weird, since the PR to the `main` branch passed all the tests. Given the complexity, I am going to withdraw this PR and probably start a new one - I am sure the changes I put in is nothing to do with the plot stuff so if the test for current `ornl-next` branch is passing, my PR should be passing without problems.

**Pull request closed without merging**
