### PR TITLE
Fix index out of range errors when data is transposed in ImageInfoWidget

### LINKED ISSUE #31675: Index out of range error in slice viewer with transposed axis
### Expected behavior
- Transposed workspaces (where TOF is in Y) should be handled

### Actual behavior
- Multiple index errors are produced as the mouse is moved
- On Mac OSX swapping axis does not update the button, this is likely a missing call to `paint` or equivalent when the button changes

### Steps to reproduce the behavior
- Load `CNCS_23937` or any workspace where the number of spectra != TOF range
- Set TOF into `y` and spectra to `x`
- Move mouse into top right, notice on the table that spectra and TOF are flipped incorrectly
- When your mouse goes OOB relative to the original (untransposed axis) you will get errors

This affects both Event and Histogram workspaces 
### Platforms affected
All

### PR DESCRIPTION
**Pull request by joseph-torsney**
Fixes an error that occurred primarily in the SliceViewer when the ImageInfoWidget receives data at the current cursor position on transposed data. TOF and Spectra info were displayed in the incorrect cells in the widget, and on data where the size of one axis did not match the other, `Index out of range` errors would occur

**To test:**
1. Load a matrix workspace e.g. `CNCS_23937` and open the SliceViewer
3. Hover over the image, ensuring there are no errors in the log and the image info is correct, both when the data is transposed and not transposed.
4. Try steps 1-2 with MD data, e.g. 
```
ws = CreateMDWorkspace(Dimensions='3', Extents='-5,5,-2,2,-6,6',
                       Names='Q_lab_x,Q_lab_y,Q_lab_z', Units='U,U,U',
                       Frames='QLab,QLab,QLab',
                       SplitInto='2', SplitThreshold='50')
```

Fixes #31675. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by RichardWaiteSTFC — COMMENTED** [review]
Unfortunately it looks like this breaks the behaviour of the imageInfo widget for MD objects - try the above tests with this workspace 
```
ws = CreateMDWorkspace(Dimensions='3', Extents='-5,5,-2,2,-6,6',
                       Names='Q_lab_x,Q_lab_y,Q_lab_z', Units='U,U,U',
                       Frames='QLab,QLab,QLab',
                       SplitInto='2', SplitThreshold='50')
```

**Comment by martyngigg** [comment]
I've removed Richard from the assignment here as he's away this week. As this is a bug I think we should investigate it for the release.

**Comment by Harrietbrown** [comment]
Checking over I can not see any issues with the image info in the workspace @RichardWaiteSTFC said they found a problem. Am I missing something since there has not been a commit since then.

**Review by Harrietbrown — DISMISSED** [review]
Fantastic, this has fixed that other issue now. good to have it in for the release. Good Job!

**Review by DanielMurphy22 — APPROVED** [review]
Re-approving after fixing release note conflict

**Review by DavidFair — APPROVED** [review]

**Pull request merged**
