### PR TITLE
Review RRO Workflow diagram

### LINKED ISSUE #15534: Review ReflectometryReductionOne workflow diagram
While testing #15075 I noticed a couple of issues in the workflow diagram:
- Looking at the diagram it seems that we only apply transmission corrections if the input workspace is not in `lambda` (which I think is not correct)
- I find the transmission correction process a bit unclear
- The last step, after `ConvertUnits` should be `RotateSource` again (we are rotating the source back to its original position).

This issue is to review the workflow diagram and update it if necessary.

### PR DESCRIPTION
**Pull request by MattKing06**
After a series of changes the workflow diagram for the ReflectometryReductionOne algorithm does not match with the flow of code. This PR aims to change the workflow diagram so that it is representative of the current code for the algorithm.

**To test:**
- Build Qt-help documentation for ReflectometryReductionOne-v1
- Step through the workflow and see that it represents the flow in the code.

Fixes #15534 

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
Just two minor suggestions:
- This is just a personal preference: could we make the new figures a bit smaller so that font size in the figures is similar to the font size in the maintext?
- In the workflow diagram, before we rotate the source back to its original position, should we ask "WAS source in correct position" instead of "IS source in correct position"? The reason is that when we rotate the source the first time, we are moving it to the "correct" position, so the answer to the second "Is source in correct position" is "Yes".

**Comment by MattKing06** [comment]
@raquelalvarezbanos 

- I'm not quite sure how to change the text size of the objects in the workflow diagram, I'll have to look into this
- I agree that the second decision should be changed, however instead of "was source in correct position" how do you feel about having a decision saying "was source rotated?" with the "Yes" branch resulting in the re-rotation and the "No" branch leading to the OutputWorkspace

**Comment by raquelalvarezbanos** [comment]
No, no, I didn't mean to suggest changing the workflow diagram but the size of the new figures CurrentExperimentSetupForReflectometry.png and RotatedExperimentSetupForReflectometry.png. If we make them a bit smaller the text in the figures will match our current text size in the main text. I just think they are a bit big, but again this is just a personal preference.

**Comment by MattKing06** [comment]
Ahh I see now, yes I agree they should be smaller! thanks :+1:

**Comment by raquelalvarezbanos** [comment]
The workflow diagram looks good, there is also a new section explaining the rotation of the source.

:shipit:

**Comment by FedeMPouzols** [comment]
Nice figures. It seems that this doc improvement was really needed.

**Pull request merged**
