### PR TITLE
Add a save option for state the ISIS SANS GUI

### LINKED ISSUE #20294: Add option to save state on the ISIS SANS GUI
In this issue we will add a simple functionality to save out the state of a a reduction to a `JSON` file which can be specified by the user. This will aide the communication between the developer and the instrument scientists.

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Fixes #20294

~~**Do not merge or test before #20229 has been merged**~~

This PR adds a save option for the ISIS SANS state of a particular row.

**To test:**

Please find test data here: smb://olympic/babylon5/Scratch/Anton/GUI_TEST

1. Open the ISIS SANS v2 experimental interface
1. Select `SANS2D` as the instrument (below the data table)
2. For the user file load: USER_SANS2D_154E_2p4_4m_M3_Xpress_8mm_SampleChanger_FRONT.txt
3. For the batch file load: batch_file.csv
4. Go the `Settings>State Diagnostic` tab. You should see a tree view populated with data
5. At the bottom of the tab select a save location and press save.
    * Confirm that a `json` file with the state has been saved out
6. Just place gibberish in the to-save line edit field and press save.
    * Confirm that a warning is shown.

**Release Notes** 
Not required, the GUI is being released in this cycle

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gvardany** [comment]
I could give a spin, any chance you can make the test data files accessible outside?

**Comment by NickDraper** [comment]
Noticed during testing

image

**Comment by NickDraper** [comment]
Minor point but
image

If you enter a filename without extension in the browse dialog, it remains without any extension here, but .json is added to the file saved.  This box should show the full file plus extension.

**Comment by NickDraper** [comment]
If you are careful with file locations this works fine, but ...

If the files in the Batch_file.csv are not in you data search directories (even if they were in the same directory as the batch file) then problems occur:

- The reduction table appears to fill up ok
- You get these entries in the log

```
There was a bad entry for row 0. See here for more details: StateMask: The provided inputs are illegal. Please see: {"Mask file not found.": "mask_file: ['MASK_SANS2D_REAR_Edges_16Mar2015.xml', 'MASK_SANS2D_FRONT_Edges_16Mar2015.xml', 'MASK_SANS2D_REAR_Bottom_3_tubes_16May2014.xml', 'MASK_SANS2D_BOTH_Extras_24Mar2015.xml', 'MASK_SANS2D_beam_stop_4m_x_100mm_2July2015_medium_beamstop.xml', 'MASK_SANS2D_REAR_module2_tube12.xml']\nMakes sure that the mask file is in your path"}
Loading of the batch file failed. See here for more details: There was a bad entry for row 0. See here for more details: StateMask: The provided inputs are illegal. Please see: {"Mask file not found.": "mask_file: ['MASK_SANS2D_REAR_Edges_16Mar2015.xml', 'MASK_SANS2D_FRONT_Edges_16Mar2015.xml', 'MASK_SANS2D_REAR_Bottom_3_tubes_16May2014.xml', 'MASK_SANS2D_BOTH_Extras_24Mar2015.xml', 'MASK_SANS2D_beam_stop_4m_x_100mm_2July2015_medium_beamstop.xml', 'MASK_SANS2D_REAR_module2_tube12.xml']\nMakes sure that the mask file is in your path"}
```
- The State Diagnostic table will be empty

**Review by NickDraper — CHANGES_REQUESTED** [review]
Overall tested ok, but found a issues that needs addressing

**Comment by AntonPiccardoSelg** [comment]
@NickDraper Regarding the batch file location: This behaviour is identical to ISIS SANS V1. In principal we can add the batch file path to the data search directory, but would this be to intrusive?

**Comment by AntonPiccardoSelg** [comment]
@NickDraper 

I have 
* highlighted the *Runs* selection in the side bar on start up
* ensured that only .json files can be saved. This includes
   * The file filter has been set to `*.json`
   * Other selected file formats will be changed to .json in the line edit field (at the latest when `Save` has been pressed).
* added a clearer hint that the data path needs to be added to the Mantid search directories if data cannot be found.

**Review by NickDraper — APPROVED** [review]

**Comment by NickDraper** [comment]
Good to go

**Pull request merged**
