### PR TITLE
Fix docstring directives for old sip definitions.

### PR DESCRIPTION
**Pull request by martyngigg**
Description of work.

Fix sip definitions for newer sip versions.

**To test:**

Most easily tested on macOS with the latest version of sip If the build passes then this is good.

*No issue*

**Release Notes** 

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by keeeto** [comment]
So using `sip` 4.19.7 and `pyqt` 5.10

I got the following:
```
/Users/keithbutler/src/mantid-git/build/qt/python/mantidqt/widgets/sip_widgetscoreqt4part0.cpp:997:5: error: cannot
      initialize a member subobject of type 'sipAssignFunc' (aka 'void (*)(void *, long, const void *)') with an lvalue of
      type 'void (void *, Py_ssize_t, void *)' (aka 'void (void *, long, void *)'): type mismatch at 3rd parameter
      ('const void *' vs 'void *')
    assign_QHash_0100QString_0100QString,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/keithbutler/src/mantid-git/build/qt/python/mantidqt/widgets/sip_widgetscoreqt4part0.cpp:11568:5: error: cannot
      initialize a member subobject of type 'sipAssignFunc' (aka 'void (*)(void *, long, const void *)') with an lvalue of
      type 'void (void *, Py_ssize_t, void *)' (aka 'void (void *, long, void *)'): type mismatch at 3rd parameter
      ('const void *' vs 'void *')
    assign_InterfaceManager
```

**Comment by samueljackson92** [comment]
@keeeto This now compiles for me. Can you retest at some point to confirm it's fixed for you?

**Comment by keeeto** [comment]
I'm afraid that I am still getting the same error as above. I have done a `make clean`, re-run `cmake` (which works), then run a `make`. 
@samueljackson92 what are the versions of `pyqt` and `sip` that you get when you run `brew info`?
I have the following
```
sip: stable 4.19.7 (bottled), HEAD
Tool to create Python bindings for C and C++ libraries
https://www.riverbankcomputing.com/software/sip/intro
/usr/local/Cellar/sip/4.19.3 (10 files, 832KB)
  Built from source
/usr/local/Cellar/sip/4.19.4 (10 files, 840.5KB)
  Built from source
/usr/local/Cellar/sip/4.19.7 (10 files, 840.5KB) *
  Built from source
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/sip.rb
==> Dependencies
Recommended: python ✔, python3 ✔
==> Options
--without-python
	Build without python support
--without-python3
	Build without python3 support
--HEAD
	Install HEAD version
==> Caveats
The sip-dir for Python is /usr/local/share/sip.
```
and
```
pyqt: stable 5.10 (bottled)
Python bindings for v5 of Qt
https://www.riverbankcomputing.com/software/pyqt/download5
/usr/local/Cellar/pyqt/5.9 (961 files, 44MB)
  Built from source
/usr/local/Cellar/pyqt/5.10 (984 files, 44.9MB) *
  Poured from bottle on 2018-01-25 at 21:03:20
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pyqt.rb
==> Dependencies
Required: qt ✔, sip ✔
Recommended: python ✔, python3 ✔
==> Options
--with-debug
	Build with debug symbols
--with-docs
	Install HTML documentation and python examples
--without-python
	Build without python support
--without-python3
	Build without python3 support
```

**Comment by martyngigg** [comment]
@keeeto Could you try running:
```
cd /Users/keithbutler/src/mantid-git/build
rm qt/python/mantidqt/widgets/sip_widgetscoreqt4part0.cpp
make
```
and seeing what happens?

**Comment by keeeto** [comment]
Hmm, same issue. I guess that sip_widgetscoreqt4part0.cpp is being generated as part of the build, as I removed it, but the same error occurs.

**Comment by martyngigg** [comment]
Yep, it's auto generated from the input `.sip` file. Can you try `rm qt/python/mantidqt/widgets/_widgetscoreqt4.sip` and then `make`. I think something is not being rebuilt properly.

**Comment by keeeto** [comment]
Ah, okay. That's cleared up one problem. Now I only get a problem with `qt/python/mantidqt/widgets/sip_widgetscoreqt5part0.cpp`
I tried `rm qt/python/mantidqt/widgets/_widgetscoreqt5.sip`, but now the build fails after complaining that it requires `_widgetscoreqt5.sip`.

**Review by rosswhitfield — APPROVED** [review]
This fixes the build for me on Arch Linux with sip `4.19.7`. But this should wait until an OSX user also **Approves** the PR.

**Review by keeeto — APPROVED** [review]
This now builds on OSX with up to date `sip 4.19.7` .

**Pull request merged**
