### PR TITLE
Use mantid fitting in IntegratePeaks1DProfile (instead of scipy as was too slow)

### LINKED ISSUE #37526: Add option to use mantid fitting in IntegratePEaks1DProfile
**Is your feature request related to a problem? Please describe.**
Mantid fitting can be flakier than scipy but is a lot quicker!

**Describe the solution you'd like**
The fitting function is already based on mantid composite function objects, this issue would be to add a new option to fit using the mantid `Fit` algorithm instead of `scipy.minimize` - I think for now let's only support cost functions  `RSq`, `ChiSq` when fitting with mantid as I think there is a bug with the Poisson MLE

### PR DESCRIPTION
**Pull request by RichardWaiteSTFC**
### Description of work

Use mantid fitting in `IntegratePeaks1DProfile` for speed.
Previously scipy fitting used, but the only minimizer that worked robustly was a simplex/Nelder-Mead method which was very slow (slow to converge, lots of function evaluations per iteration).
The original issue was to add mantid fitting as an option, but the mantid fitting with the relatively new option `StepSizeMethod="Sqrt epsilon"`  seems more robust than scipy fitting and orders of magnitude quicker. So in order to reduce duplication the scipy fitting has been completely replaced by mantid `Fit` algorithm.

In order to do this have also exposed a couple of IPEakFunction methods to python
- `getWidthParameterName`
- `getCentreParameterName`

Which are used to construct function parameter constraints.

Fixes #37526 

**Report to:** Nick Funnell (LMX/PEARL)

### To test:

(1) Run this script

```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

ws  =Load(Filename=r'C:/Users/xhg73778/Desktop/SXD34361.nxs', OutputWorkspace='SXD34361')
peaks = FindSXPeaksConvolve(InputWorkspace=ws, PeakFindingStrategy="IOverSigma", NCols=7, NRows=7, NFWHM=6, ThresholdIoverSigma=5)

profile_kwargs = {"GetNBinsFromBackToBackParams": True, "NFWHM": 6,
                "CostFunction": "Poisson", "FixPeakParameters": "A",
                "FractionalChangeDSpacing": 0.05,
                "IntegrateIfOnEdge": False,
                "LorentzCorrection": True,
                "IOverSigmaThreshold": 2.5,
                'BackgroundFunction': 'FlatBackground',         
                "OutputFile": "SXD34361_profile_testpdf"}

peaks_int = IntegratePeaks1DProfile(ws, peaks_small, **profile_kwargs)
```

(2) Check the pdf file, peaks should be integrated well, with peak shape in TOF spectrum a good fit and most intense pixels included in peak mask

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by GuiMacielPereira — CHANGES_REQUESTED** [review]
I've tried to run the test script on Linux but unfortunately it fails with a GSL error:

```
Load-[Notice] Load started
Load-[Notice] Load successful, Duration 2.75 seconds
FindSXPeaksConvolve-[Notice] FindSXPeaksConvolve started
Python-[Notice] Found 27 peaks in bank1
Python-[Notice] Found 27 peaks in bank2
Python-[Notice] Found 38 peaks in bank3
Python-[Notice] Found 54 peaks in bank4
Python-[Notice] Found 34 peaks in bank5
Python-[Notice] Found 21 peaks in bank6
Python-[Notice] Found 26 peaks in bank7
Python-[Warning] invalid value encountered in sqrt

Python-[Notice] Found 34 peaks in bank8
Python-[Notice] Found 29 peaks in bank9
Python-[Notice] Found 31 peaks in bank10
Python-[Notice] Found 21 peaks in bank11
FindSXPeaksConvolve-[Notice] FindSXPeaksConvolve successful, Duration 21.06 seconds
IntegratePeaks1DProfile-[Notice] IntegratePeaks1DProfile started
gsl: simplex.c:288: ERROR: non-finite function value encountered
Default GSL error handler invoked.
Received signal: SIGABRT
Aborted (core dumped)
```

**Comment by RichardWaiteSTFC** [comment]
> I've tried to run the test script on Linux but unfortunately it fails with a GSL error:
> 
> ```
> Load-[Notice] Load started
> Load-[Notice] Load successful, Duration 2.75 seconds
> FindSXPeaksConvolve-[Notice] FindSXPeaksConvolve started
> Python-[Notice] Found 27 peaks in bank1
> Python-[Notice] Found 27 peaks in bank2
> Python-[Notice] Found 38 peaks in bank3
> Python-[Notice] Found 54 peaks in bank4
> Python-[Notice] Found 34 peaks in bank5
> Python-[Notice] Found 21 peaks in bank6
> Python-[Notice] Found 26 peaks in bank7
> Python-[Warning] invalid value encountered in sqrt
> 
> Python-[Notice] Found 34 peaks in bank8
> Python-[Notice] Found 29 peaks in bank9
> Python-[Notice] Found 31 peaks in bank10
> Python-[Notice] Found 21 peaks in bank11
> FindSXPeaksConvolve-[Notice] FindSXPeaksConvolve successful, Duration 21.06 seconds
> IntegratePeaks1DProfile-[Notice] IntegratePeaks1DProfile started
> gsl: simplex.c:288: ERROR: non-finite function value encountered
> Default GSL error handler invoked.
> Received signal: SIGABRT
> Aborted (core dumped)
> ```

Thanks, I think that error comes from GSL, so there's not much more I can do than add a try/catch!

**Review by GuiMacielPereira — DISMISSED** [review]
The try/catch block successfully keeps the fit running for other spectrum numbers if any of the spectrum fails. In the example workspace provided, about 7 spectra out of the 342 spectra seem to fail to fit. I checked the these spectra and they look more noisy than usual so that is likely what is causing it.

I think this is anyway outweighed by the massive speed up of this change. Just because I was curious I tried to run the original algorithm and the predicted time was more than an hour, whilst this version runs on just over a minute. Great stuff!

**Review by GuiMacielPereira — APPROVED** [review]
Code looks good, massive improvement to the runtime (see my comment above) and all tests pass :+1:

**Pull request merged**
