### PR TITLE
ObservingViews now delete themselves on close

### LINKED ISSUE #24643: ObservingViews don't delete themselves on close
### Expected behavior
Closing the Matrix/Table displays or instrument view should delete the QWidget completely

### Actual behavior
It doens't

### Test script
```python
# The following line helps with future compatibility with Python 3
# print must now be used as a function, e.g print('Hello','World')
from __future__ import (absolute_import, division, print_function, unicode_literals)

# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *

import matplotlib.pyplot as plt

import numpy as np
from mantidqt.plotting.functions import plot
import sys

table = Load("SavedTableWorkspace.nxs")
matrix = Load("irs26173_graphite002_red.nxs")

from qtpy.QtWidgets import QApplication

a = QApplication.topLevelWidgets()
t = [x for x in a if "WorkspaceDisplay" in str(type(x))][0]
print("Num widgets {}".format(len(a)))

print(sys.getrefcount(t))
import gc
gc.collect()
print(t)
view = gc.get_referents(t)
print(view)
pres = view[1]['presenter']
print(pres.view)
```

If the script runs - a WorkspaceDisplay window is alive. If the script fails on `t = ...` no WorkspaceDisplay windows are alive.

### PR DESCRIPTION
**Pull request by dtasev**
**Description of work.**
Matrix/Table displays and InstrumentView will now delete themselves on close.
Issue to document this has been opened: #24644

**To test:**
* Test script
```python
# The following line helps with future compatibility with Python 3
# print must now be used as a function, e.g print('Hello','World')
from __future__ import (absolute_import, division, print_function, unicode_literals)

# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *

import matplotlib.pyplot as plt

import numpy as np
from mantidqt.plotting.functions import plot
import sys

table = Load("SavedTableWorkspace.nxs")
matrix = Load("irs26173_graphite002_red.nxs")

from qtpy.QtWidgets import QApplication

a = QApplication.topLevelWidgets()
t = [x for x in a if "WorkspaceDisplay" in str(type(x))][0]
print("Num widgets {}".format(len(a)))

print(sys.getrefcount(t))
gc.collect()
print(t)
view = gc.get_referents(t)
print(view)
pres = view[1]['presenter']
print(pres.view)
```

If the script runs - a WorkspaceDisplay window is alive. If the script fails on `t = ...` no WorkspaceDisplay windows are alive. To test for instrument view change `"WorkspaceDisplay"` to `"inst"`.

Fixes #24643 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — CHANGES_REQUESTED** [review]
This seems to work when just closing the views. However, if I then go on to delete the corresponding workspace then I get the following error message:
```
Error occurred in handler:
Traceback (most recent call last):
  File "/media/data1/source/github/mantidproject/mantid/qt/python/mantidqt/widgets/common/workspacedisplay_ads_observer.py", line 25, in wrapper
    func(*args, **kwargs)
  File "/media/data1/source/github/mantidproject/mantid/qt/python/mantidqt/widgets/common/workspacedisplay_ads_observer.py", line 62, in deleteHandle
    self.window.close(name)
  File "/media/data1/source/github/mantidproject/mantid/qt/python/mantidqt/widgets/common/observing_presenter.py", line 36, in close
    self.view.emit_close()
  File "/media/data1/source/github/mantidproject/mantid/qt/python/mantidqt/widgets/common/observing_view.py", line 43, in emit_close
    self.close_signal.emit()
RuntimeError: wrapped C/C++ object of type MatrixWorkspaceDisplayView has been deleted
```

**Review by Pasarus — CHANGES_REQUESTED** [review]
Further to @martyngigg 's comments it is evident that the error appears once for everytime the view's were opened so this is likely caused by the objects still existing. (Also occurs on closing workbench)

**Review by Pasarus — DISMISSED** [review]
Seems to work in all cases described now :+1:

**Review by Pasarus — DISMISSED** [review]
Seems to work in all cases described now :+1: good spot on adding back in the clear observers.

**Review by martyngigg — APPROVED** [review]

**Pull request merged**
