### PR TITLE
Missed instrument view serialisation commits

### PR DESCRIPTION
**Pull request by samueljackson92**
#16962 was merged prematurely before I could add some commits based on suggestions from the tester. The majority of this has therefore already been tested in PR #17249.

**To test:**
Two minor changes:
- Min/Max values should now be correctly saved
- The expanded elements of the tree view should now be saved

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
OK I'll test it once the changes have built OK.

**Comment by KarlPalmen** [comment]
I've done some more testing and find that although the instrument tree is preserved the selected component is not preserved in an old project file made prior to this most recent change.

**Comment by samueljackson92** [comment]
@KarlPalmen That doesn't make any sense? The first of these two commits adds support for preserving the tree expansion, so I would expect older files to preserve the selected component and not the tree? (Or nothing at all if the file is very old).

I think it is easiest if you show me when you get a moment.

**Comment by KarlPalmen** [comment]
It worked OK this morning with freshly loaded workspace.

**Comment by KarlPalmen** [comment]
Further test have gone well. :shipit:

**Pull request merged**
