### PR TITLE
Disable TransformToIqt doc test

### PR DESCRIPTION
**Pull request by robertapplin**
### Description of work
This PR disables the TransformToIqt doc test because it is still failing in the nightly, even after recent improvements in #37400

Re-opening this issue #35992

### To test:
The doc test job should pass.

*This does not require release notes* because **this change is to our tests**

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by sf1919** [comment]
Should this go into release-next instead? Otherwise release-next nightly will still fail

**Comment by SilkeSchomann** [comment]
> Should this go into release-next instead? Otherwise release-next nightly will still fail

Good idea.

**Comment by robertapplin** [comment]
> Should this go into release-next instead? Otherwise release-next nightly will still fail

The PR to enable the TransformToIqt doc test went into `main` (https://github.com/mantidproject/mantid/pull/37400), so this only needs to go into `main`

**Review by SilkeSchomann — APPROVED** [review]
The doc tests are passing now.

**Pull request merged**
