### PR TITLE
Skip BayesQuasiTest on macOS

### PR DESCRIPTION
**Pull request by cailafinn**
#### Summary of work
Failing due to fitting differences (probably). Skipping as there are no known macOS users for this algorithm. Should still be fixed to allow consistency, this is a temp fix only.

#### Purpose of work
Allow the nightly build to pass. 

#### On Windows & Linux:
1. Run the test using the `systemtest` script in the build directory.
2. The test passes.
#### On macOS:
1. Attempt to run the test using the `systemtest` script. 
2. The test is skipped. 

*This does not require release notes* because **there are no user-facing changes.**

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by sf1919** [comment]
Does this need to be on `release-next`?

**Review by robertapplin — APPROVED** [review]
Thanks for adding this skip. I'm not aware that Bayes Quasi is used on Mac, so we should be good to investigate this later

**Comment by RichardWaiteSTFC** [comment]
Happy to merge this - does it need a MacOS tester or should we just see if the nightly builds on OSX?

**Comment by robertapplin** [comment]
> Happy to merge this - does it need a MacOS tester or should we just see if the nightly builds on OSX?

I believe it shouldn't need a MacOS tester because the MantidSystemTest framework handles the skipping

**Pull request merged**
