### PR TITLE
Add a Region Of Interest mode to the Instrument view

### LINKED ISSUE #11824: Extract ROI into a new workspace
This issue was originally [TRAC 10985](http://trac.mantidproject.org/mantid/ticket/10985)

SANS would like to define an ROI, or a set of ROI, then extract those selected pixels into a new workspace.

### PR DESCRIPTION
**Pull request by NickDraper**
This adds a region of interest (ROI) mode to the instrument window.

This gathers together functionality from other modes, and add an intersection based view for applying ROIs.

This also changes the Mask/Group tab name to "draw" and the instrument tree tab name to "instrument".

fixes #11824
### Documentation

The page http://www.mantidproject.org/MantidPlot:_Instrument_View has been updated
### release notes

http://www.mantidproject.org/ReleaseNotes_3_5_UI_Changes#Instrument_View
### To Test
1. Load up some data
2. Play around with adding masks, ROI's and groups, check the interplay between them.
3. Test the options under the Save or apply and save button in each mode.

### CODE REVIEW

**Comment by mantid-roman** [comment]
* When I apply and save ROI to a workspace (or file) the region on the view is masked out instead.
* When the save file dialog opens the cursor changes to "wait".
* I saved a ROI from a LOQ workspace to a file. Then I loaded it and masked the workspace with it. There were detectors I didn't select.

**Comment by NickDraper** [comment]
Thanks I’ll take another look


Regards,
Nick Draper

**Comment by NickDraper** [comment]
The third issue we agreed after discussing it appears to be due to a mismatch of the instrument definintons used for LoadMask and Load for the dataset.

**Comment by mantid-roman** [comment]
The windows test failure seems unrelated.

**Pull request merged**
