### PR TITLE
Learning peak shapes for SCD Profile fitting

### LINKED ISSUE #23470: Smarter Initial Guesses for Peak Profile
`IntegratePeaksProfileFitting' currently uses a constant guess for initial peak sizes.  This will update the algorithm so that it fits the strongest peaks first and updates is initial guess based on peaks it has already fit, ultimately providing a higher level of automation for users.

### PR DESCRIPTION
**Pull request by sullivanbt**
**Description of work.**
Changes the `IntegratePeaksProfileFitting` algorithm to automatically learn peak shapes.

**To test:**
```python
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np
plt.ion()

event_ws = Load(Filename='/SNS/MANDI/IPTS-8776/nexus/MANDI_9113.nxs.h5', OutputWorkspace='event_ws')
MDdata = ConvertToMD(InputWorkspace='event_ws', QDimensions='Q3D', dEAnalysisMode='Elastic', Q3DFrames='Q_lab', OutputWorkspace='MDdata', MinValues='-5,-5,-5', MaxValues='5,5,5', MaxRecursionDepth=10)
mtd.remove('event_ws') #Free up memory

peaks_ws = FindPeaksMD(InputWorkspace='MDdata', MaxPeaks=150, DensityThresholdFactor=5000, OutputWorkspace='peaks_ws')
FindUBUsingFFT(PeaksWorkspace='peaks_ws', MinD=65, MaxD=120, Tolerance=0.15, Iterations=10, DegreesPerStep=1.0)
IndexPeaks(PeaksWorkspace='peaks_ws')

IntegratePeaksMD(InputWorkspace='MDdata', PeakRadius=0.019, BackgroundInnerRadius=0.020, BackgroundOuterRadius=0.021, 
                 PeaksWorkspace='peaks_ws', OutputWorkspace='peaks_ws', CylinderLength=0.4, PercentBackground=20,
                 ProfileFunction='IkedaCarpenterPV')
mtd.remove('event_ws') #Free up memory

moderatorFile = '/SNS/MANDI/shared/ProfileFitting/franz_coefficients_2017.dat'

#These are temporary until Parameters files are updated.
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='fitConvolvedPeak', ParameterType='Bool', Value='False')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='sigX0Scale', ParameterType='Number', Value='1.0')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='sigY0Scale', ParameterType='Number', Value='1.0')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='numDetRows', ParameterType='Number', Value='255')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='numDetCols', ParameterType='Number', Value='255')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='numBinsTheta', ParameterType='Number', Value='50')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='numBinsPhi', ParameterType='Number', Value='50')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='fracHKL', ParameterType='Number', Value='0.25')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='dQPixel', ParameterType='Number', Value='0.003')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='mindtBinWidth', ParameterType='Number', Value='15.0')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='maxdtBinWidth', ParameterType='Number', Value='50.0')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='peakMaskSize', ParameterType='Number', Value='5')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='sigSC0Params', ParameterType='String', 
                       Value='5.68860816e-06 7.63702849e-01 8.31642225e-02 3.06656383e-03')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='sigAZ0', ParameterType='Number', Value='0.0025')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='sigP0Params', ParameterType='String', 
                       Value='0.1460775 1.85816592 0.26850086 -0.00725352')


IntegratePeaksProfileFitting(OutputPeaksWorkspace='peaks_ws_out', OutputParamsWorkspace='params_ws', InputWorkspace='MDdata', 
                             PeaksWorkspace='peaks_ws', RunNumber=9113, ModeratorCoefficientsFile=moderatorFile, DQMax=0.2,
                             IntensityCutoff=np.median((mtd['peaks_ws'].column('Intens'))))
                             

plt.plot(mtd['__fitSigX0_Workspace'].readX(0), mtd['__fitSigX0_Workspace'].readY(0),'.',label='Fit Peaks')
xLearned = np.array(mtd['__fitSigX0_Workspace'].readX(1))
yLearned = np.array(mtd['__fitSigX0_Workspace'].readY(1))
sIDX = np.argsort(xLearned)
plt.plot(xLearned[sIDX], yLearned[sIDX],label='Learned Peak Shape')
plt.legend(loc='best')
plt.xlabel('Theta (rad)')
plt.ylabel('sig_theta (rad)')

```

Fixes #23470 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by VickieLynch — COMMENTED** [review]
Add check for RunNumber of peak matching RunNumber of MDWorkspace and remove RunNumber from input of this algorithm. The initial values for peak shapes work well.

**Comment by sullivanbt** [comment]
This is implemented now.  It can be tested with:

```python
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np
plt.ion()

event_ws = Load(Filename='/SNS/MANDI/IPTS-8776/nexus/MANDI_9113.nxs.h5', OutputWorkspace='event_ws')
MDdata = ConvertToMD(InputWorkspace='event_ws', QDimensions='Q3D', dEAnalysisMode='Elastic', Q3DFrames='Q_lab', OutputWorkspace='MDdata', MinValues='-5,-5,-5', MaxValues='5,5,5', MaxRecursionDepth=10)
mtd.remove('event_ws') #Free up memory

peaks_ws = FindPeaksMD(InputWorkspace='MDdata', MaxPeaks=150, DensityThresholdFactor=5000, OutputWorkspace='peaks_ws')
FindUBUsingFFT(PeaksWorkspace='peaks_ws', MinD=65, MaxD=120, Tolerance=0.15, Iterations=10, DegreesPerStep=1.0)
IndexPeaks(PeaksWorkspace='peaks_ws')

IntegratePeaksMD(InputWorkspace='MDdata', PeakRadius=0.019, BackgroundInnerRadius=0.020, BackgroundOuterRadius=0.021, 
                 PeaksWorkspace='peaks_ws', OutputWorkspace='peaks_ws', CylinderLength=0.4, PercentBackground=20,
                 ProfileFunction='IkedaCarpenterPV')
mtd.remove('event_ws') #Free up memory

moderatorFile = '/SNS/MANDI/shared/ProfileFitting/franz_coefficients_2017.dat'

#These are temporary until Parameters files are updated.
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='fitConvolvedPeak', ParameterType='Bool', Value='False')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='sigX0Scale', ParameterType='Number', Value='1.0')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='sigY0Scale', ParameterType='Number', Value='1.0')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='numDetRows', ParameterType='Number', Value='255')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='numDetCols', ParameterType='Number', Value='255')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='numBinsTheta', ParameterType='Number', Value='50')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='numBinsPhi', ParameterType='Number', Value='50')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='fracHKL', ParameterType='Number', Value='0.25')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='dQPixel', ParameterType='Number', Value='0.003')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='mindtBinWidth', ParameterType='Number', Value='15.0')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='maxdtBinWidth', ParameterType='Number', Value='50.0')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='peakMaskSize', ParameterType='Number', Value='5')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='sigSC0Params', ParameterType='String', 
                       Value='5.68860816e-06 7.63702849e-01 8.31642225e-02 3.06656383e-03')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='sigAZ0', ParameterType='Number', Value='0.0025')
SetInstrumentParameter(Workspace='peaks_ws', ParameterName='sigP0Params', ParameterType='String', 
                       Value='0.1460775 1.85816592 0.26850086 -0.00725352')

peaks_ws.getPeak(3).setRunNumber(15)
IntegratePeaksProfileFitting(OutputPeaksWorkspace='peaks_ws_out', OutputParamsWorkspace='params_ws', InputWorkspace='MDdata', 
                             PeaksWorkspace='peaks_ws', ModeratorCoefficientsFile=moderatorFile, DQMax=0.2,
                             IntensityCutoff=np.median((mtd['peaks_ws'].column('Intens'))))
                             

plt.plot(mtd['__fitSigX0_Workspace'].readX(0), mtd['__fitSigX0_Workspace'].readY(0),'.',label='Fit Peaks')
xLearned = np.array(mtd['__fitSigX0_Workspace'].readX(1))
yLearned = np.array(mtd['__fitSigX0_Workspace'].readY(1))
sIDX = np.argsort(xLearned)
plt.plot(xLearned[sIDX], yLearned[sIDX],label='Learned Peak Shape')
plt.legend(loc='best')
plt.xlabel('Theta (rad)')
plt.ylabel('sig_theta (rad)')
```

Notice the error output at the end (for the peak we did not fit because we changed the run number.)

**Review by VickieLynch — DISMISSED** [review]
Much better with RunNumber check

**Review by AndreiSavici — CHANGES_REQUESTED** [review]
This seems like a pretty important change. I think it should be in the release notes

**Review by AndreiSavici — APPROVED** [review]

**Pull request merged**
