### PR TITLE
Improve Dev Docs for Multithreading

### PR DESCRIPTION
**Pull request by cailafinn**
**Description of work.**
Brought the docs back up to date to fix broken links. Also added some information on multithreading in python, which is frequently used in the python interfaces to keep the GUI thread from hanging. 

**To test:**
1. Build the dev-docs-html target and check the formatting. 

*There is no associated issue.*

*This does not require release notes* because **it is a developer documentation change.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by RichardWaiteSTFC — COMMENTED** [review]
Thanks for clarifying this, and for adding a helpful section on python. I just had a couple of questions:

1. I've seen PRAGMA_OMP used for parallle loops like so
```
  PRAGMA_OMP(parallel for schedule(dynamic, 1) )
  for (int ithread = 0; ithread < nThreads; ithread++) {
    PARALLEL_START_INTERUPT_REGION
```
Is this in the scope of this docs page?
2. Can we specify the number of threads etc. when running Async tasks in python?

**Review by RichardWaiteSTFC — DISMISSED** [review]
Thanks for adding those extra bits, looks good to me!

**Review by martyngigg — CHANGES_REQUESTED** [review]
Thanks for bringing this up to date and adding the Python elements - it's much more useful now.

Could I ask that we rename the document though? The title `MultiThreading in Algorithms`  implies it's only to be used in algorithms and especially now we've added the Python parts that's not really true. It is probably worth noting that a few of the OpenMP macros do indeed only work from an algorithm but the others like your scheduling example are generic.

**Comment by ConorMFinn** [comment]
I've also noticed that `INTERUPT` is mispelled. Can I correct this here or should it be another PR?

**Comment by RichardWaiteSTFC** [comment]
> I've also noticed that `INTERUPT` is mispelled. Can I correct this here or should it be another PR?

Oh yes, I'm assuming that's more than a doc change given it's like that here
https://github.com/mantidproject/mantid/blob/de259314d655b6c31c46dac22c46bbf8fd7d5abd/Framework/Algorithms/src/FitPeaks.cpp#L919

I'm happy for that to be a separate PR but I don't feel strongly either way - what do you think @martyngigg?

**Comment by martyngigg** [comment]
> > I've also noticed that `INTERUPT` is mispelled. Can I correct this here or should it be another PR?
> 
> Oh yes, I'm assuming that's more than a doc change given it's like that here
> 
> https://github.com/mantidproject/mantid/blob/de259314d655b6c31c46dac22c46bbf8fd7d5abd/Framework/Algorithms/src/FitPeaks.cpp#L919
> 
> I'm happy for that to be a separate PR but I don't feel strongly either way - what do you think @martyngigg?

Oh yes! How funny that no one has noticed that in 10+ years! As it's a code change and will affect many algorithms/files that's definitely a separate PR.

**Review by martyngigg — APPROVED** [review]

**Pull request merged**
