### PR TITLE
Remove reference to deprecated numpy.distutils

### LINKED ISSUE #37421: Numpy.distutils deprecation
Launching a developer build of Mantid on a Linux machine (happens on both IDAaaS and Ubuntu) using the `launch_mantidworkbench.sh` script will generate the following deprecation warning:

```
DeprecationWarning: numpy.distutils is deprecated since NumPy 1.23.0, as a result 
of the deprecation of distutils itself. It will be removed for Python >= 3.12. For older 
Python versions it will remain present. It is recommended to use setuptools < 60.0 for 
those Python versions. For more details, see: 
https://numpy.org/devdocs/reference/distutils_status_migration.html
```

### PR DESCRIPTION
**Pull request by jclarkeSTFC**
As of NumPy 1.23.0, `numpy.distutils` is deprecated. It was used here to check if an argument is a sequence, so I just implemented an equivalent method and deleted the `numpy.distutils` import.

See [here](https://github.com/numpy/numpy/blob/v1.26.0/numpy/distutils/misc_util.py#L497-L504) for what NumPy was doing.

Fixes #37421 

### To test:

Tests should pass, `IntegratePeaks1DProfile` should still work.

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by sf1919** [comment]
I suspect the doc test failures are due to needing to rebase after these two pieces of work were undertaken
https://github.com/mantidproject/mantid/pull/37467
https://github.com/mantidproject/mantid/pull/37475

**Comment by sf1919** [comment]
I think this also solves half the problems in #37277

**Review by robertapplin — CHANGES_REQUESTED** [review]
Code changes look good - nice use of `collections.abc.Sequence`. The `epsilon` variable has been replaced because it didn't exist in the code and was a typo. Just wanted to check if this means a test in this area would be useful? Or is this area difficult to test?

**Comment by jclarkeSTFC** [comment]
> Code changes look good - nice use of `collections.abc.Sequence`. The `epsilon` variable has been replaced because it didn't exist in the code and was a typo. Just wanted to check if this means a test in this area would be useful? Or is this area difficult to test?

Thanks, probably @RichardWaiteSTFC would have the best idea about testing.

**Comment by robertapplin** [comment]
Also another question, is this `epsilon` typo in release-next? And if so, is it important to be fixed for the release?

**Comment by RichardWaiteSTFC** [comment]
> Also another question, is this `epsilon` typo in release-next? And if so, is it important to be fixed for the release?

The typo is in `release-next` but the bug isn't triggered in the code because the step size passed to `calc_hessian` is a sequence. It was just that the function might be useful in other places!

**Review by robertapplin — APPROVED** [review]
I think adding a test might be slightly out of scope of this PR because its original purpose is to remove the use of deprecated numpy.distutils,so happy to approve!

**Pull request merged**
