### PR TITLE
MaskBins Fixed bug in the error message

### PR DESCRIPTION
**Pull request by gvardany**
Fixed the bug #17129 .

**To test:**

1. Load/create a workspace.
2. `MaskBins` with `XMin`>`XMax`
3. Inspect the exception/log message.

Does not need to be in the release notes.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
When tested as described, the error message appeared twice.

**Comment by KarlPalmen** [comment]
Perhaps the duplicate error message can be made into another issue :shipit: .

**Comment by gvardany** [comment]
I think it's because it logs an error and then throws the exception. Shouldn't just throwing exception be sufficient?

**Comment by gvardany** [comment]
Seems the issue is still open, but the PR is merged. Should I close or remove the duplicated message issue?

**Comment by peterfpeterson** [comment]
The proper way is to say "Fixes #..." and github will take care of it for you.

**Pull request merged**
