### PR TITLE
Script Editor Zoom

### LINKED ISSUE #25800: Code editor not zoomed in when pressing `Ctrl + =` or `Ctrl + Shift + =`
### Expected behavior
Code editor zooms in when pressing `Ctrl + =` or `Ctrl + Shift + =`. This is the behaviour in most apps (some require Shift to make the `=` be a `+`).

### Actual behavior
It prints `=` or `+`.

### Steps to reproduce the behavior
Open Workbench, focus the code editor and press `Ctrl + =`

### Platforms affected
Discovered on Ubuntu 18.04

### PR DESCRIPTION
**Pull request by PhilColebrooke**
**Description of work.**
This pull request makes it possible to use the keyboard shortcuts Ctrl++ and Ctrl+- to zoom in and out of the script editor. This feature is now present in both MantidPlot and Mantid Workbench.

**To test:**
1. Open Workbench, click on the script editor area, check that Ctrl++ zooms in and Ctrl+- zooms out (both the keys next to backspace and the num pad keys).
2. Repeat for MantidPlot.

Fixes #25800 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by NickDraper — DISMISSED** [review]
Code is fine.

Works in the workbench and mantidplot with both the numberpad and numbers keys, and the mouse scroll wheel (not the scroll wheel for ipython, but that's ok)

However the key based zoom only works for the scripting windows not ipython in workbench, while it works all round in Mantidplot.

**Comment by NickDraper** [comment]
Taking myself off as tester as I'm at ICANS next week

**Comment by PhilColebrooke** [comment]
To whoever picks up this PR:

The keyboard shortcuts Ctrl+- and Ctrl++ (or Ctrl+Shift+=)  should now work for zooming in and out on both the script editor and the IPython console, with Workbench and MantidPlot.

**Review by ghost — CHANGES_REQUESTED** [review]
For me only `Ctrl Shift +` zooms in and only `Ctrl -` zooms out. `Ctrl +` just gives me an `=` and `Ctrl Shift -` does nothing. This is for both the script editor and IPython console. Is this the case for you as well?

Also, the zoom only occurs on one tab, would it make more sense if, when you zoom in on a script in one tab, then switch to another, the font size remains the same? 

Also, when you close the script window and re-open it the font sizes are all reset, should we store the font size in QSettings so it can be restored?

**Review by ghost — COMMENTED** [review]
This is looking good and working well. Just one comment below

**Review by ghost — APPROVED** [review]
This looks good to me now 👍

**Pull request merged**
