### PR TITLE
sort instruments alphabetically by name after filling instrument list

### LINKED ISSUE #29874: Order Instruments Alphabetically
**Original reporter:** Steve King @smk78 

### Expected behavior
ISIS instruments appear in alphabetical order
### Actual behavior
Accessing the list of instruments at the ISIS facility gives an odd order which is partially alphabetical.
### Steps to reproduce the behavior
See the Instrument list when `Facility = ISIS` in the Help > Mantid About menu or in File > Settings > General
Need to change the order defined here: https://github.com/mantidproject/mantid/blob/master/instrument/Facilities.xml

### Platforms affected
All

### PR DESCRIPTION
**Pull request by SilkeSchomann**
Fixes [#29874](https://github.com/mantidproject/mantid/issues/29874)

The list of instruments at a facility was only partially in alphabetical order.

To test:

Check the instrument list for the facility ISIS both in Help > About Mantid Workbench and in File > Settings > General.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — CHANGES_REQUESTED** [review]
Thanks for making these changes. I agree that it is helpful to have this file ordered alphabetically so it is easier to find a given instrument.

Could we also ensure that in the GUI element we sort the instrument list too? - https://github.com/mantidproject/mantid/blob/master/qt/applications/workbench/workbench/widgets/about/presenter.py#L123
I think it's best that the GUI not rely on the source being sorted as someone could add an instrument out of order in this file and that shouldn't cause any runtime issues as it will be hard to guarantee that this file stays sorted.

**Comment by martyngigg** [comment]
We actually already have a widget called [InstrumentSelector](https://github.com/mantidproject/mantid/blob/master/qt/python/mantidqt/widgets/instrumentselector.py#L13) that does this alphabetization - perhaps we could use this widget instead of a custom one in the about box?

**Review by martyngigg — CHANGES_REQUESTED** [review]
It's nice to reuse an existing widget to do this and the instrument selection is now ordered sensibly for users to find their instruments more easily. 👍

I've noticed though that when I select a different facility the item in the instrument box selected by default appears to be not the first but something else - when selecting a new facility, unless the default instrument is in the instrument list can we select the first by default?

Also, although this is not strictly in the issue, could we sort the facility list in the view alphabetically too?

**Comment by martyngigg** [comment]
This looks great functionally now. The boxes in settings and about screen behave as I would expect them to.

One oddity I spotted was on the settings screen. There seems to be an extra combobox  where the word instrument used to be:

Screenshot 2020-12-08 at 09 21 25


Compared to what is currently in the nightly:

Screenshot 2020-12-08 at 09 41 56

**Review by martyngigg — APPROVED** [review]
Thanks for fixing that issue.

This looks good now.

**Comment by gvardany** [comment]
Does this sort the facilities.xml file or the makes the logic such that they appear sorted no matter the order in which they are written there?

**Comment by SilkeSchomann** [comment]
It does not impact facilities.xml. The items are ordered in the GUI before display.

Kind regards,

Silke
________________________________

**Pull request merged**
