### PR TITLE
Remove Typo From Multithreading.h

### PR DESCRIPTION
**Pull request by cailafinn**
**Description of work.**
Simply removes a mispelling from the Interrupt macros in `Multithreading.h`. Seemed worth doing given how frequently they are used in algorithms and the like. 

**To test:**
Try a few algorithms to check they work as expected. Should be mostly covered by the unit tests. Any errors would stop the build. 

*There is no associated issue.*

*This does not require release notes* because **it is a maintenance fix with no user facing effects**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DanielMurphy22 — COMMENTED** [review]
The algorithms seem to work fine. Not really sure how to check that these are indeed still multithreading but the code change seems like a simple replace all on the repo. I will approve after we have released 6.3 and release-next has had it's final remerge into main, as @thomashampson warned of the merge conflicts of making large sweeping changes when he was fixing cppcheck.

**Comment by DavidFair** [comment]
Thanks for fixing this! This was really niggling me when I was pointed someone to the docs for threading, but I promptly forgot about it....

**Comment by ConorMFinn** [comment]
>  I will approve after we have released 6.3 and release-next has had it's final remerge into main

@DanielMurphy22 I think this has been done now?

**Review by DanielMurphy22 — APPROVED** [review]
Works well! Simple but effective!

**Review by DavidFair — APPROVED** [review]

**Pull request merged**
