### PR TITLE
Handle positive images (MaxEnt)

### LINKED ISSUE #15151: Improvements to MaxEnt
In `MaxEnt`:

- Code refactoring (split the algorithm into different classes)
- Add ability to handle strictly positive images

### PR DESCRIPTION
**Pull request by raquelalvarezbanos**
1. Code refactoring
2. Adds the ability to deal with positive images.

**To test:**
- Code review. The algorithm was refactored into different classes: 
  - `MaxentData` stores the information related to the signal (both in real and image space), which includes: the experimental data and errors, the reconstructed data and the reconstructed image. It also performs calculations related to the data, such as the chi-sq, search directions and quadratic coefficients, etc.
  - `MaxentEntropy` defines the necessary operations related to the entropy. This is an abstract base class from which two concrete classes are derived at the moment. The entropy formula to use depends on the type of image: if there is no restriction on the image (i.e. if it can take any real number, positive, negative or zero) we use the derived class `MaxentEntropyNegativeValues`. If the image is restricted to positive values only, `MaxentEntropyPositiveValues` is used.

These classes have been moved to a subdirectory of `Framework/Algorithms`, `MaxEnt/`. Feedback/comments/suggestions are very welcome :)
- Test the algorithm, you should be able to reproduce the examples in the documentation. There is a new section "Positive Images" explaining the new functionality.

Fixes #15151.

Link to [Release notes](http://www.mantidproject.org/index.php?title=Release_Notes_3_7_MuonAnalysis&diff=26376&oldid=26371).

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Anders-Markvardsen** [comment]
Please note when I run the usage example "Reconstruct Fourier coefficients" I get the red line shown in the picture below:

capture

And e.g. the y-values I get from the first two 5 data points are

0.00314850300793657	0.00161405937431524	-0.000615333098501683	0.000358778870428882	0.00149631642052572
3.46664366102216e-05	4.95231388697469e-11	1.04385740509336e-11	-6.87859643033083e-11	4.23497448750756e-11

I would have expected some of these to be zero

**Comment by raquelalvarezbanos** [comment]
I think those numbers are reasonable, for instance, for the second spectrum, they are not zero but of the order of `10^{-11}`, which is very small in comparison to the values the reconstructed signal takes at the fourier coefficients, `~0.8`. I think a certain level of noise is expected. Maybe it could be reduced by selecting different values for the technical parameters, I haven't tried...

@Anders-Markvardsen I was looking into the possibility of adding the user examples as doc-tests but the first example, "Reconstruct Fourier Coefficients" takes ~1 minute, is this acceptable? (I'm running in debug mode, windows) I think you mentioned it was really fast when you ran it...

**Comment by Anders-Markvardsen** [comment]
In release on my machine is this example takes about 2 seconds, which is acceptable. You could double check to see if you see the on your PC in release.

I must admit I still don't understand why e.g. the first data point is 3.46664366102216e-05? I will of course review the code in more detail later:) But if the this data is input as zero I at this struggle to understand how it ends up as 3.46664366102216e-05

**Comment by raquelalvarezbanos** [comment]
Well, my understanding is that (but I can be wrong) some background (in the sense of small numbers, as the 3.46e-5 we are getting) is expected. The reason why I think this is not so unreasonable is because (considering this specific example of a real input signal):

- The imaginary part of the reconstructed data (what we would expect to be exactly zero in an ideal case) is not compared to the experimental data to calculate a chi-square (we can't make this comparison because for the imaginary part of the experimental data we have no errors, so we can't compute a chi-square `( d - d_calc )^2 / sigma^2`), so in principle it could end up taking any number.
- The way in which we calculate the solution data (real and imaginary parts) is via the solution image. That is, once a solution image is found (an image whose chi-square and angle reach the target values) then we use that image to calculate and return the reconstructed data. 
- I assume this operation (i.e. just a Fourier transform from image to data) is not perfect. I've tried the following example where I just create a perfect signal (real part is a perfect cosine, imaginary part is a perfect sine, so the Fourier transform must be a perfect delta peak at `w - w0` with imaginary part `= 0` for all values):

```
from math import pi, sin, cos
from random import random, seed
seed(0)
# Create a test workspace
X = []
YRe = []
YIm = []
E = []
N = 200
w = 3
for i in range(0,N):
              x = 2*pi*i/N
              X.append(x)
              YRe.append(cos(w*x))
              YIm.append(sin(w*x))
              E.append(0.1)
ws = CreateWorkspace(DataX=X+X,DataY=YRe+YIm,DataE=E+E,NSpec=2)
wsFFT = FFT(InputWorkspace='ws', InputImagWorkspace='ws', Imaginary=1)
print wsFFT.readY(1)[0]
print wsFFT.readY(1)[1]
print wsFFT.readY(1)[2]
```
and the output I get is of the order of `~10e-16`

- We are getting numbers `~10e-11` and the worse number we are getting is `~10e-5` (I haven't checked all of them, I am just talking about the ones in your first comment).
- In addition to the small errors associated to a FT calculation, the solution image is not going to be perfect (our experimental data have errors associated), so I think it could lead to reconstructed data with a small complex component. For instance, in the example above, if, instead of using a perfect cosine + sine I add a small random component, like this:

```
from math import pi, sin, cos
from random import random, seed
seed(0)
# Create a test workspace
X = []
YRe = []
YIm = []
E = []
N = 200
w = 3
for i in range(0,N):
              x = 2*pi*i/N
              X.append(x)
              YRe.append(cos(w*x)+(random()-0.5)*0.0001)
              YIm.append(sin(w*x)+(random()-0.5)*0.0001)
              E.append(0.1)
ws = CreateWorkspace(DataX=X+X,DataY=YRe+YIm,DataE=E+E,NSpec=2)
wsFFT = FFT(InputWorkspace='ws', InputImagWorkspace='ws', Imaginary=1)
print wsFFT.readY(1)[0]
print wsFFT.readY(1)[1]
print wsFFT.readY(1)[2]
```
now the output I get is `~10e-5`

I think the key is that the imaginary part of the reconstructed data is not compared to the imaginary part of the experimental data (as the latter have no errors associated), but using the solution image, and if this solution image is not perfect (although it can be a very good approximation it may have small errors associated due to the calculations performed in the algorithm, also errors resulting from the fact that the experimental data are noisy, etc) a small background different from zero is not so unreasonable. What do you think?

**Comment by Anders-Markvardsen** [comment]
Firstly, thanks for adding the doc tests

Secondly, I just realised that I misunderstood the data graph under needs the “Reconstruct Fourier coefficients” example. This is because in the figure it has title ‘data’ and one of the output of the usage example is data, which contains reconstructed real and image data, but because I looked at the figure first I thought it contained the original data and reconstructed data. Hence, could you for example change the title of this figure to perhaps “Comparing the real of part of original and reconstructed data” 

Thirdly, yes the non zero values for the reconstructed data does concern me, in fact more now that I understand what they are. I think this can be worked at outside this issue. In your example it does not make physical sense that the imaginary part of the data are ever non-zero, for such cases, which could be always when ComplexData=False, an option could be to implement a FFT algorithm such as see page 510 in http://apps.nrbook.com/c/index.html. 

Fourtly, does both the real and imaginary part of image (always) contribute to the entropy?

**Comment by raquelalvarezbanos** [comment]
Yes, both the real and imaginary parts of the image always contribute to the entropy. The reason is that a real input may have a complex Fourier transform. We can modify the underlying FFT algorithm to use NR, but the NR method returns a complex Fourier transform too, so I think we will always end up with a complex image (unless we are dealing with a very specific input for which its Fourier transform is real).

**Comment by raquelalvarezbanos** [comment]
Yes, I'll change the titles to make it more clear (I left the default title which I agree can be confusing)

**Comment by Anders-Markvardsen** [comment]
Added #15553 which I think will also remove the issue of non-zero imaginary for the example discussed above.

About add a NR like RealFFT algorithm to Mantid and using it MaxEnt, that would provide a general speedup where this can be used, but for now this could be faked by setting imaginary part of (normal) FFT to zero when required when ComplexData and/or ComplexImage is false

**Comment by Anders-Markvardsen** [comment]
Restructoring is a very good improvements and now works with entropy designed for positive images also. 

Note you have opdated the RST file Description section accordingly yet

**Comment by Anders-Markvardsen** [comment]
can't remember now what the policy of deleting or not deleting branches are now with the new testing workflow

**Comment by raquelalvarezbanos** [comment]
Ideally there should be a second reviewer (@gatekeeper) reviewing the changes, the first tester should test normally but should not merge the branch. They should include a :shipit: once they are happy with the changes and wait for the second tester to merge and delete the branch.

**Comment by Anders-Markvardsen** [comment]
Thanks for the reminder - will remember next time

**Pull request merged**
