### PR TITLE
Add documentation pages on techniques on absorption correction

### LINKED ISSUE #36835: Documentation page for absorption and multiple scattering corrections
**Description**
Spencer has sent some useful notes on performing absorption and multiple scattering corrections in Mantid. It would be good to upload these to the Techniques page on the Mantid static website. https://archive.mantidproject.org/Category_Techniques.html

See the attached pdf file for the notes.
[Applying_corrections.pdf](https://github.com/mantidproject/mantid/files/14221226/Applying_corrections.pdf)

**Acceptance Criteria**
- We have a separate documentation page containing these notes. And there is a link to these notes on the techniques category menu seen in the link above.

### PR DESCRIPTION
**Pull request by adriazalvarez**
### Description of work
This PR adds a new documentation page detailing some of the procedures to apply multiple scattering absorption corrections within Mantid. 
Based on a document redacted originally by Spencer.

Fixes #36835 

### To test:
- Build docs enabling screenshots, check images displayed correctly.
- Check for grammar mistakes or typos.

**Added release notes**

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by robertapplin — CHANGES_REQUESTED** [review]
Really excellent piece of documentation, well illustrated by images - thanks for the hard work on this!

Spotted a few typos, then happy to approve.

Also I think it would be good to change places where we have :math:`S(Q,w)` to :math:`S(Q, \omega)`

**Comment by adriazalvarez** [comment]
Thanks for your careful read. I'm not sure how I missed so many typos 👓⚡

**Comment by sf1919** [comment]
There is one warning on Doxygen but we already have an issue raised to deal with it (#37286). So there is nothing holding up reviewing this one.

**Review by robertapplin — APPROVED** [review]
Looks good, thanks for the changes!

**Pull request merged**
