### PR TITLE
Improve tridiagonal matrix inversion on large matrices

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

For large tridiagonal matrices with |D|>2 the analytical approach to inverting the matrix runs into problems because cosh and sinh overflow. Instead of using the non-analytical approach in this case, use a alternative formula for R_ij that is valid in the large k limit. 

This will remove a performance hit when trying to run spline interpolation (including error calculation) on workspaces with >~1000 bins. This is done by the MonteCarloAbsorption algorithm when the interpolation options are enabled

The following maths shows the expression for R_ij on the final line that I've used in the large k limit (k is the dimension of the square matrix):

image

The final term is pretty close to zero for large k in almost all cases except where i and j reach their maximum values of k-1 (i and j are 0-based). At this point the final term equals $e^{-2\lambda}$ which is small but not negligible so I've kept it in for that reason

**To test:**

Run script on https://github.com/mantidproject/mantid/pull/33917

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DannyHindson** [comment]
@gui-co - I've created this PR with a change to allow the analytical matrix inversion used inside Matrix.cpp to operate without any overflows even if the spectrum has a large number of bins. This improves the performance of the spline interpolation used by MonteCarloAbsorption.cpp.
This could be merged instead of https://github.com/mantidproject/mantid/pull/33917 or if the adjustments I've suggested on that PR are made then both could perhaps be merged. They're in different parts of the code base so don't interfere

**Comment by gui-co** [comment]
Thank for having a look into this.

I think this is the solution to the problem described in #33917. I will close my PR.

**Comment by RichardWaiteSTFC** [comment]
Code change looks good - I ran the script in #33917 and it executed in ~ 20 minutes. It might just be my setup so I will compare this to main

**Review by RichardWaiteSTFC — APPROVED** [review]
So it's 2 hours since I started the script on main and it hasn't finished yet - so this looks like a big improvement! Code looks good and I can confirm the output workspace has the same number of bins (something that is mentioned in #33917 as being fixed).

**Pull request merged**
