### PR TITLE
Beta fix: Fit to raw data in Muon Analysis

### PR DESCRIPTION
**Pull request by tom-perkins**
Fix the "fit to raw data" option in the Muon Analysis interface,

**To test:**
_Data set: `MUSR00022725.nxs` in unit test data_
- Set facility to ISIS, open _Interfaces/Muon/Muon Analysis_ and load data set
- Go to "Settings" tab, in "Data Binning" select fixed rebinning with steps of 5 (so the difference between rebinned and raw data is clear)
- Go to "Data Analysis" tab:
  - Function (top part of page): set up `GausOsc`, Frequency 1.3, tick "Global" box for A, Sigma, Frequency
  - Data (centre of page): tick checkboxes for groups `fwd` and `bkwd`, set label for fit to "Rebinned"
  - Options (bottom of page): ensure "Fit to Raw Data" is off
- Fit the data
- Now turn on "Fit to Raw Data" option. Set the fit label to "Raw" and fit again.
- Compare the workspace groups `MuonSimulFit_Rebinned` and `MuonSimulFit_Raw`. They should be different:
  results_raw_rebinned

Re #17602 (does not close that issue as it contains other points too)

No release notes. The new fitting functionality is already contained in the 3.8 release notes.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@tom-perkins Was the branch based off `release-v3.8`? If so we need to change the base of the pull request to that branch. See https://github.com/blog/2224-change-the-base-branch-of-a-pull-request for details.

**Comment by KarlPalmen** [comment]
:shipit:

**Comment by martyngigg** [comment]
@tom-perkins The branch has developed a merge conflict. Please merge in `origin/release-v3.8`.

**Comment by martyngigg** [comment]
Thanks, Tom.

As it was a big merge conflict I think it might be worth retesting it. @KarlPalmen Would you have time to retest this?

**Comment by KarlPalmen** [comment]
Yes I have time to test this.

**Comment by KarlPalmen** [comment]
Yes It works as described :shipit:

**Comment by martyngigg** [comment]
Thanks, @KarlPalmen

**Review by martyngigg — APPROVED** [review]

**Pull request merged**
