### PR TITLE
Correct the bad example of FitPeak in doc test

### LINKED ISSUE #15985: FitPeaks usage example does not fit the peak
Make sure the usage example is actually fitting the peak. Starting position of 2.15 might work. Keep a reasonable number of digits in sigma, so it will pass with gsl2.

### PR DESCRIPTION
**Pull request by wdzhou**
Description of work.

**To test:**

Check whether the current doc test makes sense.

Fixes #15985.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by rosswhitfield** [comment]
This still gives me different results with GSL2
```
Expected:
    Chi-square = 7.13874: Peak centre = 2.14171, Height = 8365.83632, Sigma = 0.00564
Got:
    Chi-square = 112.08353: Peak centre = 2.11292, Height = 231.92368, Sigma = 0.00542
```

@AndreiSavici What do you get?

**Comment by rosswhitfield** [comment]
If I change it to PeakParameterValues='2000,2.14,0.01' then I get
`Chi-square = 1.74892: Peak centre = 2.14201, Height = 7490.67153, Sigma = 0.00776`

**Comment by rosswhitfield** [comment]
Works for me with GSL2. @AndreiSavici can you check Ubuntu 16.04

Otherwise when the builds pass :shipit:

**Comment by AndreiSavici** [comment]
Works on Ubuntu 16.04

**Pull request merged**
