### PR TITLE
Refactor point group to use Group

### PR DESCRIPTION
**Pull request by MichaelWedel**
This fixes [#11006](http://trac.mantidproject.org/mantid/ticket/11006).

The changes from ticket [#10305](http://trac.mantidproject.org/mantid/ticket/10305) made it possible to determine the crystal system automatically from the symmetry operations present in the point groups. All point groups were added. When reviewing the unit tests, I discovered what I believe was a bug in hexagonal/trigonal point groups. The following example script returns "True" before applying the changes from this ticket:

```
pg = PointGroupFactoryImpl.Instance().createPointGroup("6/mmm")
print pg.isEquivalent([1,0,0], [1,1,0]);
```

In fact, this is not true. Writing (100) in hexagonal with additional index i = -(h+k) gives (hkil) = (10-10). Applying all the permutations from 6/mmm gives (1-10) and (-110), but not (110). After applying the changes from this ticket, the script correctly prints "False".

**Testing information**
Make sure the unit tests, system tests and doc-tests pass. Other than that it's only code review. The names of some point groups were changed (trigonal ones, that were not rhombohedral as the names suggested, but hexagonal). Greping these names in the sources (also systemtests) did not give me any results, so this should not cause problems within Mantid.

### CODE REVIEW

**Comment by MichaelWedel** [comment]
Jenkins retest this please

**Comment by MichaelWedel** [comment]
Jenkins retest this please

**Comment by MichaelWedel** [comment]
Jenkins retest this please

**Comment by MichaelWedel** [comment]
Jenkins retest this please

**Comment by MichaelWedel** [comment]
Jenkins retest this please

**Comment by MichaelWedel** [comment]
Jenkins retest this please

**Comment by MichaelWedel** [comment]
Jenkins retest this please

**Comment by MichaelWedel** [comment]
Jenkins retest this please

**Comment by FedeMPouzols** [comment]
Tests (unit, system, doc) passed locally, and on the CI servers doc tests are now run on win7, and system tests run on rhel6. So I'd take that as good sign enough. Also, the example and variations of it behave as expected.
Code looks very good and comes with documentation and new test cases.

**Pull request merged**
