### PR TITLE
Close and review all leak issues with Poco::XML document, nodelist, etc. objects

### PR DESCRIPTION
**Pull request by FedeMPouzols**
This addresses [#10637](http://trac.mantidproject.org/mantid/ticket/10637) and hopefully closes all remaining Poco::XML issues. 

As part of this a few small remaining leaks have been fixed with AutoPtr or release(). I also removed a good bunch of unused poco header includes (Poco/File, Fath, NodeIterator, NodeFilter, etc. very frequently included and much less frequently used in practice) that seem to have been copy-pasted in multiple places. I also changed some unit tests to use AutoPtr. While these were not terrible issues, I think it is better to avoid bad code examples in unit tests.

**To test**:
- Code review
- Make sure all tests pass
- Overall, this should give the final touch to the Poco-XML clean-up (see "blocked by" tickets), but of course there can always be more issues
- Try to catch any remaining issue

### CODE REVIEW

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
I've fixed the merge conflict. Let's see if the issue with LoadMaskTest on mac persists.

**Comment by FedeMPouzols** [comment]
Aha, something was causing a segfault in the LoadMask unit test, only on mac, and only in say 30-50% of builds. But I got one crash where the error message was clear: double free corruption. I realized that I added a couple of ->release() calls in the LoadMask destructor, one for m_pDoc and another one for m_pRootElem. That's wrong, m_pRootElem is assigned from Poco::DOM::Document::documentElement() which does not require a release and is simply a pointer to the root element of the document tree that is freed when doing m_pDoc->release().

**Pull request merged**
