### PR TITLE
Fixes #21701 - Refactor and update sample correction documentation

### LINKED ISSUE #21701: Help: Document comparing Multiple scattering absorption (and other absorption) corrections in Mantid
Anders made a start on something similar to this with a summer student last year, get what you can from him.
#20072

### PR DESCRIPTION
**Pull request by marshallmcdonnell**
**Description of work.**

Update the sample correction documentation. Added initial absorption correction section and updated the multiple scattering correction section. Tables included to document what is currently available in Mantid, features of the algorithms, and where they are applicable (sample geometry, energy mode, etc.)

**Report to:** @martyngigg @keeeto @peterfpeterson @Anders-Markvardsen SpencerHowells

**To test:**

Build docs-html, specifically for AbsorptionAndMultipleScattering.rst

Fixes  #21701.
Follows-up from #20072, #20145
Provide guidance for continuing with #20235

*This does not require release notes* because it only adds user documentation

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by SpencerHowells** [comment]
@marshallmcdonnell The corrections available via the Inelastic>Corrections interface can also be run on diffraction. I did that for the the detector banks of (OS)IRIS.

**Comment by marshallmcdonnell** [comment]
SpencerHowells Thanks for looking at this! I must not have the same interface right now since the Inelastic>Corrections in my MantidPlot do not show sample correction algorithms

Just to check, for absorption were you referring to: `IndirectAnnulusAbsorption`, `IndirectCylinderAbsorption`, and `IndirectFlatPlateAbsorption`? That is what I assume for OSIRIS.

I wasn't sure about the multiple scattering corrections. I assume the `MuscatData` and `MuscatFunc` are not great options for diffraction [at least not without knowledge of S(Q,w)]. I assumed `VesuvioCalculateMS` is specific to Vesuvio but seems it could generalize (from me looking over the code quickly)

Let me know and I can change the tables accordingly. Also, let me know if I missed anything in the lists!

**Review by peterfpeterson — CHANGES_REQUESTED** [review]
Overall a great improvement. There needs to be more clarity on which algorithms are actually wrappers on top of another for a specific shape.

**Comment by SpencerHowells** [comment]
@marshallmcdonnell Interfaces>Indirect>Corrections has been there for several years and has 2 gtabs for doing the calculations:
1. CalculatePaalmanPings. Uses the algorithms FlatPlate/CylinderPaalmanPingsCorrection. These are based on the code developed in the ISIS Atlas/Gudrun packages for Disordered diffraction. I converted the Fortran to Python and added inelastic option.
2. CalculateMonteCarloAbsorption. Uses the Indirect... algorithms and SimpleShapeMonteCarloAbsorption which I wrote. 

These GUIs read in sample & container data and convert unit from EnergyTransfer or d-spacing (or any other) to wavelength for the calculations. The corrections are then converted back to the input unit.
The tab ApplyAbsorptionCorrections uses the the data & corrections workspaces.
The MC version is an approximation while we await the MC code being extended to PP formulism.

For MultipleScattering I have a MC version based on the inelastic code which I can use on ILL D4 data. It could be adapted for general use.

**Comment by peterfpeterson** [comment]
@SpencerHowells Can we make a new issue for converting your multiple scattering code to C++? @marshallmcdonnell was thinking of doing a MC multiple scattering extension to the current absorption MC code. I'm suspicious it is a very similar approach.

**Comment by SpencerHowells** [comment]
@peterfpeterson @marshallmcdonnell Yes - go ahead. It is indeed a similar approach.

**Comment by marshallmcdonnell** [comment]
For the MC code, I opened Issue #23874 to address this port. @SpencerHowells I'll contact you offline to discuss getting the code. Thanks!

**Review by peterfpeterson — APPROVED** [review]
Welcome improvement on sample corrections.

**Pull request merged**
