### PR TITLE
Interactive Tool use RangeMarker instead of VerticalMarker's

### LINKED ISSUE #25898: Consolidate RangeMarker with workbench interactive_tool code
The `RangeMarker` type was added to `mantidqt.widgets.fitpropertybrowser` in #25879 but could be used in the `interactive_tool` code rather than it also having separate VerticalMarker objects.

I think it is also worth moving the markers to the `plotting` package as while they are used by fitting that are really to do with annotating a plot.

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR replaces the VerticalMarkers used in the interactive_tool for Fitting plots with a RangeMarker. Do this has provided the following benefits:
- Dragging the markers when changing the fit range is far quicker (not as much lag)
- The RangeMarker cannot be dragged off the edge of the plot.
- The markers in the RangeMarker can be seamlessly switched. (i.e. the min and max markers can be moved either side of each other. The endx and startx will still be correct in the FitPropertyBrowser.)

**To test:**
1. Open the workbench
2. Load the data below
3. Right click and Plot spectrum 0.
4. Click `Fit`
5. Move the range markers around and check the correct values are displayed in the FitPropertyBrowser.
6. Choose a `Lorentzian` and `Flat Background`
7. Choose `Fit`->`Fit`
8. The fit should be produced between the range provided.

Compare this to the version in master, and it should have the benefits stated above.

**Data Files**
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/3397207/irs26176_graphite002_red.zip)

Fixes #25898 

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gemmaguest** [comment]
I got this unhandled exception by clicking Fit twice: `AttributeError: 'FitInteractiveTool' object has no attribute 'fit_start_x_moved'`

**Review by gemmaguest — CHANGES_REQUESTED** [review]
Code changes look good and on the whole it works as described and is a good improvement :+1:. Just a few issues I found while testing:
- The unhandled exception I mentioned in the previous comment.
- If I edit StartX or EndX in the text boxes to be outside the allowed range, then the marker is shown at the limit but the text box shows the value I entered - this is confusing because I don't know which is correct.
- If I pan or zoom, the boundaries remain limited to the original start/end of what was visible when I enabled Fit, which I find confusing (e.g. zoom in, click Fit, zoom out, then try to move the markers wider and they won't go).

**Comment by robertapplin** [comment]
@gemmaguest Thanks for the review, I have fixed the top two points you mentioned. I am not sure I understand the third one. The range marker should have a upper and lower bound within which it can move (based on the first and last x value of the displayed spectrum), so I don't think panning and zooming should affect this.

**Review by gemmaguest — APPROVED** [review]
Thanks for the changes. The code looks good and all the issues I found are fixed :+1:

(We discussed the issue with pan/zoom offline because my description was a bit misleading - it was to do with when you first enable Fit using the toolbar button, not when you perform a Fit from the drop-down menu).

One minor thing we might want to change in future is that if you manually enter a start/end value that's outside the limits, it currently gets ignored. It might be better to clip it to the limit instead. This would depend how users want to use it though, and I think the current behaviour is still better than before, so I'm happy for this to go in.

**Pull request merged**
