### PR TITLE
Fix display formatting issues on Muon plotting and Fitting tabs for 4k displays

### LINKED ISSUE #31234: muon display problems
On nightly I do not have the x or y boxes (beneath the plot) for selecting the plotting range. 

image

### PR DESCRIPTION
**Pull request by sf1919**
**Description of work.**
This fixes display issues caused by using Muon Analysis and Frequency Domain Analysis with a 4k display.

**To test:**
1. Open Mantid
2. Open Interfaces >> Muon >> Frequency Domain Analysis
3. Check that X max, X min, Y max and Y min appears beneath the plotting window
4. Open the Fitting Tab 
5. Check that Plot Guess, Selected Workspace and Fit Status on the left hand side of the screen can be read in full.
6. Close The Frequency Domain Analysis GUI
7. Open Interfaces >> Muon >> Muon Analysis
8. Check that X max, X min, Y max and Y min appears beneath the plotting window
9. Open the Fitting Tab
10. Check that Fitting Type, Plot Guess, Simultaneous over, Select Workspace and Fit Status on the left hand side of the screen can be read in full.

Fixes #31234 .

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
looks good on my high res laptop. I still need to check it on Linux. @Matt-Cumber I have started a build to produce a mac installer for you to test

**Comment by Matt-Cumber** [comment]
Everything is visible on Mac and the min max line edits are not squished

**Comment by AnthonyLim23** [comment]
looks good on my linux too

**Review by AnthonyLim23 — APPROVED** [review]
It looks good on all OS's :shipit:

**Pull request merged**
