### PR TITLE
Remove deprecation of PerformIndexOperations after tester complaint

### LINKED ISSUE #15261: Remove deprecation of PerformIndexOperations
From James Lord:

While setting up input workspaces to test Maxent I note that I can use (deprecated) PerformIndexOperations to swap two spectra in a workspace or arbitrarily select and rearrange them, but that its replacement GroupDetectors (with the GroupingPattern property set) leaves the selected spectra sorted in the original order!

I am supposed to believe the message:
PerformIndexOperations has been deprecated. It will be removed in the next release of Mantid. The same functionality is provided by GroupDetectors-v2. Its GroupingPattern property accepts the same syntax as PerformIndexOperations' ProcessingInstructions property.

Compare for example:

Load(Filename=r'\\britannic\MuonTrainingCourse\Reference material\CdS\Data\EMU00020721.nxs', OutputWorkspace='EMU00020721') # any workspace should do

GroupDetectors(InputWorkspace='EMU00020721', OutputWorkspace='GroupedForward', GroupingPattern='0,1,3') GroupDetectors(InputWorkspace='EMU00020721', OutputWorkspace='GroupedReverse', GroupingPattern='3,1,0') PerformIndexOperations(InputWorkspace='EMU00020721', ProcessingInstructions='0,1,3', OutputWorkspace='IndexedForward') PerformIndexOperations(InputWorkspace='EMU00020721', ProcessingInstructions='3,1,0', OutputWorkspace='IndexedReverse')

GroupedForward and IndexedForward are correct, containing spectra 1,2,4, as is IndexedReverse which has the spectra swapped round as intended (4,2,1). GroupedReverse isn't!

Also playing with GroupDetectors a second time on the above output workspaces it appears that the "workspace index" numbers 0 to N-1 are interpreted as spectra i+1. For example:

PerformIndexOperations(InputWorkspace='IndexedReverse', ProcessingInstructions='1,2', OutputWorkspace='IndexedRevThenIndForw')
This works and gives spectra 2 and 1 in that order.

GroupDetectors(InputWorkspace='IndexedReverse', GroupingPattern='1,2', OutputWorkspace='IndexedRevThenIndForw')
This gives an error:
Error in execution of algorithm GroupDetectors:
Spectrum number 3 not found

GroupDetectors also doesn't work if the Workspace doesn't have spectrum numbers on its Y axis (I suppose the name implies it shouldn't, but there isn't then a suitable replacement for PerformIndexOperations...)

### PR DESCRIPTION
**Pull request by NickDraper**
This just removes the deprecation tag from PerformIndexOperations after feedback from one of our testers that GroupDetectors cannot do all of the things that it allowed.
### Release Notes

Nothing to include for this
### To Test

run PerformIndexOperations you should not get the deprecation warning

fixes #15261

### CODE REVIEW

**Comment by NickDraper** [comment]
Py lint error is nothing to do with this change - no python was touched

**Comment by martyngigg** [comment]
Yes, the pylint error has a fix on `master` that is not on the `release` branch. It can be safely ignored

**Comment by KarlPalmen** [comment]
Deprecation warning still appears when usage example is run.

**Comment by KarlPalmen** [comment]
but the deprecation message is not present in the documentation.

**Pull request merged**
