### PR TITLE
Fix for crash when opening instrument view with old Muon data

### LINKED ISSUE #34544: Instrument viewer crashes with DEVA workpace with no facility and IDF
**Describe the bug**
When loading very old data that does not have a facility and IDF associated with it, you can end up with a workspace that will crash Mantid if you attempt to view it in instrument viewer.

Low priority because users are unlikely to load this old data, but the hard crash should be resolved.

**To Reproduce**

- Load DEVA01360 from the ISIS sample data.
- Show instrument on one of the workspaces. Mantid crashes

**Expected behavior**
It's probably useful to still be able to view very old data like this, so I think we would like to still be able to load the data, but just disable instrument viewer in this case. However if this turns out to be a large amount of work we may want to reconsider whether we support loading data like this.

**Platform/Version (please complete the following information):**
 - OS: Ubuntu, probably all

**Additional context**
We think that this is due to the workspace not having an instrument, so it is hopefully a simple check. However, using `CreateWorkspace` I think creates a workspace with no instrument, and `Show Instrument` is greyed out in this case, so I'm not sure if there is something else going on too. Hopefully catching the crash in the debugger will give more information.
```
ws=CreateWorkspace([1,2,3], [4,5,6])
```

For info, this is an old ISIS instrument that is decommissioned: https://www.isis.stfc.ac.uk/Pages/deva.aspx

### PR DESCRIPTION
**Pull request by jhaigh0**
### Description of work

https://github.com/mantidproject/mantid/pull/16406 made it possible to load certain old data. As part of this, an empty instrument was added to the workspace by LoadEventMuon which caused a problem when opening the instrument viewer.

This PR adds a check when constructing the instrument renderer to check for an empty instrument.

Fixes #34544

### To test:

- Load `DEVA01360.nxs` from the unit test data (you may have to build the `StandardTestData` target if not already built)
- Attempt to open one of the workspace in the instrument viewer, there should be an appropriate warning and no crash

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by robertapplin — CHANGES_REQUESTED** [review]
Loaded the old Muon dataset and attempted to do "Show Instrument". It now shows a warning that no detectors were found, and does not crash. Code changes look good - just wanted to check would it be possible to add a test for this, or not so easy?

**Comment by jhaigh0** [comment]
> Loaded the old Muon dataset and attempted to do "Show Instrument". It now shows a warning that no detectors were found, and does not crash. Code changes look good - just wanted to check would it be possible to add a test for this, or not so easy?

I thought a test might be not so bad to write but then found that there is no test file for the InstrumentRenderer...

**Comment by jhaigh0** [comment]
> Ah I see. If you are willing, it would be great to add a test file (but only add a test case for whats fixed in this PR so you dont need to do too much). Feel free to push back on this suggestion though if you think its not worth the effort

No I think that's worthwhile, I'll have a look at that

**Review by robertapplin — APPROVED** [review]
Thanks for adding the test file - this looks like a good fix to me :)

**Pull request merged**
