### PR TITLE
Release GIL in WorkspaceGroup ADS updates

### LINKED ISSUE #33863: GIL and ADS observer deadlock with workspace groups
**Original reporter:** Max at ISIS

**Describe the bug**
There is still a hang similar to #33664 where Mantid can get into a deadlock where:
- A python algorithm is running and holds the GIL. This algorithm calls into code that causes an ADS update without releasing the GIL.The ADS notification waits on a Poco lock to notify its observers.
- Meanwhile another thread is already doing a Poco notification and has that lock; but that notification causes a call into python which requires the GIL, ending in deadlock.

The problem is that the first thread is not releasing the GIL before calling into the C++ code that does the ADS update.

A fix was added in PR #33756 to ensure DataServiceExporter calls that cause ADS notifications release the GIL. However we are seeing the same problem with the exports for [WorkspaceGroup](https://github.com/mantidproject/mantid/blob/main/Framework/PythonInterface/mantid/api/src/Exports/WorkspaceGroup.cpp#L86) so a similar fix needs to be added there for any WorkspaceGroup methods that cause ADS updates (I think this comprises `add`, `addWorkspace` and `remove`). 

**To Reproduce**
At the moment I can only reproduce this in the reflectometry GUI with live data and batch processing running. This requires the ISIS archive to be enabled and also requires live data to be running on an ISIS reflectometry instrument so needs to be done in cycle during an experiment. However, testing the below with batch processing only would also exercise the affected code to ensure nothing is broken after we fix this, even if it's hard to reproduce the problem.

- Open the ISIS Reflectometry interface
- Go to the Batch->Load menu and load this [json file](https://github.com/mantidproject/mantid/files/8653732/python_hang_batch.zip)
- Click Start Monitor. This starts the live data monitor and after a while should result in two workspaces - `TOF_live` and `IvsQ_binned_live` if valid live data is running and can be reduced. Open sliceviewer on the former and a line plot on the latter. If this fails, skip this step.
- Click Process to start processing the runs in the table. They should gradually turn green as processing completes.
- Leave everything running. I find the deadlock normally occurs within a minute or so.

**Expected behavior**
It should  be possible to run multiple python algorithms simultaneously that cause ADS updates (including via WorkspaceGroup modifications) without crashing or deadlock. 

**Screenshots**
image

**Platform/Version (please complete the following information):**
 - OS: seen on IDAaaS and Ubuntu 20.04, but probably all
 - Mantid Version 6.3.0 and also the nightly including after PR #33756

### PR DESCRIPTION
**Pull request by gemmaguest**
**Report to:** Max at ISIS

This avoids a potential deadlock where the ADS update calls into python code and hangs waiting on the GIL

Fixes #33863

**To test:**

Follow the instructions in the linked issue and try to reproduce the bug. It should no longer be reproducible.

Note that I have found a similar bug when processing multiple batches at the same time so we are not completely robust against that; that's quite an edge case and is beyond the scope of this PR, so just test with processing one batch while live data is also running.

*This does not require release notes* because **it is already covered by the release note for #33756**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
I just noticed this is going to `main`. Should we put this one in the release?

**Review by cailafinn — DISMISSED** [review]
No longer crashing and the code changes look good to me. Good to get this in, hopefully Max doesn't find any more 👍 

Edit: Yes, off the back of what Martyn said, should probably be in release-next. I need to get back into the release habit of checking that

**Comment by sf1919** [comment]
Is this on the correct base branch?

**Review by martyngigg — CHANGES_REQUESTED** [review]
I'm just going to hit "request" for changes so the target branch can be fixed without risk of this being merged beforehand.

**Review by martyngigg — APPROVED** [review]

**Pull request merged**
