### PR TITLE
CalculateFlatBackground: supports histogram and distributions

### LINKED ISSUE #18015: CalculateFlatBackground: remove HistogramValidator and its include
### Actual behavior

The algorithm `CalculateFlatBackground` works only for histograms but must work for non histogram data. In particular, it is recommended that the workspace must have const bin width or must be a distribution.

Delete #include "MantidAPI/HistogramValidator.h"
and delete HistogramValidator from

  declareProperty(
      make_unique<WorkspaceProperty<>>(
          "InputWorkspace", "", Direction::Input,
          boost::make_shared<HistogramValidator>()),
      "The input workspace must either have constant width bins or is a "
      "distribution\n"
      "workspace. It is also assumed that all spectra have the same X bin "
"boundaries");

### Platforms affected

All

### PR DESCRIPTION
**Pull request by vreimund**
Running `CalculateFlatBackground` with point data tells you that the InputWorkspace is required to be a histogram. The code indeed uses the histogram validator for the input workspace. However, the documentation says that in particular distributions are supported as well as histograms with constant bin width. The implementation is well designed to take histograms and distributions into account.

I deleted some includes for header files that are not necessary as well.

I will create a next issue for taking care of the input validation.

**To test:**

Run `CalculateFlatBackground` with a distribution as recommended by the documentation.
For example, run:

``` Python
# Create a test distribution
X = ([1, 2, 1, 2, 1, 2])
Y = range(2*3)
E = np.ones(2*3)
CreateWorkspace(DataX=X, DataY=Y, DataE=E, NSpec=3, OutputWorkspace='test_1', Distribution=True)
CalculateFlatBackground(InputWorkspace='test_1', OutputWorkspace='out', StartX=0, EndX=10, OutputMode='Return Background', SkipMonitors=True)
```

Fixes #18015.

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
The documentation could do with a usage example with a distribution. To test this, I'll need to know how to obtain a distribution.

**Comment by reimundILL** [comment]
I added an example how to get a distribution for test on top. I think the only thing to take care about is that x y and e have the same size. Code in the documentation can then be easily modified. Do you think I should update the documentation as well? I wanted to keep changes as little as possible and as much as necessary.

**Comment by KarlPalmen** [comment]
Yes. I'd appreciate an update of the documentation.

**Comment by KarlPalmen** [comment]
Usage examples in documentation look good.

**Comment by KarlPalmen** [comment]
:shipit: , subject to builds working.

**Pull request merged**
