### PR TITLE
NexusDescriptor, LoadHelper :: Stop recursion on certain group entries

### LINKED ISSUE #19009: Custom nexus attribute issue in NexusDescriptor and LoadHelper
`NexusDescriptor`, used in `confidence` methods of the loaders crawls recursively into the HDF tree of the file to set up the tree hierarchy. `LoadHelper`, used in many loaders, recursively walks through the file to read all the metadata leafs into sample logs.

In the case when a nexus file has a HDF group entry that contains a variable length string type entry unknown to nexus (e.g. ILL data for scanning instruments), they both segfault on recursion, when reaching this entry. The actual problem is in the nexus side with freeing the memory for variable-length string type of HDF entries.

The solution is to add a custom attribute for these special files and to stop the recursion when hitting a data group with that attribute.

(Alternative solution was to cut the recursion if NXclass attribute is not specified, and this worked as well.)

### PR DESCRIPTION
**Pull request by gvardany**
[files.zip](https://github.com/mantidproject/mantid/files/1011217/files.zip)

At ILL a new format of nexus files are planned to be produced for the scanning instruments.
The actual *scanned data* block is implemented using HDF5 hyper slabs, which is not in official nexus specification. 
When trying to read these blocks with regular nexus machinery one runs into a memory problem, that is tracked down to be inside the nexus code, and not in mantid or hdf (see the issue description).
This PR implements a protection relying on the custom NXclass names that are attributed to the new type of nexus files.
The aim is to stop the recursion in `NexusDescriptor::walkFile` ([L252](https://github.com/mantidproject/mantid/pull/19031/files#diff-5ac18ff3234bdf712052b6dc486ce826R252)) and `LoadHelper::recurseAndAddNexusFieldsToWsRun` ([L214](https://github.com/mantidproject/mantid/pull/19031/files#diff-cf91cb19ced37e956a8ebf60b08e65a7R214)) when hitting the custom entry for ILL data scan block.

The rest of the changes in this PR **do not** change any behaviour, they are some minor improvements for readability and error handling.

**To test:**

1. Merge in branch #18868 and build.
2. Set the facility to ILL.
3. Try to load all the attached files with the generic `Load`.
4. There should be no crash, neither after closing MantidPlot.

Fixes #19009 .

Does not need to be in the release notes.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@gvardany The attached zip file seems to be empty.

**Comment by gvardany** [comment]
I have updated it, please check again.

**Comment by martyngigg** [comment]
The code changes look okay to me and I've tested some ISIS files and the logs all load okay. 

I think it is worth either @ianbush or @soininen double checking some more files as the large set of changes are in the code that only reads ILL files.

**Review by martyngigg — COMMENTED** [review]
The code changes look okay to me and I've tested some ISIS files and the logs all load okay.

I think it is worth either @ianbush or @soininen double checking some more files as the large set of changes are in the code that only reads ILL files.

**Comment by ianbush** [comment]
I have tried these changes with another file, before the inclusion of the class name to skip, and everything looked to work.

Unfortunately, after that one, there are no more we can test with for now.

**Comment by martyngigg** [comment]
@gvardany Thanks. When I try to load either of the files I get an error:

```
Error in execution of algorithm LoadILLTOF:
The instrument D20 is not valid for this loader!
Error in execution of algorithm Load:
The instrument D20 is not valid for this loader!
```

**Comment by ianbush** [comment]
@martyngigg I have just realised you mean standard ILL files, I will have a double check.

**Comment by gvardany** [comment]
Can you merge in branch #18868 and try again? Or you can directly try on that branch, since this one is merged in there.

**Review by martyngigg — APPROVED** [review]
@gvardany Thanks. I've confirmed that without these changes I indeed get a segfault when trying to load the D20 files attached here. This is fixed by these changes.

**Comment by martyngigg** [comment]
@ianbush I'm happy with this. If and when you are could you stick the squirrel on?

**Comment by ianbush** [comment]
Testing files for D33, D17 and IN5 show no issues :shipit: .

**Pull request merged**
