### PR TITLE
Add Polarization Efficiencies to GUI

### LINKED ISSUE #34744: Specify polarisation efficiencies via a workspace
Currently in the ISIS Reflectometry interface, polarisation analysis can be done but is limited to using efficiencies specified in the Instrument Parameter File. For POLREF, users need more flexibility and would like to be able to provide a workspace/filename instead. We should add an option similar to the flood correction to be able to use a workspace or the parameters file. (Although check whether the parameters file method is still useful; if not, remove it.)

image

It would be useful to do #34720 first and then we can use the same pattern for the polarisation corrections.

**Implementation**
I think it should be straightforward to optionally use a passed-in workspace instead of one extracted from the parameters file.
- In `ReflectometryReductionOneAuto` add input properties to pass the workspace and correction method (`Efficiencies` and `CorrectionMethod` from `PolarizatioEfficiencyCor`).
- `ReflectometryReductionOneAuto::getPolarizationEfficiences()` currently creates the efficiencies workspace from the parameters file. It should use the passed-in workspace instead, if one is given. Note that this method also returns a "correction option" which indicates the type of polarisation analysis being done; this can be inferred from the number of workspaces in the input workspace group (2=>PNR, 4=>PA).
- `ReflectometryISISLoadAndProcess` should take a filename and do the necessary loading then pass it to RROA as a workspace. It should also expose the `CorrectionMethod` property.

### PR DESCRIPTION
**Pull request by cailafinn**
# BLOCKED BY: 
- [x] #34805

**Description of work.**
Adds a GUI element to allow selection of a workspace for the new Polarization Efficiencies property of the Refl Load and Process algorithm. 

The logic is set up such that the check box enables and disables the polarization correction, then the combo box allows selection of workspaces or to be left blank should the user wish to use the values in the parameter file. 

**To test:**
1. Talk to Conor or Rachel about getting the corrections file. It's not public, so it can't be put here. 
2. Load the file into mantid
3. Boot up the Refl GUI
4. Switch the instrument to POLREF.
5. Go to the Experiment Settings Tab
6. Enable polarization corrections
7. Check the combo box gets enabled. 
8. Select the downloaded workspace
9. Go back to the Runs tab
10. Enter `31835` into the Run column (not the group, the second box down) and `1.0` into the angle column
11. Click process
12. Check that the `IvsLam_31835` workspace group contains a workspace ending with `_--` and `_++`

Fixes #34744 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by rbauststfc — COMMENTED** [review]
These changes look great for providing the GUI functionality that we need for the scientists' December experiment and they're working really well for me. 👍

I'll hold off approving this until the algorithm changes have been approved to avoid this accidently being merged in too soon. It may also be good for Gemma to gatekeeper this one so that we get the benefit of her expert testing, given that these changes will be used soon after they have gone in.

There are a few things that I wanted to make a note of so that we remember to look at them as we continue to develop this after this first phase, but they're not important to sort out now:

1) When you change instrument in the dialog it correctly disables the polarization correction controls and unticks the Polarization Analysis checkbox, but doesn't clear the Polarization Efficiencies workspace. The selected workspace won't be used without the tick box being ticked, so there's no bug here, but it might be nice just as a tidy-up to clear the selected workspace as well.

2) We've discussed that a next step for this would be to allow the user to pass in a file name as an alternative to a workspace name. The algorithms support this already, so it would just be a change to the GUI. The same functionality is required for providing the flood workspace, so these could be looked at together, as suggested on the issue.

3) We should look at hooking up saving and reloading the value of the new input via the Encoder and Decoder.

4) We should confirm if there's still a need for the option to look up polarization correction settings from the parameter file. This currently won't work for POLREF because they don't have the necessary settings.

**Comment by ConorMFinn** [comment]
> There are a few things that I wanted to make a note of so that we remember to look at them as we continue to develop this after this first phase, but they're not important to sort out now

I've created an issue for this stuff here:
#34812

**Review by rbauststfc — DISMISSED** [review]
@mantidproject/gatekeepers please could this be prioritised? It's the GUI side that needs to be merged after PR #34805 (please don't merge it until #34805 has gone in)

**Comment by sf1919** [comment]
@mantidproject/gatekeepers - #34805 has now gone in so this is ready to be reviewed

**Review by DannyHindson — APPROVED** [review]
Re-approving following rebase onto main following #34805 merge

**Pull request merged**
