### PR TITLE
(Topic Branches) Add Recovery to config and remove WS from ADS after

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**
- Wraps all the new code in try catch blocks to exit the thread if something goes wrong
- Adds a new config option for these changes
- Adds WS blacklisting, removing all workspaces that did not exist prior
- Automatically saves in timestamped folders, which are rotated so only 5 are present (by default)

**To test:**
- Check `%appdata%/recovery` a maximum of 5 checkpoints should be present
- It should save every minute
- Switch the config option off and check that saving stops
- Add a failure to the python script (e.g. `str(1)+int(2)`) check it stops once

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by keeeto** [comment]
Hi @DavidFair , I am getting a build error on this 

`/Users/keithbutler/src/mantid-git/mantid/MantidPlot/src/ProjectRecoveryThread.cpp:37:11: error: use of undeclared identifier 'SAVING_ENABLED_CONFIG_KEY'
          SAVING_ENABLED_CONFIG_KEY, returnedValue);
          ^
/Users/keithbutler/src/mantid-git/mantid/MantidPlot/src/ProjectRecoveryThread.cpp:32:54: warning: unused parameter 'key' [-Wunused-parameter]
boost::optional<T> getConfigValue(const std::string &key) {`

**Comment by DavidFair** [comment]
Ahh good catch, that was a bug where it was only loading the key. I've pushed a fix

A lot of that code should be moved elsewhere in #22647

**Comment by keeeto** [comment]
Nice, builds now. I'll test it out.

**Review by keeeto — APPROVED** [review]
This works properly now.

**Pull request merged**
