### PR TITLE
BASISReduction: option to carry out powder reduction

### LINKED ISSUE #25425: BASISReduction: option to carry out powder reduction
To-Do's:
- [ ] Add checkbox in `BASISReduction` algorithm to call `BASISPowderReduction`
- [ ] Add source to `BASISReduction` algorithm to implement a call to `BASISPowderReduction`

### PR DESCRIPTION
**Pull request by jmborr**
**Description of work.**
To-Do's:
- [x] Add checkbox in `BASISReduction` algorithm to call `BASISPowderReduction`
- [x] Add source to `BASISReduction` algorithm to implement a call to `BASISPowderReduction`
- [x] Update algorithm documentation
- [x] Update release notes
- [x] Test for PR reviewer

**Report to:** N/A

**To test:**
Donwload the [comparison data](https://www.dropbox.com/s/i7vpizogshlfub7/reference_data.zip?dl=0) and unzip under directory `/tmp`. Then run the following script than runs the reduction and loads the comparison data. It will take a few minutes to complete

```
BASISReduction(RunNumbers='90177',
               DoFluxNormalization=True,
               FluxNormalizationType='Monitor',
               ReflectionType='silicon_111',
               EnergyBins=[-100, 0.4, 100],
               MomentumTransferBins=[1.1, 1.8, 1.1],
               DivideByVanadium=True,
               NormRunNumbers='90176',
               OutputPowderSpectrum=True)
reference_sqw = LoadNexus('/tmp/BASIS_90177_divided_sqw.nxs')
reference_sq = LoadNexus('/tmp/BASIS_90177_divided_sq.nxs')
reference_sq_angle = LoadNexus('/tmp/BASIS_90177_divided_sq_angle.nxs')
```
You can plot the following workspaces together. They should match:
- `reference_sqw` and `BSS_90177_divided_sqw`
- `reference_sq` and `BSS_90177_divided_sq`
- `reference_sq_angle` and `BSS_90177_divided_sq_angle`

Fixes #25425

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by VickieLynch — DISMISSED** [review]
Output does match reference data. Documentation added and also release note. Coding is acceptable. Future work should be to reduce execution time below 19 minutes.

**Comment by martyngigg** [comment]
@jmborr There seems to be a problem downloading `BASIS_90177_divided_sq.nxs`. Did it get uploaded to the server?

**Comment by jmborr** [comment]
@martyngigg  thanks for letting me know, I'm going to check after I arrive to work

**Comment by jmborr** [comment]
@martyngigg Gosh, I just realized this file was only meant for a local test using the system test suite, not to be uploaded to the remote store :blush: I have deleted the related md5 file and pushed to remote

**Comment by martyngigg** [comment]
@jmborr Thanks for fixing that.

**Comment by martyngigg** [comment]
The system test failure is unrelated.

**Comment by jmborr** [comment]
@VickieLynch @martyngigg :dancing_women:  thanks a million :dancing_women:

**Pull request merged**
