### PR TITLE
SANS - Wav loops speedup

### LINKED ISSUE #28987: Speed up looping over wavelengths for SANS
At the moment reductions iterating over multiple wavelength slices are very slow because the looping is performed _outside_ of Q1D. As there is an increased operational need at ISIS to perform more regular wavelength overlap checks (eg, for signs of multiple scattering, but also for future autovalidation), and to facilitate the simulation of the ESS Loki instrument, this looping should be moved _inside_ Q1D.

This will not be a simple task and, because it touches the heart of the ISIS SANS data reduction, it will need very careful testing and validation to ensure that the new procedure replicates the existing output.

This now a quite urgent task.

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**

The final part of the wavelength loops work. In this PR we:
- Move wavelength information into a simpler format (list of pairs)
- Rework the core SANS Reduction loop to process n wavelength slices during one pass, rather than n passes
- "Re-plumb" the properties to get the expected workspaces back, in the expected order
- Simplified the output bundles data structure and how to iterate over it significantly

One victim of these changes was the SANSReductionCore V2 workflow which will no longer work. However this is not used in the group as there is a small unexplained difference in results.
The development effort for the small performance gain on event workspaces to both explain or fix the differences / switch over and now fix-up is not a priority based on the sprint planning.

**To test:**
- Download the ISIS Training data set
- Open Mantid and SANS->ISIS SANS
- Point the user file to either the toml or .txt file called MaskFile in LoqDemo
- Open the CSV file in the same folder
- Select the first row and hit process
- Go to settings, Q, Wavelength
- Under Wavelength change `Log` to `RangeLog`
- Enter `1:1:15` to process wavelength slice 1-15 in 1 Angstrom slices
- It should be noticeably faster than master, data validity has been checked by running the same system tests (unmodified) before and after these changes

Fixes #28987 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DavidFair** [comment]
I've tweaked this for 6.1. Now we have a separate master/main branch would somebody be able to look at reviewing and merging it so we have testing time for the subsequent release?

**Comment by gemmaguest** [comment]
@martyngigg We'd like to get this in now. You're still assigned - do you want to finish the review, or shall I take over?

**Comment by martyngigg** [comment]
@gemmaguest Apologies, I hadn't spotted I was still assigned. If you could take over the review that would be great.

**Review by gemmaguest — CHANGES_REQUESTED** [review]
Seems about 20 seconds quicker (40s vs 60s) in a debug build :+1:

I'm getting this error though when I reprocess a row that's already been processed. If I delete the `first_time_trans` group and try again then it works.

```
SANSSingleReduction-[Notice] SANSSingleReduction started
SANSSingleReduction-[Error] Error in execution of algorithm SANSSingleReduction:
SANSSingleReduction-[Error]
SANSSingleReduction-[Error]   at line 108 in '/home/gemma/work/checkout/mantid2/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANS/SANSSingleReduction.py'
SANSSingleReduction-[Error]   caused by line 138 in '/home/gemma/work/checkout/mantid2/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANS/SANSSingleReductionBase.py'
SANSSingleReduction-[Error]   caused by line 201 in '/home/gemma/work/checkout/mantid2/scripts/SANS/sans/algorithm_detail/single_execution.py'
SANS-[Error]   File "/home/gemma/work/checkout/mantid2/scripts/SANS/sans/gui_logic/models/batch_process_runner.py", line 80, in _process_states_on_thread
    self.batch_processor([state.all_states], use_optimizations, output_mode, plot_results, output_graph, save_can)
  File "/home/gemma/work/checkout/mantid2/scripts/SANS/sans/sans_batch.py", line 33, in __call__
    return self._execute(states, use_optimizations, output_mode, plot_results, output_graph, save_can=save_can)
  File "/home/gemma/work/checkout/mantid2/scripts/SANS/sans/sans_batch.py", line 43, in _execute
    save_can=save_can)
  File "/home/gemma/work/checkout/mantid2/scripts/SANS/sans/algorithm_detail/batch_execution.py", line 125, in single_reduction_for_batch
    reduction_alg.execute()

SANS-[Error]
  at line 108 in '/home/gemma/work/checkout/mantid2/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANS/SANSSingleReduction.py'
  caused by line 138 in '/home/gemma/work/checkout/mantid2/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANS/SANSSingleReductionBase.py'
  caused by line 201 in '/home/gemma/work/checkout/mantid2/scripts/SANS/sans/algorithm_detail/single_execution.py'
```

**Comment by DavidFair** [comment]
Closing as CI is struggling with this older PR in favour of...

**Pull request closed without merging**
