### PR TITLE
Add calculation to invert a symmetric tridiagonal matrix and speed up MonteCarloAbsorption

### LINKED ISSUE #29253: Improve performance of the HistogramData::interpolateYCSplineInplace error calculation
The error calculation that has recently been implemented in HistogramData::interpolateYCSplineInplace (used by MonteCarloAbsorption for example) includes a matrix inversion that currently uses the Kernel::Matrix::Invert function
This means that MonteCarloAbsorption calculations that involve spline interpolation (mainly calculations done with a sparse instrument) on histograms with a lot of bins have slowed down. 
The matrix is a tridiagonal matrix whose inverse can be calculated via an analytic formula which is faster. This is described in this paper ("Analytical inversion of symmetric tridiagonal matrices", G Y Hu and R F O’Connell, J. Phys. A: Math. Gen. 29 (1996) ):
https://pdfs.semanticscholar.org/7dea/05d36df6d8b68f849c2096ed4c702880e6aa.pdf?_ga=2.83631315.433930395.1598440014-1935417443.1587399255
This issue covers implementation of that analytic formula and minor change to HistogramData::interpolateYCSplineInplace to use this

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

The error calculation in HistogramData::interpolateYCSplineInplace requires a matrix to be inverted. This has caused the absorption calculations in MonteCarloAbsorption to slow down in some cases when spline interpolation is used (mainly when a sparse instrument calculation is run) on a workspace with a large number of bins
This change speeds up the absorption calculations by implementing a fast analytical calculation to invert a tridiagonal matrix in the special case where it's symmetric and the diagonal elements (in each of the 3 diagonals) are the same. If the matrix doesn't satisfy these conditions, the inversion function just reverts to the standard Matrix::Invert function.
The analytic calculation is described here:
"Analytical inversion of symmetric tridiagonal matrices", G Y Hu and R F O'Connell, J. Phys. A: Math. Gen. 29 (1996)
[AnalyticalInversionOfSymmetricTridiagonalMatrices.pdf](https://github.com/mantidproject/mantid/files/5163931/AnalyticalInversionOfSymmetricTridiagonalMatrices.pdf)

Having worked through the derivation in the paper I got a couple of different minus signs for the case where -2 < D < 2. So my implementation isn't a 100% match. My implementation does produce correct inverses on simple 2x2 matrices though with D values in this range so happy these extra features in my code are correct

**To test:**

Run ILLDirectGeometryReduction.IN4 system test (on release build) before and after this PR. This test runs the DirectILLSelfShielding algorithm which in turn runs the MonteCarloAbsorption algorithm with a sparse instrument with CSpline interpolation specified. When run locally I see a speed up from about 1m 10 seconds to about 50 seconds

Fixes #29253 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by Pasarus — DISMISSED** [review]

**Comment by gvardany** [comment]
I wonder how long did `ILLDirectGeometryReduction.IN4` test take before the error calculation is introduced (still with sparse and CSpline)? What about the output, does this change the error, or it only improves the performance? Also, could you add a reference to the paper in the documentation, including your notes that there are couple of signs that do not match.

**Comment by DannyHindson** [comment]
This performance improvement means that the run time of the ILLDirectGeometryReduction.IN4 test is now equal to what it was before the error calculation was introduced (so was ~50 seconds for me before the error calculation and is now back to that duration).
This change does not change the output, just the speed.
Yes will add a note to the documentation. The Matrix class and its methods aren't documented anywhere I think so will add the reference to the MonteCarloAbsorption documentation page which is the only place that uses the new method

**Comment by DannyHindson** [comment]
@gvardany - would you be able to have another look at this and approve\merge ahead of the code freeze? I just did one further commit which was the documentation change you requested

**Comment by gvardany** [comment]
I am happy with the explanation, @Pasarus can you approve again?

**Review by Pasarus — APPROVED** [review]

**Pull request merged**
