### PR TITLE
EnginXFitPeaks: add new optional property to generate table workspace

### LINKED ISSUE #11748: EnginX FitPeaks Output
This ticket is blocks :  [TRAC8368](http://trac.mantidproject.org/mantid/ticket/8368)

FitPeaks currently does not output the difc and zero values. They are accessible through the python console but having them available in a table would be better.

### PR DESCRIPTION
**Pull request by FedeMPouzols**
This fixes #11748

**To test**:
- Tests should pass. The new option is tested in a doc-test but like in PR #806 I refrained from adding a test case for it in the unit test as that would further slow it down 
- Code review.
- You can also double-check if it works locally with commands like in the doc-test:

```
difc, zero = EnginXFitPeaks(ws, 0, [0.65, 1.9], OutputParametersTableName=out_tbl_name)
```

There's a small ugliness in that there's a bit of code duplication with PR #806, as these two are in different tickets. This is commented in the code and can be sorted out, putting common utility methods in EnginXUtils, in follow-up tickets/issues when these two are merged. This can be done for example in [#10910](http://trac.mantidproject.org/mantid/ticket/10910#comment:9) which is in part about refactoring common stuff and moving it into EnginXUtils.

### CODE REVIEW

**Comment by Anders-Markvardsen** [comment]
Note running algorithm with ENGIN00213855, Workspaceindex=0 and ExpectedPeaks=0.65,1.9 generates the output:

EnginXFitPeaks started
i_min = 2354 i_max = 9503
Error in execution of algorithm ConvertTableToMatrixWorkspace:
The input table is empty
Error in execution of algorithm EnginXFitPeaks:
The input table is empty
  at line 67 in 'C:/Backup/Backup_folder1/work/code/Mantid/git/mantid/Code/Mantid/Framework/PythonInterface/plugins/algorithms\EnginXFitPeaks.py'
  caused by line 194 in 'C:/Backup/Backup_folder1/work/code/Mantid/git/mantid/Code/Mantid/Framework/PythonInterface/plugins/algorithms\EnginXFitPeaks.py'
  caused by line 205 in 'C:/Backup/Backup_folder1/work/code/Mantid/git/mantid/Code/Mantid/Framework/PythonInterface/plugins/algorithms\EnginXFitPeaks.py'

**Comment by FedeMPouzols** [comment]
Ah, this is actually an error condition that wasn't being checked. I've added a verbose exception for this.

If you do this (or any similar very wrong guess of the expected peaks):

```
Load("ENGINX00213855", OutputWorkspace='foo')
EnginXFitPeaks(InputWorkspace='foo', WorkspaceIndex=0, ExpectedPeaks=[0.65, 1.9, 33, 99])
```

You sould now get an error like this:

```
Error in execution of algorithm EnginXFitPeaks:
Could not fit any peak. Please check the list of expected peaks, as it does not seem to be appropriate for the workspace given. More details: Could find 4 peaks using the algorithm FindPeaks but then it was not possible to fit any peak starting from these peaks found and using 'BackToBackExponential' as peak function.
  at line 69 in '/home/fedemp/mantid-repos/mantid-urgent/mantid/Code/Mantid/Framework/PythonInterface/plugins/algorithms/EnginXFitPeaks.py'
  caused by line 204 in '/home/fedemp/mantid-repos/mantid-urgent/mantid/Code/Mantid/Framework/PythonInterface/plugins/algorithms/EnginXFitPeaks.py'
```
I added this as an exception, rather than simply an error message, as the algorithm cannot finish succesfully and cannot produce sensible output values when this happens.

**Comment by Anders-Markvardsen** [comment]
Now when running ENGIN00213855, Workspaceindex=0 and ExpectedPeaks=0.65,1.9 get the informative output:

Error in execution of algorithm EnginXFitPeaks:
Could not fit any peak. Please check the list of expected peaks, as it does not seem to be appropriate for the workspace given. More details: Could find 2 peaks using the algorithm FindPeaks but then it was not possible to fit any peak starting from these peaks found and using 'BackToBackExponential' as peak function.
  at line 69 in 'C:/Backup/Backup_folder1/work/code/Mantid/git/mantid/Code/Mantid/Framework/PythonInterface/plugins/algorithms\EnginXFitPeaks.py'
  caused by line 204 in 'C:/Backup/Backup_folder1/work/code/Mantid/git/mantid/Code/Mantid/Framework/PythonInterface/plugins/algorithms\EnginXFitPeaks.py'

**Comment by Anders-Markvardsen** [comment]
Code review good and test added for new algorithm property

**Pull request merged**
