### PR TITLE
Remove resize support from EventWorkspace

### LINKED ISSUE #17073: EventWorkspace has inconsistent settings for spectrum numbers
Some methods initialize `spectrumNumber = workspaceIndex` while others use `spectrumNumber = workspaceIndex + 1`. This might cause issues in various places. In particular it can lead to duplicate spectrum numbers.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Unlike `Workspace2D` or any other `MatrixWorkspace`, `EventWorkspace` had support for resizing. This is potentially dangerous (see, e.g., the bug #17073).

This change is also an important prerequisite for the introduction of centralized index handling in Mantid, in particular the MPI related bits, where resize support would be difficult and expensive.

**To test:**
- Thorough code review.
- Test the TOPAS and SNS live data listeners, they do not have any (activated) unit tests. Probably you need to be at SNS to do that.

Apart from simple cases where the resizing methods where not necessary, I adopted the strategy of creating a new workspace of correct size and calling `initializeFromParent`. This seems to be also the way `CreateEmptyInstrument` solves this problem.

Fixes #17073.

Internal change, no release notes.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
Is this worth including in R3.8?  Should we not just merge this into R3.9 early on?

**Comment by SimonHeybrock** [comment]
@NickDraper I suggested that in #TSC, put @peterfpeterson thought otherwise.

**Comment by peterfpeterson** [comment]
Doesn't this potentially double memory footprint during algorithm execution?

**Comment by SimonHeybrock** [comment]
@peterfpeterson Where?

**Comment by peterfpeterson** [comment]
I've been looking at this  more and it looks like you are right. I still need to try it out, and you need to resolve some merge conflicts.

**Comment by SimonHeybrock** [comment]
@peterfpeterson Great! I was not sure and thought you found such an algorithm...

Merge conflict resolved.

**Comment by peterfpeterson** [comment]
I tested this with a NOMAD reduction that includes `DiffractionFocussing` and didn't see appreciable difference in memory usage (staring at conky as it ran) compared to not having the changes. :shipit:

**Pull request merged**
