### PR TITLE
Add Hinting line edit to options column

### LINKED ISSUE #23022: Update sans GUI to use JobTreeView
The JobTreeView is now finished so should be put into the SANS GUI.

### PR DESCRIPTION
**Pull request by Matthew-Andrew**
**Description of work.**

This adds the line edit hints to the options column of the SANS table. It has had the branch from ~~~#23362~~~ merged in so should be merged after that branch has been merged into master and then had master merged into the release branch

**To test:**

* Open the SANS GUI
* Type 'W' into the options column you should be shown a hint for WavelengthMin and WavelengthMax
* Type 'E' into the options column you should be shown a hint for EventSlices

Fixes #23022 . 

*This does not require release notes* because being merged into feature branch

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gemmaguest** [comment]
@Mantid-Matthew Could you do the merge from master into the feature branch so that I can see just the changes that are relevant to this PR?

**Comment by Mantid-Matthew** [comment]
@gemmaguest I have now hopefully sorted out all the mergeing

**Comment by gemmaguest** [comment]
Looks like there are still conflict markers in JobTreeView.cpp

**Review by gemmaguest — CHANGES_REQUESTED** [review]
Code changes look good and it behaves as expected :+1: Just one minor query in line.

**Review by gemmaguest — APPROVED** [review]

**Pull request merged**
