### PR TITLE
Fix hb2a colltrans

### PR DESCRIPTION
**Pull request by Kvieta1990**
**Description of work.**

- This fixes the issue with the `HB2AReduce` algorithm when the 'colltrans' column is not available in the data file.

- This applies to the situation when the 'colltrans' motor is not connected during the measurement.

**To test:**

Launch the `mantidworkbench` and load in the following file on analysis to test out,

`/HFIR/HB2A/IPTS-29290/exp882/Datafiles/HB2A_exp0882_scan0012.dat`

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KedoKudo** [comment]
@Kvieta1990 I have two questions regarding this PR:

- Is there a Gitlab issue associated with this PR?  If so, could you link it in the description.
- Is there a sibling PR targeting `ornl-next`. If so, could you link it in the description?  If not, I think we need one.

**Comment by Kvieta1990** [comment]
> @Kvieta1990 I have two questions regarding this PR:
> 
> * Is there a Gitlab issue associated with this PR?  If so, could you link it in the description.
> * Is there a sibling PR targeting `ornl-next`. If so, could you link it in the description?  If not, I think we need one.

Thanks a lot for your comments!

- There is no GitLab issue associated with this PR.

- I can for sure create a sibling PR to `ornl-next`.

**Comment by Kvieta1990** [comment]
@KedoKudo This is the sibling PR to `ornl-next`, [https://github.com/mantidproject/mantid/pull/34703](https://github.com/mantidproject/mantid/pull/34703). I created this via cherry pick commits. Please let me know if anything further I need to do. Thank you!

**Comment by sf1919** [comment]
Please can you move the release note to v6.6.0?

**Review by KedoKudo — DISMISSED** [review]
The PR looks good and thanks for updating the reference file as well.

**Comment by Kvieta1990** [comment]
> Please can you move the release note to v6.6.0?

sure. will do that

**Comment by Kvieta1990** [comment]
@KedoKudo Following comments from @sf1919, I moved the doc to `v6.6.0` for this PR. Do we need to do the same thing for the PR to `ornl-next`?

Also, I noticed that the test the other PR (#34703) is stuck at `RHEL7 + System Tests` for overnight. Not sure what is happening there and how we can move forward. Any comments?

**Comment by sf1919** [comment]
RHEL7 is no longer supported. We've removed the tests from main but I wonder if ornl-next branch needs to be updated also? @peterfpeterson do you know?

**Comment by KedoKudo** [comment]
> @KedoKudo Following comments from @sf1919, I moved the doc to `v6.6.0` for this PR. Do we need to do the same thing for the PR to `ornl-next`?
> 
> Also, I noticed that the test the other PR (#34703) is stuck at `RHEL7 + System Tests` for overnight. Not sure what is happening there and how we can move forward. Any comments?

My understanding is that we only care about the checks in the PR targeting the main branch.  As long as this PR passes, we will merge the sibling one (targeting `ornl-next`) regardless of the sibling's build status.

@peterfpeterson Is my understanding correct or am I missing something important here?

**Review by KedoKudo — APPROVED** [review]

**Pull request merged**
