### PR TITLE
Indirect - Vesuvio - Add functionality for providing discontinuous list of runs

### LINKED ISSUE #20938: Indirect - Vesuvio - Allow for using a comma when defining run numbers in driver script
Currently in a Vesuvio driver script, run numbers can only be specified by defining an inclusive range with the format 'A-B'. It is therefore not possible to define a discontinuous range of run numbers.

To fix this, the ability to use a comma to create a list of run numbers/ranges should be added.

### PR DESCRIPTION
**Pull request by brandonhewer**
Currently, the LoadVesuvio algorithm cannot be used to load a discontinuous list of runs and as a result the Vesuvio driver script cannot be used to do so either.
This PR adds a method for parsing comma separated runs and run ranges with the specification:
A, B: Parse run string A and run string B
A-B: Parse all files from A to B inclusively
A: Parse run string A

**To test:**
1. Execute the supplied driver script, which uses a run string of format 'A-B, C' as a test.

**Test File:**
[vesuvio_driver_script.zip](https://github.com/mantidproject/mantid/files/1406608/vesuvio_driver_script.zip)

Fixes #20938. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gvardany** [comment]
Just was skimming over, have you considered using http://docs.mantidproject.org/nightly/api/python/mantid/api/MultipleFileProperty.html ?
It is quite a powerful property that does all this sort of parsing for you.

**Comment by brandonhewer** [comment]
@gvardany This is a great piece of advice - should have checked this before creating a method for achieving an identical effect. Cheers! :)

**Comment by brandonhewer** [comment]
@gvardany Do you know if there is a way to default the instrument for the property (to avoid adding 'VESUVIO' at the front of each run number? It could possibly break existing scripts which use LoadVesuvio.

**Comment by gvardany** [comment]
Glad this is helpful. I don't think there is a way to default the instrument name, however this could be a logical feature to add. In fact, for ILL we do not have the prefixes at all, so we had to implement a `nofileprefix` flag at https://github.com/mantidproject/mantid/blob/master/instrument/Facilities.xml#L594 . But this is a facility wide setting, and not instrument specific.
Btw, I noticed a typo in the documentation, in the first row of the table, when you do `INST1,2,3.ext` it does not sum, it loads them individually and puts in a group.

**Comment by NickDraper** [comment]
@AnthonyLim23 I'm closing this PR for now, but I won't delete the branch, yet ...

If you disagree then bring it back to life.

**Comment by AnthonyLim23** [comment]
I thought this was closed

**Pull request closed without merging**
