### PR TITLE
GSASIIRefineFitPeaks output fitted peaks workspace

### LINKED ISSUE #21510: GSASIIRefineFitPeaks should output a fitted peaks workspace
The information previously returned from GSASIIRefineFitPeaks was not that useful on its own. Changes recently brought into GSASIIscriptable (as of revision **3216**) allow us to extract the fitted peaks from the G2Project object. The algorithm should now be able to output a workspace with the fitted peaks.

### PR DESCRIPTION
**Pull request by josephframsay**
The fitted peaks from GSAS-II are now output as a workspace from GSASIIRefineFitPeaks. A lot of shared code was also refactored into a common helper class in the system test

**To test:**

**Make sure the GSASIIRefineFitPeaks system test passes locally - this is not currently run on the build server**

You'll need GSAS-II installed. Install it using one of the scripts in `scripts/GSAS-II` or follow the instructions [here](https://subversion.xray.aps.anl.gov/trac/pyGSAS).

Sample data is at `\\olympic\Babylon5\Public\JoeRamsay\GSASIIRefineFitPeaks`.

Run the following script (replace the marked variables with your GSAS-II installation directory and the name of a new GSAS-II project file, which will be created by the algorithm)
```
import os

# Replace this
path_to_gsas = "/path/to/directory/containing/GSASIIscriptable.py"

data_dir = r"\\olympic\Babylon5\Public\JoeRamsay\GSASIIRefineFitPeaks"

ws_path = os.path.join(data_dir, "ENGINX_280625_focused_bank_1.nxs")
spectrum = Load(Filename=ws_path, OutputWorkspace="ENGINX_280625_1")

# Replace this
gsas_proj_file = "/somewhere/local/Test.gpx"

phase_file = os.path.join(data_dir, "FE_ALPHA.cif")
iparams_file = os.path.join(data_dir, "template_ENGINX_241391_236516_North_bank.prm")

GSASIIRefineFitPeaks(PathToGSASII=path_to_gsas, 
                     InputWorkspace=spectrum,
                     SaveGSASIIProjectFile=gsas_proj_file,
                     PhaseInfoFile=phase_file,
                     InstrumentFile=iparams_file,
                     RefinementMethod="Rietveld refinement",
                     OutputWorkspace="FittedPeaks")
```

Overplot `FittedPeaks` on `ENGINX_280625_1`. The fit isn't great, but you should be able to see that some peaks line up, and a sensible workspace is output.

capture

Fixes #21510 

**Release Notes** 
[Here](https://github.com/mantidproject/mantid/commit/f0d8082fb486cadbaa3189dacda0be649ee06a8b)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by ElliotAOram** [comment]
My fit differs slightly from yours most notably with reduced intensity in all peaks. Is this okay?
image

**Comment by ElliotAOram** [comment]
Test pass but I get the same runtime warnings as I did in #21618 . This is good to merge once runtime warnings are fixed

**Comment by josephframsay** [comment]
@ElliotAOram this is fine - I think I must have attached the wrong plot, as when I run the script I get the same results as you. Also, I don't think the runtime warnings are a problem - they seem to crop up all the time in GSAS-II without actually affecting anything

**Review by ElliotAOram — APPROVED** [review]
As the RuntimeWarnings are generated from GSAS, there isn't much we can do to resolve them. Although if we can work out the cause at some stage, it might be worth telling the GSAS devs? Either way this is fine to merge 👍

**Pull request merged**
