### PR TITLE
Change to closest and furtherst monitors mumbers on LET

### PR DESCRIPTION
**Pull request by abuts**

### CODE REVIEW

**Comment by abuts** [comment]
this resolves ticket http://trac.mantidproject.org/mantid/ticket/11398

**Comment by abuts** [comment]
should be very easy to verify and I will even do it myself using right to merge trivial changes as soon as all tests passed.

**Comment by abuts** [comment]
looks like random failure

**Comment by abuts** [comment]
jenkins, retest this please

**Comment by FedeMPouzols** [comment]
All is ok, I run ISIS system test locally just in case and everything went fine.

**Pull request merged**
