### PR TITLE
Apply ROI Detector IDs to experiment settings

### LINKED ISSUE #34110: Sum detector segments in reflectometry GUI batch reduction
As part of the work to support 2D detectors, we need to be able to sum across segments in a 2D detector when performing a batch reduction in the ISIS reflectometry GUI. This will require the following changes:
- [x] Add a field to the Experiment Settings lookup table to specify the segments of interest (initially this will be a pattern specifying the detector IDs)
- [ ] The Apply button on the Preview tab should update this from the instrument viewer ROI
- [x] Pass this value through to the underlying workflow algorithm ReflectometryISISLoadAndProcess when performing the reduction (via the ROIDetectorIDs property which can be set via the functions in `RowProcessingAlgorithm.cpp`)

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR will set the ROI Detector IDs in the lookup table in the experiment settings table whenever the apply button is clicked on the preview tab.

**Questions**
- [ ] Something to check: does the full-detector range get added to the lookup table if no region is selected in the instrument view, and Apply is clicked?
- [ ] Do we want to show detector ids as a range rather than a list separated by commas?

**To test:**

- Open the ISIS Reflectometry interface and go to the Preview tab
- Load the test dataset INTER45455_inst and set angle to `1.0`
- Before setting any ranges, click the Apply button and check the Experiment Settings tab - the ROI Detector IDs field in the table should be empty
- Now select a range on the instrument view on the Preview tab and repeat - the ROI Detector IDs should be set to the detectors selected 

Fixes #34110 

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gemmaguest** [comment]
@robertapplin Sorry it took me a while to get round to looking at this! Is it ready for review now, do you remember?

**Comment by robertapplin** [comment]
> @robertapplin Sorry it took me a while to get round to looking at this! Is it ready for review now, do you remember?

I think it is ready for a review! Although it looks like I had some questions in the PR description, but maybe these are something to consider for a future PR(?)

**Comment by gemmaguest** [comment]
@robertapplin Could you rebase onto main? It doesn't seem to be picking up that the dependency is now merged, and also something weird has gone on with the windows build... Hopefully a rebase will resolve it!

**Comment by gemmaguest** [comment]
>     * [ ]  Something to check: does the full-detector range get added to the lookup table if no region is selected in the instrument view, and Apply is clicked?

I just checked and it's empty if there is no selection. I think this is fine; the underlying algorithm should use a sensible default if the ROI is not provided. Also I think in a future improvement we will set a default range on the Preview tab anyway, so it will then always have a value anyway.

>     * [ ]  Do we want to show detector ids as a range rather than a list separated by commas?

Yes, I think this would be a good improvement, but can be done in a future PR. I've added a note to this issue to do it: #34220

**Review by gemmaguest — DISMISSED** [review]
Code looks good and works as expected. Some nice improvements to the way processing instructions are passed to make it consistent with the other types of ROI :+1: This is part of a prototype tab which is not exposed yet so release notes aren't required at this point. Happy to merge when tests pass :shipit:

**Review by gemmaguest — DISMISSED** [review]

**Comment by martyngigg** [comment]
I was just looking at the Windows build here and for some reason it's skipping building the unit tests and just jumping straight to trying to run them. I'm not sure why though.

**Comment by martyngigg** [comment]
So it looks like the build fell over but for some reason it didn't cause the job to exit. The build error is buried in the console log:

```
C:\Jenkins\workspace\pull_requests-conda-windows\qt\scientific_interfaces\ISISReflectometry\GUI\Preview\PreviewPresenter.cpp(171,36): error C2039: 'Strings': is not a member of 'Mantid::Kernel' [C:\Jenkins\workspace\pull_requests-conda-windows\build\qt\scientific_interfaces\ISISReflectometry\MantidScientificInterfacesISISReflectometryQt5.vcxproj]
C:\Jenkins\workspace\pull_requests-conda-windows\Framework\Kernel\inc\MantidKernel/make_cow.h(18): message : see declaration of 'Mantid::Kernel' [C:\Jenkins\workspace\pull_requests-conda-windows\build\qt\scientific_interfaces\ISISReflectometry\MantidScientificInterfacesISISReflectometryQt5.vcxproj]
C:\Jenkins\workspace\pull_requests-conda-windows\qt\scientific_interfaces\ISISReflectometry\GUI\Preview\PreviewPresenter.cpp(171,36): error C3083: 'Strings': the symbol to the left of a '::' must be a type [C:\Jenkins\workspace\pull_requests-conda-windows\build\qt\scientific_interfaces\ISISReflectometry\MantidScientificInterfacesISISReflectometryQt5.vcxproj]
C:\Jenkins\workspace\pull_requests-conda-windows\qt\scientific_interfaces\ISISReflectometry\GUI\Preview\PreviewPresenter.cpp(171,45): error C2039: 'simpleJoin': is not a member of 'Mantid::Kernel' [C:\Jenkins\workspace\pull_requests-conda-windows\build\qt\scientific_interfaces\ISISReflectometry\MantidScientificInterfacesISISReflectometryQt5.vcxproj]
C:\Jenkins\workspace\pull_requests-conda-windows\Framework\Kernel\inc\MantidKernel/make_cow.h(18): message : see declaration of 'Mantid::Kernel' [C:\Jenkins\workspace\pull_requests-conda-windows\build\qt\scientific_interfaces\ISISReflectometry\MantidScientificInterfacesISISReflectometryQt5.vcxproj]
C:\Jenkins\workspace\pull_requests-conda-windows\qt\scientific_interfaces\ISISReflectometry\GUI\Preview\PreviewPresenter.cpp(171,55): error C3861: 'simpleJoin': identifier not found [C:\Jenkins\workspace\pull_requests-conda-windows\build\qt\scientific_interfaces\ISISReflectometry\MantidScientificInterfacesISISReflectometryQt5.vcxproj]
```

I'll look at why the build didn't just stop the job.

**Comment by gemmaguest** [comment]
@robertapplin I added a fix for this build failure, hope that's ok

https://builds.mantidproject.org/job/pull_requests-conda-osx/417/clang/source.dc4ae16b-7b6a-4fef-870e-afb136670afc/#111

**Comment by martyngigg** [comment]
Had the build passed before I would have merged this so I'll go ahead and merge it now as nothing significant is different from the approving review.

**Pull request merged**
