### PR TITLE
Indirect Unscripted testing changes

### LINKED ISSUE #24983: Indirect unscripted testing bugs
Let me know if some of these are not worth fixing. 

The reduction tab jumps back to the top of the GUI when run is pressed. - annoying but not breaking anything.

For the second test at step 10 I end up with 51 spectra not 50

In the last part of the second test the contour plot seems to be empty (all zeros)

For the I(Q,T) I got the error

float division by zero
  at line 81 in 'C:/Users/BTR75544/nightly/MantidNightlyInstall/plugins/python/algorithms\WorkflowAlgorithms\TransformToIqt.py'
  caused by line 162 in 'C:/Users/BTR75544/nightly/MantidNightlyInstall/plugins/python/algorithms\WorkflowAlgorithms\TransformToIqt.py'```
using  26184 to 5 with both  sample and resolution selected
image

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR updates some of the acceptance testing steps. It also adds a check for analysers and reflections for the Iqt interface before performing TransformToIqt.

**To test:**
1.`Interfaces`->`Indirect`->`Data Analysis`->`Iqt` interface
2. Load the data below and click `Run`. An error message stating the reflections are different should appear.

Check the changes to the acceptance tests.

*No release notes required as the bug is relatively minor and was probably unnoticed*

Fixes #24983

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
flake8 failed

**Comment by AnthonyLim23** [comment]
code looks fine

**Comment by robertapplin** [comment]
@AnthonyLim23 This has now passed the checks

**Comment by AnthonyLim23** [comment]
I dont think I will get time to review this for a few days. So I am going to unassign myself in the interest of getting it in quickly.

**Review by martyngigg — APPROVED** [review]
We now get an appropriate error message if there is an analyser mismatch.

**Pull request merged**
