### PR TITLE
Fit Script Generator - Implement Edit Local Parameter dialog

### LINKED ISSUE #30684: Fit Script Generator - Implement EditLocalParameterDialog
### Description
It should be possible to use the EditLocalParameterDialog from the Fit Script Generator interface. Both in sequential and simultaneous mode.

This is opened by the `...` button when you click a parameter in the FunctionTreeView.

### Platforms affected
All

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR implements the Edit Local Parameter dialog for the Fit Script Generator interface. It is now possible to select a local parameter using the `...` button in the function tree and edit the values/ties/fixes/constraints for this parameter across all the domains that it exists in.

**To test:**
1. Comment out this line
https://github.com/mantidproject/mantid/blob/44daa7417226a56f8d1896ea6b2f2b1bc576a5d1/scripts/Muon/GUI/Common/fitting_tab_widget/fitting_tab_view.py#L52
2. Go to Muon Analysis interface
3. click `Load Current Run`
4. Go to Fitting tab and click `Fit Generator`
5. Click `Add Workspaces`. Select the first workspace and click add.
6. Right click the function browser and add a `FlatBackground` and then `ExpDecay`
7. Select a parameter and click the `...`. The Edit Local Parameter dialog should open.
8. Try out fixing, tying and constraining the parameter. Click `Ok` each time and check the changes have been applied within the function tree. 
9. Opening the dialog should also load in the current fixes/ties/constraints seen in the function tree.

Fixes #30684 

*This does not require release notes* because **the Fit Script Generator is inaccessible to users at the moment.**

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by robertapplin** [comment]
I squashed some of the commit history in this PR to make the rebase easier.

**Comment by Harrietbrown** [comment]
when setting parameters it does not set it to the correct workspace. If you set a tie on the last worksapce opn the list it will instead set it to the first one in the script generator.

**Comment by robertapplin** [comment]
Thanks for spotting that, I'm surprised I didn't notice that earlier. It should be fixed now

**Comment by Harrietbrown** [comment]
If you go to set a constraint you can enter anyting into the text box and will not give any indication of if it is valid or not. same with ties. it will just not be entered when you click OK

**Comment by robertapplin** [comment]
> If you go to set a constraint you can enter anyting into the text box and will not give any indication of if it is valid or not. same with ties. it will just not be entered when you click OK

This should be ok as the `EditLocalParameterDialog` class handles this the same in indirect and the other places where this dialog is used. If an invalid tie or constraint is set in the dialog then it will not be used. Changing the way this works is probably outside the scope of this PR

**Review by Harrietbrown — APPROVED** [review]
You're right that the lack o warning about an invalid value may be outside of the scope of the PR. the code looks good and the ties/constraints are added as described. Good job

**Pull request merged**
