### PR TITLE
Consolidate ALFView tests

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work**
This PR makes a few changes to the unit tests for ALFView. These changes ensure the tests (in particular the presenter tests) are easier to read, and that the tests run slightly faster.

**To test:**
Code review and make sure tests pass

*There is no associated issue.*

*This does not require release notes* because **it is an internal change to the tests**

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by RichardWaiteSTFC — COMMENTED** [review]
Looks good, much clearer and caching the empty instrument and some of the test data (e.g. non-ISIS data workspace) is a good idea!

However I do get an exceptioin when running `ALFInstrumentModelTest.h` locally
The call stack
```	MantidKernel.dll!Mantid::Kernel::PropertyManager::setPropertyValue(const std::string & name, const std::string & value) Line 452	C++
 	MantidKernel.dll!Mantid::Kernel::PropertyManagerOwner::setPropertyValue(const std::string & name, const std::string & value) Line 105	C++
 	MantidAPI.dll!Mantid::API::Algorithm::setPropertyValue(const std::string & name, const std::string & value) Line 1842	C++
 	MantidDataHandling.dll!Mantid::DataHandling::Load::setPropertyValue(const std::string & name, const std::string & value) Line 110	C++
 	MantidKernel.dll!Mantid::Kernel::IPropertyManager::setProperty(const std::string & name, const std::string & value) Line 310	C++
 	MantidQtInterfacesDirectTestQt5.exe!`anonymous namespace'::loadFile(const std::string & filename) Line 58	C++
 	MantidQtInterfacesDirectTestQt5.exe!ALFInstrumentModelTest::ALFInstrumentModelTest() Line 77	C++
 	MantidQtInterfacesDirectTestQt5.exe!ALFInstrumentModelTest::createSuite() Line 80	C++
```
The console output
```
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: Mantid::Kernel::Exception::NotFoundError at memory location 0x00000088B031ED60.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: Mantid::Kernel::Exception::NotFoundError at memory location 0x00000088B031ED60.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: Mantid::Kernel::Exception::NotFoundError at memory location 0x00000088B031BBF0.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: Mantid::Kernel::Exception::NotFoundError at memory location 0x00000088B031BBF0.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: std::runtime_error at memory location 0x00000088B031B0A0.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: `anonymous namespace'::DummyException at memory location 0x00000088B031A020.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: `anonymous namespace'::DummyException at memory location 0x00000088B031A020.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: `anonymous namespace'::DummyException at memory location 0x00000088B031A020.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: `anonymous namespace'::DummyException at memory location 0x00000088B031A020.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: `anonymous namespace'::DummyException at memory location 0x00000088B031A020.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: `anonymous namespace'::DummyException at memory location 0x00000088B031A020.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: Mantid::Kernel::Exception::NotFoundError at memory location 0x00000088B0319850.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: Mantid::Kernel::Exception::NotFoundError at memory location 0x00000088B0319850.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: std::runtime_error at memory location 0x00000088B0318CE0.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: Mantid::Kernel::Exception::NotFoundError at memory location 0x00000088B031EA20.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: Mantid::Kernel::Exception::NotFoundError at memory location 0x00000088B031EA20.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: Mantid::Kernel::Exception::ExistsError at memory location 0x00000088B031EC70.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: Mantid::Kernel::Exception::NotFoundError at memory location 0x00000088B031EAA0.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: Mantid::Kernel::Exception::NotFoundError at memory location 0x00000088B031EAA0.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: Mantid::Kernel::Exception::NotFoundError at memory location 0x00000088B031DA70.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: Mantid::Kernel::Exception::NotFoundError at memory location 0x00000088B031DA70.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: Mantid::Kernel::Exception::NotFoundError at memory location 0x00000088B031D700.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: Mantid::Kernel::Exception::NotFoundError at memory location 0x00000088B031D700.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: Mantid::Kernel::Exception::NotFoundError at memory location 0x00000088B031D790.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: Mantid::Kernel::Exception::NotFoundError at memory location 0x00000088B031D790.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: Mantid::Kernel::Exception::NotFoundError at memory location 0x00000088B031A5F0.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: Mantid::Kernel::Exception::NotFoundError at memory location 0x00000088B031A5F0.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: `anonymous namespace'::DummyException at memory location 0x00000088B0318A20.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: `anonymous namespace'::DummyException at memory location 0x00000088B0318A20.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: Mantid::Kernel::Exception::NotFoundError at memory location 0x00000088B0318250.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: Mantid::Kernel::Exception::NotFoundError at memory location 0x00000088B0318250.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: boost::wrapexcept<boost::bad_lexical_cast> at memory location 0x00000088B0316DF0.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: Mantid::Kernel::Exception::NotFoundError at memory location 0x00000088B031B8E0.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: Mantid::Kernel::Exception::NotFoundError at memory location 0x00000088B031B8E0.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: boost::wrapexcept<boost::bad_lexical_cast> at memory location 0x00000088B031B850.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: std::runtime_error at memory location 0x00000088B031DBA8.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: std::invalid_argument at memory location 0x00000088B031CFD8.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: std::invalid_argument at memory location 0x00000088B031D710.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: std::runtime_error at memory location 0x00000088B031EA50.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: std::invalid_argument at memory location 0x00000088B031AA98.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: std::invalid_argument at memory location 0x00000088B031B1D0.
Exception thrown at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: std::invalid_argument at memory location 0x00000088B031EE30.
Unhandled exception at 0x00007FFA4AB6CF19 in MantidQtInterfacesDirectTestQt5.exe: Microsoft C++ exception: std::invalid_argument at memory location 0x00000088B031EE30.
```

**Comment by robertapplin** [comment]
> However I do get an exceptioin when running `ALFInstrumentModelTest.h` locally The call stack
That is strange, might it be because it is looking for the new test data but it can't find it? If so you might need to build the `StandardTestData` target

**Comment by RichardWaiteSTFC** [comment]
> > However I do get an exceptioin when running `ALFInstrumentModelTest.h` locally The call stack
> 
> That is strange, might it be because it is looking for the new test data but it can't find it? If so you might need to build the `StandardTestData` target

Hmm I built `StandardTestData` and I still get the exception...can you reproduce this? I've checked and the test is in the cmake file so presumably it was run on jenkins.

**Comment by robertapplin** [comment]
> > > However I do get an exceptioin when running `ALFInstrumentModelTest.h` locally The call stack
> > 
> > 
> > That is strange, might it be because it is looking for the new test data but it can't find it? If so you might need to build the `StandardTestData` target
> 
> Hmm I built `StandardTestData` and I still get the exception...can you reproduce this? I've checked and the test is in the cmake file so presumably it was run on jenkins.

Strange, I can't reproduce this. From your call stack it looks like its giving an `invalid_argument` exception when setting the `Filename` property for the `Load` algorithm. Does the `ALF82301_preprocessed.nxs` file exist in this location?
```
<build_folder>/ExternalData/Testing/Data/UnitTest
```
```

**Review by RichardWaiteSTFC — APPROVED** [review]
I don't have the file you added in this PR, so I think the issue is with my setup - so I'm approving!

**Pull request merged**
