### PR TITLE
Beam Centre Finder Additional Features

### LINKED ISSUE #21338: Additional features for the SANS V2 BeamCentreFinder
The following features were requested as additions

- Continuous plotting of results.

- A verbose mode to keep output workspaces from all iterations.

- An option to set Q limits for just the beam centre finder without switching tab.

### PR DESCRIPTION
**Pull request by Matthew-Andrew**
Description of work.
The following features were requested as additions

- Continuous plotting of results.

- A verbose mode to keep output workspaces from all iterations.

- An option to set Q limits for just the beam centre finder without switching tab.

**To test:**

- Get the loqdemo dataset from http://download.mantidproject.org/ . There is a sample ISIS data set on the bottom right. 
- Add the loqdemo folder to the directories path in mantid.

- Open the SANS GUI V2, Interfaces-> SANS

- Click on load user file navigate to loqdemo folder and load maskfile.txt

- Click on load batch file, load batch_mode_reduction

- Switch to the beamCentre tab, change the Max iterations to 3, click the verbose box and click run.

- Verify that output graphs are produced. 

- Verify that a workspace group called iteration_# is produced for each iteration containing the output.

- Click on the Initial COM box and verify that the first iteration line output in the log is _Itr 0: (321.735208613, 327.871486798)  SX=15505.9794889  SY=772.794267593_

Fixes #21338. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
So I do get a graph and the iteration workspace groups.

The graph might update with the iterations, but the differences are so subtle they are not visible, so it is possible that the graph is not updating.

image

The graph looks like this, which is almost ok.

ACTION: The graph title "Bottom" needs changing as that refers to just one of the workspaces plotted on it.

**Comment by NickDraper** [comment]
Initial COM (Not at all clear what this means by the way!)

The line I get is different from the test example:
```
Itr 0: (322.747708908, 327.872958999)  SX=7209.78821823  SY=1242.05905925
```

I'm not sure if this is a problem or not

**Comment by NickDraper** [comment]
image
Also on design:

The Verbose and Initial COM checkboxes are placed so they look like they are related to the Left/Right and Up/Down Find Beam Centre Options.  However, I suspect that they are unrelated general options that have just been popped on the bottom.  This is confusing and they need their own label, even if it is just Options:

**Review by NickDraper — CHANGES_REQUESTED** [review]
See my earlier comments

**Comment by Mantid-Matthew** [comment]
Have made the following changes:

- Restructured the interface slightly and added tooltips.

- Changed the graph title

- I've double the checked the graph and I think it does update

- The initial COM numbers will in fact be slightly different every time so ignore the last test.

**Comment by Mantid-Matthew** [comment]
@NickDraper if you could have another look at this that would be great so I can tell the ZOOM guys it is ready for them to use on nightly.

**Comment by NickDraper** [comment]
Bad failure state if files are not found.

The process button is left in a "Processing ..." greyed out state

log entry
```
RuntimeError: Trying to find the SANS file 74024, but cannot find it. Make sure that the relevant paths are added and the correct instrument is selected.
Traceback (most recent call last):
  File "C:/Mantid/Code/scripts/Interface\ui\sans_isis\work_handler.py", line 32, in on_finished
    result = self._worker.result
AttributeError: 'NoneType' object has no attribute 'result'
```

**Comment by NickDraper** [comment]
After adding the directory to the data directories, I get a log fill of this when clicking process

```
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
Type is <type 'str'>
```

**Review by NickDraper — APPROVED** [review]

**Comment by NickDraper** [comment]
All is good now

**Pull request merged**
