### PR TITLE
Remove RHEL6 from build scripts

### PR DESCRIPTION
**Pull request by rosswhitfield**
Just a clean up of the buildscript. We dropped support for RHEL6 in [v3.9.0](http://docs.mantidproject.org/nightly/release/v3.9.0/index.html)

**To test:**
* Code review
* If the builds pass that means I didn't break the build script 😉 

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
@LamarMoore Does this affect the builds you are doing on the SCARF cluster?

**Review by peterfpeterson — APPROVED** [review]
The changes all look reasonable. Thanks for cleaning out unused code.

**Comment by peterfpeterson** [comment]
You should merge `master` into this branch so it can get merged.

**Comment by martyngigg** [comment]
@SimonHeybrock These are scripts that are purely for the build servers and we haven't had a RHEL 6 machine in quite some time. Lamar has a set of custom scripts to build on SCARF.

**Pull request merged**
