### PR TITLE
Pull over remaining system tests classes and data content links

### PR DESCRIPTION
**Pull request by martyngigg**
Fixes issue [#11176](http://trac.mantidproject.org/mantid/ticket/11176)

**Tester**

Check that all of the analysis tests that were in the [systemtests](https://github.com/mantidproject/systemtests) repository are now included in this repository, along with external links to the required data files.

### CODE REVIEW

**Comment by martyngigg** [comment]
This is now being held up by [#11211](http://trac.mantidproject.org/mantid/ticket/11176)

**Comment by martyngigg** [comment]
@peterfpeterson @stuartcampbell @rosswhitfield @Anders-Markvardsen @OwenArnold - Any comments would be gratefully received.

I'd like to get this merged as soon as we can.

**Comment by abuts** [comment]
Jenkins retest this please

**Comment by peterfpeterson** [comment]
The last fail is the same two tests that are broken on master. Otherwise I think this is good. The long builds are for the first download of system data. :+1:

**Comment by martyngigg** [comment]
The fixes for the two tests that were broken have now been merged so this should be good to go.

**Pull request merged**
