### PR TITLE
Add tooltips to Lookup Table Errors

### LINKED ISSUE #33587: Display error tooltips on the lookup table and remove the popup warning
On the lookup table on the ISIS Reflectometry GUI, invalid inputs are highlighted in red. Some of these are obvious but others are not; in particular when you have duplicate search criteria, the angle and title-matcher are highlighted in red. Sometimes there is a popup message when the angle is duplicated but this is misleading because it only refers to the angle and does not always pop up. It would be better to set an error message on the cells that contain invalid values. 

I think we should only do this for the search criteria because the other cells have a tooltip explaining what the settings is for which is probably more useful than an error message.

~We should address issue #33586 first~

### PR DESCRIPTION
**Pull request by cailafinn**
**Description of work.**
Added help message tooltips to the table when errors are detected. Rather than the description of what the column is for, when there is a lookup criteria error the tooltip is changed to indicate what the problem is and how to fix it. 

**To test:**
1. Open the Refl GUI
2. Click the Experiment Settings tab
3. On the table, check that the tooltips on the cells in the Angle and Title columns contain a description of what those cells are for.
4. Add an additional row, those columns should now be highlighted red
5. Check the tooltips now contain an "multiple wildcards" error message and details. 
6. Change one of the angles
7. Check the tooltip has been reverted
8. Change the other to the same angle as in step 6
9. Check the tooltip has a "duplicate search criteria" error.
10. Change one of the titles
11. Check the tooltip is reverted

Fixes #33587 

*This does not require release notes* because **it is part of the larger piece of work to add title lookup to the GUI**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by RichardWaiteSTFC — COMMENTED** [review]
Step 3 suggests the tool tip for the title column should be different from the Angle column. I see the same tool tip (for angle) for all columns
image

**Comment by ConorMFinn** [comment]
> Step 3 suggests the tool tip for the title column should be different from the Angle column. I see the same tool tip (for angle) for all columns

So the titles of the columns give the tooltip for the entire table, the individual cells have the specific tooltips for each column (this is existing behaviour previously agreed with the scientists, I admit it's a little weird)

**Review by RichardWaiteSTFC — APPROVED** [review]
Looks good, behaves as expected and is much clearer to the user. Nice addition to the tests and even got rid of a cpp check error!

**Review by DavidFair — APPROVED** [review]
Nice separation of concerns moving logic out of the view :+1:

**Pull request merged**
