### PR TITLE
ISISDirectInelastic failing system tests for Python 3

### LINKED ISSUE #20440: SystemTests.ISISDirectInelastic MAPS/MARI failing for python 3
There are 3 remaining failing systemtests for python 3, see [here](http://builds.mantidproject.org/job/master_systemtests-ubuntu-16.04-python3/203/testReport/)
```
SystemTests.ISISDirectInelastic.MAPSDgreduceReduction
SystemTests.ISISDirectInelastic.MARIReductionAutoEi
SystemTests.ISISDirectInelastic.MARIReductionMonSeparate
```
They all fail with `Workspace ??? not equal to its reference file`

### PR DESCRIPTION
**Pull request by ElliotAOram**
The way the `Ei` value is formatted in the SampleLogs has been changed from using the `str()` function (which has a differing precision between python2.7 and python3.x) to the `format()` function which  explicitly quotes the precision.

The reference file were also found to not contain the correct precision for `Ei` so they have also been updated (See #20440 for more details on ref file update). @abuts would you be able to take a look at the change to the reference files and check that you are happy with this?

**To test:**

Ensure the system tests for:
* `ISISDirectInelastic.MARIReductionAutoEi`
* `ISISDirectInelastic.MARIReductionMonSeparate`
* `ISISDirectInelastic.MAPSDgreduceReduction`

pass on all platforms (**including Python 3**)

Note: If you are testing this locally, the reference files have been updated so you may need to run CMake again.

Fixes #20440 

**Release Notes** 
Internal change to system tests hence not required in the release notes.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by rosswhitfield — APPROVED** [review]
Good work tracking these down. These system tests now pass with python 3. :+1:

**Comment by martyngigg** [comment]
@abuts It would be nice if we could push this through. Are you okay with these changes?

**Comment by martyngigg** [comment]
Alex confirmed to me that this is okay.

**Comment by abuts** [comment]
@martyngigg Looks completely fine to me

**Pull request merged**
