### PR TITLE
Indirect Correction Container Subtraction -  container plotting and shift

### LINKED ISSUE #16251: Indirect Correction Container Subtraction - Container plotting and shift
**Bug found in unscripted testing using mantid build from 16/05/2016**
### Expected behavior
* The Container should be plotted in the mini plot when it is loaded and you should be able to switch spectra in the miniplot. The interface and algorithm should also not leave behind any unwanted workspaces in the ADS 

### Actual behavior
* The contianer is not plotted when it is loaded in and switching spectra in the mini plot before the algorithm is run causes an unexpected exception. `__container_corrected` workspace is left in the ADS.

### Steps to reproduce the behavior
* Load in a container a see it is not plotted
* Switch spectra in the mini plot and see that an exception is thrown
* Run the algorithm and see that the `__container_corrected` workspace is still present

### Platforms affected
Found on Windows 7. Likely to affect all OS

### PR DESCRIPTION
**Pull request by ElliotAOram**
The Container Subtraction interface should now perform as expected when plotting the container workspace as well as updating automatically for shift and scale. The interface should no longer crash when changing spectra.

**To test:**

**All data is available from `\\olympic\babylon5\Public\ElliotOram\Corrections\CalculatePaalmanPings\IRIS\correction_set`**
- Open ContainerSubtraction (Interface > Indirect > Corrections > ContainerSubtraction )
- Load in the Sample: `IRS26176_graphite002_red.nxs`
- Load in the Container: `IRS26174_graphite002_red.nxs`
- Ensure the sample and container are now loaded into the miniplot.
- Check the Use scale and the use shift option and change their values slightly.
- Ensure the mini plot updates the container to match the changes you make
- Ensure you can still change the Spectrum in the miniplot using the spinner in the bottom left of the interface.
- Run the interface.
- Ensure it runs without error and the 3 curves (black, red and green) are all in the mini plot
- Try various combinations of running, changing values and switching spectrum preview to ensure nothing crashes and the interface functions as expected.
- Ensure that you can only shift the container to a maximum of the x Range of the sample (e.g. the container peak is at the far edge of the sample (`-0.54761`, `0.54325`)

Fixes #16251

[RELEASE NOTES](https://github.com/mantidproject/mantid/blob/fc409a7c85f86c2dd165ab89f96146be02e1457b/docs/source/release/v3.7.0/indirect_inelastic.rst#bugfixes)

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by ElliotAOram** [comment]
@raquelalvarezbanos there might be a small bug in this where the workspace is being scaled twice by mistake. I'll double check to see if this is an issue and resolve it if it is!

**Comment by raquelalvarezbanos** [comment]
OK, just let me know when it is ready.

In the meantime, just to make sure I am testing the right thing: the "Container Subtraction" tab does not seem to have a checkbox "Use container", this option is always enabled, is this correct? In the testing instructions you say: 

> Check Use Container and Load IRS26174_graphite002_red.nxs

**Comment by ElliotAOram** [comment]
Yes, you're right it doesn't have a `use container` option, my mistake! Sorry for the confusion. I've updated the PR description to amend this.

**Comment by raquelalvarezbanos** [comment]
Thanks Elliot! Please let me know when it is ready to test

**Comment by ElliotAOram** [comment]
@raquelalvarezbanos this should be ready to test now providing it passes on the build servers!

**Comment by raquelalvarezbanos** [comment]
Followed testing instructions. Everything works as expected and Mantid does not crash when changing spectra (I tried running the interface with different values of scale factor, shift x, and different spectrum numbers).

:shipit:

**Pull request merged**
