### PR TITLE
Apply clang-tidy modernize-use-override to testing headers

### PR DESCRIPTION
**Pull request by quantumsteve**
Description of work.

This uses clang-tidy's modernize-use-override tool to add the C++11 override keyword where appropriate. This should eliminate many of the warnings emitted by GCC 5's -Wsuggest-override flag.

Unlike PR #15308, this applies changes to the testing headers.

**To test:**

This is a relatively simple keyword change done with automated tooling. Rather than reviewing every change I suggest reviewing enough files to convince yourself clang-tidy is doing the right things. A misspelled or duplicated keyword should not build.

This PR does not have an associated issue.

Does not need to be in the release notes.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by quantumsteve** [comment]
@peterfpeterson @AndreiSavici @rosswhitfield

**Comment by quantumsteve** [comment]
The last few commits modify the code generated by cxxtest, hide warnings from third party libraries, and update a macro that is generating a lot of warnings.

I commented out `-Wsuggest-final-types` and -Wsuggest-final-methods` since the two specifiers are independent of each other and I'm not convinced we want to push these two warnings down to zero.

**Comment by quantumsteve** [comment]
I suppressed `-Wsuggest-override` warnings in ICat3Stub.h. That file alone generates 2422 warnings and clang-tidy segfaults when trying to fix them. I don't think we should try fixing those by hand.

**Comment by peterfpeterson** [comment]
Significantly better on warnings. :shipit: once the builds finish passing.

**Pull request merged**
