### PR TITLE
Implement error bars in MPL based PreviewPlot

### LINKED ISSUE #28182: PreviewPlot does not have errors in workbench
Set the default instrument to MUSR
Open ALC
Set first run to be 62260
Set the last run to be 62270
Set the log to Field_Danfysik
Click load
On MantidPlot you will see nice error bars, on workbench they will be missing. 

It should be possible to enable them from the plot context menu

This is also true for indirect data analysis

### PR DESCRIPTION
**Pull request by StephenSmith25**
**Description of work.**
This PR implements error bars for the MPL preview plot. This includes adding the ability to specify line names which will always have errors and allowing the error bars to be switched on/off through the context menu.

**Note**: The error bars are currently only implemented for the ALC interface. Although the Indirect interface uses the preview plot, the context menu was disabled in a previous PR. Therefore, before adding errors to this interface we would need to address the issues surrounding the plot context menu in the IDA GUI.

**To test:**

1. Open ALC
2. Set first run to be 62260
3. Set the last run to be 62265
4. Set the log to Field_Danfysik
5. Click load
6. Error bars will be shown be default (as in Mantid plot)
7. They can be switched on/off using the right click menu on the plot

Fixes #28182 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
What instrument do I need to be set to?

**Comment by StephenSmith25** [comment]
> What instrument do I need to be set to?

I think was using MUSR

**Review by NickDraper — COMMENTED** [review]
This is good and works.
One question, should we disable the legend by default?
It really does not add much and can obscure the data
image

Let me know if you disagree and I'd be happy to approve the changes

**Review by NickDraper — COMMENTED** [review]
removed duplicate

**Comment by StephenSmith25** [comment]
I agree, having the legend on the data view is not useful and it was hidden by default on MantidPlot. The latest commit hides it by default. I also noticed that if you changed the legend before any data was plotted it would hard crash Workbench. I think that should also be fixed now.

**Review by NickDraper — APPROVED** [review]
Great work, good to go.

**Pull request merged**
