### PR TITLE
Replace the splash screen with a celebration one

### LINKED ISSUE #19896: 10 year celebration splash screen
replace the splash screen for 3.11 & add ILL

### PR DESCRIPTION
**Pull request by NickDraper**
Replaced the splash screen with a celebration one.
Also add the layered image file (Paint dot net) to allow easier editing in the future

Issue #19897 has been created to remove the balloons for the subsequent release

closes #19896

**To test:**

1. Startup Mantidplot, look at the splash screen
1. See Balloons, feel happy
1. Check that the version label at the bottom of the splash screen does not run over the image.

**Release Notes** 

 docs/source/release/index.rst

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
Gagik, Thanks for jumping in to take this one, I'm just about to add some release notes in a few minutes

**Comment by NickDraper** [comment]
Ready for testing now

**Review by gvardany — COMMENTED** [review]
Very nice image! But just to be precise, the ILL logo has been updated recently, it says now Neutrons for Society. Also would that be easy to align the logos such that the spacing in between is equal? Otherwise it is fine.

ill_logo

**Review by gvardany — APPROVED** [review]
Thanks for the update. Spacing is a lot better now.

**Pull request merged**
