### PR TITLE
General sample transmission UI

### PR DESCRIPTION
**Pull request by DanNixon**
Ticket [#11072](http://trac.mantidproject.org/mantid/ticket/11072).

To test open the General > Sample Transmission Calculator interface, review its documentation, try it with a range of wavelength ranges and samples.

### CODE REVIEW

**Comment by DanNixon** [comment]
Jenkins, retest this please.

**Comment by NickDraper** [comment]
Dan, this pull request can't be merged, could you merge master into the branch please

**Comment by FedeMPouzols** [comment]
It seems that there're conflicts again.

**Comment by FedeMPouzols** [comment]
All looks good to me. Very usable interface. Maybe you could add the x and y axes' titles, although that is well documented and on the dialog it would take space, and probably people using this don't need to be reminded what the plot shows.

**Pull request merged**
