### PR TITLE
Fix edge cases with user filename

### LINKED ISSUE #28458: Also output Batch File name in CanSAS1D and NXcanSAS
Currently SaveCanSAS1D and SaveNXCanSAS write the User File name to the SASprocess field in the metadata.

If the data being output was generated by processing a Batch File we should also write the Batch File name for enhanced traceability.

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**

Fixes the following cases where the user filename and batch filename were not output:
- Custom user file in the table
- Merged reductions

Additionally fixes constantly switching the instrument on table row change. This was because the file information equality operator was not implemented, causing us to reload file info every time

**Report to:** @smk78 

**To test:**
- Download the ISIS Sample Data -> LOQ demo
- Open the SANS GUI
- Load in Maskfile.txt to user file
- Load in the .csv from the LOQ Demo folder
- In the bottom right set the Save type to `Both`
- Ensure CanSAS1D and NXCanSAS is ticked
- Go to your output dir and remove any files with `first_time` or `second_time`

----
- For either row under the userfile column enter `MaskFile.txt`
- Select and process that row
- Go to output dir, open XML and look for `user_file` and `batch_file` they should be populated
- Clear the ADS and drag the .h5 file into Mantid
- Go to sample properties and check that both are there
-----
- Remove output files as per above
- Go to settings, at the top change to `Merged`
- Go back and process all (the row with and without the user file)
- Go to output dir and check box XML files have the above tags
- Check .h5 as above

Fixes #28458 . 

*This does not require release notes* because it is part of a new feature released for this version

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by smk78** [comment]
This should also check that user_file and batch_file are populated in NXcanSAS output when selected.

**Comment by DavidFair** [comment]
411c6857438 has introduced a regression which means we can't run unit tests....

**Review by gemmaguest — DISMISSED** [review]
Functions as described and code looks good :+1:

**Comment by gvardany** [comment]
Can we have a test for these?

**Comment by DavidFair** [comment]
> Can we have a test for these?

Yes sorry, I got so pre-occupied fixing the regression I forgot to add tests.

For files such as the `mm to m` step we have existing coverage which passed correctly. The code had to be duplicated to fix a circular import as SANSUtility does `from mantid.simpleapi import *`

**Review by gemmaguest — APPROVED** [review]

**Pull request merged**
