### PR TITLE
Update hard-coded PV names in RROLD

### LINKED ISSUE #29694: Update hard-coded block names in RROLD
`ReflectometryReductionOneLiveData` fetches live values from instruments. The block names for these values are hard-coded and it looks like some have recently changed, e.g. for Polref (I think due to the move to IBex). Ideally these would not be hard coded but for a "safe" fix for now just update the hard-coded values. This stops the live data reduction from working so this is a priority fix.

### PR DESCRIPTION
**Pull request by gemmaguest**
**Report to:** Max at ISIS

ReflectometryReductionOneLiveData fetches live values from the instrument. The PV names for the values are currently hard-coded. This PR updates them following a recent change on the instrument. It also supports two versions of the name because instruments are currently switching between IBEX and SECI and the name is changing. Longer term it would be good to avoid hard-coded values altogether but just updating them for now is a safer, smaller fix for the patch.

Fixes #29694 

**To test:**

Must be tested at ISIS

- Open the ISIS Reflectometry interface
- For each instrument, click the `Start Monitor` button. This will attempt to fetch Theta and the slit gaps from the instrument.
- The result will depend on the current state of the instrument.
  - OFFSPEC, POLREF and SURF should successfully fetch the values - check the log and they should be printed. However, the reduction may still fail: if Theta is zero, this is a valid failure because we can't reduce; it looks like the SURF reduction fails due to a monitor not existing. This is beyond scope of this PR.
  - INTER and CRISP are currently failing to fetch values due to a process not running on the instrument. You will get a timeout error in the log. Check that both PV names have been tried and both timed out (i.e. `THETA` and `Theta`)

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by robertapplin** [comment]
I am not getting the expected messages in the log. Instead I get this message for each instrument: 
image

**Comment by gemmaguest** [comment]
> 
> 
> I am not getting the expected messages in the log. Instead I get this message for each instrument:
> image
> Am I missing something?

I'm not sure but it looks like a problem with live data in general rather than the reflectometry side. Are you on the VPN?

**Comment by robertapplin** [comment]
> > I am not getting the expected messages in the log. Instead I get this message for each instrument:
> > image
> > Am I missing something?
> 
> I'm not sure but it looks like a problem with live data in general rather than the reflectometry side. Are you on the VPN?

You are right, my VPN disconnected when I went for lunch 😕

**Comment by robertapplin** [comment]
Just want to check if the merge target is correct? I am not too familiar with how patches work

**Comment by gemmaguest** [comment]
> 
> 
> Just want to check if the merge target is correct? I am not too familiar with how patches work and where they go (ie where they get merged to)

Yes, it's a patch so should go to release-next

**Review by robertapplin — APPROVED** [review]
Looks good to me, adds a test 👍

**Comment by gemmaguest** [comment]
@mantidproject/gatekeepers Could we get this merged today because it's needed for the patch release build tonight

**Pull request merged**
