### PR TITLE
Add a new `ComplexImage` property to MaxEnt

### LINKED ISSUE #15553: Add MaxEnt ComplexImage algorithm property
Add ComplexImage algorithm property to MaxEnt algorithm.

The present the entropy is calculated both for real and imaginary part. In some cases this is what you want but for example 1. if you wanted reconstruct a charge density from measured structure factors then you know that it is not physical to have imaginary charge density. 2. in some cases the Muon users know that the only real frequencies should be generated. 

Therefore add ComplexImage property which default to False if ComplexData is False, and defaults to True if ComplexData is True.

If ComplexImage is False then don't include the imaginary part of the image in calculating the entropy, and when calculating data from an image simply, and where a complex FFT is used, simply ensure that the imaginary part of the image is zero

This issue created during testing of #15494

### PR DESCRIPTION
**Pull request by raquelalvarezbanos**
Added a new input property, `ComplexImage`, so that scientists can force the image to be real.

**To test:**

Run the following script:

```
from math import pi, sin, cos
X = []
YRe = []
YIm = []
E = []
N = 500
w = 3
for i in range(0,N):
    x = 2*pi*i/N
    X.append(x)
    YRe.append(cos(w*x))
    YIm.append(sin(w*x))
    E.append(0.1)
CreateWorkspace(OutputWorkspace='ws',DataX=X+X,DataY=YRe+YIm,DataE=E+E,NSpec=2)
evolChi1, evolAngle1, image1, data1 = MaxEnt(InputWorkspace='ws', ComplexData=True, ComplexImage=True, chiTarget=2*N, A=0.001)
evolChi2, evolAngle2, image2, data2 = MaxEnt(InputWorkspace='ws', ComplexData=True, ComplexImage=False, chiTarget=2*N, A=0.001)
```

which creates a workspace with a function `cos(w0 * t) + i sin(w0 * t)`, for which the Fourier transform is a delta peak `delta (w-w0)`. Both executions should give similar results. Note that if you change the input signal to `sin(w0 * t) + i cos(w0 * t)`, like this:

```
from math import pi, sin, cos
X = []
YRe = []
YIm = []
E = []
N = 500
w = 3
for i in range(0,N):
    x = 2*pi*i/N
    X.append(x)
    YIm.append(cos(w*x))
    YRe.append(sin(w*x))
    E.append(0.1)
CreateWorkspace(OutputWorkspace='ws',DataX=X+X,DataY=YRe+YIm,DataE=E+E,NSpec=2)
evolChi1, evolAngle1, image1, data1 = MaxEnt(InputWorkspace='ws', ComplexData=True, ComplexImage=True, chiTarget=2*N, A=0.001)
evolChi2, evolAngle2, image2, data2 = MaxEnt(InputWorkspace='ws', ComplexData=True, ComplexImage=False, chiTarget=2*N, A=0.001)
```

the algorithm will fail to converge, as it will be trying to reconstruct a complex image using its real part only.

Fixes #15553

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Anders-Markvardsen** [comment]
New options ComplexImage works for all the cases I tried, including running: 

```
from math import pi, sin, cos
X = []
YRe = []
YIm = []
E = []
N = 500
w = 3
for i in range(0,N):
    x = i/float(N)
    X.append(x)
    YRe.append(cos(2*pi*w*x))
    YIm.append(sin(2*pi*w*x))
    E.append(0.1)
CreateWorkspace(OutputWorkspace='ws',DataX=X+X,DataY=YRe+YIm,DataE=E+E,NSpec=2)
evolChi1, evolAngle1, image1, data1 = MaxEnt(InputWorkspace='ws', ComplexData=True, ComplexImage=True, chiTarget=2*N, A=0.001)
evolChi2, evolAngle2, image2, data2 = MaxEnt(InputWorkspace='ws', ComplexData=True, ComplexImage=False, chiTarget=2*N, A=0.001)
```

Note your initial example confused me since it did not generate a delta function at w=3 since it did not have the x-range [0:1]:) But the above example has this.

The documentation says the transform from image to data is:

d_m = \frac{1}{N} \sum_{j=0}^{N-1} x_j e^{i 2\pi m j / N}

However to be consistent with for example the image created by the above example, which has a height just below 1 (below one OK since the data has errors) should the above equation not read:

d_m = \sum_{j=0}^{N-1} x_j e^{i 2\pi m / N}

Note if you run

```
from math import pi, sin, cos
X = []
YRe = []
YIm = []
E = []
N = 500
w = 3
for i in range(0,N):
    x = i/float(N)
    X.append(x)
    YRe.append(cos(2*pi*w*x))
    YIm.append(sin(2*pi*w*x))
    E.append(0.1)
CreateWorkspace(OutputWorkspace='ws',DataX=X,DataY=YRe,DataE=E,NSpec=1)
evolChi1, evolAngle1, image1, data1 = MaxEnt(InputWorkspace='ws', ComplexData=False, ComplexImage=True, chiTarget=2*N, A=0.001)
evolChi2, evolAngle2, image2, data2 = MaxEnt(InputWorkspace='ws', ComplexData=False, ComplexImage=False, chiTarget=2*N, A=0.001)
```

You get the nice expected result of a peak at w=-3 and w=3 both peaks of height close to 0.5

**Comment by Anders-Markvardsen** [comment]
@raquelalvarezbanos is it by purpose that you haven't added a comment to the release notes, in muon and say also under Algorithms->Improved?

**Comment by raquelalvarezbanos** [comment]
Thanks @Anders-Markvardsen, I forgot to mention this in the release notes, should be fixed now.

**Comment by Anders-Markvardsen** [comment]
I think the Pylint error is to do with build server is temporarily unstable. 

I have tested it on some further examples and I can't fault it:) and restructuring of code to accommodate this is clear. :shipit:

**Comment by Anders-Markvardsen** [comment]
Ups I pressed the wrong button. Here re-open it again for a gatekeeper to merge it :shipit:

**Comment by FedeMPouzols** [comment]
The pylint builds were a bit confused. After the last restart it seemed to go well so this should be ready to be merged as soon as the builds finish just to double check that there was no issues in the merge conflict resolution.

**Comment by raquelalvarezbanos** [comment]
Thanks @FedeMPouzols, I didn't notice it had failed again, how did you fix it?

**Comment by FedeMPouzols** [comment]
@raquelalvarezbanos: the pylint-pull-requests build has been bouncing back and forth between 0 and the real number of issues for some reason: http://builds.mantidproject.org/job/pull_requests-pylint/

**Comment by FedeMPouzols** [comment]
It may just be that a machine needed a clean build. That did the trick, but I'm not sure what was the issue.

**Pull request merged**
