### PR TITLE
Project recovery multiple instances

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Disables project recovery on start up if any other instances of MantidPlot are already running.

**To test:**

* Start an instance of MantidPlot and check that project recovery is running (create some content to recover)
* start a second instance and note that no recovery is *not* offered
* close down the second instance
* crash the first instance and start a new instance to check it can be recovered.

Does this update require release notes?
- [ ] Yes
- [X] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by keeeto — CHANGES_REQUESTED** [review]
* This doesn't offer full project recovery, but I guess that will be fixed once the branch is merged. Is this likely to cause conflicts?

* Graceful exit of the second instance of Mantid, before recovery of the first results in the recovery files being deleted.

**Comment by martyngigg** [comment]
Thanks, @keeeto. I see the problem. I'll also merge in `release-next` so we can make sure the full recovery works.

**Review by keeeto — APPROVED** [review]

**Review by keeeto — CHANGES_REQUESTED** [review]
This has fixed the previous issues. Closing Mantid instance 2 does not delete the checkpoint files from Mantid instance 1.

However, now if we segfault Mantid instance 1 then try to reload Mantid 1 whilst Mantid 2 is still running then project recovery is not offered.

**Comment by martyngigg** [comment]
@keeto We've only implemented the basic check for other instances running so to recover the crash from instance 1 then you'll also need to close instance 2, but as instance 2 is not running recovery it won't clear the recovery files on exit.

**Comment by martyngigg** [comment]
@keeeto Could you double check that this works?

**Comment by keeeto** [comment]
@martyngigg This works as you describe. One thing to note is that if two instances of Mantid are started in quick succession then project recover is not started in either; I will make a note of this in the concepts doc.

**Review by keeeto — APPROVED** [review]

**Pull request merged**
