### PR TITLE
Workbench: Replace zoom icons in plot and slice-viewer GUI

### LINKED ISSUE #25837: Workbench: Plot Window zoom icon is misleading
Since the zoom action can do both zooms in and out, it makes sense that it is just a magnifying glass with no plus in it.

Replace `mdi.magnify-plus-outline` with `mdi.magnify` in all occurrences, maybe other than the plot window, such as slice viewer, and documentation.

### PR DESCRIPTION
**Pull request by cailafinn**
**Description of work.**
Changed Mantid Workbench zoom icons to ``mdi.magnify`` in plot and slice-viewer toolbars. 

**To test:**
1. Plot a spectrum and ensure magnifying glass (zoom) icon does not contain a plus. 
2. Open the slice viewer for some data and check zoom icon does not contain a plus. 

Resolves #25837 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by Pasarus — CHANGES_REQUESTED** [review]
I like how the documentation has been kept up to date! However, could you add some release notes?

**Review by Pasarus — DISMISSED** [review]
All changes look good! :+1:

**Review by NickDraper — APPROVED** [review]
Changes are good, I updated the release notes slightly to make them more user-friendly.

**Review by Pasarus — APPROVED** [review]
Test failures aren't related changes look good still.

**Pull request merged**
