### PR TITLE
Invalidate common-bins-flag in EventWorkspace.

### LINKED ISSUE #16133: EventWorkspace does not invalidate the "common bins flag" when accessing X data.
In `MatrixWorkspace` (and thus `Workspace2D`), accessing spectrum data, e.g., with `dataX(index)` forwards to `dataX()` of a spectrum, as follows:
```cpp
  MantidVec &dataX(std::size_t const index) {
    return getSpectrum(index)->dataX();
  }
``` 
`getSpectrum` calls `invalidateCommonBinsFlag();` since the bins of a single spectrum might get modified.

However, in `EventWorkspace`, `invalidateCommonBinsFlag();` is called neither directly nor indirectly since `getSpectrum` is not used in the implementation of, e.g., `dataX(index)`, but the access is direct:
```cpp
  return this->data[index]->dataX();
```

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Fixed #16133 by using `getSpectrum` in `dataX` etc., which then invalidates the common bins flag.

**To test:**
- Check if the commons bins flag is now invalided. Try the Python example from the issue.
- Make sure the added regression test fails if the bug is reintroduced.

Unless we encounter previously hidden issues after the fix, this does not need to be in the release notes.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
@SimonHeybrock : you'd want this to go in release 3.7? I think it's worth. If so, I'll be happy to give it a check based on the examples from the issue. All looks good and worth including asap.

**Comment by NickDraper** [comment]
If we are fixing this, don't we need to pay attention to the operations that should re-validate the common-bins-flag.

EventWorkspace->setAllX()

**Comment by NickDraper** [comment]
I'd also like to see a unit test that shows the invalidation and re-validation of the common-bins-flag.

**Comment by SimonHeybrock** [comment]
@FedeMPouzols I am not the right person to judge whether or not this should be in 3.7. Since it is not a big change, I don't see why not.

@NickDraper Once the flag has been invalidated, `MatrixWorkspace::isCommonBins()` will run a check and re-validate the flag, so I don't think it is necessary to do it manually in `setAllX()`.

I will add a unit test as you suggested.

**Comment by NickDraper** [comment]
Unit test is in place and checks both invalidation and revalidation.
Code is good.

This is all under the hood stuff so does not need to be in release notes.

I'm going to assume that the system tests will pass, as they passed last time, and the only addition in between was a unit test.

:shipit:

**Comment by FedeMPouzols** [comment]
And all the tests passed again.

**Pull request merged**
