### PR TITLE
Add output options to ConvFit

### LINKED ISSUE #28721: Add Output members and Convolute members as options in ConvFit
This were options in the old ConvFit which were removed when it was updated. Feedback from scientists is that these are useful features however so they should be added back in.

### PR DESCRIPTION
**Pull request by Matthew-Andrew**
**Description of work.**

This adds the OutputCompositeMembers and the Convolve Members options to the ConvFit tab in IndirectDataAnalysis. 

**To test:**
  * Perform a fit with both options (Convolve members overwrites OutputCompositeMembers). In the output composite members case you output workspace should contain both the raw data, calculated fit, the differance between them and the individual components of the composite function which makes up the fit function. If Convolve members is selected the output should instead contain the individual components of the fit convoluted with the resolution.
  * Data to test can be found in #26631

Fixes #28721  

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
conflicts and failing tests

**Comment by AnthonyLim23** [comment]
does #28830 and this have any interdependency?

**Comment by Mantid-Matthew** [comment]
> does #28830 and this have any interdependency?

No

**Review by StephenSmith25 — COMMENTED** [review]
This functions well and the code changes look good 👍 . Just one question, which may be due to my unfamiliarity with this, but if you have the option convole members selected with multiple functions is there an easy way to determine which convolution corresponds to each function? 

For instance, I tried fitting one Lorentzian and a delta function and when plotting the output workspace spectra 4 and 5 have the same label.

**Comment by SpencerHowells** [comment]
@StephenSmith25 @Mantid-Matthew Good point! It has always been like that. I asked if it could be labelled with the Function. I seem to remember that someone looked into it.

**Comment by AnthonyLim23** [comment]
changing the labels from a fit is a nightmare. I tried it a while back.

**Comment by AnthonyLim23** [comment]
@StephenSmith25 is this approved or do we need changes?

**Review by StephenSmith25 — APPROVED** [review]

**Pull request merged**
