### PR TITLE
Remove MDEvents library

### PR DESCRIPTION
**Pull request by martyngigg**
Fixes issue [#11209](http://trac.mantidproject.org/mantid/ticket/11209)

**Tester**
As with any large set of change such as this it is difficult. Not all of the classes from `MDEvents` were merged to `DataObjects` as some classes did not belong there, e.g. `SaveMD`/`LoadMD`. They have been moved to the appropriate locations.

Make sure the tests are all passing and you agree with the changes.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by martyngigg** [comment]
Jenkins, retest this please

**Comment by martyngigg** [comment]
Jenkins, retest this please

**Comment by martyngigg** [comment]
Jenkins, retest this please

**Comment by martyngigg** [comment]
Jenkins, retest this please

**Comment by OwenArnold** [comment]
The current structure looks logical in the expanded packages, updates seem to have been done carefully. All tests passing.

**Pull request merged**
