### PR TITLE
Maximum 12 threads to be used in systemtests

### PR DESCRIPTION
**Pull request by nvaytet**
**Description of work.**

Running System Tests with a large number of cores (e.g. 25) has led to some memory issues and slow downs.
Here we capped the number of cores used by Jenkins for the System Tests to 12 (each running test still uses 2 OpenMP threads).

**To test:**

Wait for builds to complete.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — DISMISSED** [review]
The code changes look sensible here.

When the builds pass LGTM

**Comment by nvaytet** [comment]
the `ILLDetectorEfficiencyCorUserTest` tests are still taking ages on the build server: http://builds.mantidproject.org/job/pull_requests-rhel7/25386/console

**Comment by NickDraper** [comment]
@nvaytet Is this still in progress?  if not please remove the label so it can be reviewed

**Comment by nvaytet** [comment]
My apologies, this one slipped out of my mind.

**Review by martyngigg — APPROVED** [review]
I still think this is a sensible change. Real-world usage has shown that anything over 12-16 threads can start having a negative impact anyway.

**Pull request merged**
