### PR TITLE
Implement a lazy loading ExperimentInfo class

### PR DESCRIPTION
**Pull request by martyngigg**
Fixes issue [#11101](http://trac.mantidproject.org/mantid/ticket/11101)
### Tester

This is currently a stand alone piece of work that will be used by `LoadMD` in [#11111](http://trac.mantidproject.org/mantid/ticket/11111). The class accepts a pointer to a NeXus file and a path to an experiment group. When any method is called on the object it loads all information from the file at that point.

As nothing uses it yet the there are no runtime checks to perform, only a code review and check the unit test is okay.

### CODE REVIEW

**Comment by martyngigg** [comment]
Jenkins, retest this please

**Comment by martyngigg** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please...

**Comment by FedeMPouzols** [comment]
There's a a couple of places in `FileBackedExperimentInfoTest.h` where the intel compiler and old gcc cannot cope with `boost::make_shared<::NeXus::File>` (lines 38 and 240) because of the `<::`.

**Comment by martyngigg** [comment]
Thanks, I thought I'd caught all of those.

**Comment by martyngigg** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
MSVC is now complaining with some warnings that come from NeXusStream.hpp. Strange, I hadn't seen those in the previous build.

**Comment by martyngigg** [comment]
I hadn't seen that either. It must be from the NeXus inclusion in the unit test. The warning is actually something we have to suppress anyway and this is usually done in `System.h` but it is not included before the NeXus include here at the moment. I'll move the include.

**Comment by martyngigg** [comment]
That seems to have fixed the warnings now.

**Comment by FedeMPouzols** [comment]
All compilers are happy now. The code looks really neat, well organized, documented and tested. Ready for further work in LoadMD.

**Pull request merged**
