### PR TITLE
Convert QSetting properties to boolean if a boolean is expected

### LINKED ISSUE #33900: Settings cannot open if multiple mantids are opened in quick succession
**Describe the bug**
After opening two instances of Mantid in quick succession (don't wait for the first to finish loading before opening the second), the settings dialog will not open. Instead the following exception occurs.

```
Traceback (most recent call last):
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mantid_manual_testing\lib\site-packages\workbench\app\mainwindow.py", line 684, in open_settings_window
    settings = SettingsPresenter(self)
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mantid_manual_testing\lib\site-packages\workbench\widgets\settings\presenter.py", line 37, in __init__
    self.general_settings = general_settings if general_settings else GeneralSettings(parent, None, self)
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mantid_manual_testing\lib\site-packages\workbench\widgets\settings\general\presenter.py", line 54, in __init__
    self.load_current_setting_values()
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mantid_manual_testing\lib\site-packages\workbench\widgets\settings\general\presenter.py", line 192, in load_current_setting_values
    self.view.completion_enabled.setChecked(completion_enabled)
TypeError: setChecked(self, bool): argument 1 has unexpected type 'str'

```

**To Reproduce**
1. Open Mantid twice in quick succession
2. Go to File > Settings in both Mantids
3. One will not work and throw up the error reporter

**Expected behavior**
Settings should open in both windows. This is fine if you wait for Mantid to open before starting the second instance.

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: all

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
When opening multiple Mantids in quick succession, there is sometimes a race condition between the syncing of the QSettings, and the 'fixup' of the booleans values such as changing 'true' to True. The syncing can be triggered by the event loop, and if this is triggered at the correct time, the converted booleans can be overwritten back to their original string form for a specific mantid instance. When this happens, there are errors.

The solution I have gone for is to ~~use Pyside2 to~~ specify the type of the QVariant being retrieved. This seems to correctly handle the conversion of  `'false': str` to `False: bool` and `'true': str` to `True: bool`. 

**To test:**

1. Use the instructions [here](https://developer.mantidproject.org/BuildingWithCMake.html#building-the-installer-package) to create a package for this branch. Install this package locally on your system
1. Open Mantid twice in quick succession (Quadruple click)
2. Go to File -> Settings in both Mantids
3. There should not be any errors in either of the Mantids. The settings should function as normal.

*No release notes because this problem is a regression since v6.3*

Fixes #33900

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Harrietbrown** [comment]
I am unable to build the package local, so I'm unasigning myself for this.

**Comment by robertapplin** [comment]
Maybe an opportunity to use https://builds.mantidproject.org/job/build_packages_from_branch/ to create the package for testing!

**Review by DanielMurphy22 — APPROVED** [review]
Works well for me! Good job! Tested on Windows.

**Comment by robertapplin** [comment]
> Can I just ask a quick question about the `PySide2` comment? I can't see an import of this and furthermore some of our wrapped C++ components require that the backend is `PyQt5` and not `PySide2`. Could you expand a little on the comment?

Sorry, it was probably a bit of an irrelevant comment. What I think I meant is that it seems we are using the [QSettings from pyside2](https://doc.qt.io/qtforpython-5/PySide2/QtCore/QSettings.html#PySide2.QtCore.PySide2.QtCore.QSettings.value) on this line: https://github.com/mantidproject/mantid/blob/15ef1d68a3427cf52dbf91faa2072ca5c5bae02d/qt/applications/workbench/workbench/config/user.py#L101
because the `type` keyword for `QSettings::value` doesn't seem to come with `PyQt5`, unless I am mistaken?

**Comment by martyngigg** [comment]
> > Can I just ask a quick question about the `PySide2` comment? I can't see an import of this and furthermore some of our wrapped C++ components require that the backend is `PyQt5` and not `PySide2`. Could you expand a little on the comment?
> 
> Sorry, it was probably a bit of an irrelevant comment. What I think I meant is that it seems we are using the [QSettings from pyside2](https://doc.qt.io/qtforpython-5/PySide2/QtCore/QSettings.html#PySide2.QtCore.PySide2.QtCore.QSettings.value) on this line:
> 
> https://github.com/mantidproject/mantid/blob/15ef1d68a3427cf52dbf91faa2072ca5c5bae02d/qt/applications/workbench/workbench/config/user.py#L101
> 
> because the `type` keyword for `QSettings::value` doesn't seem to come with `PyQt5`, unless I am mistaken?
> 
> For Pyqt5: https://doc.qt.io/qt-5/qsettings.html#value

Thanks for the information. It look like the docs above are the C++ Qt5 documentation and not the PyQt5? I think this might be one of the classes where the PyQt5 bindings have extra features so the standard Qt docs don't show it. Looking at https://www.riverbankcomputing.com/static/Docs/PyQt5/api/qtcore/qsettings.html?highlight=qsettings#value it seems to suggest that `type` does indeed exist at the PyQt binding level so we're all good.

**Pull request merged**
