### PR TITLE
Indirect FQFit - Fix crash when loading data that has no EISF

### LINKED ISSUE #31247: Indirect FQFit - Crash when loading result data
### Expected behavior
The data should be loaded ok.

### Actual behavior
The interface hangs and eventually crashes.

### Steps to reproduce the behavior
1. Indirect Data Analysis interface
2. Go to FQFit tab
3. Load the data below.
4. Hangs and then crash
[irs26176_graphite002_red_Conv_seq_2L_0-50__Result.zip](https://github.com/mantidproject/mantid/files/6390047/irs26176_graphite002_red_Conv_seq_2L_0-50__Result.zip)

### Platforms affected
Found on windows, probably all

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR fixes a crash in FQFit when loading data that has no EISF parameter.

**To test:**
1. Indirect Data Analysis interface
2. Go to FQFit tab
3. Load the data below. It might take a while to load, but it should not crash.
4. Choose any fit function and click `Run`
5. You should see a fit in the plot when it is finished fitting.
[irs26176_graphite002_red_Conv_seq_2L_0-50__Result.zip](https://github.com/mantidproject/mantid/files/6390047/irs26176_graphite002_red_Conv_seq_2L_0-50__Result.zip)

Fixes #31247

*This does not require release notes* because **it is a regression since last release introduced in #31089**

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by robertapplin** [comment]
I want to check with @Harrietbrown if this fix is ok because it seems to have been purposefully added in #31089

**Comment by SpencerHowells** [comment]
@robertapplin This is want I want!

**Comment by SpencerHowells** [comment]
@robertapplin Not quite correct - if there is EISF there must be Width. Just realised that for some CONVFit there may not be a Lorentzian for Width.  So in SampleLogs - if Lorentzians is >=1 Width exists, if delta_function = True EISF exists.

**Review by Harrietbrown — APPROVED** [review]
The file loads as described, and the changes to the tests are good. Good job

**Pull request merged**
