### PR TITLE
Add new loader for PSD event data for DNS at MLZ

### LINKED ISSUE #22871: Create a loader for DNS PSD event data
Request from DNS instrument scientists: `LoadDNSEvent` algorithm to load the data from the new PSD detector to a Mantid `EventWorkspace`.

The event data are in qmesydaq listmode (binary) format.

@thomueller  will work on it.

### PR DESCRIPTION
**Pull request by martyngigg**
**This is a copy of #32709 to fixup the history to base on release-next. See comments on that pull request for history.**

**Description of work.**

The PR adds the algorithm LoadDNSEvent, which is a loader for the Event data of the position sensitive detector of the DNS instrument at MLZ. It loads the events into an EventWorkspace.

Requested by MLZ DNS instrumenent scientist = me.

To test:
This is also the example in the docs:

```python
eventWS = LoadDNSEvent(InputFile="DNS_psd_150c_first_tube.mdat", ChopperChannel='2', NumberOfTubes='1')
print("Number of events: {}".format(eventWS.getNumberEvents()))
print("Maximum time of flight: {}".format(eventWS.getTofMax()))
print("Number of detector pixels: {}".format(eventWS.getNumberHistograms()))
print("Number of bins: {}".format(eventWS.blocksize()))
# rebin spectra:
test2 = Rebin(InputWorkspace='eventWS', Params='0, 100, {0}'.format(eventWS.getTofMax()))
print("Number of bins after rebinning: {}".format(test2.blocksize()))
```
```
Should output:
Number of events: 184
Maximum time of flight: 6641.4
Number of detector pixels: 1024
Number of bins: 1
Number of bins after rebinning: 67
```

Fixes #22871.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DavidFair — APPROVED** [review]
Retesting locally this still works
I've diff'ed the two trees and the files are identical, minus the 6.4 changes so my previous code review and approval stands.

**Comment by DavidFair** [comment]
Since the diff is the same all of the work was ported as-is by Martyn so that he could merge it.

Also @thomueller thank you for your changes! Sorry it took a while to get everything resolved, but at least it landed for 6.3 still

**Comment by thomueller** [comment]
Sorry for the extra work, great that you could fix it. Thanks for all the support @David and Martyn and for allowing it in 6.3.

**Comment by thomueller** [comment]
Just one thing. We reduced the test files 2 times, the old ones are still on the remote store, not sure if they will be automatically removed by a bot, in case you want to delete them:
DNS_psd_pulser_first_tube_3000c.mdat.md5
ca759e6c7ed2aed36a48dd97497d22cd
DNS_psd_pulser_ON473_31.mdat.md5
8acec7cb95adbb07938e159868b6aa0b

**Comment by martyngigg** [comment]
> Sorry for the extra work, great that you could fix it. Thanks for all the support @david and Martyn and for allowing it in 6.3.

No problem. Sorry it took so long to get this through.


> Just one thing. We reduced the test files 2 times, the old ones are still on the remote store, not sure if they will be automatically removed by a bot, in case you want to delete them: DNS_psd_pulser_first_tube_3000c.mdat.md5 ca759e6c7ed2aed36a48dd97497d22cd DNS_psd_pulser_ON473_31.mdat.md5 8acec7cb95adbb07938e159868b6aa0b

Thanks for this. I'll remove them 👍🏻

**Pull request merged**
