### PR TITLE
Fix error transposing 2D MDworkspaces in sliceviewer

### LINKED ISSUE #33241: Error when transposing 2D MDHisto workspaces
**Describe the bug**
Found during manual testing for 6.3 #33201
Error when transposing 2D MDHisto workspaces (but the colorfill data are flipped)

```
Traceback (most recent call last):
  File "c:\mantid\qt\python\mantidqt\mantidqt\widgets\sliceviewer\presenter.py", line 207, in dimensions_changed
    if sliceinfo.slicepoint[data_view.dimensions.get_previous_states().index(None)] is None:
ValueError: None is not in list
```

**To Reproduce**
(1) Make the workspace
```
ws = CreateMDWorkspace(Dimensions='3', Extents='-3,3,-3,3,-3,3',
                       Names='H,K,L', Units='r.l.u.,r.l.u.,r.l.u.',
                       Frames='HKL,HKL,HKL',
                       SplitInto='2', SplitThreshold='10')
mdHisto_2D = BinMD(InputWorkspace=ws, 
    AlignedDim0='H,-1,1,100', AlignedDim1='K,-1,1,100') # 2D cut
```
(2) Open `mdHisto_2D` in sliceviewer
(3) Transpose the data (i.e. click Y next to the H label)

To see that the data are actually transposed we can add a peak like so in step (1)
```
ws = CreateMDWorkspace(Dimensions='3', Extents='-6,6,-4,4,-2,2',
                       Names='H,K,L', Units='r.l.u.,r.l.u.,r.l.u.',
                       Frames='HKL,HKL,HKL',
                       SplitInto='2', SplitThreshold='50')
expt_info = CreateSampleWorkspace()
ws.addExperimentInfo(expt_info)
SetUB(ws, 1,1,2,90,90,120)
FakeMDEventData(ws, EllipsoidParams='1e+04,0,1,1,1,0,0,0,1,0,0,0,1,0.02,0.06,0.03,1', RandomSeed='3873875')
mdHisto_2D = BinMD(InputWorkspace=ws, 
    AlignedDim0='H,-2,2,100', AlignedDim1='K,-2,2,100') # 2D cut
```

**Expected behavior**
Would flip the data without error

**Platform/Version (please complete the following information):**
 - Mantid 6.2 nightly 4 Jan

### PR DESCRIPTION
**Pull request by RichardWaiteSTFC**
**Description of work.**

Add check for ndim > 2 before attempting to access slicepoint of an integrated dim - a 2D workspace doesn't have a slicepoint, the `dimensions_changed` can only be triggered by a transposition of the axes. have added a test to stop regression.

I added a method in the model to get the number of dimensions of the workspace - I could have got this from e.g.  ` len(sliceinfo.slicepoint)` or similar, but I thought it is more obvious/readable to have a `get_number_dimensions()` - happy to change.

**To test:**

Follow instructions in issue

Fixes #33241 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by sf1919** [comment]
I have done a functional test as described in the issue and it works well - it definitely doesn't crash like it used to!
The code looks good to me too. 

I do have a couple of queries though.
1) When I was playing around doing functional testing I decided to press the ROI Extraction button and it came up with an error message and `WARNING:matplotlib.text:posx and posy should be finite values` in the log. Is this expected because of the workspace setup in this example or is this another issue?

2) Does this need a release note?

**Comment by sf1919** [comment]
Regarding 1) I'm not sure. I reproduced it several times and I didn't even need to zoom in etc for it to happen. I tested it on the most recent nightly and it also runs into the same error (as well as the crash that this PR is fixing). It's why I wondered if it was a problem with the workspace example we are using.

**Comment by RichardWaiteSTFC** [comment]
> Regarding 1) I'm not sure. I reproduced it several times and I didn't even need to zoom in etc for it to happen. I tested it on the most recent nightly and it also runs into the same error (as well as the crash that this PR is fixing). It's why I wondered if it was a problem with the workspace example we are using.

Possibly but it looks like a matplotlib error, if the cuts work OK and you reproduce this on the installed nightly I'm inclined to think it is a separate issue. If you can reproduce it and have time, would you mind making an issue for it?

**Comment by RichardWaiteSTFC** [comment]
@sf1919 added release notes - they were already on my local branch I just hadn't pushed!

**Review by sf1919 — APPROVED** [review]
As mentioned above all works well and am pleased to see a test to keep a check on this in future. Happy also with release note so will approve.

**Pull request merged**
