### PR TITLE
Remove debug poco lib packages from equivs file

### LINKED ISSUE #23048: Developer dependency package doesn't work on Ubuntu 18.04
The specific versions of the poco debug packages in the equivs control file are not available on Ubuntu 18.04. These can just be removed, similar packages for other libraries are not included in the dev dependencies, they can be manually installed as required.

### PR DESCRIPTION
**Pull request by matthew-d-jones**
**Description of work.**

Removed poco lib debug packages from the equivs control file so that it works on Ubuntu 18.04 as well as 16.04. Fixed problem occuring if `PocoFoundation` debug library is found by CMake but one of the others is missing.

**To test:**

On Ubuntu check this successfully creates the dev dependency package
```
equivs-build mantid/buildconfig/dev-packages/deb/mantid-developer/ns-control
```
Review CMake change, could also check behaviour if not all debug libraries are installed on the system. 

Fixes #23048

Does this update require release notes?
- [ ] Yes
- [x] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — APPROVED** [review]
Nice set of changes. The control file for the developer package can now again function for multiple Ubuntu versions.
There is no need to bump the version of the developer package as it looks like we never published 1.3.7 in the first place.

**Comment by DanNixon** [comment]
This does not seem to fix the original issue I had building on a clean Ubuntu 16.04 image.

I still get `ninja: error: '/usr/lib/libPocoFoundationd.so', needed by 'bin/libMantidKernel.so', missing and no known rule to make it` until I install `libpoco*-dbg`.

**Comment by ianbush** [comment]
It should ignore them for a release build, but not for a debug build, I think.

**Comment by martyngigg** [comment]
@DanNixon Thanks for remembering that. I guess we should check the validity of the symlink in `FindPoco` too and then we should be good. I'd really like to keep the `mantid-developer` control file working on both 16.04/18.04.

**Comment by martyngigg** [comment]
#23136 adds a small check for the existence of the libs that should fix this problem.

**Pull request merged**
