### PR TITLE
Reflectometry GUI now outputs stitched transmission run in wavelength

### LINKED ISSUE #18707: Reflectometry GUI does not output combined transmission run in wavelength
The reflectometry GUI should output combined (stitched) transmission run in wavelength. This doesn't happen when transmission runs are specified via the `Settings` tab.

### PR DESCRIPTION
**Pull request by PranavBahuguna**
The Reflectometry GUI was supposed to output a stitched transmission in wavelength if transmission runs are specified before processing. This happens if transmission runs were specified directly in each row being processed, but not if they were specified in the `Settings` tab. This PR fixes this very issue.

**To test:**

- Open the Reflectometry interface from Interfaces->Reflectometry->ISIS Reflectometry
- Load `INTER_NR_test2.tbl` (available from sample ISIS dataset) by navigating to Reflectometry->Import .TBL
- Opening the first group reveals they have transmission runs `13463` and `13464`. Processing the group should produce a stitched transmission workspace `TRANS_13463_13464`.
- Remove the transmission runs from the table. Go to the `Settings` tab and input `13463,13464` into `Transmission run(s)`. Go back to the `Runs` tab and process the group again and ensure you have the same results as before.

Fixes #18707.

*Does not need to be in the release notes.*

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by gemmaguest — CHANGES_REQUESTED** [review]
The changes look good, but I have found one small problem; if you remove the transmission runs from both the Runs and Settings tabs, then you cannot run the reduction - it gives the error `File "INTER" not found`. It looks like it's trying to load a transmission run even though none was specified.

**Comment by gemmaguest** [comment]
I've noticed another problem while testing this. It's not related to this PR, but might make sense to fix alongside it. If you enter different transmission runs in the `Runs` and `Settings` tabs (say 13463 in `Runs` and 13464 in `Settings`) then only one of them gets used, but both of them get loaded into workspaces, so it's not immediately obvious which one got used. Could we skip loading the one that is not used?

**Review by gemmaguest — APPROVED** [review]

**Comment by gemmaguest** [comment]
I haven't had time to fully test the new changes yet, but it looks like there is a bug where you get an `Invalid Filename ""` error if there is no transmission run specified in the `Settings` tab (even if there is one in the `Runs` tab).

**Comment by gemmaguest** [comment]
I'm now seeing the following error with this: Invalid value for property InputWorkspaces (str list) "": Select a value

**Comment by PranavBahuguna** [comment]
Could you be more specific? I cannot seem to be able to replicate this problem you are seeing.

**Comment by gemmaguest** [comment]
Ah, sorry, it's working now. I think I had the wrong instrument selected or something...

**Comment by gemmaguest** [comment]
This looks good now and behaves as expected. Please :shipit:

**Pull request merged**
