### PR TITLE
Reduce pylint warnings

### PR DESCRIPTION
**Pull request by AndreiSavici**
Ticket [#11134](http://trac.mantidproject.org/mantid/ticket/11134) aims to reduce pylint warnings. In this ticket I removed some unused imports. Unused variables is slightly harder. I removed unnecessary parentheses, and fixed some continuations. Unit test should pass. I was able to run all interfaces. Systrem test should pass as well.

### CODE REVIEW

**Comment by AndreiSavici** [comment]
retest this please

**Comment by DanNixon** [comment]
Jenkins, retest this please.

**Comment by martyngigg** [comment]
Could you update the pull request title remove the ticket number and capitalise the `r` in reduce. It would also be easier if the ticket mentioned in the comment had a link to it, following the example [here](http://www.mantidproject.org/Git_Workflow).

**Comment by AndreiSavici** [comment]
The build fails on a particular machine at ISIS, on a test where it cannot remove /tmp/test_file_for_load_md_histo_workspace_test_.txt. Master builds fail with the same error, only when they are run on  isis-mantidlx1

**Comment by martyngigg** [comment]
It looks like someone had run the tests on that machine under a different user account, meaning that the file was owned by the other user and not the `builder` account. I've removed the file.

**Comment by martyngigg** [comment]
Jenkins, retest this please.

**Pull request merged**
