### PR TITLE
Remove nist save option

### PR DESCRIPTION
**Pull request by Matthew-Andrew**
**Description of work.**
The Nist data format is no longer needed, this removes the option to use it from the GUI's but leaves the algorithm for now.
**Report to:** stephen.king@stfc.ac.uk 

**To test:**

The things to test here are that the save NIST option does not appear on either GUI but also more importantly that the other save options still function properly. An example work-flow on how to do this is below. 

Get this data
[loqdemo.zip](https://github.com/mantidproject/mantid/files/2118722/loqdemo.zip)
For both GUI's
* Open the GUI, select LOQ as the instrument
* Load MaskFile.txt as the user file 
* Load batch_mode_reduction.csv as the batch file

In old GUI
* Click 1D reduce
* Select save other and save out the reduced workspace (line_one_reduction). Check that it has saved out without error. The files should be written to the output directory set in save file dialog. 

In new GUI
* Below the data table select Both as the output format.
* Click process, confirm that the reduced files are saved out.

Fixes #22631 . 

Does this update require release notes?
Requires release notes are here #22628 
- [ ] Yes
- [ ] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by josephframsay — CHANGES_REQUESTED** [review]
Unfortunately when running with the new GUI, I get the following message:
```
argument of type 'NoneType' is not iterable
  at line 385 in '/home/joe/mantid/scripts/SANS/sans/gui_logic/sans_data_processor_gui_algorithm.py'
  caused by line 27 in '/home/joe/mantid/scripts/SANS/sans/sans_batch.py'
  caused by line 33 in '/home/joe/mantid/scripts/SANS/sans/sans_batch.py'
  caused by line 120 in '/home/joe/mantid/scripts/SANS/sans/algorithm_detail/batch_execution.py'
  caused by line 853 in '/home/joe/mantid/scripts/SANS/sans/algorithm_detail/batch_execution.py'
  caused by line 975 in '/home/joe/mantid/scripts/SANS/sans/algorithm_detail/batch_execution.py'
```

I also couldn't find the workspace `line_one_reduction` to save in the old GUI - am I misunderstanding the instruction?

**Comment by Mantid-Matthew** [comment]
Hi Joe, I think that is the bug fixed here #22671. I will merge in the relevant branch and then see whether is goes away.

With regards to finding the line one reduction in the old workspace were you running in batch mode? I think I forgot to mention this in the instructions.

**Comment by josephframsay** [comment]
@Mantid-Matthew just to confirm, I get 4 files saved from the new GUI - `first_time_front.nxs`, `first_time_rear.nxs`, `second_time_front.nxs`, `second_time_rear.nxs` - is this correct? From the old GUI, I am running in batch mode (at least, the batch mode checkbox is ticked)

**Comment by josephframsay** [comment]
Looks good to go! Always a fan of PRs with net negative line counts

**Review by josephframsay — APPROVED** [review]

**Comment by martyngigg** [comment]
@Mantid-Matthew Could assign this to an appropriate milestone?

**Comment by martyngigg** [comment]
@Mantid-Matthew Please report back to Steve King that this is now available.

**Pull request merged**
