### PR TITLE
Include Scaling step in RRO Workflow Diagram

### LINKED ISSUE #16660: Fix workflow diagram for RRO
Currently, the workflow diagram for ReflectometryReductionOne (see [here](http://docs.mantidproject.org/nightly/_images/ReflectometryReductionOne-v1_wkflw.png)) is incorrect and in parts, incomplete.

Before we review this diagram as a whole in some of the issues listed in #16455 it should be fixed as it is currently.

### PR DESCRIPTION
**Pull request by MattKing06**
This is a sub-issue of #16455

**To test:**
- Build `ReflectometryReductionOne-v1` documentation
- Check the workflow diagram is now complete and Scaling step is included

Fixes #16660

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
@MattKing06 I think we should mention this in the release notes, as it was pointed out by scientists.

**Comment by raquelalvarezbanos** [comment]
The Scaling step is displayed correctly. But now that I look at the diagram, I think the section between  `OutputWorkspace` and `Scale` is not correct. From the diagram it seems that only when `MomentumTransferMin` AND `MomentumTransferMax` AND `MomentumTransferStep` are given, we apply the `Rebin` step. But looking at the code, if the first two are not given we try to calculate them from the `IvsLam` workspace, and if the last one is not provided, we apply `CalculateResolution` (see [here](https://github.com/mantidproject/mantid/blob/master/Framework/Algorithms/src/ReflectometryReductionOne.cpp#L648-L669)). Could we update this section as part of this PR?

**Comment by MattKing06** [comment]
@raquelalvarezbanos I agree, I'll see if I can fix this as part of this PR.

**Comment by raquelalvarezbanos** [comment]
Thanks @MattKing06 I think the important thing is to clarify how these are calculated: `MomentumTransferMin` and `MomentumTransferMax` from the equation `Q = 4 \pi / \lambda * sin (\theta)` and `MomentumTransferStep` from `CalculateResolution`. It is also important to clarify that the `Rebin` in `Q` is always applied.

**Comment by raquelalvarezbanos** [comment]
The workflow diagram is increasing in size but I think that is necessary if we want to document exactly what the algorithm does. Last section of the diagram (`Rebin` and `Scale` steps) looks more clear now in my opinion, it now documents how we calculate the necessary parameters for `Rebin` when those are not given by the user.

:shipit:

**Pull request merged**
