### PR TITLE
Add C++ SipTest disabled on Apple

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

The test passes under Conda so we should keep it.

It also fixes the [Conda tests](https://builds.mantidproject.org/job/main_nightly_deployment_prototype/310/testReport/projectroot.qt.widgets/common/Build_and_test___platform__macos___MantidQtWidgetsCommonTestQt5_ExtractSubtreesTest/) on macOS. Once re-enabled the pipeline spotted that the tests did not run due to a symbol error. The library is linked to boost::python but our code made no use of Python API directly so the linker dropped the symbols. Enabling this causes the compiler to spot that we are now using Python so keeps the link to the Python dylib.

**To test:**

* In a conda environment on macOS run any MantidQtWidgetsCommon test:

```ctest -R MantidQtWidgetsCommon```

and they should pass.

*There is no associated issue.*

*This does not require release notes* because **it is an internal change.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by cailafinn — COMMENTED** [review]
Fix looks good and most tests passing, I still have `FigureCanvasQtTest` failing locally, but I'm unsure if that's a local issue

**Comment by martyngigg** [comment]
> Fix looks good and most tests passing, I still have `FigureCanvasQtTest` failing locally, but I'm unsure if that's a local issue

Thanks. Let me check if it passes for me.

**Comment by martyngigg** [comment]
It does fail for me too. I will investigate.

**Comment by martyngigg** [comment]
It looks like a high dpi issue. Could we merge this and I'll look at that separately?

**Review by cailafinn — APPROVED** [review]
Issue found unrelated and raised. Looks good :+

**Pull request merged**
