### PR TITLE
Indirect - Elastic Window - Save Workspace Normalise by lowest temperature

### LINKED ISSUE #20316: Indirect - Elastic Window - Save Workspace Normalise by lowest temperature
On clicking `Save Results`, the `elt` workspace should  be saved too.

### PR DESCRIPTION
**Pull request by jmborr**
**To test:**
Follow instructions 1 to 5 in pull request #20040, then click in `Save Result` and make sure that a Nexus `*_elt.nxs` is saved to the default save directory.

Fixes #20316

[Release Notes](https://github.com/mantidproject/mantid/blob/54fe0ed3e57518f3ff85e9a2404fa3df9e6c241a/docs/source/release/v3.11.0/indirect_inelastic.rst)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by jmborr** [comment]
@louisemccann Are you still working in Mantid?

**Comment by jmborr** [comment]
@brandonhewer Would you please test this pull request for me? :pray:

**Comment by jmborr** [comment]
@AntonPiccardoSelg  Would you please review this pull request for me?

**Comment by AntonPiccardoSelg** [comment]
@jmborr The workspaces in the ADS are:

image

The saved files are:

image

There does not seem to be any `*_elt.nxs`. Any idea what is going on?

**Comment by jmborr** [comment]
@AntonPiccardoSelg  Sorry I'm asking, but you did click in option `Normalise to Lowest Temp` before running, right?

**Comment by AntonPiccardoSelg** [comment]
The screen looks like this:
image

I thought that I might be using the wrong version, but it seems right
image

The file is saved in your case?

**Comment by SpencerHowells** [comment]
@jmborr  in the edit you have added plotSpectrum. Should it be a save?

**Comment by AntonPiccardoSelg** [comment]
The screen looks like this:
image

I thought that I might be using the wrong version, but it seems right
image

The file is saved in your case?

**Comment by jmborr** [comment]
@SpencerHowells you're right, there's actually another place in the code for saving which I left untouched :anguished:
This  was silly from my part. I'll fix it in a sec :rocket:

**Comment by jmborr** [comment]
@AntonPiccardoSelg After this last commit I did verify the interface creates a `osi104367-104371_graphite002_red_elwin_elt.nxs` file.

**Review by AntonPiccardoSelg — APPROVED** [review]
Last changes look good. The `_elt` file is saved out.
@jmborr There are some merge conflicts.

**Pull request merged**
