### PR TITLE
Remove python 2/3 compatibility code from bindings

### PR DESCRIPTION
**Pull request by peterfpeterson**
While working on changes to logging, I discovered some compatibility code. This removes most of it from the bindings.

**To test:**

If the builds pass, it is good.

*There is no associated issue.*

*This does not require release notes* because it removes compatibility with python2 which has been gone for two releases.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
The changes look fine but I'm not sure why cppcheck failed?

**Comment by martyngigg** [comment]
Is it https://github.com/mantidproject/mantid/blob/c7fb7aff154f8106cf3f8e625ddd78ea5f984d99/buildconfig/CMake/CppCheck_Suppressions.txt.in#L24 that needs removing?

**Comment by martyngigg** [comment]
I finally found the culprit for this. Changing the export code must have effected the generated modules in the build area so we no longer need:
https://github.com/mantidproject/mantid/blob/c7fb7aff154f8106cf3f8e625ddd78ea5f984d99/buildconfig/CMake/CppCheck_Suppressions.txt.in#L92.
I was able to build locally (after building the same version of cppcheck) and get it to produce no errors after removing the above.

**Comment by martyngigg** [comment]
Did a different branch get merged in here? I'm seeing way more changes than before.

**Comment by peterfpeterson** [comment]
Yes, but I don't understand why the diff is showing up that way. Messing with history to fix it.

**Review by martyngigg — APPROVED** [review]
Good start on code clean up for Python 2/3

**Pull request merged**
