### PR TITLE
possibility to accumulate log messages

### PR DESCRIPTION
**Pull request by gvardany**
**Description of work.**
There is a need for a mechanism for accumulation of log messages.
For large workflows it is often desirable to printout concise reports of important information at the completion. 
Logging in real time can get lost in other verbose output of the child algorithms, so one has to scroll back to look up for the important information.
This PR adds a possibility to accumulate log messages and then report in one go to the desired channel.

**To test:**
Play with this script, will add unit tests shortly.
```
from mantid.kernel import logger

logger.accumulate("one\n")
logger.accumulate("two\n")
logger.accumulate("three\n")

logger.flush()

logger.accumulate("four\n")

logger.flush()

logger.accumulate("five\n")

logger.flushError()

logger.accumulate("six\n")
logger.accumulate("seven\n")

logger.flushInformation()

logger.accumulate("nine\n")

logger.purge()

logger.accumulate("ten\n")

logger.flush()
```

*There is no associated issue.*

*This does not require release notes since it is mainly a developer tool.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gvardany** [comment]
The open question is what to do if an algorithm is canceled or throws before reporting.

**Comment by NickDraper** [comment]
So I'm not sure how "thread safe" you intended this to be, but there are interactions in the shared logger object that a developer would not expect.

Any flush command will flush all accumulated messages, no matter what thread (or editor window as I tested it) they were added in.  Equally the Purge command will purge all messages no matter what thread they were added in.

**Comment by NickDraper** [comment]
Other than that it works well.

**Review by NickDraper — COMMENTED** [review]
Please take a look at my thread safety comments.  Whether this needs changing depends on the intended usage and how widely this starts to be used.

**Comment by gvardany** [comment]
Good point, I made a separate accumulator per thread.

**Review by NickDraper — APPROVED** [review]
Ok this works, and is good to go for it's intended purpose, however there is a strange interation when running parts of scripts in the script editor.

When you execute lines seperately in the same script they seem to get different accumulators (or it is wiped each time).

So in the same script tab if you run 
``` 
logger.accumulate("1 one\n")
```
then 
``` 
logger.accumulate("1 two\n")
```
then 
```
logger.accumulate("five\n")
logger.flushError()
```
You only get the last message, as if you did not run the earlier sections.

If you run them all as one you get what you would expect.

**Pull request merged**
