### PR TITLE
Fix issue with SANS data stitching

### PR DESCRIPTION
**Pull request by mdoucet**
The ORNL SANS reduction UI allows you to stitch data set. Those data sets can either be from a file, or a workspace. Everything works when stitching from file. There is a problem stitching data from a workspace.

The I(q) workspace produced by the reduction is a histogram, while the saved data files are point data.
Currently, the stitching code loads the histogram data, scales it, then transforms it to point data at the end. This order is wrong. It should first transform to point data as needed, then stitch.

**To test:**
- Perform a EQSANS reduction, then stitch it to itself by selecting the workspace for the first data set and the data that was written to file for the second. Click the auto-stitch button. The two curves should remain on top of each other (they didn't before).

Here's an example reduction: `/SNS/EQSANS/IPTS-15454/shared/67315_Iq.xml`
(Make sure to change the output directory on the first tab...)

There is no GitHub issue for this PR.

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AndreiSavici** [comment]
Looks OK. :shipit:

**Comment by quantumsteve** [comment]
Does this need to be in release 3.7?  If so, the [base branch must be `release-v3.7`](http://www.mantidproject.org/Git_Workflow#Code_Freeze)

**Comment by mdoucet** [comment]
Yes. This needs to be in the release. I created a separate PR #16379 so that it can be merged in `release-v3.7`

**Comment by quantumsteve** [comment]
The doc tests passed on the other build for release 3.7.

**Pull request merged**
