### PR TITLE
Remove `QT_VERSION_CHECK`'s from Indirect interfaces

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR removes all the Qt4 and 5 version checks from the Indirect interfaces.

**To test:**
A code review and make sure the tests pass.

Part of #30268

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
As this is maintenance I'm setting it back to 6.4 as per our usual policy of maintenance going on `main` after `release-next` is created.

**Comment by robertapplin** [comment]
The merge conflicts are now fixed. @martyngigg I see you are assigned, are you happy to give it a look over?

**Review by martyngigg — CHANGES_REQUESTED** [review]
Changes look good. I just wonder if, while we are editing this code, we could look at fixing the cppcheck warnings?

**Review by martyngigg — APPROVED** [review]
Thanks for fixing those cppcheck warnings.

**Pull request merged**
