### PR TITLE
Indirect ConvolutionFitSequential -  remove property logging

### LINKED ISSUE #17177: Indirect ConvolutionFitSequential - Remove logging on copy/delete/AddSampleLogs
### Expected behavior
* ConvolutionFitSequential should not spend additional time printing the logging information for processes such as:
* Tidying up temp workspaces
* Copying and adding sample logs

### Actual behavior
* Algorithm execution is slowed due to the time it takes to log this information

### Steps to reproduce the behavior
* Run algorithm and observe the logging for AddSampleLogs, CopyLogs, DeleteWorkspace

### Platforms affected
* All

### PR DESCRIPTION
**Pull request by ElliotAOram**
Removed property logging for `AddSampleLogs`,`CopyLogs`,`DeleteWorkspace` and `RenameWorkspace` 

**To test:**
- Run the [usage example](http://docs.mantidproject.org/v3.7.1/algorithms/ConvolutionFitSequential-v1.html) and ensure that the Result log does not contain entries for any of `AddSampleLogs`,`CopyLogs`,`DeleteWorkspace` and `RenameWorkspace` _(these were at the end of the algorithm execution)_

Fixes #17177 

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
The usage example failed for me when it attempted to create `result_ws` and had error message
```
ArgumentError: Python argument types in
    AnalysisDataServiceImpl.__getitem__(AnalysisDataServiceImpl, Workspace2D)
did not match C++ signature:
    __getitem__(class Mantid::API::AnalysisDataServiceImpl {lvalue} self, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > name)
  at line 25 in 'New script'
```

**Comment by KarlPalmen** [comment]
Nevertheless, my results log window, did not contain the names of any of the algorithms listed in the test instructions even though it did indicate the ConvolutionFitSquential had successfully completed.

**Comment by ElliotAOram** [comment]
Thanks for letting me know @KarlPalmen . I'll take a look and try and work out why the usage example seems to be failing

**Comment by ElliotAOram** [comment]
The .rst has been updated since the 3.7.1 release to match a change made to ConvolutionFitSequential. The version of the docs from the [nightly build](http://docs.mantidproject.org/nightly/algorithms/ConvolutionFitSequential-v1.html) should work

**Comment by KarlPalmen** [comment]
It worked with the usage example from freshly built documentation.

**Comment by KarlPalmen** [comment]
:shipit:

**Comment by FedeMPouzols** [comment]
@shahrozahmed1 @DavidFair suppresing logging as theyvdo here could be usefulbat some pointvfor the Engg GUI especially con windows if de ser that it is toó slow when it creates the temporada workspaces for plotting, etc.

**Pull request merged**
