### PR TITLE
Expose save_image and replace_workspace to the python api of Instrument Viewer

### PR DESCRIPTION
**Pull request by gvardany**
**Description of work.**
The title says it all.

**To test:**

Run the script below by substituting the input and output directories and run numbers for raw data of your choice. 
Any data should do as long as it is loaded to a MatrixWorkspace with instrument geometry attached.
Finally, check in your specified output directory that the .png images are created and look as nice.

```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
from mantidqt.widgets.instrumentview.api import get_instrumentview
import numpy as np
from time import sleep

def show_instrument_view(runstart, runend, indir, outdir):
    config.appendDataSearchDir(indir)
    Load(Filename=str(runstart),OutputWorkspace=str(runstart))
    iv = get_instrumentview(runstart)
    iv.show_view()
    run = runstart + 1
    while run < runend:
        Load(Filename=str(run), OutputWorkspace=str(run))
        iv.replace_workspace(str(run))
        run += 1
        iv.save_image(outdir+str(run)+'.png')
    
input_directory = '/Volumes/illdata/212/d11/internalUse/rawdata'
output_directory = '/Users/vardanyan/Desktop/thumbnails/'
runstart = 8539
runend = 8560
   
show_instrument_view(runstart, runend, input_directory, output_directory)
```

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DavidFair — CHANGES_REQUESTED** [review]
I'm getting various glibc assertions / segmentation faults from the following:

```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
from mantidqt.widgets.instrumentview.api import get_instrumentview
import numpy as np
from time import sleep

inst = "OSI"

def show_instrument_view(runstart, runend, outdir):
    Load(Filename=f"{inst}{runstart}",OutputWorkspace=str(runstart))
    iv = get_instrumentview(runstart)
    iv.show_view()

    for run in range(runstart, runend):
        Load(Filename=f"{inst}{run}", OutputWorkspace=str(run))
        iv.replace_workspace(str(run))
        iv.save_image(outdir+str(run)+'.png')
    
output_directory = '/tmp/pr/'
runstart = 92762
runend = 92765
   
show_instrument_view(runstart, runend, output_directory)
```

Where OSI data is in the unit test directories
I'll try and get a stack trace too....

**Comment by DavidFair** [comment]
```
#0  futex_abstimed_wait_cancelable (private=<optimised out>, abstime=0x7fff8c7fbcd0, clockid=<optimised out>, 
    expected=0, futex_word=0x5555558f989c <_PyRuntime+1228>) at ../sysdeps/nptl/futex-internal.h:320
#1  __pthread_cond_wait_common (abstime=0x7fff8c7fbcd0, clockid=<optimised out>, 
    mutex=0x5555558f98a0 <_PyRuntime+1232>, cond=0x5555558f9870 <_PyRuntime+1184>) at pthread_cond_wait.c:520
#2  __pthread_cond_timedwait (cond=0x5555558f9870 <_PyRuntime+1184>, mutex=0x5555558f98a0 <_PyRuntime+1232>, 
    abstime=0x7fff8c7fbcd0) at pthread_cond_wait.c:656
#3  0x000055555566dd74 in PyCOND_TIMEDWAIT (us=<optimised out>, mut=0x5555558f98a0 <_PyRuntime+1232>, 
    cond=0x5555558f9870 <_PyRuntime+1184>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/condvar.h:73
#4  take_gil (tstate=0x7fff8d1e7680, ceval=0x5555558f9618 <_PyRuntime+584>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/ceval_gil.h:206
#5  PyEval_RestoreThread (tstate=0x7fff8d1e7680)
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/ceval.c:399
#6  0x00005555555d975f in PyGILState_Ensure ()
    at /home/conda/feedstock_root/build_artifacts/python-split_1620713755437/work/Python/pystate.c:1306
#7  0x00007ffff5b4aa38 in Mantid::PythonInterface::GlobalInterpreterLock::acquire ()
    at ../mantidpr/Framework/PythonInterface/core/src/GlobalInterpreterLock.cpp:32
#8  0x00007ffff5b4aa66 in Mantid::PythonInterface::GlobalInterpreterLock::GlobalInterpreterLock (this=0x7fff8c7fbd9c)
    at ../mantidpr/Framework/PythonInterface/core/src/GlobalInterpreterLock.cpp:49
#9  0x00007fffbed81092 in MantidQt::Widgets::MplCpp::ScalarMappable::setClim (this=0x7fff8d002d50, vmin=..., vmax=...)
    at ../mantidpr/qt/widgets/mplcpp/src/ScalarMappable.cpp:91
#10 0x00007fffbed79d76 in MantidQt::Widgets::MplCpp::MantidColorMap::rgb (this=0x7fff8d002d50, vmin=0, vmax=2965405, 
    value=0) at ../mantidpr/qt/widgets/mplcpp/src/MantidColorMap.cpp:125
#11 0x00007fffbe4710df in MantidQt::MantidWidgets::InstrumentRenderer::resetColors (this=0x7fff8d002cc0)
    at ../mantidpr/qt/widgets/instrumentview/src/InstrumentRenderer.cpp:322
#12 0x00007fffbe470e22 in MantidQt::MantidWidgets::InstrumentRenderer::reset (this=0x7fff8d002cc0)
    at ../mantidpr/qt/widgets/instrumentview/src/InstrumentRenderer.cpp:300
#13 0x00007fffbe400855 in MantidQt::MantidWidgets::InstrumentActor::resetColors (this=0x7fff9b2ac700)
    at ../mantidpr/qt/widgets/instrumentview/src/InstrumentActor.cpp:629
#14 0x00007fffbe3fd4ee in MantidQt::MantidWidgets::InstrumentActor::initialize (this=0x7fff9b2ac700, 
    resetGeometry=false, setDefaultView=true) at ../mantidpr/qt/widgets/instrumentview/src/InstrumentActor.cpp:133
#15 0x00007fffbe4c700a in MantidQt::MantidWidgets::InstrumentActor::qt_static_metacall (_o=0x7fff9b2ac700, 
```

**Comment by gvardany** [comment]
I think you are missing the sleep. Right now it is not properly synchronized, so you have to leave enough time for it to construct/update itself. Any suggestion on how to make it self-synchronized?

**Comment by DavidFair** [comment]
Which parts are racing? I'm tempted to slap a semaphore whilst it's loading/processing before capturing the image as a workaround in the InstrumentViewer

My concern is either users with slow machines (where races become more visible) and people scripting without sleep commands

**Comment by gvardany** [comment]
It's the sleep after replace_workspace. The issue is that `replace_workspace` currently returns immediately, even if the replacement is still happening. It feels like it is run asynchronously, but it should rather hold the GIL and return only when things are up and ready. I totally agree this has to be fixed, as users might script without sleep, and that the amount of sleep time will depend on how slow the machine is. Besides, this issue is currently blocking another widget in development that we want to put in workbench. I'll take a look at the sip layer and try to investigate why the function returns prematurely.

**Comment by gvardany** [comment]
This is the PR that changed the replacement of the instrument actor to its own background thread: https://github.com/mantidproject/mantid/pull/32680/files It looks like that `replace_workspace` just needs to wait for that thread.

**Review by DavidFair — APPROVED** [review]
This works for me and doesn't race now
Nice work, shame it didn't land for 6.3 but at least it's in for 6.4 :+1:

**Pull request merged**
