### PR TITLE
Remove generated file for doxygen

### PR DESCRIPTION
**Pull request by peterfpeterson**
During #30450 doxygen would pickup a generated file from previous PR builds. This removes that file if it is found.

**To test:**

If doxygen builds pass, it is fine.

*There is no associated issue.*

*This does not require release notes* because it is an issue with the build servers only.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by jmborr — COMMENTED** [review]
Is this fix meant to be temporary, meaning it will be removed after a few weeks?

**Comment by peterfpeterson** [comment]
Temporary until most branches no longer contain mantidplot.j

**Comment by jmborr** [comment]
OK, I switched the auto-merge on

**Review by jmborr — DISMISSED** [review]

**Review by jmborr — CHANGES_REQUESTED** [review]
Can you remove the comment of line 63?
```python
# ToDO investigate the relatively large tolerance required for some operative systems, atol=0.05
```
It is a duplicate of the comment in line 68

**Review by jmborr — APPROVED** [review]

**Pull request merged**
