### PR TITLE
Remove resetting of the fit range on changing workspace in elwin

### LINKED ISSUE #24662: Indirect Data Analysis - EndX and StartX go back to default when switching between workspaces
### Expected behavior
When you choose an endX and startX for a spectra, this should remain the endX and startX for that spectra unless you try change it again.

### Actual behavior
The endX and startX for a spectra will go back to the default value when you switch between the workspace you have selected.

### Steps to reproduce the behavior
1.`Interfaces`->`Indirect`->`Data Analysis`->`ConvFit` tab
2. Go to Multiple Input and add the workspaces below
3. For the iris workspace, adjust the startx and endx using the sliders on the miniplot.
4. Switch to the osiris workspace using the combo box above the miniplots
5. Switch back to the iris workspace. The startx and endx have changed back to the default values!

**Data Files**
[Data Files.zip](https://github.com/mantidproject/mantid/files/2817266/Data.Files.zip)

### Platforms affected
All

### PR DESCRIPTION
**Pull request by Harrietbrown**
This PR removes the resetting of the fit ranges when changing the plotted workspace in elwin tab on indirect data analysis.

**Report to:** Spencer 

**To test:**

1. Open indiect data analysis on the Elwin Tab
2. Load data from multiple runs.
3. Change between ploted workspaces from the dropdown menu. The fitting integretion range should stay the same
4. Change the range yourself.
5. Change workspace, the range should remain as what you set it as.

Fixes #24662 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by robertapplin — CHANGES_REQUESTED** [review]
The good news is that the plot ranges seem to work. The bad news is I am getting a crash when I click `Run` . Do you get this?

**Comment by Harrietbrown** [comment]
I don't get any crash, is there an error that comes with it?

**Comment by robertapplin** [comment]
> I don't get any crash, is there an error that comes with it?

No error message, just a crash. All I did was load this data in Elwin and clicked Run: (on windows)

[ElwinMultipleFiles.zip](https://github.com/mantidproject/mantid/files/5414201/ElwinMultipleFiles.zip)

**Comment by Harrietbrown** [comment]
I can't replicate the crash.

**Comment by robertapplin** [comment]
> I can't replicate the crash.

I have just tried again and I can't either even though I previously could replicate it...

Your changes don't look like they could cause a crash, so I am happy to just assume the crash was from a bad build or something.

**Review by robertapplin — APPROVED** [review]
Looks good 👍

**Comment by martyngigg** [comment]
I too could not produce a crash and I agree that it seems unlikely these changes would cause that.

**Comment by Harrietbrown** [comment]
Martin can't replicate it either. Not sure where to go from here.

**Pull request merged**
