### PR TITLE
Deadtime from table workspace not working

### LINKED ISSUE #26899: Deadtime table selection from ADS not working
There are currently two ways in which a deadtime table can be specified. Either from the current data file or from a specified table workspace. Currently when a table workspace is selected to get the deadtime from this selection is ignored and the value from the current file is used instead.

### PR DESCRIPTION
**Pull request by ciaranightingale**
When selecting a table workspace or other file for the deadtime, the correction would not be correct and the GUI would revert back to from other file.

**To test:**
- Open the muon analysis 2 interface
- Select MUSR as your instrument 
- load run 62260
- change the deadtime combo box to from table workspace
- change the dead time workspace combo box that has appeared to the only valiable workspace
- check that the dead time combo box still shows from table workspace
- in the ads, expand the workspace 62260 and right click on the counts
- show the workspace history
- scroll to the bottom and click on the MuonPreProcess which is closest to the bottom
- check that the deadtimetable is the same as the one selected in the muon interface

Fixes #26899.
---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
have you rebased this branch? It has lots of failing tests

**Comment by RichardWaiteSTFC** [comment]
The unit test is still not working - ready to review when it's fixed.

**Comment by AnthonyLim23** [comment]
I don't think we shouldn't need to change the failing test. It looks like the test changes the deadtime selection to table ws and that is not being updated.

**Review by RichardWaiteSTFC — APPROVED** [review]
Passes the test provided

**Pull request merged**
