### PR TITLE
Enable and fix all pedantic warnings

### PR DESCRIPTION
**Pull request by quantumsteve**
This fixes [#11400](http://trac.mantidproject.org/mantid/ticket/11400)

This pull request adds the -pedantic flag to clang and some gcc builds (some warnings remain with gcc 4.4). I also removed "-Wno-unused-result" from gcc 4.4 since it doesn't appear to be valid with that version.

testing: Code review (one may want to locally revert commit 9fd8d1b, which is fixes ~600 extra ; warnings) and check that no new warnings appear on the build servers.

### CODE REVIEW

**Comment by quantumsteve** [comment]
retest this please

**Comment by eXeC64** [comment]
@quantumsteve I've created a commit that fixes the `extra ';'` warnings. How would you like me to send it to you? I can either send you a `.patch`, or push the commit straight to this branch.

**Comment by quantumsteve** [comment]
skip ci

**Comment by quantumsteve** [comment]
retest this please

**Comment by quantumsteve** [comment]
previous commit removes -pedantic from rhel6. I tried building on another rhel6 machine and don't see the warnings listed on the build server.

**Comment by quantumsteve** [comment]
retest this please

**Pull request merged**
