### PR TITLE
Fix unused-variable warning in MuonFitDataSelector

### PR DESCRIPTION
**Pull request by samueljackson92**
**Description of work.**
Spotted this warning while building master.

**To test:**
 - Code review
 - Compile & check warning is gone.

_No associated issue_

Does this update require release notes?
- [ ] Yes
- [x] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
git cannot find it

**Comment by samueljackson92** [comment]
Cannot find what?

**Comment by AnthonyLim23** [comment]
the branch

**Comment by samueljackson92** [comment]
It's a branch on my mantid fork. The following should work to get a local copy:
```
git fetch git@github.com:theirusername/reponame.git theirbranch:ournameforbranch
```

**Comment by AnthonyLim23** [comment]
have I made a mistake? 

```$ git fetch git@github.com:samueljackson92/fix-unused-variable-warning-mufitdat.git fix-unused-varuiable-warning-mufitdata:sam
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.```

**Review by AnthonyLim23 — APPROVED** [review]
looks good

**Pull request merged**
