### PR TITLE
Scripts for fitting benchmarks (and a system test)

### LINKED ISSUE #13782: Add system test: EnggFittingTest
Related to/spawning from  #13348. This is to have a few simple fitting examples extracted from Engg algorithms. It should also help in making some required changes in Engg fitting more incremental and easy to track.

A few cases to start with:
- fit the bank 1 and bank 2 summed vanadium curves with a spline
- fit one or a handful of peaks for individual spectra. Use PseudoVoigt peak functions- this can be useful to compare against Gaussian peaks as traditionally used in Engg algorithms.
- Use FindPeaks + fit the multiple peaks found on focused data (bank1, bank2)

### LINKED ISSUE #15952: Add pseudo-system test for fitting/minimization benchmarks
Related to #15078, add code that can rank different minimizers according to how close they get to a "certified" solution for different test problems. One/the metric can be the chi^2.
This test is not a normal system test and it should not do any assert on the fitted parameters.

Test problems:
- The NIST nonlinear regression benchmarks http://itl.nist.gov/div898/strd/general/dataarchive.html
  (3 of which are currently included
- As a bonus several problems from the CUTEst set http://www.cuter.rl.ac.uk/Problems/mastsif.html could be added as well. 

All these tests must have:
- Predictor/response sample data. A file per test, included as test data file, sounds sensible.
- A function formula to minimize that can be parsed or converted into muparser format.
- Initial values for the function parameters. NIST tests usually provide two alternatives.
- "Certified" values, and the resulting residual/goodness of fit.
- Must be of class "SU**" in the CUTE classification. That is:
  - the objective function is a sum of squares
  - the problem is unconstrained

Because all these problems do not have error values the initial step would be to compare them with the `Unweighted least squares` cost function. They would ideally have errors but that's not the usual case. For that we have the [WeightedLeastSquaresTest](https://github.com/mantidproject/mantid/blob/master/Testing/SystemTests/tests/analysis/WeightedLeastSquaresTest.py) - related to #15028.

### PR DESCRIPTION
**Pull request by FedeMPouzols**
Adds scripts that produce the comparison and tables used for the concept page on fitting  minimizers (#17603). This also adds a system test that runs the scripts to evaluate all the tests problems that we currently have with all the minimizers (except FABADA). 

Note this PR has many files because of the test files added under `Testing/Data/SystemTest/FittingTestProblems`

**To test:**

- Code review
- Check that the systemtest works

```
./systemtest  -R FittingBenchmarks
```

(or if you don't want a flood of warnings:

```
./systemtest  -l error -R FittingBenchmarks
```
(This not needed for testing this ticket: The files for end users to be able to run the benchmark scripts without needing the system tests infrastructure are here (at ISIS): \olympic\Babylon5\Public\fedemp\fitting\FittingTestData.zip))

Fixes #15952.
Also fixes #13782.

Release notes were updated.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Anders-Markvardsen** [comment]
Hi @FedeMPouzols hope good start in Germany:) 

For this pull request, I believe WISH1770_calibration_tube3.nxs is missing - any change you could add it?

When running is separate, i.e. not as a systemtest, is it by purpose that the data_files folder of the Neutron_data is required to be in your path? Mainly that is better than hardcoding - but just wonder if you had thought about this?

Something unrelated to this - did you see my slack message

**Comment by FedeMPouzols** [comment]
@Anders-Markvardsen Re the missing `WISH1770_calibration_tube3.nxs` file, I'd expect it is included in `\olympic\Babylon5\Public\fedemp\fitting\FittingTestData.zip`, and if so that's probably the best way to make sure that we use exactly the same data.

**Comment by Anders-Markvardsen** [comment]
@FedeMPouzols Unfortunately it isn't. However, I have started to work on the file @samueljackson92 emailed (which he correctly chopped for the one example I gave him to a small region, not realising that your set contains 8 fitting tests againsts this dataset). Sam have choosen WISH, run 17701, panel 103, tube 2. However, tube 3 appears to be closer to what you had in mind. If even not quite that panel or tube, unless you let me know otherwise i will go for that WISH dataset. 

Below is picture of the Lebenbart-marquet fit to the first peak of this tube 3 dataset:

capture

**Comment by samueljackson92** [comment]
@Anders-Markvardsen yes it was not clear from the script whether you were fitting to 8 peaks or to just one. The fragment of script you sent looked like it could be cropped because you have a ```startx``` and ```endx``` for the fit window. Apologies, I think using tube 2 instead of 3 was a typo on my part.

**Comment by Anders-Markvardsen** [comment]
@FedeMPouzols and @samueljackson92 checked the above referred wish panel 103 tube 3 and it does reproduce the numbers on e.g. http://docs.mantidproject.org/nightly/concepts/FittingMinimizersWeightedComparisonDetailed.html#minimizers-weighted-comparison . will use and upload htis file

**Comment by FedeMPouzols** [comment]
@Anders-Markvardsen: I gave this a go to see if all the fits would run without issues on the build servers, but unfortunately it seems that I'm no longer allowed to push to this repo. I've attached a patch file (`git patch...`) with the fixes required by flake8 (I think all the remaining warnings are trivial). Nice to see this ready.

[0001-remove-some-remaining-flake8-warnings-spaces-re-1595.txt](https://github.com/mantidproject/mantid/files/614291/0001-remove-some-remaining-flake8-warnings-spaces-re-1595.txt)

**Comment by Anders-Markvardsen** [comment]
@FedeMPouzols thanks for the patch

**Comment by Anders-Markvardsen** [comment]
:shipit: 

(note there remain some issues with the WISH tests but they will be fixed in #18151)

**Pull request merged**
