### PR TITLE
Fix crash in VSI ThreeSlice mode when including latex for axis labels

### LINKED ISSUE #13080: VSI ThreeSlice mode crashes when including latex for axis labels
The new version of ParaView allows the axis labels to be customised using Latex. The latex is processed through Python using `matplotlib`, which requires ParaView to be able to execute arbitrary Python code.

This can be reproduced by editing [Common.cpp](https://github.com/mantidproject/mantid/blob/715f81b3ca09ed0c4110f673a2cb4118207b5e80/Code/Mantid/Vates/VatesAPI/src/Common.cpp#L20) and adding the line
```cpp
    title += "$\\AA^-1$";
```

### PR DESCRIPTION
**Pull request by martyngigg**
Fixes #13080

**Tester**
This involved a few changes to how the embedded Python in MantidPlot works with so there is a bit to test. I have compiled a list of scenarios below.

There is nothing to add to the release notes or documentation here.
## Clean open/close

Start and close MantidPlot immediately - no crash or strange behaviour
## Run Script In Thread
- Start MantidPlot
- Open Script editor
- Run some python code
- Close MantidPlot
## Run Script In Main Thread
- Start MantidPlot
- Open Script editor
- Select Execute->Mode->Serialised
- Run some python code
- Close MantidPlot
## Run Two Scripts at Once
- Start MantidPlot
- Open Script editor
- Run script in two separate tabs (change 1->2 in second):

``` python
import time
counter = 0
while counter < 10:
    print "Thread 1"
    time.sleep(5)
    counter += 1

print "done 1"
```
- Wait for completion and close MantidPlot
## VSI with LaTeX labels
- This requires a code edit to visualise at the moment. In https://github.com/mantidproject/mantid/blob/715f81b3ca09ed0c4110f673a2cb4118207b5e80/Code/Mantid/Vates/VatesAPI/src/Common.cpp#L20 add `title += "$\\AA^-1$";`
- Compile
- Start MantidPlot
- Open Script editor
- Run:

``` python
CreateSimulationWorkspace(Instrument='MARI', BinParams='-11,0.05,11', OutputWorkspace='mari')
AddSampleLog(Workspace='mari', LogName='ei', LogText='12.5', LogType='Number')
ConvertToMD(InputWorkspace='mari', QDimensions='Q3D', OutputWorkspace='mdws')
```
- Right click on ''mdws" and click open VSI
- Switch to Three Slice view and see latex labels
- Close MantidPlot
## VSI while running Python script
- Start MantidPlot
- Open Script editor
- Use the script from "VSI with LaTeX labels" and create the MD workspace 
- Start the script from "Run Two Scripts at Once"
- Open the VSI and switch to the three-slice view
- Close MantidPlot
## Run a Python Algorithm From Script and GUI
- Start MantidPlot
- Open Script editor
- Add the system test data to the path
- Run the script:

```
LoadVesuvio(Filename='14188-14189', SpectrumList='135-142', SumSpectra=True, OutputWorkspace='test')
```
- Do the same from the GUI.
- Close MantidPlot

### CODE REVIEW

**Comment by OwenArnold** [comment]
@martyngigg  windows build still failing to link.

**Comment by martyngigg** [comment]
@OwenArnold Thanks, I'll take a look.

**Comment by OwenArnold** [comment]
Looks good to me. No issues on OSX 10.10

**Comment by picatess** [comment]
Tested:
1. Clean open/close : Pass
2. Run Script In Thread : Pass
3. Run Script In Main Thread : Pass
4. Run Two Scripts at Once : Pass
5. VSI with LaTeX labels : Pass   for "$\\AA^{-1}$"
6. VSI while running Python script : Pass
7. Run a Python Algorithm From Script and GUI : Pass

All tests were fine on Windows 7

**Pull request merged**
