### PR TITLE
Update ParaView to v5.3.0

### PR DESCRIPTION
**Pull request by quantumsteve**
Description of work.

This updates Mantid to use [ParaView 5.3.0](https://blog.kitware.com/paraview-5-3-0-release-notes/). It also updates vtkMDHWSignal array to use the newer [data array layouts](https://blog.kitware.com/new-data-array-layouts-in-vtk-7-1/) in VTK. In order to see a performance improvement, the header needs to be passed to VTK at compile time.

**To test:**

1. View the updated [build instructions](https://www.mantidproject.org/Building_VATES). Note that `vtkMDHWSignalArray.h` is now in the paraview-build repository and must be available to ParaView during compilation.
2. Build Mantid with -DMAKE_VATES=ON and -DParaView_DIR=<your ParaView build directory>.
3. Try viewing a MDHistoWorkspace and a MDEventWorkspace in the VSI.

There is no GitHub issue associated with this pull request.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by quantumsteve** [comment]
@mantidproject/gatekeepers Please notify developers before merging, as this **WILL** break the developer environment for anyone building with `-DMAKE_VATES=ON`.

**Comment by rosswhitfield** [comment]
The first file I tried Vates doesn't calculate the correct signal ranges, it gets instead [1e+299, -1e+299]. This was the file `/SNS/CORELLI/IPTS-17467/shared/20161026_CaZrO2/CaZrO2_300K_symm_norm_cc_wbkg.nxs`

This works on master.

**Comment by quantumsteve** [comment]
@rosswhitfield I pushed a change the fix the issue with normalization that you observed.

**Comment by rosswhitfield** [comment]
:+1: Works now! LGMT :frog:

**Comment by peterfpeterson** [comment]
@rosswhitfield and @AntonPiccardoSelg should mark their reviews as "accepted" if this is ok.

**Review by rosswhitfield — APPROVED** [review]

**Comment by rosswhitfield** [comment]
:high_heel: :rice_ball: :shipit: :telephone_receiver:

**Pull request merged**
