### PR TITLE
Multi Dataset Fitting interface beta bugs

### LINKED ISSUE #16430: Multi-dataset fitting: misc beta bugs
Beta-test bug from Jon Taylor.

"Uses the term workspace index in the UI not spectrum  number but has all spectra checkbox
 fitting will allow a tile plot for any number if spectra to be generated (export all plots). which crashes mantid for say 285 spectra
initiating the fit makes fit algorithm unresponsive with 285 spectra and simultaneous fit selected
editing fit parameters shrinks text edit window in a way that makes it impossible to read

"Plot guess also plots the fit in the ui when the algorithm completes"

You may need to contact Jon Taylor for further information.

### PR DESCRIPTION
**Pull request by shahrozahmed1**
**Description of work.**

This PR should fix few bugs found on the Multi-Dataset Fitting interface. 
It was recommended that I should not change the term `workspace index` to anything else for the moment as it is not spectrum number displayed within the table. _Fit parameters shrinking text_ seems to be a platform issue as it seems to work fine on Windows. With help of @Jon-Taylor also discovered that `Edit Parameter Values` dialog doesn't seem to pop-up on Mac. -> Separate issue should be created for this. 
- Fixes bug with `Remove` button 
- Combobox below is now sorted in ascending order
- Plot Guess curve always plotted under fitted curve
- `Fit` button disabled during Fitting process
- pop-up question when `Export All Plot` is clicked and more than 20 spectra in table
- pop-up question when fitting simultaneous  and more than more than 20 spectra in table
- pop-up question when fitting sequentially and more than more than 100 spectra in table
  - if desired to continue fitting the settings will be remembered for current session

**To Test:**
Load -> `MUSR00015189` or any preferred data 
Go To: `Interfaces/Multi-dataset fitting` interface
`Add Workspace` & click `All Spectra` & `OK` (128 spectra should be added)
Once table loaded, Check that workspace/s can deleted be removed more freely
Check `combobox` below table is now sorted in ascending order
Right/Left button function more appropriately
Add a Function e.g: (ExpDecay)
Click `Fit` when `Fitting` property set to `Simultaneous`
Valid pop message should be displayed
Check same with `Sequential`
Check that it also remembers setting for session if `Yes` clicked

Reduce the number of spectra and `Fit` a function
Check that Plot Guess is always plotted behind `Fitted` Curve

To plot Fitted curve for `Sequential` -> `Create Ouput` property needs to be set as `true`

Fixes #16430.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
##Problem:

1. set fit to be sequential
1. have output property blank
1. click fit
1. you get an error message that the ouput is blank
1. Fit button does not re-eneable

**Comment by NickDraper** [comment]
All good apart from that

**Comment by shahrozahmed1** [comment]
@NickDraper Last commit should enable the button when `Fitting` fails.

**Comment by NickDraper** [comment]
Sorted now, all good :shipit:

**Pull request merged**
