### PR TITLE
Fix TOPAZ test for gsl2

### LINKED ISSUE #16683: Fix TOPAZ tests that fail with GSL2
Tests failing with GSL2: http://builds.mantidproject.org/view/All/job/master_clean-archlinux/405/#showFailuresLink

* CrystalTest.OptimizeCrystalPlacementTest.test_basic

### PR DESCRIPTION
**Pull request by VickieLynch**
OptimizeCrystalPlacement test was failing with gsl2.
The initial goniometer angles were perturbed to 57.6, 136.1, -0.6
The angles were optimized toward 60.2, 135.3, 0.15
With gsl1 optimized angles were 60.1, 135.0, 0.01
With gsl2 optimized angles were 59.2, 134.5, -0.7
Delta for test had to be increased from 0.3 to 1.0 for gsl2.

**To test:**

Check that test passes for OptimizeCrystalPlacement

Fixes #16683 

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by rosswhitfield** [comment]
I'm finding that this test still fails occasionally when run by itself `ctest -V -R OptimizeCrystalPlacement`. But fails consistently when run with the other tests `ctest -j8 -R CrystalTest`.
```
test 1204
    Start 1204: CrystalTest_OptimizeCrystalPlacementTest

1204: Test command: /usr/bin/cmake "-E" "chdir" "/home/rwp/mantid/release/bin/Testing" "/home/rwp/mantid/release/bin/CrystalTest" "OptimizeCrystalPlacementTest"
1204: Test timeout computed to be: 300
1204: Running 3 testsLoadIsawPeaks-[Notice] LoadIsawPeaks started
1204: LoadIsawPeaks-[Notice] LoadIsawPeaks successful, Duration 2.94 seconds
1204: LoadIsawUB-[Notice] LoadIsawUB started
1204: LoadIsawUB-[Notice] LoadIsawUB successful, Duration 0.00 seconds
1204: OptimizeCrystalPlacement-[Notice] OptimizeCrystalPlacement started
1204: OptimizeCrystalPlacement-[Notice] Number initially indexed = 277 at tolerance = 0.25
1204: OptimizeCrystalPlacement-[Notice] Output Status=success
1204: OptimizeCrystalPlacement-[Notice] Number indexed after optimization= 277 at tolerance = 0.25
1204: OptimizeCrystalPlacement-[Notice] OptimizeCrystalPlacement successful, Duration 0.30 seconds
1204: OptimizeCrystalPlacement-[Notice] OptimizeCrystalPlacement started
1204: OptimizeCrystalPlacement-[Notice] Number initially indexed = 150 at tolerance = 0.25
1204: OptimizeCrystalPlacement-[Notice] Output Status=success
1204: OptimizeCrystalPlacement-[Notice] Number indexed after optimization= 277 at tolerance = 0.25
1204: OptimizeCrystalPlacement-[Notice] OptimizeCrystalPlacement successful, Duration 0.13 seconds
1204: Fit finished. Status=success
1204: Fit finished. Status=success
1204: 
1204: In OptimizeCrystalPlacementTest::test_basic:
1204: /home/rwp/mantid/Framework/Crystal/test/OptimizeCrystalPlacementTest.h:137: Error: Expected (d == 0) up to 1.0 (1.0000), found (1.0786 != 0)
1204: OptimizeCrystalPlacement-[Notice] OptimizeCrystalPlacement started
1204: OptimizeCrystalPlacement-[Notice] Number initially indexed = 52 at tolerance = 0.25
1204: OptimizeCrystalPlacement-[Notice] No Goniometer Angles relative to the tilted Goniometer will be 'changed'
1204: OptimizeCrystalPlacement-[Notice] Output Status=success
1204: OptimizeCrystalPlacement-[Notice] Number indexed after optimization= 277 at tolerance = 0.25
1204: OptimizeCrystalPlacement-[Notice] OptimizeCrystalPlacement successful, Duration 0.03 seconds
1204: Fit finished. Status=success
1204: .OptimizeCrystalPlacement-[Notice] OptimizeCrystalPlacement started
1204: OptimizeCrystalPlacement-[Notice] Number initially indexed = 277 at tolerance = 0.25
1204: OptimizeCrystalPlacement-[Notice] No Goniometer Angles will be 'changed'
1204: OptimizeCrystalPlacement-[Notice] Output Status=success
1204: OptimizeCrystalPlacement-[Notice] Number indexed after optimization= 277 at tolerance = 0.25
1204: OptimizeCrystalPlacement-[Notice] OptimizeCrystalPlacement successful, Duration 0.15 seconds
1204: Fit finished. Status=success
1204: .
1204: Failed 1 of 3 tests
1204: Success rate: 66%
```

**Comment by rosswhitfield** [comment]
This passes for me now. LGTM :shipit:

**Comment by rosswhitfield** [comment]
Actually I still see this fail randomly. If I run `ctest -V -R CrystalTest_OptimizeCrystalPlacement` multiple times it eventually fails and every time with different results.
```
1204: In OptimizeCrystalPlacementTest::test_basic:
1204: /home/rwp/mantid/Framework/Crystal/test/OptimizeCrystalPlacementTest.h:137: Error: Expected (d == 0) up to 1.1 (1.1000), found (1.2182 != 0)
```
```
1204: In OptimizeCrystalPlacementTest::test_basic:
1204: /home/rwp/mantid/Framework/Crystal/test/OptimizeCrystalPlacementTest.h:137: Error: Expected (d == 0) up to 1.1 (1.1000), found (1.5062 != 0)
1204: /home/rwp/mantid/Framework/Crystal/test/OptimizeCrystalPlacementTest.h:137: Error: Expected (d == 0) up to 1.1 (1.1000), found (1.4027 != 0)
```
```
1204: In OptimizeCrystalPlacementTest::test_basic:
1204: /home/rwp/mantid/Framework/Crystal/test/OptimizeCrystalPlacementTest.h:137: Error: Expected (d == 0) up to 1.1 (1.1000), found (-2.0759 != 0)
```
```
1204: In OptimizeCrystalPlacementTest::test_basic:
1204: /home/rwp/mantid/Framework/Crystal/test/OptimizeCrystalPlacementTest.h:137: Error: Expected (d == 0) up to 1.1 (1.1000), found (1.4606 != 0)
1204: /home/rwp/mantid/Framework/Crystal/test/OptimizeCrystalPlacementTest.h:137: Error: Expected (d == 0) up to 1.1 (1.1000), found (1.4452 != 0)
```

@AndreiSavici Can you confirm?

**Comment by rosswhitfield** [comment]
This will continuously run the test until it fails
```sh
echo; while [ $? == 0 ]; do ctest -V -R OptimizeCrystalPlacementTest; done
```

**Comment by VickieLynch** [comment]
I have gsl 2.0 installed on my rhel 7 machine and am writing the results of the test that fails in gsl2 and they are exactly the same every time when running your continuous loop.  Even this does not fail:
echo; while [ $? == 0 ]; do ctest -j24 -R CrystalTest; done

I will try gsl 2.1

**Comment by VickieLynch** [comment]
I downloaded gsl 2.1 from ftp://ftp.gnu.org/gnu/gsl/ and installed after deleting 2.0.  Same consistent results with no failures.

**Comment by rosswhitfield** [comment]
Maybe it's not the GSL version but the newer compiler version GCC 5 that causes the problem. Andrei can you try?

**Comment by VickieLynch** [comment]
Andrei sees the answer changing with Ubuntu gsl 2.1

**Comment by rosswhitfield** [comment]
Please revert #17245 in this branch. `git revert 2dbc26f` will do it.

**Comment by rosswhitfield** [comment]
:+1: This look good now and passes for me using GSL `2.2.1`. :shipit:

@AndreiSavici can you check Ubuntu 16.04?

**Comment by AndreiSavici** [comment]
Passed for me on Ubuntu 16.04.

**Pull request merged**
