### PR TITLE
Archive search for installer testing

### PR DESCRIPTION
**Pull request by peterfpeterson**
ORNL has the desire to run more system tests that are normally skipped during the nightly builds. Adding `--archivesearch` as an option to the installer tests (and passed on to system tests) is all that is necessary to improve the discovery of bugs that are only found by more expensive system tests on more realistic data. Once setup, there will be an extra job run on [baldrick](http://builds.mantidproject.org/computer/ornl-baldrick/) downstream of [master_clean-rhel7](http://builds.mantidproject.org/job/master_clean-rhel7/).

I apologize for making the code python3 compatible as well in the same PR. The changes that matter are in `InstallerTests.py#L23` and `systemtests`.

**To test:**

This is mostly a code review.

*There is no associated issue.*

*Does not need to be in the release notes* as it affects testing rather than something that directly is seen by users.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by rosswhitfield** [comment]
I pointed the [master_systemtests-ornl](http://builds.mantidproject.org/job/master_systemtests-ornl/2/) build to this branch, lets see what happens.

**Comment by rosswhitfield** [comment]
And nope
```
13:26:38 + python /home/builder/jenkins-linode/workspace/master_systemtests-ornl/Testing/SystemTests/scripts/InstallerTests.py -o -d /home/builder/jenkins-linode/workspace/master_systemtests-ornl/build '"--archivesearch"'
13:26:38 usage: InstallerTests.py [-h] [-d directory] [-n] [-o] [-R regexp]
13:26:38                          [--archivesearch] [-l level]
13:26:38 InstallerTests.py: error: unrecognized arguments: "--archivesearch"
```

**Comment by rosswhitfield** [comment]
I changed `EXTRA_ARGS="--archivesearch"` to `EXTRA_ARGS=--archivesearch` and it's running [now](http://builds.mantidproject.org/job/master_systemtests-ornl/3/)

**Comment by rosswhitfield** [comment]
It doesn't appear to be working. Despite it taking significantly longer ~8 hours to run it still skipped system tests that should now run. _e.g._ `SNAPRedux` which should have now found the **requiredFiles** `"SNAP_34172_event.nxs"` which exists at `/SNS/SNAP/IPTS-15412/0/34172/NeXus/SNAP_34172_event.nxs`

**Comment by rosswhitfield** [comment]
The problem is the `builder` account doesn't have permission to read the data, it's not in the right groups.

**Comment by peterfpeterson** [comment]
I don't know if this PR will produce a fix for the permission issue. The two solutions that I have off the top of my head are to give `builder` access to *all* data and to change the user to `snsdata`. The former seems like the better idea since it would only have read access.

**Comment by rosswhitfield** [comment]
This all looks good and works, sorting out permissions of the `builder` account on the build servers is a different issue. :shipit:

**Pull request merged**
