### PR TITLE
Refactoring new Progress to make_unique<Progress>

### LINKED ISSUE #17590: Refactoring new Progress to Kernel::make_unique<Progress>
Work on refactoring from [Maintenance](https://github.com/mantidproject/documents/blob/master/Project-Management/TechnicalSteeringCommittee/reports/MaintenanceTasks.md) document:
- Replace new Progress with Kernel::make_unique<Progress> in the ~~35~~ 40 files that do it

File list (from grep 'new Progress'):
- AlignAndFocusPowder
- BinaryOperation
- CalculateFlatBackground
- CompareWorkspaces
- ConvolveWorkspaces
- CrossCorrelate
- DiffractionFocussing2
- FilterEventsByLogValuePreNexus
- FindPeaks
- FindPeaksMD
- LoadEventNexus
- ~LoadEventPreNexus~ (file was not found, seems it has been removed due to version 2 - 19/06/2017)
- LoadEventPreNexus2
- LoadGSS
- ~LoadInstrument~ (no `new Progress` was found, seems it was changed to a local `Progress`)
- LoadMD
- LoadTOFRawNexus
- MergeMDFiles (fixed possible raw Progress pointer leak)
- RemoveLowResTOF
- SaveMD
- SaveNexusProcessed
- SaveToSNSHistogramNexus
- SliceMD
- SmoothNeighbours
- SofQW
- UnwrapMonitor
- UnwrapSNS
- VesuvioCalculateGammaBackground

### PR DESCRIPTION
**Pull request by dtasev**
### Description of work.

Refactored file list from #17590 to use `Kernel::make_unique<Progress>` instead of `new Progress`. Some of the files were also refactored to follow the Mantid code style/naming conventions.

Special Cases:
- [Framework/MDAlgorithms/src/PlusMD.cpp](https://github.com/mantidproject/mantid/compare/17590_refactor_new_progress_to_make_unique_progress#diff-9a78f45bbfe41b6bcf01eeab0c0aea48R95)
- [Framework/MDAlgorithms/src/MinusMD.cpp](https://github.com/mantidproject/mantid/compare/17590_refactor_new_progress_to_make_unique_progress#diff-9a78f45bbfe41b6bcf01eeab0c0aea48R95)

Those 2 classes still use `new Progress` because it is passed into a `ThreadPool` and is then freed in the destructor of the `ThreadPool`, thus making `std::unique_ptr` cause a Segfault. If any other way to handle the two classes is proposed I will go ahead and implement it, otherwise they will be left as they are in this PR.

Another special case is AlignAndFocusPowder as it **does not** have a unit test. Testing for that must be done manually! This is covered by issues #17840 (unit tests), #17841 (wrong documentation)
### To test:
- Run unit tests for each of the files (except AlignAndFocusPowder)
  (LoadGSSTest is known to cause random failures in one of its tests)
- Run manual tests for AlignAndFocusPowder

Fixes #17590.

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by quantumsteve** [comment]
Can `unique_ptr<Progress>` be replaced by `Progress` in some (all?) of these cases? Is the extra indirection worthwhile?

**Comment by DimitarTasev** [comment]
Possible, I do remember seeing progress being used only locally in some algorithms, I'll take a look

**Comment by SimonHeybrock** [comment]
@quantumsteve I think the reason for the dynamic allocation is that the length of the progress bar is not know in the constructor, since it depends on the size of the workspace obtained from the properties.

@DimitarTasev Regarding `ThreadPool`: Why not pass a `unique_ptr` to transfer ownership?

**Comment by DimitarTasev** [comment]
@quantumsteve @SimonHeybrock Is a member `unique_ptr<Progress> m_progress` variable something the algorithms necessarily need? Is it better to just have a local `Progress progress` (if possible)? 

I'm thinking a good criteria would be to see in how many functions the progress report is used, if it's all over the place then I think a member variable would be nicer, as to not pollute the parameter lists unnecessarily, but if it's used in just the main exec function, it would be cleaner with a local progress.

**Comment by SimonHeybrock** [comment]
@DimitarTasev Yes, I agree. I think actually many algorithms do it like that.

**Comment by DimitarTasev** [comment]
Unassigning myself from this for now, as it's not an issue I can prioritise, hence I'm leaving it open if someone else is free to finish it off. I plan to pick it up at a later point and finish it for 3.9

**Comment by DimitarTasev** [comment]
Closing to not pollute the PR pool, as this is not an active PR

**Pull request closed without merging**
