### PR TITLE
ISIS Indirect data reduction: Change default grouping option and add validation

### LINKED ISSUE #22858: Indirect data reduction fails
* You will need : `IRS21360.raw ` from the ISIS-Data set
* Open `Indirect` > `Data Reduction`
* Settings:
    * `Instrument` : `IRIS`
    * `Analyser` : `Graphite`
    *  `Reflection` : `002`
    *  `Run Files` : `21360` - note, if the file location is not on the Mantid path, then browse manually
    *  Click `Run`

```
No registered converter was able to produce a C++ rvalue of type class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > from this Python object of type NoneType
  at line 257 in 'C:/Users/BTR75544/nightly/MantidInstall/plugins/python/algorithms\WorkflowAlgorithms\ISISIndirectEnergyTransfer.py'
  caused by line 590 in 'C:/Users/BTR75544/nightly/MantidInstall/scripts/Inelastic\IndirectReductionCommon.py'
  caused by line 670 in 'C:/Users/BTR75544/nightly/MantidInstall/scripts/Inelastic\IndirectReductionCommon.py'
Unknown error starting next batch algorithm
Got error from algorithm "ISISIndirectEnergyTransfer"
Stopping batch algorithm because of execution error
```

### PR DESCRIPTION
**Pull request by ElliotAOram**
**Description of work.**

* Added validation to the Indirect data reduction gui to ensure custom grouping is not empty
* Changed the default grouping to be individual meaning users don't have to input into that field unless they physically change the detector grouping option.

**Report to:** @brandonhewer 

**To test:**

* Open mantid plot
* Open the Indirect data reduction interface (Interfaces > Indirect > Data Reduction)
* Observe that in the `Detector Grouping` section, the mode should default to `Individual`
* Enter the run number `21360` (this can be found in the unit test data) into the `Run Files` box
* Click run and see that a workspace is created with 50 spectra (spectrumNumber 3-53)
* Change the `Detector Grouping` mode to `Custom`.
* Leave the field empty and click `Run` 
* See that a dialog box with an appropriate error message is produced.
* Enter a value into the custom grouping box e.g. `0-10`
* Observe that the workspace that has been produced (it will have overwritten the previous one stored in the ADS) contains 10 spectra.

Fixes #22858

*Does not need to be in the release notes as this was  a bug introduced during this development cycle*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by SpencerHowells** [comment]
@ElliotAOram @keeto In the Custom Grouping, input of 0-10 should give 1 spectrum adding detectors 0-10. A better test perhaps would be 0-5,6-10 which should give 2 spectra. Doing a Show Detectors will check this. Using Groups option should also have the number of spectra the number of Groups.

**Comment by SpencerHowells** [comment]
@ElliotAOram @keeeto Oops! Detector numbers start at 3! So test with 3-5,6-10 say.

**Comment by SpencerHowells** [comment]
@ElliotAOram @keeeto Grouping File option doesn't work either. I'm using this map file which I've renamed from test.map to insert.
[test_map.txt](https://github.com/mantidproject/mantid/files/2188163/test_map.txt)

**Comment by ElliotAOram** [comment]
@SpencerHowells in this case this issue is more serious than I first thought. The functionality of the custom grouping is incorrect.  looking at the original PR i don't think it was implemented correctly the first time around. 

So to confirm the custom detector grouping should do the following:
```
input: 3,4,6,7,8,9,10,11,12,13
output: Workspace containing 10 spectra from 3-13
```
```
input: 3-13
output: Workspace containing a single spectra that sums the 10 spectra together
```
```
input: 0-2
output: This should fail as it's outside the detector range 
```

**Comment by ElliotAOram** [comment]
I'll also take a look at the map file as well. what are the expected/allowed extensions for the map file?

**Comment by SpencerHowells** [comment]
@ElliotAOram The faults have indeed been there for a long time. Your comments about the grouping are correct. According to the Algorithms wiki there are 2 forms of map file. The simplest is the text version I sent and the default extension is .map. There is also an xml version which, while better to read & understand, is probably too complicated for our users. Our gui Browse searches for .map.

**Comment by ElliotAOram** [comment]
Thanks @SpencerHowells I'll look into this today and see what I can do

**Comment by ElliotAOram** [comment]
This branch is just the requirements to fix the problem seen by @AnthonyLim23 
The additional changes suggested by @SpencerHowells can be found on [this branch](https://github.com/mantidproject/mantid/tree/22858-allow-add-functionality-in-cutom-grouping)

**Comment by SpencerHowells** [comment]
@ElliotAOram The map file is working for me now.

**Comment by ElliotAOram** [comment]
Build server failures are not related

**Review by keeeto — APPROVED** [review]
This passes all of the technical testing.

One minor point, in the custom range I can enter a detector number above the numbers in the file, prompting a failure. I think that it has knowledge of the maximum detector number so should be able to prevent me from running this.

**Pull request merged**
