### PR TITLE
Indirect - Refactor IndirectCommon Functions

### LINKED ISSUE #13955: Move Indirect Common functions to GUI interface for Indirect
Spencer has asked that the following checking routines be moved to the GUI as they are commonly used.
- [x] CheckXrange
- [x] CheckAnalysers
- [x] CheckHistZero
- [x] CheckHistSame

These are currently called in the algorithms themselves so instead will be required to be refactored out into the validation section of the interface code for algorithms that use them

### PR DESCRIPTION
**Pull request by louisemccann**
The following functions have been refactored from the Indirect Common script into the algorithms that use them:
- CheckXrange
- CheckAnalysers
- CheckHistZero
- CheckHistSame

**To test:**

Run:
- BayesQuasi
- BayesStretch
- TransformToIqt
- SofQMoments
- TimeSlice
- Symmetrise

Fixes #13955 .

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by mantid-roman** [comment]
All looks good to me :shipit:

**Comment by martyngigg** [comment]
Is there a reason that we are duplicating code here?

From the issue I understand it that the idea was to just move the calls to the validation from `PyExec` to `def validateInputs()` so that problems can be caught earlier. Have I misunderstood the issue?

**Comment by louisemccann** [comment]
I think that was my mistake in interpreting what was set out in the issue - putting the checks in validation makes much more sense

**Comment by AndreiSavici** [comment]
@louisemccann if you want to continue working on this PR, please add the `InProgress` label

**Comment by louisemccann** [comment]
I think the best option is to close this PR and start again

**Pull request closed without merging**
