### PR TITLE
Add skeleton of release notes for v6.0.0

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Adds the usual skeleton set of release notes for the next version

**To test:**

Build and check there are no warnings.

*There is no associated issue.*

*This does not require release notes* because **it is the release notes!**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by RichardWaiteSTFC — APPROVED** [review]
Compiles without error - has imaging always been part of diffraction?

**Comment by DannyHindson** [comment]
@martyngigg - just noticed this maintenance task had been done which is helpful thanks as I have a PR which requires a release note for 6.0. Where do the master templates for these live? There is a "Mantid imaging" heading in the diffraction.rst file that I remove on each release because we're not tracking the imaging functionality any more in the main Mantid release notes. I was hoping to delete that from the master at some point. Not a problem for 6.0 - I'll just remove again.

**Comment by DanielMurphy22** [comment]
> Where do the master templates for these live? 

Looks like they live here: tools/release_generator/release.py
I will fix this in my release notes PR

**Comment by martyngigg** [comment]
Sorry for not replying here! I just got a load of github notifications that I think must have been backed up when my email was out! Daniel has found the correct script :+1:

**Pull request merged**
