### PR TITLE
Indirect - ISIS Calibration - Check if resolution was included in calibration when plotting result

### LINKED ISSUE #21969: Indirect - ISIS Calibration - Creating the resolution after running the calibration produces error when 'Plot Result' is clicked
In the Interfaces > Indirect > Data Reduction > ISIS Calibration interface, first running the calibration on an input file, then checking the ```Create RES File``` check-box, results in the following warning error being produced when ```Plot Result``` is clicked:
```
Error while plotting:
The workspace "" could not be found.
```

To reproduce:
- Enter ```26173``` in the ```Run No``` field.
- Click ```Run```.
- Check the check-box labelled ```Create RES File```.
- Click ```Plot Result```.

### PR DESCRIPTION
**Pull request by brandonhewer**
In the Interfaces > Indirect > Data Reduction > ISIS Calibration interface, running the calibration without creating a resolution file and subsequently checking the ```Create RES File``` check-box and clicking ```Plot Result``` produces the error:
```
Error while plotting:
The workspace "" could not be found.
```

This PR fixes this issue, by checking whether the resolution file has been created in the previous calibration run before attempting to plot it.

**To test:**
1. Navigate to ```Interfaces > Indirect > Data Reduction > ISIS Calibration```.
2. Type ```26173``` into the ```Run No``` field and press enter.
3. Click the ```Run``` button.
4. Once the calibration has completed, check the check-box labelled ```Create RES File```.
5. Click the ```Plot Result``` button.
6. Ensure no error/warning is produced and a plot of the calibration is produced.

Fixes #21969. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Mantid-Matthew** [comment]
@brandonhewer The described test worked however I found an unexpected exception was thrown when I attempted to change to the instrument in the data reduction window to TFXA or TOSCA. This also happened when I attempted to open the interface having selected these instruments from the startup screen. Having checked on master these issues don't seem to crop up so seems mostly likely a change made in this branch.

**Comment by SpencerHowells** [comment]
The Res option is only for IRIS & OSIRIS and should be disabled for TFXA & TOSCA

**Comment by brandonhewer** [comment]
@Mantid-Matthew This PR should not be working as intended (Create RES File will be disabled for TOSCA and TFXA) and is ready to be re-tested

**Comment by NickDraper** [comment]
@Mantid-Matthew I think @brandonhewer meant "This PR should now be working as intended", one letter makes quite a difference.

**Review by Matthew-Andrew — APPROVED** [review]
The original functionality still works and the errors when switching to the non calibration instruments no longer occur.

**Pull request merged**
