### PR TITLE
Fix bad_cast in LoadLiveData

### LINKED ISSUE #23230: LoadLiveData throws std::bad_cast if data size changes
**Original reporter:** Andrew at ISIS

### Expected behavior
If the data size changes, the output should be overwritten

### Actual behavior
LoadLiveData throws std::bad_cast

### Steps to reproduce the behaviour
```

# set facility to TEST_LIVE
# instrument to ISIS_Histogram
# RunFakeISISHistoDAE with NPeriods=1
# Run live data on ISIS_Histogram with output name 'live'
# Once the output has been created, run this script:
AnalysisDataService.clear()
ws1 = CreateSampleWorkspace()
ws2 = CreateSampleWorkspace()
live=GroupWorkspaces(InputWorkspaces='ws1,ws2')
# Next time LoadLiveData runs it quits with a std::bad_cast error

# Repeat but with NPeriods = 2 and this script:
AnalysisDataService.clear()
live = CreateSampleWorkspace()
```

### Platforms affected
All

### PR DESCRIPTION
**Pull request by gemmaguest**
**Report to:** Andrew at ISIS

This commit fixes the possibility of a bad cast between a group and non-group workspace in LoadLiveData.

Note that if a group workspace is replaced by a non-group workspace, its original members still remain but become ungrouped. This doesn't seem ideal but is probably better than throwing. We could delete them but it seems safer to leave them.

Fixes #23230

**To test:**

Run the instructions in the linked issue and check the error is gone.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Mantid-Matthew** [comment]
Code changes look good and following the instructions does not cause any errors. I am having a possibility unrelated issue where the LiveListener algorithm refuses to cancel and whe you attempt to close mantid after starting the live listener it crashes. Is this a known issue ?

**Comment by Mantid-Matthew** [comment]
I noticed this pull request went through #23282 would that be a better method ?

**Comment by Mantid-Matthew** [comment]
Update to use isGroup looks good. I am however still seeing the issue where I am unable to cancel the live listener algorithm I can reproduce this in two ways:
* Run FakeISISHisto then start a live listener. If you cancel FakeISISHIsto first you can then not cancel the live listener.
* Follow the first half of the test instructions in the issue. Afterwards I am unable to close the live listener from the algorithm menu.

**Comment by gemmaguest** [comment]
Ah, sorry, I'd missed your first comment. I've seen something like this before but I thought it was fixed. I'll check it out.

**Comment by gemmaguest** [comment]
Hmm, I can't reproduce the live listener problem.

**Comment by gemmaguest** [comment]
The live listener problem is reproducible in nightly so is not related to this PR. I've raised issue #23406 for that.

**Review by Matthew-Andrew — APPROVED** [review]
Given the only issue I found is already on nightly happy to approve this pull request.

**Pull request merged**
