### PR TITLE
Write PeakShape

### PR DESCRIPTION
**Pull request by OwenArnold**
[#10904](http://trac.mantidproject.org/mantid/ticket/10904) Write the PeakShape from integration algorithms

### CODE REVIEW

**Comment by OwenArnold** [comment]
Jenkins retest this please

**Comment by OwenArnold** [comment]
Jenkins retest this please

**Comment by martyngigg** [comment]
Jenkins, retest this please

**Comment by martyngigg** [comment]
The builds have got themselves into some odd state with this pull request. I suggest closing it without merging and opening a fresh one.

**Pull request closed without merging**
