### PR TITLE
Fix WorkspaceFactory outputting workspaces with an invalid vertical axis

### LINKED ISSUE #12720: WorkspaceFactory outputs invalid workspaces when child contains more spectra than parent
When creating a child workspace using the WorkspaceFactory where the child will have more spectra than the parent, no modification is done to the vertical axis, hence it ends up being too short for the child workspace which leads to issues if you try and do anything in Mantid the reads the axis.

When this happens the WorkspaceFactory should extend the axis and fill it with either zeros or empty strings to at least make it usable.

### PR DESCRIPTION
**Pull request by DanNixon**
Fixes #12720 

I can't think of an easy way to test it other then via code review.

The issue is that `differentSize` boolean is set false by the `create` function as it sees that the Y length parameter is the default so it assumes the size does not change.

In the axis code it takes either this boolean flag being false or the axis lengths being identical to assume that the axis length had not changed, which only worked for the X axis.

No release note changes as this is an internal only issue.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
@DanNixon : The system test `CalMuonDeadTimeTest` seems not to like this PR. This test is comparing the output of the algorithm CalMuonDeatTime with a file previously saved file. It could well be that the reference file needs an update?

**Comment by DanNixon** [comment]
@FedeMPouzols I don't think it fails reliably though, I'm sure I have seen a build where is passed (I thought it was the second to last but I can't seem to see that build any more).

I'll have a better look tomorrow.

**Comment by FedeMPouzols** [comment]
I just tried a rebuid, to see if the maybe? random issue had vanished away after a few days, but it failed again on the same `CalMuonDeadTimeTest`.

**Comment by DanNixon** [comment]
Yes, there does seem to be some issue with it.
I have no idea what it it though, when I load the reference file and compare it to the result of me manually running the test they are identical.

**Comment by martyngigg** [comment]
Can this be pushed back to `3.7`?

**Pull request closed without merging**
