### PR TITLE
TransformtoIqt - Integration Bug

### PR DESCRIPTION
**Pull request by mpatrou**
### Description of work
This fixes a test case where Integration and TransformtoIqt return NaN and 0 values for E and Y values respectively.

#### Summary of work
The Integration algorithm has a normalization process when calculating the values. In a test case (fileset) provided by scientists, the algorithm produces NaN values during this step, because of 0 division. We included a line to check whether the value is 0 and allow the division to happen.

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by sf1919** [comment]
Is this related to #36360 ?

**Comment by mpatrou** [comment]
The PR is related to an issue, where TransformtoIqt has Y- and E- values = 0.

**Comment by robertapplin** [comment]
Looks like a good change, and has a test. Does this need a release note?

**Comment by mpatrou** [comment]
moved this to a new PR for release-next branch

**Comment by sf1919** [comment]
This one can be closed. Anything that gets merged into `release-next` also gets merged into main as `release-next` regularly merges into main.

**Pull request closed without merging**
