### PR TITLE
Port Indirect Data Analysis GUI

### LINKED ISSUE #25983: Port Indirect Data Analysis
### Description
Port the Indirect Data Analysis GUI to the Workbench. 
Most of the requirements needed to do this should now have been fulfilled.

### Platforms affected
All

### PR DESCRIPTION
**Pull request by robertapplin**
------------------------
**Description of work.**
This PR ports the Indirect Data Analysis GUI to the workbench. The main addition required to do this was the ability to create do an external tiled plot on the workbench (now using the `plotsubplots` function - the name may want to be changed if a better one can be thought of).

**To test:**
1. Go to `Interfaces`
2. Then `Indirect Data Analysis`
4. Enter the data below for the corresponding tabs
5. Click `Run`
6. Click `Plot Spectra` or `Plot` (depending on the tab). Try `Plot Tiled` on the `Iqt` tab (accessed via the down arrow on the `Plot Spectra` button)

Also try moving around the range selectors on the embeded plots (the dashed vertical lines).

### **Test Data**
**Elwin Tab**
Input file: [irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2361048/irs26176_graphite002_red.zip)

**MSDFit Tab**
Input file: [osi92762_graphite002_elwin_eq.zip](https://github.com/mantidproject/mantid/files/2361050/osi92762_graphite002_elwin_eq.zip)
Fit Type: `Guassian`

**Iqt Tab**
Input files: [irs26173_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2361057/irs26173_graphite002_red.zip)
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2361058/irs26173_graphite002_res.zip)

**IqtFit Tab**
Input file: [irs26176_graphite002_iqt.zip](https://github.com/mantidproject/mantid/files/2361062/irs26176_graphite002_iqt.zip)
`Stretched Exponential`
`Flat background`
Note: drag the EndX on the graph to the left a bit to miss the noise (`0.2` I think)

**ConvFit Tab**
Input files: [irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2361070/irs26176_graphite002_red.zip)
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2361071/irs26173_graphite002_res.zip)
Fit Type: `Two Lorenztian`
`Flat Background`

**F(Q) Tab**
Input file: [IN16B_125878_QLd_Result.zip](https://github.com/mantidproject/mantid/files/2361073/IN16B_125878_QLd_Result.zip)
Fit Type: `Chudley Elliott`

Fixes #25983 and #25729 

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by robertapplin** [comment]
Problems which have not yet been fixed:
- It is not possible to dock a floating QDockWidget on the workbench. A QDockWidget is used for the FitPropertyBrowser and the embedded plots for the fitting tabs.
- An icon is needed for the splitter handle between the two embedded plots on the fitting tabs.

**Comment by robertapplin** [comment]
The last known problem to fix before this works on workbench:
- It is not possible to dock a floating QDockWidget on the workbench. A QDockWidget is used for the FitPropertyBrowser and the embedded plots for the fitting tabs.

**Comment by robertapplin** [comment]
@SpencerHowells has an unstable build of this.

**Comment by SpencerHowells** [comment]
@Mantid-Matthew @AnthonyLim23 First quick look. The functionalities - Elwin, Iqt, fitting - all seem to work well. There are a couple of plotting issues: 1) tiling not there but I notice there is an Issue for it; 2) legend for curves show the spectrum number. A lot of our workspaces have text eg fit function name, so that needs to be addressed.

**Comment by AnthonyLim23** [comment]
From the 2 points Spencer has pointed out, I think #26655 has at least added most of the tools for tile plots and #26716 should cover the label problem. @Mantid-Matthew, what do you think?

**Comment by SpencerHowells** [comment]
@AnthonyLim23 @Mantid-Matthew I also think the 2 plotting issues have been resolved. The curve label issue would also solve problems in other GUIs.

**Comment by Mantid-Matthew** [comment]
I suspect that some of the code in the GUI will need updating to properly use the new tile plotting functionality @SpencerHowells could you remind me what the workflow is where you would expect tiled plot to appear?

**Comment by SpencerHowells** [comment]
@Mantid-Matthew Tiled plot is only in the Iqt tab as a plot option for the results.

**Comment by SpencerHowells** [comment]
@Mantid-Matthew The *_workspace workspaces need Grouping like IqtFit

**Comment by AnthonyLim23** [comment]
got a conflict, is this ready to be looked at?

**Comment by AnthonyLim23** [comment]
@SpencerHowells I am happy with the code. Let me know if you are happy with the functionality.

**Review by AnthonyLim23 — APPROVED** [review]

**Pull request merged**
