### PR TITLE
New "energy bands" tab in tomography GUI

### LINKED ISSUE #13467: Add tab/widget for "energy bands" in the tomo gui
Initially it should have:

- Find a stack of images from an energy selective experiment (the ones with thousands (energy bands) X hundreds (angles) images.
- Select minimum energy index and maximum energy index from available ones - this x3 (one for sample images, another one for dark images, and the third one for flat images).
- Name and destination location of the simplified stack.
- Only one option for a start: sum/average throughout the energy bands.

It could make sense to add an algorithm for the underlying calculations and file read/writes, but that code could also live in the gui implementation for now. It is pretty much in the air how this is going to be used but having the algorithm would make it possible to script this easily.

Related to #13140, #12900, #12898.

### PR DESCRIPTION
**Pull request by FedeMPouzols**
Extends the "energy bands" tab of the tomo GUI and uses ImggAggWavelengths.
- [x] #15873 is required for this and should be merged in first.

**To test:**
- Tests should pass, including the new unit test cases
- Go to Main Menu ->Interfaces->Diffraction->Tomographic reconstruction->"Energy bands" tab
- Select an input path using the same example/test data as in PR #15873. Select as ouput path any existing directory where it is ok to write the files. Select for example "uniform bands", with a value of 2.
- Start the aggregation process.
- When it finishes it will show a pop up to notify the user that the
  results are ready.
- If you give empty or wrong paths it should give an informative error message.
- The "TOF boundaries" options is disabled for now - we need headers in the input files which are not available at the moment.
- The input and output formats are currently forced to "FITS".
- The interface should feel usable, and it should remember all settings.
- Check documentation updates

Fixes #13467.

Release notes: https://github.com/mantidproject/mantid/commit/20c7f46aa0829edafb6241349132180bc1984e34

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by shahrozahmed1** [comment]
@FedeMPouzols the interface for the `ImggAggWavelengths` algorithm looks good.. but for some reason the test seem to not build for me locally on windows and complains about `TomographyIfacePresenterTest` .. 
```
2>c:\users\ryq25391\documents\github\mantid4\mantidqt\custominterfaces\test\TomographyViewMock.h(128): warning C4002: too many actual parameters for macro 'MOCK_CONST_METHOD0'
2>c:\users\ryq25391\documents\github\mantid4\mantidqt\custominterfaces\test\TomographyViewMock.h(128): error C2976: 'std::map': too few template arguments
2>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\map(72): note: see declaration of 'std::map'
2>c:\users\ryq25391\documents\github\mantid4\mantidqt\custominterfaces\test\TomographyViewMock.h(128): error C2955: 'std::map': use of class template requires template argument list
2>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\map(72): note: see declaration of 'std::map'
2>c:\users\ryq25391\documents\github\mantid4\mantidqt\custominterfaces\test\TomographyViewMock.h(128): error C2039: 'Result': is not a member of 'std::map'
2>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\map(72): note: see declaration of 'std::map'
```

**Comment by FedeMPouzols** [comment]
You need to pull the last commit where that issue was fixed. There's a problem with the MSVC pre-processor.

**Comment by shahrozahmed1** [comment]
yes it seems to work now, the documentation and GUI test have been updated, simple and straight-forward interface with `ImggAggWavelengths` being ran in the background.. 
just a note that for me locally `void test_showImg_good()` test case seems to produce weird debug error however this seems to work fine for you as well on all build servers so I shall ignore it.

- [ ] Once #15873 is merged:

  ......     :shipit:

**Comment by FedeMPouzols** [comment]
Strangely enough GitHub said there was a merge conflict with this branch. In the last commit I merged master into it and it was a clean merge.

**Comment by shahrozahmed1** [comment]
:shipit:

**Comment by martyngigg** [comment]
Nice to more examples of the MVP pattern!

**Pull request merged**
