### PR TITLE
make bin/title units less ambiguous

### LINKED ISSUE #34416: Extra text in bin/spectrum title in Show Data table
I've added this issue to the upcoming release 6.5 as this is hopefully a minor fix which makes the software seem more professional. I think this despite the bug existing in the last release (6.4) too.

Found in unscripted testing

**To Reproduce**
As the first few steps here: https://developer.mantidproject.org/Testing/IndirectInelastic/IndirectInelasticAcceptanceTests.html#data-analysis-elwin

- Go to Interfaces > Indirect > Data Analysis
- Enter irs26176_graphite002_red.nxs in Input file
- Click Run - this should produce 3 new workspaces _elf, _eq and _eq2
- The text "Last 3 digits" is appended to the value for the bin / spectrum in the column / row of the Show data table

**Screenshots**
last 3 digits

**Platform/Version (please complete the following information):**
Seen on IDAaaS and Windows and exists on this release and the previous (6.4)

### PR DESCRIPTION
**Pull request by MialLewis**
**Description of work.**

In several algorithms, if the an axis contains run numbers the unit label `last 3 digits` was assigned. ~~This is label is fairly ambiguous, so have changed the label to '_Run No'. Otherwise could remove the label all together, open to suggestions.~~
It has been decided to keep this label. It has been present in the relevant algorithms for a long time, and makes sense in the context of a plot (see images below from @SpencerHowells). I have added a space to the label to separate it from the number in the bin title and have made this consistent across algorithms.

**To test:**
- Follow instructions set out in #34416 
- Plot a graph of the bin, observe the `Run No (last3digits)` axis title is unaffected by this change.

Fixes #34416

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by SpencerHowells** [comment]
@MialLewis The algorithms run over a set of runs. It is usually for a series of temperatures or other sample environment. If such values do not exist it uses the run number. This can be 6 or more digits which gives a plot a messy x-unit scale. So I decided to use just the last 3 digits. I don't know why it's taken to use both - I don't think it used to.

**Comment by MialLewis** [comment]
> @MialLewis The algorithms run over a set of runs. It is usually for a series of temperatures or other sample environment. If such values do not exist it uses the run number. This can be 6 or more digits which gives a plot a messy x-unit scale. So I decided to use just the last 3 digits. I don't know why it's taken to use both - I don't think it used to.

What do you mean by "use both"?

It looks to me as if for the dataset used in the used in the issue, no `sample environment unit` can be found. This then means `v_axis_is_sample` is set to `false`, and the relevant axis is then set to use the last 3 digits of the run number (as you describe above).

Following this, the axis caption is set to `Run No` and the label set to `last 3 digits`, which Dan has taken issue to in #34416.
I don't think its doing anything wrong/different as such, just not the clearest label.

**Comment by SpencerHowells** [comment]
@MialLewis I think I've worked out what is going on. It should give value & unit. As in '0.44 A-1'. So '176.00last 3 digits' should be '176 last 3 digits'. That is 176.00 should be the integer 176 not floating point and 'last 3 digits' is the non-standard unit. In addition the values should not show 0.... This is a formatting error which I thought was dealt with a month or 2 ago.

**Comment by MialLewis** [comment]
> @MialLewis I think I've worked out what is going on. It should give value & unit. As in '0.44 A-1'. So '176.00last 3 digits' should be '176 last 3 digits'. That is 176.00 should be the integer 176 not floating point and 'last 3 digits' is the non-standard unit. In addition the values should not show 0.... This is a formatting error which I thought was dealt with a month or 2 ago.

I agree.

The underlying axis object [NumericAxis](https://github.com/mantidproject/mantid/blob/15ef1d68a3427cf52dbf91faa2072ca5c5bae02d/Framework/API/inc/MantidAPI/NumericAxis.h) stores the bin centre values as a double, so I don't think we can display run number as an `int` easily.

So the question is, do we still want the run numbers showing as `XXX last 3 digits`, or do we want to change it to something less ambiguous (here I've changed it to `XXX_Run No`)?

Regarding the values showing as `0....`, if you are referring to issue #34101, this has been fixed in `6.5`.

**Comment by SpencerHowells** [comment]
@MialLewis I guess we'll have to put up with it not being integer. I wrote the algorithm some 10 yrs ago & don't remember this problem. Also there have been no complaints from users about ambiguity. So can you just insert a space between number & text. Regarding the 0... problem I was looking at the screen shot in the Issue. I've just run on nightly build & it has indeed been corrected. Finally, most use these days will have temperature so this will not often be seen.

**Comment by SpencerHowells** [comment]
@MialLewis I hope this shows a plot which looks ok
image

**Comment by SpencerHowells** [comment]
@MialLewis This is what a plot looks like which is fine
iris26173-26176_group_red_elwin_eq-1

**Review by DanielMurphy22 — APPROVED** [review]
Good job! Thanks for clarifying that this unit is correct and the space added is a good improvement!

**Pull request merged**
