### PR TITLE
Add Phi Options to SANS Table

### LINKED ISSUE #23960: SANS ISIS Backend add centering to SANSLoad
Currently the SANSLoad algorithm loads SANS data and applies calibrations if necessary. The instrument scientists would like it to additionally centre the workspaces here so that loaded data is calibrated and centered. 

The information about the centre position is already in the state object passed to SANSLoad. The centering is currently done as part of the processing here

thttps://github.com/mantidproject/mantid/blob/master/scripts/SANS/sans/gui_logic/presenter/run_tab_presenter.py#L353

Which should act as a good example. With this change we will technically be centering twice in a typical reduction. Once during loading and again during the reduction itself. It is possible the centering algorithm is clever enough for the second time to not take long if nothing has changed but this should be checked.

### LINKED ISSUE #23969: ISIS Sans GUI V2 add phi masking as an option to options column
The options column allows commonly set options to be changed from the front table on a row by row basis. Currently the only options which can be set here are the event slices and the wavelength min and max.

Diego wants to be able to set the phi masking options from here as well. 

The options column model is here

https://github.com/mantidproject/mantid/blob/master/scripts/SANS/sans/gui_logic/models/table_model.py#L325

The options are applied to the created state object here 

https://github.com/mantidproject/mantid/blob/master/scripts/SANS/sans/gui_logic/presenter/gui_state_director.py#L61

The relevant state variables are here

https://github.com/mantidproject/mantid/blob/master/scripts/SANS/sans/state/mask.py#L187

### LINKED ISSUE #24347: ToolTip Colour Unreadable on Ubuntu 18
**Original reporter:** @TTitcombe ISIS

### Expected behavior
Readable text everywhere on Mantid, on every system.

### Actual behavior
Text in the Hint tooltip is completely unreadable on Ubuntu 18

### Steps to reproduce the behavior
1. Interfaces -> SANS -> SANS v2 experimental
2. In the table, click on the cell under the "options" column
3. Type "W" to prompt the hint tooltip to appear, it has a cream background with white writing

Black text on this background (rgb = 255, 253, 209) appears readable on a colour picker, so that may be the change required.

### Platforms affected
Ubuntu 18

This issue is directly linked to PRs #21930 and  #21832

### PR DESCRIPTION
**Pull request by TTitcombe**
**Description of work.**

_Note that branch points to incorrect issue as this PR originally contained solutions to multiple issues_

Include PhiMin, PhiMax, UseMirror as parameters setable in the JobTreeView options column in SANS v2

**Report to:**  Nobody

**To test:**
1. Interfaces -> SANS -> SANS v2
2. Load any acceptable user and batch file
3. In the options column, type PhiMin=x, PhiMax=y, UseMirror=z, where x and y are floats, and z is either some truthy (e.g. True, 1, yes) or falsy (e.g. False, 0, no) statement
4. Click off the options column
5. Click the settings tab on the left hand side of the GUI, and the the `mask` tab at the top
6. Click `Display Mask`
7. The Displayed mask should show a radial section of the detector (with parts greyed out) e.g. if you typed "PhiMin=0, PhiMax=115, UseMirror=True" you should see the detector from angle 0-115 and angle 180-295
8. If you gave `UseMirror` neither a truthy or falsy statement, a value should not be taken and a readable error message should appear in the log

Fixes #23969 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by TTitcombe** [comment]
Checking that the hint tooltip appears readable on all platforms:
* [ ] Ubuntu 18
* [ ] Ubuntu 16
* [ ] Windows
* [ ] OSX
* [ ] RHEL7

**Comment by robertapplin** [comment]
@TTitcombe I am getting the following error when I get to the step where you click 'Display Mask'. I wrote 'PhiMin=0.0, PhiMax=115.0, UseMirror=True' in the output column
image

**Comment by TTitcombe** [comment]
> @TTitcombe I am getting the following error when I get to the step where you click 'Display Mask'. I wrote 'PhiMin=0.0, PhiMax=115.0, UseMirror=True' in the output column
> image

hmm, I don't. I'll need to look into this

**Comment by TTitcombe** [comment]
@robertapplin When you said `output column`, was that a typo or did you actually get the error when typing in the output (name) column?

**Comment by TTitcombe** [comment]
Could you send me the data used for this,  I think that might be the cause of the problem (I should have provided some SANS data for this PR)

**Comment by robertapplin** [comment]
@TTitcombe That was a typo, I meant the `Options column`. The batch file I used was 
[batch_mode_reduction.zip](https://github.com/mantidproject/mantid/files/2740032/batch_mode_reduction.zip)

**Review by Matthew-Andrew — APPROVED** [review]
This works for me

**Pull request merged**
