### PR TITLE
Minor UI changes to DGSPlanner UI

### PR DESCRIPTION
**Pull request by AndreiSavici**
This is ticket [#11516](http://trac.mantidproject.org/mantid/ticket/11516)

The goniometer picture has to be fixed by replacing the matplotlib. Martyn is looking into that

### CODE REVIEW

**Comment by AndreiSavici** [comment]
Martyn upgraded matplotlib in 3rdpartylibs-win64

**Comment by abuts** [comment]
Stretching have fixed fine. Goniometer still ugly despite new win library. Progress bar would be really nice as gui freezes for substantial time until calculations are completed.

**Comment by AndreiSavici** [comment]
Here is my screenshot on Windows 8.1 screenshot

**Comment by AndreiSavici** [comment]
Progress bar and possibility to cancel are in ticket [#11615](http://trac.mantidproject.org/mantid/ticket/11615)

**Pull request merged**
