### PR TITLE
PolDiffILLReduction: TOF mode support

### LINKED ISSUE #32157: PolDiffILLReduction: TOF mode
The data reduction for polarized diffraction on the D7 ILL instrument has three major workflows, for powder samples, single crystal samples, and when the measurement is in the TOF mode. The two latter modes of data reduction have been already implemented and are undergoing validation by the responsible scientists. The support for reducing TOF mode data is required for complete support for the D7 instrument at the ILL.

The reduction needs to include:
- Support for 2D TOF workspaces with correct normalisation by monitor or time
- Elastic peak calibration using vanadium measurement
- Calculation of time-dependent and time-independent background contributions and proper subtraction of it
- Frame-overlap correction
- Detector-analyser energy efficiency correction

### PR DESCRIPTION
**Pull request by darominski**
**Description of work.**

This PR contains the work aimed to provide support for the third and final mode of operation of the D7 instrument at the ILL, namely for the polarised spectrometry.

The updated reduction workflow includes:
- [x] Support for 2D TOF workspaces with correct normalisation by monitor or time.
- [x] Elastic peak calibration using vanadium measurement.
- [x] Calculation of time-dependent and time-independent background contributions and proper subtraction of it, including error propagation, three options provided: direct empty container counts subtraction, rectangle function based on empty container counts, and gaussian distribution with equivalent count rate but different subtraction strategy.
- [x] Frame-overlap correction.
- [x] Detector-analyser energy efficiency correction.
- [x] TOF vanadium normalisation of sample data.
- [x] Proper calculation of output S(Q, w) distribution.
- [x] Debugging flags for converting to energy, performing detector energy efficiency correction, performing frame-overlap correction.

**To test:**

The output from this PR has been reviewed and validated by responsible scientists.

1. All tests should be passing.
2. Code review. 

Fixes #32157 . 

Release notes and documentation coming soon.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gvardany** [comment]
Code looks alright, testing and documentation is adequate. It looks like there is a memory management issue in the loader though.

**Comment by darominski** [comment]
> Code looks alright, testing and documentation is adequate. It looks like there is a memory management issue in the loader though.

Indeed, there was an issue limited to Mac and Windows. I believe it was two-folds: on the memory management itself, which has been improved, and on the side of reading an 'artificial' nxs file that was mocking future 10-point measurement data. This file was created using h5py library on Ubuntu, and there were no issues reading it on RHEL7 or Ubuntu machines, but metadata was not properly read on a test machine running Mac. To not halt this PR any longer, I decided to run polarisation sorting test on a different, already existing file, and tests are passing as expected now.

**Review by gvardany — DISMISSED** [review]

**Review by gvardany — DISMISSED** [review]
Reapproving after base branch change.

**Review by sf1919 — CHANGES_REQUESTED** [review]
Please can the release note be move to a separate file? We're asking that no one adds directly to 6.3 release notes now.

**Review by sf1919 — DISMISSED** [review]
Requested change to release notes made so happy to re-approve.

**Comment by DannyHindson** [comment]
Should the change to add 6.4 to docs/source/release/index.rst and all of the changes to create rst files in docs/source/release/v6.4.0/ be in this PR? Seems like these changes are perhaps a left over from when the base branch was main?

**Comment by darominski** [comment]
Apologies for creating quite a mess. The history of the conversation has been lost due to my actions. In short, there was an issue of not rebasing to the release-next branch and still following the main, which introduced v6.4 release notes and other commits that should not be shipped with this PR. Then I have made a mistake while correcting this issue and basically cleared this PR from commits... 

In the end, all commits are back,  and the release notes are now in a separate file named: 32206_diffraction.rst, as requested. There should be no remnants of v6.4 stuff. @gvardany  could you please re-approve once tests are passing?

**Review by gvardany — APPROVED** [review]
There is a reason I hate force-pushes...

**Review by sf1919 — APPROVED** [review]
I haven't undertaken a full review of the code as this has already been done and the PR approved. However I previously requested changes with regards the release notes. I have checked and can confirm that the release notes are in a separate file as requested. On that basis I am happy to approve.

**Pull request merged**
