### PR TITLE
Expose the Q summation functionality on the settings tab

### LINKED ISSUE #21353: Expose the Q-summation functionality on the Settings tab
As described in #21167, this issue is to Expose the Q-summation functionality on the Settings tab via via SummationType and ReductionType drop downs as on the RROA dialog.

### PR DESCRIPTION
**Pull request by edwardb96**
**Merge BEFORE #21299**

Exposes the `ReductionType` and `SummationType` options of `ReflectometryReductionOneAuto` on the Reflectometry GUI settings tab via two comboboxes.

**To test:**
1. Open the ISIS Reflectometry GUI.
2. Open the .tbl file `INTER_NR_test2.tbl` from the ISIS Sample data. (`Reflectometry -> Import TBL`).
3. Experiment with processing individual rows with `SumInLambda` and then `SumInQ` with each ReductionType.
4. Check the corresponding `IvsQ_{RunNumber}` workspace's history (`Right Click -> Show History`) ensuring that the correct `ReductionType` and `SummationType` were passed to `ReflectometryReductionOneAuto`. 
5. Ensure that the ReductionType box is enabled **iff** the SummationType is set to `SumInQ`.

Fixes #21353. 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by gemmaguest — CHANGES_REQUESTED** [review]
- The changes look good and behave as described :+1:
- Changes in the new settings are picked up so that processing is re-run :+1:
- `ReductionType` is greyed out and ignored if `SummationType` is `SumInLambda` :+1:
- `ReflectometryReductionOneAuto` fails (correctly) if using `SumInQ` with `Normal` reduction type and works in all other combinations :+1:

Just a few minor issues:
- See the inline comment about a change of behaviour since the merge from master.
- The default summation type should be `SumInLambda` rather than `SumInQ`, to match the default behaviour of the algorithm.
- Is it worth adding a test to check that `getReductionOptions` does not return a reduction type when the summation type is `SumInLambda`?

**Review by gemmaguest — APPROVED** [review]

**Comment by gemmaguest** [comment]
This all looks good now :+1:

**Comment by martyngigg** [comment]
@edwardb96 There are conflicts here due to #21343 I suspect.

**Comment by edwardb96** [comment]
This PR has become part of #21299 which includes the fixes for the above test failures.

**Comment by martyngigg** [comment]
:+1:

**Pull request closed without merging**
