### PR TITLE
Advanced period arithmetic in MuonCalculateAsymmetry

### LINKED ISSUE #14020: Advanced period arithmetic in MuonCalculateAsymmetry
The algorithm should be able to combine periods in a more arbitrary way. For example, 1+3-2-4. This means that the algorithm must first add 1+3 and 2+4 and then subtract (1+3)-(2+4).

To make this change, we will need to change some of the input properties: FirstPeriodWorkspace and SecondPeriodWorkspace should be merged into a single workspace group property (group items representing the different periods). Then, PeriodOperation should allow any possible combination (accepting only +/- operations). The MuonAnalysis interface will have to be updated according to these changes.

### PR DESCRIPTION
**Pull request by tom-perkins**
Resolves #14020 

In MuonCalculateAsymmetry (and so by extension, MuonLoad and the MuonAnalysis interface), it is possible to analyse the sum or difference of two periods. This PR is to extend this functionality to allow more advanced period arithmetic, for example periods (1+2)-(3+4).

Testing:
- check all tests pass
- analyse a muon data set with 2 periods and compare the results to the installed version of Mantid
- analyse a muon data set with >2 periods. Verify that it is possible to use all periods in the analysis.
- Check that it's possible to do this analysis with the MuonAnalysis UI and MuonLoad algorithm as well as with MuonCalculateAsymmetry,

To analyse multiple periods, all workspaces should be grouped and the WorkspaceGroup passed as input to the algorithm. The SummedPeriodSet contains indexes of periods to be summed, and the SubtractedPeriodSet contains indexes of periods to be subtracted, for example in a group of 4 periods:

SummedPeriodSet = 1,2
SubtractedPeriodSet = 3,4
resulting operation is (1+2)-(3+4)

The MuonAnalysis UI has been updated with two text boxes for the left and right hand side of the subtraction above. For example, the above (1+2)-(3+4) would be input by putting "1,2" in the left hand box and "3,4" in the right hand box.

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
The Muon Analysis interface has an option ("Settings" > "Plot Cretation" > "Auto update") to auto update the plot every time a property is changed. I wanted to load a four period dataset ("EMU00006475.nxs") and sum all the periods, that is, "1,2,3,4". I noticed that every time I typed something in the corresponding QLineEdit, the plot gets updated, so that if I want to combine periods "1,2,3,4" I have to generate three plots before I can get the plot I really want. Perhaps it would be enough to change the signal associated to the slot checkForEqualPeriods(), so that this is only done once the user has finished editing. Could you have a look and see if this can be improved?

**Comment by tom-perkins** [comment]
Changed to update plot only when editing is finished (when the QLineEdit loses focus or the user presses return), rather than every time text is changed.

**Comment by raquelalvarezbanos** [comment]
Thanks, the interface works better now.

I've also tested a couple of single period datasets and it works as expected. I still have to compare results to the installed version of Mantid, but changes look good.

The only thing to bear in mind is that with these changes we won't be able to use MuonCalculateAsymmetry directly on a single period dataset. This is perfectly OK (as long as single period runs can be loaded via the interface), as scientists confirmed they are not using these algorithms directly, but only through the interface so it is totally OK to change them.

I see you have updated the algorithm's documentation, could you also add a note to the interface documentation and the release notes: http://www.mantidproject.org/Release_Notes_3_6_MuonAnalysis

**Comment by tom-perkins** [comment]
Documentation:
- [x] Update [interface documentation] (http://www.mantidproject.org/MuonAnalysisHome)
- [x] Update [release notes] (http://www.mantidproject.org/Release_Notes_3_6_MuonAnalysis)

**Comment by raquelalvarezbanos** [comment]
I've compared the results to a previous version of Mantid and they match, changes look good, so I'm happy to merge this branch.

Perhaps the only minor detail to consider is that when a single period dataset is loaded, you can enter a non-existent period number, the interface will just plot the first (and only) period but no warning message is shown. But this is just a minor detail.

**Pull request merged**
