### PR TITLE
Remove old frequency domain analysis gui

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR removes the old frequency domain analysis python script and does a small bit or renaming for the new FDA files.

**To test:**
Make sure the new Frequency Domain Analysis still opens and works as expected.

*This does not require release notes* because **it is an internal change**.

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
you should also be able to delete: maxent_presenter.py, maxent_view.py and maxent_widget.py from https://github.com/mantidproject/mantid/tree/master/scripts/Muon/GUI/FrequencyDomainAnalysis/MaxEnt 

and 
fft_view.py, fft_presenter.pt and fft_widget.py
from
https://github.com/mantidproject/mantid/tree/master/scripts/Muon/GUI/FrequencyDomainAnalysis/FFT

There are also some C++ files that we can delete. I assume those are for another day

**Comment by robertapplin** [comment]
It looks like I deleted the new FFT and MaxEnt widgets in the diff, but I actually renamed the new files and deleted the old

**Comment by AnthonyLim23** [comment]
ok, as long as you updated the imports

**Comment by robertapplin** [comment]
> ok, as long as you updated the imports

Yes they should be updated

**Comment by AnthonyLim23** [comment]
conflicts everywhere

**Review by AnthonyLim23 — APPROVED** [review]
I can make FFT's and maxents without any problems. Looks good to me

**Pull request merged**
