### PR TITLE
Workflow diagram for IndirectFlatPlateAbsorption

### LINKED ISSUE #14872: Add workflow diagram to IndirectFlatPlateAbsorption
The documentation for the ***IndirectFlatPlateAbsorption*** algorithm should include a workflow diagram.

Examples of workflow diagrams:

* [DgsReduction](http://docs.mantidproject.org/nightly/algorithms/DgsReduction-v1.html#workflow)
* [LoadEventAndCompress](http://docs.mantidproject.org/nightly/algorithms/LoadEventAndCompress-v1.html#workflow)
* [IndirectILLReduction](http://docs.mantidproject.org/nightly/algorithms/IndirectILLReduction-v1.html#workflow)

### PR DESCRIPTION
**Pull request by ElliotAOram**
Fixes #14872 

Added workflow diagram to IndirectFlatPlateAbsorption algorithm
# To Test
- Ensure that the diagram is representative of the workflow of the algorithm

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
The diagram looks good, displays correctly on the qthelp and html pages, and is ready to be merged.

I only spotted one small issue? After the decision "Can Workspace?", the branch "No" should have a "Minus" before the "Divide"? Also, the workspace used for that divide could be shown in the diagram (as in the "Yes" branch).

**Comment by ElliotAOram** [comment]
Thanks @FedeMPouzols I'll make those changes!

**Comment by ElliotAOram** [comment]
@FedeMPouzols I have added the absorption workspace to the "Divide" on the "No" branch. 
I'm not sure if there should be a "Minus" there. 
The code seems to check `if self._can_ws_name is not None:` on line 129 and then, from what I can tell, the `else` statement for this is line 165 - which has no "Minus" because there isn't a can to subtract.

**Comment by FedeMPouzols** [comment]
Oh yes, I think I got confused with another else branch. Like that it makes perfect sense. Not bothering to wait for tests that are not affected by this branch.

**Pull request merged**
