### PR TITLE
Stop SliceViewer stacking delayed refreshes

### PR DESCRIPTION
**Pull request by MialLewis**
**Description of work.**
SliceViewer currently utilises a delayed refresh. If a workspace with SliceViewer open is changed multiple times in quick succession these delayed refreshes stack and cause workbench to hang whilst they are processed.

This PR adds a simple flag to the delayed refresh to limit the amount of refreshes which can be queued.

**To test:**

1.  Run `ws = CreateSampleWorkspace()`
2.  Right click the created workspace and open sliceviewr.
3. Run:
```
for i in range(50):
    print(i)
    ws = ws*10
```
4. Observe minimal delay after execution of calculations.

*There is no associated issue.*

*This does not require release notes* because it fixes an issue caused by a recent commit.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@MialLewis I think we agreed that this might be safer to go to `main` and not for 6.4 last week? Is it the case that this really only happens with the operations in a tight loop?

**Comment by MialLewis** [comment]
> @MialLewis I think we agreed that this might be safer to go to `main` and not for 6.4 last week? Is it the case that this really only happens with the operations in a tight loop?

I was out of office on Friday so left it with Gemma to discuss with you - that's fine if it's what was decided. Yes, it is only really noticeable with tightly looped operations.

**Review by gemmaguest — CHANGES_REQUESTED** [review]
Looks good and functions really well. I've tried lots of the previous sliceviewer bug reproducers and it all works smoothly :+1:

Is it worth adding a small test? We probably can't test the view but could test that the presenter resets the flag?

**Comment by MialLewis** [comment]
> Looks good and functions really well. I've tried lots of the previous sliceviewer bug reproducers and it all works smoothly 👍
> 
> Is it worth adding a small test? We probably can't test the view but could test that the presenter resets the flag?

I've just added such a test

**Review by gemmaguest — APPROVED** [review]
Thanks for adding the test, looks good now :+1:

**Pull request merged**
