### PR TITLE
Indirect Data Analysis - Keep open option for Multiple Input

### LINKED ISSUE #23813: Indirect - Data Analysis - No keep open option for Multiple Input
**Original reporter:** Spencer

### Expected behavior
There should be a `Keep open` tick box option on the window used for multiple input of workspaces for Indirect Data Analysis.

### Actual behavior
The dialog window closes immediately after adding a workspace to the Multiple Input.

### Steps to reproduce the behavior
1.`Interfaces`->`Indirect`->`Data Analysis`-> Any Tab
2. Click `Multiple Input` and then `Add Workspace`
3. No option to keep the dialog open

### Platforms affected
All

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR changes the `Cancel` and `Ok` buttons for the buttons `Close` and `Add` in the dialog window used to add workspaces in the Multiple Input tab of MSDFit, ConvFit, IqtFit and F(Q)Fit. 
This option is different to the previous options because clicking `Add` will add the data but the dialog window will not be closed (previously, clicking `Ok` would add the data and then close the dialog).
`Close` will just close the dialog window without adding the data selected.

**To test:**
1.`Interfaces`->`Indirect`->`Data Analysis`->Any of the above interfaces
2. Select the `Multiple Input` tab
3. Click `Add Workspace`
4. Load in a data file seen below and select the spectra you want to load
5. Click `Add`. 
Make sure the dialog stays open, and that data is added to the table seen in the Multiple Input tab
6. Load different data/select a different spectrum
7. Click `Add` and ensure this data has also been added to the table. 

Clicking `Close` should then close the window.

**Data Files**
**MSDFit:**
[osi104367-104371_graphite002_red_elwin_eq.zip](https://github.com/mantidproject/mantid/files/2685812/osi104367-104371_graphite002_red_elwin_eq.zip)
[osi92762_graphite002_elwin_eq.zip](https://github.com/mantidproject/mantid/files/2685814/osi92762_graphite002_elwin_eq.zip)
**IqtFit:**
[iris26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2685817/iris26176_graphite002_red.zip)
[irs26173_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2685828/irs26173_graphite002_red.zip)

**ConvFit:**
[iris26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2685819/iris26176_graphite002_red.zip)
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2685825/irs26173_graphite002_res.zip)

**F(Q)Fit:**
[IN16B_125878_QLd_Result.zip](https://github.com/mantidproject/mantid/files/2685821/IN16B_125878_QLd_Result.zip)
[iris26174_graphite002_s0-17_Result.zip](https://github.com/mantidproject/mantid/files/2685822/iris26174_graphite002_s0-17_Result.zip)

Fixes #23813 

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by robertapplin** [comment]
@soininen Thanks for spotting this, I've just added it now

**Comment by soininen** [comment]
Instead of a 'Keep open' checkbox, `Cancel` and `OK`, would it make sense to have buttons `Add` and `Close` in the Indirect Data Selection dialog? `Add` would add the selected dataset to the analysis interface keeping the dialog open while `Close` would close the dialog. This would remove the need for the extra checkbox.

**Comment by SpencerHowells** [comment]
@soininen @robertapplin I suggested using 'Keep open' so that it looked like the Load gui. However your suggestion is probably neater.

**Comment by soininen** [comment]
It is just something that came to my mind while testing the interface. Maybe you could experiment with both if time permits? Anyway, for the code review I am perfectly fine with the check box as well. Let me know if you are going to make some changes here or whether I should just go on with the review.

**Comment by robertapplin** [comment]
@soininen I agree, having an `Add` and `Close` button rather than the checkbox would be a better solution. I will make this change

**Review by soininen — APPROVED** [review]
Adding data to the interface with the dialog works fine. I think the 'Add' and 'Close' buttons make the usage more fluid, but that's just a feeling I got while testing, I am not a heavy-duty user. Anyway, nice job! The code looks good and the release notes have been updated so I think this is good to go.

**Pull request merged**
