### PR TITLE
Python interface without ADS issues

### PR DESCRIPTION
**Pull request by SimonHeybrock**
#14685

This pull request is meant as a discussion platform for an alternative Python interface. For now it is probably quite incomplete, and this is just to get an idea what people think about this solution.

Basically this provides `mantid.experimental.pythonapi`. It should provide access to algorithms just like `simpleapi` does, but any workspace variable should behave like expected in Python. See the unit test for some examples.

I would be glad about input, e.g., about what cases I have not covered (I know about some special cases in `simpleapi.py` that I did not check yet, and there also might be issues with group workspaces), and about better ways to implement this (For example, I am unhappy about the `globals().update(vars(mantid.simpleapi))` call in `pythonapi.py`).

### CODE REVIEW

**Comment by martyngigg** [comment]
@SimonHeybrock Thanks for providing something concrete to discuss.

On the question of the `weak_ptr` handling, I had a thought the other day that maybe we should go the opposite way to what you've done here. The current implementation of `AnalysisDataService::retrieve` in python is to return a `weak_ptr. My thought was to return everything on the C++ side back to returning `shared_ptr`, as it would in C++, and implement something like a `to_weak_ptr()` function that would be able to convert the `shared_ptr` to a `weak_ptr` on request. The current `simpleapi` could then just use that on the values it returns. Everything else should then be able to operate exactly as in C++

**Comment by SimonHeybrock** [comment]
@martyngigg Your suggestion sounds good. But I suppose that should be part of a separate pull request, since it has little to do with what this one is trying to achieve?

**Comment by martyngigg** [comment]
@SimonHeybrock Yes I agree. I just thought I'd bring it up as you'd introduced the shared/weak converters here.

**Comment by martyngigg** [comment]
I think the biggest issue we will face here is how we want to go forward for scripts in the future. This api style is obviously much better in the console as the names are really quite useless then anyway. We do have to remember though that a large fraction of users will still use Mantid through the GUI. As MantidPlot is currently structured, this won't work well with the tools in there, e.g. plotting. This is arguably the fault of MantidPlot & other places in the code that are too reliant on how workspaces are named rather than just dealing with a pointer. It does also create a fundamental shift in how users interact with the workspaces on the GUI level.

Technically we can have many api styles of course but I think we have to make sure they work well with all of the tools we provide or we just end up with console scripts that don't work in the GUI or scripts that don't work well in the console.

I think this is a topic that is going to be discussed as part of the long-term plan but these changes do at least give us something tangible to play with to explore the issues.

**Comment by martyngigg** [comment]
Any thoughts @OwenArnold @peterfpeterson @stuartcampbell @rosswhitfield @FedeMPouzols?

**Comment by MichaelWedel** [comment]
One thing we discussed here at the office the other day was to introduce a check in both simpleapi and this experimental API on importing. When the other API is already loaded, the import should fail. Correct me if I'm wrong but shouldn't that disable loading the experimental API in the GUI?

**Comment by peterfpeterson** [comment]
I like the new one that @SimonHeybrock is suggesting, but I'm not sure about the legacy issues that Martyn raised. I think we are better off having one data access method though.

**Comment by OwenArnold** [comment]
@SimonHeybrock I also like this approach. I think this approach yields pythonic functionality as your unit tests demonstrate. Am I right in thinking that the algorithms still place the workspaces int the ADS, and they are cleared from the ADS with the weak pointers converted to a shared pointers? If so, would it be possible to bypass the ADS in the first place?

I think @martyngigg is right about co-existance of APIs an maybe @MichaelWedel's approach would be sufficient to stop misuse. However we want to get this API polished as possible as it will be the 3rd python API.

**Comment by MichaelWedel** [comment]
Some algorithms complain when a workspace does not have a name, if I remember correctly at least one source for this is calls to addOrReplace. I guess it's hard to bypass the ADS in those cases.

Reading Owens comment I had the following idea. If the problem is things being stored in the ADS, would it be possible to have an alternative ADS that does not store anything?

On 08 Dec 2015, at 18:21, Owen Arnold <notifications@github.com<mailto:notifications@github.com>> wrote:


@SimonHeybrock<https://github.com/SimonHeybrock> I also like this approach. I think this approach yields pythonic functionality as your unit tests demonstrate. Am I right in thinking that the algorithms still place the workspaces int the ADS, and they are cleared from the ADS with the weak pointers converted to a shared pointers? If so, would it be possible to bypass the ADS in the first place?

I think @martyngigg<https://github.com/martyngigg> is right about co-existance of APIs an maybe @MichaelWedel<https://github.com/MichaelWedel>'s approach would be sufficient to stop misuse. However we want to get this API polished as possible as it will be the 3rd python API.

**Comment by OwenArnold** [comment]
@MichaelWedel. You're right not all algorithms work correctly without having a name. However, no algorithms should depend on workspace names, or anything else that isn't explicitly passed in or out as a strongly typed object. I think the correct fix is to fix algorithms that breach these rules. I've generally been flagging these up where I find them, such as [here](https://github.com/mantidproject/mantid/issues/14642). Maybe we need to to hunt down the remaining violations.

**Comment by SimonHeybrock** [comment]
@OwenArnold You are right. My current solution is merely a workaround. I, too, would like to bypass the ADS completely since it is basically useless for what we are trying to do. Basically this implies that algorithms should not even know about the existence of the ADS?

**Comment by OwenArnold** [comment]
@SimonHeybrock. Yes, and I think there's lots of good reasons why an algorithm should never directly interact with the ADS. I'd go further and say that algorithms also shouldn't communicate directly with any SingletonHolder/DynamicFactory in Mantid.

If you find algorithms that talk to the ADS, I would suggest trying to establish who the author of that algorithm was and ask them to fix it.

**Comment by MichaelWedel** [comment]
A quick `grep -R AnalysisDataService::Instance * | grep -v -E -i "test|API" | wc -l` gives 125 occurences in `Framework`. So there are quite a few (I also wrote one of them).

**Comment by FedeMPouzols** [comment]
I could also claim a handful of ADS uses in algorithms. These ADS occurrences come in many cases from a perverse practice that we have with workspace groups, especially when the algorithm produces a group: the algorithms will check if you're creating a new group or adding workspaces to the group. This is then used for example to generate a sequence number for the individual workspaces. How could we overcome this? As with custom interfaces, there seems to be a tradition of using names of groups.

**Comment by gvardany** [comment]
@SimonHeybrock What is the status of this? Is it still relevant?

**Comment by SimonHeybrock** [comment]
@gvardany By coincidence, we just started a discussion on this this morning. So yes it is relevant, but it will never get merged, so I guess I can just close it.

**Pull request closed without merging**
