### PR TITLE
ISIS Powder HRPD extra TOF windows

### LINKED ISSUE #21149: Extra TOF windows for HRPD in ISIS Powder
HRPD use 2 TOF windows we weren't aware of when developing `isis_powder`: **10-50** and **180-280**. These should be added to the API and cropping windows should be determined for them.

### PR DESCRIPTION
**Pull request by josephframsay**
Cropping values for two TOF windows which were missed off the original requirements for HRPD have been added to the `isis_powder` library. Scientists can now focus runs for TOF windows 10-50 and 180-280.

**To test:**

As with all `isis_powder` stuff, setting up your directories is a bit fiddly - give me a shout if you need a hand, but the scripts should bark at you if you miss something out.
Setup with this script:
```
from isis_powder import HRPD
user = "Test"
calib_dir = "path/to/hrpd/calibration/directory"
out_dir = "path/to/hrpd/output/directory"
mapping_file = "path/to/attached/mapping/file"

hrpd = HRPD(user_name=user, 
            calibration_directory=calib_dir,
            output_directory=out_dir,
            calibration_mapping_file=mapping_file)
```

Some files you'll need are [here](https://github.com/mantidproject/mantid/files/1475170/HRPD.zip).

```
hrpd.create_vanadium(first_cycle_run_no=68236, do_absorb_corrections=False, window="10-50")
```
Make sure the 3 workspaces in the group `VanSplineData` are cropped from 1e4 to 5e4.

```
hrpd.create_vanadium(first_cycle_run_no=68236, do_absorb_corrections=False, window="180-280")
```
Make sure the 3 workspaces in the group `VanSplineData` are cropped from 1.8e5 to 2.8e5.

```
hrpd.focus(run_number=68262, window="180-280", 
           vanadium_normalisation=True, do_absorb_corrections=False)
```
Make sure the first workspace in `68262.raw-Results-TOF-Grp` is cropped from 1.86e5 to 2.8e5, the second from 1.8e5 to 2.798e5 and the third from 1.9e5 to 2.795e5,

```
hrpd.focus(run_number=68254, window="10-50",
           vanadium_normalisation=True, do_absorb_corrections=False)
```

Make sure the workspaces in `68254.raw-Results-TOF-Grp` are cropped from 1.2e4 to 4.99e4.

Fixes #21149 
Address part of #21148 

**Release Notes** 
[Here](https://github.com/mantidproject/mantid/pull/21197/commits/fe9fd8874e7dbf7ed40058f6dd763ca289a0c928)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by mantid-roman** [comment]
@josephframsay I guess I need a config file to run the script

**Comment by josephframsay** [comment]
@mantid-roman The script in the PR description should work with the data attached, as long as you have your directories set up correctly. What you need is:
```
/path/to/HRPD_directory/  -  calibration_directory
                              - hrpd_new_072_01_corr.cal (from the attached zip)
                              - 17_2 (directory)
                                  - hrpd_new_072_01_corr.cal (from the attached zip)
                          -  output_directory
                              - 17_2 (directory)
                          - cycle_mapping.yaml (from the attached zip)
```
Let me know if this doesn't work - it can be a right pain getting everything in the right place

**Comment by mantid-roman** [comment]
Yes, it worked. I was just confused by the message I saw.

**Comment by josephframsay** [comment]
Ah, I see. Using a config file is optional (explained [here](http://docs.mantidproject.org/nightly/techniques/ISISPowder-Tutorials.html#using-configuration-files)), so the warning that one wasn't passed is cool, as all the parameters that were needed got passed from the script instead

**Review by mantid-roman — APPROVED** [review]
Works good

**Pull request merged**
