### PR TITLE
DensityOfStates UI

### PR DESCRIPTION
**Pull request by DanNixon**
This is Trac ticket: http://trac.mantidproject.org/mantid/ticket/10298

To test open Indirect > Simulation > DensityOfStates, and load simulations with the `squaricn.phonon` and `squaricn.castep` files in test data folder, instructions can be found on QtHelp documentation.

### CODE REVIEW

**Comment by eXeC64** [comment]
Jenkins, test this please.

**Comment by DanNixon** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
I've found a few issues:

* Running with Raman against `squaricn.phonon` yields a `Attempt to assign to Property (Temperatue) of incorrect type` exception.
* Indentation - If you skim through the diff you'll notice there's some strange indentation going on. Tabs are used in some files entirely, mixed tabs and spaces in others, etc.
* Typo in documentation `fatcor`: https://github.com/mantidproject/mantid/pull/164/files#diff-b719af76d6bec1255bdd1ad393f155f1R128

Other than the aforementioned, it looks good.

**Comment by DanNixon** [comment]
Jenkins, retest this please.

**Pull request merged**
