### PR TITLE
Require Python mock as a developer dependency

### PR DESCRIPTION
**Pull request by martyngigg**
Description of work.

Bring in Python mock package as a developer dependency.

**To test:**

On Windows check you can `import mock` in Python.

The other OSs will need to have the packages installed.

*No issue*

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
Merge note: Please merge mantidproject/third-party-msvc2015#12 when this is merged.

**Comment by peterfpeterson** [comment]
LGTM. The package names are correct for rhel and fedora.

**Comment by AntonPiccardoSelg** [comment]
LGTM too. Tested on Windows. After running cmake which pulled the changes, I was able to import mock without any issues. 

What do we need to do for OSX?

**Comment by martyngigg** [comment]
In order to merge it we don't need to do anything else as it's only a dependency that can now be thought of as available everywhere.

We will need to install the mock package from the repos on Linuxes and from pip on macOS (I've updated the instructions https://github.com/mantidproject/mantid/wiki/Building-Mantid-on-OS-X-10.10-&-10.11-using-clang-and-Xcode)

**Pull request merged**
