### PR TITLE
Indirect Data reduction use the same syntax as GroupDetector algorithm

### LINKED ISSUE #22858: Indirect data reduction fails
* You will need : `IRS21360.raw ` from the ISIS-Data set
* Open `Indirect` > `Data Reduction`
* Settings:
    * `Instrument` : `IRIS`
    * `Analyser` : `Graphite`
    *  `Reflection` : `002`
    *  `Run Files` : `21360` - note, if the file location is not on the Mantid path, then browse manually
    *  Click `Run`

```
No registered converter was able to produce a C++ rvalue of type class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > from this Python object of type NoneType
  at line 257 in 'C:/Users/BTR75544/nightly/MantidInstall/plugins/python/algorithms\WorkflowAlgorithms\ISISIndirectEnergyTransfer.py'
  caused by line 590 in 'C:/Users/BTR75544/nightly/MantidInstall/scripts/Inelastic\IndirectReductionCommon.py'
  caused by line 670 in 'C:/Users/BTR75544/nightly/MantidInstall/scripts/Inelastic\IndirectReductionCommon.py'
Unknown error starting next batch algorithm
Got error from algorithm "ISISIndirectEnergyTransfer"
Stopping batch algorithm because of execution error
```

### PR DESCRIPTION
**Pull request by ElliotAOram**
**Description of work.**

This is an additional part of the fix for #22858. The original PR stopped the crash behaviour however, without this PR, the custom grouping option in the interface does not perform any of the grouping operations as expected. This is a small change that will allow users to use the same syntax for the group detectors algorithm in the custom grouping field.

**To test:**

* Open mantid plot
* Open the Indirect data reduction interface (Interfaces > Indirect > Data Reduction)
* Enter the run number 21360 (this can be found in the unit test data) into the Run Files field
* Change the Detector Grouping mode to Custom.
* Leave the field empty and click Run
* See that a dialog box with an appropriate error message is produced.
* Try out different [custom grouping patterns](http://docs.mantidproject.org/nightly/algorithms/GroupDetectors-v2.html#groupingpattern) and ensure that you get the number of spectra in the output workspace that you would expect

Fixes #22858

*No release notes required*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by ElliotAOram** [comment]
@keeeto @NickDraper what are the chances of getting this into 3.13?

**Comment by NickDraper** [comment]
@ElliotAOram Good if we can get it tested and merged today

**Comment by SpencerHowells** [comment]
Testing must also include:
Select Grouping  Mode > Groups
Number of Groups = 10
Output workspace should have 11 spectra. The first 10 with 5 detectors with the last just 1.
Best to use Show Detectors for this

**Review by NickDraper — CHANGES_REQUESTED** [review]
Code review is good, functionality is good.

However the interface docs page is now a bit out of date and a change like this needs to be in the release notes.

**Comment by NickDraper** [comment]
Current doc in the interface page:

### Custom
A comma separated list can be entered to specify the groups, e.g. 1, 3-5, 6-8, 10.

**Comment by ElliotAOram** [comment]
@NickDraper This should be good to go now providing you are happy with doc changes.

**Review by NickDraper — APPROVED** [review]

**Pull request merged**
