### PR TITLE
MantidAxType not JSON serializable

### LINKED ISSUE #31775: MantidAxType is not JSON serializable
There is a persisting warning message: 'Unknown error occurred. Full detail: Object of type 'MantidAxType' is not JSON serializable' when bin plots are being displayed in the workbench and checkpoints for project recovery are being created.

### Expected behavior

No warning message, more helpful error feedback for the user?

### Actual behavior

Recurring warning: : 'Unknown error occurred. Full detail: Object of type 'MantidAxType' is not JSON serializable'

### Steps to reproduce the behavior
1. Create a plot bin, e.g. by loading any raw D7 data from UnitTest/ILL/D7
2. Make sure your project recovery is enabled
3. Wait until an attempt is made to create a checkpoint, observe the warning message.

### Platforms affected
Observed on Debian-derived Linux distributions

### PR DESCRIPTION
**Pull request by darominski**
This PR addresses the issue of the `MantidAxType` not being JSON serializable and thus causing a stream of warnings which some of our users found confusing. The proposed solution replaces the value stored in the 'axis' variable which is a part of the creation_args dictionary that is being JSON serialized. The value of type `MantidAxType` is replaced with its value, which currently is of integer type, which is serializable. 

**To test:**

To test whether the proposed solution removes the warning:
1. In the workbench, create a bin plot, e.g. using UnitTest/ILL/D7/396940.nxs
2. Make sure that the project recovery is enabled, you may want to lower the delay between checkpoints 
3. Wait until project recovery is triggered
4. There should be no  'Unknown error occurred. Full detail: Object of type 'MantidAxType' is not JSON serializable' warning anymore.

To test whether it does not break loading back the bin plots:
5. Save the project with the bin plot open
6. Close everything and reload.
7. The bin plot should exist and look just like at the moment of saving.

Notice: If you created a plot from a workspace group with only one workspace, saving the project seems to flatten it to a workspace, thus breaking the connection of the plot to the original workspace and in such a case, the bin plot (or any plot for the matter) will not be properly created.

Fixes #31775 . 

Release note mention added.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by clayton-tom — DISMISSED** [review]
Fix works as described :+1:

**Comment by gvardany** [comment]
Can you fix the conflict please?

**Comment by darominski** [comment]
> Can you fix the conflict please?

Conflict removed.

**Comment by darominski** [comment]
@clayton-tom Since the conflict has been removed, could you please re-approve?

**Review by gvardany — DISMISSED** [review]
Re-approving as the original reviewer has left the project.

**Comment by darominski** [comment]
> Re-approving as the original reviewer has left the project.

Another conflict fixed... could you re-approve please?

**Review by gvardany — APPROVED** [review]

**Pull request merged**
