### PR TITLE
Muon Manual Background Corrections

### LINKED ISSUE #31815: Muon Corrections Tab - Add ability for Manual Background Corrections
### Description
There will be several modes for Background corrections as found on WIMDA: `None`, `Auto` and `Manual`. This issue is to create the `None` and `Manual` modes. The `Manual` mode should only allow a Flat background correction, but will allow you to change the starting parameter of the Flat background.

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR adds the ability to do Manual background corrections in the Muon Analysis and FDA interfaces.

This feature is a requirement of the WIMDA Replacement project.

**To test:**
Open Muon Analysis
Load PSI 1249
Go to Corrections tab and select `Manual` background corrections
The background column should be enabled, and the status column should say 'No background corrections'
Change the background to a non-zero value. The correction should be applied and the status label updated to 'Correction success'
Try only changing the background for a single domain
Try the display options for displaying the data
Make sure auto corrections still work as expected

Fixes #31815

*No release notes are required because **I will add them in a separate PR along with other release notes for the new model fitting feature**.*

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
If I enter a negative background value I get a pop up talking about the auto mode, which could be a bit confusing.

**Comment by AnthonyLim23** [comment]
If I enter some value for the BG correction in manual mode, then change runs all of the BG values change. We should keep the old values (they might be from a calibration run or something).

**Comment by robertapplin** [comment]
> If I enter some value for the BG correction in manual mode, then change runs all of the BG values change. We should keep the old values (they might be from a calibration run or something).

Which run numbers did you switch between and which instrument? I tried switching from `MUSR62260` to `MUSR62261`, and then tried `Load Current Run`, but the old background values are being reused as expected

**Comment by AnthonyLim23** [comment]
It seems to work now, I must have got into a funny state.

**Comment by robertapplin** [comment]
@AnthonyLim23 its ready for another look, and I've added the unit tests now

**Comment by AnthonyLim23** [comment]
do we need to add anything to the release notes?

**Comment by robertapplin** [comment]
> do we need to add anything to the release notes?

I was planning on adding release notes for background corrections and model fitting in a separate PR to avoid conflicts

**Review by AnthonyLim23 — APPROVED** [review]
looks good and completes the BG subtraction work needed for analysing PSI data

**Pull request merged**
