### PR TITLE
IndirectILLReductionFWS doc test cleanup

### LINKED ISSUE #23148: IndirectILLReductionFWS seg fault on system test
The IndirectILLReductionFWS doc tests has a segmentation fault when running on the build server.

### PR DESCRIPTION
**Pull request by gvardany**
**Description of work.**
Another attempt to mitigate the unreproducible segfault in doc test.
Does the cleanup without ADS.
The issue is often blocking other PRs, therefore high priority.

**To test:**

Doc tests pass.

 
Fixes #23148.

This does not require release notes, since it is an internal change.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by reimundILL** [comment]
All tests have passed and I rebuild Ubuntu + Doc Tests again.

**Comment by reimundILL** [comment]
All tests passed again and I rebuild Ubuntu + Doc Test once more.

**Comment by martyngigg** [comment]
I think I have found the underlying issues with these tests in #23417. I've rebuilt several times in that pull request and had no failures. It looks like the issues were related to stack and heap corruption and then when tcmalloc tries to free memory it segfaults. Apparently the memory freeing was always happening around the `IndirectILLReductionFWS` test.

**Comment by gvardany** [comment]
Ok, that's good news. Let's hope that will fix the issue permanently. This one can still be merged though.

**Comment by gvardany** [comment]
If so, should you close issue #23148 in your PR?

**Comment by martyngigg** [comment]
Thanks. I hadn't spotted that issue. I'll add the reference now.

**Review by martyngigg — APPROVED** [review]

**Pull request merged**
