### PR TITLE
New algorithm to correct TOF according to the fitted EPP

### PR DESCRIPTION
**Pull request by mganeva**
This is the last step of the refactoring of the TOFTOF data reduction workflow. The CorrectTOF algorithm applies correction according to the fitted elastic peak position. This will allow for deprecation of the algorithm TOFTOFConvertTofToDelaE (it will be replaced by CorrectTOF + ConvertUnits + ConvertToDistribution).
The corrected TOF is calculated in a similar way to ConvertEmptyToTof. This might make this algorithm usefull also for ILL instruments.
**To test:**

Review the source code, tests and documentation. The algorithm can be tested on the sample workspaces in a following way:

``` python
ws = CreateSampleWorkspace(Function="User Defined", UserDefinedFunction="name=LinearBackground, \
                                               A0=0.3;name=Gaussian, PeakCentre=8123.34, Height=5, Sigma=75",
                                               NumBanks=1,
                                               BankPixelWidth=1, XMin=6005.25, XMax=9995.75, BinWidth=10.5,
                                               BankDistanceFromSample=4.0, OutputWorkspace="ws",        
                                               SourceDistanceFromSample=1.4)

lognames = "wavelength,TOF1"
logvalues = "6.0,2123.34"
AddSampleLogMultiple(ws, lognames, logvalues)
# create EPP table
# after the PR 15962 will be merged, the table can be created with FindEPP algorithm
table = CreateEmptyTableWorkspace(OutputWorkspace="epptable")
table.addColumn(type="double", name="PeakCentre")
table_row = {'PeakCentre': 8128.59}
for i in range(ws.getNumberHistograms()):
    table.addRow(table_row)

wscorr = CorrectTOF(ws, table)
```

Fixes #xxxx.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
The pylint build had failed here because of a violation in an unrelated file. I've restarted the builds and hopefully they'll go well now.

**Comment by FedeMPouzols** [comment]
@mganeva: FitGaussianTest fails on RHEL6:
```
10:18:59 DeleteWorkspace-[Notice] DeleteWorkspace successful, Duration 0.00 seconds
10:18:59 
10:18:59 ======================================================================
10:18:59 ERROR: Conditions that raise RuntimeError.
10:18:59 ----------------------------------------------------------------------
10:18:59 Traceback (most recent call last):
10:18:59   File "/home/builder/Jenkins/workspace/pull_requests-rhel6/Framework/PythonInterface/test/python/plugins/algorithms/FitGaussianTest.py", line 32, in test_errors
10:18:59     with self.assertRaises(RuntimeError):
10:18:59 TypeError: failUnlessRaises() takes at least 3 arguments (2 given)
10:18:59 
10:18:59 ======================================================================
10:18:59 ERROR: Test that generated Gaussian peaks are reasonably well guessed.
10:18:59 ----------------------------------------------------------------------
10:18:59 Traceback (most recent call last):
10:18:59   File "/home/builder/Jenkins/workspace/pull_requests-rhel6/Framework/PythonInterface/test/python/plugins/algorithms/FitGaussianTest.py", line 63, in test_guessedPeaks
10:18:59     self._guessPeak(2,10,.7)
10:18:59   File "/home/builder/Jenkins/workspace/pull_requests-rhel6/Framework/PythonInterface/test/python/plugins/algorithms/FitGaussianTest.py", line 57, in _guessPeak
10:18:59     self.assertLess(diffPeakCentre,.03)
10:18:59 AttributeError: 'FitGaussianTest' object has no attribute 'assertLess'
10:18:59 
10:18:59 ======================================================================
10:18:59 ERROR: Cases where fit is not possible.
10:18:59 ----------------------------------------------------------------------
10:18:59 Traceback (most recent call last):
10:18:59   File "/home/builder/Jenkins/workspace/pull_requests-rhel6/Framework/PythonInterface/test/python/plugins/algorithms/FitGaussianTest.py", line 41, in test_noFit
10:18:59     self.assertTupleEqual((0.0,0.0), fitResult)
10:18:59 AttributeError: 'FitGaussianTest' object has no attribute 'assertTupleEqual'
10:18:59 
10:18:59 ----------------------------------------------------------------------
```
This is not really the fault of this code, but unfortunately we still have to support RHEL6 which has an ancient Python (2.6). It does not support many of the assert methods of more modern versions of unittest. You can see the asserts that were introduced with Python 2.7 in several tables here: https://docs.python.org/2.7/library/unittest.html#test-cases

**Comment by mganeva** [comment]
@FedeMPouzols Thanks! I will correct the test.

**Comment by mganeva** [comment]
I will appreciate if someone would review this pull request this week. Since next week I will be away until the end of May.

**Comment by OwenArnold** [comment]
@ianbush, Marina mentioned that this could be useful at the ILL. It might be a good idea for the PR to be verified in Grenoble. Do you have time to do this?

**Comment by ianbush** [comment]
@OwenArnold @mganeva Sure, no problem, I will try and take a look later today.

**Comment by ianbush** [comment]
The CorrectTOF algorithm looks good and works as expected in examples given. There are unit tests in place and the documentation seems clearly written. :shipit:

**Pull request merged**
