### PR TITLE
Fixes Dynamic Kubo Toyabe crash

### LINKED ISSUE #31926: Stop Dynamic Kubo Toyabe fitting crashing if bin width outside acceptable range
### Expected behavior
When using the Dynamic Kubo Toyabe fitting on MUSR if you enter a bin width <0.001 or >0.100 an exception should be thrown and error message provided for user. Found during testing for #31900 .

### Actual behavior
Mantid is crashing.

### Steps to reproduce the behavior
1. Open Muon Analysis GUI
2. Load a run
3. Click on fitting tab and add the Dynamic Kubo Toyabe fit function
4. Change the bin width to 0.5

### Platforms affected
Windows 10 (but likely to be all)

### PR DESCRIPTION
**Pull request by sf1919**
**Description of work.**
A try-catch statement has been added to deal with the exception being thrown when the BinWidth provided is outside the acceptable range. The BinWidth will revent to the last viable value eneterd. In addition to this the exception is being logged so the user is now aware why their change was not implemented.

**To test:**

1. Open Muon Analysis GUI
2. Load a run
3. Open the fitting tab
4. Right click in empty Property/Value table to add a function
5. Search for DynamicKuboToyabe and select
6. The Bin Width should show as 0.050.
7. Change the bin width to any 2 decimal number between 0.01 and 0.10 . The table should update to the new value ready for fitting
8. Change the bin width to a negative number. This should throw an exception with the log message 'DKT: Attribute BinWidth cannot be negative.' The BinWidth should revent to the number you used in step 7.
9. Change the bin width to a value smaller than 0.001.  This should throw an exception with the log message 'DKT: Attribute BinWidth too small (BinWidth < 0.001).' The BinWidth should revent to the number you used in step 7.
10.  Change the bin width to a value larger than 0.1.  This should throw an exception with the log message 'DKT: Attribute BinWidth too large (BinWidth > 0.1).' The BinWidth should revent to the number you used in step 7.

Fixes #31926  

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DavidFair** [comment]
So I'm just reviewing this as it's marked high priority. As it's a bug for a high priority crash I wanted to double check if this is something users are running into and do we possibly need a patch release?

**Review by DavidFair — APPROVED** [review]
This correctly resolves the problem, it correctly handled large / tiny / negative values

**Comment by sf1919** [comment]
> 
> 
> So I'm just reviewing this as it's marked high priority. As it's a bug for a high priority crash I wanted to double check if this is something users are running into and do we possibly need a patch release?

I will defer to @AnthonyLim23 on that. It wasn't spotted by a user so may not need a patch release.

**Comment by AnthonyLim23** [comment]
I have not had any complaints from users about the crash. However, that might be because they are on holiday. 

I would say if we are making a patch anyway, its worth including. However, it does not warrant a patch itself.

**Comment by martyngigg** [comment]
I've added the patch candidate label so we will find it if we do make a patch release.

**Pull request merged**
