### PR TITLE
c and c++ compiler version may be different and hence their allowed compiler options

### LINKED ISSUE #21329: Build failure with gcc , when version of gcc and g++ differ.
With gcc-6 and g++-7, building maintid fails in the make step (that is after cmake configure), because gcc-6 does not recognize the warning option "-Wimplicit-fallthrough". 

This is because the variable GCC_C_COMPILER_VERSION , set in GNUSetup.cmake only 
depends on CMAKE_CXX_COMPILER_VERSION, and does not check CMAKE_C_COMPILER_VERSION.

### Expected behavior
expected make to finish the build

### Actual behavior
build compilation step fails to build minigzip.c

### Steps to reproduce the behavior
cmake; make

### Platforms affected
All with gcc-6 and g++-7 as default compilers

### PR DESCRIPTION
**Pull request by ebknudsen**
Introduces a test in cmake's code-configuring step that takes the most conservative choice for compiler options, as the c version and c++ compiler options may be different.

In the particular case gcc was 6.4 and g++ 7.2 which leads to compilation failure since the "-Wimplicit-fallthrough" option is unknown to gcc-6.

**To test:**

Fixes #21329. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by quantumsteve** [comment]
@ebknudsen When would this situation normally come up? Is it something we want to actively support?

**Comment by ebknudsen** [comment]
I honestly don't know when this normally comes up, nor if it commonly happens.
I happens to be the case on my system (debian testing/buster) and I could make a fix for it without too much effort :-), which I thought I'd share. 
IMHO the present situation where all the configure checks pass but the compile fails due to version mismatch, is not desirable. It is better for configure to fail with a message on version mismatch - is that preferrable? 
I suppose another option to avoid the compiler flag entirely - IMHO it issues a warning about a standard language construct which is more often used by choice than by accident.

**Comment by quantumsteve** [comment]
It looks like [gcc-7](https://packages.debian.org/buster/gcc-7) is available for debian testing/buster and g++-7 requires it. Hopefully there's a better workaround than manually specifying the C and C++ compilers.

My preference would be for configure to fail with a message about the version mismatch.

**Comment by ebknudsen** [comment]
Cool. I have commited an edit to this effect. CMake will now fail to configure if gcc and g++ version don't match.

**Review by quantumsteve — APPROVED** [review]
Adds a useful error message during configuration.

**Comment by quantumsteve** [comment]
This only only potentially causes an error in the configure stage. The build server failures are unrelated.

**Pull request merged**
