### PR TITLE
Speed up Windows installer creation

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**

~~Shinks the Windows bundle down by 10% by enabling SOLID compression, tweaking the dictionary size
Reduces the build time by using all cores to byte-compile, and disabling data optimization (which saves at most 1% more over LZMA)~~

Edit: See comments below on why I've changed this PR approach

This PR simply adds the -j0 threads flag introduced recently to use all available cores whilst byte-compiling the ever-increasing number of Python files 
**To test:**

- Download the Mantid installer from CI
~- Compare it to a recently master nightly build for file size~
- Ensure it still installs / starts locally

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
I tried generating an installer using the build package option but it failed. Have you seen this before? I've put the failed build log at `\\Olympic\Babylon5\Scratch\MartynGigg\nsis-failed-build` if it helps? Could it be an older NSIS version?

**Comment by DavidFair** [comment]
Looking at the logs I see this:
`Generating uninstaller... Internal compiler error #12345: deflateInit() failed(initialization failed [-2]).`

So it looks like the compression step failed - I suspect that the new compression options are exhausting the 32 bit address space of makensis (which I'm just coming below locally), let me see if there is an easy workaround

**Comment by DavidFair** [comment]
Doing some further digging, the LZMA compression included is older (~2010) and only runs in 32-bit mode so we run into memory issues depending on the size of the files to package

Interestingly more modern NSIS forum threads refer to packaging the files up separately using 7z direct, then using NSIS plugins to extract them. Testing locally I can further shrink down from 150MB to 100MB using 7z directly (and it's significantly faster, as LZMA2 is multithreaded).

I'm going to tweak this PR to only include the multi threaded byte-compiling and come back to it in the future once I figure out the required NSIS / CMake changes

**Review by martyngigg — APPROVED** [review]
Confirmed that the package still builds and starts successfully.

**Comment by martyngigg** [comment]
I just accidentally auto merged this when I didn't mean too as I just realised I was the first reviewer 🤦🏻 
It's pretty non-contraversial though...

**Comment by DavidFair** [comment]
Ahh does the auto merge not have an option for a minimum of two reviews including approved?

**Comment by martyngigg** [comment]
It's based on the current branch settings. We only have 1 review required to avoid gatekeepers have to hit extra buttons unnecessarily when merging.

**Pull request merged**
