### PR TITLE
Muon Analysis bug that disabled fit menu

### LINKED ISSUE #22160: Muon analysis disabling browser
Open muon analysis and turn on multi fitting (in settings tab)
Go to data analysis and add a fitting function
See that in the fit menu the options are all enabled
Go to any other tab
Go back to data analysis
The options in the fit menu are disabled 

This is due to https://github.com/mantidproject/mantid/pull/22058/files being over zealous

### PR DESCRIPTION
**Pull request by AnthonyLim23**
The fit menu was being disabled when users changed tabs in Muon Analysis

**To test:**
Open muon analysis
Make sure there is no auto background (in Mantid preferences, if in doubt ask Nick)
Load some data (any)

Go to settings and make sure multiple fitting is off
Go to data analysis and the function browser should be empty
Check the fit menu is disabled (mostly) 
Add a fitting function (any) and do a fit
Change tab
Go back to data analysis 
Check that the fit menu is not disabled.

Go to settings and make sure multiple fitting is on
Go to data analysis and the function browser should be empty
Check the fit menu is disabled (mostly) 
Add a fitting function (any) and do a fit
Change tab
Go back to data analysis 
Check that the fit menu is not disabled.

Close muon analysis and turn on the auto background
Reopen muon analysis
Load some data (any)

Go to settings and make sure multiple fitting is off
Go to data analysis and the function browser should be contain the auto background function
Check the fit menu is not disabled
Do a fit
Change tab
Go back to data analysis 
Check that the fit menu is not disabled.

Go to settings and make sure multiple fitting is on
Go to data analysis and the function browser should be empty
Check the fit menu is disabled (mostly) 
Add a fitting function (any) and do a fit
Change tab
Go back to data analysis 
Check that the fit menu is not disabled.

Fixes #22160. 

**Release Notes** 

In release notes
---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by soininen** [comment]
The test instructions say 'Go to data analysis and the function browser should be empty'. However, there is an empty `CompositeFunction` there. Is this intentional?

**Comment by soininen** [comment]
If I quit MantidPlot while the auto background and multiple fitting options are enabled, the background function does not appear in the Data Analysis tab after restarting MantidPlot and loading the data.

**Comment by AnthonyLim23** [comment]
There should be no function to fit (in multiple fitting mode). Could you stick up a screen shot?

The second one is ok, as you will still be in multiple fitting mode

**Comment by soininen** [comment]
There seems to be a bug in MantidPlot: I needed to wipe my settings file to get the auto background set back to 'None'. Anyway, here is the screenshot (auto background and multiple fitting off):
muon-analysis-composite-function

**Comment by AnthonyLim23** [comment]
that is what mantid currently does (checked on 3.11)

**Review by soininen — APPROVED** [review]
Could not make the entries in the Fit menu disabled with the different combinations of multiple fitting and automatic background.

**Comment by AnthonyLim23** [comment]
this is the issue for the preferences https://github.com/mantidproject/mantid/issues/22125

**Pull request merged**
