### PR TITLE
Indirect - ElasticWindowMultiple - Read temperature sensor names from instrument parameter files

### LINKED ISSUE #21771: Indirect - ElasticWindowMultiple - Add and read temperature sensor names from IPF files
The sample changer temperature sensor names have been changed on the Indirect instruments, as a result the ElasticWindowMultiple algorithm, which has implemented the names as constants, no longer functions as expected.

In order to fix this issue, the names of the temperature sensors should be added to the IPFs and read from the ElasticWindowMultiple algorithm.

### PR DESCRIPTION
**Pull request by brandonhewer**
Currently, the ElasticWindowMultiple algorithm contains constant values for the expected names of the sample changer temperature sensors. These values have recently been updated, resulting in ElasticWindowMultiple being unusable in its existing state.

The (correct) temperature sensor names have been moved to the instrument parameter files within this PR and ElasticWindowMultiple has been modified to read these names from the appropriate IPF file.

**To test:**
1. Navigate to Interfaces > Indirect > Data Analysis > Elwin.
2. Provide the supplied file in the 'Input File' field.
3. Ensure the 'Normalise by Temp.' check-box is checked.
4. Enter ```position``` into the SE Log Name field. 
5. Click 'Run'.
6. Ensure a 'Position not found in workspace.' warning is not produced.

**Test File:**
[iris77551_graphite002_red.zip](https://github.com/mantidproject/mantid/files/1781677/iris77551_graphite002_red.zip)

Fixes #21771 . 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by ElliotAOram** [comment]
@brandonhewer is this ready to test? And if so, could you add the "supplied file" to the PR so I can test it?

**Comment by brandonhewer** [comment]
@ElliotAOram I just need to get a new data file for this test since it uses the new temperature sensor names.

**Comment by ElliotAOram** [comment]
@brandonhewer sure just let me know when it's ready to test.

**Comment by ElliotAOram** [comment]
The supplied testing file does not pass validation. The interface initially rejects the file due to absence of `_red` or `_sqw` suffix. If I override this, the interface errors when I click run as the workspace is not in units `DeltaE`. Could you check that this file is correct when you have time @brandonhewer ? Thanks

**Comment by brandonhewer** [comment]
@ElliotAOram This is my fault, I forgot to first reduce the data, I'll update the test file! 😄

**Comment by brandonhewer** [comment]
Test data has now been updated.

**Review by ElliotAOram — CHANGES_REQUESTED** [review]
When I check the `Normalise to Lowest Temperature` option and put `position` in the `SE log name` field, I get the following error in the results log.
```
Error in execution of algorithm ElasticWindowMultiple:
could not convert string to float: T1
  at line 190 in 'C:/Users/hvq65228/Documents/git/mantid/Framework/PythonInterface/plugins/algorithms\WorkflowAlgorithms\ElasticWindowMultiple.py'
  caused by line 308 in 'C:/Users/hvq65228/Documents/git/mantid/Framework/PythonInterface/plugins/algorithms\WorkflowAlgorithms\ElasticWindowMultiple.py'
  caused by line 181 in 'C:/Users/hvq65228/Documents/git/mantid/Framework/PythonInterface/plugins/algorithms\WorkflowAlgorithms\ElasticWindowMultiple.py'
Unknown error starting next batch algorithm
Got error from algorithm "ElasticWindowMultiple"
Stopping batch algorithm because of execution error
```

**Review by ElliotAOram — APPROVED** [review]
Functionality is working now (no warning produced) and I can't find a way to break this at all so good to merge!

**Pull request merged**
