### PR TITLE
Fix bug seen when remote directory not in data search path

### LINKED ISSUE #17973: Muon interface looks for workspace that doesn't exist
*Reported by Steve Cottrell, Mantid 3.8*

#### Expected behaviour
Muon Analysis interface works as designed

#### Actual behaviour
Bug seen when following the steps below:

#### Steps to reproduce the behaviour
- Load current run on the Home tab (requires that you are using Windows and are on the ISIS network)
- Go backwards a few runs using the 'back' button
- Go to the "data analysis" tab
- Tick several group checkboxes and attempt to fit. Problems seen:
  - Simultaneous fit label is "0", not the real run number
  - Red star next to run number box
  - Exception - cannot find workspace `MuonSimulFit_0_Workspaces`

capture

### PR DESCRIPTION
**Pull request by tom-perkins**
This fixes a bug seen by users when fitting data loaded via "Load current run", when the directory the data was loaded from isn't in Mantid's data search path.

Now, "load current run" automatically adds the remote directory for the relevant instrument to the data search directories when it is clicked.

As part of this, added "pre-fit checks" that make sure everything is in a valid state before doing the fit. Tests have been added for the new functionality, and a section has been added to the [developer documentation](https://github.com/mantidproject/mantid/blob/549778a7c7548b318df06030b7f993c02b1b6450/docs/source/interfaces/Muon_Analysis_developers_guide.rst#sequence-of-events-when-fit-clicked) explaining the sequence of events when "Fit" is clicked.

**To test:**

**Must test on Windows and on ISIS network**

- Open *Interfaces/Muon/Muon Analysis*
- Use "Manage Directories" to ensure that `\\MUSR\data` is **not** in your list of data search directories. If it is, then remove it.
- Select instrument MUSR and click "Load current run"
- Now `\\MUSR\data` should be in your list of data search directories
- Go to the *Data Analysis* tab. In the central section:
(Note the fields will not be filled out with this data, this is an example picture)
dataselector
  - Check another "groups" checkbox as well as the one already selected
  - There should not be any red star next to the "Runs" box
  - The "Label for simultaneous fit" should be the run number, not zero
  - Running the fit should succeed (note that the graph will not be updated automatically)

Fixes #17973.

[Release notes](https://github.com/mantidproject/mantid/blob/549778a7c7548b318df06030b7f993c02b1b6450/docs/source/release/v3.9.0/muon.rst#id1) have been updated.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
Tested following instructions:

- After clicking on "Load current run" I can see that `\\MUSR\data` has been added to the list of data search directories. The run loaded was 61335.
- However, when I go to the *Data Analysis* tab I see the run that was previously loaded with a red star (the error message is "unable to find file"):

muonanalysis

If I change the run number to the one in the PR description, i.e. 20918, the red star disappears and I can fit the data successfully. I assume it should work with run number 61335 too?

**Comment by tom-perkins** [comment]
Thanks for testing! I think the problem in this case is that the current run is first saved under a name like `MUSRauto_E.tmp` while being recorded, and only later renamed. (I just looked in `\\MUSR\data` and there is still no file called `MUSR00061335.nxs` at the moment). 

I think this needs a special case to handle the current run before the NeXus file is saved, I will look into how this can be done.

**Comment by raquelalvarezbanos** [comment]
OK, thanks Tom. I am unassigning myself as I am on leave tomorrow and Friday, and will not be able to look at this.

**Comment by tom-perkins** [comment]
Added special handling for the case when the current run is loaded, but the file still has its temporary name on the remote server (e.g. `MUSRauto_A.tmp`) and has not yet been saved under its real name. 

This involved passing an optional filename in. Tests have been updated for this new behaviour.

**Comment by Anders-Markvardsen** [comment]
will not manage to look at this before end of today - but have put a note to pick it up on the 5th Jan next unless where this issue has not been dealt with before then

**Comment by raquelalvarezbanos** [comment]
I tested this again and it seems to be working now. :shipit: when all tests pass

**Pull request merged**
