### PR TITLE
IndirectSimulations - NMoldyn4Interpolation algorithm

### LINKED ISSUE #17289: Indirect Simulations - NMoldyn4Interpolation algorithm
Add NMoldyn4Interpolation algorithm. This algorithm maps NMoldyn simulated s(q,e) data onto OSIRIS Q and E values.
This algorithm has been written by Alex Phimister (MSG summer student)

### PR DESCRIPTION
**Pull request by louisemccann**
Add NMoldyn4Interpolation algorithm. This algorithm maps NMoldyn simulated s(q,e) data onto OSIRIS Q and E values.
This algorithm has been written by Alex Phimister (MSG summer student)

**To test:**

Go through examples [here](https://github.com/mantidproject/mantid/blob/2284c4c6489ce039beb04d7a5fed83fb7389b6cc/docs/source/algorithms/NMoldyn4Interpolation-v1.rst)

Fixes #17289 .

[RELEASE NOTES](https://github.com/mantidproject/mantid/blob/0ee850e770e05af6d2e2e052508e164c7ed571fd/docs/source/release/v3.8.0/indirect_inelastic.rst)

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by SpencerHowells** [comment]
The description refers to Q & energy values for Osiris. I assume it will work for any instrument.

**Comment by louisemccann** [comment]
According to the documentation Alex provided the algorithm currently only supports OSIRIS experimental data

**Comment by DavidFair** [comment]
I've marked this as in progress as we try to figure out what is causing the big discrepancies on RHEL 6

**Comment by DavidFair** [comment]
Following discussions with @SpencerHowells we confirmed there are no users of this script on RHEL 6. Instead of trying to diagnose the discrepancy with RHEL 6 (I suspect older Python/Numpy) we have disabled the test for this platform and print a warning to anyone using NMoldyn4Interpolation with Python 2.6 or below.

**Review by dtasev — CHANGES_REQUESTED** [review]
Documentation examples don't run in Mantid Script Window

**Review by dtasev — APPROVED** [review]

**Comment by DimitarTasev** [comment]
Everything looks good :shipit:

**Comment by AndreiSavici** [comment]
Please merge master into the branch

**Comment by martyngigg** [comment]
What in particular means that this can only support OSIRIS?

**Comment by martyngigg** [comment]
@louisemccann Unfortunately a merge conflict has arisen. Can you merge in master, please?

**Pull request merged**
