### PR TITLE
Remove indirect verbose option

### PR DESCRIPTION
**Pull request by DanNixon**
This is Trac ticket: http://trac.mantidproject.org/mantid/ticket/10850

This PR goes with systemtests#11

To test, check that no indirect UI has a verbose option, try a couple of the analysis interfaces to make sure the UI is not broken (e.g. ConvFit, corrections) (UIs that use algorithms are unlikely to break, those using Python are more so).

In most interfaces irs26173_graphite002_red is the sample, irs26176_graphite002_red is the can/container and irs26173_graphite002_res is the resolution, the default options will usually give results.

### CODE REVIEW

**Comment by DanNixon** [comment]
I want to make sure the system tests pass on Windows before this is merged.

**Comment by DanNixon** [comment]
Jenkins, retest this please.

**Comment by martyngigg** [comment]
Jenkins, retest this please.

**Comment by martyngigg** [comment]
@DanNixon Is this ready to go, assuming the builds pass? The develop system tests look okay for indirect but we still have the `InProgress` label here.

**Comment by martyngigg** [comment]
Jenkins, retest this please.

**Comment by martyngigg** [comment]
All is well with the builds now.

**Comment by DanNixon** [comment]
Yeah, the InProgress label is no longer needed. I just added it to prevent it from being merged before the Windows tests had been run.

**Pull request merged**
