### PR TITLE
Improve workspace concepts documentation

### LINKED ISSUE #6875: Workspace Documentation
This issue was originally [TRAC 6029](http://trac.mantidproject.org/mantid/ticket/6029)

Following the email from Max 28/10/12, where he complained about the workspace documentation.

1) Easy Fix, overhaul the workspace documentation to contain:

* A description of what it is for
* A usage example
* The relationship between it and other workspace types. A graphical representation would be great.

2) Somehow enforce that changes to the workspace structures, including additions and modifications flag up that the documentation is out of date on the WIKI and therefore force us to update it. This would be much better than continually upsetting users.

### PR DESCRIPTION
**Pull request by NickDraper**
Added python documentation to all workspace types, instrument, run and sample.

closes #6875

All doctested
### Release Notes

http://www.mantidproject.org/ReleaseNotes_3_6_UI_Changes#Documentation
### To test

Look at the concepts pages for workspaces etc

### CODE REVIEW

**Comment by peterfpeterson** [comment]
@NickDraper Does this "fix #6875"? You need to add that to the description if it does.

**Comment by NickDraper** [comment]
Yes,

Thanks for the spot I’ve updated the PR now.

Regards,
Nick Draper

**Comment by KarlPalmen** [comment]
looks very good, but I have spotted 3 possible errors, which I think came from copying and pasting something and forgetting to make all the necessary modifications. These I've commented in the commits.

**Comment by NickDraper** [comment]
@KarlPalmen I've fixed all the issues you spotted, thanks for catching them.

**Comment by KarlPalmen** [comment]
I found one more cut and paste error in MD Workspace as commented above.

**Comment by KarlPalmen** [comment]
I've removed my assignment, because I'll be away for just over 1 week.

**Pull request merged**
