### PR TITLE
Fix Vesuvio fitting when no intensity constraints applied.

### LINKED ISSUE #17734: Vesuvio: Fits of close peaks can produce negative intensities
The following driver script produces the issue
```python
"""
Main driver script for VESUVIO users to do TOF fitting

It requires the vesuvio script
"""
from mantid.kernel import *
from mantid.api import *
from mantid.simpleapi import *
import vesuvio.commands
reload(vesuvio.commands)
from vesuvio.commands import fit_tof
import numpy as np

# --------------------------------------------------------------------------------
# Standard flags to modify processing
# --------------------------------------------------------------------------------

# Specify the run(s) to process. Can be either a single number or a list of
# two numbers defining ranges

runs = "23271-23296" #300 K E OFF




# Holds flags to alter how processing occurs
flags = dict()

# Fitting mode. Options are:
#    bank: spectra from each bank are summed and each bank is then fitted separately
#    spectrum: spectra are fitted individually
flags['fit_mode'] = 'spectrum'

# Spectra selection. Can be a single number, a list of two numbers defining a range
# or one of the keyword strings "forward", "backward", "all"
# Example: 135 will only process spectrum 135 (only applies if fit_mode="spectrum")
# Example 2: 135-185 will process all spectra in the range (only applies if fit_mode="spectrum")
# Example 3: "forward" will process all spectra in the forward scattering banks
#flags['spectra'] = '143-150'
flags['spectra'] = '135-198'
flags['spectra'] = '145'

# Masses and properties for fit. Each mass is a dictionary of properties about that mass
# All functions require the following keywords:
#   'value': The mass value itself
#   'function': The name of the function approximate the mass profile: GramCharlier/Gaussian
#   'width': The value/values for the width. A single number specifies a fixed width whereas
#            a list of numbers specifies a default and allowed range for the width as [min,default,max]
# If the function is set to GramCharlier (generally only for the first mass) then there are additional
# keywords:
#    'hermite_coeffs': A list of 1/0 to indicate whether a given coefficient is included
#    'k_free': True/False to indicate whether k is either fixed or remains free
#    'sears_flag': If k is fixed then sears_flag=1 fixes k=sqrt(2)/12 whereas sears_flag=0
#                 fixes k=0

#ked

#  ENTER MASS (AMU),DEBYE TEMP (K)
#27 433
#  TEMPERATURE (K)
#120
#  EFFECTIVE TEMPERATURE=   187.6374     K
#  KINETIC ENERGY=   24.25509      meV =    281.4561      K
#  RMS ATOMIC MOMENTUM ALONG Q=   10.21953      A-1
#  RMS DISPLACEMENT=  6.7506626E-02 A
#  TEMPERATURE (K)

#Current Mantid limitation in data fitting is
#that it is not able to model/fit the multiple
#scattering (visible largely as the green residual)
#in backscattering as I is unable to assume no
#single scattering off protons despite multiple scattering
#off protons present. 

#In the light of this problem, it was assumed that
#carbon and oxygen widths found in single scattering
#approximation from backscattering are good 
#(say, to within 10 percent) estimates of true values.
#those values with bounds were then used in forward
#Scattering fitting.

mass1 = {'value': 1.0079, 'function': 'GramCharlier', 'width': [4, 5, 6], 'hermite_coeffs': [1,0,1], 'k_free': 0, 'sears_flag': 1}
mass2 = {'value': 16.0, 'function': 'Gaussian', 'width': 12.0}
mass3 = {'value': 27.0, 'function': 'Gaussian', 'width': 15.5}
flags['masses'] = [mass1, mass2,mass3]

# Intensity constraints. Can be None or a list of lists defining the required
# constraints to be imposed between the intensity values for each mass.
# Example 1: list([0, 1, 0, -4]) defines a single constraint that the intensity of mass 2
#            should be 4 times the intensity of mass 4

flags['intensity_constraints'] = None

flags['bin_parameters'] = '110,.5,500'

# Background. Defines a function an associated attributes
# Currently only a Polynomial is supported. To switch off the
# background set
flags['background'] = None
#flags['background'] = {'function': 'Polynomial', 'order': 2}


# --------------------------------------------------------------------------------
# Corrections flags
# --------------------------------------------------------------------------------

# Run(s) for an empty container subtracted before final fitting is performed
# Set to None for no subtraction or a set of run numbers in the same format as runs variable
#flags['container_runs'] = "22035-22058"
flags['container_runs'] = None

# Fixes the scale factor for the container, if not specified then the factor is
# calculated form the result of a linear fit
#flags['fixed_container_scaling'] = 1

# Outputs workspaces containing the correction factors for each correction and
# workspaces containing the input data with the single correction applied.
flags['output_verbose_corrections'] = True

# Enable gamma correction for gamma emissions due to neutron absorption in
# sheilding
flags['gamma_correct'] = True

# Scale factor for gamma correction
# If set to None or not set the scale factor is caulcuated from a linear fit of
# gamma and total scattering to the input data
flags['fixed_gamma_scaling'] = 0.9


# Holds flags specific to multiple scattering
flags['ms_flags'] = dict()

# Values assumed in VMS program DINSMS_BATCH
# The program DINSMS_BATCH uses those sample parameters together with the sigma divided by the sum absolute of scattering intensities for each detector (detector bank), sigma/int_sum



flags['ms_flags']['SampleWidth'] = 10.0
flags['ms_flags']['SampleHeight'] = 10.0
flags['ms_flags']['SampleDepth'] = 0.1

# the thick program version written by Elliot Oram
# using relative scattering intensities 
# averaged  from fitting forward scattering 
# and using measured  experimental transmission of the sample yields
# the tickness parameter:

#   428.891



# Sample thickness paramaeter 
flags['ms_flags']['SampleDensity'] = 428.891
#flags['ms_flags']['SampleDensity'] = 1



# Optional parameters (default values are given)
#flags['ms_flags']['Seed'] = 123456789
#flags['ms_flags']['NumScatters'] = 3
flags['ms_flags']['NumScatters'] = 2
#flags['ms_flags']['NumRuns'] = 10
flags['ms_flags']['NumEvents'] = 1000000
# flags['ms_flags']['NumEvents'] = 1000000
#flags['ms_flags']['SmoothNeighbours'] = 3
#flags['ms_flags']['ScatteringScaleFactor'] = 1


# --------------------------------------------------------------------------------
# Advanced flags
# --------------------------------------------------------------------------------

# Calibration file specifying the detector positions and parameter values
flags['ip_file'] = 'ip_file.txt'


# Differencing mode. You should rarely need to modify this. Options are:
#    single
#    double
flags['diff_mode'] = 'single'

# Maximum number of iterations to use in fitting
flags['max_fit_iterations'] = 5000

# Configuration of the minimizer to use in fitting
flags['fit_minimizer'] = 'Simplex,AbsError=1e-08,RelError=1e-08'


# --------------------------------------------------------------------------------
# Run fit
# --------------------------------------------------------------------------------
fit_tof(runs, flags, iterations=1)
```

The required runs can only be accessed from ISIS. [ip_file.txt](https://github.com/mantidproject/mantid/files/515459/ip_file.txt) is provided.

The `23271-23296_params_iteration_1` workspace contains a row labelled `f1.Intensity` and it's value should be positive.

### PR DESCRIPTION
**Pull request by martyngigg**
Removes the use of a special Vesuvio composite function type when there are no intensity constraints to apply.

The changes are entirely isolated to Vesuvio at ISIS.

**To test:**

The script is in the issue. It will need to be tested at ISIS.

Fixes #17734 .

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
RHEL 7 failure is just warnings regarding Nexus and everything else passed.

**Comment by martyngigg** [comment]
@louisemccann Would you have time to test this today?

**Comment by louisemccann** [comment]
@martyngigg Sure, I will take a look

**Comment by martyngigg** [comment]
Thanks

**Comment by louisemccann** [comment]
f1.Intensity is positive, :shipit:

**Pull request merged**
