### PR TITLE
Added dockable tabs to workbench data analysis

### PR DESCRIPTION
**Pull request by Matthew-Andrew**
**Description of work.**

When the Data Analysis interface was ported to workbench the dockable tabs feature didn't work in Qt5. This updates the implimentation of this feature to restore the ability to dock and undock tabs. Bringing the interface on workbench into feature parity with that on plot. I developed this on windows so would be good to get a tester using a different OS to check the docking/undocking works ok there as this is the sort of thing which can vary between OS's.

**To test:**
Open the Data Analysis interface on workbench. Go to any of the fit tabs and check you can undock and re-dock the Function Browser and the plot windows in a sensible manner.

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DannyHindson — CHANGES_REQUESTED** [review]
I've built this on Ubuntu and generally works fine - can undock the function\plot widgets and put them back again. I've added a couple of detail level comments. Also can the plot widget be given a title - like it has in Mantid Plot?

DockableTabs1
I noticed this because it seems to be possible to undock one of the function\plot widgets and then redock it so that the two widgets appear as tabs (see following screenshot). Couldn't see this feature in Mantid Plot so may be a Qt5 feature. The plot widget gets an empty tab which might be due to the lack of a title:

DockableTabs2

**Comment by Mantid-Matthew** [comment]
Thanks a lot for the swift review. I have updated the dock-able widgets so that tabbing on top of one another is not permitted and added a title to the plots widget. Hopefully this improves things?

I've had some feedback of odd behavior when you resize the window from Spencer which I am going to in investigate tomorrow and I have asked @DanielMurphy22 to give this a go on MacOS as I've previosly found docking and undocking to function very differently there. So please hold off on approving/mergeing for now.

**Review by DanielMurphy22 — COMMENTED** [review]
I've checked on Mac and it actually seems to work rather well! Docking and undocking is sensible. The only minor thing is that an undocked window has the "Close, Minimise, Maximise" buttons greyed out (which may be the case for other OSs) and there is the non-obvious feature that double-click on the topbar of a window will toggle b/w docked/undocked. I believe these minor things would be a pain to harmonise across different platforms so for Mac I'm happy!

I'll leave it for Danny to approve.

**Comment by DanielMurphy22** [comment]
Also, a bit outside the scope of this PR, but the but "Fit Single Spectrum" button in the mini-plots window can be compromised (although the "Plot Current Preview" cannot!) and the settings, help and generate script buttons in the bottom left of the interface look rather bad on Mac too.
Screenshot 2020-05-29 at 09 31 03

**Comment by DannyHindson** [comment]
@Mantid-Matthew I've retested following your further commits and they all look good. I also see the same behaviour Daniel describes about the text on the "Fit Single Spectrum" button being squashed (on my Ubuntu build) but I don't think anything you've done in this PR has introduced that. So happy to approve without that.
Are you happy for me to approve now or are you still working on the input from Spencer about resizing?

**Comment by DannyHindson** [comment]
I just noticed while shutting stuff down that PyCharm has these messages in it which are generated when the Data Analysis UI is opened:
QLayout: Attempting to add QLayout "" to MantidQt::CustomInterfaces::IDA::IndirectDockWidgetArea "dockArea", which already has a layout
QLayout: Attempting to add QLayout "" to MantidQt::CustomInterfaces::IDA::IndirectDockWidgetArea "dockArea", which already has a layout
QLayout: Attempting to add QLayout "" to MantidQt::CustomInterfaces::IDA::IndirectDockWidgetArea "dockArea", which already has a layout
QLayout: Attempting to add QLayout "" to MantidQt::CustomInterfaces::IDA::IndirectDockWidgetArea "dockArea", which already has a layout

Not sure if they're new but I guess if it's easy to remove that would be good

**Comment by Mantid-Matthew** [comment]
- Spencer is happy with the current state of the PR
- I have removed the warnings you saw
- I rebased apologies to resolve some merge conflicts all the commits should be the same. Only the last commit removeing the uneeded layout has been added.

**Review by DannyHindson — APPROVED** [review]
Thanks. That all looks fine now

**Pull request merged**
