### PR TITLE
Clip colorbar range in Sliceviewer

### LINKED ISSUE #36087: New autoscale options set color limits outside range of data
**Describe the bug**
Found during manual testing #36061

New autoscale options set color limits outside range of data - this isn't a surprise  if you set limits using mean +/- 3 sigma the limits could be outside the extents of min/max of the intensity distribution if e.g. it isn't normally distributed.

It's not a problem with the calculation of the extents, but perhaps we should clip the lmits so that it isn't less than the minimum intensity or greater than the maximum intensity.

**To Reproduce**
(1) Make a workspace
```
md_4D = CreateMDWorkspace(Dimensions=4, Extents=[0,2,-1,1,-1.5,1.5,-0.25,0.25], Names="H,K,L,E", Frames='HKL,HKL,HKL,General Frame',Units='r.l.u.,r.l.u.,r.l.u.,meV')
FakeMDEventData(InputWorkspace=md_4D, UniformParams='5e5') # 4D data
FakeMDEventData(InputWorkspace=md_4D, UniformParams='1e5,0.5,1.5,-0.5,0.5,-0.75,0.75,-0.1,0.1') # 4D data

# Add a non-orthogonal UB
expt_info = CreateSampleWorkspace()
md_4D.addExperimentInfo(expt_info)
SetUB(Workspace='md_4D', c=2, gamma=120)

md_3D_histo = BinMD(InputWorkspace='md_4D', AlignedDim0='H,-2,2,100', AlignedDim1='K,-1,1,100', AlignedDim2='L,-1.5,1.5,100')
```
(2)  Open `md_3D_histo` in sliceviewer
(3) Check autoscale under the colorbar
(4) Make a note of the min and max
(5) Select 3-sigma from dropdown-box under autoscale checkbox
(6) Note the colorbar minimum is below 0 (the actual minimum counts)

**Expected behavior**
Would probably clip extents to min and max of data?

**Platform/Version (please complete the following information):**
 - Introduced this release (v6.8)

**Additional context**

### PR DESCRIPTION
**Pull request by MohamedAlmaki**
**Description of work**
New autoscale options set colour limits outside the range of data in the Sliceviewer. This pull request limits bar values to the range of the data.
**Purpose of work**

The colour bar limits might get outside the range of the data

**Summary of work**

In '_calculate_auto_color_limits', 'vmin'/'vmax' are clipped by data max/min values after applying the selected option.
**Further detail of work**

**To test:**
(1) Make a workspace
```
md_4D = CreateMDWorkspace(Dimensions=4, Extents=[0,2,-1,1,-1.5,1.5,-0.25,0.25], Names="H,K,L,E", Frames='HKL,HKL,HKL,General Frame',Units='r.l.u.,r.l.u.,r.l.u.,meV')
FakeMDEventData(InputWorkspace=md_4D, UniformParams='5e5') # 4D data
FakeMDEventData(InputWorkspace=md_4D, UniformParams='1e5,0.5,1.5,-0.5,0.5,-0.75,0.75,-0.1,0.1') # 4D data

# Add a non-orthogonal UB
expt_info = CreateSampleWorkspace()
md_4D.addExperimentInfo(expt_info)
SetUB(Workspace='md_4D', c=2, gamma=120)

md_3D_histo = BinMD(InputWorkspace='md_4D', AlignedDim0='H,-2,2,100', AlignedDim1='K,-1,1,100', AlignedDim2='L,-1.5,1.5,100')
```
(2)  Open `md_3D_histo` in sliceviewer
(3) Check autoscale under the colorbar
(4) Make a note of the min and max
(5) Select 3-sigma from dropdown-box under autoscale checkbox
(6) Note that the colorbar minimum must be 0, and its maximum should be +3 sigma (less than the data max value).

Fixes #36087. 

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by MohamedAlmaki** [comment]
Waiting for @zjmorgan feedback

**Comment by zjmorgan** [comment]
@MohamedAlmaki This is a good suggestion.

**Review by RichardWaiteSTFC — CHANGES_REQUESTED** [review]
This works well thanks, but it seems like there could be a test for this (even just the `_calculate_auto_color_limits` function) in 
`qt/python/mantidqt/mantidqt/widgets/colorbar/test/test_colorbar.py`

**Comment by RichardWaiteSTFC** [comment]
@MohamedAlmaki - I'm happy to approve this if you make a maintenance issue to add a unit test (don't want to delay beta testing just for this).

**Review by RichardWaiteSTFC — APPROVED** [review]

**Pull request merged**
