### PR TITLE
MuonAnalysis grouping selection - change unintuitive behaviour

### LINKED ISSUE #15457: ARGUS data loading
Raised in muon meeting 25/2 by Fiona and Peter

- Loading recent ARGUS data into Mantid using the MuonAnalysis interface doesn't look right. The asymmetry plot looks unphysical - speak to Fiona for more information. 

- [x] "Load current run" doesn't work for ARGUS. At the moment it's a special case that tries to load `\\ndw828\argusdata\current cycle\nexus\argus0000000.nxs` - should be changed to match other instruments, i.e. look in `\\argus\data\autosave.run` for the autosave file name. Issue #15469, PR #15474

### PR DESCRIPTION
**Pull request by tom-perkins**
Fixed a bug/unintuitive behaviour reported in the MuonAnalysis interface. The choice of which group/pair to plot should not be changed unexpectedly, it should be changed only if the user explicitly chooses to (via dropdown list, or one of the Plot buttons).

This included some refactoring, a selection of free functions was turned into a class (`MuonGroupingHelper`) with the aim of making it a little clearer where the UI is updated.

**To test:**

_Test data available at_ `\\olympic\babylon5\Scratch\TomPerkins\Data\argus00060926.nxs`
1. (demonstrative test) Run through the steps in the issue and see that the behaviour is more intuitive:
   - Load the test file into MuonAnalysis. Pair `long` should be plotted by default.
   - Go to grouping tab and edit entry for `fwd` to exclude detectors 10-16, which are bad for this dataset.
   - On editing, the data should be replotted (if you have auto-update set to on in the settings tab) The pair plotted should still be `long`, not `fwd`.
   - Go back to Home tab and check the dropdown list is still on `long`.
2. Use the dropdown list on the Home tab to switch between plotting `fwd`, `bwd` and `long`. Check this works as it should.
3. On the grouping tab, use the "Plot" button by the top (groups) table. The highlighted row should be the group plotted. Check this changes the dropdown on the Home tab too.
4. As with 3, but use the "Plot" button by the bottom (pairs) table.
5. Edit groupings in the group table. The plot should update automatically (if this option is chosen in the setttings), but the previously selected group/pair (i.e. `long` by default) should not be changed.
6. As 5 with the pair table
7. Turn auto-update off in the settings and check that, under these conditions, the plot is only updated by explicitly clicking one of the "Plot" buttons
8. With `fwd` selected in the Home tab dropdown list, edit the pairs table. Check that what is plotted is still `fwd` and not `long`.
9. Try further combinations to get the interface to behave unexpectedly or break.

Fixes #15457 
- [x] The [release notes](http://www.mantidproject.org/Release_Notes_3_7_MuonAnalysis#Muon_Analysis) have been updated

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
While testing, I accidentally removed all the detectors in the `fwd` group (i.e. I left the cell blank) and Mantid crashed. I created a new issue: #15514

**Comment by raquelalvarezbanos** [comment]
I've also noticed, while testing points 3 and 4 in the list, that results are plotted twice for some reason. The call stack is:

```
MantidQtCustomInterfaces.dll!MantidQt::CustomInterfaces::MuonAnalysis::plotItem(MantidQt::CustomInterfaces::MuonAnalysis::ItemType itemType, int tableRow, MantidQt::CustomInterfaces::MuonAnalysis::PlotType plotType) Line 399	C++
MantidQtCustomInterfaces.dll!MantidQt::CustomInterfaces::MuonAnalysis::plotSelectedItem() Line 389	C++
MantidQtCustomInterfaces.dll!MantidQt::CustomInterfaces::MuonAnalysis::runFrontPlotButton() Line 364	C++
MantidQtCustomInterfaces.dll!MantidQt::CustomInterfaces::MuonAnalysis::setGroupOrPairToPlot(int index) Line 3096	C++
MantidQtCustomInterfaces.dll!MantidQt::CustomInterfaces::MuonAnalysis::runGroupTablePlotButton() Line 767	C++
```
the first time, and
```
MantidQtCustomInterfaces.dll!MantidQt::CustomInterfaces::MuonAnalysis::plotItem(MantidQt::CustomInterfaces::MuonAnalysis::ItemType itemType, int tableRow, MantidQt::CustomInterfaces::MuonAnalysis::PlotType plotType) Line 399	C++
MantidQtCustomInterfaces.dll!MantidQt::CustomInterfaces::MuonAnalysis::runGroupTablePlotButton() Line 772	C++
```
the second, but this is unrelated to the changes in this PR.

**Comment by tom-perkins** [comment]
I think the second point is related to the changes here. The problem is that the new function `setGroupOrPairToPlot` is badly named because it not only sets the group but causes a replot too, so that the plot always matches the group set in the UI.
It should be renamed `setGroupOrPairAndReplot` or similar to make this clearer. Because a plot is caused by this, there's no need for the separate plot calls too as they cause the data to be plotted twice.

**Comment by raquelalvarezbanos** [comment]
OK, I see where this happens:

```
  if (groupNumber != -1) {
    PlotType plotType = parsePlotType(m_uiForm.groupTablePlotChoice);

    // Update the combo box on the home tab
    setGroupOrPairToPlot(groupNumber);
    m_uiForm.frontPlotFuncs->setCurrentIndex(
        m_uiForm.groupTablePlotChoice->currentIndex());

    plotItem(Group, m_groupTableRowInFocus, plotType);
  }
```

If `setGrouporPairToPlot()` causes a plot, could the last line, `plotItem()` be removed or will this potentially break other functionality in the interface?

**Comment by raquelalvarezbanos** [comment]
OK, I've just seen your last commit :)

**Comment by tom-perkins** [comment]
Yes, I think the call to `plotItem()` is unnecessary now that setting the group/pair causes a refresh of the plot. Hopefully this will be less confusing now the function has been renamed!

The point of forcing a replot when the group is changed is so that the plot is always in sync with the group/pair selected on the UI.

**Comment by raquelalvarezbanos** [comment]
Makes sense, I agree the plot has to be in sync with the group/pair selected

**Comment by raquelalvarezbanos** [comment]
I followed testing instructions, everything behaves as described (changing groups/pairs, editing detector IDs, etc). I found a problem when all detectors are removed from the table, but as I think that is unrelated to the changes in this PR, I created a new issue (#15514). Unfortunately changes can't be tested, as MuonAnalysis is not testable at present.

:shipit:

**Comment by tom-perkins** [comment]
I've merged in master and updated the release notes in the source, as they have been moved there from the wiki. No code changes (besides release notes update).

**Comment by FedeMPouzols** [comment]
All tested exhaustively (manually) and the release notes are already in the new release RST pages.

**Pull request merged**
