### PR TITLE
ISIS Reflectometry: Reprocess rows with changed data

### LINKED ISSUE #19970: ISIS Reflectometry: Process selected rows with changed data
Currently in the Reflectometry interface if we change the data in a processed row while reduction is paused, the changed row is not reprocessed. This should be changed so that modified rows will be reprocessed again.

In addition, changing which rows in the table are selected will cause the interface to attempt to process rows that have already been processed unnecessarily. Processed rows whose data has not been altered should be ignored when reprocessing rows.

### PR DESCRIPTION
**Pull request by PranavBahuguna**
This PR adds several new features to the ISIS Reflectometry interface:
- While reduction is paused, selecting new rows of data will cause them to be processed after resuming while deselected ones and already processed data items will be ignored. This is as opposed to previously where the interface simply reprocessed all selected rows, regardless of whether they had been processed before.
- Manually altering data in a previously processed row while paused will cause that row and its containing group to be set unprocessed.
- Adding/removing rows from a group while paused will set that group unprocessed.

**To test:**
- Code review.
- For manual testing:
  - Open the interface from Interfaces->Reflectometry->ISIS Reflectometry
  - Change instrument to `POLREF` and enter investigation id `1520249` (you may need to login to the ICAT catalog). Transfer all runs to the table.
  - Select several groups and process them. Pause midway through and select some new additional groups before processing again. Fully processed groups that were selected should be ignored and the new groups should be processed too.
  - Select several groups, process them and as before, pause midway through. In a previous fully-processed group, change the data of some of the rows. When you resume again, these rows (as well as their containing groups) should be set unprocessed.
- Repeating same steps as before, add/remove some rows from groups while paused. The affected groups should be set unprocessed,

Fixes #19970.

**Release Notes** 

*Release notes have been updated.*

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [x] Are the unit tests small and test the class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by PranavBahuguna** [comment]
@AntonPiccardoSelg All major changes are now implemented, feel free to test this again.

**Review by AntonPiccardoSelg — CHANGES_REQUESTED** [review]
The linux warnings are being pick up: http://builds.mantidproject.org/job/pull_requests-ubuntu-python3/2642/warnings32Result/new/

Else there is not much to change. :+1:

**Comment by AntonPiccardoSelg** [comment]
Followed the test instructions. Works fine.  If reduced workspaces are deleted, they get reprocessed when the user tries to reduce them again :+1:. Please :shipit:

**Review by AntonPiccardoSelg — APPROVED** [review]
LGTM

**Pull request merged**
