### PR TITLE
Indirect Bayes - ResNorm adjustments

### LINKED ISSUE #23828: Indirect - Bayes - ResNorm tab adjustments
**Original reporter:** Spencer

### Expected behavior
- Prevent extra Fit plot when you click `Plot` in the output options
- Include ability to load Sqw files for Vanadium
- SampleLogs – copy & add file-names for sample & resolution

### Steps to reproduce the behavior
1. `Interfaces`->`Indirect`->`Bayes`->ResNorm tab

### Platforms affected
All

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR introduces a few changes in the ResNorm interface of Indirect Bayes:
- Prevents an extra `Fit` plot when you click Plot in the output options
- Allows the ability to load Sqw files for Vanadium
- SampleLogs – copy & add file-names for sample & resolution
- In the mini-plot, the `Fit` line has been changed colour from red to green

**To test:**
1. `Interfaces`->`Indirect`->`Bayes`->`ResNorm` Tab
**A**
2. Load the first set of data below
3. Click `Run` and wait
4. `Plot` all of the output. There should be two graphs plotted only: Intensity and Stretch
**B**
2. Load the second set of data
3. Click `Run` and wait
4. It should run without failing

Check the sample logs of the workspaces in the `_ResNorm` output group workspace to make sure that the sample logs from the resolution file have been copied over. There should also be additional logs including `sample_filename` and `resolution_filename`.

**Data**
**A**
[irs26173_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2594797/irs26173_graphite002_red.zip)
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2594798/irs26173_graphite002_res.zip)

**B**
[iris26173_graphite002_sqw.zip](https://github.com/mantidproject/mantid/files/2594800/iris26173_graphite002_sqw.zip)
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2594801/irs26173_graphite002_res.zip)

Fixes #23828 

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by mantid-roman** [comment]
@robertapplin There are conflicts

**Review by mantid-roman — CHANGES_REQUESTED** [review]
I see only one plot and an error message:
```
Property "WORKSPACE" is not set to a valid value: "Workspace irs26173_graphite002_ResNorm_Stretch is not of the correct type".
```

**Comment by robertapplin** [comment]
@mantid-roman Sorry, forgot to say you need to select `All` in the plot combo box in order to get both plots to appear

**Review by mantid-roman — APPROVED** [review]
👍

**Pull request merged**
