### PR TITLE
Fix Qt5 build on Visual Studio

### LINKED ISSUE #20381: Create initial layout for mantidqt/workbench python modules
The new [workbench design](https://github.com/mantidproject/documents/blob/master/Design/Workbench/design-contents.md) makes extensive use of a utility `mantidqt` library that will contain the reusable widgets and any required plotting code.

This issue is to create a basic layout and build rules for both the `mantidqt` package and `workbench` package, along with start up code for a main window. 

Installation will not yet be considered here.

### PR DESCRIPTION
**Pull request by martyngigg**
Description of work.

Adds QScintilla for Qt5 and applies some additional fixes for Visual Studio.

**To test:**

* Checkout the code and set the `ENABLE_WORKBENCH` option in cmake.
* Build all
* A workbench executable should now exist in bin\[Release,Debug]
* Run this.

Fixes #20381

**Release Notes** 
*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by mantid-roman** [comment]
I have a folder named `$${CMAKE_CFG_INTDIR}` in my build directory. Is it a name it is supposed to have?

**Comment by martyngigg** [comment]
Oh. No, that's not right. A variable dereference has gone wrong. Did that just appear with this PR?

**Comment by martyngigg** [comment]
Thanks!

**Comment by mantid-roman** [comment]
@martyngigg Do you think the failure is unrelated?

**Review by mantid-roman — APPROVED** [review]
No failure at all! It works.

**Pull request merged**
