### PR TITLE
Function to get parameter correction file for instrument

### LINKED ISSUE #13091: Add Function to LoadIDFFromNexus to locate parameter correction file.
This is step 4 of ticket #12255 .

The function will search for a subfolder 'embedded_instrument_corrections' for the instrument folder and if found look for a parameter correction file of the form [Instrument name]_Parameter_Corrections.xml
and return/output its name. Return/output "" if none found. All instrument folders as provided by config will be searched.

Unit test this function with file present and file absent.

Optionally call the function from LoadIDFFromNexus in the appropriate place and check it returns/outputs appropriate value.

### PR DESCRIPTION
**Pull request by KarlPalmen**
Fixes #13091.

To test review the code.
Check that the unit test is adequate and correct
Build and check the subfolder of the instrument folder "embedded_instrument_corrections" exists and has one test file in it for instrument TEST1.

You may also run it and use debugger to check that the function returns the correct value.

### CODE REVIEW

**Comment by Anders-Markvardsen** [comment]
Look clear, but could you place embedded_instrument_corrections/TEST1_Parameter_Corrections.xml in folder IDFs_for_UNIT_TESTING please to keep separate files we use for testing to files we use in production

**Comment by KarlPalmen** [comment]
I did attempt that, but the correction file was not found and so I concluded that IDFs_for_UNIT_TESTING is not in the list of instrument folders searched.

**Comment by KarlPalmen** [comment]
Dear Anders

I ran the debugger to see which folders my machine uses as instrument folders. I find two
C:\Users\kevp43.CLRC\AppData\Roaming\mantidproject\mantid\instrument and the usual instrument folder.

To move the test correction file folder to IDFs_for_UNIT_TESTING, it will be necessary for

(a)    All build servers to have that file in their list of instrument folders

(b)   My machine to be configured so and instructions for this to be included in the comments of the unit test.

If (a) is false, then this is a separate issue.

Karl

**Comment by KarlPalmen** [comment]
I'll make the test file into a scoped file, so it won't get shipped with Mantid.

**Comment by KarlPalmen** [comment]
I've found that scoped file is unsuitable for this purpose. It puts the file in a temporary folder of its own making and not where it is needed for the test. Also I've found that GIT apparently will not store and empty folder. So to store the embedded_instrument_corrections in GIT it must contain a file. If it contains a file, the test can use that file. This suggests using the test file as I have done, until a production file is available, then use the production file and delete the test file.

**Comment by Anders-Markvardsen** [comment]
TEST file in folder embedded_instrument_corrections is to be replaced by production soon

**Pull request merged**
