### PR TITLE
Update indirect_inelastic release notes

### PR DESCRIPTION
**Pull request by louisemccann**
Update descriptions of changes made in the Indirect Inelastic release notes 

No issue number required

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AndreiSavici** [comment]
:shipit:

**Comment by AndreiSavici** [comment]
I've killed the win7 and rhel7 builds

**Comment by AndreiSavici** [comment]
@louisemccann could you change the target for the merge from master to release 3.9?

**Comment by martyngigg** [comment]
@louisemccann @AndreiSavici It looks as if this branch was created with `master` as a base rather than `release-v3.9`. Comparing `release-v3.9` to this branch gives: https://github.com/mantidproject/mantid/compare/release-v3.9...update_indirect_release_notes which shows that we will merge all of that extra stuff if we merge this.  

@louisemccann Please take a look at http://www.mantidproject.org/Git_Workflow#New_branches for how to start new branches based off the release branch.

To fix up this branch you can run:

```
git fetch -p
git checkout update_indirect_release_notes
git rebase --onto origin/release-v3.9 origin/master update_indirect_release_notes
git push -f origin ￼update_indirect_release_notes
```

Once you've done that then can you click the edit button at the top right and change the base branch to `release-v3.9`? Thanks.

**Comment by louisemccann** [comment]
@martyngigg thanks for the tip

**Comment by martyngigg** [comment]
Thanks for fixing that, it's good to go now.

**Pull request merged**
