### PR TITLE
HistogramData rollout: ConvFit.cpp to ResNorm.cpp

### LINKED ISSUE #18755: HistogramData rollout: ConvFit.cpp to ResNorm.cpp
This issue is part of the HistogramData rollout, see #17641.
Algorithms covered in this issue are:

- MantidQt/CustomInterfaces/src/Indirect/ConvFit.cpp
- MantidQt/CustomInterfaces/src/Indirect/CorrectionsTab.cpp
- MantidQt/CustomInterfaces/src/Indirect/IndirectDataReductionTab.cpp
- MantidQt/CustomInterfaces/src/Indirect/IndirectSymmetrise.cpp
- MantidQt/CustomInterfaces/src/Indirect/Iqt.cpp
- MantidQt/CustomInterfaces/src/Indirect/IqtFit.cpp
- MantidQt/CustomInterfaces/src/Indirect/ISISCalibration.cpp
- MantidQt/CustomInterfaces/src/Indirect/ISISDiagnostics.cpp
- MantidQt/CustomInterfaces/src/Indirect/ISISEnergyTransfer.cpp
- MantidQt/CustomInterfaces/src/Indirect/ResNorm.cpp

### PR DESCRIPTION
**Pull request by PranavBahuguna**
This PR is part of refactoring effort to use the new interface of the HistogramData module.
See #17641 for details.

The following algorithms were converted to use `HistogramData`:

- MantidQt/CustomInterfaces/src/Indirect/ConvFit.cpp
- MantidQt/CustomInterfaces/src/Indirect/CorrectionsTab.cpp
- MantidQt/CustomInterfaces/src/Indirect/IndirectDataReductionTab.cpp
- MantidQt/CustomInterfaces/src/Indirect/IndirectSymmetrise.cpp
- MantidQt/CustomInterfaces/src/Indirect/Iqt.cpp
- MantidQt/CustomInterfaces/src/Indirect/IqtFit.cpp
- MantidQt/CustomInterfaces/src/Indirect/ISISCalibration.cpp
- MantidQt/CustomInterfaces/src/Indirect/ISISDiagnostics.cpp
- MantidQt/CustomInterfaces/src/Indirect/ISISEnergyTransfer.cpp
- MantidQt/CustomInterfaces/src/Indirect/ResNorm.cpp

No performance tests were added.

No algorithms show significantly improved performance.

Fixes #18755.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
If I run indirect data reduction ISIS Energy Transfer after just loading file `iris26176_graphite002_red.nxs`, Mantid gets an unexpected exception ``Attempt to assign property (SpectrumMin) of incorrect type``.

**Comment by PranavBahuguna** [comment]
@KarlPalmen I tried doing the same thing on master and got the same result. This means that it isn't the result of any changes I made.

**Comment by PranavBahuguna** [comment]
@KarlPalmen According to @louisemccann, this shouldn't work anyway as `iris26176_graphite002_red.nxs` is already reduced data. If you wish to test this, ensure you have access to the ADS and type in `26176`, this will load a .raw file.

**Comment by KarlPalmen** [comment]
I tried the suggestion and it worked. Other tests that I believe use the modified code also work. :shipit:

**Pull request merged**
