### PR TITLE
Muon fitting functions: change unit tests

### LINKED ISSUE #16418: Change tests of muon fitting functions
See [here](https://github.com/mantidproject/mantid/issues/16267#issuecomment-221582173). Muon fitting functions:

- Abragam
- DynamicKuboToyabe
- ExpDecayMuon
- ExpDecayOsc
- GaussDecay
- GaussOsc
- Keren
- MuonFInteraction
- StaticKuboToyabe
- StaticKuboToyabeTimesExpDecay
- StaticKuboToyabeTimesGausDecay
- StaticKuboToyabeTimesStretchExp
- StretchExpMuon

### PR DESCRIPTION
**Pull request by raquelalvarezbanos**
Tests that tested fitting results were moved to `FitTest`. Added tests for function values (in most cases those were missing).

**To test:**

Code review, all tests should pass.

Fixes #16418.

Maintenance task, does not need to be in the release notes.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
@FedeMPouzols

**Comment by KarlPalmen** [comment]
Code review OK and builds work :shipit:

**Comment by FedeMPouzols** [comment]
Some of the `test_Category()` test cases have been removed by mistake (in a couple of `StaticKuboToyabe...` functions I think). Other than that (not even sure if those tests are that important) this looks ready to go.

**Comment by raquelalvarezbanos** [comment]
Thanks @FedeMPouzols I added back the test for `StaticKuboToyabeTimesStretchExp` (I think this is the only one I accidentally removed).

**Comment by KarlPalmen** [comment]
OSX appears to have completed successfully (see Details), but news of this has not made it here.

**Comment by KarlPalmen** [comment]
:shipit: subject to OSX build 7140 issue.

**Comment by FedeMPouzols** [comment]
Yes, the OSX build finished succesfully.

**Pull request merged**
