### PR TITLE
Fit funtion for EISF of alkyl chains

### LINKED ISSUE #21367: Fit funtion for EISF of alkyl chains
[Paper containing the model](https://github.com/mantidproject/mantid/files/1535700/2016_Sharma_Membrane.dynamics.altered.by.Tocopherol.pdf)
 formula for Ri is number 11 and for EISF - formula 13

### PR DESCRIPTION
**Pull request by jmborr**
This PR complements PR #21373 because I forgot to commit the unit test file

Fixes #21367
---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by jmborr** [comment]
@brandonhewer I'm sorry I forgot to commit the unit test for this fit function, so I had to create a new pull request. Can you please take a quick look to the unit test file?

**Comment by NickDraper** [comment]
@brandonhewer This appears to be waiting on you

**Comment by Mantid-Matthew** [comment]
@jmborr The tests here look fine however I think you need to add the test name to the CMakeLists.txt or the test will not get detected or run by the build servers. 

The relevant file is https://github.com/mantidproject/mantid/blob/21367_EISFDiffSphereAlkyl/Framework/PythonInterface/test/python/plugins/functions/CMakeLists.txt

**Comment by jmborr** [comment]
@Mantid-Matthew thanks a lot, I had missed that!

**Review by Matthew-Andrew — APPROVED** [review]
Once it passes the system tests this should be good to go :)

**Comment by NickDraper** [comment]
vesuvio failures are unrealted

**Pull request merged**
