### PR TITLE
Functional quaternions

### PR DESCRIPTION
**Pull request by OwenArnold**
As a follow on from @SimonHeybrock's #18780. `Quaternions` have **mutable/stateful** behaviour where they really ought to have **functional** behaviour. 

Look at the current `Quat`. This makes coding more error prone. Consider taking the `inverse` for example - That modifies the original! This is logically incorrect. In future we will very likely start using `Eigen` so this small PR should be a helpful step in that direction.

Methods changed to be `const` on `Quat` are:

* `inverse()`
* `normalize()`
* `conjugate()`

All return a new `Quat`

WIP. **DO NOT MERGE**. Cannot be considered for merging until #18780 is merged.

**TESTER**. A code review and verification that all tests still pass will be sufficient. This is an under-the-hood change, so no need to update release notes.

### CODE REVIEW

**Comment by OwenArnold** [comment]
**BEWARE** changes as part of unmerged #18906 to `DetectorInfo::setRotation` which would become logically incorrect, but would still compile with these changes.

**Comment by SimonHeybrock** [comment]
@OwenArnold `Eigen::Quaterniond::normalize()` normalizes the quaterniond. `normalized()` returns a normalized variant, so this is inconsistent.

I am not sure how beneficial changing this now is. We are risking of breaking things, and have to learn two new interfaces instead of 1. Or was your intention to make the interfaces 100% equivalent, such that we can later just use search & replace to use `Eigen`?

**Comment by OwenArnold** [comment]
@SimonHeybrock I did have the forthcoming Eigen replacement in mind. I think this step would make that easier. Good point on `Quaterniond::normalize` I'd need to change that back. I don't think these changes are necessary to merge, but the stateful behaviour of `Quat` is wrong for a number of it's methods such as `inverse`, and this makes the current implementation ugly and error prone. Shall we just shelve this PR for now?

**Comment by SimonHeybrock** [comment]
@OwenArnold I think that might be a good idea. We can have another look once we have a clearer idea of how (and when) a rollout of `Eigen` could happen (I suspect this will not be in the near future).

**Comment by OwenArnold** [comment]
Eigen will replace this functionality eventually.

**Pull request closed without merging**
