### PR TITLE
Fix Muon Analyis 2 resizing snapback

### PR DESCRIPTION
**Pull request by StephenSmith25**
**Description of work.**
When the dockable plot window was resized in the Muon Analysis 2 interface it would often snapback to its original size. This issue was raised by Adrian Hillier during testing. It appears to be an a bug with Qt, see https://bugreports.qt.io/browse/QTBUG-65592 for the bug report. The fix is taken directly from that link. I've only been able to reproduce the issue on windows. 

**Report to:** [Adrian Hillier]

**To test:**

- Open the Muon Analysis 2 Interface
- Resize the dock widget 
- It should preserve the size set by the user and no longer snapback. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by alicerussell1 — COMMENTED** [review]
This fixes the issue in the Muon Analysis interface but it is also happening in the frequency domain analysis interface - should this be done as part of this PR as well?

**Comment by StephenSmith25** [comment]
Yeah good spot, I had forgot about the frequency domain analysis interface. The change has now been added there as well.

**Review by alicerussell1 — APPROVED** [review]
This looks good to me 👍

**Comment by NickDraper** [comment]
Please mention to Adrian Hillier that this has been merged

**Pull request merged**
