### PR TITLE
Internet helper enum class

### PR DESCRIPTION
**Pull request by peterfpeterson**
This converts `InternetHelper::HTTPStatus` to be an `enum class` and changes lots of returns from `int` to the enum. 

**To test:**

This is a refactor so a code review is appropriate.

*There is no associated issue.*

*This does not require release notes* because it is a refactor and should not change any functionality.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DavidFair — CHANGES_REQUESTED** [review]
Our Python layer needs a converter from the Enum Class <-> `int`:
```
Traceback (most recent call last):
  File "mantidpr/qt/python/mantidqt/mantidqt/dialogs/errorreports/presenter.py", line 92, in error_handler
    status = self.share_all_information(continue_working, name, email, text_box)
  File "mantidpr/qt/python/mantidqt/mantidqt/dialogs/errorreports/presenter.py", line 71, in share_all_information
    status = self._send_report_to_server(share_identifiable=True,
  File "mantidpr/qt/python/mantidqt/mantidqt/dialogs/errorreports/presenter.py", line 120, in _send_report_to_server
    status = errorReporter.sendErrorReport()
TypeError: No to_python (by-value) converter found for C++ type: Mantid::Kernel::InternetHelper::HTTPStatus
```

**Comment by peterfpeterson** [comment]
We don't have tests for that?!?!?! Time for some TDD.

**Comment by DavidFair** [comment]
Apparently not, I'm lucky I picked the error reporter instead of a Catalogue service :fearful:

**Review by DavidFair — APPROVED** [review]
Nice to have strongly types enums for HTTP status codes.
This now works for error reporter, I'd rather land this sooner rather than later so any edge cases (like the error reporter) get flushed out in cases that require facility specific testing

**Pull request merged**
