### PR TITLE
Better masking tools for Instrument View

### LINKED ISSUE #18240: Better Masking Tools for Instrument View
This is a sub issue of #10144 .

Currently we can create a mask workspace & cal files from an ROI in the instrument view. This issue should extend this to add the following:
 - [x] Drag and drop a mask workspace onto the instrument view.
   - this should only apply it to the view and not the data
 - [x] Add a way to save ROI/mask shapes to a file/workspace (probably a TableWorkspace)

### PR DESCRIPTION
**Pull request by samueljackson92**
This adds some additional functionality to the instrument view.

**To test:**

 - Check that you can now overlay mask workspaces onto the projection surface by dragging and dropping the workspace (same as for a peaks workspace).
 - Check that you can use the new save shapes to table option to save the shapes that are drawn on the view to a table workspace. Dragging and dropping this workspace back onto the view should recreate the shapes on the view.
- Try this between different runs of the same instrument.
- Try this between different runs of a different instrument.

Fixes #18240 .

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
If find that if I load two EMU files. On the first I create a mask through instrument view draw and then save the shape to table. I then move that table onto an instrument view of the second workspace in 3D view, it then produces the expected error message asking for an unwrapped view, which I think is a 2D view, then Mantid crashes. This I got both times I did it.

**Comment by samueljackson92** [comment]
@KarlPalmen I shall take a look.

**Comment by samueljackson92** [comment]
@KarlPalmen Can you retest this again now please?

**Comment by KarlPalmen** [comment]
Looks good :shipit: . This suggests that similar should be available for a mask saved to a table workspace.

**Pull request merged**
