### PR TITLE
Set multiple dissimilar algorithm properties at one time.

### PR DESCRIPTION
**Pull request by quantumsteve**
DO NOT MERGE THIS INTO MASTER!

This is a potential implementation of option 2 in [this design document](https://github.com/mantidproject/documents/pull/8). Currently, I want to get feedback from others and check that this builds on all platforms.

I used `std::make_tuple` to construct each property. So far I've been unable to get uniform initialization of a std::tuple. [This](http://stackoverflow.com/questions/16703838/is-it-possible-to-infer-template-parameters-of-tuple-from-brace-type-initializat) post seems to suggest  doing so is impossible.

I tried to forward parameters to the appropriate function. We'll want to verify that this is both actually working and beneficial before merging.

### CODE REVIEW

**Comment by OwenArnold** [comment]
Nicely done!

**Comment by martyngigg** [comment]
On it's own I'm not sure this adds much to be honest. We replace 4 lines of code with 4 other lines of code but once combined with the `executeAsChildAlg` call I think this will really be beneficial to have a single place where child algorithms are executed.

**Comment by quantumsteve** [comment]
Attempting to get closer to @martyngigg's suggestion to combine creating the child algorithm, setting properties, and executing it.

What should go into IAlgorithm vs Algorithm? Same for IPropertyManager? and PropertyManagerOwner?

**Comment by martyngigg** [comment]
Personally I think that the interfaces should stay pure and have no implementation at all so I would say these should go in `Algorithm` & ``PropertyManagerOwner` respectively.

**Pull request closed without merging**
