### PR TITLE
15574 plot every error bar

### LINKED ISSUE #15574: Plot every error bar - one time option change
plot every error bar

This is already possible with option, change default? Currently off
->change default

This needs documentation in the release notes nad details of how to set back.

### PR DESCRIPTION
**Pull request by NickDraper**
Performs a one off change on first run to plot every error bar.

This is just a change to a setting, subsequent manual changes should be preserved.

**To test:**
1. Load a dataset, plot with errors, zoom in close, every point should have an error bar.
2. Then use view -> preferences 2D plots->curves, set draw all errors off, and do the same thing.
3. Look at the Release notes and check they make sense.

Fixes #15574

[UI Release notes](/docs/source/release/v3.7.0/ui.rst)

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [ ] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
RHEL 7 actually passed, but the notification failed

**Comment by rosswhitfield** [comment]
:+1: leeroy tried and failed to set the status on github. Probably just a temporary network problem somewhere.

**Comment by KarlPalmen** [comment]
When testing, I found I had to add the error bars via the Graph menu and also can remove them there. 

I could not find any reference to error bars in view -> preferences 2D plots->curves. Functionality not as described in test.

For the test, I loaded ARGUS002687, viewed spectra 92 to 96 and zoomed.

**Comment by KarlPalmen** [comment]
I tested again and realised that I plotted via `Workspace->PlotSpectra` rather than `(Workspace)->PlotSpectraWithErrors`. Now I get coloured error bars. I also find that `Graph->AddErrorBars` will add grey error bars. We seem to have two mechanisms for adding error bars.

I also found the `Draw All Errors` checkbox as shown in the release notes.

So now functionality seems to be as described, provided I plot spectrum with error bars, but there is also another way of showing error bars, via 'Graph'.

**Comment by KarlPalmen** [comment]
:shipit:  bearing in mind the issues I have raised.

**Pull request merged**
