### PR TITLE
Update CMakeLists.txt with SHA of MSlice master

### PR DESCRIPTION
**Pull request by SilkeSchomann**
Update CMakeLists.txt with latest SHA of MSlice master before code freeze.

**To Test**

Check if the SHA matches the current MSlice master.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DavidFair** [comment]
I'm seemingly getting errors pulling this using Cmake into an existing (but fresh) tree:

For reference here's how I'm testing
```
git checkout master && cd ~/mantidprBuild && cmake ../mantidpr  # Switch to master and regen SHA
cd ../mantidpr && git test-pr 31180 && cd ~/mantidprBuild && cmake ../mantidpr # Switch to SHA on this PR
```

Gives me 
```
fatal: reference is not a tree: 4682250059ea56b4af0c444853924ebfad019976
CMake Error at scripts/ExternalInterfaces/mslice/tmp/mslice-gitupdate.cmake:175 (execute_process):
  execute_process failed command indexes:

    1: "Child return code: 128"



CMake Error at scripts/ExternalInterfaces/CMakeLists.txt:26 (message):
  Unable to update mslice.


-- Configuring incomplete, errors occurred!
```

Interestingly, the SHA matches the upstream repo's current HEAD, and we're not doing a shallow clone on the CMake file, so I'm unsure what's going on here :thinking:. Any ideas?

**Comment by SilkeSchomann** [comment]
No idea. I've used 

_git test-pr origin 31180_

to test this on Windows and it definitely uses the correct version of MSlice.

**Comment by DavidFair** [comment]
I'm getting the same error on another un-related build directory. I'll ask someone on #general in Slack to give it a go

**Review by DavidFair — APPROVED** [review]
The issues I was seeing were local, simply running a `git fetch` resolved them and @gemmaguest confirmed it worked through CMake first time

So let's :shipit:

**Pull request merged**
