### PR TITLE
load pelican data with larger eos bin event file (no ticket)

### PR DESCRIPTION
**Pull request by geishm-ansto**
Pelican instrument data at ANSTO comprises a hdf file and related binary event file. The scientists can save a hdf file during an experiment but the event file is continually being updated. This change allows the scientist to load the hdf file with the portion of the event data that is relevent to ensure consistency. It is only used as a simple cross check that the experiment is proceeding as expected. The result is not used for any normal processing and the user is alerted to the unexpected difference in recorded events between the files.

**To test:**
This change does not change the results of any processing and the existing tests are still valid.

There are no release notes as there is no functional change to the processing.

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by sf1919** [comment]
If I understand the description of the changes made then this gives users additional functionality. In which case it will require a release note.

**Comment by geishm-ansto** [comment]
@sf1919 Hi, I've added the release note but am stuck on a reported cppcheck error "<--- Unmatched suppression: constParameter" on line 643. I have run cppcheck locally with --enable=all and do not see any errors. Is there any addnl info to help identify the issue?

**Comment by sf1919** [comment]
My first thought with this is that perhaps there is a supression in the CppCheck_Suppression file that is no longer working because of changes to the file. I've had a look and this does seem to be the case.

Take a look at at the CppCheck_Suppressions file (https://github.com/mantidproject/mantid/blob/main/buildconfig/CMake/CppCheck_Suppressions.txt.in) for any CppCheck suppressions for the file you're working on (in this case LoadPLN.cpp). There are 3 suppressions listed. 

Next look at which 3 lines in the original file, before you edited it, are being suppressed. Now compare this with your changed file. You will find that at the moment line 643 of your changed file is an empty line so there is nothing to suppress. You need to change the CppCheck_Suppressions file with the correct line numbers to be suppressed.

Fingers crossed that should fix your problems.

**Comment by sf1919** [comment]
I don't know if you've come across it but if you need assistance it's worth asking on the Mantid Slack tech-qa channel. Details of how to join can be found at https://developer.mantidproject.org/DeveloperAccounts.html.

**Comment by geishm-ansto** [comment]
Thanks, I'll look into the tech qa channel.
I assume the lines were added when the cppcheck options were changed. I've removed the suppression and it passes cppcheck now. Several unrelated tests failed due to timeout and one due to an assertion error. I've noticed in the past the test system can be flaky. I'll touch a file later to force a rebuild as I can't relaunch the build.

**Comment by geishm-ansto** [comment]
@sf1919 All the checks have passed now, is there anything else you would like?

**Comment by sf1919** [comment]
I hadn't planned to review this PR - I've just been checking all PRs have relevant release notes.

I do need to do a funtional test of this PR - to check that loading files still works even with the changes. However, I don't know anything about Pelican or how scientists use Mantid for Pelican experiments. Can you give me some instructions as to how use Mantid for Pelican data and provide a sample file I can load?

Once I have this I'll do the functional test and review the code.

**Comment by geishm-ansto** [comment]
@sf1919 The Pelican instrument has a loader that was introduced in PR 24697 and includes functionals tests for regression testing. Mantid also includes the Pelican reduction algorithms, introduced with PR 31094, that also includes functional tests. The reduction tests rely on the output of the loader. All of these tests passed as part of this PR. The sample file PLN00446664.hdf  was added in the original PR.

**Review by sf1919 — APPROVED** [review]
I have attempted a functional test of this PR using the file mentioned in #24697. However no test instructions were available in either that PR or this one, and with limited knowledge of Pelican data, I have not been as thorough as I would like. Generally most PRs require a functional test unless it is adding/updating a unit or system test only.

The file loaded without any error messages. I was unsure what to expect in terms of plotting options but they were as below - I hope that is what is expected.

Screenshot (147)

I have reviewed the code and it looks fine. I can see some new variables for calculations but no new methods and having looked at the test for this Load algorithm I can see how that might not need updating.

Thank you for adding the release note. It sounds like a good new feature for scientists that will be of great use during experiments.

**Pull request merged**
