### PR TITLE
EnggCalibrate: add output with the fitted (peak) parameters

### LINKED ISSUE #15180: EnggCalibrate: add output to expose the fitted peaks
This will give access to the peak positions found/fitted for every bank (normally Ceria peaks).
Required to be able to plot the second point of #13377 (which could be a plot of the TZERO-DIFC line with the cloud of points for every peak).

### PR DESCRIPTION
**Pull request by FedeMPouzols**
Fixes  #15180.
- Code review. This PR also includes a bit of refactoring of `EnggFitPeaks`
- Unit, doc, and system tests have been updated and extended. They should pass.
- The new output is described in the documentation (table of properties), and some examples are given.
- Make sure that this makes it possible to implement the second point of #13377. That would require plots of the 'dSpacing' column against the 'X0' column of the `EnggCalibrate` output parameters table, for banks 1, 2, etc.
- For an example of how to retrieve the peak parameters, see the `EnggFitPeak` and `EnggCalibrate` documentation examples.

Release note: http://www.mantidproject.org/ReleaseNotes_3_7_Framework_Changes#Improved

### CODE REVIEW

**Comment by shahrozahmed1** [comment]
capture
On Windows platform, while carrying out `Calibration` on Engineering Diffraction GUI, this error seems to be produced, however following this if I execute `EnggFitPeaks` algorithm with any of three workspaces generated; (`engggui_calibration_sample_ws` or `engggui_vadium_curves_ws` or `engggui_vanadium_integration_ws`) the algorithm runs fine.

**Comment by FedeMPouzols** [comment]
Aha, that is a problem in the Engg GUI because it expects the usual couple of outputs when it calls EnggCalibrate but it is not setting the new output workspace. I'll fix that. Otherwise the Engg GUI would be partially broken.

**Comment by FedeMPouzols** [comment]
BTW, I should have included in the testing instructions "do a simple check with the GUI". Good that you caught this @shahrozahmed1 !

**Comment by FedeMPouzols** [comment]
@shahrozahmed1 : I think that this last commit fixes the issue. It just sets the new property, using the same workspace names as we are using in the GUI (egggui_calibration_bank_1, etc.). (it got mixed with several other changes that are just from clang-format).

**Comment by shahrozahmed1** [comment]
@FedeMPouzols The changes made to algorithms and GUI look good, a valid graph is being produced using `dSpacing` and `X0` values of each bank. The `EnggCalibrate` and `EnggFitPeaks` documentation & unit tests have also been updated accordingly. This branch is ready to be merged.

**Pull request merged**
