### PR TITLE
SpectrumInfo and DetectorInfo rollout: algorithms <IFunction.cpp to ScaleXTest.h>

### LINKED ISSUE #18564: SpectrumInfo and DetectorInfo rollout: algorithms <IFunction.cpp to ScaleXTest.h>
This issue is part of the SpectrumInfo and DetectorInfo rollout, see https://github.com/mantidproject/mantid/issues/17743.
Algorithms covered in this issue are:
Framework/API/src/IFunction.cpp
Framework/Algorithms/test/NormaliseByDetectorTest.h
Framework/Algorithms/test/SetInstrumentParameterTest.h
Framework/Algorithms/test/RingProfileTest.h
Framework/Algorithms/test/ScaleXTest.h

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
## Description of work.
This PR is part of refactoring effort to use the new interface of the SpectrumInfo and DetectorInfo modules.
See https://github.com/mantidproject/mantid/issues/17743 for details.

The following algorithms and tests were refactored to use SpectrumInfo/DetectorInfo:
```
Framework/API/src/IFunction.cpp
Framework/Algorithms/test/NormaliseByDetectorTest.h
Framework/Algorithms/test/SetInstrumentParameterTest.h
Framework/Algorithms/test/RingProfileTest.h
Framework/Algorithms/test/ScaleXTest.h
```

Performance tests were added for:
Most changes are in test files and unrelated to perforamance tests.
`IFunction.cpp` does not seem to have tests and none of its children seems to have a test either. 

The following algorithms have improved performance:
-

## To test.

Code review.

Fixes #18564
Internal change, no release notes (potential performance improvements will be added to release notes as part of the umbrella issue).

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
Looks good. :+1: 
(ParameterMap (or something equivalent) is not yet supported in Instrument-2.0 so the changes in this case are not particularly "beautiful").

:shipit: once Jenkins gives his ok.

**Comment by AntonPiccardoSelg** [comment]
@SimonHeybrock  The tests are not directly failing because of the changes in `iFunction.cpp`, but rather the underlying mechanics of `indexOf`. I started looking first at `HistogramDomainCreatorTest.h`. The only test which is visibly failing is `test_fit_GaussLinear`. It is failing at [this point](https://github.com/mantidproject/mantid/blob/fca41d72715315332685330260c13fcb1e46cf49/Framework/API/src/IFunction.cpp#L768). The ultimate cause for the failure is that `m_detIDToIndex`is empty but it is being queried internally via `SpectrumInfo::getDetector` (line 186). Is `SpectrumInfo` not compatible with "dummy" workspaces which are used in tests environments? Might be best to discuss this in slack.

**Comment by SimonHeybrock** [comment]
@AntonPiccardoSelg Good catch, I have indeed overlooked to case of the first exception being swallowed, and a later retry.

Can this simply be fixed by moving the line
```cpp
m_lastIndex[thread] = index;
```
in `SpectrumInfo::getDetetor` down below the whole code block that attempts to get the detector?

**Comment by SimonHeybrock** [comment]
@AntonPiccardoSelg Good, could you also add the following regression test, in `API/test/SpectrumInfoTest.h`, ideally after `test_no_detector`:

```cpp
  void test_no_detector_twice() {
    // Regression test: Make sure that *repeated* access also fails.
    const auto &spectrumInfo = m_workspaceNoInstrument.spectrumInfo();
    TS_ASSERT_THROWS(spectrumInfo.detector(0),
                     Kernel::Exception::NotFoundError);
    TS_ASSERT_THROWS(spectrumInfo.detector(0),
                     Kernel::Exception::NotFoundError);
  }
```

It failed for me before the change and works after, but maybe you can double check.

Thanks!

**Comment by AntonPiccardoSelg** [comment]
@SimonHeybrock  The test works fine, if the exception is changed to `std::out_of_range` as in `test_no_detector`.

**Comment by SimonHeybrock** [comment]
Green now, :shipit:!

**Pull request merged**
