### PR TITLE
Update ParaView to v5.2.0.

### PR DESCRIPTION
**Pull request by quantumsteve**
Description of work.

This updates Mantid to build against ParaView v5.2.0. Since the changes to Mantid are quire minor, I'm **not** marking this core.

Most the changes were required to successfully build on Windows. The two patches should improve the performance of surface rendering by about 2x.

**To test:**

1. Build ParaView with the [updated build instructions](http://www.mantidproject.org/Building_VATES).
2. Build Mantid with `-DMAKE_VATES=ON` and `-DParaView_DIR=<your ParaView build directory>`.
3. Try viewing a MDHistoWorkspace and a MDEventWorkspace in the VSI.

There is no GitHub issue associated with the PR.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by stuartcampbell** [comment]
@quantumsteve There are no testing instructions... I can guess what to do, but it would be best to have detailed instructions.

**Comment by quantumsteve** [comment]
@VickieLynch I added two patches that should improve surface rendering by ~2x. Next I'll try to attach the progress bars.

**Comment by quantumsteve** [comment]
@mantidproject/gatekeepers Please merge mantidproject/paraview-build/pull/6 with this PR.

**Comment by martyngigg** [comment]
@quantumsteve I'm just building ParaView 5.2 now

**Comment by martyngigg** [comment]
@quantumsteve Any reason we're not waiting until the proper `5.2` release? I notice there is now a `-RC4` tag.

**Comment by quantumsteve** [comment]
@martyngigg I don't see any harm in waiting for the final tag on Friday. I was hoping to catch any outstanding issues before the release, but we're so close now that I'm not sure it'll make any difference.

**Comment by martyngigg** [comment]
I've just played with a bit with some histo & event workspaces in all views and it looks good.

While we're this close let's wait for the final `5.2.0` tag. I'll retest when that comes out.

**Comment by quantumsteve** [comment]
@martyngigg I updated the build servers and this branch to ParaView v5.2.0

**Comment by martyngigg** [comment]
@quantumsteve Looks good. I'll wait for the builds and then merge it so we don't run into too many issues with PR builds next week.

**Comment by martyngigg** [comment]
I just gave the Ubuntu build a go with the generated package - all looks good.

**Pull request merged**
