### PR TITLE
More detailed description of Mayers algorithm

### PR DESCRIPTION
**Pull request by jamesquantum**
Hopefully now gives a better description of what the algorithm does and where certain terms are coming from

#20072

### CODE REVIEW

**Review by Anders-Markvardsen — APPROVED** [review]
Read it again and it now reads clear to me (including 'fixed number of second order scattering events' which is clear now looked more closely at the input parameters)

**Comment by martyngigg** [comment]
@jamesphysics This is a great improvement to this page. My only minor comment is that the `[1]__` doesn't appear as a link when I build it. I think the same is true in the `MultipleScatteringCylinderAbsortption` too.

Could you look at that?

**Comment by Anders-Markvardsen** [comment]
thanks @martyngigg just noticed this all well for #20145

**Comment by jamesphysics** [comment]
thanks for noticing this, should be fixed now on all three documents

**Comment by martyngigg** [comment]
Looks good. Thanks.

**Review by martyngigg — APPROVED** [review]

**Comment by martyngigg** [comment]
Windows failure is unrelated.

**Pull request merged**
