### PR TITLE
Add x and y limits to the main view of sliceviewer

### PR DESCRIPTION
**Pull request by rosswhitfield**
This allows you to view and update the x and y limits of the image easily. The value should update if you zoom or pan. Changing a value will update the plot with the new limits. This is to make these more accessible then the previous method of double clicking the axis values.

I have place the new boxes where I thought most appropriate but are open to moving them if someone has a better suggestion.

sliceviewer_extents

#### Summary of work

Fixes [EMW977](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=977)

### To test:

Open any MDHistoWorkspace, MDEventWorkspace or MatrixWorkspace with sliceviewer, pan or zoom and check that the values update, change a x/y min/max and check that the plot limits are updated.

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by zjmorgan** [comment]
Seems like it works well for MDHisto workspaces

**Comment by zjmorgan** [comment]
With non-ortho view and MDEvent workspaces, the axis limits don't seem to make sense to me. like they do for MDHisto. Look at YMin/Ymax which are +- 6.93. I would think they would be +8

image

Here is my test script

```python
ws = CreateMDWorkspace(Dimensions='4', 
                       EventType='MDEvent',
                       Extents='-9,7,-10,9,-8,8,-2,2',
                       Names='values,[H,0,0],[0,K,0],[0,0,L]',
                       Units='a.b.u.,r.l.u.,r.l.u.,r.l.u.')

FakeMDEventData(ws, UniformParams='1000000')

SetMDFrame('ws', MDFrame='HKL', Axes=[1,2,3])

AddSampleLog('ws', LogName='sample')
ws.getExperimentInfo(0).run().addProperty('W_MATRIX', list(np.eye(3).flatten()), True)

SetUB('ws', a=5, b=5, c=7, alpha=90, beta=90, gamma=120)
```

**Comment by rosswhitfield** [comment]
@zjmorgan Good catch. That should be fixed now. The X min/max limit values will still not align with the values on the axis because they are taken at Y=0.

**Comment by zjmorgan** [comment]
@rosswhitfield Looks good. Regarding the Xmin/Xmax, that makes sense. With the guidelines turned on, it's not too hard to understand the meaning for y=0.

image

**Review by zjmorgan — APPROVED** [review]
This looks good and am happy with the location of the boxes.

**Pull request merged**
