### PR TITLE
Adding logscale colorbar to instrument view

### PR DESCRIPTION
**Pull request by zjmorgan**
**Description of work.**

Instrument view does not have the normal `LogScale` option for colormap. This is often more useful for viewing data compared to `SymLog` as most data is represented as counts (positive values) and `SymLog` is really meant for data that is equally positive as negative. This adds the logarithmic colorbar scaling back in at the request of users.

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by RichardWaiteSTFC — COMMENTED** [review]
I've tried this with SXD23767.raw (in system test data)
`Could not show instrument for workspace 'SXD23767':
unknown`
It could be that it has detector pixels with 0 counts but from the code it looks like it should handle that..I'll have a look in debug

**Comment by zjmorgan** [comment]
> > I've tried this with SXD23767.raw (in system test data) `Could not show instrument for workspace 'SXD23767': unknown` It could be that it has detector pixels with 0 counts but from the code it looks like it should handle that..I'll have a look in debug
> 
> When I open the workspace in instrument viewer it goes through the debugger initially with linear scale and clim (0,0) successfully and then tries to go through with index =1 (now log formerly symlog - perhaps this breaks backward compatibility re-ordering the indices of the scales?) and the color limits taken from the data and it crashes on this line
> 
> https://github.com/mantidproject/mantid/blob/dae439947e0e0f4ba6ee96bf4700cbd34ef07c47/qt/widgets/mplcpp/src/ColorbarWidget.cpp#L63

Thanks for this line. I should be able to track this down.

**Comment by RichardWaiteSTFC** [comment]
@zjmorgan - is this ready to re-review?

**Comment by zjmorgan** [comment]
@RichardWaiteSTFC 

Almost. I can still produce a matplotlib exception when entering negative values for log scale. It seems the logic is not completely right on the GUI side.

**Comment by zjmorgan** [comment]
@RichardWaiteSTFC this is now ready to be re-reviewed. Thanks!

**Comment by RichardWaiteSTFC** [comment]
I still get an error for workspace `SXD23767` - can you reproduce this?
(1) `Load(Filename="SXD23767.raw", OutputWorkspace="SXD23767")`
(2) Right-click > Show Instrument
```
Traceback (most recent call last):
  File "C:\Users\xhg73778\AppData\Local\mambaforge\envs\mantid-developer\lib\site-packages\matplotlib\cbook\__init__.py", line 307, in process
    func(*args, **kwargs)
  File "C:\Users\xhg73778\AppData\Local\mambaforge\envs\mantid-developer\lib\site-packages\matplotlib\colorbar.py", line 495, in update_normal
    self._draw_all()
  File "C:\Users\xhg73778\AppData\Local\mambaforge\envs\mantid-developer\lib\site-packages\matplotlib\colorbar.py", line 530, in _draw_all
    self._process_values()
  File "C:\Users\xhg73778\AppData\Local\mambaforge\envs\mantid-developer\lib\site-packages\matplotlib\colorbar.py", line 1103, in _process_values
    b = self.norm.inverse(b)
  File "C:\Users\xhg73778\AppData\Local\mambaforge\envs\mantid-developer\lib\site-packages\matplotlib\colors.py", line 1707, in inverse
    raise ValueError("Invalid vmin or vmax")
ValueError: Invalid vmin or vmax
Could not show instrument for workspace 'SXD23767':
unknown
```

**Pull request closed without merging**
