### PR TITLE
Refactor isis & sns data archives to use internethelper

### PR DESCRIPTION
**Pull request by NickDraper**
# To test

This needs to be tested at ISIS (develop tests done here) and SNS
1. startup mantiplot
2. tick the search archives box in the data paths dialog, or first use dialog
3. make sure your facility is selected
4. Load a file that is not on a local path eg MAR11067
5. If the file still loads then things are good

Ticket http://trac.mantidproject.org/mantid/ticket/11067

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
The builds failed on linuxes, I think because of the uppercase NET in SNSDataArchive.cpp:18, "#include <Poco/NET/HTTPResponse.h>". It also looks like on osx an include is needed for std::stringstream, probably <sstream>

Other than that everything looks fine. I could do the testing at ISIS and then leave it for someone at SNS to finish it.

**Comment by NickDraper** [comment]
Test this please

**Comment by NickDraper** [comment]
Jenkins test this please

**Comment by FedeMPouzols** [comment]
This works well here at ISIS (tested on win7). I'm not merging it as it still needs a check from someone at SNS. Just a note for other testers in case you run into the same issue: I started testing on a debian virtual machine inside the win7 machine, and for some reason it doesn't work well (the request is correctly sent through our proxy but at some point packets are being dropped).

Unassigning myself now. Please could someone at SNS give it a check?

**Comment by peterfpeterson** [comment]
This cannot  be cleanly merged into master. Please merge master into your branch and we can try again.

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please...

**Comment by FedeMPouzols** [comment]
Jenkins, don't lose hope and retest this please

**Comment by NickDraper** [comment]
jenkins, test this please.

**Pull request merged**
