### PR TITLE
Fix UnEx and Deprecation Warning in Waterfall Plots

### LINKED ISSUE #33913: Unhandled Exception when Adjusting Y Offset of Lines with Errorbar Caps
**Describe the bug**
Mantid throws an error reporter unEx when the cap size is >0 on a waterfall plot and the Y offset is adjusted. 

```
The modification of the Axes.lines property was deprecated in Matplotlib 3.5 and will be removed two minor releases later. Use Axes.add_line instead.
```
A lot of waterfall plot code also uses this functionality. It is mainly used to maintain the order of the lines in a plot such that they can be reliably offset. 

**To Reproduce**
1. Load a workspace and plot >=2 spectra into a waterfall plot
2. Open the figure options -> curves -> set the error bars visible -> set the caps >0
3. Close fig options
4. Click the toolbar button to adjust curve offset
5. Adjust the Y axis value

**Expected behavior**
1. The offset should be changed without errors

**Platform/Version (please complete the following information):**
 - OS: All
 - Mantid Version: 6.4 Nightlies

**Additional context**

Stack Trace:
```
Traceback (most recent call last):
File "C:\MantidNightlyInstall\bin\mantidqt\widgets\waterfallplotoffsetdialog\presenter.py", line 27, in
self.view.y_offset_spin_box.valueChanged.connect(lambda: self.update_y_offset())
File "C:\MantidNightlyInstall\bin\mantidqt\widgets\waterfallplotoffsetdialog\presenter.py", line 55, in update_y_offset
self.ax.update_waterfall(self.view.get_x_offset(), new_y)
File "C:\MantidNightlyInstall\bin\mantid\plots\mantidaxes.py", line 1101, in update_waterfall
self.lines.add_line(cap)
AttributeError: 'ArtistList' object has no attribute 'add_line'
```

### LINKED ISSUE #33950: Matplotlib deprecation warning about `Axes.lines` property
**Describe the bug**
There is a matplotlib deprecation warning that needs to be fixed.
```
The modification of the Axes.lines property was deprecated in Matplotlib 3.5 and will be removed two minor releases later. Use Axes.add_line instead.
```

**To Reproduce**
From a conda environment (matplotlib > 3.5):

1. Run the following script in mantid
```
from mantid.simpleapi import *
import matplotlib.pyplot as plt
from matplotlib.ticker import (MultipleLocator, AutoMinorLocator)

#Example data
exp_decay = CreateSampleWorkspace(Function='User Defined',
                                  UserDefinedFunction='\
                                  name=ExpDecay,Lifetime = 20,Height = 200;name=Gaussian,\
                                  PeakCentre=50, Height=10, Sigma=3',
                                  XMax=100, BinWidth=2)

#Create figure and axes
fig, axes = plt.subplots(ncols=2,nrows=1,subplot_kw={'projection': 'mantid'})

# Plot with errorbars on the left set of axes
axes[0].plot(exp_decay, specNum=1, color='red', label='400 K', linewidth=1.0, drawstyle='steps')
axes[0].set_title('Steps and Grids')
axes[0].xaxis.set_minor_locator(AutoMinorLocator())
axes[0].grid(True, which = 'both', axis = 'both') # major/minor, x/y

# Add an inset, use trial and error to find the right location
inset = fig.add_axes([0.77, 0.70, 0.18, 0.18],projection='mantid') #[left, bottom, width, height]
inset.plot(exp_decay, specNum=5, color='blue', label='Log Peak', marker ='.')
plt.yscale('log') #only affects the most recently called axes
inset.set_xlim(40, 60), inset.set_ylim(5, 20)
inset.xaxis.set_minor_locator(AutoMinorLocator()) #inserts 5 minor b/w each major
inset.tick_params(which='minor', width = 0.5, length=4, color='b', direction='in', top='on')
inset.set_title('Inset')

#Plot on the right set of axes
axes[1].errorbar(exp_decay, specNum=1, capsize=2.0, errorevery=5, color='green', label='spec 1', linestyle='--')
axes[1].set_xlabel('Time-of-flight ($\mu s$)', fontsize = 12, fontstyle = 'italic', fontweight = 'bold')
axes[1].set_ylabel('Counts ($\mu s$)$^{-1}$')
axes[1].set_title('Errorbars')

#Use tight layout for subplots and create a legend
plt.tight_layout()
fig.legend(loc='center right')

fig.show()
```
3. Click on the cog (plot options)
6.  Change the Axes to `Errorbar (0,1)`, and `Apply`. There is a deprecation warning:
```
The modification of the Axes.lines property was deprecated in Matplotlib 3.5 and will be removed two minor releases later. Use Axes.add_line instead.
```

**Expected behavior**

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: [e.g. Windows, RHEL 7, Ubuntu, macOS]
 - OS Version:
 - Mantid Version [e.g. 6.0.0]

**Additional context**

### PR DESCRIPTION
**Pull request by cailafinn**
**Description of work.**
Fixed an unhandled exception in waterfall plots and a deprecation warning. 

This has been a nightmare. There isn't a clean way to control the order of the lines in a plot without using a (now) deprecated accessor. ~~As a result, these changes result in some regressions in the way that waterfall plots function. Whether these are worth the fix is worth discussing.~~

1. ~~The fill on waterfall plots is no longer maintained when changes are made to the figure options. This will need to be re-set each time.~~
2. ~~The order of the lines in the plot is no longer maintained. This makes the "reverse order" button act a bit more like a shuffle.~~
~~(The tests related to these have, as a result, been removed)~~

We are now simply suppressing the warning. The shuffling of the reverse button is actually a separate issue that was introduced from the 3.5 upgrade rather than any of these changes. Here: #34006

**To test:**
1. Plot a graph of a workspace
2. Right click the figure and change the plot type to waterfall. 
4. Change the offset using the |<>| toolbar button
5. May as well set a fill as well to show that behaviour
6. Open the figure options (cog)
7. Switch to the curves tab and then the inner errorbars tab
8. Unhide the errorbars and set a capsize
9. Apply to all
10. Click okay
11. Adjust the offset again
12. No exception should be seen

Fixes #33913 

Also fixes #33950 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by sf1919** [comment]
This will need testing on both Conda and non-Conda builds as we will be releasing both versions.

**Comment by AnthonyLim23** [comment]
When changing the error bars (turning them on or off) resets the fill of the plot. Is that the expected behaviour?

**Comment by ConorMFinn** [comment]
Yeah, those are the regressions mentioned in points 1. and 2. in the description of work section. This was due to being to edit the `ax.lines` property being deprecated. We can't edit it to fix the order, so re-plotting ends up changing them. The fill being removed is part of this as the order changing meant the fills didn't line up, so the neatest solution was to remove the fill.

**Comment by AnthonyLim23** [comment]
ok, just wanted to double check

**Review by AnthonyLim23 — DISMISSED** [review]
Looks good to me. Works as expected and a proper fix is planned.

**Review by MialLewis — DISMISSED** [review]
Working on conda, regressions are as described in the PR.

**Comment by robertapplin** [comment]
This also fixes #33950

**Comment by DannyHindson** [comment]
Just gatekeeping a few issues and came across this one. Are you all happy this gets merged now or do you want to run it past Martyn when he's back (tomorrow)? Conor mentions in the description that the pros\cons of removing the deprecation warning perhaps need to be discussed. I'll leave it alone for this evening...

**Comment by ConorMFinn** [comment]
I think it's worth running by Martyn. There might be a better solution, but if there is I can't find it. Either another dev can take a look or we can spend a bit more time on it during maintenance

**Comment by ConorMFinn** [comment]
This has had some fairly major changes made since before and should no longer contain regressions, so could it be re-reviewed?

**Comment by MialLewis** [comment]
> This has had some fairly major changes made since before and should no longer contain regressions, so could it be re-reviewed?

will pick this up tomorrow morning

**Review by MialLewis — APPROVED** [review]
Now working, no deprecation warnings, no regressions.

**Pull request merged**
