### PR TITLE
ConvFit sample log update

### LINKED ISSUE #14267: ConvFit Sample and Resolution filename
The sample logs should include the name of the resolution file as well as the name of the sample file. These should be named:
* `sample_filename`
* `resolution_filename`

*`sam_workspace` already exists in ConvFit sample logs but should be renamed as shown above.*

### PR DESCRIPTION
**Pull request by ElliotAOram**
Fixes #14267

The output workspace from ConvFit should now contain `sample_filename` and `resolution_filename`

**Data for testing is available from `/ExternalData/Testing/Data/UnitTest/`**
# To Test
- Open ConvFit (Interfaces > Indirect > Data Analysis > ConvFit)
- Sample = `irs26176_graphite002_red.nxs`
- Resolution = `irs26173_graphite002_res.nxs`
- Change Fit Type to `One Lorentzian`
- Check `Temp. Correction` and enter a value into the corresponding input field
- Click `Run`
- Ensure that the OutputWorkspace (ending in `_Result`) contains sample_filename, resolution_filename, temperature_correction and temperature_value.
- Ensure that the workspaces in the group workspace (workspace ending in `_Workspaces`) also has these entries in the log (It is probably only necessary to check one or two of these workspaces)

### CODE REVIEW

**Comment by ElliotAOram** [comment]
This require validation to ensure that is use temp corr is checked then there must be a value in the corresponding field.

**Comment by ElliotAOram** [comment]
Merged with master to accommodate for VS2015 updates

**Comment by shahrozahmed1** [comment]
this branch is still not up to date, once the branch has been updated it can be merged to master.

**Comment by ElliotAOram** [comment]
This pull request has been closed due to incorrect merging. To avoid confusion I shall open a fresh pull request

**Pull request closed without merging**
