### PR TITLE
EngDiff UI Grey out Inspect Background button until usable

### LINKED ISSUE #29099: Grey out inspect background button of Eng Diff UI fitting until valid
Grey out the "inspect background" button in the fitting tab until the pre-requisites are met (row selected with background subtraction run).

### PR DESCRIPTION
**Pull request by clayton-tom**
**Description of work.**
Grey out (disable) the Inspect Background button until a run with a background subtraction has been selected.

**Report to:** Richard Waite

**To test:**
1. Open up the Engineering Diffraction GUI (Interfaces -> Diffraction -> Engineering Diffraction)
2. Go to the fitting tab
2. Load a couple of focused run files, e.g.
[29099test.zip](https://github.com/mantidproject/mantid/files/5161812/29099test.zip)
3. Ensure Inspect Background button is disabled initially
4. Tick `Subtract BG` checkbox for one run, select this row and check the button enables (and works)
5. Check that the button remains greyed out for the other run
6. Check the box for both runs, select both and ensure button is enabled and produces two plots
7. Deselect and check the button is disabled

Fixes #29099 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by RichardWaiteSTFC** [comment]
Nice work the button is greyed unless the subtract background checkbox is checked. Ideally we want to enable the inspect background button when the background has been calculated even if it is not currently subtracted from the data (i.e. the subtract bg checkbox has been ticked in the past but might not currently be ticked) - which is best determined by looking for the workspace key in the model.bg_params attribute (you won't need to change the plotting code - it can handle that scenario). If the condition for enabling the inspect background could query have a `if ws_name in self.model.get_bg_params:` that'd be great

**Review by RichardWaiteSTFC — DISMISSED** [review]
Looks good, turns out the plotting background doesn't work for a ws with a calculated bg but not subtracted which as discussed offline is something best left for another PR - thanks for checking it out.

**Review by DavidFair — DISMISSED** [review]
Could we add a/some test(s) to `test_data_presenter` to make sure this does not regress in the future?

(An example of how to mock the view in that file is `test_worker_success_valid_filename_no_sample_logs`)

Once that's done I'm happy to :shipit:

**Comment by martyngigg** [comment]
This was approved before freeze on Friday and just needed a test. I'm happy for this to go into 5.1

**Review by martyngigg — APPROVED** [review]

**Pull request merged**
