### PR TITLE
Enable peaks overlay for the nonorthogonal slice viewer.

### LINKED ISSUE #27464: Workbench Sliceviewer: non-orthogonal axes
As a user of the sliceviewer, with data in the HKL frame, I want to have an option to toggle non-orthogonal axes in the view such that the axes are aligned with the axes in the crystal coordinate system.

The peaks workspace display should have the peaks transformed appropriately.

The line viewers should show the integrated intensity along the respective reciprocal lattice vectors.

It would be acceptable that the minimal viable product disables the line and peaks viewer in non-orthogonal mode.

Useful matplotlib links:
  - https://matplotlib.org/examples/axes_grid/demo_curvelinear_grid.html
  - https://matplotlib.org/gallery/images_contours_and_fields/affine_image.html?highlight=affine%20image

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Adds support for peaks workspace overlays for non-orthogonal axes in the new slice viewer.

**To test:**

The following script creates a fake peak at a known HKL.

```python
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

ws = CreateMDWorkspace(Dimensions='3', Extents='-5,5,-5,5,-5,5',
                       Names='H,K,L', Units='r.l.u.,r.l.u.,r.l.u.',
                       Frames='HKL,HKL,HKL',
                       SplitInto='2', SplitThreshold='50')
expt_info = CreateSampleWorkspace()
ws.addExperimentInfo(expt_info)
SetUB(ws, 1,1,2,90,90,120)
FakeMDEventData(ws, PeakParams='1e+06,0,1,0,0.5', RandomSeed='3873875')
peaks_ws = CreatePeaksWorkspace(ws, 1)
peaks_ws.getPeak(0).setHKL(0,1,0)
```

* Run the script
* Open the sliceviewer
* Click the non-orthogonal axes button
* Click the peaks overlay button
* The peak should be displayed at [0,1,0] on the Axes.

Play around with the UB, add more peaks and check clicking on the peaks zooms to them correctly.

Fixes #27464

*This does not require release notes* because **the sliceviewer release notes will be created separately.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by RichardWaiteSTFC** [comment]
Have found exception when viewing an integrated and non-integrated peaks in non-orthogonal view and changing the viewing axes (x,y,z) .
image

**Comment by RichardWaiteSTFC** [comment]
There is also an issue with zooming in on peaks - the extent of the binned data decreases as the user zooms in which can lead to peaks disappearing into unbinned regions.
image

**Comment by martyngigg** [comment]
As discussed offline the issue mentioned in the previous comment is not an issue with the peaks overlay so it will be handled by a separate issue: #29165

**Review by RichardWaiteSTFC — COMMENTED** [review]
> Looks good - as discussed during testing some issue with axes limits and binning in non-orthogonal view were found but these are separate to this PR and an issue has been created.

Sorry meant to add this as the review...

**Review by RichardWaiteSTFC — APPROVED** [review]
Looks good - as discussed during testing some issue with axes limits and binning in non-orthogonal view were found but these are separate to this PR and an issue has been created.

**Comment by DavidFair** [comment]
Plus some tidying too :+1:

**Pull request merged**
