### PR TITLE
Allow individual log level control for each channel

### LINKED ISSUE #12703: Update logging properties configuration
This issue was originally [TRAC 11865](http://trac.mantidproject.org/mantid/ticket/11865)

It would be really useful to be able to log to console at ```notice``` and file at ```information```. However, the current [http://docs.mantidproject.org/nightly/concepts/PropertiesFile.html#logging-properties documentation] does not explain how to have ```logging.channels.fileFilterChannel.level``` be lower than ```logging.loggers.root.level```. Update the documentation to explain how to do this.

### PR DESCRIPTION
**Pull request by NickDraper**
fixes #12703

Extends the logging to allow individual control of logging per output channel.
- console
- file
- GUI message display

The GUI message display is controlled by the right click action as before, but there are now two python commands to control the other log channels.  They can also be altered by using the config file if you want to make a longer term change.

``` python

   #Set the console to log at debug level on above (7=debug)
  ConfigService.setConsoleLogLevel(7)
  #Set the file to only log at critical level (1=critical)
  ConfigService.setConsoleLogLevel(7)
```
### To test
1. start up python
2. load the log file
3. look at the console output
4. change the log settings using the right click on the log output in the GUI, and the python commands above and check they respond ok.
5. changes to the GUI log level will be remembered on startup, but not the others.

Documentation has been updated, but this is too internal to mention in the release notes.

### CODE REVIEW

**Comment by peterfpeterson** [comment]
There is  an off by one error somewhere in this. Setting the log level (via python or properties file) to `5`   / `information` only logs at `notice`. Setting it to `debug` logs at `information`.

Also, the `PropertiesFile.rst` should have an extra row in the table for `logging.loggers.consoleFilterChannel.level` as it is a new attribute.

**Comment by NickDraper** [comment]
Sorry the documentation was wrong- I forgot about that 1 = Fatal, not critical.  This means that 6 = information, not 5.  I've changed all the tooltips and doc examples.

I've also set the file channel to log at information by default.
The root level is also set to information, but is filtered up to notice for the console and gui.

If you drop a logging level at runtime below the root level it will automatically drop the root level too.

**Comment by NickDraper** [comment]
Also added the update to PropertiesFile.rst

**Comment by peterfpeterson** [comment]
I'm ready to pass this if you undo your change to `Fit.cpp` which was commented as "temporary".

**Comment by NickDraper** [comment]
The "temporary" change is important, and should be committed with this pull request.  Without it you get unit tests failing.  There is an "undocumented feature" in Fit that causes the additional call to minimizer->costFunctionVal() on line 186, when the logging level is info or below to change the value of some of the final fitted parameters very slightly.  Roman is tracking down the underlying cause of this in  issue #12948. In the mean time the temporary fix is to remove the conditional logging statement.

The "undocumented feature" was not caused in this work, just discovered.  If you drop the logging level in the properties file on master then you will get the same unit test failures.

**Pull request merged**
