### PR TITLE
QLRun Mantid Algorithm

### LINKED ISSUE #13826: Indirect Bayes Quasi change QLRun to Mantid Algorithm
~~Quasi can take quite a long time to run and currently it has poor progress tracking. It would be good to update this to work properly. So that it tracks the global state of the algorithm running rather than each individual child in the tracking progress bar.~~

This issue was previously about the above, it will now deal with the conversion of the python script to an algorithm. The Progress tracking will be dealt with in a separate issue. #13944

### PR DESCRIPTION
**Pull request by ElliotAOram**
Fixes #13826

QLRun is now a Mantid algorithm as opposed to the previously used script. This is normally run in the Indirect Bayes : Quasi interface.
# To Test
- Open Quasi (Interfaces > Indirect > Bayes > Quasi)
- Load in a sample and resolution
  - Sample = `ExternalData\Testing\Data\DocTest\irs26176_graphite002_red.nxs`
  - Resolution = `ExternalData\Testing\Data\DocTest\irs26173_graphite002_red.nxs`
- All the default options should be fine in the interface
- Click Run 
  - _There is currently no Progress Tracking on this algorithm. This will be in #13944 after this branch is merged._
- Ensure the following workspaces are produced:
  - `irs26176_graphite002_QLd_Prob` <- MatrixWorkspace
  - `irs26176_graphite002_QLd_Result` <- MatrixWorkspace
  - `irs26176_graphite002_QLd_Workspace` <- WorkspaceGroup
    - The WorkspaceGroup should contain workspaces 0-9
- Ensure the mini plot is updated in the interface and the result looks reasonable.
  _If you wish to ensure the clarity of the data, you could potentially compare it to data produced by 3.5 version of Mantid. No changes have actually been made to the workflow of the algorithm._

### CODE REVIEW

**Comment by mantid-roman** [comment]
It didn't work for me:

AlgorithmManager:: Unable to create algorithm QLRun Algorithm not registered QLRun

**Comment by SpencerHowells** [comment]
Don't forget this only runs on Windows because of the Fortran code.

**Comment by mantid-roman** [comment]
I am on Windows

**Comment by ElliotAOram** [comment]
@mantid-roman I've just tried running it my end and it seems to pick it up fine. 
image

**Comment by mantid-roman** [comment]
It was my mistake - I didn't have mingw in my path.
Now if I select Stretched Exponential I get this:

```
Error in execution of algorithm QLRun
global name 'program' is not defined
  at line 189 in 'C:/Users/hqs74821/Work/mantid/Framework/PythonInterface/plugins/algorithms\WorkflowAlgorithms\QLRun.py'
```

**Comment by ElliotAOram** [comment]
This algorithm needs to be added to the system test before it can be included
Furthermore, the doctest will need to be adapted to accept any output due to the fact the code can only run on windows.

**Comment by ElliotAOram** [comment]
@mantid-roman This should be ready to test again, apologies for the delay!

**Pull request merged**
