### PR TITLE
Fix equations in docs

### PR DESCRIPTION
**Pull request by peterfpeterson**
~~Do not merge before #29814.~~

This PR does three things:
1. Change the rendering of equations in html to use [mathjax](https://www.mathjax.org/)
2. Change the rendering of equations in qtassistant to use pngmath
2. Some of the equations in the absorption and multiple scattering concept page had an error and did not render correctly.

**To test:**

Build the documentation and look at the absorption and multiple scattering page. All equations should render.

*There is no associated issue.*

#29817 is the version into `ornl-next`.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by peterfpeterson** [comment]
In the `conf.py` add
```
rst_prolog = r"""\
.. only:: html
  :math:`\renewcommand\AA{\unicode{x212B}}`
"""
```

**Review by AndreiSavici — CHANGES_REQUESTED** [review]
I would leave `\AA` and modify cmake or conf.py to use mathjax for html and imgmath for qthelp

**Comment by AndreiSavici** [comment]
The html build looks OK, the qthelp is till using mathjax, not imgmath

**Review by AndreiSavici — APPROVED** [review]
Works now. I had to clean my cmake cache. Might need clean nightly builds

**Comment by peterfpeterson** [comment]
To get the correct math render in qthelp on a local build, you'll need to `cmake -DDOCS_MATH_EXT=sphinx.ext.imgmath .` in your build directory before rebuilding with this.

**Pull request merged**
