### PR TITLE
Faster, simpler EventList::sortTof

### PR DESCRIPTION
**Pull request by quantumsteve**
Description of work.

This replaces a lot of custom logic with `tbb::parallel_for` and `tbb::parallel_sort`. Besides being simpler code ( 324 fewer lines!), it also appears to be significantly faster. I ran `DataObjectsTest.EventListTestPerformance` and the total time decreased from 2.03 seconds to 1.22 seconds. `test_sort_tof`decreased from 0.29 seconds to 0.13 seconds. 

**To test:**

Try this on larger, "real" data and verify that performance still improves.

There is no GitHub issue associated with this pull request.

Release notes?

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by peterfpeterson** [comment]
Results from running on my 24 core (w/ hyperthreading) for some arbitrary NOMAD data running `AlignAndFocusPowder` in a "real" situation. Note that there is some dependencies from disk cache.

```
stats: median, mean, stddev
=======master
real  68.0  84.4 21.8
user 596.0 596.2  2.0
sys   31.0  31.4  1.0
=======tbb_EventList
real  60.0  60.2  1.0
user 610.0 608.2  3.1
sys   34.0  34.0  1.4
```

**Comment by quantumsteve** [comment]
@mantidproject/tech-steering We would appreciate additional options on this PR. Despite the tiny improvements Pete found, this improves the situation on MacOS and removing 321 lines of Mantid code is a win in itself. This would also make it easier to [change parallel sorting algorithms](https://software.intel.com/en-us/articles/a-parallel-stable-sort-using-c11-for-tbb-cilk-plus-and-openmp) in the future (see [start of Mantid branch](https://github.com/mantidproject/mantid/compare/parallel_stable_sort?expand=1)).

**Comment by SimonHeybrock** [comment]
Definitely :+1: from me, code looks much better and going from 84 seconds to 60 seconds it not so minor!

**Comment by OwenArnold** [comment]
Looks good. Well done @quantumsteve.

**Comment by martyngigg** [comment]
Very nice. It has always bugged that we had so much custom code for sorting.

**Review by peterfpeterson — APPROVED** [review]

**Comment by peterfpeterson** [comment]
The simpler code using a better supported (by someone else) parallel sort are good improvements. :shipit: once builds pass.

**Pull request merged**
