### PR TITLE
Port MaxEnt from fortran

### LINKED ISSUE #12683: Port maxEnt to Python from FORTRAN
This issue was originally [TRAC 11845](http://trac.mantidproject.org/mantid/ticket/11845)

F2Py usage limits the code to windows only.

Look to port and document the code to python (or C++ if performance requires it).

 - - - - 
Keywords: muonOther

### PR DESCRIPTION
**Pull request by raquelalvarezbanos**
Fixes #12683

This is a first version of MaxEnt. There are many things that can be improved and are likely to be changed.

No mention in the release notes for the moment.

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
Example script with some of the cases I've tested:

```
from math import pi, sin, cos
from random import random

# Create a test workspace
X = []
Y = []
E = []
N = 200
w = 3
for i in range(0,N):
       x = 2*pi*i/N
       X.append(x)
       Y.append(sin(w*x))
       #Y.append(sin(w*x))
       #Y.append(sin(2*w*2*pi*i/N)+(random()-0.5)*0.2)
       #Y.append(cos(2*w*2*pi*i/N)+(random()-0.5)*0.2)
       #Y.append(sin(w*x)-0.5*cos(2*w*x))
       #Y.append(cos(w*x)+cos(2*w*x)+(random()-0.5)*0.5)
       E.append(0.1)

CreateWorkspace(OutputWorkspace='ws',DataX=X,DataY=Y,DataE=E,NSpec=1)
MaxEnt(InputWorkspace='ws', EvolChi='EvolChi', EvolAngle='EvolAngle',ReconstructedImage='image',ReconstructedData='data',chiTarget=N,Background=0.001)
```

**Comment by raquelalvarezbanos** [comment]
Another script example:

```
X = []
Y = []
E = []
N = 200

for i in range(0,N):
       x = ((i-N/2) *1./N)
       X.append(x)
       Y.append(0)
       E.append(0.001)
       
# One Fourier coefficient
suffix = 'One'
Y[5] = Y[195] = 0.85
CreateWorkspace(OutputWorkspace='ws'+suffix,DataX=X,DataY=Y,DataE=E,NSpec=1)
MaxEnt(InputWorkspace='ws'+suffix, EvolChi='EvolChi'+suffix, EvolAngle='EvolAngle'+suffix,ReconstructedImage='image'+suffix,ReconstructedData='data'+suffix,chiTarget=N,Background=0.0001)

# Two Fourier coefficients
suffix = 'Two'
Y[5] = Y[195] = 0.85
Y[10] = Y[190] = 0.85
CreateWorkspace(OutputWorkspace='ws'+suffix,DataX=X,DataY=Y,DataE=E,NSpec=1)
MaxEnt(InputWorkspace='ws'+suffix, EvolChi='EvolChi'+suffix, EvolAngle='EvolAngle'+suffix,ReconstructedImage='image'+suffix,ReconstructedData='data'+suffix,chiTarget=N,Background=0.0001)

# Three Fourier coefficients
suffix = 'Three'
Y[5] = Y[195] = 0.85
Y[10] = Y[190] = 0.85
Y[20] = Y[180] = 0.85
CreateWorkspace(OutputWorkspace='ws'+suffix,DataX=X,DataY=Y,DataE=E,NSpec=1)
MaxEnt(InputWorkspace='ws'+suffix, EvolChi='EvolChi'+suffix, EvolAngle='EvolAngle'+suffix,ReconstructedImage='image'+suffix,ReconstructedData='data'+suffix,chiTarget=N,Background=0.0001)
```

**Comment by raquelalvarezbanos** [comment]
Real muon dataset:

```
Load(Filename=r'MUSR00022725.nxs', OutputWorkspace='MUSR00022725')
CropWorkspace(InputWorkspace='MUSR00022725', OutputWorkspace='MUSR00022725', XMin=0.11, XMax=1.6, EndWorkspaceIndex=0)
RemoveExpDecay(InputWorkspace='MUSR00022725', OutputWorkspace='MUSR00022725')
Rebin(InputWorkspace='MUSR00022725', OutputWorkspace='MUSR00022725', Params='0.016')
MaxEnt(InputWorkspace='MUSR00022725', EvolChi='evolChi', EvolAngle='evolAngle', ReconstructedImage='image', ReconstructedData='data',Background=0.005,ChiTarget=250)
```

**Comment by Anders-Markvardsen** [comment]
Works with the example provided.

Clear code to read including choice of method/attribute names and code documentation. Clear algorithm documentation

**Pull request merged**
