### PR TITLE
34367 Diffraction RB Number box validation and unit tests

### LINKED ISSUE #34367: EngDiff UI tries to save files to invalid paths if punctuation in RB Number box
**Describe the bug**
Punctuation such as (\ : - /) in RB Number box in the EngDiff UI results in the save directory being truncated and the interface tries to write files (from calibration and focus tabs) into directories which do not exist. 

**To Reproduce**
(1) Follow Test 2 in the manual testing instructions (latest version not yet merged) - using punctuation e.g. `My_RB-Num\ber`
https://github.com/mantidproject/mantid/blob/33e61abf3a7ed9a3e352ca91886efe03d9afc5b8/dev-docs/source/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.rst

**Expected behavior**
Overwrites RB number entered with truncated string - or doesn't accept punctuation?

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: [e.g. Windows, RHEL 7, Ubuntu, macOS]
 - OS Version:
 - Mantid Version [e.g. 6.0.0]

**Additional context**

### PR DESCRIPTION
**Pull request by warunawickramasingha**
**Description of work**
Punctuation such as (\ : ~ # } / $ ) in RB Number box in the EngDiff UI results in the save directory([Save location]/user/[RB number]) being truncated and the interface tries to write files (from calibration and focus tabs) into directories which do not exist.

**Summary of work**
When invalid characters are present in the RB number box of the EngDiff UI, it tries to create invalid paths that violates directory naming conventions. Therefore, before going further ahead with the processing, the value in the RB Number box is validated and the user is prompted with a warning if the validation fails. 

**Further detail of work**
Python's regex library was used to do a validation for the value present in the RB Number field and the user is only allowed to proceed with the processing in the Calibration, Focus, and GSAS 2 tabs if the validation passes.

**To test:**

(1) Follow Test 2 in the manual testing instructions (latest version not yet merged) - using punctuation e.g. My_RB-Num\ber
https://github.com/mantidproject/mantid/blob/33e61abf3a7ed9a3e352ca91886efe03d9afc5b8/dev-docs/source/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.rst
(2) user should be prompted with an error if the value present in RB Number contains invalid characters to create a directory.

Fixes #34367 

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by SilkeSchomann — DISMISSED** [review]
The new box validation prevents users from entering invalid values. 👍

**Comment by robertapplin** [comment]
Qt provides us with several validation classes which we can use alongside the `setValidator` method on a QLineEdit widget https://doc.qt.io/qt-6/qlineedit.html#setValidator . Would using a `QRegExpValidator` be suitable for the purpose of this PR?

Here is an example of where it has been used elsewhere in the codebase https://github.com/mantidproject/mantid/blob/7b51bc910c34f610787978c4fa82f271125c65c8/qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/colorselector.py#L88

**Comment by warunawickramasingha** [comment]
@robertapplin Thank you very much for denoting the QRegExpValidator feature which will drastically reduce the number of code lines to fix this issue. I will update the PR with that feature. 
The only difference is now the user is not getting an error message after entering invalid characters but rather it is not allowed to enter the invalid values in the QLineEdit widget which is OK in this case.

**Review by robertapplin — DISMISSED** [review]
Thanks for the changes, functional it seems to work quite well. Happy to approve

**Comment by RichardWaiteSTFC** [comment]
Great suggestion @robertapplin - I didn't know about this!
I think it's just missing a release note, but happy to merge when that's added!

**Review by robertapplin — APPROVED** [review]

**Pull request merged**
