### PR TITLE
Feature/10774 calculate poldi 1d spectrum

### PR DESCRIPTION
**Pull request by MichaelWedel**
The original POLDI analysis software calculates a theoretical 1D spectrum in terms of d (which is converted to Q for plotting). Because the 1D spectrum contains information from all detectors, its calculation is very similar to that of the 2D spectrum.

This 1D-spectrum is mainly used in connection with the residual analysis. I would like to add this feature to the 2D-fit for completeness and easier comparison of results.

### CODE REVIEW

**Comment by MichaelWedel** [comment]
A system test was changed in this context as well, it's in the following pull request:
https://github.com/mantidproject/systemtests/pull/9

**Comment by MichaelWedel** [comment]
test this please

**Comment by MichaelWedel** [comment]
Sorry, I forgot to add testing information, adding that now.

**Testing information**
Make sure the algorithm now also outputs a 1D-spectrum (diffractogram). The usage example for PoldiFitPeaks2D has been adapted, so along with the 2D-spectrum that is in `OutputWorkspace`, there is also a diffractogram of Silicon in `Calculated1DSpectrum`.

**System test**
The system test also checks that the 1D spectrum, it is in the following pull request:
https://github.com/mantidproject/systemtests/pull/9

**Comment by FedeMPouzols** [comment]
Verifying this together with its sibling systemtest/ pr: https://github.com/mantidproject/systemtests/pull/9

**Comment by FedeMPouzols** [comment]
All looks very good to me and tests pass.

**Comment by FedeMPouzols** [comment]
There's a bug in some gcc 4.9 versions (4.9.1) that makes gcc fail when compiling a test generated by CxxTest:
`PoldiSpectrumConstantBackgroundTest::testParameterCount(): "internal compiler error: in possible_polymorphic_call_targets, at ipa-devirt.c:1557"`. 
Just noting it here in case this shows up at some point later on. Upgrading to 4.9.2 fixes the issue I think.

**Pull request merged**
