### PR TITLE
Add requests library

### PR DESCRIPTION
**Pull request by Matthew-Andrew**
**Description of work.**

This adds the requests library to Mantid. The requests library is the defacto standard for managing http messaging in python although is unfortunately not  in the standard library. The need for more sophisticated requests has come about due to some upgrades to the error reporting service with plans currently in place to upload the recovery files generated by mantid as well as as screenshots of the current state. I would envisage it also being useful for any other Http based messaging required in the future as well.

The alternative in the standard library is urllib/urllib2 but this has far less support for uploading large multipart files and also has a different name/interface for python 2/3 making writing compatible code with it difficult.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by quantumsteve — CHANGES_REQUESTED** [review]
Please add a justification for adding this dependency to Mantid. What do you plan to use it for that is missing from existing dependencies?

**Comment by Mantid-Matthew** [comment]
@quantumsteve I've added a justification to the description.

**Comment by martyngigg** [comment]
@Mantid-Matthew Could you fix up the merge conflicts here now.

**Comment by martyngigg** [comment]
@quantumsteve Do you have any objections here? I think it's reasonable as even the Python standard library docs recommend using `requests`: https://docs.python.org/3/library/urllib.request.html#module-urllib.request

**Review by quantumsteve — DISMISSED** [review]

**Comment by quantumsteve** [comment]
@martyngigg Using `requests` over `urllib` makes sense and I don't want to hold up work.

On a higher level I'm curious if we're duplicating functionality in the C++ layer, and if that duplication is required and/or desirable? (Admittedly, I have the least experience with networking libraries in either language)

**Comment by martyngigg** [comment]
I think you're correct here. There is some level of duplication. @Mantid-Matthew Is the ErrorReporter class actually used anywhere in the C++ layer?

**Comment by Mantid-Matthew** [comment]
There is some level of duplication as we currently send some of the http requests through the internet helper class and half from the python layer, which I would agree is not desirable. This mainly came about because uploading files and images is better supported and therefore substantially easier in python. I don't think the error reporter class is called from anywhere in the C++ layer. Moving it to python would not end the duplication though as the InternetHelper class already exists to support the usage service. It is probably possible to do the file uploading from C++ but I would have to investigate exactly how.

**Comment by martyngigg** [comment]
`InternetHelper` also supports a wide variety of other places so we couldn't just get rid of that. I guess it's whether we ever see a need for `ErrorReporter` to be used from `C++` and when we get rid of MantidPlot we could consider just having it has a pure python implementation.

**Comment by martyngigg** [comment]
@Mantid-Matthew Could you fix the merge conflicts then we can get this merged?

**Comment by peterfpeterson** [comment]
Resolving the conflicts in `CMakeLists.txt` is non-trivial. I'm having a go at merging `master` into the branch and will push again. @quantumsteve or @martyngigg should look it over and approve again once that is done.

**Review by martyngigg — APPROVED** [review]
Looks good to me.

**Comment by quantumsteve** [comment]
:+1:

**Pull request merged**
