### PR TITLE
Elemental Analysis - Checkboxes

### LINKED ISSUE #23097: Elemental Analysis Data-Loading Checkbox Widgets
Add checkbox widgets for peak type and detector selection

### PR DESCRIPTION
**Pull request by ewancook**
**Description of work.**
Adds:
- Popup window for element peak selection
- Printing out of selected element data (as above)
- Detector and Peak Type checkboxes

**Report to:** Aidy

**Expected Functionality**
- Checking/Unchecking the Peaks and Detectors checkboxes should do nothing (for this PR)
- Right clicking an element should bring up a widget with only Primary Peaks selected (initially), on changing this, the state should be preserved when closed
- Left clicking an element after modifying its popup should print out the selected peaks
- Changing the peak data file should close all open element popups and update the popup peak data with the new peak data. Example JSON is provided below:
```JSON
{
  "Ag": {
    "Z": 47,
    "A": 107.87,
    "Primary": {
      "K(4->1)": 3177.7,
      "K(5->1)": 3184.9,
      "L(3->2)": 868.1,
      "L(4->2)": 900.7,
      "M(4->3)": 304.7,
      "6->5": 141
    },
    "Secondary": {}
  }
}
```

**To test:**
Test for exceptions to the *Expected Functionality*

No unit tests are provided as, for this, they would be testing the implementation rather than the functionality.

Closes #23097 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by ewancook** [comment]
Some commits were duplicated in a rebase, and some follow from previous PRs

**Comment by AnthonyLim23** [comment]
selecting major/minor peaks does not alter the selection. Is this correct?

**Comment by ewancook** [comment]
Correct - this is being addressed in #23426

**Review by AnthonyLim23 — APPROVED** [review]
looks good

**Pull request merged**
