### PR TITLE
Fix LoadNXSPE incorrect detector size

### LINKED ISSUE #33370: Incorrect detector size in LoadNXSPE giving errors in SofQW3
**Original reporter:** R. Stewart / ISIS

**Describe the bug**

When using [MSlice](https://github.com/mantidproject/mslice) on some datafiles and for certain step sizes a "beating" or "aliasing" effect is observed, but not for other equivalent data. In some cases, this effect is inherent in the data and step size used and should be addressed by MSlice determining an appropriate default step size.

However, in some cases it is the result of a bug in the `LoadNXSPE` algorithm. For example:

mantid_sqw_nxspe_alias_bug

Here the cuts were produced using the same parameters with the `SofQWNormalisedPolygon` algorithm but on two different input data source - a reduced NeXus `.nxs` and NXSPE file respectively. The two files were producing using the same [reduction algorithms](https://github.com/mantidproject/mantid/blob/main/scripts/Inelastic/Direct/DirectEnergyConversion.py) - the only difference is that in one case `SaveNexus` was used and in the other case `SaveNXSPE` was used.

The bug is because `LoadNXSPE` uses a [fixed size detector](https://github.com/mantidproject/mantid/blob/bda448eb838c6afc307092c47aa2215d6d9f7a3f/Framework/DataHandling/src/LoadNXSPE.cpp#L276) which is always set to be a sphere of 1cm radius. However, this is actually often smaller than the physical detector size. Now the `SofQWNormalisedPolygon` algorithm actually calculates the `2theta` extends of each spectrum from the detector size. Since the detector size loaded from `.nxspe` files are smaller than the physical size, there artificial "gaps" in the scattering-angle representation of the data. When converted into Q-space by `SofQWNormalisePolygon` this leads to the aliasing behaviour shown in the picture above.

The NeXus `.nxs` files saves the original detector size so the `2theta` extents calculated by `SofQWNormalisedPolygon` is correct, and no aliasing is seen.

**To Reproduce**

Run this script:

```python
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

datadir = '//olympic/Babylon5/Public/duc/Ross nxspe files'
reffile = 'LET73024_rings_3.70'
step_size = 0.01166

wnxs = Load(datadir+'/'+reffile+'.nxs')
q_nxs = SofQW3(wnxs, EMode='Direct', QAxisBinning='0,%f,5' % (step_size), EAxisBinning='-0.5,10,0.5')
q_nxs = Transpose(q_nxs)
SaveNexus(q_nxs, datadir+'/'+'q_nxs.nxs')

wnxspe = Load(datadir+'/'+reffile+'.nxspe')
q_nxspe = SofQW3(wnxspe, EMode='Direct', QAxisBinning='0,%f,5' % (step_size), EAxisBinning='-0.5,10,0.5')
q_nxspe = Transpose(q_nxspe)
SaveNexus(q_nxspe, datadir+'/'+'q_nxspe.nxs')
```

and plot the generated `q_nxs` and `q_nxspe` workspaces. The data are on the babylon system `\\olympic\Babylon5\Public\duc\Ross nxspe files` - the `.nxs` file is 65MB, and the `.nxspe` file is 2MB.

**Expected behavior**
The two q-cuts look similar without the beating / aliasing in the cut from the `.nxspe` datafile.

**Platform/Version (please complete the following information):**
 - OS: Windows 10, Scientific Linux 7 (DAaaS system).
 - Mantid Version: nightly / master

### PR DESCRIPTION
**Pull request by mducle**
**Description of work.**

The `.nxspe` files define the detector positions using `polar` and `azimuth` angles in a spherical coordinate system, and the detector extents using a `polar_width` and `azimuth_width`. Whilst the `*_width` quantities are read in by the `LoadNXSPE` algorithm they are *not* used to generate the detectors in the generated workspace. Instead, the detectors are set uniformly to be spheres of radius 1 cm.

As described in issue #33370 this leads to problems when using the `SofQWNormalisedPolygon` on these workspaces because the 1 cm radius sphere is *smaller* than the true detector size and causes aliasing when rebinned into Q-space. 

This PR still keeps the detectors as spheres but sets their radius to be equal to the chord subtending the smaller of either the `polar_width` or `azimuthal_width` angles. In the particular datafiles which are the subject of issue #33370 this is ok because the data is actually the product of a `GroupDetectors` over rings of constant `2theta` so there is really only a single independent angle (the `polar` angle - the `azimuthal` angle is irrelevant for these data). For the other commonly used `.nxspe` data (a "1-to-1" mapping) the detectors are approximately square so the `polar_width` and `azimuthal_width` is approximately the same, so this fudge of using spherical detectors should also work. (In future it might be worthwhile to implement a "bannana" shaped detectors, but probably a better long term solution is to deprecate the `.nxspe` format in favour of the processed/reduced NeXus files).

**Report to:** R. Stewart / ISIS

**To test:**

Run the script in the issue #33370 and check you get this result:

mantid_sqw_nxspe_alias_bug_fixed

Additionally, you can also set the logging level to `Debug` and look at the start of the output of `SofQWNormalisePolygons` (`SofQW3`). This prints the calculated 2theta extents of the detectors. The values for the `.nxs` and `.nxspe` workspaces should now be similar (2theta widths of approximately 1 degree); previously the `.nxs` files had 2theta widths of ~1 deg, whilst the `.nxspe` files had widths of ~0.3deg

Fixes #33370. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by AndreiSavici — COMMENTED** [review]
Do you need release notes?

**Review by AndreiSavici — DISMISSED** [review]
I can still use the instrument view. Tested on SEQUOIA data

**Review by AndreiSavici — DISMISSED** [review]

**Review by SilkeSchomann — DISMISSED** [review]
Works well and fixes the problem that was caused by a fixed detector size in LoadNXSPE.

**Comment by martyngigg** [comment]
It looks like we have a system test failure in CNCS reduction.

**Comment by mducle** [comment]
@AndreiSavici could you check the new LoadNXSPE on CNCS data? For some reason it was inferring a negative radius in data from `CNCSReductionTest` (which might be from a negative `polar_width` or `azimuthal_width`. I've changed the code so that it takes the absolute value of the inferred radius but this might not be what we want. Unfortunately I'm working at home on a very slow connection and haven't managed to download the required files to run the systemtest myself...

**Comment by mducle** [comment]
@AndreiSavici sorry... I figured out how to download the files directly from the MD5 hash... and how to by pass the script which tries to download every test data... so the generated CNCS file gives a negative `azimuthal_width` of around -0.5 degrees whilst the `polar_width` is around 0.2 degrees. I've made another change which takes the smallest of the absolute of the widths... previously it just took the absolute of the smallest - e.g. made the pixels bigger than they should be.

**Review by AndreiSavici — APPROVED** [review]

**Pull request merged**
