### PR TITLE
Sans table change feature branch

### LINKED ISSUE #23022: Update sans GUI to use JobTreeView
The JobTreeView is now finished so should be put into the SANS GUI.

### PR DESCRIPTION
**Pull request by Matthew-Andrew**
**Description of work.**

This is a feature branch to add the JobTreeView to the SANS GUI in place of the DataProcessorWidget there are several advantages to this.
* Key board shortcuts for copy/paste/delete and tabbing
* A simplifying of much of the underlying code
* Greater flexibility going forward. 

**To test:**

This Feature branch is made up of several PR's these are
* #23139
* #23190
* #23338
* #23382

The main test left remaining here is to do a general overview of the GUI in it's new state and check that there are no regressions from the current state of master.

Fixes #23022  

Have updated release notes with user visible changes.
---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gemmaguest** [comment]
One thing I notice is that the error messages are less helpful. I loaded the test batch file and entered `20` in the event slicing box and got this error when I tried to process. I got the same error message when I changed the run number to `bad`:
`There seems to have been an issue with setting the states. Make sure that a user file has been loaded` 

v3.13.0 gives more helpful messages:
`There was a bad entry for row 0. The provided event slice configuration ['20'] cannot be parsed because of 20`
`There was a bad entry for row 0. Trying to find the SANS file bad, but cannot find it. Make sure that the relevant paths are added and the correct instrument is selected.`

**Comment by gemmaguest** [comment]
I'm not sure if it's related to this PR or a problem on master, but I have an error with the beam centre finder which doesn't occur in v3.13.0. I loaded the usual mask and batch file then clicked `Run` on the beam centre tab. It got `nan`s on the first iteration then threw an unexpected exception when it tried to plot it (due to #23114)

```
Starting centre finder routine...
Itr 0: ( 324.46, 330.99 )  SX=nan  SY=nan
```

**Review by gemmaguest — CHANGES_REQUESTED** [review]
See the 3 comments I made separately

Otherwise looks good and behaves as expected. The reflectometry interface and toy JobTreeView interface also still work fine.

**Comment by gemmaguest** [comment]
This all looks good now. The error messages now display as useful tooltips, and the tooltips are reset when cell data changes. It's nice that the row colour is also reset when the cell data changes.

The beam centre finder problem also occurs on master so is not related to this PR, so I think this is good to merge :+1:

As a side note, one other minor thing I noticed is that if you enter invalid inputs (e.g. clear the `Can Scatter` cell in the usual example), then the error message contains `\n` characters which are displayed as `\n` rather than newlines. This is the same in the old pop-up error message in v3.13.0 though so doesn't really relate to this PR.

**Review by gemmaguest — APPROVED** [review]

**Comment by martyngigg** [comment]
Failing system tests are those the known failures on `master` and are unrelated to this PR.

**Pull request merged**
