### PR TITLE
SEQ new idf

### LINKED ISSUE #21184: New IDF for SEQUOIA
New IDF for SEQUOIA from calibration using powder Vanadium, Si, and C60 data.

### PR DESCRIPTION
**Pull request by yxqd**
Description of work.

**To test:**

Load data before and on Nov 13, 2017 and data after and on Nov 14 to check the difference. It is most obvious for short packs around the beam

Fixes #21184 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by AndreiSavici — APPROVED** [review]

**Comment by AndreiSavici** [comment]
Also added a new issue (#21189)

**Comment by yxqd** [comment]
Thanks @AndreiSavici @quantumsteve !

**Comment by yxqd** [comment]
Hi @AndreiSavici / @quantumsteve  can you undo this pull request? We need to postpone the update.

**Comment by quantumsteve** [comment]
@yxqd You should see a revert button on the same line as the merge commit.

**Comment by yxqd** [comment]
Thanks @quantumsteve

**Pull request merged**
