### PR TITLE
Allow MDHistoWorkspace to be produced from NormPoly transformation

### LINKED ISSUE #13602: Allow and OutputMDWorkspace to be selected in NormalisedPolygon Method
Currently users cannot output an MDHistoWorkspace if they choose to use the NormalisedPolygon method in ConvertToReflectometryQ. 

There needs to be a method of producing an MDHistoWorkspace from the output of the FractionalRebinning used by ConvertToReflectometryQ.

This means that NormalisedPolygon (a more useful method) can then be used without such restrictions.

### PR DESCRIPTION
**Pull request by MattKing06**
Fixes #13602 

ConvertToReflectometryQ should now have no restrictions on whether or not you can output an MD Workspace when performing a NormPoly Transform.

**To Test**:

<b> Producing MDWorkspace </b>
- Load [data](https://slack-files.com/T02J4MMEW-F0AA5NGSY-405b51aad0) in Mantid
- Run this code through script interpreter:

``` python
out_ws, dump_vertexes = ConvertToReflectometryQ(InputWorkspace='data_th_lam',OutputWorkspace='QxQy_polyMD', OutputDimensions='Q (lab frame)',
Extents='-0.0005,0.0005,-0,0.2', OutputAsMDWorkspace=True,Method='NormalisedPolygon',  IncidentTheta=0.44, OverrideIncidentTheta=True, NumberBinsQx=100, NumberBinsQz=100,DumpVertexes=True, OutputVertexes='dump_vertexes')
```
- See that an MDHistoWorkspace called `QxQy_polyMD` is produced

<b> Produce 2D Workspace </b>
- Load [data](https://slack-files.com/T02J4MMEW-F0AA5NGSY-405b51aad0) in Mantid
- Run this code through script interpreter:

``` python
out_ws, dump_vertexes = ConvertToReflectometryQ(InputWorkspace='data_th_lam',OutputWorkspace='QxQy_poly2D', OutputDimensions='Q (lab frame)',
Extents='-0.0005,0.0005,-0,0.2', OutputAsMDWorkspace=False,Method='NormalisedPolygon',  IncidentTheta=0.44, OverrideIncidentTheta=True, NumberBinsQx=100, NumberBinsQz=100,DumpVertexes=True, OutputVertexes='dump_vertexes')
```
- See that a 2DWorkspace `QxQy_poly2D` is produced

<b> Comparing Plots </b>
- Open the MDHistoWorkspace in SliceViewer
- Open the 2DWorkspace in SliceViewer
- Compare the plots to make sure they are identical.

### CODE REVIEW

**Comment by ElliotAOram** [comment]
@MattKing06 The two slice views look identical expect the colour scale (left hand side) differs. For PolyMD the scale is from `5.14e+11 - 5.14e+01` where as the poly2D scale is from `1.03e+04 - 1.03e-06`
I don't know if this is an issue as I'm not too familiar with the interface. That aside, it functions as expected. I'll be happy to merge this is the above colour scaling feature is correct

**Comment by ElliotAOram** [comment]
@MattKing06 as a small aside, it might be worth adding progress tracking to ConvertToReflectometryQ. When I ran it from the scripts provided, it took about 30seconds to complete and it was a little unclear if it it was still working or if it had just crashed.
It would probably make most sense for this to be done in a separate issue.

**Comment by MattKing06** [comment]
@ElliotAOram I have added some changes to ConvertToReflectometryQ, when you test it be sure to test both outputting as an MDWorkspace, and as a 2DWorkspace (for both NormPoly and Center Transformations) as well. I don't think the algorithm would have allowed this before, but it should with this commit.

**Comment by ElliotAOram** [comment]
This looks fine functionality wise. It can be merged once it passes the tests.

**Pull request merged**
