### PR TITLE
Adding FFTPreProcessing into Frequency Domain Analysis

### LINKED ISSUE #20231: Adding padding and apodization to FDAG
Add in the functionality from #20216 into the frequency domain GUI

### PR DESCRIPTION
**Pull request by AnthonyLim23**
**Do not merge before #20310**

It should be possible to add padding and an apodization function to the data before a FFT. This PR incorporates the FFTPreProcessing algorithm into the Frequency Domain Analysis GUI. The FFT part of the GUI has been tested see #20205 but there has been some refactoring since. 

**To test:**

0. Open muon analysis and load some data (current run will do). **If you do not do this it will not work** 

1. Open Frequency Domain Analysis GUI. 
2. Try different combinations of the advanced options and the spectrum (0) should change. The output will be under the group workspace (e.g. MUSR00023456) 

If you show the hidden workspaces then you can inspect the intermediate outputs. These are the time domain functions multiplied by an equation and with extra zeros added. 

3. If the workspace is set PhaseQuad then the table will look a little different. Before pressing the button make sure the data archive search is on. 

4. This should produce a PhaseTable  and add a workspace to the group (like step 2). 

5. Turning off the generate new phase table and pressing the button does not change the phase table (I suggest opening the phase table first and changing the axis), when the button is pressed it should not change.

6. Turn on the generate new phase table and see that it does change,.   

Fixes #20231 . 

**Release Notes** 

The documentation will be updated in #20312 
---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
This is important to stay in this release

**Comment by AnthonyLim23** [comment]
```
import mantid.simpleapi as mantid

ws = mantid.AnalysisDataService.retrieve("__phaseQuad__")

first = ws.getSpectrum(0)
second = ws.getSpectrum(1)

mantid.AnalysisDataService.addOrReplace("first",ws.getSpectrum(0))
```
need to pass a spectrum to each of Re and Im. 

Need to add some tests and maybe disable the button (see maxEnt). 

should add a "make phase table" row in FFT table

-- refactor later to make generating a phase table an algorithm.

**Comment by AnthonyLim23** [comment]
the latest merge of master has caused some threading errors. Investigating it now

**Comment by AnthonyLim23** [comment]
fixed the crashes. Just flake 8 to fix

**Comment by NickDraper** [comment]
@AnthonyLim23 This has a collection of merge conflicts that need your attention.

The build failures or at least some of them are unrelated, and something Martyn is fixing

**Comment by AnthonyLim23** [comment]
@NickDraper  it should be easy as the current version has already solved the merge conflicts with master (which had MaxEnt merged). 

I am currently fixing the failing tests.

**Comment by AnthonyLim23** [comment]
The names of the files will be dealt with in a separate issue #20655

I think this is ready to review/test

**Review by mantid-roman — APPROVED** [review]
It works.
Maybe for the future: code needs more comments and docstrings

**Pull request merged**
