### PR TITLE
Update Qt library names in the OS X packaging script.

### PR DESCRIPTION
**Pull request by quantumsteve**
Description of work.

This updates the library name to patch what is reported by `otool -L`. OS X 10.9 and 10.10 seem OK with the wrong path, but on 10.11, `install_name_tool` isn't changing the library name, causing a sanity check to fail.

**To test:**

Check if you can make a package on OS X 10.11 and the current OS X build servers still pass.

This issue has no associated issue.

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gvardany** [comment]
This worked on El Capitan, but looks like it fails on previous OS X versions. Should we have an if statement to check the version and put the paths correspondingly?

**Comment by quantumsteve** [comment]
@mantidproject/gatekeepers Can we get this into master and release-v3.7 today? It already successfully built an package (the last commit updated comments) and is preventing one of our OS X build servers from functioning.

**Comment by peterfpeterson** [comment]
This is marked for v3.8. Should it be `cherry-pick`ed into v3.7?

**Comment by quantumsteve** [comment]
@peterfpeterson Yes.

**Comment by gvardany** [comment]
:shipit:

**Comment by martyngigg** [comment]
@gvardany I see you have marked this to be shipped but closed the PR. Did you mean to close this?

**Comment by gvardany** [comment]
No, sorry for misunderstanding, I meant :shipit:

**Comment by martyngigg** [comment]
No problem. Thanks for clarifying.

**Comment by martyngigg** [comment]
I've cherry-picked the changes to `release-v3.7`

**Pull request merged**
