### PR TITLE
Replace draw with draw_idle for some functions

### LINKED ISSUE #37046: Live data updates causing plots to freeze
We believe this to be the main cause of all the error reports comeing through: https://github.com/ISISNeutronMuon/mantid-isis-support/issues/184

**Describe the bug**
When the underlying workspace is replaced / updated while the plot is open, if the plot is being updated (resized, legend being moved, etc) it can cause a freeze.

**To Reproduce**
- Set facility to `TEST_LIVE`
- Run the `FakeISISHistoDAE` algorithm with default parameters
- Load live data
  - Set instrument to `ISIS_Histogram`
  - Set the update rate to be 5 seconds
  - Set the output workspace name
- Plot a spectra from the output workspace (if you get unlucky with the timing it will say invalid data, just try again)
- Drag the legend around the plot, when the next live update occurs the plot and workbench will freeze

**Expected behavior**
Should continue as normal

**Platform/Version (please complete the following information):**
 - OS: All
 - OS Version:
 - Mantid Version 6.9.0

### PR DESCRIPTION
**Pull request by sf1919**
### Description of work
Replacing canvas.draw() with canvas.draw_idle() to improve plotting performance.

#### Summary of work

In figuremanager.py replace canvas.draw with canvas.draw_idle() in the functions:-
- replaceHandle
- renameHandle
- deleteHandle

#### Purpose of work
This is the first step to trying to resolve the issues as outlined in #37030 . It is one of the suggestions that has been made by super users. Initial testing suggests it will definitely make a difference but more testing with users is needed before we can say the original issue is resolved.

The plan is to test this a bit more and then get it merged in to see if it reduces the crashes being reported through Error Reporter.

**Report to:** see issue #37030 for more details

_Notes from Jonathan/Core team_
We think this PR will solve a lot of the plotting problems but not those described in #37030 which is based around the quantity of data plotted, we've seen similar problems in older version.

I have written up #37046 to describe the issue this PR will fix

### To test:
See #37046

Fixes #37046

*This does not require release notes* because **it is anticiapted more will need to be done to resolve the original issue and a release note for overall improvements will be added then.**

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by jhaigh0** [comment]
package build https://builds.mantidproject.org/job/build_packages_from_branch/756/

**Review by GuiMacielPereira — COMMENTED** [review]
I just tested the substitutions by following the instructions in #37030 and I am not seeing any noticeable difference in behaviour. In both `draw()` and `draw_idle()` the plot hangs and asks if the user wants to force quit.

I am running it on Pop_OS (Ubuntu 22.04)

**Comment by GuiMacielPereira** [comment]
I noticed a regression with the plot curves not showing on the superplot, and opened a new issue #37039

**Comment by jhaigh0** [comment]
I have updated the PR text to explain how it fixes this issue https://github.com/mantidproject/mantid/issues/37046

**Review by thomashampson — CHANGES_REQUESTED** [review]
Please nobody merge this, we may put it into `release-next` for a patch release.

**Comment by thomashampson** [comment]
replaced by #37052

**Pull request closed without merging**
