### PR TITLE
Changes to move to Visual Studio 2019

### LINKED ISSUE #26217: Move to VS2019
1. Check that mantid will compile in VS2019
1. Create a simple instruction list for everyone else to follow
1. Organise a time for everyone to migrate

### PR DESCRIPTION
**Pull request by ghost**
**Description of work.**
Changes to C++ and CMake files to make Mantid Visual Studio 2019 compatible. This involved adding some includes and renaming `Process.h` to `Processes.h` to avoid conflicting with some Visual Studio header.

**To test:**
- Firstly, build this branch with Visual Studio 2017 and check everything works; everything builds and MantidPlot and Workbench start etc.
- Then follow the instructions given in the markdown file in the zip below to install Visual Studio 2019 and build Mantid. Check everything runs OK.

[vs2017_to_2019.zip](https://github.com/mantidproject/mantid/files/3427862/vs2017_to_2019.zip)

Refs #26217. 

*This does not require release notes* because **developer tool change**.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
@hsautessella Could you create an account at gravatar.com, I'd hate to have to fail the PR for that reason.

**Comment by hsautessella** [comment]
I'm not sure GitHub uses Gravatar any more, maybe I just couldn't get it working. I've changed my picture directly, anyway. It said it might take a few minutes to update

**Review by NickDraper — COMMENTED** [review]
All good so far, the instructions need to say that the reboot inbetween VS installation and using cmake is indeed essential

**Review by NickDraper — APPROVED** [review]
Builds all passed, everything looks good.

**Pull request merged**
