### PR TITLE
Add x error to binary operations

### LINKED ISSUE #13524: Add  X Errors to Binary Operations
In order to execute the SANS reduction chain we need to introduce DX to the Binary Operations. Currently the DX values are being ignored.

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Fixes #13524

**Context**

The binary operations did not respect x errors, but rather stripped them. For the SANS reduction with x errors we need to multiply and add a scalar value to the workspace (all in python).
In this ticket we extend the functionality for Multiply and Plus algorithms to handle X errors. 

Other binary algorithms (Multiply, Divide, PoissonErrors, WieghtedMean) will not respect x errors (in fact it is not clear how to handle them with these algorithms. If one of these algorithms is called with workspaces containing x errors, a warning is issued, but the data is processed in the old style.
# For testing

**Test**

Run the following script. Compare the outputs and make sure that only Plus and Mutliply respect DX values. For the other algorihtms check that a warning has been issued.

``` python
import math
# DATA FOR DX
dataX = [1,2,3,4,5,6]
dataY1 = [1.,1.,1.,1.,1.]
dataY2 = [2.,2.,2.,2.,2.]
dataE1 = [3.,3.,3.,3.,3.]
dataE2 = [4.,4.,4.,4.,4.]
ws_dx = CreateWorkspace(dataX, dataY1, dataE1, UnitX="MomentumTransfer")
ws_dx2 = CreateWorkspace(dataX, dataY2, dataE2, UnitX="MomentumTransfer")

# Set the DX values
dataDX1 = [5.,5.,5.,5.,5., 5.]
dx = ws_dx.dataDx(0)
for index in range(0, len(dataDX1)):
    dx[index] = dataDX1[index]

# Set the DX values
dataDX2 = [6.,6.,6.,6.,6., 6.]
dx2 = ws_dx2.dataDx(0)
for index in range(0, len(dataDX2)):
    dx2[index] = dataDX2[index]


# DATA FOR NO_DX
dataX_no_Dx = [1,2,3,4,5,6]
dataY1_no_Dx = [1.,1.,1.,1.,1.]
dataY2_no_Dx = [2.,2.,2.,2.,2.]
dataE1_no_Dx = [3.,3.,3.,3.,3.]
dataE2_no_Dx = [4.,4.,4.,4.,4.]
ws_no_Dx = CreateWorkspace(dataX_no_Dx, dataY1_no_Dx, dataE1_no_Dx, UnitX="MomentumTransfer")
ws_no_Dx2 = CreateWorkspace(dataX_no_Dx, dataY2_no_Dx, dataE2_no_Dx, UnitX="MomentumTransfer")


# PLUS
print "====== START  CHECKING PLUS FOR SINGLE SPECTRUM"
ws_new = Plus(ws_dx, ws_dx2)
ws_new_no_Dx = Plus(ws_no_Dx, ws_no_Dx2)
print "Output with Dx:"
print "Are there any DX values: " + str(ws_new.hasDx(0))
added_errors =  ws_new.dataDx(0)
print "Expecting %f for each entry" %(math.sqrt(5*5 + 6*6))
print "Entries are" + str(added_errors)
print
print "Output without Dx:"
print "Are there any DX values: " + str(ws_new_no_Dx.hasDx(0))
print 
print "Test DX scalar addition:"
a = 5
ws_new_scalar_add = ws_dx2+a
print "Added Workspace has DX values: " + str(ws_new_scalar_add.hasDx(0))
print "Expecting %f and have %f" % (ws_dx2.readDx(0)[0], ws_new_scalar_add.readDx(0)[0]) # A scalar value should not be added to DX
print "====== STOP  CHECKING PLUS FOR SINGLE SPECTRUM"
print


# Multiply
print "====== START  CHECKING MULTIPLY FOR SINGLE SPECTRUM"
ws_new = Multiply(ws_dx, ws_dx2)
ws_new_no_Dx = Multiply(ws_no_Dx, ws_no_Dx2)
print "Output with Dx:"
print "Are there any DX values: " + str(ws_new.hasDx(0))
added_errors =  ws_new.dataDx(0)
print "Expecting %f for each entry" %(math.sqrt(5*5 + 6*6))
print "Entries are" + str(added_errors)
print
print "Output without Dx:"
print "Are there any DX values: " + str(ws_new_no_Dx.hasDx(0))
print
print "Test DX scalar multiplication:"
a = 5
ws_new_scalar_add = ws_dx2*a
print "Added Workspace has DX values: " + str(ws_new_scalar_add.hasDx(0))
print "Expecting %f and have %f" % (ws_dx2.readDx(0)[0], ws_new_scalar_add.readDx(0)[0]) # A scalar value should not be multiplied to DX
print "====== STOP  CHECKING MULTIPLY FOR SINGLE SPECTRUM"
print

# Minus
print "====== START  CHECKING MINUS FOR SINGLE SPECTRUM"
ws_new = Minus(ws_dx, ws_dx2)
ws_new_no_Dx = Minus(ws_no_Dx, ws_no_Dx2)
print "Output with Dx:"
print "Are there any DX values: " + str(ws_new.hasDx(0))
print
print "Output without Dx:"
print "Are there any DX values: " + str(ws_new_no_Dx.hasDx(0))
print "====== STOP  CHECKING MINUS FOR SINGLE SPECTRUM"
print

# DIVIDE
print "====== START  CHECKING DIVIDE FOR SINGLE SPECTRUM"
ws_new = Divide(ws_dx, ws_dx2)
ws_new_no_Dx = Divide(ws_no_Dx, ws_no_Dx2)
print "Output with Dx:"
print "Are there any DX values: " + str(ws_new.hasDx(0))
print
print "Output without Dx:"
print "Are there any DX values: " + str(ws_new_no_Dx.hasDx(0))
print "====== STOP  CHECKING DIVIDE FOR SINGLE SPECTRUM"
print


# POISONERRORS
print "====== START  CHECKING POISSONERRORS FOR SINGLE SPECTRUM"
ws_new = PoissonErrors(ws_dx, ws_dx2)
ws_new_no_Dx = PoissonErrors(ws_no_Dx, ws_no_Dx2)
print "Output with Dx:"
print "Are there any DX values: " + str(ws_new.hasDx(0))
print
print "Output without Dx:"
print "Are there any DX values: " + str(ws_new_no_Dx.hasDx(0))
print "====== STOP  CHECKING POISSONERRORS FOR SINGLE SPECTRUM"
print

# WEIGHTEDMEAN
print "====== START  CHECKING WEIGHTEDMEAN FOR SINGLE SPECTRUM"
ws_new = WeightedMean(ws_dx, ws_dx2)
ws_new_no_Dx = WeightedMean(ws_no_Dx, ws_no_Dx2)
print "Output with Dx:"
print "Are there any DX values: " + str(ws_new.hasDx(0))
print
print "Output without Dx:"
print "Are there any DX values: " + str(ws_new_no_Dx.hasDx(0))
print "====== STOP  CHECKING WEIGHTEDMEAN FOR SINGLE SPECTRUM"
print
```

### CODE REVIEW

**Comment by martyngigg** [comment]
What is the expected behaviour if one workspace has X errors and the other does not?

**Comment by picatess** [comment]
Currently only the lhs is checked

**Comment by picatess** [comment]
Issue is moved to #13557

**Comment by martyngigg** [comment]
It's not entirely clear what should happen to the X errors in a large classes of cases that binary operations deal with, e.g. only one side has errors, both sides have different errors etc.

The use case simply requires the X errors to be propagated through when multiplying/adding by a scalar. The `Scale` algorithm is much more limited in its scope and shouldn't hit as many problems when wondering what to do with the X values so this behaviour will be applied there.

**Pull request closed without merging**
