### PR TITLE
Fix wrong graph axis being scaled on MacOS.

### PR DESCRIPTION
**Pull request by quantumsteve**
Description of work.

On MacOS [right-clicks don't change the focus of the window](https://superuser.com/questions/292895/mac-os-focus-on-right-click), letting one right-click on one plot and modify the axes of another. This PR follows suggestions from @martyngigg and @mantid-roman to override this behavior.

**To test:**

This is best tested on MacOS.
On Master:
1. Open or create a workspace where one can plot more than one spectra 
     i. I used `ExternalData/Testing/Data/UnitTest/IRS26173.RAW`
2. Right-click the workspace and use the "Plot Spectrum..." menu option to plot two spectra in separate windows.
3. Right click on the y-axis and click the option to scale axis.
4. Repeat step 3 with the other window and repeat until the axes change in the other (unclicked) window.

On this branch:
1. Repeat steps 1-3 above.
2. Repeat step 4 above, verifying that the modified axis matches the one clicked on.

This issue was reported by @mganeva. There is no GitHub issue associated with the pull request.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gvardany** [comment]
I was wondering if https://github.com/mantidproject/mantid/issues/20086 is related or can be easily fixed here?

**Comment by gvardany** [comment]
I wonder if this can be fixed in a more general way by setting the focus on right click anywhere on the window (not just the axis), it seems all the context menus are getting wrong.

**Comment by gvardany** [comment]
Can one test this branch  `20086_focus_right_click` ?

**Comment by quantumsteve** [comment]
@gvardany I agree that this is a more general issue, though I'm increasingly less comfortable with this workaround. Would @martyngigg's second suggestion of emitting a pointer to the layer better match the expectations of a MacOS user?

**Comment by quantumsteve** [comment]
I tried opening two finder windows and right-clicks works as expected, but the focus doesn't change.

**Comment by gvardany** [comment]
True, that the focus does not change, but the right click is attributed with the right finder window. This is similar to the multiple plot windows in the branch I've posted. I agree though that this is a workaround, if you have a better solution please go ahead.

**Comment by quantumsteve** [comment]
Closing this since we haven't settled on a solution. Ideally we'd avoid such platform-specific interaction patterns in the new workbench.

**Pull request closed without merging**
