### PR TITLE
Increase number of neighbors in detector search

### PR DESCRIPTION
**Pull request by zjmorgan**
**Description of work.**

The algorithm `PredictPeaks` was missing some obvious peaks in CORELLI data. It was discovered by expanding the search space of the number of nearest neighbors from 11 to 21 in `DetectorSearcher.cpp`, the missing peaks are picked up. This changes is similar to https://github.com/mantidproject/mantid/commit/bd12976bba4647275a544531cdecd1bb1efae486 which helped the HB2C instrument with a similar problem of missing predicted peaks.

**To test:**

Run the new system test `PredictPeaksTestCORELLI`. Before the change, the test would fail. In the latest version, the test passes.

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by jmborr — COMMENTED** [review]
since 5 or 11 looks to me somewhat arbitrary, wouldn't be better to introduce a new parameter (with default to 11) so that User can change this number if so pleases?

**Comment by zjmorgan** [comment]
> since 5 or 11 looks to me somewhat arbitrary, wouldn't be better to introduce a new parameter (with default to 11) so that User can change this number if so pleases?

My thought that this parameter is a bit too nuanced to be exposed as an additional variable to the user. Ideally, no peak should be missed if it obviously lies on a detector. To me, this parameter is more of a fudge factor related to an imperfect algorithm especially when you have tube-like detectors.

**Comment by jmborr** [comment]
> > since 5 or 11 looks to me somewhat arbitrary, wouldn't be better to introduce a new parameter (with default to 11) so that User can change this number if so pleases?
> 
> My thought that this parameter is a bit too nuanced to be exposed as an additional variable to the user. Ideally, no peak should be missed if it obviously lies on a detector. To me, this parameter is more of a fudge factor related to an imperfect algorithm especially when you have tube-like detectors.

I am not familiar with the algorithm but I want to make sure we won't need to re-edit this source file in the future because of the same Nneighbor reason. I guess my question is: will `Nneighbor=11` cover all the scenarios that were previously covered with old value `Nneighbor=5`? If so, then I'm happy with this change. Otherwise we need a parameter.

**Comment by zjmorgan** [comment]
> > > since 5 or 11 looks to me somewhat arbitrary, wouldn't be better to introduce a new parameter (with default to 11) so that User can change this number if so pleases?
> > 
> > 
> > My thought that this parameter is a bit too nuanced to be exposed as an additional variable to the user. Ideally, no peak should be missed if it obviously lies on a detector. To me, this parameter is more of a fudge factor related to an imperfect algorithm especially when you have tube-like detectors.
> 
> I am not familiar with the algorithm but I want to make sure we won't need to re-edit this source file in the future because of the same Nneighbor trouble. I guess my question is: will `Nneighbor=11` cover all the scenarios that were previously covered with old value `Nneighbor=5`? If so, then I'm happy with this change. Otherwise we need a parameter.

Think of it this way. With more nearest-neighbors, we predict more peaks. We should get the same ones as before but with ones that couldn't be placed on a detector.

The case where this observed was during an experiment. The exact same measurements were repeated at different temperatures. It was expected that the same number of peaks should be predicted to lie on the detectors for both sets of measurements. Due to not having a sufficiently high enough nearest neighbors, the two sets had slightly different number of peaks that were to be integrated. Since some were missing, it was very difficult to understand if certain special reflections at the two temperatures had undergone a significant change in intensity indicating a change in the sample.

**Comment by zjmorgan** [comment]
Why 5? For pixelated rectangular detectors, I imagine is the closest pixel to the Q plus one up/down/left/right for a total of 5. The situation is more complicated for tube detectors which have a gap between tubes. This issue seems to only occur with these types of instruments and requires searching outside of the gap.

**Comment by jmborr** [comment]
> Why 5? For pixelated rectangular detectors, I imagine is the closest pixel to the Q plus one up/down/left/right for a total of 5. The situation is more complicated for tube detectors which have a gap between tubes. This issue seems to only occur with these types of instruments and requires searching outside of the gap.

From your answers I understand that increasing the number of neighbors will cover box rectangular and tube detectors scenarios. Am I right here?

Also, I guess the algorithm will take longer to complete now. Did you notice a significant increase in execution time?

**Comment by zjmorgan** [comment]
Here is a timing test on an older machine used for development. Note I do 10 repetitions.

```python
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
from mantid.geometry import CrystalStructure
import numpy as np

import time

# Generate a workspace with an instrument definition
ws = CreateSimulationWorkspace(Instrument='WISH',
                               BinParams='0,10000,20000',
                               UnitX='TOF')

# Set a random UB, in this case for an orthorhombic structure
SetUB(ws, a=5.5, b=6.5, c=8.1, u='12,1,1', v='0,4,9')

# Set an arbitrary crystal structure with 2 atoms and some
# systematic absences due to space group Pbca
cs = CrystalStructure('5.5 6.5 8.1', 'P b c a',
                      """Ni 0.232 0.114 0.543 1.0 0.00843;
                         Al 0.434 0.041 0.854 1.0 0.01120""")
ws.sample().setCrystalStructure(cs)

start = time.time()

for i in range(10):

    predicted = PredictPeaks(InputWorkspace=ws,
                             CalculateStructureFactors=True,
                             MinDSpacing=0.5,
                             WavelengthMin=0.9, WavelengthMax=6.0)

stop = time.time()

print(stop-start)
```

Summary:
11 nearest-neighbors: 61.40 seconds
21 nearest-neighbors: 73.53 seconds

That's 83%.

**Comment by zjmorgan** [comment]
Second test:

11 = 62.38 seconds
21 = 71.86 seconds

That's 87% as fast

**Comment by RichardWaiteSTFC** [comment]
This looks good to me - tested on WISH and indeed it does predict more peaks (as found in the systems test as well). WISH  integrate the predicted peaks so it's very important to get as many as possible than for it to be quick (within limits!) -  and it doesn't actually seem to slow it down much.
I'm assuming increasing the neighbour search above 21 predicted no more peaks on the CORELLI data set? Would it be possible to check this using the WISH systems test example as well? If 21 is optimal for that example I'd be happy to keep it hard-coded and approve (as long as you're happy @jmborr?)

**Comment by zjmorgan** [comment]
> This looks good to me - tested on WISH and indeed it does predict more peaks (as found in the systems test as well). WISH integrate the predicted peaks so it's very important to get as many as possible than for it to be quick (within limits!) - and it doesn't actually seem to slow it down much. I'm assuming increasing the neighbour search above 21 predicted no more peaks on the CORELLI data set? Would it be possible to check this using the WISH systems test example as well? If 21 is optimal for that example I'd be happy to keep it hard-coded and approve (as long as you're happy @jmborr?)

I added a new system test for CORELLI. With 11, the one peak will not be predicted with 21. It will show up.

**Comment by jmborr** [comment]
> Second test:
> 
> 11 = 62.38 seconds 21 = 71.86 seconds
> 
> That's 87% as fast

I think this modest speed penalty is a bargain if you get your precious peaks 😃

**Comment by jmborr** [comment]
> > This looks good to me - tested on WISH and indeed it does predict more peaks (as found in the systems test as well). WISH integrate the predicted peaks so it's very important to get as many as possible than for it to be quick (within limits!) - and it doesn't actually seem to slow it down much. I'm assuming increasing the neighbour search above 21 predicted no more peaks on the CORELLI data set? Would it be possible to check this using the WISH systems test example as well? If 21 is optimal for that example I'd be happy to keep it hard-coded and approve (as long as you're happy @jmborr?)
> 
> I added a new system test for CORELLI. With 11, the one peak will not be predicted with 21. It will show up.

👍

**Review by jmborr — APPROVED** [review]

**Pull request merged**
