### PR TITLE
Boost 1.82 and numpy.distutils

### PR DESCRIPTION
**Pull request by peterfpeterson**
This pulls in the following changes from `main`
* 2024-04-30 #37205
* 2024-06-13 #37357
* 2024-06-17 #37498
* 2024-07-04 #37631
* 2024-07-22 #37664
* 2024-07-25 #37259
* 2024-07-25 #37682
* #37440
* current state of `.github/workflows` and mantid-developer environments
* This contains a merge of #37701
* random things from `main` to get the builds to pass

### CODE REVIEW

**Comment by sf1919** [comment]
It might also be worth looking at bringing in #37664 and #37682 ?

**Comment by sf1919** [comment]
Some more suggestions to add as perhaps its one of the dependency updates thats done it
- #37610 
- #37573 
- #37540 
- #37440

**Comment by peterfpeterson** [comment]
@robertapplin suggested
* #37653
* #37655

**Comment by peterfpeterson** [comment]
This was done instead by #37717

**Pull request closed without merging**
