### PR TITLE
updated eng diff testing instructions

### LINKED ISSUE #37269: Update testing docs for EngDiff UI
**Describe the outcome that is desired.**
Testing instructions for Sequential fitting in the Engineering Diffraction interface [Test 9](https://developer.mantidproject.org/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.html#test-9) need to have a few minor updates as listed below.

1. Test step 6 need to be updated with the name of the GroupWorkspace as the suffix `_logs_Fitting`
2. Test step 8 need to beupdated as `compared to step 6`

### PR DESCRIPTION
**Pull request by warunawickramasingha**
### Description of work
Did below updates to the testing instructions for Sequential fitting in the Engineering Diffraction interface [Test 9](https://developer.mantidproject.org/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.html#test-9) 

1. Test step 6 need to be updated with the name of the GroupWorkspace as the suffix `_logs_Fitting`
2. Test step 8 need to beupdated as compared to step `6`
#### Summary of work

Fixes #37269. 

### To test:
Code review and check builds pass

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by sf1919 — COMMENTED** [review]
The documentation itself loads without warnings and looks correctly formatted when opened as a html page. However I've noticed that Tests 4 and 9 start with step 0 rather than step 1 is that deliberate?

**Comment by sf1919** [comment]
I thought it would be useful to run through the testing documentation to check that the added bits made sense in the context of testing. I undertook Test 4 first as this is needed to be done in advance of Test 9 (where the changes are). Unfortunately I am stuck on step 2 as I don't seem to have `runs_info`. These are all the workspaces I have

Screenshot (371)
Screenshot (372)

**Comment by RichardWaiteSTFC** [comment]
> I thought it would be useful to run through the testing documentation to check that the added bits made sense in the context of testing. I undertook Test 4 first as this is needed to be done in advance of Test 9 (where the changes are). Unfortunately I am stuck on step 2 as I don't seem to have `runs_info`. These are all the workspaces I have

The workspace is there but named differently: it's called `run_info_Fitting`.
There's a few minor changes required to test 4 - I'll submit a review shortly

**Review by RichardWaiteSTFC — CHANGES_REQUESTED** [review]
Changes to test 9 look good - just some additional changes to test 4 as pointed out by @sf1919  (which are probably my fault!)

Could you clarify that the name of the log table workspaces have the suffix `_Fitting` here
https://github.com/mantidproject/mantid/blob/8c9f713d8bb3c502d83111fdbd6318751ff9644a/dev-docs/source/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.rst?plain=1#L152

Could `run_info` be changed to `run_info_Fitting` here

https://github.com/mantidproject/mantid/blob/8c9f713d8bb3c502d83111fdbd6318751ff9644a/dev-docs/source/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.rst?plain=1#L153

And in terms of formatting I think workspace names need double `` to make them standout - thanks!

**Comment by warunawickramasingha** [comment]
> `run_info_Fitting`

Thanks Sarah and Richard, I will add those updates. 

In addition, regarding the steps numbering for Test 4 - should they start from step 0 rather than step 1?

**Review by RichardWaiteSTFC — APPROVED** [review]
Thanks for this!

**Pull request merged**
