### PR TITLE
Support building with Homebrew HEAD

### LINKED ISSUE #28423: Missing Pip in MacOS bundle
Related to this [forum post](https://forum.mantidproject.org/t/lmfit-installation/658)

### Expected behavior
pip installer bundled with mantid packages on MacOS
### Actual behavior
Not for last few versions
### Steps to reproduce the behavior
Run `/Applications/MantidWorkbench.app/Contents/Frameworks/Python.framework/Versions/2.7/bin/python -m pip installer lmfit --user`
### Platforms affected
Mac, checked on Mantid 5.0, 4.2

**Is it possible for there to be a test that checks this is included??**

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Adds various fixes to support building against the HEAD versions of Homebrew packages. The biggest change is with Poco 1.10 as their api has changed in a couple of key classes and brew now has Python 3.8. OpenMP is now supported too.

**To test:**

* The installation instructions from a clean machine have been updated in dev-docs
* For existing installations a few [additional steps](https://gist.github.com/martyngigg/517648235f9b7eeb13921ef241be7364) are required to prepare for the brew upgrade.
* Build as normal and check MantidPlot/Workbench works.

Fixes #28423 

*This does not require release notes* because **the builders have not been updated yet so the changes are not visible.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gvardany** [comment]
I could run cmake on build server, and start the build. Unfortunately VPN kicks me out, so I cannot see it through the end, but if build starts that's already fine. Open was found as well. Could you just make an issue to remove the `legacy` bits once the build servers are updated?

**Comment by gvardany** [comment]
Actually following further, I still get the same problem of not being able to `brew link` `qtscintilla2` and `qtscintilla2qt4` at the same time. So I cannot run cmake with MantidPlot and Workbench both enabled:

```
Undefined symbols for architecture x86_64:
  "QsciScintilla::wheelEvent(QWheelEvent*)", referenced from:
      ScriptEditor::wheelEvent(QWheelEvent*) in ScriptEditor.cpp.o
  "QsciScintilla::findFirstInSelection(QString const&, bool, bool, bool, bool, bool, bool, bool)", referenced from:
      vtable for ScriptEditor in moc_ScriptEditor.cxx.o
  "QsciScintilla::setCaretLineFrameWidth(int)", referenced from:
      vtable for ScriptEditor in moc_ScriptEditor.cxx.o
  "QsciScintilla::findFirst(QString const&, bool, bool, bool, bool, bool, int, int, bool, bool, bool)", referenced from:
      vtable for ScriptEditor in moc_ScriptEditor.cxx.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[1561/3522] Building CXX object qt/widgets/mplcpp/CMakeFiles/MantidQtWidgetsMplCppQt5.dir/src/Plot.cpp.o
/Users/builder/mantid/qt/widgets/mplcpp/src/Plot.cpp:97:10: warning: local variable 'kwargs' will be copied despite being returned by name [-Wreturn-std-move]
  return kwargs;
         ^~~~~~
/Users/builder/mantid/qt/widgets/mplcpp/src/Plot.cpp:97:10: note: call 'std::move' explicitly to avoid copying
  return kwargs;
         ^~~~~~
         std::move(kwargs)
1 warning generated.
```

**Comment by martyngigg** [comment]
@gvardany Thanks for checking this. I'll have a look at my mac and see what I've done there. Just for completeness what version of macOS do you see this on?

**Comment by gvardany** [comment]
It's 10.13.

**Comment by gvardany** [comment]
This is what happens when doing`brew link qscintilla2`:

```
Linking /usr/local/Cellar/qscintilla2/2.11.4_1... 
ln -s ../Cellar/qscintilla2/2.11.4_1/include/Qsci Qsci
ln -s ../../Cellar/qscintilla2/2.11.4_1/share/sip/Qsci Qsci
ln -s ../Cellar/qscintilla2/2.11.4_1/lib/libqscintilla2_qt5.15.0.0.dylib libqscintilla2_qt5.15.0.0.dylib
ln -s ../Cellar/qscintilla2/2.11.4_1/lib/libqscintilla2_qt5.15.0.dylib libqscintilla2_qt5.15.0.dylib
ln -s ../Cellar/qscintilla2/2.11.4_1/lib/libqscintilla2_qt5.15.dylib libqscintilla2_qt5.15.dylib
ln -s ../Cellar/qscintilla2/2.11.4_1/lib/libqscintilla2_qt5.dylib libqscintilla2_qt5.dylib
ln -s ../../../../Cellar/qscintilla2/2.11.4_1/lib/python3.8/site-packages/PyQt5/Qsci.pyi Qsci.pyi
ln -s ../../../../Cellar/qscintilla2/2.11.4_1/lib/python3.8/site-packages/PyQt5/Qsci.so Qsci.so
```
So we can add the symlink for the dylib of `qscintilla2qt4` by hand, but I'm not sure what to do with Qsci.so and Qsci.pyi since they have no versions attached.

**Comment by martyngigg** [comment]
@gvardany Thanks for spotting this. It looks like we have already added support for a keg-only version of qscintilla2qt4 as I assume we must of had this problem originally and I hadn't noticed the formula hadn't been updated.
I've updated the formula in `homebrew-mantid` so can you do `brew update && brew reinstall qscintilla2qt4`. The formula should stop trying to symlink itself now.

**Comment by martyngigg** [comment]
I think `qscintill2a` can be symlinked as normal.

**Comment by gvardany** [comment]
@martyngigg I think that was not the problem and it was keg-only already. But that's exactly the issue; cmake finds it, but it still fails to link `[2619/4672] Linking CXX shared library bin/libMantidQtWidgetsCommonQt4.dylib
FAILED: bin/libMantidQtWidgetsCommonQt4.dylib `. Shall we add the link and include directories in cmake directives?

**Comment by gvardany** [comment]
```
qscintilla2qt4 is keg-only, which means it was not symlinked into /usr/local,
because it conflicts with qscintilla2.

For compilers to find qscintilla2qt4 you may need to set:
  export LDFLAGS="-L/usr/local/opt/qscintilla2qt4/lib"
  export CPPFLAGS="-I/usr/local/opt/qscintilla2qt4/include"

==> Summary
🍺  /usr/local/Cellar/qscintilla2qt4/2.10.4: 80 files, 5MB, built in 46 secon
```

**Review by gvardany — COMMENTED** [review]
The issue with the qscintilla2qt4 still persists on my setup, but it's fine on Martyn's. So I am happy to approve this, we can investigate and fix that in another PR.

**Review by gvardany — APPROVED** [review]

**Pull request merged**
