### PR TITLE
Correctly format FullProf output in SaveReflections

### LINKED ISSUE #31004: SaveReflections incorrectly formatting FullProff files
### Expected behavior
There are several issues with SaveReflections not formatting FullProf output that can be addressed together

- When modulation vectors are present then they need to be in the header - two rows per q (i.e. one each for +/-q) preceded by an index number starting from 1. There is then instead of having a column per q (as in Jana) there is just one column and it references the q index.
- Need title row as first row  - can just say title
- For parent structures (no modulations) there is a cod column - this needs to be populated with 1s

### Steps to reproduce the behavior
Will upload relevant example files

### PR DESCRIPTION
**Pull request by RichardWaiteSTFC**
**Description of work.**
There were several issues with SaveReflections not formatting FullProf output that have been addressed
- Add a title line on first line
- Set multiplicity of reflection (Cod) to be one by default - fixed bug where went from [1..npeaks]
- When modulation vectors are present then they need to be in the header - two rows per q (i.e. one each for +/-q) preceded by an index number starting from 1. There is then instead of having a column per q (as in Jana) there is just one column and it references the q index.
- If it looks like constant wavelength then put wavelength in heading (default is 0 which is ignored for TOF Laue)

In addition I have fixed the bug which led to incorrect HKL determined for parent peak of satellites: previously the HKL of the parent was determined casting to int but this fails for modulations with components >=0.5 (note that for non-primitive cells the modulation can be >0.5). It was this change that necessitated changing the Jana test files as well as FullPRof (now exported peaks have same HKL in both formats!).

**To test:**

(1) Run this script
```
LoadNexusProcessed(Filename='TOPAZ_3007.peaks.nxs', OutputWorkspace='peaks')
LoadIsawUB(InputWorkspace='peaks', Filename='TOPAZ_3007.mat')
IndexPeaks(PeaksWorkspace='peaks')
SaveReflections('peaks', Filename='test_fullprof.hkl', Format='FullProf') # parent
PredictFractionalPeaks(Peaks='peaks', RequirePeaksOnDetector=False, ModVector1='0.2,0,0', MaxOrder=1, FracPeaks='frac')
SaveReflections('frac', Filename='test_fullprof_mod.hkl', Format='FullProf') # modulated
```
(2) Check that the output looks as it should (see description)
(3) Change the modulation to be 0.5 and re-run
```
PredictFractionalPeaks(Peaks='peaks', RequirePeaksOnDetector=False, ModVector1='0.5,0,0', MaxOrder=1, FracPeaks='frac_com')
SaveReflections('frac_com', Filename='test_fullprof_mod_commensurate.hkl', Format='FullProf') # modulated commensurate
```
The parent Bragg peak HKL should be the same as before

Fixes #31004 and #31005

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by zjmorgan** [comment]
Based on the FullProf 
[manual](https://github.com/mantidproject/mantid/files/6238624/fullprof_int_format.pdf), the third line should be `f_handle.write("  {} 0 0\n".format(wl))` where `wl` is the wavelength. I think the column header line may not also be needed along with the last column of wavelength. 

This looks like to me that this format from the manual is for a monochromatic beam. Do you know if there is a reference for time-of-flight data?

**Comment by RichardWaiteSTFC** [comment]
> Based on the FullProf
> [manual](https://github.com/mantidproject/mantid/files/6238624/fullprof_int_format.pdf), the third line should be `f_handle.write(" {} 0 0\n".format(wl))` where `wl` is the wavelength. I think the column header line may not also be needed along with the last column of wavelength.
> 
> This looks like to me that this format from the manual is for a monochromatic beam. Do you know if there is a reference for time-of-flight data?

So on p138 of the manual (I put a link in the original issue as well) the first number is indeed wavelength (R_lambda) although I believe this is ignored for whitebeam TOF (from an example WISH file that I have). Note, this is not one of the lines I have changed in this PR as this is currently working for WISH. My understanding is that monochromatic instruments such as WAND do add in the wavelength on this line after the file has been written, which I accept is not ideal. I was considering accessing the wavelengths in the peak table to check if the instrument is monochromatic (I don't know if you are aware of another way to check?) and write it in automatically but I wasn't sure the wavelength was stored in the peak tables for monochromatic instruments (I have less experience with these instruments in mantid). In addition some of this stuff might be subject to change with the introduction of this new LeanPeak class - can you advise on this @zjmorgan?
With regards to documentation for whitebeam TOF Laue, the documentation is a bit patchy. As you point out WISH currently write out a column of wavelengths that in the documentation should correspond to c1 which links to a section which labels C1-C9 as "Coefficients of the linear combinations of basis functions.". That said, as the wavelength of each peak is needed for extinction and absorption corrections, I assume the program needs one of the wavelength or two-theta to be provided - so I assumed again as this works for WISH it was another undocumented feature (like the fact that the R_lambda will be ignored). Later on p139 it says for Irf=4 the columns c1-c3 are read but not used and correspond to coefficients for extinction correction despite only supporting 1 extinction coefficient as in SHELX - and we don't even have columns fro c2-c3!
Overall I would say the documentation for whitebeam TOF Laue (correspond to `n_pat = -1` on p69) is not that consistent! So I was relying on the example files I had access to. Hope that helps.

**Comment by zjmorgan** [comment]
The changes look good and seems to do exactly what we need for both TOF and CW. Testing with real data gives good results for CW instrument WAND2 and the wavelength check does correctly get set at the header.

**Review by peterfpeterson — APPROVED** [review]
Approving on behalf of Zach who doesn't have permissions

**Pull request merged**
