### PR TITLE
Load grouping from IDF if not present in file

### LINKED ISSUE #14085: Auto grouping in the ALC interface
From James:

>I'm trying to analyse some recent CHRONUS data in the Muon ALC Analysis interface.

>I've set the default instrument to CHRONUS (just in case), browsed to the correct files for the start and end, selected a log value, etc. I put Grouping=Auto. But when I click "Load" I get an error "Couldn't load detector grouping".

>However loading the same runs into the Muon Analysis interface, it picks up the default grouping table automatically.

>Using "Custom" grouping in the ALC interface does work but I had to copy/paste the lists out of the Muon Analysis Grouping tab (typing in 600 numbers wasn't an option!)

### PR DESCRIPTION
**Pull request by tom-perkins**
`LoadMuonNexus` should load grouping from IDF if there is no entry in the NeXus file.

The property _DetectorGroupingTable_ in `LoadMuonNexus-v1` is an output property that returns
a grouping table. If there is no grouping information in the NeXus file but this property is specified,
first try loading grouping from the IDF. If that fails, use a dummy grouping. (In either of these cases,
a log message specifies what has been done).

Also deal with files in which there is a grouping entry, but it is all zeros or otherwise invalid.

Use case: this enables such files to be used in ALC (and elsewhere) in the same way as MuonAnalysis (which already handles bad grouping in this way).

Added a note to the algorithm documentation, and two unit tests for missing and zero grouping.

**To test:**

Files: can be found at `\\olympic\babylon5\Scratch\TomPerkins\Data\grouping`.
`EMU00019489.nxs` has a grouping entry, but it's all zero.
`CHRONUS0003422.nxs` has no grouping entry at all.
(You can see this using HDFView, under `run/histogram_data_1/grouping`).
- Run `LoadMuonNexus` on these files, specifying a name for _DetectorGroupingTable_.
  - A TableWorkspace should be produced with the supplied name. It should have the detector grouping in it.
- Check that the new unit tests cover these two cases.

Fixes #14085.

[Release notes](https://github.com/mantidproject/mantid/blob/14085_missing_grouping/docs/source/release/v3.7.0/muon.rst#algorithms) have been updated.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
Release note needs to be qualified to indicate that it only applies to version 1.

**Comment by tom-perkins** [comment]
Updated release notes to make version clear

**Comment by KarlPalmen** [comment]
I notice via HDFView that the grouping at the location described is all 0s. I take that to mean there is just one group.

**Comment by KarlPalmen** [comment]
Is there not yet a file with a grouping other than 0s. Did you not obtain one when working on this issue?

**Comment by KarlPalmen** [comment]
Tests as described ran as expected and a message indicating group loaded from IDF was shown as expected. :shipit:

**Pull request merged**
