### PR TITLE
Indirect - Data Analysis Interfaces - Separate Mini-plot for Difference

### LINKED ISSUE #20241: Indirect - Plot Preview - Separate Plot for Diff in Interfaces
Currently, in the Indirect interfaces, Diff is plotted in the same plot diagram as Sample and Fit. A separate plot, below the existing one, should be added, in which Diff should be plotted.

### PR DESCRIPTION
**Pull request by brandonhewer**
Currently, the sample, fit and difference are all plotted in the same mini-plot. The difference should be plotted in a separate mini-plot below the existing one.

**To test:**
1. Navigate to Interfaces > Indirect > Data Analysis.
2. Follow the instructions outlined for the mentioned tabs:
    - **ConvFit**:
        1. Provide the supplied Sample (\*\_red) file with run number 26173 into the 'Sample' field.
        2. Provide the supplied Resolution (\*\_res) file into the 'Resolution' field.
        3. Navigate through each spectrum by changing the 'Plot Spectrum' spinner.
        4. For each spectrum, ensure the Sample is plotted in the top mini-plot and the bottom mini-plot is empty.
        5. Select 'One Lorentzian' in the 'Fit Type' drop-down menu.
        6. Click 'Run'.
        7. Navigate through each spectrum by changing the 'Plot Spectrum' spinner.
        8. For each spectrum, ensure the Sample and Fit are plotted in the top mini-plot and their difference is plotted in the bottom mini-plot.
        9. Provide the supplied Sample (\*\_red) file with run number 26176 into the 'Sample' field.
        10. Navigate through each spectrum by changing the 'Plot Spectrum' spinner.
        11. For each spectrum, ensure the Sample is plotted in the top mini-plot and the bottom mini-plot is empty.
    - **IqtFit**:
        1. Provide the supplied Iqt (\*\_iqt) file with run number 26176 into the 'Input' field.
        2. Navigate through each spectrum by changing the 'Plot Spectrum' spinner.
        3. For each spectrum, ensure the input is plotted in the top mini-plot and the bottom mini-plot is empty.
        4. Click 'Run'.
        5. Navigate through each spectrum by changing the 'Plot Spectrum' spinner.
        6. For each spectrum, ensure the input and fit are plotted in the top mini-plot and their difference is plotted in the bottom mini-plot.
        7. Provide the supplied Iqt (\*\_iqt) file with run number 26173 into the 'Input' field.
        8. Navigate through each spectrum by changing the 'Plot Spectrum' spinner.
        9. For each spectrum, ensure the Sample is plotted in the top mini-plot and the bottom mini-plot is empty.
    - **MSDFit**:
        1. Select any model in the 'Model' drop-down menu.
        2. Provide the supplied Sample (\*\_red) file with run number 26173 into the 'Input' field.
        3. Navigate through each spectrum by changing the 'Plot Spectrum' spinner.
        4. For each spectrum, ensure the input is plotted in the top mini-plot and the bottom mini-plot is empty.
        5. Change the selected range with the blue dotted range selectors in the mini-plot (such that a non-zero range is selected).
        6. Click 'Run'.
        7. Navigate through each spectrum by changing the 'Plot Spectrum' spinner.
        8. For each spectrum, ensure the input and fit are plotted in the top mini-plot and their difference is plotted in the bottom mini-plot.
        9. Provide the supplied Sample (\*\_red) file with run number 26176 into the 'Input' field.
        10. Navigate through each spectrum by changing the 'Plot Spectrum' spinner.
        11. For each spectrum, ensure the input is plotted in the top mini-plot and the bottom mini-plot is empty.
    - **JumpFit**:
        1. Provide the supplied Result (\*\_Result) file with run number 26173 into the 'Sample' field.
        2. Ensure the sample is plotted in the top mini-plot and the bottom mini-plot is empty.
        3. Click 'Run'.
        4. Ensure the fit and sample are plotted in the top mini-plot and the bottom mini-plot is empty.
        5. Provide the supplied Result (\*\_Result) file with run number 26176 into the 'Sample' field.
        6. Ensure the sample is plotted in the top mini-plot and the bottom mini-plot is empty.

## Test Files
**ConvFit**
[convfit-testfiles.zip](https://github.com/mantidproject/mantid/files/1390757/convfit-testfiles.zip)

**IqtFit**
[iqtfit-testfiles.zip](https://github.com/mantidproject/mantid/files/1390761/iqtfit-testfiles.zip)

**MSDFit**
[msdfit-testfiles.zip](https://github.com/mantidproject/mantid/files/1390763/msdfit-testfiles.zip)

**JumpFit**
[jumpfit-testfiles.zip](https://github.com/mantidproject/mantid/files/1390769/jumpfit-testfiles.zip)

Fixes #20241. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
I'm getting a crash with `ConvFit` when I follow your testing procedures. My stack trace suggests it's somewhere in the vicinity of `IDA::ConvFit::addDefaultParametersToTree(QString const&)`

**Comment by brandonhewer** [comment]
@martyngigg Thanks for noticing this, the addDefaultParametersToTree was on the wrong line.

**Comment by martyngigg** [comment]
That fixed the crash, thanks.

**Comment by martyngigg** [comment]
I'm seeing a crash in `IqtFit` now I'm afraid. To reproduce:

1. Provide the supplied Iqt (\*\_iqt) file with run number 26176 into the 'Input' field.
2. Navigate through each spectrum by changing the 'Plot Spectrum' spinner.
3. For each spectrum, ensure the input is plotted in the top mini-plot and the bottom mini-plot is empty.
4. Click 'Run'.
5. Navigate through each spectrum by changing the 'Plot Spectrum' spinner and leave it on `13` (or a number higher than the number of spectra in the 26173` file
6. Provide the supplied Iqt (\*\_iqt) file with run number 26173 into the 'Input' field.
 7. :boom:

I see this assert failure in my console log too:

`ASSERT failure in QList<T>::operator[]: "index out of range", file /usr/include/qt4/QtCore/qlist.h, line 477`

**Comment by brandonhewer** [comment]
@martyngigg The latest commit should fix the crash in IqtFit.

**Review by martyngigg — APPROVED** [review]
I've run through the rest of the testing instructions and everything seems fine now.

**Comment by ianbush** [comment]
Release notes?

**Comment by brandonhewer** [comment]
@ianbush Changes have now been added to the release notes

**Comment by ianbush** [comment]
Thanks @brandonhewer, it now has some merge conflicts for the release notes though.

**Comment by brandonhewer** [comment]
@ianbush Thanks for the notice, I've fixed the merge conflicts

**Pull request merged**
