### PR TITLE
Add OutputSuffix to ISISIndirectEnergyTransfer

### PR DESCRIPTION
**Pull request by MohamedAlmaki**
### Description of work
This pull request introduces a new option to the ISISIndirectEnergyTransfer algorithm that appends each output workspace name with a suffix. This new feature addresses the issue of having the same output name when running the algorithm with different configurations. 

#### Purpose of work
Sam Jones reported this issue in one of his autoreduction scripts. The bug occurred because he was running the algorithm with two different grouping options, and the second run would always override the previous one as they both had the same output name.

*There is no associated issue.*

**Report to:** @Pasarus 

### To test:
1- Run the following script:
```
ISISIndirectEnergyTransfer(InputFiles='IRS21360.raw',
                           OutputWorkspace='IndirectReductions',
                           Instrument='IRIS',
                           Analyser='graphite',
                           Reflection='002',
                           SpectraRange=[3, 53],
                           OutputSuffix="test"
)
```
2- Check the output workspace and it should end with the specified suffix

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by robertapplin** [comment]
When I run the script I get the following error

```
Error in execution of algorithm ISISIndirectEnergyTransfer:
Problem setting "InputWorkspaces" in GroupWorkspaces-v1: When converting parameter "InputWorkspaces": When setting value of property "InputWorkspaces": The workspace "IRS21360test" is not in the workspace list.

  at line 321 in 'C:/Users/mlc47243/Documents/mantid-dev/mantid-review/mantid/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ISISIndirectEnergyTransfer.py'
  caused by line 1081 in 'c:\users\mlc47243\documents\mantid-dev\mantid-review\mantid\framework\pythoninterface\mantid\simpleapi.py'
  caused by line 970 in 'c:\users\mlc47243\documents\mantid-dev\mantid-review\mantid\framework\pythoninterface\mantid\simpleapi.py'
  caused by line 953 in 'c:\users\mlc47243\documents\mantid-dev\mantid-review\mantid\framework\pythoninterface\mantid\simpleapi.py'
RuntimeError: ISISIndirectEnergyTransfer-v1: Problem setting "InputWorkspaces" in GroupWorkspaces-v1: When converting parameter "InputWorkspaces": When setting value of property "InputWorkspaces": The workspace "IRS21360test" is not in the workspace list.

  at line 321 in 'C:/Users/mlc47243/Documents/mantid-dev/mantid-review/mantid/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ISISIndirectEnergyTransfer.py'
  caused by line 1081 in 'c:\users\mlc47243\documents\mantid-dev\mantid-review\mantid\framework\pythoninterface\mantid\simpleapi.py'
  caused by line 970 in 'c:\users\mlc47243\documents\mantid-dev\mantid-review\mantid\framework\pythoninterface\mantid\simpleapi.py'
  caused by line 953 in 'c:\users\mlc47243\documents\mantid-dev\mantid-review\mantid\framework\pythoninterface\mantid\simpleapi.py'
  File "<string>", line 6, in <module>
  File "c:\users\mlc47243\documents\mantid-dev\mantid-review\mantid\framework\pythoninterface\mantid\simpleapi.py", line 1090, in __call__
    raise RuntimeError(msg) from e
```

**Comment by MohamedAlmaki** [comment]
I have fixed the name convention and added a release note. For the unit tests, there are no unit tests written for the algorithm and only one system test. Do you think we need to add a system test?

**Comment by robertapplin** [comment]
> I have fixed the name convention and added a release note. For the unit tests, there are no unit tests written for the algorithm and only one system test. Do you think we need to add a system test?

Yes please, I think this would be very useful! It might be something to add in one of these files

https://github.com/mantidproject/mantid/blob/3bdaa5f88bc2150395cfbc518e992cc0abbdc61d/Testing/SystemTests/tests/framework/ISISIndirectEnergyTransferTest.py#L12

https://github.com/mantidproject/mantid/blob/3bdaa5f88bc2150395cfbc518e992cc0abbdc61d/Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ISISIndirectEnergyTransferTest.py#L26

**Review by robertapplin — APPROVED** [review]
Looks great, its working as expected, it has a release note and we have a test to check it continues to work in the future. Thank you!

**Pull request merged**
