### PR TITLE
DirectILL swap container subtraction and self-shielding correction

### LINKED ISSUE #27051: Direct ILL invert background subtraction logic
**Original reporter:** [ILL]/[Fåk]

### Expected behavior

In direct ILL reduction background subtraction should happen before correcting the sample for absorption, currently it it the contrary.

### PR DESCRIPTION
**Pull request by gvardany**
**Description of work.**

Swaps the empty container subtraction and the self-shielding correction order in `DirectILLApplySelfShielding` algorithm. This change is approved by the instrument scientist to give better results.

**To test:**
Code review should suffice.

Fixes #27051 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by Harrietbrown — CHANGES_REQUESTED** [review]
Just remove that one blank line in the release notes and this will be good to go.

**Review by Harrietbrown — DISMISSED** [review]
All good, a small change.

**Comment by gvardany** [comment]
Apparently the line was needed, otherwise there was a warning in docs.

**Review by Harrietbrown — APPROVED** [review]
Good work.

**Pull request merged**
