### PR TITLE
Remove RectangularDetector monitor and use normal monitor

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
We have made a minor change to the `CreateSampleWorkspace` algorithm to create a normal `Detector` monitor instead of a `RectangularDetector` monitor. This has been done because we were experiencing a few bugs as mentioned in Gemma's comments below. We also felt it didn't make sense to use a `RectangularDetector` monitor which only has one pixel (as this seems equivalent to just a single ordinary Detector), and whether a RectangularDetector monitor is a true-to-life situation is doubtful.

**To test:**
Code review and make sure the tests pass.

Run Gemma's script below.

*There is no associated issue.*

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gemmaguest** [comment]
I think there is an existing bug with SmoothNeighbours that this PR resolves

```
ws=CreateSampleWorkspace(StoreInADS=False, NumBanks=1, BankPixelWidth=3, NumMonitors=2)
sum=SmoothNeighbours(ws, SumPixelsX=3, SumPixelsY=1)
print('Summed workspace: number of histograms =', sum.getNumberHistograms(), ', expected 3')
```

It is supposed to skip monitors, but before this PR they were included so gave:
```
Summed workspace: number of histograms = 5 , expected 3
```

After this PR it successfully excludes them: 
```
Summed workspace: number of histograms = 3 , expected 3
```

**Comment by gemmaguest** [comment]
You've also spotted that the test was wrong because this bug meant the monitors were at the end, when really they should be at the start! :+1:

**Comment by gemmaguest** [comment]
This also fixes a bug where the monitors did not display on instrument viewer; they display as expected now:

image

**Review by gemmaguest — APPROVED** [review]
Code changes look good and as per the comments this functions better than before - monitors were previously being created as a cylindrical detector within a rectangular detector bank, which I think is an unexpected arrangement that was causing problems in various parts of the code. Existing test behaviour is unchanged - the test that has been modified in this PR had a bug in it which has now been fixed.

**Comment by robertapplin** [comment]
@mantidproject/gatekeepers Please can we get this merged? Its holding up another PR

**Pull request merged**
