### PR TITLE
Expose IFunction method setMatrixWorkspace to python

### PR DESCRIPTION
**Pull request by RichardWaiteSTFC**
**Description of work.**
Expose IFunction method setMatrixWorkspace to python so can make get calculated parameter values by parsing the  Parameters.xml file associated with instrument. This will be used to estimate the integration range of single-crystal peaks (using the Parameters.xml file to calculate values for BackToBackExponential parameters A,B and S and hence the fwhm of the peak). This will then be used to estimate an integration radius (input to IntegratePEaksMD)

This involved adding a method tot he FunctionFactory to create an IPeakFunction instead of an IFunction and exposing the fwhm() of the IPEakFunction to python.

Thanks to @martyngigg, @Pasarus and @StephenSmith25 for their help!

**To test:**
(1) Run this script
```
ws = LoadEmptyInstrument(InstrumentName='ENGIN-X', OutputWorkspace='ws')
LoadParameterFile(Workspace=ws, Filename='C:/mantid/instrument/ENGIN-X_Parameters.xml')
axis = ws.getAxis(0)
unit = axis.getUnit()
axis.setUnit("TOF")

func = BackToBackExponential()
print('Initialised param values:', [func.function.getParameterValue(ii) for ii in range(func.nParams())])
func.function.setParameter(3, 24000) # set centre
func.function.setMatrixWorkspace(ws, 800, 0.0,0.0) # calculate A,B,S
print('Calc param values:', [func.function.getParameterValue(ii) for ii in range(func.nParams())])
```
(2) The printed output should be
```
Initialised param values: [0.0, 1.0, 0.05, 0.0, 1.0]
Calc param values: [0.0, 0.0709293, 0.0251457, 24000.0, 17.342028614131035]
```

(3) Check we can do the same with an IPeakFunction and use this to calculate the fwhm
```
func = FunctionFactory.Instance().createPeakFunction("BackToBackExponential")
print('Initialised param values:', [func.getParameterValue(ii) for ii in range(func.nParams())])
print('Initial fwhm = ', func.fwhm())
func.setParameter(3, 24000) # set centre
func.setMatrixWorkspace(ws, 800, 0.0,0.0) # calculate A,B,S
print('Calc param values:', [func.getParameterValue(ii) for ii in range(func.nParams())])
print('explicitly set:', [func.isExplicitlySet(ii) for ii in range(func.nParams())])
print('fwhm = ', func.fwhm())
```
(4) The printed output should look like 
```
Initialised param values: [0.0, 1.0, 0.05, 0.0, 1.0]
Initial fwhm =  16.5684305715229
Calc param values: [0.0, 0.0709293, 0.0251457, 24000.0, 17.342028614131035]
explicitly set: [False, True, True, True, True]
fwhm =  72.62347002386443
```
(5) Check you get an error if you try to make a IPEakFunction from a function name that is not a peak e.g.
```
func = FunctionFactory.Instance().createPeakFunction("LinearBackground") # should throw ValueError
```

*There is no associated issue.*

*This does not require release notes* because small change to API that has not been requested externally.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — COMMENTED** [review]
Any chance we could add a test in https://github.com/mantidproject/mantid/blob/50d7ff1a9aab51a73ac8970d62f93be7750bf622/Framework/PythonInterface/test/python/mantid/api/IFunction1DTest.py ?

**Comment by RichardWaiteSTFC** [comment]
> Any chance we could add a test in https://github.com/mantidproject/mantid/blob/50d7ff1a9aab51a73ac8970d62f93be7750bf622/Framework/PythonInterface/test/python/mantid/api/IFunction1DTest.py ?

Of course - I hadn't spotted there were tests in this area, thanks! FYI I am also planning to add the ability to create an `IPeakFunction` in the `FunctionFactory` so I can access methods such as `fwhm` etc. so I have labelled this a draft for now

**Review by Pasarus — APPROVED** [review]
Good change :+1:

**Comment by gvardany** [comment]
Is this worth a release note?

**Comment by gvardany** [comment]
OK, just read in the description.

**Pull request merged**
