### PR TITLE
Fix GSAS-II interaction in Engineering UI

### LINKED ISSUE #35134: Engineering Diffraction interaction with GSAS-II not working on Windows
The GSAS tab on the Engineering Diffraction UI provides a call from Mantid to GSAS-II. This has stopped working on Windows recently and fails with the following error. The message is quite long but the main problem seems to be that numpy isn't able to load the mkl-service python package (Intel math kernel library):
```
GSAS-II call must have failed, as the output project file was not found.


---------------------
---------------------
 Errors from GSAS-II 
---------------------
---------------------
C:\Users\iao46725\gsas2full\lib\site-packages\numpy\__init__.py:138: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:\Users\iao46725\gsas2full\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "C:\Users\iao46725\gsas2full\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Users\iao46725\gsas2full\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\mantid\qt\python\mantidqtinterfaces\mantidqtinterfaces\Engineering\gui\engineering_diffraction\tabs\gsas2\call_G2sc.py", line 194, in <module>
    import GSASIIscriptable as G2sc  # noqa: E402
  File "C:\Users\iao46725\gsas2full\GSASII\GSASIIscriptable.py", line 1266, in <module>
    import numpy.ma as ma
  File "C:\Users\iao46725\gsas2full\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import core
  File "C:\Users\iao46725\gsas2full\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "C:\Users\iao46725\gsas2full\python.exe"
  * The NumPy version is: "1.19.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed: The specified module could not be found.


---------------------
---------------------



GSAS-II call must have failed, as the output result file was not found.


---------------------
---------------------
 Errors from GSAS-II 
---------------------
---------------------
C:\Users\iao46725\gsas2full\lib\site-packages\numpy\__init__.py:138: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:\Users\iao46725\gsas2full\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "C:\Users\iao46725\gsas2full\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Users\iao46725\gsas2full\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\mantid\qt\python\mantidqtinterfaces\mantidqtinterfaces\Engineering\gui\engineering_diffraction\tabs\gsas2\call_G2sc.py", line 194, in <module>
    import GSASIIscriptable as G2sc  # noqa: E402
  File "C:\Users\iao46725\gsas2full\GSASII\GSASIIscriptable.py", line 1266, in <module>
    import numpy.ma as ma
  File "C:\Users\iao46725\gsas2full\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import core
  File "C:\Users\iao46725\gsas2full\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "C:\Users\iao46725\gsas2full\python.exe"
  * The NumPy version is: "1.19.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed: The specified module could not be found.


---------------------
---------------------
```

The problem doesn't happen on my Ubuntu VM (and I hope not on IDAaaS either).

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

Correct GSASII path for finding dlls when called from Engineering Diffraction UI in Mantid. GSAS was previously running mkl from the Mantid conda environment which worked if the GSAS\Mantid mkl versions were approximately the same but broke recently when Mantid increased its version. This only affected Windows where finding shared libraries (dlls) is more reliant on the PATH environment variable+ the mkl package is Windows-only. It may be the case though that even on Linux, GSAS is relying on some part of the Mantid Conda environment so I've included an edit to PATH on Linux also.

Solution could be improved calling activate script for GSASII Conda environment. Not doing that in release sprint because it probably involves inserting a new .bat file layer that calls activate followed by the G2SC python script so changes to PATH are retained in the same subprocess

**To test:**

Install GSAS2 from here: https://subversion.xray.aps.anl.gov/trac/pyGSAS/wiki/InstallWindows

Open up the Engineering Diffraction interface and perform the Calibration and Focus steps from Test 1 of the Engineering Diffraction manual testing instructions: https://developer.mantidproject.org/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.html

Then move to the GSAS tab. Enter:
- a project name
- Select ENGINX_305738_all_banks.prm as the Instrument Group (perhaps this is auto populated)
- select `scripts/Engineering/ENGINX/phase_info/FE_GAMMA.cif` as the phase file
- Select ENGINX_305761_307521_all_banks_TOF.gss as Focused Data (perhaps this is auto populated)

Click on the "Refine in GSAS II" button and check it completes without errors

Fixes #35134. 

*This does not require release notes* because **it was a regression in this release**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by RichardWaiteSTFC — COMMENTED** [review]
This seems to work for me using GSAS2 v5487, note I didn't add it to the PATH and didn't set it to be the default python 3.7 during install - is that OK? 
~~I will check `main` now to see if I can reproduce the issue.~~ I can reproduce the issue on main

If the GSAS2 path in the UI settings is incorrect (e.g. the default path is set to `opt/GSAS` or similar - perhaps it should be blank?) then I get the following error which perhaps could be handled more graciously
```
Traceback (most recent call last):
 File "c:\mantid-conda\mantid\qt\python\mantidqtinterfaces\mantidqtinterfaces\Engineering\gui\engineering_diffraction\tabs\gsas2\presenter.py", line 34, in on_refine_clicked
 number_output_histograms = self.model.run_model(
 File "c:\mantid-conda\mantid\qt\python\mantidqtinterfaces\mantidqtinterfaces\Engineering\gui\engineering_diffraction\tabs\gsas2\model.py", line 99, in run_model
 runtime = self.call_gsas2()
 File "c:\mantid-conda\mantid\qt\python\mantidqtinterfaces\mantidqtinterfaces\Engineering\gui\engineering_diffraction\tabs\gsas2\model.py", line 186, in call_gsas2
 gsas2_called = self.call_subprocess(command_string_list)
 File "c:\mantid-conda\mantid\qt\python\mantidqtinterfaces\mantidqtinterfaces\Engineering\gui\engineering_diffraction\tabs\gsas2\model.py", line 251, in call_subprocess
 shell_process = subprocess.Popen(
 File "C:\Users\xhg73778\AppData\Local\mambaforge\envs\mantid-developer\lib\subprocess.py", line 858, in __init__
 self._execute_child(args, executable, preexec_fn, close_fds,
 File "C:\Users\xhg73778\AppData\Local\mambaforge\envs\mantid-developer\lib\subprocess.py", line 1311, in _execute_child
 hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 3] The system cannot find the path specified
```

**Comment by DannyHindson** [comment]
> This seems to work for me using GSAS2 v5487, note I didn't add it to the PATH and didn't set it to be the default python 3.7 during install - is that OK? ~I will check `main` now to see if I can reproduce the issue.~ I can reproduce the issue on main
> 
> If the GSAS2 path in the UI settings is incorrect (e.g. the default path is set to `opt/GSAS` or similar - perhaps it should be blank?) then I get the following error which perhaps could be handled more graciously
> 
> ```
> Traceback (most recent call last):
>  File "c:\mantid-conda\mantid\qt\python\mantidqtinterfaces\mantidqtinterfaces\Engineering\gui\engineering_diffraction\tabs\gsas2\presenter.py", line 34, in on_refine_clicked
>  number_output_histograms = self.model.run_model(
>  File "c:\mantid-conda\mantid\qt\python\mantidqtinterfaces\mantidqtinterfaces\Engineering\gui\engineering_diffraction\tabs\gsas2\model.py", line 99, in run_model
>  runtime = self.call_gsas2()
>  File "c:\mantid-conda\mantid\qt\python\mantidqtinterfaces\mantidqtinterfaces\Engineering\gui\engineering_diffraction\tabs\gsas2\model.py", line 186, in call_gsas2
>  gsas2_called = self.call_subprocess(command_string_list)
>  File "c:\mantid-conda\mantid\qt\python\mantidqtinterfaces\mantidqtinterfaces\Engineering\gui\engineering_diffraction\tabs\gsas2\model.py", line 251, in call_subprocess
>  shell_process = subprocess.Popen(
>  File "C:\Users\xhg73778\AppData\Local\mambaforge\envs\mantid-developer\lib\subprocess.py", line 858, in __init__
>  self._execute_child(args, executable, preexec_fn, close_fds,
>  File "C:\Users\xhg73778\AppData\Local\mambaforge\envs\mantid-developer\lib\subprocess.py", line 1311, in _execute_child
>  hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> FileNotFoundError: [WinError 3] The system cannot find the path specified
> ```

I don't remember what options I was presented with during the GSAS2 install on my laptop. But since you can reproduce on main and it seems like it's fixed on this PR it sounds like it's a valid test.

I think I'll pick up the GSAS path validation as a separate issue on main

**Comment by DannyHindson** [comment]
> Also a separate issue is that this doesn't seem to work for texture grouping, even though I used a texture.prm. Is that a known issue/expected? If so, perhaps we could check and stop the users using a prm with texture in the name?
> 
> ```
> GSAS-II call must have failed, as the output result file was not found.
> ---------------------
> ---------------------
>  Errors from GSAS-II 
> ---------------------
> ---------------------
> Traceback (most recent call last):
>   File "C:\Users\xhg73778\gsas2full\GSASII\GSASIIscriptable.py", line 1716, in load_pwd_from_reader
>     Iparm1, Iparm2 = instprm
> ValueError: too many values to unpack (expected 2)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "c:\mantid-conda\mantid\qt\python\mantidqtinterfaces\mantidqtinterfaces\Engineering\gui\engineering_diffraction\tabs\gsas2\call_G2sc.py", line 200, in <module>
>     add_histograms(data_files, gsas_project, instrument_files, number_of_regions)
>   File "c:\mantid-conda\mantid\qt\python\mantidqtinterfaces\mantidqtinterfaces\Engineering\gui\engineering_diffraction\tabs\gsas2\call_G2sc.py", line 30, in add_histograms
>     instbank=loop_region_index,  # indexing starts at 1
>   File "C:\Users\xhg73778\gsas2full\GSASII\GSASIIscriptable.py", line 2164, in add_powder_histogram
>     [h.name for h in self.histograms()],bank=instbank)
>   File "C:\Users\xhg73778\gsas2full\GSASII\GSASIIscriptable.py", line 1718, in load_pwd_from_reader
>     Iparm1, Iparm2 = load_iprms(instprm, reader, bank=bank)
> ValueError: not enough values to unpack (expected 2, got 0)
> 
> ---------------------
> ---------------------
> ```

I'll check with Dan but yes need to do something a bit extra here one way or another

**Comment by DannyHindson** [comment]
@gemmaguest - this is the issue I just mentioned that I'm wondering if we can put into the release

**Review by RichardWaiteSTFC — APPROVED** [review]
Looks good, happy for GSAS path validation and texture fix to be handled in separate issues!

**Pull request merged**
