### PR TITLE
Muon analysis update group saving and loading

### LINKED ISSUE #29115: Update load and save XML for MA
The load and save buttons will need updating for the grouping tab on muon analysis.

It will need to:
1. save out a new XML file that includes periods
2. Load new XML files correctly. If a period is missing it will not be created (e.g. have fwd for just 1 and 3)
3. Load legacy XML files correctly. This will assume one instance of each group for the available periods

### PR DESCRIPTION
**Pull request by Matthew-Andrew**
**Description of work.**

This updates the loading and saving routines for muon grouping xml files so that the period information contained in groups can be saved and loaded. 

**To test:**

 * Load some multiperiod data into the MuonAnalysis GUI. If you have access to the ISIS data archive the HIFI84447.
 * On the grouping tab save out an xml file and re-load it. Check that the periods information has been preserved in the groups.
 * Check that old grouping files still load correctly. Default grouping files can be found in the `instrument/Grouping` directory of the mantid source directory.

Fixes #29115  

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
not sure why, but my version seems to have the old order for the groups (fwd1, fwd2 etc.).

**Comment by AnthonyLim23** [comment]
The only other thing that I can see is that loading legacy xml files will only ever create single period data. Not sure if there is much we can do about that.

**Comment by Mantid-Matthew** [comment]
> 
> 
> not sure why, but my version seems to have the old order for the groups (fwd1, fwd2 etc.).

I think this is because this was based off the grouping PR before this re-ordering was implimented. I have now rebased and think it works for me. Let me know if this doesn't solve it for you.

**Comment by Mantid-Matthew** [comment]
> 
> 
> The only other thing that I can see is that loading legacy xml files will only ever create single period data. Not sure if there is much we can do about that.

Yes this is worth bearing in mind but don't think there is a sensible way to solve this here. For the default grouping files we do create a copy of the default grouping for every period. But I think when they have loaded a specific file we should stick with only periods they explicitely specify.

**Review by AnthonyLim23 — COMMENTED** [review]
looks good

**Review by AnthonyLim23 — DISMISSED** [review]

**Review by DavidFair — APPROVED** [review]
I've fixed a one letter typo for you in the release notes
I'm happy to merge this once the CI finishes (just to cover myself)

**Pull request merged**
