### PR TITLE
Set last run to "Auto" in ALC interface

### LINKED ISSUE #10057: Make it possible to set the last run to "Auto"
This issue was originally [TRAC 9214](http://trac.mantidproject.org/mantid/ticket/9214)

Original Reporter: Arturs Bekasovs

This ticket is blocked by : 
 - [X] [TRAC6931](http://trac.mantidproject.org/mantid/ticket/6931)
 - [X] [TRAC9213](http://trac.mantidproject.org/mantid/ticket/9213)
 - [x] Issue #13862 
 - [x] Issue #13899 

Make it possible to set last_run to "Auto" which will make the interface to observe changes in the directory of the first_run and append any new files to the data set.

 - - - - 
Keywords: ALC

### PR DESCRIPTION
**Pull request by tom-perkins**
Resolves #10057.

User can enter the last run as "auto", which will automatically set the last run to the most recently modified file in the same directory as first_run.
The interface will then monitor this directory and automatically add files to the data set as they are added to the directory (or removed). 

Test:
- Get a set of muon data, for example HIFI 83077-83157 (\isis\inst$\cycle_15_1\NDXHIFI...) and put a subset of these files in a test directory.
- Open ALC interface, set first_run to the first file in the test directory.
- Set last run to "Auto" (not case-sensitive) and click Load. Verify that all files in the directory are automatically loaded.
- Copy some more of the data sets into the test directory. Verify that they are automatically picked up and loaded.
- Test that interface can handle some sets being removed from the directory.
- Test that existing functionality is not broken, i.e. setting last_run to a file (not auto) works.

Could not add a unit test for this because the data files used in the tests do not appear in a directory, so cannot find the other files automatically. This did however prompt the handling of exceptions that may be thrown in this situation.

Documentation updates:
- [x] Update [release notes](http://www.mantidproject.org/Release_Notes_3_6_MuonAnalysis)
- [x] Update [interface documentation](http://www.mantidproject.org/Muon_ALC:_Data_Loading)

### CODE REVIEW

**Comment by tom-perkins** [comment]
Added a checkbox to the ALC that sets last_run to "Auto" and disables editing text and the browse button. Unchecking the box enables editing, enables the browse button and clears the text.

**Comment by raquelalvarezbanos** [comment]
I've tried the suggested sample dataset and verified that new runs are automatically picked up and loaded. I've also checked that the existing functionality works. However, I've noticed a couple of things:

- The user may want to stop observing the directory, that means they uncheck "Auto". In this case, we should disconnect the signals emitted by the watcher from the corresponding slot. I've checked that at the moment, the interface keeps updating every new file.

- When I remove some of the previously loaded datasets, I get an error: "Invalid string position". For instance, I copied runs HIFI00083077 to HIFI00083097 to my test directory. Then, if I remove HIFI00083085 to HIFI00083086, I get the "Invalid string position" error. The interface does not seem to work well after this.

- Regarding the documentation (sorry, this is entirely my fault because I didn't mention), changes should be added to mantid\docs\source\interfaces\Muon_ALC.rst. The wikipage you have updated:
http://www.mantidproject.org/Muon_ALC:_Data_Loading and also:
http://www.mantidproject.org/Muon_ALC
http://www.mantidproject.org/Muon_ALC:_Baseline_Modelling
http://www.mantidproject.org/Muon_ALC:_Peak_Fitting
should be deleted, as the documentation was moved to the .rst file. I thought we had an issue to delete these old wiki pages, but if we don't, could you create one please?

**Comment by tom-perkins** [comment]
Created #14624 to delete the ALC wiki pages, as I couldn't find the existing issue.

**Comment by raquelalvarezbanos** [comment]
Thanks for the new changes, now we can stop watching the directory and the re-entrancy problem was fixed. There is just one additional issue I didn't notice before, the new functionality does not seem to work with MUSR datasets (I was using MUSR00015189.nxs - MUSR00015193.nxs)

**Pull request merged**
