### PR TITLE
Replace all uses of boost::assign with initializer lists

### LINKED ISSUE #15175: Replace all uses of boost::assign with initializer lists
Initializer lists are now available on all compilers. This should remove the need for using boost::assign. Replace all instances of `boost::assign` with initializer lists.

In many cases, tests mostly, it should also be possible to use `std::array` rather than `std::vector`

### PR DESCRIPTION
**Pull request by shahrozahmed1**
Fixes #15175

Now that Initializer lists are available on all compilers, we no longer require the use of `boost::assign`

**To Test**
- No more usage of `boost::assign` in any of the Mantid files; instead the initialiser list utilised
- The functionalities of the files has not been affected so all the related tests should pass
- Code review

_No need to include this in the release notes._

### CODE REVIEW

**Comment by martyngigg** [comment]
No functional testing required here as the unit tests will cover it.

**Comment by martyngigg** [comment]
I've found a couple of other references in the following classes:
- [RebinByTimeBaseTest](https://github.com/mantidproject/mantid/blob/a8434ee822533a8b44daf405aa65d685f1ff0be8/Framework/Algorithms/test/RebinByTimeBaseTest.h)
- [ClusterIntegrationBaseTest.h](https://github.com/mantidproject/mantid/blob/a8434ee822533a8b44daf405aa65d685f1ff0be8/Framework/Crystal/test/ClusterIntegrationBaseTest.h)

**Comment by martyngigg** [comment]
I'm happy with the rest of the changes so when those two classes are updated we can merge.

**Comment by shahrozahmed1** [comment]
@martyngigg I'm not sure how I have missed those classes, however the previous commit carries the changes required.

**Comment by martyngigg** [comment]
@shahrozahmed1 Easily done with so many to do. I can't find any more now so I think we're done.

**Comment by martyngigg** [comment]
I'm ignoring the failure on RHEL6 as it's an unrelated jenkins network error. The console says everything built and the tests passed.

**Pull request merged**
