### PR TITLE
Indirect - Diffraction Diffspec - Prevent check for 'runs' equality unless SumFiles is false

### LINKED ISSUE #20031: Indirect - Diffraction Diffspec - Invalid run equality requirement
The ISISDiffractionReduction algorithm, requires the number of runs in the input file and vanadium file to be equal. This should not be the case when Sum Files is selected.

### PR DESCRIPTION
**Pull request by brandonhewer**
In the ISISIndirectDiffractionReduction algorithm, it is usually the case that the number of runs in the samples file and the vanadium runs file need to be equal. This is not true when SumFiles is set to true/selected.

Added a falsity check for the SumFiles property before checking whether the number of runs in the samples file is equal to the number of runs in the vanadium file.

**To test:**
1. Access the Diffraction interface by navigating to Interfaces > Indirect > Diffraction.
2. Select OSIRIS as the Instrument.
3. Ensure 'diffspec' is selected in the Reflection drop-down menu.
4. Select an input *_red.nxs (sample) file.
5. Ensure that the 'Sum Files' checkbox is checked.
6. Ensure that the checkbox 'Use Vanadium File' is checked.
7. Select a vanadium range with a different number of runs than the input sample range.
8. Run the algorithm and ensure it runs successfully without throwing an error/exception.

Sample Run Numbers: 10203-10204
Vanadium Run Numbers: 10156

Fixes #20031. 

**Release Notes** 

Added an explanation of the bug fix to the release notes.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by louisemccann** [comment]
update indirect release notes eg `Same number of vanadium and sample files required`

**Review by louisemccann — CHANGES_REQUESTED** [review]
During testing, if `Use Vanadium Files` was clicked but no vanadium file was entered the algorithm worked fine.

Add validation for the `Use validation file` check, best to do this in the interface

**Comment by louisemccann** [comment]
This still fails when `IRIS` is the selected instrument

**Comment by louisemccann** [comment]
@brandonhewer this has developed merge conflicts

**Comment by brandonhewer** [comment]
@louisemccann Resolved merge conflicts.

**Comment by NickDraper** [comment]
Brandon, could you resolve these conflicts please (merge in master)

**Comment by KarlPalmen** [comment]
How does one determine the number of runs in an Vanadium or input sample file, to carry out instruction 6?

**Review by KarlPalmen — CHANGES_REQUESTED** [review]
After step 5, I checked Vanadium file and attempted to run without selecting a Vanadium file. The error box appeared as expected, but it still attempted to execute the algorithm, so causing other errors to appear.  

Also I need to know how to identify necessary files for step 6. I have HDFView so can examine the Nexus contents.

**Comment by SpencerHowells** [comment]
For the number of runs, info might be available in the Sample Logs. In other routines we have a list of the run numbers, for example.

**Comment by brandonhewer** [comment]
@KarlPalmen I should have added test files for this purpose. Mistake on my behalf! The issue was simply forgetting to return from within execution.

**Comment by KarlPalmen** [comment]
The attempting run without Vanadium file when Vanadium file checkbox is selected fails as expected.

Can you please provide some multi-run files to do the rest of the test?

**Comment by brandonhewer** [comment]
@KarlPalmen I've added example Run Numbers (for Sample and Vanadium) to the PR description.
Sample Run Numbers: 119977-119988
Vanadium Run Numbers: 119963-119974

**Comment by KarlPalmen** [comment]
When I entered the run numbers suggested. The run button was disabled and displayed as ``Invalid Run``. The red stars indicate ``Unable to find file: search object (first run number)``. Need I have something set up?

**Comment by brandonhewer** [comment]
@KarlPalmen Seems those run numbers weren't included in the build. Ok I'll revise with numbers that do exist.

**Comment by KarlPalmen** [comment]
I looked at the IRIS files and find those run numbers have yet to be used. The largest run number I found is 75269.

**Comment by brandonhewer** [comment]
@KarlPalmen I'm not sure this PR has a purpose, I feel as though this code should be moved to a new PR. This issue is in fact part of a bigger problem not understood at the time.

**Comment by brandonhewer** [comment]
@KarlPalmen See: https://github.com/mantidproject/mantid/pull/20491

**Comment by KarlPalmen** [comment]
Also there are no unit tests modified. If there were, they'd give me a clue about files to use.

**Comment by brandonhewer** [comment]
More general issue found with Summing files -> the relationship between Vanadium files and Sample files was incorrect -> fix moved to PR #20491

**Pull request closed without merging**
