### PR TITLE
Fix sum file behaviour for vesuvio diffraction

### PR DESCRIPTION
**Pull request by martyngigg**
Description of work.

**To test:**

Requires access to the ISIS archive.

The following scripts provides a basis for testing. When `SumFiles=True` there should be a group output with a single reduced workspace. When `SumFiles=False` there should be a workspace per input run. 

```
VesuvioDiffractionReduction(InputFiles='15288,15289',
                        OutputWorkspace='DiffractionReductions',
                        SumFiles=True,
                        InstrumentParFile='IP0005.dat')
```

No issue number

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by louisemccann** [comment]
The example works as expected but entering a range of runs in the form `22668-22674` produces the following error:
```
RuntimeError: Workspace2D::getSpectrum, histogram number 196 out of range 196
  at line 148 in 'C:/Users/PKB22426/Documents/Build1/mantid/Framework/PythonInterface/plugins/algorithms\LoadVesuvio.py'
  caused by line 362 in 'C:/Users/PKB22426/Documents/Build1/mantid/Framework/PythonInterface/plugins/algorithms\LoadVesuvio.py'
  at line 107 in 'C:/Users/PKB22426/Documents/Build1/mantid/Framework/PythonInterface/plugins/algorithms\WorkflowAlgorithms\VesuvioDiffractionReduction.py'
  caused by line 44 in 'C:/Users/PKB22426/Documents/Build1/mantid/scripts/Inelastic\IndirectReductionCommon.py'
  caused by line 934 in 'C:\Users\PKB22426\Documents\Build1\Build\bin\Release\mantid\simpleapi.py'
  at line 4 in 'C:/Users/PKB22426/Documents/test4.py'
  caused by line 934 in 'C:\Users\PKB22426\Documents\Build1\Build\bin\Release\mantid\simpleapi.py'
```

**Comment by martyngigg** [comment]
Thanks, @louisemccann. That should be fixed now.

**Comment by louisemccann** [comment]
Input as a range and comma separated list work as expected. :shipit: once all tests pass

**Comment by AndreiSavici** [comment]
At some point consider refactoring https://github.com/mantidproject/mantid/blob/410ce375fc402fa32911aaaab5803b5618cd38f6/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/VesuvioDiffractionReduction.py#L202-L207
It seems to me that `IntArrayProperty` will do the work for you, so you don't need to loop over pieces of the input string array
`print(IntArrayProperty("array_generator","1-4,  7-11").value.tolist())` yields `[1, 2, 3, 4, 7, 8, 9, 10, 11]`

**Comment by martyngigg** [comment]
Good point. That would be much easier. Thanks.

**Pull request merged**
