### PR TITLE
MuonAnalysis: fix "load current" for non-Windows systems

### LINKED ISSUE #10329: Make 'load current' work for linux and mac also
This issue was originally [TRAC 9486](http://trac.mantidproject.org/mantid/ticket/9486)

It was noticed during testing of http://trac.mantidproject.org/mantid/ticket/9417 that 'load current' in fact have hardcoded paths for Windows, which means this functionality currently only works for Windows.

No Muon user have ever complained about this, hence interested they all appear to be windows users!

However, Jay showed me code in std::string CatalogInfo::transformArchivePath(std::string &path) that demonstrate how to make this work for linux and mac also using the path information in facilities.xml

    `<filelocation>`
      `<prefix regex="\\\\isis\\inst\$\\Instruments\$">``</prefix>`
      `<windows replacement="">``</windows>`
      `<linux replacement="/archive">``</linux>`
      `<mac replacement="/archive">``</mac>`
    `</filelocation>`

This ticket is to do something similar here for MuonAnalysis

### PR DESCRIPTION
**Pull request by tom-perkins**
Resolves #10329 
Pull request is an updated version of #14446 

The "load current" button in Muon Analysis gets the latest data set from the selected (ISIS) instrument. 

This does _not_ use the `\\isis\inst$\Instruments$\NDX...` catalog path that is mounted under `/archive` on Linux/Mac. Rather, the data is on an SMB share named after the machine, e.g. `\\MUSR\data`.

This works fine on Windows but, on Unix-like systems, it is necessary to explicitly mount the shared drives to access the data (and unmount afterwards).

(Tester will need a Linux/Mac machine, access to the ISIS network, and probably root permissions, unless there is a way to access the data using something like `gvfs-mount`?).

Also updated the path for ARGUS instrument - this had a hardcoded special case that appears to no longer apply, so is now treated the same as the other instruments.

Test: open Muon Analysis interface and click the "Load current" button. Dataset should be loaded.

### CODE REVIEW

**Comment by martyngigg** [comment]
@MikeHart85 Are able to pick this back up to test or should someone else pick it up?

**Comment by MikeHart85** [comment]
@martyngigg This will not work the way it's implemented right now.

As some of the comments in the code acknowledge, mounting the network drive would require root privileges. 

I don't know of any easy way around this. Running Mantid as root is probably not an option. Adding sudo to the command would likely require some prior setup to allow Mantid to do that without a password prompt... also not an ideal scenario. The best option I can think of at the moment is setting up `/etc/fstab` with all available/required instrument network directories during installation, along with a `user` flag on each entry. That way the mount could be done without root privileges and the security risk would be minimal.

Even with that resolved, the command would not work as is:
- The mount target directory needs to exist prior to mount being run
- Potentially may need to also be `chown`ed and/or `chmod`ded
- If the `fstab` approach is used, the `mount` command will need to change
- `/mnt` isn't necessarily the best place to mount to. On Ubuntu, for example, the typical mount point is `/media/$USER`. But both of those directories would again require root privileges to manipulate. Arguably it might be better to mount to `~/.mantid/mount` or something along those lines.

A while back, @OwenArnold and I also discussed how having access to network locations on Linux would be something other parts of Mantid would benefit from as well (Catalog for example). So moving this feature to a more general place and just invoking it from here would probably make sense.

Overall, this needs more thought/work and isn't ready to merge. Could we bump it to 3.7 for now?

**Comment by martyngigg** [comment]
@MikeHart85 Thanks for the update. I agree that I don't think this is the way to solve this.

Mantid should simply assume that things like mounts are set up and we just need to be more flexible about how we let users specify things like the location of the archive or the location of the current cycle directory, for example. Mantid currently only has the concept of the archive so we would need to introduce the concept of a "current" cycle. 

This is certainly not critical as Muons exclusively use windows so the issue can be bumped back.

**Comment by OwenArnold** [comment]
@MikeHart85 @martyngigg We already have some ways of specifying mount points in Mantid. I think this should go back to 3.7

**Comment by tom-perkins** [comment]
Archiving for reasons above and because no users have ever asked for this feature

**Pull request closed without merging**
