### PR TITLE
Indirect - Data Analysis - Extract Convolution Fit Members

### LINKED ISSUE #20168: Indirect - ConvFit - Convert output to member workspaces
The output from ConvFit (Interfaces > Indirect > Data Analysis > ConvFit) contains a GroupWorkspace which has a workspace for each spectrum, which contains a histogram for Data, Calc, Diff and each member contribution to calc. This should be able to be converted to workspaces containing only the convolution members.

There does not currently exist an algorithm for producing a second GroupWorkspace from the first, which contains a workspace for each convolution member.

### PR DESCRIPTION
**Pull request by brandonhewer**
Currently, there is no option for extracting members (e.g. Data, Calc, Diff, Delta, Lorentzian) from the result of a convolution fit, into their own workspaces.

An 'ExtractMembers' boolean property has been added to the ConvolutionFitSequential algorithm, to provide users the option to extract members, each into their own workspace, which are subsequently grouped into a *_Members group workspace. The ConvFit interface has been updated to reflect this change, through the addition of a checkbox labelled 'ExtractMembers' in the properties table.

**To test:**
1. Navigate to Interfaces > Indirect > Data Analysis.
2. Click on the 'ConvFit' tab.
3. Supply a reduced (*_red.nxs) file into the Sample field (test files provided below).
4. Supply a resolution (*_res.nxs) file into the Resolution field (test files provided below).
5. Set Fit Type to One Lorentzian (for test files) or to the function whose shape best fits the miniplot.
6. In the properties table, check the checkbox with the label 'ExtractMembers'.
7. Run the algorithm.
8. Ensure a *_Members workspace was created.
11. Open a workspace from inside the *_Workspaces group workspace inside the viewer (table view).
12. Take note of the the names of all the members (row labels).
13. Expand the *_Members workspace and check that a workspace for every member is included:
      Name of member workspaces will have format *_NameOfMember
      **NOTE:** 'Convolution' member should be correctly renamed to 'Lorentzian1', 'Lorentzian2', 'Delta'                
                       depending on the function which was used in the convolution fitting, represented by that member.
14. Open the input sample (*_red) workspace and for each member workspace check that is has the 
      same number of spectrum (in this case - rows) as the sample workspace.
15. For each member workspace, check that it has the same X-values (Q-space) as the sample workspace, 
      excluding the first x-value in the sample workspace.

[ConvFitTestFiles.zip](https://github.com/mantidproject/mantid/files/1205356/ConvFitTestFiles.zip)

Fixes #20168. 

**Release Notes** 

#### Changes have been added to the release notes and workflow diagram has been updated.
---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [x] Are the unit tests small and test the class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] Do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by jmborr** [comment]
I ran the interface in my Ubuntu 16.04 with both with python 2.7 and python 3.5 builds. It does the fit but trying to  `plot` or `show data` or `CloneWorkspace` for any of the the `_Member` workspaces other than `Data` results in segmentation fault.
```
********* SEGMENTATION FAULT *********
 /home/jbq/repositories/mantidproject/mantid3/cmake-build-debug/bin/libMantidAPI.so(+0x31a121) [0x7fd85a0f3121]
 /home/jbq/repositories/mantidproject/mantid3/cmake-build-debug/bin/libMantidAPI.so(+0x31a350) [0x7fd85a0f3350]
 /lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7fd8529db4b0]
 /home/jbq/repositories/mantidproject/mantid3/cmake-build-debug/bin/libMantidAPI.so(+0x3442dc) [0x7fd85a11d2dc]
 /home/jbq/repositories/mantidproject/mantid3/cmake-build-debug/bin/libMantidAPI.so(+0x3966a6) [0x7fd85a16f6a6]
 /home/jbq/repositories/mantidproject/mantid3/cmake-build-debug/bin/libMantidAPI.so(+0x399c8b) [0x7fd85a172c8b]
 /home/jbq/repositories/mantidproject/mantid3/cmake-build-debug/bin/libMantidAPI.so(_ZNK6Mantid3API15MatrixWorkspace12getDimensionEm+0xca) [0x7fd85a16b5d0]
 /home/jbq/repositories/mantidproject/mantid3/cmake-build-debug/bin/libMantidAPI.so(_ZN6Mantid3API10MDGeometryC1ERKS1_+0x177) [0x7fd85a15c30f]
 /home/jbq/repositories/mantidproject/mantid3/cmake-build-debug/bin/libMantidAPI.so(_ZN6Mantid3API12IMDWorkspaceC1ERKS1_+0x42) [0x7fd85a16f4dc]
 /home/jbq/repositories/mantidproject/mantid3/cmake-build-debug/bin/libMantidAPI.so(_ZN6Mantid3API15MatrixWorkspaceC1ERKS1_+0x33) [0x7fd85a165c17]
 /home/jbq/repositories/mantidproject/mantid3/cmake-build-debug/bin/libMantidDataObjects.so(+0x6d24c5) [0x7fd84c7d84c5]
 /home/jbq/repositories/mantidproject/mantid3/cmake-build-debug/bin/libMantidDataObjects.so(_ZN6Mantid11DataObjects11Workspace2DC2ERKS1_+0x26) [0x7fd84c7d5c42]
 /home/jbq/repositories/mantidproject/mantid3/cmake-build-debug/bin/libMantidDataObjects.so(_ZNK6Mantid11DataObjects11Workspace2D7doCloneEv+0x2b) [0x7fd84c7d7899]
 /home/jbq/repositories/mantidproject/mantid3/cmake-build-debug/bin//libMantidAlgorithms.so(+0x5fa6bb) [0x7fd81aea76bb]
 /home/jbq/repositories/mantidproject/mantid3/cmake-build-debug/bin//libMantidAlgorithms.so(_ZN6Mantid10Algorithms14CloneWorkspace4execEv+0x164) [0x7fd81aea6a6e]
 /home/jbq/repositories/mantidproject/mantid3/cmake-build-debug/bin/libMantidAPI.so(_ZN6Mantid3API9Algorithm4execENS_8Parallel13ExecutionModeE+0x67) [0x7fd85a03240b]
 /home/jbq/repositories/mantidproject/mantid3/cmake-build-debug/bin/libMantidAPI.so(_ZN6Mantid3API9Algorithm7executeEv+0xa17) [0x7fd85a02bc73]
 /home/jbq/repositories/mantidproject/mantid3/cmake-build-debug/bin/libMantidAPI.so(_ZN6Mantid3API9Algorithm16executeAsyncImplERKN4Poco4VoidE+0x53) [0x7fd85a031787]
 /home/jbq/repositories/mantidproject/mantid3/cmake-build-debug/bin/libMantidAPI.so(_ZN6Mantid3API14AlgorithmProxy16executeAsyncImplERKN4Poco4VoidE+0x46) [0x7fd85a065716]
 /home/jbq/repositories/mantidproject/mantid3/cmake-build-debug/bin/libMantidAPI.so(+0x28f4d6) [0x7fd85a0684d6]
 /usr/lib/libPocoFoundationd.so.31(_ZN4Poco12PooledThread3runEv+0x94) [0x7fd85827fd82]
 /usr/lib/libPocoFoundationd.so.31(+0x223d8d) [0x7fd85827cd8d]
 /usr/lib/libPocoFoundationd.so.31(_ZN4Poco10ThreadImpl13runnableEntryEPv+0xf0) [0x7fd85827ca34]
 /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7fd852d776ba]
 /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fd852aad3dd]

********* SEGMENTATION FAULT *********
 /home/jbq/repositories/mantidproject/mantid3/cmake-build-debug/bin/libMantidAPI.so(+0x31a121) [0x7fd85a0f3121]
 /home/jbq/repositories/mantidproject/mantid3/cmake-build-debug/bin/libMantidAPI.so(+0x31a350) [0x7fd85a0f3350]
 /lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7fd8529db4b0]
 /usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZN6QBrushC2Ev+0xc) [0x7fd856a5b93c]
 /usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZN8QPainterC2EP12QPaintDevice+0xdb) [0x7fd856a970ab]
 /usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore+0x55c) [0x7fd85698de8c]
 /usr/lib/x86_64-linux-gnu/libQtGui.so.4(+0x3ea6c8) [0x7fd856b626c8]
 /usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZN14QWidgetPrivate16syncBackingStoreEv+0xa0) [0x7fd856980c50]
 /usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZN7QWidget5eventEP6QEvent+0x388) [0x7fd8569939b8]
 /usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZN11QMainWindow5eventEP6QEvent+0x113) [0x7fd856d779b3]
 ./MantidPlot() [0x534d51]
 /usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x8c) [0x7fd85693cfdc]
 /usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x2b6) [0x7fd856943f16]
 ./MantidPlot() [0x84334b]
 /usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN16QCoreApplication14notifyInternalEP7QObjectP6QEvent+0x8d) [0x7fd8561c990d]
 /usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x376) [0x7fd8561cd3c6]
 /usr/lib/x86_64-linux-gnu/libQtCore.so.4(+0x1bb13e) [0x7fd8561fa13e]
 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x2a7) [0x7fd84a383197]
 /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x4a3f0) [0x7fd84a3833f0]
 /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2c) [0x7fd84a38349c]
 /usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x7e) [0x7fd8561fa2ae]
 /usr/lib/x86_64-linux-gnu/libQtGui.so.4(+0x272616) [0x7fd8569ea616]
 /usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN10QEventLoop13processEventsE6QFlagsINS_17ProcessEventsFlagEE+0x3f) [0x7fd8561c818f]
 /usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x1b5) [0x7fd8561c84f5]
 /usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN16QCoreApplication4execEv+0x99) [0x7fd8561ce4b9]
 ./MantidPlot() [0x90c9fd]
 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7fd8529c6830]
 ./MantidPlot() [0x48f5b9]
Segmentation fault (core dumped)
```

**Comment by brandonhewer** [comment]
Oh dear, not exactly expected behaviour. Taking a look into this, thanks for finding it :)!

**Comment by brandonhewer** [comment]
@jmborr The issue was that only one NumericAxis was created - the ownership of the pointer for that numeric axis was supplied to the first workspace, each subsequent workspace received a NULL pointer. Attempting to read the memory where there axis should have been lead to a segmentation fault.

**Comment by jmborr** [comment]
OK, please let me know once all the build servers give their pass

**Comment by jmborr** [comment]
@brandonhewer Explanation of this new option `ExtractMembers` should be included in help file `Indirect Data Analysis.rst`.

**Review by jmborr — APPROVED** [review]
it all looks good to me

**Pull request merged**
