### PR TITLE
Allow AppendSpecta to append multiple times

### LINKED ISSUE #13357: Allow AppendSpecta to append multiple times
Add a parameter that defines the number of times the append should be done, will be equivalent to:
```
for i in range(n_spec - 1):
    if i == 0:
        input = ws
    else:
        input = new_ws
       
    AppendSpectra(InputWorkspace1=input,
                  InputWorkspace2=ws,
                  OutputWorkspace=new_ws)
```

### PR DESCRIPTION
**Pull request by DanNixon**
Fixes #13357 

To test, run the algorithm on a MatrixWorkspace add see the effects of changing the `Repeat` parameter.

Release notes updates [here](http://www.mantidproject.org/index.php?title=ReleaseNotes_3_5_Framework_Changes&diff=24952&oldid=24948).

### CODE REVIEW

**Comment by DanNixon** [comment]
The Doxygen failure is unrelated to changes here.

**Comment by KarlPalmen** [comment]
Documentation Issues:

The wording in the 'repeat' property description is not clear. It does not explicitly state what is meant by the number. It could be interpreted as the number of repeats and so if set to 2, one would have the spectra added 3 times. Also it could state that it does not apply to event workspaces. The warning statement from this needs to refer to the property as in documentation rather than as in the code.

**Comment by DanNixon** [comment]
@KarlPalmen The warning did refer to the property name and the property description did say "for MatrixWorkspaces only"

I've changed the property name back to "Number".

**Comment by KarlPalmen** [comment]
I see you did add the 'for Matrix workspaces' later on and changing the property to 'Number' resolves the other issues.

**Comment by KarlPalmen** [comment]
I've just tried it and it appears that your change of the property back to 'Number' has not been completed. Something in the code looks for 'Repeat'.

**Comment by KarlPalmen** [comment]
Line 88 of AppendSpectra.cpp and the unit test need modifying to complete the change in property name.

**Pull request merged**
