### PR TITLE
Fix BeamCentreFinder not running at all

### LINKED ISSUE #27973: Beam Centre Finder has Stopped Working in SANS
The beam centre finder currently doesn't work with the following exception:

```
Error in execution of algorithm SANSBeamCentreFinder:
to_string
at line 186 in '/home/matthew/Documents/Mantid/mantid/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANS/SANSBeamCentreFinder.py'
caused by line 254 in '/home/matthew/Documents/Mantid/mantid/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANS/SANSBeamCentreFinder.py'
caused by line 390 in '/home/matthew/.local/lib/python2.7/site-packages/enum/init.py'
Traceback (most recent call last):
File "/home/matthew/Documents/Mantid/mantid/scripts/Interface/ui/sans_isis/worker.py", line 39, in run
self.result = self.func(*self.args, **self.kwargs)
File "/home/matthew/Documents/Mantid/mantid/scripts/SANS/sans/gui_logic/models/beam_centre_model.py", line 101, in find_beam_centre
verbose=self.verbose, component=self.component)
File "/home/matthew/Documents/Mantid/mantid/scripts/SANS/sans/sans_batch.py", line 120, in call
find_direction, verbose, component)
File "/home/matthew/Documents/Mantid/mantid/scripts/SANS/sans/sans_batch.py", line 127, in _execute_reduction_method
return centre_finder_new(state, r_min, r_max, max_iter, xstart, ystart, tolerance, find_direction, verbose, component)
File "/home/matthew/Documents/Mantid/mantid/scripts/SANS/sans/algorithm_detail/centre_finder_new.py", line 76, in centre_finder_new
beam_centre_alg.execute()
RuntimeError: to_string
at line 186 in '/home/matthew/Documents/Mantid/mantid/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANS/SANSBeamCentreFinder.py'
caused by line 254 in '/home/matthew/Documents/Mantid/mantid/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANS/SANSBeamCentreFinder.py'
caused by line 390 in '/home/matthew/.local/lib/python2.7/site-packages/enum/init.py'
```

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**

Fixes up two errors in the beam centre finder:

- The first is an erronous to_string which was introduced with the
conversion to Python enums in PR #27508
- The second is an error with plotting in workbench which has always
existed. A seperate issue is open, however we can work around it in the
mean time for safety.

**To test:**
On both Workbench and Mantid Plot:
- Download the ISIS Training Data
- Open the ISIS SANS GUI (not old)
- Click user file and browse to the `loqdemo` folder in ISIS Training Data
- Open `MaskFile.txt`
- Load `batch_mode_reduction.csv` into the Batch file
- Hit Load
- Click Beam Centre
- Hit Run
- Check it runs more than 1 iteration, don't worry if it fails to converge after 10 iteration

Fixes #27973 .

*This does not require release notes* because this was a regression introduced during development and has not been noticed by users (yet)

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Mantid-Matthew** [comment]
If I run the beam centre finder multiple times in a row I end up with multiple plots but only the first one is ever used. The others remain as empty blank plots with the same name.

**Comment by Mantid-Matthew** [comment]
There are two more minor issues that I don't think need to be fixed here:

1) If i try and run the beam centre finder without first loading data in the runs tab I get the following misleading error.

Errors in getting states...
Trying to find the SANS file 74044, but cannot find it. Make sure that the relevant paths are added and the correct instrument is selected.

2) If I cancel the Beamcentre finder algorithm whilst it is running this provokes an unhandled exception.

**Comment by DavidFair** [comment]
> If I run the beam centre finder multiple times in a row I end up with multiple plots but only the first one is ever used. The others remain as empty blank plots with the same name.
This is fixed in #27996 - I've cherry picked the commit into this branch for testing

**Comment by Mantid-Matthew** [comment]
I now the first time I try and run beam centre finder get two graphs one black and one white neither of which displays the relevant data.

**Comment by Mantid-Matthew** [comment]
Having investigated this further this seems to be a result of using matplotlib3 on Ubuntu so not relevant to this PR.

**Comment by DavidFair** [comment]
> I now the first time I try and run beam centre finder get two graphs one black and one white neither of which displays the relevant data.

This was a local issue on @Mantid-Matthew 's machine, since resolving it does it now plot correctly?

**Review by Matthew-Andrew — APPROVED** [review]
This works for me now the base issue in #27996 has been resolved.

**Pull request merged**
