### PR TITLE
Abins: support Vasp 6 data

### LINKED ISSUE #35879: Abins support for VASP6
**Original reporter:** Arunabhiram Chutia (working with Stewart Parker)

**Describe the bug**
Data from the vasprun.xml file of a VASP6 vibration calculation looks incorrect in Abins, and very different from equivalent VASP5 calculation.

This appears to be because the units of frequency have changed from the internal atomic units to THz; when a unit conversion is applied in the parser, this greatly increases the frequencies used in Abins.

**To Reproduce**

I will procure some sample files and use these for testing

**Expected behavior**

Results should be very close between equivalent calculations with Vasp5 and Vasp6; the unit conversion should be handled correctly.

### PR DESCRIPTION
**Pull request by ajjackson**
**Description of work**
The vasprun.xml outputs from VASP 6 have different units from VASP 5, leading to totally incorrect frequency scaling in Abins spectra from these files.

**Purpose of work**
Facility users and ISIS scientists are updating to the new version of VASP and will expect their Abins calculations to give correct results.

**Report to:** Sanghamitra Mukhopadhyay, Arunabhiram Chutia

**Summary of work**
The new format helpfully includes metadata with the unit, so we can at least detect this scenario reliably.

Code checks if unit is specified and that it equals THz, in which case a simple 1e12 conversion factor is used. Otherwise, fall back on the old behaviour and convert from "atomic units".

**To test:**
A unit test has been added; I have manually verified that the frequencies in cm-1 agree with the corresponding rows of the OUTCAR file from this calculation, so the unit conversion looks correct. Happy to forward this file to reviewer if necessary.

Extract from ref data for new test:
```
            }
        },
        "k_points_data": {
            "frequencies": {
                "0": [
                    3758.652058798503,
                    3045.46194564425,
                    3039.376253597146,
                    2961.8374272309843,
                    2914.216844200306,
                    2889.584033690314,
                    1447.2473639338514,
                    1420.4918188272136,
                    1397.2985216556688,
                    1383.7365527572535,
                    1322.7138871195007,
                    1241.1169149057066,
                    1208.2719436429059,
                    1125.3941240423046,
                    1106.5495237683774,
                    1019.7605923577939,
                    887.9148520875917,
                    784.7980528307953,
                    407.7814979147206,
                    277.6760772785486,
                    229.35854160521706,
                    39.12264490892534,
                    21.826273864047753,
                    5.403960857824778,
                    -0.3905829827756099,
                    -11.481003448843689,
                    -16.47976907977257
                ]
            },
            "k_vectors": {
                "0": [
                    0.0,
:
```

extract from calculation OUTCAR:

```
Eigenvectors and eigenvalues of the dynamical matrix
 ----------------------------------------------------


   1 f  =  112.681554 THz   707.999085 2PiTHz 3758.652065 cm-1   466.013253 meV
             X         Y         Z           dx          dy          dz
      7.104865  4.636756  4.886933     0.001140    0.001681    0.000000
      5.952226  5.591239  4.886933    -0.000840   -0.009044    0.000000
      4.761575  4.826518  4.886933     0.195432   -0.138444   -0.000000
      3.990656  5.423032  4.886933    -0.776820    0.582306    0.000000
      5.999345  6.247652  5.781661    -0.002597   -0.001417    0.000781
      5.999345  6.247652  3.992205    -0.002597   -0.001416   -0.000781
      8.064111  5.179509  4.886933     0.000496   -0.001840   -0.000000
      7.068581  3.990516  5.779398    -0.000216    0.000377   -0.000861
      7.068581  3.990516  3.994468    -0.000215    0.000377    0.000862

   2 f  =   91.300652 THz   573.658917 2PiTHz 3045.461946 cm-1   377.588988 meV
             X         Y         Z           dx          dy          dz
      7.104865  4.636756  4.886933     0.201892    0.224985   -0.000002
      5.952226  5.591239  4.886933     0.002290    0.017153   -0.000001
      4.761575  4.826518  4.886933    -0.001393   -0.001275    0.000000
      3.990656  5.423032  4.886933    -0.000547   -0.000848    0.000000
      5.999345  6.247652  5.781661    -0.000431   -0.019389   -0.026040
      5.999345  6.247652  3.992205    -0.000431   -0.019391    0.026044
      8.064111  5.179509  4.886933    -0.698447   -0.390372   -0.000000
      7.068581  3.990516  5.779398    -0.001159   -0.202089    0.303576
      7.068581  3.990516  3.994468    -0.001159   -0.202082   -0.303567

   3 f  =   91.118208 THz   572.512584 2PiTHz 3039.376254 cm-1   376.834459 meV
             X         Y         Z           dx          dy          dz
      7.104865  4.636756  4.886933     0.000002    0.000002    0.302249
      5.952226  5.591239  4.886933     0.000000    0.000000    0.039763
      4.761575  4.826518  4.886933     0.000000   -0.000000   -0.000638
      3.990656  5.423032  4.886933    -0.000000    0.000000   -0.001044
```

Fixes #35879 

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by robertapplin — DISMISSED** [review]
Looks good 👍

**Review by SilkeSchomann — CHANGES_REQUESTED** [review]
@ajjackson Could you please add a release note for this?

**Comment by ajjackson** [comment]
> @ajjackson Could you please add a release note for this?

done!

**Review by SilkeSchomann — APPROVED** [review]
Thanks for adding the release note!

**Pull request merged**
