### PR TITLE
D16 water normalization debugging

### PR DESCRIPTION
**Pull request by eurydice76**
The `rescale_flux` method has been fixed and refactored in both versions of SANSILLReduction algorithms.

### CODE REVIEW

**Comment by darominski** [comment]
Could you provide an example how this can be tested?

**Comment by eurydice76** [comment]
By running the system test ...

**Comment by darominski** [comment]
I am not fully sure what do you mean. Since there was a logic issue and the tests were passing, then they were clearly lacking coverage. Upon checking, the `SANSILLReductionTest` from the system tests do not specify `ReferenceInputWorkspace`  so it never entered this part of the code. Some coverage exists in `SANSILLReduction2Test`, but as you suggested, it did not have the same issue as observed by Stef, therefore it cannot test the solution because D16 is unfortunately not covered at all by `SANSILLReduction2Test`. Could you please add that test?

**Review by perenon — APPROVED** [review]
This PR enhances the code readability of two SANSILLReduction algorithms (v1 and v2). A system test for the second one provided, comparing v1 and v2 output.

**Pull request merged**
