### PR TITLE
Add F(q) default parameter estimations

### PR DESCRIPTION
**Pull request by StephenSmith25**
**Description of work.**
This PR adds default parameter estimations to the F(q) tab. It also adds a none entry to the single template function browser to be consistent with the other tabs in the interface which start with 'none' in the function browser.

**To test:**

- Data to test each tab of the Indirect Data Analysis GUI can be found in #26631.
- Open the Indirect Data Analysis GUI
- Go to the F(Q) fitting tab
- Load Data
- Test the plot guess checkbox with each function in the interface, you should get a "good" guess with each function now.
- Lastly, check that the function browser behaves as expected. E.g switch between the template and full function view using the checkbox.

This PR is part of the IDA minor fixes epic #28484.

----------------------------
#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by alicerussell1 — COMMENTED** [review]
This works well, just one question. I have noticed there is no estimate for the EISF functions when you have multiple inputs  - is this deliberate or have they been forgotten?

**Comment by SpencerHowells** [comment]
@alicerussell1 @StephenSmith25 I haven’t worked it out yet - I forgot!

**Comment by SpencerHowells** [comment]
@StephenSmith25 @alicerussell1 I've had a look at the functions. They are too complicated to give an easy estimate. The only parameter would be Amplitude = y(0) which is hardly worth the effort!

**Comment by alicerussell1** [comment]
Okay, we'll just leave those ones then, I just wanted to make sure they were considered.

**Review by alicerussell1 — APPROVED** [review]
All looks good to me, produces good estimates for the functions it can 👍

**Comment by gemmaguest** [comment]
Should there be unit tests for these changes?

**Comment by StephenSmith25** [comment]
There are unit tests for the parameter estimation class used in this PR, which I implemented in a separate PR this Sprint. Unfortunately the `SingleTemplate**` classes are not covered by unit tests. Given I’ve only been on Indirect a couple of weeks I ignored this issue (which probably isn’t great), but I feel adding tests to this interface is quite a big task (as there are a fair few areas which are untested), which should probably be prioritised at the start of next release.

**Comment by gemmaguest** [comment]
Ok, yes, it looks like it's a bigger job and out of scope of this PR to add those tests :+1:

**Pull request merged**
