### PR TITLE
Fix Windows Python 3 test failures

### LINKED ISSUE #27744: Python 3: Fix remaining tests under Python 3.7/3.8/matplotlib 3.1
#27742 attempted to turn on Python 3 support by default but shows that tests are currently broken running under Python 3.7 or Python 3.8 and also matplotlib 3.1.

This issues is to fix these tests.

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**
Fixes multiple Python 3 issues on Windows, these primarily come from small incompatible changes as our packages don't quite match Ubuntu's

**To test:**
- Ensure the unit test suite and system tests complete

Fixes #27744 . 

*This does not require release notes* because it is part of an epic moving to Python 3

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
The tests finally passed!

**Review by Harrietbrown — APPROVED** [review]
All the tests are passing, Good job.

**Comment by martyngigg** [comment]
Thanks for looking at this quickly @Harrietbrown.

**Comment by martyngigg** [comment]
@mantidproject/gatekeepers Another Python 3-related set of changes. Could I get these merged and then I can try a test build with Python 3 as the default?

**Comment by Harrietbrown** [comment]
No problem

**Pull request merged**
