### PR TITLE
Initial spectroscopy and muon release notes for v6.8

### PR DESCRIPTION
**Pull request by RichardWaiteSTFC**
**Description of work**

Initial spectroscopy and muon release notes for v6.8

I wasn't sure whether to keep the MSCLICE section, I note that there's a separate `mslice_direct_geometry.rst` that has some content.

**To test:**
(1) Build docs
(2) Check links and formatting in html

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by SilkeSchomann** [comment]
@RichardWaiteSTFC I suggest moving all MSlice release notes from `mslice_direct_geometry.rst` to the MSlice section below the CrystalField section in `direct_geometry.rst`. We use `mslice_direct_geometry.rst` when updating the MSlice SHA as it often includes various MSlice release notes in just one pull request.

**Comment by RichardWaiteSTFC** [comment]
> @RichardWaiteSTFC I suggest moving all MSlice release notes from `mslice_direct_geometry.rst` to the MSlice section below the CrystalField section in `direct_geometry.rst`. We use `mslice_direct_geometry.rst` when updating the MSlice SHA as it often includes various MSlice release notes in just one pull request.

Thanks @SilkeSchomann - I'll move all the notes out of `mslice_direct_geometry.rst` and then do I keep the file as empty or delete it (or it doesn't matter)?

**Comment by SilkeSchomann** [comment]
I think you can just delete it.

**Review by sf1919 — CHANGES_REQUESTED** [review]
Please could we add some links to the Abins and Abins2D algorithms in the release notes for Indirect Geometry?

**Review by sf1919 — APPROVED** [review]
Thanks for making the changes I requested.

I built the documentation and there were no warnings. It looks good (i.e. no formatting issues) and the links all work. Spelling and grammar look good to me too.

Lets get this in :)

**Comment by RichardWaiteSTFC** [comment]
@sf1919 - do you want to get this in before or after #36184?

**Comment by sf1919** [comment]
Before. You will need to do another PR to clean up any release notes that have gone in since you did the main work (plus adding images, writing the intro page etc). May as well get this one in so it's clearer what work is left to do.

**Review by thomashampson — APPROVED** [review]

**Pull request merged**
