### PR TITLE
Fix summation error on instrument view and ALF view

### LINKED ISSUE #34815: InstrumentView ALF runs counts not summed correctly for out of plane angle
**Original reporter:** Russell, and David Voneshen

**Describe the bug**
There is a bug in the InstrumentView and ALFView where the out of place angle plot is not calculated correctly for particular ALF runs.

For ALF83743 the calculate out of plane plot is zeroed all over.
image

For ALF83745 the out of plane plot count intensity is lower than should be expected.
image

**To Reproduce**
Open ALFView and load 83743
Click the Pick tab
Click the 'Select whole tube'
Hover over a tube and look at the plot on the left hand side
Now load 83745 and do the same thing

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR fixes an error where the values in a Y histogram are not being summed correctly because the starting number is 0 as an integer rather than a double.

**To test:**
Select ALF instrument in settings, and turn on data archive.
Open ALFView
Load run 83743
Click on Pick tab.
Select a rectangular region on the InstrumentWidget
The RHS plot should look like this:
image

Fixes #34815

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by SilkeSchomann** [comment]
With a very narrow rectangle I've managed to select 0 tubes:
image

**Comment by SilkeSchomann** [comment]
Any slightly less narrow rectangle results in the expected RHS plot though and at least one selected tube.

**Comment by robertapplin** [comment]
> Any slightly less narrow rectangle results in the expected RHS plot though and at least one selected tube.

Thanks, it should be working now so that any overlapping of a shape with a detector should now select that detector

**Review by SilkeSchomann — APPROVED** [review]
Now it works fine even with a very narrow rectangle :-)

**Review by martyngigg — COMMENTED** [review]
Nice catch. You'd like to think that with static explicit types in C++ that this wouldn't happen are you would at least get a warning!

**Pull request merged**
