### PR TITLE
Require tbb in developer rpm

### PR DESCRIPTION
**Pull request by peterfpeterson**
**To test:**

Build the rpm (or grab it from [copr](https://copr.fedorainfracloud.org/coprs/mantid/mantid/build/437828/)) and install it.

_There is no associated issue_

_Since it is for the developer rpm, it does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by quantumsteve** [comment]
Should tbb also be added to [CPACK_RPM_PACKAGE_REQUIRES](https://github.com/mantidproject/mantid/blob/3e87ea1e17604c38c9751793c0230975adbee250/CMakeLists.txt#L240)

**Comment by peterfpeterson** [comment]
Thats a job for when we actually require it in the build.

**Comment by quantumsteve** [comment]
I think we have a chicken and egg problem. We need the rpm to depend on `tbb` before rebuilding ParaView but the rpm won't actually require `tbb` until after ParaView is rebuilt.

Is having a few nightly builds which depend on tbb but do not use it a big deal?

**Comment by peterfpeterson** [comment]
Not a big deal either way. Do you want it added to this PR?

**Comment by quantumsteve** [comment]
Yes, I think that would make sense.

**Comment by quantumsteve** [comment]
LGTM. If the builds pass, :shipit:

**Pull request merged**
