### PR TITLE
Improve masking behaviour of `Display Mask` in ISIS SANS GUI

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Fixes #20237

This PR ensures that masked workspaces are shown correctly when using the `Display Mask` functionality of the mask tab in the ISIS SANS GUI. Note that this is in the OLD gui

**To test:**

Please find test data here: smb://olympic/babylon5/Scratch/Anton/GUI_TEST

1. Open the ISIS SANS Gui
1. Select `SANS2D` as the instrument
2. For the user file load: USER_SANS2D_154E_2p4_4m_M3_Xpress_8mm_SampleChanger_FRONT.txt
3. For sample scatter select `SANS2D00034484`
4. Press `Load`
5. Go to the mask tab and press `Display Mask`
    * Confirm that the InstrumentView opens and that the masked areas are displayed in a grey color

**Release Notes** 
See [here](https://github.com/mantidproject/mantid/pull/20308/commits/5640e7017990fdc4b611b9486ef65bfb4002c430)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by KarlPalmen — COMMENTED** [review]
In code review I only find removal of old code for displaying mask. I do not find any new code.

**Comment by AntonPiccardoSelg** [comment]
@KarlPalmen Yes that is right. This is one of these cases where removing code, improves the software.

**Comment by KarlPalmen** [comment]
I think the Clang failure is for some code that made onto master without having a Clang patch applied. I encountered this with another issue. It may be better to merge master into the branch, than run the patch.

**Review by KarlPalmen — APPROVED** [review]
Test worked after waiting sometime for it to work. Masked areas shown in grey and the pick miniplot shows no data for these areas. I was also able to add a mask via draw, which hen showed up in grey like the other masking and after applying to data, this new masked  showed no data in the pick miniplot.

**Comment by AntonPiccardoSelg** [comment]
@KarlPalmen Thanks for testing

**Pull request merged**
