### PR TITLE
Add an option in the BASISreduction algorithm to divide the structure factor by vanadium data

### LINKED ISSUE #15495: Add an option in the BASISreduction algorithm to divide the structure factor by vanadium data
Instrument scientist cite as highly desirable an option in the BASISreduction algorithm to divide the structure factor by vanadium data. Two divisions are possible:
1 the division is done on the data collected at each pixel
2 the division is done for each Q-slice, in the structure factor S(Q,E)

### PR DESCRIPTION
**Pull request by jmborr**
Description of work.

**To test:**
- Download [testing_issue_15495.zip](https://github.com/mantidproject/mantid/files/157649/testing_issue_15495.zip), and uncompress.
- Load script BASISReductionOld.py in the Script Window of Mantidplot. Then, "Execute All" to register the old version of BASISReduction algorithm.
- Load script callBASISReduction.py in the Script Window of Mantidplot and follow the instructions. You may have to run BASISReductionOld through the graphical interface of the algorithm, instead of running the corresponding lines in the script.
- Compare BSS_33207_sqw and BSS_33207_sqw_old.
- Compare BSS_33207_divided_sqw versus BSS_33207_divided_sqw_old.
- Verify the documentation, specially section "Vanadium Normalization" and the workflow diagram.

Fixes #15495

[Release notes](/docs/source/release/v3.7.0/indirect_inelastic.rst)

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AndreiSavici** [comment]
You should try this convention for processing multiple files: http://www.mantidproject.org/MultiFileLoading

**Comment by jmborr** [comment]
@AndreiSavici I will show the convention to the BASIS instrument scientists after this ticket is tested, because they are not used to. They may be willing to switch since they are starting to use the Indirect Data Analysis interface, which loads the files according to the convention you pointed out.

By the way, would you test this pull request for me, please? I sent a message to Stuart yesterday but he has not replied.

**Comment by stuartcampbell** [comment]
@jmborr Can you change the convention as @AndreiSavici suggested ?

**Comment by jmborr** [comment]
@stuartcampbell Not before this pull request passes, and then I'll talk to the instrument scientists. I'll argue that it's better to adopt the standard convention, but I'll keep the current convention if that is what the instrument scientsts wish.

**Comment by stuartcampbell** [comment]
@jmborr Sorry I forgot the convention was already in use in this routine, so yes we should change it as an additional change and not part of thus PR.  Have you done any tests for the new functionality ?

**Comment by jmborr** [comment]
@stuartcampbell The tests I've done are the ones I ask the tester to try. The first test asks to reduce a run with the old and with the new algorithm, the reduced workspaces should be the same. The second test is made of two parts: in the first part one uses the old algorithm to separately reduce a sample run and a vanadium run, then divide the sample by the vanadium. In the second part one uses the new algorithm to reduce both the sample and vanadium and carry out the normalization. The output workspaces from the first and second parts should be the same.
Attached file testing_issue_15495.zip contains a python script to carry out these tasks.

**Comment by stuartcampbell** [comment]
@jmborr Can you confirm that the run number at line 50 in your `callBASISReduction.py` script should be 33207 rather than 32264

**Comment by stuartcampbell** [comment]
The tests look ok. :shipit:

**Comment by jmborr** [comment]
@stuartcampbell  Yes! I was fumbling with the script and forgot to correct the changes. 33207 should be at line 50.

**Comment by jmborr** [comment]
:tada: Thanks!

**Pull request merged**
