### PR TITLE
Fix for Mantid freezing when handling Engineering Diffraction

### LINKED ISSUE #20836: Engineering diffraction
Gui freezes Mantid and give useless error dialog

image

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Fixes #20836

The fixes stop the GUI freezing up (However quitting the thread is still taking ages. Maybe somebody should look into this). 

**To test:**

* Open MantidPlot
* Open Interfaces > Diffraction > Engineerig Diffraction
  * Confirm that it does not freeze up Mantid and starts quickly
* Close the interface
  * Confirm that not freeze up Mantid when shutting down
* Close the Mantid
  * Confirm that there are not error messages

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by soininen** [comment]
@AntonPiccardoSelg Mantid sometimes segfaults when opening and closing the Engineering interface. I'm trying to find a way to reproduce the issue reliably.

**Comment by soininen** [comment]
The segfault seems to happen quite often when one
- Opens the Engineering Diffraction interface
- Changes the values of *Calibration sample #* on the 'Calibration' tab
- Closes the interface

Here is [backtrace.txt](https://github.com/mantidproject/mantid/files/1362785/backtrace.txt) from my system if it helps.

**Comment by AntonPiccardoSelg** [comment]
This does not have an easy fix. Nick's changes will ensure that the GUI does not freeze on startup. With the current setup it will still freeze when closing the GUI and if there is a file-finding operation in progress.

**Comment by NickDraper** [comment]
Only a partial fix, but it will do for this release

**Pull request merged**
