### PR TITLE
Add tools to overlay peaks on the slice viewer in Workbench

### LINKED ISSUE #27465: Sliceviewer: peaks viewer
The Sliceviewer in MantidPlot allows overlay of a `PeaksWorkspace` onto an MD workspace. It displays a list of peaks and upon selection can draw a marker to show the peak centre and optionally a circle/ellipse to display an intgerated region if applicable.

Screenshot from 2020-01-27 13-18-47

The workbench sliceviewer port needs to have the same functionality. Requirements:
* As a user I wish to take a peaks workspace and "import" it into the sliceviewer. The list of peaks should be displayed with the same information that is in the peaks table when a PeaksWorkspace is viewed standalone.
* The sliced data should display an `X` to display the location of each peak centre.
* The table display should include information about the coordinate system and whether the workspace is integrated or not. In addition there will be controls to
  * remove the peaks workspace overlay and table
  * hide peaks on the display
  * erase a peak by clicking on the peak centre (this should erase the peak from the workspace)
  * add a peak by clicking on the data view
* Once a list of peaks is available, as a user, if I select a particular row of the table then the slice view should snap and zoom to have the peak centre at the centre of the display.
* If a selected peak is integrated then a user should see the shape of the integration region drawn around the centre. The peak centre marker should remain (MantidPlot does not do this currently).
* The viewer should allow multiple peaks workspaces to be overlayed simultaneously.

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Adds button to slice viewer in Workbench to allow peaks to be overlayed on top of the main data workspace.

**To test:**
Use the following script to create some peaks workspaces. The SXD data is in the [training data](http://sourceforge.net/projects/mantid/files/Sample%20Data/TrainingCourseData.zip/download) on the download page.

```python
SXD23767 = Load(Filename='SXD23767.raw', LoadMonitors='Exclude')
    mdws = ConvertToMD(
        InputWorkspace=SXD23767,
        QDimensions="Q3D",
        dEAnalysisMode="Elastic",
        QConversionScales="Q in A^-1",
        LorentzCorrection='1',
        MinValues=[-15, -15, -15],
        MaxValues=[15, 15, 15],
        SplitInto='2',
        SplitThreshold='50',
        MaxRecursionDepth='14')
    peaksws = Load('peaks_qLab.nxs')
   # no shapes
    IntegratePeaksMD(
        InputWorkspace=mdws,
        PeaksWorkspace=peaksws,
        PeakRadius=0.5,
        OutputWorkspace='peaksws_sphere_nobkgd')
    # spheres
    IntegratePeaksMD(
        InputWorkspace=mdws,
        PeaksWorkspace=peaksws,
        PeakRadius=0.5,
        BackgroundInnerRadius=1.1,
        BackgroundOuterRadius=1.4,
        OutputWorkspace='peaksws_sphere_withbkgd')

  # ellipses
  FindUBUsingFFT(PeaksWorkspace=peaksws, MinD=0.8, MaxD=10)
    IndexPeaks(PeaksWorkspace=peaksws, Tolerance=0.1)
    IntegrateEllipsoids(
        InputWorkspace=SXD23767,
        PeaksWorkspace='peaksws',
        SpecifySize=True,
        RegionRadius=2.8,
        PeakSize=0.25,
        BackgroundInnerSize=2.5,
        BackgroundOuterSize=2.75,
        OutputWorkspace='peaksws_ellipse_with_bkgd')
```
Open the slice viewer on the MD workspace. Click the button with circles in it and select a workspace. Move the slider around the see the peaks appear. Click on a peak in the table to "zoom" to it.

Fixes #27465 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
splitter between sliceviewer and the peaks list is invisible (at least on windows)
image

**Comment by NickDraper** [comment]
Clicking cancel on the peak list selection dialog also clear any already selected and shown lists.

1. Show a peaks list
1. Click the icon again to show the dialog
1. it will correctly have the right peaks list ticked.
1. click cancel
1. The existing peaks list is removed, I don't think it should be

**Comment by NickDraper** [comment]
Not sure if this is worth fixing as the work around is obvious, but mentioning it anyway.

If you click on a peak, then using the sliders navigate away from that peak and lose it.
So you click on the peak again, nothing happens and you have not changed the selected peak.

Clicking on another peak and then back to the one you really wanted works fine.

**Comment by NickDraper** [comment]
What should multiple selection do?
image

**Comment by NickDraper** [comment]
Might be a separate issue:
The lineplots are not showing what I'd expect:  I've drawn on where the cursor was pointing.
image
There is no peaks in the data appear to be offset from the screen image

**Comment by NickDraper** [comment]
clicking at the top left of the table select the whole table, not too useful really

**Comment by NickDraper** [comment]
Again not too sure of what we want here:
Clicking home moves off the peak, but the peak remains selected, should we deselect it as you are no longer looking at the peak?  I think as long as we sort out that clicking on the peak again will take us back that will do.

**Comment by NickDraper** [comment]
Minor differences:
1. In mantidplot the first column was Run, not RunNumber, this might be worth changing as it takes up less space.
1. Clicking on the column names sorts them in mantidplot (perhaps a future issue?)

**Comment by NickDraper** [comment]
Multiple peaks lists all plot with the same colours
image

**Comment by NickDraper** [comment]
Is the zoom extent for peaks with background correct?
image

sliceviewer from mantidplot

**Comment by NickDraper** [comment]
Zooming in on the same peak does not appear to have plotted the ellipse the same
image
image

**Comment by NickDraper** [comment]
Pressing ctrl+c leads to a crash
image

**Review by NickDraper — CHANGES_REQUESTED** [review]
See my collection of comments

**Comment by martyngigg** [comment]
@NickDraper Thanks for reviewing this initially.

I think I have addressed all of the comments:

> splitter between sliceviewer and the peaks list is invisible (at least on windows)
> ...
> It is about on the dodgy red hand drawn line.

I don't think we can do much about this easily - it was the same on MantidPlot for me. We can open an issue in the future if it's still an issue for users.  

> Clicking cancel on the peak list selection dialog also clear any already selected and shown lists.
> 
>     1. Show a peaks list
> 
>     2. Click the icon again to show the dialog
> 
>     3. it will correctly have the right peaks list ticked.
> 
>     4. click cancel
> 
>     5. The existing peaks list is removed, I don't think it should be

Fixed.

> Not sure if this is worth fixing as the work around is obvious, but mentioning it anyway.
> 
> If you click on a peak, then using the sliders navigate away from that peak and lose it.
> So you click on the peak again, nothing happens and you have not changed the selected peak.
> 
> Clicking on another peak and then back to the one you really wanted works fine.
> 
> Mantidplot did this as well.

I've improved this here and clicking on an already selected peak brings you back to it.


> What should multiple selection do? - I'm not too sure myself (perhaps we could/should disable it?)
> ...
> I think at the moment it only shows the first selected peak
> It is disabled in Mantidplot

This was a bug and now multiple selection is disabled in workbench too.

> Might be a separate issue:
> The lineplots are not showing what I'd expect: I've drawn on where the cursor was pointing.
> ...
> The peaks in the data appear to be offset from the screen image

I've created #28579 to look into this.


> Minor differences:
> 
>     1. In mantidplot the first column was Run, not RunNumber, this might be worth changing as it takes up less space.
> 
>     2. Clicking on the column names sorts them in mantidplot (perhaps a future issue?)

I've reused the standard table used to display the peaks so I'd prefer to keep the naming consistent and let's see if sorting in this view is required but it can be added.


> Multiple peaks lists all plot with the same colours

This should be fixed and the workspace title is now styled with the color of the marker.

> Is the zoom extent for peaks with background correct?
> ...

The plotting of the ellipsoids was total rubbish after I rechecked it where I'd misunderstood something. This should be fixed now.


> Pressing ctrl+c leads to a crash
>...

This is now fixed.

**Comment by martyngigg** [comment]
I've also created a testing IDAaaS instance for Pascal to play with. It might be worth addressing any comments he has in future pull requests though as this is quite large given it's the first implementation of it.

**Review by NickDraper — APPROVED** [review]
All the items, I raised, that need fixing, work well now, the ellipse orientation and extents are now the same as in mantidplot.

**Pull request merged**
