### PR TITLE
New CNCS geometry. Refs #11001

### PR DESCRIPTION
**Pull request by AndreiSavici**
This is the new geometry for CNCS. The branch in mantidgeometry was merged already

### CODE REVIEW

**Comment by NickDraper** [comment]
The test failure appears unrelated.

Jenkins, test this please.

**Comment by NickDraper** [comment]
Jenkins wake up and test this please

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by NickDraper** [comment]
I was initially slightly confused that this covered changes to CNCS_definition.xlm as well as a new file, but I understand now, CNCS_definition has been edited to be the "new" file, and the new file is the old definition.

**Pull request merged**
