### PR TITLE
Reorganise Qt cmake code

### LINKED ISSUE #20288: Create CMake function to add qt-based targets
In order to develop the workbench in parallel with the existing MantidPlot code we need to build all widget code against both Qt4 and Qt5.

To minimise the duplication of cmake code we need to create helper functions to add these targets.

A [prototype](https://github.com/martyngigg/sandbox/blob/master/python/matplotlib/cppwidget/cmake/QtTargetFunctions.cmake) has been created to test this out.

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work**

Adds CMake functions to create targets for Qt-based libraries so that a single set of sources can produce targets for both Qt4/Qt5. Updates the widgets/common library to compile against Qt5.

It also introduces an new library, `LegacyQwt`, that contains code from common widgets that depends
on Qwt5 to isolate these dependencies.

All other targets currently build against Qt4 alone.

Note that the plugins have been reorganised in both the build and packages to ensure separation of versions compiled against Qt4 & Qt5. The Qt widget/interfaces plugins are now in the `plugins/qtX` where X is the major version of Qt. The ParaView plugins, filters, sources etc are now located in the `plugins/paraview` directory and the VSI widgets/views have been moved to `plugins/qtX`. This removes the need for the separate `pvplugins` directory and tidies up the packaging. 

**Packages for Qt4 need to be tested on all OSs**

**To test:**

Code review and build locally.

To enable Qt5 targets then install Qt5 packages on Linuxes and run `cmake -DENABLE_WORKBENCH=ON .` 

Fixes #20288

**Release Notes** 

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by peterfpeterson — APPROVED** [review]
Nothing looks overly crazy. My favorite part of the PR is that you've relabled the current stuff as "legacy".

**Comment by martyngigg** [comment]
Maybe I should have relabelled everything "Legacy..."? :wink:

**Comment by SimonHeybrock** [comment]
There is a merge conflict now.

**Comment by martyngigg** [comment]
I meant to mark this in progress anyway as Ian found an issue with loading the plugins.

**Review by rosswhitfield — CHANGES_REQUESTED** [review]
When building without Vates I'm getting
```
[1/2] Building CXX object Framework/Kernel/CMakeFiles/Kernel.dir/src/UsageService.cpp.o
FAILED: Framework/Kernel/CMakeFiles/Kernel.dir/src/UsageService.cpp.o 
ccache /usr/bin/c++  -DBOOST_ALL_DYN_LINK -DBOOST_ALL_NO_LIB -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG -DENABLE_OPENCASCADE -DHAVE_STDINT_H -DIN_MANTID_KERNEL -DKernel_EXPORTS -DPSAPI_VERSION=1 -isystem /usr/include/nexus -I../Framework/Types/inc -I../Framework/Kernel/inc -isystem eigen-src -IFramework/Types -fopenmp -O3 -DNDEBUG -fPIC -fvisibility=default   -Wall -Wextra -Wconversion -Winit-self -Wpointer-arith -Wcast-qual -Wcast-align -fno-common -Wno-deprecated -Wno-write-strings -Wno-unused-result -Woverloaded-virtual -fno-operator-names -Wpedantic -Wsuggest-override -Wimplicit-fallthrough=0 -std=gnu++14 -MD -MT Framework/Kernel/CMakeFiles/Kernel.dir/src/UsageService.cpp.o -MF Framework/Kernel/CMakeFiles/Kernel.dir/src/UsageService.cpp.o.d -o Framework/Kernel/CMakeFiles/Kernel.dir/src/UsageService.cpp.o -c ../Framework/Kernel/src/UsageService.cpp
../Framework/Kernel/src/UsageService.cpp: In member function ‘virtual std::__cxx11::string Mantid::Kernel::UsageServiceImpl::generateStartupMessage()’:
../Framework/Kernel/src/UsageService.cpp:219:7: error: ‘MAKE_VATES’ was not declared in this scope
   if (MAKE_VATES) {
       ^~~~~~~~~~
```
It works with Vates.

**Comment by martyngigg** [comment]
Thanks, @rosswhitfield. It should be fixed now.

**Review by rosswhitfield — APPROVED** [review]

**Comment by samueljackson92** [comment]
Tested this on OSX. It built fine but when I start up Mantid I get the following:
```
Could not open library /Applications/MantidPlot.app/plugins/qt4//libMantidScientificInterfacesEnggDiffractionQt4.dylib: dlopen(/Applications/MantidPlot.app/plugins/qt4//libMantidScientificInterfacesEnggDiffractionQt4.dylib, 10): Library not loaded: @rpath/libMantidScientificInterfacesMuonQt4.dylib
  Referenced from: /Applications/MantidPlot.app/plugins/qt4//libMantidScientificInterfacesEnggDiffractionQt4.dylib
  Reason: image not found
Could not open library /Applications/MantidPlot.app/plugins/qt4//libMantidScientificInterfacesISISSANSQt4.dylib: dlopen(/Applications/MantidPlot.app/plugins/qt4//libMantidScientificInterfacesISISSANSQt4.dylib, 10): Library not loaded: @rpath/libMantidScientificInterfacesMuonQt4.dylib
  Referenced from: /Applications/MantidPlot.app/plugins/qt4//libMantidScientificInterfacesISISSANSQt4.dylib
  Reason: image not found
```

**Review by samueljackson92 — CHANGES_REQUESTED** [review]
Tested this on OSX. It built fine but when I start up Mantid I get the following:
```
Could not open library /Applications/MantidPlot.app/plugins/qt4//libMantidScientificInterfacesEnggDiffractionQt4.dylib: dlopen(/Applications/MantidPlot.app/plugins/qt4//libMantidScientificInterfacesEnggDiffractionQt4.dylib, 10): Library not loaded: @rpath/libMantidScientificInterfacesMuonQt4.dylib
  Referenced from: /Applications/MantidPlot.app/plugins/qt4//libMantidScientificInterfacesEnggDiffractionQt4.dylib
  Reason: image not found
Could not open library /Applications/MantidPlot.app/plugins/qt4//libMantidScientificInterfacesISISSANSQt4.dylib: dlopen(/Applications/MantidPlot.app/plugins/qt4//libMantidScientificInterfacesISISSANSQt4.dylib, 10): Library not loaded: @rpath/libMantidScientificInterfacesMuonQt4.dylib
  Referenced from: /Applications/MantidPlot.app/plugins/qt4//libMantidScientificInterfacesISISSANSQt4.dylib
  Reason: image not found
```

**Comment by peterfpeterson** [comment]
I wonder if @samueljackson92 issues are related to @yxqd issues in https://github.com/mantidproject/mantid/pull/21068. He fixed part of it by moving things to use `Poco::Path` for putting together directory names.

**Comment by martyngigg** [comment]
@samueljackson92 Thanks for testing that - there were a couple of RPATH references I hadn't updated. Hopefully this should work now. Could you retest?

**Comment by samueljackson92** [comment]
@martyngigg Of course.

**Comment by martyngigg** [comment]
@samueljackson92 I think we addressed all of the OSX issues, right? If so could you mark this as approved?

**Review by samueljackson92 — APPROVED** [review]

**Comment by martyngigg** [comment]
It's passed :tada:

**Comment by martyngigg** [comment]
@mantidproject/gatekeepers I'd appreciate this one getting through quickly as it impacts a lot of files.

**Pull request merged**
