### PR TITLE
Fix system test reference data

### LINKED ISSUE #24364: SANSILLReductionTest build failures
Investigate spurious failing SystemTests.SANSILLReductionTest.ILL_D22_Test

For example:

http://builds.mantidproject.org/job/pull_requests-rhel7/25761/

http://builds.mantidproject.org/job/pull_requests-rhel7/25713/

### PR DESCRIPTION
**Pull request by vreimund**
**Description of work.**

Fix system test which always seems to fail on Ubuntu (consecutive execution) by updating ~~its reference data~~ Parameter files.
~~I do wonder why it does not fail much on the RHEL build server.~~
Different build servers have different versions of muParser installed which has different meaning of `log`.

Sorry for uploading a Nexus file first.

**To test:**

Make sure the system test passes on your system.

Fixes #24364.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by reimundILL** [comment]
The RHEL workspaces obtained from two different PRs (this one and one reported in the issue description) did not match! This explains the spurious failing but raises new questions.

On my machine (clean build, cleared cache) it works just fine.

**Comment by martyngigg** [comment]
The Windows failure here is fixed in #24365

**Review by martyngigg — APPROVED** [review]
This looks good to me now. It passed on my Ubuntu build and in my CentOS 7 docker container consistently.

**Comment by martyngigg** [comment]
@mantidproject/gatekeepers LGTM The only changes are system test related and OSX doesn't run those. It fixes the long running ILL D22 failure stopping nightly build deployment.

**Pull request merged**
