### PR TITLE
Fix theta value in POLREF GUI

### LINKED ISSUE #17657: POLREF GUI: update theta value after reduction
When the reduction is finished, the table should be populated with the correct theta value.

### PR DESCRIPTION
**Pull request by raquelalvarezbanos**
**To test:**

Open "Interfaces" > "Reflectometry" > "ISIS Reflectometry (Polref)". Populate the table like this (you'll have to add a new row using the fifth icon above the table):

polref

Select the first row and hit "Process". Column "Angle" should be populated with ~ 0.70. Select the second row and hit "Process". Value in column "Angle" should not change.

Fixes #17657.

I don't think this needs to be in the release notes, it was reported by Jos during beta testing.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
First theta value changes to 1.419
Second does not change

**Comment by NickDraper** [comment]
Code changes are simple and small, very low risk

:shipit:

**Comment by raquelalvarezbanos** [comment]
Thanks, Nick. I've just checked and there's a factor of 2 missing. I'll correct that.

**Comment by NickDraper** [comment]
Existing issue is fixed, the change is very minor and safe there is no need to wait for the build servers.

:shipit:

Unrelated issue found in testing, raised for the next release #17690

**Pull request merged**
