### PR TITLE
Use RunWidget in Indirect Tools interface

### PR DESCRIPTION
**Pull request by robertapplin**
### Description of work
This PR ensures the new RunWidget is used in the Indirect Tools interface.

Part of #37381

### To test:
1. `Interfaces`->`Indirect`->`Tools`->`Transmission` tab
2. Chemical Formula: `H2-O`
3. Mass density: 1.0
4. Click `Run`. There should be no errors. While running the Run button should be disabled. When finished it should be re-enabled
5. Clear chemical formula and click Run. A validation message should appear.

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by sf1919** [comment]
When undertaking Step 4 I got an error message. I thought this was because I didn't have a facility and instrument selected. Even doing that though didn't stop the warning because apparently the Cheimical Formula for Sample was not recognised.

Is there a setup step missing in the test?

**Comment by SpencerHowells** [comment]
@sf1919 @robertapplin Where is the message from? The Formula alg also does the check.

**Comment by robertapplin** [comment]
> When undertaking Step 4 I got an error message. I thought this was because I didn't have a facility and instrument selected. Even doing that though didn't stop the warning because apparently the Cheimical Formula for Sample was not recognised.
> 
> Is there a setup step missing in the test?

Hmm that is strange, just to check did you use a numeric zero in `H2-0` or did you use the letter O like `H2-O`? I think it will only work for the letter O

**Comment by sf1919** [comment]
Yes thats exactly what I must have done! Thanks @robertapplin . Functional testing completed so I will move onto code review

**Review by sf1919 — APPROVED** [review]
I have undertaken a functional test of this PR. I can confirm that when the Chemical is set correctly it does run and when it doesn't you get the relevant warning. You also get a warning when no chemical has been set.

The run button is greyed out during the run too.

Reviewing the code and doing a functional test in v6.10 for comparison I can confirm that there is no loss of functionality. I would argue the validation warnings are clearer now with the yellow triangle symbol.

The code looks clean and unused variables etc have been removed.

This looks good to me so I am approving.

**Pull request merged**
