### PR TITLE
Fix bug with tiled plots

### LINKED ISSUE #18199: Serialise tiled plots to project files properly
This is a sub issue of #15602.

This appears to be a bug that has crept in for tiled plots.

### PR DESCRIPTION
**Pull request by samueljackson92**
Tiled plots do not have the correct size when reloaded. 

**To test:**
  - Create a tiled plot by right clicking on a workspace, selecting some spectra and choosing "tile plot"
 - Save and reload the project
 - Tile plot should be shown correctly now

Fixes #18199 .

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
Even works with project saved before fix. :shipit:

**Comment by samueljackson92** [comment]
@KarlPalmen Could also check saving & reloading a single plot? Just to check that is unchanged?

**Comment by KarlPalmen** [comment]
Yes it works with simple 1-D plot and waterfall plot.

**Comment by SimonHeybrock** [comment]
@samueljackson92 This branch has developed a merge conflict.

**Pull request merged**
