### PR TITLE
Pull in the system test code and tests

### PR DESCRIPTION
**Pull request by martyngigg**
Fixes trac issue [#10870](http://trac.mantidproject.org/mantid/ticket/10870)

**Tester**
There are a large number of files changed but the majority of them are simply moves from putting the old `Test/PerformanceTests` & `Code/Mantid/TestingTools` under the new `Code/Mantid/Testing` directory rather than having lots of different directories with test things under them.

The build scripts have been updated to that `rhel6` pull-requests builds the system tests & `Windows` runs the doc tests.

### CODE REVIEW

**Comment by martyngigg** [comment]
Jenkins, retest this please.

**Comment by martyngigg** [comment]
Jenkins, retest this please

**Comment by martyngigg** [comment]
Jenkins, retest this please.

**Comment by martyngigg** [comment]
@peterfpeterson @rosswhitfield @sic @OwenArnold @Anders-Markvardsen - I wouldn't mind a few eyes on this one.

My intention here was to get the scripts in order to run the system tests and doctests on the pull request. For sake of ease in testing I have added a single system test: `HRPD` as it hasn't changed in a long time. I would like to push this through and verify everything is working before pulling in everything (which should be much simpler). Let me know what you think.

**Comment by martyngigg** [comment]
Jenkins, retest this please.

**Comment by rosswhitfield** [comment]
:sparkles: From what I can make of all the changes and what I tested it looks good. :+1:

**Comment by peterfpeterson** [comment]
It works, but there is a fair amount of gymnastics to actually run the system tests as a normal developer. There should be a follow on bit of work to copy a templated version of `runSystemTests.py` into the `CMAKE_BINARY_DIR` which would also eliminate some of the command line arguments.

**Comment by martyngigg** [comment]
I agree but it felt like this would turn into a never ending list of improvements so I stopped at porting what we currently have.

**Comment by peterfpeterson** [comment]
Can we have couple more up-votes from @sic @OwenArnold @Anders-Markvardsen so this can be merged?

**Comment by martyngigg** [comment]
Any comments @sic @OwenArnold @Anders-Markvardsen?

**Comment by peterfpeterson** [comment]
@martyngigg there is a small merge conflict in the main build script.

**Comment by martyngigg** [comment]
Thanks @peterfpeterson. I'll take a look what has happened

**Comment by martyngigg** [comment]
Jenkins,  retest this please.

**Comment by martyngigg** [comment]
Jenkins, retest this please.

**Comment by OwenArnold** [comment]
Jenkins retest this please

**Comment by OwenArnold** [comment]
Worked as expected. Looks ready to go pending the update to the ORNL build servers.

**Pull request merged**
