### PR TITLE
Fix "plot guess" leaving old guesses on plot

### LINKED ISSUE #18060: "Plot guess" leaves stale curves on graph
#### Expected behaviour
*Plot guess* should only have one guess curve, which corresponds to the function and parameters currently set, and updates itself automatically when parameters are changed.

#### Actual behaviour
Stale plot guesses can get left on the graph.

#### Steps to reproduce the behaviour
- Open *Interfaces/Muon/Muon Analysis*. Ensure the multi fitting mode is enabled, i.e. "compatibility mode" is *not* on.
- Load a dataset, go to Data Analysis tab and set up a function
- *Display/Plot guess*: a guess curve is plotted
guess1

- Change one of the fit parameters - nothing happens. 
- *Display/Remove guess*: instead of removing the first guess, a second guess is plotted on top
guess2

- *Display/Remove guess* (again) - the second guess is removed, but there is no way of removing the first one - it's stuck there now.

The same happens if you "plot guess", fit the data and then select "Remove guess" - it plots a second guess instead of removing the first, and it is not possible to remove the first, stale guess.

Note that the problem only appears with the new fitting UI. "Plot guess" works fine in compatibility mode (multi fitting off).

(See also #15872, which was a similar problem.)

#### Reported by
James Lord, Mantid 3.8, Windows

### PR DESCRIPTION
**Pull request by tom-perkins**
Fixed the *Plot guess* functionality in MuonAnalysis. This should work the same as it did with the old fitting UI: there should be only one guess curve, which auto-updates when the function or parameters are changed. "Remove guess" should do what it says and not plot another guess.

When multi fit mode (the new fitting UI) is on, need to remove any plotted guess before updating the function in the model, then plot it again if necessary. This is because the `PropertyHandler` that knows whether a guess is plotted is held by the `CompositeFunction` that is being replaced.

Unit tests added to cover new function.

**To test:**

- Open *Interfaces/Muon/Muon Analysis* and, on the Settings tab, tick "enable multiple fitting".
- Load some data on the Home tab, for example `MUSR00015190.nxs` (unit test data).
- Go to Data Analysis tab and set a fit function in the function browser at the top. Click *Display/Plot guess*.
- Edit one of the parameters of the function and verify the guess curve updates automatically.
- Click *Display/Remove guess* and verify the guess is removed.
- Plot the guess again, then run the fit and remove the guess. This should work OK and not plot a second guess when you try to remove it.

Turn off "enable multiple fitting", then close and reopen MuonAnalysis and follow the same steps. "Plot guess" should work here too (no change from before).

Fixes #18060.

[Release notes](https://github.com/mantidproject/mantid/blob/5fe0bc7b2b4c1d9287a537a18ab3303bab353bd6/docs/source/release/v3.9.0/muon.rst#id1) have been updated.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
When testing, I found after fitting, if I remove the guess and then put it back, it appears in a new colour. This applies regardless of whether multiple fitting is enabled. Is this behaviour OK?

**Comment by KarlPalmen** [comment]
Besides the guess colour issue. It works well :shipit:

**Comment by tom-perkins** [comment]
Regarding the guess colour issue: I tried this in Mantid 3.7.2 and it was the same, so I think this is OK as it matches the old behaviour.

**Comment by martyngigg** [comment]
@tom-perkins Could you merge master in here? The docs have a conflict in them now. Otherwise this looks good.

**Pull request merged**
