### PR TITLE
Fix problem with beam arrow not showing when sample shape loaded from file

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

Modify check on whether source and sample present before beam arrow is plotted

Previous check involved casting source and sample to boolean. If either object implemented `__len__` then (as is case for ICompAssembly) then there was a chance a valid source or sample ptr could evaluate the false if `__len__`=0

I noticed this while loading a workspace containing a sample shape from a .nxs file that I'd created using the SaveNexusESS algorithm. I use this save algorithm because it saves the instrument geometry inside the .nxs file without requiring an IDF file and that's useful when the instrument geometry has been created using a the WorkspaceCreationHelper class.

I think the source and sample in a workspace that are loaded from an ESS .nxs file are of type ICompAssembly due to the code in InstrumentBuilder::addComponent. For most sources\samples this won't have any children meaning `__len__` is zero. It's not very clear to me why InstrumentBuilder chooses to use the ICompAssembly class for things like source\sample but since the shape plotting can be made to work using this fix I've not investigated changing InstrumentBuilder.

**To test:**

1) Run the lines up to and including call to SetSample in the following script
2) Right click on ws and select show sample
3) Observe beam arrow present
4) Run remaining lines that save ws to a file and reload it
5) Right click on ws and select show sample
6) Observe beam arrow still present

```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d.art3d import Poly3DCollection

cuboid = " \
<cuboid id='some-cuboid'> \
<height val='2.0'  /> \
<width val='2.0' />  \
<depth  val='0.2' />  \
<centre x='10.0' y='10.0' z='10.0'  />  \
</cuboid>  \
<algebra val='some-cuboid' /> \
"

ws = CreateSampleWorkspace()
SetGoniometer(ws, Axis0="45,0,1,0,-1")
SetSample(ws, Geometry={'Shape': 'CSG', 'Value': cuboid})

SaveNexusESS(ws,'test_ws.nxs')
mtd.clear()
ws = LoadNexus('test_ws.nxs')
```

*There is no associated issue.*

*This does not require release notes* because **problem relates to show sample shape functionality added during this release**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DannyHindson** [comment]
@DanielMurphy22 - this is the fix I mentioned on the standup earlier with a test script to show when it happens

**Comment by DannyHindson** [comment]
Maybe I should I add a test for this. I'll try and do this later on

**Comment by DannyHindson** [comment]
I've added a unit test. While doing this I noticed that the problem only occurs if the .nxs file was created using SaveNexusESS rather than SaveNexus. So not perhaps as general as I first thought. 

When you simply do SaveNexus on a test workspace created using CreateSampleWorkspace or similar you don't get an instrument saved in the .nxs - so no source or sample are saved. In this case it's correct that you don't show a beam arrow. I've updated the test script to use SaveNexusESS now instead.

**Review by DanielMurphy22 — APPROVED** [review]
Great to have the fix and test even if it is a less common problem than thought. Makes the code more stable! Good job! Very clear test instructions!

**Pull request merged**
