### PR TITLE
Updated Elwin header file to fix crash

### LINKED ISSUE #32545: Main Elwin File input crashes
**Describe the bug**
Attempting to load a file using the initial file input load in Elwin crashes Mantid.

**To Reproduce**
1. Open Indirect->Data Analysis GUI
2. Click Browse button
3. Attempt to load ```irs26173_graphite002_red.nxs``` from the Usage Examples (can be downloaded from https://download.mantidproject.org/)
4. Mantid crashes

**Expected behavior**
Following steps 1-3 should not result in a crash

**Platform/Version (please complete the following information):**
Windows 10
Mantid 6.1.20210913.1238

### PR DESCRIPTION
**Pull request by sf1919**
**Description of work.**
Made sure the correct functions were in private slots to prevent a crash. 

**To test:**

To Test Elwin File Input Loader
1. Open ```Indirect->Data Analysis GUI```
2. Click Browse button
3. Load ```irs26173_graphite002_red.nxs``` from the Usage Examples (can be downloaded from https://download.mantidproject.org/)
4. File should successfully load without any error messages or crashes

Test file load
1. Open ```Indirect->Data Analysis GUI```
2. Click Browse button
3. Find a file that does not have a _red or _sqw ending - for example ```EMU00020884.nxs``` from the Training Course data
4. You should receive a pop up explaining that the file is incorrect and why. Close the dialog box and the Input File box should be empty.

Test Add Workspace Dialog
1.  Open ```Indirect->Data Analysis GUI```
2. From the drop down menu choose Workspace
3. Click Add Workspace
4. Click Browse button
5. Find a file that does not have a _red or _sqw ending - for example ```EMU00020884.nxs``` from the Training Course data
6. Tick All Spectra and click Add.
7.  You should receive a pop up explaining that the file is incorrect and why. The Add Workspace Dialog box closes.

Fixes #32545

*This does not require release notes* because **it fixes a bug introduced during release work.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by Harrietbrown — APPROVED** [review]
This fixes the loading file crash. Good job.

**Comment by martyngigg** [comment]
Great stuff that we caught this before release.

Out of curiousity, could you help me understand how the access status caused a crash? My naive first thought was that the compiler would say when the member functions have the wrong access specifier but I must be missing something...

**Comment by sf1919** [comment]
Not entirely sure myself if I'm honest but when I made changes in a previous PR I moved ```void checkNewPreviewSelected(int index);``` from the private slots part of the header to private instead of the other method I should have moved. By doing this it seems to have prevented this following line from running
```connect(m_uiForm.cbPreviewFile, SIGNAL(currentIndexChanged(int)), this, SLOT(checkNewPreviewSelected(int)));``` in the cpp file. Given they were both private perhaps thats why it didn't pick it up?

**Comment by martyngigg** [comment]
Ah I see - I'm guessing there was a warning in the terminal saying something like "no such slot..." but those warnings are lost really easily and may even be hidden on Windows...

The problem is with the macro-style forms of `connect`. The `SLOT` macro cannot check if the method has been declared as a slot in the header so has to leave it to runtime to see if one exists in the code generated by `Q_OBJECT` but it just warns and nothing else. I guess it then entirely depends on the code as to whether it is important that this function runs.
I wonder if we can divert these warnings somewhere more helpful... 🤔

**Pull request merged**
