### PR TITLE
Robustness improvements to Python fit functions

### LINKED ISSUE #7914: Python peak functions: Remove restriction that they require a deriviative.
This issue was originally [TRAC 7068](http://trac.mantidproject.org/mantid/ticket/7068)

Issue details are blank in trac

### LINKED ISSUE #16841: Missing function1D attribute on Python functions causes crash
### Expected behavior

Running this code with a lower case 'd' in "function1D" causes crash on fit

``` python
import numpy

class Lorentz(IFunction1D):

    def init(self):
        self.declareParameter("Amplitude", 0.0) #Amplitude
        self.declareParameter("Gamma", 0.0) #Full width at half height
        self.declareParameter("PeakCentre", 0.0) #Peak centre

    def function1d(self, xvals):

        return xvals

FunctionFactory.subscribe(Lorentz)
```
### Actual behavior

On fitting this code causes Mantid to crash
### Steps to reproduce the behavior

Open training course data file 11001_deltaE
Plot spectrum
Add other function "Lorenz"
Start fitting
### Platforms affected

Tested on Windows, most likely affects all platforms

### LINKED ISSUE #22331: Crash when attempting to create vanilla custom fit function
Using Mantid 3.12.1 and the script window within MantidPlot.

When created the custom fit function from the page https://www.mantidproject.org/Python_1D_Functions : 

```
from mantid.api import *
import numpy

class Example1DFunction(IFunction1D):

    def init(self):
        self.declareParameter("C", 0.0)

    def function1D(self, xvals):
        # Access current values during the fit
        c = self.getParameterValue("C")

        return c*numpy.sqrt(xvals)

FunctionFactory.subscribe(Example1DFunction)
```

This works fine.

But when using the example from https://www.mantidproject.org/Introduction_to_Python_Fit_Functions#Function_Types : 

```
from mantid.api import *
import numpy as np

# You choose which type you would like by picking the super class
class Example1DFunction(IFunction1D): # or IPeakFunction

    def category(self):
        return 'Examples'

   # explained later

# Register with Mantid
FunctionFactory.subscribe(Example1DFunction)
```

Mantid crashes. 

Furthermore when running 

```
from mantid.api import *
import numpy as np

# You choose which type you would like by picking the super class
class ExampleFunction(IFunction1D): # or IPeakFunction

    def category(self):
        return 'Examples'

   # explained later

# Register with Mantid
FunctionFactory.subscribe(Example1DFunction)
```

Mantid returns the unhelpful error message:

```
RuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.
  at line 13 in 'New script'
  caused by line 1272 in 'C:\MantidInstall\bin\mantid\simpleapi.py'
```

In this issue please

* Fix Mantid so that it does not crash when the middle script is run 
* provide a more meaningful error message when the last script is run

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work**

This work fixes issues where users could supply incorrect Python function class definitions and mantid would crash rather than checking and throwing an appropriate error.

**To test:**

* Try out the instructions in the issue
* Try out variations of `function1D`, i.e. wrong return type, misspelled to try and get it to crash. 
* Try the example solutions from the [advanced training course](https://www.mantidproject.org/Extending_Mantid_With_Python:_Exercise_6_Solution) with and without the derivatives. The peak function types without a derivative should now work also. 

Fixes #22331, fixes #16841. fixes #7914

*Release notes have been added.* 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Anders-Markvardsen** [comment]
Tried all examples listed above + a number of addition ones. No crashes observed and nice output when doing something you shouldn't except for the following case where try to subscribe a build in function by accident that you haven't ready redefined:

For example:

```
FunctionFactory.subscribe(Example1DFunction)
```

which returns:

```
RuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.
  at line 14 in 'C:/Midlertiddig/mantidBuild1/MantidPlot/lll.py'
  caused by line 1272 in 'C:\Midlertiddig\mantidBuild1\bin\Release\mantid\simpleapi.py'
```

Could this case be handled also?

Note where you first redefine an existing function this works fine. For example:

```
class Example1DFunction(IFunction1D):

    def init(self):
        self.declareParameter("C", 0.0)

    def function1D(self, xvals):
        # Access current values during the fit
        c = self.getParameterValue("C")

        return c*numpy.sqrt(xvals)

FunctionFactory.subscribe(Example1DFunction)
```

**Comment by Anders-Markvardsen** [comment]
Separately, as discuss with Martyn, the suggested GitHub command line instructions does not work well. 

If you do:

```
git checkout -b martyngigg-22331_python_fitfunction_crash master
git pull https://github.com/martyngigg/mantid.git 22331_python_fitfunction_crash
```
This firstly requires you to do a merge commit and change the commit message to include the re #xxx which is irritating. In addition, if you follow the instructions above and push back a change this will push it to martyngigg-22331_python_fitfunction_crash and will not kick off the build servers. When I tried to commit to https://github.com/martyngigg/mantid.git 22331_python_fitfunction_crash it doesn't just work as is. In summary this Git workflow is painful to work with as is

**Review by mantid-roman — APPROVED** [review]
It works as expected

**Comment by martyngigg** [comment]
Thanks for looking over this. I'm just attempting to address Anders' final comment regarding subscribing incorrect python types

**Comment by Anders-Markvardsen** [comment]
When 

```
FunctionFactory.subscribe(Gaussian)
```

Get the accurate error message: 

```
ValueError: subscribe(): Unexpected type. Expected a class derived from IFunction1D or IPeakFunction, found: function
``` 

Initial my reaction was this comment was too developer focussed, but thinking out it I like it because it highly the technical requirement for registering a fit function.

Executed 4 different scripts tested various aspect and they all passed

**Review by Anders-Markvardsen — APPROVED** [review]
Pass functional tests. Code nice coverage of test and comments plus thanks for code cleanups

**Pull request merged**
