### PR TITLE
Fix exception on ISIS Energy Transfer > Plot Time

### PR DESCRIPTION
**Pull request by DanNixon**
Fixes [#11394](http://trac.mantidproject.org/mantid/ticket/11394).

To test:
1. Open Indirect Data Reduction > ISIS Energy Transfer
2. Select OSIRIS
3. Load a run
4. Click Plot Time
5. Change the spectra range
6. Click Plot Time
7. Repeat 5 to 6 until you are happy it works

### CODE REVIEW

**Comment by DanNixon** [comment]
Jenkins, retest this please.

**Comment by DanNixon** [comment]
Jenkins, retest this please.

**Comment by KarlPalmen** [comment]
It does not work for me. I get exception when I try it on Windows 7. Test failed.

**Comment by DanNixon** [comment]
Jenkins, retest this please.

**Comment by KarlPalmen** [comment]
I still get a type exception for the minimum spectrum.

**Comment by DanNixon** [comment]
Jenkins, retest this please.

**Comment by KarlPalmen** [comment]
The test makes more progress but fails having successfully run several child algorithms. It fails with a type error when it loads again.

The error shown to the results log is:
InelasticIndirectReduction successful, Duration 2.30 seconds
Load started
Cannot process ICPevent log. Period 1 assumed for all data.
Load successful, Duration 2.59 seconds
Algorithm property given value of incorrect type.
Stopping queue execution.
Got error from algorithm "GroupDetectors"
Stopping batch algorithm because of execution error

**Comment by DanNixon** [comment]
@KarlPalmen Actually now that you mention ```GroupDetectors``` I have noticed another issue with the routine that needs to be fixed.

**Comment by DanNixon** [comment]
Jenkins, retest this please.

**Comment by DanNixon** [comment]
Jenkins, retest this please.

**Comment by DanNixon** [comment]
Jenkins, retest this please.

**Comment by DanNixon** [comment]
I've given up trying to get the CI to pass on this, over the last 3 retests it has passed on all platforms so should be OK to be tested now.

**Comment by KarlPalmen** [comment]
It works for me (on Windows 7).

**Comment by DanNixon** [comment]
Jenkins, retest this please.

**Comment by KarlPalmen** [comment]
It works again, but I have noticed, that when I plot again and create a new graph in a new window, the previous graphs are updated to look like the new graph. Is this supposed to happen?

**Comment by DanNixon** [comment]
@KarlPalmen That's just an issue with plotting, it happens on quite a few indirect interfaces.
There is an existing [ticket](http://trac.mantidproject.org/mantid/ticket/8236) to fix this.

**Comment by DanNixon** [comment]
I think this should be OK to merge, I have well and truly given up with Jenkins now, everything that needs to have passed has passed (just not at the same time).

**Pull request merged**
