### PR TITLE
Correction for gravity extra length sans

### LINKED ISSUE #15208: Gravity drop Lextra in GravitySANSHelper needs correction
Richard wrote:
> Instead of (L2)^2 we have (Lextra + L2)^2   but we ought to have  ( (Lextra+L2)^2 - (Lextra)^2 )

The L2 correction when gravity is taken into consideration has a small bug. The fix will affect `GravitySANSHelper` which is references in `Q1D2`, `Qxy` and `TOFSANSResolutionByPixel`.

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Fixes #15208 
# For testing:
- Code review should be enough for this issue, as the functionality is covered by the system tests (for which the test data had to be changed). The actual code change would not be visible to the user.
- Confirm in the code that the change is indeed (L+Lextra)^2 - Lextra^2

### CODE REVIEW

**Comment by picatess** [comment]
Spoke to Richard, those are the only changes for this bug fix.

**Comment by matthew-d-jones** [comment]
Calculation is clear, commented and matches the required change.

**Comment by OwenArnold** [comment]
@Anton. I think this should be mentioned in the release notes if not already mentioned.

**Comment by picatess** [comment]
Added to release notes: http://www.mantidproject.org/index.php?title=ReleaseNotes_3_7_SANS&diff=26303&oldid=26237

**Pull request merged**
