### PR TITLE
Improvements to SimulatedDensityOfStates: force constants import

### PR DESCRIPTION
**Pull request by ajjackson**
**Description of work.**
- Implements an alternative file import option to the SimulatedDensityOfStates algorithm, using the Euphonic python package developed as part of the PACE project at ISIS.

  This imports files with "force constants" data, from which frequencies/eigenvectors are computed at arbitrary q-points. This allows the analysis process to be further decoupled from the *ab initio* calculations, and provides access to data computed with the popular Phonopy code. This supports a much wider range of atomistic calculators; up to this point SimulatedDensityOfStates has only been compatible with CASTEP.

- The selection of appropriate q-point sampling meshes can be unintuitive as they are related to the reciprocal lattice vectors. We implement a one-parameter scheme (Moreno-Soler length cutoff) which allows a reasonable default behaviour over many input systems.

- Modifies the Indirect/Simulation Interface to accept the new file formats and dispatch appropriately

This is related to work on the Abins algorithm, as we intend to also provide Euphonic-based inputs there.
As an external Python package with a compiled-C element, including the Euphonic dependency is not entirely trivial. Given that a move to Conda packaging is imminent, it was decided not to add Euphonic to all the existing Mantid build processes. Effectively there are three options available to users:

1. Use a Conda build of Mantid. The Euphonic conda-forge package has been added to the Mantid build recipes, so for Mantid build this way the new features should "just work".
2. Where Mantid was build against a user-accessible Python, `pip install euphonic[phonopy_reader]` should do the trick. It would be helpful if we could arrange for iDAaaS environments to be configured this way.
3. Where Mantid has its own Python environment, Pip needs to be called from inside that environment. A script has been created in the Script Repository which will manage this and refresh the import paths, allowing the new features to be used without restarting mantid. This script is */user/AdamJackson/install_euphonic.py*.

If a user tries to import force constants data using the DensityOfStates interface, an error is produced in the same way as if they try to import IR/Raman data from a .phonon file which is missing that data. A warning message is also produced in the log which directs them to the Script Repository installer.

**To test:**

- Some sample data can be found in the Euphonic test suite: I suggest the *quartz-666-grid.phonon* and *quartz.castep_bin* files from https://github.com/pace-neutrons/Euphonic/tree/master/tests_and_analysis/test/data/castep_files/quartz and *mp-7041-20180417.yaml* file from https://github.com/pace-neutrons/Euphonic/tree/master/tests_and_analysis/test/data/phonopy_files/CaHgO2 . Also grab a benzene example from existing Mantid test data: Data/UnitTest/benzene_Abins.phonon (MD5 ec53aa8ff74b7cd257d7a82c3d6547fd).

*Previously I suggested the CaHgO2-666-grid.yaml file, but this is not a supported file as it does not provide force constants.*

- Make sure that things fail gracefully (and no more than necessary) if the extra library was not installed.
  - On a clean non-Conda installation, open the Indirect/Simulation interface and navigate to DensityOfStates tab. You should be able to select the .phonon file and choose DOS or IR outputs. An error should be raised and handled gracefully if Raman is selected for bezene_Abins.phonon (as that data is missing); CaHgO2-666-grid.yaml is missing both IR and Raman.
  - Try loading some force constants data: either a .castep_bin or .yaml file. This should raise an error, handle it reasonable gracefully, and log an informative message about needing the Euphonic library.
- Install Euphonic with the Script Repository installer, and repeat the above. Hopefully, this time you can get a DensityOfStates using the .castep_bin and .yaml files, and .phonon files continue working as before.
- With a fresh Conda build of Mantid, Euphonic should be available out-of-the-box. You can check this with `import euphonic` from the Workbench IPython interpreter. To check that the C extension is available you could also `import euphonic._euphonic`.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by ajjackson** [comment]
I have noticed some erroneous results when using the existing .phonon file reader. This might be related to a change in the CASTEP file formats, or a feature that was not used in the original development/testing.
It appears that q-point coordinates are incorrectly read as "weights", leading to incorrect DOS intensities including negative portions. This behaviour will also need to be fixed so that I can sanity-check the new results against them!

broken-zns-pdos

**Comment by ajjackson** [comment]
I've tried to cut down on redundancy a bit in the Indirect/Simulations/DensityOfStates interface and make the logic easier to follow. However, due to limited C++ experience it is possible that my code was not very idiomatic!

**Comment by ajjackson** [comment]
At this point I believe the basic features are working, but the builds will fail because the Euphonic dependency is not installed.

**Comment by DavidFair** [comment]
I'm going to clear the milestone on this since the merge window is today and it appears to be a draft from 25 days ago. Feel free to add it to the 6.2 milestone if that's the new target, or drop a message if this is wrong

**Comment by ajjackson** [comment]
The current state of this is that it seems to work but relies on Euphonic to be installed. I have a script in the Script Repository that installs a local Euphonic with Pip using a subprocess, but this requires the Mantid process to be restarted before it can be accessed. @martyngigg is it going to be possible to write a system test that does this installation/restart/run-test cycle or is that outside the existing framework? I suppose it could call MantidPython as a child process but then that limits the quality of debug information :thinking: 

At the moment the Algorithm handles the "Euphonic not installed" scenario with an appropriate error, but the Interface will bring down Mantid if it sees this error. So I need to add some kind of "safe" check step.

**Comment by martyngigg** [comment]
> The current state of this is that it seems to work but relies on Euphonic to be installed. I have a script in the Script Repository that installs a local Euphonic with Pip using a subprocess, but this requires the Mantid process to be restarted before it can be accessed. @martyngigg is it going to be possible to write a system test that does this installation/restart/run-test cycle or is that outside the existing framework? I suppose it could call MantidPython as a child process but then that limits the quality of debug information 🤔

Can we do the pip install into a temporary `prefix` that we control using `--prefix` on `pip` and add this to the `sys.path` after the installation without needing to restart? 

> 
> At the moment the Algorithm handles the "Euphonic not installed" scenario with an appropriate error, but the Interface will bring down Mantid if it sees this error. So I need to add some kind of "safe" check step.

**Comment by ajjackson** [comment]
> Can we do the pip install into a temporary `prefix` that we control using `--prefix` on `pip` and add this to the `sys.path` after the installation without needing to restart?

This approach seems promising. I have now got something similar to that happening within the install_euphonic.py script, which you can find in the ScriptRepository under users/AdamJackson. I use another package to safely parse version numbers, so install it into temporary directory, add it to the path and `reload(site)`. This seems to make it consistently importable (for a sample size of one platform...)

**Comment by martyngigg** [comment]
> > Can we do the pip install into a temporary `prefix` that we control using `--prefix` on `pip` and add this to the `sys.path` after the installation without needing to restart?
> 
> This approach seems promising. I have now got something similar to that happening within the install_euphonic.py script, which you can find in the ScriptRepository under users/AdamJackson. I use another package to safely parse version numbers, so install it into temporary directory, add it to the path and `reload(site)`. This seems to make it consistently importable (for a sample size of one platform...)

This sounds good. It's Python so I'm sure it will work cross platform :)

**Comment by ajjackson** [comment]
One thing I'm finding a little tricky is where in the path to insert the new libraries. For some reason if I put it right at the start then the systemtest framework starts freaking out and can't find `nose` any more. Looking at indexed elements from `sys.path` in my dev container:

```
[(0, '/mantid_src/Testing/SystemTests/tests'), (1, '/mantid_src/Testing/SystemTests/scripts'), (2, '/mantid_build/bin'), (3, '/mantid_src/Framework/PythonInterface'), (4, '/mantid_src/qt/python'), (5, '/mantid_src/qt/applications/workbench'), (6, '/mantid_src/scripts'), (7, '/mantid_src/scripts/Calibration'), (8, '/mantid_src/scripts/DiamondAttenuationCorrection'), (9, '/mantid_src/scripts/Diffraction'), (10, '/mantid_src/scripts/Engineering'), (11, '/mantid_src/scripts/GSAS-II'), (12, '/mantid_src/scripts/Inelastic'), (13, '/mantid_src/scripts/Interface'), (14, '/mantid_src/scripts/Reflectometry'), (15, '/mantid_src/scripts/SANS'), (16, '/mantid_src/scripts/SCD_Reduction'), (17, '/mantid_src/scripts/TemporaryREF_MScripts'), (18, '/mantid_build/scripts'), (19, '/mantid_build/scripts/ExternalInterfaces/mslice/src/mslice'), (20, '/mantid_src/Framework/PythonInterface/test'), (21, '/usr/lib/python36.zip'), (22, '/usr/lib/python3.6'), (23, '/usr/lib/python3.6/lib-dynload'), (24, '/usr/local/lib/python3.6/dist-packages'), (25, '/usr/lib/python3/dist-packages'), (26, '/mantid_src/Testing/SystemTests/lib/systemtests'), (27, '/mantid_src/Framework/PythonInterface/test'), (28, '/mantid_src/Testing/SystemTests/tests/framework'), (29, '/mantid_src/Testing/SystemTests/tests/framework/ISIS'), (30, '/mantid_src/Testing/SystemTests/tests/framework/ISIS/SANS'), (31, '/mantid_src/Testing/SystemTests/tests/framework/ISIS/SANS/LARMOR'), (32, '/mantid_src/Testing/SystemTests/tests/framework/ISIS/SANS/ZOOM'), (33, '/mantid_src/Testing/SystemTests/tests/framework/ISIS/SANS/WORKFLOWS'), (34, '/mantid_src/Testing/SystemTests/tests/framework/ISIS/SANS/LOQ'), (35, '/mantid_src/Testing/SystemTests/tests/framework/ISIS/SANS/SANS2D'), (36, '/mantid_src/Testing/SystemTests/tests/framework/reference'), (37, '/mantid_src/Testing/SystemTests/tests/qt'), (38, '/mantid_src/Testing/SystemTests/lib/systemtests'), (39, '/mantid_src/Framework/PythonInterface/test'), (40, '/mantid_src/Testing/SystemTests/tests/framework'), (41, '/mantid_src/Testing/SystemTests/tests'), (42, '/mantid_src/Testing/SystemTests/scripts'), (43, '/mantid_build/bin'), (44, '/mantid_src/Framework/PythonInterface'), (45, '/mantid_src/qt/python'), (46, '/mantid_src/qt/applications/workbench'), (47, '/mantid_src/scripts'), (48, '/mantid_src/scripts/Calibration'), (49, '/mantid_src/scripts/DiamondAttenuationCorrection'), (50, '/mantid_src/scripts/Diffraction'), (51, '/mantid_src/scripts/Engineering'), (52, '/mantid_src/scripts/GSAS-II'), (53, '/mantid_src/scripts/Inelastic'), (54, '/mantid_src/scripts/Interface'), (55, '/mantid_src/scripts/Reflectometry'), (56, '/mantid_src/scripts/SANS'), (57, '/mantid_src/scripts/SCD_Reduction'), (58, '/mantid_src/scripts/TemporaryREF_MScripts'), (59, '/mantid_build/scripts'), (60, '/mantid_build/scripts/ExternalInterfaces/mslice/src/mslice'), (61, '/mantid_src/Framework/PythonInterface/test'), (62, '/usr/lib/python36.zip'), (63, '/usr/lib/python3.6'), (64, '/usr/lib/python3.6/lib-dynload'), (65, '/usr/local/lib/python3.6/dist-packages'), (66, '/usr/lib/python3/dist-packages'), (67, '/mantid_src/Testing/SystemTests/lib/systemtests'), (68, '/mantid_src/Framework/PythonInterface/test'), (69, '/mantid_src/Testing/SystemTests/tests/framework'), (70, '/mantid_src/Testing/SystemTests/tests/framework/ISIS'), (71, '/mantid_src/Testing/SystemTests/tests/framework/ISIS/SANS'), (72, '/mantid_src/Testing/SystemTests/tests/framework/ISIS/SANS/LARMOR'), (73, '/mantid_src/Testing/SystemTests/tests/framework/ISIS/SANS/ZOOM'), (74, '/mantid_src/Testing/SystemTests/tests/framework/ISIS/SANS/WORKFLOWS'), (75, '/mantid_src/Testing/SystemTests/tests/framework/ISIS/SANS/LOQ'), (76, '/mantid_src/Testing/SystemTests/tests/framework/ISIS/SANS/SANS2D'), (77, '/mantid_src/Testing/SystemTests/tests/framework/reference'), (78, '/mantid_src/Testing/SystemTests/tests/qt')]
```

The errors go away if I put it at 26 (i.e. after /usr/lib/python3/dist-packages but before lib/systemtests). But that's weird; by coming after /usr/lib we don't actually get the updated Scipy. And why do the system packages have higher priority than the local systemtest packages?

It seems to me that this should be the other way around: temporary folder goes first, followed by mantid stuff, followed by system stuff.

**Comment by martyngigg** [comment]
> The errors go away if I put it at 26 (i.e. after /usr/lib/python3/dist-packages but before lib/systemtests). But that's weird; by coming after /usr/lib we don't actually get the updated Scipy. And why do the system packages have higher priority than the local systemtest packages?

> It seems to me that this should be the other way around: temporary folder goes first, followed by mantid stuff, followed by system stuff.

That is odd. I would say your order makes sense too. It's quite possibly that the order has never had much attention paid to it as it didn't really matter before. Perhaps we have a more sublte dependency on the scipy version that first thought?

**Comment by ajjackson** [comment]
Have pushed a work-in-progress that tries to put updated Scipy at the beginning of the (temporary) path, and Euphonic at the end. On Ubuntu it is blowing up with complaints about Nose and "PytestTester"; as far as I can tell this comes down to some kind of scipy/numpy/pytest version incompatibility. But we are trying to _not_ update numpy, and these Scipy versions _should_ be compatible with the installed Numpy.

It's not clear if a) this will translate to any real problem for users or if it is specific to testing or b) if there is any issue for environments other than Ubuntu. I guess the systemtests usually run in RHEL so we'll see what happens there.

**Comment by ajjackson** [comment]
Hmm, this doesn't bode well

```
Installing collected packages: scipy, spglib, seekpath, zipp, typing-extensions, importlib-metadata, importlib-resources, pint, threadpoolctl, euphonic
  Running setup.py install for euphonic: started
    Running setup.py install for euphonic: finished with status 'done'
Successfully installed euphonic-0.6.1 importlib-metadata-4.6.1 importlib-resources-5.2.1 pint-0.17 scipy-1.5.4 seekpath-2.0.1 spglib-1.16.1 threadpoolctl-2.2.0 typing-extensions-3.10.0.0 zipp-3.5.0

Traceback (most recent call last):
  File "/tmp/tmpururywn5", line 12, in <module>
    systest.execute()
  File "/home/builder/jenkins-linode/workspace/pull_requests-rhel7/Testing/SystemTests/lib/systemtests/systemtesting.py", line 249, in execute
    self.runTest()
  File "/home/builder/jenkins-linode/workspace/pull_requests-rhel7/Testing/SystemTests/tests/framework/SimulatedDensityOfStatesEuphonicPackaging.py", line 95, in runTest
    globals()['euphonic'] = importlib.import_module('euphonic')
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmpxcq8lx6h/lib/python3.6/site-packages/euphonic/__init__.py", line 5, in <module>
ModuleNotFoundError: No module named 'pint'
```

It's installing euphonic into a prefix, succesfully finding the library to load, but failing to find a dependency that was installed at the same time?!

@martyngigg At this point I'm tempted to try a straight `--user` install. Yes it will interact with other tests, but then if it does break other parts of Mantid that would be good to know anyway.

**Comment by ajjackson** [comment]
At this point I have managed to tidy up the prefix and environment management quite a lot. The systemtest now passes on my development container, but I'm still hitting the Pint import error on the CI server.

**Comment by ajjackson** [comment]
Further challenges; on a Mac OSX / Conda build, the systemtest fails because the Euphonic Pip package expects a particular compiler to be available. I'm looking into whether we can get wheel builds so this installs more easily for end-users.

**Comment by ajjackson** [comment]
cppcheck is failing. The only relevant comment I see is

> /jenkins_workdir/workspace/pull_requests-cppcheck/qt/scientific_interfaces/Indirect/DensityOfStates.cpp
> 121 | useStlAlgorithm | 398 | style | Consider using std::transform algorithm instead of a raw loop.

I've considered it and decided I'd rather not. Is this style suggestion really blocking the CI from running or am I missing something?

**Comment by ajjackson** [comment]
```
10:31:23 + errors_count=1094
10:31:23 + '[' 1094 -ne 1095 ']'
10:31:23 + echo 'CppCheck found 1094 errors.'
10:31:23 CppCheck found 1094 errors.
```
Ah, I see the problem. CppCheck is failing because I inadvertently _fixed_ a problem, so now there are too few.

**Review by Harrietbrown — APPROVED** [review]
With this PR using the Library I have no problems loading the test files. And the conda build works great. there were a few issues with the install script associated with the PR and I have asked it be updated for any future use in testing. good job.

**Pull request merged**
