### PR TITLE
Fix package name for Indirect Bayes Routines

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

A new package, [quasielasticbayes](https://github.com/mantidproject/quasielasticbayes/), now wraps the fortran code that we had pre-compiled and stuck in the source code directory. A few iterations on the name this dev cycle mean that if we release without updating the name internally then platforms such as Linux/macOS won't be able to install the library to activate the functionality. This fixes the name and removes the old libraries.

**To test:**

* This must be tested on Windows. Run all of the ISISIndirectBayes tests
```cmd
systemtest -C Release -R ISISIndirectBayes
```

*There is no associated issue as I just spotted this was incorrect*

*This does not require release notes* because **it is a change to something that has been noted.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@SpencerHowells That shouldn't be a problem. I realised the old name was not going to work for that so this should let it happen now.

**Comment by Harrietbrown** [comment]
Running the tests on my build I get DLL errors for MantidRemoteAlgorithms and MantidRemoteJobManagers. The tests are passing however.

**Review by Harrietbrown — APPROVED** [review]
Thanks for pointing out the dll solution I recal now having to do that with debug a while ago, I just hadn't done it for release.

The tests compile and run fine. good job.

**Review by DavidFair — APPROVED** [review]
LGTM, nice to move the bins out of the source into our deps tree too :+1:

**Pull request merged**
