### PR TITLE
Clear cache algorithm

### LINKED ISSUE #16506: ClearCaches algorithm
### Expected behavior
We need to be able to clear file of in memory caches used in Mantid

### Plan
Create an algorithm with boolean options to clear

1. The algorithm cache
1. The Instrument cache
1. The Downloaded instrument cache %appdata%\mantidproject\instrument
1. The geometry cache %appdata%\mantidproject\instrument\geometryCache
1. ?The analysis data service?
1. UsageService

### LINKED ISSUE #16571: Generic Algorithm Interface - If the 1st property is Boolean is does not respond to clicks
You can see this in DownloadInstrument, and ClearCache(in another PR).

### PR DESCRIPTION
**Pull request by NickDraper**
Created a new ClearCache algorithm

**To test:**

Test the alg manually, however there is another bug that will get in the way until fixed #16571.

**how to get the sizes of the caches**

``` python
#AlgorithmCache
AlgorithmManager.size()

#Analysis dataservice
AnalysisDataService.size()
#InstrumentDataService - not possible from python

#UsageService - not possible from python

#Files in the download instrument cache
import glob
glob.glob(ConfigService.getInstrumentDirectories()[0] + "*.xml")

#files in the geometry cache
import glob,os
glob.glob(os.path.join(ConfigService.getInstrumentDirectories()[0],"geometryCache", "*.vtp"))
```

Fixes #16506.

Added to framework new algs

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by abuts** [comment]
Attempt to use algorithm instantly kills Mantid. 
Do not understand how these changes may do it, so may be something different happens (crash occurs on some poco thread during logging) but have not yet experienced this problem with anything else

**Comment by NickDraper** [comment]
Was that with any particular propertites selected?

Was mantid doing anything else at the time?

**Comment by abuts** [comment]
I tried all properties and tried a selection --- the result is the same. 

nothing else was going on (except couple of Mantids on other folders) -- I merged to master and did a clean build and tried to clear the cache (mainly useless, though instruments may be still cleared)

Both debug and release versions are affected.

**Comment by NickDraper** [comment]
@abuts this is ready for testing again.  Thanks

**Comment by abuts** [comment]
Looks ok now
:shipit:

**Pull request merged**
