### PR TITLE
Increase memory requirement to try and address Jenkins hang

### LINKED ISSUE #31757: Increase memory requirement in ISIS_WISHSingleCrystalReduction system test
The ISIS_WISHSingleCrystalReduction.WISHSingleCrystalPeakPredictionTest is occasionally hanging on Jenkins. Having investigated this it seems like the actual memory requirement is 24.5GiB (=26.3GB) whereas the memory requirement in the system test's requiredMemoryMB method is 24000 MB. Not entirely sure which GiB\GB convention is used everywhere but it seems like it's too small.

It's possible the test is running on servers where there's not enough memory available - hard to say for sure but it seems worth trying to increase the memory requirement a small amount to 27000 to see if this fixes it.

Note - it's also the case that the test has started outputting a lot of "information" messages about columns in the peak workspace being skipped. This is as a result of an improvement to CompareWorkspaces where it indicates if any columns are being skipped. I don't think this would cause a hang but mentioning here in case the memory requirement change doesn't fix it. We should probably change CompareWorkspaces to include the missing cols (eg tbar) in its comparisons at some point - both to reduce the logging output and to improve the quality of the comparison

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

The ISIS_WISHSingleCrystalReduction.WISHSingleCrystalPeakPredictionTest system test hangs occasionally on Jenkins eg 
https://builds.mantidproject.org/job/pull_requests-rhel7/44323/consoleFull

Increasing memory requirement here to match actual amount of memory used based on tests done on local CentOS VM. This may address the hang on Jenkins

**To test:**

Code review and check system test passes on Jenkins. I will try and make sure the test actually gets run (and not skipped due to the memory requirement) on Jenkins to demonstrate it still works

Fixes #31757. 

*This does not require release notes* because **no functional change**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DavidFair — APPROVED** [review]
I suspected we might have a few tests failing because of OOM / low memory

Out of curiosity if we go back a number of Mantid releases and run this test, was it previously 2.4GB required or always incorrectly labelled?
I'm wondering if there's a regression somewhere that means were using 300MB more memory when we don't need to, which can quickly add up

**Comment by DannyHindson** [comment]
> I suspected we might have a few tests failing because of OOM / low memory
> 
> Out of curiosity if we go back a number of Mantid releases and run this test, was it previously 2.4GB required or always incorrectly labelled?
> I'm wondering if there's a regression somewhere that means were using 300MB more memory when we don't need to, which can quickly add up

I went back as far as the v6.0.0 release and it was using the same amount of memory then as it is now. So if it's gone up it's not a very recent change.

I've not managed to get the RHEL job on this PR to actually run the test where I made the change yet. I've had 3 attempts which have run on isis-ndw1598 (twice) and ornl-mantid-agent02 (once) and it was skipped on all 3 occasions. Do some of the machines not have as much as 27000MB of available memory?

**Comment by DannyHindson** [comment]
The WISHSingleCrystalPeakPredictionTest did run (and complete successfully) on this job on isis-ndw1851:

https://builds.mantidproject.org/job/pull_requests-rhel7/44452/consoleFull

**Comment by DavidFair** [comment]
Don't quote me on this, but I think the test checks if the requested memory is available at that point. Since we run tests with multi-processing if we have one test (likely a WISH one) taking the majority of the memory the scheduler will skip the next

I'd really like to update our system tests to:
- Require accurate memory requirements (if you exceed it by x% the test will be failed)
- Run a bin packing algorithm based on RAM and CPU, to pair up large tests with a number of small ones
- Possibly complete tests in "buckets" of given sizes, so for unreliable tests we can pass a list of tests that were running in a batch together rather than every system test in one

Unfortunately, our current tests are generally good enough and most builders only run with 3-4 cores for system tests to workaround this, so I haven't had the justification to do this yet

**Pull request merged**
