### PR TITLE
Abins: fix compatibility with CRYSTAL17 molecular calculations

### PR DESCRIPTION
**Pull request by ajjackson**
~~**Do not merge before #26650**~~

~~Be aware that this branch is based on #26650 and only the last few commits are relevant to this PR.~~

**Description of work.**

Abins raises errors when loading a recent molecular vibration calculation from CRYSTAL17. This appears to be related to a small difference in the format of the output block for atomic positions:
```
     ATOM             X(ANGSTROM)         Y(ANGSTROM)         Z(ANGSTROM)`
```
compared to
```
     ATOM          X(ANGSTROM)         Y(ANGSTROM)         Z(ANGSTROM)`
```
The current parsing implentation uses `in` to compare strings; I have added an alternative option to to support the use of regular expressions, and modified the CRYSTAL parser to use a regex which tolerates different amounts of whitespace.

The new regex setup should therefore be fully backwards compatible, but does create some redundancy in the code. One option would be to deprecate the `msg=` option that uses `in`, or to convert all *msg* inputs to a regex implementation automatically.

In order to test this, it was necessary to add a new test case with the data from CRYSTAL17 alongside the existing CRYSTAL14 test data.

The process used to generate the existing reference data files for Abins tests does not appear to already be included in the Mantid repository. I have added appropriate method to GeneralLoadAbInitioTester. As a pure function/`@staticmethod`, this _could_ be located almost anywhere, but it seems sensible to keep it near the method used for loading and comparing the data.

Creating reference output with a given build of Mantid/Abins now takes
two lines of Python, e.g.:

```python
loader = AbinsModules.LoadCRYSTAL(ab_initio_filename='ref.out')
AbinsModules.GeneralLoadAbInitioTester.save_ab_initio_test_data(loader, 'my_new_test')
```

which will write the necessary *my_new_test_data.txt* file and *my_new_test_atomic_displacements_data_{k}.txt* files for each phonon wavevector.

**TODO**

- [x] Wait for #26650 to be accepted and rebase onto master
- [x] A release note is needed to confirm the CRYSTAL17 fix
- [x] It could be worth developing some Abins developer documentation including instructions to use the test framework. Start an issue/branch for that?

**To test:**

```bash
ctest --output-on-failure -R Abins
```
---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by ajjackson** [comment]
I don't quite understand it yet, but the Python 3 build error looks legit.

**Comment by dtasev** [comment]
Could this be because `msg` gets passed as `None` (the default value) at some point?

Testing locally I can reproduce the error

```
In [1]: bytes(None, "utf8")                                                                                                                                                              
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-b9dbc2b15705> in <module>
----> 1 bytes(None, "utf8")

TypeError: encoding without a string argument
```

**Comment by ajjackson** [comment]
Thanks for investigating, I'll try to clear this up next week

**Comment by ajjackson** [comment]
I think this is ready for review @Mantid-Matthew

**Comment by ajjackson** [comment]
There is a failed test on RHEL but I'm not convinced it's anything to do with Abins.

> SystemTests.AlignAndFocusPowderFromFilesTest.ChunkingCompare

**Comment by dtasev** [comment]
I'll rebuild it and check if it passes afterwards. If it does I'll add it as an unreliable test

**Comment by ajjackson** [comment]
Looks like it passed!

**Review by Matthew-Andrew — APPROVED** [review]
Code changes look good and relevant tests added.

**Pull request merged**
