### PR TITLE
Create FlipperEfficiency System Test

### LINKED ISSUE #37306: Add a system test for FlipperEfficiency
This needs a system test that runs through the whole algorithm once we're certain of what the inputs and outputs should be.

The FlipperEfficiency algorithm is unit tested with dummy data but we want the system tests to be acting as realistically as possible.

**Data**

Any run number between `ZOOM38249` and `ZOOM38333` can be passed as the input workspace group. All the even run numbers starting (and including) `ZOOM38253` are unpolarised, the rest are polarised. We should pass `00,10,11,01` to the SpinStates parameter of the algorithm for these datasets.

We have confirmed that these runs are suitable to be made public.

Some pre-processing of the raw data is needed before the workspace group will be ready to pass to the algorithm:

- Convert to wavelength.
- Extract the spectrum corresponding to monitor 3 into it's own workspace group (this is the normalising monitor). This should be spectrum 3.
- Extract the spectrum corresponding to monitor 4 into it's own workspace group (this is the monitor between the analyser and main detector that is used for the transmission measurement). This should be spectrum 4.
- Normalise the monitor 4 workspace group by the monitor 3 workspace group (i.e. mon4WsGrp/mon3WsGrp).  The normalised workspace group is now ready to use in the algorithm.

Examples of the required pre-processing can be seen in Diego's example script.

### PR DESCRIPTION
**Pull request by cailafinn**
Pair programmed with @yusufjimoh 

#### Summary of work
Add a system test for the FlipperEfficiency algorithm.
Part of the Polarized SANS Epic. 

Fixes #37306 

#### Further detail of work
Also does some refactoring to reduce code duplication. 

### To test:
- Check both new tests can be run by the `systemtest` script (you may need to explicitly re-run cmake and build the `SystemTestData` target).

*This does not require release notes* because **system tests are not user facing.**

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by rbauststfc** [comment]
Thanks @yusufjimoh and @cailafinn, the code is looking really good on this one and it's great to see these system tests all coming together.

Caila, do you think it's worth kicking off a build from branch for this, the way you did with the helium analyser test, to confirm it's happy on all operating systems?

**Comment by cailafinn** [comment]
> Caila, do you think it's worth kicking off a build from branch for this, the way you did with the helium analyser test, to confirm it's happy on all operating systems?

Thanks for the reminder! Build started here: https://builds.mantidproject.org/job/build_packages_from_branch/

**Comment by rbauststfc** [comment]
Thanks for the build from branch. Looks like all was OK on Linux and Mac, but maybe nothing ran on Windows? Should we try and get that to run again, or do we think things are too flaky on Jenkins just at the moment? I can build this locally and test on my Windows machine if necessary.

**Comment by cailafinn** [comment]
> Thanks for the build from branch. Looks like all was OK on Linux and Mac, but maybe nothing ran on Windows? Should we try and get that to run again, or do we think things are too flaky on Jenkins just at the moment? I can build this locally and test on my Windows machine if necessary.

I think it's too flaky with the system test data on windows at the moment to be worth kicking off a bunch of builds. A check it passes on a local windows (Release) build should be sufficient, IMO.

**Review by rbauststfc — APPROVED** [review]
I've run the tests locally on Windows and they all pass. Everything passed OK on Mac and Linux via the CI tests. Code changes are all looking really good, so this is good to go in. 👍

**Pull request merged**
