### PR TITLE
Document module mantid.utils.reflectometry.orso_helper

### LINKED ISSUE #38395: Document the new utility module mantid.utils.reflectometry.orso_helper
**Describe the outcome that is desired.**
A new page in Mantid documentation detailing the functionality of the module

**Describe any solutions you are considering**
Branch [isis_orso_docs_update](https://github.com/mantidproject/mantid/tree/isis_orso_docs_update) has a draft of the documentation.

**Additional context**
From the documentation draft:

> The ``mantid.utils.reflectometry.orso_helper`` module provides functionality for reading and saving
> reflectivity data in ORSO (**O**pen **R**eflectometry **S**tandards **O**rganization) format.
> It defines classes such as ``MantidORSOSaver``,  ``MantidORSODataset``, and ``MantidORSODataColumns``
> to facilitate the creation, manipulation, and saving of ORSO datasets.
> The ``MantidORSOSaver`` class manages the saving of datasets in ASCII or Nexus formats,
> while the ``MantidORSODataset`` class constructs the dataset with necessary metadata and data columns.
> Finally, the ``MantidORSODataColumns`` class handles the addition and management of data columns and their
> associated metadata.
> This module integrates with the Mantid framework to ensure that reflectivity data can be standardized
> and shared in compliance with ORSO specifications.

### PR DESCRIPTION
**Pull request by jmborr**
### Description of work
A documentation page briefly describes the classes implemented in the module

Fixes #38395
Companion to #38402

### To test:
Just build the documentation (`ninja docs-html`) and review resulting file `docs/html/api/python/mantid/utils/reflectometry.html`

This does not require release notes

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by rbauststfc — COMMENTED** [review]
Thanks very much for putting this together! The class diagram is very useful and the wording in the document is really clear. I'm sure this will be really useful for people trying to use these helper classes going forward.

Just one thing I wanted to double check - I notice that we're using itallics to highlight things like `mantid.utils.reflectometry.orso_helper` and the helper class names, rather than using double apostrophes (i.e. the way `.ort` and `.orb` are highlighted)? My feeling is that the double apostrophes are a bit more common elsewhere in the Mantid docs. That said, this still looks good as it is, so I'm happy to go with whatever you prefer here - just let me know and I'll be happy to approve once the tests are passing.

**Comment by sf1919** [comment]
I've set the tests that failed to re-run as looking at them both I think the runners flaked out rather than there being a test failure.

**Comment by jmborr** [comment]
> Just one thing I wanted to double check - I notice that we're using itallics to highlight things like `mantid.utils.reflectometry.orso_helper` and the helper class names, rather than using double apostrophes (i.e. the way `.ort` and `.orb` are highlighted)? My feeling is that the double apostrophes are a bit more common elsewhere in the Mantid docs. 

I switched to double apostrophes :slightly_smiling_face:

**Review by rbauststfc — APPROVED** [review]
Brilliant, thanks @jmborr, the page is rendering well with the double apostrophes. Thanks again for putting all of this together!

**Pull request merged**
