### PR TITLE
Generate pycharm.bat script on windows

### LINKED ISSUE #21690: Create common scripts to help PyCharm config for workbench
Several step are required to config PyCharm to run the workbench. We need a way to automate as many of these processes as possible with the ideal being it is able to run out of the box. The step that are required (on windows) include: *(note these will most likely be easier on different OS)*
* [ ] ENABLE_WORKBENCH in Cmake (will eventually be default to TRUE) 
* [ ] Setup Python Configurations
  * Must include path to:
    * `Workbench-script.pyw`
    * Mantid Python
    * Working directory
  * Add content roots:
    * Config specific build dir (e.g. `build/bin/Release`)
    * Source dir
  * Mark source directories:
    * `qt/python`
    * `qt/applications/workbench`
* [ ] Launch PyCharm with Mantid dependencies (currently done with script written by Roman)

### PR DESCRIPTION
**Pull request by ElliotAOram**
This script is required when launching pycharm for mantid workbench to ensure the paths are correct.

**To test:**

**This can only be tested on windows**

* Run Cmake on windows.
* Ensure that the `pycharm.bat` file is create in your build directory.
* Download and install [PyCharm community edition](https://www.jetbrains.com/pycharm/download/#section=windows) (if you don't already have it)
* Run the batch file and ensure Pycharm launches.

Additionally, you can try to build and run the Mantid Workbench using the instructions below:
[Build instruction for the workbench with Pycharm](https://www.mantidproject.org/Building_the_workbench_with_pycharm)

Fixes #21690 

**Release Notes** 
*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by josephframsay** [comment]
`pycharm.bat` is generated fine, but unfortunately it crashes on my machine with the following:
capture

**Comment by ElliotAOram** [comment]
Thanks @josephframsay I'll look into it

**Comment by ElliotAOram** [comment]
Interestingly it looks like this is caused by your command not being encapsulated in `" "`. I can't say I fully understand why that's happening. @josephframsay what version of windows are you running?

**Comment by josephframsay** [comment]
@ElliotAOram Oooh that's nasty. I'm running Windows 7

**Comment by josephframsay** [comment]
@ElliotAOram please could you rebase or merge to a recent version of master? I'm getting the googletest error when running CMake

**Comment by ElliotAOram** [comment]
@josephframsay should be rebased to master now :)

**Comment by josephframsay** [comment]
The script now opens pycharm nicely. I now get the following warning, is this a problem?
capture

**Comment by ElliotAOram** [comment]
@josephframsay are you running CMake thorugh cmake-gui? If so did you open it from command line. There's a problem at the moment meaning that you have to open cmake-gui via command line on windows to build the workbench.
As for the error message when you run the batch file, I'll see if I can track that down!

**Comment by josephframsay** [comment]
Ah, that'll be it! Everything now works nicely, including building the workbench, though that error does seem a little odd

**Review by josephframsay — APPROVED** [review]
All good now!

**Pull request merged**
