### PR TITLE
Correct zero padding and prefix for CRISP

### LINKED ISSUE #17586: CRISP: Update zero padding entry
CRISP has been switched over to using 8 digits. Update the corresponding entry in `instrument/Facilities.xml`.

### PR DESCRIPTION
**Pull request by raquelalvarezbanos**
**To test:**
- Open MantidPlot
- Open "First time setup" and set facility to ISIS and instrument to CRISP. In "Manage User Directories" make sure "Search Data Archive" is checked.
- Open `Load` dialog
- Old format (no zero padding and `CSP` prefix): enter `99776` and hit `Run`. Workspace `CSP99776` should be loaded into Mantid
- New format (padding and `CRISP` prefix): enter `99778` and hit `Run`. Workspace `CRISP00099778` should be loaded into Mantid

Fixes #17586.

Release notes were updated with this change and with changes merged in PR https://github.com/mantidproject/mantid/pull/17476

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
This is the conflict in `instrument/Facilities.xml`

```
<<<<<<< HEAD
    <zeropadding size="8" startRunNumber="99778" prefix="CRISP"/>
=======
    <zeropadding size="8" startRunNumber="99778" prefix="CRISP"/> 	
>>>>>>> origin/master
```

?

**Comment by martyngigg** [comment]
@raquelalvarezbanos This is my fault. I saw emails from Max & Rob and it didn't look like it was being taken care of. I just put the minimal update directly on `master`. Sorry, I didn't realise you were looking at it.

**Comment by martyngigg** [comment]
Shall we close this and we can make the minor release note update directly on `master` too?

**Comment by martyngigg** [comment]
Thanks. Sure, I'll add the note now.

**Pull request closed without merging**
