### PR TITLE
Allow columns in sliceviewer peaks table to be sorted

### LINKED ISSUE #28697: Peaks table in sliceviewer peaks view needs to be sortable
As a user I need to be able to identify strong peaks and find them quickly in the peaks table of the slice viewer. The peaks table needs to be sortable by column like that standard peaks table. It would also be helpful to have the peaks table use fewer decimal places for most columns.

Care needs to be taken with how the peaks are referenced in the peaks viewer model as it currently tracks the index in the table.

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Enables the peaks table in the sliceviewer to allow sorting by clicking on the column header.

Also contains a small tweak to the formatting to reduce the number of digits in each column.

**To test:**

* Use script in #28506 to produce an mdws & peaks workspace.
* Start the sliceviewer
* Overlay the peaks workspace
* Sort the table by any column and see it does the expected thing
* Select a peak and make sure the view zooms to the correct point

Fixes #28697 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DannyHindson — COMMENTED** [review]
Just started having a look at this PR. I used the script from https://github.com/mantidproject/mantid/pull/28506 to test it. Here are a few initial comments:

- the sorting works. It would be useful perhaps to be able to return the table to its initial state which is sorted by the "index" shown on the lhs. This isn't a proper column though so couldn't click on it to achieve a sort by "index". Not the end of the world
- the peaks overlay table seems to have a fixed size on the rhs of the slice viewer screen. The width seems to be determined by the width of the workspace name. Is there a way of making it bigger? No problem if not - was just thinking it would make testing easier
- I noticed that if you click on the peak index on the far left of the peaks table then you can select a row in the peaks table but the main view doesn't zoom to the selected peak. The auto-zooming only happens if you click on one of the data cells to select the row

The last two points aren't obviously within the scope of the PR but thought I'd mention them while I was having a look around

**Comment by martyngigg** [comment]
Thanks for testing this.

> Just started having a look at this PR. I used the script from #28506 to test it. Here are a few initial comments:
> 
>     * the sorting works. It would be useful perhaps to be able to return the table to its initial state which is sorted by the "index" shown on the lhs. This isn't a proper column though so couldn't click on it to achieve a sort by "index". Not the end of the world

Yes this is a little bit annoying and it appears Qt has no out of the box way to do this. Could I persuade you that we can spin this out to a future issue? The sorting ability is quite important for the usability and I think its better with it and this small quirk than not?

> 
>     * the peaks overlay table seems to have a fixed size on the rhs of the slice viewer screen. The width seems to be determined by the width of the workspace name. Is there a way of making it bigger? No problem if not - was just thinking it would make testing easier

The slider is annoyingly not very visible but can be dragged to make the view wider. We could look into a better default split for the table in the future. 

>     * I noticed that if you click on the peak index on the far left of the peaks table then you can select a row in the peaks table but the main view doesn't zoom to the selected peak. The auto-zooming only happens if you click on one of the data cells to select the row

This turned out to be a single line of code to hook up to a different signal so I've added this one.

**Comment by DannyHindson** [comment]
Yes fine to let the other points go for now. You can return the table to it's unsorted state by using the "peaks overlay" window to remove a workspace and readd it so that's a workaround in case someone wants to do this.
One more question - does the colour of the workspace name at the top of the peaks table signify anything? With just one workspace selected it seems to be green on Windows (recent nightly build) and red on my Ubuntu VM (where I'm testing this PR)

**Comment by martyngigg** [comment]
The colour is supposed to match the colour of the peak markers. You can add multiple workspaces so the idea was that you could easily see which workspace your peak is in. There was a change to how the colour was computed recently so maybe that's not in the nightly but is in this branch.

**Review by DannyHindson — COMMENTED** [review]
Just retested. All previously discussed points now fine. I noticed that if I select a row in the peaks table and press any key the slice viewer seems to crash with this error:
image
Message in the main workbench window says the error is from peaksviewer/view.py L31
I guess the "self" parameter doesn't need to be explicitly passed to keyPressEvent?

**Comment by martyngigg** [comment]
> Just retested. All previously discussed points now fine. I noticed that if I select a row in the peaks table and press any key the slice viewer seems to crash with this error:
> image
> Message in the main workbench window says the error is from peaksviewer/view.py L31
> I guess the "self" parameter doesn't need to be explicitly passed to keyPressEvent?

Ah yes good catch! That was the refactor to allow introducing the `QSortFilterProxy` type. I swapped `QTableWidget` for `super` without thinking but that's not correct here as I just want the standard table behaviour. I've corrected that now. The diff between the old and new HEAD after the rebase can be seen [here](https://github.com/mantidproject/mantid/compare/bdee7a170b7d74ce13b9a298f4d63aeee32a5e9f..465c880cd58dd8c661245ca7d71250887e09d530)

**Review by DannyHindson — APPROVED** [review]
All looks good now thanks

**Comment by martyngigg** [comment]
Thanks, Danny.

I also must apologise as I've just realised that I left no description or testing instructions on the PR! Very poor example by me. I've added them for reference but sorry about that again.

**Comment by martyngigg** [comment]
@mantidproject/gatekeepers If anyone is around I'd appreciate this getting in tonight.

**Comment by martyngigg** [comment]
Thanks, Steve.

**Pull request merged**
