### PR TITLE
add newest EQSANS IDF

### LINKED ISSUE #25951: add newest EQSANS IDF
The IDF should be thoroughly checked against  `MaskBTP`

### PR DESCRIPTION
**Pull request by jmborr**
**Description of work.**
- [x] New IDF
- [x] Removed redundant old IDF
- [x] Mask test
- [x] [release notes](https://github.com/mantidproject/mantid/blob/4c7d1157cf1fd8466d6f92eadd3b084acdbece7a/docs/source/release/v4.1.0/sans.rst)

**To test:**

Make sure the following script does what it is supposed to do

```
source_dir = '/home/jbq/repositories/mantidproject/mantid1'
w = LoadEventNexus('EQSANS_68200')
LoadInstrument(w, Filename=f'{source_dir}/instrument/EQ-SANS_Definition_20190615_21001231.xml')
MaskBTP(w, Bank='1-48', Pixel='1-8,249-256')  # mask tips of all tubes
MaskBTP(w, Bank='17', Tube='2')  # mask rogue tube
MaskBTP(w, Components='back-panel')  # mask whole back panel
```

Fixes #25951

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by jmborr** [comment]
@peterfpeterson MaskBTP raises with the new IDF when using properties `Bank`, `Tube`, or `Pixel`, I suspect the cause is that the component hierarchy of the new IDF does not conform to the component hierarchy implied in MaskBTP.

Old IDF: `EQ-SANS_Definition_19000131_20190614.xml`
New IDF: `EQ-SANS_Definition_20190615_21001231.xml`

```
new_eqsans = LoadEmptyInstrument('EQ-SANS_Definition_20190615_21001231.xml')
MaskBTP(new_eqsans, Tube='1-10')

RuntimeError: index 49160 is out of bounds for axis 0 with size 49153
  at line 131 in 'Framework/PythonInterface/plugins/algorithms/MaskBTP.py'
```

**Comment by peterfpeterson** [comment]
The issue is the additional level of `font-panel` and `back-panel` and changed what `detector1` was holding. I've added changes to `MaskBTP` to handle this.

**Comment by jmborr** [comment]
> The issue is the additional level of `font-panel` and `back-panel` and changed what `detector1` was holding. I've added changes to `MaskBTP` to handle this.



I'm going to check this!

**Comment by jmborr** [comment]
```
etp=LoadEmptyInstrument(InstrumentName='EQSANS')
MaskBTP(etp, Bank='1-24',Pixel='1-10, 246-256')
```


Now it's working very nicely :smile:

**Comment by jmborr** [comment]
@peterfpeterson so do you think this PR is kosher?

**Comment by jmborr** [comment]
@quantumsteve Steve, would you please please test this PR so that I can get it merged once and for all? :pray:

**Review by quantumsteve — DISMISSED** [review]

**Comment by jmborr** [comment]
@peterfpeterson Pete, it seems you must give your OK too

**Review by quantumsteve — APPROVED** [review]

**Comment by jmborr** [comment]
@AndreiSavici @rosswhitfield Can any of you merge this, please?

**Pull request merged**
