### PR TITLE
Indirect - Vesuvio - Parallelization in VesuvioCalculateMS algorithm

### LINKED ISSUE #21034: Indirect - VESUVIO - Parallelization of VesuvioCalculateMS
The VesuvioCalculateMS Algorithm, currently does not utilise the parallelization features in OpenMP.
Going forwards, this will be useful, for providing a significant increase in performance, when VesuvioCalculateMS is used more frequently in upcoming additions to Vesuvio analysis in Mantid.

### PR DESCRIPTION
**Pull request by brandonhewer**
Currently, the VesuvioCalculateMS algorithm does not make use of parallelization features. Going forward, this could have a significant impact on performance, as the number of use cases for this algorithm increases.

**To test:**

Fixes #21034. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
@brandonhewer We need some notes in this PR on how to test it.

**Comment by NickDraper** [comment]
@brandonhewer These changes seem extensive and are a bit too much to trust just to code review.  Please provide some steps to test it, or point out why the unit and system tests are sufficient, otherwise this might never get tested.

**Comment by brandonhewer** [comment]
@NickDraper The parallelization in this PR needs to be moved to a more appropriate location. This PR definitely needs steps to test, I've mistakenly left it in favour of some other bugs I've received.

**Comment by NickDraper** [comment]
@AnthonyLim23 Can you close this if we are unlikely to attempt to resurrect the work

**Pull request closed without merging**
