### PR TITLE
BASISReduction: set normalization to first slice as option

### LINKED ISSUE #16108: BASISReduction: set normalization to first slice as option
### Expected behavior
The normalization to the first slice should not be implememented when user wants to compare different runs (for instance, substracting the empty can)

### Actual behavior
The normalization to the first slice is always carried out

### Platforms affected
All

### Solution
Introduce a check box to carry out normalization to the first slice. Default should be unchecked.

### PR DESCRIPTION
**Pull request by jmborr**
An option  to normalize by the maximum of the first spectrum is introduced as a property.

**To test:**

Build target `SystemTestData` and make sure the `myBuilDir/ExternalData/Testing/Data/SystemTest/` directory is at the top in the list of user directories of MantidPlot. Then run the following script

```
# Reduce
BASISReduction(RunNumbers="13387",EnergyBins=[-120,0.4,120], MomentumTransferBins=[0.2,0.2,2.0])
RenameWorkspace(InputWorkspace="BSS_13387_sqw", OutputWorkspace="BSS_13387_NotNormalized_sqw")
# Reduced and normalize all spectra to the maximum of the first spectrum
BASISReduction(RunNumbers="13387",EnergyBins=[-120,0.4,120], MomentumTransferBins=[0.2,0.2,2.0], NormalizeToFirst=1)
RenameWorkspace(InputWorkspace="BSS_13387_sqw", OutputWorkspace="BSS_13387_Normalized_sqw")
#######################################################################################
# BSS_13387_Normalized_sqw is just BSS_13387_NotNormalized_sqw multiplied by 0.717661
#######################################################################################

```

Fixes #16108.

[Release notes](https://github.com/mantidproject/mantid/blob/16108_BASISreduction/docs/source/release/v3.7.0/indirect_inelastic.rst) have been updated

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by jmborr** [comment]
@VickieLynch Thanks for accepting the test challenge! :boom:

**Comment by VickieLynch** [comment]
Works as described.  Will ship it when tests finish.

**Comment by VickieLynch** [comment]
:shipit:

**Comment by jmborr** [comment]
@VickieLynch @FedeMPouzols Thanks for your help :bowtie:

**Pull request merged**
