### PR TITLE
Recatagorised muon fitting functions

### LINKED ISSUE #26827: Release notes for fitting functions
need to add to the release notes:

Bessel
CombGaussLorentz
StretchedKT
FmuF
Meier 
MuH 
StandardSC
SilverBaseline
TFMuonium
HighTFMuonium
TriangleOsc
StaticLorentzianKT
SpinGlass
RFresonance
ZFMuonium
DampedBessel
AFM_LF
AFM_ZF
GausBroadGausKT
PCRmagRedfield
PCRmagnet
PCRmagnetfnorm
RedfielsCutoff
SCGapSwave
SCgapAnisoSWave
SCgapDwave
SCgapPwave
ZFdipole
ZFelectronDipole
ZFprotonDipole
PCRmagnetZFKT

### PR DESCRIPTION
**Pull request by Matthew-Andrew**
:warning: Do not merge before #27377  :warning: 

With the addition of many new muon fitting functions it was asked that they be re-categorised to make finding relevant ones easier.

This splits the fitting functions up into generic, specific and modelling.

It also updates the release notes to list the newly added and categorized functions.

**Description of work.**

**To test:**
  * Open Muon Analysis go to the fitting tab and try to add a function. There should be 3 categories Muon Generic, Muon Specific and Muon Modelling.
  * Try running fits with some of the re-catagorised functions to check that they still work
  * Build the release notes and check that all the links are working correctly. 

Fixes #26827  

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
@Mantid-Matthew Have you spotted all the build failures from unit tests that check the category?

**Comment by Mantid-Matthew** [comment]
@NickDraper Yes just fixing now

**Comment by AnthonyLim23** [comment]
unrelated failure

**Comment by alicerussell1** [comment]
The works as expected and the code looks good but the `CodeConventions` failing test is related - my guess would be that it doesn't like the space in the category name

**Comment by Mantid-Matthew** [comment]
I think your correct it doesn't like the space in the category name as categories are tested against the regex expression `^([A-Z][a-zA-Z]+\\?)+$` which doesn't allow for any spaces. 

I think for now I'll just remove the space from the categories as there may be some code which expects them to be spaceless.

**Comment by AnthonyLim23** [comment]
there seems to be something wrong with the fit functions. @Mantid-Matthew have you seen this?

**Review by alicerussell1 — APPROVED** [review]
This looks good to me 👍

**Pull request merged**
