### PR TITLE
Engineering Diffraction GUI bank combo box removed and assorted refactoring

### PR DESCRIPTION
**Pull request by josephframsay**
After the work in #21164, the combo box for bank number in the ED GUI was made obsolete, as the list widget takes care of both run and bank numbers. This PR took care of removing the combo box and all related code.

A large amount of refactoring was also done, which involved moving some helper functions to anonymous namespaces (instead of having them as methods) and renaming some methods and attributes whose purpose did not match their original name, 

Addresses #21238 

**To test:**

Essentially, make sure everything still works as it did after #21226.

Some sample data is [here](https://github.com/mantidproject/mantid/files/1460806/ENGINX_focused_runs.zip).

Load a run from the above data by browsing with the first **Browse** button, then clicking **Load**.
Select the loaded run from the list widget by clicking its label - it should be plotted in the plot window.
Click **Fit** to do a fit - some workspaces with fit parameters should appear in the Workspaces area, and the fitted peaks should be plotted over the original plot. **Update:** The x axis label should be updated when workspaces are plotted so that the workspace units and plot label actually match.

Try changing the peaks with the Peaks line-edit, fitting while multiple runs are loaded, and anything else you think might break things.

Check that fitting information was saved (as `.csv`). On Windows this will be in `C:\EnginX_Mantid\User`, on Linux `~/EnginX_Mantid/User`.

**Release Notes**
The changes to the fitting tab are not complete - this change is a small part of the effort to enable multi-run fitting, which will be included in the release notes once it's been put to bed.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by ElliotAOram** [comment]
Might not be 100% related to this PR, but when you load in data initially, the x axis on the plot window is wrong. I assume this should be TOF not d-spacing?

image

**Comment by ElliotAOram** [comment]
Is it worth doing a sanity check on the data range? e.g. if the peak list contains a value outside the X range of what it is trying to fit (e.i. data ranges from 10,000->60,000 in TOF, peak list should not contain anything outside of this range)

**Comment by ElliotAOram** [comment]
Finally when you come to do peak selection, I might be worth making the distinction between the units for the peak location (e.g. store them all in d-spacing or TOF - not a mix)

**Review by ElliotAOram — APPROVED** [review]
Refactoring looks good and changes in PR function as described. The changes I have mentioned are beyond the scope of this PR, so I'm happy to approve this.

**Review by martyngigg — CHANGES_REQUESTED** [review]
Can we fix the incorrect units on the X axis easily? Units are very important and it doesn't look great if some this simple is not correct.

**Review by martyngigg — APPROVED** [review]

**Pull request merged**
