### PR TITLE
SliceViewer - Fix squished 2D Workspace plot when transposing the data

### LINKED ISSUE #29487: Sliceviewer 2D matrix transposition squashes image
### Expected behavior
When transposing a WS2D on sliceviewer (changing axes) the image should fill the axes (which appear to scale correctly)

### Actual behavior
It does not, the image appears squashed against either the x or y axis

### Steps to reproduce the behavior
1. Load a 2D workspace such as MAR1160
2. Open the sliceviewer
3. Transpose the image by changing the dimension for the x/y axes

### Platforms affected
Confirmed on windows, assumed on all

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR fixes a bug which caused the transpose of a matrix workspace on the SliceViewer to be squished.

The problem was caused by using the wrong `extents` to interpolate y data to the count data when the `transpose` kwarg was set to `True`.

**To test:**
1. Load a 2D workspace such as MAR1160 (training data)
2. Open the SliceViewer
3. Transpose the image by using the `x` and `y` buttons.
4. The data should be transposed ok. The colourbar should also stay the same colour intensity.

Fixes #29487

This is a regression so no release notes are required.

### CODE REVIEW

**Review by StephenSmith25 — COMMENTED** [review]
Fixes the issue and the changes look good 👍 . Is there anywhere you can add a unit test for this?

**Comment by StephenSmith25** [comment]
Looking good to go, just one question to help me understand things - I see you've made some changes to normalization and added a new parameter to the function, how come this was required? As it appears the transpose issue was solved by just setting the extents - so wondering where the other changes come into the fix.

**Comment by robertapplin** [comment]
> Looking good to go, just one question to help me understand things - I see you've made some changes to normalization and added a new parameter to the function, how come this was required? As it appears the transpose issue was solved by just setting the extents - so wondering where the other changes come into the fix.

I made some additional changes as I noticed that the `normalize_by_bin_width` kwarg was not being passed all the way to the `SamplingImage` class as it should be (although this didn't appear to be causing any problems at present). I also changed the `normalization` word to `normalize_by_bin_width` to try and keep the naming consistent throughout this piece of code (as it was slightly confusing).

**Review by StephenSmith25 — APPROVED** [review]
Ah okay, I see - Well looks good to go then 👍

**Pull request merged**
