### PR TITLE
TOFTOF GUI refactoring

### LINKED ISSUE #20535: Add new features to TOFTOF GUI
Following features are requested by users:

1. Option to replace special values (NaNs) in S(Q,W) with 0.
2. Make keeping of the intermediate workspaces optional. If False, keep only:
   - `dataBinE`
   - `dataS`
   - `dataSQW`
   - `VanNorm`
   - `EcNorm`
   - `g..Norm` 
and delete the rest.

3. Option to create a diffractogram
```python
step1 = RemoveMaskedSpectra('dataBinE')
step2 = IntegrateByComponent(step1)
step3 = ConvertSpectrumAxis(step2, Target='Theta')
step4 = Transpose(step3)
```
4. Name the output S(Q,W) workspaces with `_sqw` suffix

5. Add option to save the S(Q,W) and S(2theta,W) as NXSPE and Nexus.

milestone 3.11, I plan to submit a PR by the beginning of next week.

### PR DESCRIPTION
**Pull request by mganeva**
This PR:
1. adds to TOFTOF GUI features requested by instrument scientist
2. switches the data reduction workflow to MergeRuns instead of TOFTOFMergeRuns (TOFTOFMergeRuns can be deprecated in the next release)
3. reduces number of flake8 warnings in the toftof_reduction script (#20508).

**To test:**
Download the test data 
[testdata.zip](https://github.com/mantidproject/mantid/files/1329808/testdata.zip)

Start the TOFTOF data reduction GUI: Interfaces->Direct->DGS Reduction and choose facility MLZ and instrument TOFTOF.

Test that the GUI works at different settings and that the consistent Python script is generated with 'Export' button.

Fixes #20535. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AndreiSavici** [comment]
@mganeva is this supposed to be in 3.11 or in 3.12?

**Comment by soininen** [comment]
The attached reduction fails at the workspace saving step with the message
```
ValueError: Invalid value for property InputWorkspace (MatrixWorkspace) "wsVanNorm_wsDetCoeffs_gwsDataCorr_gwsDataCleanFrame_wsEppTable_gwsDataTofCorr_gwsDataDeltaE_gwsDataCorrDeltaE_gwsDataS": The workspace must have common bin boundaries for all histograms
```
I guess `SaveNXSPE` cannot handle varying bin widths.


[TOFTOF_failing_reduction.txt](https://github.com/mantidproject/mantid/files/1332792/TOFTOF_failing_reduction.txt)

**Comment by mganeva** [comment]
@soininen Thanks, I will disable it if binning in E should be disabled.

**Comment by soininen** [comment]
Found another problem:
```Error in execution of algorithm CorrectTOF
Input WorkspaceGroups are not of the same size.
ValueError: Input WorkspaceGroups are not of the same size.
  at line 98 in '<Interface>'
```
This happens when selecting Correct TOF `sample` (see the attached reduction).
[TOFTOF_failing_reduction.txt](https://github.com/mantidproject/mantid/files/1332981/TOFTOF_failing_reduction.txt)

**Review by soininen — APPROVED** [review]
The few problems found while testing the reduction interface seem to have been fixed. All in all, a nice interface and clean code.

**Comment by mganeva** [comment]
The last commit is the minor change that adjusts the GUI layout for small screens. It does not affect the functionality.

**Pull request merged**
