### PR TITLE
Fix a bug saving add files for multi period data

### LINKED ISSUE #33965: SANS Interface: Unable to add runs containing multiple periods
Reported by Dirk (@dehoni):

**Describe the bug**
The SANS GUI does not properly add runs that contain multiple periods. No error is produced. An added file is created, together with an "add_monitor.nxs" not present for single period runs. Trying to use the file created in the reduction table turns the line blue with the tag "Ended up in added branch where it is neither processed or raw?". Normal measurements with 1 period and polarised raw files as they come get reduced as expected.

**To Reproduce**
Please use any two files from the LARMOR experiments RB2210159 or  2210170.

    Open the ISIS SANS interface
    Click Sum runs and add files
   In the reduction table call the added file and click process. The reduction will stall with the line turning blue.

**Expected behavior**
Mantid should show a more meaningful error message explaining that the file could not be found/is corrupted. 

Added nxs files containing periods should be processed with the SANS GUI as unadded nxs files with periods are.

**Platform/Version (please complete the following information):**
    OS: Idaas
    OS Version:
    Mantid Version 6.3.0

**Additional context**
Whilst this has been labelled for the attention of the ISIS LSS/SANS team, this may be a wider issue with the sum run functionality in Mantid for files with multiple periods.

### PR DESCRIPTION
**Pull request by gemmaguest**
**Report to:** @smk78 @dehoni

This PR fixes a bug in the SANS GUI where summed files for multi-period data were not being saved correctly.
- There was a bug setting the filename for subsequent periods after the first one, where the save path was being pre-pended too many times. This meant that only the first period was saved; monitors were also not being saved.

Fixes #33965

**Description of work.**

**To test:**

- Find a LARMOR user file - here is a minimal version which you can save as e.g. `MaskFile.toml`. 
```
toml_file_version = 1

[instrument]
  name = "LARMOR"

[detector.configuration]
  selected_detector = "All"

[binning]
  wavelength = {start = 2.2, step=0.035, stop=10.0, type = "Log"}
```
- Ensure you have a default save directory set
- Open the ISIS SANS interface
- Select the `Sum Runs` tab on the left
- In Runs To Sum enter `63550, 63552` and click `Add`
- At the bottom click `Sum`
- Check the filename in the Save File text box (this should be `LARMOR00063552-add` by default) - a file should have been created in the save directory with this name.
- Load the saved file into Mantid and check that it is a workspace group containing two event workspaces for the data for each period, and two Workspace2Ds for the monitors:
image
- Click Remove All in the GUI to reset and ensure the save filename is empty.
- Repeat the test using runs `63551,63552`. These are histo workspaces. The output should contain two Workspace2Ds, one for each period. Note that the monitor workspaces are deliberately not included:
image

Release notes to follow

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by MialLewis — COMMENTED** [review]
Code looks good, have followed through the tests and everything is working. Conda-Linux test is failing though this looks unrelated to this PR, will approve when the issue is resolved and it passes.

issue mentioned above does not seem to be relevant given this PR would not be in nightly (behaviour in this PR works as expected).

**Comment by MialLewis** [comment]
> * 63551,63552

Note for anyone repeating this test 63552 should be 63553 for this second part.

**Review by MialLewis — APPROVED** [review]

**Comment by MialLewis** [comment]
@mantidproject/gatekeepers Could someone please take a look at this now the tests are passing? Thanks

**Comment by gemmaguest** [comment]
> Tested on Mantid Nightly 6.3.20220606.1933: Adding transmission files produces files that can be used in GUI reduction. However adding event mode files (e.g. 63591, 63593, 63595), produces a *-add.nxs and *-add_monitors.nxs. Loading *-add file in Mantid produces a single EventWorkspace and not the expected WorkspaceGroup. Is the PR already part of the Nightly build?

@dehoni Sorry for the slow response. This was not in the nightly when you messaged but has just gone in so should be in the next one.

**Pull request merged**
