### PR TITLE
Citations in user docs

### PR DESCRIPTION
**Pull request by peterfpeterson**
Use [sphinxcontrib-bibtex](https://sphinxcontrib-bibtex.readthedocs.io) to unify citations in the sphinx documentation. This PR sets up the majority of the framework while leaving the work of converting most of the references to other PRs. There are a few things that are combined in this PR.
1. Add `sphinxcontrib.bibtex` as an optional plugin for the sphinx site. It will print a warning and create broken links in the output documentation.
1. Convert some documentation to the new citation technology as an example for a maintenance task.
1. Add `python*-sphinxcontrib-bibtex` to the developer package for fedora. It is not immediately available for rhel and back-porting was not a simple recompile.
1. clean-up of linking in the top level `index.rst` to other pages. They were done with urls rather than sphinx's built-in referencing.

Things that aren't done:
1. Update ubuntu developer package for `python*-sphinxcontrib-bibtex`
1. Create a rhel package for `python2-sphinxcontrib-bibtex`
1. Figure out how we want to update build servers that don't have a "convenient" package available. The biggest issue is on rhel7 where we are pushing out nightly documentation.
1. Modify ~50 documentation files to use new citation framework

The estimation of how many/what files need to be modified is
```shell
rg doi.org docs/source/ -l
rg -i isbn docs/source/ -l
```
The same command should work for `ag` and `ack` as well, but slower.

**To test:**

1. Install the new dependency
2. Build the docs
3. Look at the documentation for `SetSamleMaterial` and the new `~/references.html` that are created. The full list of modified files can be seen in the changeset.

*There is no associated issue.*

*Does not need to be in the release notes* because it is a reformatting of citations in the documentation.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
not really essential for this release moving to 3.13

**Comment by martyngigg** [comment]
@peterfpeterson Should we move this to 3.14?

**Comment by peterfpeterson** [comment]
I have ideas for how to get the dependencies everywhere, but this isn't an issue to hold up the release.

**Comment by NickDraper** [comment]
@peterfpeterson This brach appears to have been stale since August 2018.  I'm closing the PR for now, but will leave the branch alive.

**Pull request closed without merging**
