### PR TITLE
Adjust autoscaling behaviour in Muon Analysis

### PR DESCRIPTION
**Pull request by StephenSmith25**
Previously, when any new data was plotted in the Muon Analysis GUI, the axes would autoscale to fit the new data. This behavior is unwanted sometimes and in most cases is unnecessary as an autoscale button exists within the GUI. This PR adjusts the behavior of the autoscaling, such that it is now only performed when it was is truly necessary, e.g the plot type changes.

**Report to:** [Adrian Hillier]

**To test:**

1. Open the Muon Analysis 2 GUI
2. Load some data (e.g MUSR62260)
3. Increment the run (the y axis shouldn't change)
4. Change the plot type to counts (the y axis should now autoscale to the new data)
5. Change to tiled plotting (the graphs should all autoscale to the same y axis)
6. Check the other functionality works. 

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by alicerussell1 — COMMENTED** [review]
If you have a tiled plot of groups/pairs and in the grouping tab remove one of the plots by unticking the box, the remaining plots rescale is this intended?

**Comment by StephenSmith25** [comment]
I think its easier if they automatically autoscale in this case - but it wasn't behaving as intended so I've made a change, thanks for spotting that.

**Comment by StephenSmith25** [comment]
I had to add another change as stepping through tiled plotting wasn't behaving correctly.

**Review by alicerussell1 — DISMISSED** [review]
This all works well now 👍

**Review by alicerussell1 — APPROVED** [review]
Still works

**Comment by NickDraper** [comment]
please mention this to Adrian Hillier

**Pull request merged**
