### PR TITLE
Implement alternative space group settings

### LINKED ISSUE #14204: Add alternative settings for space groups and point groups
Currently, all 230 space group types are registered in Mantid with exactly one setting. For many space groups, there are alternative origin choices or different settings (for example orthorhombic with switched axes). With those alternative settings included, there are more than 500 space groups. It's similar for point groups (for example monoclinic point groups with different unique axes).

Instead of adding all those additional groups manually with generators, the more general solution is to use space group transformations. Two settings of the same group type are related through a matrix/vector pair that represents change of coordinate system and shift of origin, which can be expressed with Geometry::SymmetryOperation. In principle everything described above can be achieved using only SymmetryOperation and adding an operator to Group.

While this covers the "low level implementation", the behavior should be encapsulated in a separate class that performs the transformation (and the reverse transformation). It should be possible to construct objects of this class using only a SymmetryOperation or a string (that can be parsed as a SymmetryOperation).

Furthermore it should be possible to have "named space group transformations". These would describe a transformation from one space group setting to another and store the operation, the initial space group and the target space group. These should be accessible through a factory similar to SpaceGroupFactory, which can be queried in two basic ways:

1. Get all transformations for space group symbol A
2. Get transformation from space group A to space group B.

Suppose there are three space groups `A`, `B` and `C`, where all three are different settings of the same space group with A being the standard setting. Two transformations are registered into the factory, `A -> B` and `A -> C`, but the user should be able to get a transformation `C -> B`. The factory would look up all transformations for `C` and check each element of the result for transformations to `A`. This transformation should be calculated on the fly the first time it's requested and cached for repeated use (just like SpaceGroupFactory generates SpaceGroup-objects only once and caches them).

### PR DESCRIPTION
**Pull request by MichaelWedel**
This fixes #14204.

**Changes**
Introduced `Geometry::GroupTransformation` to transform between space groups. They are specified in the same way as `SymmetryOperation` (using `x,y,z`-notation). Because of the similarities, the matrix/vector-representation was moved to a more abstract `MatrixVectorPair`-class that is used by both `SymmetryOperation` and `GroupTransformation`. The parser for the `x,y,z`-string had to be replaced because the transformation symbols are a bit different, the whole thing is now implemented using `boost::spirit`. Finally, the `SpaceGroupFactory` was extended a bit to make subscribing transformed space groups more convenient. The system test has been adjusted to test the added space groups, the documentation has been updated.

I decided not to implement a factory for the transformations. There is not much repetition happening except for subscribing the monoclinic space groups, but there are not so many. It may something to keep in mind though if people would like to transform crystal structures. In that case the factory would be useful.

**To test**
The changes regarding `MatrixVectorPair` and the parser should be covered by the existing (and new) unit tests, the other changes are covered by system- and doctests. @martyngigg, I'd appreciate if you could take a look at the parser code now that the builder code has been moved to a more appropriate place.

For manual testing you could use the following script as a starting point:

```
from mantid.geometry import SpaceGroupFactory, CrystalStructure, ReflectionGenerator

def get_hkl_d_f(crystalStructure):
    generator = ReflectionGenerator(crystalStructure)
    hkls = generator.getUniqueHKLs(0.7, 10.0)

    # Return hkl, d, F^2 sorted by (d, F^2), descending
    return sorted(zip(hkls, generator.getDValues(hkls), generator.getFsSquared(hkls)), key=lambda x: (-x[1], -x[2]))

# Two descriptions of the same crystal structure (almost silicon) with origin choice 1 and 2
almostSiliconChoice1 = CrystalStructure('5.41 5.41 5.41', 'F d -3 m', 'Si 0 0 0 1.0 0.02')
almostSiliconChoice2 = CrystalStructure('5.41 5.41 5.41', 'F d -3 m :2', 'Si 1/8 1/8 1/8 1.0 0.02')

data_1 = get_hkl_d_f(almostSiliconChoice1)
data_2 = get_hkl_d_f(almostSiliconChoice2)

# Print HKL, d and F^2
for d1, d2 in zip(data_1, data_2):
    print '{0:>10} {1:.5f} {2:8.2f} {3:>10} {4:.5f} {5:8.2f}'.format(*(d1 + d2))
```

It shows that there are now two alternative settings for No. 227 and that it does not matter which representation is chosen to do computations.

Another "pair" you can try with the above code is the following made-up structure:

```
fakeStructure1 = CrystalStructure('6 10 5', 'P b n m', 'Al 0.234 0.112 0.654 1.0 0.01; O 0 1/4 1/2 1.0 0.02')
fakeStructure2 = CrystalStructure('10 5 6', 'P n m a', 'Al 0.112 0.654 0.234 1.0 0.01; O 1/4 1/2 0 1.0 0.02')
```

### CODE REVIEW

**Comment by martyngigg** [comment]
@MichaelWedel I'm happy to review the code. I wonder if someone with better knowledge of space groups etc could review the functionality?

**Comment by MichaelWedel** [comment]
Just as a reminder to myself, I have to put this into the release-notes.

**Comment by martyngigg** [comment]
I'm happy with the code here. I will check with Pascal if he has managed to take a look at it.

**Comment by martyngigg** [comment]
I've checked over the code and I'm happy with it. @VickieLynch would you be able to test the functionality here? Pascal has not managed to find time to look at it.

**Comment by PascalManuel** [comment]
I have and there are a few issues.

However, the built did not contain the latest implementation.

I will test the cif loader (didn;t work either in the end) in mantidnightly. If this is also merged in nightly, I can test both together.

________________________________

**Comment by MichaelWedel** [comment]
Updated release notes: http://www.mantidproject.org/index.php?title=ReleaseNotes_3_6_Diffraction&diff=26198&oldid=26113

**Pull request merged**
