### PR TITLE
Switch macOS system test runner to use Python from MantidWorkbench bundle

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

When MantidPlot is disabled the `MantidPlot.app` bundle no longer exists and the system tests fail to even start. This switches to use the Python from inside the `MantidWorkbench.app` bundle.

**To test:**

I tested this as follows:

* Run `cmake -DENABLE_MANTIDPLOT=OFF -DENABLE_CPACK=ON -DCPACK_PACKAGE_SUFFIX=` and build
* Build a package with `ninja package`
* Change directory to the root of the cloned source code
* `mkdir build` and move the package generated from step 2 to `build`
* Run `WORKSPACE=$PWD EXTRA_ARGS="-R CodeConventions" bash buildconfig/Jenkins/systemtests` and the test should run and pass 

Refs #28650

*This does not require release notes* because **it is an internal task.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DanielMurphy22** [comment]
@martyngigg 
I've tried running the test instructions here. It seems that it skipped almost all of the tests. Is this enough, or is there a way for me to force these tests??

```
FrameworkManager-[Notice] Welcome to Mantid 5.1.20201019.859
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid
FrameworkManager-[Information] Instrument updates disabled - cannot update instrument definitions.
FrameworkManager-[Information] Version check disabled.
[ 50%]   1/  2 : CodeConventions.Algorithms ... (success: 0.14s)
[100%]   2/  2 : CodeConventions.FitFunctions . (success: 0.00s)

################################################################################
Total runtime: 00:00:24

100% tests passed, 0 tests failed out of 2 (511 skipped)
All tests passed? True
```

**Comment by martyngigg** [comment]
@DanielMurphy22 It's the presence of the `EXTRA_ARGS` that does this. I did it as it one test ran then I was happy they all would start but if you did `WORKSPACE=$PWD bash buildconfig/Jenkins/systemtests` it would attempt to run all of them.

**Review by DanielMurphy22 — APPROVED** [review]
> @DanielMurphy22 It's the presence of the `EXTRA_ARGS` that does this. I did it as it one test ran then I was happy they all would start but if you did `WORKSPACE=$PWD bash buildconfig/Jenkins/systemtests` it would attempt to run all of them.

Thanks for explaining this! Works as described then.

**Comment by gvardany** [comment]
Can you just confirm that the removal of `buildconfig/Jenkins/doctests.bat` and ` buildconfig/Jenkins/doctests` is not accidental.

**Comment by martyngigg** [comment]
@gvardany Thanks for checking. Yes as they are no longer used. The doc tests are run as part of the nightly builds so the separate jobs are not necessary.

**Pull request merged**
