### PR TITLE
Fixed bug to get correct extent of bin arguments from axes limits of sliceviewer

### LINKED ISSUE #29165: SliceViewer: zoom on non-orthogonal view decreases extent of binned data plotted
Zooming on the non-orthogonal sliceviewer does not act as one would expect. On the orthogonal view as you zoom the view fills with more of the data but with the nonorthogonal view the data in the view seems to remain constant:

nonortho-zoom

# Steps To Reproduce

The following script produces a workspace that allows angles to be played with:

```python
from mantid.simpleapi import *

SXD23767 = Load(Filename='SXD23767.raw', LoadMonitors='Exclude')
# Set some UB with angles we can play with
SetUB(SXD23767, 1,1,2,90,90,120)
mdws = ConvertToDiffractionMDWorkspace(InputWorkspace='SXD23767',
                                       OutputDimensions='HKL')
```

* Open in the sliceviewer
* Click non-orthogonal view
* Zoom in on a position by scrolling

### PR DESCRIPTION
**Pull request by RichardWaiteSTFC**
**Description of work.**

Fixed bug that was not getting the proper extent for binning arguments when rebinning non-orthogonal data based on axes limits in sliceviewer. The y-axis is not aligned with the vertical plot axis which wasn't reflected in the determination of the limits (xmin,xmax).

**To test:**
(1) Make a non-orthog MD workspace with this script
```
ws = CreateMDWorkspace(Dimensions='3', Extents='-5,5,-5,5,-5,5',
                       Names='H,K,L', Units='r.l.u.,r.l.u.,r.l.u.',
                       Frames='HKL,HKL,HKL',
                       SplitInto='2', SplitThreshold='50')
expt_info = CreateSampleWorkspace()
ws.addExperimentInfo(expt_info)
SetUB(ws, 1,1,2,90,90,120)
FakeMDEventData(ws, PeakParams='1e+06,0,1,0,0.5', RandomSeed='3873875')
```
(2) Plot in sliceviewer with non-orthog view
(3) Zoom in using scroll or dragging the mouse, the data available data should fill the screen as expected (not produce a lot of whitespace as in original issue)

Fixes #29165 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by StephenSmith25 — DISMISSED** [review]
Looks good to me, fixes the issue nicely 👍

**Comment by RichardWaiteSTFC** [comment]
Thanks for reviewing this @StephenSmith25, I've just spotted that when you first put the non-orthog view on it doesn't rebin the data it just transforms what was plotted in the orthogonal view giving a parallelogram of data on the plot. If you zoom out this parallelogram disappears because the rebin is done with the calculated extents which cover the entire plot. I'm just checking with @martyngigg  that this behaviour is OK for this release (and maybe the above becomes a separate issue), or whether it needs addressing in this PR. Sorry for not keeping you updated!

**Comment by StephenSmith25** [comment]
No worries, I had noticed that, but was saw the attached issue only referenced issues with zooming in. But I guess it shouldn't be too much hassle to also trigger a rebin.

**Review by StephenSmith25 — APPROVED** [review]
Looks good to go, fixes the issue and has the added benefit that the data is now rebinned when non-orthogonal axes are turned on.

**Pull request merged**
