### PR TITLE
All groups/pairs from home tab in muon analysis

### LINKED ISSUE #19712: Muon select groups or pairs via home tab
The Muon group want the multi fit mode in muon analysis to decide if to use all groups or all pairs based on the selection in the home tab.

### PR DESCRIPTION
**Pull request by AnthonyLim23**
This work allows the user to alter the default state of the multiple fitting mode in muon analysis based on the selected workspace in the home tab. 

**To test:**

1. Open muon analysis and load some data.
2. Go to the grouping tab and add a new group and a new pair. 
3. Go back to the home tab and change the selected workspace
4. Go to the settings tab and make sure multiple fitting is selected
5. Go to the data analysis tab. All groups or all pairs should be selected (depending on if you have loaded a group or pair in the home tab). The display underneath should also be correct (i.e only the groups or pairs show). 
6. Repeat 3-5 alternating between groups and pairs. 
Fixes #19712 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DTasev** [comment]
Changing to a group in the `Home` tab disables the multiple fitting checkbox, is this intended?

**Comment by AnthonyLim23** [comment]
yes it is. The muon group wanted it to detect if it was a group and asymmetry, then to change to TFAsymmetry mode.

**Review by dtasev — APPROVED** [review]

**Comment by DTasev** [comment]
Changes look good and work as intended, happy to :shipit:

**Comment by martyngigg** [comment]
@AnthonyLim23 There is a merge conflict in `MuonAnalysis.cpp`. It looks simple to fix but I don't think I should fix it here just to be sure I don't do the wrong thing.

**Comment by NickDraper** [comment]
Build failures on OsX are unrelated false positives

**Comment by NickDraper** [comment]
Based on earlier testing I will merge this

**Pull request merged**
