### PR TITLE
Fix links between error and y cols in table workspaces

### LINKED ISSUE #27915: Table errors and plotting
Reported by James

If you create a table workspace using the script:
```
# The following line helps with future compatibility with Python 3
# print must now be used as a function, e.g print('Hello','World')
from __future__ import (absolute_import, division, print_function, unicode_literals)

# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *

import matplotlib.pyplot as plt

import numpy as np

table = CreateEmptyTableWorkspace()

table.addColumn(type="int", name = "Run")
table.addColumn(type="double", name = "B")
table.addColumn(type="double", name = "T")
table.addColumn(type="double", name = "f0.A")
table.addColumn(type="double", name = "f0.AError")
table.addColumn(type="double", name = "f0.B")
table.addColumn(type="double", name = "f0.BError")
table.addColumn(type="double", name = "f0.C")
table.addColumn(type="double", name = "f0.CError")

for run in range(10):
    row = {"Run": run, "B": float(run), "T":float(run)+300.,
           "f0.A": float(run)*0.1, "f0.AError": float(run)*0.01,
           "f0.B": float(run)*0.2, "f0.BError": float(run)*0.02,
           "f0.C": float(run)*0.3, "f0.CError": float(run)*0.03}
    table.addRow(row)
           
```
Then set the run column to X values and the remaining columns to Y and Y error as appropriate. The try and create a line with error plot for `f0.B` Mantid will say there are no associated errors. I think this is because we have different number of y and y error columns.

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

The features for setting columns in a table workspace to X, Y or Y Error weren't working properly in the case where a workspace had a mix of Y columns with\without associated error cols (code was designed with assumption that all Y cols had associated error cols or no Y cols had associated error cols).

Made some changes to fix this. The C++ table workspace class now stores the linked Y column for a column that has been set to "Y Error". The python code has also been updated to calculate the "label index" on the fly when building the column titles instead of storing this in the ErrorColumn class

**To test:**

Problem was in workbench only.

Run the script on the linked issue and then right click on resulting workspace called "table" and select Show Data. Set columns to various combinations of X, Y and Y error using the right click menu. The original problem was visible without actually plotting anything in that the column headers didn't reflect the actions taken properly. Here's what the column headers should look like following the fix:

TableWorkspaceWithCorrectColumnHeadings

Worth spending some time on the various permutations here - particularly cases where a column has been set up initially as one type and then switching to another eg set up a column as Y error and then change it to X

Finally having checked the column headers react properly to changes I suggest you test the plotting works by right clicking on a Y column and selected Plot, Line with Y Errors

Fixes #27915.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@AnthonyLim23 Do we think this is necessary for James or just something he happened across? As Danny said this was in 4.2 and with the changes to workspace etc I think it might be better to put this in the next release if we can?

**Comment by AnthonyLim23** [comment]
This is something he came across and it did cause some confusion.

**Comment by martyngigg** [comment]
@AnthonyLim23 As there are workarounds and the number of non-trivial changes is high we're going to put this in `master`.

**Comment by AnthonyLim23** [comment]
The work around would be to use a script to pull out the values and plot them on their own. I don't know if the users would be able to do that.  

My other concern is if you have values y1, y2, y3 and y4, with errors for y2, y3 and y4. Then the user tries to plot y2 with errors, the errors will be from y3.

**Comment by AnthonyLim23** [comment]
if we could provide a script that would extract values or rearrange the columns so the y values without errors are at the end, that would help users

**Review by martyngigg — APPROVED** [review]
I'm happy how this works now. It seems robust with whatever column changes you try and make. :+1:

**Pull request merged**
