### PR TITLE
Muon analysis and results table

### LINKED ISSUE #22153: sequential fit and results table
Trying 3.12. I did a simultaneous fit (standard single spectrum fitting) to the reserve CdS data. In Results Table I can select the fit by name but no runs are shown, also no log values, and I can't create a table. So it's badly broken! Where do I find the old version to reinstall...

### PR DESCRIPTION
**Pull request by AnthonyLim23**
The muon analysis interface had a bug that prevented results table being generated correctly. 

Fixes #22153. 

**To test:**

Open muon analysis
Go to the data analysis tab and make sure multiple fitting is unticked
On the home tab load some MUSR 62260
Go to the data analysis tab and add a fitting function (doesn't matter which)
Do a fit

Then click sequential fit. 
In the runs box add a 4 (so it reads 62260-4)
Click start
When its complete close the box

Go to the home tab and load run MUSR 62270
Go to data analysis and do a fit

Go to the home tab and load run MUSR 62271
Go to data analysis and do a fit

Go to the settings tab and tick multiple fitting

In data analysis add a fitting function 
Click simultaneous
In the runs box add a -3 (reads 62271-3)
Do a fit

Go to the results table  tab
Click create table
It should have data for 62260, 62270 and 62271

Click the sequential  button and then create a table
 It should contain data for runs 62260, 62261, 62262,.  62263, 62264

Click simultaneous then create table
Should make a table

Click multiple then create table
Should make a table

Go to data anlysis
Go to fit -> sequential fit
In the runs box type have 62271, 62280-3
Go to results table
Click sequential and create table
The table should contain data for runs 62271, 62280 ,62281, 62282, 62283
**Release Notes** 

In release notes
---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DanNixon — APPROVED** [review]
Result tables were created as expected from the fits performed.

**Comment by SimonHeybrock** [comment]
If this is for the patch, shouldn't it go to the patch branch, not `master`?

**Comment by AnthonyLim23** [comment]
When I made the branch there was no patch, because it is only a few commits (4) its easy enough to cherry pick

P.S. The builds are just doc changes

**Comment by martyngigg** [comment]
Build failures are unrelated.

**Pull request merged**
