### PR TITLE
LoadFITS: use fixed size 8 bytes word in fast load loop

### LINKED ISSUE #14361: LoadFITS: avoid too many allocations in the fast load loop
LoadFITS became much slower after the fixes made in #14108 (slow down by a factor of 2x, 4x or even more for large loads). This is because of the `new` being done for every pixel.

### PR DESCRIPTION
**Pull request by FedeMPouzols**
Fixes #14361.

**To test**: code review.

The `new` operation that was introduced in the loop that reads the image pixels has turned out to be very slow (in comparison to the operations done for every pixel). I double-checked the FITS standard and confirmed that the pixel bit depth is between 8 and 64 bits. Also in practice I'm not aware of any datasets using more than that. 

The solution in this branch is to use a small good old array on the stack. An alternative solution would be to use `new` with `scoped_array` but outside the loop, allocating one small array for every thread. This requires using `PARALLEL_GET_MAX_THREADS` for the initial allocation and then taking the thread-specific buffer with `PARALLEL_THREAD_NUMBER`. This seems to work well but I'm not sure how common is that in Mantid algorithms.

I did a few performance checks and these show that a new (or std::vector) are too much overhead, having really bad worst case when running this many times for large input chunks.

Comparisons of alternative LoadFITS loops. Load times in seconds:

```
GCC 4.9.2 on debian

A stack of 1350 images (512x512)
with new:          [8.84, 18.5]
with std::vector:  [8.76, 16.3]
with array:        [2.60, 2.75]

A stack of 144 images (512x512)
with new:          [1.45, 1.52]
with std::vector:  [1.44, 1.52]
with array:        [0.44, 0.47]
```

```
MSVC 2012

A stack of 144 images (512x512)
with new:          [1.38, 1.51]
with std::vector:  [1.82, 2.09]
with array:        [0.99, 1.09]
```

```
GCC 4.9.2 on debian

With scoped_arrays outside the loops, [0.45, 0.49] ~= same time as using the threads' stacks
```

(the ranges come from 7 repetions, after a couple of initial runs to cache the files (for the small stack case)).

Not related to this issue/branch, but still interesting to note: I'm puzzled by why MSVC (in Release mode) is so slower than GCC . It normally produces fast code for this type of loops. Maybe the OMP threads are underperforming.

TODO: quick check again with MSVC 2015 just to see if there's any big difference - to be added in a comment below.

### CODE REVIEW

**Comment by martyngigg** [comment]
Is this still in progress or is it ready to be looked at? It seems like it would be good to get this in as a far better fix to my original one!

**Comment by FedeMPouzols** [comment]
Oops, I think this is ready, so I've removed the "in progress" label. The quick check with MSVC 2015 got delayed, but I wouldn't expect any bad surprises. I'll put the load times in a comment a bit later.

**Comment by martyngigg** [comment]
Sounds good. The code changes here are definitely the most sensible thing given the knowledge about the header so removing `new` is good.

**Comment by FedeMPouzols** [comment]
MSVC 2015 seems to improve a bit the performance of this kind of loop with respect to our older MSVC. 
But the run time is very variable which may have to do with how the threads run or the file system.

```
MSVC 2015

A stack of 144 images (512x512)
with array:        [0.64, 1.07]
```
(with typical times ~0.80, but still some outliers as high as 1.32 when I repeated the run some 30 times).

**Pull request merged**
