### PR TITLE
Report usage statistics for ISIS Reflectometry GUI

### LINKED ISSUE #27030: Report usage for ISIS Reflectometry GUI
The new ISIS Reflectometry GUI doesn't currently report usage statistics. As well as reporting when the interface is opened, I'd also like to report when some of the "main features" are used:
- change instrument
- search/transfer
- autoprocess
- process
- live data monitor
- enabling/disabling slicing
- restoring experiment/instrument defaults
- add/remove rows in the per-theta defaults table
- saving workspaces
- enabling auto-save
- refreshing the workspaces and params lists in the save tab

We probably don't want to report the detail of common operations like changing settings and edits to the runs table.

### PR DESCRIPTION
**Pull request by gemmaguest**
This PR adds usage reporting for specific features to the ISIS Reflectometry interface. (Note that opening the GUI already reports usage via its inheritance of UserSubWindow.)

This PR also makes some minor adjustments to the save tab's presenter/view interactions so that we can report usage more helpfully - the logic to set the save path and update the workspaces list has been moved from `QtSaveView::subscribe` to the `SavePresenter` constructor.

Note that there is a spurious report for InstrumentChanged when the GUI is opened which is difficult to avoid because the `currentIndexChanged` signal gets sent when the combo box is set up. I don't think it's a big enough issue to worry about fixing.

**To test:**

Should be tested by someone at ISIS in MantidPlot or Workbench

- Tick `Report usage data` in the first time setup dialog
- Open the `ISIS Reflectometry` interface
- On the Save tab, check that the save directory matches your mantid default save directory and that the list of workspaces matches the workspaces that currently exist
- Load or remove some workspaces in the ADS and click `Refresh` on the save tab and check that the list of workspaces updates
- Try out various other interactions, e.g. 
  - the menu items (note that you can just cancel operations like Load Batch after selecting the menu item - its usage will still be reported)
  - clicking search, autoprocess (again you can cancel)
  - enter a run and angle (e.g. for instrument INTER, `13460`, `0.5`) and click process
  - click Start Monitor (it doesn't matter if it fails to start)
  - click Restore Defaults on the Instrument or Experiment tab
  - change the slicing type on the Event tab
- Check that some sensible usage reports have been produced (contact me for the results if you don't have access to the database)
- Ensure you untick `Report usage data` when you have finished

Fixes #27030 

*This does not require release notes* because **it is a developer feature**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gemmaguest** [comment]
This is on hold as we plan to discuss alternative ways to report sub-features next week

**Comment by gemmaguest** [comment]
We decided that the format used here of multiple `->`s for subfeatures is what we'd support going forward so this is no longer on hold.

**Review by NickDraper — COMMENTED** [review]
Code review is good

**Comment by NickDraper** [comment]
Some examples that made it through to the database

```
15230 | Feature | ISIS Reflectometry->SaveTab->PopulateWorkspaces |   | 1 | 4.1
-- | -- | -- | -- | -- | --
15227 | Feature | ISIS Reflectometry->RunsTab->InstrumentChanged |   | 2 | 4.1
15228 | Feature | ISIS Reflectometry->RunsTab->PauseAutoprocessing |   | 1 | 4.1
15229 | Feature | ISIS Reflectometry->RunsTab->StartAutoprocessing |   | 1 | 4.1
````
now deleted from the DB

**Review by NickDraper — APPROVED** [review]
Code tests ok, simple reporting additions

**Pull request merged**
