### PR TITLE
External gtest

### LINKED ISSUE #16266: Move gmock 1.7 to be ExternalProject

### PR DESCRIPTION
**Pull request by peterfpeterson**
This is just an attempt to delete more code than @rosswhitfield.

**To test:**

If it passes all of the builds, it is ready to be merged and notify the development team. Please note that this does advance the version of gtest used to 1.8.0 from 1.7.0.

This fixes #16266 and takes care of an issue from the list of [maintenance tasks](https://github.com/mantidproject/documents/blob/110a84c090e013cebff4d36b7dc816366df37310/Project-Management/TechnicalSteeringCommittee/reports/MaintenanceTasks.md) for a very long time.

*Does not need to be in the release notes.*

Applying a patch in an external project has a good example [here (pastebin)](http://pastebin.com/eSMQHmHz).

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by peterfpeterson** [comment]
Somehow this is getting linked into the main application. On normal exit I get
```
MantidUI-[Notice] MantidPlot is shutting down...

[ FATAL ] googletest-src/googletest/include/gtest/internal/gtest-port.h:2044:: pthread_key_delete(key_)failed with error 22
bin/launch_mantidplot.sh: line 49: 12560 Aborted                 (core dumped) LD_PRELOAD=${LOCAL_PRELOAD} TCMALLOC_RELEASE_RATE=${TCM_RELEASE} TCMALLOC_LARGE_ALLOC_REPORT_THRESHOLD=${TCM_REPORT} LD_LIBRARY_PATH=${LOCAL_LDPATH} QT_API=pyqt $VGLRUN$INSTALLDIR/MantidPlot $*
```

**Comment by peterfpeterson** [comment]
The thing to test is:
1. Delete your build create a build directory and `cd` into it
2. `cmake ../`
3. `make -j 3000 Kernel KernelTest`
4. `rm bin/KernelTest`
5. `cmake .`
6. `make -j 10000 Kernel KernelTest`

This should link and be able to run the tests that were built. `KernelTest` does use some mock objects.

**Comment by peterfpeterson** [comment]
It appears that the failing tests are those that use `MOCK_METHOD0`. Fortunately, `NDRandomNumberGenerator` in `Kernel` does so this can be debugged/tested without a ton of rebuilding.

**Comment by peterfpeterson** [comment]
It should also be mentioned that this all works great for `DEBUG` builds as seen in the [last RHEL7 build](http://builds.mantidproject.org/job/pull_requests-rhel7/11838/).

**Comment by peterfpeterson** [comment]
Clean builds need to happen for compilation to pass. Otherwise old `gmock`/`gtest` locations are still stuck in the `CMakeCache.txt`

**Comment by peterfpeterson** [comment]
Last round of builds were `CLEAN` and `BUILDPACKAGE` except rhel7 which doesn't have an option to make the package.

**Comment by rosswhitfield** [comment]
All the tests pass using the external gtest. Once we are able to get through clean builds on all the OSs, :shipit:.

**Comment by rosswhitfield** [comment]
It looks like this has broken the packaging
```
22:00:37 CMake Error at /home/builder/jenkins_root/workspace/pull_requests-ubuntu/build/googletest-build/googlemock/gtest/cmake_install.cmake:40 (file):
22:00:37   file INSTALL cannot find
22:00:37   "/home/builder/jenkins_root/workspace/pull_requests-ubuntu/build/googletest-build/googlemock/gtest/libgtest_main.a".
22:00:37 Call Stack (most recent call first):
22:00:37   /home/builder/jenkins_root/workspace/pull_requests-ubuntu/build/googletest-build/googlemock/cmake_install.cmake:49 (include)
22:00:37   /home/builder/jenkins_root/workspace/pull_requests-ubuntu/build/googletest-build/cmake_install.cmake:37 (include)
22:00:37   /home/builder/jenkins_root/workspace/pull_requests-ubuntu/build/cmake_install.cmake:56 (include)
```

**Comment by peterfpeterson** [comment]
[This commit](https://github.com/mantidproject/mantid/pull/18737/commits/e18a7bbeffcecac5d57243c592e0e2606ffd1b94) fixed the windows patching issue as seen [here](http://builds.mantidproject.org/job/pull_requests-win7/12833/).

The packaging issue was fixed by [adjusting the patch file](https://github.com/mantidproject/mantid/pull/18737/commits/7e86ddb90e6671387837a99ece7b1d762e5c7281) to not let gtest give `install` commands as demonstrated in [ubuntu + doc + packaging](http://builds.mantidproject.org/job/pull_requests-ubuntu/12476/)

**Comment by rosswhitfield** [comment]
:shipit:

**Pull request merged**
