### PR TITLE
fit function to model QENS data with Teixeira water

### LINKED ISSUE #17597: fit function to model QENS data with Teixeira water
A fitfunction to model the Q-dependence of the FWHM from a lorentzian fit is already implemented in fit function TeixeiraWater. This fit function is the Lorentzian with its FWHM given by the Teixeira model, in order to directly fit QENS data.

### PR DESCRIPTION
**Pull request by jmborr**
Fit function to model QENS data assuming a particle undergoing jump-diffusion.

**To test:**
- Review  the code.
- In a MantidPlot session, run the example included in the document page.
- After you run the example, use workspaces "data" and "resolution" to do a manual fit using the "Fit Function" tool of MantidPlot. You may want to import the following string as the model:
  `(composite=Convolution,FixResolution=true,NumDeriv=true;
  name=TabulatedFunction,Workspace=resolution,WorkspaceIndex=0,Scaling=1,Shift=0,XScaling=1;
  (name=DeltaFunction,Height=0.5,Centre=0,constraints=(0<Height<1);
  name=TeixeiraWaterSQE,Q=0.3,Height=0.5,Tau=10,Length=1.0,Centre=0;
  ties=(f1.Height=1-f0.Height,f1.Centre=f0.Centre)));
  name=LinearBackground,A0=0,A1=0`

Fixes #17597.

[Release notes](https://github.com/mantidproject/mantid/blob/e6612e0148ae209af2dd2a75e6852cf445cece6b/docs/source/release/v3.9.0/indirect_inelastic.rst) have been updated

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by jmborr** [comment]
@SpencerHowells  Do you know of anybody in ISIS that could review this pull request?
Once this is approved, I'll open an issue to add the functionality to extract the Q-values from a workspace.

**Comment by SpencerHowells** [comment]
Raquel Alvarez Banos is now part of our little team

**Comment by jmborr** [comment]
@raquelalvarezbanos Hi Raquel, would you be willing to test this new fit function for QENS data, please?

**Comment by jmborr** [comment]
@raquelalvarezbanos Ooops, I have to make some changes, so forget about my request...for now :bowtie:

**Comment by raquelalvarezbanos** [comment]
Yes, I'll be happy to test this :)

**Comment by raquelalvarezbanos** [comment]
Looks good to me. I tried the example in the documentation and the suggested model:

example

Also tried with real dataset and got decent results.

The only comment is that fitting parameters are not displayed in the usual table (like this one [here](http://docs.mantidproject.org/nightly/fitfunctions/DiffSphere.html)). However there's a description below the equation, so I guess this is intentional, @jmborr ?

**Comment by raquelalvarezbanos** [comment]
Tested with `irs26176` and `irs26173` (@SpencerHowells hope these are the right files). Model is similar to that in the description:

examplerealdata

This is the best can I get, which I guess is not too bad considering I have no idea about initial values for the fitting parameters.

**Comment by SpencerHowells** [comment]
Not too bad. It could either be that the initial values are not good enough OR an extra elastic component which I know exists in some spectra.

**Comment by jmborr** [comment]
@raquelalvarezbanos Thanks for catching the missing description of the fitting parameters. I just made a commit to correct that.
I'd like to do the fit with irs26176 and irs26173. I see under Testing/Data/SystemTest/ many files prefixed with irs26176 and irs26173:
`irs26176_diffspec_red.nxs.md5         irs26176_graphite002_QLr_Parameters.nxs.md5  irs26176_graphite002_red.nxs.md5
irs26176_graphite002_cyl_Abs.nxs.md5  irs26176_graphite002_QLr_Workspace.nxs.md5   irs26176_graphite002_width_water.dat.md5`
`irs26173_diffspec_red.nxs.md5     irs26173_graphite002_ResNorm_Paras.nxs.md5
irs26173_graphite002_red.nxs.md5  irs26173_graphite002_res.nxs.md5`
Which are the ones I'm supposed to select among these?

**Comment by raquelalvarezbanos** [comment]
I tried with `irs26176_graphite002_red` and `irs26173_graphite_res`, the first as the sample and the latter as the resolution (tabulated) workspace. I used the same model as you but without constraints.

**Comment by jmborr** [comment]
@raquelalvarezbanos  What is the vertical dimension in these workspaces? It doesn't seem to be Q, but I need the Q values

**Comment by SpencerHowells** [comment]
Right-click on the sample ws to Show Detectors and it will give the Q values

**Comment by jmborr** [comment]
@SpencerHowells Nice, I didn't know this feature!

**Comment by jmborr** [comment]
@raquelalvarezbanos To fit irs26176 and irs26173 one can use the fit string from the documentation but removing the constraints on parameters Heigth because the total intensity is not normalized in the experiment, as in the example in the documents:
`(composite=Convolution,NumDeriv=true;
name=TabulatedFunction,Workspace=resolution,WorkspaceIndex=0,Scaling=1,Shift=0,XScaling=1;
(name=DeltaFunction,Height=1.0,Centre=0;
name=TeixeiraWaterSQE,Q=_Q_,Height=1.0,Tau=1.25,DiffCoeff=2.25,Centre=0;
ties=(f1.Centre=f0.Centre)));
name=LinearBackground,A0=0,A1=0`
I attach python script to the the fitting: 
[fit_irs26176_with_Teixeira.zip](https://github.com/mantidproject/mantid/files/499129/fit_irs26176_with_Teixeira.zip)
fist_and_last_fits

**Comment by SpencerHowells** [comment]
What a result!

**Comment by jmborr** [comment]
@raquelalvarezbanos Hi Raquel, can you please give the OK to this pull request if you see no other problem?
Note: The "failed" RHEL7+System Tests is due to three warnings present in the master branch, they have nothing to do with the code I added.

**Comment by jmborr** [comment]
@SpencerHowells I have uploaded the global-fit script for the water data to the [script repository](https://github.com/mantidproject/scriptrepository/tree/master/indirect%20inelastic/models/TeixeiraWaterSQE)

**Comment by raquelalvarezbanos** [comment]
:shipit:

**Comment by raquelalvarezbanos** [comment]
Sorry both, I've been away

**Comment by jmborr** [comment]
Sweet :strawberry: !

**Pull request merged**
