### PR TITLE
D2B normalisation fix

### LINKED ISSUE #23521: D2B normalisation issue
SumOverlappingTubes mishandles the normalisation for D2B. Regression introduced in [commit](https://github.com/mantidproject/mantid/commit/31ee693da52feee3dbc817d7a076e8f4f5bca9f8#diff-c14bdc0dcda2d37d78af5b4215449580). When many detector pixels fall into one bin, it has to count the number of detectors to normalise by. Zero counting detectors should be counted as well, which was disabled in that commit. The proper thing would be to count zero counting pixels, but ignore the masked pixels. In this case one should explicitly mask the dead pixels to avoid biasing the average.

### PR DESCRIPTION
**Pull request by gvardany**
**Description of work.**

The normalisation in `SumOverlappingTubes` got broken (see the issue).
This was not captured since the tests were using data with sufficiently high counts.
The bug was revealed in a recent short measurement, where many pixels counted 0.

This PR fixes the bug, and adds more rigor to the tests.

**Report to:** G. Cuello.
 

**To test:**

- [ ] ```red = PowderDiffILLDetScanReduction(Run='540162')```
 Plot and confirm by eye, that the ratio of the highest peak and the background is about 10. The test run should be in system test data under ILL/D2B.

- [ ] ```./systemtest -R ILLPowderDiffDetScanReduction``` 

Fixes #23521 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by vreimund — APPROVED** [review]
Code looks good, tests added. Result looks good:


@gvardany I resolved the conflict concerning the release notes, please confirm that this is ok

**Comment by gvardany** [comment]
My understanding is this:
- `ILLPowderDiffDetScanReductionTest.D2B_LowCounts_ReductionTest` went out of sync after PR#23479 made the result of , since it is using the newest data, which is affected by the new instrument parameters file.
- `ILL_D2B_DetEffCorrTest.ILL_D2B_DetEffCorrTest` accidentally passed during the time when system test base was broken (using `CheckWorkspacesMatch`). After the fix of that, it actually started to fail, which is expected since the bug fix does affect this. 
- `ILLPowderDiffDetScanReductionTest.D20_NoMask_ReductionTest` forgot to specify one of the options. Again once passed because of broken system test base.

**Comment by gvardany** [comment]
If I checkout 5d29243, and run `./systemtest -R D2B_DetEffCorr`, here is the tip of the output:
```
CheckWorkspacesMatch-[Notice] Data mismatch. Inputs=[calib,calib_1]
CheckWorkspacesMatch-[Notice] Data mismatch. Inputs=[response,response_1]
CheckWorkspacesMatch-[Notice] CheckWorkspacesMatch successful, Duration 0.00 seconds. Processed as a workspace group
RESULT|memory footprint increase|843972608.0

err: 
********************************************************************************


################################################################################
Total runtime: 00:00:36

100% tests passed, 0 tests failed out of 1 (458 skipped)
All tests passed? True

```
That is the test is marked as success, though `CheckWorkspacesMatch` reports `Data mismatch`.

**Comment by gvardany** [comment]
Should be sorted now. Please make sure that the system test do run and pass on the server and locally:
`./systemtest -R ILLPowderDiff`
`./systemtest -R D2B_DetEffCorr`

**Pull request merged**
