### PR TITLE
Move mantidqtpython wrappers to a subdirectory

### PR DESCRIPTION
**Pull request by martyngigg**
This allows cleaner separation of the legacy wrappers from the new (not yet created) `mantidqt` library.

Description of work.

**To test:**

A code review should suffice. The MantidPlot tests should confirm if everything still works.

*No issue*

**Release Notes** 

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gvardany** [comment]
I could build `mantidqtpython`, but when building `MantidPlot` (or all) I get:
```
sip: Unable to find file "mantidqt.sip"
make[3]: *** [MantidPlot/sip_qtipart0.cpp] Error 1
make[2]: *** [MantidPlot/CMakeFiles/MantidPlot.dir/all] Error 2
make[1]: *** [MantidPlot/CMakeFiles/MantidPlot.dir/rule] Error 2
make: *** [MantidPlot] Error 2
```

**Comment by martyngigg** [comment]
Thanks for catching that, @gvardany. The build servers must have an old copy of the required files so they didn't spot the error. I'll look into it.

**Comment by martyngigg** [comment]
@gvardany That should be fixed now.

**Review by gvardany — APPROVED** [review]
Thanks, it's fixed now :shipit:

**Pull request merged**
