### PR TITLE
Add ability to rotate Ellipse and Rectangle shapes in Instrument Viewer Widget

### PR DESCRIPTION
**Pull request by rosswhitfield**
**Description of work.**

This adds the rotation property to Ellipse and Rectangle shape. This does not add control points for rotation.

**To test:**

Draw an Ellipse or Rectangle, then edit the rotation property of that shape.

2021-09-15-104014_1124x763_scrot

Check that applying as Mask, ROI or Group works as expected.

2021-09-15-104032_1124x763_scrot

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by rosswhitfield** [comment]
Rabased on master to fix merge conflict from #32401

**Review by Harrietbrown — COMMENTED** [review]
The rectangle and ellipse shapes are both rotateable is the plan to expand this to the other shapes as well in the future?

**Comment by rosswhitfield** [comment]
> The rectangle and ellipse shapes are both rotateable is the plan to expand this to the other shapes as well in the future?

It doesn't make sense to implement it for the Circle Sector or the Arbitrary Shape.

That leaves the Elliptical Ring and Rectangle Ring but that wasn't requested at this point, so maybe later if it's requested.

**Comment by Harrietbrown** [comment]
> > The rectangle and ellipse shapes are both rotateable is the plan to expand this to the other shapes as well in the future?
> 
> It doesn't make sense to implement it for the Circle Sector or the Arbitrary Shape.
> 
> That leaves the Elliptical Ring and Rectangle Ring but that wasn't requested at this point, so maybe later if it's requested.

How complex would it be to make them rotate like the others? If it is non trivial then I guess we could leave it, but if it is simple I see no reason not to implement it while we are at it.


Also, are there tests for this functionality?

**Comment by rosswhitfield** [comment]
> > > The rectangle and ellipse shapes are both rotateable is the plan to expand this to the other shapes as well in the future?
> > 
> > 
> > It doesn't make sense to implement it for the Circle Sector or the Arbitrary Shape.
> > That leaves the Elliptical Ring and Rectangle Ring but that wasn't requested at this point, so maybe later if it's requested.
> 
> How complex would it be to make them rotate like the others? If it is non trivial then I guess we could leave it, but if it is simple I see no reason not to implement it while we are at it.

Not trivial, there is added complexity that the Rings are shapes made of shapes and different control points.

> Also, are there tests for this functionality?

No. There is very little existing tests for the Instrument Viewer and there are no tests for drawing masks. If there was I would have added a new test. Implementing tests for this would be far more work than implementing this feature as I would be starting from nothing.

**Review by Harrietbrown — DISMISSED** [review]
The rectangle and ellipse shapes are able to be rotated. Good job

**Comment by rosswhitfield** [comment]
More merge conflicts, this time from #32465

**Review by Harrietbrown — APPROVED** [review]

**Pull request merged**
