### PR TITLE
ConvertToMD: Relax checks for CopyToMD mode

### LINKED ISSUE #19136: ConvertToMD: CopyToMD fails with output from SofQW
The following script reproduces the problem.

```
Load(Filename='ExternalData/Testing/SystemTests/tests/analysis/reference/MARIReduction.nxs', OutputWorkspace='MARIReduction')

SofQWNormalisedPolygon(InputWorkspace='MARIReduction', OutputWorkspace='SofQW', QAxisBinning='0.1,0.01,4.5', EMode='Direct')
ConvertToMD(InputWorkspace='SofQW', OutputWorkspace='sqw_md',QDimensions="CopyToMD",Q3DFrames='HKL')
```

`ConvertToMD` should ignore the target frame argument in this case and just print a warning.

### PR DESCRIPTION
**Pull request by martyngigg**
Description of work.

Ignores `Q3DFrames` & `QConversionScales` arguments if the transform mode is not `Q3D`

**To test:**

The test file is part of the SystemTestData.

```
Load(Filename='ExternalData/Testing/SystemTests/tests/analysis/reference/MARIReduction.nxs', OutputWorkspace='MARIReduction')
SofQWNormalisedPolygon(InputWorkspace='MARIReduction', OutputWorkspace='SofQW', QAxisBinning='0.1,0.01,4.5', EMode='Direct')
ConvertToMD(InputWorkspace='SofQW', OutputWorkspace='sqw_md', Q3DFrames='HKL')
```

Before these changes the algorithm would stop and claim that a UB matrix is required. After these changes it should complete successfully.

Fixes #19136.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by soininen** [comment]
This seems to work as advertised for both _Q3DFrames_ and _QConversionScales_ properties. However, when looking at the [documentation](http://docs.mantidproject.org/nightly/algorithms/ConvertToMD-v1.html) of `ConvertToMD`, I would expect the _Vproj_ and _Wproj_ properties to be ignored as well if mode is not 'Q3D'. Instead, I get the error log
```
The projections are coplanar. Will use defaults [1,0,0],[0,1,0] and [0,0,1]
```
when changing the last line of the test script to
```python
ConvertToMD(InputWorkspace='SofQW', OutputWorkspace='sqw_md', Wproj='1,0,0')
```

**Comment by martyngigg** [comment]
@soinen Good point. I don't spot that was `Q3D` only also. I'll fix up the code.

**Comment by martyngigg** [comment]
@soininen The code should now ignore those values if they are set and print a warning.

**Comment by soininen** [comment]
Tried this out with the test script provided and with different combinations of `Q3DFrames`, `QConversionScales`, `Uproj`, `VProj`, and `Wproj` properties. The properties get ignored with a warning message, as one would expect. The code changes look good, too, so :shipit:

**Pull request merged**
