### PR TITLE
Fix regression in vtkMDHistoHexFactoryTestPerformance.

### PR DESCRIPTION
**Pull request by quantumsteve**
Description of work.

This fixes a performance regression in [VatesAPITest.vtkMDHistoHexFactoryTestPerformance](http://builds.mantidproject.org/view/Tests/job/master_performancetests/Master_branch_performance_tests/VatesAPITest.vtkMDHistoHexFactoryTestPerformance.testGenerateHexahedronVtkDataSet.htm). Modulo division is slow enough to slow down the test by ~40%. Switching this to a comparison virtually eliminates this penalty.

**To test:**

I found it easier to use `<chrono>` to time [this for loop](https://github.com/mantidproject/mantid/blob/2e9e0a43f8ade436125be7394307424d9f9a4f03/Vates/VatesAPI/src/vtkMDHistoHexFactory.cpp#L133). Alternatively, one can run and time the specific performance test.

There is no GitHub issue associated with this pull request.

*Does not need to be in the release notes.* Regression added after latest release.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@quantumsteve This PR has developed a merge conflict.

**Comment by quantumsteve** [comment]
@martyngigg Fixed.

**Comment by martyngigg** [comment]
The code changes look good to me. Anything to add @LamarMoore?

**Comment by quantumsteve** [comment]
With #18308 merged, this PR is redundant.

**Pull request closed without merging**
