### PR TITLE
Abins python3  ( AbinsModules to Python 3 #19816 #19816)

### PR DESCRIPTION
**Pull request by dymkowsk**
0) Fix failure of system tests when Mantid is compiled against Python3
1) Define additional local variables to avoid breaking too long lines (to avoid "continuation line over-indented for visual indent" )
2) Redefine the way numpy array is put into 1D workspace (to fix shift of peaks by bin width observed between Python2 and Python3):  
    a) Use more consistent values of frequencies
    b) Change CreateWorspace to WorkspaceFactory
3) Make sure order of workspaces in group workspace is the same in Python2 and Python3 
4) Remove methods for 2D map to improve readability (2D map not implemented in this version and those methods are not used at all)
5) Remove comas from except clause 
6) Change unicode to six.text_type and (int, long) to six.integer_types
7) Clean up system test (AbinsTest.py)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by peterfpeterson** [comment]
The osx tests all have `Abins` in their names.

**Comment by dymkowsk** [comment]
I think now should be all Ok. Rhel7 fails at units tests but there is not because of Abins.  @peterfpeterson  could you restart the checks for my last commit?

**Comment by dymkowsk** [comment]
@peterfpeterson  I have just added 0) to my description of pull request to better motivate  this pull request. Before I made a pull request I run system tests locally on my machine with build against Python3 and they were all passed. However, system tests for Python3 hasn't been tested on Jenkins.

**Review by peterfpeterson — APPROVED** [review]
I ran all of the system tests that have `Abins` in the name with python3 and they pass. It's good to merge.

**Pull request merged**
