### PR TITLE
Feature/macports build

### PR DESCRIPTION
**Pull request by mganeva**
I've introduced the following changes to be able to build, pack and install Mantid using macports+clang on Mavericks:
1. quotes in DarwinSetup.cmake for ${PYQT4_SYMLINK_Qtso} and ${SITEPACKAGES_SYMLINK_sipso}. Without quotes my cmake was complaining about number of arguments for FIND and SUBSTRING functions.
2. IF for PYQT4_PATH, SITEPACKAGES_PATH and OPENSSL_ROOT_DIR variables in DarwinSetup.cmake to be able to set them externally with cmake -D.
3. MACPORTS option to avoid execution of the make_package.rb which contains hard-coded path to the libraries in /usr/local. Macports store libraries in /opt/local and this file breaks the installation with macports.

Please, test that my changes do not break build with homebrew. I have no homebrew to test it by myself.

### CODE REVIEW

**Comment by quantumsteve** [comment]
test this please

**Comment by quantumsteve** [comment]
test this please

**Comment by quantumsteve** [comment]
Since these changes don't affect either of our osx builds, I'll merge them in as is. 

Does your macports bundle include all necessary python libraries? They used to be part of 3rdpartylibs-mac, but are now copied from site-packages. 

There are some linking issues with the FixBundle.cmake.in script, so you will likely still need to set DYLD_LIBRARY_PATH before using the python interface.

**Comment by jcns** [comment]
Thank you for testing. For the moment, I did not have any problems with python libraries and I was able to run all my python scripts, but I will check it.

**Pull request merged**
