### PR TITLE
Restore axis tick format on project save and load

### LINKED ISSUE #31259: Scientific Formatting on Plotting not saving
As seen in Manual testing #31111 

### Expected behavior
When changing the Tick format on the axis of a plot to "Scientific Format" this should still be set as this format when project is saved and reopened.

### Actual behavior
Unless the "Log" checkbox is ticked, the plot axis is defaulting to Decimal format when the project is saved and reloaded.

### Steps to reproduce the behavior
- Load a file
- Plot one or more of the spectra from it. 
- Double click on either the x or y axis to edit the axis. 
- In the dialog that appears change Tick Format to Scientific Format. Plot axis will then change to Scientific Format. 
- Save the project and re-open it,
The tick labels will revert to decimal format.

### Platforms affected
All

### PR DESCRIPTION
**Pull request by srikanthravipati**
**Description of work.**

Created a dictionary of supported tick formats and applied the correct format to plot axes ticks when the project is loaded.

If an axis tick format is not available in the above dictionary, 'ScalarFormatter' is set as the default format.

**To test:**

-> Load a file
-> Plot one or more of the spectra from it
-> Change an axis tick format by clicking on the axis.  As an example, change an axis tick format to 'scientific format'.
-> Save the project and re-open it

The tick format should be the same (scientific) format as set previously.

Fixes #31259.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by SilkeSchomann — DISMISSED** [review]
Looks good to me and fixes #31259.

**Comment by gemmaguest** [comment]
@srikanthravipati Could you fix the conflicts, and also set the milestone?

**Comment by srikanthravipati** [comment]
> @srikanthravipati Could you fix the conflicts, and also set the milestone?

@gemmaguest Done.

**Review by SilkeSchomann — APPROVED** [review]
Looks good now.

**Pull request merged**
