### PR TITLE
Fix IMAT IDFs from 2015 and 2016 causing issues due to overlapping IDs

### LINKED ISSUE #19552: IMAT contains duplicate detector IDs
The IMAT [IDF](https://github.com/mantidproject/mantid/blob/master/instrument/IMAT_Definition_2015.xml) tries to reuse detector ids...this is not doing what the author expected. This affects **IMAT_Definition_2015.xml AND IMAT_Definition_2016.xml**. Both should be fixed as part of this.

For example, ID 1 is used twice because it appears once [here](https://github.com/mantidproject/mantid/blob/master/instrument/IMAT_Definition_2015.xml#L103), and then again in the range [here](https://github.com/mantidproject/mantid/blob/master/instrument/IMAT_Definition_2015.xml#L45). The second attempt leaves an parasitic detector - it is part of the full in-memory instrument but cannot actually be referenced since it's ID is invalid. See (`Instrument::markAsDetector` ) if you're interested in seeing how the detector ends up orphaned.

After fixing, much of this can be sanity checked by eye. 

1. ID Lists should contain unique detector id ranges.
1. ID Lists should be used only once within a given IDF.

This is blocking the rollout of Instrument 2.0 features.

### PR DESCRIPTION
**Pull request by dtasev**
Description of work.

The camera has been removed from the definition files. This should hopefully fix any ID collisions.

**To test:**

Fixes #19552. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by OwenArnold** [comment]
Before I check this, can you verify that putting an (temporary) else in here https://github.com/mantidproject/mantid/blob/f4143857254a0e82ca2fc92731a6a7cdfaa66d1b/Framework/Geometry/src/Instrument.cpp#L719
like 
```cpp
else {
  throw std::runtime_error("Duplicate detector dropped");
}
```
Then building and running `LoadEmptyInstrument` for all the IDFs changed does not result in an error, and also that the number of detectors reported in the Detector table matches the expectations from the IDF?

**Comment by DTasev** [comment]
@OwenArnold Just a note that I couldn't reproduce the error before. I tried it and all of the IDFs loaded in with the change and I did not get Mantid to throw

**Comment by OwenArnold** [comment]
@DTasev That could be because of the rhs of the `||` unique object check. Delete that out and see if it throws.

**Review by OwenArnold — APPROVED** [review]
Duplicates removed. 
Instrument Scientists consulted about changes
Test Data verified with Instrument Scientist.

**Pull request merged**
