### PR TITLE
Make handling of expected peak units more robust in EnggFitPeaks

### LINKED ISSUE #21342: Engineering Diffraction GUI peak picker uses wrong units
The peak selector in the ED GUI updates the list of candidate peaks with values in TOF, but the fitting algorithms treat these values as though they are in D. This means when they're converted to TOF (from TOF), they end up being way off to the right on the X axis, and so obviously fitting fails.

### Steps to reproduce the behavior

Load up the ED GUI and select the Fitting tab. Load in some focused ENGINX data clear the peaks list by hitting **Clear**. Select a couple of peaks by clicking **Select peaks** and then shift-clicking on the peaks. Notice that the peak centres that appear in the Peaks line-edit are in TOF (as might be expected, given the plot is in TOF). Now when you click **Fit** the fit will fail with errors such as
`Given peak centre 4.97839e+08 is out side of given data's range (14421.3, 64081.5).`

### Platforms affected
All

### PR DESCRIPTION
**Pull request by josephframsay**
Previously, if passed a list of peak centres in TOF, `EnggFitPeaks` assumed they were in dSpacing, and so converted them to TOF as if they were, leading to incorrect expected peak centres to be passed to the fitting routines.

This PR makes the handling of units in EnggFitPeaks more robust. If none of the expected peaks lie in the limits of the x axis of the input workspace, then EnggFitPeaks converts them from TOF to D, and sees if any of the converted peaks lie within the limits. If not, the algorithm fails.

This change enables the peak picker to be used in the ED GUI, as peaks are normally selected from a plot in TOF.

**To test:**

Make sure EnggFitPeaks unit test passes locally and remotely.

Make a sample workspace:
```

peak_def1 = "name=FlatBackground,A0=1;" \
            "name=BackToBackExponential, I=15000, A=0.1, B=0.14, X0=41209, S=50"
peak_def2 = "name=FlatBackground,A0=1; " \
            "name=BackToBackExponential, I=6000, A=0.02, B=0.021, X0=46895, S=40"

sample_ws = CreateSampleWorkspace(Function="User Defined",
                                  UserDefinedFunction=peak_def1 + ";" + peak_def2,
                                  NumBanks=1, BankPixelWidth=1, XMin=40000, XMax=50000, 
                                  BinWidth=25)

EditInstrumentGeometry(Workspace=sample_ws, L2=[1.5], Polar=[90], PrimaryFlightPath=50)
```

First try running EnggFitPeaks with the expected peak centres in TOF:
```
fit_results = EnggFitPeaks(InputWorkspace=sample_ws, WorkspaceIndex=0, 
                           ExpectedPeaks=[41209, 46895])
```

The fit should run successfully. The `dSpacing` column in `fit_results` should contain the equivalent peak centres - approximately 2.238 and 2.547.

Running the fit with the numbers:
```
fit_results = EnggFitPeaks(InputWorkspace=sample_ws, WorkspaceIndex=0, 
                           ExpectedPeaks=[2.238, 2.547])
```
Should give you a similar table.

Finally, EnggFitPeaks supports a GSAS-style conversion from TOF to D if the relevant parameters are set on the workspace. Try the following:
```
run = sample_ws.mutableRun()
run.addProperty("difa", 0.0, False)
run.addProperty("difc", 18400.0, False)
run.addProperty("tzero", 4.0, False)

fit_results = EnggFitPeaks(InputWorkspace=sample_ws, WorkspaceIndex=0, 
                           ExpectedPeaks=[41209, 46895])
```
And verify, again, that the `dSpacing` column contains sensible values (in this case approx 2.239 and 2.548).

Fixes #21342 

**Release Notes** 
[Here](https://github.com/mantidproject/mantid/pull/21355/commits/a49d6c938cba484b0e367186151f8c69fe867a64)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [x] Are the unit tests small and test the class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by josephframsay** [comment]
Currently waiting on discussions with ENGINX scientists about what units they actually want to work in, and therefore whether this is the best way to tackle this issues with the peak picker

**Comment by josephframsay** [comment]
Following a meeting with intrument scientists, from their point of view it makes sense to have TOF before fitting and D after, so these changes are probably the best way to address the problems with the peak picker

**Review by NickDraper — COMMENTED** [review]
Code review ok

**Review by NickDraper — APPROVED** [review]
All tests pass

**Pull request merged**
