### PR TITLE
Indirect - OSIRIS Diffraction Reduction (diffonly) -  Incorrect output when supplying Manual D-Range

### LINKED ISSUE #20763: OSIRISDiffractionReduction - No output produced in _dRange workspace
In Interfaces > Indirect > Diffraction, running the interface in OSIRIS diffonly mode (calling the OSIRISDiffractionReduction algorithm) and supplying a Manual D-Range, results in the _dRange output workspace having no data (all zeroes).

This can be produced with any of the Sample Run Numbers 119977-119988 (supplied as Range or List), Vanadium Run Numbers 119963-119974 and enabling Manual D-Range and supplying a list of values.

### PR DESCRIPTION
**Pull request by brandonhewer**
The OSIRISDiffractionReduction algorithm was producing output data with only zero values, when a manual d-range was supplied. An error was also being displayed pertaining to the summing of workspaces using the 'sum' function in python.

**To test:**
1. Navigate to Interfaces > Indirect > Diffraction.
2. Ensure `OSIRIS` is selected as the instrument, and `diffonly` is set as the reflection mode.
3. Enter `119977-119988` into the 'Run Numbers' field.
4. Provide the supplied calibration file into the 'Cal File' field.
5. Enter `119963-119974` into the 'Vanadium Runs' field.
6. Check the 'Manual dRange (Vanadium)' checkbox.
7. Enter `1-12` into the 'Manual dRange (Vanadium)' text field.
8. Click Run.
9. Plot the created \*\_dRange workspace.
10. Ensure the output is not a flat line at 0 (i.e. the output contains non-zero values).

[osiris_041_RES10.zip](https://github.com/mantidproject/mantid/files/1356273/osiris_041_RES10.zip)

Fixes #20763 . 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gvardany** [comment]
@brandonhewer In bullet 4 did you mean to attach the cal file to the PR?

**Comment by brandonhewer** [comment]
@gvardany Yes, sorry I'll attach that now.

**Comment by brandonhewer** [comment]
@gvardany I've added the mentioned calibration file.

**Comment by NickDraper** [comment]
@AnthonyLim23 @brandonhewer This seemed to fail it's own system test

**Review by martyngigg — APPROVED** [review]
Everything seems to work as expected with the algorithm and interface. Good to go.

**Comment by martyngigg** [comment]
The windows build failure is again the PhaseQuadMuon problem.

**Comment by martyngigg** [comment]
@mantidproject/gatekeepers This is ready to go for the release branch too.

**Pull request merged**
