### PR TITLE
Fix importing string series logs

### LINKED ISSUE #17923: String series logs can no longer be imported
#### Expected behaviour
Should be able to import string series logs with the "Sample logs" dialog

#### Actual behaviour
String series logs are no longer imported correctly (regression)

#### Steps to reproduce the behaviour
- Load a workspace
- Right-click on it in the dock and select "Sample Logs..."
- Choose a string series log and try to import it.

Results:

**Mantid 3.6**
icpevent mantid 3 6

**Mantid 3.7 and 3.8**
icpevent mantid 3 7

#### Platforms affected
This worked on Mantid 3.6 but is broken in Mantid 3.7 and 3.8.

### PR DESCRIPTION
**Pull request by tom-perkins**
Importing string series logs into MantidPlot (via Sample Logs dialog) has been broken since Mantid 3.7, but worked in Mantid 3.6 and before. Re-enable this functionality by setting the column type correctly.

Also matched the old formatting by left-aligning/vertically centering text and making the column wide enough for its contents.

**To test:**

- Create a dataset with a string series log:
```python
ws = CreateSampleWorkspace()
run = ws.mutableRun()
prop = StringTimeSeriesProperty("string_series")
prop.addValue("2016-11-10T11:58:20", "hello")
prop.addValue("2016-11-10T11:58:24", "message2")
prop.addValue("2016-11-10T11:58:26", "message3")
run.addProperty("string_series", prop, False)
```
- Right-click on the workspace in MantidPlot and select *Sample Logs...*
- In the dialog, select the `string_series` log and click *Import selected log*
- Log should be imported correctly, with values in the table - not a blank values column. (See the issue)
- Can also try this with a real workspace that has a string series log. (I used the `ICPEVENT` log from `EMU00066122.nxs`)

Fixes #17923.

[Release notes](https://github.com/mantidproject/mantid/blob/bd01f708ebaf7e35d6d1e86260e2d6d3b71e42cc/docs/source/release/v3.9.0/ui.rst#bugs-resolved) have been updated.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
It doesn't work for me on Windows 7. I get "0" in the imported log.

**Comment by KarlPalmen** [comment]
It does work with the string series logs. Only the single string logs such as the dates and "Test workspace" produce the zero.

**Comment by tom-perkins** [comment]
That's a good point, the same fix could be made to single string logs. I will do that now.

**Comment by tom-perkins** [comment]
Merged in `master` to fix release notes conflicts. The fix has also been applied to single string logs.

**Comment by KarlPalmen** [comment]
This one has conflict in the release notes (ui.rst).

**Comment by KarlPalmen** [comment]
This one has a merge conflict that can't be fixed by the issues of the PR, because the issuer has left.

**Comment by martyngigg** [comment]
@KarlPalmen We should aim to resolve these conflicts. They will be trivial if they are in the release notes.

**Comment by martyngigg** [comment]
@KarlPalmen I have resolved the conflict. Can you restest this?

**Comment by martyngigg** [comment]
I've retested this and it is good to go. Documentation test is unrelated - these are GUI only changes.

:shipit:

**Pull request merged**
