### PR TITLE
Rounding sample thickness display value

### LINKED ISSUE #22969: Sample thickness displaying float precision
Currently when the sample thickness is being read in from the nexus file it is undergoing a float32 to float64 conversion when stringified leading to some extra digits beyond the float precision.

### PR DESCRIPTION
**Pull request by Matthew-Andrew**
**Description of work.**
This rounds the sample thickness to 2 decimal places before displaying it.
**Report to:** steve 

**To test:**
* Get the data from #22949
* In the ISIS SANS GUI load USER_LOQ_181R_M3_Eastoe_8mm_Changer_MAIN.txt as the userfile
Load 

* Load batch_mode_reduction.csv as the batch file

Check that the sample thickness displays as 1.10

Fixes #22969. 

Does this update require release notes?
- [ ] Yes
- [x] No
This is fixing an issue with a feature added this release.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by NickDraper — APPROVED** [review]
It works!

**Comment by NickDraper** [comment]
image

**Comment by martyngigg** [comment]
It looks like there are some unit test failures here.

**Review by martyngigg — CHANGES_REQUESTED** [review]
Marking as request changes due to test failures.

**Review by martyngigg — APPROVED** [review]

**Pull request merged**
