### PR TITLE
13250 example saveascii python algorithm

### LINKED ISSUE #13250: Create example Python algorithm to save workspace in ascii format
This algorithm is intended only as a demonstration of saving a workspace in ascii format using python.

### PR DESCRIPTION
**Pull request by matthew-d-jones**
Closes #13250 

Added an example python algorithm which writes a workspace to file in ascii format. The algorithm serves only as a demonstration, the SaveAscii algorithm should ordinarily be used instead.
A documentation file with test is also added. The test writes the workspace obtained by CreateSampleWorkspace() to file and compares the first three lines of the file with what is expected.

### CODE REVIEW

**Comment by matthew-d-jones** [comment]
Pylint is failing on the algorithm class not having \__init__ defined, but this seems to be consistent with other python algorithm scripts.

**Comment by NickDraper** [comment]
@martyngigg Do you have any suggestions on the best approach here?

**Comment by martyngigg** [comment]
You can put `#pylint: disable=no-init` at the top of the file to ignore the warning

**Comment by matthew-d-jones** [comment]
Ah, I see that in other files now, thanks @martyngigg

**Pull request merged**
