### PR TITLE
Reorder export as batch keys to mirror sans table

### LINKED ISSUE #25538: Consistent order of SANS batch files
ISIS SANS has a button to export the table to a batch file. This batch file is a dictionary of fields and values, so the ordering of the fields is irrelevant. However, the export table button arranges the fields in a different order to the table itself. The scientists would like the batch file save order to mirror the table order, to avoid confusion.

### PR DESCRIPTION
**Pull request by TTitcombe**
**Description of work.**
Data in the ISIS SANS table can be exported as a batch file. This PR reorders how the data is written to a csv so that data terms in the batch file appear in the same order as in the table.

**To test:**
1. Interfaces -> SANS -> ISIS SANS
2. Type any data in any of first 7 columns of the table (numbers in the first 6, a name in "Output Name")  
3. Click `export table` (directly above the table) and save it
4. Open up the csv. Compare the order of the data labels with the order of the column titles in the ISIS SANS table. They should align. (The format of the batch file is key1 | value1 | key2 | value2 etc., so some columns will be empty if you didn't provide data in each table column)
5. Back in the ISIS SANS interface, highlight the row you populated and lcick the bin icon
6. Click `Load Batch File` in the upper right corner and select the csv file
7. This should populate the table with the row you created earlier

Fixes #25538 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Code looks good. The batch files save as described. However if you leave a column blank, then export the table, then attempt to load that table, an error will be thrown. I don't know if this is intentional or not.

**Comment by TTitcombe** [comment]
Was it the output name which was left blank, or any column? The output name bug should have been fixed in #25453

**Review by ghost — COMMENTED** [review]
It seems to be any column. For example exporting the following, with "Sample Direct" left empty:
image

Then loading that back in gives the following error:
image

Similar errors are raised for each column left blank.

**Comment by TTitcombe** [comment]
Oh, sorry, that's intended behaviour. If sample transmission/direct is defined then direct/transmission must also be defined. Same with can transmission/direct.

You should be able to: leave sample transmission and direct blank; leave can transmission and direct blank; leave all the cans blank; leave output name blank; or any combination of these

**Review by ghost — APPROVED** [review]
Looks good and works as described

**Pull request merged**
