### PR TITLE
SaveAscii2 - SpectrumMetaData algorithm property

### LINKED ISSUE #15623: SaveAscii to have Q and Angle values
Users in the Indirect group have been asking for a better SaveAscii that includes Q and Angle values for each spectra.
This could be implemented as an additional property on the current SaveAscii Algorithm. This would potentially also then require changes in the LoadAscii algorithm to compensate.

### PR DESCRIPTION
**Pull request by ElliotAOram**
The SaveAscii2 algorithm now has a new property `SpectrumMetaData`. This property enables additional meta data to be output to the ascii file. Currently the only valid inputs for the additional meta data are SpectrumNumber, Q and Angle.

**To test:**

Code review:
- The way I've implemented this might not be the best way. It's currently a map that is used to store the relevant SpecNo,Q and angle values which are then printed in the ascii file. If you can think of a better way of doing this, let me know.
- The `WriteSpectrumID` property is still in this algorithm. This can be duplicated by having `SpectrumNumber` in the SpectrumMetaData property and hence makes the `WriteSpectrumID` property somewhat redundant. It'd be good to hear thoughts on this as well.

Functional testing:
- Load in a workspace that has units of Q 
  - `irs26176_graphite002_red` is a possible data set
- Execute SaveAscii with the SpectrumMetaData of SpectrumNumber,Q,Angle (case should not matter)
- Show the detectors on the workspace you input to save ascii.
- Load the saved ascii file
- Ensure Angle(ascii) == Theta(det_table)
- Ensure `Q == Q`

Fixes #15623 

[Release Notes](https://github.com/mantidproject/mantid/blob/15623_SaveAscii_spectrumMetaData/docs/source/release/v3.7.0/framework.rst#id71)

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
I loaded irs26176_graphite002_red and then saved it to ASCII. I found for spectrum 1 that the 3 metadata saved in the order I written them in the new property. Scrolling down confirmed this for spectrum 2, 3 and 9. Loading the ASCII file showed only one detector and none of the metadata, but I expect this is merely because this work has not yet been applied to LoadASCII. Is there an issue for that?

**Comment by KarlPalmen** [comment]
I then tested for bad input. I responded with appropriate error message, if I added an invalid metadata type. If I missed out Q, I get "Error in execution of algorithm SaveAscii: Inconsistent spectra interval". This occurred again after I put Q back. I used WorkspaceIndexMin=0 ...Max=16.

**Comment by ElliotAOram** [comment]
@KarlPalmen there isn't an issue for this at the moment. This is because this has been requested by end users so they can take there data away and use it else where but they were being held back due to the lack of information about each spectra. I don't believe they ever intend to put it back in.
As for the error I'll look into that now

**Comment by KarlPalmen** [comment]
I did not get the error on a second run of the test.

**Comment by KarlPalmen** [comment]
It seems the error I found is minor and can be treated as a separate issue, if encountered again. :shipit:

**Comment by FedeMPouzols** [comment]
Looks like a useful option, and it's very well documented and tested.

**Pull request merged**
