### PR TITLE
Viridis colormap

### PR DESCRIPTION
**Pull request by AndreiSavici**
Added viridis colormap.

**To test:**
Plot something in sliceviewer, then change the colormap to viridis.

If you have matplotlib >1.5, the map was created using

```
import matplotlib.cm
v=matplotlib.cm.get_cmap("viridis")
import numpy as np
vir=(np.array(v.colors)*255).astype(int)
```

Not related to any issue

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by quantumsteve** [comment]
Would you add Viridis to the scrollbar in `Preferences->MD Plotting->Default color map`?

**Comment by quantumsteve** [comment]
@AndreiSavici @stuartcampbell Any updates on the cmake 3.5 packages for RHEL 6 & 7?

**Comment by stuartcampbell** [comment]
@quantumsteve They've been done for a while... 

https://copr-be.cloud.fedoraproject.org/results/sic/backports/epel-6-x86_64/00172613-cmake/
https://copr-be.cloud.fedoraproject.org/results/sic/backports/epel-7-x86_64/00172588-cmake/

**Comment by quantumsteve** [comment]
The RPM issues have been addressed by upgrading the build servers to CMake 3.5.

If all the builds pass, :shipit:

**Pull request merged**
