### PR TITLE
More OSX floating window issues

### LINKED ISSUE #17465: Some more OSX floating window problems
While working on project serialisation I realised I missed a few other window types that should be made floating in OSX.  #16912 , #16790 

### Expected behavior
Floating windows should stay on top of the main window in OSX

### Actual behavior
They disappear behind the main window. Currently culprits:
 - Script window
 - Algorithm dialogs
 - History window
 - VSI
 - Spectrum viewer

### Steps to reproduce the behavior
Open one of the offending windows

### Platforms affected
OSX

### PR DESCRIPTION
**Pull request by samueljackson92**
I missed a few interfaces in earlier issues. I believe this makes all interfaces consistent across Mantid. Floating windows in OSX will no always be on top of the main window and will not "disappear" behind the main window. The penalty we pay for this that Qt + OSX cannot have both a minimise and maximise button on the floating windows (despite trying all the flag combinations of flags...), so here we force the window to offer the minimise button.

**To test:**

The following windows should now properly appear as floating in OSX:
- Instrument View
- Spectrum viewer
- Slice viewer
- VSI
- Algorithm Dialogs
- Algorithm History window
- Scripting window

Fixes #17465 .

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
@OwenArnold or another othe Mac user, could you pick this up for testing please.

**Comment by OwenArnold** [comment]
I'll take a look at this.

**Comment by OwenArnold** [comment]
Would have been good to have avoided some of the duplication while setting the flags in these different locations, but otherwise works ok.

**Comment by OwenArnold** [comment]
:shipit:

**Pull request merged**
