### PR TITLE
Blocksize show data

### PR DESCRIPTION
**Pull request by peterfpeterson**
There was a bug in getting the right click menu working and showing the data in a table.

**To test:**

1. `LoadNeXusMonitors(Filename='TOPAZ_24989', OutputWorkspace='TOPAZ_24989')`
2. The right click menu should not crash mantid
3. "Show Data" should show a nice table

Spectrum 1 should have 30001 data points, Spectrum 2 should have 200002 data points.

*There is no associated issue.*

*Does not need to be in the release notes* because it is fixing a bug that was only recently introduced.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by AndreiSavici — APPROVED** [review]
Works as expected. I did not get any error now when I right click on the workspace. Plots are OK, the table is shown. However, there is no way in the table to see where the correct data has ended. For the example in the test, the first spectrum has only 30002 good bins. The x value after that is garbage. We should either force it to NaN or change somehow the background. Either way, just create an issue for next release

**Review by AndreiSavici — CHANGES_REQUESTED** [review]
Pete thinks he can fix things tomorrow.

**Comment by peterfpeterson** [comment]
There is still an open issue with "Color Fill Plot" which is actually a problem inside `MatrixWorkspaceMDIterator`. I am working on that as a separate PR.

**Review by AndreiSavici — APPROVED** [review]

**Comment by AndreiSavici** [comment]
Works, except color fill plot and slice viewer. @peterfpeterson  is working on those changes as a separate PR.

**Pull request merged**
