### PR TITLE
Migrate Vesuvio content from scripts repo to mantid repo

### LINKED ISSUE #14993: Move Vesuvio Scripts and Algorithms to mantid Repo
Scripts and algorithms currently used on Vesuvio are housed in the `mantidproject/scripts` repository. These need to be moved to the `mantidproject/mantid` repository. The associated tests will also need to be moved and all the tests must pass.

### LINKED ISSUE #14994: Rename VesuvioWorkflow to VesuvioCommands
The name `VesuvioWorkflow` has led to some misconceptions about what the script is designed to do. As such this script should be renamed to `VesuvioCommands`

### PR DESCRIPTION
**Pull request by ElliotAOram**
The algorithms and scripts relating to Vesuvio have been moved over from script repository to the mantid repository. Tests have been updated as required as well as data for these tests added. This issue also fixes #14994 so please ensure that VesuvioWorkflow is not mentioned in the code.
# To test
- Ensure that the unit and system tests related to these changes all run successfully.
- Ensure that the docs are built and hod some information about the algorithms
  - An additional issue will be opened to improve the documentation for these algorithms including workflow diagrams

Fixes #14993

[Release notes](docs/source/release/v3.7.0/indirect_inelastic.rst)

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by ElliotAOram** [comment]
All non Windows builds failed due to having different expected values in `VesuvioTOFFitTest` than those that were produced on Windows.

**Comment by ElliotAOram** [comment]
VesuvioTOFFit should now be working although some investigation into why these tests are different should be carried out. Although this is perhaps best handled in a separate issue

**Comment by martyngigg** [comment]
It's good that we now have these testable and much more easily distributable.

There are many improvements that we'll want to make before we consider them done but these can now be done with backup of the tests and will be addressed in future issues.

**Comment by martyngigg** [comment]
:shipit:

**Comment by FedeMPouzols** [comment]
The release note link is broken (it's a relative link and GitHub doesn't seem to handle that), but it looks good in the diff, as well as everything else.

**Pull request merged**
