### PR TITLE
Switch ConfigManager::getValue() to use boost optional return

### LINKED ISSUE #22647: Switch ConfigService::getValue to use optional<T>
Currently the config service returns an integer, either 0 or 1 to indicate whether the output parameter is populated.
This makes it a strong candidate for replacing with `boost::optional` and tidy up it's callers during maintenance

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**
Switch ConfigManager::getValue to use boost optional return instead of using `0/1` return value to indicate success.

This also allows us to use get value or default, tidying up a lot of callers

Additionally a specialisation was added for `bool` which can either accept `true`/`on` or `1` (the former being upper or lower case)

**To test:**

Ensure unit tests pass
Code review

Fixes #22647

Does this update require release notes?
- [ ] Yes
- [x] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by peterfpeterson — CHANGES_REQUESTED** [review]
Some minor changes to improve support for bools from `ConfigService` that you missed. The lines listed are the `getString` locations. Code nearby will need to be changed too.
* `ConfigService.cpp` L1705
* `MultipleFileProperty.cpp` L83
* `ConfigDialog.cpp` L964 and L969
* `ApplitcationWindow.cpp` L5018
* `CreateUserDefinedBackground.cpp` L174
* `InstrumentWidget.cpp` L268
* `MantidUI.cpp` L3830
* `FileFinder.cpp` L65
* Things that look at `datasearch.searcharchive` are comparing to a string not a bool and should be left unchanged.

Another pass through the list of properties in the [user docs](http://docs.mantidproject.org/nightly/concepts/PropertiesFile.html) would track down other things that should be changed.

In general, this is a good improvement.

**Review by peterfpeterson — APPROVED** [review]
I like the consistent means of specifying bool properties

**Comment by martyngigg** [comment]
@DavidFair There are some build issues - can you take a look?

**Review by peterfpeterson — APPROVED** [review]
This is ready to merge once the builds pass.

**Comment by martyngigg** [comment]
@DavidFair There seems to be a consistent test failure on OSX related to the multiple file property.

**Comment by martyngigg** [comment]
I'll pick this up now as David did not have time to look into it before he left.

**Pull request merged**
