### PR TITLE
Port Indirect Data Reduction

### LINKED ISSUE #25901: Port Indirect Data Reduction
### Description
Port the Indirect Data Reduction GUI to the Workbench. 
This will require vertical range selectors and an embedded contour plot.

### Platforms affected
All

### PR DESCRIPTION
**Pull request by robertapplin**
~~Merge #25879 First~~
----------------------

**Description of work.**
This PR ports the Indirect Data Reduction GUI.

**To test:**
**ISISEnergyTransfer:**
Use run-number `26176` -> `Run`
**ISISCalibration:**
Use run-number `26176` -> Tick `Create RES` -> `Run`
**ISISDiagnostics:**
Use run-number `26176` -> `Run`
**Transmission**
Sample: run number `26176`
Container: run number `26174` -> `Run`
**Symmetrise**
Input File: [irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2486896/irs26176_graphite002_red.zip)
Move the vertical lines on the graph slightly towards 0
Click `Preview`, then click `Run`
**S(Q,w)**
Input File: [irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2486896/irs26176_graphite002_red.zip) -> `Run`

**Moments**
Input File: [iris26176_graphite002_sqw.zip](https://github.com/mantidproject/mantid/files/2486919/iris26176_graphite002_sqw.zip) -> `Run`

Try moving the markers on the previewplots.

Fixes #25901

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gvardany** [comment]
@robertapplin There are merge conflicts now.

**Comment by robertapplin** [comment]
@gvardany Thanks, those merge conflicts should be fixed now

**Comment by DTasev** [comment]
@gvardany Do you have time to review this, or should I pick it up?

**Comment by gvardany** [comment]
@DTasev Please go ahead. I can check the ILL tab tomorrow.

**Review by dtasev — CHANGES_REQUESTED** [review]
It works pretty well! Just a few things:

I'm seeing a warning in the console output:
```
QObject::connect: No such signal MantidQt::MantidWidgets::RangeSelector::rangeChanged(double, double) in ../qt/scientific_interfaces/Indirect/ISISCalibration.cpp:135
```

The plots don't seem to react to `right click > plot tools > pan/zoom`.

There is also a few conflicts

**Comment by robertapplin** [comment]
@martyngigg do you know why the Pan/Zoom tools are not working?

**Comment by martyngigg** [comment]
@robertapplin I'm not sure. Do they work in the corrections interface?

**Comment by robertapplin** [comment]
@martyngigg No, they don't work on corrections either. Would it be best to fix this in a separate PR?

**Comment by martyngigg** [comment]
@robertapplin That sounds sensible. Most likely cause is that we've messed around with the mouse event filtering on the canvas when we were implementing the fit selectors? The `PreviewPlot` has an [eventFilter](https://github.com/mantidproject/mantid/blob/master/qt/widgets/plotting/src/Mpl/PreviewPlot.cpp#L247) that checks for mouse events. Perhaps the makers are interfering with this?

**Comment by robertapplin** [comment]
@martyngigg Ah you might be right, I have managed to fix the zoom tool. However I am not sure if the pan tool was working before as it was previously set to false even when it had been selected, do you know if this used to work?

**Comment by robertapplin** [comment]
@martyngigg Nevermind, I have fixed the pan tool too 👍

**Comment by martyngigg** [comment]
Good stuff :+1:

**Comment by robertapplin** [comment]
@DTasev  The pan and zoom tools should now be working. I have also decided that the Range and Single selectors should be invisible while these tools are selected as you can't move them anyway.

**Review by dtasev — CHANGES_REQUESTED** [review]
Looks better, the plots now correctly respond to Pan/Zoom. I noticed a few things:

#### ISIS Calibration
The 2nd plot, next to Resolution, doesn't have any lines by default, but changing the tool back to Pan and then back to None adds some lines that weren't there.

#### ISIS Diagnostics
The plot only has 2 lines after loading, but changing to Pan and then back adds 2 more.

#### S(Q, w)
The Run, Save Result, Plot Spectrum and Plot Contour buttons looks squished:
image

**Comment by robertapplin** [comment]
@DTasev Good spot, those should be fixed now 👍

**Review by dtasev — CHANGES_REQUESTED** [review]
A couple of minor comments, and this Qt warning started showing up:
```
ISISIndirectEnergyTransferWrapper-[Notice] ISISIndirectEnergyTransferWrapper started
Python-[Warning] Chop threshold not found in instrument parameters
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
```

to replicate I loaded into the ISIS Energy Transfer tab run: IRIS 26176, and pressed `Run`

**Comment by robertapplin** [comment]
I think that message is unrelated and can be fixed in a separate PR as I didn't change any algorithms. I also could not reproduce that `QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)` on windows

**Review by dtasev — DISMISSED** [review]
I think it's some event happening to update some part of the GUI, but I couldn't see a `QVector<int>` even used anywhere within `qt/scientific_interfaces/indirect` so I am not sure where that connection is. I'm happy for this to be in a separate PR

**Comment by NickDraper** [comment]
Builds aborted as there was nothing that could cause a failure from the release notes merge

**Pull request merged**
