### PR TITLE
Fix ISIS command iface expecting user file in batch

### LINKED ISSUE #27758: ISIS Command Interface Possible Regressed
### Expected behavior
The following script should succeed
```
# The following line helps with future compatibility with Python 3
# print must now be used as a function, e.g print('Hello','World')
from _future_ import (absolute_import, division, print_function, unicode_literals)
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np
from sans.command_interface.ISISCommandInterface import *
MASKFILE = FileFinder.getFullPath('USER_ZOOM_Mahmoudi_4m_sampleChanger_191F_12mm_Large_BEAMSTOP_M5.txt')
print(MASKFILE)
BATCHFILE = FileFinder.getFullPath('batchmod.csv')
print(BATCHFILE)
Clean()
ZOOM()
MaskFile(MASKFILE)
BatchReduce(BATCHFILE, format='.nxs', saveAlgs={"SaveCanSAS1D": ".xml"})
```
### Actual behavior
Produces error, looks like it's stripping the file path somewhere
```
IOError: [Errno 21] Is a directory: '/home/matthew/Documents/Mantid-python3/mantidBuild/ExternalData/Testing/Data/UnitTest/'
  File "/home/matthew/Desktop/batch_test.csv", line 20, in <module>
    BatchReduce(BATCHFILE, format='.nxs', saveAlgs={"SaveCanSAS1D": ".xml"})
  File "/home/matthew/Documents/Mantid/mantid/scripts/SANS/sans/command_interface/ISISCommandInterface.py", line 917, in BatchReduce
    use_reduction_mode_as_suffix=use_reduction_mode_as_suffix)
  File "/home/matthew/Documents/Mantid/mantid/scripts/SANS/sans/command_interface/ISISCommandInterface.py", line 789, in WavRangeReduction
    state = director.process_commands()
  File "/home/matthew/Documents/Mantid/mantid/scripts/SANS/sans/command_interface/command_interface_state_director.py", line 155, in process_commands
    state = self._process_command_queue(data_state)
  File "/home/matthew/Documents/Mantid/mantid/scripts/SANS/sans/command_interface/command_interface_state_director.py", line 265, in _process_command_queue
    process_function(command)
  File "/home/matthew/Documents/Mantid/mantid/scripts/SANS/sans/command_interface/command_interface_state_director.py", line 356, in _process_user_file
    new_state_entries = user_file_reader.read_user_file()
  File "/home/matthew/Documents/Mantid/mantid/scripts/SANS/sans/user_file/user_file_reader.py", line 41, in read_user_file
    with open(self._user_file) as f:
```

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**
Fixes the ISIS command interface expecting a user file to specified in the provided batch file

**To test:**
- Run the script attached to the original issue

Fixes #27758 

*This does not require release notes* because it has only been noticed by a developer (future users could run into it though and it's not obvious the problem, hence fixing it now)

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Mantid-Matthew** [comment]
RuntimeError: CommandInterfaceStateDirector: Setting the lower and upper wavelength bounds is not possible. We require also a step and step range
  File "/home/matthew/Desktop/TypeHintExamples.py", line 26, in <module>
    BatchReduce(BATCHFILE, format='.nxs', saveAlgs={"SaveCanSAS1D": ".xml"})
  File "/home/matthew/Documents/Mantid/mantid/scripts/SANS/sans/command_interface/ISISCommandInterface.py", line 932, in BatchReduce
    use_reduction_mode_as_suffix=use_reduction_mode_as_suffix)
  File "/home/matthew/Documents/Mantid/mantid/scripts/SANS/sans/command_interface/ISISCommandInterface.py", line 803, in WavRangeReduction
    state = director.process_commands()
  File "/home/matthew/Documents/Mantid/mantid/scripts/SANS/sans/command_interface/command_interface_state_director.py", line 155, in process_commands
    state = self._process_command_queue(data_state)
  File "/home/matthew/Documents/Mantid/mantid/scripts/SANS/sans/command_interface/command_interface_state_director.py", line 265, in _process_command_queue
    process_function(command)
  File "/home/matthew/Documents/Mantid/mantid/scripts/SANS/sans/command_interface/command_interface_state_director.py", line 532, in _process_wavrange
    raise RuntimeError("CommandInterfaceStateDirector: Setting the lower and upper wavelength bounds is not"

**Comment by Mantid-Matthew** [comment]
I get the stacktrace above when I try to run the script provided in the issue.

**Comment by DavidFair** [comment]
So looking at this there are a couple of things going on:

- An incorrect batch file with a user_file column (that's blank) was used during testing
- Fixing this incorrect file would in effect break the system tests (and API), since the more strict check required the user to call `MaskFile` for each row (or populate them)

With a correct batch file it appears to work correctly, whilst an incorrect batch file will fail the reduction (as shown above). 
Testing locally and discussing this with Matthew I think it should work with the `user_file` column (which was blank) removed. Could you check locally?

**Review by Matthew-Andrew — APPROVED** [review]
Code changes look good and the original issue is now fixed. 

Build failure is unrelated and on master already.

**Pull request merged**
