### PR TITLE
Detect add files without using -add extension

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**
Detects add files without using the -add extension. This allows us to:

- Specify an added file without requiring the -add extension
- Load event nexus data that isn't added
- Refactor to some minor extent.

This enables us to next handle event data for transmission runs. For example SANS2D123-add and SAND2D-asdf will both be accepted

**To test:**
- Go to the unit test data direction (build/ExternalData/Testing/Data/UnitTest)
- Copy out `ZOOM9947-a` or set your data directory to the above
- Open the ISIS Sans Interface in Mantid
- Open the following user file
[USER_ZOOM[snip].txt](https://github.com/mantidproject/mantid/files/6305704/USER_ZOOM_Schoofs_4m_SampleChanger_193B_5x2mm_Small_BEAMSTOP_M5Trans_StandardOnly.txt)
- Enter `ZOOM9947-a` for the first 3 ~rows~ columns, hit process row
- The following error should appear and is expected (PR two resolves it): 
- `Cannot load event-mode data for transmission calculation`
- Try renaming ZOOM9947 to some other names including `ZOOM9947-add` they should all give the same above error

Part of #27482

*This does not require release notes because it doesn't fully resolve the problem. The follow-up PR will complete the work and include release notes*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DanielMurphy22 — COMMENTED** [review]
It took me a wee while to figure out what this PR was achieving, but it is very nice now that added runs are detected without the naming extension being required. Your comments in the code were very useful!!

If the file is named `ZOOM9947.nxs` and the input to the table is `ZOOM9947-a` should that work??? In this case it complains that `Unable to find file: search object ZOOM9947-add`.
It does work however if the input to the table is `ZOOM9947` or `ZOOM9947-add`.

Also, sorry to nitpick your words in the description, but pretty sure you meant "Enter `ZOOM9947-a` for the first 3 *columns*" rather than rows.

Overall I'm happy with this, I get the error message as you stated, and I'm happy to approve when the conflict is resolved!

**Comment by DavidFair** [comment]
> If the file is named `ZOOM9947.nxs` and the input to the table is `ZOOM9947-a` should that work??? In this case it complains that `Unable to find file: search object ZOOM9947-add`.

Hmm, yes that should work, it's a separate problem to this PR but essential makes it useless. I'm surprised as this works for me though, I wonder if the test-pr command is broken due to the merge conflict. I need to commit my current work before attempting to fix the conflict though so I'll get that resolved towards the end of the day

> Also, sorry to nitpick your words in the description, but pretty sure you meant "Enter ZOOM9947-a for the first 3 columns" rather than rows.

Yeah haha, that's what I get for writing a PR at 8PM "quickly", sorry about that

**Comment by DanielMurphy22** [comment]
> Hmm, yes that should work, it's a separate problem to this PR but essential makes it useless. I'm surprised as this works for me though, I wonder if the test-pr command is broken due to the merge conflict. I need to commit my current work before attempting to fix the conflict though so I'll get that resolved towards the end of the day

Happy to call at some stage to understand why this case isn't working for me!

**Comment by DavidFair** [comment]
@DanielMurphy22 I've resolved the merge conflict if you want to give it another spin. At least locally my system tests and GUI testing in this PR (TODO create it in a second) rely on the fact we use files like `123-histo` and `123-event` despite being added files 

I wonder if this is a Window / Linux + Mac filesystem problem, what OS are you on as I'm testing on Linux?

**Comment by DanielMurphy22** [comment]
> I wonder if this is a Window / Linux + Mac filesystem problem, what OS are you on as I'm testing on Linux?

I'm on Ubuntu, so maybe I'm just confused!

**Comment by DavidFair** [comment]
Could you check to see the file is in one of your data search directories, I've just retested and it works for me still

**Review by DanielMurphy22 — APPROVED** [review]
My misunderstanding! This is ready to go!

**Pull request merged**
