### PR TITLE
Add support for NeXus files in LoadVesuvio

### LINKED ISSUE #18843: LoadVesuvio does not work with NeXus files
Bug report from Giovanni:

### Actual behavior

I was trying to use "LoadVesuvio" to load the first calibration runs we could measure this evening, but I am getting the following strange error:

Error in u_len value read from file, it would be -26; where it is calculated as u_len = ad_data - ad_user - 2, where ad_data: 0, ad_user: 24
Error in execution of algorithm LoadVesuvio:
Inconsistent value for the field u_len found
at line 146 in 'C:/MantidInstall/plugins/python/algorithms\LoadVesuvio.py'
caused by line 232 in 'C:/MantidInstall/plugins/python/algorithms\LoadVesuvio.py'
caused by line 558 in 'C:/MantidInstall/plugins/python/algorithms\LoadVesuvio.py'
caused by line 609 in 'C:/MantidInstall/plugins/python/algorithms\LoadVesuvio.py'
caused by line 926 in 'C:\MantidInstall\bin\mantid\simpleapi.py'

My guess is that this has to do with the change in the names of the VESUVIO runs from EVS***** to VESUVIO********. However, the "Load" command works normally..

Could you please have a look. The last run I was trying to load is 25999.

### Platforms affected

All

### PR DESCRIPTION
**Pull request by martyngigg**
Description of work.

Uses `Load` in `LoadVesuvio` so that it can use either `.raw` or `.nxs` files. 

**To test:**

This will need to be tested at ISIS with access to the data archive.

Run `25999` uses the new long naming convention and is a standard 6-period file - this should now load with `LoadVesuvio`.

Also check older files still load, i.e ones prefixed `EVS`

Fixes #18843 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by louisemccann — APPROVED** [review]

**Comment by louisemccann** [comment]
LGTM :shipit:

**Comment by martyngigg** [comment]
Please don't merge this yet - I think the documentation test is a real failure

**Comment by martyngigg** [comment]
@louisemccann Could you check this again after the builds finish?

**Comment by martyngigg** [comment]
@louisemccann Could you double-check this again now?

**Comment by louisemccann** [comment]
Able to load old and new files, :shipit:

**Comment by martyngigg** [comment]
Thanks

**Comment by martyngigg** [comment]
The test failures on OSX are unrelated. They are the currently unstable MantidPlot tests.

**Pull request merged**
