### PR TITLE
Version 2 of LoadSQW

### LINKED ISSUE #11056: LoadSQW will fail when loading sqw file with image not aligned with lab frame
This issue was originally [TRAC 10214](http://trac.mantidproject.org/mantid/ticket/10214)

subj. 

Currently LoadSQW will not load a sqw file with DND image not aligned according to "lab frame ?" coordinates (not sure the term is correct). The pixels (MD events) in SQW file are expressed in these coordinates. 

The algorithm will formally work, but the result will be incorrect. 

The purpose of the ticket is to modify load SQW to load data properly.

### PR DESCRIPTION
**Pull request by martyngigg**
Fixes #11056

**Tester**
This version should match the output of `LoadSQW` v1 when the `Q3DFrames` property is set to `Q_sample.` Unfortunately `CompareMDWorkspaces` is not helpful here as the metadata such as dimension names have been changed to be more representative of the output generated and to match `ConvertToMD`. You can use the `test_horace_reader.sqw` file along with `BinMD` to convince yourself that the output is the same.

Release notes for 3.7 need to be been updated after the release.

### CODE REVIEW

**Comment by martyngigg** [comment]
@abuts I've made those changes around the splitting. Let me know what you think.

**Comment by abuts** [comment]
As far as I see, a minor thing left:
```C
     ++chunksRead;
    if (chunksRead == NCHUNKS_SPLIT) {
      splitAllBoxes();
    }
```
Is not nullifying chunksRead==NCHUNKS_SPLIT reached first time, it does not seems work any more 
nullifying chunksRead or making other counter would help.

**Comment by martyngigg** [comment]
Nice catch. I'll fix it

**Comment by martyngigg** [comment]
@abuts That bug should be fixed now

**Comment by abuts** [comment]
when I try to load fe_demo.sqw from Horace demo, it fails with: 
```
Time to setup box structure: 2.106s
    npixtot: 89026560
Memory: 42359748 (free), 50329176 (total).
Error in execution of algorithm LoadSQW:
Matrix::operator*(V3D) Item A!=B 0 3 
```
LoadSQW v1 works and produces reasonable result

**Comment by martyngigg** [comment]
@abuts I've looked at the issue of loading `fe_demo.sqw`. It seems like one (or more) of the pixel fields has a `0` in the `irun` field. This version of `LoadSQW` uses the `irun` field to lookup how to transform the pixel coordinates to the request output frame. What should be done for invalid values in these cases?

**Comment by abuts** [comment]
@martyngigg  This may indicate problem in Horace I have not noticed. I am investigating this issue. 

LoadSQW should report incorrect SQW file on warning level (pixel N has run index == 0) and reject suspicious pixel(s). I wander how can Horace handle this.

**Comment by martyngigg** [comment]
@abuts I've added checks for the invalid pixels.

I also regenerated `fe_demo.sqw` after updating my version of Horace. I ran

```python
LoadSQW(Filename='fe_demo.sqw', Q3DFrames='HKL', OutputWorkspace='fe_demo_hkl_v2')
BinMD(InputWorkspace='fe_demo_hkl_v2', AlignedDim0='[H,0,0],-3,3,120', AlignedDim1='[0,K,0],-3,3,120', 
           AlignedDim2='[0,0,L],-0.1,0.1,1', AlignedDim3='en,0,700,44', OutputWorkspace='q3d_cut_hkl')
```
and this gives me

fe_demo_3dcut

in the slice viewer. Did you mean doing the cut in Horace and loading that or doing the cut with `BinMD`?

**Comment by abuts** [comment]
First picture is 3D cut in Horace, loaded using LoadSQW. Second picture -- the same loaded 3D cut binned by BinMD to improve accuracy.

**Comment by martyngigg** [comment]
Has `LoadSQW` ever been able to load Horace cut-type objects? I ran `save(cc3, 'fe_demo_3d_cut.sqw')` in Horace and `LoadSQW` v1 hangs and v2 gives me an error that the unit cell is not initialized.

Have I done something wrong in Horace?

**Comment by abuts** [comment]
V1 was not and this what was unsatisfactory about it and the point of the (my) ticket. In most cases image is randomly oriented vrt. the crystal Cartesian coordinate system and most peoples do crustal realignment, where the misalignment of the crystal Cartesian (pixels coordinate system) is fixed by adjustment of the matrix, describing the image. as MD workspace does not have such possibility, the correct alignment should be better brought from the beginning.

**Comment by martyngigg** [comment]
Is there anything different about how a cut is saved in Horace. Should we be creating a `MDHistoWorkspace` or `MDEventWorkspace`?

**Comment by abuts** [comment]
Horace SQW object is the combination of histo and MD workspace. As MDWS is more generic object so we should create MDWS.

A Horace SQW object has two coordinate systems -- one is kind of "Crystal Cartesian" or I believe kind of "lab frame" aligned with the beam, which never changed and defined at sqw generation -- pixels are always in this coordinates, and another one is HKL, lab or whatever (I am not sure what aar or rrr or what possible combinations of these options for projection are possible). It can be realigned if decided that initial coordinate system was not aligned properly, to obtain e.g. true HKL, so generally it is randomly oriented wrt the pixels and reflects the physical problem.   When any physical operation is performed, which involves pixels, they are recalculated into the coordinate system, defined by projection you provide. 

This approach is fast and allows much grate flexibility than MDWS, but decision to go Mantid way was taken from other considerations.

**Comment by abuts** [comment]
It is actually a good question if one wants MD workspace read from sqw have hkl or random coordinate system, related to sqw's DND object. May be user should get choice on that, if both options work with later operations. hkl, from other hand, may simplify later operations and despite need to do sample realignment again may be preferred option. I can not choose. But lower dimensions sqw cuts should be readable in any case.

**Comment by martyngigg** [comment]
@abuts When you have time this should be ready to test again.

**Comment by martyngigg** [comment]
@abuts I've improved the progress reporting as we discussed

**Comment by abuts** [comment]
Work as described and huge improvements  wrt. Owen's version.
Number of additional improvements still can be done, the changes are big and good enough to build on the basis of them.

**Pull request merged**
