### PR TITLE
Poisson

### LINKED ISSUE #14490: Add Poisson cost function
The correct cost function formula for Poisson statistics should be (for bin contents=N, fitted mean count rate=y)
y<0: forbidden (infinite cost)
y>=0, N=0: cost function=2_y
y>=0, N>0: cost function=2_( (y-N) + N*(log(N)-log(y)) )

### PR DESCRIPTION
**Pull request by mantid-roman**
**Description of work.**
This PR adds a new Poisson cost function. To achieve this the cost function concept has been abstracted. 

**To test:**
Load some muon data and plot a few spectra
Fit to the spectra using least squares and poisson cost functions
The parameters should be similar but different. 

Fixes #14490. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@AnthonyLim23 @NickDraper Do you know anything about this? There's no issue and as Roman has now left there is no one to pick it up. Was it an experiment or something that had a requirement from somewhere?

**Comment by AnthonyLim23** [comment]
This is something that the muon group has been asking for. They have low counts so a poisson fit is better for them. I know that James was testing it for Roman, but not heard anything else since.

**Comment by AnthonyLim23** [comment]
Left to do:

1. Write unit tests for the new cost function (there is a file for it just needs tests adding)
2. Add to release notes
3. Add documentation #

**Comment by AnthonyLim23** [comment]
James has used this and said he cannot find any obvious problems.

**Comment by NickDraper** [comment]
@DavidFair Could you pick up the developer role on this PR and add some unit tests

**Comment by DavidFair** [comment]
Closing as this is a PR (from a fork) in favour of #26755

**Pull request closed without merging**
