### PR TITLE
Add journal search to Reflectometry GUI

### LINKED ISSUE #26897: Investigate ICat problems and possible alternatives
ISIS Reflectometry users continue to report problems with ICat. This can be especially severe over weekends and into the early week. Apparently when reported the response is that ICat has had ingestion problems and that it will catch up in a day or two (which it does) but this is too late for a live experiment.

For reflectometry at the moment, all we need is the run number and title for all runs in an investigation and we require these as soon as possible after the run is complete. We may be the only group using ICat in this way.

This issue is to investigate whether ICat can be improved or whether we can/should use another method instead, e.g. that used by JournalViewer. Some investigation was done by Edward and I believe he found a way that would be quick and simple to get this metadata. I will look up the details and add them to this issue.

I've marked this as high priority as it underpins the automation that the reflectometry GUI provides so largely negates new functionality that has been added in recent years if it doesn't work reliably.

### PR DESCRIPTION
**Pull request by gemmaguest**
**Description of work.**

This PR adds a second method for finding metadata about runs in the ISIS Reflectometry GUI. It adds a method to the `QtCatalogSearcher` class to perform the search using `ISISJournalGetExperimentRuns` rather than `CatalogGetDataFiles`. This is required because the latter uses ICat, which is currently unreliable.

The journal search means we need to know the cycle name. This method is used if the cycle name is provided, and ICat is used if it is not. We may want to change this in future (and possibly improve functionality to provide a drop-down list of cycle names) but this is sufficient for a first cut at this functionality.

This PR also:
- Cleans up the `SearchModel` class so that metadata is parsed and errors set on construction (this logic has been moved out of `RunsPresenter`).
- Remove the Location field from the search results list because this isn't used.
- Clean up usage of `ITableWorkspace` - confine this to `QtCatalogSearcher`.

**Report to:** Max at ISIS

**To test:**

Must be tested by someone at ISIS. Ensure you have Search Data Archive enabled in the Manage User Directories dialog.

- Open the ISIS Reflectometry interface.
- Check that the new "Cycle" input is available on the Runs tab.
- Try performing a search with or without specifying the cycle, e.g. `INTER`, investigation `1920400`, cycle `19_4`. If the cycle is missing, you will be prompted for an ICat login -> although note that if you login here it will crash (fix coming in PR #28488). To get around this, run the `CatalogLogin` algorithm separately first to avoid the login via the GUI. Then the ICat search should work.
- When you click Search the list of runs for this experiment should be populated in the search results box. The results should be the same as the list you get from the `ISISJournalGetExperimentRuns` algorithm.
- Any runs without `th=` in the title (which specifies the angle) should be highlighted blue.
- Select some items in the results list and click `Transfer`. They should appear in the table on the right (you may need to expand the groups to see them), unless they are blue (invalid) rows in which case they will not be transferred.
- Click `Autoprocess` (and OK the warning if you get one). All valid rows should be transferred to the main table and will start processing. Ensure that the Cycle input is greyed out during processing. Note you must click Pause before to stop autoprocessing before you can exit the GUI.

Fixes #26897 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gemmaguest** [comment]
@rprospero This is ready for review now

**Review by alicerussell1 — CHANGES_REQUESTED** [review]
This works really well, search with the journal seems to be much more reliable and avoids having to log into ICat. Just a small thing if the id or the cycle are not found it just does nothing which makes it look like it hasn't searched for it. It would be useful to have an error or warning to say it has not been found?

**Comment by gemmaguest** [comment]
> 
> 
> This works really well, search with the journal seems to be much more reliable and avoids having to log into ICat. Just a small thing if the id or the cycle are not found it just does nothing which makes it look like it hasn't searched for it. It would be useful to have an error or warning to say it has not been found?

Good point - I've raised #28727 for this because we could use some other improvements around this area to do it properly, and it's beyond the scope of this PR.

**Comment by gemmaguest** [comment]
I'll fix the conflicts...

**Review by alicerussell1 — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
