### PR TITLE
NormaliseToMonitor blocksize fix

### PR DESCRIPTION
**Pull request by peterfpeterson**
It was discovered that for TOPAZ data that was just loaded, `NormaliseToMonitor` was raising an error:
```
ExtractSpectra-[Error] blocksize undefined because size of histograms is not equal
```
This PR addresses that issue.

**To test:**

Try running the following scripts without and with this PR.
```python
S=Load("TOPAZ_15629",LoadMonitors=True)
S=NormaliseToMonitor(InputWorkspace='S',MonitorWorkspace='S_monitors')
```

```python
S=Load("TOPAZ_15629",LoadMonitors=True)
S=NormaliseToMonitor(InputWorkspace='S',MonitorWorkspace='S_monitors',
      MonitorWorkspaceIndex=1)
```

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by VickieLynch** [comment]
Works for my needs, but Andrei suggested trying normalizing by the other monitor:
S=Load("TOPAZ_15629",LoadMonitors=True)
S=NormaliseToMonitor(InputWorkspace='S',MonitorWorkspace='S_monitors',MonitorWorkspaceIndex=1)
RuntimeError: Histogram::setSharedX: size mismatch

**Review by VickieLynch — COMMENTED** [review]
Everything connected to blocksize is fixed and works correctly. I am looking now to see why the output of the normalized events is the same as the input.  If I bin the workspace, the histograms are changed with normalization.

**Review by VickieLynch — APPROVED** [review]
When warning is removed, this is ready to merge.  I read the documentation and I should have been setting 
integration ranges for the event workspaces.  Thanks Pete for the quick fix of this problem.

S=NormaliseToMonitor(InputWorkspace='S',MonitorWorkspace='S_monitors',IntegrationRangeMin=1000,IntegrationRangeMax=16666)

**Comment by peterfpeterson** [comment]
Resolving the conflict requires re-testing this PR. The next push should be finished, but @VickieLynch should try it out again.

**Review by VickieLynch — APPROVED** [review]
Works after changes for merge

**Pull request merged**
