### PR TITLE
Reduce precison of startx and endx

### LINKED ISSUE #34399: Indirect Data Analysis datatable startX and endX not showing full values.
In indirect Data analysis fit tabs the startX and endX columns do not show the decimals of the values if the trailing values are too long. e.g. `1.11111111111` will display as `1. ...` unless the column is resized to fit the whole value.

### PR DESCRIPTION
**Pull request by MohamedAlmaki**
**Description of work**
This PR fixes the StartX and EndX columns in the indirect data analysis data table.

**Purpose of work**

To make the number appear clearer in the indirect data analysis data table.

**Summary of work**

The precision of the columns has been reduced 

**Further detail of work**

The precision of the columns has been decreased so that they display properly. Before, there were trailing dots because the numbers were too long.

**To test:**
1- Go to Interfaces > Indirect > Data Analysis
2- Go to the Conv Fit tab
3- Click Add Workspace
4- With the combo boxes set to File
5- Click browse and load the irs26176_graphite002_red.nxs file from the sample data
6- Click browse and load the resolution file irs26173_graphite002_res.nxs from the sample data
7- Click Add and close the dialogue.
8- You should see that StartX and EndX have 6 figures precision. 

Fixes #34399. 

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by robertapplin** [comment]
I can confirm the Start and End X's are to 6 decimal places. I just want to check, is it ok that I can type in more than six decimal places? And I can also enter letters into the Start and End X fields?

image

**Comment by robertapplin** [comment]
Off the top of my head, I can't remember. But I think the way to go is to use a `DoubleItemDelegate`. I think some of the Muon interfaces do some Double validation inside a table:

https://github.com/mantidproject/mantid/blob/d623f2a798fb5cf1efe80879ab697272024b761a/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/utilities/table_utils.py#L202

Do you want to investigate as a separate PR?

**Comment by MohamedAlmaki** [comment]
I think it is better to resolve this in another PR

**Review by robertapplin — APPROVED** [review]
Looks good, there is only 6 decimal places for the start and end x

**Comment by MohamedAlmaki** [comment]
issue raised [here](https://github.com/mantidproject/mantid/issues/35714)

**Pull request merged**
