### PR TITLE
Vesuvio - update test values to peak height and bin index

### LINKED ISSUE #16065: Vesuvio - Update values that are being tested
Many of the Vesuvio tests are testing the first and last bin of the data. This is good to ensure that the data doesn't change expectedly when we change the algorithm. When testing Vesuvio data (especially when using fitting) it would be good to replace testing the first/last bin with testing the maximum height of the data and the corresponding bin as this data is much more meaningful than simply testing the first and last bin which are mostly likely just background noise. 

The tests that require updating are:
* [x] VesuvioCommandsTest
* [x] VesuvioPreFitTest
* [x] VesuvioCorrectionsTest
* [x] VesuvioTOFFitTest

### PR DESCRIPTION
**Pull request by ElliotAOram**
The unit and system tests for `VesuvioPreFit`, `VesuvioTOFFit` and `VesuvioCorrections` have all been updated to check the value for bin index as well as peak height as this data is more meaningful than checking the first and last bin. These tests have been run on Windows 7 and Ubuntu 14.04 and build servers should check RHEL7 (system tests) and RHEL6 unit tests

**To test:**
- Ensure the unit and system tests pass on the build servers.
- Code review to ensure the changes seem like a sensible change for the tests

Fixes #16065

_Concerns testing therefore does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
Agreed that these are more sensible tests as we really care where the peak ends up and how big it is - we don't care about the noise.

**Comment by martyngigg** [comment]
@ElliotAOram The branch has developed a merge conflict

**Comment by ElliotAOram** [comment]
@martyngigg this should be good to go now (providing tests pass).

**Comment by martyngigg** [comment]
This is good to go now.

:shipit:

**Pull request merged**
