### PR TITLE
Fix issues with workbench plotting with matplotlib 3.1

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Windows/Mac are now shipping matplotlib 3.1 with Python 3. A few issues have cropped up preventing plotting from working. This fixes them and sneaks in a packaging fix for Python 2 (the last commit). 

**To test:**

Build the workbench with Python 3 on Windows.
Start workbench and plot something.
The plot should work and there are no warnings.

*There is no associated issue.*

*This does not require release notes* because **Python 3 support will be announced separately.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DanielMurphy22** [comment]
This isn't a Windows Only issue. Workbench plotting doesn't work on MacOS either.

**Comment by martyngigg** [comment]
Thanks @DanielMurphy22. I think this should fix both issues.

**Comment by gvardany** [comment]
This seems to have fixed the original issue with the buttons attribute, but there is another one on macOS.
Screenshot 2020-01-15 at 09 15 16

**Comment by martyngigg** [comment]
Thanks @gvardany. I wonder why my plot worked. Did you plot from a script or the menu?

**Comment by gvardany** [comment]
The context menu.

**Comment by gvardany** [comment]
Apparently changing https://github.com/mantidproject/mantid/blob/master/Framework/PythonInterface/mantid/plots/__init__.py#L504 to `set_draggable(True)` fixes the problem. So one should branch on the mpl version there.

**Comment by martyngigg** [comment]
> Apparently changing https://github.com/mantidproject/mantid/blob/master/Framework/PythonInterface/mantid/plots/__init__.py#L504 to `set_draggable(True)` fixes the problem. So one should branch on the mpl version there.

Thanks!

**Comment by martyngigg** [comment]
There were a few places where draggable was used so I've created a helper function to put the check in a common place.

**Comment by martyngigg** [comment]
I think this should be ready to review again now.

**Comment by gvardany** [comment]
Looks fine on macOS now 👍

**Review by PhilColebrooke — COMMENTED** [review]
A few things I've found:
- Upon opening Workbench I get this error in the log: ```"is" with a literal. Did you mean "=="?```.
- A warning after plotting and opening figure options: ```an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.```
- Right-clicking a workspace and doing Plot -> Colorfill: ```AttributeError: 'MantidAxesSubplot' object has no attribute '_hold'```

But otherwise plotting works fine so I wonder if these things should be done in separate issues to allow this PR to be merged.

**Comment by martyngigg** [comment]
Thanks both.

@PhilColebrooke I agree. I will make a separate issue for those problems.

**Review by PhilColebrooke — DISMISSED** [review]

**Comment by martyngigg** [comment]
@PhilColebrooke The `_hold` problem with colorfill plots was trivial so I've pushed it up here. Could you re-review that bit? Thanks.

**Review by PhilColebrooke — APPROVED** [review]
Colourfill plots are working now.

**Pull request merged**
