### PR TITLE
Gsas2 tab outputs Reflections and Instrument parameters

### LINKED ISSUE #34512: EngDiff: Add to the workspaces the GSASII tab outputs
Requested feedback from Saurabh

**Describe the solution you'd like**
Want the following outputs from GSASII tab in EngDiff interface:
- Add to the current output Table Workspace:
   - Microstrain value (no unit)
   - Sigma-1 and Gamma (Y) values
   - x fitting range
   - mark which parameters were refined

- output reflections to a table workspace separately
- output sample logs in a workspace group like currently in the fitting tab (controlled by settings).

### PR DESCRIPTION
**Pull request by DanielMurphy22**
**Description of work.**
Superceeds part of work in #34709

Added a reflections table workspace, instrument parameters table workspace and more columns to the lattice parameters table workspace when a successful refinement is run on the EngDiff GSASII tab.

**To test:**
On the Calibration tab, create new with `/archive/ndxenginx/Instrument/data/cycle_19_1/ENGINX00305738.nxs`
On the Focus tab use:
```
# Sample Run 
/archive/ndxenginx/Instrument/data/cycle_19_1/ENGINX00305761.nxs
# Vanadium
/archive/ndxenginx/Instrument/data/cycle_19_1/ENGINX00307521.nxs
```

Then move to the gsas2 tab where, Insturment Group and Focused data are prefilled. Set Phase to `mantid/scripts/Engineering/ENGINX/phase_info/FE_GAMMA.cif` and make sure to add a project_name near the top.

Click Refine and the output workspaces should include:
```
project_name_GSASII_instrument_parameters
project_name_GSASII_lattice_parameters
project_name_GSASII_reflections
```
Run refinements with different things refined (mustrain, sigma and gamma) and check the tableworkspace titles update accordingly.
Fixes #34512

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DannyHindson — CHANGES_REQUESTED** [review]
It seems to be the case that my change to get the GSAS call working in PyCharm debug mode on Windows requires a .exe extension to be added to the python executable. The subprocess call only seems to require the extension when the executable is supplied in the `executable` parameter - for some reason it added the .exe extension itself when the executable name was the first part of the command string. So you also need a change here in gsas2\model.py:
```
        if platform.system() == "Windows":
            gsas2_python_path = os.path.join(self.path_to_gsas2, "python.exe")
```

I must have had this change locally when I was trying to find a solution but forgot to include it when I sent the other changes over via Slack.

**Review by DannyHindson — COMMENTED** [review]
All looks fine apart from that

**Review by DannyHindson — APPROVED** [review]
This all looks good now. I've noticed two things unrelated to this change that you could maybe pick up separately?
1) #34827 There are some warning written to the log when it's at "info" level like this. Think I mentioned these before but never recorded in an issue:
image

2) When you click the Load button on the Calibration tab it populates the "Instrument Group" field with a path to a .prm file on the GSAS II tab. If you click Load twice it puts the same path into "Instrument Group" twice which gives an error when you hit Refine. This sounds obscure but it's happened to me once or twice. I must have hit Load more than once because I wasn't sure if it had loaded the calibration. #34829

**Comment by DanielMurphy22** [comment]
Thanks for the review, I've raised issues for the 2 separate issue you mention which I can reproduce on main. #34827 #34829

**Pull request merged**
