### PR TITLE
fix scd calib issues

### PR DESCRIPTION
**Pull request by VickieLynch**
Description of work.
Fixes the following problems found by instrument scientist:
When lattice parameters are entered, the calibration is worse.
Ignore peaks on edges with parameter EdgePixels.
XML output not correct from parallel region (XmlFilename)

**To test:**
https://www.dropbox.com/s/uv3c4t6pddch458/Si2mm_Cubic_F_I_20.integrate?dl=0
https://www.dropbox.com/s/ozciwztjyig7rm7/Si2mm_Cubic_F.mat?dl=0

``` Python
LoadIsawPeaks(Filename='Si2mm_Cubic_F_I_20.integrate', OutputWorkspace='Si2mm_orig')
LoadIsawUB(Filename='Si2mm_Cubic_F.mat', InputWorkspace='Si2mm_orig')
num,err=IndexPeaks(PeaksWorkspace='Si2mm_orig',RoundHKLs=False)
print "Original peaks file: number indexed, error indexing = ", num,err
wksp=mtd['Si2mm_orig']
lattice = wksp.sample().getOrientedLattice()
print "lattice, errors = ", lattice.a(),lattice.b(),lattice.c(),lattice.alpha(),lattice.beta(),lattice.gamma(),lattice.errora(),lattice.errorb(),lattice.errorc(),lattice.erroralpha(),lattice.errorbeta(),lattice.errorgamma()
print "U = ",lattice.getU()
print "B = ", lattice.getB()
LoadIsawPeaks(Filename='Si2mm_Cubic_F_I_20.integrate', OutputWorkspace='Si2mm')
SCDCalibratePanels(PeakWorkspace='Si2mm', a=5.430710,b=5.430710,c=5.430710,alpha=90,beta=90,gamma=90,
    useL0=True, usetimeOffset=True,usePanelWidth=True, usePanelHeight=True, usePanelPosition=True, usePanelOrientation=True, RotateCenters=False,
    AllowSampleShift=False, DetCalFilename='TOPAZ_Si2mm.DetCal', ResultWorkspace='LMResults', XmlFilename='TOPAZ_Si2mm.xml', 
    ColWorkspace='LMCol', RowWorkspace='LMRow', TofWorkspace='LMTof', NumIterations=20,EdgePixels=20,CellType="Cubic")
num,err=IndexPeaks(PeaksWorkspace='Si2mm',RoundHKLs=False)
print "MANTID optimized peaks file: number indexed, error indexing = ", num,err
wksp=mtd['Si2mm']
lattice = wksp.sample().getOrientedLattice()
print "lattice, errors = ", lattice.a(),lattice.b(),lattice.c(),lattice.alpha(),lattice.beta(),lattice.gamma(),lattice.errora(),lattice.errorb(),lattice.errorc(),lattice.erroralpha(),lattice.errorbeta(),lattice.errorgamma()
print "U = ",lattice.getU()
print "B = ", lattice.getB()
```

Refs #16199 since all problems in issue were not fixed.

Algorithm changes already in release notes since these are bug fixes from previous ticket.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AndreiSavici** [comment]
Is there a reason that this algorithm should work only for rectangular detectors or `sixteenpacks`?

**Comment by AndreiSavici** [comment]
PR #16526 and #16527 are the same, one for `master`, one to `release-v3.7`

**Comment by VickieLynch** [comment]
I have tried CORELLI and modifications are needed for this to work for sixteenpacks.

**Comment by AndreiSavici** [comment]
:shipit:

**Comment by FedeMPouzols** [comment]
Is this a duplicate of #16526?

**Comment by FedeMPouzols** [comment]
About the always restarting builds I'd suspect that the Jenkins plugin got confused with these two PRs in parallel with the same commits.

**Comment by FedeMPouzols** [comment]
There is a warning from clang (unused variable): http://builds.mantidproject.org/job/pull_requests-osx/7247/warnings13Result/

**Comment by FedeMPouzols** [comment]
I was about to say... 
"This is a good fix for SCDCalibratePanels. From what I can see in the commit history of this branch it was started off release-v3.7. I'm going to merge it in so that this fix can make it to the release."

@VickieLynch, @AndreiSavici: could you fix that? And if it needs some documentation (the point about the parameter CellType and its default that you mention in #16526 that could be added as well).

**Comment by FedeMPouzols** [comment]
Well in view that the builds kept restarting I've closed the other PR and pushed a commit that comments out the unused variable. Hopefully we'll have builds/tests on all platforms soon.

**Pull request merged**
