### PR TITLE
Fixes the bug currently in MayersSampleCorrection

### PR DESCRIPTION
**Pull request by marshallmcdonnell**
When using the `MultipleScattering`==`True`, the correction disagreed both with the `CarpenterSampleCorrection` and what is sensible for the correction.

This fixes the bug where the conversion factor `rns` that is used in the multiple scattering was incorrectly applied to the absorption (attenuation) factor as well, causing the overall correction to reduce the signal far too much.

Example
--------

First, an example for a powder diffraction sample workspace spectrum with material as vanadium:
  Before bug fix
image

  After bug fix
image

Second, an example for a diamond spectrum from POWGEN at SNS:
  Before bug fix
image

  After bug fix
image

**Report to:** anyone using the `MayersSampleCorrection` or interested in multiple scattering for cylinders (using isotropic scattering assumption), @Anders-Markvardsen 

**To test:**

I used the following script to perform both the tests above, if it helps. If you would like to try on another instrument, modify the `make_instrument_workspace` function:

```python
from __future__ import (absolute_import, division, print_function)

from mantid.simpleapi import *
import matplotlib.pyplot as plt

def cylinder_sample(workspace, radius, height):
    # Define function to create sample shape
    radius_m = radius/100.
    height_m = height/100.
    xml = '<cylinder id="sample">' \
               '<centre-of-bottom-base x="0.0" y="{0}" z="0.0" />' \
                '<axis x="0.0" y="1.0" z="0" />' \
                '<radius val="{1}" />' \
                '<height val="{2}" />'\
                '</cylinder>'.format(0.5*height_m, radius_m, height_m)
    CreateSampleShape(InputWorkspace=workspace, ShapeXML=xml)
    SetSampleMaterial(workspace, ChemicalFormula=material,
                      SampleNumberDensity=num_density)
    return workspace


def make_sample_workspace():
    # Create a fake workspace with TOF data
    sample_ws = CreateSampleWorkspace(Function='Powder Diffraction',
                                      NumBanks=1,BankPixelWidth=1,XUnit='TOF',
                                      XMin=1000,XMax=10000)
    return sample_ws

def make_instrument_workspace(instrument, run_type='diamond', params="300.,10.0,166667.0"):
    # Select instrument for runs
    if instrument == "PG3":
        dia_run = 39169
        van_run = 37830
    elif instrument == "NOM":
        dia_run = 122825
        van_run = 122827
    else:
        raise Exception("Instrument %s not a selection in [NOM, PG3]" % instrument)

    # Select sample type
    if run_type =='diamond':
        wksp = "%s_%d" % (instrument, dia_run)
    elif run_type =='vanadium':
        wksp = "%s_%d" % (instrument, dia_run)
    else:
        raise Exception("Run type %s not a selection in [diamond, vanadium]" % run_type)

    # Focus down to a few spectra
    Load(Filename=wksp, OutputWorkspace=wksp)
    Rebin(InputWorkspace=wksp, OutputWorkspace=wksp, Params=params)
    grp_wksp, spectra_count, group_count = CreateGroupingWorkspace(InstrumentName=instrument, GroupDetectorsBy='Group')
    DiffractionFocussing(InputWorkspace=wksp, OutputWorkspace=wksp, GroupingWorkspace=grp_wksp, PreserveEvents=False)
    return wksp


def get_mayers_results(sample_ws):
    # CalculateMayersSampleCorrections
    ConvertUnits(InputWorkspace=sample_ws, OutputWorkspace=sample_ws, Target="TOF")
    mayers_abs = MayersSampleCorrection(sample_ws, MultipleScattering=False)
    mayers_ms = MayersSampleCorrection(sample_ws, MultipleScattering=True)
    return mayers_abs, mayers_ms


def get_carpenter_results(sample_ws):
    ConvertUnits(InputWorkspace=sample_ws, OutputWorkspace=sample_ws, Target="Wavelength")
    corrections = CalculateCarpenterSampleCorrection(InputWorkspace=sample_ws,CylinderSampleRadius=0.2)
    absCorr = corrections.getItem(0)
    carpenter_abs = Divide(sample_ws, absCorr)
    carpenter_ms  = CarpenterSampleCorrection(sample_ws)
    return carpenter_abs, carpenter_ms

def plot_abs(axis, sample_ws, mayers_abs, carpenter_abs, wkspIndex=0):
    axis.plot(sample_ws, wkspIndex=wkspIndex,label='Sample')
    axis.plot(mayers_abs, wkspIndex=wkspIndex, label='Mayers')
    axis.plot(carpenter_abs, wkspIndex=wkspIndex, label='Carpenter')
    axis.set_title("Absorption")
    axis.legend()

def plot_ms(axis, sample_ws, mayers_ms, carpenter_ms, wkspIndex=0):
    axis.plot(sample_ws, wkspIndex=wkspIndex, label='Sample')
    axis.plot(mayers_ms, wkspIndex=wkspIndex, label='Mayers')
    axis.plot(carpenter_ms, wkspIndex=wkspIndex, label='Carpenter')
    axis.set_title("Multiple Scattering")
    axis.legend()


if __name__=="__main__":
    # Set sample workspace with instrument
    sample_ws = make_sample_workspace()
    sample_ws = make_instrument_workspace('PG3')

    # Set sample material
    material = 'V'
    num_density = 0.07261
    cyl_height_cm = 4
    cyl_radius_cm = 0.25
    sample_ws = cylinder_sample(sample_ws, cyl_radius_cm, cyl_height_cm)

    # Calculate corrections
    mayers_abs, mayers_ms = get_mayers_results(sample_ws)
    carpenter_abs, carpenter_ms = get_carpenter_results(sample_ws)

    # Get all wksps in wavelength
    sample_ws = ConvertUnits(sample_ws, "Wavelength")
    mayers_abs = ConvertUnits(mayers_abs, "Wavelength")
    mayers_ms = ConvertUnits(mayers_ms, "Wavelength")
    carpenter_abs = ConvertUnits(carpenter_abs, "Wavelength")
    carpenter_ms = ConvertUnits(carpenter_ms, "Wavelength")

    # Plot
    fig, ax = plt.subplots(2, subplot_kw={'projection':'mantid'}, sharex=True)
    plot_abs(ax[0], sample_ws, mayers_abs, carpenter_abs)
    plot_ms(ax[1], sample_ws, mayers_ms, carpenter_ms)
    plt.show()
```

Re #22556 (does not fix since the issue discusses refactor as well, will be a separate PR to fully close the issue)

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by peterfpeterson — APPROVED** [review]
The fix is essentially for a typo. It is reasonable to expect that various inelastic corrections should be in agreement.

**Review by martyngigg — APPROVED** [review]
This makes sense after looking back at the original paper.

**Comment by martyngigg** [comment]
Thanks for catching this!

**Comment by DannyHindson** [comment]
@marshallmcdonnell @martyngigg - I appreciate this question is a bit of a long shot given that it's a while since this bug was fixed but here goes anyway...
I've recently written a new multiple scattering algorithm in Mantid based on a method originally implemented in a Fortran program called Discus. The details of this were given to me by Spencer Howells. It doesn't rely on an isotropic scattering assumption and it will also (eventually) work for inelastic instruments - although only works for elastic so far.

I've done some comparisons between the results of my new algorithm vs other existing multiple scattering calculations (Carpenter, Mayers). It agrees pretty well but the MayersSampleCorrection multiple scattering correction is slightly smaller than the rest (ie corrected intensity is slightly larger).

Do you know why the MayersSampleCorrection ms code includes a factor called `rns`? I've reviewed the paper describing the calculation and I don't see a reason for it being included. This PR I've commented against reduces it's impact but I wonder if it shouldn't be there at all. If I set rns=1 (ie effectively exclude it) then the results agree v well. 

The algorithm is based on this paper that Martyn shared with me. The `rns` term only appears in pencil notes and not in the main text. It appears to be something to do with equation (28) but I don't think that equation is relevant. The algorithm should just implement equation (27):

MayersCh5MultipleScatteringCorrections

**Comment by marshallmcdonnell** [comment]
@DannyHindson Sorry I do have a foggy memory on all this now but here is what I do remember / see:
 - The RNS term looks to be a term for the number of scatterers (i.e. particles or atoms) in the system since it is a rho * volume term with conversions in it (I'm looking [here](https://github.com/mantidproject/mantid/blob/cf8bc851e8a7e4e31a5a6041915a8b590b82861c/Framework/Algorithms/src/SampleCorrections/MayersSampleCorrectionStrategy.cpp#L146-L149)). The `1e6` is converting the volume from m to cm and the `1e24` is converting Angstroms^3 to cm^3. The 1e-22 is described in the comments, which looks like a "fudge factor" :disappointed: 
 - Relating this to the paper, that seems like it would be the `nV` term in Eq. (28) in the first fraction of the equation.
 - For the comment:
 > It appears to be something to do with equation (28) but I don't think that equation is relevant. The algorithm should just implement equation (27)
 Well, they are the same equation, just with Eq. 22 substituted into Eq. 27 for the N_1 term but I see your point in that one is more direct to what we are calculating. But, here is where I am fuzzy since I remember having lots of trouble connecting the Mayers paper to the implementation and found other papers on multiple scattering to help me out better to understand what was going on.

Hope this helps and excited to see the new MS correction algorithm!
Just an FYI (you may already know) but maybe update [this page on Mantid sample corrections](https://docs.mantidproject.org/nightly/concepts/AbsorptionAndMultipleScattering.html) with the new algorithm if you don't mind.

**Comment by DannyHindson** [comment]
@marshallmcdonnell - thanks for your thoughts. Martyn Gigg here has told me that one of the instrument scientists here (Ron Smith) wrote the original code for this algorithm so I'll perhaps ask Ron also about this.

The new MS correction algorithm is called CalculateMultipleScattering so the documentation page for the algorithm should give you an idea of what it is. A "beta" version of this will go into the 6.2 Mantid release. I'll do some more work on this in the next release (validating the results, more support on how to apply the correction and some work to speed up the calculation)

**Pull request merged**
