### PR TITLE
Add python editor to workbench

### LINKED ISSUE #21251: Add scripting environment to workbench
The main part of the workbench design layout revolves around the [tabbed scripting widget](https://github.com/mantidproject/documents/blob/master/Design/Workbench/main-layout.png).

This should be added to the workbench as the main widget.

Work required:
* export MessageDisplay to `mantidqt` library to display output
* export syntax-highlighted code editor to Python
* define execution framework in new workbench including abilities to:
  * show progress markers as each line is executed
  * mark lines as errors when a syntax or runtime error is encountered 
* add tab containing an embedded IPython terminal 
* script code should be able to be executed within the workbench environment from the command line

### PR DESCRIPTION
**Pull request by martyngigg**
Description of work.

**To test:**

* Start the workbench
* The editor should appear as one of the main widgets. Try it out.

Fixes #21251 

Please note that the lack of unit test coverage in some areas will be addressed in #21563. This is not yet going out to production but is required for the upcoming user meeting.

**Release Notes** 
*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by ElliotAOram** [comment]
Seems to be an issue with QScintilla not picking up Debug version when building solution in Debug mode.

**Review by ElliotAOram — COMMENTED** [review]
Not required for user meeting but worth remembering:
* Can't right click on tabs to get context menus for them.
* Keyboard shortcuts for tab creation don't work (e.g. Ctrl+n for new tab)

**Review by ElliotAOram — APPROVED** [review]
Functionality of python editor all works okay. Looks good to merge.

**Comment by ElliotAOram** [comment]
This works in Debug mode now 👍

**Comment by martyngigg** [comment]
Thanks for retesting

**Comment by SimonHeybrock** [comment]
@martyngigg There is a small conflict now.

**Comment by martyngigg** [comment]
@SimonHeybrock Thanks. That should be fixed now.

**Comment by martyngigg** [comment]
@SimonHeybrock This is ready to go again now.

**Pull request merged**
