### PR TITLE
Add preview spectrum selection to IDA Diagnostics tab

### PR DESCRIPTION
**Pull request by DanNixon**
Fixes [#11199](http://trac.mantidproject.org/mantid/ticket/11199).

To test:
- Open IDR > Diagnostics, select IRIS
- Load `26176`
- Change preview spectrum using `Preview Spectrum` option in property browser
- Ensure that shifting focus to and from the run files entry does not cause the files and preview spectrum to be reloaded/created.

### CODE REVIEW

**Comment by DanNixon** [comment]
Jenkins, retest this please.

**Comment by DanNixon** [comment]
Jenkins, retest this please.

**Comment by FedeMPouzols** [comment]
The new property works well. Min/max limits are checked. It all seems to be updated / not updated appropriately when changing focus, file, and spectrum number.

Was the 'preview spectrum' supposed to be a spin box?

I could only find issues by extreme misuse. This is probably not worth fixing. If you try to load for example HRP37125.RAW, you'll get an uncaught exception ('Unknown property search object SpectrumMin').

**Comment by DanNixon** [comment]
@FedeMPouzols Originally yes, but I decided that this was better than taking up extra plot space with a spin box.

It would be nice if the property manager could display a spin box for number types (it probably can, I just haven't done it yet).

**Pull request merged**
