### PR TITLE
Release notes fixing typos and making formats consistent

### PR DESCRIPTION
**Pull request by keeeto**
**Description of work.**

Cleaning the release notes so that section headings are consistent across the different pages. Also fixed up some small typos.

**To test:**

* Look through different release notes to see if they are consistent

Not a fix.

Does this update require release notes?
- [ ] Yes
- [X] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Mantid-Matthew** [comment]
Do the ToDo statements need to be removed from this file ? https://github.com/mantidproject/mantid/blob/cleaning-release-notes/docs/source/release/v3.13.0/index.rst ?

**Comment by keeeto** [comment]
@Mantid-Matthew yep, that's right. I'm not sure 3.13 has a doi yet. I guess that when a proper release is created then it will get the doi.

**Comment by martyngigg** [comment]
@keeeto That's correct. Although the link has the same format each time.

**Review by Matthew-Andrew — APPROVED** [review]
This looks good to go :)

**Pull request merged**
