### PR TITLE
New algorithm ConvertUnitsUsingDetectorTable 

### PR DESCRIPTION
**Pull request by stuartcampbell**
This is a new algorithm  that basically does the same as ConvertUnits, but doesn't use the instrument geometry, but parameters from a TableWorkspace.

This is mainly for use within the VISION commissioning and will have further development including the extraction of common code between the ConvertUnits\* algorithms

### CODE REVIEW

**Comment by stuartcampbell** [comment]
To Test:  As this is a new algorithm (under development), then running some examples similar to the usage tests / unit test should be ok.  It isn't used by any other algorithm yet.

**Comment by stuartcampbell** [comment]
I really do not understand why the Windoze builds are failing - Anyone any ideas ?

**Comment by KarlPalmen** [comment]
Yes. I think the scheduling of the Windows builds may have gone wrong, so one begins before the previous as finished and this causes a failure of the one just begun, because it can't delete a file.

**Comment by KarlPalmen** [comment]
That idea was wrong. There are two ISIS windows build servers. See slack-general for more details.

**Pull request merged**
