### PR TITLE
Remove unused MATLAB bindings

### PR DESCRIPTION
**Pull request by quantumsteve**
Description of work.

The MATLAB bindings are unused, untested and most likely don't work. It was decided that these should be removed.

**To test:**

Check that the builds still pass.

There is no GitHub issue associated with this pull request.

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by AndreiSavici — APPROVED** [review]
The only matlab mentions left are in documentation/comments. Ready to merge if builds pass

**Review by rosswhitfield — APPROVED** [review]

**Comment by martyngigg** [comment]
@abuts I presume you don't use these either?

**Comment by abuts** [comment]
They were broken so I can not use it. 

From other side, I will be happy to use some parts of Mantid in the incoming project, but not sure how many efforts it would be to use them vs. running export ASCII couple of times.

**Comment by martyngigg** [comment]
I think it would require significant effort to get this working properly for production use. We can always resurrect this from history if we need to.

**Comment by abuts** [comment]
fair enough. As only myself seems is interested in this, and nobody else have asked for this in 3 years time, I think we can kill it.

**Pull request merged**
