### PR TITLE
Fix RHEL 7 - GCC7 build

### PR DESCRIPTION
**Pull request by DavidFair**
Description of work.
As part of some personal projects with compilers I've fixed some GCC 7 compilation errors on RHEL7. I thought I'd contribute this back to the project for others to benefit too.

---

Currently this uses the software collections within RHEL to switch between compilers. 
The other nice feature RHEL has is any changes between `libstdc++` 4.8.x (default compiler) and `libstdc++` 5.x onwards is statically compiled into the final binaries. This means it is backwards compatible without requiring end users to install the devtoolset package.

---
There is no reason this shouldn't work on Ubuntu/Debian based systems. However it will fail to link as the default ABI changed between GCC5 and 6. This means Ubuntu 16.04, which uses the C++03 ABI cannot easily use GCC6 onwards without rebuilding boost. (see [here](https://bugs.launchpad.net/ubuntu/+source/llvm-toolchain-3.8/+bug/1664321)). 
Ubuntu 16.10 onwards will work correctly as the default compiler was changed to using the C++14 ABI.

**To test:**
Setup RHEL7 ([see](https://www.mantidproject.org/Building_with_CMake#Red_Hat_7.2FCentOS_7))
Then:
```
sudo subscription-manager repos --enable rhel-server-rhscl-7-rpms
sudo yum install devtoolset-7
```
Switch to bash instance which uses GCC 7 as default compiler
```
scl enable devtoolset-7 bash
mkdir build_gcc7
cd build_gcc7
cmake <path_to_mantid_src>
```

Edit: An upstream bug [here](https://bugzilla.redhat.com/show_bug.cgi?id=1519073) has been introduced into the standard library causing it to fail to link. 
Instead run make with `-i` to ignore link failure and check all files compile correctly, or wait for the patch release on the devtoolset and it should link properly this time.

Run all tests to verify it compiled correctly

Fixes N/A

**Release Notes** 
*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by quantumsteve** [comment]
@DavidFair Do the linking errors exist on earlier versions of the devtoolset?

**Review by quantumsteve — APPROVED** [review]
LGTM. I don't see any controversial changes and the builds still pass.

**Comment by DavidFair** [comment]
@quantumsteve - No there wasn't linking errors previously, I compiled and ran all system tests in November with the above changes.

**Comment by martyngigg** [comment]
Thanks, @DavidFair!

**Pull request merged**
