### PR TITLE
Fix Flake8 warnings associated with reduction GUI

### PR DESCRIPTION
**Pull request by josephframsay**
As part of #20508, 2 files associated with the reduction GUI have been refactored to reduce cyclomatic complexity

**To test:**
Make sure all unit and system tests pass, and code review. In addition, if this is your area, feel free to throw some data at me to test the affected scripts with, to make sure I haven't broken anything

Address part of #20508 . 

**Release Notes** 
*Does not need to be in the release notes as the change is internal*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by mganeva** [comment]
Please, don't merge it, because the TOFTOF GUI have got broken. I will prepare a problem description and a dataset for testing and attach it here.

**Comment by mganeva** [comment]
There are some changes which influence the generation of the data reduction script and change it's logic. @jburle will give some more details on it. 

I suggest to @josephframsay roll back all the commits which are related to the TOFTOF GUI. I plan to submit some changes to our interface in the next couple of days and can reduce amount of Flake8-warnings by myself. Would you agree to that?

**Review by ghost — CHANGES_REQUESTED** [review]
toftof_reduction.py: the changes rearrange the sequence of lines in the generated Python script and thus break it. The original order and conditional inclusion/exclusion of l() calls are important and must be preserved.

**Comment by josephframsay** [comment]
Ah, sorry about that. Is it just `toftof_reduction.py` that's causing problems? If so, I'll get rid of those changes and you can do what want with that file

**Comment by mganeva** [comment]
I could do some code simplification during the work on #20535

**Comment by josephframsay** [comment]
That'd be wicked, if possible. Thanks!

**Comment by josephframsay** [comment]
Closed as all files taken care of elsewhere

**Pull request closed without merging**
