### PR TITLE
Allow for optional azimuthal angles in PDLoadCharacterizations

### LINKED ISSUE #21892: Unscripted Testing ORNL Powder Diffraction
1. Guidelines for unscripted testing are available here: http://www.mantidproject.org/Unscripted_Manual_Testing
2. Comment against this ticket the OS environment you are testing against.
3. Don't spend more than a few hours on the testing; fatigue will kick in!
4. If you find errors in the (possibly scant) documentation, please correct them.
5. Close the this issue once you are done.
If you find bugs:
* Search to see if an issue already exists
* create an issue if it is new
 * Urgent bugs or crashes should by against the current release, and assigned to a developer, then go and talk to the developer if possible.
 * Less urgent bugs should be against a subsequent release, and assigned if the correct developer is known.

### Specific Notes:

See http://www.mantidproject.org/PowderDiffractionReduction

### PR DESCRIPTION
**Pull request by peterfpeterson**
The original intent was to fix a bug when users specify a instrument parameter file,
but not focus positions. This also finally fills in (minor) functionality for specifying azimuthal angles.

**To test:**

There are new unit tests which exercise the new behavior. A code review is sufficient.

Fixes #21892.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by wdzhou** [comment]
It seems that you forgot to upload "Test_characterizations_focus_azi.txt"

**Comment by peterfpeterson** [comment]
That can't be the case since things that aren't windows passed.

**Review by wdzhou — DISMISSED** [review]
All the changes look good to me.

:shipit: after all tests are passed.

**Review by martyngigg — APPROVED** [review]
This should be good now.

**Pull request merged**
