### PR TITLE
Toml V1 Changes and Format Switch

### LINKED ISSUE #33659: Final tasks for release of SANS TOML v1
This issue captures those remaining tasks necessary for moving to v1 of SANS TOML User Files identified during the review of https://github.com/mantidproject/mantid/pull/33065# and subsequently discussed with @DavidFair , @rmdalgliesh & Sarah.

Currently the monitors to be used in the reduction can be set in [instrument.configuration] _and_ in [normalisation] and [transmission]. This not only runs the risk of confusion for Users/Instrument Scientists, but could also lead to bad data depending on which location assumes precedence.

Agreed:
  
  - [x] to _discontinue_ the use of selected_monitor in _both_ [normalisation] and [transmission] and to only select the monitors in [instrument.configuration].
  - [x] to _change_ the data type of norm_monitor and trans_monitor in [instrument.configuration] from numeric (= 2, = 3) to string (= "M2", = "M3").
  - **not** to facilitate in TOML using the existing (but very, very, rarely used) code permitting reductions with a _different_ normalisation monitor for the transmissions; ie, the current behaviour in 6.3.0 is not to be changed.
  - [x] _to facilitate_ in TOML the use of the existing (but unknown!) code for using a ROI for transmissions instead of a single monitor; ie, to implement what was TRANS/ROI=roi_file.xml and TRANS/MASK=mask_file.xml.
  
    This is to be done by allowing:

    [instrument.configuration]
      trans_monitor = "ROI"

    [transmission.ROI]
      file = "roi_file.xml"

    (Note that TRANS/MASK operates as an anti-ROI, but Mantid mask creation is flexible enough to allow both use cases in one file)
  - **not** to rename anything that was transmission.monitor as transmission.detector.

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**
- Drops duplicated selector for normalisation and transmission monitors.
We will instead specify the monitor name (e.g. M1) then go and lookup
this in the normalisation block.

- Additionally adds tests and some hard-coded assumptions that
instrument.configuration always uses spectra numbers. Now both will
lookup the spec num from the relevant block.

- Updates the transmission test to better reflect we can have a different
normalisation. In a future PR we will add support for this and the
relevant tests, but at the moment add a test to ensure nobody hardcodes
this assumption.

- Adds support for ROI masks on transmission runs using the special "ROI"
flag. This will ignore the monitor directive and skip straight to
[transmission.ROI] instead to load a file.

- Formally go to the V1 format, where we effectively commit to being forwards 
compatible from this point onwards. This will cause the V0 files to break to encourage
people to have a single set of V1 (instead of a mix of V0 and V1) files.

Re #33659

**Report to:** @smk78 

**To test:**
- Ensure system tests pass, these exercise our TOML files against existing legacy files
- Review docs

Fixes #33659

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by smk78** [comment]
> @smk78 We're going to have to implement normalising to a different monitor with a transmission: 

Ahh, ok.

> The difficult part is, what do you want to call `use_different_normalisation_monitor` and `different_normalisation_monitor`?

I think, something a bit more consistent then.
So in [instrument.configuration] the normalisation monitor has the key `norm_monitor`, right? And the transmission monitor has the key `trans_monitor`. 

What about using `use_different_norm_monitor` and `trans_norm_monitor`? I'd like to avoid having norm/trans in one place and normalisation in another.

**Comment by smk78** [comment]
Let's go with my suggestions then!

The section MON[/TRANS]/SPECTRUM=n[/INTERPOLATE] in SANS-Toml-v1.rst will also need updating of course... do you want to put some changes in a PR for me to review?

**Comment by DavidFair** [comment]
@smk78 Done see https://github.com/mantidproject/mantid/pull/33660/commits/93a2ce4e8bdf513eeec692aef329362be9f055b8

**Comment by DavidFair** [comment]
So I've just checked and this is the correct attribute to map from old to new. However it does look like a misleading name:

`binning.2d_reduction.interpolate`

Any ideas how we should rename it?
Looking at the implementation in `SansConvertToWavelengthAndRebin.py` the only condition it checks for is that we don't have event data whilst trying to interpolate https://github.com/mantidproject/mantid/blob/e9f5df9bdcb8338a2e3772f2ef9a34d8350b610d/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANS/SANSConvertToWavelengthAndRebin.py#L132

**Comment by smk78** [comment]
> So I've just checked and this is the correct attribute to map from old to new. However it does look like a misleading name:
> 
> `binning.2d_reduction.interpolate`
> 
> Any ideas how we should rename it? 

The current key you have is that used for 2D Q binning under L/QXY. But here the \INTERPOLATE is supposed to do an interpolating rebin of the specified time-of-flight spectrum. So `binning.monitor.interpolate`? Or simply `binning.monitor`?

But unlike with Q or wavelength binning elsewhere, this \INTERPOLATE carries no arguments, so how it decides how to do the interpolation must be hard-coded?

**Comment by DavidFair** [comment]
> The current key you have is that used for 2D Q binning under L/QXY. But here the \INTERPOLATE is supposed to do an interpolating rebin of the specified time-of-flight spectrum. So `binning.monitor.interpolate`? Or simply `binning.monitor`?

We could do:
```
[binning]
  [binning.monitor]
    interpolate = true
```

> But unlike with Q or wavelength binning elsewhere, this \INTERPOLATE carries no arguments, so how it decides how to do the interpolation must be hard-coded?

Internally the algorithm:
> y-values [in] the input spectra are approximated with a time series where the value at the center of each bin is the mean count rate over the bin. This series is interpolated by calculating cubic splines that fit this series and evaluating the splines at the centers of the requested bin.

https://docs.mantidproject.org/nightly/algorithms/InterpolatingRebin-v1.html

**Comment by DavidFair** [comment]
On the TOML side we're good to go
I've emailed Sarah as we need some newer SANS2D test data. The current batch uses interpolate as it's from 2012-2014 so it's no good after this change on the TOML side

**Review by gemmaguest — APPROVED** [review]
Code changes look good. Lots of test changes which is expected for these user file changes, and new tests added :+1: System tests look thorough and are passing (currently re-running just do to copyright header change).

**Comment by smk78** [comment]
@DavidFair : does the merge _also_ take care of the last iteration of updates to the .rst file?

**Comment by DavidFair** [comment]
Yep, once it builds overnight the docs here will update too: https://docs.mantidproject.org/nightly/techniques/SANS-Toml-v1.html

**Comment by smk78** [comment]
> Yep, once it builds overnight the docs here will update too: https://docs.mantidproject.org/nightly/techniques/SANS-Toml-v1.html

They don't seem to have updated yet...?

**Comment by gemmaguest** [comment]
It looks like the nightly builds haven't completed since Tuesday... I'll see if I can find out why

image

**Comment by martyngigg** [comment]
These are updated now. There turned out to be an issue with the page updating and the builds were fine.

**Comment by gemmaguest** [comment]
> These are updated now. There turned out to be an issue with the page updating and the builds were fine.

@martyngigg The builds are fine but the nightly docs still don't seem to have updated?

**Comment by smk78** [comment]
Yup! They are. Thanks!

**Pull request merged**
