### PR TITLE
Indirect - Data Corrections - Plot spectrum option

### LINKED ISSUE #23757: Indirect - Data Corrections - Plot Spectrum number option
**Original reporter:** Spencer

### Expected behavior
It should be possible to choose which spectrum to plot in `Container Subtraction` and `Apply Absorption Corrections` in the Plot Output options.
This should be done by having separate `Plot Contour` and `Plot Spectrum` buttons.

`Interfaces`->`Indirect`->`Corrections`

### Platforms affected
All

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR introduces the option to choose which spectrum you want to plot output for on the `ContainerSubtraction` and `ApplyAbsorptionCorrections` Tabs.
This means there is now also a separate option to `Plot Contour` on both tabs.

**To test:**
1. `Interfaces`->`Indirect`->`Data Corrections`
2. Load the data below in turn into the corresponding tabs
3. Click `Run`

- The maximum spectrum number you should be able to enter is 50.
- Try clicking `Plot Spectrum` and `Plot Contour`, and make sure the Run, Plotting and saving options are disabled while plotting is taking place.
- Changing the spectrum number should result in different Plot Spectrum plots (although it may be hard to see)

- The relevant documentation should be updated with descriptions of the new changes http://docs.mantidproject.org/nightly/interfaces/Indirect%20Corrections.html

**Data Files**

**ContainerSubtraction:**
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2484087/irs26176_graphite002_red.zip)
[irs26174_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2484088/irs26174_graphite002_red.zip)

**ApplyAbsorptionCorrections:**
Sample: [irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2484094/irs26176_graphite002_red.zip)
Corrections: [irs26176_graphite002_FlatPlate_MC_Corrections.zip](https://github.com/mantidproject/mantid/files/2484093/irs26176_graphite002_FlatPlate_MC_Corrections.zip)
`Tick use container`
Container: [irs26174_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2484092/irs26174_graphite002_red.zip)

Fixes #23757 

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DanNixon — DISMISSED** [review]
Looks good to me, plotting works as described.

**Review by gvardany — DISMISSED** [review]
Could you please update the relevant interface documentations? http://docs.mantidproject.org/nightly/interfaces/Indirect%20Corrections.html
Also it seems there is a screenshot missing there, could you check?

**Comment by robertapplin** [comment]
@gvardany The interface documentation should now be updated

**Review by keeeto — APPROVED** [review]
This all looks good and functions as it should.

**Pull request merged**
