### PR TITLE
Add axis autoscale checkbox to plot config dialog

### LINKED ISSUE #27548: Autoscale turned off if you visit Figure Options
### Expected behavior

In workbench:

1. Load MAR11060.raw
2. Plot Spectra 1-10
3. open Figure Options and then close without changing any options by hitting OK
4. Run SumSpectra on the workspace with output workspace=input workspace

Plot should update to show single summed spectrum instead of 10 separate ones and should autoscale

### Actual behavior

Plot doesn't autoscale and summed curve is cropped (top portion not visible). Note that if you don't visit the Figure Options page in the middle of this process it does autoscale. Seems like the Figure Options page is turning off the autoscale feature. 

I did a bit of looking into this. I think it's caused by the Axes tab in the Figure Options dialog (mantid\qt\python\mantidqt\widgets\plotconfigdialog\axestabwidget\presenter.py), specifically this line in apply_properties:

ax.set_xlim(new_props.xlim)

This appears to turn off autoscaling. Perhaps apply_properties should return early if no properties have changed without reapplying all the limits (same as the curves tab does)?

### Steps to reproduce the behavior

See above

### Platforms affected

Was testing on Windows

### PR DESCRIPTION
**Pull request by samtygier-stfc**
Fixes #27548

Adds a checkbox to the plot config dialog and keeps it in sync with the plot autoscale options.

This avoids autoscaling getting accidentally disabled by the config box. Also makes it easy for the user to re-enable autoscaling

**Description of work.**

This is to solve the issue of autoscaling being disabled by opening the plot config dialog. Now the autoscale setting for each axis is explicitly tracked, and and controllable with the check box. A previous approach to solving this by checking for changes to the limits ( bbb6c024b777da8cb9f0132df2b2d7b272bac785 ) caused issues and so was removed ( 4c806e1c340fea021466ac021df19d296f498647 ). Tracking autoscale is more reliable and also makes it easy to expose and option to the user.

**To test:**

Test case in #27548

Fixes #27548

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by samtygier-stfc** [comment]
Screenshot at 2020-11-18 17-43-00

**Comment by samtygier-stfc** [comment]
Tests failing due to mock expecting xlim to be called, but now it is only called when needed.

From discussion with @Pasarus 

- Needs to work with project saving ( qt/python/mantidqt/project/plotssaver.py ), and not prevent loading of old files
- Tool tip on the limit entries when disabled. Possibly a QGroupBox around the checkbox and limit entry
- Presenter should not access widgets directly, only through methods in view. (Fix other cases in class)
- Test with multiple axes plots

**Comment by samtygier-stfc** [comment]
Screenshot at 2020-11-19 13-28-34
Dialog with a QGroupBox

**Comment by samtygier-stfc** [comment]
Screenshot at 2020-11-24 13-55-19

New figure options dialog.

To play with all the options make sure you have 2d and 3d axes in your figure

```python
MAR11060 = Load("MAR11060.raw")
fig, axes = plt.subplots(nrows=3, num='MAR11060-1', subplot_kw={'projection': 'mantid'})
axes[0].plot(MAR11060, color='#1f77b4', label='MAR11060: spec 1', specNum=1)
axes[0].plot(MAR11060, color='#ff7f0e', label='MAR11060: spec 2', specNum=2)
axes[1].plot(MAR11060, color='#2ca02c', label='MAR11060: spec 3', specNum=3)
axes[1].plot(MAR11060, color='#d62728', label='MAR11060: spec 4', specNum=4)
axes[2] = plt.subplot(313, projection="mantid3d")
axes[2].plot_wireframe(MAR11060)
for i in [0,1,2]: axes[i].set_title(f'subplot {i+1}')
plt.show())
```

**Review by DanielMurphy22 — DISMISSED** [review]
I've been testing on Mac. The new Axes tab is great and here's how I see it: 

Screenshot 2020-11-25 at 11 16 06

This solves the original issue well and seeks to work with lots of different types of plots, but I've a few requests:

- Firstly, you've a small conflict in the release notes (happens all the time)
- When I plot a wireframe, at least on Mac, the figure options seems too narrow. I don't know why this is different from other plots. As you can see below its "okay",but if this is something that's easy to fix that would be great.
Screenshot 2020-11-25 at 11 14 00

- Working with 3D plots. So the two true 3D plots in Workbench (surface and wireframe) have their data masked when the limits are reduced, and then unmasked when they are widened again. This is set through set_xlim3d(), set_ylim3d() and set_zlim3d() in `Framework/PythonInterface/mantid/plots/mantidaxes.py` which you seem to have included, but it doesn't work with these steps:

1.  Run 
```
import matplotlib.pyplot as plt

ws = CreateSampleWorkspace(Function = 'Exp Decay')
fig, ax = plt.subplots(subplot_kw={'projection':'mantid3d'})
ax.plot_wireframe(ws)
plt.show()
```
2. In figure options, go to the Z axis and set the upper limit to `0.2` and click Apply. 
3. Now tick to enable autoscale and again click Apply. 

The Zaxis limits have been reset but the data has not been unmasked, which means that set_zlim3d() hasn't been called. This is the case for all 3 axes and for both wireframe and surface plots.

**Comment by sf1919** [comment]
So I've tested this on my 4k Latop with Windows and 2nd monitor. 

I also get the new tabs in the Axes tab which is great to see.
Screenshot (61)

I ran the script suggetsed by @samtygier-stfc  above and then followed the instructions in #27458 with regards opening the Figure Options and running SumSpectra. The resulting plots have autoscaled as required.
Screenshot (62)

As you can see the plots don't automatically open to full screen but when I resize them to full screen there doesn't seem to be any issues resizing.
Screenshot (63)

The only thing to mention is all the labels seem a bit squished and difficult to read but thats outside the scope of this issue and @DanielMurphy22 seems to be getting the same if his screenshots are anything to go by.

**Comment by samtygier-stfc** [comment]
Thanks.

- I'll rebase to fix the conflict.
- Width is being set by the widest of the dialog pages. I've added a minimum width to the axes tab widget, so that it is a good width even on its own
- I think the 3d data cropping is new as of #28632 . It was doing the over spilling still when I was testing it. We don't want to call `set_zlim3d()` because it will turn autoscaling back off. I think instead `MantidAxes3D` needs to reset to the original data when autoscale is called. I'll have a go at this.
- Matplotlib is prone to overlapping things. `tight_layout` can help and maybe could be used? I think thats for another issue though, unless I've made anything worse.

**Review by DanielMurphy22 — COMMENTED** [review]
Brilliant! - The autoscale and 3D set_data_to_nan in mantidaxes work well together now!
- The width of the figure options for wireframe plots is notably better. 

I'm happy to approve, but should possibly wait for @martyngigg or someone else on Linux to test.

**Review by martyngigg — APPROVED** [review]
I'm happy with the new view. It looks good 👍 and it's nice to fix the autoscaling problem at the same time as giving users more control.

**Pull request merged**
