### PR TITLE
Add CylinderAxis property to cylinder absorption algorithm

### LINKED ISSUE #25648: Cylinder absorption only works for samples oriented along z
Cylinder absorption and flat plate only work for samples oriented along z. This breaks for Mari. Could we have more flexibility to orient samples along any direction and rotation (i.e. for flat plates that are not perpendicular to the beam)

### PR DESCRIPTION
**Pull request by aybamidele**
**Description of work.**
I added a CylinderAxis property to the cylinder absorption algorithm.

**To test:**

Run the following script with different values for `CylinderAxis`
```python
ws = CreateSampleWorkspace()
ws = ConvertUnits(ws,"Wavelength")
SetSampleMaterial(ws,ChemicalFormula='Cd')

wsOut = CylinderAbsorption(ws,
    NumberOfWavelengthPoints=5, CylinderSampleHeight=4, CylinderAxis=[0,1,0],
    CylinderSampleRadius=0.4, NumberOfSlices=2, NumberOfAnnuli=2)

print ("  over %i bins, ranging from  %.2f to %.2f" %
    (wsOut.blocksize(),
    wsOut.readY(0)[0],
    wsOut.readY(0)[wsOut.blocksize()-1]))
```
For the unit tests, I obtained the output workspace result values using MC absoprtion for the same sample and orientation. I then compared the results with the output for cylinder absorption.
Fixes #25648 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by aybamidele** [comment]
@martyngigg I wanted to ask if this is going in the right direction. Also, I wanted to know how to go about testing the algorithm in light of the new changes.

**Comment by aybamidele** [comment]
@martyngigg I've compared the MC Absorption results with the Cylinder Absorption results for the `x`, `y` and `z` axes. They tally, but for some reason, the values are different for any other orientation. Do you know why this might be the case?

**Comment by aybamidele** [comment]
After probing the issue further, I found that the the track length is zero for orientations in the XY plane giving the error `Unable to generate valid track through sample interaction volume after 5000 attempts. Try increasing the maximum threshold or if this does not help then please check the defined shape.` Trying to offset the center also yields the same error. 

```
// To avoid glancing tracks, we multiply offset the cylinder's position by
    // half it's height  (scaled by 0.01)
    V3D offset{1, 1, 0};
    offset.normalize();
    offset = - offset * 0.02;

    std::vector<double> center{offset};
     std::cout << "A" << center[0] << ", " << center[1] << ", " << center[2] << "\n";
    geometry->declareProperty(
        std::make_unique<FloatArrayProperty>("Center", std::move(center)), "");
```
This was the code I used to try to solve the problem.

**Review by martyngigg — COMMENTED** [review]
```python
from __future__ import (absolute_import, division, print_function, unicode_literals)

# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *

import matplotlib.pyplot as plt

import numpy as np

ws = CreateSampleWorkspace()
ws = ExtractSpectra(ws, StartWorkspaceIndex=5, EndWorkspaceIndex=5)
ws = ConvertUnits(ws, "Wavelength")

material = '(Li7)2-C-H4-N-Cl6'
number_density = 0.1 
SetSampleMaterial(ws, ChemicalFormula=material, SampleNumberDensity=number_density)
ws_clone = CloneWorkspace(ws)

radius = 0.8
height = 3.0
lambda_pts = 25
cyl_abs = CylinderAbsorption(ws, CylinderSampleRadius=radius, CylinderSampleHeight=height, CylinderAxis=[0,0,1],
    NumberOfWavelengthPoints=lambda_pts, NumberOfSlices=50, NumberOfAnnuli=50)
    
SetSample(ws_clone, Geometry={'Shape': 'Cylinder', 'Height': height,
                'Radius': radius,
                'Center': [0.,0.,0], 'Axis': [0.,0.,1.]})
cyl_abs_clone = CylinderAbsorption(ws_clone,
    NumberOfWavelengthPoints=lambda_pts, NumberOfSlices=50, NumberOfAnnuli=50)

fig, ax = plt.subplots(subplot_kw={'projection': 'mantid'})
ax.plot(cyl_abs, label='cyl')
ax.plot(cyl_abs_clone, label='clone')
ax.legend()
fig.show()
```

**Review by martyngigg — CHANGES_REQUESTED** [review]
The above script shows a discrepancy when the curves should match.

**Review by martyngigg — DISMISSED** [review]
Axis orientation parameter looks like it is working properly now.

**Comment by NickDraper** [comment]
@martyngigg Shouldn't we get this into the release notes, it is one of the few things that the direct inelastic group have been asking for.

**Comment by martyngigg** [comment]
:man_facepalming: Yes sorry. I was to focussed on finding why the code didn't work in the edge case.

**Review by martyngigg — APPROVED** [review]

**Pull request merged**
