### PR TITLE
Upgrade IPython on Windows

### LINKED ISSUE #11286: IPython crashes Mantid on string substitution
This issue was originally [TRAC 10444](http://trac.mantidproject.org/mantid/ticket/10444)

Observed on windows

Build mantid in Debug mode, go to Ipyton window, type Re and tab to see the list of algorithm starting with Re

Mantid throws Runtime error

assert: "f==frame" in file text\qtextdocument_p.cpp line 1500. 

You can debug the application or just finish Mantid session.

### LINKED ISSUE #13215: IPython script interpreter: autocompletion crashes
Start writing for example `InstrumentW` and then use the TAB-autocompletion. It works but it immediately crashes on an assert (QtCored4.dll, qglobal.cpp:2303, "f == fname" in text\qtextdocument_p.cpp: 1500).

This is the trace that you get If you do Retry -> Debug:

```
    QtCored4.dll!qt_message_output(QtMsgType msgType, const char * buf) Line 2311   C++
    QtCored4.dll!qt_message(QtMsgType msgType, const char * msg, char * ap) Line 2369   C++
    QtCored4.dll!qFatal(const char * msg, ...) Line 2553    C++
    QtCored4.dll!qt_assert(const char * assertion, const char * file, int line) Line 2019   C++
    QtGuid4.dll!QTextDocumentPrivate::scan_frames(int pos, int charsRemoved, int charsAdded) Line 1500  C++
    QtGuid4.dll!QTextDocumentPrivate::finishEdit() Line 1214    C++
    QtGuid4.dll!QTextDocumentPrivate::endEditBlock() Line 1202  C++
    QtGuid4.dll!QTextDocumentFragmentPrivate::QTextDocumentFragmentPrivate(const QTextCursor & _cursor) Line 235    C++
    QtGuid4.dll!QTextDocumentFragment::QTextDocumentFragment(const QTextCursor & cursor) Line 314   C++
    QtGuid4.dll!QTextCursor::selection() Line 1770  C++
    QtGui_d.pyd!000007fec1dae97a()  Unknown
    python27_d.dll!000000001e17b438()   Unknown
    python27_d.dll!000000001e2178a4()   Unknown
    python27_d.dll!000000001e215283()   Unknown
    python27_d.dll!000000001e20fdaa()   Unknown
    python27_d.dll!000000001e15b73d()   Unknown
    python27_d.dll!000000001e109abb()   Unknown
    python27_d.dll!000000001e218bce()   Unknown
    python27_d.dll!000000001e2153d0()   Unknown
    python27_d.dll!000000001e20fdaa()   Unknown
    python27_d.dll!000000001e218e5a()   Unknown
    python27_d.dll!000000001e217989()   Unknown
    python27_d.dll!000000001e215283()   Unknown
    python27_d.dll!000000001e20fdaa()   Unknown
    python27_d.dll!000000001e218e5a()   Unknown
    python27_d.dll!000000001e217989()   Unknown
    python27_d.dll!000000001e215283()   Unknown
    python27_d.dll!000000001e20fdaa()   Unknown
    python27_d.dll!000000001e218e5a()   Unknown
    python27_d.dll!000000001e217989()   Unknown
    python27_d.dll!000000001e215283()   Unknown
    python27_d.dll!000000001e20fdaa()   Unknown
    python27_d.dll!000000001e218e5a()   Unknown
    python27_d.dll!000000001e217989()   Unknown
    python27_d.dll!000000001e215283()   Unknown
    python27_d.dll!000000001e20fdaa()   Unknown
    python27_d.dll!000000001e218e5a()   Unknown
    python27_d.dll!000000001e217989()   Unknown
    python27_d.dll!000000001e215283()   Unknown
    python27_d.dll!000000001e20fdaa()   Unknown
    python27_d.dll!000000001e218e5a()   Unknown
    python27_d.dll!000000001e217989()   Unknown
    python27_d.dll!000000001e215283()   Unknown
    python27_d.dll!000000001e218dbf()   Unknown
    python27_d.dll!000000001e217989()   Unknown
    python27_d.dll!000000001e215283()   Unknown
    python27_d.dll!000000001e218dbf()   Unknown
    python27_d.dll!000000001e217989()   Unknown
    python27_d.dll!000000001e215283()   Unknown
    python27_d.dll!000000001e20fdaa()   Unknown
    python27_d.dll!000000001e15b73d()   Unknown
    python27_d.dll!000000001e109abb()   Unknown
    python27_d.dll!000000001e129169()   Unknown
    python27_d.dll!000000001e109abb()   Unknown
    python27_d.dll!000000001e20f3c6()   Unknown
    sip_d.pyd!000007fecb3abe92()    Unknown
    QtCore_d.pyd!000007fec2b45ebb() Unknown
    QtCore_d.pyd!000007fec2b45c0b() Unknown
    QtCore_d.pyd!000007fec2b45b07() Unknown
    QtCored4.dll!QMetaObject::metacall(QObject * object, QMetaObject::Call cl, int idx, void * * argv) Line 246 C++
    QtCored4.dll!QMetaObject::activate(QObject * sender, const QMetaObject * m, int local_signal_index, void * * argv) Line 3558    C++
    QtCored4.dll!QMetaObject::activate(QObject * sender, int signal_index, void * * argv) Line 3616 C++
    QtCored4.dll!QMetaObject::activate(QObject * sender, int from_signal_index, int to_signal_index, void * * argv) Line 3435   C++
    QtCore_d.pyd!000007fec2b34bcb() Unknown
    QtCore_d.pyd!000007fec2b39971() Unknown
    python27_d.dll!000000001e17b438()   Unknown
    python27_d.dll!000000001e2178a4()   Unknown
    python27_d.dll!000000001e215283()   Unknown
    python27_d.dll!000000001e20fdaa()   Unknown
    python27_d.dll!000000001e15b73d()   Unknown
    python27_d.dll!000000001e109abb()   Unknown
    python27_d.dll!000000001e218bce()   Unknown
    python27_d.dll!000000001e2153d0()   Unknown
    python27_d.dll!000000001e20fdaa()   Unknown
    python27_d.dll!000000001e15b73d()   Unknown
    python27_d.dll!000000001e109abb()   Unknown
    python27_d.dll!000000001e20f3c6()   Unknown
    sip_d.pyd!000007fecb3abe92()    Unknown
    QtCore_d.pyd!000007fec2b45ebb() Unknown
    QtCore_d.pyd!000007fec2b45c0b() Unknown
    QtCore_d.pyd!000007fec2b45b07() Unknown
    QtCored4.dll!QMetaObject::metacall(QObject * object, QMetaObject::Call cl, int idx, void * * argv) Line 246 C++
    QtCored4.dll!QMetaCallEvent::placeMetaCall(QObject * object) Line 528   C++
    QtCored4.dll!QObject::event(QEvent * e) Line 1194   C++
    QtGuid4.dll!QApplicationPrivate::notify_helper(QObject * receiver, QEvent * e) Line 4562    C++
    QtGuid4.dll!QApplication::notify(QObject * receiver, QEvent * e) Line 3944  C++
>   MantidPlot.exe!MantidApplication::notify(QObject * receiver, QEvent * event) Line 29    C++
    QtCored4.dll!QCoreApplication::notifyInternal(QObject * receiver, QEvent * event) Line 946  C++
    QtCored4.dll!QCoreApplication::sendEvent(QObject * receiver, QEvent * event) Line 231   C++
    QtCored4.dll!QCoreApplicationPrivate::sendPostedEvents(QObject * receiver, int event_type, QThreadData * data) Line 1570    C++
    QtCored4.dll!qt_internal_proc(HWND__ * hwnd, unsigned int message, unsigned __int64 wp, __int64 lp) Line 498    C++
    user32.dll!0000000077769bd1()   Unknown
    user32.dll!00000000777698da()   Unknown
    QtCored4.dll!QEventDispatcherWin32::processEvents(QFlags<enum QEventLoop::ProcessEventsFlag> flags) Line 810    C++
    QtGuid4.dll!QGuiEventDispatcherWin32::processEvents(QFlags<enum QEventLoop::ProcessEventsFlag> flags) Line 1204 C++
    QtCored4.dll!QEventLoop::processEvents(QFlags<enum QEventLoop::ProcessEventsFlag> flags) Line 150   C++
    QtCored4.dll!QEventLoop::exec(QFlags<enum QEventLoop::ProcessEventsFlag> flags) Line 204    C++
    QtCored4.dll!QCoreApplication::exec() Line 1218 C++
    QtGuid4.dll!QApplication::exec() Line 3824  C++
    MantidPlot.exe!main(int argc, char * * argv) Line 215   C++
    MantidPlot.exe!__tmainCRTStartup() Line 536 C
    MantidPlot.exe!mainCRTStartup() Line 377    C
    kernel32.dll!00000000775c59cd() Unknown
    ntdll.dll!000000007787b891()    Unknown
```

### PR DESCRIPTION
**Pull request by martyngigg**
Upgrades IPython to version 3.2.1

**To test:**

**Windows only changes**
- Start MantidPlot and verify the IPython console is present and functioning.
- Start the `mantidpython` script from the desktop and verify that IPython starts and functions correctly.
- Start the IPython notebook link on the desktop and verify the kernel & browser start correctly.

Refs #13699 

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@FedeMPouzols I know you've seen a few issues with the old version. Would you mind testing this one?

**Comment by FedeMPouzols** [comment]
@martyngigg : sure, I'll have a look later today or tomorrow. Great that it was possible to fix these issues now!

**Comment by FedeMPouzols** [comment]
The Python console works well as usual, both from MantidPlot and from the `mantidplot` script.
As for #13699, I can switch to the `nbAgg` backend in notebooks and I can see interactive plots (move around, zoom in/out, save (download).
But I'm afraid this still crashes for me when I try to use tab autocompletion in the Python console of MantidPlot (as in #'13215):
debug_autocompl_assert

(compiled in debug mode with VS 2015 Update 2, on windows 7).

**Comment by martyngigg** [comment]
@FedeMPouzols I'm out of ideas of what to do with this now. As we are hopefully moving to Qt 5 in the not too-distant future should we merge this anyway as it enables the web backend for the IPython notebook to work?

**Comment by FedeMPouzols** [comment]
@martyngigg: definitely yes. This change is good. I wouldn't worry much about the crash in debug mode. It seems to be a very persistent issue throughout several releases of several libraries.

This updates IPython on windows. All works well and now we can use interactive plots in notebooks (see [comment above](https://github.com/mantidproject/mantid/pull/16742#issuecomment-230447555)).
:shipit:

**Comment by martyngigg** [comment]
Thanks. I'll remove the fixes comments for those to crash issues

**Pull request merged**
