### PR TITLE
Indirect - SofQW Progress Tracking

### LINKED ISSUE #14222: SofQW Progress Tracking
The SofQW algorithm does not have any progress tracking. It requires both labels and numerical tracking.

*Appears to have progress tracking and be running in batch algo runner so not sure why this isn't working*

### PR DESCRIPTION
**Pull request by louisemccann**
Implemented progress tracking option to SofQW algorithm. Progress tracker informs user that an output workspace is being created

**To test:**

Run SofQW algorithm and follow example shown:
[http://docs.mantidproject.org/nightly/algorithms/SofQW-v1.html](url)

Fixes #14222 .

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

Refs #14222

### CODE REVIEW

**Comment by KarlPalmen** [comment]
Usage example referred to in test instructions is too fast to test functionality.

**Comment by louisemccann** [comment]
Try 
`ws=Load ("IRS26173_ipg.nxs")
outws=SofQW(InputWorkspace=ws,QAxisBinning='0.5,0.25,2',Emode='Indirect',EFixed=1.84)`

**Comment by KarlPalmen** [comment]
I tried it, but it is still too fast for me.

**Comment by SpencerHowells** [comment]
Try decreasing the Qbinning to say 0.5,0.02,2.0

**Comment by KarlPalmen** [comment]
Thank you @SpencerHowells for your suggestion. I tried it and it took 0.02 seconds. Changing 0.02 to 0.002 raised it to 0.03 seconds.

**Comment by SpencerHowells** [comment]
Is that still to fast? If so I'll look for a bigger data set.

**Comment by KarlPalmen** [comment]
Yes. We'll need a data set big enough to justify this change.

**Comment by ElliotAOram** [comment]
@KarlPalmen I think due to the speed of our developer machines this one is proving slightly tricky to test! 
Could you try the `iris26176_graphite002_red.nxs` located at `\\olympic\babylon5\Public\ElliotOram\DataReduction\S(Q, w)` with the following script:
`ws = mtd['iris26176_graphite002_red']
outws=SofQW(InputWorkspace=ws,QAxisBinning='0.5,0.00001,2',Emode='Indirect',EFixed=1.84)`
This took about 3.5 seconds to run on a release copy of mantid so hopefully it should be long enough to be able to see the progress bar. If not, please let me know and I shall find a larger file.

**Comment by KarlPalmen** [comment]
I'm  going to try that.

**Comment by KarlPalmen** [comment]
I found that the first line of the script and all variations of it I tried did not work for me, and so I loaded and ran SofQW  in the GUI with the properties shown in the script.

SofQW ran with a plain progress bar with just a percentage in it, the briefly showed one with "Creating workspace" in it.

Is this what you intended?

**Comment by KarlPalmen** [comment]
The sample logs of both workspaces appear to be the same. No new logs have been added to the output workspace.

**Comment by KarlPalmen** [comment]
Is modification of the sample log part of this issue?

If NO then :shipit: .

**Comment by ElliotAOram** [comment]
I think the sample log is being dealt with separately now in #17056

**Pull request merged**
