### PR TITLE
Unpin cmake to allow >3.26

### LINKED ISSUE #37521: Unpin cmake
Cmake was pinned to <3.27 to avoid problems with updating MSlice as an external project. 

The setting for UPDATE_DISCONNECTED gets ignored otherwise.

From cmake docs [here](https://cmake.org/cmake/help/latest/module/ExternalProject.html):

Changed in version 3.27: When UPDATE_DISCONNECTED is true, the update step will be executed if any details about the update or download step are changed. Furthermore, if using the git download/update method, the update logic will be modified to skip attempts to contact the remote. If the GIT_TAG mentions a ref that is not known locally, the update step will halt with a fatal error.

### PR DESCRIPTION
**Pull request by jclarkeSTFC**
Previously there was a problem with the UPDATE_DISCONNECTED option in cmake.

I disabled a warning about the `FindBoost` module by setting the `cmake` policy, see [here](https://cmake.org/cmake/help/latest/module/FindBoost.html). It recommends using the `BoostConfig.cmake` config file from the Boost repository, but the version of Boost that we're currently using doesn't appear to have that file. 

The pattern that we were using for including `googletest` and `span` is now deprecated, see [here](https://cmake.org/cmake/help/latest/module/FetchContent.html#command:fetchcontent_getproperties), so I've changed to use the newer method, i.e. using `FetchContent_MakeAvailable()`.

Updating the minimum `cmake` version in `CMakeLists.txt` from 3.16 to 3.21 sets policies for that version, so I had to disable policy [CMP0108](https://cmake.org/cmake/help/latest/policy/CMP0108.html) to allow for the Muon target to target itself via an alias. 

Fixes #37521 

### To test:
Try changing the mslice SHA and check that works.

To update `cmake` and clear the cache file, run `mamba env update -f mantid-developer-win.yml`, then delete `build/CMakeCache.txt`

*This does not require release notes* because **these changes will not affect the user.**

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by jclarkeSTFC** [comment]
Now that Boost has been updated, we should switch from changing the `cmake` policy to using `BoostConfig.cmake`, which (in 1.82 anyway) can be found in `boost/tools/boost_install/BoostConfig.cmake`. I suggest that we do this as a separate issue.

**Comment by sf1919** [comment]
> Now that Boost has been updated, we should switch from changing the `cmake` policy to using `BoostConfig.cmake`, which (in 1.82 anyway) can be found in `boost/tools/boost_install/BoostConfig.cmake`. I suggest that we do this as a separate issue.

Yes - agreed. If you haven't already can you raise that separate issue and link it to this one?

**Comment by sf1919** [comment]
@peterfpeterson one to keep an eye on for  `ornl-next`

**Comment by peterfpeterson** [comment]
Being annoying...
1. Are there any custom cmake modules that we could drop when moving to a newer version?
2. Is there a higher minimum version of cmake to change to in the current main `CMakeLists.txt`? It is currently set to 3.16 and we don't appear to support that far back

**Comment by jclarkeSTFC** [comment]
> Being annoying...
> 
>     1. Are there any custom cmake modules that we could drop when moving to a newer version?
> 
>     2. Is there a higher minimum version of cmake to change to in the current main `CMakeLists.txt`? It is currently set to 3.16 and we don't appear to support that far back

I've updated the minimum `cmake` version in `CMakeLists.txt` to 3.21 so it matches the conda recipe.

For dropping modules, there's the Boost one I linked to above, but maybe we could do any others as separate issues?

**Review by jhaigh0 — COMMENTED** [review]
Cmake runs okay and updates mslice, this warning does get introduced though

```
CMake Deprecation Warning at Framework/Muon/CMakeLists.txt:85 (cmake_policy):
  The OLD behavior for policy CMP0108 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
````

I was going to say is there a way to surpress that but its probably good that we're reminded. Will there be a way to do this in a non-deprecated way in the future?

**Comment by peterfpeterson** [comment]
I'm totally fine with removing custom finders in a separate PR. My point was not to forget that there is a relatively quick audit to do.

**Comment by jclarkeSTFC** [comment]
> Cmake runs okay and updates mslice, this warning does get introduced though
> 
> ```
> CMake Deprecation Warning at Framework/Muon/CMakeLists.txt:85 (cmake_policy):
>   The OLD behavior for policy CMP0108 will be removed from a future version
>   of CMake.
> 
>   The cmake-policies(7) manual explains that the OLD behaviors of all
>   policies are deprecated and that a policy should be set to OLD only under
>   specific short-term circumstances.  Projects should be ported to the NEW
>   behavior and not rely on setting a policy to OLD.
> ```
> 
> I was going to say is there a way to surpress that but its probably good that we're reminded. Will there be a way to do this in a non-deprecated way in the future?

I've linked issue #37722 to deal with this

**Review by jhaigh0 — APPROVED** [review]

**Comment by jclarkeSTFC** [comment]
> I'm totally fine with removing custom finders in a separate PR. My point was not to forget that there is a relatively quick audit to do.

I think the TBB one can go in the bin, #37726

**Pull request merged**
