### PR TITLE
Visual normalization enhancement for MD Workspaces

### LINKED ISSUE #12832: improve auto-select normalization for MDHistoWorkspace
Setting NumEventsNormalization for diffraction returns an incorrect result. @AndreiSavici suggests that for MDHistoWorkspace, NumEventsNormalization should only be used if the instrument is inelastic and there is no MDNorm algorithm in the history. 

I think the best place to implement this logic is in [MDHistoWorkspace::displayNormalization()](https://github.com/mantidproject/mantid/blob/master/Code/Mantid/Framework/DataObjects/src/MDHistoWorkspace.cpp#L1231).

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Fixes #12832 

**Context** 

With this ticket we want to ensure that MDHisto workspaces show the correct normalization when displayed in the VSI

The rules for MDHIsto normalization is:
IF  Is not based on Q3D or QMod:
  VOLUME_NORMALIZATION
ELIF energy mode is Elastic:
  VOLUME_NORMALIZATION
ELIF  underlying workspace was event worksapce:
   NO_NORMALIZATION
ELSE 
   NUMEVENT_NORMALIZATION
## For Testing

**Check ConvertToMD follows the rules specified above**

``` python
ws2D = CreateSimulationWorkspace(Instrument='MAR',BinParams=[-3,0.1,3],UnitX='DeltaE')
event = CreateSampleWorkspace(WorkspaceType='Event')
ws2D_elastic = CreateSampleWorkspace()
AddSampleLog(Workspace=ws2D,LogName='Ei',LogText='3.0',LogType='Number')
AddSampleLog(Workspace=event ,LogName='Ei',LogText='3.0',LogType='Number')

pars = dict();
pars['InputWorkspace']=ws2D
pars['Q3DFrames']='HKL'
pars['QConversionScales']='HKL'
pars['PreprocDetectorsWS']='preprDetMantid'
pars['MinValues']='-3,-3,-3.,-50.0'
pars['MaxValues']='3.,3.,3.,50.0'
pars['SplitInto']=50
pars['MaxRecursionDepth']=1
pars['MinRecursionDepth']=1
pars['OverwriteExisting']=1  

#---------------------------------
# CHECK ConvertToMD
# ----------------------

# Create an MDEventWorksapce -- Workspace2D, QMOD, Inelastic
pars['QDimensions']='|Q|'
pars['dEAnalysisMode']='Direct'
expect_numEvent_for_histo=ConvertToMD(**pars)
print "Workspace2D, QMOD, Inelastic"
print "Should have VolumeNormalization for displayNormalization and has: " + str(expect_numEvent_for_histo.displayNormalization())
print "Should have NumEventNormalization for displayNormalizationHisto and has: " + str(expect_numEvent_for_histo.displayNormalizationHisto())
print

# Create an MDEventWorksapce -- Workspace2D, NoQ Inelastic
pars['QDimensions']='CopyToMD'
pars['dEAnalysisMode']='Direct'
SetUB(Workspace=ws2D,a='1.4165',b='1.4165',c='1.4165',u='1,0,0',v='0,1,0')
expect_volume_for_histo=ConvertToMD(**pars)
print "Workspace2D, NoQ Inelastic"
print "Should have VolumeNormalization for displayNormalization and has: " + str(expect_volume_for_histo.displayNormalization())
print "Should have VolumeNormalization for displayNormalizationHisto and has: " + str(expect_volume_for_histo.displayNormalizationHisto())
print

# Create an MDEventWorksapce -- EventWorkspace, QMOD, Inelastic
pars['InputWorkspace']=event
pars['QDimensions']='|Q|'
pars['dEAnalysisMode']='Direct'
expect_no_for_histo=ConvertToMD(**pars)
print "EventWorkspace, QMOD, Inelastic"
print "Should have VolumeNormalization for displayNormalization and has: " + str(expect_no_for_histo.displayNormalization())
print "Should have NoNormalization for displayNormalizationHisto and has: " + str(expect_no_for_histo.displayNormalizationHisto())
print

# Create an MDEventWorksapce --WS2D, QMOD, Elastic
pars['InputWorkspace']=ws2D_elastic
pars['QDimensions']='|Q|'
pars['dEAnalysisMode']='Elastic'
expect_volume_for_histo_elastic=ConvertToMD(**pars)
print "WS2D, QMOD, Elastic"
print "Should have VolumeNormalization for displayNormalization and has: " + str(expect_volume_for_histo_elastic.displayNormalization())
print "Should have VolumeNormalization for displayNormalizationHisto and has: " + str(expect_volume_for_histo_elastic.displayNormalizationHisto())
print


```

**Check BinMD**
- Take each sample workspace from above and send it through BinMD
  - Confirm that the displayNormalization of the resulting MDHisto worksapce, matches the expected displayNormalization of the underlying MDEventWorkspace. (Note that since we have a MDHisto worksapce displayNormalization and displayNormalizationHisto are the same)

You can use the following script to do this (Note that you need to workspaces from before):

``` python
#----------------------
# BinMD
#-----------------------

# Workspace2D, QMOD, Inelastic
BinMD_expected_numEvent = BinMD(InputWorkspace='expect_numEvent_for_histo', AlignedDim0='DeltaE,-3,3,50', OutputWorkspace='expected_binned_volume')
print "Workspace2D, QMOD, Inelastic"
print "Should have NumEventNormalization and has: " + str(BinMD_expected_numEvent .displayNormalization())
print

# Workspace2D, NoQ Inelastic
BinMD_expected_volume = BinMD(InputWorkspace='expect_volume_for_histo', AlignedDim0='DeltaE,-3,3,50', OutputWorkspace='expected_binned_volume')
print "Workspace2D, NoQ Inelastic"
print "Should have VolumeNormalization and has: " + str(BinMD_expected_volume.displayNormalization())
print

# EventWorkspace, QMOD, Inelastic
BinMD_expected_no= BinMD(InputWorkspace='expect_no_for_histo', AlignedDim0='DeltaE,-3,3,50', OutputWorkspace='expected_binned_volume')
print "EventWorkspace, QMOD, Inelastic"
print "Should have NoNormalization and has: " + str(BinMD_expected_no.displayNormalization())
print

# WS2D, QMOD, Elastic
BinMD_expected_volume_elastic= BinMD(InputWorkspace='expect_volume_for_histo_elastic', AlignedDim0='|Q|,-2.38419e-07,0.0242561,50', OutputWorkspace='expected_binned_volume')
print "WS2D, QMOD, Elastic"
print "Should have VolumeNormalization and has: " + str(BinMD_expected_volume_elastic.displayNormalization())
print
```

**Check SliceMD**
- Take each sample workspace from above and send it through SliceMD
  - Confirm that the displayNormalization and displayNormalizationHisto of the resulting MDEvent workspace is the same as for the input workspace. The settings should just be passed through. 

You can use the following script to do this (Note that you need to workspaces from before):

``` python
print "################"
print "#SliceMD"
print "################"
# Workspace2D, QMOD, Inelastic
SliceMD_expected_numEvent = SliceMD(InputWorkspace='expect_numEvent_for_histo', AlignedDim0='DeltaE,-3,3,50')
print "Workspace2D, QMOD, Inelastic"
print "Should have VolumeNormalization and has: " + str(SliceMD_expected_numEvent .displayNormalization())
print "Should have NumEventsNormalization and has: " + str(SliceMD_expected_numEvent .displayNormalizationHisto())
print

# Workspace2D, NoQ Inelastic
SliceMD_expected_volume = SliceMD(InputWorkspace='expect_volume_for_histo', AlignedDim0='DeltaE,-3,3,50')
print "Workspace2D, NoQ Inelastic"
print "Should have VolumeNormalization and has: " + str(SliceMD_expected_volume.displayNormalization())
print "Should have VolumeNormalization and has: " + str(SliceMD_expected_volume.displayNormalizationHisto())
print

# EventWorkspace, QMOD, Inelastic
SliceMD_expected_no= SliceMD(InputWorkspace='expect_no_for_histo', AlignedDim0='DeltaE,-3,3,50')
print "EventWorkspace, QMOD, Inelastic"
print "Should have VolumeNormalization and has: " + str(SliceMD_expected_no.displayNormalization())
print "Should have NoNormalization and has: " + str(SliceMD_expected_no.displayNormalizationHisto())
print

# WS2D, QMOD, Elastic
SliceMD_expected_volume_elastic= SliceMD(InputWorkspace='expect_volume_for_histo_elastic', AlignedDim0='|Q|,-2.38419e-07,0.0242561,50')
print "Should have VolumeNormalization and has: " + str(SliceMD_expected_volume_elastic.displayNormalization())
print "Should have VolumeNormalization and has: " + str(SliceMD_expected_volume_elastic.displayNormalizationHisto())
print
```

**Check IntegrateMDHistoWorkspace**
- Take each sample workspace from above and send it through IntegrateMDHisto
  - Confirm that the displayNormalization of the resulting MDHisto workspace is equal to the one of the input workspace. The setting is just passed through.

You can use the following script to do this (Note that you need to workspaces from before):

``` python
print "##########################"
print "#IntegrateMDHistWorkspace"
print "#########################"
# Workspace2D, QMOD, Inelastic
IntegrateMDHistoWorkspace_expected_numEvent = IntegrateMDHistoWorkspace(InputWorkspace='BinMD_expected_numEvent', P1Bin=[-10,0,10])
print "Workspace2D, QMOD, Inelastic"
print "Should have NumEventsNormalization and has: " + str(IntegrateMDHistoWorkspace_expected_numEvent .displayNormalization())
print

# Workspace2D, NoQ Inelastic
IntegrateMDHistoWorkspace_expected_volume= IntegrateMDHistoWorkspace(InputWorkspace='BinMD_expected_volume', P1Bin=[-10,0,10])
print "Workspace2D, NoQ Inelastic"
print "Should have VolumeNormalization and has: " + str(IntegrateMDHistoWorkspace_expected_volume.displayNormalization())
print

# EventWorkspace, QMOD, Inelastic
IntegrateMDHistoWorkspace_expected_no= IntegrateMDHistoWorkspace(InputWorkspace='BinMD_expected_no',  P1Bin=[-10,0,10])
print "EventWorkspace, QMOD, Inelastic"
print "Should have NoNormalization and has: " + str(IntegrateMDHistoWorkspace_expected_no.displayNormalization())
print

# WS2D, QMOD, Elastic
IntegrateMDHistoWorkspace_expected_volume_elastic= IntegrateMDHistoWorkspace(InputWorkspace='BinMD_expected_volume_elastic', P1Bin=[-10,0,10])
print "WS2D, QMOD, Elastic"
print "Should have VolumeNormalization and has: " + str(IntegrateMDHistoWorkspace_expected_volume_elastic.displayNormalization())
print
```

**Check MDNormDirectSC**

For this one we only have a check for underlying EventWorkspace, Inelastic and Q3D. Run the example below and confirm that the output matches the expectation:

``` python
import mantid
import os
from mantid.simpleapi import *
config['default.facility']="SNS"
from numpy import *

DGS_input_data=Load("CNCS_7860")
# Keep events (SofPhiEIsDistribution=False)
# Do not normalize by proton charge in DgsReduction
DGS_output_data=DgsReduction(
         SampleInputWorkspace=DGS_input_data,
         SofPhiEIsDistribution=False,
         IncidentBeamNormalisation="None",
         EnergyTransferRange="-1.5,0.01,2.7",
        )
DGS_output_data=DGS_output_data[0]
SetGoniometer(DGS_output_data,Axis0="10.,0,1,0,1")
SetUB(DGS_output_data, 5.,3.2,7.2)
DGS_output_data=CropWorkspace(DGS_output_data,XMin=-1.5,XMax=2.7)
MDE=ConvertToMD(DGS_output_data,
        QDimensions="Q3D",
        dEAnalysisMode="Direct",
        Q3DFrames="HKL",
        QConversionScales="HKL")
histoData,histoNorm=MDNormDirectSC(MDE,
        AlignedDim0="[H,0,0],-0.2,1.6,100",
        AlignedDim1="DeltaE,-1.5,3.,100",
        )
normalized=histoData/histoNorm
histoShape=histoNorm.getSignalArray().shape
print "The normalization workspace shape is (%d, %d)" % histoShape
print "Out of those elements, "+str(nonzero(histoNorm.getSignalArray())[0].size)+" are nonzero"

print "Should have NoNormalization and has: " + str(histoData.displayNormalization())
```

### CODE REVIEW

**Comment by martyngigg** [comment]
I've reviewed the code and I'm happy with the changes that have been made.

**Comment by AndreiSavici** [comment]
For some reason, the displayNormalization() function is not exposed to python. So this ticket cannot be tested as described

**Comment by picatess** [comment]
Exposed `<displayNormalization()>` and `<displayNormalizationHisto()>`, testing should be possible

**Comment by AndreiSavici** [comment]
Works as expected. Here are some of the results (displayNormalization/displayNormalizationHisto):
- elastic 3D events (vol norm/vol norm)
- workspace 2D events (no norm/ no norm)
- elastic with MDNorm (no norm/ no norm)
- inelastic events (vol norm/ num ev norm)
- inelastic histo (num ev norm/ num ev norm)

**Pull request merged**
