### PR TITLE
Fix FindSXPeaks returning incorrect TOF

### LINKED ISSUE #17331: FindSXPeaks gives incorrect TOF
Saurabh reported that running the FindSXPeaks algorithm on some ENGINX data gave him peaks with TOF flight outside of the bounds of the data.

### Expected behavior
Peaks should be found with the correct TOF and intensity

### Actual behavior
The found peaks are incorrect and have little physical meaning

### Steps to reproduce the behavior
The following script should reproduce the issue:

```python
ws = LoadRaw(Filename='/Users/samueljackson/data/ENGINX00252486.raw')
ws = CropWorkspace(ws, StartWorkspaceIndex=0, EndWorkspaceIndex=2400)
test = FindSXPeaks(InputWorkspace=ws, OutputWorkspace='test')
```
The peaks found do not correspond to the position of the peaks in the data.

### Platforms affected
All

### PR DESCRIPTION
**Pull request by samueljackson92**
This fixes the issue with FindSXPeaks return the incorrect time of flight.

**To test:**

Here's a script that will reproduce the issue:

``` python
ws = LoadRaw(Filename='ENGINX00252486.raw')
ws = CropWorkspace(ws, StartWorkspaceIndex=2269, EndWorkspaceIndex=2270)
test = FindSXPeaks(InputWorkspace=ws, OutputWorkspace='test')
```

The peaks found in the workspace test will not match the TOF. Apply the change the correct TOF should then be found.

Fixes #17331 .

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
Tested this fix running the script provided and it worked as expected: the input workspace has two spectra with peaks at ~37000 and ~37035, and the peak found by the algrotihm was at ~37016 (which is ~the average). The intensity found also matches the average of the two peaks.

Code changes look good to me: `SXPeak` has been modified to take into account the instrument geometry, and `SXPeak::getQ()` now works similarly to `Peak::getQLabFrame()`.

:shipit:

**Comment by raquelalvarezbanos** [comment]
Just noticed the name of your branch. I think we tend to name branches like this: `<issuenumber>_<shortdescription>` (see [here](http://www.mantidproject.org/Working_with_git)). Not sure if everyone follows this convention but I do tend to use it.

**Comment by samueljackson92** [comment]
@raquelalvarezbanos I've been told that it's no longer mandatory, although I usually I do include the issue number in the name as I find it useful. But in this case I created the branch before the issue as I wasn't 100% sure whether there was an issue at the time.

**Comment by raquelalvarezbanos** [comment]
Perfect, if it's no longer mandatory, there's no need to use it :)

**Comment by FedeMPouzols** [comment]
Note that you can always change the name of your branch (`git branch -m`) if you'd like to use the `<issuenumber>_...` style but you started it before you know the issue number.

**Comment by samueljackson92** [comment]
@FedeMPouzols a command I did not know! Thanks! I guess that would cause issues though if you tried to change it after the branch has been published?

**Comment by FedeMPouzols** [comment]
@samueljackson92: when you have already pushed your branched there is still a quick way of getting thing working. You can remove the branch on github and then push again.

**Pull request merged**
