### PR TITLE
Change error count to reflect current state

### PR DESCRIPTION
**Pull request by Pasarus**
**Description of work.**
Cppcheck is currently failing on all PRs as the known error count is off by 1 due to an extra error being added before the fix that effectively turned back on Cppcheck in PRs.

**To test:**
 builds pass Cppcheck

*There is no associated issue.*

*This does not require release notes* because *developer facing*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by thomashampson — APPROVED** [review]
@mantidproject/gatekeepers can we have this merged ASAP?

**Comment by DannyHindson** [comment]
@thomashampson @Pasarus - I'm seeing a cppcheck job on #32058 fail this morning with 289 </error> tags in the output

The PR has just two C++ units affected (one .h and one .cpp) and I don't see these being reported in the <error> output. Is it possible the count has genuinely gone up to 289 now?

This PR had been approved and had previously passed all of its jobs (so was just waiting for the gatekeeper to merge). Seems like the cppcheck job got rerun yesterday pm for some reason.

**Comment by DannyHindson** [comment]
I think the fact this PR only changed a .sh file meant that the cppcheck job was skipped so maybe the count was actually 289 yesterday afternoon even though the cppcheck job was green on this PR. I'm going to fix one of the cppcheck issues to bring the count down to 288 on a separate PR - one of them is in a unit I created

**Comment by DannyHindson** [comment]
Think I've sorted this out in the end - the warning count hadn't increased after all. I was counting the closing `</errors>` tag as well. The problem was actually a glitch in the grep command that counts the number of warnings

**Pull request merged**
