### PR TITLE
Replace raw owning pointers with unique_ptr in Properties

### LINKED ISSUE #15289: C++11 Change raw owning pointers to `std::unique_ptr<>`
Change raw owning pointers to `std::unique_ptr<>`. Having `PropertyManager::declareProperty` accept a `unique_ptr` may be a good place to start.

### PR DESCRIPTION
**Pull request by tom-perkins**
Changed `PropertyManager::declareProperty` to accept a `unique_ptr` rather than a raw owning pointer, and propagated changes from there. The property manager takes ownership of the property passed in - this is as before, but using a `unique_ptr` makes it clearer that this is happening.

Made the same kind of change to `IPropertyManager::setPropertySettings`. Together these changes have replaced a lot of instances of `new` with `make_unique`.

There should be no changes to functionality as a result of this PR.

Updated the "Concepts" documentation for `Property` to give examples of how to declare a property in this way. 

**To test:**

No functional changes - code review only. The existing tests should cover the changes here. Make sure that declaring algorithm properties from Python still works exactly the same (nothing should have changed).

Fixes #15289.

The [Release notes](http://www.mantidproject.org/ReleaseNotes_3_7_Framework_Changes#Properties_and_Settings) have been updated with examples.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
Great (and painful) job and big code improvement. `PropertyMap` is now a `std::map<std::string, std::unique_ptr<Property>>` and `PropertyManager::declareProperty()` now takes properties a `std::unique_ptr<Property> p,` rather than `Property *p`. The code and tests have been updated. Good changes done with care, using `std::move()` and `std::make_unique<>()` / `Mantid::Kernel::make_unique<>()` wherever possible.

The Properties concept page reads well. The examples are now updated for `unique_ptr` and the rationale for this is well explained.

I checked out this branch and had a look at the diff. Also, in case, I grepped for omissions in `declareProperty()` calls. It all looked fine to me.

Setting properties is sufficiently tested that we can be sure that the core changes in Kernel and API are fine.

As this fixes only of #15289, it would be good to open another issue for the remaining raw pointers, and see if that one can be split into different areas or topics as well.

I'm not totally sure if we want to expose this C++ level details to users in the release notes?

:shipit:

**Comment by FedeMPouzols** [comment]
Oops, this was ready to be merged just a second ago. But after merging #15459 in a conflict has arisen. Sorry for that, I didn't notice that both branches touch many files in similar places. @tom-perkins : can you check the conflict?

**Comment by FedeMPouzols** [comment]
I'm afraid there's some 10 files with conflicts, `GroupDetectors[2].cpp` and a few `Load...` algorithms.

**Comment by tom-perkins** [comment]
I've created #15467 to continue the work once this issue is closed. 

For the release notes, I guess it depends if users write their own algorithms in C++, or if they tend to use Python only. As long as the concepts page is correct then it should be ok to leave it out of the release notes.

**Comment by FedeMPouzols** [comment]
The last second merge conflict is now fixed and all back to normal.

:shipit:

**Pull request merged**
