### PR TITLE
Allow the specification of user files in batch files

### LINKED ISSUE #10190: Allow the Specification of User Files in Batch Files
This issue was originally [TRAC 9347](http://trac.mantidproject.org/mantid/ticket/9347)

Steve King would like to the ability to specify User Files in the .csv Batch Files.  He mentioned the first line of the batch file being an ideal place for this, but based on an initial code inspection I'm not convinced this is the ideal place for it since `BatchReduce` of `SANSBatchMode.py` tries to parse every line.

From a usability standpoint, we'd also need to put some thought into how this information would be displayed in the GUI.  It would not be good to have the "User File" field at the top of the GUI displaying one thing, only to then have the batch file go away and use something else in the reduction.  Perhaps adding an extra column in the batch table and then striking out the User File field is the way forward?

Any changes need to be documented on the appropriate Wiki page:

http://www.mantidproject.org/SANS_batch_file_format

 - - - - 
Keywords: sasnUI

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Fixes #10190 
### For Testing
-  You can find the required files here: \olympic\Babylon5\Scratch\Anton\Testing\10190_UserFile_in_Batch_File_Mode\Sandbox
-  The default user file is: USER_LOQ_151D_Xpress_6mm which should be loaded in the User File line edit field.
-  The batch files are:
  - batch_blank_user_file.csv: It does not contain a user_file entry
  - batch_individual_user_files.csv: It contains individual user_file entries
  - batch_mixed_blank_and_individual.csv: It contains individual and partially blank user_file entries
-  Set the data search directory to the folder with these test files  and enable the archive search.
-  The user files in the batch file are:
  - user_file_1.txt which has MASK V32>V47 turned off
  - user_file_2.txt which has GRAVITY ON and GRAVITY/LEXTRA=12.
  - user_file_3.txt which is the same as USER_LOQ_151D_Xpress_6mm
-  Set the instrument to LOQ and load USER_LOQ_151D_Xpress_6mm into the user file line edit field. This will ensure that you have these settings every time you open th SANS GUI.

**Batch file without user file should use default user file**
1. Open the SANS GUI. (Make sure that the instrument is LOQ and the user file is USER_LOQ_151D_Xpress_6mm)
2. Make sure that the mode is set to "Single run mode" and load data set 92053
3. Run the 1D reduction and rename the reduced data.
4. Select "Batch mode"
5. Load the batch file: batch_blank_user_file.csv
6. Run the 1D reduction
   - Confirm that the there are no error messages
   - Confirm that there are three more output workspaces
7. Plot the spectrum of the renamed workspace and of one of the batch-produced workspaces
   - Confirm that they lie on top of each other, ie the default user file was being used
8. Close the SANS GUI and clear all the memory

**Batch file with custom user files**
1. Open the SANS GUI. (Make sure that the instrument is LOQ and the user file is USER_LOQ_151D_Xpress_6mm)
2. Make sure that the mode is set to "Single run mode" and load data set 92053
3. Run the 1D reduction and rename the reduced data.
4. Select "Batch mode"
5. Load the batch file: batch_individual_user_files.csv
6. Run the 1D reduction
   - Confirm that the there are no error messages
   - Confirm that there are three more output workspaces
7. Plot the spectrum of the renamed workspace against the workspace with the name iteration_individual_user_file_1
   - Confirm that they deviate
8. Plot the spectrum of the renamed workspace against the workspace with the name iteration_individual_user_file_2
   - Confirm that they deviate
9. Plot the spectrum of the renamed workspace against the workspace with the name iteration_individual_user_file_3
   - Confirm that they lie on top of each other
10. Close the SANS GUI and clear all the memory

**Batch file with mixed custom files and blank user file entries**
1. Open the SANS GUI. (Make sure that the instrument is LOQ and the user file is USER_LOQ_151D_Xpress_6mm)
2. Make sure that the mode is set to "Single run mode" and load data set 92053.On teh Reduction tab check "Account for gravity" and set the extra length to 100 ( for a clear effect)
3. Run the 1D reduction and rename the reduced data.
4. Select "Batch mode"
5. Load the batch file: batch_individual_user_files.csv
6. Run the 1D reduction
   - Confirm that the there are no error messages
   - Confirm that there are three more output workspaces
7. Plot the spectrum of the renamed workspace against the workspace with the name iteration_mixed_user_file_1
   - Confirm that they deviate
8. Plot the spectrum of the renamed workspace against the workspace with the name iteration_mixed_user_file_2
   - Confirm that they do not deviate. They should not deviate since the default setting should have been used for this run.
9. Plot the spectrum of the renamed workspace against the workspace with the name iteration_mixed_user_file_3
   - Confirm that they deviate. Althoug the user files themselves are the same for the default case and this workspace, the manual user-change in the GUI should not have been picked up for this run.
10. Close the SANS GUI

Additional note for tester: Once this issue passes testing please inform @picatess , such that the SANS wikie pages can be updated

### CODE REVIEW

**Comment by Anders-Markvardsen** [comment]
please resolve merge conflict in scripts/CMakeLists.txt

**Comment by picatess** [comment]
@Anders-Markvardsen The merge conflict has been resolved.

**Comment by picatess** [comment]
@Anders-Markvardsen  The requested corrections were added to SANSBatchMode.py

**Comment by Anders-Markvardsen** [comment]
Tested and also added comment about allowed number of elements clear

**Comment by picatess** [comment]
Changed the Wiki documentation to accomodate the new functionality

**Pull request merged**
