### PR TITLE
load cansas data without idev

### LINKED ISSUE #17002: Loading data without Idev in LoadCanSAS causes Mantid to crash
Steve wrote:

>Attached are 4 CanSAS 1D files.
cansas-multi – Copy – 2frame.xml and the - 1frame.xml were edited out of a much larger xml file written by SasView with many <SASdata> blocks.
I noted they didn’t have the current v1.1 header (because Lewis called the class directly and the default version is 1.0) so I manually changed it in one file.
writtenby40alpha is a different dataset written by a current build version of SasView. But could just as easily have been written by the current release.
All will read back into SasView and display ok.
writtenby40alpha.xml will load fine into Mantid, but any of the other crash Mantid fatally!

Should not crash since Idev is optional.

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Fixes #17002

This PR fixes an issue with LoadCanSAS which required Idev to be mandatory. The CanSAS standard states that the Idev entry is optional. See [here](http://www.cansas.org/formats/canSAS1d/1.1/doc/element_SASdata.html). 

This PR fixes this crash. If the Idev field is missing, then the strategy is to use the square root of the intensity as a measure of the error. If the Idev field is present, then just use it.
# To Test

The test files are be found here:
[canSASTestFiles.zip](https://github.com/mantidproject/mantid/files/381031/canSASTestFiles.zip)

__ Load file with missing Idev information__
- Load _withoutIdev.xml_ 
  - Confirm that there is no error

**Load file with Idev information**
- Load _withIdev.xml_ 
  - Confirm that there is no error
# Release Nots

See [here](https://github.com/mantidproject/mantid/pull/17005/commits/162f477609001dcd8dbbc47189cfc602f81950f3)

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
The load without IDEV did not crash, but produced error message, because it could not find an instrument.
```
Load started
Either the InstrumentName or Filename property of LoadInstrument most be specified
Error in execution of algorithm LoadInstrument:
Either the InstrumentName or Filename property of LoadInstrument most be specified to load an IDF in 
Load successful, Duration 0.13 seconds
```

**Comment by AntonPiccardoSelg** [comment]
@KarlPalmen The error message is related to that particular file which was given to me by the instrument scientists. Another file which does not contain Idev and won't produce the error messages can be found here:

[withoutIdev2.xml.zip](https://github.com/mantidproject/mantid/files/383574/withoutIdev2.xml.zip)

**Comment by KarlPalmen** [comment]
Thank you for the file. This one without Idev loaded without error.

**Comment by KarlPalmen** [comment]
Looks good :shipit:

**Pull request merged**
