### PR TITLE
Sample container and corrections logs

### LINKED ISSUE #13649: Add Sample, Container and Corrections to logs in Indirect
**This issue has been raised by Spencer:**

In order to make the logs for a workspace more informative. It would be good to add the sample, container and correction file to the logs of a workspace. This issue should be fixed alongside or after #13648 

Blocked by: 
* [x] #13648 

**This should be fixed during the beta test period before 3.5**

### PR DESCRIPTION
**Pull request by ElliotAOram**
Fixes #13649 

Correction and Container logs have been added to the _red workspace after corrections runs
- This fix needs to be confirm with Spencer before merging to ensure it is how he expected
- This issue should be merged after #13648 to avoid merge conflicts
- [x] Confirmed with Spencer
- [x] #13648 merged
# To Test
## Container
- Open ContainerSubtraction tab (Interfaces > Indirect > Corrections > ContainerSubtraction)
- Run with a `Sample` and `Container` (**MATCHING** irs26176 and irs26174 files will work - ask if unsure)
- Ensure that the resulting workspace from Container Subtraction now has the entry `container_filename` in the sample log with the container value being the name of the container file  
## Correction
- Open ApplyPaalmanPings tab (Interfaces > Indirect > Corrections >  ApplyPaalmanPings)
- Run with a `Sample` and `Correction` (I can provide these if required)
- Ensure that the resulting workspace from  ApplyPaalmanPings now has the entry `correction_filename` in the sample log with the container value being the name of the corrections file

### CODE REVIEW

**Comment by ElliotAOram** [comment]
Spencer has informed me that these logs should be added to the result Workspaces **NOT** the original `_red` Workspace.

**Comment by martyngigg** [comment]
Is it correct that these logs should only appear when this is run through the interface? Should they not be there if the reduction was done through pure Python?

**Comment by SpencerHowells** [comment]
I think you are correct Martyn. Best to do it in the Python.

**Comment by ElliotAOram** [comment]
This is my fault sorry. I should have put these in the algorithms rather than the interface. I will change this now.

**Comment by martyngigg** [comment]
Thanks, @ElliotAOram

**Comment by martyngigg** [comment]
Looks okay to me now.

**Pull request merged**
