### PR TITLE
Use system python even if anaconda is in the path

### PR DESCRIPTION
**Pull request by peterfpeterson**
Some users at ORNL have been installing python which breaks `mantidpython` in a variety of ways. This starts the python that mantid was built with. This is only a solution for linux.

**To test:**
1. Activate anaconda (may need to install it first)
2. Start `mantidpython` and see that it happily tries to startup with that python. You can see which version is started by running `import sys;print sys.argv[0]". This cannot be passed via the command line as a`-c` option though.
3. Rerun `cmake to` get the templates filled in
4. Start `mantidpython` again to see the warning
5. Deactivate anaconda, start `mantidpython` and don't see the warning

Also try out `mantidpython --classic` (vanilla python) and `mantidpython notebook` to start a jupyter notebook.

_There is no associated issue_

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by rosswhitfield** [comment]
How about changing `command -v ipython` to just `/usr/bin/ipython`? Is there an OS that this doesn't work?

**Comment by peterfpeterson** [comment]
This is a stopgap until we can find a more reliable way to figure out which `ipython` we were compiled against. CMake gives us `PYTHON_EXECUTABLE` but doesn't currently give out `IPYTHON_EXECUTABLE`. Once it does we can get rid of this warning and the `if` at the top of the script. Looking closer at the windows version of this file, it already implements something like that.

**Comment by peterfpeterson** [comment]
Most of the previous comments can be ignored as this is a completely new solution that just uses the python mantid was built with.

**Comment by rosswhitfield** [comment]
It works. I tested it will python 2 and 3. :shipit:

**Pull request merged**
