### PR TITLE
New algorithm for MD Normalization for single crystal data

### LINKED ISSUE #23320: Allow non-axis aligned cuts and slices in MDNorm algorithms
For single crystal diffraction and inelastic one might want to perform non axis-aligned cuts/slices. This can also be used to perform symmetry operation. The issue is keeping track of detector trajectories end points. To this end, the following steps have to be performed:

- [x] Create an algorithm to store information about end of the detector trajectories into a matrix workspace PR #23351
- [x] Have an algorithm recalculate the limits after the conversion to an MD workspace PR #23928
- [ ] Calculate binning and normalization for arbitrary directions and for symmetry related directions.

### PR DESCRIPTION
**Pull request by AndreiSavici**
**Description of work.**
This provides an algorithm to calculate single crystal `S(Q)` (diffraction) or `S(Q,DeltaE)` (direct geometry inelastic)

**To test:**
Run the examples in systemtests or documentation.

Fixes #23320 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by OwenArnold** [comment]
@AndreiSavici how does this tie-in or differ from the existing suite of Algorithms in this direction, for example `MDNormSCD`?

**Comment by AndreiSavici** [comment]
@OwenArnold It's going to replace them. Think of BinMD with non axis-aligned option vs axis aligned. After some thorough testing (think about 2 releases) `MDNormSCD` and `MDNormDirectSC` will be deprecated

**Review by VickieLynch — COMMENTED** [review]
Figure for single crystal in docs does not match example script. Everything else looks goodk.

**Review by rosswhitfield — APPROVED** [review]
Tried different combinations of merged runs and different symmetry operations, at least for single crystal this appears to be doing the correct thing.

**Pull request merged**
