### PR TITLE
Allow start and end X boxes to be negative in model fitting

### LINKED ISSUE #32450: Model Fitting fit range negative number not allowed
**Original reporter:** James Lord

**Describe the bug**
The Start and End X in Model fitting appears to get confused after a while of switching between parameters. The negative sign `-` also cant seem to be entered for some reason.

**To Reproduce**
1. Load HIFI 77766-77786
2. Fitting tab, tick simultaneous fit
2. Fitting tab, add Chebyshev with n=4 and ExpDecayOsc with Frequency =1
3. Sequential fit all with `Initial parameters for each fit` checked
4. Create results table
5. Go model fitting and select f1.Phi as the x parameter. The start X is negative, but trying to change it to another negative number will not be allowed.

**Platform/Version (please complete the following information):**
Windows

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR allows you to enter a negative value for the start or end X when necessary in the model fitting tab. Previously the double was only allowed to be positive (probably because we didn't need to allow negative numbers previously).

**To test:**
Load HIFI 77766-77776. Wait for them to load
Fitting tab, select simultaneous fit
Add a Chebyshev function with n=4 and ExpDecayOsc with Frequency =1
Sequential fit all with Initial parameters for each fit checked
Create results table on the results tab
Go to model fitting. Select the `f1.Phi` parameter to be the x parameter.
Attempt to change the Start X (which is already negative) to another negative number. This should now be possible.
Make sure the Start X doesn't go lower than the lowest data value on the x axis of the plot.

Fixes #32450

*This does not require release notes* because **previously we did not need to enter a negative value for start and end X, but we will for model fitting.*

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by sf1919 — DISMISSED** [review]
I have tested this and it works well. You can now change to a negative X value but the Start Value in the Model Fitting tab does not change.

Looking at the code there are a couple of changes I would request. The first is - should we be writing a test for this? As this is potentially a new feature then I think it would be a good idea to do this.

Secondly I think there should be a release note for this. It is perhaps not a bug as the funtionality has not been required before. However looking at the code I'm wondering if this enables negative X axis changes on other plots? If so I think I would add this to the release notes as an improvement rather than a bug fix.

**Comment by martyngigg** [comment]
Can I just double check if this is for the release or not? The milestone is 6.2 but target branch is master.

**Comment by AnthonyLim23** [comment]
I have updated this to be against release. This is because being able to fit to the negative range is also helpful for fitting to FFT data.

- open the frequency GUI
- Load MUSR 62260
- Go to the transform tab and click calculate
- Change the x range on the plot to -500 to 500
- Go to the fitting tab
- Add a flat BG, and 2 gaussians (sigma = 10 for both and the centres should be 100 and -100)
- Change the range to -500 to 500
- Click fit - it will work


There are no tests because it changes views.

I have updated the release notes

**Review by SilkeSchomann — APPROVED** [review]
Negative frequencies can now be fitted. There is also a release note.

**Pull request merged**
