### PR TITLE
Move MuonAnalysis documentation to .rst file

### LINKED ISSUE #11731: Update Muon Interface documentation
This issue was originally [TRAC 10892](http://trac.mantidproject.org/mantid/ticket/10892)

This ticket is to update the muon interface documentation. Add also a link to the muon group webpage where data can be downloaded.

### LINKED ISSUE #13644: Move MuonAnalysis documentation to mantid help system
Move the content of the wiki pages: http://www.mantidproject.org/MuonAnalysis to a new .rst file.

Also, review and add new functionality/improvements added to the interface that is not included there.

### PR DESCRIPTION
**Pull request by raquelalvarezbanos**
Sulaimaan (work experience student at ISIS) created an .rst file for the `MuonAnalysis` interface.

**To test:**

Build and read the documentation for the `MuonAnalysis` interface. It should look similar to the [wiki page](http://www.mantidproject.org/MuonAnalysisSettings).

I've noticed that in the `Home` tab, section `Detector Grouping`, the option to specify a value for `alpha` does not seem to exist any more, so I've removed the section explaining how to use it. This is the only difference with the wiki page.

Fixes #13644.
Fixes #11731

[Release notes](https://github.com/mantidproject/mantid/blob/f51624cf2c51695d82128c9d88efaa5de77893b1/docs/source/release/v3.8.0/muon.rst) have been updated.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
I'm away next week, so I'm unassigning myself, so someone else can test it, if the build problem is fixed.

**Comment by tom-perkins** [comment]
All the documentation from the wiki page has been migrated to rst and looks good. 

The alpha text box is still present, but only appears if a pair is selected (it is not visible when a group is selected, or before data is loaded). The description of this box should be replaced, with a note explaining that it is only visible for pairs. 

*No data:*
nodata

*Group:*
group

*Pair:*
pair

The images of the different tabs of the interface have been replaced by automated screenshots - this is a good improvement as they will always be up to date in this way.

The Ubuntu build keeps failing for some reason, but is not related to this PR (no code changes here).

**Comment by raquelalvarezbanos** [comment]
Thanks @tom-perkins I'll update that when I am back from my holidays.

**Comment by tom-perkins** [comment]
All looks good :shipit:

**Comment by FedeMPouzols** [comment]
There were some failures in doc tests (apparently related to fitting results slightly different than expected) but that has nothing to do with this branch.

**Pull request merged**
