### PR TITLE
Fix python lib errors

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR fixes python lib errors occuring on master. Fixed by @martyngigg & @DavidFair .

**To test:**
Try building and there should be none of these errors.

https://files.slack.com/files-pri/T02J4MMEW-F01GSU1D909/image.png

No related issue. No release notes required.

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DavidFair** [comment]
Marking high priority as this affects multiple people building master

**Comment by martyngigg** [comment]
Thanks both. I'll just wait to the build parts of the CI run and merge when they are done.

**Comment by martyngigg** [comment]
Sorry @DavidFair I hadn't spotted the assignment. Feel free to merge this when you are happy.

**Review by DavidFair — APPROVED** [review]
This builds for me from fresh

It's also been ack'd by Harriet and Joe as fixing their problem too on existing build directories

**Comment by DavidFair** [comment]
I'm happy if you want to merge it too @martyngigg - whoever noticed first when the CI jobs finish :smile:

**Comment by DavidFair** [comment]
Failure is unrelated

**Pull request merged**
