### PR TITLE
Add warning on QENS Fitting interface for missing workspaces

### LINKED ISSUE #37706: Crash in the IQt tab
**Describe the bug**
Crash upon deleting ws in the ADS with the `Clear` button and re-running fitting.

**To Reproduce**
1. Go to Interfaces->Inelastic->I(Q, T)
2. Click Add Workspace and add [irs26176_graphite002_iqt.zip](https://github.com/user-attachments/files/16331874/irs26176_graphite002_iqt.zip)
3. Set the indices from 0-5
4. Add two Expontatials
5. Click Run
6. Delete all workspaces from the ADS by clicking on `Clear`
7. Click Run
8. Mantid crashes with unhandled exception

**Expected behavior**

Error is displayed instead of crash.

**Platform/Version (please complete the following information):**
 - OS: Ubuntu
 - OS Version: 22.04
 - Mantid Version 6.10

### PR DESCRIPTION
**Pull request by adriazalvarez**
### Description of work
This PR fixes #37706. Although I haven't been able to reproduce the crash described in the issue neither on Windows nor MacOSX. I have reproduced a crash in the conditions described in #37706 on Mantid v6.10 when workspaces needed in the QENS interface are deleted from the ADS and the `Run` button is clicked. 
I think this crash was fixed during this sprint as a `Run` widget has been added in place of the `Run` button in most Inelastic interfaces. This widget catches exceptions thrown from the presenter or the model when  the `Run` button is clicked, and avoids the aforementioned crash. 
However, due to the way the ADS handles the workspaces when they are cleared vs. when they are deleted, the behaviour is different. In one case(Delete) the error is caught in the model, and shown as a warning dialog, while in the other case (Clear) the error is caught by the algorithm per-se, and gives an uninformative error message on the Messages center('_Algorithm Property does not exist_'). 

#### Summary of work
I have added a check in the validation stage of the data presenter that checks the workspaces in the data model against the workspaces in the ADS, and raise an error if any of the workspaces on the data model is not on the ADS. Now in both cases, Delete and Clear workspaces, error message will be the same, informing that the problem is that one of the target workspace has been deleted from the ADS. 

Fixes #37706 . 

### To test:
1. Open `Interfaces->Inelastic->QENS Fitting'
2. Go to `I(Q,t)` tab and load some sample data: 'irs26174_graphite002_iqt` from the Usage Data. 
3. On the property browser, add 1 exponential to fit. 
4. Delete the workspace: `irs26174_graphite002_iqt` from the ADS (click on delete). 
5. Click on `Run` button on the interface. 
6. A warning box with message : `No input data...` should appear. 
7. Close the `QENS Fitting` interface and repeat steps 1-6, but this time remove the workspace by clearing the ADS
instead of deleting. Same warning message should appear. 
---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by SilkeSchomann** [comment]
@adriazalvarez Is it possible to add a test for this warning?

**Review by Despiix — APPROVED** [review]
Manual tested acording to test instructions. The pop up appears during both occasions (clear and delete). The code also looks good!
Tested on: Windows 11

**Comment by robertapplin** [comment]
Unassigned myself as I realised there is still a comment from Silke that needs addressing

**Comment by adriazalvarez** [comment]
@SilkeSchomann We don't have at the moment tests for the this IqtPresenter, if you agree, it would be a good idea to to add these tests as part of a separate issue, I have opened it here. #37890

**Pull request merged**
