### PR TITLE
Updated MSlice version to 2.10.1

### PR DESCRIPTION
**Pull request by SilkeSchomann**
#### Summary of work

This PR updates the MSlice version used by Mantid workbench from 2.10 to 2.10.1 so that the nightly builds of Mantid use an MSlice version that is compatible with matplotlib 3.9.2.

*There is no associated issue.*

### To test:

Check that all tests pass. You could also install Mantid workbench from the artifacts and check that the MSlice interface opens without an error message.

*This does not require release notes* because **this is not the version of MSlice that will be used in Mantid release 6.12., but a temporary version.**

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by jclarkeSTFC** [comment]
Shouldn't conda pick up 2.12.1 with the old pin? The third version number isn't specified so I would have thought that conda would get the latest 2.12.* version

**Comment by perenon** [comment]
For your information, we have at ILL an automatic mechanism installing the nightly in a conda env. every night. 
Today, the conda env. contains the 2.10_62 version of mslice. The mslice interfaces opens properly.

**Comment by SilkeSchomann** [comment]
> Shouldn't conda pick up 2.10.1 with the old pin? The third version number isn't specified so I would have thought that conda would get the latest 2.10.* version

Unfortunately not, otherwise the current nightly would use MSlice 2.10.1 now and not 2.10. I think that only works when the pin is 2.10.*. Since MSlice is normally not released between Mantid releases, an exact pin is the safer option.

**Comment by SilkeSchomann** [comment]
> For your information, we have at ILL an automatic mechanism installing the nightly in a conda env. every night. Today, the conda env. contains the 2.10_62 version of mslice. The mslice interfaces opens properly.

In this case it picked up the MSlice nightly version instead of the released version. For a Mantid nightly this is fine, but I doubt that we want this behaviour for released versions of Mantid.

**Review by jclarkeSTFC — APPROVED** [review]

**Pull request merged**
