### PR TITLE
Error from selecting curves in plot options

### LINKED ISSUE #37358: Error from editing plot settings in a plot
**Original reporter:** James Cresswell

**Describe the bug**
Hiding curves in the settings dialog in a plot caused an error:
```
  File "/opt/mantidworkbenchnightly/lib/python3.10/site-packages/mantidqt/widgets/plotconfigdialog/presenter.py", line 75, in apply_properties
    tab.apply_properties()
  File "/opt/mantidworkbenchnightly/lib/python3.10/site-packages/mantidqt/widgets/plotconfigdialog/curvestabwidget/presenter.py", line 65, in apply_properties
    self._replot_current_curve(plot_kwargs)
  File "/opt/mantidworkbenchnightly/lib/python3.10/site-packages/mantidqt/widgets/plotconfigdialog/curvestabwidget/presenter.py", line 153, in _replot_current_curve
    ax.add_line(lines_to_remove.pop())
IndexError: pop from empty list
```

**To Reproduce**
I asked the user for the data he used and he sent me this folder: 
[MantidTroubleshooting.zip](https://github.com/mantidproject/mantid/files/15307167/MantidTroubleshooting.zip)

The script generated from the faulty plot was the following:
```python
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np


import matplotlib.pyplot as plt
from mantid.plots.utility import MantidAxType
from mantid.api import AnalysisDataService as ADS

IvsQ_74306_74307_74308 = ADS.retrieve('IvsQ_74306_74307_74308')
IvsQ_74374_74375_74376 = ADS.retrieve('IvsQ_74374_74375_74376')
IvsQ_74324_74325_74326 = ADS.retrieve('IvsQ_74324_74325_74326')
IvsQ_74388_74389 = ADS.retrieve('IvsQ_74388_74389')
IvsQ_74342_74343_74344 = ADS.retrieve('IvsQ_74342_74343_74344')

fig, axes = plt.subplots(edgecolor='#ffffff', num='S12 MS024', subplot_kw={'projection': 'mantid'})
axes.errorbar(IvsQ_74342_74343_74344, capsize=1.0, color='#1f77b4', elinewidth=1.0, label='IvsQ_74342_74343_74344: spec 330', linewidth=1.0, marker='.', markersize=4.0, wkspIndex=0)
axes.errorbar(IvsQ_74324_74325_74326, capsize=1.0, color='#ff7f0e', elinewidth=1.0, label='IvsQ_74324_74325_74326: spec 330', linewidth=1.0, marker='.', markersize=4.0, wkspIndex=0)
axes.errorbar(IvsQ_74306_74307_74308, capsize=1.0, color='#2ca02c', elinewidth=1.0, label='IvsQ_74306_74307_74308: spec 330', linewidth=1.0, marker='.', markersize=4.0, wkspIndex=0)
axes.errorbar(IvsQ_74388_74389, capsize=1.0, color='#e377c2', elinewidth=1.0, label='S12 Si PET MS024 Rinse Lipid Air IvsQ_74388_74389: spec 330', linewidth=1.0, marker='.', markersize=4.0, wkspIndex=0)
axes.errorbar(IvsQ_74374_74375_74376, capsize=1.0, color='#d62728', elinewidth=1.0, label='IvsQ_74374_74375_74376: spec 330', linewidth=1.0, marker='.', markersize=4.0, wkspIndex=0)
axes.minorticks_on()
axes.tick_params(axis='x', which='minor', **{'gridOn': False, 'tick1On': True, 'tick2On': False, 'label1On': True, 'label2On': False, 'size': 0, 'tickdir': 'out', 'width': 1})
axes.tick_params(axis='y', which='minor', **{'gridOn': False, 'tick1On': True, 'tick2On': False, 'label1On': True, 'label2On': False, 'size': 0, 'tickdir': 'out', 'width': 1})
axes.tick_params(axis='x', which='major', **{'gridOn': True, 'tick1On': True, 'tick2On': False, 'label1On': True, 'label2On': False, 'size': 6, 'tickdir': 'out', 'width': 1})
axes.tick_params(axis='y', which='major', **{'gridOn': True, 'tick1On': True, 'tick2On': False, 'label1On': True, 'label2On': False, 'size': 6, 'tickdir': 'out', 'width': 1})
axes.set_title('S12 MS024')
axes.set_xlabel('q ($\\AA^{-1}$)')
axes.set_ylabel('Reflectivity')
axes.set_xlim([0.0079686, 0.39723])
axes.set_ylim([0.0, 3.4784])
axes.set_xscale('log')
axes.set_yscale('log')
legend = axes.legend(fontsize=8.0).set_draggable(True).legend

fig.show()
# Use plt.show() if running the script outside of Workbench
#plt.show()
# Scripting Plots in Mantid:
# https://docs.mantidproject.org/tutorials/python_in_mantid/plotting/02_scripting_plots.html
``` 

Then open the plot options dialog.
Select the second or the third curve and click Apply. You should get an error.
If you select and deselect other curves, you should also get an error sometimes.

**Expected behavior**
No error when selecting or deselecting other curves.
No change of behaviour when changes are applied but nothing was changed in the plotconfigdialog

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: Rocky Linux 8.9 (Green Obsidian)
 - Mantid Version 6.9.20240425.1854

### PR DESCRIPTION
**Pull request by GuiMacielPereira**
### Description of work
Fixes https://github.com/mantidproject/mantid/issues/37358

### To test:
Follow instructions on https://github.com/mantidproject/mantid/issues/37358 and check that no error is thrown

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by jhaigh0 — DISMISSED** [review]
Can't reproduce the crash using the instructions. Just needs a release note now 👍

**Review by cailafinn — CHANGES_REQUESTED** [review]
Could we have a unit test to catch the crashing behaviour? Otherwise code looks good and functionally working well. No longer crashing with a variety of attempts and different workspaces.

**Comment by GuiMacielPereira** [comment]
Added unit test, checked that it failed when using previous code. Interestingly, this issue only arises if the `plt.errorbar()` has  the arguments `marker, markersize, capsize`. Not sure why, but probably because it adds cap lines to the error bar container

**Review by cailafinn — APPROVED** [review]
New test looks good, code looks good, working well functionally. Nice work. 

Incidentally, the cause of the extra lines is due to the error bar caps. They're represented under the hood in `matplotlib` by two additional sets of "lines" (`ax.get_lines()`) without lines between the data points but with the horizontal line markers to represent the caps. This is why the index was ending up all wrong.

**Pull request merged**
