### PR TITLE
Close sliceviewer when underlying ws deleted

### LINKED ISSUE #32638: Sliceviewer doesn't close when workspace deleted
**Describe the bug**
When deleting the workspace (both underlying and rebinned)  workspace it doesn't close the sliceviewer window

**To Reproduce**
(1) Make workspace
```
ws = CreateMDWorkspace(Dimensions='3', Extents='-5,5,-5,5,-5,5',
                       Names='Q_lab_x,Q_lab_y,Q_lab_z', Units='U,U,U',
                       Frames='QLab,QLab,QLab',
                       SplitInto='2', SplitThreshold='50')
```
(2) Open it in sliceviewer
(3) Delete the _svrebinned and the original workspace (don't use clear)

**Expected behavior**
Would close sliceviewer - as it did in 6.1

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: [e.g. Windows, RHEL 7, Ubuntu, macOS]
 - OS Version:
 - Mantid Version [e.g. 6.0.0]

**Additional context**

### PR DESCRIPTION
**Pull request by RichardWaiteSTFC**
**Description of work.**
Since the changes in #32204, the slice viewer wasn't closing when the underlying workspace is deleted. The workspace name is now stored in the slice viewer model to avoid the problem.

**To test:**

1. Load some data and open the slice viewer.
2. Delete the workspace and verify that the slice viewer closes.
3. Load some data and open the slice viewer.
4. Rename the workspace and verify that the window title of the slice viewer chnages.
5. Delete the workspace and verify that the slice viewer closes.

Fixes #32638 

*This does not require release notes* because it was a bug introduced since the last release.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by RichardWaiteSTFC** [comment]
This test doesn't seem to be effected by the blocking on the QThreadAppCall for the delete handle - the ws name of model ws is not set to empty when blocking=False
https://github.com/mantidproject/mantid/blob/8d9f695d08b0ebb9b9ff98cef7ec544bdb757063/qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_view.py#L188

**Comment by thomashampson** [comment]
This test now hangs:
https://github.com/mantidproject/mantid/blob/8d9f695d08b0ebb9b9ff98cef7ec544bdb757063/qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_view.py#L239

**Comment by DavidFair** [comment]
Just an FYI this interface is still leaking memory and not clearing up it's workspace handle on deletion, this doesn't need to be fixed for the release though.

**Review by RichardWaiteSTFC — COMMENTED** [review]
This looks good - sliceviewer behaves as expected for rename, deletion, rename and deletion, and replacement (which shouldn't have changed). 
There is the issue of the test didn't pick up the bug but I think this doesn't need to be fixed for the release
https://github.com/mantidproject/mantid/blob/8d9f695d08b0ebb9b9ff98cef7ec544bdb757063/qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_view.py#L188
If the tests pass then this should be approved (but I can't do it myself because nominally it's my PR).

**Comment by DavidFair** [comment]
@RichardWaiteSTFC If you're happy with Tom's changes can you approve
@thomashampson if you're happy with Richard's changes can you approve

I'll merge this once I get both and/or a third reviewer joins the foray - that we we all review each other's code

**Review by DavidFair — APPROVED** [review]

**Comment by martyngigg** [comment]
Thanks for getting this through everyone!

**Pull request merged**
