### PR TITLE
Expose fit parameters in JumpFit UI

### LINKED ISSUE #12734: Expose fit parameters to JumpFit UI
The current parameters were put in for water but may not work for all samples, they should be exposed to the JumpFit UI.

This will mean that the JumpFit algorithm can just be removed, as essentially this was just a wrapper around Fit and the UI will just call Fit directly.

This is also a good time to try creating the UI programatically from a fit function which is going to be needed for ConvFit in #12669.

### PR DESCRIPTION
**Pull request by DanNixon**
Fixes #12734.

To test:
- Open Indirect > Bayes > JumpFit
- Load `Babylon5/Public/DanNixon/data/cf_Result.nxs`
- Fit should be generated automatically and parameters updated in property browser
- Change the fit function

Release notes updates [here](http://www.mantidproject.org/index.php?title=Release_Notes_3_5_Indirect_Inelastic&diff=24279&oldid=24276).

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
When I reproduce the steps in the description the fitting parameters are updated in the property browser, but I get the following error:

>Error in execution of algorithm Fit:
>Infinte number or NaN found in input data.
>Error in execution of algorithm JumpFit:
>Infinte number or NaN found in input data.
>Unknown error starting next batch algorithm
>Got error from algorithm "JumpFit"
>Stopping batch algorithm because of execution error

It seems that there is something wrong with the input file? If I change the fitting range it works and the Fit (and Diff) curves are displayed in the plot.

**Comment by DanNixon** [comment]
I was just about to comment with some better data to use, indeed the original data did contain a couple of NaN values and I'm fairly sure this was the issue.

**Comment by raquelalvarezbanos** [comment]
If you want me to test it with the better data just let me know, but I agree that the issue was due to the input dataset rather than the code.

**Comment by DanNixon** [comment]
I think this may also be causing master builds to fail. At least locally for me.

**Pull request merged**
