### PR TITLE
[SCD451] update mod UB in SelectCellOfType

### PR DESCRIPTION
**Pull request by KedoKudo**
**Description of work.**
- Original Gitlab Story: [SCD451](https://code.ornl.gov/sns-hfir-scse/diffraction/single-crystal/single-crystal-diffraction/-/issues/451)
- This is #33570 into `main`

The current `SelectCellOfType` and `SelectCellWithForm` is trying to update the HKL using the transformation from unit cell class, which only works if the transformation is between very different unit cell types.
However, for cases where the same unit cell type with different unit cell base permutation (e.g. going from a,b,c to b,c,a), this will fail as the transformation matrix from the unit cell will always be an identical matrix, but the unit cell base has already changed (i.e. the UB has changed).
To resolve this issue, the following changes are introduced in this PR:

- The transformation matrix for HKL is calculated from the current UB and the new UB instead of directly from the unit cell HKL transformation.
- Both `SelectCellOfType` and `SelectCellWithForm` now uses the standard `validateInputs` to check the validity of the inputs instead of during the `exec()`
- Variable names are updated to be more explicit instead of using abbreviations.
- The modUB update is included in  `SelectCellOfType`  via a new member function added into `SelectCellWithForm`.

**To test:**
- Build the branch and launch the workbench on a machine with access to SNS data
- Use the following script to perform the test

```python
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

LoadIsawPeaks(Filename='/SNS/TOPAZ/IPTS-10003/shared/xpwang/K2V3O8_1213_2021_use_workbench/xpwang_2019_sat_Niggli.integrate', OutputWorkspace='Niggli_peaks')
FindUBUsingIndexedPeaks(PeaksWorkspace='Niggli_peaks', Tolerance=0.12, ToleranceForSatellite=0.07, CommonUBForAll=True)
IndexPeaks(PeaksWorkspace='Niggli_peaks', Tolerance=0.12, ToleranceForSatellite=0.07, RoundHKLs=False, CommonUBForAll=True)
FindUBUsingIndexedPeaks(PeaksWorkspace='Niggli_peaks', Tolerance=0.12, ToleranceForSatellite=0.07, CommonUBForAll=True)
#
SelectCellOfType(PeaksWorkspace='Niggli_peaks', CellType='Orthorhombic', Centering='P', Apply=True, AllowPermutations=True)
#
IndexPeaks(PeaksWorkspace='Niggli_peaks', Tolerance=0.12, ToleranceForSatellite=0.07, RoundHKLs=False, CommonUBForAll=True)
FindUBUsingIndexedPeaks(PeaksWorkspace='Niggli_peaks', Tolerance=0.12, ToleranceForSatellite=0.07, CommonUBForAll=True)
```
- From the console, confirming that the mod vector are permutated in a similar fashion to the lattice constants.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by rosswhitfield — CHANGES_REQUESTED** [review]
After running your script, if I do `SaveIsawUB('Niggli_peaks', 'ub.mat')` the saved UB contains no modulation vectors where previously it did. Is that the correct behaviour?

**Comment by sf1919** [comment]
Please can you change the release note? We have now moved to separate release notes (deadline for merging in older PRs has now passed). Further details can be found at https://forum.mantidproject.org/t/move-to-separate-release-notes/803

**Comment by KedoKudo** [comment]
Our CIS is working on writing a new story to address the underlying issue, therefore this PR is currently on hold (no change will be made to this PR until the new story is ready). If needed, I can close this PR.

**Comment by sf1919** [comment]
Theres no need to close this PR - we just need to make sure it does not get merged with a note going directly into framework.rst as I'm about to start moving all the notes currently in their out to a new file.

**Pull request closed without merging**
