### PR TITLE
Fix plotting integrated peaks in sliceviewer with no background

### PR DESCRIPTION
**Pull request by rosswhitfield**
I introduced this bug in #30661 :facepalm: 

**Description of work.**

Mantid crashes when trying to plot integrated spherical and elliptical peaks when there is no background.

**To test:**

Extending the examples from #30661

These should now work. Open with sliceviewer and select the different peaks.

```python
ws = CreateMDWorkspace(Dimensions='3', Extents='-2,2,-2,2,-2,2',
                       Names='Q_lab_x,Q_lab_y,Q_lab_z', Units='U,U,U',
                       Frames='QLab,QLab,QLab',
                       SplitInto='2', SplitThreshold='50')
expt_info = CreateSampleWorkspace()
ws.addExperimentInfo(expt_info)

# add peak
p = CreatePeaksWorkspace(InstrumentWorkspace='ws', NumberOfPeaks=0, OutputWorkspace='peaks')
SetUB('peaks', 1,1,1,90,90,90)
pk = p.createPeak([1,1,1]) # axes aligned with viewing axes
p.addPeak(pk)

IntegratePeaksMD(InputWorkspace='ws', PeakRadius=0.5, PeaksWorkspace='peaks', OutputWorkspace='sphere_no_bg')
IntegratePeaksMD(InputWorkspace='ws', PeakRadius=[0.5,0.4,0.3], Ellipsoid=True, PeaksWorkspace='peaks', OutputWorkspace='ellipse_no_bg')
```

*This does not require release notes* because it was only added this release.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by RichardWaiteSTFC** [comment]
Hmm, sorry I missed that too - I always forget to check no background that's why I made the test `test_draw_creates_ellipse_with_expected_properties_with_nonzero_alpha_no_background` in `test_peaksviewer_representation_ellipsoid.py` - is it no longer working as expected? Maybe there should be a similar test for spherical too - I have an open PR that has touched these tests so I could look into it tomorrow if you need this merged in a hurry?

**Comment by rosswhitfield** [comment]
> Hmm, sorry I missed that too - I always forget to check no background that's why I made the test `test_draw_creates_ellipse_with_expected_properties_with_nonzero_alpha_no_background` in `test_peaksviewer_representation_ellipsoid.py` - is it no longer working as expected? Maybe there should be a similar test for spherical too - I have an open PR that has touched these tests so I could look into it tomorrow if you need this merged in a hurry?

I think the reason it wasn't picked up by the test was the `bg_outer` were being set to zero where it appears sometimes in practice they are `None`. If you want to dig into the tests later that would be great.

**Comment by RichardWaiteSTFC** [comment]
> I think the reason it wasn't picked up by the test was the `bg_outer` were being set to zero where it appears sometimes in practice they are `None`. If you want to dig into the tests later that would be great.

I am testing this now but maybe instead we should set the background radii consistently to be either 0 (as I believe it used to be prior to #30430 and fixed in #30623?) or None in the event the backgorund integration/subtraction wasn't requested.

**Review by RichardWaiteSTFC — APPROVED** [review]
Bug fix works well - long term I think we should set the background radii to consistently in the event no subtraction is done but perhaps I can address this in my PR #30657 without holding up this fix

**Pull request merged**
