### PR TITLE
Fix 2 for calMuonDetectorPhases doc

### PR DESCRIPTION
**Pull request by AnthonyLim23**
An OSX doc test was failing so it has been updated.

Build the docs and run the doc test on the OSX server. 

**To test:**

**Release Notes** 

---
doesnt need to be in release notes
#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by keeeto — APPROVED** [review]
This code runs and produces the required results on OSX.

**Comment by martyngigg** [comment]
@AnthonyLim23 This is now unfortunately failing on Ubuntu

**Comment by martyngigg** [comment]
I just tried it out on the builder and it looks good. :+1:

**Comment by AnthonyLim23** [comment]
unrelated failure

**Pull request merged**
