### PR TITLE
Neutron energy calculation in DetectorEfficiencyCorUser

### LINKED ISSUE #16745: Fix energy calculation in DetectorEfficiencyCorUser algorithm
### Expected behavior
The final neutron energy for the efficiency evaluation should be calculated either as E = E_i - DeltaE or E = E_i + DeltaE depending on the convention.

### Actual behavior
In some cases, the convention E = E_i + DeltaE is erroneously chosen due to broken heuristics.

### PR DESCRIPTION
**Pull request by soininen**
Always assume final energy E_f = E_i - dE (E_i initial energy, dE energy transfer) for the detector efficiency calculation in the DetectorEfficiencyCorUser algorithm.

Fixes #16745.

_Does not need to be in the release notes._

### CODE REVIEW

**Comment by abuts** [comment]
Could you, please resolve the conflicts as I can not easy  see changes full changes.

As for the changes itself I do not fully understand the reason -- 

it seems the algorithm is intended for use by direct instruments only (second part of the formula within the loop) but the check of the sign convention is done for direct vs indirect instruments. 

Is this correct? 


The purpose of the algorithm is not entire clear. 
As I understand, it corrects detector efficiency according to a user-provided formula. Why is the formula, tabulated in DetectorEfficiencyCorrections insufficient? 

The algorithm needs better description of its applicability and limitations (not this ticket, scope but  would substantially help to understand the algorithm purpose...)

**Comment by mganeva** [comment]
Since we also use this algorithm for TOFTOF@MLZ, may be I could comment on the purpose. The formula tabulated in the DetectorEfficiencyCor algorithm considers only the probability of neutron detection by each detector. For TOFTOF, the energy-dependent intensity loss factor accounts also for absorption of neutrons by the Ar gas in the flight chamber, Al windows of sample environment and so on.

The formula derived for TOFTOF (see paper T. Unruh, 2007, doi:10.1016/j.nima.2007.07.015) is set in the instrument parameter file and is used by DetectorEfficiencyCorUser algorithm.

**Comment by abuts** [comment]
This would be nice to have in the algorithm description. 
Anyway, the branch is currently in conflict with master.

**Comment by soininen** [comment]
The algorithm is indeed for direct geometry instruments. I do not think it makes sense to use it for indirect geometry, as in backscattering instruments the final neutron energy is defined by the analyzer and is thus constant.

As for not using DetectorEfficiencyCor or He3TubeEfficiency algorithms, ILL is in the same situation as MLZ: more accurate efficiency corrections for the IN4, IN5 and IN6 instruments exist.

I will fix the merge conflicts, do some code cleanup, and revise the algorithm description.

**Comment by abuts** [comment]
github still claims conflicts (no commit?)

**Comment by soininen** [comment]
No push yet.

**Comment by soininen** [comment]
After a bit of trouble with the build servers, this should be ready for another review.

**Comment by abuts** [comment]
changes are clear and look reasonably simple. Algorithm works.
:shipit:

**Comment by FedeMPouzols** [comment]
It appears that the branch has some merge conflict. @soininen could you merge master again and see what happened? There may be some conflict with the large Histogram roll-out PR that has been merged today.

**Comment by soininen** [comment]
@FedeMPouzols, the merge conflicts have been resolved.

**Pull request merged**
