### PR TITLE
Indirect Data Analysis Jump Fit - Add PlotGuess option

### LINKED ISSUE #15413: Indirect Data Analysis JumpFit - Add plot Guess option
When the auto run feature was removed from JumpFit the Diff curve (that was shown before running) was also removed. It would be useful to restore this curve as a plot guess. 
* [x] Update interface with plot guess option
* [x] Signal/Slot for running while plot guess is checked
* [x] Ensure the ADS is kept clean during the plot guessing

### PR DESCRIPTION
**Pull request by ElliotAOram**
The JumpFit interface now has a plot guess option allowing the user to view what the fit will be like before running it. 
# To test:
- Turn on `Show Invisible Workspaces` (Preferences > Mantid > Options > 2nd tick box from top)
- Test data can be found at `\\olympic\babylon5\Public\ElliotOram\DataAnalysis\JumpFit\IRIS`
- Open JumpFit (Interfaces > Indirect > Data Analysis > Jump Fit)
- Load in Sample (`irs26176_graphite002_Result.nxs`)
- Check the `PlotGuess` option in the interface 
  - Ensure a green PlotGuess curve appears in the mini plot
  - Ensure a single workspace is added to the ADS
- Change the value for `Tau`
  - Ensure the PlotGuess curve updates
- Change the `Fit Function`
  - Ensure the PlotGuess still appears in after the function has changed
    - The curve will most likely not be the same as previous
- Uncheck the PlotGuess option
  - Ensure the workspaces originally generated in the ADS are removed
- Check the Plot Guess option again
- Click `Run`
  - Ensure the mini plot is updated with a red and blue curve (`Fit` and `Diff`)
  - Ensure the PlotGuess option has been unchecked
  - Ensure the green curve no longer exists in the mini plot
  - Ensure the PlotGuess workspace is removed from the ADS

Fixes #15413 

**[Release notes](http://www.mantidproject.org/Release_Notes_3_7_Indirect_Inelastic#Jump_Fit)**

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by shahrozahmed1** [comment]
when combo-box `Fit Function` is set as `ChudleyElliot` with new `tau` value; it updates the green curve .. however when I change `Fit Function` to `TeixeiraWater` or `HallRoss` and then change `tau`, the green curve is not updated. Other than that everything else seems to work fine.

**Comment by shahrozahmed1** [comment]
maybe a small description of the change made to [Jump Fit tab](https://github.com/mantidproject/mantid/blob/master/docs/source/interfaces/Indirect_DataAnalysis.rst#jumpfit) in the documentation

**Comment by ElliotAOram** [comment]
@shahrozahmed1 I've looked into this and this is actually not a problem. These fit function don't seem to be overly sensitive to initial parameters (possible because this data set is very straight forward for fitting as well. You can get variation out of it though.
Try the following:
* HallRoss:
  * Tau=1, L=1
  * Tau=1, L=0.01
* Fick Diffusion;
   * D=1
   * D=0
* TeixeiraWater
  * Tau=1, L=1
  * Tau=1, L=0.01

**Comment by shahrozahmed1** [comment]
Tests provided for `HallRoss`, `Fick Diffusion` & `TeixeiraWater` produces good output. `PlotGuess` option works well in general, this PR is ready to be merged ..:shipit:..

**Pull request merged**
