### PR TITLE
Fixes for isis sans gui

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
No Release notes and no issue number.

### Test for bad incident monitor

* Use the loqdemo data and test that the reduction completes without issues

### Test that masking table updating works

* On the mask table tab, after loading a user file and data. Press the `Update Rows` button and confirm that it updates

### Test that merged reduction can be run

* With the test data run a merged reduction

### Test that masking tables for zoom works

* Create a mask for zoom data, add it to the user file and load the user file and data into Mantid
* Press `Display Mask`

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Mantid-Matthew** [comment]
The first three seem to work fine. I get an error however when taking the following steps.

- Open Interface
- Usinf LOQ sample data load the userfile
- Then load the batch file

The error looks like 

Traceback (most recent call last):
  File "C:/Users/ANDMT/Documents/RAL/mantid/scripts/Interface\ui\sans_isis\sans_data_processor_gui.py", line 295, in _handle_instrument_change
    self._instrument = SANSInstrument.from_string(instrument_string)
  File "C:/Users/ANDMT/Documents/RAL/mantid/scripts/SANS\sans\common\enums.py", line 64, in from_string
    raise RuntimeError("Could not convert {0} from string. Unknown value.".format(convert_from_string))
RuntimeError: Could not convert  from string. Unknown value.

**Comment by AntonPiccardoSelg** [comment]
@Mantid-Matthew I don't get an error when I follow your steps. Can you show me later on via screen sharing?

**Comment by AntonPiccardoSelg** [comment]
@Mantid-Matthew  I have disabled the check for `Rear_Det_Z` for `ZOOM`. I think this makes sense for the time that they produce data without this meta data. Once they have this information, we need to enable this again.

**Comment by Mantid-Matthew** [comment]
@AntonPiccardoSelg I can't reproduce the first error so was probably an input error somewhere on my part. With the change to rear_det_z the ZOOM mask stuff now seems to be working. 

Happy to merge once checks are done.

**Review by Matthew-Andrew — APPROVED** [review]

**Pull request merged**
