### PR TITLE
Make sanitizers work with Python

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**

This is the final missing piece of the puzzle, I couldn't figure out why
LD_PRELOAD was not working. It turns out ctest calls bin/mantidpython,
which has it's own override for LD_PRELOAD

With this we can run sanitizers for both C++ and Python natively without
messing around with scripts. Hopefully this work will enable us to flush
out some flakey tests.

I wasn't intending to do this work today, but I stumbled upon the fix whilst trying to get the sanitizers working locally, so it made sense to package it before I forgot it.

**To Test**
- Run `ctest -R Kernel -VV` check `ASAN_OPTIONS` and `LSAN_OPTIONS` are both there
- Run `ctest -R python -VV` check that LD_PRELOAD errors aren't emitted (you will likely see leaks)

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
I thought I would try and run this with `LD_DEBUG=libs` so that the dynamic loader would print exactly what it was trying to load.

I ran `env LD_DEBUG=libs env PYTHONPATH=$PWD/bin env LD_PRELOAD=/usr/lib/gcc/x86_64-linux-gnu/8/libasan.so  /usr/bin/python3 /home/mgigg/Code/mantidproject/mantid-nightly/Framework/PythonInterface/test/python/mantid/kernel/ArrayPropertyTest.py` to get `mantidpython` out of the way and create a simple example.

Scrolling through the output I noticed this snippet:

```
      4839:     calling init: /lib/x86_64-linux-gnu/libdl.so.2
      4839:     
      4839:     
      4839:     calling init: /usr/lib/gcc/x86_64-linux-gnu/8/libasan.so
      4839:     
      4839:     /usr/lib/gcc/x86_64-linux-gnu/8/libasan.so: error: symbol lookup error: undefined symbol: __isoc99_printf (fatal)
      4839:     /usr/lib/gcc/x86_64-linux-gnu/8/libasan.so: error: symbol lookup error: undefined symbol: __isoc99_sprintf (fatal)
      4839:     /usr/lib/gcc/x86_64-linux-gnu/8/libasan.so: error: symbol lookup error: undefined symbol: __isoc99_snprintf (fatal)
      4839:     /usr/lib/gcc/x86_64-linux-gnu/8/libasan.so: error: symbol lookup error: undefined symbol: __isoc99_fprintf (fatal)
      4839:     /usr/lib/gcc/x86_64-linux-gnu/8/libasan.so: error: symbol lookup error: undefined symbol: __isoc99_vprintf (fatal)
      4839:     /usr/lib/gcc/x86_64-linux-gnu/8/libasan.so: error: symbol lookup error: undefined symbol: __isoc99_vsprintf (fatal)
      4839:     /usr/lib/gcc/x86_64-linux-gnu/8/libasan.so: error: symbol lookup error: undefined symbol: __isoc99_vsnprintf (fatal)
      4839:     /usr/lib/gcc/x86_64-linux-gnu/8/libasan.so: error: symbol lookup error: undefined symbol: __isoc99_vfprintf (fatal)
      4839:     /usr/lib/gcc/x86_64-linux-gnu/8/libasan.so: error: symbol lookup error: undefined symbol: __cxa_throw (fatal)
      4839:     /usr/lib/gcc/x86_64-linux-gnu/8/libasan.so: error: symbol lookup error: undefined symbol: swift_demangle (fatal)
```

I do also see this when running `KernelTest` but later on in the log. I don't know if this is related at all.

**Comment by DavidFair** [comment]
A thorough search makes it look like an upstream non-issue: https://patchwork.ozlabs.org/patch/622983/

To quote:

>  we don't have failed dlsym calls (still, this hack is useful just in
> case) - the __isoc99_*printf* interceptors make no sense, glibc has never
> exported those.  Thus, if we bump ABI of libasan again for GCC 7, IMHO those
> bogus interceptors should be ifdefed out for glibc or removed completely.

Interestingly they still haven't fixed this as of GCC 9.3 as I get the same messages emitted.

---------
> I don't know if this is related at all.

Sorry are you referring to this? I'm reposting it here so we have a copy
```
469: Test command: /usr/bin/cmake "-E" "chdir" "/home/mgigg/Code/mantidproject/mantid-nightly/builds/sanitizers/bin/Testing" "/home/mgigg/Code/mantidproject/mantid-nightly/builds/sanitizers/bin/mantidpython" "--classic" "/home/mgigg/Code/mantidproject/mantid-nightly/Framework/PythonInterface/test/testhelpers/testrunner.py" "/home/mgigg/Code/mantidproject/mantid-nightly/Framework/PythonInterface/test/python/mantid/kernel/ArrayPropertyTest.py"
469: Environment variables: 
469:  PYTHONPATH=/home/mgigg/Code/mantidproject/mantid-nightly/Framework/PythonInterface/test/python/mantid/kernel::
469: Test timeout computed to be: 300
469: ==32031==Shadow memory range interleaves with an existing memory mapping. ASan cannot proceed correctly. ABORTING.
469: ==32031==ASan shadow was supposed to be located in the [0x00007fff7000-0x10007fff7fff] range.
469: ==32031==This might be related to ELF_ET_DYN_BASE change in Linux 4.12.
469: ==32031==See https://github.com/google/sanitizers/issues/856 for possible workarounds.
469: ==32031==Process memory map follows:
469:    0x000000400000-0x0000007b4000   /usr/bin/python3.6
469:    0x0000009b3000-0x0000009b4000   /usr/bin/python3.6
469:    0x0000009b4000-0x000000a51000   /usr/bin/python3.6
```

**Comment by martyngigg** [comment]
My apologies for the confusion. I forgot to annotate with our Slack discussion. The fix to not call gcc directly in [Sanitizers.cmake](https://github.com/mantidproject/mantid/pull/28441/files#diff-a6c0a07a093963d1ed6f4500a2d37294R21) fixed that. I'm now just getting

```shell
 PYTHONPATH=$PWD/bin LD_PRELOAD=/usr/lib/gcc/x86_64-linux-gnu/8/libasan.so  /usr/bin/python3 /home/mgigg/Code/mantidproject/mantid-nightly/Framework/PythonInterface/test/python/mantid/kernel/ArrayPropertyTest.py
==21362==AddressSanitizer CHECK failed: ../../../../src/libsanitizer/asan/asan_interceptors.cc:313 "((__interception::real___cxa_throw)) != (0)" (0x0, 0x0)
    #0 0x7f0748b91522  (/usr/lib/gcc/x86_64-linux-gnu/8/libasan.so+0xf9522)                          
    #1 0x7f0748bae0e9 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/usr/lib/gcc/x86_64-linux-gnu/8/libasan.so+0x1160e9)
    #2 0x7f0748acf80c in __cxa_throw (/usr/lib/gcc/x86_64-linux-gnu/8/libasan.so+0x3780c)            
    #3 0x7f07363af291 in int Mantid::PythonInterface::callMethod<int>(_object*, char const*) ../../Framework/PythonInterface/core/inc/MantidPythonInterface/core/CallMethod.h:99
    #4 0x7f07363af30d in Mantid::PythonInterface::AlgorithmAdapter<Mantid::API::Algorithm>::version() const ../../Framework/PythonInterface/mantid/api/src/PythonAlgorithm/AlgorithmAdapter.cpp:59
    #5 0x7f073505cca4 in Mantid::API::AlgorithmHistory::AlgorithmHistory(Mantid::API::Algorithm const*, Mantid::Types::Core::DateAndTime const&, double const&, unsigned long) ../../Framework/API/src/AlgorithmHistory.cpp:5
3                                                                                                             
```
when running. I attempted a very simple [test project](https://github.com/martyngigg/sandbox/tree/7fef6ddce6e858cf079f6bbada4fdf9a5b8885f9/cpp/python/sanitizers) to try and emulate what we are doing and this works - I just can't figure out what mantid is doing wrong. I assume somewhere we have something not loading asan into it.

**Comment by DavidFair** [comment]
I'm not having much luck either - I get a hard hang (looks like an infinite loop) running the ArrayPropertyTest:

```
#0  0x00007fe14b32140e in __asan_handle_no_return () from /usr/lib/gcc/x86_64-linux-gnu/9/libasan.so
#1  0x00007fe14b241fdd in __interceptor___cxa_throw () from /usr/lib/gcc/x86_64-linux-gnu/9/libasan.so
#2  0x00007fe14257d34b in Poco::FileImpl::handleLastErrorImpl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib/libPocoFoundation.so.50
#3  0x00007fe14257da29 in Poco::FileImpl::isDirectoryImpl() const () from /usr/lib/libPocoFoundation.so.50
#4  0x00007fe14362a72d in Mantid::Kernel::ConfigServiceImpl::addDirectoryifExists (this=this@entry=0x615000023580, 
    directoryName="/root/.mantid/instrument/", directoryList=std::vector of length 0, capacity 0)
    at ../mantid/Framework/Kernel/src/ConfigService.cpp:1730
#5  0x00007fe14362b472 in Mantid::Kernel::ConfigServiceImpl::cacheInstrumentPaths (this=this@entry=0x615000023580)
    at ../mantid/Framework/Kernel/src/ConfigService.cpp:1701
#6  0x00007fe14363261e in Mantid::Kernel::ConfigServiceImpl::updateConfig (this=this@entry=0x615000023580, 
    filename="/root/.mantid/Mantid.user.properties", append=append@entry=true, update_caches=update_caches@entry=true)
    at ../mantid/Framework/Kernel/src/ConfigService.cpp:773
...
```

**Comment by martyngigg** [comment]
@DavidFair I'm going to put this in draft to indicate it's not ready yet.

**Pull request closed without merging**
