### PR TITLE
Indirect - ABins - Performance increase (of rebinning routines)

### LINKED ISSUE #21172: Indirect - ABins - Improve performance to acceptable standard
Currently the ABins routines are considered to be too slow to be used effectively by users, with a significant performance decrease introduced in recent updates.

### PR DESCRIPTION
**Pull request by brandonhewer**
Recently the performance of ABins declined significantly and has posed an issue to the instrument scientists, due to requiring an infeasible amount of time required for the routines to complete.

Profiling indicated this was, on the most part, the fault of the current rebinning routines. This PR increases the performance of these routines by utilising numpy's histogram function.

Further profiling has shown the increase in performance to be between 10-20x with a data size of around 4100.

**To test:**
1. Open a version of Mantid which does not include the changes made in this PR.
2. Open the supplied script in the Mantid script editor.
3. Change the `data_folder` variable to the path pointing out an Abins phonon file on your local machine
4. Save the script.
5. Execute the script.
6. Copy and paste the print message into a separate document.
7. Open a version of Mantid which does include the changes made in this PR.
8. Open the previously saved script in the Mantid script editor.
9. Execute the script.
10. Copy and paste the print message into a separate document.
11. Compare the two profiling results, ensuring that a significant increase in performance is present.

**Profiling Script:**
[run_benchmarks_1d.zip](https://github.com/mantidproject/mantid/files/1471004/run_benchmarks_1d.zip)

Fixes #21172 . 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@brandonhewer Are we close to getting fixes for the system tests?

**Comment by brandonhewer** [comment]
@martyngigg The ABins tests all passed when built previously. Had some unrelated python SANS test failures.

**Comment by martyngigg** [comment]
@brandonhewer Thanks. These should now be fixed in #21220

**Comment by martyngigg** [comment]
@brandonhewer There is still a failure of one of the Abins system tests unfortunately.

**Review by martyngigg — APPROVED** [review]
This looks great. In my tests the time taken for test script dropped from >400s to ~30s.

The tests have not been affected so we can be confident this has not affected the output. 

Nice work!

**Comment by ianbush** [comment]
Should this be in the release notes?

**Comment by martyngigg** [comment]
Good point. @brandonhewer Could we add a note to the indirect section, please?

**Comment by martyngigg** [comment]
@ianbush I think this is ready to go now.

**Pull request merged**
