### PR TITLE
Test adaptive radius integration

### PR DESCRIPTION
**Pull request by VickieLynch**
Fixes issue [11435](http://trac.mantidproject.org/mantid/ticket/11435)

Check that unit test works using AdaptiveQMultiplier.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
This extends the unit test `IntegratePeaksMD2` to cover new properties that were added in a previous ticket. It all looks good and seems to be working well. We  got unrelated test failures on two platforms (two well known friends: LoadFullprofResolutionTest which lately tends to be dizzy, and the MERLIN system test on rhel7). I'd put my hand in the fire that this is just fine.

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by VickieLynch** [comment]
Jenkins, retest this please

**Pull request merged**
