### PR TITLE
ALC interface bug

### LINKED ISSUE #23359: ALC bugs
Open Mantid and set the default instrument to EMU

Open the ALC interface
inputs should be (you wont have the plot):
image

then press load (this takes a while)

Once the plot appears go to base line modelling
Add a fitting function
Add a region
You cannot fit to the top of the data

Go to curve fitting
Add a gaussian
Do a fit
It will be a mess (the data needs sorting)

### PR DESCRIPTION
**Pull request by AnthonyLim23**
The ALC interface had a bug that caused the fitting range to be shorter than the data range and for the plot to look like a mess.

**To test:**

Open mantid and set the default instrument to EMU
Tuyrn on search the data archieve
Open the ALC interface (in Muon)
For the first data put 81061 and for last put 81142
Select field_danfysik for the log value
tick the subtract box in the periods section and set the second combo box to 2.
In calculation set the max to 16
Click run and wait for the data to load

Click baseline modelling
Add a linear background fit function
Add 2 fitting regions
Set one to before the peak and one to after peak
You should be able to go up to the largest x value (this was bug 1)
Do the fit

Go to the curve fitting
Add a Gaussian (put sigma = 1, centre = 2100 and height  =0.1)
Do a fit
The fitted result should make sense (and not be a jumbled mess).

Fixes #23359. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by Pasarus — CHANGES_REQUESTED** [review]
Code looks good, would it be good to add tests here? so that in future this bug wouldn't be an issue. Also release notes are required.

**Comment by AnthonyLim23** [comment]
the fix could be:

```
            AllOf(Property(&QwtData::size, 3),  QwtDataX(1, 1360.200, 1E-3), 
                        QwtDataX(2, 1364.520, 1E-3),QwtDataX(0, 1398.090, 1E-3),
                 QwtDataY(1, 0.14289, 1E-5),  QwtDataY(2, 0.12837, 1E-5),
                 QwtDataY(0, 0.15004, 1E-5)),
            AllOf(Property(&std::vector<double>::size, 3),
                  VectorValue(0,  1.284E-3, 1E-6),
                  VectorValue(1,1.280E-3, 1E-6),
                  VectorValue(2, 1.285E-3, 1E-6 ))));

'''

**Comment by AnthonyLim23** [comment]
@Pasarus the test that was broken, was broke because the values were not in the correct order (ironically) so we have a test for the sorting

**Comment by Pasarus** [comment]
Looks good! when the build passes I would like to approve

**Review by Pasarus — APPROVED** [review]

**Pull request merged**
