### PR TITLE
Add Current Save Folder to SANS, change default save option to Memory

### LINKED ISSUE #23957: ISIS SANS GUI V2 prominently display save option
The SANS GUI currently automatically saves the output of reductions to the default save directory specified by Mantid. Occasionally users are unaware of where this is saving and struggle to find their files. For this reason they have requested that the current default save directory be displayed on the front page of the GUI. 

Relevant files are:
 * https://github.com/mantidproject/mantid/blob/master/scripts/Interface/ui/sans_isis/sans_data_processor_gui.py
 * https://github.com/mantidproject/mantid/blob/master/scripts/Interface/ui/sans_isis/sans_data_processor_window.ui
* https://github.com/mantidproject/mantid/blob/master/scripts/SANS/sans/gui_logic/presenter/run_tab_presenter.py

This has already been done in the sum runs tab here which it may be worth looking at:
https://github.com/mantidproject/mantid/blob/master/scripts/SANS/sans/gui_logic/presenter/add_runs_presenter.py#L11

### LINKED ISSUE #23968: ISIS SANS Gui V2 Set save option to memory by default
Currently the default save option in the new GUI is to put the outputs into the ADS and save to disk. The default should be changed to just putting the outputs into the ADS.

### PR DESCRIPTION
**Pull request by TTitcombe**
**Description of work.**
Added text in the SANS reduction GUI to display the current save location for easier management.
Additionally, changed the default save option from **both** to **memory**.

To keep uniformity across the application, text on the *Sum Runs* tab was changed from "Output Directory" to "Save Directory"

**Report to:** [nobody]

**To test:**

On Interfaces -> SANS -> ISIS SANS v2 experimental, with the runs tab selected text will show "Save Directory: " plus the current path, if selected. Click *Manage Directories* and select a default save directory. This directory change should be reflected in the text.

Additionally, in *Save Options* in the bottom right corner of the GUI, the default radio button should be *Memory*.

Fixes #23957.
Fixes #23968.
---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by Matthew-Andrew — CHANGES_REQUESTED** [review]
Code changes look good to me and work as intended when tested. Could a unit test be added that the correct method is called on the view when we update the ConfigService singleton?

**Review by Matthew-Andrew — DISMISSED** [review]
All looks good to me now :+1:

**Comment by martyngigg** [comment]
A conflict has occurred after another pull request was merged. @TTitcombe can you merge in master can fix that?

**Review by Matthew-Andrew — APPROVED** [review]
Merge looks clean so still looks good to go to me.

**Pull request merged**
