### PR TITLE
Workbench: Add non-orthogonal axes support to slice viewer

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Adds a button to toggle display of non-orthogonal axes in the workbench slice viewer. This first cut disables both line-plots and the peaks overlay that will be dealt with in future issues.

**To test:**

```python
from mantid.simpleapi import *

SXD23767 = Load(Filename='SXD23767.raw', LoadMonitors='Exclude')
# Set some UB with angles we can play with
SetUB(SXD23767, 1,1,2,90,90,120)
mdws = ConvertToDiffractionMDWorkspace(InputWorkspace='SXD23767',
                                       OutputDimensions='HKL')
```

Refs #27464

*This does not require release notes* because **I think it is worth making release notes for the work once it is more complete so we can make proper screenshots before it goes into 5.1**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by AndreiSavici — CHANGES_REQUESTED** [review]
There is only one issue. When you switch the x/y dimensions (still keeping the same for plotting), only the axis label changes, not the picture or the axis limits. So I want [0,K,0] to be my X, and [H,0,0] to be Y. Try first by using the orthogonal view

**Comment by martyngigg** [comment]
@AndreiSavici Thanks for reviewing this and catching that error. I was missing passing a transpose argument through. It should be okay now.

**Review by AndreiSavici — DISMISSED** [review]

**Comment by rosswhitfield** [comment]
This doesn't work for MDHisto with > 3 non-integrated dimensions.

Continuing from your example, if you do
```python
binned = BinMD(mdws, AlignedDim0='[H,0,0],0,5,20', AlignedDim1='[0,K,0],-2,2,100', AlignedDim2='[0,0,L],-2,4,1')
```
it will work, but if you do 
```
binned2 = BinMD(mdws, AlignedDim0='[H,0,0],0,5,20', AlignedDim1='[0,K,0],-2,2,100', AlignedDim2='[0,0,L],-2,4,160')
```

you get 
```
Traceback (most recent call last):
  File "/home/rwp/src/mantid/qt/python/mantidqt/widgets/sliceviewer/view.py", line 264, in non_orthogonal_axes_toggle
    self.presenter.nonorthogonal_axes(state)
  File "/home/rwp/src/mantid/qt/python/mantidqt/widgets/sliceviewer/presenter.py", line 149, in nonorthogonal_axes
    self.new_plot()
  File "/home/rwp/src/mantid/qt/python/mantidqt/widgets/sliceviewer/presenter.py", line 59, in new_plot_MDH
    self.view.data_view.plot_MDH(self.model.get_ws(), slicepoint=self.get_slicepoint())
  File "/home/rwp/src/mantid/qt/python/mantidqt/widgets/sliceviewer/view.py", line 199, in plot_MDH_nonorthogonal
    self.image = pcolormesh_nonorthogonal(self.ax,
  File "/home/rwp/src/mantid/Framework/PythonInterface/mantid/plots/axesfunctions.py", line 54, in _pcolormesh_nonortho
    x, y, z = get_md_data2d_bin_bounds(workspace, transpose=transpose, normalization=normalization)
  File "/home/rwp/src/mantid/Framework/PythonInterface/mantid/plots/datafunctions.py", line 376, in get_md_data2d_bin_bounds
    assert len(coordinate) == 2, 'The workspace is not 2D'
AssertionError: The workspace is not 2D
```

**Comment by martyngigg** [comment]
Thanks for checking this, Ross. As well as missing the transpose argument I also missed passing the indices through when retrieving the data. This should be fixed now.

**Review by rosswhitfield — APPROVED** [review]

**Pull request merged**
