### PR TITLE
File-based Sample Environment XML Definition

### PR DESCRIPTION
**Pull request by martyngigg**
Adds support for parsing the definition of a `SampleEnvironment` from an XML-based definition file. Users interact with the high-level `SetSample` algorithm but heavy lifting is split over many independent classes with their own tests.

**To test:**

The script below shows the two main intended usage modes. The second call requires the definition to be discoverable. The [CRYO-01.txt](https://github.com/mantidproject/mantid/files/266117/CRYO-01.txt) file contains such a definition (it needs to be renamed `.xml` as GitHub don't allow .xml uploads). Place this file in the `instrument/sampleenvironments/ISIS/MARI/` directory.

``` python
import mantid
import mantid.simpleapi as sapi

# Either load a file with a real facility/workspace
#ws = sapi.Load(Filename='MAR11015.raw')      
# or fake it                                                                                                                                                         
mantid.config["default.facility"] = "ISIS"
mantid.config["default.instrument"] = "MARI"
ws = sapi.CreateSampleWorkspace()

ws = sapi.Load(Filename='MAR11015.raw')

# User-defined definition of just sample geometry (centimetres)
sapi.SetSample(ws, Geometry={'Shape':'FlatPlate', 'Width': 2.0, 'Height': 1.0,
                             'Thick': 0.1, 'Center': [0.,0.,0.]},
              Material={'ChemicalFormula': 'V'})

# Predefined can/sample geometry
sapi.SetSample(ws, Environment={'Name': 'CRYO-01', 'Can': '8mm'},
              Geometry={'Height': 4.0},
              Material={'ChemicalFormula': 'V'})
```

Refs #16044.

The release notes will be updated as part of the roadmap issue #15543

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
I'm now building this locally for a bit of functional testing, and I'm having a look at the changes.
I'm leaving it unassigned for now in case more eyes/opinions are available for this PR.

**Comment by martyngigg** [comment]
Thank you, @FedeMPouzols. As you say as many eyes from @mantidproject/gatekeepers, @NickDraper would be good.

**Comment by peterfpeterson** [comment]
I'm looking it over as well.

**Comment by peterfpeterson** [comment]
This seems like a bad algorithm name. In common usage somebody would (with beam dimensions from #16233, stitching together various examples):
```python
SetSampleMaterial(ws, ChemicalFormula="(Li7)2-C-H4-N-Cl6")
SetSample(ws, Environment={'Name': 'CRYO-01', 'Can': '8mm'},
              Geometry={'Height': 4.0},
              Material={'ChemicalFormula': 'V'})
SetBeam(ws, Geometry={'Shape': 'Slit', 'Width': beam_width, 'Height': beam_height'})
ws_abs = CalculateSampleCorrection(w1, Method="MonteCarlo",
    MethodArgs={"NLambda": 500, "NEvents": 300})
```
Ideally, the beam dimensions would be picked up from logs. I think `SetSampleEnvironment` is a better name.

**Comment by martyngigg** [comment]
@peterfpeterson That was a question I put in the design document and no one commented on it.

The original intent of `SetSample` was to supersede `SetSampleMaterial` and have all of the sample attributes setable in one shot. The `Geometry` & `Material` flags of `SetSample` actually apply to the sample, the environment is completed defined in the file definition so the sequence would be:

```python
SetSample(ws, Environment={'Name': 'CRYO-01', 'Can': '8mm'},
              Geometry={'Height': 4.0},
              Material={'ChemicalFormula': '(Li7)2-C-H4-N-Cl6'})
SetBeam(ws, Geometry={'Shape': 'Slit', 'Width': beam_width, 'Height': beam_height'})
ws_abs = CalculateSampleCorrection(w1, Method="MonteCarlo",
    MethodArgs={"NLambda": 500, "NEvents": 300})
```

**Comment by martyngigg** [comment]
I agree that it would be nice to pick the beam size form the logs. That seems like a subtask of its own as we're going to have to be able to define the names of logs etc.

**Comment by FedeMPouzols** [comment]
For the future, would it be useful to be able to give an arbitrary path to the environment XML file, outside of `facilities/instrument/...`?

**Comment by martyngigg** [comment]
@FedeMPouzols Yes that is probably worth doing. That should be pretty easy to support as we could just detect check of the 'Name' field points to an existing file and use that.

**Comment by NickDraper** [comment]
Looks good, failure cases for missing file are well reported.

For the future ClearAllMemory should clear the caches.


:shipit:

**Comment by martyngigg** [comment]
@NickDraper Have you read @peterfpeterson comments?

**Comment by NickDraper** [comment]
I had and I have to say I agreed with your response, 2 of the 3 parts of SetSample are to do with the samepl, not the environment.

**Comment by peterfpeterson** [comment]
I guess I didn't read the design as close as I should have. I've looked over the code and am trying functional testing now.

**Comment by FedeMPouzols** [comment]
I can only say :shipit:.

**Comment by FedeMPouzols** [comment]
@martyngigg: after merging #16233 this has a merge conflict.

**Comment by martyngigg** [comment]
Thanks, @FedeMPouzols. I've sorted that now.

**Comment by martyngigg** [comment]
Is this ready to go? I've got more squirrels than usual.

**Comment by peterfpeterson** [comment]
I'm trying it out. Please don't merge until a third squirrel makes it.

**Comment by peterfpeterson** [comment]
It *does* work, but it needs several improvements as future work in the 3.8 release cycle.:shipit: so we can start folding it into scripts for testing and to modify/improve the design. Future work (annotated here, ticket numbers will be added):

1.  ad-hoc definition of sample in can (without separate xml file)
1. changing the xml a little (can/cans -> container/containers) for clarity
3. docs are missing - including adding description of units in xml
4. "material widget" needs to show the extra info
5. Algorithm dialog does not work very well/at all
5. Extra information calculated by `SetSampleMaterial` needs to be added to `Material` as member methods.
6. Deprecate `SetSampleMaterial`

**Pull request merged**
