### PR TITLE
 Apply background correction with dark runs to scatter data for ISIS SANS

### LINKED ISSUE #10193: Optionally Apply Background Correction
sans_feature
This issue was originally [TRAC 9350](http://trac.mantidproject.org/mantid/ticket/9350)

The ISIS SANS interface needs to be expanded to allow background corrections using so-called "dark runs".

My understanding is that there are two kinds of dark run; "natural background" (i.e. source off) and "dark current" (i.e. source on, but shutter closed).

It is not clear whether or not this would be best implemented as a User File command, as checkboxes in the GUI, or both.

Implementing this seems trivial enough, though we'd need to be careful about scaling a 10-hour background run before applying it to a 1-hour data run, run example.  It may be useful to see how this has been done at the SNS.

We are to account for periods where they have been used.

 - - - - 
Keywords: Bilby

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Fixes #10193 

The code is being tested by Richard currently and should make it into 3.6
# For Testing

**Test that loading user filese shows in GUI**

The different user files can be found here: \olympic\Babylon5\Scratch\Anton\Testing\10193_background_correction\User_File_Read_In_Test

The instrument is LOQ

Load the following user files and confirm that there is information in the BackgrounCorrection section on the Settings tab:
- user_file_det_time_mean.txt:   Detecotr is selected, time is selected, mean is selected
- user_file_det_time_tof.txt: Detecotr is selected, time is selected, tof is selected
- user_file_det_uamp_tof.txt: Detecotr is selected, uamp is selected, tof is selected
- user_file_mon_all_time_mean.txt: All monitors are selected, time is selected, mean is selected
- user_file_mon_all_time_tof.txt: All monitors are selected, time is selected, tof is selected
- user_file_mon_all_uamp_tof.txt: All monitors are selected, uamp is selected, tof is selected
- user_file_mon_mixed_time_mean.txt: Both detectors and monitors are selected, time is selected, mean is selected
- user_file_mon_partial_time_mean.txt: Some monitors are selected, time is slected, mean is slected
- user_file_mon_partial_time_tof.txt: Some monitors are selected, time is slected, tof is slected
- user_file_mon_partial_uamp_tof.txt: Some monitors are selected, uamp is slected, tof is slected
- user_file_no_background.txt: no background is selected
- user_file_bad_wrong_input_string.txt: invalid input is selected. nothing should be displayed

**Test that dark run is operated without any issuese**

The relevenat user file and depenedencies can be found here: \olympic\Babylon5\Scratch\Anton\Testing\10193_background_correction\MergeTesting

The test data is:
Sample Scattering:  SANS2D00033120-add.nx
Can Scattering:  SANS2D00033118-add.nxs
Sample Transmission: SANS2D00033125-add.nxs
Can Transmission: SANS2D00033123-add.nxs
Sample Direct: SANS2D00033123-add.nxs
Can Direct: SANS2D00033123-add.nxs
1. Start the ISIS SANS GUI
   2.1 The instrument is SANS2DTUBES
   2.2 Load the user file USER_SANS2D_153K_2p4_4m_M4_Xpress_20_14mm_changer.txt
2. Load the workspaces
3. Press 1D Reduce
   - Confirm that no errors occur

### CODE REVIEW

**Comment by martyngigg** [comment]
Is this ready to go or should it move back to v3.7?

**Comment by picatess** [comment]
@martyngigg  This is still being tested by Richard. I will pop up to check if he is happy with it later on.In principle it would be good to have it in 3.6. It is orthogonal functionality to the current SANS code.

**Comment by picatess** [comment]
@matthew-d-jones

**Comment by matthew-d-jones** [comment]
Confirmed all user files display the correct settings in the interface and remainder of the test worked as described. Some code can be refactored later using a function that is implemented in another branch, a maintenance issue will be created for this.
I'm happy for this to be merged with the branch for the 3.6 release.

**Comment by martyngigg** [comment]
@matthew-d-jones That's good. Please click merge as usual but then don't delete the branch.

@picatess Can you then open a new pull request for this branch but target it at `release-v3.6.0`. This is will work in this case as the branch was created before the release branch.

**Pull request merged**
