### PR TITLE
Ensure output EventLists have correct sort order after filtering

### LINKED ISSUE #18477: Script giving different results in Mantid v3.8 and a recent branch
The following script:

```
Load(Filename=r'\\isis\inst$\ndxinter\instrument\data\cycle_16_2\INTER00038415.nxs', OutputWorkspace='38415', LoadMonitors=True)
FilterByTime(InputWorkspace='38415', OutputWorkspace='38415_filter', StopTime=200)
Rebin(InputWorkspace='38415_filter', OutputWorkspace='38415_0_200', Params='0,100,100000', PreserveEvents=False)
```

is giving me different results on Mantid 3.8 and a recent branch. I need to investigate why before the release.

### PR DESCRIPTION
**Pull request by martyngigg**
Description of work.

Fixes an issue with `EventList` where the sort order was inconsistently defined after `FilterByTime`.

**To test:**

The following scripts creates a filtered event workspace:
```
ws = CreateSampleWorkspace("Event",BankPixelWidth=1)
AddTimeSeriesLog(ws, Name="proton_charge", Time="2010-01-01T00:00:00", Value=100) 
AddTimeSeriesLog(ws, Name="proton_charge", Time="2010-01-01T00:10:00", Value=100)
AddTimeSeriesLog(ws, Name="proton_charge", Time="2010-01-01T00:20:00", Value=100)
AddTimeSeriesLog(ws, Name="proton_charge", Time="2010-01-01T00:30:00", Value=100)
AddTimeSeriesLog(ws, Name="proton_charge", Time="2010-01-01T00:40:00", Value=15)
AddTimeSeriesLog(ws, Name="proton_charge", Time="2010-01-01T00:50:00", Value=100)

#Extract the first 30 minutes  * 60 = 1800 seconds (roughly half of the data)
wsFiltered = FilterByTime(ws,StartTime=0,StopTime=1800)
```

Run the script and plot the first spectrum before and after apply these changes. After the changes the output should match that from `v3.8.0`.

@raquelalvarezbanos Could you double check your example with the `INTER` file?

Fixes #18477 

*I have chosen not to include this in the release notes. In `v3.8` `FilterByTime` behaves as expected even though the bug was present due to the way the workspace was construct. Refactoring around workspace creation (#17123) meant that the bug surfaced.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
Looks good. I've run the script in the description and after the fix results match those from release `3.8`. I've also tried my example with the `INTER` dataset and it works too.

**Review by peterfpeterson — APPROVED** [review]
Explicitly setting the sorting in the output appears to be correct.

**Comment by martyngigg** [comment]
@wdzhou Do you have anything to add here?

If not can we get this merged? It will be important for beta testing as it fixes a regression we introduced this development cycle.

**Comment by martyngigg** [comment]
Can we get this merged for the beta version?

**Comment by AndreiSavici** [comment]
Looks OK to me.

**Comment by wdzhou** [comment]
I think the change is good!

**Pull request merged**
