### PR TITLE
Added Mantid::NeXus::NexusHDF5Descriptor class caching metadata

### PR DESCRIPTION
**Pull request by williamfgc**
**Description of work.**
Introduce new class to describe entries in a HDF5 file
Populates Metadata entries map in constructor (RAII) using HDF5 API directly. 
Goal is to reference this map so it can be reused within algorithms
HDF5 is linked privately
Internal reference to all entries accessible in public function

**Report to:** 
@peterfpeterson @quantumsteve 

**To test:**
Nothing to test, yet.

Subtask of #28405 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by peterfpeterson** [comment]
[windows doesn't like the function you're using](https://builds.mantidproject.org/job/pull_requests-windows/35413/msbuild/new/source.10713474-5194-4764-9b20-111fee9ec493/#82)

**Review by peterfpeterson — CHANGES_REQUESTED** [review]
The code itself looks good. There are likely changes in follow-on work as this gets used by `LoadEventNexus` and friends that can wait until then. The only criticism is that there isn't a unit test verifying that it can build a tree.

**Review by peterfpeterson — APPROVED** [review]

**Review by martyngigg — COMMENTED** [review]
Just a quick question. Is there a reason the HDF5 C++ api wasn't used?

**Comment by williamfgc** [comment]
@martyngigg thanks for asking. This functionality was already in Nexus (licenses are compatible) which uses the native HDF5 C API. So I guess two reasons, i) didn't want to reinvent the wheel, ii) cut the middleman since the C++ APIs build on top of the HDF5 C API, and as of 2016 [there has been issues reported with string mapping](https://stackoverflow.com/questions/32072272/using-std-string-in-hdf5-creates-unreadable-output).

**Pull request merged**
