### PR TITLE
Add ability to filter message window statements

### LINKED ISSUE #24480: Add the ability to separate framework logging from script print statements in Messages window
The workbench currently pumps all printable output to the Messages pane. It was requested by many scientists that there be a way to "filter" the Messages window so that it can display just the output from script printing or both script printing and framework logging combined. It is not yet clear how best to approach this and may require a rewrite of the Messages display widget.

An additional request after the user meeting was to be able to filter output from separate python script tabs.

### PR DESCRIPTION
**Pull request by ghost**
**Description of work.**
This PR adds options to the Message Display's context menu to filter which messages you'd like to be shown. You can show/hide "Mantid Framework" messages or filter to only show output from scripts or specific scripts.
image

It works by keeping a history of outputted messages (assigning the path of the associated script to the Message object), then when the user requests to filter, the text display is repopulated with only the requested messages.

**To test:**

1)
    - Open several scripts in Workbench. Call them "Script 1", "Script 2", etc.
    - In each script have them print something to the display (e.g. `print("This is script 1")`, `print("This is script 2")` etc.)
    - Right-click in the message display window and untick the "All Script Output" button. All the printed messages should disappear.
    - One-by-one, tick the scripts to show their print messages again. They should be restored in the order they were printed.
    - Untick any of the scripts, then run that script. No new print messages should be displayed when running. Now re-tick the script in the context menu, the new messages should now be displayed.
    - With one of these scripts unticked in the context menu, raise an error within that script. The error should be displayed.
    - Right-click the message display and click `Clear`. All messages should be removed and the "Filter by" menu in the context menu should not contain any scripts.

2) 
    - Create 2 new scripts, but do not save them! They should be named "New" and "New (1)" in the tab bar.
    - Print something from these scripts and make sure they are added to the message display's context menu.
    - Now save one of the scripts and make sure the name has been updated in the message display's context menu, and that ticking/unticking that script toggles the message that was printed whilst the script was not saved.

3)
    - In the message display's context menu toggle "Mantid Framework Output" off and set the logging level to Debug.
    - Now run: `CreateWorkspace(DataX=[0, 1, 2], DataY=[0, 1, 2], NSpec=1, OutputWorkspace="ws")`
    - Nothing should be displayed in the window.
    - Now toggle "Mantid Framework Output" on. The `CreateWorkspace` log messages should be displayed.
    - Now toggle "Mantid Framework Output" off again and close Workbench.
    - When you re-open Workbench and open the message display's context menu, the "Mantid Framework Output" option should remain unticked.
    

Fixes #24480 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by NickDraper — CHANGES_REQUESTED** [review]
From Functional testing:

1. It would be better to have the menu items changed a bit.
   1.  Clear should be changed to Clear All as it will clear more than you can see.
   1. Instead of the individual script choices we should just offer the following:
      - All scripts
      - Current script (and have it change with the selected tab)
      - No scripts
1. If you resave an already saved file under a different file name the filtering does not pick up that name change.
   1. create a new tab, save it as test2, and then save as as test22, the filtering still thnks it is test2
1. We might also want to think of changing the user facing language from Filter by, to Show.

**Comment by NickDraper** [comment]
I do like the fact that error logs still pop through even if they are "filtered out"

**Comment by hsautessella** [comment]
@NickDraper This is ready for another look

**Comment by NickDraper** [comment]
Almost sorted, but I've found another test case that fails.

When showing the active tab, but run script imultaneously on multiple tab, all of the messages appear into a single tab.

image

**Review by NickDraper — APPROVED** [review]
With the known issue documented I'm happy to approve this.

**Pull request merged**
