### PR TITLE
Update copyright to include CSNS

### LINKED ISSUE #28399: Update copyright to include the CSNS
Update all of the Mantid code copyright statements to include the CSNS
```
Copyright &copy; 2018 ISIS Rutherford Appleton Laboratory UKRI,  NScD Oak Ridge National Laboratory, European Spallation Source , Institut Laue - Langevin  &  CSNS, Institute of High Energy Physics，Chinese Academy of Sciences.
 ```

Copyright statements that are not ours should be left alone.

### PR DESCRIPTION
**Pull request by NickDraper**
**Description of work.**

Updated python file for python 3 and new CSNS copyright statement

**To test:**

Code review a sample of file changes, don't try to do them all you will go blind!

Fixes #28399 

*This does not require release notes* because **it is an internal change not visible to users**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — CHANGES_REQUESTED** [review]
`SaveNXSPE` is failing to compile. It looks like it had the old full licence in it so maybe the script got confused.

The `Algorithm.h` header has been removed from the original.

**Comment by NickDraper** [comment]
Thanks for the spot, a correction has just gone in

**Comment by martyngigg** [comment]
Do we think the windows failure is real? I'm concerned about the warnings about the simpleapi.

**Comment by martyngigg** [comment]
Never mind. My page hadn't refreshed I don't think, so I must have seen on old version.

**Review by martyngigg — APPROVED** [review]

**Comment by martyngigg** [comment]
I'm going to merge this to avoid merge conflicts accumulating.

**Pull request merged**
