### PR TITLE
Bump cppcheck warning count for cppcheck 2.5

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**
This bumps the warning count after upgrading to cppcheck 2.5 to the
current value, 1203

**To test:**
- Check cppcheck passes

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DavidFair** [comment]
Marking as high priority as this will hold up builds now

**Review by thomashampson — APPROVED** [review]
Can confirm that the new value for ALLOWED_ERRORS_COUNT is consistent with the new value since bumping cppcheck to 2.5.

**Comment by martyngigg** [comment]
cppcheck has gone through so I'll merge as no other code has actually changed.

**Comment by DannyHindson** [comment]
I've just had a failure on cppcheck on a PR with target branch release-next (both jobs from same PR):

https://builds.mantidproject.org/job/pull_requests-cppcheck/48501/
https://builds.mantidproject.org/job/pull_requests-cppcheck/48502/

It seems like the current count on release-next is 1204. It's higher than on master due to a refactor PR on the Indirect UI that has been merged in master only

I think the cppcheck job on this PR passed because no C++ files were altered so the actual check was skipped.

Can we change the release-next warning count to 1204?

**Pull request merged**
