### PR TITLE
35646 fixing a memory leak when loading nexus files

### LINKED ISSUE #35646: Load memory leak
When loading data we have a memory leak. The below script should always start and end at about the same memory usage (widget above the messages box). However, on my IDAaS it goes up from 0.3 to 0.5. 

```
start = 18587
num = 66
for j in range(num):
    run = start+j
    Load("HIFI"+str(run), OutputWorkspace="HIFI"+str(run))
   
AnalysisDataService.clear()
CleanFileCache()
```

### PR DESCRIPTION
**Pull request by warunawickramasingha**
### Description of work

There had been a memory leak due to not freeing up the dynamically allocated memory buffers when loading nexus files from the disk. And also there was a QFileDialog object being created without being deleted due to not having a parent QWidget.

Fixes #35646. 

### To test:

1. Load and save some nxs files
```
start = 50087
nruns = 6
for irun in range(nruns):
    run = start+irun
    ws_name = "WISH000"+str(run)
    Load(ws_name, OutputWorkspace=ws_name)
    SaveNexus(ws_name, <path to save ws> + ws_name + ".nxs")
AnalysisDataService.clear()
CleanFileCache()
```

2. Restart the workbench and update Search Data Archive to `off` in manage user directories so that files are loaded from the disk.
3. Run the below and see the memory usage before and after.
```
for ntries in range(10):
    start = 50087
    nruns = 6
    for irun in range(nruns):
        run = start+irun
        ws_name = "WISH000"+str(run)
        Load(ws_name, OutputWorkspace=ws_name)
    AnalysisDataService.clear()
    CleanFileCache()
```

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by GuiMacielPereira — COMMENTED** [review]
I altered the Python script so I don't run out of memory on my machine:
```
for ntries in range(5):
    start = 50087
    nruns = 6
    for irun in range(nruns):
        run = start+irun
        ws_name = "WISH000"+str(run)
        Load(<path-to-ws> + ws_name + ".nxs", OutputWorkspace=ws_name)
        AnalysisDataService.clear()
        CleanFileCache()
```

So in total I loaded and deleted 5 x 6 wish workspaces.
The results I got before the fix and after the fix are very similar:

**Before the fix**
220MB in memory (before running it) -> 760MB (after running it)

**After the fix**
270MB in memory (before running it) -> 770MB (after running it)

Still, it's nowhere near the amount @RichardWaiteSTFC mentioned in https://github.com/mantidproject/mantid/issues/35646#issuecomment-1578125779, so maybe this issue is already fixed?

Either way, your changes are good to be implemented, so I am wondering if I should approve them and create a separate PR to investigate this further?

**Comment by GuiMacielPereira** [comment]
The reason I say this is because ideally we should try running the original issue https://github.com/ISISNeutronMuon/mantid-isis-support/issues/117 and report back to the user confirming that it is fixed.

**Comment by warunawickramasingha** [comment]
In that case, I think it would be better to remove the Fixes #35646. tag from this PR and allow the original issue to be investigated further.

**Comment by GuiMacielPereira** [comment]
I changed my mind: the issue should be closed when this PR is merged, as there is no remaining memory leak coming from Load() (apart from external libraries leaks). Even before this fix, the large amounts of memory leaks mentioned could not be replicated by me or @jclarkeSTFC, so I would say closing the issue is a safe approach.

**Review by GuiMacielPereira — APPROVED** [review]

**Pull request merged**
