### PR TITLE
Update reflectometry parameter files

### LINKED ISSUE #18639: Update reflectometry IDFs
Scientists are going to send updated versions of the IDFs.

### PR DESCRIPTION
**Pull request by raquelalvarezbanos**
Updated versions of the parameter files sent by Max.

**To test:**

Code changes.

Fixes #18639.

Release notes will be updated as part of https://github.com/mantidproject/mantid/issues/18580

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
changes are to parameter files and doc tests / system test reference files

**Comment by NickDraper** [comment]
sys test and doc tests pass

load checked to ensure matching parameter files loaded and have new values shown in instrument view

**Comment by NickDraper** [comment]
:shipit:

**Comment by raquelalvarezbanos** [comment]
@NickDraper I mentioned scientists that these changes broke some of the tests, I explained Max Skoda why results were different and we agreed that this is expected and he confirmed they are happy (at least so far) with the new parameters.

**Pull request merged**
