### PR TITLE
ConvFit support for BASIS files

### LINKED ISSUE #20192: ConvFit support for BASIS files
These [Resolution and Data files](https://www.dropbox.com/s/49zpiqwssct6inx/res_data.zip?dl=0) result in erroneous sequential fitting if the following model is used:
`Convolution(Resolution, Delta + Lorentzian(FWHM)) + LinearBackground`

Contents of the zip file:
BASIS_59293_divided_sqw.nxs = data
BASIS_59304_divided_sqw.nxs = resolution

Results for the Lorentzian's FWHM:
```
# Q      FWHM(meV)
0.25   0.0002871726928108466
0.35   0.0006650270132659233
0.45   0.00072466683252982622
0.55   0.00069262352686265231
0.65   0.0006407072483685767
0.75   0.00055436295695961558
0.85   0.00053331999235226306
0.95   0.00062267394656063176
1.05   0.00057665353748676831
1.15   4.5314187154913623e-07
1.25   1.5380579391199557e-06
1.35   2.7204326475232993e-07
1.45   2.569172830259147e-07
1.55   2.0550013517500603e-07
1.65   2.4956577844427097e-07
1.75   3.3130201440524048e-07
1.85   1.0652818707828362e-06
1.95   3.5867983531256399e-06
```
The correct values, resulting both from fitting with a python script in Mantid and from fitting in DAVE:
```
#  Q   FWHM(meV)
0.25   0.00876649987410376																	
0.35   0.0123421351570015
0.45   0.0206384272674493
0.55   0.0289144693239161
0.65   0.0425792805053647
0.75   0.0477424785984907
0.85   0.0569612981314161
0.95   0.069796003715339
1.05   0.0840384230390653
1.15   0.163630955696123
1.25   0.0737139469980427
1.35   0.135503163750217
1.45   0.0935978531044716
1.55   0.114692511163929
1.65   0.10318761003682
1.75   0.130757406620174
1.85   0.160972434436317
1.95   0.0311461513761639
```

### PR DESCRIPTION
**Pull request by jmborr**
Things done:
- Correct treatment of the resolution function: convolve sample and resolution spectra with same momentum transfer.
- [ConvolutionFitSequential](http://docs.mantidproject.org/nightly/algorithms/ConvolutionFitSequential-v1.html) now passes the workspace index by default to [PlotPeakByLogValue](http://docs.mantidproject.org/nightly/algorithms/PlotPeakByLogValue-v1.html)
- Doctest compatible with python 3.x

**To test:**
The test compares manually running the interface against running a python script. Download and unzip testing files [example.zip](https://www.dropbox.com/s/yfg75laythx0yat/example.zip?dl=0) in directory `/tmp`. Then run the following script:
```
resolution_file = '/tmp/resolution.nxs'  # resolution file
data_file = '/tmp/data.nxs' # data file
resolution = Load(resolution_file)
data = Load(data_file)
n_h = data.getNumberHistograms()  # number of spectra
q = resolution.getAxis(1).extractValues() # list of Q values
# Model function
function = '''(composite=Convolution,FixResolution=true,NumDeriv=true;
name=Resolution,Workspace=resolution,WorkspaceIndex=0;
(name=DeltaFunction,Height=0.5,Centre=0;
name=Lorentzian,Amplitude=0.5,PeakCentre=0,FWHM=0.0035));
name=LinearBackground,A0=0,A1=0'''
# Carry out a sequential fit using Algorithm PlotPeakByLogValue
workspaces = ['data,i%d' % i for i in range(n_h)]
workspaces = ';'.join(workspaces)
PlotPeakByLogValue(Input=workspaces,
    OutputWorkspace='fit',
    Function=function,
    StartX=-0.0998,
    EndX=0.0998,
    FitType='Sequential',
    PassWSIndexToFunction=True,
    MaxIterations=500,
    CreateOutput=True,
    EvaluationType='CentrePoint')
# Create the workspace containing FWHM against Q
fwhm_values = list()
fwhm_errors = list()
for i in range(n_h):
    ws = mtd['data_{}_Parameters'.format(i)]
    row = ws.row(4)  # this is the row containing the FWHM value
    fwhm_values.append(row['Value'])
    fwhm_errors.append(row['Error'])
CreateWorkspace(q, fwhm_values, fwhm_errors, UnitX='MomentumTransfer', OutputWorkspace='fwhm', WorkspaceTitle='FWHM versus Q')
```
Plot output workspace `fwhm`.
Now run the ConvFit interface with the example files, and then plot FHWM. You should obtain the same plot as the one obtained from workspace `fwhm`.

Fixes #20192

Updated [release notes](https://github.com/mantidproject/mantid/blob/b522d28abba070868eb5bbea3fbc8a269c5c34ea/docs/source/release/v3.11.0/indirect_inelastic.rst)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by brandonhewer** [comment]
The shape of the FWHM plot is the same in both cases, however, the scale is different by a factor of 10 - 

In the image below, the plot on the left was generated using the ConvFit interface. The plot on the right was generated using the provided script.
convfit_test

**Comment by jmborr** [comment]
@brandonhewer Thanks for reviewing, and good that you caught the disparity! I'll look into it...

**Comment by jmborr** [comment]
OK, I created workspace `fwhm` as a non-distribution. As a result, the Y-vales are divided by the bin width of the X-axis (0.1) when shown in a plot. That's why this plot shows Y-values 10 times bigger than the other plot.
To fix this, add the following optional argument to algorithm `CreateWorkspace` in the last line of the testing script:
```Distribution=True```
The resulting `fwhm` workspace will now show the same Y-values as the plot from the interface.

**Comment by jmborr** [comment]
I added a new property to `ConvolutionFitSequential` so that user can optionally request updating the workspace index when carrying out the sequential fit.

**Comment by jmborr** [comment]
@brandonhewer If everything is fine by you, can you please finalize your review?

**Comment by jmborr** [comment]
@brandonhewer Can you please finish this review ASAP? I have the user that prompted the issue asking me when are these changes going to be incorporated into Mantid.

**Comment by brandonhewer** [comment]
I receive a brief abort error when using the supplied files as input to the ConvFit interface - this is immediately followed by Mantid closing.

When using files known to work correctly in the ConvFit interface I receive the following error message:
convfit_error

**Comment by brandonhewer** [comment]
Should the newly added property ("PassWsIndexToFunction") be added to the property table in the ConvFit interface?

**Comment by jmborr** [comment]
@brandonhewer Well I'll be dammed :frowning: I'm going to fix this thing.

**Comment by jmborr** [comment]
@brandonhewer I have now fixed the error and the interface works with the `irs*.nxs` files, in addition to passing the test. Please check.

**Comment by brandonhewer** [comment]
Merge conflicts have arose on this Pull Request due to a restructure of the Mantid source. I've just had to deal with similar issues on a couple of my Pull Requests :).

**Comment by jmborr** [comment]
@brandonhewer Finally! I hope now you will find no more troubles preventing the OK to the review

**Comment by brandonhewer** [comment]
Should PassWsIndexToFunction be in the properties table in the ConvFit interface? There is currently no way to change this property within the interface.

**Comment by jmborr** [comment]
@brandonhewer No, workspace index should not be available in the interface because ConvFit must pass the workspace index to PlotPeakByLogValue in all cases.

**Review by brandonhewer — APPROVED** [review]
Works as expected within the ConvFit interface and with the supplied script

**Comment by jmborr** [comment]
@martyngigg Is there a problem with the pull request? If not, can you please merge it to master?

**Comment by martyngigg** [comment]
@jmborr My apologies. I assigned it to do just that and got distracted!

**Comment by jmborr** [comment]
@martyngigg :man_dancing:  thanks! :man_dancing:

**Pull request merged**
