### PR TITLE
Feature/10263 poldi refine close peaks combined

### PR DESCRIPTION
**Pull request by MichaelWedel**
Currently, PoldiFitPeaks1D refines all peaks independently. Sometimes when two peaks are very close to each other, this does not work properly.

Instead, the algorithm should fit peaks that are only a few FWHMs apart together as a composite function. In that case, the x-ranges have to be combined so that they contain all peaks that are considered "close".

### CODE REVIEW

**Comment by MichaelWedel** [comment]
retest this please

**Comment by MichaelWedel** [comment]
**Testing information**
Make sure all the tests pass, especially the system test "POLDIFitPeaks1DTest", where the new behavior is tested. In systemtests there's a new data file that contains a calculated correlation spectrum - if you like you can plot the output of the following script to see that two peaks are refined together. Increasing the "AllowedOverlap"-parameter may lead to peaks being refined one by one, which should give worse results.

```
Load(Filename='poldi_2_phases_theoretical_reference.nxs', OutputWorkspace='correlation_spectrum')
PoldiPeakSearch(InputWorkspace='correlation_spectrum', MinimumPeakSeparation=8, MaximumPeakNumber=30, MinimumPeakHeight=180, OutputWorkspace='peaks')
DeleteTableRows(TableWorkspace='peaks', Rows='9,10')
PoldiFitPeaks1D(InputWorkspace='correlation_spectrum', FwhmMultiples=4, AllowedOverlap=0.1, PoldiPeakTable='peaks')
```

**Comment by FedeMPouzols** [comment]
Checking this and it's sibling systemtests/ pull request: https://github.com/mantidproject/systemtests/pull/10

**Comment by MichaelWedel** [comment]
I realized there are some extra files from resolving a merge conflict, I will remove them. Also, the documentation was not updated properly, which I also fixed (good thing you just raised that point in the dev workshop :-) ). Could you update your local branch once the build has passed please?

**Comment by MichaelWedel** [comment]
retest this please

**Comment by MichaelWedel** [comment]
retest this please

**Comment by MichaelWedel** [comment]
retest this please

**Comment by FedeMPouzols** [comment]
Aha, everything seems fine and the system tests had passed with the branch before today's updates. I'm passing them again just in case.

**Comment by FedeMPouzols** [comment]
All is good, all tests pass, the example given above seems to work as expected, and it comes with good developer doc and user doc explaining the why and hows of the new algorithm version.

**Pull request merged**
