### PR TITLE
Formatting CMake files: scripts to tools

### LINKED ISSUE #25003: Run cmake_format
[cmake_format](https://github.com/cheshirekow/cmake_format) should make our cmake files easier to read. Apply it to things that aren't finders back-ported from a newer cmake.

### PR DESCRIPTION
**Pull request by alicerussell1**
**Description of work.**
This PR formats the CMake files to make them easier to read. This has been done using [cmake_format](https://github.com/cheshirekow/cmake_format). This is for the files from scripts to tools.

**To test:**
Read through and check it is easy to read and that no changes have been made that will effect the functionality of the file.

Fixes #25003 
---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by TTitcombe — CHANGES_REQUESTED** [review]
CMakelists looks a lot cleaner. 
I just have a few comments about possible over-indentation, mainly in `set` and `set-property` commands.
I haven't tagged every instance to avoid spamming comments, but I can do if you would like

**Review by TTitcombe — APPROVED** [review]

**Comment by TTitcombe** [comment]
This PR makes really nice changes to CMakeLists to make them a lot more readable :tada:

**Review by martyngigg — COMMENTED** [review]
@alicerussell1 This is great. I've always found the inconsistency in these files makes them hard to read.

Could I ask you to create another pull request with the contents of `cmake-format --dump-config yaml` in a file called `.cmake-format.yaml` in the top-level directory of the repository? It'll allow us to ensure the configuration is consistent across time.

**Comment by martyngigg** [comment]
Could I also ask that we add some documentation, similar to Tom's [`clang-tidy` documentation](https://github.com/mantidproject/mantid/pull/25330/files), to `dev-docs/source/ToolsOverview.rst` on how we run the tool?

**Comment by martyngigg** [comment]
@alicerussell1 Can I make a small change to my request for committin the `.cmake-format`  file? The yaml one seems to have some horrible handling of unicode with things like
```yaml
additional_commands:
  !!python/unicode 'foo':
    !!python/unicode 'flags':
    - !!python/unicode 'BAR'
    - !!python/unicode 'BAZ'
```
Let's go with JSON instead: `cmake-format --dump-config json` into a `.cmake-format.json`.

**Pull request merged**
