### PR TITLE
Create symlinks only for existing targets in macOS package

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

See description in commit for more detail. This should fix the systemtests build as the package can now be installed non-interactively with `cp -r`. Currently we [see](https://builds.mantidproject.org/view/Master%20Pipeline/job/master_systemtests-osx/878/consoleText):
```
Installing package '/Users/builder/Jenkins/workspace/master_systemtests-osx/build/mantid-4.1.20191029.2052-HighSierra.dmg'
Error in subprocess Returned with code 1
cp: /Volumes/mantid-4.1.20191029.2052-HighSierra/MantidPlot.app/Contents/Frameworks/QtCore.framework/Helpers: No such file or directory
cp: /Volumes/mantid-4.1.20191029.2052-HighSierra/MantidPlot.app/Contents/Frameworks/QtCore.framework/Resources: No such file or directory
cp: /Volumes/mantid-4.1.20191029.2052-HighSierra/MantidPlot.app/Contents/Frameworks/QtGui.framework/Helpers: No such file or directory
cp: /Volumes/mantid-4.1.20191029.2052-HighSierra/MantidPlot.app/Contents/Frameworks/QtHelp.framework/Helpers: No such file or directory
cp: /Volumes/mantid-4.1.20191029.2052-HighSierra/MantidPlot.app/Contents/Frameworks/QtHelp.framework/Resources: No such file or directory
cp: /Volumes/mantid-4.1.20191029.2052-HighSierra/MantidPlot.app/Contents/Frameworks/QtNetwork.framework/Helpers: No such file or directory
cp: /Volumes/mantid-4.1.20191029.2052-HighSierra/MantidPlot.app/Contents/Frameworks/QtNetwork.framework/Resources: No such file or directory
cp: /Volumes/mantid-4.1.20191029.2052-HighSierra/MantidPlot.app/Contents/Frameworks/QtOpenGL.framework/Helpers: No such file or directory
cp: /Volumes/mantid-4.1.20191029.2052-HighSierra/MantidPlot.app/Contents/Frameworks/QtOpenGL.framework/Resources: No such file or directory
cp: /Volumes/mantid-4.1.20191029.2052-HighSierra/MantidPlot.app/Contents/Frameworks/QtScript.framework/Helpers: No such file or directory
cp: /Volumes/mantid-4.1.20191029.2052-HighSierra/MantidPlot.app/Contents/Frameworks/QtScript.framework/Resources: No such file or directory
cp: /Volumes/mantid-4.1.20191029.2052-HighSierra/MantidPlot.app/Contents/Frameworks/QtSql.framework/Helpers: No such file or directory
cp: /Volumes/mantid-4.1.20191029.2052-HighSierra/MantidPlot.app/Contents/Frameworks/QtSql.framework/Resources: No such file or directory
cp: /Volumes/mantid-4.1.20191029.2052-HighSierra/MantidPlot.app/Contents/Frameworks/QtSvg.framework/Helpers: No such file or directory
cp: /Volumes/mantid-4.1.20191029.2052-HighSierra/MantidPlot.app/Contents/Frameworks/QtSvg.framework/Resources: No such file or directory
cp: /Volumes/mantid-4.1.20191029.2052-HighSierra/MantidPlot.app/Contents/Frameworks/QtWebKit.framework/Helpers: No such file or directory
cp: /Volumes/mantid-4.1.20191029.2052-HighSierra/MantidPlot.app/Contents/Frameworks/QtWebKit.framework/Resources: No such file or directory
cp: /Volumes/mantid-4.1.20191029.2052-HighSierra/MantidPlot.app/Contents/Frameworks/QtXml.framework/Helpers: No such file or directory
cp: /Volumes/mantid-4.1.20191029.2052-HighSierra/MantidPlot.app/Contents/Frameworks/QtXml.framework/Resources: No such file or directory
:

Installing failed. Returned with code 1
```

**To test:**

* Build a package on mac.
* Mount the dmg with `hdiutil attach <path-to-dmg>`
* `sudo cp -r /Volumes/<mantid-VERSION>/MantidPlot.app /Applications` and it should succeed.

*There is no associated issue.*

*This does not require release notes* because **this is a regression from this cycle**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gvardany** [comment]
I wonder if the failure on macOS package build is related?

**Comment by martyngigg** [comment]
@gvardany I've seen those types of errors before but only very occasionally. When it makes the package it opens a finder window and sometimes it can't seem to get access to the window. I've rebuilt it to see what happens.

**Comment by martyngigg** [comment]
The same error seems to have occurred on master so it must be the machine but it's not obvious what the problem is.

**Comment by martyngigg** [comment]
@gvardany This seems to have worked on my latest try and there is a package there. I think it's quite sensitive to whether the machine has a GUI user logged in as the same user that Jenkins is running as.

**Review by gvardany — APPROVED** [review]
Was able to install from command line.

**Pull request merged**
