### PR TITLE
Fix RotateInstrumentComponent doc test for win7 debug

### LINKED ISSUE #15204: RotateInstrumentComponent doc test fails on win7, debug mode
In the `ExBank` example, tiny numerical differences (0 instead of -1.38778e-17, for detector 1, and 1.38778e-17 instead of 0, for detector 2). Probably the test should compare a limited number of digits, as it doesn't look like a relevant difference.
```
01:52:03       print 'Positions of detectors 1 and 2 after rotation'
01:52:03       print 'Det 1',ws.getInstrument().getDetector(1).getPos()
01:52:03       print 'Det 2',ws.getInstrument().getDetector(2).getPos()
01:52:03   Expected:
01:52:03       Original positions of detectors 1 and 2
01:52:03       Det 1 [-0.0888151,-0.108221,0.145]
01:52:03       Det 2 [-0.0659955,-0.123469,0.145]
01:52:03       Positions of detectors 1 and 2 after rotation
01:52:03       Det 1 [-1.38778e-17,-0.108221,0.233815]
01:52:03       Det 2 [0,-0.123469,0.210996]
01:52:03   Got:
01:52:03       Original positions of detectors 1 and 2
01:52:03       Det 1 [-0.0888151,-0.108221,0.145]
01:52:03       Det 2 [-0.0659955,-0.123469,0.145]
01:52:03       Positions of detectors 1 and 2 after rotation
01:52:03       Det 1 [0,-0.108221,0.233815]
01:52:03       Det 2 [1.38778e-17,-0.123469,0.210996]
```

### PR DESCRIPTION
**Pull request by FedeMPouzols**
Fixes #15204.

Still compares 6 digits but avoids issues with tiny (eps) values that are different from 0, or -tiny values that are printed as "-0" instead of "0"

**To test:**
- Tests should pass
- Review the change and make sure it is sensible

This is an internal change, so no release note.
I'm not very happy that the test (intended also as example code) gets a bit obfuscated. But I didn't find any other way to fix the test given the way we are checking the outputs

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
@MattKing06 , @raquelalvarezbanos : I think you've been working with/on this algorithm. If so, could you have a look that this makes sense?

**Comment by raquelalvarezbanos** [comment]
The algorithm we have been working on is `RotateSource`. I haven't worked on this one, but maybe @MattKing06  has...?

**Comment by MattKing06** [comment]
@raquelalvarezbanos @FedeMPouzols I haven't worked on this algorithm, but I noticed that this is a related issue to [this issue](https://github.com/mantidproject/mantid/issues/15203). Does RotateSource use RotateInstrumentComponent?

**Comment by raquelalvarezbanos** [comment]
If I remember correctly, `RotateSource` uses `MoveInstrumentComponent`

**Comment by raquelalvarezbanos** [comment]
Changes solve the issue. This may not be the ideal solution (the method `pos3D_as_str()` is going to be visible to users), but I don't see what else we could do to fix the doc tests. We could rotate by a different angle, but the examples wouldn't be so clear.

:shipit:

**Pull request merged**
