### PR TITLE
Added imaging release notes

### PR DESCRIPTION
**Pull request by dtasev**
Release notes for Imaging have been added

### CODE REVIEW

**Comment by DTasev** [comment]
Test failure is unrelated

**Comment by NickDraper** [comment]
release notes only and doc builds are happy :shipit:

**Comment by DTasev** [comment]
I  think @Anders-Markvardsen is going to add a few things to the release notes, can we hold on from merging until then?

**Comment by Anders-Markvardsen** [comment]
thanks for holding off with this pr. added reference to horizon funding for this work. Agree :shipit:

**Comment by DTasev** [comment]
PR is ready for merge

**Pull request merged**
