### PR TITLE
Fix error reporter not launching on MantidPlot

### LINKED ISSUE #29329: MantidPlot Error Reporter Dialog Does Not Appear After Running SegFault Algorithm
@LamarMoore @martyngigg 
# Expected behavior
The error reporter dialog should appear

### Actual behavior
It does not appear

### Steps to reproduce the behavior
Follow steps for test 1 from http://developer.mantidproject.org/Testing/ErrorReporter-ProjectRecovery/ErrorReporterTesting.html

### Platforms affected
MacOS, have not tried on other OS

### PR DESCRIPTION
**Pull request by StephenSmith25**
**Description of work.**
This PR fixes the error reporter not launching for MantidPlot due to the launch script pointing to the wrong path.

**To test:**

1. Code review
2. Test the package builds for OSX and Windows. 
3. Open Mantid plot
4. Run the segfault algorithm and check that the error reporter correctly appears.

Fixes #29329 . 

This does not require release notes as it was an issue introduced this sprint.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
This fixes the problem on Windows and the error reporter now pops up as expected after Segfault. Nice work.
I'll leave Daniel to approve when he's done the macOS testing.

**Review by DanielMurphy22 — CHANGES_REQUESTED** [review]
Testing on MacOS: 
For a Segfault on MantidPlot, the error reporter still does not appear! 
It does however appear for unhandled exceptions (not crashing and closing)!

**Comment by martyngigg** [comment]
@StephenSmith25 Would you like me to take a look? It'll be a bit tough if you don't have a mac :)

**Comment by StephenSmith25** [comment]
> @StephenSmith25 Would you like me to take a look? It'll be a bit tough if you don't have a mac 😃

I'm on a call with Daniel now to see if I can get anywhere with it, If not I think you'll have to look into it.

**Comment by martyngigg** [comment]
I've started a package build at https://builds.mantidproject.org/job/pull_requests-osx/37464/

**Comment by martyngigg** [comment]
A new [package](https://builds.mantidproject.org/job/pull_requests-osx/37480/artifact/build/mantid-5.0.20200909.1004-HighSierra.dmg) has built.

**Review by DanielMurphy22 — APPROVED** [review]
This now works correctly on Mac!

**Comment by martyngigg** [comment]
@mantidproject/gatekeepers it would be great if we could get this into nightly.

**Pull request merged**
