### PR TITLE
Add normalisation by bin width for 2d plots in workbench

### LINKED ISSUE #27468: 2D plots: bin width normalisation

### PR DESCRIPTION
**Pull request by alicerussell1**
**Description of work.**
This PR as normalisation by bin width in the same way it is implemented for 1d plots. 
In Mantidplot, spectrum view rebins the data before plotting so it is always normalised. 

Note: This has not been done implemented in sliceviewer, this will be done in a separate PR (#27359 ) 

**To test:**
Load a workspace in workbench (e.g. MAR11060)
Right click on the workspace and click `plot`-> `colorfill`
Right click on the plot and toggle the normalisation and check it works as expected (you can compare with mantidplot to check if it is correct) 
Try doing 2d plots from the script and check they can be normalised correctly (example scripts can be found [here](https://docs.mantidproject.org/nightly/api/python/mantid/plots/index.html))

Fixes #27468 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by NickDraper — CHANGES_REQUESTED** [review]
Can we add a right-click menu to control normalization, and log-linear axes and log-linear colour scale similar to that on the 1D plot

**Comment by NickDraper** [comment]
Also the normalization doesn't seem to work
image

the rebin string was 0,100,10000,10,11000,500,20000 on MAR11060

**Comment by NickDraper** [comment]
Plot have problems if the underlying workspace is replaced

This comes in the message window at error level
```
Error occurred in handler:
Traceback (most recent call last):
  File "c:\mantid\code\qt\applications\workbench\workbench\plotting\figuremanager.py", line 45, in wrapper
    func(*args, **kwargs)
  File "c:\mantid\code\qt\applications\workbench\workbench\plotting\figuremanager.py", line 120, in replaceHandle
    redraw_this = ax.replace_workspace_artists(workspace)
  File "c:\mantid\code\framework\pythoninterface\mantid\plots\__init__.py", line 445, in replace_workspace_artists
    workspace_artist.replace_data(workspace)
  File "c:\mantid\code\framework\pythoninterface\mantid\plots\__init__.py", line 151, in replace_data
    new_artists = self._data_replace_cb(self._artists, workspace)
  File "c:\mantid\code\framework\pythoninterface\mantid\plots\__init__.py", line 825, in _update_data
    return self._redraw_colorplot(plotfunctions.imshow, artists, workspace, **kwargs)
  File "c:\mantid\code\framework\pythoninterface\mantid\plots\__init__.py", line 884, in _redraw_colorplot
    self._attach_colorbar(artist_new, artist_orig.colorbar)
  File "c:\mantid\code\framework\pythoninterface\mantid\plots\__init__.py", line 1047, in _attach_colorbar
    cb.update_normal(mappable)
  File "C:\Mantid\Code\external\src\ThirdParty\lib\python2.7\lib\site-packages\matplotlib\colorbar.py", line 987, in update_normal
    self.draw_all()
  File "C:\Mantid\Code\external\src\ThirdParty\lib\python2.7\lib\site-packages\matplotlib\colorbar.py", line 349, in draw_all
    self._process_values()
  File "C:\Mantid\Code\external\src\ThirdParty\lib\python2.7\lib\site-packages\matplotlib\colorbar.py", line 705, in _process_values
    b = self.norm.inverse(self._uniform_y(self.cmap.N + 1))
  File "C:\Mantid\Code\external\src\ThirdParty\lib\python2.7\lib\site-packages\matplotlib\colors.py", line 1048, in inverse
    return vmin * np.ma.power((vmax / vmin), val)
ZeroDivisionError: float division by zero```

**Comment by alicerussell1** [comment]
I have fixed the issue with replacing the workspace and added the other options into the right-click menu. The issue with rebinning seems to be because it does not normalise by default unless the distribution is true or the global setting `graph1d.autodistribution` is on. I have added a check so if the data is uneven it will normalize but this also changes it for 1d plots - is this desired or would it be better to find another way to do it?

**Comment by NickDraper** [comment]
All of the points referred to before have been dealt with, normalization works, there is a nice right click menu, and updating works as well.

One final improvement.  It is hard to see, just by looking at the graph wether it has been normalized or not.
image

Perhaps, replace the title "spectrum" with the label we could use for the counts axis in a 1D plot, or is it possible to label a colour bar?

**Review by NickDraper — DISMISSED** [review]
Great, this is good to go now
image

**Comment by alicerussell1** [comment]
@NickDraper I have had to merge in master to resolve a merge conflict but I've not changed any of my code - can you approve it again

**Review by NickDraper — APPROVED** [review]
Last change was just merging master

**Pull request merged**
