### PR TITLE
Sequential fit in muon analysis

### LINKED ISSUE #22020: Sequential fit crashes
Open muon analysis and load some data
Go to the data analysis tab and add a fitting function
Select sequential fit
Use the browse button to pick some files (has to be more than one)
Click start and it will crash.

### PR DESCRIPTION
**Pull request by AnthonyLim23**
Browse would in muon analysis' sequential fit dialog would crash mantid
**To test:**
Open Muon analysis
Load HIFI 108372
Go to data analysis and add a fitting function
Do a fit
Then go to fit-> sequential fit
In the Runs box have: 108372-3,108376
Click start (it should work)
Close the dialog
Turn off the data archive and add the path to your muon data in the search directory path
Do another sequential fit but this time select your muon data with the browse button
It should work

Remove the muon path from the search directory path see #22042

Fixes #22020. 

**Release Notes** 

In release notes
---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
link to some data \\ISIS\inst$\NDXHIFI\Instrument\data\cycle_09_5

**Review by LamarMoore — APPROVED** [review]
Worked as described. Everything seems fine.

**Comment by LamarMoore** [comment]
@AnthonyLim23 there is a merge conflict with the documentation.

**Comment by NickDraper** [comment]
I've resolved that

**Comment by NickDraper** [comment]
I've aborted the rebuild as it is only a minor release notes conflict resolution and our build servers are queued up enough as it is

**Pull request merged**
