### PR TITLE
Upgrade bundled matplotlib on Windows

### PR DESCRIPTION
**Pull request by martyngigg**
Description of work.

Upgrades matplotlib in the Windows bundle to the latest version.

See mantidproject/thirdparty-msvc2015#33 and please merge this when this PR is merged.

**To test:**

* Build the branch
* Try out some of the matplotlib examples in the documentation

*No issue*

[Release Notes](https://github.com/martyngigg/mantid/commit/c9d623029f66169409ab735614000625cdfc0d14)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by MatthewBowles** [comment]
This breaks some plot customization in `mslice`. Trying to change the colour / style / width of a line causes an error and removes the plot.

Everything else looks ok.

**Comment by martyngigg** [comment]
@MatthewBowles Thanks. I'll try and make the necessary changes to `mslice`.

**Comment by martyngigg** [comment]
@Mantid-Matthew Would you mind taking another look at this? I've updated mslice to the current version of `master`.

**Comment by martyngigg** [comment]
@MatthewBowles  Would you mind taking another look at this? I've updated mslice to the current version of `master`.

**Review by MatthewBowles — CHANGES_REQUESTED** [review]
Unfortunately, I seem to have the same problem - I can't change the colour or style of any line. I tried all 3 different ways of doing this:

- Double-click overplot line on slice plot
- Double click on cut
- Settings button on cut window

And all 3 resulted in errors with different tracebacks...

**Comment by martyngigg** [comment]
Closing in favour of a new PR with upgraded numpy, scipy at the same time.

**Pull request closed without merging**
