### PR TITLE
Indirect - ConvFit - Fix incorrect column name for delta function EISF errors

### LINKED ISSUE #20024: Indirect - ConvFit - Incorrect name for EISF error in delta function table
Sequential parameter table. For delta function the name of the EISF error parameter is incorrect. It gives eg f1.f1.f1EISF_Err instead of f1.f1.f1.f0.EISF_Err.

### PR DESCRIPTION
**Pull request by brandonhewer**
Fixed an issue where the column name for EISF errors of a convolution delta function was incorrect. The previous string manipulation (substr) used incorrect values, which have been modified.

**To test:**
1. Load a sample workspace from a *_red.nxs file and an associated resolution workspace from a *_res.nxs
    file (test files attached).
2. Navigate to Interfaces > Indirect > Data Analysis and click on the ConvFit tab.
3. Input the created sample workspace into the sample field and the resolution workspace into the
    resolution field.
4. Set fit type to one/two lorentzians and make sure that under 'Delta Function', use is set to True.
5. Run the algorithm and open the created TableWorkspace.
6. Ensure that all Y-value column names match with their associated Error-value column names.

Test files:
[ConvFitFiles.zip](https://github.com/mantidproject/mantid/files/1155632/ConvFitFiles.zip)

Fixes #20024. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by PranavBahuguna — APPROVED** [review]
Following testing instructions produce a table workspace with the expected properties and error is no longer thrown when algorithm is run.

:shipit:

**Comment by ianbush** [comment]
Would it make sense to add a unit test for this?

**Comment by louisemccann** [comment]
@ianbush I don't think it does, this is just fixing a spelling mistake

**Comment by ianbush** [comment]
@louisemccann So it is, I misunderstood when I first looked!

**Pull request merged**
