### PR TITLE
Indirect - IqtFitMultiple - Find indices of stretched exponentials in function

### LINKED ISSUE #21991: Indirect - IqtFitMultiple - Error produced when StretchedExp is not at index 1 in the Composite Function
In IqtFitMultiple, the StretchedExp function is expected at index 1, if this is not the case, the attempt at creating valid ties for the function will fail.

Instead, the indices of the Stretched Exponentials in the fit function should be found and used to create the ties.

### PR DESCRIPTION
**Pull request by brandonhewer**
Currently, the IqtFitMultiple algorithm assumes that the Stretched Exponential function will be found at index 1 in the fit function. With the introduction of the new IndirectFitPropertyBrowser, this order is not guaranteed.

This PR ensures the IqtFitMultiple algorithm first finds the indices of Stretched Exponential functions, before creating the ties on their ```Stretching``` (Beta) parameter.

**To test:**
1. Navigate to Interfaces > Indirect > Data Analysis > IqtFit
2. Provide the supplied file in the ```Input``` field.
3. Change the ```Exponential``` spinner to 2.
4. Check the ```Stretched Exponential``` check-box.
5. Check the ```Make Beta Global``` check-box.
6. Click ```Run```.
7. Ensure the ```StretchExp``` function in the function browser is expanded.
8. Change the ```Plot Spectrum``` spinner and ensure the ```Stretching``` parameter remains constant throughout all spectra.

**Test File:**
[irs26176_graphite002_iqt.zip](https://github.com/mantidproject/mantid/files/1790013/irs26176_graphite002_iqt.zip)

Fixes #21991. 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by edwardb96** [comment]
It's probably a case of user error but this doesn't seem to be working for me. Changing the plot spectrum value causes the lifetime and height to jump around. Also of interest is that pressing run issues the warning `Property {} to {} does not apply to any of the  input workspaces`.

**Comment by brandonhewer** [comment]
@edwardb96 The fault was with the test instructions in this case, the parameter was meant to be ```Stretching``` not ```Lifetime```.

**Review by edwardb96 — DISMISSED** [review]
In that case this PR now works as described in the test above. :+1: Tested on Fedora 27.

**Comment by martyngigg** [comment]
@brandonhewer I think this branch has been based off `master` rather than release branch as there are some commits that don't look right.

This should fix it up for you:

```
git checkout 21991_IndirectIqtFitMultiple
git fetch
git rebase --onto origin/release-v3.12 origin/master 21991_IndirectIqtFitMultiple
```

**Comment by brandonhewer** [comment]
The issue with the history of commits on this branch should now be fixed.

**Comment by martyngigg** [comment]
@edwardb96 Would you have time to give this a quick test again?

**Comment by edwardb96** [comment]
@martyngigg I have now tested again and can confirm it still works.

**Pull request merged**
