### PR TITLE
Change systemtests to rhel7

### PR DESCRIPTION
**Pull request by rosswhitfield**
Change systemtests to rhel7 for pull request builds.

### CODE REVIEW

**Comment by rosswhitfield** [comment]
Jenkins, retest this please

**Comment by martyngigg** [comment]
Jenkins, retest this please

**Comment by rosswhitfield** [comment]
Jenkins, retest this please

**Comment by martyngigg** [comment]
Jenkins, retest this please

**Comment by rosswhitfield** [comment]
Jenkins, retest this please

**Comment by martyngigg** [comment]
Looks good now.

**Pull request merged**
