### PR TITLE
Fixed issue with select data button enabling

### LINKED ISSUE #29410: Select data in muon analysis
It is possible to get muon analysis into an odd state.

Load some data (2 or more runs)
Go to fit and add a function
Turn on simultaneous mode
Turn on TF asymmetry mode
Turn off TF asymmetry mode
The select data button has been activated - using this can get you into an odd state

just need to delete https://github.com/mantidproject/mantid/blob/9fb3dca5d87f92b72f68ec366078e9da7d083332/scripts/Muon/GUI/Common/fitting_tab_widget/fitting_tab_presenter.py#L318

### PR DESCRIPTION
**Pull request by tolu28-coder**
**Description of work.**
Fixed issue with select data data enabling on muon analysis

**To test:**

1.Open moun analysis interface and load some data (2 or more runs)
2.Go to fit and add a function
3.Turn on simultaneous mode
4.Turn on TF asymmetry mode
5.Turn off TF asymmetry mode
6.The select data button has been activated - using this can get you into an odd state

Fixes #29410 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by AnthonyLim23 — APPROVED** [review]
looks good to me

**Comment by martyngigg** [comment]
I've just realised this was targeted at `master` but has the release 5.1 milestone. I assume it should be on the release branch?

**Comment by AnthonyLim23** [comment]
yes please

**Comment by martyngigg** [comment]
I can manually fix this if needs be?

**Comment by AnthonyLim23** [comment]
yes please.

**Comment by martyngigg** [comment]
:+1: Done.

**Pull request merged**
