### PR TITLE
Fix Memory Leak in LoadSQW2

### PR DESCRIPTION
**Pull request by martyngigg**
Coverity spotted an object that wasn't being deleted when running the `LoadSQW2` algorithm.

**To test:**

A code review should suffice as the unit tests will cover the functional tests.

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
This fixes the issue, :shipit: 

Just out of curiosity, is there any particular reason why they used raw new/delete here and not a scoped/similar_ptr?

**Comment by martyngigg** [comment]
@FedeMPouzols You are right, I should have not been lazy and set a better example. I'll fix it.

**Comment by FedeMPouzols** [comment]
Or maybe there could be a maintenance task for places like this where we have new/delete leftovers that can be improved. There seem to be a few in Kernel for example.

**Comment by martyngigg** [comment]
@FedeMPouzols I've fixed that as it took no time but a maintenance task for that type of clean up would be a good idea too.

**Pull request merged**
