### PR TITLE
Add option to SaveReflections to separate by modulation vector

### LINKED ISSUE #26839: SaveReflections: Add option to save peaks with different modulation vectors to separate files
As a user I wish to save peaks in the JANA format. Currently all peaks are saved to the same file. It be useful to be able to save separate files for each modulation vector to help with identifying separate domains.

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Adds a checkbox option to allow saving peaks with separate modulation vectors into separate files in the Jana format. Currently users are post-processing the files and splitting them. The default is off to the preserve the current behaviour. 

**Report to:** ISIS/Fabio

**To test:**
This script demonstrates taking a workspace with fractional peaks and modulated structure information and saving it. Play with using multiple modulation vectors and see it splits across multiple files

```python
LoadNexusProcessed(Filename='TOPAZ_3007.peaks.nxs', OutputWorkspace='peaks')
LoadIsawUB(InputWorkspace='peaks', Filename='TOPAZ_3007.mat')
IndexPeaks(PeaksWorkspace='peaks')
PredictFractionalPeaks(Peaks='peaks', RequirePeaksOnDetector=False, ModVector1='-0.5,0,0.5', MaxOrder=1, FracPeaks='frac')
SaveReflections('peaks',Filename='test_jana.hkl',Format='Jana',SplitFiles=True)
```

Fixes #26839

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by RichardWaiteSTFC** [comment]
Seems to be an issue of assigning hklm to peaks when the modulation vector  includes componeonts that are 0.5.

In the screenshot below the modulation vector is (0.5,0,0.5) and the highlighted row is an example of where the indexing is incorrect - it can be (3,2,3), +1 or (4,2,4),-1.

image

If the modulation is changed to be e.g. 0.4 there is no problem

image

**Comment by RichardWaiteSTFC** [comment]
The fractional peak table has incorrect lattice parameters
image

**Comment by RichardWaiteSTFC** [comment]
Combined PeakWorkspaces with different modulation vectors (created by PredictFractionalPeaks with a modulation vector rather than HKL offset) when saved the algorithm doesn't recognise there are two different modulation vectors.
image
This may not be common practice - but maybe one might do this if for example there were >3 modulation vectors

**Comment by martyngigg** [comment]
> Seems to be an issue of assigning hklm to peaks when the modulation vector includes componeonts that are 0.5.
> 
> In the screenshot below the modulation vector is (0.5,0,0.5) and the highlighted row is an example of where the indexing is incorrect - it can be (3,2,3), +1 or (4,2,4),-1.
> 
> image
> 
> If the modulation is changed to be e.g. 0.4 there is no problem
> 
> image

@RichardWaiteSTFC Thanks for testing this. Could you a comment on how you reproduced this?

**Comment by martyngigg** [comment]
> Combined PeakWorkspaces with different modulation vectors (created by PredictFractionalPeaks with a modulation vector rather than HKL offset) when saved the algorithm doesn't recognise there are two different modulation vectors.
> image
> This may not be common practice - but maybe one might do this if for example there were >3 modulation vectors

I think this is most likely an issue with `CombinePeaksWorkspaces` not saving the vectors correctly. Could we create a separate issue for that?

**Comment by RichardWaiteSTFC** [comment]
> > Seems to be an issue of assigning hklm to peaks when the modulation vector includes componeonts that are 0.5.
> > In the screenshot below the modulation vector is (0.5,0,0.5) and the highlighted row is an example of where the indexing is incorrect - it can be (3,2,3), +1 or (4,2,4),-1.
> > image
> > If the modulation is changed to be e.g. 0.4 there is no problem
> > image
> 
> @RichardWaiteSTFC Thanks for testing this. Could you a comment on how you reproduced this?

This can be reproduced using the script in the PR (as the modulation vector used there is -0.5,0,0.5)

**Comment by martyngigg** [comment]
@RichardWaiteSTFC Thanks for testing this. I think it should be fixed now. No rush to test though.

**Review by RichardWaiteSTFC — COMMENTED** [review]
This works as expected, though it throws up a warning  (possibly due to python 2/3 differences?)

     Enum[item_name] is deprecated; use getattr(Enum, item_name)

**Comment by martyngigg** [comment]
@RichardWaiteSTFC I think I have fixed the warning and test failures now. I had not updated the reference files with the new information.

**Review by RichardWaiteSTFC — DISMISSED** [review]
SaveReflections works as expected. As discussed with Pas (WISH) when there are overlapping satellite peaks there should be an row for each modulation vector - but this will be raised as another issue as for now there is a workaround for such cases (doing integration/saving separately for each domain).

**Comment by gemmaguest** [comment]
@martyngigg This has conflicts

**Comment by martyngigg** [comment]
@gemmaguest Thanks. I'll fix them.

**Comment by martyngigg** [comment]
This is ready to go now.

**Review by RichardWaiteSTFC — APPROVED** [review]
Last commit just fixes some tests - the code is unchanged since last review.

**Comment by gemmaguest** [comment]
@martyngigg Sorry, there are more conflicts!

**Comment by martyngigg** [comment]
@gemmaguest Doh :man_facepalming: As it is just the release notes I was wondering if you minded merging it locally to master, fixing the conflict (just keep both lines that have been added) and pushing to the merge to master? I sometime do this with other PRs that have trivial conflicts in release notes to avoid the whole rebuild cycle and more potential conflicts.

**Comment by martyngigg** [comment]
Thanks!

**Pull request merged**
