### PR TITLE
Changes to make MPI build work again

### PR DESCRIPTION
**Pull request by stuartcampbell**
I've added the FindBoost.cmake file and a hack so it can find the boost mpi libraries.
This will also need a boost version of at least 1.41.0-27.el6.x86_64 (for RHEL6).

### CODE REVIEW

**Comment by stuartcampbell** [comment]
To test, you can just look at the status of the job (http://builds.mantidproject.org/job/master_clean_rhel6_mpi_systemtested/) - which at the moment is looking at this branch, so if you merge this, please DO NOT delete this branch until I have changed the job on jenkins.

**Comment by VickieLynch** [comment]
I want to see if this works on my rhel6 machine.  I will not merge until you have removed the In Progress label.

**Comment by stuartcampbell** [comment]
There was a little nastiness that I did in order to get the test data in the correct place, you can see the full horror in the job config.  It is basically down to the Testing directory in parallel to the Framework (which we are running cmake from and therefore it can't find it)

I also found that I had to use LD_PRELOAD to point at the MPI library.

**Comment by stuartcampbell** [comment]
Updated Jenkins job

**Pull request merged**
