### PR TITLE
Fix shrinking instrument view image on high-pixel density displays

### LINKED ISSUE #34081: Instrument view window shrink
Related history: https://github.com/mantidproject/mantid/issues/29465 https://github.com/mantidproject/mantid/issues/28468

**Describe the bug**
On MacOS the instrument viewer displays in the bottom left corner of the display window. 
Regression from 6.3

**To Reproduce**
Have a second screen connected
Load any data
open the instrument viewer
select a display that is not Full3D (e.g. cylindrical)
Does it display in the bottom left or the full window??

See screenshots in linked issues at the top^^^

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: MacOS
 - OS Version: Monteray (all)
 - Mantid Version  6.4 candidate

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Fixes issues with scaling of the instrument view images depending on the pixel density of the monitor display.

**To test:**

This needs to be tested on a mac with retina screen and an additional lower-resolution screen connected.
Use the following script to determine this information: 

```python
from qtpy.QtWidgets import QApplication
for screen in QApplication.screens():
    print(screen.name())
    print(screen.devicePixelRatio())
```

It should print 2.0 for a retina display and 1.0 for a standard external screen.
If all values are the same then the test of moving the window between screens will not be valid.

All tests will need a workspace with an instrument. Pick any file from the standard test data.

**1. Open on Retina Screen**

* Move workbench to the retina screen
* Click show instrument and check the instrument image is full size in the viewport
* Change to one of the unwrapped views, i.e `CylinderY` and the image should still be fullsize in the viewport

**2. Open on the Standard Def Screen**

* Close any instrument view windows
* Move workbench to the standard definition screen
* Click show instrument and check the instrument image is full size in the viewport
* Change to one of the unwrapped views, i.e `CylinderY` and the image should still be fullsize in the viewport

**3. Move Window Between Screens**

* Close any instrument view windows
* Click show instrument and check the instrument image is full size in the viewport
* Drag the window to the retina screen and check that one the drag is complete the image is still full size in the viewport
* Drag the window back and check again.
* Do the above for the unwrapped view too.

Fixes #34081

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DanielMurphy22 — CHANGES_REQUESTED** [review]
As shown in person, this code change doesn't fully work in the case where you open instrument viewer on one screen and move it to the other screen. Also, when the shrink was observed (oddly on the large worse resolution monitor) moving the cursor over the image gave a flickering version of the correctly repainted image, behind the shrunk static version. The flickering hints at many repaint events, which are not noticed by the user on the laptop retina screen. I am on a release build which may play a difference.

**Comment by DanielMurphy22** [comment]
I really thought this resize would work but I'm still getting the same Screenshot 2023-01-26 at 13 22 41

**Comment by martyngigg** [comment]
> Shall we try a build package from branch?

It could be worth it. Did you start on the laptop and drag to the other monitor or the other way around?

**Comment by DanielMurphy22** [comment]
yes started on laptop

**Comment by martyngigg** [comment]
I think I have found a far better solution to this but I'm going to create a new branch and PR as the changes are drastically different.

**Pull request closed without merging**
