### PR TITLE
Change ISIS Mantid configuration script to process Instrument scientists provided files describing files, which should be copied to users

### LINKED ISSUE #13217: Implement instrument-scientist provided list of sample scripts, to copy to users for their personal analysis
Per user request below, it should be easy to modify existing user's configuration script to allow instrument scientist to define list of sample files, they want to provide to users. These files then would be copied to users as now happens with specified list of files. 

Yes, its possible.
I will implement it and put into system. I think it will really work next cycle.

Regards,

On 23/07/2015 08:04, .... (STFC,RAL,ISIS) wrote:

 
Ah, yes that must have been a meeting I missed. I understand.
 
However, in the case of MARI users, at present on the instrument they have friendly wrapper scripts to use, and I worry that if they get home and then are confronted with the full reduction script, it might blow their tiny minds. Certainly given how useless my user is being, I wouldn’t want to let her loose on the proper script. Perhaps we could discuss it with Tatiana, but might it be possible for MARI users to get the wrapper scripts iliad_mari.py and template_mari.py, or whatever they’re called in their RB directories?
 
Thanks

### PR DESCRIPTION
**Pull request by abuts**
This is relatively simple change to ISISDirectConfiguration script, written on an IS request (fixes #13217 ) which allows instrument scientists to define files, they want to copy to users and to make simple changes to contents of these files to account for python referencing these files. The files themselves usually reside in MantidScriptRepository and sample files for ISIS inelastic instruments have been pushed there for instrument scientists to try. 

Logic is relatively simple, there is unit test, which verifies this functionality and the changes have been tested together with administrative script on the live test server so they work.

Test by code review. 

Its administrative rather then Mantid change so no release notes.

### CODE REVIEW

**Comment by abuts** [comment]
The failures does not have anything to do with the ticket.

**Comment by abuts** [comment]
Failure have nothing to do with the ticket -- its something about RHEL6 configuration.

**Comment by KarlPalmen** [comment]
I've got a rebuild of RHEL6 to work.

**Comment by abuts** [comment]
fixed as PR https://github.com/mantidproject/mantid/pull/13519

**Pull request merged**
