### PR TITLE
Code to calculate rotation angle from sample logs during reduction (ISIS) 

### PR DESCRIPTION
**Pull request by abuts**
Also attempt to fix some pylint warnings

### CODE REVIEW

**Comment by abuts** [comment]
Jenkins, retest this please

**Comment by abuts** [comment]
here is the change allowing to read rotation angle from ISIS sample environment logs and  saving it into nxspe files + couple of minor bugs identified during instrument scientist testing. 

There is also some changes to reduce pylint warnings. 

Changes are easy observable by code review, (just add ?w=1 to comparison with master to see meaningful changes) 

as soon as system/unit tests have passed (and they have -- I've merged it to develop and run tests independently) they proven to be correct 

There are random failures due to Jenkins bug. I will to to rebuild couple of times, but they are not connected with code so can be disregarded.

**Comment by abuts** [comment]
Jenkins retest this please

**Comment by abuts** [comment]
Jenkins retest this please

**Comment by abuts** [comment]
This fixes ticket: http://trac.mantidproject.org/mantid/ticket/11177

**Comment by abuts** [comment]
Jenkins retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by abuts** [comment]
Jenkins retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please.

**Comment by FedeMPouzols** [comment]
This seems to be ready to be merged in. I'm passing the system tests locally now...

**Comment by FedeMPouzols** [comment]
All unit tests passed, and also all the system tests that I could run stretching my available RAM (including the ISISDirectInelastic tests).

**Pull request merged**
