### PR TITLE
Add BondAnalysis mode in SimulatedDensityOfStates

### LINKED ISSUE #13165: Add BondAnalysis mode in SimulatedDensityOfStates
Add a mode that outputs a table workspace containing the bonded atoms and the mode of vibration of the bond (stretching or bending).

This will need to read in both the `.castep` file for the bond pairs and the `.phonon` file for the momentum of the vibration of each atom.

This will provide something similar to the output Crystal provides using the same logic used to classify vibrations:
- Pairs of bonded atoms with a negligible relative motion are ignored
- The motion between the two atoms is decomposed, such that long + ang + out = 1
  - Along the path between the two atoms (long)
  - In the place between the two atoms and a third atom (ang)
  - Out of the plane (out)
- The vibration mode is then classified as follows:
  - Stretching: long > 0.85
  - Bending: ang > 0.85
  - Other: other

### PR DESCRIPTION
**Pull request by DanNixon**
Fixes #13165.

To test:
- Use the CASTEP and .phonon files in `Babylon5/Public/DanNixon/CASTEP/ba`
- Run `SimulatedDensityOfStates` in BondAnalysis spectrum type
- See that there are a significant number of stretching modes found in the higher mode numbers

Since this feature is still somewhat experimental it is not mentioned in the release notes.

### CODE REVIEW

**Comment by stuartcampbell** [comment]
Can I use my own set of .castep and .phonon files ?  Or do I need to get the ones from babylon ?

**Comment by DanNixon** [comment]
Any should work, although I have been testing with only a couple of datasets.

**Comment by ElliotAOram** [comment]
This issue was left in progress by Dan I will continue to work on it for 3.6

**Comment by ElliotAOram** [comment]
I am closing this PR for the time being and I will pick it up at another time from the branch 13165_separate_vibration_modes_in_dos

**Pull request closed without merging**
