### PR TITLE
PyChop update

### LINKED ISSUE #21814: Update PyChop with new flux tables for MAPS and MERLIN
MAPS has recently had a new guide installed which has improved the flux at the sample position by up to x25 times. The MERLIN moderator has also been changed (a Gd foil has been added as a neutron poison). This results in a reduced integrated flux but a better time structure (better resolution). 

These physical changes to the instrument means that the look-up table for the flux used in PyChop needs to be updated.

The new flux table for MAPS is here:
[PyChopMAPS_CalibWB_Guide.zip](https://github.com/mantidproject/mantid/files/1747447/PyChopMAPS_CalibWB_Guide.zip)

### PR DESCRIPTION
**Pull request by mducle**
Updates the flux look-up table for MAPS. Fixes minor bugs (incorrect FWHM vs energy transfer for multi-rep, incorrect approximate formula for FWHM vs energy transfer).

The original issue also mentions that the flux on MERLIN has changed. However, the measurements of this has just been carried out and the results are not yet processed. It will be added in another PR soon.

**To test:**

Run the PyChop interface and check that the flux looks something like the picture on the right rather than the left. Check that when multirep is selected that the lines are not all horizontal but have a curvature as in the picture.

pychop_fixes

Fixes #21814

**Release Notes** - Added

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by AndreiSavici — APPROVED** [review]
Looks good. Fix the merge conflict

**Comment by AndreiSavici** [comment]
Just a note for you, since I am running matplotlib 2.0:
```
/home/3y9/Mantid/mantid/scripts/PyChop/PyChopGui.py:205: MatplotlibDeprecationWarning: axes.hold is deprecated.
    See the API Changes document (http://matplotlib.org/api/api_changes.html)
    for more details.
  self.resaxes.hold(False)
```

**Comment by martyngigg** [comment]
I can fix the merge conflict manually when I merge it. It's only a release note change.

**Comment by mducle** [comment]
Oh sorry. I forgot about this. I'll bear the deprecation warning in future too.

**Pull request merged**
