### PR TITLE
Update live data test instructions

### LINKED ISSUE #35047: Live Data test instructions Minor update
https://github.com/mantidproject/mantid/issues/34954#issuecomment-1385699370

Live Data instructions: https://developer.mantidproject.org/Testing/LiveData/LiveDataTests.html
The instructions in the 'ADARA Fake Event' manual testing section could do with an explicit description on how to start collecting live data.

Please also make sure that these instructions make sense for people brand new to Live Data

### PR DESCRIPTION
**Pull request by jclarkeSTFC**
**Description of work**
Improved instructions for live data testing, the current version can be found [here](https://developer.mantidproject.org/Testing/LiveData/LiveDataTests.html).

**Purpose of work**

Fixes #35047 

**To test:**
- Build dev-docs-html project
- Check live data manual testing page looks okay and the instructions are clear

*This does not require release notes* because **it is an update to developer documentation**

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by cailafinn — CHANGES_REQUESTED** [review]
Changes look good, but I've just noticed that there's a link to a video at the top of the page that doesn't appear to go anywhere. Could this be fixed as part of this PR?

**Comment by jclarkeSTFC** [comment]
> Changes look good, but I've just noticed that there's a link to a video at the top of the page that doesn't appear to go anywhere. Could this be fixed as part of this PR?

Thanks yes, I meant to do that. I'll ask in the next stand-up if anybody knows which video this link is supposed to be pointing at.

**Comment by jclarkeSTFC** [comment]
The video has been located, now the question is where to put it.

**Comment by jclarkeSTFC** [comment]
Video link should now work.

**Review by cailafinn — APPROVED** [review]
All now looking good. Video working as expected :shipit:

**Pull request merged**
