### PR TITLE
Make I0MonitorIndex Optional

### LINKED ISSUE #15075: ReflectometryReductionOne and ReflectometryReductionOneAuto should not need I0MonitorIndex
Request from Tim Charlton. Refm is missing the monitor, but we want to be able to proceed with the reduction anyway.

### PR DESCRIPTION
**Pull request by MattKing06**
Description of work.

**To test:**
- Unit tests and System tests should pass
- Tim Charlton should be given the opportunity to test this out

Fixes #15075

Either link to [Release notes](http://www.mantidproject.org/Release_Notes_3.7) change-set or state "Does not need to be in the release notes."

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
As discussed with Matt, the workflow diagram needs to be updated according to changes in this PR. 

In addition to that, when looking at the current workflow diagram I noticed some inconsistencies between the diagram and the code. I created a new issue (#15534)

**Comment by raquelalvarezbanos** [comment]
Code changes look good and `ReflectometryReductionOne` now works when no monitor index is provided (I tried the example in the documentation), but I guess we should wait for Tim's feedback on this... @MattKing06 when you are back, can you please remind him to test this?

**Comment by raquelalvarezbanos** [comment]
No news from Tim?

**Comment by MattKing06** [comment]
@raquelalvarezbanos I've yet to receive a reply from Tim about the functionality of this fix. He did reply saying that he was at a conference and he would try the fix once he was back in the office.

**Comment by raquelalvarezbanos** [comment]
Tim is happy with the new functionality and this change has also been requested by Jos and Max, so I think it's time to :shipit:

**Pull request merged**
