### PR TITLE
Remove newline chars in the script builder when writing history

### LINKED ISSUE #22898: Project Recovery cannot deal with multiline commands
**Original reporter:** [username facility]/[nobody]. 

Labelled high priority as it could lead to non-release of the Project Recovery.

### Expected behavior

The order workspace script should be able to deal with commands that have newlines within them.

### Actual behavior

Project recovery crashes in OrderWorkspaceHistory due to commands spanning more than one line.

### Steps to reproduce the behavior

* With ISIS archive access tuned on, run the following script

```
from isis_powder import Polaris

config_file_path = r"/Users/keithbutler/Mantid/RecoveryMode/TestScripts/Polaris/polaris_config_example.yaml"
polaris_example = Polaris(config_file=config_file_path,
                          user_name="Mantid")                         
polaris_example.create_vanadium( mode="Rietveld", do_absorb_corrections=True, 
                                first_cycle_run_no=98531, multiple_scattering=False)
```

* Once you are sure the project history has been saved evoke a crash with `Segfault`
* Restart Mantid, when offered project recovery choose `Yes`

### Platforms affected

All

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**
Removes newline characters in the script builder if they exist, for example in a shape geometry. 

**To test:**
- Run the unit tests
- Run the following script which will create a log entry for `SetSample` that has newline chars
```
from isis_powder import Polaris

config_file_path = r"/Users/keithbutler/Mantid/RecoveryMode/TestScripts/Polaris/polaris_config_example.yaml"
polaris_example = Polaris(config_file=config_file_path,
                          user_name="Mantid")                         
polaris_example.create_vanadium( mode="Rietveld", do_absorb_corrections=True, 
                                first_cycle_run_no=98531, multiple_scattering=False)
```

- Crash Mantid and check that the SetSample entry does not split across multiple lines. 
- Note: SetSample will not work due to serialising a Python dictionary incorrectly

Fixes #22898

Does this update require release notes?
- [ ] Yes
- [x] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by keeeto** [comment]
@DavidFair - the `SetSample` command is now printing correctly as a single line, however I am still getting errors in this. 
About the types of value being set.
`ValueError: Invalid value for property Geometry (Dictionary) "{"Center":"0,0,0","Height":"4","Radius":"0.25","Shape":"Cylinder"}": Error setting value from string.
Unknown property search object Center`

**Review by keeeto — APPROVED** [review]
This does work as described. The set sample caveat should be recorded to the concepts document.

**Comment by AndreiSavici** [comment]
If it's in release 3.13, it should be branched from `release-next`

**Review by AndreiSavici — DISMISSED** [review]
Change upstream branch

**Pull request merged**
