### PR TITLE
ILL Reflectometry Auto

### LINKED ISSUE #24555: Reflectrometry work-flow
In need of a final reduction work-flow for the ILL reflectometers, a Python algorithm called `ReflectometryILLAutoReduction` needs to be created.

This is the highest level algorithm which calls
- `ReflectometryILLPreProcess`
- `ReflectometryILLSumForeground`
- `ReflectometryILLPolarizationCor`
- `ReflectometryILLConvertToQ`

It should reduce one row of a typical Cosmos table. The direct beam needs to be cached for being used by different rows.

### PR DESCRIPTION
**Pull request by vreimund**
**Description of work.**

The new algorithm `ReflectometryILLAutoProcess` performs a complete reduction of TOF reflectometry (specular) data recorded with D17 and FIGARO at the ILL. It is designed to reduce a row (multiple direct and reflected angles together) of the legacy COSMOS table. 

**To test:**

TBW.

Fixes #24555.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
@reimundILL Verena, if this is to make the release these failures need to be resolved soon.

**Comment by reimundILL** [comment]
Hi @NickDraper  , working on it now. For this work, quality matters more than being included in the release.

**Comment by reimundILL** [comment]
Unrelated Flake8 errors.

**Comment by reimundILL** [comment]
Unrelated Windows build error

**Comment by martyngigg** [comment]
@reimundILL Is this still in progress?

**Comment by reimundILL** [comment]
Yes, it seems to be ready soon. I am verifying with our data to gain confidence.

**Comment by reimundILL** [comment]
The detector position is wrong for summing in lambda for fractional line positions, this needs to be fixed in `ReflectometryILLSumForeground`

**Comment by reimundILL** [comment]
When switching `_correctForChopperOpenings` off in `ReflectometryILLConvertToQ`, magnitudes of the output workspace seem to be corrected. But after a verification process, this method should work as expected. However, there seems to be a general problem treating a bent sample, or divergence.

**Comment by reimundILL** [comment]
ReflectometryBeamStatistics verification: 

|Variable           | Cosmos | Mantid |
|-------------------|------------------------------|-----------------------------|
|da_det             | 0.00234743  | 0.00234904 |
|det_fwhm           | 0.00371554  | 0.00369628 |
|detdb_fwhm         | 0.00315529  | 0.00314500 |
|pixelwidth         | 0.00120000  | 0.001195   |
|firstif            | 0.00288008  | 0.00285386 |
|**om_fwhm (deg)**      | **0.0266156**   |    **0.0004603**   |
|om_fwhm_real (deg) | 0.0266156   |                             |
| parref.s2w        | | 0.000573 |
| pardir.s2w        | | 0.001058  |
| parref.s3w        | | 0.000601 |
| pardir.s3w        | | 3.445     |
| **pardir.sdetd**      | 0.5 * firstif / om_fwhm=0.054105 | **3.09999**     |

**Comment by reimundILL** [comment]
ReflectometryBeamStatistics verification `secondif`:

|Variable           | Cosmos | Mantid |
|-------------------|------------------------------|-----------------------------|
| da_det            | 0.00221557 | not calculated since not needed |
| det_fwhm          | 0.00331308 | 0.00329766 |
| detdb_fwhm        | 0.00287249 | 0.00286473 |
| pixelwidth        | 0.00120000 | 0.001195 |
| secondif          | 0.00165086 | 0.00163335 |
| **om_fwhm (deg)**     | **0.0152561**  | **0.00026344** |
| **pardir.sdetd**      | 0.5 * secondif / om_fwhm=0.054105 | **3.09999**     |

**Comment by reimundILL** [comment]
- The incoherent reduction for D17 using the sample angle compares well with Cosmos. However, one data point is missing.

- The incoherent reduction for D17 using the detector angle was ok but will show a shift in the momentum transfer now.

- The coherent reduction for D17 shows sometimes this shift in momentum transfer.

- The reduction for FIGARO could not yet be verified successfully. In the best case I see an offset in reflectivity only.

**Comment by reimundILL** [comment]
After merging master, the `GroupToXResolution` does not compute the expected output.

**Comment by NickDraper** [comment]
Removing the milestone as this is not ready, put it back if this is urgent for R4.2

**Comment by gvardany** [comment]
This is superseded by PR #27485

**Pull request closed without merging**
