### PR TITLE
Main revision of Muon release notes for v6.4.0

### PR DESCRIPTION
**Pull request by sf1919**
**Description of work.**
Main revision of Muon release notes for v6.4.0
- removed hidden Model Fitting notes
- Added single release note for features available under feature flags.
- Rewording of notes to make them more concise.

**To test:**

- remove `build/docs/doctrees`
- build the documents again and check there are no warnings
- Check that the links work
- Check the information is still correct
- Grammar/Spelling check
*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by SilkeSchomann** [comment]
The title of the page with the Muon changes is 'MuSR Changes' and not 'Muon Changes'. Is this intended?

**Comment by SilkeSchomann** [comment]
Most subsections have an empty section called 'Bugfixes'. Would it make sense to just remove any subsection without changes?

**Comment by sf1919** [comment]
> The title of the page with the Muon changes is 'MuSR Changes' and not 'Muon Changes'. Is this intended?

Good catch! I've checked the templates and in future it will be Muon Changes. This seems to be a hangover from the old system of release notes.

**Review by SilkeSchomann — APPROVED** [review]
Muon release notes are formatted as expected 👍

**Pull request merged**
