### PR TITLE
SANS: Remove Log Binning for 2D Reductions

### LINKED ISSUE #34572: Remove log binning for 2D reductions
From Greg:

For 2D reduction of SANS, there are currently two possibilities for specifying Qxy. We would like the option of “log” binning removed. It currently does not work, you can’t start at 0 on a log plot, and the group agreed that “lin” binning should be the only option. (Screenshot called MantidFix1.png is attached.)

image

### PR DESCRIPTION
**Pull request by cailafinn**
**Description of work.**
Log binning doesn't make sense for these reductions as they have to start from 0. Remove it and show a warning if a user happens to load a TOML user file containing the invalid setup. 

**To test:**
1. Make sure you have the Training Course Data
2. Go into the `maskfile.toml` in the `loqdemo` and save a copy with the `[binning.2d_reduction]` `type` set to `"Log"`.
3. Boot the ISIS SANS GUI
4. Load the user file you just made
5. You should get a warning with a useful message in the details. 
6. Change the `type` back to `"Lin"`.
7. Load the file again. It should load cleanly and correctly set the values on the GUI (Settings -> Q, Wavelength, Detector Limits). 
8. There should not be a way to change the step type for Qxy present on the GUI. 

Fixes #34572 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DanielMurphy22 — COMMENTED** [review]
Looks really good. Just would like to discuss the behaviour! So if I set the step type to "Dan" in the TOML file then there is no warning and I guess it continues happily setting it to Lin. Also if I load from MaskFile.txt where I've tried to set it to LOG then it also is silently assuming Lin with no error message. Feel free to argue to keep the code as is, but is it harder to have the error message appear for txt files and invalid step types? Or is there a reason you'd rather not?

**Comment by ConorMFinn** [comment]
The `.txt` based mask files aren't really intended to be used anymore, so I'm hesitant to add more error handling to an old system that's not meant to really be used. A log QXY would be invalid anyway, so I can't see one of those mask files existing. 

You make a good point about the TOML ones though, since we're checking the error anyway it makes more sense to check if it isn't LIN

**Review by DanielMurphy22 — CHANGES_REQUESTED** [review]
Thanks for adding the test! Are you wanting to support setting "LIN" in the maskfile? At the moment I'm getting the error: `LIN binning is not supported for 2D reductions. The type must be set to "Lin".`

**Comment by ConorMFinn** [comment]
No, some of the underlying code relies on the setting being in the `"Lin"` form as specified by `RangeStepType.LIN`. Good point though, so I'm glad I checked

**Review by DanielMurphy22 — APPROVED** [review]

**Pull request merged**
