### PR TITLE
Setting the logging to debug changes fit parameters in unit tests.

### LINKED ISSUE #12948: Setting the logging to debug changes fit parameters in unit tests
Setting the root logger level to debug, leads to unit test failures that are related to a call to `minimizer->costFunctionVal()` in `Fit.cpp`.

As far as I can follow this should never happen  The error show in 2 unit tests, one of which is `CurveFittingTest_SeqDomainSpectrumCreatorTest`.  The error message is

```
985: In SeqDomainSpectrumCreatorTest::testFit:
985: C:/Mantid/Code/Mantid/Framework/CurveFitting/test/SeqDomainSpectrumCreatorTest.h:277: 
Error: Expected (fun->getParameter(0) == 2.0) up to 1e-6 (0.0000), found (1.9999 != 2.0000)
```

it can be prevented by removing the following lines in Fit (starting at line 184)
```
if (g_log.is(Kernel::Logger::Priority::PRIO_INFORMATION)) {
      g_log.debug() << "Iteration " << iter
                    << ", cost function = " << minimizer->costFunctionVal()
                    << "\n";
    }
```

### PR DESCRIPTION
**Pull request by mantid-roman**
Fixes #12948.

See the test case in the issue.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
3 system tests that failed:
- win7: TEST-MDAlgorithmsTest.ConvertCWPDMDToSpectraTest
- hel7:     SystemTests.CalibrateRectangularDetector_Test.PG3Calibration and     SystemTests.POLDIFitPeaks2DTest.POLDIFitPeaks2DPawleyTest

I've re-started these two builds to see if they're spurious. Let's see what happens. The POLDI test could be a true positive, as I remember Michael having issues with POLDI tests on different platforms depending on the log level.

**Comment by mantid-roman** [comment]
Failure of POLDIFitPeaks2DPawleyTest isn't spurious but without Michael it's hard to tell how to fix it.

**Comment by FedeMPouzols** [comment]
Yes, the other failures didn't happen in the second run. It's only `POLDIFitPeaks2DPawleyTest`. I run `POLDIFitPeaks2DPawleyTest` also locally on debian and I got a similar result:
```
` File "<string>", line 1, in <module>
  File "/home/fedemp/test/mantid-repos/mantid/Code/Mantid/Testing/SystemTests/lib/systemtests/stresstesting.py", line 200, in execute
    self.runTest()
  File "/home/fedemp/test/mantid-repos/mantid/Code/Mantid/Testing/SystemTests/tests/analysis/POLDIFitPeaks2DTest.py", line 113, in runTest
    self.assertLessThan(np.abs(cell_a - 5.4311946) / cell_a_err, 1.5)
  File "/home/fedemp/test/mantid-repos/mantid/Code/Mantid/Testing/SystemTests/lib/systemtests/stresstesting.py", line 414, in assertLessThan
    raise Exception(msg)
Exception: Expected 1.69436 < 1.5 
```
So it's this line https://github.com/mantidproject/mantid/blob/master/Code/Mantid/Testing/SystemTests/tests/analysis/POLDIFitPeaks2DTest.py#L113 where the expected difference is 1.5% and on linux is now a bit bigger. I'm guessing that @MichaelWedel might have fine-tuned these comparisons for the buggy behavior before this branch. So we have two options: 
- increase a bit that figure, for example from 1.5 to 2 and tell Michael when he's back just in case (I'd say this is not risky as the POLDI functionality does not change, only the espsilon of a test comparison), 
- or wait until then (I think he was back in September?).

Other than that, the changes look good and this fixes a tricky issue when developing tests.
Other system tests which are also sensitive to fitting results are working well, including the EnginX ones. So I'd say that these changes are safe and very convenient.

**Comment by mantid-roman** [comment]
You are right. Let's fix this issue now.

**Comment by FedeMPouzols** [comment]
All looks good. We have to remember to remind Michael that this is now fixed as he might want to revisit his tests.

**Comment by MichaelWedel** [comment]
Thanks for notifying me @FedeMPouzols, I found your comment in one of my older tickets regarding something related. The test checks how many multiples of the parameter error deviates from the expected value. In this case it checked that the results deviates not more than 1.5 * parameter error. Since the check for the value did not have to be adjusted it could simply mean that the error got smaller, I'll check that in more detail. But the Pawley function is also covered by a doctest, so I'm confident that nothing major has happened.

I'm just wondering why the test changed in the first place, since I added code to PoldiFitPeaks2D that sets the log-level to something "non-buggy".

**Comment by mantid-roman** [comment]
It wasn't about logging. The bug was due to inconsistency in calculations of the cost function and its derivatives. The minimizer expected those calculations to be synchronized for efficiency. Calling cost function's val() method an extra time (debug code did that) was breaking the synchronization and changing the fit results. Maybe your code calls val() someplace?

**Comment by MichaelWedel** [comment]
Okay, thanks for the clarification. I have made some tests with theoretical data and everything checks out. At some point I could integrate what I did as a real system test, or replace the current Pawley test.

**Pull request merged**
