### PR TITLE
Two new minimizers: DTRS and More-Sorensen

### LINKED ISSUE #15897: Translate RAL_NLLS fortran fitting library to C++.
The SCD numerical group has developed a fitting library for Mantid. The library needs to be translated to C++ and integrated into Mantid.

### PR DESCRIPTION
**Pull request by mantid-roman**
Added two new minimizers - DTRS and More-Sorensen.

**To test:**

Fit some data sets using these minimzers.

Fixes #15897.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Anders-Markvardsen** [comment]
Hi Roman, the translation is clear and good. Note, I did a search for 'abs' and found all no cases of abs (only fabs), and I have tested with various examples.

Could you add a sentence along the lines of 'This code was originally translated from Fortran code on https://ccpforge.cse.rl.ac.uk/gf/project/ral_nlls June 2016' in the new .h files you have added?  To give someone looking at the code an idea where it comes from

In e.g. TrustRegionMinimizer.h currently use both camelCase and non-camelCase for functions names - is there a good reason for this?

**Comment by Anders-Markvardsen** [comment]
Looks good :shipit: 

Note also that Tyrone from STFC SCD numerical group had also tested Roman's translation and he writes: "These two aside -- assuming I'm interpreting the results correctly -- I'm happy with the performance of Roman's implementation.  By my count, the trust region codes (specifically DTRS) finds a smaller minimum 8 times, while Levenberg-Marquardt only gets smaller twice (for MGH10 and
ECKERLE4) (and for the other 33 problems, both approaches agree as to the local minimum found).  Interestingly, for the examples that actually come from ISIS (the five vesuvio problems), DTRS always returns a smaller (local) minimum."

**Comment by peterfpeterson** [comment]
The links in the `rst` files point to a project page that has no clear information on what the minimizers are/do. Please add links to useful information about these.

**Comment by Anders-Markvardsen** [comment]
@peterfpeterson thanks for you interest. In fact we have very little information about nearly all the minimizers we support, however we have this issue #15014 currently down for 3.8 which will rectify this

**Pull request merged**
