### PR TITLE
Fix InstrumentView rebin bug

### LINKED ISSUE #34625: Rebinning for second time on ALFView does not behave as expected
**Describe the bug**
When rebinning data for a second time on ALFView, the rebinning is done on the data which has been rebinned and not the original data. It is more sensible to rebin based on the original data.

**To Reproduce**
1) Open `Direct`->`ALFView` interface
1) Load data [ALF82301](file:///home/mlc47243/Documents/other-documents/ALFView/ALF82301.zip)
2) Click on `Pick` tab
3) Click on `Add single crystal peak` icon so that the little graph doesn’t keep changing
4) Click on the peak
5) Expand `Rebin` section. Filter by d-spacing range `5.0,0.01,6`
6) Filter by d-spacing range again with a different range `5.5,0.01,6`
7) This second rebinning is not performed on the original data

**Expected behavior**
The rebinning should be performed on the original data, as a first rebin attempt is likely a mistake or requires an adjustment.

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR fixes a bug where rebinning data on the InstrumentView Pick tab multiple times will keep rebinning the previously rebinned data instead of the originally loaded data. I think the rebinning should be performed on the originally loaded data for a few reasons:

- If you don't know the desired rebinning, you might do an initial 'test' rebin and then want to adjust the rebin parameters based on the results. This is not possible as you would have to close and reopen the interface to load the original data back in.
- Performing a rebin on top of a rebin is confusing as its hard to understand the net rebin effect. A single rebin operation is surely much preferred.

This can be tested on the ALFView interface as it has an embedded instrument view widget.

**To test:**
1. Open `Direct`->`ALFView` interface
2. Load ALF82301.The data should look like
image

4. Click 'Pick' tab
5. Expand 'Rebin' section
6. Use parameters `4,0.01,6` and click `Run`
image
7. Then use parameters `5,0.01,6` and click `Run`
image
8. Then use parameters `5.5,0.01,6` and click `Run`
image

Fixes #34625

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by RichardWaiteSTFC — COMMENTED** [review]
Just tried this with SXD and ran into a problem possibly if rebin throws an error?

(1) Load SXD data  `Load(Filename='SXD23767.raw', OutputWorkspace='SXD23767')`
On my computer the RAM used by mantid is now 1.5 GB
(2) Open in instrument view
(3) Put silly rebin parameters `800,0.01,19000` (too fine binning seems to eventually produce this error)
```
Error in execution of algorithm Rebin
Rebin: error (see log)
Rebin: bad allocation
```
(4) Put in more sensible rebin params `800,1,19000`
RAM jumps to ~9GB RAM and instrument view looks weird (looks like data cropped)
image
 (5) Close instrument view - RAM now 7GB...

**Review by RichardWaiteSTFC — DISMISSED** [review]
Nice fix, works as described (note @robertapplin found that the behaviour in my previous comment could be reproduced on main - so not related to this PR). It doesn't look like there are any tests in this area, so not worth holding up this fix for one.

There is a separate bug using rebin tool which seems to incorrectly set the slider (the limits should be 800 and 1000 on the image below) - do you want me to create a separate issue?
image

**Comment by robertapplin** [comment]
> Nice fix, works as described (note @robertapplin found that the behaviour in my previous comment could be reproduced on main - so not related to this PR). It doesn't look like there are any tests in this area, so not worth holding up this fix for one.
> 
> There is a separate bug using rebin tool which seems to incorrectly set the slider (the limits should be 800 and 1000 on the image below) - do you want me to create a separate issue? image

Yes that would be great thanks - just checked and I can reproduce the same issue

**Comment by martyngigg** [comment]
I was about to merge this but paused as I don't think this should be classified as a bug - it was functionally correct before was just inconvenient, as you say, to be able to go back to the original.

I think you have made completely valid points w.r.t to the usability issues here in the instances that you describe. An issue I can see however is that we now effectively have a copy of the original data that is impossible to delete until you close the view. If I had say a 20GB dataset (e.g. WISH) then I essentially keep a 20GB copy and then still need the space for the new workspace and if memory gets tight I've got no way of killing the original even if I don't want to rebin again.

I think we need to try and come up with a way to be able to control this. Maybe an option to "keep original workspace" or something that can have a warning if selected that it will use more memory? When unchecked it would behave as before and the act of unchecking it would delete the original if once was stored? Just one thought...

**Comment by RichardWaiteSTFC** [comment]
> I was about to merge this but paused as I don't think this should be classified as a bug - it was functionally correct before was just inconvenient, as you say, to be able to go back to the original.
> 
> I think you have made completely valid points w.r.t to the usability issues here in the instances that you describe. An issue I can see however is that we now effectively have a copy of the original data that is impossible to delete until you close the view. If I had say a 20GB dataset (e.g. WISH) then I essentially keep a 20GB copy and then still need the space for the new workspace and if memory gets tight I've got no way of killing the original even if I don't want to rebin again.
> 
> I think we need to try and come up with a way to be able to control this. Maybe an option to "keep original workspace" or something that can have a warning if selected that it will use more memory? When unchecked it would behave as before and the act of unchecking it would delete the original if once was stored? Just one thought...

So this was my concern (for WISH) - I think they way it works is that it only copies the data if the user choses to rebin and on closing the instrument view it then keeps the rebinned version of the workspace rather than the original. I think WISH (who as rule are not going to rebin in instrument view because of the data size) will not mind the current version or having an additional option as you suggest.

One thing that occurs to me (probably a separate PR) is that we do not need to rebin the whole worksapce, just the curve in the curve preview - would this avoid our problems? The user then optimises the rebin parameters and applies it to the workspace outside the viewer?

**Comment by robertapplin** [comment]
> I was about to merge this but paused as I don't think this should be classified as a bug - it was functionally correct before was just inconvenient, as you say, to be able to go back to the original.
> 
> I think you have made completely valid points w.r.t to the usability issues here in the instances that you describe. An issue I can see however is that we now effectively have a copy of the original data that is impossible to delete until you close the view. If I had say a 20GB dataset (e.g. WISH) then I essentially keep a 20GB copy and then still need the space for the new workspace and if memory gets tight I've got no way of killing the original even if I don't want to rebin again.
> 
> I think we need to try and come up with a way to be able to control this. Maybe an option to "keep original workspace" or something that can have a warning if selected that it will use more memory? When unchecked it would behave as before and the act of unchecking it would delete the original if once was stored? Just one thought...

That is a fair point, I will add a checkbox with the described behaviour.

I wonder if there is a way to set the checkbox automatically as ticked (or unticked) depending on how large the loaded dataset is. Is there maybe a method on `Workspace` that returns a memory size?

**Comment by martyngigg** [comment]
> > I was about to merge this but paused as I don't think this should be classified as a bug - it was functionally correct before was just inconvenient, as you say, to be able to go back to the original.
> > I think you have made completely valid points w.r.t to the usability issues here in the instances that you describe. An issue I can see however is that we now effectively have a copy of the original data that is impossible to delete until you close the view. If I had say a 20GB dataset (e.g. WISH) then I essentially keep a 20GB copy and then still need the space for the new workspace and if memory gets tight I've got no way of killing the original even if I don't want to rebin again.
> > I think we need to try and come up with a way to be able to control this. Maybe an option to "keep original workspace" or something that can have a warning if selected that it will use more memory? When unchecked it would behave as before and the act of unchecking it would delete the original if once was stored? Just one thought...
> 
> That is a fair point, I will add a checkbox with the described behaviour.
> 
> I wonder if there is a way to set the checkbox automatically as ticked (or unticked) depending on how large the loaded dataset is. Is there maybe a method on `Workspace` that returns a memory size? And if so, do you have an idea for what the threshold should be for ticking/unticking it?

Thanks. There is a method for the workspace size but it's a bit arbitrary really what you would pick I think. I would say let's check it by default and if the warning comes up as some text that's just below the boxes then it can be seen and unchecked. We can then remember the value for future behaviour?

**Comment by robertapplin** [comment]
Thanks, should be ready for another test @RichardWaiteSTFC . The 'Keep original workspace' option should be saved in the QSettings and reloaded upon reopening the interface. Unticking the option should delete the original workspace if it exists

**Review by RichardWaiteSTFC — APPROVED** [review]
Looks good, I believe it functions as expected (see below for memory in GB)
image
I think the default behaviour is correct (to keep the original workspace) and subsequently instrument view remembers what the status of the checkbox was on close/re-open.

**Pull request merged**
