### PR TITLE
Fix warning on FuryFit regarding numerical derivatives

### PR DESCRIPTION
**Pull request by DanNixon**
Fixes [#11133](http://trac.mantidproject.org/mantid/ticket/11133).

To test, see that the error is no longer emitted in system tests (just after the Fit call in `(OS)IRISFuryAndFuryFitMulti`).

### CODE REVIEW

**Comment by DanNixon** [comment]
Jenkins, retest this please.

**Comment by martyngigg** [comment]
It looks like there is now a merge conflict with master that needs resolving. It is most likely from ~~#227~~ I guess

**Comment by DanNixon** [comment]
Jenkins, retest this please.

**Comment by martyngigg** [comment]
This has removed the warnings and not affected the results but the error on OS X is still present.

**Pull request merged**
