### PR TITLE
Fix Vesuvio system tests

### PR DESCRIPTION
**Pull request by martyngigg**
Description of work.

Fixes broken system tests that were introduced with #21806.

**To test:**

* `systemtest -R VesuvioCommands`
* `systemtest -R VesuvioLoading`

The tests should pass. 

*No issue*

**Release Notes** 
*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by ElliotAOram** [comment]
`VesuvioLoading` now  passes locally for me, but I'm still having issues in `VesuvioCommands`

```
FAILED:
VesuvioCommandsTest.CalculateCumulativeAngleAveragedData
VesuvioCommandsTest.FitSingleSpectrumBivariateGaussianTiesTest
VesuvioCommandsTest.PassPreLoadedWorkspaceToFitTOF
```

**Comment by ElliotAOram** [comment]
```
Traceback (most recent call last):
  File "c:\users\hvq65228\appdata\local\temp\tmpvytpaw", line 9, in <module>
    exitcode = systest.returnValidationCode(99)
  File "C:\Users\hvq65228\Documents\github\mantid\Testing\SystemTests\lib\systemtests\stresstesting.py", line 375, in returnValidationCode
    if self.doValidation():
  File "C:\Users\hvq65228\Documents\github\mantid\Testing\SystemTests\lib\systemtests\stresstesting.py", line 345, in doValidation
    validation = self.validate()
  File "C:/Users/hvq65228/Documents/github/mantid/Testing/SystemTests/tests/analysis\VesuvioCommandsTest.py", line 503, in validate
    _test_caad_workspace(self, '15039-15045_normalised_iteration_' + str(exit_iteration), functions)
  File "C:/Users/hvq65228/Documents/github/mantid/Testing/SystemTests/tests/analysis\VesuvioCommandsTest.py", line 46, in _test_caad_workspace
    caad_workspace = mtd[workspace_name]
KeyError: "'15039-15045_normalised_iteration_1' does not exist."
```

**Comment by martyngigg** [comment]
@brandonhewer Any ideas? They passed locally for me.

**Comment by brandonhewer** [comment]
@martyngigg I'll take a look at these issues

**Comment by ElliotAOram** [comment]
All passing except `PassPreLoadedWorkspaceToFitTOF`:
```
Traceback (most recent call last):
  File "c:\users\hvq65228\appdata\local\temp\tmpicp6fi", line 8, in <module>
    systest.execute()
  File "C:\Users\hvq65228\Documents\github\mantid\Testing\SystemTests\lib\systemtests\stresstesting.py", line 216, in execute
    self.runTest()
  File "C:/Users/hvq65228/Documents/github/mantid/Testing/SystemTests/tests/analysis\VesuvioCommandsTest.py", line 413, in runTest
    self._fit_results = fit_tof(runs_ws, flags)
  File "C:/Users/hvq65228/Documents/github/mantid/scripts/Inelastic\vesuvio\commands.py", line 32, in fit_tof
    flags.get('spectra', None), vesuvio_loader)
  File "C:/Users/hvq65228/Documents/github/mantid/scripts/Inelastic\vesuvio\loading.py", line 90, in __init__
    mtd.addOrReplace(self._tof_workspace_suffix(sample_runs, spectra),
  File "C:/Users/hvq65228/Documents/github/mantid/scripts/Inelastic\vesuvio\loading.py", line 146, in _tof_workspace_suffix
    return runs + "_" + spectra + "_tof"
  File "C:\Users\hvq65228\Documents\build\bin\Release\mantid\api\_workspaceops.py", line 32, in op_wrapper
    inplace, reverse)
  File "C:\Users\hvq65228\Documents\build\bin\Release\mantid\api\_workspaceops.py", line 93, in _do_binary_operation
    resultws = _api.performBinaryOp(self,rhs, op, output_name, inplace, reverse)
Boost.Python.ArgumentError: Python argument types in
    mantid.api._api.performBinaryOp(Workspace2D, str, str, str, bool, bool)
did not match C++ signature:
    performBinaryOp(class boost::shared_ptr<class Mantid::API::WorkspaceGroup>, double, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, bool, bool)
    performBinaryOp(class boost::shared_ptr<class Mantid::API::IMDHistoWorkspace>, double, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, bool, bool)
    performBinaryOp(class boost::shared_ptr<class Mantid::API::IMDWorkspace>, double, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, bool, bool)
    performBinaryOp(class boost::shared_ptr<class Mantid::API::IMDHistoWorkspace>, class boost::shared_ptr<class Mantid::API::IMDHistoWorkspace>, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, bool, bool)
    performBinaryOp(class boost::shared_ptr<class Mantid::API::WorkspaceGroup>, class boost::shared_ptr<class Mantid::API::WorkspaceGroup>, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, bool, bool)
    performBinaryOp(class boost::shared_ptr<class Mantid::API::WorkspaceGroup>, class boost::shared_ptr<class Mantid::API::IMDWorkspace>, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, bool, bool)
    performBinaryOp(class boost::shared_ptr<class Mantid::API::IMDWorkspace>, class boost::shared_ptr<class Mantid::API::WorkspaceGroup>, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, bool, bool)
    performBinaryOp(class boost::shared_ptr<class Mantid::API::IMDWorkspace>, class boost::shared_ptr<class Mantid::API::IMDWorkspace>, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, bool, bool)
```

**Comment by martyngigg** [comment]
@ElliotAOram Could you re-test this one?

**Review by ElliotAOram — APPROVED** [review]
Test are all working now (on windows)! @mantidproject/gatekeepers this is still broken on master, so a quick merge would be great!

**Comment by SimonHeybrock** [comment]
I assume the build server comes to the same agreement -- given that `master` is already broken, and all changes here should affect only the already broken tests I feel that merging ahead of time is safe.

**Comment by yxqd** [comment]
Merging this PR causes systemtests of conda build of mantid framework to fail: http://builds.mantidproject.org/view/Master%20Pipeline/job/master_systemtests-conda/174/
http://builds.mantidproject.org/view/Master%20Pipeline/job/master_systemtests-conda/175/

**Comment by peterfpeterson** [comment]
Those builds happened *before* this was merged.

**Comment by yxqd** [comment]
@peterfpeterson you are right.

**Pull request merged**
