### PR TITLE
Fix LoadLogs loading thowing an error on rubbish log files

### LINKED ISSUE #20515: LoadLog shows error on bad ISIS logs
@FreddieAkeroyd reported to us that a few of the log files for the start of this cycle seem to cause an error in mantid:

```
We had an issue with the log writer in a new version of EPICS, that has ended up with some “junk” being put into the _ICPputlog.txt file that is loaded when Mantid reads .raw files on IBEX instruments. I loaded ENGINX0000275776.raw into Mantid and got:
 
ISIS log file contains unrecognised second column entries://isis/inst$/NDXENGINX/Instrument/data/cycle_17_2/ENGINX00275776_ICPputlog.txt
Unable to successfully run LoadLog Child Algorithm
Unable to successfully run LoadLog Child Algorithm
 
It looks like the other logs were read OK, I just wanted to make you aware of it so you could check the new Mantid release is working OK
```

### Expected behavior
LoadLogs should ignore the rubbish in those lines

### Actual behavior
LoadLogs throws an error.

### Steps to reproduce the behavior
Run LoadRaw with the raw file & logs from ENGINX mentioned in Freddie's email.

### Platforms affected
All.

### PR DESCRIPTION
**Pull request by samueljackson92**
This changes the LoadLog routine to fix the issue that @FreddieAkeroyd was seeing. Mantid now appears to load the raw file cleanly.

**To test:**
 - Go to the archive and grab everything for run ENGINX0000275776
 - Try loading the raw file with `LoadLogs = true`
 - Before these changes you should see an error
   - Afterwards you should see none
 - Code review.

Fixes #20515 

**Release Notes** 
*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
Should we lift one of those log files out and add a unit test?

**Comment by samueljackson92** [comment]
Might be a good idea, yes.

**Comment by samueljackson92** [comment]
@martyngigg Don't approve this just yet I want to investigate further why it chose the two column file.

**Comment by samueljackson92** [comment]
@martyngigg it seems that it chooses the 3 column file type because the text contains spaces? In this function it parses the first word and then attempts to parse another. Because that successfully returns a string then it assumes it must be a three column format.

https://github.com/mantidproject/mantid/blob/d307fc25793d6ff7526fdb9541bf9dbb6326a3e2/Framework/DataHandling/src/LoadLog.cpp#L495-L540

**Comment by martyngigg** [comment]
Sam, `cppcheck` seems to be unhappy.

**Review by martyngigg — APPROVED** [review]
This looks good to go now and helps avoid a warning with some bad ISIS log files that were written when commissioning the new DAE software.

**Comment by martyngigg** [comment]
The Windows failure is the unrelated MantidPlotSerialise test timeout.

**Pull request merged**
