### PR TITLE
Fix documentation warnings

### LINKED ISSUE #34391: Fix documentation warnings
**Describe the bug**
There are more than 20 warnings when building the user documentation. Some of these warnings relate to the ISISPoweder-OSIRIS.rst file which is also not showing in tables of content. It is hoped that by fixing these warnings it may resolve that issue also.

**To Reproduce**
1. Build the documentation and note the warning messages.

**Expected behavior**
There should be no warnings.

**Platform/Version (please complete the following information):**
- release-next branch built on Windows 10 machine on 15/09/22

**Addtional Context**
Warnings are on the following files:-
- DNS Powder TOF.rst
- dns_powder_tof_data_tab.rst
- dns_powder_tof_options_tab.rst
- dns_powder_tof_paths_tab.rst
- dns_powder_tof_plotting_tab.rst
- dns_powder_tof_script_generator_tab.rst
- release\v6.4.0\mantidworkbench.rst
- BinMDCoordinateTransformations.rst
- CreateBackToBackParameters.rst
- CreateIkedaCarpenterParameters.rst
- ISISPowder-OSIRIS-v1.rst
- release\v6.4.0\direct_geometry.rst

### PR DESCRIPTION
**Pull request by MialLewis**
**Description of work.**

- Added `ISISPowder-OSIRIS-v1` to index
- Fixed typos in `ISISPowder-OSIRIS-v1` document cross references
- Removed the following references in `ISISPowder-OSIRIS-v1`, which appear to refer to non-existing sections:
    -  output_directory_osiris_isis-powder-diffraction-ref
    -  vanadium_normalisation_osiris_isis-powder-diffraction-ref
    -  grouping_file_name_osiris_isis-powder-diffraction-ref
    -  input_mode_osiris_isis-powder-diffraction-ref
- Fixed remaining warnings related to documentation, as per #34391 
 
**To test:**
- Build documentation via `docs-html` target. Observe no warnings.
- Check `ISISPowder-OSIRIS-v1` is in index.
- Check relevant references in `ISISPowder-OSIRIS-v1.rst` work.
- Check files listws in #34391 appear correctly.

Resolves #34391.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by MialLewis** [comment]
I note that https://github.com/mantidproject/mantid/pull/32517 removed the interpretation of doc warnings as errors. Doc warnings are now quite hard to track, as they are only shown in the console output and do not show up in the visual studio error list. 

Is there any appetite for reenabling this, assuming the issue that prompted this 12 months ago is no longer relevant?

**Comment by jhaigh0** [comment]
All seems great, I don't get any errors.

@Harrietbrown are you happy with the changes made to `ISISPowder-OSIRIS-v1`? In particular, the removal of refferences to 'non-existing sections'.

**Comment by MialLewis** [comment]
> All seems great, I don't get any errors.
> 
> @Harrietbrown are you happy with the changes made to `ISISPowder-OSIRIS-v1`? In particular, the removal of refferences to 'non-existing sections'.

I spoke to Harriet yesterday, and believe she is going to make some further changes after this PR is merged.

**Comment by Harrietbrown** [comment]
> > All seems great, I don't get any errors.
> > @Harrietbrown are you happy with the changes made to `ISISPowder-OSIRIS-v1`? In particular, the removal of refferences to 'non-existing sections'.
> 
> I spoke to Harriet yesterday, and believe she is going to make some further changes after this PR is merged.

That is correct.

**Review by jhaigh0 — APPROVED** [review]
All the minor fixes have fixed the warnings and files display properly.

Further changes to re-add links to `ISISPowder-OSIRIS-v1.rst` will be made in a separate pr as discussed.

**Comment by martyngigg** [comment]
> I note that #32517 removed the interpretation of doc warnings as errors. Doc warnings are now quite hard to track, as they are only shown in the console output and do not show up in the visual studio error list. I presume this is why these errors have built up over time.
> 
> Is there any appetite for reenabling this, assuming the issue that prompted this 12 months ago is no longer relevant?

Thanks for spotting this @MialLewis. I think you are right that we should re-enable this as I can't see a reason why we would want them to slip through. As you say we don't want them to keep building up.

**Pull request merged**
