### PR TITLE
Add slit calculator

### PR DESCRIPTION
**Pull request by eXeC64**
This is ticket [#10828](http://trac.mantidproject.org/mantid/ticket/10828)

In this pull request we:
- Add the `CalculateSlits` algorithm.
  - Documentation also added
  - Unit test also added
- Add a SlitCalculator widget.
- Add a menu item for the slit calculator in both the new and old ISIS Reflectometry Reduction UIs.
- Fixed some indentation errors in MantidWidgets' `CMakeLists.txt`

### CODE REVIEW

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by OwenArnold** [comment]
If it's OK with you Jean, I'd like to verify this one.

**Comment by JeanBilheux** [comment]
no problem.  And you are more the guy to do it anyway.

Jean

On Feb 13, 2015, at 12:07 PM, Owen Arnold <notifications@github.com<mailto:notifications@github.com>> wrote:


If it's OK with you Jean, I'd like to verify this one.

�

**Comment by OwenArnold** [comment]
All looks working as expected. Please add a section about the slit calculator here http://www.mantidproject.org/ISIS_Reflectometry_GUI.

**Pull request merged**
