### PR TITLE
Add unit tests for existing remote algorithms (+ SimpleJSON)

### PR DESCRIPTION
**Pull request by FedeMPouzols**
This fixex trac ticket [#11122](http://trac.mantidproject.org/mantid/ticket/11122).

This is a bunch of unit tests that had been missing for a long time. Even though we canot go very far in testing these algorithms at this point, It is important to have these basic tests there as a preventive step now that there's going to be a refactoring of remote algorithms and lots of code will be rearranged and moved around (see 'blocking'  tickets for details).

Tester: make sure that the tests pass and make sense.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
It currently fails to compile on win7 cause the algorithms were missing the dll export.

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by KarlPalmen** [comment]
I saw that there are many tests with name containing 'wronProperties'. I think 'wrongProperties' was intended.

**Comment by FedeMPouzols** [comment]
Yes, you're right. Thanks for spotting that. Copy&paste propagated the typo to several tests. It should be ok now.

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, test this please

**Comment by FedeMPouzols** [comment]
Jenkins, test this please

**Comment by FedeMPouzols** [comment]
Jenkins, test this please

**Pull request merged**
