### PR TITLE
fixed missing environment variables (no ticket)

### PR DESCRIPTION
**Pull request by geishm-ansto**
Fixed a bug when loading datafile. Environment variables were hard coded in the loaders for EMU and PLN and with recent changes and planned the existing soln did not include all the parameters. The implemented soln loads all available env parameters in the datafile. 

The unit test scripts for the loaders have been updated to reflect the changes.

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by geishm-ansto** [comment]
System passed but it did not include a release note, on commiting a release note the a system issue with access to 'origin' resulted in a failure. Now subsequent commits are not triggering a rebuild. Assume it is an issue with the server.

**Comment by sf1919** [comment]
It looks like there was a disconnection failure on the Windows runner used. I've set the test running again on a different runner so hopefully there won't be a problem this time round.

If you have problems like this again please post a message to the Jenkins slack channel so that a member of the DevOps Team can investigate.

**Comment by sf1919** [comment]
Have you any files I can use to test these loaders?

**Comment by geishm-ansto** [comment]
There are two datasets at ../Data/UnitTest/{"EMU0020493.tar",   "PLN0044464.hdf", "PLN0044464.bin"} that are used as part of the automatic tests that were updated for this PR.  Historically at ANSTO, the datasets contain a two files (*.hdf, *.bin) where the raw event data is stored in the bin file but for some instruments the two files are collated into a single tar file.  Browse to the folder and select the tar or hdf file to load the dataset. I didn't see the need to add any additional files to the test suite but if you need more let me know.

**Review by sf1919 — APPROVED** [review]
I've had a look over the code and it looks fine. I've tested that the loaders still work using the data suggested. I am therefore approving this PR.

However in finding ways to test this PR I noted that I couldn't get gold of the file listed in the LoadEMU documentation. I've raised this as a separate issue (#35827 ) as it shouldn't hold up this PR. I didn't check the documentation for LoadPLN but I would recommend this is also checked.

**Pull request merged**
