### PR TITLE
Rename remaining AbinsModules references in documentation

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Recent cleanup renamed all of the script modules but left a
couple of straggling references

**To test:**

Review changes.

*There is no associated issue.*

*This does not require release notes* because **it is a minor docs cleanup.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@ajjackson Would you be able to review this? It should be a quick one. I can't request a review for some reason as your not in the regular dropdown box.

**Review by cailafinn — APPROVED** [review]
Changes look good, references cleared up 👍

**Comment by ajjackson** [comment]
Thanks for cleaning up my mess while I was on holiday, much appreciated 😄

**Comment by martyngigg** [comment]
No problem. I'm not sure why the CI didn't flag the warnings on the original pull request.

**Pull request merged**
