### PR TITLE
Fix OSX build with OCCT 7.6.0

### LINKED ISSUE #32927: OSX Fails to build with OCCT 7.6.0
**Describe the bug**
As of this [commit](https://github.com/Open-Cascade-SAS/OCCT/commit/a8b605eb5e7f181c7bed7c7ef89108c4fd7ba054#diff-c1f6b634b4d06fa87c555ed830384bcc8ea4287f3321cb1765532f4c7b5d3e81) OCCT has removed access to `Poly_Triangulation::nodes` which is used in `RenderingHelpersOpenGL`

**To Reproduce**
Update Conda env
Build

**Additional context**
It looks like they've replace this with `NbNodes` instead, so we need to investigate what differences there are too

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**
As of this commit https://github.com/Open-Cascade-SAS/OCCT/commit/a8b605eb5e7f181c7bed7c7ef89108c4fd7ba054 access to the internal
array of pointers underlying the triangle nodes has been removed. Instead we need to ask for the number of nodes (which we already
do) then simply call a getter for that index. This simplifies code on our side too.

There's a place where we are manually doing the normal of the triangles. Whilst the framework has a method built in, I'm not
comfortable changing this. Long-term we're going to have to migrate from OpenGL anyway on OSX so....

**To test:**
- Update Conda env to use latest Mantid Developer OSX: `conda env update --file mantid-developer-osx.yml --prune`
- Ensure OCCT is 7.6.0 in conda env: `conda list occt`
- Build and check OpenGL rendering in Instrument View still works

Fixes #32927 

*This does not require release notes* because it's internal API breakage

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DanielMurphy22 — CHANGES_REQUESTED** [review]
InstrumentViewer seems to work but I'm worried that the conda build is slower for the most important use of OpenCascade in Mantid -> The Mesh sample shape plotting! I'm using the [CSGObject Sample shape plotting](https://docs.mantidproject.org/nightly/plotting/MeshPlotHelp.html#csgobject) example, in which SetSample takes 0.55 seconds on my old non-conda build and 3.9 seconds on this new conda build! I am struggling creating 2 release builds on my Mac (one conda, one not) to check this is a fair comparison, so I'd be interested if you can check your 2 builds to see if you get this slow down?

Screenshot 2021-11-10 at 16 05 07
Screenshot 2021-11-10 at 16 08 51

**Comment by DavidFair** [comment]
:+1: I'll try with OCCT 7.5.0 and 7.6.0 to determine if this is due to changes in the latest version or something between our dependency versions and the recent one...

**Review by DanielMurphy22 — APPROVED** [review]
I've built in release with and without conda and there is now no speed difference! Code looks good to me, but I had to google Compat shim!

**Comment by DavidFair** [comment]
So testing locally they were both ~0.26s with 0.7.5 and 0.7.6
In debug mode the overhead is definitely a touch larger, but still within ~3s so it looks like the optimiser clears the overhead of having to index in each time

**Pull request merged**
