### PR TITLE
Masked bins flag needs checking after cropping

### LINKED ISSUE #33556: MaskBins/Crop/Rebin sequence not behaving as expected
**Describe the bug**
A user has reported that after cropping out all masked bins, rebin crashes.
When CropWorkspace is used to crop off all masked bins in a workspace, it still shows hasMaskedBins==True and an empty
list in maskedBinsIndices. And Rebin does not like that.

**To Reproduce**
```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

ws = CreateSampleWorkspace(NumBanks=1,BankPixelWidth=1)
wsmasked = MaskBins(ws, 0, 1000)

print(wsmasked.hasMaskedBins(0))
print(wsmasked.maskedBinsIndices(0))

wscropped = CropWorkspace(wsmasked, XMin=1100)

print(wscropped.hasMaskedBins(0))
print(wscropped.maskedBinsIndices(0))

# Executing this will block!
test = Rebin(wscropped, Params=1000)
```

### PR DESCRIPTION
**Pull request by darominski**
**Description of work.**

This PR implements a proposed fix to the issue related to masked bins flag never being reset, even if masked bins were cropped away from the workspace. A new function of the `MatrixWorkspace`, `setUnmaskedIndex`, allows removing a key related to a workspace index one wants to 'unflag' as masked. The issue with cropping out the masked bins is fixed by better controlling propagation of the mask flags: they are assigned only if the length of the list of remaining masked bins in a particular spectrum is non-zero, otherwise, the masked flag is removed.  

**To test:**
1. Run the example from the linked issue:

```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

ws = CreateSampleWorkspace(NumBanks=1,BankPixelWidth=1)
wsmasked = MaskBins(ws, 0, 1000)

print(wsmasked.hasMaskedBins(0))
print(wsmasked.maskedBinsIndices(0))

wscropped = CropWorkspace(wsmasked, XMin=1100)

print(wscropped.hasMaskedBins(0))
try:
    print(wscropped.maskedBinsIndices(0)) 
except RuntimeError:
    print("No masked bin indices in the cropped workspace.")

# Executing this will no longer block
test = Rebin(wscropped, Params=1000)
```

2. The has masked bins flag for the cropped workspace should return false, and thus a `RuntimeError` should be raised when calling `maskedBinsIndices(workspace_index)`.
3. Rebinning should execute without an issue.

Fixes #33556 . 

Release note added.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gui-co** [comment]
The provided script is working properly.

But I am wondering if it would not be better to transfer `checkMaskedBins()` function to "ExtractSpectra" algorithm. This Alogithm does the actual work on the workspace and if you use it instead of "CropWorkspace" you end up with the same error as described in the issue.

```python
from mantid.simpleapi import *

ws = CreateSampleWorkspace(NumBanks=1,BankPixelWidth=1)
wsmasked = MaskBins(ws, 0, 1000)

print(wsmasked.hasMaskedBins(0))
print(wsmasked.maskedBinsIndices(0))

wsextract = ExtractSpectra(wsmasked, XMin=1100)

print(wsextract.hasMaskedBins(0))
try:
    print(wsextract.maskedBinsIndices(0)) 
except RuntimeError:
    print("No masked bin indices in the cropped workspace.")

test = Rebin(wsextract, Params=1000)
```

**Comment by darominski** [comment]
> The provided script is working properly.
> 
> But I am wondering if it would not be better to transfer `checkMaskedBins()` function to "ExtractSpectra" algorithm. This Alogithm does the actual work on the workspace and if you use it instead of "CropWorkspace" you end up with the same error as described in the issue.
> 
> ```python
> from mantid.simpleapi import *
> 
> ws = CreateSampleWorkspace(NumBanks=1,BankPixelWidth=1)
> wsmasked = MaskBins(ws, 0, 1000)
> 
> print(wsmasked.hasMaskedBins(0))
> print(wsmasked.maskedBinsIndices(0))
> 
> wsextract = ExtractSpectra(wsmasked, XMin=1100)
> 
> print(wsextract.hasMaskedBins(0))
> try:
>     print(wsextract.maskedBinsIndices(0)) 
> except RuntimeError:
>     print("No masked bin indices in the cropped workspace.")
> 
> test = Rebin(wsextract, Params=1000)
> ```

Thank you for looking into this. You are absolutely correct, that the issue would still be there if only cropping was modifying. Well spotted. Indeed, the issue could be solved simply but controlling propagation of masking flag in the `ExtractSpectra` algorithm.

**Review by gui-co — DISMISSED** [review]
Thanks for the changes.

**Review by martyngigg — CHANGES_REQUESTED** [review]

**Review by martyngigg — APPROVED** [review]
Thanks for updating that name. This looks good. 👍🏻

**Pull request merged**
