### PR TITLE
AlC documentation update

### PR DESCRIPTION
**Pull request by AnthonyLim23**
**Description of work.**
This updates the ALC docs. I have agreed the wording with Steve.
-->

**To test:**

Build the docs, check it looks ok and that the link works.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by Matt-Cumber — CHANGES_REQUESTED** [review]
This is great and is a nice snippet as to what is going on behind the scenes with the ALC. Is it worth mentioning you can also change the instrument through **file -> settings**, and reach manage user directories through **file -> manage user directories**. Also not sure if this is just me but the help button (little question mark) on the ALC doesn't take me to the ALC docs and instead I get `Missing page - qthelp://org.mantidproject/doc/interfaces/Muon ALC.html`. Looks like an **s** is missing from **docs** maybe?

**Comment by AnthonyLim23** [comment]
You need to build the docs explicitly. It is easier to just use the docs-html target and then find the file in the build directory. 

I think the benefit of only saying one way to do things, is that it makes it simpler and less confusing  for the user.

**Comment by Matt-Cumber** [comment]
> You need to build the docs explicitly. It is easier to just use the docs-html target and then find the file in the build directory.

I have built the docs and all links work etc. But I thought you should be able to still see the help page from this button. 

> I think the benefit of only saying one way to do things, is that it makes it simpler and less confusing for the user.

That's fair enough, if Steve is happy then this is fine

**Comment by AnthonyLim23** [comment]
ah sorry, you will in the package build

**Review by Matt-Cumber — APPROVED** [review]
Changes look good to me 👍

**Pull request merged**
