### PR TITLE
New algorithm LoadDNSEvent

### LINKED ISSUE #22871: Create a loader for DNS PSD event data
Request from DNS instrument scientists: `LoadDNSEvent` algorithm to load the data from the new PSD detector to a Mantid `EventWorkspace`.

The event data are in qmesydaq listmode (binary) format.

@thomueller  will work on it.

### PR DESCRIPTION
**Pull request by JoachimCoenen**
**Description of work.**

This pull request adds the `LoadDNSEvent` algorithm for loading for dns psd event data (mesytec psd listmode data), generated by the new DNS-PSD detector.

**To test:**

TBD

Fixes #22871.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by mganeva** [comment]
@JoachimCoenen's time in our group unfortunately finishes. I will take over the work on this PR as soon I'll be back to the office. For the moment, I put state 'In progress'.

**Comment by NickDraper** [comment]
@mganeva What is the state of this PR?  If you want it to be included in the next release it needs to be ready for test in the next day or so.

**Comment by NickDraper** [comment]
@mganeva It's been 3 months since the last commit to this failing PR.  Might it be worth closing the PR and creating a new one when the code is ready for testing?

**Comment by NickDraper** [comment]
This PR is being closed as it is almost a year old and has not been recently progressed. If it is important to progress this work reopen the PR and prioritise the work.
Otherwise, the underlying branch will be removed at the next cleanup along with the next release unless it is progressed further.

**Pull request closed without merging**
