### PR TITLE
instrument window render tab not available in python

### LINKED ISSUE #13076: InstrumentWindowRenderTab is not available in Python
In the last example of the wiki page that describes the Instrument View Python commands (http://www.mantidproject.org/MantidPlot:_Instrument_View#Python_control), about the instrument tree tab, InstrumentWindowRenderTab.FULL3D is used, but the InstrumentWindowRenderTab class is not available in my command line:
```
In [11]: InstrumentWindowRenderTab
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-44-ca8d5b94e3b3> in <module>()
----> 1 InstrumentWindowRenderTab

NameError: name 'InstrumentWindowRenderTab' is not defined
```
 I can only see InstrumentWindow, InstrumentWindowMaskTab and InstrumentWindowPickTab. It may be that InstrumentWindowRenderTab  is not exposed to Python in current versions or that there is something wrong in the way it is exposed and/or imported. This needs a bit of investigation if you're familiar with python and boost::python.

 This is part of / blocking #11766.

### PR DESCRIPTION
**Pull request by shahrozahmed1**
Fixes #13076

Enabled `InstrumentWindowRenderTab` and its attributes by creating a new class called `InstrumentWindowTypes.h` which shall allow `InstrumentWindowTab` to make its attributes public just with `InstrumentWindowRenderTab`

To Test: whether `InstrumentWindowRenderTab` and it's attributes e.g: `InstrumentWindowRenderTab.FULL3D` are functioning

### CODE REVIEW

**Comment by DanNixon** [comment]
Can you clang-format `InstrumentWindowTypes.h`.

**Comment by FedeMPouzols** [comment]
@shahrozahmed1 : did you include/push all your local changes in this branch? I saw this was working on your machine, but in my build I cannot see `InstrumentWindowRenderTab`. I still get a `NameError: name 'InstrumentWindowRenderTab' is not defined`.

**Comment by DanNixon** [comment]
It may be worth adding some more [test](https://github.com/mantidproject/mantid/blob/master/Code/Mantid/MantidPlot/test/MantidPlotInstrumentViewTest.py) cases.

**Comment by FedeMPouzols** [comment]
This is now working well and there's a new test with a few commands on `RenterTab` which will hopefully help prevent this sort of issues in the future. There's still the issue that some of the set methods of the instrument window and tabs do not seem to have the effect that they should (like `setSurfaceType`) but that's part of the other related github/issues.

**Comment by FedeMPouzols** [comment]
@shahrozahmed1 : I forgot to mention, when this and the other `InstrumentWindow` python issues are fixed (if the others can be fixed) there should be a line or two about the bug fixes in the relates notes.

**Pull request merged**
