### PR TITLE
Diamond attenuation script

### PR DESCRIPTION
**Pull request by peterfpeterson**
This is a python port of Malcom Guthrie's diamond attenuation code done by Cip Pruteanu. It doesn't currently use mantid, but needs to be in the repository before that refactoring can be done. This PR is a starting point for this functionality.

**To test:**

The peaks file [peaks.txt](https://github.com/mantidproject/mantid/files/652112/peaks.txt) should be used to generate the two UB matrices [snap13108UB2.txt](https://github.com/mantidproject/mantid/files/652115/snap13108UB2.txt) (extension should be `.dat`) and [snap13108UB1.txt](https://github.com/mantidproject/mantid/files/652114/snap13108UB1.txt) (extension should be `.dat`). Run using `mantidpython scripts/DiamondAttenuationCorrection/FitTrans.py`. The script is interactive.

*There is no associated issue*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by peterfpeterson** [comment]
@CipPruteanu Please attach an example peaks file to this PR to aid in testing.

**Comment by martyngigg** [comment]
Should these go inside the `Diffraction` directory?

**Comment by peterfpeterson** [comment]
I don't think so since it is at a similar level to `scripts/Engineering` and `scripts/PearlPowderISIS`.

**Comment by martyngigg** [comment]
LGTM :shipit:

**Pull request merged**
