### PR TITLE
Refs #11035. Remove CurveFitting dependency from SINQ

### PR DESCRIPTION
**Pull request by MichaelWedel**
In ticket #10774 the POLDI constant background function was changed to inherit from CurveFitting::FlatBackground. This causes problems on Mac OS, so I'm going to revert this dependency.

### CODE REVIEW

**Comment by MichaelWedel** [comment]
**Testing information**
Since this seems to be a Mac-problem, it would be best if someone on that system tested this ticket. A good test is running the system tests, which failed before, but should work with the dependency removed.

**Comment by martyngigg** [comment]
I am a little confused as to why the pull request shows so many commits to be merged. When I try locally it only merges one commit, which is what I expect. I am building a package to test the changes but I'm pretty sure they will be okay as the dependency has been removed at the CMake level.

**Comment by MichaelWedel** [comment]
This might have something todo with master accidentally being force-pushed yesterday and the following repair-works. Should I just merge master into the branch again?

**Comment by martyngigg** [comment]
Yes I think you are right, I hadn't seen the slack messages. You don't need to merge master, the reset has taken it back to where it should be and all of the other commits mentioned here are already on master so merging this branch will actually only merge your changes.

The system tests look good now so I think this is okay.

**Pull request merged**
