### PR TITLE
Remove Unused Original Engineering Diffraction GUI Code

### LINKED ISSUE #28092: Remove Old Engineering Diffraction GUI Code
The interface is no longer used and is hidden for the release of mantid 5.0. 

The remaining code should be removed to tidy up the codebase.

### PR DESCRIPTION
**Pull request by cailafinn**
**Description of work.**
The old Engineering Diffraction GUI is no longer in use by the scientists and has been hidden from the list of interfaces in the release of Mantid 5.0. This PR removes that dead code.

**To test:**
1. Do some general checks on the new GUI to make sure nothing important was removed. 
    i. Calibration numbers are 307521 and 305738
   ii. Focusing number is 305761

Fixes #28092

*This does not require release notes* because **the GUI has already been removed from the list of interfaces.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — DISMISSED** [review]
Good to get rid of stuff we know longer use :+1:

**Comment by martyngigg** [comment]
The failing test has shown we have something that slipped through and broke the docs build on RHEL7. It is unrelated to these changes.

**Comment by NickDraper** [comment]
@ConorMFinn There are some conflicts here that need your attention

**Review by martyngigg — APPROVED** [review]

**Comment by martyngigg** [comment]
The removal of the Python 2 job from leeroy means "RHEL7 Python 2" is now obselete and should be ignored.

**Pull request merged**
