### PR TITLE
User feedback fixes to PolDiffILLReduction

### LINKED ISSUE #30863: User feedback to PolDiffILLReduction technique
Following the user feedback certain modifications to the `PolDiffILLReduction` and `D7AbsoluteCrossSections` algorithms and to the relevant documentation of the technique are needed:

- [x] Instrument calibration coming from YIG calibration is not specified in the examples of the `PolDiffILLReduction` nor the `PolarizedILLDiffraction` technique documentation
- [x] Sample height, beam height and beam width are not parameters commonly known: their value should be fixed so it does not impact attenuation calculation, if possible.
- [x] The density choice between number density and mass density is not clear enough.
- [x] The unit for Y-axis of polarization correction is incorrect
- [x] Flipping ratio plots should be made available for instrument scientist, along with polarization correction value
- [x] The algorithm crashes when processing vanadium in `PolDiffILLReduction` with the property `OutputTreatment` set to 'Average'
- [x] Add option to turn off the normalisation for diagnostic purposes
- [x] `D7AbsoluteCrossSections` does not provide expected results when either 'Sum' or 'Average' are specified for the `OutputTreatment` property
- [x] There is an issue in calculating cross-sections of magnetic samples: the magnetic component cross-section looks inverted, which leads to issues in incoherent scattering cross-section.
- [x] Check the error propagation throughout the algorithm.

### PR DESCRIPTION
**Pull request by darominski**
This PR addresses the issues and feature requests from D7 users:

- [x] Instrument calibration coming from YIG calibration is not specified in the examples of the PolDiffILLReduction nor the PolarizedILLDiffraction technique documentation
- [x] Sample height, beam height and beam width are not commonly known parameters: their value should be fixed so it does not impact attenuation calculation, if possible.
- [x] The density choice between number density and mass density is not clear enough.
- [x] The unit for Y-axis of polarization correction is incorrect
- [x]  Flipping ratio plots should be made available for instrument scientists, along with polarization correction value
- [x]  The algorithm crashes when processing vanadium in PolDiffILLReduction with the property OutputTreatment set to 'Average'
- [x]  Add option to turn off the normalisation for diagnostic purposes
- [x] D7AbsoluteCrossSections does not provide expected results when either 'Sum' or 'Average' are specified for the OutputTreatment property
- [x]  There is an issue in calculating cross-sections of magnetic samples: the magnetic component cross-section looks inverted, which leads to issues in incoherent scattering cross-section.
- [x]  Check the error propagation throughout the algorithm.
- [x]  Replace `PolDiffILLReduction` property names for 'Container' and 'Absorber' with 'Empty' and 'Cadmium'
- [x]  Replace 'Sum' with 'Merge' as one of the acceptable values for `OutputTreatment` property in `D7AbsoluteCrossSections` 

Other changes include a workflow modification around reducing vanadium data. One change includes not inverting vanadium in the `PolDiffILLReduction`, and doing so only before vanadium is used to put data on absolute scale in `D7AbsoluteCrossSections`. The other modification involves the relative normalisation that is now done using vanadium data rather than the sample itself.

**To test:**

Using D7 data available from the unit test suite, run the following example:

```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

vanadium_dictionary = {'SampleMass':8.54,'FormulaUnits':1,'FormulaUnitMass':50.94,
                       'SampleChemicalFormula':'V', 'Height':2.0,'SampleDensity':0.2,
                     'SampleInnerRadius':2.0, 'SampleOuterRadius':2.49,'BeamWidth':2.5,'BeamHeight':2.5,
                     'ContainerChemicalFormula':'Al','ContainerDensity':0.0027,'ContainerOuterRadius':2.52,
                     'ContainerInnerRadius':1.99, 'ElementSize':0.5}

sample_dictionary = {'SampleMass':2.932,'FormulaUnits':1,'FormulaUnitMass':182.56,
                     'SampleChemicalFormula':'Mn0.5-Fe0.5-P-S3','Height':2.0,'SampleDensity':0.118,
                     'SampleInnerRadius':2.0, 'SampleOuterRadius':2.49,'BeamWidth':2.5,'BeamHeight':2.5,
                     'ContainerChemicalFormula':'Al','ContainerDensity':0.0027,'ContainerOuterRadius':2.52,
                     'ContainerInnerRadius':1.99, 'ElementSize':0.5}


# Beam with cadmium absorber, used for transmission
PolDiffILLReduction(
    Run='396991',
    OutputWorkspace='cadmium_transmission_ws',
    ProcessAs='BeamWithCadmium'
)
# Beam measurement for transmisison
PolDiffILLReduction(
    Run='396983',
    OutputWorkspace='beam_ws',
    CadmiumTransmissionInputWorkspace='cadmium_transmission_ws_1',
    ProcessAs='EmptyBeam'
)

# Quartz transmission
PolDiffILLReduction(
    Run='396985, 396986',
    OutputWorkspace='quartz_transmission',
    CadmiumTransmissionInputWorkspace='cadmium_transmission_ws_1',
    BeamInputWorkspace='beam_ws_1',
    ProcessAs='Transmission'
)

# Empty container
PolDiffILLReduction(
    Run='396917, 396918',
    OutputWorkspace='container_ws',
    ProcessAs='Empty'
)

# Absorber
PolDiffILLReduction(
    Run='396928, 396929',
    OutputWorkspace='absorber_ws',
    ProcessAs='Cadmium'
)

# Polarisation correction
PolDiffILLReduction(
    Run='396939, 396940',
    OutputWorkspace='pol_corrections',
    CadmiumInputWorkspace='absorber_ws',
    EmptyInputWorkspace='container_ws',
    TransmissionInputWorkspace='quartz_transmission_1',
    OutputTreatment='Average',
    ProcessAs='Quartz'
)

# Vanadium transmission
PolDiffILLReduction(
    Run='396990',
    OutputWorkspace='vanadium_transmission',
    CadmiumTransmissionInputWorkspace='cadmium_transmission_ws_1',
    BeamInputWorkspace='beam_ws_1',
    ProcessAs='Transmission'
)

# Vanadium reduction
PolDiffILLReduction(
    Run='396993, 396994',
    OutputWorkspace='vanadium_ws',
    CadmiumInputWorkspace='absorber_ws',
    EmptyInputWorkspace='container_ws',
    TransmissionInputWorkspace='vanadium_transmission_1',
    QuartzInputWorkspace='pol_corrections',
    OutputTreatment='Sum',
    SampleGeometry='Annulus',
    SelfAttenuationMethod='Numerical',
    SampleAndEnvironmentProperties=vanadium_dictionary,
    ProcessAs='Vanadium'
)
# Sample transmission
PolDiffILLReduction(
   Run='396986, 396987',
   OutputWorkspace='sample_transmission',
   CadmiumTransmissionInputWorkspace='cadmium_transmission_ws_1',
   BeamInputWorkspace='beam_ws_1',
   ProcessAs='Transmission'
)
print('Sample transmission is {0:.3f}'.format(mtd['sample_transmission_1'].readY(0)[0]))

# Sample reduction
PolDiffILLReduction(
    Run='397004, 397005',
    OutputWorkspace='sample_ws',
    CadmiumInputWorkspace='absorber_ws',
    EmptyInputWorkspace='container_ws',
    TransmissionInputWorkspace='sample_transmission_1',
    QuartzInputWorkspace='pol_corrections',
    SelfAttenuationMethod='Numerical',
    OutputTreatment='Individual',
    SampleGeometry='Annulus',
    SampleAndEnvironmentProperties=sample_dictionary,
    ProcessAs='Sample'
)
print("The reduced sample data contains {} entries with {} spectra and {} bins.".format(mtd['sample_ws'].getNumberOfEntries(),
          mtd['sample_ws'][0].getNumberHistograms(), mtd['sample_ws'][0].blocksize()))

# Normalise sample data
D7AbsoluteCrossSections(
    InputWorkspace='sample_ws',
    OutputWorkspace='sample_norm',
    CrossSectionSeparationMethod='XYZ',
    NormalisationMethod='Vanadium',
    VanadiumInputWorkspace='vanadium_ws',
    OutputTreatment='Merge',
    OutputUnits='TwoTheta',
    ScatteringAngleBinSize=1.0, # degrees
    SampleAndEnvironmentProperties=sample_dictionary,
    AbsoluteUnitsNormalisation=False
)

print("The normalised sample data contains {} entries with {} spectra and {} bins.".format(mtd['sample_norm'].getNumberOfEntries(),
          mtd['sample_norm'][0].getNumberHistograms(), mtd['sample_norm'][0].blocksize()))

```

There should be no issues, also when:
1. `NormalisationMethod` is changed to 'None', or 'Paramagnetic' or 'Incoherent', in the two latter case, the Y-axis unit should be 'normalised intensity'
2. `OutputTreatment` is changed to 'Individual'
3. `OutputUnits` are changed to 'TwoTheta'.

The flipping ratios should be present in the ADS.

Fixes #30863. 

Release notes added.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by StephenSmith25** [comment]
Is it intended for this PR to make it into the 6.1 release?

**Comment by gvardany** [comment]
Yes, just pending my review.

**Review by gvardany — COMMENTED** [review]
Code-wise looks ok. I couldn't run though the script in the description, is fails quite early on, can you fix that? Also I see you added one more system test, is it enough for all these changes that you introduced? For the beam height and width, what's the fixed value?

**Comment by darominski** [comment]
> Code-wise looks ok. I couldn't run though the script in the description, is fails quite early on, can you fix that? Also I see you added one more system test, is it enough for all these changes that you introduced? For the beam height and width, what's the fixed value?

Absolutely, the very first call had an incorrect `OutputWorkspace` name, changed to the correct one (`cadmium_transmission_ws`), and everything should run properly.

**Comment by gvardany** [comment]
There are few more issues:
- there are dangling tmp workspaces, enable show invisible workspaces and run up to the sample reduction included
- the intensity values are order of 10^13 in absolute units, this doesn't make sense to me at all
- the sample reduction progress gets stuck in the middle for a few seconds, I guess it's the attenuation calculation, but perhaps the progress can be better split. It is not easy however to guess how long attenuation will take, since it depends on the settings.

**Comment by darominski** [comment]
> There are few more issues:
> 
>     * there are dangling tmp workspaces, enable show invisible workspaces and run up to the sample reduction included
> 
>     * the intensity values are order of 10^13 in absolute units, this doesn't make sense to me at all
> 
>     * the sample reduction progress gets stuck in the middle for a few seconds, I guess it's the attenuation calculation, but perhaps the progress can be better split. It is not easy however to guess how long attenuation will take, since it depends on the settings.

ad 1. I cannot seem to be able to reproduce this issue, there are no temporary unintended workspaces coming from Python operations as far as I can see, and I've run the example script step-by-step, and all at once until the specified point, yet still these were not shown. I do have the switch turned on for showing hidden workspaces. Could you tell me which call creates them in your case?

ad 2. Naturally, numbers that high were critically flawed. This was caused by two factors: way too large number densities in the example, and not optimal way matching attenuation workspace to the sample workspace. This has been corrected and results are much more reasonable, yet we still should validate them with D7 scientists at some point.

ad 3. This may be a small issue but indeed it's unclear what percentage to assign here. As you correctly mentioned, the execution could be either very quick in case of user-provided attenuation workspaces, or extremely long for high-granularity numerical integration or many-event MC simulations. I would propose to revisit this when we have more feedback on this feature from D7 scientists on how they prefer (or not) to use this option.

**Review by gvardany — APPROVED** [review]
OK, I'm happy with explanations, the intermediate workspaces are gone, probably this was related to wrong handling of ClearCache property value. Let's get this into the scientists hands.

**Pull request merged**
