### PR TITLE
Multi plot canvas bug and fixes Muon grouping tab test

### LINKED ISSUE #26291: Elemental Analysis "FigureCanvasQTAgg has been deleted"
### Expected behavior
Opening the GUI a second time opens the plots again.

### Actual behavior
1. Open "Elemental Analysis"
2. Load 2695
3. Click GE1 or any of the others
4. Close the whole window
5. Open and load again
6. This should show up:
```
wrapped C/C++ object of type FigureCanvasQTAgg has been deleted
 at line 38 in '/home/dtasev/dev/m/scripts/MultiPlotting/subplot/subplot_ADS_observer.py'
 caused by line 274 in '/home/dtasev/dev/m/scripts/MultiPlotting/subplot/subplot.py'
 caused by line 127 in '/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5agg.py'
 caused by line 433 in '/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_agg.py'
 caused by line 702 in '/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5.py'
```

### PR DESCRIPTION
**Pull request by AnthonyLim23**
~~**MERGED AFTER #26289**~~

**Description of work.**
The multiple plotting window would throw an error after being closed and reopened. This fixes it. 
The problem was due to the ADS observer sticking around. 

**To test:**

Open Interface->Muon->Elemental Analysis
Load 2695
Click GE1 or any of the others
Close the whole window
Open and load again
No error should appear

Fixes #26291. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by dtasev — DISMISSED** [review]
Fixes the crash. To be merged after #26289. Failed tests are unrelated

**Comment by AnthonyLim23** [comment]
@Mantid-Matthew have you seen the python3 failure before? It looks like it has something to do with the ADS observer in the muon GUI

**Comment by Mantid-Matthew** [comment]
I think that will fix the crash here as the phase context should then correctly exist.

**Comment by DTasev** [comment]
86fd60d09500c8b5a41375e8c2ee888313b0f186 onwards seem completely unrelated to this PR why are they apart of it? Are they actually related to the changes for Multi plot canvas? If not I'd rather move them to a separate PR so this can get through.

**Comment by AnthonyLim23** [comment]
the changes are not related, however the failing test should not pass in the first place. So I thought it would be best to fix it now, as it was easy. Then we should see less failures elsewhere

**Comment by AnthonyLim23** [comment]
unrelated failures

**Review by dtasev — APPROVED** [review]
Multi plot canvas bug is fixed, and the Muon test doesn't seem to fail anymore

**Pull request merged**
