### PR TITLE
Update mantid-developer.spec

### PR DESCRIPTION
**Pull request by stuartcampbell**
Updated our dependencies to use the upstream `python-sphinx-bootstrap-theme`

**To test:**
Nothing to really test.  Check that the developer rpm builds.

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — COMMENTED** [review]
@stuartcampbell Does this require a the version to be bumped up?

**Comment by stuartcampbell** [comment]
Not sure, the version I've got into fedora is newer than the one we had in copr.  But I don't think its needed.

**Comment by martyngigg** [comment]
Sorry, I meant for the `.spec` file. I'm not sure what the protocol is.

**Comment by stuartcampbell** [comment]
Sorry - yes of course it should.  Done it.

**Review by martyngigg — APPROVED** [review]
Good to go

:shipit:

**Comment by peterfpeterson** [comment]
I just kicked this off on [copr](https://copr.fedorainfracloud.org/coprs/mantid/mantid/build/515633/).

**Comment by stuartcampbell** [comment]
Shouldn't be needed on copr for any of the rhel or fedoras as this is now in the main fedora or epel repos.

**Pull request merged**
