### PR TITLE
Convert Group 14 from Python 2 to Python 3

### PR DESCRIPTION
**Pull request by peterfpeterson**
This PR deals with the Python2 to Python3 conversion of things in `scripts/HFIR_4Circle_Reduction/` towards #18550.

**To test:**

Code review
Go to Interfaces -> Diffraction -> HFIR 4Circle Reduction
Confirm that there are no import or general errors when opening the interfaces
Play around with the interfaces (no data needed)
Confirm that there are no Python related errors
Does not need to be in the release notes.
Description of work.

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by wdzhou — CHANGES_REQUESTED** [review]
There is an error to launch HFIR 4-circle UI
caused by line 18 in '/home/wzz/Mantid_Project/Mantid-Master/scripts/HFIR_4Circle_Reduction/reduce4circleGUI.py'
caused by line 6 in '/home/wzz/Mantid_Project/Mantid-Master/scripts/HFIR_4Circle_Reduction/peakprocesshelper.py'
caused by line 5 in '/home/wzz/Mantid_Project/Mantid-Master/scripts/HFIR_4Circle_Reduction/fourcircle_utility.py'

**Comment by wdzhou** [comment]
from urllib2.error import URLError
shall be replaced by
from urllib2 import URLError

**Review by wdzhou — APPROVED** [review]

**Comment by wdzhou** [comment]
:shipit:

**Review by AndreiSavici — CHANGES_REQUESTED** [review]
Several files do not have the `from __future__ import...` statement

**Review by AndreiSavici — APPROVED** [review]

**Pull request merged**
