### PR TITLE
Improve IMAT IDF

### LINKED ISSUE #20141: Improve IMAT IDF
The latest IMAT IDF was found to have wrong pixel shape. While that has not caused any bad data, the pixel definition is done by a script. It should be better to use a RectangularDetector.

### PR DESCRIPTION
**Pull request by dtasev**
Description of work.

The IDF used to have the pixels generated by a script. It has now been rewritten to use `RectangularDetector` definition, simplifying the IDF. 

Additionally the banks have been reoriented, and now produce higher and clearer peaks. This change has been verified with an IMAT scientist to produce better data than the last IDF.

**To test:**
- Review the IDF.
- Try `LoadEmptyInstrument` with the IDF.

Fixes #20141. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DavidFair** [comment]
@DTasev You have a merge conflict on the IDF?

**Review by DavidFair — APPROVED** [review]
This tidies up the IDF and the peaks from focussing data have a higher intensity as it rectifies the bank orientation

**Review by peterfpeterson — CHANGES_REQUESTED** [review]
IDF changes need to be in the release notes

**Comment by DTasev** [comment]
I don't have push permissions to the repository anymore, this is a patch to add the release note:

- [File](https://gist.github.com/DTasev/0dbc4613ef381a17dc3648ac5dc54d49)
or raw

```
diff --git a/docs/source/release/v3.11.0/diffraction.rst b/docs/source/release/v3.11.0/diffraction.rst
index 4cbe7c6653..eca0a67ada 100644
--- a/docs/source/release/v3.11.0/diffraction.rst
+++ b/docs/source/release/v3.11.0/diffraction.rst
@@ -32,13 +32,6 @@ Single Crystal Diffraction
 - New algorithm :ref:`ConvertMultipleRunsToSingleCrystalMD <algm-ConvertMultipleRunsToSingleCrystalMD>` which loads, converts to single crystal MDWorkspace and combines a series of runs.
 - :ref:`FindPeaksMD <algm-FindPeaksMD>` has been modified to only add peaks to runs that contributed to that peak. This is a lot faster when multiple runs are in the same MDworkspace.

-
-Imaging
--------
-
-- The IMAT IDF has been improved to more accurately represent the instrument.
-
-
 Full list of `diffraction <http://github.com/mantidproject/mantid/pulls?q=is%3Apr+milestone%3A%22Release+3.11%22+is%3Amerged+label%3A%22Component%3A+Diffraction%22>`_
 and
 `imaging <http://github.com/mantidproject/mantid/pulls?q=is%3Apr+milestone%3A%22Release+3.11%22+is%3Amerged+label%3A%22Component%3A+Imaging%22>`_ changes on GitHub.

```

**Review by peterfpeterson — APPROVED** [review]

**Pull request merged**
