### PR TITLE
Ensure HKL labels within instrument view miniplot remain visble when zooming

### LINKED ISSUE #32084: Re-plot HKL index of peaks in plot widget of instrument viewer when zoom level changed
**Describe the bug**
In instrument viewer peak table can be overlaid and by picking the detector of the peak or a region of interest  (pick tab -> e.g. circle) the peak position would be indicated by the HKL in the plot widget which displayed the summed spectra in that ROI.
When you zoomed the index would be re-plotted so it was always visible.

image

**To Reproduce**
(1) In workbench load some data 
`Load(Filename='SXD23767.raw', OutputWorkspace='SXD23767')`

(2) Add a peak (Pick tab -> pick peak (see icon below) -> click on a detector -> click on position of peak in spectrum in plot widget)
image

(3) Select a ROI that includes peak (pick tab -> circle)
image

(4) Zoom in on plot over a y range that doesn't include the HKL - in this case 000. It will no longer be visible

image

**Expected behavior**
As on mantid plot
image

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

See commit message details for more detail than the title suggests.

A commit is included that removes the old Qt4-based code.

**To test:**

* See the instructions in the linked issue and ensure the label remains visible as the
   zoom level changes

Fixes #32084

*This does not require release notes* because **fill in an explanation of why**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by RichardWaiteSTFC — COMMENTED** [review]
Done some functional testing and it's much better!
Still a few issues though, I wonder if the labels are interfering with the autoscaling of the axes extent/tight_layout? The labels can be seen outside the plot area and the width of the plot shrinks when zooming in on a peak.
image
Also i think an unrelated bug but instrument view appears to plot all spectra and subsequently adds all peak labels when you draw a ROI then delete it (or when you click on the magnifying glass on the pick tab - probably other things too would cause this)
image

**Comment by RichardWaiteSTFC** [comment]
Also after using the new rebin function it doesn't seem to replot the peak labels

**Review by RichardWaiteSTFC — APPROVED** [review]
Looks good, the labels outside the xrange are no longer plotted and this has fixed the shrinking plot.

**Comment by martyngigg** [comment]
@mantidproject/gatekeepers Could I get this merged?

**Pull request merged**
