### PR TITLE
Enable loading of 2015 POLDI data

### PR DESCRIPTION
**Pull request by MichaelWedel**
This fixes [#11632](http://trac.mantidproject.org/mantid/ticket/11632).

**Testing information**
A new system test for PoldiLoadRuns has been added (including a new POLDI data file with the new structure) that covers these changes. All other POLDI tests should still work.

### CODE REVIEW

**Comment by MichaelWedel** [comment]
The pylint job reports 13 new problems, but those are in files I did not touch. I suppose that's the "diff" to the last pylint build?

**Comment by MichaelWedel** [comment]
The windows failure seems unrelated, I've scheduled a new build.

**Comment by FedeMPouzols** [comment]
This adds an updated NeXus dictionary, and moves the old one to a 'legacy' dict file. All looks fine, LoadLotsOfFiles now includes one POLDI 2015 file, and the relevant tests passed also locally, so let's merge it in just in time...

I was curious about pylint's pickiness. I found one issue in one of the files involved in this branch (PoldiMerge.py), but in a place that has not changed here:
http://builds.mantidproject.org/job/pull_requests-pylint/35/violations/file/PoldiMerge.py/
That's a place where it might be good to give a specific expected exception type.
I'm amazed. Pylint has an error for 'too few public methods' in a class...

**Comment by MichaelWedel** [comment]
I will make a ticket for the next release to remove all outstanding pylint issues with the POLDI related code. I particularly like these warnings "too few public methods", "too many private methods" (I think there are more, but I don't recall them now), too.

**Pull request merged**
