### PR TITLE
NXcanSas read and write

### LINKED ISSUE #15811: Implement read and writer for NXCansas format
Stephen King requested the implementation for reading and writing NXCansas data. Stephen will provide further information.

>I have been kindly asked to provide an update on the latest development on the canSAS data formats.

> As .... send to this list last year, work happens mostly in this repository on github:
https://github.com/canSAS-org/canSAS2012

> It contains the documentation - which is rendered to http://cansas-org.github.io/canSAS2012/
There are two example files - reduced data in canSAS/HDF5 format, to be found here:
https://github.com/canSAS-org/canSAS2012/tree/master/examples/contributions

>* D2O_100pc.hdf5 (3D reduced data)
>* H2O_100pc.hdf5 (3D reduced data)

>Please has a look and inspect those if you can. We welcome any feedback to this list.

>There is a writer to create the example files in the documentation in that repository.>
For reading this python snippet from some experimental work in NeXus will (with some adaptation) read in a canSAS data file and return a data structure of Numpy arrays that allows transparent addressing and slicing of data and axes:
https://github.com/nexusformat/features/blob/master/src/recipes/D1A00000000
00001/recipe.py

>Related to this: NeXus has pretty much competed the adoption of the canSAS-style axis scheme.

>Feel free to add any other updates about ongoing or completed work.

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Description of work.

This PR implements a loader and a reader for the the NXcanSAS data format. Information regarding this data format can be found [here](http://download.nexusformat.org/sphinx/classes/contributed_definitions/NXcanSAS.html) and [here](http://cansas-org.github.io/NXcanSAS/classes/contributed_definitions/NXcanSAS.html).

Fixes #15811 
## To test:

A windows installer can be found here: \olympic\Babylon5\Scratch\Anton\Testing\NXcanSAS

The sample data can be found here: \olympic\Babylon5\Scratch\Anton\Testing\NXcanSAS\BenchMarkingSANS2D_D20

**Test saving 2D**
- Open the ISIS SANS GUI
- Set the instrument to SANS2DTUBES
- Load the user file: USER_SANS2D_154E_2p4_4m_M3_Xpress_8mm_SampleChanger.txt
- Set the input files as:

| type | Scatter | Transmission | Direct |
| --- | --- | --- | --- |
| sample | SANS2D00034484 | SANS2D00034505 | SANS2D00034461 |
| can | SANS2D00034481 | SANS2D00034502 | SANS2D00034461 |
- Press load
- Press 2D reduction

You should see an output workspace with the name: 34484rear_2D_1.75_16.5
- Open the algorithm `SaveNXcanSAS`
- Set the workspace 34484rear_2D_1.75_16.5 as the input workspace and set a file name
- Run the algorithm
  - Confirm that the file was created
  - Use HDFViewer to open the file and confirm that it can be opened
- Open the algorithm `LoadNXcanSAS`
- Set the file name to the file that was just saved
- Set the name of the output workspace to _InWS_from_NXCanSAS_
- Run the alogorithm
  - Confirm that the workspace has been loaded

Now we want to compare the workspaces. Note that 34484rear_2D_1.75_16.5 is a histogram worksapce whilie the freshly loaded workspace will be point data. 
- Apply ConvertToHistogram to 34484rear_2D_1.75_16.5 and set the output workspace name to `ReferenceWS`
- Compare the data of `ReferenceWS` and `nWS_from_NXCanSAS`
  - Confirm that the Y values are the same (compare them roughly)
  - Confirmt that the X values are the same
  - Confirm that the number of entries on what is normally the spectrum axis is the same
  - Open the SampleLog and confirm that entries for `UserFile`, `run_number` and `run_title` exist

**Test saving 1D**
1. Follow the same steps as above but press `1D Reduce` instead. You should have a 1D workspace called 34484rear_2D_1.75_16.5
2. Follow the same save and load procedure as for the 2D workspace.

**Test saving 1D with transmission workspaces**
1. Follow the same steps as above but press `1D Reduce` instead. You should have a 1D workspace called 34484rear_2D_1.75_16.5 and two transmission workspaces. Add them to the save option (one for can and one for the sample). 
2. Follow the same steps as above but enable, "Load Transmissions"

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by MattKing06** [comment]
For 2D Data the comparison for X and Y data was successful with a tolerance of 1e-06 which is fine, however I'm concerned that the 1D comparison was only successful with a tolerance of 1e-03 and with the 1D transmission workspaces case I needed a tolerance of 1e-02 for the comparison to be successful. Other than that the functional loading and saving of the workspaces was fine and they were viewable in HDF5View and could be loaded into Mantid using LoadNXCanSAS manually or the Load algorithm would choose LoadNXCanSAS. Let me know if this needs testing again due to the tolerance issues.

**Comment by AntonPiccardoSelg** [comment]
@MattKing06 

I compared the 1D data which we get directly from the reduction and the reloaded data. On my machine, they seem to match nicely.  The values are saved as they are, i.e. they are passed to H5Cpp without any alterations.

**Comment by MattKing06** [comment]
The problem mentioned previously was to do with the fact the datasets were using logarithmic binning. After converting the produced histogram to point data and then running the comparison with the saved file the workspaces matched successfully. 

:shipit:

**Comment by FedeMPouzols** [comment]
This comes with excellent tests. I was curious to check their run times as the tests are very exhaustive and this is a pair of `DataHandling` algorithms. The save and load tests took 4.80 and 3.90s in the ubuntu job, which seems to rank them among the top "slow" unit tests in `DataHandling`. I'd definitely prefer this than having less tests, but if possible some tests could be moved to system tests later on. We have several other slow tests anyway.

**Pull request merged**
