### PR TITLE
Project Recovery - Offer to recover if Mantid exited incorrectly

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**
This is the second major PR for project recovery. It adds the following features:
- Remove checkpoints on graceful exit
- Only save, if there is something to save
- Offer to recover a script if a checkpoint folder is found
- Converted `OrderWorkspaceHistory` from a script to a Mantid Alg
- Add option to ScriptBuilder to append timestamps
- Add function to get Mantid start time
- We only save out commands since Mantid start

**Still pending**
- Bug where a race condition occurs if a workspace is renamed or removed whilst project recovery is executing
- Some edge cases when project recovery has completed (do we restart thread)
- Handling the configuration value less than 0
- Opening GUI windows which were previously closed

**To test:**
- Open Mantid generate some workspaces
- Group a  workspace together, to check that duplicate elimination works
- Exit mantid forcefully (kill `PID` for example)
- Check that loading back in correctly asks about project recovery
- Check that both the `Open in script editor` and `No` option clear the recovery checkpoints after they complete
- Check that recovery starts saving again if `No` is selected

------
- Add an error to the `OrderWorkspaceHistory` alg, for example `str("hello") + int (1)`
- Attempt project recovery
- Ensure that the checkpoints are not deleted if it fails
-----------
- Create some sample workspaces and perform some methods on them
- Save the project normally
- Open / Close Mantid
- Load the project normally
- Perform some more commands
- Kill Mantid
- Reload and recover
- Check that only commands in the second instance were saved

Does this update require release notes?
- [x] Yes
- [ ] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by keeeto** [comment]
`SaveNexus` writes a timestamp that does not contain milliseconds. This results in an error in the `OrderWorkspace` algorithm when it is trying to recover. 

* Save algorithms are not required in the recovery mode, it could be possible to simply set up the recovery mode to ignore all Save algorithms.

**Review by keeeto — APPROVED** [review]
Apart from the issue with the issue with `SaveNexus`, which is now a separate issue in the project recovery roadmap #22715 , this passes all of the tests prescribed.

I have also tested this out with a few other scenarios and the recovery mode works well.

**Comment by martyngigg** [comment]
The failing tests are all related to the problems with the reflectometry test that was fixed on master.

**Comment by martyngigg** [comment]
On minor thing I noticed is that `OrderWorkspaceHistory` is missing a unit test. I'm not going to hold up merging this for the release but it would be good to add one in maintenance.

**Comment by martyngigg** [comment]
Just a note to record this: I don't seem see the recovery directories being removed on a clean exit so basically I get the recovery dialog every time. 

This is with Ubuntu 16.04.

**Pull request merged**
