### PR TITLE
Visual display of fit benchmarking results 

### LINKED ISSUE #18173: Provide visual display of fit benchmarking results
Extend the fit benchmarking scripts introduced with #17654 to generate visual display of data from the benchmarking tables. 

Initially suggest limiting this to 1D fit problems and neutron_data fitting problems. Have an .rst file automatic created, where for each 1D fit problem a section is created with contains

* Title of fit problem 
* a plot of the data
* (a plot of the initial starting guess)
* a plot of the solution found
* Python lines of code representing the fit problem before the fit started, and for someone to copy and paste for rerunning

Add link for each fit problem to the problem name.

### PR DESCRIPTION
**Pull request by AnthonyLim23**
The fit benchmark now produces plots of the initial guess and best result along with the raw data. 

**To test:**
Run fit benchmarking and check the plots that are produced correctly (in MantidPlot directory in build).

Fixes #18173. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Anders-Markvardsen** [comment]
I like the plots - high information content:-)

Just also ran it with: problems, results_per_group = fitbk.do_fitting_benchmark(neutron_data_group_dirs=neutron_data_group_dirs,
                                                       minimizers=minimizers, use_errors=use_errors)  

and get error:
ChiSquaredWeightedDividedByNData=3.613769498398606)
*** with minimizer BFGS, Status: iteration is not making progress towards solution, chi2: 0.492937480012
   params: [-2.131326578357653e-06, 7.097766607789367e-05, 597.0759602257853, 0.998221142098683, 0.30050566400283385, 24027.49888351154, 22.909983240694284], errors: [70.84652436919865, 0.0029420192809220154, 86.44423418935342, 639.2875430129517, 65.47327348235147, 86.06823245447431, 93.04491138043895]
   sum sq: 309.25000232
Result object: <test_result.FittingTestResult object at 0x000000002A1852E8>
*** with minimizer Damped GaussNewton, calculated: chi2: CalculateChiSquared_returns(ChiSquared=895016.8520944729, ChiSquaredDividedByDOF=258.15311568920475, ChiSquaredDividedByNData=257.63294533519655, ChiSquaredWeighted=12554.235237436757, ChiSquaredWeightedDividedByDOF=3.6210658313921997, ChiSquaredWeightedDividedByNData=3.613769498398606)
*** with minimizer Damped GaussNewton, Status: success, chi2: nan
   params: [nan, nan, nan, nan, nan, nan, nan], errors: [nan, nan, nan, nan, nan, nan, nan]
   sum sq: nan
Result object: <test_result.FittingTestResult object at 0x000000003173F0F0>
ValueError: x and y must have same first dimension
  at line 48 in 'C:/Backup/Backup_folder1/work/code/Mantid/fitting/FitMinimizerTesting/runScripts.py'
  caused by line 139 in 'C:/Backup/Backup_folder1/work/code/Mantid/git/mantid/scripts/CompareFitMinimizers\fitting_benchmarking.py'
  caused by line 179 in 'C:/Backup/Backup_folder1/work/code/Mantid/git/mantid/scripts/CompareFitMinimizers\fitting_benchmarking.py'
  caused by line 293 in 'C:/Backup/Backup_folder1/work/code/Mantid/git/mantid/scripts/CompareFitMinimizers\fitting_benchmarking.py'
  caused by line 142 in 'C:/Backup/Backup_folder1/work/code/Mantid/git/mantid/scripts/CompareFitMinimizers\plotHelper.py'
  caused by line 3154 in 'C:\Backup\Backup_folder1\work\code\Mantid\git\mantid\external\src\ThirdParty\lib\python2.7\lib\site-packages\matplotlib\pyplot.py'
  caused by line 1812 in 'C:\Backup\Backup_folder1\work\code\Mantid\git\mantid\external\src\ThirdParty\lib\python2.7\lib\site-packages\matplotlib\__init__.py'
  caused by line 1424 in 'C:\Backup\Backup_folder1\work\code\Mantid\git\mantid\external\src\ThirdParty\lib\python2.7\lib\site-packages\matplotlib\axes\_axes.py'
  caused by line 386 in 'C:\Backup\Backup_folder1\work\code\Mantid\git\mantid\external\src\ThirdParty\lib\python2.7\lib\site-packages\matplotlib\axes\_base.py'
  caused by line 364 in 'C:\Backup\Backup_folder1\work\code\Mantid\git\mantid\external\src\ThirdParty\lib\python2.7\lib\site-packages\matplotlib\axes\_base.py'
  caused by line 223 in 'C:\Backup\Backup_folder1\work\code\Mantid\git\mantid\external\src\ThirdParty\lib\python2.7\lib\site-packages\matplotlib\axes\_base.py'

Perhaps something on my side - but do you see anything obvious I do wrong

**Comment by AnthonyLim23** [comment]
The error is on my end. Because the data did not get a fit the x and y values have different length axes. I can add a line into the plot to ensure that the x,y and E arrays are the same length (if not dont plot it).

**Comment by AnthonyLim23** [comment]
I have tracked the bug down to tight_layout. I think the error is something to do with trying to plot nans or infs. I will look into this on Monday

**Comment by AnthonyLim23** [comment]
@Anders-Markvardsen  it should now work

**Comment by Anders-Markvardsen** [comment]
I now get this error message:

unknown line in supposedly NIST test file, ignoring: # An example of (full) detector calibration for the ENGIN-X instrument
unknown line in supposedly NIST test file, ignoring: name = 'ENGINX 193749 calibration, spectrum 651, peak 23'
unknown line in supposedly NIST test file, ignoring: input_file = 'ENGINX193749_calibration_spec651.nxs'
unknown line in supposedly NIST test file, ignoring: function = 'name=LinearBackground;name=BackToBackExponential,I=26061.4,A=1,B=0.05,X0=37027.1,S=38.7105'
unknown line in supposedly NIST test file, ignoring: fit_parameters = {'StartX': 36844.7449265, 'EndX': 37300.5256846}
unknown line in supposedly NIST test file, ignoring: description = ''
* Testing fitting for problem definition file C:\Backup\Backup_folder1\work\code\Mantid\fitting\FitMinimizerTesting\FittingTestData\Neutron_data\ENGINX193749_calibration_peak23.txt
* Testing fitting of problem ENGINX 193749 calibration, spectrum 651, peak 23
*** with minimizer BFGS, calculated: chi2: CalculateChiSquared_returns(ChiSquared=241944.00307832944, ChiSquaredDividedByDOF=69.78482926978063, ChiSquaredDividedByNData=69.64421504845407, ChiSquaredWeighted=9467.99234985445, ChiSquaredWeightedDividedByDOF=2.73088905389514, ChiSquaredWeightedDividedByNData=2.7253863989218337)
*** with minimizer BFGS, Status: iteration is not making progress towards solution, chi2: 1.92979784475
   params: [8.280464595050015e-07, 7.86532613271447e-05, 26061.39999921229, 0.998357295477235, 0.5424822418129515, 37027.098671700056, 38.71062629973126], errors: [70.26302988604925, 0.0018915057817658584, 470.3822094665766, 863.6971284066205, 257.9547156527425, 10.590727093426855, 59.55694088377018]
   sum sq: 12786.9617587
Result object: <test_result.FittingTestResult object at 0x000000002AB75080>
*** with minimizer Damped GaussNewton, calculated: chi2: CalculateChiSquared_returns(ChiSquared=241944.00307832944, ChiSquaredDividedByDOF=69.78482926978063, ChiSquaredDividedByNData=69.64421504845407, ChiSquaredWeighted=9467.99234985445, ChiSquaredWeightedDividedByDOF=2.73088905389514, ChiSquaredWeightedDividedByNData=2.7253863989218337)
*** with minimizer Damped GaussNewton, Status: success, chi2: nan
   params: [nan, nan, nan, nan, nan, nan, nan], errors: [nan, nan, nan, nan, nan, nan, nan]
   sum sq: nan
Result object: <test_result.FittingTestResult object at 0x000000002AB75DD8>
saving to Fit_for_ENGINX_193749_calibration,_spectrum_651,_pea_1.pdf
saving to start_for_ENGINX_193749_calibration,_spectrum_651,_pea_1.pdf
unknown line in supposedly NIST test file, ignoring: # An example of (full) detector calibration for the ENGIN-X instrument
unknown line in supposedly NIST test file, ignoring: name = 'ENGINX 193749 calibration, spectrum 651, peak 5'
unknown line in supposedly NIST test file, ignoring: input_file = 'ENGINX193749_calibration_spec651.nxs'
unknown line in supposedly NIST test file, ignoring: function = 'name=LinearBackground;name=BackToBackExponential,I=15.1595,A=1,B=0.05,X0=13072.9,S=0.854238'
unknown line in supposedly NIST test file, ignoring: fit_parameters = {'StartX': 12986.356148, 'EndX': 13161.356148}
unknown line in supposedly NIST test file, ignoring: description = ''
* Testing fitting for problem definition file C:\Backup\Backup_folder1\work\code\Mantid\fitting\FitMinimizerTesting\FittingTestData\Neutron_data\ENGINX193749_calibration_peak5.txt
* Testing fitting of problem ENGINX 193749 calibration, spectrum 651, peak 5
*** with minimizer BFGS, calculated: chi2: CalculateChiSquared_returns(ChiSquared=896374.1003100238, ChiSquaredDividedByDOF=258.54459195558803, ChiSquaredDividedByNData=258.02363278929874, ChiSquaredWeighted=12679.696582587236, ChiSquaredWeightedDividedByDOF=3.6572531244843485, ChiSquaredWeightedDividedByNData=3.6498838752410006)
*** with minimizer BFGS, Status: iteration is not making progress towards solution, chi2: 0.0591780139405
   params: [8.064243044686288e-06, 8.756264967713895e-05, 15.15942564442358, 0.9998075039221472, 0.030943465517163735, 13072.900209107567, 0.8538398914161023], errors: [234.1876225048843, 0.017948199973026806, 9045.327041204853, 20199.289158706804, 0.4327892042690981, 45.885374654226595, 7323.405469000947]
   sum sq: 22.9801575094
Result object: <test_result.FittingTestResult object at 0x000000002CD2D780>
*** with minimizer Damped GaussNewton, calculated: chi2: CalculateChiSquared_returns(ChiSquared=896374.1003100238, ChiSquaredDividedByDOF=258.54459195558803, ChiSquaredDividedByNData=258.02363278929874, ChiSquaredWeighted=12679.696582587236, ChiSquaredWeightedDividedByDOF=3.6572531244843485, ChiSquaredWeightedDividedByNData=3.6498838752410006)
*** with minimizer Damped GaussNewton, Status: success, chi2: nan
   params: [nan, nan, nan, nan, nan, nan, nan], errors: [nan, nan, nan, nan, nan, nan, nan]
   sum sq: nan
Result object: <test_result.FittingTestResult object at 0x000000002CD00400>
saving to Fit_for_ENGINX_193749_calibration,_spectrum_651,_pe_1.pdf
saving to start_for_ENGINX_193749_calibration,_spectrum_651,_pe_1.pdf
unknown line in supposedly NIST test file, ignoring: # An example of (full) detector calibration for the ENGIN-X instrument
unknown line in supposedly NIST test file, ignoring: name = 'ENGINX 193749 calibration, spectrum 651, peak 6'
unknown line in supposedly NIST test file, ignoring: input_file = 'ENGINX193749_calibration_spec651.nxs'
unknown line in supposedly NIST test file, ignoring: function = 'name=LinearBackground;name=BackToBackExponential,I=17.0679,A=1,B=0.05,X0=13642.3,S=1.25655'
unknown line in supposedly NIST test file, ignoring: fit_parameters = {'StartX': 13556.2988352, 'EndX': 13731.2988352}
unknown line in supposedly NIST test file, ignoring: description = ''
* Testing fitting for problem definition file C:\Backup\Backup_folder1\work\code\Mantid\fitting\FitMinimizerTesting\FittingTestData\Neutron_data\ENGINX193749_calibration_peak6.txt
* Testing fitting of problem ENGINX 193749 calibration, spectrum 651, peak 6
*** with minimizer BFGS, calculated: chi2: CalculateChiSquared_returns(ChiSquared=896378.2677188818, ChiSquaredDividedByDOF=258.54579397717964, ChiSquaredDividedByNData=258.02483238885486, ChiSquaredWeighted=12681.316095063077, ChiSquaredWeightedDividedByDOF=3.6577202466290966, ChiSquaredWeightedDividedByNData=3.6503500561494175)
*** with minimizer BFGS, Status: iteration is not making progress towards solution, chi2: 0.0918213143657
   params: [0.0009925572073004782, 8.215622335352455e-05, 17.063705196153943, 0.9901884183856565, 0.0014201451685478608, 13642.300455545308, 1.2477966047771283], errors: [203.3538679395699, 0.014942597311393293, 11710.250406685473, 357.1726397264943, 0.9821156184903916, 574.1247193370922, 552.4192154391542]
   sum sq: 45.0994971755
Result object: <test_result.FittingTestResult object at 0x000000002EF001D0>
*** with minimizer Damped GaussNewton, calculated: chi2: CalculateChiSquared_returns(ChiSquared=896378.2677188818, ChiSquaredDividedByDOF=258.54579397717964, ChiSquaredDividedByNData=258.02483238885486, ChiSquaredWeighted=12681.316095063077, ChiSquaredWeightedDividedByDOF=3.6577202466290966, ChiSquaredWeightedDividedByNData=3.6503500561494175)
*** with minimizer Damped GaussNewton, Status: success, chi2: nan
   params: [nan, nan, nan, nan, nan, nan, nan], errors: [nan, nan, nan, nan, nan, nan, nan]
   sum sq: nan
Result object: <test_result.FittingTestResult object at 0x000000002EF00080>
saving to Fit_for_ENGINX_193749_calibration,_spectrum_651,_pe_1.pdf
saving to start_for_ENGINX_193749_calibration,_spectrum_651,_pe_1.pdf
unknown line in supposedly NIST test file, ignoring: # An example of fitting of a spline background on a Vanadium run from ENGIN-X
unknown line in supposedly NIST test file, ignoring: name = 'ENGINX 236516 vanadium, bank 1, 10 brk'
unknown line in supposedly NIST test file, ignoring: input_file = 'ENGINX236516_vanadium_bank1.nxs'
unknown line in supposedly NIST test file, ignoring: function = 'name=BSpline, Order=3, NBreak=10'
unknown line in supposedly NIST test file, ignoring: fit_parameters = {'StartX': 0, 'EndX': 5.4}
unknown line in supposedly NIST test file, ignoring: description = ''
* Testing fitting for problem definition file C:\Backup\Backup_folder1\work\code\Mantid\fitting\FitMinimizerTesting\FittingTestData\Neutron_data\ENGINX236516_vanadium_bank1_10brk.txt
* Testing fitting of problem ENGINX 236516 vanadium, bank 1, 10 brk
*** with minimizer BFGS, calculated: chi2: CalculateChiSquared_returns(ChiSquared=12996186895.608942, ChiSquaredDividedByDOF=920214.3238411769, ChiSquaredDividedByNData=919498.1530783176, ChiSquaredWeighted=9019526.999999989, ChiSquaredWeightedDividedByDOF=638.6410111166175, ChiSquaredWeightedDividedByNData=638.1439790575909)
*** with minimizer BFGS, Status: success, chi2: 271.393277157
   params: [0.0, 0.0, -38.87711899615912, 17.792379208565535, -1.268315350623293, 64.49130252106153, 463.41713344088555, 895.8821403835625, 1240.2994314056998, 1563.546741879147, 1755.9906115447793], errors: [0.0, 0.0, 2.05507661473514, 5.9415578706271726, 3.894441011439195, 1.5902824211380489, 0.6463646251998239, 0.4472087455283905, 0.3737660514337523, 0.2629037167100756, 0.19157037510946667]
   sum sq: 11420144456.1
Result object: <test_result.FittingTestResult object at 0x0000000030193358>
*** with minimizer Damped GaussNewton, calculated: chi2: CalculateChiSquared_returns(ChiSquared=12996186895.608942, ChiSquaredDividedByDOF=920214.3238411769, ChiSquaredDividedByNData=919498.1530783176, ChiSquaredWeighted=9019526.999999989, ChiSquaredWeightedDividedByDOF=638.6410111166175, ChiSquaredWeightedDividedByNData=638.1439790575909)
*** with minimizer Damped GaussNewton, Status: success, chi2: 318.553613054
   params: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], errors: [0.0, 0.0, 2.0550766147351602, 5.94155787062707, 3.8944410114392958, 1.590282421138047, 0.6463646251998245, 0.4472087455283908, 0.37376605143375213, 0.2629037167100742, 0.191570375109465]
   sum sq: 12996186895.6
Result object: <test_result.FittingTestResult object at 0x000000003021B470>
saving to Fit_for_ENGINX_236516_vanadium,_bank_1,_10_1.pdf
saving to start_for_ENGINX_236516_vanadium,_bank_1,_10_1.pdf
unknown line in supposedly NIST test file, ignoring: # An example of fitting of a spline background on a Vanadium run from ENGIN-X
unknown line in supposedly NIST test file, ignoring: name = 'ENGINX 236516 vanadium, bank 1, 30 brk'
unknown line in supposedly NIST test file, ignoring: input_file = 'ENGINX236516_vanadium_bank1.nxs'
unknown line in supposedly NIST test file, ignoring: function = 'name=BSpline, Order=3, NBreak=20'
unknown line in supposedly NIST test file, ignoring: fit_parameters = {'StartX': 0, 'EndX': 5.4}
unknown line in supposedly NIST test file, ignoring: description = ''
* Testing fitting for problem definition file C:\Backup\Backup_folder1\work\code\Mantid\fitting\FitMinimizerTesting\FittingTestData\Neutron_data\ENGINX236516_vanadium_bank1_20brk.txt
* Testing fitting of problem ENGINX 236516 vanadium, bank 1, 30 brk
*** with minimizer BFGS, calculated: chi2: CalculateChiSquared_returns(ChiSquared=12996186895.608942, ChiSquaredDividedByDOF=920866.3569481288, ChiSquaredDividedByNData=919498.1530783176, ChiSquaredWeighted=9019526.999999989, ChiSquaredWeightedDividedByDOF=639.0935307872167, ChiSquaredWeightedDividedByNData=638.1439790575909)
*** with minimizer BFGS, Status: iteration is not making progress towards solution, chi2: 271.571442182
   params: [0.0, 0.0, 0.0, 0.0, -34.777786735615194, -0.23217276253824384, 9.403164581870763, 10.518815388043825, 6.9370493019956445, 23.376185751191002, 105.27314795392769, 255.25549186620273, 432.7606425867379, 642.904527771586, 852.8387462122648, 1024.8159138642388, 1181.2756648755885, 1344.0905885589189, 1499.2540663640739, 1656.3704447943758, 1764.274947534601], errors: [0.0, 0.0, 0.0, 0.0, 0.2969752358990893, 4.875475179221807, 3.6015516975085915, 2.904013666105598, 2.8019264478481194, 1.7168463013481126, 0.8926037075471759, 0.5743792622533908, 0.4352643347282554, 0.3575564321987009, 0.31032578355701995, 0.2818846923827822, 0.2619545200518803, 0.24567755004886271, 0.23241019091497173, 0.17352479212642852, 0.13053971913808446]
   sum sq: 11420108667.4
Result object: <test_result.FittingTestResult object at 0x0000000033334390>
*** with minimizer Damped GaussNewton, calculated: chi2: CalculateChiSquared_returns(ChiSquared=12996186895.608942, ChiSquaredDividedByDOF=920866.3569481288, ChiSquaredDividedByNData=919498.1530783176, ChiSquaredWeighted=9019526.999999989, ChiSquaredWeightedDividedByDOF=639.0935307872167, ChiSquaredWeightedDividedByNData=638.1439790575909)
*** with minimizer Damped GaussNewton, Status: success, chi2: 318.778787022
   params: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], errors: [0.0, 0.0, 0.0, 0.0, 0.29697523589910957, 4.87547517922111, 3.601551697508593, 2.9040136661055596, 2.801926447848105, 1.7168463013481154, 0.8926037075471729, 0.5743792622533928, 0.4352643347282565, 0.3575564321987066, 0.3103257835570216, 0.281884692382785, 0.26195452005188036, 0.24567755004886316, 0.23241019091497092, 0.17352479212642874, 0.13053971913808146]
   sum sq: 12996186895.6
Result object: <test_result.FittingTestResult object at 0x00000000333422B0>
saving to Fit_for_ENGINX_236516_vanadium,_bank_1,_30_1.pdf
saving to start_for_ENGINX_236516_vanadium,_bank_1,_30_1.pdf
unknown line in supposedly NIST test file, ignoring: # An example of two Gaussian peaks from the instrument VESUVIO, bad initial values
unknown line in supposedly NIST test file, ignoring: name = 'EVS14188-90_processed Gaussian peaks 1'
unknown line in supposedly NIST test file, ignoring: input_file = 'EVS14188-90_peaks.nxs'
unknown line in supposedly NIST test file, ignoring: function = 'name=Gaussian, Height=0.01,PeakCentre=0.00037,Sigma=1e-05 ; name=LinearBackground,A0=0,A1=0;name=Gaussian, Height=0.0979798,PeakCentre=0.000167,Sigma=1e-05'
unknown line in supposedly NIST test file, ignoring: # fit_parameters = {'StartX': 0, 'EndX': 0}
unknown line in supposedly NIST test file, ignoring: description = ''
* Testing fitting for problem definition file C:\Backup\Backup_folder1\work\code\Mantid\fitting\FitMinimizerTesting\FittingTestData\Neutron_data\EVS14188-90_Gaussian_peaks_1.txt
* Testing fitting of problem EVS14188-90_processed Gaussian peaks 1
*** with minimizer BFGS, calculated: chi2: CalculateChiSquared_returns(ChiSquared=1.6510732406215207, ChiSquaredDividedByDOF=0.0016234741795688502, ChiSquaredDividedByNData=0.0016108031615819714, ChiSquaredWeighted=3359.7648016900866, ChiSquaredWeightedDividedByDOF=3.3036035414848444, ChiSquaredWeightedDividedByNData=3.277819318722036)
*** with minimizer BFGS, Status: Failed to converge after 500 iterations., chi2: 1.38482556729
   params: [0.0002324930260989513, 0.0003054508323446593, 1e-05, 0.025458922451202168, -2.7545549828613267e-05, 0.13068595953165535, 0.00016535106749548663, 1e-05], errors: [0.004428362297988117, 0.00021824815021357122, 0.00022485682240997004, 0.001854685257540242, 5.019839701523972, 0.004763191973277161, 4.113824546441107e-07, 4.253059114712241e-07]
   sum sq: 1.34813353381
Result object: <test_result.FittingTestResult object at 0x0000000005E821D0>
*** with minimizer Damped GaussNewton, calculated: chi2: CalculateChiSquared_returns(ChiSquared=1.6510732406215207, ChiSquaredDividedByDOF=0.0016234741795688502, ChiSquaredDividedByNData=0.0016108031615819714, ChiSquaredWeighted=3359.7648016900866, ChiSquaredWeightedDividedByDOF=3.3036035414848444, ChiSquaredWeightedDividedByNData=3.277819318722036)
*** with minimizer Damped GaussNewton, Status: success, chi2: 1.55012700718
   params: [266.27318363580633, 0.001994966285019734, 1.1884806557115978e-09, 0.04925650361832962, -98.19965255512948, 0.08456583601695118, 0.00016621257793525383, 3.02023415449114e-06], errors: [0.0, 0.0, 0.0, 1479.4678811560138, 0.5143531081402585, 143.90486255959473, 2845277.3457312617, 6.612048265565655e-28]
   sum sq: 1.59176763722
Result object: <test_result.FittingTestResult object at 0x0000000036120F28>
saving to Fit_for_EVS14188-90_processed_Gaussian_pea_1.pdf
saving to start_for_EVS14188-90_processed_Gaussian_pea_1.pdf
unknown line in supposedly NIST test file, ignoring: # An example of two Gaussian peaks from the instrument VESUVIO, good initial values
unknown line in supposedly NIST test file, ignoring: name = 'EVS14188-90_processed Gaussian peaks 1'
unknown line in supposedly NIST test file, ignoring: input_file = 'EVS14188-90_peaks.nxs'
unknown line in supposedly NIST test file, ignoring: function = 'name=Gaussian, Height=0.0271028,PeakCentre=0.000371946,Sigma=1e-05; name=LinearBackground,A0=0,A1=0;name=Gaussian, Height=0.0979798,PeakCentre=0.000167,Sigma=1.7267e-05'
unknown line in supposedly NIST test file, ignoring: # fit_parameters = {'StartX': 0, 'EndX': 0}
unknown line in supposedly NIST test file, ignoring: description = ''
* Testing fitting for problem definition file C:\Backup\Backup_folder1\work\code\Mantid\fitting\FitMinimizerTesting\FittingTestData\Neutron_data\EVS14188-90_Gaussian_peaks_2.txt
* Testing fitting of problem EVS14188-90_processed Gaussian peaks 1
*** with minimizer BFGS, calculated: chi2: CalculateChiSquared_returns(ChiSquared=1.1202899434683808, ChiSquaredDividedByDOF=0.0011015633662422623, ChiSquaredDividedByNData=0.0010929657985057374, ChiSquaredWeighted=2298.2078929951294, ChiSquaredWeightedDividedByDOF=2.2597914385399505, ChiSquaredWeightedDividedByNData=2.242154041946468)
*** with minimizer BFGS, Status: iteration is not making progress towards solution, chi2: 0.751916719449
   params: [0.06826060850490975, 0.00037258716880340026, 1e-05, 0.007567628545617181, -6.29584533313227e-05, 0.1547323377238475, 0.0001658445455414375, 1.7267e-05], errors: [0.004504905280251212, 7.470129770638955e-07, 7.529841715661026e-07, 0.002014235498034017, 5.338316447639594, 0.003663126720848956, 4.5558577374955543e-07, 4.886242403587123e-07]
   sum sq: 0.735125028684
Result object: <test_result.FittingTestResult object at 0x00000000377EE940>
*** with minimizer Damped GaussNewton, calculated: chi2: CalculateChiSquared_returns(ChiSquared=1.1202899434683808, ChiSquaredDividedByDOF=0.0011015633662422623, ChiSquaredDividedByNData=0.0010929657985057374, ChiSquaredWeighted=2298.2078929951294, ChiSquaredWeightedDividedByDOF=2.2597914385399505, ChiSquaredWeightedDividedByNData=2.242154041946468)
*** with minimizer Damped GaussNewton, Status: success, chi2: 0.487418880465
   params: [0.11392104043493853, 0.0003733259770525626, 5.577999282024106e-06, 0.0017497256831945135, -3.5027232618867683, 0.13051001843669777, 0.0001665288590226634, 3.0132258606503588e-05], errors: [0.006033530851642759, 3.380088512256704e-07, 3.4050337889730804e-07, 0.0026134535241101394, 6.463172832846941, 0.0029070843793147783, 7.094674417777859e-07, 8.652490417892673e-07]
   sum sq: 0.477220399273
Result object: <test_result.FittingTestResult object at 0x00000000377EEE48>
saving to Fit_for_EVS14188-90_processed_Gaussian_pea_1.pdf
saving to start_for_EVS14188-90_processed_Gaussian_pea_1.pdf
unknown line in supposedly NIST test file, ignoring: # Test example from the GEM instrument, fit Ikeda-Carpender peaks
unknown line in supposedly NIST test file, ignoring: name = 'GEM peak 1'
unknown line in supposedly NIST test file, ignoring: input_file = 'GEM63437_focused_bank3.nxs'
unknown line in supposedly NIST test file, ignoring: function = 'name=FlatBackground,A0=0.0567018;name=IkedaCarpenterPV,I=297.132,Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342,SigmaSquared=3195.44,Gamma=1.25415,X0=8831.8,ties=(Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342);name=IkedaCarpenterPV,I=113.422,Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342,SigmaSquared=1073.44,Gamma=0.710369,X0=5406.07,ties=(Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342);name=IkedaCarpenterPV,I=57.6345,Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342,SigmaSquared=791.78,Gamma=0.578873,X0=4610.4,ties=(Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342);name=IkedaCarpenterPV,I=12.1933,Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342,SigmaSquared=572.213,Gamma=0.78892,X0=3823.17,ties=(Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342);name=IkedaCarpenterPV,I=13.2863,Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342,SigmaSquared=453.857,Gamma=1.77924,X0=3508.92,ties=(Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342);name=IkedaCarpenterPV,I=16.3072,Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342,SigmaSquared=366.159,Gamma=1.4837,X0=3122.9,ties=(Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342);name=IkedaCarpenterPV,I=7.41345,Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342,SigmaSquared=315.152,Gamma=1.96745,X0=2944.05,ties=(Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342);name=IkedaCarpenterPV,I=1.34762,Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342,SigmaSquared=200.798,Gamma=10.1902,X0=2705.33,ties=(Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342);name=IkedaCarpenterPV,I=7.09738,Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342,SigmaSquared=264.513,Gamma=1.23854,X0=2585.33,ties=(Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342);name=IkedaCarpenterPV,I=3.73496,Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342,SigmaSquared=223.369,Gamma=2.56355,X0=2418.88,ties=(Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342);name=IkedaCarpenterPV,I=3.55469,Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342,SigmaSquared=251.021,Gamma=0.0614421,X0=2332.04,ties=(Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342);name=IkedaCarpenterPV,I=17.5205,Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342,SigmaSquared=6049.07,Gamma=-0.883851,X0=2138.75,ties=(Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342);name=IkedaCarpenterPV,I=10.3457,Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342,SigmaSquared=158.85,Gamma=-1.38948,X0=2137.35,ties=(Alpha0=0.734079,Alpha1=2.06725,Beta0=32.0172,Kappa=48.7342)'
unknown line in supposedly NIST test file, ignoring: fit_parameters = {'StartX': 2050.8564217228977, 'EndX': 9433.6384439359281}
unknown line in supposedly NIST test file, ignoring: description = ''
* Testing fitting for problem definition file C:\Backup\Backup_folder1\work\code\Mantid\fitting\FitMinimizerTesting\FittingTestData\Neutron_data\GEMpeak1.txt
* Testing fitting of problem GEM peak 1
IndexError: Matrix is empty.

In the terminal I get:

Fit-[Error] Error in execution of algorithm Fit:
Fit-[Error] Matrix is empty.

Do you see this also?

**Comment by AnthonyLim23** [comment]
I think I have seen something similar. If the matrix is empty does that mean the data cannot be found?

**Comment by Anders-Markvardsen** [comment]
I think the answer to that is no. I just tried again now where I only run GEMpeak1.txt and same error. This test is looking for input_file = 'GEM63437_focused_bank3.nxs' which as far as I can tell matches 'GEM63437_focused_bank3.nxs'. The systemtest https://github.com/mantidproject/mantid/blob/master/Testing/SystemTests/tests/analysis/FittingBenchmarks.py test neutron_data test against trust_region only (to limit the test it runs) hence it is possible (although I was not likely) that a change to the fitting now is causing a problem for fitting this problem with a non trust region minimizer

**Comment by AnthonyLim23** [comment]
huh... thats very strange. I will look into it tomorrow

**Comment by AnthonyLim23** [comment]
are you running the same script as before (neutron data)?

**Comment by Anders-Markvardsen** [comment]
Yes same script

**Review by Anders-Markvardsen — APPROVED** [review]
Tested and plots very informative.

Now what remains is to make these available from the fit benchmarking tables - a separate issue has been created for this

**Comment by AnthonyLim23** [comment]
@mantidproject/gatekeepers can we get the above commit put back into master. It was removed by mistake.

**Pull request merged**
