### PR TITLE
Fix crash importing mslice cli in workbench

### LINKED ISSUE #29061: Using mslice.cli in workbench causes segfaults
**Original reporter:** Tatiana / @mducle 

### Expected behavior
Mslice functionality in a script should work seemlessly: https://mantidproject.github.io/mslice/cli.html
### Actual behavior
Crash when importing mslice
### Steps to reproduce the behavior
Open a workbench package on any OS
Run in script editor `import mslice.cli as mc`
### Platforms affected
Workbench (4.2,5.0,Nightly) on All OS I think

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Forces update to algorithm selector onto GUI thread and more methods of matplotlib figure manager onto GUI thread.

See final commit message for further details.

**To test:**

In workbench running

```python
import mslice.cli
```

no longer crashes.

There are also updates to the figuremanager to ensure that all future methods are run on the QApplication thread. Try any mantid plotting examples from https://docs.mantidproject.org/nightly/plotting/index.html#plotting in the script editor and they should not crash. This is best done on a Windows debug build so it loudly complains if anything is wrong.

Refs #29061

Note this does not yet fix the crash as mslice also needs updates using the new methods provided here.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DanielMurphy22 — CHANGES_REQUESTED** [review]
This fix mostly seems good. both importing mslice and importing the helloworld.py example from the issue now work.
When Matt and I ran an example script from Tatiana, using mslice, plotting a colormesh from the output object of Mslice caused a hard crash. I thin it's worth us figuring out if this is related to this PR before merging.

**Comment by martyngigg** [comment]
I've tried a simple script that creates and plots a slice:
```
# Python Script Generated by Mslice on 2020-08-06 07:00:05
import mslice.cli as mc
import mslice.plotting.pyplot as plt

ws_MAR21335_Ei60_00meV = mc.Load(Filename='MAR21335_Ei60.00meV.nxs', OutputWorkspace='MAR21335_Ei60.00meV')

fig = plt.gcf()
ax = fig.add_subplot(111, projection="mslice")
slice_ws = mc.Slice(ws_MAR21335_Ei60_00meV, Axis1="|Q|,0.27356,11.0351,0.04671", Axis2="DeltaE,-30.0,58.2,0.3", NormToOne=False)

mesh = ax.pcolormesh(slice_ws, cmap="viridis")
mesh.set_clim(0.0, 376.8665783219241)
cb = plt.colorbar(mesh, ax=ax)
cb.set_label('Intensity (arb. units)', labelpad=20, rotation=270, picker=5)
ax.set_title('MAR21335_Ei60.00meV')
mc.Show()
```

and this appears to work for me. Does it work for you?

**Review by Matt-Cumber — DISMISSED** [review]
Running the script from @martyngigg produces this debug error window on Windows. 
image

**Comment by DanielMurphy22** [comment]
The example script from @martyngigg runs successfully in MantidPlot 5.0 and Workbench 4.2. 
Workbench 5.0 fails at the import line, and this PR fails when trying to plot the slice.

**Comment by martyngigg** [comment]
Thanks, both. I'm starting to think this is related to upgrading matplotlib as part of the Python 3 move.

**Comment by martyngigg** [comment]
@DanielMurphy22 @Matt-Cumber I have fixes for this but I'm going to have to add code to both `mantid` and `mslice` but I want to reuse some code in `mantidqt` so I'll have to do this in 2 steps. Can we get this merged and then we'll need to wait for a nightly and then I can create the pull request on `mslice`?
I've updated the test instructions above for this PR alone.

**Review by DanielMurphy22 — APPROVED** [review]
Re-checked and importing works! Approving this so it can progress as highlighted by @martyngigg above!

**Comment by martyngigg** [comment]
@mantidproject/gatekeepers Would it be possible to get this into nightly?

**Pull request merged**
