### PR TITLE
Tidy Indirect 6.6 release notes

### LINKED ISSUE #35157: Tidy 6.6 `indirect_geometry.rst`

### PR DESCRIPTION
**Pull request by jhaigh0**
**Description of work.**

Tidied the 6.6 Indirect Geometry release notes file.

**This must be merged after #35137 !!**

**To test:**

 - Build `docs-html`
 - Open `indirect_geometry.html`
 - Read through the notes and check that the grammar and spelling are good
 - Check that links work and go where you expect

Fixes #35157

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by MialLewis — CHANGES_REQUESTED** [review]
One comment, otherwise looks good.

**Comment by SpencerHowells** [comment]
@jhaigh0 @MialLewis The notes in several places refer to Indirect Data Manipulation when it is Inelastic Data Manipulation and run from the new interface category Inelastic.

**Comment by jhaigh0** [comment]
> @jhaigh0 @MialLewis The notes in several places refer to Indirect Data Manipulation when it is Inelastic Data Manipulation and run from the new interface category Inelastic.

Yes, I was confused about this. I'll go and change that.

**Comment by SpencerHowells** [comment]
@jhaigh0 It's also on the main page.

**Comment by jhaigh0** [comment]
@AnthonyLim23 Could you advise what needs to be changes from `Indirect` to `Inelastic` in [this documentation](https://github.com/mantidproject/mantid/blob/main/docs/source/interfaces/indirect/Indirect%20Data%20Manipulation.rst)

I can see that the title and second word in the opening paragraph would need to change, but should the file name and location change too?

I don't want to go changing documentation where I'm not 100% sure on the content itself.

**Comment by SpencerHowells** [comment]
@jhaigh0 @AnthonyLim23 When you click in the ? button of the interface it cannot find the html file.

**Comment by AnthonyLim23** [comment]
@SpencerHowells  you need to compile the docs and Mantid to get it to work.

**Comment by SpencerHowells** [comment]
@jhaigh0 Here's an edited html file with changes marked in red.
[Indirect Data Manipulation.zip](https://github.com/mantidproject/mantid/files/10683940/Indirect.Data.Manipulation.zip)
There is 1 section that needs to be completely removed as it is indirect specific.
The interface catalogue document also needs editing.

**Comment by jhaigh0** [comment]
> @jhaigh0 Here's an edited html file with changes marked in red. [Indirect Data Manipulation.zip](https://github.com/mantidproject/mantid/files/10683940/Indirect.Data.Manipulation.zip) There is 1 section that needs to be completely removed as it is indirect specific. The interface catalogue document also needs editing.

Thank you, I will make a separate pull request with these changes

**Review by MialLewis — APPROVED** [review]

**Pull request merged**
