### PR TITLE
Fix performance regression in ExperimentInfo::getInstrument

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Recent changes around `ComponentInfo` caused some moderately expensive copies of vectors of component Ids in `ExperimentInfo::getInstrument()`. This PR replaces this with `shared_ptr` --
`ExperimentInfo::getInstrument` is slow otherwise. This is a problem, since `getInstrument` is called by `getDetector`, i.e., for every spectrum in a workspace.

**To test:**

No releated issue, but this was discovered by @VickieLynch as part of https://github.com/mantidproject/mantid/issues/19385.

No release notes, issue was introduced after last release.

Marked as high priority due to serious slowdowns in nightly builds, e.g., when opening the instrument view.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
According to a quick local test this might also be fixing the issues seen with the performance of `DiffractionFocussing2` in https://github.com/mantidproject/mantid/issues/19339.

**Comment by OwenArnold** [comment]
@SimonHeybrock According to the residental memory usage, this does reduce the memory sufficiently for `DiffractionFocussing2TestPerformance`!

**Comment by SimonHeybrock** [comment]
@OwenArnold :( (we should still see an impovement on systems with sufficient memory though).

**Comment by OwenArnold** [comment]
Code looks good. :shipit: when the tests are green.

**Comment by OwenArnold** [comment]
@SimonHeybrock Looking at the performance tests this morning. This fix might also address http://builds.mantidproject.org/job/master_performancetests2/Master_branch_performance_tests/APITest.MatrixWorkspaceTestPerformance.test_move_bank_and_read_positions_x10.htm. `MatrixWorkspace::getDetector` calls `getInstrument()` so reading is suddenly very expensive via this old style access.

**Pull request merged**
