### PR TITLE
Normalisation of fit results on workbench

### LINKED ISSUE #25727: Normalisation of fit results in workbench
### Expected behaviour
In workbench the fit parameters should correspond to the scaling on the plot
### Actual behaviour
The fit parameters automatically rescale to bin width, while the plot is not rescaled to bin width
### Steps to reproduce the behaviour
- Use Workbench
- From the sample data from the Mantid tutorial load GEM38370_Focussed.nxs
- Plot spectrum number 5
- set axis range to between `2` and `2.25`
- open fit
- add peaks corresponding to approximately `2.11`, `2.14` and `2.19`
- add linear background.
- press fit.
- Fit parameters have been normalised while the plot has not.
workbench_fit_rescaling
### Platforms affected
All.

### PR DESCRIPTION
**Pull request by ghost**
**Description of work.**
When fitting on Workbench, if the plot was normalised the fitting algorithm still ran on un-normalised data. The plotted line looked correct because line plotted using the fit parameters was normalised on plotting, but the fit results in the `FitPropertyBrowser` did not match the plot. This was due to the `m_shouldBeNormalised` flag not being set in Workbench as it is in MantidPlot.

This PR ensures the relevant flag is set before any fitting takes place.

**To test:**
- Follow the instructions in the associated issue and check the fit results in the dock widget match the plotted line.
- Carry out some more fits on plots that are normalised/non-normalised and check the corresponding results are normlised/non-normalised.
- When carrying out fits, do some plot guesses and make sure they are sensible (there was a bug where plot guesses were normalised twice).

Fixes #25727.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gemmaguest** [comment]
Some potential issues / things that confused me (probably not all related to this PR!):

- When you do a fit or display the plot guess, the image gets zoomed out to its full extent vertically. If you do a fit again, the image also gets zoomed out horizontally.

- The difference is always shown even if I untick `Plot Difference`

- When you remove a plot guess, the legend gets moved up to the top right corner and can no longer be dragged around.

- The legend displays less informative labels than MantidPlot, e.g. `GEM38370_Focussed_Workspace: spec 2` instead of `GEM38370_Focussed_Workspace-Calc`

- The vertical markers are shown over the top of the legend.
fit_markers_over_legend

- If I move the plot settings dialog to a different monitor to the plot and then click one of the drop-down boxes, the drop-down menu appears on the wrong monitor.
fit_drop_down_on_diff_monitor

- If I delete the fit results workspaces while Fit is still enabled in the plot, they do not disappear from the plot window until something else causes a redraw (e.g. resizing the window). If I delete them after doing the Fit twice, I get this error and I can't clear them from the plot at all:
```
Data Object 'GEM38370_Focussed_NormalisedCovarianceMatrix' deleted from data service.
Data Object 'GEM38370_Focussed_Parameters' deleted from data service.
Error occurred in handler:
Traceback (most recent call last):
  File "/home/gemma/work/checkout/mantid2/qt/applications/workbench/workbench/plotting/figuremanager.py", line 46, in wrapper
    func(*args, **kwargs)
  File "/home/gemma/work/checkout/mantid2/qt/applications/workbench/workbench/plotting/figuremanager.py", line 96, in deleteHandle
    ax.remove_workspace_artists(workspace)
  File "/home/gemma/work/checkout/mantid2/Framework/PythonInterface/mantid/plots/__init__.py", line 370, in remove_workspace_artists
    workspace_artist.remove(self)
  File "/home/gemma/work/checkout/mantid2/Framework/PythonInterface/mantid/plots/__init__.py", line 115, in remove
    self._remove(axes, self._artists)
  File "/home/gemma/work/checkout/mantid2/Framework/PythonInterface/mantid/plots/__init__.py", line 140, in _remove
    artist.remove()
  File "/usr/lib/python2.7/dist-packages/matplotlib/artist.py", line 149, in remove
    self._remove_method(self)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 1712, in <lambda>
    line._remove_method = lambda h: self.lines.remove(h)
ValueError: list.remove(x): x not in list
Data Object 'GEM38370_Focussed_Workspace' deleted from data service.
```

**Review by gemmaguest — COMMENTED** [review]
Code changes look good and the normalisation matches the plot now :+1:

Could you confirm whether any of the issues in my previous comment are related to this PR? If not, I'm happy to approve.

**Comment by hsautessella** [comment]
As far as I can tell, those things all happen in master as well. Most, if not all, could do with having issues raised, I think.

**Comment by gemmaguest** [comment]
@hsautessella There are conflicts now

**Review by gemmaguest — APPROVED** [review]
I've added issues for all of the unrelated bugs so this is good to go

**Pull request merged**
