### PR TITLE
Add ability to load A0 parameters to Function(Q) tab

### LINKED ISSUE #36349: FunctionQ tab should be able to read the `A0` parameter from IqtFit result
**Is your feature request related to a problem? Please describe.**
It should be possible to load in a results workspace from the I(Q, t) tab in QENS Fitting if it contains an A0 parameter.

The functions that should be made available for this parameter should be the fit functions beginning with EISF.

This issue should wait for #36348 to be completed.

**Acceptance Criteria**

- It should be possible to load A0 data from the  I(Q, t) tab into Function(Q) tab
- When A0 data is loaded, only EISF fit functions should be available

### PR DESCRIPTION
**Pull request by robertapplin**
### Description of work
This PR adds the ability to load a `_Result` workspace from the I(Q, t) fitting tab into the Function (Q) fitting tab if one of the fit parameters is `A0`. It is then possible to use one of the EISF fit functions to perform a fit.

This PR also changes the calculation of the HWHM. Rather than creating a new separate workspace containing the HWHM, the FWHM or Width spectra is changed in-place in the loaded workspace, and the label of the spectra is updated to read "HWHM". This keeps the ADS clean and leads to less confusion. It also means the code is greatly simplified.

Fixes #36349 

### To test:
1. Open Inelastic QENS Fitting interface
2. Go to Function(Q) tab
3. Load the following workspace containing `A0`
[irs26176_graphite002_iqt_Iqt_seq_1S_0-50__Result.zip](https://github.com/user-attachments/files/16232438/irs26176_graphite002_iqt_Iqt_seq_1S_0-50__Result.zip)

5. Select the `f1.A0` parameter, click `Add`, then `Close` the data selection dialog
6. The data should be plotted ok
7. Make sure only the EISF fit functions are visible.
8. Select a fit function and click `Run`
9. It should do a fit

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by robertapplin** [comment]
Build package from branch here: https://builds.mantidproject.org/job/build_packages_from_branch/845/

**Review by adriazalvarez — CHANGES_REQUESTED** [review]
Followed test instructions, everything is working correctly. 
The new parameter A0 is visible from the function Q tab on compatible files, and the EISF functions are available when this parameter is loaded. 
Also, refactoring of the calculation of HWHM is really nice and reduces a lot of code. 

If it is not too much to ask, could you update the documentation entry for the QENS Fitting interface, indicating that this is possible to do now. (And why we would want to be interested in fitting EISF functions to A0).

**Comment by robertapplin** [comment]
> If it is not too much to ask, could you update the documentation entry for the QENS Fitting interface, indicating that this is possible to do now. (And why we would want to be interested in fitting EISF functions to A0).

I think this is a good idea. I have added a table to the documentation. @spencerhowells is there anything I can add to the documentation for the scientific part of this question, i.e. why we want to use EISF functions for A0?

**Review by adriazalvarez — APPROVED** [review]
Thanks for completing the documentation with the available fit types for different sets of QENS fitting data. 
It would be good to add in the future more context around the fitting, but that can be part of another documentation-oriented issue.

**Pull request merged**
