### PR TITLE
Fix beam center finder masking in ISIS SANS

### LINKED ISSUE #16759: Beam Center Finder seems to not work for LARMOR any longer
The beam center finding functionality seems to have stopped working for LARMOR, while it still works for SANS2D. 

This has been only noticed very recently by Rob.

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Description of work.
Fixes #16759 

The beam center finding suddenly stopped workgin for all instruments. The issue was an incorrect shape XML for masking out pizza-slices from wavelength workspaces.

**Cause**

This seems to have been a case of "bug fixes bug". A bug fix before release 3.7.1 relating to the geometry xml was merged into master (see [here](https://github.com/mantidproject/mantid/pull/16004)). This bug fix also fixed system tests relating to the beam center finder.

The bug fix exposed the bug which has led to erratic behaviour of the beam center finder. As a fix we provide a correct geometry xml string and adjust the system test.

**To test:**

A windows installer can be found here: \olympic\Babylon5\Scratch\Anton\Testing\16759_LARMOR_Beam_Center_Issue

Please find the relevant test data here: \olympic\Babylon5\Scratch\Anton\Testing\16759_LARMOR_Beam_Center_Issue
1. Open the ISIS SANS interface
2. Set the instrument to LARMOR
3. Load the user file: USER_Pappas_RB1569004_162B_ISISStat_r9818.txt
4. In sample scatter set the path to the workspace: LARMOR00009839.nxs
5. On the Geometry tab, set the "Max iterations" to 0
6. On the Geometry tab, press Run
   - Opent the Up, Down, Left, Right workspaces which should have appeared in the WorkspaceWindow and plot them. Confirm that what you see is not all zero

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
Does the test data need to be copied to a directory that has been selected in "Manage user directories" as a "Data search directory"?

**Comment by AntonPiccardoSelg** [comment]
@KarlPalmen Mantid needs to see the test data yes. Alternatively you can add the network location to  the data search directory, so there is no need to copy anything.

**Comment by martyngigg** [comment]
The XML algebra string is now what you would expect it to be for a hollow cylinder.

I ran the test instructions for the v3.7.1 and then on this PR and I got the following two images:

larmor-beamcentre

The left is `v3.7.1` and the right this PR - clearly the fix has worked and the code is now doing the correct thing.

:shipit:

**Comment by FedeMPouzols** [comment]
Looks good. If this issue has been visible to users maybe we should add a bug fix line in the release notes.

**Comment by AntonPiccardoSelg** [comment]
@FedeMPouzols  That is good idea. :+1: I will add it to a current bug fix I am doing.

**Pull request merged**
