### PR TITLE
PyChop bugfixes

### LINKED ISSUE #18485: PyChop bugfixes
Instrument scientists on LET and MERLIN have identified several necessary changes to PyChop to fix bugs or for useability reasons:

1. On Merlin, PyChop currently outputs all possible Ei reps, even where the incident neutron flux means that such reps would be unobservable. A restriction that Ei < 7 meV should be applied to not display low energy reps which cannot be seen. LET should have a similar restriction for Ei > 30 meV.

2. On LET, the pulse removal chopper frequency should be less than 150 Hz (physical limit of the chopper).

3. On LET, in "Expert mode", the chopper 2 phase box disappears. Also "Expert Mode" should show another tab which displays the moderator and chopper time components of the overall resolution.

4. On LET, the frequency of chopper 4 in high resolution mode should be the same as the pulse removal chopper (chopper 3) frequency - not the resolution chopper frequency divided by 2 as at present (for other modes, it should stay as the resolution chopper frequency / 2).

5. LET has new resolution chopper disk, with slots of size 31, 20 and 15mm, so for high resolution mode, chopper 5 slot_width should now be 15mm.

### PR DESCRIPTION
**Pull request by mducle**
Fixes some bugs, and makes some modifications in PyChop as identified by instrument scientists:

1. Restricts energy ranges of multi-reps to those with non-negligible neutron fluxes (defined externally as `E>7meV` for Merlin and `E<30meV` for LET.

2. Fixes typos and other bugs in calculations for LET (restricts frame overlap chopper speed to less than 150Hz, the physical limit; changed the slot dimensions of the final [resolution] chopper, since LET now has a new disk; changed the frequency of chopper 4 to reflect new high resolution operating conditions.

3. Added facility to output a text to the screen similar to what the old matlab programs (`MChop` and `MultiRep`) used to do - particularly, outputs separately the time-widths at the detector due to the moderator and choppers.

**To test:**

Check in Mantid that `Interfaces` -> `Direct` -> `PyChop` runs. 

Select `LET` as the instrument, and check that the frequencies list of the pulse removal chopper go up to 150Hz only, in 10Hz increments. Check that the resolution chopper frequencies still go to 300Hz (also in 10Hz increments).

Set the resolution chopper to run at 300Hz and the pulse removal chopper at 100Hz, set the incident energy to 1meV and select `High Resolution` mode and click calculate. Then select `Intermediate` mode and click calculate again. Check that the second calculation gives a noticeably worst resolution than the first (previous, LET had a miscut disk, such that the resolution in `High Resolution` mode is about the same as in `Intermediate` mode. 

Click `Show multireps` and then calculate. Check that reps above 30meV are not shown in the plots (to see what they would be, click `Options` -> `Instrument Scientist Mode` and then click on the now revealed `Script Output` tab (you will have to click `Calculate` again.

Set `Merlin` as the instrument, select the `G` chopper and set the frequency to 600Hz, and incident energy to 50meV. Click `Calculate` and check that reps below 7meV are not shown in the plots.

Check that otherwise, PyChop behaves as expected.

Fixes #18485.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AndreiSavici** [comment]
All tests are OK except the last one. I get the low energy reps for MERLIN even if I'm not in the instrument scientist mode

image

**Comment by AndreiSavici** [comment]
Looks OK. If you want it in 3.9 you should merge it into the release branch first, not master :shipit:

**Comment by AndreiSavici** [comment]
:+1:

**Review by peterfpeterson — CHANGES_REQUESTED** [review]
This needs release notes.

**Review by peterfpeterson — APPROVED** [review]

**Pull request merged**
