### PR TITLE
Powder diffraction instruments D2B and D20 support in DrILL

### LINKED ISSUE #29281: Add D2B and D20 instruments support in DrILL (ILL)
### Expected behavior

Allow users to process D2B and D20 data with the DrILL interface.
The algorithms are already there, this issue only concerns processing via the interface.

### Actual behavior

No current support for these instruments in the interface. One has to write a script and call the algorithms for data processing.

### PR DESCRIPTION
**Pull request by gui-co**
**Description of work.**

This PR adds the support for two powder diffraction instruments in the DrILL interface: D2B and D20.

**To test:**

Tests based on https://docs.mantidproject.org/nightly/algorithms/PowderILLParameterScan-v1.html and https://docs.mantidproject.org/nightly/algorithms/PowderILLDetectorScan-v1.html

1. change the facility to ILL
2. add `ExternalData/Testing/Data/SystemTest/ILL/D2B/` and `ExternalData/Testing/Data/SystemTest/ILL/D20/` to your user directories
3. create a file named `test_d2b.mrd` with:
```json
{
    "Instrument": "D2B",
    "AcquisitionMode": "Detector scan",
    "VisualSettings": {
        "FoldedColumns": {}
    },
    "GlobalSettings": {
        "NormaliseTo": "Monitor",
        "CalibrationFile": "",
        "UseCalibratedData": true,
        "Output2DTubes": true,
        "Output2D": true,
        "Output1D": true,
        "CropNegativeScatteringAngles": true,
        "HeightRange": "",
        "InitialMask": "20",
        "FinalMask": "30",
        "ComponentsToMask": "",
        "ComponentsToReduce": "",
        "AlignTubes": true
    },
    "Samples": [
        {
            "Run": "508093:508095",
            "OutputWorkspace": "ws"
        }
    ]
}
```
and a file named `test_d20.mrd` with:
```json
{
    "Instrument": "D20",
    "AcquisitionMode": "Parameter scan",
    "VisualSettings": {
        "FoldedColumns": {}
    },
    "GlobalSettings": {
        "CalibrationFile": "",
        "ROCCorrectionFile": "",
        "NormaliseTo": "None",
        "ROI": "0,153.6",
        "Observable": "sample.temperature",
        "SortObservableAxis": false,
        "ScanAxisBinWidth": "0",
        "CropNegative2Theta": true,
        "ZeroCountingCells": "Interpolate",
        "Unit": "ScatteringAngle"
    },
    "Samples": [
        {
            "Run": "967087,967088",
            "OutputWorkspace": "ws"
        }
    ]
}
```
4. open the interface: *Interface* -> *ILL* -> *Drill*
5. in the interface menu bar, load the D2B file (*File* -> *Load rundex*)
6. process the data: *Process* -> *Process all rows*
7. observe that the processing happened by checking the presence of workspace `ws`
8. repeat 5-7 the D20 json file

Fixes #29281.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gvardany** [comment]
Can you resolve the conflicts?

**Comment by gui-co** [comment]
I resolved the conflicts and added a release note for v6 instead of v5.1.

**Comment by gvardany** [comment]
This is fine, just keep an eye when the default value removal is merged, this will get a conflict.

**Review by gvardany — APPROVED** [review]
Looks good.

**Pull request merged**
