### PR TITLE
Engin-X full calibration improvements

### LINKED ISSUE #15317: Outliers in Engin-X full calibration: understand them and come up with robust procedure to fix them
With EnggCalibrateFull applied on the last calibration runs we get a handful of "outlier" detectors for which the fitting misbehaves (values too far off from their neighbors). These probably lack enough data in a way that seriously misguides the fitting. Narrow down how exactly the difc/zero values are being fitted and "fix" them using some of the alternatives discussed with instrument scientists:
- Force a reduced selected set of easier peaks
- Simplify the fitting with more constrained boundaries, or even simpler peak shape
- Average between neighbors

### PR DESCRIPTION
**Pull request by FedeMPouzols**
Fixes #15317

**To test**:
- Check code changes.
- Unit, system and doc tests have been updated and extended.
- Adds new output to EnggCalibrateFull that exposes the parameters fitted for every peak for every detector.
- The documentation of EnggFitPeaks now provides more details and links to functions and algorithms.
- Basic tests of the Engg GUI should go well. For example a basic focus and a basic calibration should still run normally (final calibration results might change slightly).
- The calibration is now more reliable in general. Differences are not big except for 15-30 detectors which were suffering from wrong peak fits. This is not obvious to check (some hints given below).

Some of the changes made here go a bit in the direction of #14596: the long vanadium run used now in the full calibration system test is 194547, to match the ceria run 193749.

To see a full calibration in action (warning may take tens of minutes on slow machines). Note this is not strictly required, as it is tested in a system test:

```
Load('ENGINX00193749.nxs', OutputWorkspace='ws_ceria')
Load('ENGINX00194547.nxs', OutputWorkspace='ws_vana')

posTable_all, peaksTable_all = EnggCalibrateFull(Workspace='ws_ceria', VanadiumWorkspace='ws_vana', SpectrumNumbers='1-2400', OutDetPosFilename='enginx_calibrate_full_ceria193749_both_banks.csv')
```

And to inspect the results, for example:

```
tbl=mtd['posTable_all']
L2=tbl.column('\delta L2 (calibrated - old)')
# check differences in L2
min(L2), sum(L2)/len(L2), max(L2)
# find the max difference for example
val, idx = min((val, idx) for (idx, val) in enumerate(L2))
val, idx

# Check position and parameters for one detector example (spectrum 802):
postTable_one, peaksTable_one  = EnggCalibrateFull(Workspace='ws_ceria', VanadiumWorkspace='ws_vana', SpectrumNumbers='802', OutDetPosFilename='enginx_calibrate_full_ceria193749_one.csv')

# To see statistics about the detectors (using the .csv file that EnggCalibrateFull produces):
import numpy as np
import matplotlib.pyplot as plt
calib = genfromtxt('enginx_calibrate_full_ceria193749_both_banks.csv', delimiter=',')
calib.shape

L2_delta = calib[:,10]
difc = calib[:,11]
tzero = calib[:, 12]
# check percentiles:
np.percentile(tzero, 99)
# cumulative distribution plots
def cdf_plot(data):
    values, base = np.histogram(data, bins=100)
    cumulative = np.cumsum(values)
    plt.plot(base[:-1], cumulative, c='blue')
    plt.show()

cdf_plot(difc)
cdf_plot(tzero)
cdf_plot(L2_delta)
```

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
@shahrozahmed1 : as you found, this is terribly slow on windows.
I think on your machine it was estimating~25h to run in debug mode. On my machine the estimated time to run through all the detectors are:
- this branch built in debug mode but running without debugging: ~9h 45m
- this branch built in release mode: ~5h 45m
- With the Mantid 3.6 binary (before this branch): ~1h 5m

On debian this doesn't take more than 7-8m.

**Comment by FedeMPouzols** [comment]
Aha, I'm beginning to think that whatever has caused this slow-down is not in this branch.
I've tried the following: copy the Engg* python algorithms from Mantid 3.6 (installed in `C:\MantidInstall\plugins\python\algorithms`) on top of my testing repository (example, `D:\test\mantid-repos\mantid\Framework\PythonInterface\plugins\algorithms`). Then when I run the release build I get again estimated run times of the order of up to 7 or 8 hours.

**Comment by shahrozahmed1** [comment]
Other than the fact while running the algorithm `EnggCalibrateFull()` was extremely slow on Windows which is not a fault within this branch, some good detailed documentation provided regarding the changes made within this pull request. The `EnggFitPeaksTest`, `EnggCalibrateTest` unit tests and  `EnggCalibrationTest` system test have also been updated accordingly, *luckily for us the system tests are not running on Windows*. The `engggui_difc_zero_peaks_bank_..` plot after calibration on `Engineering Diffraction Interface` look even more smoother with these changes. 

... :shipit: ...

**Comment by AndreiSavici** [comment]
No mention of release notes one way or the other

**Comment by FedeMPouzols** [comment]
This is a low level change that does not need to go in the release notes. More changes follow after this issue and the algorithm specific notes will be updated when that work is finished.

**Pull request merged**
