### PR TITLE
Change sum-banks algorithm to include monitors

### PR DESCRIPTION
**Pull request by gemmaguest**
This PR modifies the ReflectometryISISSumBanks algorithm to copy the monitors from the original workspace into the result. This is required because the result will be used in the ISIS reflectometry reduction workflow algorithms, which assume the input contains monitors.

Part of #34106

**To test:**

- Run this script:
```
ws = LoadNexusProcessed('INTER45455_inst')
ReflectometryISISSumBanks(InputWorkspace=ws, OutputWorkspace='summed')
```
- Check that the monitors have been copied from the original workspace into the summed workspace, i.e. the first 3 spectra are the same (the spectrum numbers are different, which is expected, but the data is the same):
image
- The data should like this:
image

*This does not require release notes* because **it concerns a new algorithm that is not in production use yet**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by sf1919** [comment]
I've done the functional test and the data looks like it should in the table and sliceviewer for both workspaces. I just want to check that the log messages are what you would expect. This is what I'm getting.
Screenshot (200)

**Comment by gemmaguest** [comment]
> I've done the functional test and the data looks like it should in the table and sliceviewer for both workspaces. I just want to check that the log messages are what you would expect. 

Yes, those warnings are fine - it's just that there are unused detectors in the IDF, which end up with invalid detector IDs, so the algorithm that extracts the monitors doesn't know how to handle them. It just ignores them, which is what we want.

**Review by sf1919 — APPROVED** [review]
The changes work as expected and the code looks good.

**Comment by gemmaguest** [comment]
@mantidproject/gatekeepers Could we get this merged as it's blocking other PRs? Thanks.

**Pull request merged**
