### PR TITLE
Drag and Drop feature for Peak Workspaces in the VSI

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Please see the original ticket [#11040](http://trac.mantidproject.org/mantid/ticket/11040)

### CODE REVIEW

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by picatess** [comment]
Jenkins, retest, this please

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by OwenArnold** [comment]
jenkins retest this please

**Comment by OwenArnold** [comment]
I've run the tests for this according to Anton's test script. They all pass.

**Pull request merged**
