### PR TITLE
Error in Doctest for ProcessIndirectFitParameters

### LINKED ISSUE #13441: Error in .rst file for ProcessIndirectFitParameters algorithm causing Doc test failure
There is an error in the .rst file for the new ProcessIndirectFitParameters algorithm, caused by a late addition of a new property which was not accommodated for in the .rst.

### PR DESCRIPTION
**Pull request by ElliotAOram**
Fixes #13441

An extra parameter has been added to the call to ProcessIndirectFitParameters algorithm in the .rst I believe this should fix the issue that was causing the failure.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
The change looks fine. I'll just wait for the `ubuntu + doc tests` build and merge it.

You can also pass parameters by name if you just don't want to give any value to optional parameters, something like `ProcessIndirectFitParameters(..., OutputWorkspace=wsName)`

**Comment by ElliotAOram** [comment]
Thanks,

Do you think it's worth making this change now so that the Doc test is a bit clearer?

Probably best to also check that `ubuntu  + doc tests` actually checks it this time.

**Comment by FedeMPouzols** [comment]
As you prefer really. It's just an alternative. Different doc tests use one or the other, and I guess that different developers/users will prefer / be irritated by any of them. I somehow tend to pass by name, but I'll admit that that can turn simple commands into very long lines.

I'll see if this test is actually run.

**Comment by FedeMPouzols** [comment]
Oh wait, it run and it failed with this:
```
09:44:06 Exception raised:
09:44:06     Traceback (most recent call last):
09:44:06       File "/usr/lib/python2.7/doctest.py", line 1315, in __run
09:44:06         compileflags, 1) in test.globs
09:44:06       File "<doctest ProcessIndirectFitParametersExample[0]>", line 17, in <module>
09:44:06         ProcessIndirectFitParameters(tws, 'A', "B", "" ,wsName)
09:44:06       File "/home/builder/Jenkins/workspace/pull_requests-ubuntu/build/bin/mantid/simpleapi.py", line 729, in algorithm_wrapper
09:44:06         algm.execute()
09:44:06     RuntimeError: Some invalid Properties found
```

**Comment by ElliotAOram** [comment]
I'll take a look at it now

**Comment by FedeMPouzols** [comment]
A few lines up it shows the more detailed logs:
```
09:44:06 PropertyManager-[Error] Property "OUTPUTWORKSPACE" is not set to a valid value: "Enter a name for the Output workspace".
09:44:06 PropertyManager-[Error] Property "OUTPUTWORKSPACE" is not set to a valid value: "Enter a name for the Output workspace".
```

**Comment by FedeMPouzols** [comment]
`Document: algorithms/ProcessIndirectFitParameters-v1` run succesfully in 'ubuntu + doc tests'. No need to wait for other builds that are anyway not going to check this.

**Pull request merged**
