### PR TITLE
Muon ALC - Disable load when editing runs begins

### LINKED ISSUE #30527: Muon ALC - Loading second batch of runs doesn't load them
**Original reporter:** James Lorde

### Expected behavior
The data should be loaded when `Load` is clicked.

### Actual behavior
The data isn't loaded until you click `Load` for a second time. Also the Log is being reset.

### Steps to reproduce the behavior
1. Open Muon ALC interface
2. Instrument is HIFI. Runs 83929-49
3. Click `Load`
4. Select log `sample_mgn_field`
5. Enter a new batch of runs 83951-71
6. Click `Load` 
7. The files are found, but not loaded. You have to click `Load` again for them to load. Also the log is changed back to `run_number`.

### Platforms affected
Found on windows, probably all.

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR fixes two minor bugs:
- One where it takes two clicks of the Load button to load the runs. The problem was caused by the load button being disabled milliseconds before the actual press of the Load button, so it appears it has been pressed when actually it hadn't. The fix was to disable the load button when editing of the runs begins, rather than when the editing of the runs end. This prevents the confusion seen in this issue.
- The sample log being reset whenever new runs are entered. It should just keep the old log when possible.

**To test:**
1. Open Muon ALC interface
2. Instrument is HIFI. Runs 83929-49
3. Press the enter key and wait for the runs to be found.
4. Select log `sample_mgn_field`
5. Click `Load`
6. Enter a new batch of runs 83951-71. The Load button should be disabled when the editing begins.
7. Press the enter key and wait for the runs to be found.
8. When the files are found the Log should have remainded the same `sample_mgn_field` and not have been reset.
7. Click `Load`. It should load it all successfully.

Fixes #30527

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by Matt-Cumber — CHANGES_REQUESTED** [review]
This was a good spot from James. The log saving was going to be fixed next sprint anyway but good to have in the next release. Since we are changing the log selector functionality could we also disable the Plot By Log box when load is pressed, this bug was introduced and missed when merging #30458. It would also be great to have a unit test for setCurrentLog in the view

**Comment by robertapplin** [comment]
> This was a good spot from James. The log saving was going to be fixed next sprint anyway but good to have in the next release. Since we are changing the log selector functionality could we also disable the Plot By Log box when load is pressed, this bug was introduced and missed when merging #30458. It would also be great to have a unit test for setCurrentLog in the view

I have disabled the plot by log box as suggested. The setCurrentLog is a private member function and so cannot be easily tested. Its probably best to leave this for later when a test suite is created for the entire view.

**Review by Matt-Cumber — CHANGES_REQUESTED** [review]
The plot by log box is disabled for me once the data has been found. I'd suggest removing the enablePlotByLogGroup function, and within the enableAll and disableAll functions just include the plotbyloggroup widget (as you have done already with enableAll). I tried this myself and it seems to work okay

**Review by Matt-Cumber — APPROVED** [review]
Thanks for making those changes. Good to go now

**Pull request merged**
