### PR TITLE
Grouping tab should automatically update upon changes to tables

### LINKED ISSUE #25111: Muon GUI should automatically recalculate when groups updated
**Original reporter:** James Lord 

Currently when changes are made to values in the grouping tab you need to click update all to force the GUI to recalculate before the changes can be used. This update should instead happen automatically.

### PR DESCRIPTION
**Pull request by Matthew-Andrew**
**Description of work.**

This updates the new GUI so that when the group or pair tables are changed the data is automatically recalculated. As this then removes the need for the update all button this is removed.

**Report to:** James Lord 

**To test:**
* Open FrequencyDomainAnalysis, select MUSR as the instrument and load a run. If you are not at ISIS 22725 is in the unit test directory
* Go to the grouping tab, make some changes to the groups and pairs table and check that the group and pair workspaces in the ADS are automatically updated.

Fixes #25111  

*This does not require release notes* because it is a change a new GUI

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by TTitcombe — COMMENTED** [review]
In testing, changing data in the pair and group table does update the workspaces in the ADS. If you have a workspace open in Mantidplot then the data is changed without needing to reopen the workspace.

However, if you change a group name a new set of workspaces are created in `MUSR22825 Groups` with the new name, and the old group will still exist. The group table, however, only has the four groups. Not sure if this is intended behaviour or not

**Comment by Mantid-Matthew** [comment]
Currently we never remove anything from the ADS by design, although I do agree that this gets a bit odd when you are renaming things.

I have found a related issue whereby if you add a pair which uses a group and then rename that group you get an error as the pair still looks for the group via the old name when recalculating. I'll look into trying to sorting out both these issues now.

**Comment by Mantid-Matthew** [comment]
Having looked into this further the changing of group and pair names in the GUI is a larger issue than I initially thought as the back-end is not setup to handle group names changing once they are created. I have created a new issue for this here #25168.

**Review by TTitcombe — APPROVED** [review]
Code changes looks good. Changes in group and pair tables update workspaces in the ADS as intended :+1:

**Comment by martyngigg** [comment]
It was asked that this be reported to James Lord when merged.

**Pull request merged**
