### PR TITLE
Add page for StringContainsValidator

### LINKED ISSUE #20832: String constraints validator documentation
In PR #20368, StringContainsValidator was exposed to python. However, it lacks a documentation page :(
In the release notes, there is already an entry for the validator, just need to add a link to the documentation page.

Should be part of 3.11 release

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work**

Adds a page for `StringContainsValidator`.

**To test:**

Build the docs and check that the page for `StringContainsValidator` exists. 

Fixes #20832 

**Release Notes** 

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by KarlPalmen — COMMENTED** [review]
There is no link from the release notes seen in the code review.

**Review by KarlPalmen — CHANGES_REQUESTED** [review]
Unable to find document. A link from the release notes would have been helpful here.

**Comment by NickDraper** [comment]
It's an python API page and does not need to be mentioned in the release notes as it is indexed as part of the python API docs.

**Comment by KarlPalmen** [comment]
I found the built document via search and found it satisfactory.

**Pull request merged**
