### PR TITLE
Add release note regarding last supported Mac OS versions

### LINKED ISSUE #26361: Update release notes to notify move to macOS 10.13 next release
We have not moved the minimum required version of OSX in some time. ORNL now require High Sierra as a minimum and our policy has always been to stay one release behind the most recent but we have slipped in this. Moving to macOS High Sierra brings us back into line and also gives us access to a C++17 compliant compiler.

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

**To test:**

Read the notes.

Fixes #26361.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by robertapplin — APPROVED** [review]
The release notes changes look good 👍

**Comment by DanNixon** [comment]
@martyngigg Is this intended for `release-next`?

**Comment by martyngigg** [comment]
:man_facepalming: Thanks for catching that.

**Comment by martyngigg** [comment]
I've updated the base branch. Thanks.

**Pull request merged**
