### PR TITLE
Add SilverBaseline to fit function

### PR DESCRIPTION
**Pull request by hankwustfc**
Description of work:

Add SilverBaseline to Mantid fit functions.

To test:

1.Test if the documentation is added
2.Test if the fit function is working
3.Test the function with the unit test file
---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by NickDraper — DISMISSED** [review]
Docs, test and code ok

**Review by martyngigg — DISMISSED** [review]

**Comment by martyngigg** [comment]
I've rebased and I just want to check the builds run through as there were some CMake conflicts.

**Review by NickDraper — APPROVED** [review]
code tests and docs ok

**Comment by AnthonyLim23** [comment]
add to release notes in #26827

**Pull request merged**
