### PR TITLE
workbench about dialog

### LINKED ISSUE #28481: Workbench First Use / About Dialog
Create a dialog to merge the first use and help->about dialogs of mantidplot in workbench.

This is a critical path as we need somewhere in the workbench to ask the usage data question in order to be GDPR compliant. So it still needs that functionality and to have the do not show again until functionality.

I suggest we stick to primarily the design for first use and just add in those remaining aspects of help->about that are missing.  There are not many that need adding:

1.  Release Date (Desirable) - this is only shown on full releases, it is in the version otherwise
1. Homepage link (Desirable) - no need there is already a link in the help menu
1. Project members icons (Essential)

Not needed are:
1. Revision
1. Citation (it is in a log message)
1. Release DOI  (it is in a log message)
1. The Mantidplot stuff

### PR DESCRIPTION
**Pull request by NickDraper**
**Description of work.**
Add a Help-> About dialog that combines the functionality of the Help->about and first use dialogs from Mantidplot.

**To test:**
1. Check the links work
1. Check it formats ok on linux (and ideally mac)
1. Check that the do not open until next release works, you can edit the last_version in the workbench.ini to fool it.
1. Check that changing the usage works as it did in mantidplot.

Fixes #28481 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — CHANGES_REQUESTED** [review]
Generally this looks good but I do have a couple of issues.

Screenshot from 2020-04-15 10-37-18

1. On my Ubuntu setup I have the facility/instrument combo boxes show up with a black background. Note that the MantidPlot version is fine.
2. The tooltip for the usage reporting checkbox doesn't show any text but suggests there is some there?
3. Lastly, the usage reporting checkbox does not seem to respect my `usagereports.enabled` config setting. I turned it on in the file, started workbench and the box was unchecked. I then checked the box, closed workbench and on startup the box was unchecked again. I used https://requestbin.com/ each time to verify that mantid itself was always sending the usage report so it was respecting my config setting.

**Review by martyngigg — CHANGES_REQUESTED** [review]
This looks much better now w.r.t to my previous points and the layout without the custom fonts looks good to me. :+1: 

I have one final issue, the dialog pops up every single time I start workbench - I assume this was not intended? I tried both leaving facility set to ISIS and selecting WISH as an instrument and also selecting SNS as facility and DAS as instrument. I confirmed that the properties file has the updating settings but restarting workbench still shows the about box again.

**Comment by NickDraper** [comment]
> I have one final issue, the dialog pops up every single time I start workbench - I assume this was not intended? I tried both leaving facility set to ISIS and selecting WISH as an instrument and also selecting SNS as facility and DAS as instrument. I confirmed that the properties file has the updating settings but restarting workbench still shows the about box again.

I've looked into the code, and it is pretty much an identical port from Mantidplot to workbench, so I suspect that you just clicked the do not show box so long ago you forgot about it.

Workbench: presenter.py Lines 57-92
Mantidplot: ApplicationWindow.cpp lines 603-660

**Review by martyngigg — APPROVED** [review]
I think you are correct. I mostly likely ticked the don't show option so long ago I'd forgotten about it.

Good to go.

**Pull request merged**
