### PR TITLE
14955 stretched exp ft origin

### LINKED ISSUE #14955: StretchedExpFT peak centre is not a parameter
Spencer has found a bug in StretchedExpFT:
> The peak centre/origin is not a parameter.
So in a convolution where sample & resolution are offset it doesn't get it correct.

### PR DESCRIPTION
**Pull request by jmborr**
Fixes #14955 

To test:
- Review code changes
- Load the files from the Usage Example of the Documentation into MantidPlot, and setup the appropriate model in the Fit-Window widget. Then, change the "origin" parameter and then Plot-Guess to check that the curve shifts along the X-axis.

Release notes in [here](http://www.mantidproject.org/ReleaseNotes_3_6_Framework_Changes#Improved_2)

### CODE REVIEW

**Comment by ElliotAOram** [comment]
@jmborr I've tested the changes and they all work as described, so I'm happy to merge when the tests pass.
Looks like it might be something to do with FitFunction.CodeConventions (http://www.mantidproject.org/Mantid_Standards). not exactly sure, but perhaps to do with the parameter naming?

**Comment by jmborr** [comment]
I renamed parameter "Origin" to comply with naming conventions for fit-function parameters

**Comment by ElliotAOram** [comment]
I have checked this again (just to be sure) and it works as described. Happy to merge.

**Comment by jmborr** [comment]
@ElliotAOram Thanks a lot for reviewing.

**Pull request merged**
