### PR TITLE
Engg::Add "cropped" calibration in EnggDiffraction 

### LINKED ISSUE #14591: Add "cropped" calibration in EnggDiffraction
Similar to "focus cropped", have two fields:
- a run-number(s) field  (in a box that is disabled by default) where you can give a range of spectrum IDs for the calibration (the non-full calibration).
- A bank name

The bank name must be used following the old conventions to generate GSAS files.

So the calibration has 2 mandatory parameters:
- Vanadium run
- calibration sample (Ceria)
+ 2 optional parameters (in a "advanced/partial calibration" box:
- Bank name
- Spectrum IDs

### PR DESCRIPTION
**Pull request by shahrozahmed1**
Fixes #14591 

**This should be merged after the following pull request has been merged #14904**
- [x] _#14904 merged_

This branch will enable `Interface/Diffraction/Engineering Diffraction/Calibration/``Calibration Cropped` to be processed, vanadium run number under `Cropped Calibration` which will be reading from the vanadium field, & user are unable to modify, the `specIds` selected are passed to the `EnggCalibration`.  

**To Test**
- Code Check
- GUI: `Calibration Cropped Sample #:` updated as soon as new Ceria is changed under `Make New Calibration` section
- GUI: `Spectrum IDs:` only enabled if the `Bank Name:` is set as `Enable Spectrum-IDs`
- The files are still generated how they are generated for standard calibration
- Make sure additional parameter is being passed when `Cropped Calibration` process is carried out

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
Code looks good and it comes with good documentation about the new "cropped" type of calibration. It is well integrated with the view/presenter with a new notification. The calibration is working well and the output file is generated correctly. We have to modify how the output par/prm file is produced, and now that we have this "cropped" calibration it may require a name suffix or small changes to the output file, but that's a subject for other issues (like #14594).
@shahrozahmed1 : I've opened another issue to add tests for this new functionality: #14923.

**Comment by FedeMPouzols** [comment]
@shahrozahmed1 : also, the browse button of the calibration run number in "cropped calibration" remains grayed-off/disabled for me. Let's check this when you're back. It might be a platform specific issue.

**Comment by shahrozahmed1** [comment]
@FedeMPouzols the browse button of the cropped calibration run number is greyed-out purposely as it will be reading from sample run number and updating that in the text box, just thought it is bit more logical to do that. However if you would like me to enable it, I can do in one of the issues I am working on.

**Comment by FedeMPouzols** [comment]
Ah, I see, it makes sense.

**Pull request merged**
