### PR TITLE
Rename Data Analysis to QENS Fitting

### LINKED ISSUE #36363: Rename Inelastic Data Analysis GUI to QENS Fitting
Requested by: Spencer & Sanghamitra

**Describe the outcome that is desired.**
We want to rename the Inelastic Data Analysis GUI to QENS Fitting so it has a better description of what it does.

As well as renaming the GUI, we also want to rename the files and classes that make-up the GUI. This also means we want to rename some of the tests and test classes.

We should also make sure the documentation file is updated and a release note is added.

**Acceptance Criteria**
- The Analysis interface is accessible as the "QENS Fitting" interface in the inelastic category
- The Analysis file names, and contents of the files, use the term `Inelastic` instead of `Indirect`. It should also use `QENSFitting` term instead of `Analysis` where appropriate.

### PR DESCRIPTION
**Pull request by robertapplin**
### Description of work
This PR renames the Inelastic Data Analysis interface to Inelastic QENS Fitting because it provides a better description of what the interface actual does. This PR also renames a lot of the files, and folder locations related to this interface. The interface documentation is also updated.

Fixes #36363

### To test:
Read through the QENS Fitting interface documentation and follow the workflow examples.

Check that the `QENS Fitting` interface now exists in the `Inelastic` category.

Follow the following test instructions
https://developer.mantidproject.org/Testing/Inelastic/DataAnalysisTests.html

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by SpencerHowells** [comment]
@robertapplin the tabs themselves need changing. The word 'fitting' is redundant. ConvFit becomes Convolution and F(Q) becomes Function(Q).

**Comment by robertapplin** [comment]
> @robertapplin the tabs themselves need changing. The word 'fitting' is redundant. ConvFit becomes Convolution and F(Q) becomes Function(Q).

I have a separate issue recorded here https://github.com/mantidproject/mantid/issues/36853

**Review by adriazalvarez — CHANGES_REQUESTED** [review]
Thanks for renaming so many files! I like the new name better, and so other naming changes are also very good. The interface works ok, and the documentation is updated with the new reference (unless some `Data Analysis` ref has escaped me).
One thing, I don't see a release note?  
Also I'm not so sure about re-referencing the old release notes. Should we say in the old release notes (`:ref:QENS Fitting (previously Data Analysis)` <...>`)?  I'm not sure. I ask your opinion.

**Comment by robertapplin** [comment]
> One thing, I don't see a release note? Also I'm not so sure about re-referencing the old release notes. Should we say in the old release notes (`:ref:QENS Fitting (previously Data Analysis)` <...>`)? I'm not sure. I ask your opinion.

Good point, I'll add a release note! I think we shouldn't bother about changing the interface name in the old release notes (as long as the link works!)

**Review by adriazalvarez — APPROVED** [review]
Thanks for the changes.

**Pull request merged**
