### PR TITLE
Add inelastic discus workflow algorithm

### LINKED ISSUE #33723: Add Discus workflow algorithm for simple shapes
Spencer Howells has put together a python algorithm that acts as a wrapper around DiscusMultipleScatteringCorrection and calls SetSample first. The algorithm is called SimpleShapeDiscusInelastic
The parameter names are tuned for inelastic users
This issue covers work to create tests\documentation for the algorithm and create a PR to get this reviewed and merged

[SimpleShapeDiscusInelastic.zip](https://github.com/mantidproject/mantid/files/8397515/SimpleShapeDiscusInelastic.zip)

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

Add workflow algorithm called SimpleShapeDiscusInelastic created by Spencer Howells. The new algorithm calls DiscusMultipleScatteringCorrection for some simple sample shapes. I've added a documentation page and a unit test suite

**To test:**

1) Load these two files which are part of the Mantid unit test data files:
- irs26176_graphite002_red.nxs
- iris26176_graphite002_sqw.nxs
2) Open up the SimpleShapeDiscusInelastic algorithm dialog and run with the following parameters:

image

The algorithm should complete successfully and generate a workspace group called "MuscatResults"

Fixes #33723.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by SpencerHowells** [comment]
@DannyHindson In validateInputs I couldn’t work out how to test for ChemicalFormula.

**Comment by DannyHindson** [comment]
> @DannyHindson In validateInputs I couldn’t work out how to test for ChemicalFormula.

I hadn't noticed those couple of lines commented out. If you add a not it will work ie `if not self._chemical_formula:`. I'll push a further change now to include that

**Review by cailafinn — COMMENTED** [review]
Code all looks good, just a quick functional question:
- Would it be possible to add progress reporting? As it stands it isn't obvious how far the algorithm has progressed, though I understand that may be a limitation of the called algo rather than this one.

**Comment by DannyHindson** [comment]
> Code all looks good, just a quick functional question:
> 
> * Would it be possible to add progress reporting? As it stands it isn't obvious how far the algorithm has progressed, though I understand that may be a limitation of the called algo rather than this one.

Firstly - apologies for the typos in the file names. Hope that didn't hold you up. I've just corrected them.
I didn't know this until now but it seems like if you add startProgress and endProgress parameters to calls to child algorithms made via the simpleapi, the progress from the child algorithm gets reported up to the parent algorithm. So I've just made this change and seems to work nicely. The Discus algorithm takes up almost all the time so have just hooked up progress reporting from that child algorithm

**Review by cailafinn — APPROVED** [review]
Looks good to me now! That's also really good to know about adding progress reporting. Nice work 👍

**Pull request merged**
