### PR TITLE
Algorithm to save as open-genie ascii files

### LINKED ISSUE #13497: Algorithm to save OpenGenie ascii files
Call it `SaveOpenGenieAscii`, `SaveFocusedOpenGenieAscii` or similar.
This will go to `Framework/DataHandlers`.

- Input: a (matrix) workspace (we'll be using it for focused workspaces an example of which is `ENGINX00213855focussed.nxs`). You can also use example `engggui_focusing_output_ws` workspaces from the Engg GUI focus tab.
- Output: an OpenGenie ascii file (ask me for a example file that we got from ENGINX scientists).

The algorithm has to write:
- for every spectra:
  x axis, y axis, error axis (which go as variables `x`, `y` and `e`
- all the logs available in the workspace
- all these variables are written sorted by alphabetical order (see the example file).

As a first version we can just assume that there's only one spectrum, as in focused workspaces. If there are more: give error message and fail. This may be all we need, as we are only saving focused workspaces for now.

The algorithm should come with a documentation page (rst) and a unit test. These two items can be included as part of this issue or can be done as sibling issues.

I'd put a warning note in the algorithm documentation saying that this algorithm is being developed for a particular purpose (interfacing with ENGIN-X OpenGenie scripts) and is under development/testing.

### PR DESCRIPTION
**Pull request by shahrozahmed1**
Fixes  #13497

**To Test**
- Input: a (matrix) workspace 
- Execute `SaveOpenGenieAscii` with the input workspace
- Save the OpenGenie ascii file where appropriate

### CODE REVIEW

**Comment by shahrozahmed1** [comment]
@FedeMPouzols As we decided yesterday that, this can be considered as a pull request because it is still useful to save the `x`, `y` and `e` axis in OpenGenieAscii format and could be merged for Release 3.5.. and I can create another issue to include the all the logs available in the workspace inside the 2nd version of `SaveOpenGenieAscii` file for Release 3.6.

**Comment by FedeMPouzols** [comment]
@shahrozahmed1 : that makes sense, we can merge this in by the end of the week, so a basic version of this algorithm is already introduced in 3.5.

**Comment by FedeMPouzols** [comment]
Code looks good, it works well and it comes with a doc test. This should be a solid starting point for the algorithm.

I think that there is an issue in the number written after `GXWorkspace`. The algorithm is writing the number of spectra, `nSpectra`, where it should be writing the number of entries or variables that are dumped into the ascii file (in the example that we got it happened to be 87 but in this case it would always be 3, for x,y, and e).

Maybe you could also add a small sentence in the documentation to clarify the behavior of the algorithms, as it says that it saves focused data. So you could add that it assumes focused data (a single spectrum) but if a workspace with multiple spectra is passed it will save the first spectrum and ignore the others.

Also, a minor coding conventions point: for methods we use camelCase with lowercase for the first letter, so `WriteToFile` would be `writeToFile`, etc. That can be fixed here or later.

Oh, and remember to add the [new algorithm](http://www.mantidproject.org/ReleaseNotes_3_5_Framework_Changes#New) in the release notes.

**Comment by stuartcampbell** [comment]
I was just wondering, what OpenGENIE format was used to produce this output file - I think that the algorithm should be named something less generic as it looks like something specific to ENGINX ?

**Comment by FedeMPouzols** [comment]
@stuartcampbell: My understanding/guess is that the example that they gave us is produced simply as a dump of the OpenGenie workspace/session into an ascii file. They were using binary files which they don't know well. But then they found that their scripts also manage to load these ascii files.
I'm trying to clarify with them what exact command or script they used.

To be on the safe side this could start as SaveEnggOpenGenieAscii and then be renamed if it turns out to be sufficiently general. My impression is that this algorithm would be usable to pass Mantid workspace data to OpenGenie for whatever legacy scripts. Not sure if that's a good idea at all though!

**Comment by FedeMPouzols** [comment]
Got this examples from Saurabh:

Open Genie – reading writing ‘his’ files in different formats:

Read bin/ascii format:
```
w=get(1,"C:\\Engin-X\\focus\\ENGINX999682_2.his")
printn w
printn w.x
```
Read hdf format:
```
w2=get(0,"C:\\Engin-X\\focus\\example.dat")
printn w2.label.x
```
Writing array to file:
```
Set/file/Output "C:\\Engin-X\\focus\\example.dat"
put /New w label="label" comment="comment" (bin format) 
put /New /hdf w label="label" comment="comment" (hdf format) 
put /New/ASCII w label="label" comment="comment" (ascii format) 
```
There should be a note in the documentation that this algorithm writes files in OG ascii format as saved by `put /New/ASCII...`.

**Comment by stuartcampbell** [comment]
@FedeMPouzols - looking at the example writing, I think leaving the name as is, is a good idea.  I just wanted to check that there was nothing ENGINX specific, which there isn't - sorry.

**Comment by FedeMPouzols** [comment]
Good to have a first working version of the algorithm already in 3.5!

**Pull request merged**
