### PR TITLE
Fixes compilation error with boost 1.58

### PR DESCRIPTION
**Pull request by mganeva**
Minor changes: template specifications have been removed from the boost::bind statements to fix the compilation error with boost 1.58.

### CODE REVIEW

**Comment by rosswhitfield** [comment]
I tested this with boost 1.58 on ArchLinux and it fixes the build. :+1: I don't see why this bugfix shouldn't be included in release 3.4.

**Comment by stuartcampbell** [comment]
:+1:

**Comment by MichaelWedel** [comment]
Okay, then I'll go on and merge it. I just thought with the code-freeze and all...

**Comment by quantumsteve** [comment]
Please put this in release 3.4. Homebrew has an open pull request to upgrade boost to 1.58 (https://github.com/Homebrew/homebrew/pull/38743) so this will affect our build servers in the near future.

**Pull request merged**
