### PR TITLE
Add back to back exponential usage example to PDCalibration

### LINKED ISSUE #31800: Add BackToBackExponential usage example to PDCalibration
As requested by Pete Peterson. Richard supplied this script on Slack:
```
Load(Filename=r'\\isis.cclrc.ac.uk\inst$\ndxenginx\instrument\data\cycle_12_4\ENGINX00193749.nxs', 
     OutputWorkspace='193749')
dpks = (1.913220892, 1.631600313, 
            1.562138267, 1.352851554, 1.104598643)
PDCalibration(InputWorkspace='193749',
            TofBinning=[10000,-0.0005,46000], 
            PeakPositions=dpks,
            PeakWindow = 0.03,
            MinimumPeakHeight = 0.5,
            PeakFunction = 'BackToBackExponential',
            CalibrationParameters = 'DIFC',
            OutputCalibrationTable='cal_B2B_DIFC_chisqTrue',
            DiagnosticWorkspaces = 'diag_B2B_DIFC_chisqTrue',
            UseChiSq = True)
```

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

Added a further usage example to the PDCalibration documentation showing use with the BackToBackExponential peak function

**To test:**

Review change and check Jenkins doc tests pass

Fixes #31800. 

*This does not require release notes* because **there's no functional change**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DannyHindson** [comment]
@peterfpeterson - as discussed earlier this week

**Comment by rosswhitfield** [comment]
And Pete is back on vacation... I think the thing he was looking for in the example was how to create and specify the starting parameters of the BackToBackExponential for PDCalibration, that's the bit that was missing. Having a look myself, is this all just specified in the instrument parameter file, like https://docs.mantidproject.org/nightly/concepts/InstrumentDefinitionFile.html#using-fitting-parameter?

**Comment by DannyHindson** [comment]
Yes - specifically the part where it describes the `<formula>` tag. Here's the ENGIN-X parameter file where Richard set this up. Shall I add that link into the PDCalibration documentation page somewhere?
```
<?xml version="1.0" encoding="UTF-8" ?>

<!--If North and South banks require different Bk2Bk params,
the create a distinct ENTITY for each bank-->

<!DOCTYPE parameter-file [
        <!ENTITY alpha "0.0968">
        <!ENTITY beta_0 "0.0216">
        <!ENTITY beta_1 "0.0123">
        <!ENTITY sigma_0_sq "0.0">
        <!ENTITY sigma_1_sq "82.1321">
        <!ENTITY sigma_2_sq "42.5988">
]>

<parameter-file instrument="ENGIN-X" valid-from="2020-10-23">


<component-link name="NorthBank" >

  <parameter name="alpha" type="number">
    <value val="&alpha;" />
  </parameter>
  <parameter name="beta_0" type="number">
    <value val="&beta_0;" />
  </parameter>
  <parameter name="beta_1" type="number">
    <value val="&beta_1;" />
  </parameter>
  <parameter name="sigma_0_sq" type="number">
    <value val="&sigma_0_sq;" />
  </parameter>
  <parameter name="sigma_1_sq" type="number">
    <value val="&sigma_1_sq;" />
  </parameter>
  <parameter name="sigma_2_sq" type="number">
    <value val="&sigma_2_sq;" />
  </parameter>

  <parameter name="BackToBackExponential:S" type="fitting">
    <formula eq="sqrt((&sigma_2_sq;)*centre^4+(&sigma_1_sq;)*centre^2+(&sigma_0_sq;))" unit="dSpacing" result-unit="TOF" />
  </parameter>
  <parameter name="BackToBackExponential:A" type="fitting">
    <formula eq="((&alpha;)/centre)" unit="dSpacing" result-unit="1/TOF" /> <fixed />
  </parameter>
  <parameter name="BackToBackExponential:B" type="fitting">
    <formula eq="((&beta_0;)+(&beta_1;)/(centre^4))" unit="dSpacing" result-unit="1/TOF" /> <fixed />
  </parameter>

</component-link>

<component-link name="SouthBank" >

  <parameter name="alpha" type="number">
    <value val="&alpha;" />
  </parameter>
  <parameter name="beta_0" type="number">
    <value val="&beta_0;" />
  </parameter>
  <parameter name="beta_1" type="number">
    <value val="&beta_1;" />
  </parameter>
  <parameter name="sigma_0_sq" type="number">
    <value val="&sigma_0_sq;" />
  </parameter>
  <parameter name="sigma_1_sq" type="number">
    <value val="&sigma_1_sq;" />
  </parameter>
  <parameter name="sigma_2_sq" type="number">
    <value val="&sigma_2_sq;" />
  </parameter>

  <parameter name="BackToBackExponential:S" type="fitting">
    <formula eq="sqrt((&sigma_2_sq;)*centre^4+(&sigma_1_sq;)*centre^2+(&sigma_0_sq;))" unit="dSpacing" result-unit="TOF" />
  </parameter>
  <parameter name="BackToBackExponential:A" type="fitting">
    <formula eq="((&alpha;)/centre)" unit="dSpacing" result-unit="1/TOF" /> <fixed />
  </parameter>
  <parameter name="BackToBackExponential:B" type="fitting">
    <formula eq="((&beta_0;)+(&beta_1;)/(centre^4))" unit="dSpacing" result-unit="1/TOF" /> <fixed />
  </parameter>

</component-link>

</parameter-file>
```

**Comment by rosswhitfield** [comment]
Yeah, it would good to include this information.

**Review by rosswhitfield — APPROVED** [review]

**Pull request merged**
