### PR TITLE
Reduce SCDCalibratePanels errors

### LINKED ISSUE #14915: SCDCalibratePanels errors
Check why errors in table are so large.  Make second pass with l0 and t0 fixed from average of first pass and make sure table has the same values for all detectors.  DetCal file should have lines for all detectors for AllPanelsInOneGroup option.  Output cell parameters after DetCal is applied and they should be less than 0.05 from input.  Need plots like ISAW's.

### PR DESCRIPTION
**Pull request by VickieLynch**
Fixes #14915 

To test use [peaks.txt](https://github.com/mantidproject/mantid/files/132980/peaks.txt)

``` python
LoadIsawPeaks(Filename='peaks.txt', OutputWorkspace='peaks')
SCDCalibratePanels(PeakWorkspace='peaks', a=6.516, b=18.948, c=9.7609999999999992, alpha=90, beta=108.98, gamma=90, DetCalFilename='LM.DetCal', ResultWorkspace='LMResults', ColWorkspace='LMCol', RowWorkspace='LMRow', TofWorkspace='LMTof', MinimizerError=1.0e-05, NumIterations=5000)

LoadIsawPeaks(Filename='peaks.txt', OutputWorkspace='peaks')
SCDCalibratePanels(PeakWorkspace='peaks', a=6.516, b=18.948, c=9.7609999999999992, alpha=90, beta=108.98, gamma=90, DetCalFilename='Simplex.DetCal', ResultWorkspace='SimplexResults', ColWorkspace='SimplexCol', RowWorkspace='SimplexRow', TofWorkspace='SimplexTof', MinimizerError=1.0e-05, NumIterations=5000)
```

### CODE REVIEW

**Comment by VickieLynch** [comment]
[peaks.txt](https://github.com/mantidproject/mantid/files/132980/peaks.txt)

**Comment by VickieLynch** [comment]
http://www.mantidproject.org/ReleaseNotes_3_7_Diffraction#Crystal_Improvements

**Comment by AndreiSavici** [comment]
@VickieLynch Neither the issue, nor the pull request explain what you are doing. What does "make the errors smaller" means? I can just multiply the errors by 0.1, and I solved the issue. I assume that you have some physical meaning for your changes, but I did not find the documentation.

**Comment by VickieLynch** [comment]
@AndreiSavici By smaller, I mean make the calibration better.  In the issue I have a list of problems with this calibration found by Xiaoping which were all fixed.

**Comment by VickieLynch** [comment]
3 vectors output are center of bank, and two vectors of bank corner (base and up)

**Comment by FedeMPouzols** [comment]
This branch has developed a merge conflict with master.

**Comment by VickieLynch** [comment]
Have MANDI peaks file and ISAW's output calibration for these peaks. Comparing with Mantid's calibration.

**Pull request merged**
