### PR TITLE
Ornl Refactor the ORNL SANS Code

### LINKED ISSUE #22560: Refactor the ORNL SANS Code
End with the `properties` for the workflow: `Setup*` and `*Reduction`.

To be updated!
Depends on #24290

### PR DESCRIPTION
**Pull request by jmborr**
Fixes #22560

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by jmborr** [comment]
@ricleal I'm looking now...

**Comment by jmborr** [comment]
@Mantid-Matthew Hi Matt, can you please check that test `scripts/tests/SANS/gui_logic/table_model_test.py::test_serialise_options_dict_correctly` is doing what you intend to do?
It seems that you are comparing serialization of a python `dict` to a string. However, serialization will not always give the same result because there's no guarantee of the order in which the (key, value) pairs are accessed. See method `OptionsColumnModel._serialise_options_dict` that does the serialization work

**Comment by jmborr** [comment]
@Mantid-Matthew thank you! I just rebased master onto this branch

**Comment by ricleal** [comment]
I will fix this on monday

**Comment by ricleal** [comment]
@jmborr It's been like this for a while... :(

**Comment by jmborr** [comment]
@ricleal :smile: thanks for taking care of updating the branch!

**Comment by ricleal** [comment]
@jmborr There's errors in our rewrite! The merge failed I think. Give a few hours to check what went wrong.

**Comment by ricleal** [comment]
# DO NOT USE MERGE ON THIS BRANCH

Use:
```
git checkout master
git pull origin master
git checkout ORNL_SANS
git rebase -i master
git push -f
```

**Comment by jmborr** [comment]
@ricleal why shouldn't we use `merge`?

**Comment by ricleal** [comment]
@jmborr `rebase` applies our branch on top of master, so when you do `git log` you see our changes on top. Merges I think it merges by date, all changes are scattered and difficult to visualise... Besides Mantid uses `rebase` in the workflow.
Whatever we choose we need to stick to it, I spent 1h solving conflicts this morning :(

**Comment by jmborr** [comment]
Unless I am very mistaken, I think that we are going to be spending 1h solving the very same conflicts every time we rebase our branch onto master.

**Comment by ricleal** [comment]
@jmborr Misteriouly if I rebased from origin I have conflicts ... however if I pull master and then rebase locally to master I have no issues.... strange isn’t it?

**Comment by jmborr** [comment]
@ricleal curious, I did the rebase with no problems, even though it grabbed 291 commits from master

**Comment by ricleal** [comment]
@jmborr I think our branch is haunted :)

**Comment by NickDraper** [comment]
@ricleal @jmborr Hello,  This looks to be a pretty substantial rewrite.  Personally I'd be a bit uncomfortable including a change of this scale after the code freeze.  Let me know your thoughts.

**Comment by jmborr** [comment]
@NickDraper granted it's a large number of commits. Maybe when it's time to merge we could split the changes into a set of issues and then add merge one issue at a time. At any rate we won't get to that decision for the next three months

**Comment by NickDraper** [comment]
I've set a tentative milestone for this to be R4.1 then, just to be clear it is not the current release.

**Comment by jmborr** [comment]
@ricleal I am going to update `ORNL_SANS` with latest master. [This recent pull request](https://github.com/mantidproject/mantid/pull/25012) fixes the Flake8 warnings that are preventing your latest changes to be checked by the build servers

**Pull request closed without merging**
