### PR TITLE
Compile from Windows using Ninja

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR makes it possible to compile mantid from a windows environment using the Ninja generator.

**To do:**
- [X] Ability to configure and generate a Ninja build from the command line
           `cmake --preset=win-ninja .`
- [X] Ability to build mantid from the command line
           `cmake --build .`
- [X] Ability to open mantid from the command line - https://github.com/mantidproject/mantid/pull/34155
           `python bin/workbench-script.pyw` 🟢 
           `bin\MantidWorkbench.exe` ❌ - but this doesn't work in a normal windows build either
           `bin\workbench.exe` 🟢 
- [x] Ability to run the system tests from the command line
           e.g. `systemtest -R AlgorithmDialogsMatrixWorkspaceStartupTest`
- [x] Ability to run the unit tests from the command line
           e.g. `ctest -R test_colorbar -V`
- [x] Ability to build the documentation from the command line (and other targets)
           `cmake --build . --target docs-html`
           `cmake --build . --target docs-qtassistant`
           `cmake --build . --target docs-qthelp`
- [X] Check for speed-up benefits when making code changes and then building
    - When running the system tests after making no changes, it is quicker to recognise it doesn't need to update the test data
    - When building, it seems to be quicker as it only builds what needs to be rebuilt

**To test:**
From a new clone and a new build directory:

1. Open `x64 Native Tools Command Prompt for VS 2019` from the windows search menu
2. Activate your conda enviroment
3.  From the source directory:
```
cmake --preset=win-ninja .
```
5. From the build directory:
```
cmake --build .
```
6. Open the `command_prompt.bat` in your build folder, and attempt to run a systemtest and unittest
7. Open workbench from cmd using `python bin/workbench-script.pyw`

Part of #33801

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DanielMurphy22** [comment]
Setting the environment by opening the correct command prompt seems similar to the command varsall amd64 command here: https://github.com/mantidproject/mantid/blob/main/buildconfig/windows/command-prompt.bat.in

**Comment by robertapplin** [comment]
Running the system tests from the cmd line now seems to be working for me e.g.
```
systemtest -R AlgorithmDialogsMatrixWorkspaceStartupTest
```
Using the `-C` flag should show a warning saying that it isn't required for a Ninja-generated build.

I have also tried running the unit tests and they also seem to work, with or without a configuration:
```
ctest -C Release -R test_colorbar -V
```
or
```
ctest -R test_colorbar -V
```

@DanielMurphy22 Would you be able to check this for me whenever you have a spare moment? (no rush)

**Comment by robertapplin** [comment]
Documentation seems to build fine too!

**Comment by robertapplin** [comment]
Closed and replaced by #34467

**Pull request closed without merging**
