### PR TITLE
More work on SNSPowderReduction workflow diagram

### LINKED ISSUE #15074: Correct errors in SNSPowderReduction's workflow diagram

### PR DESCRIPTION
**Pull request by wdzhou**
Fixes #15074.

### CODE REVIEW

**Comment by wdzhou** [comment]
For tester:  Please check the documentation for SNSPowderReduction.  The workflow diagrams there are more complete and accurate than before.

**Comment by KarlPalmen** [comment]
Your branch name does have the issue number first according to our convention and so has taken longer than usual from me to find.

**Comment by KarlPalmen** [comment]
I cannot find SUNSPowderReduction in current documentation http://docs.mantidproject.org/nightly/algorithms/index.html and so can only determine whether your workflow diagrams there are more complete and accurate than before by checking the commits and the code they document.

**Comment by KarlPalmen** [comment]
I cannot find SNSPowderReduction in the current documentation at http://docs.mantidproject.org/nightly/algorithms/index.html so can only test that
workflow diagrams there are more complete and accurate than before
by looking at your commits and the corresponding code.

**Comment by KarlPalmen** [comment]
I found some errors in the SNSPowderReduction workflow chart. `RunNumber`, `Sum` and `Have MPI` don't connect to anything and the chart does not end with a yellow oval.

**Comment by wdzhou** [comment]
All the reported issues have been fixed.

**Comment by KarlPalmen** [comment]
I'll test this tomorrow morning, taking care to use the release 3.6 branch.

**Comment by KarlPalmen** [comment]
Testing as normal then merging into release branch.

**Comment by KarlPalmen** [comment]
Flow charts now appear to have correct syntax.

**Pull request merged**
