### PR TITLE
New load widget for Elwin Tab

### LINKED ISSUE #29536: Elwin input
The Elwin tab of QENS data analysis can only accept files, when all of the other tabs can select from workspace. This issue is to allow Elwin to select data from a workspace.

### PR DESCRIPTION
**Pull request by sf1919**
**Description of work.**
A new loader for Elwin has been developed. Users can choose whether to upload from a file or use an exisiting workspace. 

**To test:**
1. Open Mantid and navitgate to Interfaces/Indirect/Data Analysis
2. The Elwin tab is the default when opening the Data Analysis GUI. Please check the GUI looks as per image below

Screenshot (16)

3. Download the Elwin dataset from PR #26631 
4. Click 'Browse' and navigate to where you downloaded irs26176_graphite002_red.nxs. Choose it to load file. Data should load in the plotting area below and no error messages should occur.
5. Click Run towards the bottom of the screen. 3 new workspaces should have been added to the Workspace list ending with '_elf', '_eq', and '_eq2' respectively. No error messages should occur.
6. Close the GUI
7. Reopen the GUI
8. Change the drop down on the left from File to Workspace. The GUI interface should change and look as per the image below.

Screenshot (17)

9. Click on Add Workspace
10. Change the dropdown to Workspace and you should be able to add irs26176_graphite002_red. Tick All Spectra and press Add.
11. Click Close on the Workspace Dialog. The Table should now have all the Spectra listed.
12. Change the Spectrum in the plotting area below using the up/down button toggles. 
13.  Click Run towards the bottom of the screen. 3 new workspaces should have been added to the Workspace list ending with '_elf', '_eq', and '_eq2' respectively. No error messages should occur.

Fixes #29536 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by SpencerHowells** [comment]
@sf1919 Would you like this road tested? If so, I usually get an UnstableBuild.

**Comment by sf1919** [comment]
> 
> 
> @sf1919 Would you like this road tested? If so, I usually get an UnstableBuild.

That would be great @SpencerHowells . I have created an unstable windows build for you in Jenkins at https://builds.mantidproject.org/job/pull_requests-windows/45307/ . Please note though that the layout of the Input part of the Elwin tab is not correct. I've made some further changes so that it fill the tab but they are not in version of the unstable build. They will be included in the next commit.

I'm currently working on tests so there will be at least one (if not more) commits to come. That being said now is a good time for you to do some user testing so many thanks :)

**Comment by SpencerHowells** [comment]
@sf1919 Loading .red files seems to be Ok. Trying .raw crashes Mantid. Also in the Browse window the Filter should now include .raw.

**Comment by SpencerHowells** [comment]
@sf1919 Sarah - forget the last comment - misread the details in the heat! Both file & workspace input seem to be Ok.

**Comment by SpencerHowells** [comment]
@sf1919 If I load a .red file it runs. If I then load from the workspace it runs Ok. However if I try to go straight into loading from WS  without doing a file first it shows the spectra but the ws name is not shown in the drop-down menu & there is no preview plot.

**Comment by sf1919** [comment]
> 
> 
> @sf1919 If I load a .red file it runs. If I then load from the workspace it runs Ok. However if I try to go straight into loading from WS without doing a file first it shows the spectra but the ws name is not shown in the drop-down menu & there is no preview plot.

Presumably when you are trying to load WS the second way there are no WS already loaded into Mantid? The WS load is checking what workspaces are available to you already but if you haven't loaded any WS into your current instance it's not going to find any. 

Could you check something that worked for me just to be certain? Can you
- Open the Indirect Data Analysis GUI
- Load from a file in the Elwin Tab
- Close the GUI
- Reopen the GUI
- Try to load a workspace
In theory that should work because the original file remains as a workspace in Mantid until you clear the workspaces or close Mantid as a whole.

**Comment by SpencerHowells** [comment]
@sf1919 When I do that the workspace box shows all the spectra. However the Preview file list is blank & there is no plot.
image

**Comment by sf1919** [comment]
Thanks for testing @SpencerHowells . Definitely a problem here so will continue working on this. Will contact you once its ready for testing again - if you're ok to test it again?

**Comment by SpencerHowells** [comment]
@sf1919 Always willing to test!

**Review by SilkeSchomann — APPROVED** [review]
Code looks good and functionality as expected

**Comment by sf1919** [comment]
@mantidproject/gatekeepers please can this be merged in? It's currently blocking PR #32069

**Pull request merged**
