### PR TITLE
MatrixWorkspace::maskBins  Replace NaN with 0.

### LINKED ISSUE #16948: Masking to replace also NaN with 0
### Expected behaviour
Masking should 0 down also the NaN values/errors, if present.

### Actual behaviour
Masking is not replacing NaN with 0.

### Steps to reproduce the behaviour

* Load/create a workspace with some NaN values.
* Mask the bins containing NaN with MaskBins or MaskDetectors.

### Platforms affected
ALL

### PR DESCRIPTION
**Pull request by gvardany**
This PR replaces NaN/Inf values/errors with 0 during the masking with non-0 weight.

**To test:**

- Load/create a workspace with some NaN values.
- Mask the bins containing NaN with MaskBins or MaskDetectors.

Fixes #16948.

[RELEASE NOTES](https://github.com/mantidproject/mantid/blob/16948_MatrixWorkspace_maskBins_replaceNaNwithZero/docs/source/release/v3.8.0/framework.rst#id17) 

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by tom-perkins** [comment]
Tested with both `MaskBins` and `MaskDetectors`. In both cases NaNs were changed to zeros in bins that were masked.

- What should happen to Inf values? With `MaskDetectors` they are converted to zero too, but with `MaskBins` the Inf was changed into a NaN.
- Is it possible to add a test to `MatrixWorkspaceTest` for this case?

**Comment by gvardany** [comment]
@tom-perkins Thanks for pointing this out. I have added a similar treatment also for `Inf` values.
Moreover, when the weight is 0, `maskBins` should be just equivalent to `flagMasked`, so the values should be conserved, including `NaN` and `Inf`. I have added the test. Please test again, now there should not be difference between what you get from `MaskBins` and `MaskDetectors`.

**Comment by tom-perkins** [comment]
Changes look good, now NaN and Inf are both zeroed (except when the weight is zero) and the new test covers the changes. Happy to :shipit:

**Comment by peterfpeterson** [comment]
This should be added to the release notes.

**Comment by gvardany** [comment]
I have added a line in release notes.

**Pull request merged**
