### PR TITLE
Updates to Engg algorithms: mask pulses, normalization, additional properties, file extensions, phase information

### LINKED ISSUE #13045: Add input property for rebinning bin size (for the initial rebinning in ToF)
This is about the very early rebinning that is being done in ToF units at the beginning of the `EnggCalibrateFull` algorithm. Currently, the bin size is hard-coded as '-0.0005' which was taken from OpenGenie routines. Turn this into an input property to the algorithm, using that value as default.

Other rebinning steps (where and if they're done) need to be clarified, but leave that out of this issue.

### LINKED ISSUE #13378: Engg algorithms: normalize all files by current + update Vanadium integration/fit
Make sure that all the input files are normalized by current, always in all algorithms.

Since this is not being done in the current versions of the algorithms, the change will imply also changing all the test values. So at the same time:

- Update the Vanadium fit (BSpline, order 3, 50 break points) and the default Vanadium curves in the tests (this is related to #13230) (which also implies changes in most test values).

### LINKED ISSUE #14788: Mask out some bins for Engin-X runs (Engg algorithms)
In Engin-X data there are a few bins with pulses that should be masked out.
When the run files are processed those bins should be masked out, for any run. This could be introduced as a "BinsToMask" option in the `Engg` algorithms, with a default value set to the list of   Engin-X. The EnggDiffraction GUI should always use this option for Engin-X runs.

This is a list of bins that should be masked for Engin-X from Saurabh's scripts:

```
    ws_b1=MaskBins(ws_b1,0,5300)
    ws_b1=MaskBins(ws_b1,19930,20400)
    ws_b1=MaskBins(ws_b1,39960,40450)
    ws_b1=MaskBins(ws_b1,59850,62000)
    ws_b1=MaskBins(ws_b1,79930,82670)

    ws_b2=MaskBins(ws_b2,0,5300)
    ws_b2=MaskBins(ws_b2,19930,20400)
    ws_b2=MaskBins(ws_b2,39960,40450)
    ws_b2=MaskBins(ws_b2,59850,62000)
    ws_b2=MaskBins(ws_b2,79930,82670)
```

### LINKED ISSUE #15338: ENGG GUI: split .prm file and change extension
The "both banks" approach does not seem to work well with the enginx OpenGenie scripts in the end. The template given with EnggUtils needs to be split. The calibration should output `North_` and/or `South_` files (or `Custom_`, see #15337). Also, use ".par" extension, as legacy scripts like only that extension.

### PR DESCRIPTION
**Pull request by FedeMPouzols**
Introduces several modifications to the Engg algorithms to finish all the workflow plans discussed with scientists so far. All these are done at once to update the unit/doc/system tests for all the changes consistently:
- # 14788: Masking of some pulses, with defaults for EnginX
- # 13045: Add input property for rebinning bin size (for the initial rebinning in ToF) in EnggCalibrateFull
- # 13378: Normalization by proton charge always enabled by default in  EnggFocus (the Vanadium updates were done already)
- # 15338: use ".prm" as extension for the output calibration files, and  be able to generate individual files per bank

And it also adds several phase information files as a resource for various Engg scripts and algorithms.

This depends on:
- [x] #16092 needs to be merged first

**To test:**
- check documentation updates, now EnggFocus has two more child algorithms.
  Check the documentation of the new properties
- check code
- check the updates to the documentation of the Engg GUI
- unit/doc/system tests should all pass (one doc test was fitting a
  spurious peak from a pulse of Engin-X and has been updated)
- this should not change how the Engg GUI works (you will only notice some changes if
  the sample data had big pulses). In particular, calculate a normal calibration and
  see that the output ".prm" instrument files for GSAS are produced. Calculate a
  "cropped" calibration and see that the file is also produced correctly.
- make sure that if you specify a custom name in "cropped"
  calibration, next to the output "_all_banks.prm" there is a prm file
  with the name of the custom bank
- Some 20 EXPECT_CALL conditions were not being satisfied in
  EnggDiffractionPresenterTest (can be seen as warnings when running the test with
  `-V`). These have been fixed, and `VerifyAndClearExpectations` calls
  have been added to enforce those conditions as test failures rather than simply warnings.

Fixes #14788
Fixes #13378
Fixes #13045
Fixes #15338

Release notes: https://github.com/mantidproject/mantid/commit/492ad64aa8a5e5b7eec8eb6bd2ac6f09d90467e7

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by shahrozahmed1** [comment]
When I carry out cropped calibration with a customised bank name or particular bank, it produces the correct file with correct file name but it doesn't update the path on the GUI accordingly

**Comment by shahrozahmed1** [comment]
I cant seem to find where exactly it is masking of some of the pulses

**Comment by FedeMPouzols** [comment]
The pulses are masked using the new option in `EnggFocus`, `MaskBinsXMins` and `MaskBinsXMaxs`, with the default list in the documentation. For example, EnggCalibrate-v1.rst was updated to not use one "peak" that turned out to be a pulse (the 1.097 in d-spacing). It doesn't necessarily mask anything in all cases, depending on the data that you have. Some of the pulses are nor present in some data files, and other pulses are outside of the effective range of some files, for example the ~40000, ~60000, and ~80000 are usually outside of the effective range. So this remains hidden most of the time.

I'll take a look at the issue with the cropped calibration update.

**Comment by FedeMPouzols** [comment]
Aha, I think the last commit fixes the issue with the name of the "current calibration" when using "cropped" calibrations. I've also changed it so that the full path is shown. So you should now see the correct name, if you have enough space or expand the interface wide enough you should see the full path (and it should be the same as in the logs).

The code will always generate an "all_banks" file, and then the individual files/banks. This happens even if there is only one individual file/bank, I'd keep it like that for consistency. But anyway the name shown is the "custom/North/South" name of the cropped bank when calibrating in "cropped" mode.

**Comment by FedeMPouzols** [comment]
Oh and if you leave the custom name box empty it should call it "cropped" by default.

**Comment by shahrozahmed1** [comment]
All GUI code has been reorganised, cleaned up presenter and view. New property for `EnggCalibrateFull` algorithm to set the `RebinBinWidth`, `EnggFocus` now contains param to allow Min and Max MaskBins. Normalisation is also carried out in the background to each spectra value by current proton charge for `Engg Focus`.
`.prm` files name and GUI current calibration updates according to the bank calibrated, also writes out calibration file which can be used for GSAS. Presenter test will now fail on the builds when the warning is generated, instead of just going unnoticed until next time test is locally ran. 
This PR now looks good and ticks of lots of issues in one go.

:shipit:

**Comment by FedeMPouzols** [comment]
The last merge commit was to address a supposed merge conflict which was auto-resolved (in the interface rst and diffraction.rst (release notes)).

**Comment by shahrozahmed1** [comment]
`VesuvioTOFFitTest` is failing which has nothing to do with this branch

**Comment by shahrozahmed1** [comment]
:shipit:

**Pull request merged**
