### PR TITLE
Fix PhaseQuad test

### LINKED ISSUE #20776: PhaseQuad test problems
The swap test in phaseQuad is failing http://builds.mantidproject.org/job/pull_requests-win7/17596/testReport/junit/AlgorithmsTest/PhaseQuadMuonTest/testSwapOrder/

### PR DESCRIPTION
**Pull request by AnthonyLim23**
This is an attempt to fix the random failures on the build servers. 

Fixes #20776 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — APPROVED** [review]
Code-wise the changes look fine for now.

The windows builds need to pass a few times for this to be considered a fix.

**Comment by peterfpeterson** [comment]
`AlgorithmsTest_PhaseQuadMuonTest` results:
* [17626 failed](http://builds.mantidproject.org/job/pull_requests-win7/17626/)

**Comment by AnthonyLim23** [comment]
just looked and the test does not match the version I am currently trying. I will look into this some more tomorrow

**Comment by peterfpeterson** [comment]
Sorry. I hit the "comment" button after you pushed changes. I will start a new comment with builds of the current tip as the result.

**Comment by peterfpeterson** [comment]
[17637 failed](http://builds.mantidproject.org/job/pull_requests-win7/17637/)

**Comment by martyngigg** [comment]
The Ubuntu test failure are the unreliable docs test.

@mantidproject/gatekeepers I think we can merge this now.

**Pull request merged**
