### PR TITLE
Handle corrupted data in SANS event slicing

### LINKED ISSUE #27490: Event slicing with a specific run causes FilterByTimeErrors to error
**Original reporter:** ISIS/Steve

### Expected behavior
Filtering by time should (and does for all other runs) work correctly when slicing data

### Actual behavior
FilterByTime fails stating that either the relative or absolute time must be specified:

```
Error in execution of algorithm FilterByTime:
You need to specify either the StartTime or StopTime parameters; or both the AbsoluteStartTime and AbsoluteStopTime parameters; but not other combinations.
```

### Steps to reproduce the behavior
- Process SANS2D99959115.nxs with event slicing

### Platforms affected
All

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**
Since the mechanisms for cleaning corrupted proton logs (such as those found in cycle 19/1) exist in the SANS codebase and the script for fixing up individual files has gone AWOL it makes sense to re-use the implementation.
    
We now clean up sample logs before time slicing so that it no longer wraps around to negative vals. Additionally, I've added a validator to FilterByTime to give a better error message

**Report to:** ISIS/Steve

**To test:**
You need access to Babylon
- Check you have access to `Public/David Fairbrother/PR Data`
- Open the SANS GUI
- Set the mask file to the one given in the previously stated folder
- Set the batch file to `repro.csv`
- Go to settings -> General...etc. -> Slices
- Add 1:60:60
- Go back to Runs and process data
- If this finishes correctly the issue is resolved

Secondly:
- In Mantid create a SampleWorkspace
- Attempt to run FilterByTime with a stop time < 0 and a valid error is produced

Fixes #27490 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DavidFair** [comment]
Marking this as high, as a user can't process some data currently and they're pushing for a fix ASAP

**Review by cailafinn — CHANGES_REQUESTED** [review]
Code looks good, however I am currently getting this error: `Error in execution of algorithm SANSLoad:
SANSCalibration: The file for   does not seem to exist` though it may be due to me missing some files.

**Review by cailafinn — APPROVED** [review]
Error found on previous review is a known bug when the masks folder in the data archive is not in the user directories. Actual focus for this PR works as expected and fixes the issue.

**Comment by DanNixon** [comment]
Because handling bad data with special cases is obviously better than actually fixing the data...

**Comment by DavidFair** [comment]
Yeah, we spent 3 days looking for a script which would have fixed this for the single file but couldn't find it anywhere.

I'm already discussing removing this special case handling since it only applies to cycle 19/1 data, so when it's out of scope....

**Comment by DanNixon** [comment]
> I'm already discussing removing this special case handling since it only applies to cycle 19/1 data, so when it's out of scope....

Have fun with that.

**Pull request merged**
