### PR TITLE
Muon freq data with correct y units

### LINKED ISSUE #33296: Labels for FFT and Maxent
The labels for FFT and Maxent are not correct. This requires 2 small changes:

1. Change the FFT to have a y label of "intensity" (in the muon GUI)
2. Change MuonMaxent to have a y label of "Probability" for the main output. This can be done on the algorithm.

### PR DESCRIPTION
**Pull request by AnthonyLim23**
**Description of work.**

**To test:**

Open the frequency domain analysis GUI (muon)
Load MUSR 62260
Go to the transform tab
Press `Calculate FFT`
Check the y axis label is intensity

At the top of the tab, change it from FFT to MaxEnt
Press Calculate MaxEnt
Check the y axis label is probability

Fixes #33296. and fix https://github.com/mantidproject/mantid/issues/32829

In release notes

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by sf1919** [comment]
Does this also fix #32829 ?

**Comment by AnthonyLim23** [comment]
yes

**Comment by sf1919** [comment]
The y axis labels appear to be hard coded in. Is this what we want? Will FFT always be 'Intensity' on y-axis and Max-Ent always be 'Probability'?

**Comment by AnthonyLim23** [comment]
the short answer is yes. I can provide a longer one if you would like

**Review by sf1919 — APPROVED** [review]
I have tested the functionality of this and it works as expected. Even chaging the workspace and using imaginary data in FFT and changing to calculate by all detectors rather than groups for MaxEnt caused no issues and y-axis displayed correctly.

As discussed above the y-axis labels can be hard coded for these specific plots so the solution is fine.

Release note are in separate file as requested at this time.

I am therefore happy to approve.

**Pull request merged**
