### PR TITLE
FindPeaksMD improvements for multiple runs

### PR DESCRIPTION
**Pull request by rosswhitfield**
Add check in FindPeaksMD to only add peaks for a particular experiment info if events were contributed from the run. This is mush faster for multiple runs!

**To test:**
I used this for testing with corelli but you should try other instruments. FindPeaksMD went from ~35 minutes to ~25 seconds!
```
md=LoadMD('/SNS/users/rwp/testmd.nxs')
FindPeaksMD(InputWorkspace=md,DensityThresholdFactor=50000, OutputWorkspace='peaks')
```

Release notes added

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by VickieLynch — COMMENTED** [review]
Good news is that it finds exactly the same peaks for a single orientation of TOPAZ.  Bad news is that it is 20-25% slower.

**Comment by rosswhitfield** [comment]
@VickieLynch I could add a check if `NumExperimentInfo==1` then skip my new stuff. That should bring the speed back up for a single run MD.

**Comment by VickieLynch** [comment]
@rosswhitfield Sounds like a good idea

**Review by VickieLynch — COMMENTED** [review]
I still get about 14% slower.  Are you doing anything else for single runs?

**Comment by rosswhitfield** [comment]
@VickieLynch It has one check `if (nexp > 1)` then it should do nothing else.

**Comment by rosswhitfield** [comment]
Once we get this into master we have a [performance test](http://builds.mantidproject.org/job/master_performancetests2/Master_branch_performance_tests/) that should highlight any differences.

**Review by VickieLynch — APPROVED** [review]
I think I am comparing a build with debug info with nightly that does not have that and so the timings are OK.

**Pull request merged**
