### PR TITLE
LoadNexusProcessed for EventWorkspace bugfix

### LINKED ISSUE #15725: LoadNexusProcessed for EventWorkspace bin boundaries
### Expected behavior

Looking at an empty container run cached from autoreduction in NOMAD the `EventWorkspace` data has the fields:

```
NX/mantid_workspace_1/event_workspace> ls
  NX Data  : axis1[6,6001] (NX_FLOAT64)
  NX Data  : axis2[6] (NX_FLOAT64)
  NX Data  : error_squared[3030057] (NX_FLOAT32)
  NX Data  : indices[7] (NX_INT64)
  NX Data  : tof[3030057] (NX_FLOAT64)
  NX Data  : weight[3030057] (NX_FLOAT32)
```

### Actual behavior

The restored workspace shows `Bins: 5`

### Steps to reproduce the behavior

1. `LoadNexusProcessed(Filename="NOM_67811_494ca787ff3b195ec0d02f214bf8a6b3f8855d23.nxs")`
2. Look at the properties and see that there only 5 bins rather than 6000.

### PR DESCRIPTION
**Pull request by peterfpeterson**
The bug was an assumption that event data always has a common x-axis on load.

**To test:**

Code review and and confirm that all the builds pass.

Fixes #15725.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
This has developed a merged conflict with master. It's probably in the release notes file?

**Comment by KarlPalmen** [comment]
Builds have passed, but not otherwise tested. :shipit:

**Comment by quantumsteve** [comment]
This branch still has a merge conflict that needs to be resolved.

**Comment by peterfpeterson** [comment]
You don't have to wait for the builds. I resolved the conflict in the release notes (again). :frowning:

**Pull request merged**
