### PR TITLE
Indirect update unscripted testing documentation

### LINKED ISSUE #29350: Indirect update unscripted testing documentation
### Description
Some of the unscripted testing documentation is slightly outdated and needs updating.

### Steps to reproduce the behavior
Read through the Indirect unscripted testing documentation and update the parts which are outdated. Some issues include:
- Different names for buttons or options 
- New output plotting widget is now used

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR makes minor updates to the Indirect unscripted testing documentation. These updates include:
- Different names for buttons or options
- New output plotting widget is now used

**To test:**
Read through the Indirect unscripted testing documentation and make sure it can be easily followed in the Indirect GUI's.

Fixes #29350

*This does not require release notes* because **developer docs**

### CODE REVIEW

**Comment by martyngigg** [comment]
Would there be any reason not to include this on the release branch? I assume it's updating the docs to match the code?

**Comment by martyngigg** [comment]
Could you also connect the issue with Zenhub?

**Comment by robertapplin** [comment]
> Would there be any reason not to include this on the release branch? I assume it's updating the docs to match the code?

No reason not to, should I rebase this to `release-next`? Yes, some of the wording in the docs was slightly outdated

**Comment by martyngigg** [comment]
> > Would there be any reason not to include this on the release branch? I assume it's updating the docs to match the code?
> 
> No reason not to, should I rebase this to `release-next`? Yes, some of the wording in the docs was slightly outdated

It looks like nothing has gone onto `master` since we created the release branch so you should be okay to just go to `Edit` at the top of the page and change the target to `release-next`.

**Comment by robertapplin** [comment]
> > > Would there be any reason not to include this on the release branch? I assume it's updating the docs to match the code?
> > 
> > 
> > No reason not to, should I rebase this to `release-next`? Yes, some of the wording in the docs was slightly outdated
> 
> It looks like nothing has gone onto `master` since we created the release branch so you should be okay to just go to `Edit` at the top of the page and change the target to `release-next`.

Ah ok, it should be ready now 👍

**Review by martyngigg — APPROVED** [review]
Good improvements!

**Pull request merged**
