### PR TITLE
Get tooltips from ReflectometryISISLoadAndProcess

### LINKED ISSUE #27889: Get tooltips from ReflectometryISISLoadAndProcess
In the ISIS Reflectometry in `QtBatchView` we are still using `ReflectometryReductionOneAuto` to get the tooltips rather than `ReflectometryISISLoadAndProcess`. If we change it we will break the `Encoder` and `Decoder` unit tests because C++ tests cannot use python algorithms. The code needs to be reorganised to avoid creating the algorithm, or the tests rewritten in python. The fix needs to be added in `QtBatchView.cpp` and the column properties updated in `PerThetaDefaults.h`.

This only affects tooltips for a couple of the properties (the first and second transmission runs, which are documented as single inputs rather than lists) so is not an urgent fix.

### Steps to reproduce
This will only become apparent after PR #27854 because these fields are not used otherwise.
- Open the ISIS Reflectometry interface
- Go to the Experiment tab
- Hover over the cell in the transmission runs column
- Note that its description matches that from [ReflectometryReductionOneAuto](https://docs.mantidproject.org/nightly/algorithms/ReflectometryReductionOneAuto-v3.html) rather than [ReflectometryISISLoadAndProcess](https://docs.mantidproject.org/nightly/algorithms/ReflectometryISISLoadAndProcess-v1.html?highlight=reflectometryisisloadandprocess).

### PR DESCRIPTION
**Pull request by giovannidisiena**
**Description of work.**
In the ISIS Reflectometry in QtBatchView we are now using ReflectometryISISLoadAndProcess to get the tooltips rather than ReflectometryReductionOneAuto. This required changes to allow the Python algorithm to be run in the Encoder and Decoder C++ unit tests.

**To test:**
- Open the ISIS Reflectometry interface
- Go to the Experiment tab
- Hover over the cell in the transmission runs columns
- The descriptions should match those from [ReflectometryISISLoadAndProcess](https://docs.mantidproject.org/nightly/algorithms/ReflectometryISISLoadAndProcess-v1.html?highlight=reflectometryisisloadandprocess) rather than [ReflectometryReductionOneAuto](https://docs.mantidproject.org/nightly/algorithms/ReflectometryReductionOneAuto-v3.html). 

---
- Run `ctest -C Debug -VV -R EncoderTest` and `ctest -C Debug -VV -R DecoderTest`.
They should both pass.

Fixes #27889 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by giovannidisiena** [comment]
@martyngigg the changes appear to be causing a segfault in:
https://github.com/mantidproject/mantid/blob/27cea756a8e9c9d79da23ea706555d731005b2d8/Framework/PythonInterface/core/inc/MantidPythonInterface/core/Testing/PythonInterpreterGlobalFixture.h#L48
any ideas why?

**Review by cailafinn — CHANGES_REQUESTED** [review]
Just a note about the copyright information. Otherwise, the tests pass and the tooltips are correct. Nice work :+1:

**Review by cailafinn — APPROVED** [review]
Looks good to me now. Tests pass and tooltips are correct.

**Comment by martyngigg** [comment]
Unrelated test failure.

**Pull request merged**
