### PR TITLE
ISISPowder use absorption correction on samples

### LINKED ISSUE #20219: ISIS_Powder - Use AbsorptionCorrections for samples instead of MayersSampleCorrection

### PR DESCRIPTION
**Pull request by josephframsay**
**Description of work.**

Previously ISIS_Powder did not support absorption correction on non-vanadium samples. We now check whether a sample is vanadium or not. In both cases we use Mayers' Sample Correction, but in the case of a non-vanadium sample, we explicitly disable correction for multiple scattering (possibly to be added at some point in the future).

**To test:**

Run a focus on some powder data, first with the `do_absorb_corrections` flag set to `False`, then `True`. Plotting the resultant spectra on top of each other should show distinct evidence of absorption corrections taking place

Fixes #20219 . 

**Release Notes** 
*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
@josephframsay  what do you mean by 'Run a focus on some powder data'? Also could you suggest some example data?

**Review by AnthonyLim23 — CHANGES_REQUESTED** [review]
The code looks good to me. The only thing is that the release notes and documentation should be updated.

**Comment by josephframsay** [comment]
The changes don't need to go in the documentation - as long as testing works, this should be good to go!

**Comment by josephframsay** [comment]
Yup, changes definitely don't need to go in the docs, as the extra parameters are in internal functions which aren't exposed to the user

**Comment by AnthonyLim23** [comment]
I used these scripts: 

```
from isis_powder.polaris import Polaris
from isis_powder.routines.sample_details import SampleDetails

calibration_dir = r"C:\Users\BTR75544\ISIS_Powder\Examples\Calibration"
output_dir = r"C:\Users\BTR75544\ISIS_Powder\Examples\output"
cycle_file = r"C:\Users\BTR75544\ISIS_Powder\Examples\polaris_cycle_map_example.yaml"

polaris_obj = Polaris(mode="Rietveld", user_name="Test", output_directory=output_dir,
                      calibration_directory=calibration_dir, calibration_mapping_file=cycle_file)

sample_details_obj=SampleDetails(height=4.0,radius=0.4, center=[0.,0.,0.]) 
sample_details_obj.set_material(chemical_formula="Si")

polaris_obj.set_sample_details(sample=sample_details_obj)
polaris_obj.focus(input_mode="Summed", run_number="98533", do_absorb_corrections=True, multiple_scattering=False, do_van_normalisation=True)
```

and 
```
# Create Vanadium
import isis_powder.polaris
reload(isis_powder.polaris)

calibration_dir = r"C:\Users\BTR75544\ISIS_Powder\Examples\Calibration"
output_dir = r"C:\Users\BTR75544\ISIS_Powder\Examples\output"
cycle_file = r"C:\Users\BTR75544\ISIS_Powder\Examples\polaris_cycle_map_example.yaml"

polaris_obj = isis_powder.polaris.Polaris(mode="Rietveld", user_name="Test", output_directory=output_dir,
                                          calibration_directory=calibration_dir, calibration_mapping_file=cycle_file)

polaris_obj.create_vanadium(first_cycle_run_no=98533, do_absorb_corrections=True, multiple_scattering=True)
```

I changed the multiple_scattering flag for both and got the expected result.

**Review by AnthonyLim23 — APPROVED** [review]

**Review by peterfpeterson — CHANGES_REQUESTED** [review]
This needs release notes or an explanation of *why* it doesn't.

**Comment by AnthonyLim23** [comment]
@peterfpeterson Joe gave an explanation 4 days ago. So its near the bottom of the conversation.

**Review by peterfpeterson — APPROVED** [review]

**Comment by peterfpeterson** [comment]
It would have been helpful to put in the "details" portion of the PR so its easier to see. Generally the sentence should be "This does not need to be in the release notes because ...".

**Pull request merged**
