### PR TITLE
Consistently position const in FileSaver class using east const approach

### LINKED ISSUE #37283: Position const consistently in Reflectometry GUI AsciiSaver class
The Reflectometry GUI has an `AsciiSaver` class. As per [this PR comment](https://github.com/mantidproject/mantid/pull/37268#discussion_r1592259123), this class mixes the east/west positions of the `const` identifier. This has no functional impact, but it would be good to make this consistent through this file for readability.

### PR DESCRIPTION
**Pull request by yusufjimoh**
### Description of work
Consistently position const in FileSaver.cpp  and FileSaverTest.h classes following the east const approach

Fixes #37283 

### To test:
Review the FileSaver.cpp class to ensure const position follows the east const approach.
Review the FileSaverTest.h class to ensure const position follows the east const approach.

This does not require release notes because the changes involved refactoring some few lines of code without introducing any functional changes

### CODE REVIEW

**Comment by rboston628** [comment]
https://mariusbancila.ro/blog/2018/11/23/join-the-east-const-revolution/

**Review by GuiMacielPereira — CHANGES_REQUESTED** [review]
Looks good, I just noticed some lines where you can switch to east convention too:

- Line 82
- Line 96
- Line 102

**Review by GuiMacielPereira — APPROVED** [review]
Use of `const` is now consistent and I checked that mantid opens normally and there are no issues when saving a file in the Reflectometry GUI.

**Comment by peterfpeterson** [comment]
When we update `clang-format` to >=14 this can be done by adding
```
QualifierAlignment: Right
```
to `.clang-format` configuration file

**Pull request merged**
