### PR TITLE
Modify processTubes so that bank identification works for Bilby

### LINKED ISSUE #34760: Bilby InstrumentView Side by Side view improvement
**Original reporter**
Liliana De Campo

**Description**
A request to improve the Side by side view on InstrumentViewer has been made by a Bilby instrument user. A similar request was made by SXD users [here](https://github.com/mantidproject/mantid/issues/34560), but I thought I'd record this in a different issue. It might be worth running changes to the InstrumentViewer Side by side view past Liliana De Campo to see if her issues are also solved by this work.

The following was provided in their email:
```
When looking at 2D Bilby data, the 3D view is perfect!

But in the side-to-side view, the sequence of the detector tubes is messed up:
the tubes are organised in 8-packs, and the picture shows that 8 peaks with high intensity are at the wrong place; red circles
also the center of the back detector (direct beam area) lands at a funny position; orange circles
and they are not all aligned (overall shape of the detector panels is not a smooth rectangle), see blue circles)

It seems that this side-by-side view is a little different in different Mantid versions, but none of them is perfect.

A better side-so-side viewer would make it much easier for us to mask different detector areas
```

bilby

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

Modification to the side by side view in the instrument view to be more flexible in the way banks of tubes are identified. The processTubes function previously only went up to the grandparent level of the supplied tube if the parent of the supplied tube only had a single child. Broaden this out to always go up to the grandparent level and if the set of tubes found isn't flat, fall back to considering the parent level. This will help identify banks in the Bilby instrument where a bank consists of several eight packs of tubes.

I've also modified the function calcBankRotation which is used for all different types of detector (tubes, rectangular, structured):

- update the logic when the normal and the bank centre are parallel that returned an empty Quat - didn't work for case where normal and z axis were 180 degrees apart
- Rotate bank normal to +ve or -ve z depending on whether bank is at -ve or +ve z respectively

Finally I've added some bank centre overrides to the Bilby instrument definition using the new feature implemented in https://github.com/mantidproject/mantid/pull/35070

**To test:**

Run the LoadBBY algorithm with the BBY0001356.tar file available here: [https://cloudstor.aarnet.edu.au/plus/s/j7dBLMlaKd9QwGS](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcloudstor.aarnet.edu.au%2Fplus%2Fs%2Fj7dBLMlaKd9QwGS&data=05%7C01%7Clilianad%40ansto.gov.au%7Ca70c66778516482e4ca508db05ce42e5%7C4cbf9a84567a44d09db11dbfbf8393f0%7C0%7C0%7C638110155748664879%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xM8UJ28z94wCAHOeBrmgswZxMx3k%2B%2F8DR7zDbvURhg8%3D&reserved=0)

Right click on the resulting workspace in the ADS and select Show Instrument
Select Side by Side view
Observe that there are now 6 banks

Run the LoadEmptyInstrument algorithm on the `VISION_Definition_20160815-.xml` instrument definition file and check the side by side view renders OK. The last significant change to processTubes prior to this PR was to accommodate the VISION IDF and its definition of banks so need to check I've not broken that

Fixes #34760.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DannyHindson** [comment]
Email exchange with Liliana De Campo (17th Feb 2023):

```
From: DE CAMPO, Liliana <lilianad@ansto.gov.au> 
Sent: 17 February 2023 00:18
To: Hindson, Danny (STFC,RAL,ISIS) <danny.hindson@stfc.ac.uk>
Subject: RE: Mantid side by side view for Bilby instrument [SEC=UNOFFICIAL]

Hello Danny!

That looks absolutely perfect!

Many many thanks from the Bilby team!

Do you perhaps know when this might be incorporated into a stable version?

All the best,
lela

From: Danny Hindson - STFC UKRI <[danny.hindson@stfc.ac.uk](mailto:danny.hindson@stfc.ac.uk)> 
Sent: Thursday, 16 February 2023 8:00 PM
To: DE CAMPO, Liliana <[lilianad@ansto.gov.au](mailto:lilianad@ansto.gov.au)>
Subject: RE: Mantid side by side view for Bilby instrument [SEC=UNOFFICIAL]

Great. Here’s a link to some Mantid installers (for Windows, Linux and Mac):

https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstfc365-my.sharepoint.com%2F%3Af%3A%2Fg%2Fpersonal%2Fdanny_hindson_stfc_ac_uk%2FEnaRR8u6hIFBi56zXbNDaswB3nLvG9lqsStCJSt_xf4npw%3Femail%3Dlilianad%2540ansto.gov.au%26e%3D1XBl61&data=05%7C01%7Clilianad%40ansto.gov.au%7Cd4cb5547d25d473720cc08db0ffc4999%7C4cbf9a84567a44d09db11dbfbf8393f0%7C0%7C0%7C638121348580612277%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5j7A%2BFDeKsN%2FPkT4mnHCR2XxaiuJbbFvpGItPIARhIw%3D&reserved=0

Please can you install and check if the side by side view looks OK for you. If the banks need some small adjustments you can do this by editing the Bilby instrument definition file which is in instrument\BILBY_Definition.xml in the Mantid install directory (I think you’ll need to restart Mantid after any changes). There is a tag called side-by-side-view-location against each bank that has an x and a y attribute. If the positions aren’t quite right then please send me back the updated BILBY_Definition.xml file when you’ve finished editing it.

One final thing to mention – the current development build triggers an error (like the following) in the message log when you open the instrument viewer. This is unrelated to my changes and will hopefully be fixed soon:
```
image
```
Thanks
Danny

From: DE CAMPO, Liliana <[lilianad@ansto.gov.au](mailto:lilianad@ansto.gov.au)> 
Sent: 15 February 2023 22:11
To: Hindson, Danny (STFC,RAL,ISIS) <[danny.hindson@stfc.ac.uk](mailto:danny.hindson@stfc.ac.uk)>
Subject: RE: Mantid side by side view for Bilby instrument [SEC=UNOFFICIAL]

Hi Danny!

That looks absolutely perfect – thank you so much!

And we usually don’t save the 2D file at this stage of the reduction, so there is no work that we have to redo.

Many thanks!
lwla

From: Danny Hindson - STFC UKRI <[danny.hindson@stfc.ac.uk](mailto:danny.hindson@stfc.ac.uk)> 
Sent: Thursday, 16 February 2023 1:53 AM
To: DE CAMPO, Liliana <[lilianad@ansto.gov.au](mailto:lilianad@ansto.gov.au)>
Subject: RE: Mantid side by side view for Bilby instrument [SEC=UNOFFICIAL]

Hi Lela,

I’m going to send you the installer soon (today or tomorrow). I loaded the ws_sam.ws file you sent me into instrument viewer on my development copy of Mantid and it now looks like this:
```
image
```
In general you’ll probably need to run the reduction again on previously reduced files to get the new side by side view working on them. This is because nexus files for reduced data (eg ws_sam.ws) have an instrument definition embedded in them. The new bank locations for the side by side view are now part of the instrument definition following my changes but these locations won’t be present in previously reduced files. So I had to do a bit of manual work to merge these into the file you sent me.

Thanks
Danny
```

**Review by sf1919 — COMMENTED** [review]
I have tested the functionality of this PR and all seems to work. I made sure to test the VISION IDF file as directed. It was really helpful to have that included in the test rather than having to work out what the previous changes were (to ensure no breaking changes).

The code looks fine.

My only query is - shouldn't there be tests for PanelSurface?

**Comment by DannyHindson** [comment]
> I have tested the functionality of this PR and all seems to work. I made sure to test the VISION IDF file as directed. It was really helpful to have that included in the test rather than having to work out what the previous changes were (to ensure no breaking changes).
> 
> The code looks fine.
> 
> My only query is - shouldn't there be tests for PanelSurface?

Thanks for having a look at this. The instrument viewer is very light on tests in general. So the different views in the instrument viewer use the units Projection3D, UnwrappedCylinder, UnwrappedSphere and PanelsSurface and I don't think any of them have tests. That's not necessarily a good tradition to carry on with though. How about I create a unit test suite for PanelsSurface for the functions I've changed?

**Comment by sf1919** [comment]
Sound like a great idea - thanks @DannyHindson

**Comment by DannyHindson** [comment]
I've added some unit tests. This required some changes to a few other units - mainly to allow me to mock one of the classes used in the PanelsSurface class (InstrumentActor).

While retesting everything I noticed a problem that was introduced in #35104 that is unrelated to these changes. When I look at the VISION instrument using the test instructions on this PR the screen is blank when I first switch to side by side view. If I resize the window (even by a tiny amount) the instrument then appears. This only affects the view with "OpenGL" enabled on the Display Options menu and it impacts all of the views apart from 3D. Not sure what's causing this but will need to look into separately

**Comment by DannyHindson** [comment]
@sf1919 - I've just noticed that I don't see the bug I referred to in my previous message any more (the one about the instrument viewer being black until the window is resized). Not sure if it's because I'm in the office today on different screens compared to yesterday. Anyway - would be interesting to know if you see the problem

**Comment by sf1919** [comment]
First of all - I am not seeing the OpenGL issue discussed above. I think that has been solved possibly?

Secondly - I've been looking at the image above. I've realised that the 6 banks I am getting when I do side-by-side view for BBY0001356.tar is not in the same order. Instead it looks like below - is that an issue?

Screenshot (247)

**Comment by DannyHindson** [comment]
I don't see the OpenGL problem with the VISION instrument any more either. I'm working from home again today using the same monitors as when I saw it on Weds so not sure what was going on there. Let's assume that's not a real issue.

The problem about the BILBY bank's not being arranged properly is strange. When I look at the same file on my development branch `34760_ModifyTubeBankIdentificationForBilby` it looks as it does in my screenshot on this PR. I'll try building the `pr/35164-merged` branch just to be 100% aligned with what you're doing. I'll let you know what I see

**Comment by DannyHindson** [comment]
I just tried using a build based on the `pr/35164-merged` branch and the BILBY layout is still OK for me. Please can you check\try a couple of things:
1) if you look inside your BILBY_definition.xml file do you see the new "side-by-side-view-location" tags that I added in this PR. Sometimes Mantid downloads the IDF files so wondering if these changes have got lost somehow

2) Please can you try deleting any files starting with "BILBY" from your geometryCache directory which should be here or similar: `C:\Users\iao46725\AppData\Roaming\mantidproject\mantid\instrument\geometryCache`. And then start up Mantid and try loading the BILBY .tar file, viewing it in instrument viewer as before

**Comment by sf1919** [comment]
For info - I have been doing a clean build each time (nuking the build folder and re-running CMake). Perhaps there is some sort of setting that needs to be changed to make it work correctly?

**Review by sf1919 — APPROVED** [review]
Thank you for adding the PanelsSurfaceTest to undertake testing associated with this PR. Hopefully it will enable tests for any future changes to PanelsSurface.

It all works well - the two suggestions to make the detectors display correctly worked. 

LGTM

**Pull request merged**
