### PR TITLE
Add information about run numbers for multiple file reduction in Indirect Energy Transfer algorithm

### LINKED ISSUE #36850: Indirect Reduction "multi" files keep run number info
**Reported by:** Sanghamitra

**Is your feature request related to a problem? Please describe.**
In the Indirect Reduction interface there is the option to "Sum files". This produces a "multi" reduced file which is the summed reduction of many run numbers.

It has been reported that users would like to be able to find out which run numbers were used to produce a "multi" file. At the moment, only the first run number is saved in the workspace name and the sample logs. It would be useful to have access to which run numbers were used because users can forget which runs were used for a particular multi file.

**Describe the solution you'd like**
I think the best solution would be to make sure the `run_number` sample log includes all the run numbers used in the summed reduction.

**Describe alternatives you've considered**
Considered adding run numbers to the workspace name, but this is not a great way to do things. It would also result in long workspace names.

**Acceptance criteria**
- For all instrument reductions, it is possible to look up which run numbers were used for a "multi" workspace.
- Save the multi workspace to a file, and then load it back in. Check that the run number info is retained.

### PR DESCRIPTION
**Pull request by adriazalvarez**
### Description of work
This PR adds information about the run numbers used in the reduction of multiple files when passing the Indirect Energy Transfer algorithm either from the Indirect Data Reduction interface or from a direct call to the ISISIndirectEnergyTransfer algorithm. This feature was requested by scientists.
Additionally, the output workspace name was not giving useful information about multiple run numbers. In this PR, the output workspace name contains a string just after the instrument name with the first and last runs used in the reduction separated by a dash.

Fixes #36850. 

#### Further detail of work

In #36850, it is explained that in most cases there is a log called 'multi_run_numbers' which stores the run numbers used in the reduction, but not when performing reduction with 'TOSCA' data. Also, in some cases, reduction is performed by combining chopped workspaces instead of separated runs. To add more context valid information, I have added the information about multiple runs in two sample logs:
- `run_number` log stores all the runs used in the multiple file reduction separated by commas. 
- `multi_run_reduction` log informs whether the reduction was done with chopped runs or regular runs. 

### To test:
- Set access to Search Data Archive from Mantid `Manage User Directories` setting. 
- Open `Indirect` -> `Data Reduction` interface. 
- Select `IRIS` instrument and on run numbers type `26184,26185,26186`
- Run the algorithm. Check ADS
- Output workspace name starts with `irs26184-26186`.
- Open `show sample logs` in the output workspace. 
- `run_number` sample log shows: `26184,26185,26186`.
- `multi_run_reduction` sample log shows: `regular_runs`
---------------
- Back to the `Data Reduction` interface. 
- Select `OSIRIS` as the instrument now and on run numbers type `97944-97945`.
- Run the algorithm. Check ADS
- Output workspace name starts with `osiris97944-97945`.
-  Open `show sample logs` in the output workspace. 
- `run_number` sample log shows: `97944,97945`.
- `multi_run_reduction` sample log shows: `regular_runs`
---------------
- Back to the `Data Reduction` interface. 
- Select `TOSCA` as the instrument now and on run numbers type `22797-22798`.
- Run the algorithm. Check ADS
- Output workspace name starts with `tosca22797-22798`.
-  Open `show sample logs` in the output workspace. 
- `run_number` sample log shows: `22797,22798`.
- `multi_run_reduction` sample log shows: `chopped_runs`

**Added release notes**

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by sf1919** [comment]
Unfortunately I have run into an error after running the algorithm. As a result the ADS only has files for 26184 and not any grouped/combined data

Screenshot (373)_a

**Comment by adriazalvarez** [comment]
From the screenshot it looks like you have tried to load the run 02185 instead of 26185. I have input 02185 in the current stable release (6.9.1) and got the same error. So I think is not related to this PR. But if you think it is, can you give me more details so that I try to reproduce?

**Comment by sf1919** [comment]
I've continued to undertake a functional test. The only way I could get the output workspace to be correct (and named correctly) was to ensure I'd ticked `Sum Files`. Is this what I was supposed to do?

**Comment by adriazalvarez** [comment]
yes, it shouldn't do anything when you don't combine the files.

**Review by sf1919 — APPROVED** [review]
The changes look good and a good response to user need. I like the fact that users are provided with information on which runs have been summed in two ways - via the workspace name and in the sample logs. I do note that there was a concern about length of workspace name in the original issue (#36850) but I presume this is no longer a problem?

Functionally this works well and it is good to see it works with several instruments. 

Reviewing the code it is good to see the testing has been extended to include these changes and a relevant release note has been added. Looking good overall. Happy to approve.

**Pull request merged**
