### PR TITLE
Require boost 1.53

### PR DESCRIPTION
**Pull request by quantumsteve**
Description of work.

This updates the minimum version of boost to version 1.53 (which is shipped with RHEL 7). This version can construct a boost::shared_ptr from a std::unique_ptr and will make PR #15423 easier, cleaner, and less error-prone.

I'm using the [boost157 package from softwarecollections.org](https://www.softwarecollections.org/en/scls/denisarnaud/boost157/) on RHEL6 and updated the finder to look in the necessary directories.

**To test:**

verify that RHEL6 still builds and passes all tests.

No issue number.

Should this be in the release notes?

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
Looks good and all builds are happy with this.
I'd say this doesn't need to go in the release notes. Or do/will we have developer oriented release notes?

:shipit:

**Comment by martyngigg** [comment]
`boost157` is not installed on the ISIS RHEL6 machine yet. I'll merge this when that has happened.

**Comment by FedeMPouzols** [comment]
Oops, I wrongly took for granted that it had been updated on all machines.

**Comment by peterfpeterson** [comment]
It is now on all ORNL RHEL6 machines. It is ready once ISIS is.

**Comment by FedeMPouzols** [comment]
`isis-mantidlx1` now has boost-1.57, from https://www.softwarecollections.org/en/scls/denisarnaud/boost157/.

**Comment by martyngigg** [comment]
:+1:

**Pull request merged**
