### PR TITLE
Improve CompareMDWorkspaces for comparing MDEvents (master)

### PR DESCRIPTION
**Pull request by wdzhou**
**Description of work.**

Improve the MDEvent comparison in algorithm CompareMDWorkspaces.

This is ORNL SPEC #105

This is a fork from https://github.com/mantidproject/mantid/pull/31804.

**To test:**

Fixes #xxxx. 

*This does not require release notes* because **mostly internal change only**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by AndreiSavici — APPROVED** [review]

**Comment by martyngigg** [comment]
I'm not quite sure why but I think this might have caused the [`ConvertHFIRSCDtoMDE_HB3A_Test`](https://builds.mantidproject.org/view/Master%20Pipeline/job/master_systemtests-osx/1213/) test to fail on macOS and Windows.

**Comment by martyngigg** [comment]
It looks like the test passes if I disabled the sorting so I guess there are one of 2 options:
* a subtle bug in the sorting logic
* the workspaces were never supposed to be equal in the first place and this has uncovered that bug.

As it's a HFIR test I don't really feel confident in saying what the output should be. Could someone with more knowledge of that take a look?

**Comment by AndreiSavici** [comment]
https://github.com/mantidproject/mantid/pull/31873/files#diff-6e09c6fdf50d91c6170aca49a7c473225426ce5b4a2ea240ffef86569c60d1f9R425-R426
Should have used `std::stable_sort` instead

**Comment by martyngigg** [comment]
> https://github.com/mantidproject/mantid/pull/31873/files#diff-6e09c6fdf50d91c6170aca49a7c473225426ce5b4a2ea240ffef86569c60d1f9R425-R426
> Should have used `std::stable_sort` instead

That doesn't seem to help unfortunately. Could @wdzhou take a llok when he is back?

**Pull request merged**
