### PR TITLE
Add Load Button to SANS GUI

### LINKED ISSUE #23773: ISIS SANS Add option to save out Can seperately
Currently the new SANS GUI saves out the results of a reduction which is the sample reduction minus the Can reduction. Users would like to have an option where it also saves out the Can workspaces separately. 

This option probably belongs with the other save options at the bottom of the main GUI page. A lost of workspace names to save is generated here 

https://github.com/mantidproject/mantid/blob/master/scripts/SANS/sans/algorithm_detail/batch_execution.py#L918

### LINKED ISSUE #23797: Add load button to new SANS GUI
Loading through the SANS GUI automatically applies calibrations so is more useful than loading through the standard ADS. Currently loading can only be done as part of the process step however which can be time consuming and which users may not care about. This issue is to add a load button to the GUI to load the files currently listed in the table. If some rows are selected it should load only those rows and if no rows are selected it should load everything.

To get started with this issue it is worth looking at how the process button is handled as the process button does exactly this loading as its first step. 

* https://github.com/mantidproject/mantid/blob/master/scripts/SANS/sans/gui_logic/presenter/run_tab_presenter.py#L353

It is also worth looking at the provide loaded state method from here which can probably just be resued

thttps://github.com/mantidproject/mantid/blob/master/scripts/SANS/sans/gui_logic/presenter/run_tab_presenter.py#L353

### LINKED ISSUE #24212: SANS v2 - Output log error when Displaying Mask
### Expected behavior
An instrument view with a circle at the centre should be given.

### Actual behavior
Error in output log.

### Steps to reproduce the behavior
1. Open `Interfaces` > `SANS` > `SANS v2`
2. Choose Load User File; from the ISIS sample data in the loqdemo
folder, choose Maskfile.txt
3. Choose Load Batch File; from the ISIS sample data in the
loqdemo folder, choose
batch_mode_reduction.csv
4. In the Settings tab:
-Go to Mask
-Click Display Mask

The following error is seen in the output log:
image

### Platforms affected
All - I assume

### PR DESCRIPTION
**Pull request by TTitcombe**
**Description of work.**
Add a load button to the new SANS GUI. Upon click, will load selected rows (all rows if none selected) workspaces into MantidPlot.

Additionally, this PR adds a save_can button. When clicked the unsubtracted can and sample workspaces will be added to ADS.

**Report to:** [nobody]

**To test:**
- On MantidPlot, go ->Interfaces->SANS -> ISIS SANS v2 experimental
- There will be a load button near the top right of the main tab.
- Load in any accepted user and batch file and click load. The corresponding workspaces should be added to MantidPlot *without* any further reduction taking place (e.g. if you name the output workspace in the table _outputWS_, that should not appear in MantidPlot, as that is a product of the reduction).
- Copy/duplicate/create several rows of data to process. Select a combination of them and click load. The workspaces corresponding to the selected rows *only* should be in MantidPlot.

Created additional tests in `batch_process_runner_test` to check that the correct signals are being sent when workspaces are loaded.

**To test save_can functionality**: load user and batch file which contains a separate can workspace. Process with combinations of *save_can* and *use_optimizations*.
- When *save_can* is ticked: output workspaces for LAB_SAMPLE and HAB_SAMPLE in a group
- When *use_optimization* is ticked: output workspaces for LAB/HAB _NORM and _COUNTS in a group titled "optimizations". The unsubtracted can workspace should be in the same group as the samples.

**If saving to a file only:**
- Only raw data and optimization workspaces should be on ADS
- If save_can is ticked the sample should **not** be on ADS but the can **should** be. However can workspaces should be in the optimizations group to be kept out of the way and avoid user confusion.
- Check that can and sample are also saved out when save_can is checked

**If saving to both:**
- check that can and sample workspaces saved when save_can is checked.
- Workspaces on ADS should be the same as when using save mode _memory_

Fixes #23797 
Fixes #23773 
Fixes #24212

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by TTitcombe** [comment]
Do not pull yet as including issue #24129 into this PR

**Review by Matthew-Andrew — CHANGES_REQUESTED** [review]
Mostly looks good just a few things I noticed whilst testing:
  * Currently the unsubtracted sample doesn't seem to be saved out when save Can is ticked.
  * Can the can workspace be put in the optimizations workspace group if save can is not selected. I am a bit worried users might get confused by the current setup
  * There is an odd error probably unrelated to this PR whereby if I load some data which does not exist i.e. add a couple of 00's onto the end of a run number and them click process rather than just skip over processing that row a message box pops up with an error message todo with dicts and items
  * I've also queried a few things in the code below.

**Comment by Mantid-Matthew** [comment]
@TTitcombe All previous issues seem to be dealt with :+1:  I am still seeing one inconsistency however. If I run a reduction with use optimizations unticked and save can ticked I currently don't get the can workspaces output to the ADS

**Review by Matthew-Andrew — DISMISSED** [review]
This now works as intended :+1:

**Review by Matthew-Andrew — APPROVED** [review]

**Pull request merged**
