### PR TITLE
EnginX Calibration plots workspace automatically

### LINKED ISSUE #24775: EnginX Calibration Plotting
The fit ran for the calibration in the Engineering gui is plotted, the scientists would like the same to happen when running the script.

### PR DESCRIPTION
**Pull request by LowriJenkins**
**Description of work.**
The EnginX GUI calibration automatically plots the calibrations made, this change makes it so that the script also does this.
**To test:**
```
import Engineering.EnginX as Enginx
Enginx.main("236516", "test", None, force_cal=True)
```
The difcs from calibration should be plotted

Fixes #24775 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Mantid-Matthew** [comment]
This works fine for me when run from inside mantidplot. 

However when I run the scripts from mantidpython which I'm assuming approximates the autoreduction framework I find that the plots when they appear are unresponsive. I cannot close them without closing the mantidpython session and none of the others options seems to work.

**Comment by Mantid-Matthew** [comment]
I just did `sh bin/mantidpython` which yes is IPython I think. The script interpreter within mantidplot did not seem to have an issue though if that is helpful in narrowing things down.

**Review by Matthew-Andrew — APPROVED** [review]
This seems to be a niche issue on unity which won't effect the intended use cases so approving.

**Comment by martyngigg** [comment]
As we've had issues before with system tests I'm just going to verify they work still on macOS & Ubuntu. Have you tried Windows?

**Review by martyngigg — CHANGES_REQUESTED** [review]
There is one minor issue on my Ubuntu environment. I don't have the `python-tk` package installed, the build servers might not either, and running the tests at the moment gives:
```python

```

If we add

```python
os.environ['MPLBACKEND'] = 'Agg'
```
underneath the sip stuff at https://github.com/mantidproject/mantid/blob/master/Testing/SystemTests/scripts/runSystemTests.py#L30 then this will a make sure that matplotlib uses the non-interactive backend.

**Comment by martyngigg** [comment]
@ElliotAOram Does ISIS autoreduction set the `MPLBACKEND` yet?

**Comment by martyngigg** [comment]
It works on `macOS` :+1:

**Review by martyngigg — APPROVED** [review]
Works for me on Ubuntu now without Tk installed.

**Pull request merged**
