### PR TITLE
New algorithm: LineProfile

### LINKED ISSUE #19286: Algorithm for making horizontal and vertical cuts or slices from a MatrixWorkspace
Mantid lacks a proper algorithm for making arbitrarily bounded averaged cuts or slices of a MatrixWorkspace. Existing algorithms such as [Rebin2D](http://docs.mantidproject.org/nightly/algorithms/Rebin2D-v1.html) do not handle special values, especially NaNs correctly. These should not be taken into account at all when the average is calculated. Additionally, rebinning params are clumsy to use in this case.

### PR DESCRIPTION
**Pull request by soininen**
This PR introduces a new algorithm LineProfile. The algorithm gives a horizontal or vertical cut of a Matrix workspace by averaging or summing the bins over a given line width.

**To test:**

Try giving the algorithm both correct and incorrect input. Does it behave as expected in the 'usual' cases? How about corner cases? Are error/warning messages comprehensible?

A close-to real-life use case is shown below. The *SofQWNormalisedPolygon* algorithm produces a workspace where NaNs signify missing data which should be ignored in the profile.
```python
# Add correct path-to-build below!
buildDir = <path to Mantid's build dir>
Load(
    Filename=dataDir + 'ExternalData/Testing/Data/UnitTest/ILL/IN4/084447.nxs', 
    OutputWorkspace='084447')
ExtractMonitors(
    InputWorkspace='084447',
    DetectorWorkspace='dets', MonitorWorkspace='mons')
CorrectTOFAxis(
    InputWorkspace='dets',
    OutputWorkspace='in_tof',
    IndexType='Workspace Index',
    ElasticBinIndex=175,
    L2=2)
ConvertUnits(
    InputWorkspace='in_tof',
    OutputWorkspace='in_DeltaE',
    Target='DeltaE',
    EMode='Direct',
    ConvertFromPointData=False)
Rebin(
    InputWorkspace='in_DeltaE',
   OutputWorkspace='rebinned_DeltaE',
   Params='-80,1,8',
   PreserveEvents=False)
ws = SofQWNormalisedPolygon(
    InputWorkspace='rebinned_DeltaE',
    OutputWorkspace='SofQW',
    QAxisBinning='0,0.05,8',
    EMode='Direct')
profile = LineProfile(
    InputWorkspace=ws,
    Direction='Horizontal',
    Centre=2,
    HalfWidth=1,
    Start=-50,
    End=-5,
    IgnoreNans=True)
# Comparion to a case where NaNs are replaced by zeros.
ReplaceSpecialValues(
    InputWorkspace=ws,
    OutputWorkspace='infsremoved'
    NanValue=0,
    NanError=0)
profile_NaNs = LineProfile(
    InputWorkspace='infsremoved',
    Direction='Horizontal',
    Centre=2,
    HalfWidth=1,
    Start=-50,
    End=-5,
    IgnoreNans=True)
```

Fixes #19286.

*Release notes were updated accordingly.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by mantid-roman — CHANGES_REQUESTED** [review]

**Comment by mantid-roman** [comment]
Will the name of the algorithm be clear to all users? To me it sounds like jargon of a particular technique.

**Comment by mantid-roman** [comment]
Setting `Start > End` gave me an unclear error message:
```
RuntimeError: Histogram: BinEdges size cannot be 1
```

**Comment by mantid-roman** [comment]
Setting `HalfWidth` to a negative number produces a histogram of nans and no error message.

**Comment by mantid-roman** [comment]
Setting `HalfWidth` to a large negative number gives error:
```
Profile completely outside input workspace.
```

**Comment by soininen** [comment]
Thanks for reviewing this! There was indeed a bug in how the validator for `HalfWidth` was set up and I forgot to check that *Start* < *End* in `validateInputs()`. These should now be fixed.

**Comment by soininen** [comment]
@mantid-roman Let me know if you have good ideas for the algorithm's name. `LineProfile` was a natural choice for me, but maybe the users might be looking for something different... `Cut`? `LineCut`? `CutProfile`? `CrossSection`?

**Review by mantid-roman — APPROVED** [review]

**Comment by mantid-roman** [comment]
@soininen I don't have a name suggestion. You can ask people on Slack and if there is a better alternative rename it later. Otherwise everything looks fine to me. :shipit:

**Comment by NickDraper** [comment]
All looks good, merging

**Pull request merged**
