### PR TITLE
Bugfix for SNS live data

### PR DESCRIPTION
**Pull request by stuartcampbell**
Description of work.

@peterfpeterson's bugfix for SNS live data

**To test:**

Start live data on POWGEN and run the processing script

``` python
import os
cal_dir = '/SNS/PG3/shared/CALIBRATION/2016_2_11A_CAL/'
cal_file  = os.path.join(cal_dir, 'PG3_PAC_d29581_2016_08_29.h5')
char_file = os.path.join(cal_dir, 'PG3_char_2016_08_01-HR-PAC-8mm.txt')

print 'Number events =', input.getNumberEvents()

PDLoadCharacterizations(Filename=char_file,
                        OutputWorkspace='characterizations')
PDDetermineCharacterizations(InputWorkspace=input,
                             Characterizations='characterizations',
                             ReductionProperties='__pd_reduction_properties')
manager=PropertyManagerDataService.retrieve('__pd_reduction_properties')
Rebin(InputWorkspace=input, OutputWorkspace=input,
Params=(manager['tof_min'].value,100,manager['tof_max'].value))


if True: #input.getNumberEvents() > 0:
    AlignAndFocusPowder(InputWorkspace=input, OutputWorkspace=output,
                        CalFilename=cal_file,
                        Params=-0.0008,
                        RemovePromptPulseWidth=50,
                        ReductionProperties='__pd_reduction_properties')
```

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by rosswhitfield** [comment]
I still see a lot of warnings, I assume this is what you were trying to fix?
```
...
SNSLiveEventDataListener-[Warning] Invalid pixel ID: 205300 (TofF: 14778.7 microseconds)
SNSLiveEventDataListener-[Warning] Invalid pixel ID: 134920 (TofF: 3368.9 microseconds)
SNSLiveEventDataListener-[Warning] Invalid pixel ID: 196090 (TofF: 1628 microseconds)
SNSLiveEventDataListener-[Warning] Invalid pixel ID: 196361 (TofF: 9988.6 microseconds)
SNSLiveEventDataListener-[Warning] Invalid pixel ID: 159237 (TofF: 4836.6 microseconds)
...
```

**Comment by stuartcampbell** [comment]
@peterfpeterson - Was this supposed to fix the invalid pixel stuff ? or is some other issue that should be merged anyway ?

**Comment by peterfpeterson** [comment]
It fixes an issue with the `Frequency` log being missing on live data.

**Comment by rosswhitfield** [comment]
OK. So I connected to live data but I still don't see the `Frequency` log? What am I meant to be testing here?

**Comment by peterfpeterson** [comment]
That is the point. Before this change, the run object would throw an error on the very first log not found. With this change, it will actually try all three.

**Comment by rosswhitfield** [comment]
But I didn't see any errors before.

**Comment by peterfpeterson** [comment]
The testing instructions were wrong. You could probably reduce it to running `RemovePromptPulse`.

**Comment by rosswhitfield** [comment]
Whatever :shipit:

**Pull request merged**
