### PR TITLE
Remove manual linking to asan library

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

If included then clang on Linux reports "incompatible ASan runtimes"
on running the executables. This lets the -fsanitize flag handle
everything, which seems to do the correct thing for gcc and clang.

**Report to:** [nobody]. 

**To test:**

* Build `KernelTest` with address sanitizer (`WITH_ASAN`) with clang on Linux
* Run `KernelTest` and see there are no errors about incompatible ASan runtimes

*There is no associated issue.*

*This does not require release notes* because **it is a developer change.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by quantumsteve — CHANGES_REQUESTED** [review]
I agree that the manual linking is incorrect.

Tried building and running tests with both GCC and clang on Ubuntu 18.04. No issues with GCC, but encountering problems running python tests with clang. See for example

```
~/Documents/MantidProject/build$ ctest -R python.SANS.user_file.state_director_test.state_director_test --verbose
UpdateCTestConfiguration  from :/home/svh/Documents/MantidProject/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/svh/Documents/MantidProject/build/DartConfiguration.tcl
Test project /home/svh/Documents/MantidProject/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1931
    Start 1931: python.SANS.user_file.state_director_test.state_director_test

1931: Test command: /home/svh/Documents/MantidProject/build/bin/mantidpython "--classic" "/home/svh/Documents/MantidProject/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/home/svh/Documents/MantidProject/mantid/scripts/test/SANS/user_file/state_director_test.py"
1931: Environment variables: 
1931:  PYTHONPATH=/home/svh/Documents/MantidProject/build/python-xmlrunner-src:/home/svh/Documents/MantidProject/mantid/scripts/test/SANS/user_file:
1931: Test timeout computed to be: 300
1931: Traceback (most recent call last):
1931:   File "/home/svh/Documents/MantidProject/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py", line 134, in <module>
1931:     import mantid  # noqa
1931:   File "/home/svh/Documents/MantidProject/build/bin/mantid/__init__.py", line 102, in <module>
1931:     import mantid.kernel as kernel
1931:   File "/home/svh/Documents/MantidProject/build/bin/mantid/kernel/__init__.py", line 17, in <module>
1931:     from ._kernel import *
1931: ImportError: /home/svh/Documents/MantidProject/build/bin/libMantidTypes.so: undefined symbol: __asan_option_detect_stack_use_after_return
1/1 Test #1931: python.SANS.user_file.state_director_test.state_director_test ...***Failed    0.05 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.12 sec

The following tests FAILED:
	1931 - python.SANS.user_file.state_director_test.state_director_test (Failed)
Errors while running CTest
```

**Comment by martyngigg** [comment]
Interesting - thanks. I'd only tried the C++ tests. I'll take another look when I get some time.

**Comment by martyngigg** [comment]
It seems the default link type is different between gcc and clang [is different](https://stackoverflow.com/questions/47021422/how-to-enable-address-sanitizer-for-multiple-c-binaries/47022141#47022141) and it looks like this is causing problems when `python`, which does not have asan enabled, tries to load the sanitize-enabled shared libraries. Using `shared-libasan` does not appear to work either.

@quantumsteve I was wondering whether it would be acceptable to merge this and open a separate issue for the Python tests under clang? I think there is still value in being able to instrument the C++ unit tests.

**Review by quantumsteve — APPROVED** [review]

**Comment by quantumsteve** [comment]
I'm fine with moving clang to a separate issue.

**Pull request merged**
