### PR TITLE
Fix isis direct reduction wait mode

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Fixes a mixup between a method/value comparision in direct reduction scripts.

**To test:**

* Run the `MARIReductionWaitAndSum` system test and it should pass
* All system tests should pass

*There is no associated issue.*

*This does not require release notes* because **it was broken this dev cycle.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by abuts — DISMISSED** [review]
This is absolutely necessary changes, fixing direct inelastic reduction script currently broken in nightly. 
Needs urgent merge and commit to nightly

**Comment by martyngigg** [comment]
Thanks, Alex. I will just make sure the CI checks pass (or it won't deploy anyway) and then I'll merge it

**Review by abuts — APPROVED** [review]
Apparently, the system tests, related to the issue have been disabled. Set of changes was necessary to fix enabled  tests+ it worth adding the check for the archive commit log.

If the tests were disabled because they were failing (in parallel mode), its a huge problem for Mantid.

**Comment by martyngigg** [comment]
The tests were disabled by accident after a python 2->3 conversion and there is no problem with them running in parallel.

**Pull request merged**
