### PR TITLE
Use new workflow algorithm for live data monitor

### LINKED ISSUE #26119: Live monitor should use new workflow algorithm
The live monitor is currently failing on the ISIS Reflectometry GUI because it is using `ReflectometryReductionOneAuto`, but the GUI now provides properties in a format for the new workflow algorithm `ReflectometryISISLoadAndProcess`. We should switch to use the latter algorithm from the GUI. This will also provide additional functionality such as summing transmission runs and slicing input runs.

### PR DESCRIPTION
**Pull request by gemmaguest**
**Report to:** Max at ISIS

This PR fixes a bug where the live data monitor does not start on the ISIS Reflectometry GUI.

- Replace direct use of ReflectometryReductionOneAuto with the new wrapper ReflectometryISISLoadAndProcess. This fixes a problem with invalid properties being passed from the GUI, which also uses the latter. It also gives it more comprehensive support of the new GUI features such as being able to sum input transmission runs.
- Tidy up property lists in the algorithms.
- Fix an issue where a clone was being done of the input live workspace which was only updated with the output values when the first chunk of data arrives. This was confusing users. The output workspace now only appears when the data arrives.
- Make grouping of TOF workspaces optional so that we can disable it for live data.
- Make reloading of input workspaces optional so that we can disable it for live data - if for some reason the workspace is not there or is the wrong type we would get a confusing error if we try to reload it from file because there is no file for live data.

Fixes #26119

**To test:**

- Open the ISIS Reflectometry GUI
- Click `Start monitor`
- Ensure there are no errors about invalid properties being set
- Depending on whether live data is available for the current instrument you may get other errors about theta being zero or a timeout trying to access the DAE. You could try a different instrument in this case.

Release notes to follow

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by dtasev — APPROVED** [review]
Started the live monitor with INTER and data was loaded and processed correctly. No errors shown

**Review by dtasev — CHANGES_REQUESTED** [review]
Requesting changes as some of the tests need adjusting

**Comment by DTasev** [comment]
I'm rebooting the [failed Ubuntu Python 3 build](https://builds.mantidproject.org/job/pull_requests-ubuntu-python3/18905/) as it's a `test_sliceviewer` fail I haven't seen before

**Review by dtasev — APPROVED** [review]
Added `test_sliceviewer` to unreliable tests ([build](https://builds.mantidproject.org/job/pull_requests-ubuntu-python3/18905/)). All tests now pass here

**Pull request merged**
