### PR TITLE
Preparation for Euphonic version bump: make compatible with both 0.6 and 1.*

### PR DESCRIPTION
**Pull request by ajjackson**
**Description of work**
Make Abins and SimulatedDensityOfStates compatible with newer versions of Euphonic than currently pinned. At this point the pin is _not_ changed.

Clean up some of the legacy logic from this code.

**Purpose of work**
Mantid has pinned euphonic to 0.6.x, which is outdated. This has caused some dependency complications (#35797 ) and is blocking some Abins refactoring/features (e.g. #33755)

Rather than update the dependency, existing code and incorporate new features simultaneously, here we begin by making it possible to update the dependency without (hopefully) breaking anything that already exists.

**Summary of work**
- Prepare Mantid for API changes in Euphonic versions 1.x, ahead of updating dependency.
- Remove logic in SimulatedDensityOfStates and Abins that handle missing Euphonic library, as _some_ version of this dependency should always be available in current versions of Mantid. (This dates from the pre-Conda Mantid in which Euphonic was an optional dependency.)
- Remove complex temporary installation from Systemtest; again, this is no longer needed

**Further detail of work**
The API change isn't such a big problem to handle: one small function has been deprecated and as it wraps one that still exists we can just insert equivalent code.

**To test:**

With the `main` branch of Mantid, update Euphonic to a version > 1.0 using mamba. (The current release is 1.2.0). Run Mantid unit tests and systemtests; some of them should fail. (In particular the SimulatedDensityOfStates systemtests; to avoid running unrelated tests you could use `-R Abins` and `-R SimulatedDensity` arguments!)

On this branch, the tests should pass with both Euphonic 0.6.* and with Euphonic 1.*

*This does not require release notes* because **there are no user-facing changes, unless they are in the habit of installing incorrect package versions in their Mantid environment**

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by robertapplin** [comment]
The code changes look great. When I run all the Abins tests, the `AbinsCRYSTAL2D` fails:

```
./systemtest.bat -R Abins

test_name: AbinsTest.AbinsCRYSTAL2D
filename: C:\Users\mlc47243\Documents\mantid-dev\mantid-review\mantid\Testing\SystemTests\tests\framework\AbinsTest.py
test_date: 2023-07-20 16:40:55
host_name: NDLT1353
environment: win64
status: failed validation
time_taken: 4.68
memory footprint increase: 10.5
output:
RESULT|iteration time_taken|1 4.68
RESULT|time_taken|4.68
AbinsCRYSTAL2D
Saving mismatch to "AbinsCRYSTAL2D-mismatch.nxs"
Workspace AbinsCRYSTAL2D not equal to its reference file
RESULT|memory footprint increase|10.5
```

This does not happen if I run `AbinsCRYSTAL2D` on its own

**Comment by robertapplin** [comment]
I also get an error when running the SimulatedDensity system tests. I'm running these on Windows

```
$ ./systemtest.bat -R SimulatedDensity
Updating testing data...
ninja: no work to do.
ninja: no work to do.

Running tests...
FrameworkManager-[Notice] Welcome to Mantid 6.7.20230719.0915.dev6+uncommitted
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid
ConfigService-[Information] logging set to information priority
=============================================
SimulatedDensityOfStates
Na2SiF6_DOS.nxs
phonopy-Al_DOS.nxs
This ISIS Command Interface is deprecated.
Please change 'import ISISCommandInterface' or 'from ISISCommandInterface'to use 'sans.command_interface.ISISCommandInterface' instead.
Test module SimulatedDensityOfStates has 2 tests:
    - SimulatedDensityOfStates.SimulatedDensityOfStatesEuphonicTest
    - SimulatedDensityOfStates.SimulatedDensityOfStatesTest
Traceback (most recent call last):
  File "C:\Users\mlc47243\Documents\mantid-dev\mantid-review\mantid\Testing\SystemTests\lib\systemtests\systemtesting.py", line 710, in start_in_current_process
    exec(script.asString(self._clean), exec_globals, exec_locals)
  File "<string>", line 8, in <module>
ImportError: cannot import name 'SimulatedDensityOfStatesEuphonicTest' from 'SimulatedDensityOfStates' (C:/Users/mlc47243/Documents/mantid-dev/mantid-review/mantid/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SimulatedDensityOfStates.py)

********************************************************************************
test_name: SimulatedDensityOfStates.SimulatedDensityOfStatesEuphonicTest
filename: C:\Users\mlc47243\Documents\mantid-dev\mantid-review\mantid\Testing\SystemTests\tests\framework\SimulatedDensityOfStates.py
test_date: 2023-07-20 16:47:11
host_name: NDLT1353
environment: win64
status: algorithm failure
time_taken:
output:
SystemTest runner script produced no output to StdOut
err:
********************************************************************************

Traceback (most recent call last):
  File "C:\Users\mlc47243\Documents\mantid-dev\mantid-review\mantid\Testing\SystemTests\lib\systemtests\systemtesting.py", line 710, in start_in_current_process
    exec(script.asString(self._clean), exec_globals, exec_locals)
  File "<string>", line 8, in <module>
ImportError: cannot import name 'SimulatedDensityOfStatesTest' from 'SimulatedDensityOfStates' (C:/Users/mlc47243/Documents/mantid-dev/mantid-review/mantid/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SimulatedDensityOfStates.py)

********************************************************************************
test_name: SimulatedDensityOfStates.SimulatedDensityOfStatesTest
filename: C:\Users\mlc47243\Documents\mantid-dev\mantid-review\mantid\Testing\SystemTests\tests\framework\SimulatedDensityOfStates.py
test_date: 2023-07-20 16:47:11
host_name: NDLT1353
environment: win64
status: algorithm failure
time_taken:
output:
SystemTest runner script produced no output to StdOut
err:
********************************************************************************


################################################################################
Total runtime: 00:00:07

FAILED:
SimulatedDensityOfStates.SimulatedDensityOfStatesEuphonicTest
SimulatedDensityOfStates.SimulatedDensityOfStatesTest

0% tests passed, 2 tests failed out of 2 (0 skipped)
```

**Comment by ajjackson** [comment]
> The code changes look great. When I run all the Abins tests, the `AbinsCRYSTAL2D` fails:
> 
...
> 
> This does not happen if I run `AbinsCRYSTAL2D` on its own. I am using euphonic 1.2.1

I've seen this one locally, but some reason it doesn't happen on the CI. It's a puzzling one... but I don't think it is related to these changes or the Euphonic version.

The Windows one looks like it might be a namespace collision between the SimulatedDensityOfStates.py test and algorithm of the same name. I had wondered if that would be a problem but it worked fine on Linux, would not have guessed it is OS-dependent :sweat_smile: Will see if that can be fixed by renaming the test file.

**Comment by ajjackson** [comment]
Ok, have pushed up the file rename. I don't have a Windows machine to test with, could you try running the systemtests on this?

I will open a new Issue re: the AbinsCRYSTAL2D failure

**Comment by robertapplin** [comment]
> Ok, have pushed up the file rename. I don't have a Windows machine to test with, could you try running the systemtests on this?

Thanks for looking into this. It looks like one of the tests is now passing, but there is a failure for the other:

```
$ ./systemtest.bat -R SimulatedDensity
Updating testing data...
ninja: no work to do.
ninja: no work to do.

Running tests...
FrameworkManager-[Notice] Welcome to Mantid 6.7.20230719.0915.dev6+uncommitted
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid
ConfigService-[Information] logging set to information priority
=============================================
SimulatedDensityOfStatesEuphonicPackaging
Na2SiF6_DOS.nxs
phonopy-Al_DOS.nxs
This ISIS Command Interface is deprecated.
Please change 'import ISISCommandInterface' or 'from ISISCommandInterface'to use 'sans.command_interface.ISISCommandInterface' instead.
Test module SimulatedDensityOfStatesEuphonicPackaging has 2 tests:
    - SimulatedDensityOfStatesEuphonicPackaging.SimulatedDensityOfStatesEuphonicTest
    - SimulatedDensityOfStatesEuphonicPackaging.SimulatedDensityOfStatesTest
Traceback (most recent call last):
  File "C:\Users\mlc47243\Documents\mantid-dev\mantid-review\mantid\Testing\SystemTests\lib\systemtests\systemtesting.py", line 710, in start_in_current_process
    exec(script.asString(self._clean), exec_globals, exec_locals)
  File "<string>", line 12, in <module>
  File "C:\Users\mlc47243\Documents\mantid-dev\mantid-review\mantid\Testing\SystemTests\lib\systemtests\systemtesting.py", line 260, in execute
    self.runTest()
  File "C:\Users\mlc47243\Documents\mantid-dev\mantid-review\mantid\Testing\SystemTests\tests\framework\SimulatedDensityOfStatesEuphonicPackaging.py", line 122, in runTest
    self._install_euphonic_to_tmp_prefix(tmp_prefix)
  File "C:\Users\mlc47243\Documents\mantid-dev\mantid-review\mantid\Testing\SystemTests\tests\framework\SimulatedDensityOfStatesEuphonicPackaging.py", line 116, in _install_euphonic_to_tmp_prefix
    cls._add_libs_from_prefix(pathlib.Path(tmp_prefix))
  File "C:\Users\mlc47243\Documents\mantid-dev\mantid-review\mantid\Testing\SystemTests\tests\framework\SimulatedDensityOfStatesEuphonicPackaging.py", line 53, in _add_libs_from_prefix
    ("Could not find site-packages for temporary dir. " "Here are the directory contents: ") + "; ".join(directory_contents)
TypeError: sequence item 0: expected str instance, WindowsPath found

********************************************************************************
test_name: SimulatedDensityOfStatesEuphonicPackaging.SimulatedDensityOfStatesEuphonicTest
filename: C:\Users\mlc47243\Documents\mantid-dev\mantid-review\mantid\Testing\SystemTests\tests\framework\SimulatedDensityOfStatesEuphonicPackaging.py
test_date: 2023-07-24 09:16:11
host_name: NDLT1353
environment: win64
status: algorithm failure
time_taken:
output:
SystemTest runner script produced no output to StdOut
err:
********************************************************************************

SimulatedDensityOfStates-[Notice] SimulatedDensityOfStates started
SimulatedDensityOfStates-[Information] Algorithm: SimulatedDensityOfStates v1
SimulatedDensityOfStates-[Information] Execution Date: 2023-07-24 08:16:11.672542000
SimulatedDensityOfStates-[Information] Execution Duration: -1 seconds
SimulatedDensityOfStates-[Information] UUID: 4ec4fb2e-50a8-44b9-9258-deef5650291d
SimulatedDensityOfStates-[Information] Parameters:
SimulatedDensityOfStates-[Information]   Name: CASTEPFile, Value: C:\Users\mlc47243 ... iF6_CASTEP.phonon, Default?: No, Direction: Input
SimulatedDensityOfStates-[Information]   Name: PHONONFile, Value: , Default?: Yes, Direction: Input
SimulatedDensityOfStates-[Information]   Name: ForceConstantsFile, Value: , Default?: Yes, Direction: Input
SimulatedDensityOfStates-[Information]   Name: ForceConstantsSampling, Value: 20, Default?: Yes, Direction: Input
SimulatedDensityOfStates-[Information]   Name: Function, Value: Gaussian, Default?: Yes, Direction: Input
SimulatedDensityOfStates-[Information]   Name: PeakWidth, Value: 10.0, Default?: Yes, Direction: Input
SimulatedDensityOfStates-[Information]   Name: SpectrumType, Value: DOS, Default?: Yes, Direction: Input
SimulatedDensityOfStates-[Information]   Name: CalculateIonIndices, Value: 0, Default?: Yes, Direction: Input
SimulatedDensityOfStates-[Information]   Name: StickHeight, Value: 0.01, Default?: Yes, Direction: Input
SimulatedDensityOfStates-[Information]   Name: Scale, Value: 1, Default?: Yes, Direction: Input
SimulatedDensityOfStates-[Information]   Name: BinWidth, Value: 1, Default?: Yes, Direction: Input
SimulatedDensityOfStates-[Information]   Name: Temperature, Value: 300, Default?: Yes, Direction: Input
SimulatedDensityOfStates-[Information]   Name: ZeroThreshold, Value: 3, Default?: Yes, Direction: Input
SimulatedDensityOfStates-[Information]   Name: Ions, Value: , Default?: Yes, Direction: Input
SimulatedDensityOfStates-[Information]   Name: SumContributions, Value: 0, Default?: Yes, Direction: Input
SimulatedDensityOfStates-[Information]   Name: ScaleByCrossSection, Value: None, Default?: Yes, Direction: Input
SimulatedDensityOfStates-[Information]   Name: OutputWorkspace, Value: Na2SiF6_DOS, Default?: No, Direction: Output
Python-[Notice] Calculating summed density of states without scaled intensities
SimulatedDensityOfStates-[Notice] SimulatedDensityOfStates successful, Duration 0.05 seconds
RESULT|iteration time_taken|1 0.05
RESULT|time_taken|0.06
FileFinder-[Information] found path = C:\Users\mlc47243\Documents\mantid-dev\mantid-review\buildninja\ExternalData\Testing\Data\SystemTest\Na2SiF6_DOS.nxs
Load-[Notice] Load started
Load-[Information] Algorithm: Load v1
Load-[Information] Execution Date: 2023-07-24 08:16:11.797506000
Load-[Information] Execution Duration: -1 seconds
Load-[Information] UUID: 676ce225-d297-451d-a07b-5f822dbd52b2
Load-[Information] Parameters:
Load-[Information]   Name: Filename, Value: C:\Users\mlc47243 ... t\Na2SiF6_DOS.nxs, Default?: No, Direction: Input
Load-[Information]   Name: OutputWorkspace, Value: RefFile, Default?: No, Direction: Output
Load-[Information]   Name: LoaderName, Value: LoadNexusProcessed, Default?: No, Direction: Output
Load-[Information]   Name: LoaderVersion, Value: 2, Default?: No, Direction: Output
Load-[Information]   Name: SpectrumMin, Value: 1, Default?: Yes, Direction: Input
Load-[Information]   Name: SpectrumMax, Value: 2147483647, Default?: Yes, Direction: Input
Load-[Information]   Name: SpectrumList, Value: , Default?: Yes, Direction: Input
Load-[Information]   Name: EntryNumber, Value: 0, Default?: Yes, Direction: Input
Load-[Information]   Name: LoadHistory, Value: 1, Default?: Yes, Direction: Input
Load-[Information]   Name: FastMultiPeriod, Value: 1, Default?: Yes, Direction: Input
Load-[Information] Using LoadNexusProcessed version 2.
ExperimentInfo-[Information] run_start/start_time not stored in workspace. Default to current date.
LoadNexusProcessed-[Information] detector_list block not found. The workspace will not contain any detector information.
Load-[Notice] Load successful, Duration 0.08 seconds
CompareWorkspaces-[Notice] CompareWorkspaces started
CompareWorkspaces-[Information] Algorithm: CompareWorkspaces v1
CompareWorkspaces-[Information] Execution Date: 2023-07-24 08:16:11.877535000
CompareWorkspaces-[Information] Execution Duration: -1 seconds
CompareWorkspaces-[Information] UUID: 8e62807d-bee6-42ae-bb9e-a20049f37dce
CompareWorkspaces-[Information] Parameters:
CompareWorkspaces-[Information]   Name: Workspace1, Value: Na2SiF6_DOS, Default?: No, Direction: Input
CompareWorkspaces-[Information]   Name: Workspace2, Value: RefFile, Default?: No, Direction: Input
CompareWorkspaces-[Information]   Name: Tolerance, Value: 1e-08, Default?: No, Direction: Input
CompareWorkspaces-[Information]   Name: CheckType, Value: 1, Default?: Yes, Direction: Input
CompareWorkspaces-[Information]   Name: CheckAxes, Value: 1, Default?: Yes, Direction: Input
CompareWorkspaces-[Information]   Name: CheckSpectraMap, Value: 1, Default?: Yes, Direction: Input
CompareWorkspaces-[Information]   Name: CheckInstrument, Value: 1, Default?: Yes, Direction: Input
CompareWorkspaces-[Information]   Name: CheckMasking, Value: 1, Default?: Yes, Direction: Input
CompareWorkspaces-[Information]   Name: CheckSample, Value: 0, Default?: Yes, Direction: Input
CompareWorkspaces-[Information]   Name: ToleranceRelErr, Value: 0, Default?: Yes, Direction: Input
CompareWorkspaces-[Information]   Name: CheckAllData, Value: 0, Default?: Yes, Direction: Input
CompareWorkspaces-[Information]   Name: NumberMismatchedSpectraToPrint, Value: 1, Default?: Yes, Direction: Input
CompareWorkspaces-[Information]   Name: DetailedPrintIndex, Value: 2147483647, Default?: Yes, Direction: Input
CompareWorkspaces-[Information]   Name: Result, Value: 0, Default?: Yes, Direction: Output
CompareWorkspaces-[Information]   Name: Messages, Value: compare_msgs, Default?: Yes, Direction: Output
CompareWorkspaces-[Notice] The workspaces "Na2SiF6_DOS" and "RefFile" matched!
CompareWorkspaces-[Notice] CompareWorkspaces successful, Duration 0.06 seconds
RESULT|memory footprint increase|7.265625

********************************************************************************
test_name: SimulatedDensityOfStatesEuphonicPackaging.SimulatedDensityOfStatesTest
filename: C:\Users\mlc47243\Documents\mantid-dev\mantid-review\mantid\Testing\SystemTests\tests\framework\SimulatedDensityOfStatesEuphonicPackaging.py
test_date: 2023-07-24 09:16:11
host_name: NDLT1353
environment: win64
status: success
time_taken: 0.06
memory footprint increase: 7.265625
output:
RESULT|iteration time_taken|1 0.05
RESULT|time_taken|0.06
RESULT|memory footprint increase|7.265625

err:
********************************************************************************


################################################################################
Total runtime: 00:00:18

FAILED:
SimulatedDensityOfStatesEuphonicPackaging.SimulatedDensityOfStatesEuphonicTest

50% tests passed, 1 tests failed out of 2 (0 skipped)
All tests passed? False
```

**Comment by robertapplin** [comment]
> I've seen this one locally, but some reason it doesn't happen on the CI. It's a puzzling one... but I don't think it is related to these changes or the Euphonic version.

The system tests only get run on Linux for our CI (for speed reasons), so that would explain why we don't see the failure on there. If it helps, I can create a PR to help you debug the issue (a bit like this one https://github.com/mantidproject/mantid/pull/35683) ?

**Comment by ajjackson** [comment]
> =============================================
SimulatedDensityOfStatesEuphonicPackaging
Na2SiF6_DOS.nxs
phonopy-Al_DOS.nxs
This ISIS Command Interface is deprecated.
Please change 'import ISISCommandInterface' or 'from ISISCommandInterface'to use 'sans.command_interface.ISISCommandInterface' instead.
Test module SimulatedDensityOfStatesEuphonicPackaging has 2 tests:
    - SimulatedDensityOfStatesEuphonicPackaging.SimulatedDensityOfStatesEuphonicTest
    - SimulatedDensityOfStatesEuphonicPackaging.SimulatedDensityOfStatesTest

I don't understand. The file `SimulatedDensityOfStatesEuphonicPackaging.py` has been renamed in the last commit, this test shouldn't exist with this name.

**Comment by robertapplin** [comment]
> I don't understand. The file SimulatedDensityOfStatesEuphonicPackaging.py has been renamed in the last commit, this test shouldn't exist with this name. Is it running on stale file?

It looks like your last commit renames SimulatedDensityOfStates.py to SimulatedDensityOfStatesTest.py , if I am reading that right?

**Comment by ajjackson** [comment]
Ah sorry, it is actually the last two commits.

First I changed _SimulatedDensityOfStatesEuphonicPackaging.py_ to _SimulatedDensityOfStates.py_ but this caused an error on the Windows tests, probably because it ended up putting this into the same namespace as the Algorithm of same name. So the next commit renamed the same file to _SimulatedDensityOfStatesTest.py_.

From the "Files changed" tab I can see that the file _SimulatedDensityOfStatesEuphonicPackaging.py_ has been removed, so I don't see how it can turn up in tests with a clean environment.

**Comment by robertapplin** [comment]
> Ah sorry, it is actually the last two commits.

Ah ok, I see that now! I've cleaned my build folder and run the test again, and it seems to be working now - so thanks for those changes!

**Review by robertapplin — APPROVED** [review]
Happy to approve this as the failing `AbinsCRYSTAL2D` system test on windows is unrelated to this PR. A separate issue to deal with this has been opened here https://github.com/mantidproject/mantid/issues/35830

**Pull request merged**
