### PR TITLE
Move FitDataModel to common location on Inelastic interfaces

### LINKED ISSUE #37063: Investigate why Elwin is using a `FitDataModel`
**Describe the outcome that is desired.**
It appears the Elwin presenter has a FitDataModel. To my knowledge, Elwin is not performing a fit, so its confusing why its using a FitDataModel.

We need to figure out if the `FitDataModel` has a misleading name, or if Elwin shouldn't be using the FitDataModel.

If the `FitDataModel` should be used by Elwin, we should move it out of the `QENSFitting` folder and into the `Common` folder because it is also used in the Manipulations interface.

**Acceptance Criteria**
- The FitDataModel has been renamed and moved to the common folder location
OR
- Elwin no longer uses the FitDataModel

### PR DESCRIPTION
**Pull request by adriazalvarez**
### Description of work
This PR moves the FitDataModel and FitData classes from QENSFitting folder to the common folder within the Inelastic interfaces folder. Additionally, it renames the FitDataModel to DataModel. The reason for this is that the class can be used and it is used (by elwin tab on Data Processor interface) as a general data model to prepare the workspaces for diverse operations, so it is of general application to both qens fitting and data processor interfaces. 
#### Summary of work

Fixes #37063 . 

### To test:
- Do `Elwin`  manual tests on Data processor manual testing: https://developer.mantidproject.org/Testing/Inelastic/DataProcessorTests.html
- Follow QENS Fitting manual tests: https://developer.mantidproject.org/Testing/Inelastic/QENSFittingTests.html
- Every test should work normally

*This does not require release notes becuase it is an internal change*

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by warunawickramasingha — CHANGES_REQUESTED** [review]
The code changes looks fine, but when following the testing instructions at [2. Indirect data](https://developer.mantidproject.org/Testing/Inelastic/DataProcessorTests.html#id8) at `step 9` when clicked `Run` it gave below error

image

```
Error in execution of algorithm ElasticWindowMultiple
The ElasticWindow algorithm produced differently sized workspaces. Please check the input files are compatible.
  at line 190 in 'C:/Codes/mantid_for_Testing/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ElasticWindowMultiple.py'
```
Can you please have a look?

**Comment by adriazalvarez** [comment]
Thanks for taking a look. What you mention is part of an unfortunate coincidence. There are two `irs26176_graphite002_red.nxs` reduced files, one is on `UsageData` and the other on `SampleData-ISIS`. If you have both folder added to your path, the file finder loads the `UsageData` one. But if you try to manually load the `irs26176_graphite002_red.nxs` from the `SampleData-ISIS`, the workspace should contain 50 spectra, and the algorithm should run without problem 
I will open a separate issue to redact better the manual testing instruction so that we don't have this problem in the future.

**Comment by warunawickramasingha** [comment]
When following [Conv Fit tab](https://developer.mantidproject.org/Testing/Inelastic/QENSFittingTests.html#id5) at `Step14` when clicked on `Fit Single Spectrum`  the workbench crashed without any doom window. Please have a look.

**Comment by adriazalvarez** [comment]
I don't experience any crash following the convfit instructions, is it reproducible?

**Comment by warunawickramasingha** [comment]
Yes it is re creatable, I just followed the same steps on a fresh conda environment to be sure and it crashed at the same place when Click `Fit Single Spectrum`

**Review by warunawickramasingha — APPROVED** [review]
Code changes looks good and I followed the given developer testing instructions in a windows 10 machine.

I found some issues in the testing instructions as commented in this ticket which needs to 
be addressed separately. 

The crash I observed will be fixed by this https://github.com/mantidproject/mantid/pull/37511

Happy to approve these changes!

**Pull request merged**
