### PR TITLE
SaveNexus crashes with long file name

### LINKED ISSUE #16146: Mantid crashes during saving of project
Operation with groups of workspaces leads to very long names of the resulting workspaces. It causes mantid crash during saving of project.

### Expected behavior
Get the Mantid project saved.

### Actual behavior
Mantid crash

### Steps to reproduce the behavior
Create a workspace with the very long name, for example:
``` python
wsname = 'bh28000019_van_ar27630120leer_sfleer_scaled_bh28_Van-300K_with-all-corr_sfdata_group_bh28_Van-300K_with-all-corr_vana_coefs_2theta-11.56_bh28_Van-300K_with-all-corr_sfdata_group_vanacorr_bh28000020_van_ar27630121leer_nsfleer_scaled_bh28_Van-300K_with-all-corr_nsfdata_group_bh28_Van-300K_with-all-corr_vana_coefs_2theta-11.56_bh28_Van-300K_with-all-corr_nsfdata_group_vanacorr_ar27630060nicr_ar27630061nicr_ar27630120leer_sfleer_scaled_ar27630121leer_nsfleer_scaled_bh28_Van-300K_with-all-corr_nsf_data_nicrcorr'
CreateSampleWorkspace(OutputWorkspace=wsname)
plotSpectrum(wsname, 1, True)
```
Click Menu File->Save Project As..  to save the project.

### Platforms affected
I've observed this crash on mac os x (mavericks and el capitan) and on linux debian jessie.

### PR DESCRIPTION
**Pull request by samueljackson92**
#16146 reported a crash when file names are extremely long. A little digging shows that this is due to something going wrong in the NXopen call in SaveNexus. As we can't directly edit that code here's a fix that throws an exception in the event that the file name is too long and the file cannot be created.

**To test:**

Here's a script that should reproduce the error. The first file should be saved correctly, but Mantid should crash on saving the second file. Applying the fix should show that the first file still saves correctly but that the second file now gives and error in the output log. You might need to change the size of the filename depending on the limits of your file system (but it's probably 255).

``` python
wsname = "a"*255
CreateSampleWorkspace(OutputWorkspace=wsname)
SaveNexus(wsname, wsname)

wsname = "b"*256
CreateSampleWorkspace(OutputWorkspace=wsname)
SaveNexus(wsname, wsname)
```

Fixes #16146.

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by ElliotAOram** [comment]
Tested as described above using script and it is possible to now see the error message regarding length
image
I also tested that this solves the steps described in the original issue (#16146 ) and it all looks good :shipit:

**Comment by quantumsteve** [comment]
@samueljackson92 Thank you for reporting this issue upstream.

**Comment by samueljackson92** [comment]
@quantumsteve Would like me to have a crack at making a pull request for it if I get a free moment some time?

**Comment by quantumsteve** [comment]
@samueljackson92 While I think submitting a PR is good idea, I'm not a NeXus developer and don't have commit access. You may want to work with your local NeXus representation http://wiki.nexusformat.org/NIAC

**Pull request merged**
