### PR TITLE
Only Change PxD when Fitting Polarised SANS Analyser Transmission

### LINKED ISSUE #37445: DepolarizedAnalyserTransmission should only fit for p*d
The `DepolarizedAnalyserTransmission` algorithm (completed under #36383) fits equation `T(λ) = TE(λ) * exp(-μ)` to find values for `μ` and `TE`. However, the transmission of the empty cell `TE(λ)` is a function of the wavelength, not a single value as is currently returned by the algorithm. Instead we should just be fitting to obtain the value for `p*d` (pressure * path length).

The value `TE(λ)` represents the transmission of the empty cell, and so when we normalise our depolarized workspace by our empty cell workspace in the algorithm this is actually giving us: `T(λ)/TE(λ) = exp(-μ)`. We should therefore only be fitting for `p*d`.

As we will be fitting for just a single parameter, the covariance matrix that the algorithm outputs is not relevant and can be removed.

### PR DESCRIPTION
**Pull request by cailafinn**
#### Summary of work
Adjust the algorithm (after discussions with the scientists) to only fit the PxD parameter (explanations for why we're doing this can be found in the documentation and the issue description).

Fixes #37445 
Refs #37459

#### Further detail of work
- Removed the T_E calculation from the fitting formula.
- Removed the covariance matrix calculation now that we only have one fitting parameter. 
- Adjusted the tests to fit the new calculation. 
- Some refactoring to improve readability. 

Note: this PR does not cover the changes to the error calculation for this algorithm. That will come later. 

### To test:
1. Run the following script:
```python
CreateSampleWorkspace(OutputWorkspace='mt', Function='User Defined', UserDefinedFunction='name=LinearBackground, A0=-0.112, A1=-0.004397', XUnit='wavelength', NumBanks=1, BankPixelWidth=1, XMin=3.5, XMax=16.5, BinWidth=0.1)
CreateSampleWorkspace(OutputWorkspace='dep', Function='User Defined', UserDefinedFunction='name=ExpDecay, Height=0.1239, Lifetime=1.338', XUnit='wavelength', NumBanks=1, BankPixelWidth=1, XMin=3.5, XMax=16.5, BinWidth=0.1)

output = DepolarizedAnalyserTransmission("dep", "mt", OutputFitCurves='out_fit')
```
2. Check the outputted curves and parameter look sensible (is it a good fit?)
3. Run the algorithm from the Algorithm window and check the validation is working
4. Build the docs and check they are formatted correctly. 

*This does not require release notes* because **this functionality is new to this release.**

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by RichardWaiteSTFC — APPROVED** [review]
Test instructions work well and input validation still functions (though perhaps unusual to switch `StartX` and `EndX` if `StartX > EndX` without warning/error, though I think this is unrelated to this change). Changes look good, tests clearer now with helper functions as well. And thanks for updating docs!

**Comment by RichardWaiteSTFC** [comment]
Ah sorry - forgot to build docs - doing that now!

**Comment by RichardWaiteSTFC** [comment]
Yep docs build fine, format looks good and references work!

**Comment by rbauststfc** [comment]
This looks like it's gone into main but was needed for the release?

**Pull request merged**
