### PR TITLE
Store Workspace Dx data for each bin instead of for each bin edge

### LINKED ISSUE #16298: Store Workspace Dx data for each bin instead of for each bin edge
During work on #16096 it became clear that `Dx` data is only ever needed for bin centers, not for bin edges, since it is storing a delta-Q value for each bin in, e.g., SANS. Currently basically all code using `Dx` somehow works around the extra unwanted value.

After discussions with @AntonPiccardoSelg, ORNL as part of ticket #16119 (https://github.com/mantidproject/mantid/pull/16141), and Andrew Jackson (ESS SANS) the consensus is that we never need `Dx` for bin edges.

Most changes are fairly simple (and simplify existing code), but we have to be able to load legacy files. This could be done by simply dropping the last value (if it is present).

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Title says it all, also see the issue description.

The only major and potentially breaking change is loading old Nexus files. I went with the assumption that delta-Q varies slowly and we can thus simply drop the last value (see also the additional unit test in `LoadNexusProcessed`). Please comment on whether or not that makes sense.

**To test:**

Apart from code review,
- Test loading an viewing workspaces with Dx data.
- Make sure that old processed Nexus files (with 1 Dx value too many) can be loaded correctly, and that a warning is printed.

Fixes #16298.

I added this to the SANS release notes, or should it be in a more general section?

@AntonPiccardoSelg You might be a good candidate for reviewing this. 

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AntonPiccardoSelg** [comment]
@SimonHeybrock Could you merge master into this branch? Thank you.

**Comment by SimonHeybrock** [comment]
@AntonPiccardoSelg Done (I did not build/test locally, I hope the merge went fine, we will see).

**Comment by SimonHeybrock** [comment]
@AntonPiccardoSelg Have you had a look at this? If not, I don't mind pushing this to 3.9, it is nothing critical.

**Comment by AntonPiccardoSelg** [comment]
There seems to be a difference in the DX values when I run the same sample script in for Mantid3.7.2 and this branch.

M3.7.2
old_version


This branch:
new_version

**Comment by AntonPiccardoSelg** [comment]
The issue was with the normalization of the plot. Once the bin normalization is turned off, the displayed data is the same. Checking the actual values also reveals that this change has not altered the reduction result.

Code changes look good. Tested with the sample script above. All worked well and is correct. This new implementation of DX makes much more sense for how we store QResolution results in SANS. Happy to :shipit:

**Pull request merged**
