### PR TITLE
Fix beam stop arm masking for certain angles in the ISIS SANS Gui

### LINKED ISSUE #18711: FindDetectors does not find all detectors at all angles for ISIS SANS
This has come out of a SANS investigation for Steve King who complained that he cannot mask his beam stop arm using the SANS Mask/Line command at 150 degrees.

An investigation showed that the culprit is FindDetectorsInShape. The issue can be reproduced with a sample workspace:
```python
import math
import matplotlib.pyplot as plt

ws = CreateSampleWorkspace()
MoveInstrumentComponent(ws, ComponentName="bank1", X=-0.075/2, Y=-0.075/2, Z=5, RelativePosition=False)


# Just above 30 degrees
degrees_good = 30.0000001
x_good = math.cos(math.radians(degrees_good))
y_good = math.sin(math.radians(degrees_good))

shape_good = '<cylinder id="arm"><centre-of-bottom-base x="0.0" y="0.0" z="5.0" /><axis x="' + str(x_good) + '" y="'+ str(y_good) +'" z="0.0" /><radius val="0.004" /><height val="1000000.0" /></cylinder>'

# Just under/equal to 30 degrees
degrees_bad = 30.
x_bad = math.cos(math.radians(degrees_bad))
y_bad = math.sin(math.radians(degrees_bad))
shape_bad = '<cylinder id="arm"><centre-of-bottom-base x="0.0" y="0.0" z="5.0" /><axis x="' + str(x_bad) + '" y="'+ str(y_bad) +'" z="0.0" /><radius val="0.004" /><height val="1000000.0" /></cylinder>'

found_good = FindDetectorsInShape(ws, shape_good)
print(found_good)
found_bad = FindDetectorsInShape(ws, shape_bad)
print(found_bad)
```

In principle it can happen that the detector is found if the detector position does not lie in the shape. This is unlikely here. A quick simulation of the sample workspace's detectors shows, that there are detectors which lie within the cylinder:
```python
import matplotlib.pyplot as plt
import math
import numpy as np
# Fake Detector simulation

# X
x_points = 10
x_start = 0.
x_step = 0.008

# Y
y_points = 10
y_start = 0.
y_step = 0.008

x = []
y = []
for y_point in range(0, y_points):
    y_value = y_start + y_point*y_step
    for x_point in range(0, x_points):
        x_value = x_start + x_point*x_step
        x.append(x_value)
        y.append(y_value)

degrees = 31
cylinder_width = 0.008
cylinder_length = 1
sampling = np.linspace(0, 0.1,20)
centre_line = math.tan(math.radians(degrees))*sampling
left_line = math.tan(math.radians(degrees))*(sampling - cylinder_width/2)
right_line = math.tan(math.radians(degrees))*(sampling + cylinder_width/2)



print(len(x))
plt.plot(x,y,'x')
plt.plot(sampling, centre_line)
plt.plot(sampling, left_line)
plt.plot(sampling, right_line)
plt.show()
```

which results in:
image

Hence there should be detectors which are found

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Fixes #18711 

The underlying issue is a precision issue. The code itself was correct but the definition of a very large cylinder which is being compared with very small values was unfortunate. The large value is intended to simulate a semi-infinite cylinder. The fix defines the length of the cylinder to 10m instead of 1e6m which is still sufficiently large in comparison with all available detector geometries.

**To test:**

Please find the sample data here: smb://olympic/babylon5/Scratch/Anton/LOQ_BUGS
Make sure that the data is in the Mantid path

1. Open the ISIS SANS GUI
2. Set the instrument to LOQ
3. Load the instrument user file: USER_LOQ_164D_M4_Lu_12mm_Changer_MAIN_maskline.txt
4. As a scatter sample set:
5. Press `Load data`
6. Go to the `Masking` tab and press `Display mask`
    * Confirm that the there is a line mask on the detector bank (light blue line)
7. Edit the user file: Change MASK/LINE 8 149.9 to MASK/LINE 8 150.1
8. Reload the user file
9. Close the existing instrument view and repeat step 6 

For release notes see [here](https://github.com/mantidproject/mantid/commit/39f5548a6daf9d502edc16681da2f7bf030d6a68)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AntonPiccardoSelg** [comment]
Differnence between the reference file and the new output where the cylinder length of the beam stop mask is reduced.

image

**Comment by NickDraper** [comment]
Functionally fine :shipit: once RHEL7 and the system tests pass

**Comment by AntonPiccardoSelg** [comment]
In order to investigate the discrepancy between the reference file and the new reduction output, the cylinder mask length was varied and the found detectors were recorded in files (see below). A comparison of the found detectors reveals that the lengths between 10m and 1e5m find the same detector. 1e6m and 1e7m differ, but they also differ amongst themselves. 

The result justify an update of the reference data since it seems to have been incorrect.

The test script was
```python
import csv
def read_file(file_name):
    data = []
    with open(file_name, 'rb') as csvfile:
        reader = csv.reader(csvfile, delimiter=',', quotechar='|')
        for row in reader:
            data.extend(row)
    
    # Remove last element
    data = data[:-1]
    data = [int(element) for element in data]
    return data
         
      
def are_arrays_identical(arr1, arr2):
    return sorted(arr1) == sorted(arr2)
    
            
file_name_10 = "C:/Sandbox/length_10.txt"
file_name_100 = "C:/Sandbox/length_100.txt"
file_name_1000 = "C:/Sandbox/length_1000.txt"
file_name_1e4 = "C:/Sandbox/length_1e4.txt"
file_name_1e5 = "C:/Sandbox/length_1e5.txt"
file_name_1e6 = "C:/Sandbox/length_1e6.txt"
file_name_1e7 = "C:/Sandbox/length_1e7.txt"


data_10 = read_file(file_name_10)
data_100 = read_file(file_name_100)
data_1000 = read_file(file_name_1000)
data_1e4 = read_file(file_name_1e4)
data_1e5 = read_file(file_name_1e5)
data_1e6 = read_file(file_name_1e6)
data_1e7 = read_file(file_name_1e7)

print("Perform comparison")
print (are_arrays_identical(data_10, data_100))
print (are_arrays_identical(data_10, data_1000))
print (are_arrays_identical(data_10, data_1e4))
print (are_arrays_identical(data_10, data_1e5))
print (are_arrays_identical(data_10, data_1e6))
print (are_arrays_identical(data_10, data_1e6))
print (are_arrays_identical(data_10, data_1e7))
print (are_arrays_identical(data_1e6, data_1e7))


print "Number of found detectors"
print("1e1m produced {0} detectors".format(len(data_10)))
print("1e2m produced {0} detectors".format(len(data_100)))
print("1e3m produced {0} detectors".format(len(data_1000)))
print("1e4m produced {0} detectors".format(len(data_1e4)))
print("1e5m produced {0} detectors".format(len(data_1e5)))
print("1e6m produced {0} detectors".format(len(data_1e6)))
print("1e7m produced {0} detectors".format(len(data_1e7)))
```

OUTPUT:
```
Perform comparison
True
True
True
True
False
False
False
False
Number of found detectors
1e1m produced 675 detectors
1e2m produced 675 detectors
1e3m produced 675 detectors
1e4m produced 675 detectors
1e5m produced 675 detectors
1e6m produced 689 detectors
1e7m produced 2423 detectors
```

The files were:

[length_1e4.txt](https://github.com/mantidproject/mantid/files/755057/length_1e4.txt)
[length_1e5.txt](https://github.com/mantidproject/mantid/files/755053/length_1e5.txt)
[length_1e6.txt](https://github.com/mantidproject/mantid/files/755054/length_1e6.txt)
[length_1e7.txt](https://github.com/mantidproject/mantid/files/755058/length_1e7.txt)
[length_10.txt](https://github.com/mantidproject/mantid/files/755056/length_10.txt)
[length_100.txt](https://github.com/mantidproject/mantid/files/755055/length_100.txt)
[length_1000.txt](https://github.com/mantidproject/mantid/files/755059/length_1000.txt)

**Comment by martyngigg** [comment]
I don't quite understand why the number of found detectors changes based on the length of the cylinder. Granted `1000 Km` is ludicrously large compared to the scales we work with it should effectively be infinite in that direction.

The change is obviously necessary to fix the masking problem but it would be nice to investigate this a little further I think.

**Comment by AntonPiccardoSelg** [comment]
@martyngigg I did not trace the exact point of failure, but from changing the length of the mask, it seemed like this is an issue with precision. I will have a futher look at this.

**Pull request merged**
