### PR TITLE
Rename many Abins files, remove unused

### PR DESCRIPTION
**Pull request by ajjackson**
**Description of work.**
This is an extensive body of somewhat superficial refactoring for readability, maintainability and general quality-of-life purposes. It affects the python modules in *Scripts* that support the Abins algorithm.

- Make modules distinguishable from classes, e.g. `InstrumentProducer -> instrumentproducer`

  The existing naming and usage conventions for Abins are quite confusing. Classes are defined in module files sharing a TitleCase name, and imported by `__init__` into the AbinsModules namespace. This makes it difficult to reason about when you are looking at a class and when you are looking at a module. In an especially misleading example, AbinsModules.IOModule is usually not a module but a *class*. The primary benefit of this scheme is that it is easy to determine in which _file_ classes are defined.

  The PEP8 recommendation is that python module names should be lowercase and short, with underscores for clarity if necessary. Here I adopt a pattern that underscores are only used if the module is _not_ named after a class (i.e. *AbinsTestHelpers*-> *test_helpers*); modules that define classes are named with a lower-case rendition of the TitleCase class name (e.g. *InstrumentProducer* -> *instrumentproducer*). This mostly preserves the ease of finding appropriate files, while clearly distinguishing modules from classes.

- Rename `AbinsModules -> abins`, `AbinsXXX -> XXX`

  There is much redundant use of the name "Abins" for classes that are already within the Abins namespace. This has been streamlined in this PR, such that e.g. `AbinsModules.AbinsParameters` becomes `abins.parameters`. As a result, *this refactor removes over 150 instances of the word "abins" from the Mantid codebase.*

- Establish `from abins.constants import CONSTANT` as preferred idiom

  Abins stores many named values in `AbinsModules.AbinsConstants` (now `abins.constants`). These include aliases for significant integers, as well as unit conversion factors. There is a convention that these constants are named in CAPS -- presumably in imitation of the convention for C pre-processor constants/macros. Given that all variables with ALLCAPS names have been imported from AbinsConstants, it is redundant to include the module prefix every time they are used (e.g. rather than `if kpt == AbinsModules.AbinsConstants.GAMMA_POINT`, `if kpt == GAMMA_POINT` is adequately clear). A pattern is adopted in this commit that wherever practical, constants should be imported to the module before use. Through consistent application without too much redundancy, this convention improves the readability of the code.

- Drop "General" from names

  There is a python convention to give base classes generic names without adding any prefixes like "General" to explicitly indicate this. `GeneralAbInitioProgram -> input.abinitioloader`, `GeneralAbInitioParser -> input.textparser` (the functionality of this class would not apply to binary *ab initio* data, and is applicable to text files that don't contain *ab initio* data), `GeneralLoadAbInitioTester -> abins.input.tester`.

- Rename ab initio data loading classes from `LoadXXX` to `XXXLoader`

  Classes should be nouns. It is misleading that `LoadCASTEP()` does not load any data, but instantiates an object capable of loading.

- Replace InstrumentProducer class with a function _abins.instruments.get_instrument()_

  There is no reason for this factory class to hang around as an object; it has one job and that can be a pure function. `__init__` seems the best place for it but this name/location is a bit of a compromise. This change goes beyond renaming and into refactoring; generally such changes should be left for a later PR. Some other comparable issues deferred to such a PR:

  - SCalculatorFactory would also be perfectly manageable as a pure function. But where should it live?
    - SPowderSemiEmpiricalCalculator inherits `object` and includes some transferable methods for IO. These could be on an SCalculator base class. The corresponding module could also host `get_scalculator()`.
  - PowderData and PowderCalculator could be combined to a single class that calculates _and_ stores the tensors used in powder averaging. It's not obvious that there are any other contexts that this kind of data is used, so little is gained by separating the classes.
  - It would be a good idea name such a class _PowderTensors_ which makes it clearer that it deals with an intermediate mathematical construction, rather than general powder properties.

- Remove unused modules

  Several modules in Abins relate to storing and manipulating single-crystal data. However, this functionality has not been implemented and is not exposed to the user. It is anticipated that support will be added for single-crystal simulations in the next year; this would interact with the PACE/Euphonic collaboration with the ISIS Excitations group. At this stage it seems best to remove the unused code while determining the best way forwards; it can always be recovered from the Git history if that turns out to be helpful.

**To test:**
There shouldn't be any user-visible changes (making the fair but not certain assumption that users only interact with the Abins _Algorithm_). Unit tests and system tests should pass; no new tests have been added, and some single-crystal-related tests have been removed.

A release note is included, explaining that the AbinsModules API has been significantly changed and is now accessed as `abins`. It's questonable whether this belongs under "improvements".

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by ajjackson** [comment]
MantidPlot seems to be blowing up while building the docs. I don't see a connection to these changes, but it's not easy to see where the problem lies either.

**Review by NickDraper — DISMISSED** [review]
Lots of changes, but all straight forward and well explained in the PR text.

This looks a lot more pythonic and cleaner now, good work

**Review by NickDraper — APPROVED** [review]
I approved the work, then fixed a merge conflict in the release notes, so this is a re approval

**Comment by martyngigg** [comment]
Unrelated test failure.

**Pull request merged**
