### PR TITLE
Fixes to dimension labelling in MD slicing algorithms

### LINKED ISSUE #12582: Dimension labels are strange after scaled cut_md
This issue was originally [TRAC 11744](http://trac.mantidproject.org/mantid/ticket/11744)

Run the following script look at cut_r, the scaling although correct (bragg peaks in integer positions), has a side effect of altering the dimension axes to:
* ['1.11zeta',0,0]
* [0, '1.11eta', 0]
* [0, 0, '1.11x1']

Investigate if there is anything we can do here

```python
ws = Load(Filename='SXD23767.raw',OutputWorkspace='SXD23767',LoadMonitors='Exclude')

SetUB(ws, UB=[-0.15097235,  0.09164432 , 0.00519473 ,0.0831895,   0.14123681, -0.06719047, -0.0384503, -0.05534039, -0.1633801 ])
s = ws.sample()
SetGoniometer(ws)

scales =  'Q in A^-1' # 'Q in lattice units' 
HKL = ConvertToMD(InputWorkspace=ws, QConversionScales=scales, QDimensions='Q3D', dEAnalysisMode='Elastic', Q3DFrames='HKL', OutputWorkspace='HKL', MinValues='-10,-10,-10', MaxValues='10,10,10')


HKL = mtd['HKL']
p = Projection()
p.setType(0, 'r')
p.setType(1, 'r')
p.setType(2, 'r')
proj = p.createWorkspace('proj')

cut_r = CutMD(HKL, Projection=proj, NoPix=True, PBins=[[0.1], [0.1], [0.1]])

p = Projection()
p.setType(0, 'a')
p.setType(1, 'a')
p.setType(2, 'a')
proj = p.createWorkspace('proj')

cut_a = CutMD(HKL, Projection=proj, NoPix=True, PBins=[[0.1], [0.1], [0.1]])

l = -4.0
svw1 = plotSlice(cut_r, colorscalelog=True)
svw1.setSlicePoint(2, l)
svw2 = plotSlice(cut_a, colorscalelog=True)
svw2.setSlicePoint(2, l)
```

### LINKED ISSUE #15743: CutMD fails to correctly identify the units of the input workspace
### Expected behavior
I expected an MDWorkspace created with ConvertToMD using the `QConversionScales="Q in A^-1"` to be detected by CUtMD as having units of inverse angstroms.

### Actual behavior
CutMD thinks the workspace is in RLU and thus does not perform the expected unit conversions.

### Steps to reproduce the behavior
Turn on debug in the log and look for lines like `In dimension with index 0 and units Angstrom^-1 taken to be of type r`

```python
ws = Load(Filename='SXD23767.raw',OutputWorkspace='SXD23767',LoadMonitors='Exclude')

SetUB(ws, UB=[-0.15097235,  0.09164432 , 0.00519473 ,0.0831895,   0.14123681, -0.06719047, -0.0384503, -0.05534039, -0.1633801 ])
s = ws.sample()
SetGoniometer(ws)

HKL_ang = ConvertToMD(InputWorkspace=ws, QConversionScales='Q in A^-1', QDimensions='Q3D', dEAnalysisMode='Elastic', Q3DFrames='HKL', OutputWorkspace='HKL_ang', MinValues='-10,-10,-10', MaxValues='10,10,10')
HKL_latt = ConvertToMD(InputWorkspace=ws, QConversionScales='Q in lattice units', QDimensions='Q3D', dEAnalysisMode='Elastic', Q3DFrames='HKL', OutputWorkspace='HKL_latt', MinValues='-10,-10,-10', MaxValues='10,10,10')

HKL_ang = mtd['HKL_ang']
HKL_latt = mtd['HKL_latt']
p = Projection()
p.setType(0, 'a')
p.setType(1, 'a')
p.setType(2, 'a')
proj = p.createWorkspace('proj')

cut_r_ang = CutMD(HKL_ang, Projection=proj, NoPix=True, PBins=[[0.1], [0.1], [0.1]])
cut_r_latt = CutMD(HKL_latt, Projection=proj, NoPix=True, PBins=[[0.1], [0.1], [0.1]])
```

### Platforms affected
All

### LINKED ISSUE #15761: MD slicing algorithms do not use target units in output workspace
Improve unit test coverage with use of slice algorithms with unit conversions (in CutMDTest) as part of fixing this issue. MDFrames changes caused this bug and this wasn't caught due to poor test coverage.

### Expected behavior
The MD slicing algorithms (SliceMD and BinMD) should use target units, given in the BasisVector properties, in the output workspace.

### Actual behavior
Looks like the addition of MDFrames broke the expected behaviour. Now the output workspace just has whatever units are in the corresponding dimension of the input workspace. 

### Steps to reproduce the behavior
```python
ws = Load(Filename='SXD23767.raw',OutputWorkspace='SXD23767',LoadMonitors='Exclude')

SetUB(ws, UB=[-0.15097235,  0.09164432 , 0.00519473 ,0.0831895,   0.14123681, -0.06719047, -0.0384503, -0.05534039, -0.1633801 ])
s = ws.sample()
SetGoniometer(ws)

HKL_ang = ConvertToMD(InputWorkspace=ws, QConversionScales='Q in A^-1', QDimensions='Q3D', dEAnalysisMode='Elastic', Q3DFrames='HKL', OutputWorkspace='HKL_ang', MinValues='-10,-10,-10', MaxValues='10,10,10')
HKL_latt = ConvertToMD(InputWorkspace=ws, QConversionScales='Q in lattice units', QDimensions='Q3D', dEAnalysisMode='Elastic', Q3DFrames='HKL', OutputWorkspace='HKL_latt', MinValues='-10,-10,-10', MaxValues='10,10,10')

HKL_ang = mtd['HKL_ang']
HKL_latt = mtd['HKL_latt']
p = Projection()
p.setType(0, 'a')
p.setType(1, 'a')
p.setType(2, 'a')
proj = p.createWorkspace('proj')

cut_r_ang = CutMD(HKL_ang, Projection=proj, NoPix=True, PBins=[[0.1], [0.1], [0.1]])

p = Projection()
p.setType(0, 'r')
p.setType(1, 'r')
p.setType(2, 'r')
proj = p.createWorkspace('proj')

cut_r_latt = CutMD(HKL_ang, Projection=proj, NoPix=True, PBins=[[0.1], [0.1], [0.1]])

print("HKL_ang has units of " + HKL_ang.getDimension(0).getUnits())
print("HKL_latt has units of " + HKL_latt.getDimension(0).getUnits())

print("cut_r Ang and no conversion has units of " + cut_r_ang.getDimension(0).getUnits())
print("cut_r Ang convert to Latt has units of " + cut_r_latt.getDimension(0).getUnits())
```
### Platforms affected
All

### PR DESCRIPTION
**Pull request by matthew-d-jones**
When the input workspace to CutMD was had units if `A^-1` and units of `RLU` were requested in the output, dimension labels were changed by CutMD to something like:
- ['1.11zeta',0,0]
- [0, '1.11eta', 0]
- [0, 0, '1.11xi']

where `2*pi*astar == 2*pi*bstar == 2*pi*cstar == 1.11` in this example.
I changed the behaviour to match Andrei's request that the numerical factor be instead in the units label, such that dimension labels in the previous example are:
- ['zeta',0,0]
- [0, 'eta', 0]
- [0, 0, 'xi']

and the units label for each dimension is `in 1.11 A^-1`. This is consistent with ConvertToMD.

Changes to do with MDFrames (made since the #12582 bug ticket was created) had created two other bugs which I discovered and fixed as part of this PR. Unit conversions through CutMD were actually not resulting in any change to the unit labels in the output workspace, even though the scaling was taking place. I added new unit tests to CutMDTest to cover unit conversions which will hopefully avoid these bugs being reintroduced in the future.

**To test:**
`SXD23767.raw` is in the test data and can be used to test this PR using the following script. Output units of `A^-1` are expected in the case with no conversion from inverse angstroms, and units of `in 1.11 A^-1` in the case with conversion from inverse angstroms to rlu.

``` python
ws = Load(Filename='SXD23767.raw',OutputWorkspace='SXD23767',LoadMonitors='Exclude')

SetUB(ws, UB=[-0.15097235,  0.09164432 , 0.00519473 ,0.0831895,   0.14123681, -0.06719047, -0.0384503, -0.05534039, -0.1633801 ])
s = ws.sample()
SetGoniometer(ws)

HKL_ang = ConvertToMD(InputWorkspace=ws, QConversionScales='Q in A^-1', QDimensions='Q3D', dEAnalysisMode='Elastic', Q3DFrames='HKL', OutputWorkspace='HKL_ang', MinValues='-10,-10,-10', MaxValues='10,10,10')

HKL_ang = mtd['HKL_ang']
p = Projection()
p.setType(0, 'a')
p.setType(1, 'a')
p.setType(2, 'a')
proj = p.createWorkspace('proj')

cut_r_ang = CutMD(HKL_ang, Projection=proj, NoPix=True, PBins=[[0.1], [0.1], [0.1]])

p = Projection()
p.setType(0, 'r')
p.setType(1, 'r')
p.setType(2, 'r')
proj = p.createWorkspace('proj')

cut_r_latt = CutMD(HKL_ang, Projection=proj, NoPix=True, PBins=[[0.1], [0.1], [0.1]])

print("CutMD carried out with input units of A^-1 and no conversion requested, output has units " + cut_r_ang.getDimension(0).getUnits())
print("CutMD carried out with input units of A^-1 and conversion to RLU requested, output has units " + cut_r_latt.getDimension(0).getUnits())
```

Fixes #12582
Fixes #15743
Fixes #15761

Release notes (framework.rst Vates section) were updated.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [ ] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AndreiSavici** [comment]
For the cut_r_latt, I would have expected that the labels look like `[H,0,0]` and not `['zeta',0,0]`

**Comment by FedeMPouzols** [comment]
This has developed a merge conflict with the current master.

**Comment by martyngigg** [comment]
This seems to have developed another merge conflict. @matthew-d-jones Could you take a quick look? @AndreiSavici Could you verify this one once the conflict is resolved? It's been waiting for a while.

**Comment by matthew-d-jones** [comment]
@martyngigg Release notes again :(

**Comment by AndreiSavici** [comment]
:shipit:

**Pull request merged**
