### PR TITLE
Enable SymmetryOperation to have vector-components >= 1

### LINKED ISSUE #14970: Symmetry operations bugs
I am trying to use symmetry operations to transform some coordinates, to use them in symmetrization algorithms
```
symOp = SymmetryOperationFactory.createSymOp("x,y,z+1")
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-103640a8447c> in <module>()
----> 1 symOp = SymmetryOperationFactory.createSymOp("x,y,z+1")

RuntimeError: Error in parsing symbol x,y,z+1:
Failed to parse component string z+1: Could not parse entire string. in  on line 0

symOp = SymmetryOperationFactory.createSymOp("x,y,z+10/20")
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-d00995784753> in <module>()
----> 1 symOp = SymmetryOperationFactory.createSymOp("x,y,z+10/20")

RuntimeError: Error in parsing symbol x,y,z+10/20:
Failed to parse component string z+10/20: Could not parse entire string. in  on line 0

symOp = SymmetryOperationFactory.createSymOp("x,y,z+5/3")
print symOp.transformCoordinates([1.,2.,3.])

[1,2,3.66667]
```

Here are the things that need to be fixed:
1. Be able to add an integer 1 or 2 to one of the components
2. Be able to use more than one digit
3. Need to have 5/3 be 1.6667, not 0.6667

### PR DESCRIPTION
**Pull request by MichaelWedel**
Fixes #14970.

To enable the requested behavior it seemed appropriate to do some minor cleanup in `SymmetryOperation` first, the creation of actual `std::pair<IntMatrix, V3R>` instances was dropped for some intermediate steps during parsing/creating in favor of `MatrixVectorPair<int, V3R>`.

The procedures for wrapping vector components to the appropriate interval are now part of `Group` where they are explicitly carried out on the symmetry operations.

Nevertheless, all of this is more or less internal and I don't think this needs to go into the release notes.

**To test:**

Review the code changes. Test as many cases of symmetry operations as you can think of and try to break everything. Here are some examples that work now but did not work before:

```
op1 = SymmetryOperationFactory.createSymOp("x+5,y+2,z-10/20")
print op1.transformCoordinates([0, 0, 0]) # should print [5,2,-0.5]

op2 = SymmetryOperationFactory.createSymOp("-z+1,-x-2,-y-1/2")
print op2.transformCoordinates([3, 2, 1]) # should print [0, -5, -2.5]

op3 = SymmetryOperationFactory.createSymOp("z+1+4-1/5, x, y")
print op3.transformCoordinates([3, 2, 1]) # should print [5.8, 3, 2]
```

Group now has to make sure that the symmetry operations used for construction are properly confined. Try some variations of this example and see if you can break it:

```
g = Group("x+5,y+2,z-10; x,y,z; -x,-y,-z")

print g.isGroup() # should print True
print g.getOrder() # should print 2
print g.getSymmetryOperationStrings() # should only print x,y,z and -x,-y,-z
```

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AndreiSavici** [comment]
Code looks good. Checked that getIdentifier() handles the fractions  correctly (10/4 is transformed to 5/2, -10/10 is transformed to 1)
My only small question is that if I create a "group" that is not a group, does it make sense to get an order?
`g = Group("x+5,y+2,-z-10/3; x,y,z; -x,-y,-z")
print g.isGroup()
print g.getOrder()`
I've tried to give bad inputs, like floating point numbers, or 1/0, and at least in python it complains gracefully.
Documentation was changed both internally and the user facing one.
I agree that no release notes are necessary

**Comment by AndreiSavici** [comment]
:shipit:

**Comment by martyngigg** [comment]
@MichaelWedel It looks like the branch has developed some merge conflicts

**Comment by MichaelWedel** [comment]
Thanks for notifying me @martyngigg, I merged master and `kdiff3` automagically resolved the conflicts properly.

**Comment by martyngigg** [comment]
:+1:

**Pull request merged**
