### PR TITLE
Apply correct transform to ellipsoid eigenvectors when axes swapped in sliceviewer

### LINKED ISSUE #30433: Sliceviewer not not overlaying ellispoids with correct orientation when axes swapped
### Expected behavior
When swapping the viewing axes X/Y the ellipsoid of an integrated peak would be re-plotted

### Actual behavior
The data is transposed but the ellipsoid shell looks the same (see screenshot). Even worse, if the peak table is removed and then added again to the sliceviewer the ellipsoid is plotted the same. 

image

### Steps to reproduce the behavior
(1) Make an MD workspace and integrate some peaks
```
Load(Filename='SXD23767.raw', OutputWorkspace='SXD23767', LoaderName='LoadRaw', LoaderVersion='3')
ConvertToDiffractionMDWorkspace(InputWorkspace='SXD23767', OutputWorkspace='SXD23767MD', OneEventPerBin='0')
FindSXPeaks(InputWorkspace='SXD23767', PeakFindingStrategy='AllPeaks', AbsoluteBackground=2000, 
    ResolutionStrategy='AbsoluteResolution', XResolution=200, PhiResolution=3, TwoThetaResolution=3, 
    OutputWorkspace='peaks')
IntegratePeaksMD(InputWorkspace='SXD23767MD', PeakRadius=0.35, BackgroundInnerRadius=0.35,
    BackgroundOuterRadius=0.5, Ellipsoid=True, PeaksWorkspace='peaks', OutputWorkspace='peaks_int', 
    UseOnePercentBackgroundCorrection=False)
```
(2) Open sliceviewer and overlay the integrated peak workspace
(3) Zoom to a peak (click peak in the table)
(4) Swap X/Y

### PR DESCRIPTION
**Pull request by RichardWaiteSTFC**
**Description of work.**

Previously the eigenvectors of the integrated ellipsoid were not actually transformed into the basis of the viewing axes which led to the ellipsoid not changing when the axes were swapped.

**To test:**

(1) Run this script to make a fake ellipsoidal peak - `IntegratePEaksMD` will throw an error because the workspace doesn't have the necessary instrument info - but the peak still gets integrated correctly.
```
ws = CreateMDWorkspace(Dimensions='3', Extents='-5,5,-5,5,-5,5',
                       Names='Q_lab_x,Q_lab_y,Q_lab_z', Units='U,U,U',
                       Frames='QLab,QLab,QLab',
                       SplitInto='2', SplitThreshold='50')
expt_info = CreateSampleWorkspace()
ws.addExperimentInfo(expt_info)
FakeMDEventData(ws, EllipsoidParams='1e+05,1,1,1,1,0,0,0,1,0,0,0,1,0.01,0.04,0.02,1', RandomSeed='3873875')
FakeMDEventData(ws, EllipsoidParams='1e+05,2,2,2,0.7071,0.7071,0,-0.7071,0.7071,0,0,0,1,0.01,0.04,0.02,1', RandomSeed='3873875')

# add peak
p = CreatePeaksWorkspace(InstrumentWorkspace='ws', NumberOfPeaks=0, OutputWorkspace='peaks')
SetUB('peaks', 1,1,1,90,90,90)
pk = p.createPeak([1,1,1]) # axes aligned with viewing axes
p.addPeak(pk)
pk = p.createPeak([2,2,2]) # axes 45 deg in XY plane
p.addPeak(pk)
# integrate with bg
IntegratePeaksMD(InputWorkspace='ws', PeakRadius=0.6, BackgroundInnerRadius=0.6, BackgroundOuterRadius=1, 
    PeaksWorkspace='peaks', OutputWorkspace='peaks_int', Ellipsoid=True, UseOnePercentBackgroundCorrection=False)
# integrate without bg
IntegratePeaksMD(InputWorkspace='ws', PeakRadius=0.6, PeaksWorkspace='peaks', OutputWorkspace='peaks_int_nobg', 
    Ellipsoid=True, UseOnePercentBackgroundCorrection=False)
```
(2) Open the MD workspace in sliceviewer and overlay the integrated peak workspace with no background
(3) Zoom in on the two peaks and then swap the X,Y axes - the ellipse should be transposed correctly and the ellipsoid should match the orientation and ellipticity of the peaks (it is easier to see this if you saturate the colorscale by turning off the autoscaling and setting the upper color limit to ~5)
(4) Check the ellipsoid radius of the peak at (1,1,1) is correct. The peak radii (red dashed line) should be roughly 0.3, 0.6, 0.4 along Qx,Qy,Qz respectively.
(5) Repeat steps (2-4) but this time with the peak workspace integrated with a background. Check the inner background shell coincides with the peak integration region for various permutations of the viewing axes.
(6) Check the outer background shell radii for the peak at (1,1,1) are roughly 0.5, 1, 0.7 along Qx,Qy,Qz respectively.

Note there is a separate issue (#30446) where the data are sometimes not  plotted correctly when the axes are transposed.

**To-Do**
- Add a test specifically for integration without a background

Fixes #30433 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by rosswhitfield — CHANGES_REQUESTED** [review]
If you don't include the background it fails,

`IntegratePeaksMD(InputWorkspace='ws', PeakRadius=0.6, PeaksWorkspace='peaks', OutputWorkspace='peaks_int', Ellipsoid=True, UseOnePercentBackgroundCorrection=False)`

with

```
Python-[Error] Traceback (most recent call last):
  File "/home/rwp/src/mantid/qt/python/mantidqt/widgets/sliceviewer/view.py", line 586, in peaks_overlay_clicked
    self.presenter.overlay_peaks_workspaces()
  File "/home/rwp/src/mantid/qt/python/mantidqt/widgets/sliceviewer/presenter.py", line 349, in overlay_peaks_workspaces
    self._create_peaks_presenter_if_necessary().overlay_peaksworkspaces(names_to_overlay)
  File "/home/rwp/src/mantid/qt/python/mantidqt/widgets/sliceviewer/peaksviewer/presenter.py", line 205, in overlay_peaksworkspaces
    self.notify(PeaksViewerPresenter.Event.OverlayPeaks)
  File "/home/rwp/src/mantid/qt/python/mantidqt/widgets/sliceviewer/peaksviewer/presenter.py", line 235, in notify
    presenter.notify(event)
  File "/home/rwp/src/mantid/qt/python/mantidqt/widgets/sliceviewer/peaksviewer/presenter.py", line 87, in notify
    self._overlay_peaks()
  File "/home/rwp/src/mantid/qt/python/mantidqt/widgets/sliceviewer/peaksviewer/presenter.py", line 110, in _overlay_peaks
    self.model.draw_peaks(self._view.sliceinfo, self._view.painter)
  File "/home/rwp/src/mantid/qt/python/mantidqt/widgets/sliceviewer/peaksviewer/model.py", line 77, in draw_peaks
    peak_repr = draw_peak_representation(peak_origin, peak.getPeakShape(), slice_info,
  File "/home/rwp/src/mantid/qt/python/mantidqt/widgets/sliceviewer/peaksviewer/representation/draw.py", line 50, in draw_peak_representation
    return _get_factory(peak_shape).draw(peak_origin, peak_shape, slice_info, painter, fg_color,
  File "/home/rwp/src/mantid/qt/python/mantidqt/widgets/sliceviewer/peaksviewer/representation/ellipsoid.py", line 72, in draw
    a, b, c, shell_thick = _bkgd_ellipsoid_info(shape_info)
  File "/home/rwp/src/mantid/qt/python/mantidqt/widgets/sliceviewer/peaksviewer/representation/ellipsoid.py", line 123, in _bkgd_ellipsoid_info
    width = (max((a, b, c)) - max((inner_a, inner_b, inner_c))) / max((a, b, c))  # fractional width of shell
ZeroDivisionError: float division by zero
```

**Comment by RichardWaiteSTFC** [comment]
Good spot thanks, I actually hadn't finished testing this and meant to label it a draft, sorry!

**Comment by RichardWaiteSTFC** [comment]
@rosswhitfield thanks for pointing out the error when there is no bg - I have fixed this and added a test to stop regression. If you get another chance to review that'd be great (note that I have updated the instructions).

**Review by rosswhitfield — APPROVED** [review]
Thanks! This all looks good now.

**Pull request merged**
