### PR TITLE
Removing LET2014 system test.

### PR DESCRIPTION
**Pull request by abuts**
This addresses  http://trac.mantidproject.org/mantid/ticket/11217

### CODE REVIEW

**Comment by abuts** [comment]
This is simple ticket which removes piece of outdated code, brushes up couple of other small pieces of code, tries to fix some minor pylint warnings and deletes references files. 

No new functionality is added so as soon as unit and system tests passed, ticket can be safely merged. 

Addressing some issues mentioned in the ticket, I've verified that LET2015 system test checks the same workflow as 2014 system test so no new system tests are needed.

**Comment by abuts** [comment]
Jenkins retest this please

**Comment by abuts** [comment]
Jenkins retest this please

**Comment by AndreiSavici** [comment]
Jenkins retest this please

**Comment by abuts** [comment]
There are random failures, the last one due to no space on rhel-6 machine hard drive left. It is important to have rhel-6 build to pass at least once -- it runs system tests which verify code changing due chasing pylint warnings. All other tests have already passed at least once. 

As soon as rhel-6 passes at least once, one can be sure that the changes have not introduced new bugs.

**Comment by AndreiSavici** [comment]
passed in matrix build #1902

**Pull request merged**
