### PR TITLE
Final Revision of V 6.2 release notes

### PR DESCRIPTION
**Pull request by sf1919**
**Description of work.**
Final tidy up of release notes ahead of V 6.2 release. Each section has been done as a separate commit. This PR covers:-

- Diffraction
- Direct Geometry
- Framework 
- Indirect Geometry
- Muon
- SANS
- Workbench

This PR does not cover (because no further changes were necessary):-
- Reflectometry

**To test:**

- remove build/docs/doctrees
- build the documents again and check there are no warnings
- Check the information is still correct
- Are the images visible and clearly illustrate the new feature/improvement?
- Check that the links work
- Grammar/Spelling check

*There is no associated issue.*
---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by sf1919** [comment]
There is one small spelling error in Diffraction still to correct but just in case there are additional changes to be made I'm holding off committing that just yet.

**Review by martyngigg — CHANGES_REQUESTED** [review]
I think this look like a great improvement to the look and reading of the notes. If we could take care of that warning mentioned in #32569 then I'm happy. I think any other changes can go in in the respective pull requests if we fix anything further

**Review by martyngigg — APPROVED** [review]
The warning has gone! Let's :shipit:

**Comment by martyngigg** [comment]
@mantidproject/gatekeepers Can we get this in as it blocks a couple of PRs for the release branch.

**Pull request merged**
