### PR TITLE
Expose DataProcessorAlgorithm::copyProperty to python

### PR DESCRIPTION
**Pull request by peterfpeterson**
This is a quick PR to expose one more function to python.

**To test:**

A small example (I'm starting in another branch) is to add an algorithm:
```python
from __future__ import (absolute_import, division, print_function)

from mantid.api import mtd, AlgorithmFactory, DataProcessorAlgorithm, MatrixWorkspaceProperty, MultipleFileProperty
from mantid.kernel import Direction
from mantid.simpleapi import AlignAndFocusPowder

EXTENSIONS_NXS = ["_event.nxs", ".nxs.h5"]

class AlignAndFocusFromFiles(DataProcessorAlgorithm):
    def category(self):
        return "Diffraction\\Reduction"

    def name(self):
        return "AlignAndFocusFromFiles"

    def summary(self):
        """
        summary of the algorithm
        :return:
        """
        return "The algorithm used for reduction of powder diffraction data"

    def PyInit(self):
        self.declareProperty(MultipleFileProperty(name="Filename",
                                                  extensions=EXTENSIONS_NXS),
                             "Files to combine in reduction")
        self.declareProperty(MatrixWorkspaceProperty('OutputWorkspace', '',
                                                     Direction.Output),
                             doc='Combined output workspace')

        propsToCopy = ["CalFileName", "GroupFilename", "GroupingWorkspace",
                       "CalibrationWorkspace", "OffsetsWorkspace",
                       "MaskWorkspace", "MaskBinTable",
                       "Params", "ResampleX", "Dspacing", "DMin", "DMax",
                       "TMin", "TMax", "PreserveEvents",
                       "RemovePromptPulseWidth", "CompressTolerance",
                       "UnwrapRef", "LowResRef",
                       "CropWavelengthMin", "CropWavelengthMax",
                       "PrimaryFlightPath", "SpectrumIDs", "L2", "Polar", "Azimuthal",
                       "LowResSpectrumOffset", "ReductionProperties"]
        self.copyProperties("AlignAndFocusPowder", propsToCopy)

    def PyExec(self):
        pass

# Register algorithm with Mantid.
AlgorithmFactory.subscribe(AlignAndFocusFromFiles)

```

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by peterfpeterson** [comment]
The competent gatekeeper can resolve conflicts when merging in.

**Comment by gvardany** [comment]
Works fine, but I was wondering what should happen in these cases?
```
self.copyProperties("AlignAndFocusPowder")
self.copyProperties("AlignAndFocusPowder", None)
```
In the first case the algorithms subscribes to mantid fine, but you get an error when trying to call the dialog, for example. 
In the second case nothing happens, but maybe an error could be relevant?

**Comment by peterfpeterson** [comment]
You must have the results log turned off. There is a clear warning message now about not specifying an algorithm to copy from, or failing to list properties to copy. For some reason the algorithm is still registered, but that is an issue in the registration logic rather than what is being added here.

**Comment by gvardany** [comment]
Ok, looks good :shipit:

**Pull request merged**
