### PR TITLE
MatchPeaks

### LINKED ISSUE #17367: New PythonAlgorithm MatchPeaks
In general, Mantid workspaces can be transformed by algorithms like for example AppendSpectra or ConjoinSpectra. Evaluating a set of workspaces may demand for a new algorithm MatchPeakPositions, which is responsible of moving/replacing bins: to center the data according to peak postions or match peak positions of two workspaces. In particular, the IndirectILLReduction WorkflowAlgorithm for IN16B backscattering data requires this matching of peaks. MatchPeakPositions will operate on each spectrum independently. The matching of peak position is based on the FindEPP algorithm.

### PR DESCRIPTION
**Pull request by vreimund**
MatchPeaks.py is a new Python algorithm for the category Transforms.
It is required by the IndirectILLReduction workflow algorithm for the ILL backscattering IN16b.
More history of the algorithm can be found here: https://github.com/mantidproject/mantid/issues/16753.
This algorithm should work for MatrixWorkspaces that contain maximum one elastic peak.
Hidden from the user is a tolerance value that helps evaluating optimization results from FindEPP (https://github.com/mantidproject/mantid/blob/9cd427dfa5a75e38597e10df19435c65a875a56e/Framework/PythonInterface/plugins/algorithms/FindEPP.py).
This way, the algorithm is easier to use (black box behavior) and follows the example FindEPP, where only one input and one output are required and some internal variables are as well hidden from the user. 
Implemented but uncommented is an optional second input ITableWorkspace that can be a user-defined table or a table created by FindEPP for example.
Pylint complains about too-many-branches, however, I think the code is still easy to read.

**To test:**

Run Algorithm IndirectILLReduction using the automatic GUI (ILL, instrument IN16B) in order to get left and right workspaces, then run MatchPeaks to center peaks of the left or right workspace, then visualize the workspace and verify that peaks are centered now.

UnitTest data can be used (ILLIN16B_034745, ILLIN16B_127500)

Fixes #17367

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by abuts** [comment]
May be as English is not my first language but I have a problem interpreting algorithm description
Would it be better to say:

Shift the data of the input workspace to align each spectrum peaks with each other or, if requested according to the positions, specified by second input workspace.

The description of the second property is certainly wrong:
Input workspace can not be used to extract peaks -- it does not change. 
Does it rather mean: "The workspace-source of the peak positions to align with" ?

again:
**BinRangeTable** -- is output property. Does it mean, contains the ranges of masked bins?
Its behaviour is strange. 
When I run the sample code with 
`
  output_ws,brt = MatchPeaks(InputWorkspace=ws,BinRangeTable='testTable',MaskBins=True)
`
it contain one row with 0,64 values. When I try to run it on:
`
ws = CreateSampleWorkspace(Function='User Defined',
                              WorkspaceType='Histogram',
                              UserDefinedFunction="name=Gaussian, PeakCentre=3., Height=10, Sigma=0.3",
                              NumBanks=2, BankPixelWidth=10,
                              XUnit='DeltaE', XMin=0, XMax=7, BinWidth=0.099)

output_ws,brt = MatchPeaks(InputWorkspace=ws,BinRangeTable='testTable',MaskBins=True)
`
it still 1 row with the same values. Is this correct?

**Comment by reimundILL** [comment]
I tried to improve some explanations in particular for the BinRangeTable. Agree on the algorithm description, and the description of InputWorkspace2.
There was an error for the values of the BinRangeTable (I did not propagate a minus sign, this means I mixed left and right values of the table and also for the masking)
I added release notes.

**Comment by abuts** [comment]
I think we could :shipit: as soon as tests passed though I would be really interested to see how this all would work on real data where strong noise is present. I hope that data to reduce using this algorithm do not contain such noise.

**Comment by reimundILL** [comment]
Real data example (unittest data): shift left worspace according to peak centre of right workspace
```Python
IndirectILLReduction(Run='/home/cs/reimund/mantid/build/ExternalData/Testing/Data/UnitTest/ILLIN16B_034745.nxs', MirrorMode=True, RawWorkspace='raw', ReducedWorkspace='red', LeftWorkspace='left', RightWorkspace='right')
MatchPeaks(InputWorkspace='left', InputWorkspace2='right', MaskBins=True, OutputWorkspace='output')
```
Example Spectra 5 and 23 for left and right workspace:
[print2.pdf](https://github.com/mantidproject/mantid/files/497455/print2.pdf)
[print1.pdf](https://github.com/mantidproject/mantid/files/497456/print1.pdf)
[print3.pdf](https://github.com/mantidproject/mantid/files/497457/print3.pdf)
[print4.pdf](https://github.com/mantidproject/mantid/files/497458/print4.pdf)

For spectrum 5, the left workspace gets shifted and matches peak positions of right workspace.
For spectrum 23, no peak is present and nothing to be done to the data

**Review by abuts — APPROVED** [review]
as discussed within the comment to the code, now we cah :shipit:

**Pull request merged**
