### PR TITLE
Change the range in the color map editor => update selection widget min/max line edits

### LINKED ISSUE #12544: Colour maps in VSI
We have major issues with synchronisation of colour bars in the VSI. Nick has seen more of these issues first-hand:

From Nick
```
Colour map limits in the colour map editor did not interact well with the scaling in the VSI window.  Often you would have the colour map graph 90% to 95% compressed to the max value.
```

The issue seems to be triggered by switching views and or using the colour editors in-built with the filters.

 - - - - 
Keywords: vates

### PR DESCRIPTION
**Pull request by FedeMPouzols**
This fixes #12544 The VSI selection widget should react properly when you change the range of the color scale in the Paraview "color map editor". This is done here with a Vtk callback on the RGBPoints property of the Vtk proxy for the color lookup table of the color editor.

To test:
- Open the Paraview color map editor and use it to change the color scale range. Your changes should reflect in the VSI color selection widget (the minimum and maximum line edits).
- Play with colors and see if they behave consistently. I'm not totally sure if this is what we wanted to do, so let's chat about it (I'm putting this as "In progress" for now).

Release notes: See here http://www.mantidproject.org/ReleaseNotes_3_5_UI_Changes, in "3D Visualisation (VSI)".

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
I'm going to see if we can also keep the checkbox "auto color scaling" in sync with the Paraview map editor. That should be coming in a next commit a bit later today...

**Comment by FedeMPouzols** [comment]
I think the "auto color scaling" check box behaves well now (in sync with the Paraview color map editor).

But maybe we should still have a chat. Now that the VSI simple ColorSelectionWidget is updated by the ParaQ color map values, it turns out that we get different color ranges when switching between views. My first guess would be that we still want to enforce the default VSI auto-scale initially on all the views? Or is it better to use the scale that the ParaQ color editor produces by default?

I also noticed another oddity. This is in "use log" tick boxes. They are connected "left to right" but not "right to left". This could be easy to fix, if only I could find what vtk property is involved in that log scale check box.

**Comment by FedeMPouzols** [comment]
Aha, I think I can have the log-scale issue fixed a bit later today still in time for tonight's build.

**Comment by mantid-roman** [comment]
Can I start testing?

**Comment by FedeMPouzols** [comment]
I think this should be ready now. The last commits should have:
- fixed the issue with the log-scale check boxes
- mitigated the issue with the auto-scaled colors when switching views

About the second point we still have a glitch when you switch to the multislice view. You'll often lose the auto-scale state, so the user needs to click again on 'auto scale' if it wants the default vsi auto range instead of the Paraview range. If I don't find a very last minute solution for this, it will have to be a new ticket to sort out later.

**Comment by FedeMPouzols** [comment]
The windows failure is an unrelated issue of one of the CI machines.

**Comment by NickDraper** [comment]
Windows build on my PC is fine

**Comment by NickDraper** [comment]
Interaction seems a great improvement to me.  This alters some of the same classes as the change Anton has just put in.  Do we want to check they work nicely together?

**Comment by FedeMPouzols** [comment]
I'm going to merge the latest master and see if everything is still fine.

**Comment by NickDraper** [comment]
On windows it looks good, but this needs a check on Mac as we saw some ealier behaviour that was suspicious (max and min value not being updated)

**Comment by eXeC64** [comment]
There's a merge conflict currently.

**Pull request merged**
