### PR TITLE
Adding automatic creation of all group/pairs for a workspace in muon analysis 

### LINKED ISSUE #21397: Create all in muon analysis
The settings tab should include an "add all" option. If this is selected all groups/pairs will automatically be loaded.

### PR DESCRIPTION
**Pull request by AnthonyLim23**
The muon group wanted checkboxes, which when selected would automatically create the workspaces for all of the groups/pairs. In the current release (3.11) the workspaces are only generated when they are needed (plotted or used in multiple fitting). 

**To test:**
1. Turn on the data archieve
2. Open Muon analysis and select MUSR as the instrument.
3. Enter 62260 as the run number (some data should then load)
4. Go to the grouping tab and create a group and two pairs (add them to the tables)
5. Go to the settings tab
6. Expand the grouped workspace MUSR00062260 and it will contain 2 workspaces (binned and raw data)
7. Tick the 'Load all groups" option. The grouped workspace will now have 10 workspaces (5 binned and 5 raw).
8. Go to the grouping tab and add another group. It should be added to the grouped workspace.
9. Go to the settings tab and untick Load all groups
10. Tick Laod all pairs. The 2 pairs should be added to the grouped workspace.
11. In the grouping tab create another pair and it should be added to the grouped workspace.
12. In the settings tab tick Load all groups
13. In the home tab enter MUSR00067063 into the load run bar.
14. A grouped workspace called MUSR00067063 will be created and will contain all of the groups and pairs.

Fixes #21397. 

**Release Notes** 

Added to release notes and muon Analysis documentation has been updated. 
---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
Got a crash when testing this on step 13
image


image

Are the pairs supposed to have cleared when the run changed?
image

image


I've managed to reproduce this twice, in both cases I copied and pasted the later run no from the PR.  When it pasted over it carried a trailing space, in the first occasion I deleted it before hitting enter, in the second I didn't, both crashed.

The crash appears to leave the interface in a state where it will not load files any more.

**2nd crash**
After the 1st crash I hit continue, and then deteled all of the workspace from the workspaces toolbox and got this:
image

**Review by NickDraper — CHANGES_REQUESTED** [review]
see crashes

**Comment by AnthonyLim23** [comment]
I am not sure about the second crash. However, I have a fix for the first one. I just had to add a check to make sure that the groups/pairs to load were valid in the first place. This also fixed a bug where ticking one of the load all boxes would crash mantid. Thank you for spotting this

**Comment by AnthonyLim23** [comment]
@NickDraper  did this fix the issues for you?

**Comment by AnthonyLim23** [comment]
@NickDraper its this PR I spoke to you about yesterday

**Review by NickDraper — APPROVED** [review]

**Comment by NickDraper** [comment]
No crashes now

**Pull request merged**
