### PR TITLE
Better Colorbar range when opening Slice Viewer from the 'IndirectPlotOptions' widget.

### LINKED ISSUE #36459: Colorbar range is not always suitable when `IndirectPlotOptions` widget opens SliceViewer
**Description**
When opening the Slice Viewer from the Indirect/Inelastic interfaces, the colorbar range is not always suitable. Sometimes the range is too large, so very little detail can be seen on the opened slice without needing to adjust the maximum colorbar range. In particular, this happens on the ISIS Energy Transfer tab.

**To replicate**
1. Open Data Reduction
2. Select TOSCA
3. Load 26176
4. Click Run
5. Click the Down arrow in the plot options and select `Open Slice Viewer`
6. Very little detail can be seen on the opened slice. The colorbar maximum is needing adjusting before you can see any details.

**Potential solution**
I would have thought the `autoscale` option for the colorbar axis would cause the scale to be chosen correctly. The first thing to check is if this autoscale option is turned on by default, and if it is then why is the colorbar not being autoscaled upon opening?

**Acceptance Criteria**

- When the Slice Viewer is opened from an Indirect/Inelastic interface, the colorbar always has an appropriate range.

### PR DESCRIPTION
**Pull request by adriazalvarez**
### Description of work
As described in #36459, when opening the Slice Viewer from the Indirect/Inelastic interfaces, the colorbar range is not always suitable. 
#### Summary of work

The reason why colorbar range was not the same as when slice viewer is called from the ADS is that when opening slice viewer from the widget, there was a missing keyword argument to the sliceviewer (the singleton `UserConfig` (CONF)) which takes care of the local user configuration available when using Mantid. In the context of the slice viewer, it is setting the scales of the slice viewer plots to 'SymmetricLog10' instead of the default 'Linear' which is called when Slice Viewer is opened without keyword arguments. 

Fixes #36459 . 

### To test:

1. Open Data Reduction
2. Select TOSCA
3. Load 26176
4. Click Run
5. Click the Down arrow in the plot options and select `Open Slice Viewer`
6. Without closing Slice Viewer Window, click on the ADS and open the resulting file from running the algorithm `26176_graphite002_red`,  and show the slice viewer from the ADS. Compare that both instances of slice viewer show same colorbar range and scale.

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by robertapplin** [comment]
The SliceViewer config is now loaded into the SliceViewer when opened from the Inelastic interfaces, so nice job figuring this out!

It looks like the autoscale for Linear is not working in general, i.e. its not working when opening SliceViewer from the ADS or from the inelastic interface. Maybe we need to open a separate issue which is more specific to SliceViewer and unrelated to Inelastic?

**Comment by adriazalvarez** [comment]
Thanks for checking it out.
I'm not sure what you mean, how the Linear autoscale does not work?

**Comment by robertapplin** [comment]
> Thanks for checking it out. I'm not sure what you mean, how the Linear autoscale does not work?

When the `autoscale` option is ticked and you change the colorbar scale from `SymmetricLog10` to `Linear`, do you see that the limits on the colorbar change? Or do the limits stay the same? For me the limits stay the same, but I would have thought the limits should change when switching to `Linear`

**Comment by adriazalvarez** [comment]
I've been investigating. I think autoscale is working because when I zoom in it is automatically updated. The line edits for the limits of the colorbar I think are based on the data range, right? I also see the lower limit is not changing when moving from linear to symlog, although it changes from linear to log. In any case, seems to be a problem of the colorbar widget. We can open separate issue if you think it merits it!

**Comment by robertapplin** [comment]
> I've been investigating. I think autoscale is working because when I zoom in it is automatically updated. The line edits for the limits of the colorbar I think are based on the data range, right? I also see the lower limit is not changing when moving from linear to symlog, although it changes from linear to log. In any case, seems to be a problem of the colorbar widget. We can open separate issue if you think it merits it!

Ah yes, you are right, its working as expected - ignore me!

**Review by robertapplin — APPROVED** [review]
The SliceViewer config is now remembered when opened from the Inelastic interfaces - good job!

**Pull request merged**
