### PR TITLE
Fix Muon Analysis TF asymmetry fitting crash

### LINKED ISSUE #29388: Muon Analysis crash
It is possible to crash Muon Analysis.

1. Load data
2. Go to the fitting tab
3. Add a function
4. Share a parameter
5. Turn on TF Asymmetry mode
6. Change the run - crash

I think the solution here is to just make sure that TF asymmetry mode is forced to be unchecked when we change the run

### PR DESCRIPTION
**Pull request by StephenSmith25**
**Description of work.**
This PR fixes a crash which occurs when the run is incremented while a simultaneous TF asymmetry fit is defined. This seems to occur due to the ties being invalidated, which is likely due to be setting in both ConvertFitFunctionForMuonTFAssymetry and in the function browser. To avoid this I've added an optional boolean parameter to the algorithm, which states whether ties are to be copied.

**To test:**
- Open Muon Analysis
- Load data
- Go to the fitting tab
- Add a function
- Share a parameter
- Turn on TF Asymmetry mode
- Change the run - should no longer crash

Fixes #29388 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
it all works as expected, except when changing runs the normalization does not update on the fitting tab. However, it does update on the sequential fitting tab.

**Comment by StephenSmith25** [comment]
I've created an issue to ensure both tabs stab in sync in TF asymmetry fits #29453

**Comment by AnthonyLim23** [comment]
Ok, we will keep that as a separate issue as it is a pre-existing problem (with no globals). However, could we have a big warning in the user docs and release notes that the normalisation won't necessarily update correctly?

**Review by AnthonyLim23 — APPROVED** [review]
Works as expected, the code looks good and the documentation is clear about the consequences.

**Review by DavidFair — CHANGES_REQUESTED** [review]
I've just double checked the test file, we don't have a test actually checking that the tie is copied if it's set to true (the only call to `getTie` is in the negative case)

Could we add a test to make sure that copying ties works correctly when the flag is true and I'm happy to ship it as I'm happy with everything else.

**Comment by AnthonyLim23** [comment]
@DavidFair I think the pre-existing test cover the case for opyTies = True. Given that is the default behaviour and those tests have not been changed https://github.com/mantidproject/mantid/blob/920c43fc11b4008a8e5ca41dffaa4717b1cc926c/Framework/Muon/test/ConvertFitFunctionForMuonTFAsymmetryTest.h#L152 

It is also in the doc test

**Comment by DavidFair** [comment]
> @DavidFair I think the pre-existing test cover the case for opyTies = True. Given that is the default behaviour and those tests have not been changed
> 
> https://github.com/mantidproject/mantid/blob/920c43fc11b4008a8e5ca41dffaa4717b1cc926c/Framework/Muon/test/ConvertFitFunctionForMuonTFAsymmetryTest.h#L152

But as far as I can tell were not actually checking if the tie is copied in that test, only implicitly relying on the fact if it didn't copy the results would be different.

The metric I use is - if I broke copying of ties tomorrow indirectly, then saw these tests fail would it be obvious what's failed. If I saw a test called "copyTies" which failed I would know straight away. For the same reasons I wouldn't think to look at doc tests to diagnose a unit test problem equally.

However, fitting is one of my weaker areas in the project - so if it would be obvious to you that copying ties was broken looking at the existing test suite I'm happy to dismiss my concern?

**Comment by AnthonyLim23** [comment]
https://github.com/mantidproject/mantid/blob/920c43fc11b4008a8e5ca41dffaa4717b1cc926c/Framework/Muon/test/ConvertFitFunctionForMuonTFAsymmetryTest.h#L169 

sets a tie, does the conversion and then a fit. If the tie fails the asserts will fail, it also checks that the value has changed for the untied parameters

**Comment by StephenSmith25** [comment]
> 
> 
> https://github.com/mantidproject/mantid/blob/920c43fc11b4008a8e5ca41dffaa4717b1cc926c/Framework/Muon/test/ConvertFitFunctionForMuonTFAsymmetryTest.h#L169
> 
> sets a tie, does the conversion and then a fit. If the tie fails the asserts will fail, it also checks that the value has changed for the untied parameters

Further to what Anthony said, https://github.com/mantidproject/mantid/blob/920c43fc11b4008a8e5ca41dffaa4717b1cc926c/Framework/Muon/test/ConvertFitFunctionForMuonTFAsymmetryTest.h#L184 is ensuring that the tied parameters are equal. So I think thats covered, I didn't modify these tests, just relied on the default behavior (which will be true), so everything from before should work.

**Comment by DavidFair** [comment]
Ahh okay I see the line that asserts `f0.A1` and `f1.A1` are the same rather than checking for the existence of the tie. Sorry about any confusion caused, this ones on me.

**Review by DavidFair — APPROVED** [review]

**Pull request merged**
