### PR TITLE
Fix detector grouping and entry number

### PR DESCRIPTION
**Pull request by raquelalvarezbanos**
Fixes issue [#8837](http://trac.mantidproject.org/mantid/ticket/8837)

For tester: LoadMuonNexus1 should be able to correctly load detector grouping into a table workspace when some spectra are selected via SpectrumMin/Max or SpectrumList. All options (EntryNumber, Autogroup, etc) should work fine. To test:
1. Open a muon dataset, ideally a multi period dataset as MUSR00015189.nxs.
2. Select some spectra and set a detector grouping table.
3. Check the output: the table should have at most two rows containing the detector ids (spectrum numbers) you specified when running the algorithm. The number of rows will depend on the selected spectra. For instance, if you selected spectra indices <32, only one row will be created. If some of them are >=32, two rows will appear.
4. Repeat steps 1 and 2, but now check "AutoGroup". This option groups spectra together according to the grouping information stored in the dataset. With this option checked you should only see one or two histograms (again, depending on the specified spectra) in the output workspace. Go to "Show Detectors" and check that everything is as expected.
5. For multi period datasets, you can play with the "EntryNumber" option to load only one period.

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
Jenkins, retest this please

**Comment by KarlPalmen** [comment]
All seems good, except I noticed the phrases 'every spectra' and 'per spectra', which I think should be 'every spectrum' and 'per spectrum'. Some of these are visible to the user in messages.

**Comment by raquelalvarezbanos** [comment]
Thanks Karl, comments/messages have been corrected.

**Comment by raquelalvarezbanos** [comment]
Jenkins, retest this please

**Comment by raquelalvarezbanos** [comment]
Jenkins, retest this please

**Comment by KarlPalmen** [comment]
I'll wait till merge build has completed.

**Comment by raquelalvarezbanos** [comment]
Jenkins, retest this please

**Comment by raquelalvarezbanos** [comment]
Jenkins, retest this please

**Comment by raquelalvarezbanos** [comment]
Jenkins, retest this please

**Comment by raquelalvarezbanos** [comment]
Jenkins, retest this please

**Pull request merged**
