### PR TITLE
Indirect - Data Analysis - TransformToIqt - Replace NaN values with zeroes

### LINKED ISSUE #20396: Indirect - Data Analysis - TransformIqt - NaN values are not being replaced with 0
In TransformIqt, the NaN values in the last bin of the output workspace are not currently being replaced with zero values.

### PR DESCRIPTION
**Pull request by brandonhewer**
NaN values produced during the TransformIqt algorithm (found in the last bin of the output workspace) are currently not being replaced with zero values.

This PR applys the ReplaceSpecialValues algorithm to replace the NaN values with zero values.

**To test:**
1. Navigate to Indirect > Data Analysis > I(Q, t)
2. In the sample field provide a reduced (\*\_red) file (provided below)
3. In the resolution field provide a resolution (\*\_res) file (provided below)
4. Run the algorithm
5. Open the output workspace and check there are no NaN values contained within it

Reduced and Resolution file:
[IQT.zip](https://github.com/mantidproject/mantid/files/1281862/IQT.zip)

Fixes #20396. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by gvardany — COMMENTED** [review]
There are no more `NaN`s. Maybe you should consider also to zero `Inf` values?

**Comment by brandonhewer** [comment]
@gvardany I've added the line for setting Inf values to zero

**Review by gvardany — APPROVED** [review]
must be safer now :shipit:

**Comment by SpencerHowells** [comment]
I normalise I(q,t) to be 1 at time zero so its greatest value should be 1. Perhaps we should change values greater than 1 with zero.

**Comment by brandonhewer** [comment]
@SpencerHowells Added check for values greater than 1.0 > will now be set to 0.0

**Comment by martyngigg** [comment]
@brandonhewer The most recent change has affected the system test reference results. @SpencerHowells I assume we are okay just to update those results?

**Comment by SpencerHowells** [comment]
@brandonhewer @martyngigg Yes we can update the reference results

**Comment by peterfpeterson** [comment]
The system tests are *actually* broken.

**Comment by martyngigg** [comment]
@SpencerHowells I just wanted to check the output here. The picture below shows the output of `IqtFit` for spectrum 963 of OSIRIS after the replacement of NaN and > 1.0 (top) and before (bottom). Is such a drastic change in the shape what was really intended?

screenshot from 2017-09-14 11-53-08

**Comment by SpencerHowells** [comment]
@martyngigg @brandonhewer The science says that I(Q,t) cannot be greater than 1 so I want it truncated so that it doesn't dominate the plot & introduce confusion. Secondly the data for time > about 0.2 is rubbish due to the data. It divides the sample by the resolution and the latter has tended to zero. So it's ok.

**Comment by martyngigg** [comment]
Thanks @SpencerHowells - I just wanted to double check.

**Comment by martyngigg** [comment]
@brandonhewer The System tests are still failing: http://builds.mantidproject.org/job/pull_requests-rhel7/15857/

**Pull request merged**
