### PR TITLE
Muon check field type

### LINKED ISSUE #24889: Add checkd for transverse and longitudanal field in Muon GUI
Muon scattering instruments may be run in transverse field or longitudinal field mode. This in general requires different grouping tables. The GUI should check whether a mixture of longitudinal and Transverse runs have been loaded and warn the user if this is the case.

### PR DESCRIPTION
**Pull request by Matthew-Andrew**
**Description of work.**

This adds checks to the new muon GUI that the loaded run set is all for the same main field direction and warns the user if not.

It also adds the grouping files for CHRONUS and updates the CHRONUS IDF to be correct.

**Report to:** Anthony 

**To test:**

For MUSR 62250 is a longitudinal run and 62260 is a transverse run. Try loading these in various combinations and check you are warned appropriately.

Try loading some CHRONUS data and check that a default grouping table is created. 5000 and 8000 are runs numbers with different fields.

Fixes #24889  

*This does not require release notes* because the new GUI is not yet user facing

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
conflicts
when I changed the instrument from MUSR to CHRONUS (having loaded MUSR 66250 - 62) I got the error
`update called :  CHRONUS
Traceback (most recent call last):
  File "C:\Users\BTR75544\work\dev\mantid\scripts\Muon\GUI\Common\home_instrument_widget\home_instrument_widget_presenter.py", line 139, in handle_instrument_changed
    self._model._data.instrument = instrument
  File "C:\Users\BTR75544\work\dev\mantid\scripts\Muon\GUI\Common\muon_data_context.py", line 139, in instrument
    self.instrumentNotifier.notify_subscribers(self._instrument)
  File "C:\Users\BTR75544\work\dev\mantid\scripts\Muon\GUI\Common\muon_data_context.py", line 464, in notify_subscribers
    Observable.notify_subscribers(self, *args)
  File "C:\Users\BTR75544\work\dev\mantid\scripts\Muon\GUI\Common\observer_pattern.py", line 53, in notify_subscribers
    observer.update(self, arg, **kwargs)
  File "C:\Users\BTR75544\work\dev\mantid\scripts\Muon\GUI\MuonAnalysis\load_widget\load_widget_presenter.py", line 147, in update
    self.outer.update_new_instrument(arg)
  File "C:\Users\BTR75544\work\dev\mantid\scripts\Muon\GUI\MuonAnalysis\load_widget\load_widget_presenter.py", line 124, in update_new_instrument
    self.handle_run_widget_data_changed()
  File "C:\Users\BTR75544\work\dev\mantid\scripts\Muon\GUI\MuonAnalysis\load_widget\load_widget_presenter.py", line 85, in handle_run_widget_data_changed
    self._model._context.update_current_data()
  File "C:\Users\BTR75544\work\dev\mantid\scripts\Muon\GUI\Common\muon_data_context.py", line 225, in update_current_data
    self._current_data = self._loaded_data.get_data(run=self.current_runs[0], instrument=self.instrument)
IndexError: list index out of range1`

**Comment by AnthonyLim23** [comment]
changes also work in Muon Analysis 1

**Comment by NickDraper** [comment]
@Mantid-Matthew
Conflicts - A Haiku

```
To resolve conflicts
developer must merge
in the master branch
```

**Comment by AnthonyLim23** [comment]
if I load MUSR data, then change to CHRONUS data that happens to be the other field type, I will get a pop up saying the field direction has changed and an empty grouping table.

**Review by AnthonyLim23 — APPROVED** [review]
:shipit:

**Pull request merged**
