### PR TITLE
Error in log-log waterfall plots.

### LINKED ISSUE #16196: Log Log scaling of waterfall plots is incorrect
### Expected behavior

Waterfall plots should look good (and recognizable as waterfall plots) after scaling of the axes between log and linear scales.

### Actual behavior

Currently the log scaling is applied to the offsets for the waterfall plots causing the data to become incomparable.

### Steps to reproduce the behavior

1. load some data
1. Plot a waterfall plot of a few (4?) spectra
1. right click the plot Axis-> various log or linear scale options.

Linear- Linear
image

Log-Log
image

### Platforms affected
All

### PR DESCRIPTION
**Pull request by mantid-roman**
Changed the waterfall plot curves such that their data isn't modified but instead the curves are shifted on screen only.

**To test:**

See the description of #16196 

Fixes #16196 

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
This is working well for me locally, but I think that some tests in `MantidQtAPITest` need updating.
I'm not sure why not the same tests fail on all the platforms (for example 3 fail on Windows but only one on osx).

**Comment by FedeMPouzols** [comment]
The tests are happy now on all platforms, but there are a few doxygen warnings about some function arguments.

**Comment by FedeMPouzols** [comment]
- Code changes look good and include nice refactoring/modernization/sanitization.
- Works well for me. I changed the scale types (linear/log/power) and the offsets on the x and y axes without observing any misbehavior.

The auto-scaling (auto-range) of the axes doesn't play very well when you modify the x/y offset amounts and/or change the type of scale, but that's unrelated to this PR/issue.

I'm not sure if this was a recent bug or not. Do we want to include this fix in the release notes?

The builds had already passed except for the doxygen warnings, so I'm assuming they'll pass again...
:shipit:

**Comment by mantid-roman** [comment]
The bug isn't new but my understanding is that the waterfall plots on a log-log scale is used very rarely and hopefully it wasn't noticed by many users.

**Comment by peterfpeterson** [comment]
Is that the reason why it isn't in the release notes? Please either add release notes or explicitly state that this doesn't need to be mentioned.

**Comment by mantid-roman** [comment]
It's my opinion that this fix shouldn't be mentioned in the release notes.

**Pull request merged**
