### PR TITLE
Plotting matrix workspaces not working in certain conditions.

### LINKED ISSUE #14568: Plotting matrix workspaces not working in certain conditions
Step scan analysis creates workspaces that contain a log value as the X axis. I found out that it fails in certain cases, and it is related to plotting. If all X values in a workspace are smaller than the first value, the plotting will fail. If there is at least one X value greater than X[0], everything looks fine
screenshot from 2015-11-24 15-22-05

To test:
```
from numpy import *
x=arange(0,10,0.1)
y=sin(x)
w=CreateWorkspace(x,y)
w1=CreateWorkspace(-y,x)
w2=CreateWorkspace(-y[:15],x[:15])
w3=CreateWorkspace(-y[:35],x[:35])
```

### PR DESCRIPTION
**Pull request by mantid-roman**
Fixes #14568.

**To test**

Use the script from the issue description.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
@MattKing06 : I think this is very closely related to the issue that you were experiencing the other day with a muon data workspace?

**Comment by MattKing06** [comment]
@FedeMPouzols that's correct. I found this problem in #14484 however my fix involved just ordering the data such that it would plot. I'd be interested to see the fix for this problem in general.

**Comment by AndreiSavici** [comment]
seems to be working now

**Comment by KarlPalmen** [comment]
It didn't work for me when I ran it with a Nov 13 build (w2 did not plot).

**Comment by AndreiSavici** [comment]
@KarlPalmen sorry, I meant that I works with this fix

**Comment by KarlPalmen** [comment]
Fix works for me too.

**Pull request merged**
