### PR TITLE
13821 sans interface history

### PR DESCRIPTION
**Pull request by ricleal**

### CODE REVIEW

**Comment by ricleal** [comment]
There's a new QSettings entry for the catalog, so when the user processes data from other folder the catolog remain intact. There's also a tooltip if the user decides to enter the catalog path by end.

**Comment by FedeMPouzols** [comment]
@ricleal : pylint has a few complaints about this: http://builds.mantidproject.org/job/pull_requests-pylint/2212/violations/file/reduction_gui/settings/application_settings.py/
I think they're all simple to fix (like trailing whitespaces, unused imports, etc.).

Also, could you add some labels? I'd guess "Component/GUI" and "Component/SANS" would be appropriate.

**Comment by FedeMPouzols** [comment]
Oh, also if there was an issue that this PR fixes, remember to add the `Fixes #123456` comment so the issue gets closed when this PR is merged.

**Comment by ricleal** [comment]
@FedeMPouzols : Thanks. I left this running when I left on Friday. I'm fixing the issues now.

**Comment by ricleal** [comment]
Fixes #13821

**Comment by ricleal** [comment]
Fixes #13821

**Pull request merged**
