### PR TITLE
Update scale and shift used in reduction

### LINKED ISSUE #23309: scale and shift values should update
The scale and shift values displayed in the new GUI should update when a fit is done and have default values of 1.0. 

In addition in a merged reduction when the HAB is shifted it's value in the separate HAB file should also be shifted.

### PR DESCRIPTION
**Pull request by Matthew-Andrew**
**Description of work.**

This updates the scale and shift values after a SANS reduction so the actual values used are displayed in the GUI. This also produces a rescaled HAB workspace in the case of a merged reduction. 

* Updated view to make values changeable and set default values.
* output and update values from algorithm
* scale seperate HAB appropriately

**Report to:** Sarah 

**To test:**

 Code review
 * The data for this PR was too large to upload here if you want to test it email me and I'll send it to you.
 * Make sure the data is added to your directories path and then load USER_SANS2D_154E_2p4_4m_M3_Xpress_8mm_SampleChanger_REAR.txt as the user file and batch_file.csv as the batch file.
 * Go to Settings->General and change the reduction mode to merged and tick the two use fit boxes in the Merged settings box.
 * Go back to the run tab and click process. 
 * Hover over the row and check that updates scale and shift values are displayed.
 * Check that plotting the merge, front and rear produce results which look like the below.

image

Fixes #23309 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by soininen** [comment]
This PR doesn't seem to have any testing instructions.

**Comment by soininen** [comment]
Why the usage of tooltip? The fitted scale and shift values are very difficult to discover in my humble opinion. The user has to know that such a tooltip appears when hovering over the Options cell (even if the cell itself is empty) only after certain settings have been turned on and the data processed. Would it make sense to update the text in the Options cell to include the fitted values so they would be immediately visible?

**Comment by Mantid-Matthew** [comment]
@soininen On the assumption that the tests pass should now be ready for a re-look.

**Review by soininen — APPROVED** [review]
The fitted `MergeScale` and `MergeShift` appear in the Options cell as advertised. The code looks good to me, there are some tests and release notes have been updated as well so I think this is good to go.

On a side note, and completely out of the scope of this PR, I recommend exploring showing the content of the cells in tooltips. Now one has to resize the window and/or the columns to be able to read the whole text.

**Pull request merged**
