### PR TITLE
Add changing the colorbar label to figure options images tab

### LINKED ISSUE #28840: Can't set colorbar label in figure options
In the Images tab of the figure options, there is a Label option that doesn't seem to do anything. Now that colorbars are labelled on colorfill plots, you should be able to set what the label is.

### PR DESCRIPTION
**Pull request by PhilColebrooke**
**Description of work.**
This PR changes the Label input in the images tab of the figure options so that instead of setting the label of the image (not very useful), it sets the label of the colorbar.

**To test:**
Make an image plot with a colorbar, either a Colorfill or Surface plot.
Open figure options, go to Images tab.
Check that the Label field shows the current colorbar label, and changing it should update the label.
For image plots without a colorbar the label input should be disabled.

Fixes #28840 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by cailafinn — CHANGES_REQUESTED** [review]
Code looks good, just noticed one thing while testing:

The label option in the figure options does not match the label on the colorbar if it was changed by double clicking on it first.

**Review by cailafinn — CHANGES_REQUESTED** [review]
Just found an unhandled exception when an invalid symbol is given in the figure options. E.g. Load something like GEM38370 and replace `Counts ($\AA$)$^{-2}$` with `Counts ($\A$)$^{-2}$` for the label setting.

This may be out of scope for this PR as this occurs with all the label settings in the figure options.

**Comment by PhilColebrooke** [comment]
> Just found an unhandled exception when an invalid symbol is given in the figure options. E.g. Load something like GEM38370 and replace `Counts ($\AA$)$^{-2}$` with `Counts ($\A$)$^{-2}$` for the label setting.
> 
> This may be out of scope for this PR as this occurs with all the label settings in the figure options.

Yeah I've had a look into this and I'm not really sure how it can be fixed. The exception is only raised after the invalid label and the rest of the properties are already set, when `canvas.draw()` is called. There doesn't seem to be a way to check if a string contains invalid symbols before this.

**Comment by ConorMFinn** [comment]
> > Just found an unhandled exception when an invalid symbol is given in the figure options. E.g. Load something like GEM38370 and replace `Counts ($\AA$)$^{-2}$` with `Counts ($\A$)$^{-2}$` for the label setting.
> > This may be out of scope for this PR as this occurs with all the label settings in the figure options.
> 
> Yeah I've had a look into this and I'm not really sure how it can be fixed. The exception is only raised after the invalid label and the rest of the properties are already set, when `canvas.draw()` is called. There doesn't seem to be a way to check if a string contains invalid symbols before this.

This would appear to also have been broken in the last release. I'll make a separate issue for it, but the changes from this PR look good to me now.

**Review by cailafinn — CHANGES_REQUESTED** [review]
Code looks good and works well. Just needs the conflicts resolving.

**Review by cailafinn — APPROVED** [review]

**Pull request merged**
