### PR TITLE
Corrected Rendering of Rectangular Detectors

### LINKED ISSUE #22242: Instrument view shows now a gap between left and back SANS detectors
LoadEmptyInstrument D33:

Release 3.12:

release3-12-sansd33view

Master:

mastersansd33view

Expected behavior:
- no zickzack in particular when detector defines rectangular pixels in xy plane
- there should not be a gap between the left and back detector (it suggests that the IDF is wrong!)

### PR DESCRIPTION
**Pull request by LamarMoore**
Added correction to the rendering of rectangular detectors. Offsets and rotations were not handled correctly. This was highlighted by the D33 ILL instrument.

**To test:**

Ensure the D33 Instrument and other instruments which use `RectangularDetector` are rendered correctly. (LOQ, SANS2D etc).

Fixes #22242 . 

**Release Notes** 

*Internal fix does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by reimundILL** [comment]
Some checks that the IDF of D33 is correct (independent from instrument view):
In [7]: mtd['test'].getInstrument().getDetector(300031).getPos().norm()
Out[7]: 1.282812461936662
In [8]: mtd['test'].getInstrument().getDetector(200000).getPos().norm()
Out[8]: 1.282812461936662

**Review by vreimund — APPROVED** [review]

**Comment by reimundILL** [comment]
It renders fine now:

screenshot_2018-04-10_14-57-49

This is an instrument consisting of 5 rectangular detectors with rectangular but not squared pixels. I think it is a generally good test case

**Comment by martyngigg** [comment]
Have other non-rectangular based instruments been checked to confirm they are still okay?

**Comment by reimundILL** [comment]
I think the rendering problem cannot be easily detected when only one rectangular detector is used like for D11 and D22. Thus, I did not check other instruments.

**Comment by reimundILL** [comment]
Oh sorry, I did not realize that your question was about non-rectangular instruments. No, I did not check.

**Comment by reimundILL** [comment]
I think everybody worried can check his instrument - no need to checkout out this branch?

**Comment by LamarMoore** [comment]
@martyngigg The code modified only affects the rendering of Rectangular instruments. LOQ, SANS2D etc were checked to ensure they still render correctly.

**Comment by martyngigg** [comment]
@LamarMoore Thanks for the confirmation. I thought the code look like other bank-related things were changed but I can see that they were just removing namespace qualifiers.

**Pull request merged**
