### PR TITLE
Fix IDA preview plotting

### PR DESCRIPTION
**Pull request by DanNixon**
Fixes [#11167](http://trac.mantidproject.org/mantid/ticket/11167).

To test:
- Download the files from the ticket
- Open MSDFit
  - Load `osi92762_graphite002_elwin_eq2.nxs`
  - Click Fit Single Spectrum, should see a fit curve that will disappear when you change Plot Spectrum
  - Click Run, sill have a fit curve for all spectra that persists until another fit is done
- Open FuryFit
  - Load `irs26176_graphite002_iqt.nxs`
  - Move EndX such that is misses out the garbage at the end of the spectrum
  - Do the same tests
- Open ConvFit
  - Load Sample `irs26176_graphite002_red.nxs` (from systemtest data)
  - Load Resolution `irs26173_graphite002_res.nxs` (from systemtest data)
  - Select Fit Type: Two Lorentzians
  - Do the same tests

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please.

**Comment by DanNixon** [comment]
Jenkins, retest this please.

**Comment by FedeMPouzols** [comment]
This works well.

I tried to stress the 3 preview plots and they seem to behave. I only got into trobule once with ConvFit. After changing the spectrum and plotting/fitting several times, fitting stopped working (flat line result over and over again). But I cannot reproduce it. It might have been a glitch, and anyway it looked more related to fitting than the plot update itself which was working well.

**Comment by DanNixon** [comment]
@FedeMPouzols I kind of think that is fitting related, I've seen strange things happen every now and again if the peak centre and FWHM parameters are too far out to get a good fit.

**Pull request merged**
