### PR TITLE
SNSPowderReduction fixes

### LINKED ISSUE #24961: Unscripted Testing ORNL Powder Diffraction
1. Read http://www.mantidproject.org/Unscripted_Manual_Testing
1. Comment against this ticket the OS environment you are testing against.
1. Don't spend more than a few hours on the testing as fatigue will kick in.
1. If you find errors in the possibly scant documentation, then correct them.
1. Close the this issue once you are done.

If you find bugs:
* Search to see if an issue already exists
* create an issue if it is new
 * Urgent bugs or crashes should by against the current release, and assigned to a developer, then go and talk to the developer if possible.
 * Less urgent bugs should be against a subsequent release, and assigned if the correct developer is known.

### Specific Notes:

See http://www.mantidproject.org/PowderDiffractionReduction

### PR DESCRIPTION
**Pull request by peterfpeterson**
Various issues were discovered during unscripted testing. This resolves the last of them.
1. The vanadium radius wasn't being given to the Carpenter correction
2. Not correctly identifying cache files/cache descriptions were not unique
3. Loading the file (`MetaDataOnly=True`) when not necessary
4. Printing information about chunking when cache file was being used

Plus some other bits of code cleanup (e.g.. improving variable names, moving code into functions).

**To test:**

Try out various reductions.

Fixes #24961.

*This does not require release notes* because it is already covered in all the other things in `SNSPowderReduction` and `AlignAndFocusPowder`.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by peterfpeterson** [comment]
The `SEGFAULT` in `python.MuonQt4.grouping_tab_presenter_test.grouping_tab_presenter_test` is a known (unrelated) issue that is being worked on.

**Comment by marshallmcdonnell** [comment]
In testing with run `CORELLI_82281`, I got the following error regarding the workspace not being found in ADS:

**Comment by marshallmcdonnell** [comment]
Confirmed its working on `release-next` branch. Looks to be something to do with the `__determineCharacterizations` method

**Comment by marshallmcdonnell** [comment]
Cool, that last commit fixed my CORELLI crash test (what a simple `not` can do :grin:)

I still need to test the `MetaDataOnly` stuff as well.

**Review by marshallmcdonnell — APPROVED** [review]
`MetaDataOnly` stuff working as well (see other comments for other testing)

Overall, working for my manual testing and good quality improvements :+1: 

LGTM

**Pull request merged**
