### PR TITLE
Update DEMAND workflow to support satellite peaks

### PR DESCRIPTION
**Pull request by rosswhitfield**
**Description of work.**

Adapt DEMAND 2-circle workflow to work with satellite peaks [SCD286](https://code.ornl.gov/sns-hfir-scse/diffraction/single-crystal/single-crystal-diffraction/-/issues/286)

**To test:**

From the usage examples

```python

data_files = "HB3A_exp0724_scan0182.nxs, HB3A_exp0724_scan0183.nxs"

# Converts to MDEventWorkspace
#  If needed, the sample position can be adjusted by a height and distance - see the HB3AAdjustSampleNorm docs
data = HB3AAdjustSampleNorm(Filename=data_files)

# Finds peaks on the combined workspace, optimizing the UB matrix for the given cell type parameters
#  lattice parameters can be optionally specified to calculate the UB matrix (see docs for HB3AFindPeaks)
peaks = HB3APredictPeaks(InputWorkspace=data,
                         ReflectionCondition='B-face centred')

# Integrate the predicted peaks from the workspace above
integrated_peaks = HB3AIntegratePeaks(InputWorkspace=data, PeaksWorkspace=peaks,
                                      PeakRadius=0.25,
                                      OutputFile="./integrated_peaks.hkl")

satellites_peaks = HB3APredictPeaks(InputWorkspace=data,
                                    ReflectionCondition='B-face centred',
                                    SatellitePeaks=True,
                                    ModVector1='0.4,0,0',
                                    MaxOrder=1,
                                    IncludeIntegerHKL=False)
integrated_satellites_peaks = HB3AIntegratePeaks(InputWorkspace=data, PeaksWorkspace=satellites_peaks,
                                                 PeakRadius=0.15)
                                                 OutputFormat="Fullprof",
                                                 OutputFile="./integrated_satellite_peaks.hkl")
```

Red is nuclear peaks, green is satellite peaks

HB3A_exp0724_satellites

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by zjmorgan** [comment]
The new system test `SatellitePeaksFakeData` works well. It clearly shows the generation of the fake Bragg and satellite peaks with (mod vector greater than 1.0) setting the HKL and getting the Q-sample from the UB matrix. `HB3APredictPeaks` accurately obtains the Bragg and satellite peak positions and the `HB3AIntegratePeaks` gives back reasonable intensities (Bragg is about 10 times greater than satellites) based on the generated datasets. 

I think everything works well. The integrated reflections with 'FullProf' also looks good.

**Review by peterfpeterson — CHANGES_REQUESTED** [review]
From a standpoint of the code, this looks good. Moving more code to use interface classes makes this more generic.

Please add release notes and this is good to go.

**Review by zjmorgan — COMMENTED** [review]
If predicting the peak positions of only nuclear peaks, are there any advantages to using a normal peaks workspace as opposed to a lean one? 

```
            peaks = PredictPeaks(InputWorkspace=input_ws,
                                 ReflectionCondition=reflection_condition,
                                 CalculateGoniometerForCW=True,
                                 Wavelength=wavelength,
                                 FlipX=True,
                                 InnerGoniometer=use_inner,
                                 MinAngle=min_angle,
                                 MaxAngle=max_angle,
                                 MinDSpacing=self.getProperty("MinDSpacing").value,
                                 MaxDSpacing=self.getProperty("MaxDSpacing").value,
                                 OutputWorkspace=output_ws)
```

**Review by peterfpeterson — APPROVED** [review]

**Review by DavidFair — APPROVED** [review]
LGTM

**Pull request merged**
