### PR TITLE
Clean up naming of SofQW algoritithms

### PR DESCRIPTION
**Pull request by martyngigg**
Fixes trac issue [#11336](http://trac.mantidproject.org/mantid/ticket/11336)

**Tester**
The changes here have renamed the old `SofQW{2,3}` to `SofQWCentre`, `SofQWPolygon`, `SofQWNormalisedPolygon` and left aliases for 
- `SofQW2`->`SofQWPolygon`
- `SofQW3`->`SofQWNormalisedPolygon`
  `SofQW` itself is now a shell that defines an extra parameter to choose between the 3 options. The default is `Centre` so that running `SofQW` produces identical results as before.
  Check the documentation has been updated with the new names and that calling `SofQW` with the various options calls the correct algorithm.

### CODE REVIEW

**Comment by OwenArnold** [comment]
Changes look good, the documentation is much better. But.

* SofQW now looks like it ought to be a DataProcessing algorithm rather than just an Algorithm. That way we can extract the child algorithm from the history
* I would also suggest that SofQWTest include some kind of check that the "Method" parameter resolves to the correct child algorithm. That seemed to be absent.

**Comment by martyngigg** [comment]
I debated whether to make it a workflow algorithm or not and as it was only running a single algorithm I wasn't sure it was worth it but it won't do any harm so I'll make the change.

Good point about the unit test, I'll get that updated.

**Comment by martyngigg** [comment]
I've tidied those things up now along with reducing a bit of copy-and-paste that was in the tests.

**Comment by martyngigg** [comment]
Strange, that test passed for me when I ran it. I'll take a look.

**Comment by martyngigg** [comment]
I can only surmise that I hadn't actually compiled the test properly when I changed the code as it failed this time when I tried it. I've just pushed a fix.

**Comment by granrothge** [comment]
Would it not be better to make a single sofqw algorithm that then has  an additional parameter that can be one of  �Centre, Normalized Polygon, Or Polygon�  It should be up for debate which of the first two its the default.

Best,

Garrett


On Apr 13, 2015, at 9:37 AM, Martyn Gigg <notifications@github.com<mailto:notifications@github.com>> wrote:


I can only surmise that I hadn't actually compiled the test properly when I changed the code as it failed this time when I tried it. I've just pushed a fix.

�

**Comment by martyngigg** [comment]
@granrothge That's one of the changes that has gone in here. `SofQW` is now just a wrapper algorithm that has a `Method` parameter controlling which of the others is chosen. If this were brand new I would probably pick `Polygon` as the default but users would have got `Centre` before so I've kept it as that

**Pull request merged**
