### PR TITLE
Merge IndexPeaks and IndexPeaksWithSatellites. Deprecate IndexPeaksWithSatellites.

### LINKED ISSUE #26829: Add modulation vector input options to IndexPeaks and deprecate IndexPeaksWithSatellites
While investigating #26795 it was discovered that the code for both algorithms was basically identical. The only difference is that `IndexPeaks` does not have the options to specify modulation vectors/order for satellite peak searching instead requiring them to be specified on the `OrientedLattice` object.

As a user it would be less confusing to have a single indexing algorithm with the option for indexing satellites as well.

### LINKED ISSUE #26836: SaveIsawUB does not save satellite peaks
The ISAW UB file format allows for saving  modulation vectors yet `SaveIsawUB` does not save them if the satellites exist.

Investigate and fix the bug.

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

The process used to index peaks in `IndexPeaks` and `IndexPeaksWithSatellites` was the same and the code was very similar. The decision was made to extend `IndexPeaks` with the option to enter the modulation information and deprecate `IndexPeaksWithSatellites`. 

**To test:**

Run tests from
* #25660
* #22895 (if data from SNS available)

You can also try with [pr-26807.txt](https://github.com/mantidproject/mantid/files/3617004/pr-26807.txt) as the UB matrix and [unindexed-peaks.zip](https://github.com/mantidproject/mantid/files/3617009/unindexed-peaks.zip) to test this.

First run the following script and observe that it indexes 12 peaks and leaves the other 12 with HKL=[0,0,0] (unindexed).

```python
Load(Filename='unindexed-peaks.nxs', OutputWorkspace='sx_peaks')
LoadIsawUB(InputWorkspace='sx_peaks', Filename='pr-26807.txt')
IndexPeaks(PeaksWorkspace='sx_peaks', Tolerance=0.1, ToleranceForSatellite=0)
# IndexPeaks(PeaksWorkspace='sx_peaks', Tolerance=0.1, ToleranceForSatellite=0.1, ModVector1='0.333,0.333,0', ModVector2='-0.667,0.333,0', ModVector3='0.333,-0.667,0', MaxOrder=1)
```

Run the commented out `IndexPeaks` and check it now indexes additional peaks as satellites.

After the satellites are indexed run `SaveIsawUB` and check that the file contains a list of modulation vectors.

Fixes #26829
Fixes #26836 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by NickDraper — COMMENTED** [review]
Passes the tests in #22895

The tests in #25660 require a file only available at the SNS

**Comment by martyngigg** [comment]
I just need to check with Andrei/Ross whether the fix applied in #26941 needs to be applied here too.

**Comment by martyngigg** [comment]
I've added some further test instructions/data to the description.

**Comment by martyngigg** [comment]
I have just noticed that this fixes another issue I had around `SaveIsawUB` so I have added a final test case in the description.

**Comment by martyngigg** [comment]
@NickDraper Would you have time to finish of testing this? I've updated the instructions with some test data that doesn't require access to any SNS files.

**Review by RichardWaiteSTFC — DISMISSED** [review]
Tested with the unindexed peaks in the zip file attached. Algorithm now correctly indexes satellite peaks and successfully reproduces the functionality of IndexSatelitePeaks which is to be depreciated. 
However, during testing an issue was discovered with the flag CommonUBForAll ( (27146) which also exists in the version 4.1.0 of mantidplot.

**Pull request merged**
