### PR TITLE
Update class_maker.py

### PR DESCRIPTION
**Pull request by raquelalvarezbanos**
Fixes [#11754](http://trac.mantidproject.org/mantid/ticket/11754)

This PR is to update the class_maker script to generate code following the current standards. Specifically there are three points to have a look at: clang format, naming convention and definitions in cpp files (see original trac ticket).

**For tester**: 

I have updated class_maker.py according to clang format. To test, run the script (run with --h for help) to create a new class and check that it is formatted according to clang standards. Check the same for a new algorithm (run with --alg).

Regarding naming conventions and methods in header and source files (http://www.mantidproject.org/C%2B%2B_Coding_Standards), I have not modified or updated anything as the script was already generating code with the appropriate standards. Ensure this is correct (for instance, if a new algorithm is created there are some methods that must be overridden http://www.mantidproject.org/Algorithm_Documentation).

### CODE REVIEW

**Comment by DanNixon** [comment]
The only extra thing I can think that this could do with having is a note reminding the developer to subclass ```DataProcessorAlgorithm``` when the algorithm is a workflow algorithm.

**Comment by FedeMPouzols** [comment]
Maybe another useful reminder could be added about `processGroups()` which you need to override when your algorithm operates on a WorkspaceGroup?

**Comment by raquelalvarezbanos** [comment]
Thanks for the comments! the two reminders have been added, they are printed when class_maker is run with --alg.

**Comment by DanNixon** [comment]
Looks good, I'll not bother waiting for the CI since this isn't included in it.

**Pull request merged**
