### PR TITLE
Update Valgrind suppressions

### PR DESCRIPTION
**Pull request by martyngigg**
Fixes trac issue [#10920](http://trac.mantidproject.org/mantid/ticket/10920)

**Tester**
Check the valgrind build of the core packages no longer shows any warnings - 
http://builds.mantidproject.org/view/Valgrind/job/valgrind_develop_core_packages/

### CODE REVIEW

**Comment by martyngigg** [comment]
retest this please

**Comment by martyngigg** [comment]
retest this please

**Comment by martyngigg** [comment]
retest this please

**Comment by FedeMPouzols** [comment]
All looks fine and the 11 memory leak warnings have vanished away, so it works.

**Pull request merged**
