### PR TITLE
SampleLogs filtering

### LINKED ISSUE #30090: SampleLogs filtering
### Expected behavior

It would be nice to have the ability to filter logs using keywords or keywords fragments to speed up the search time of the desired SampleLog entry. 

### Actual behavior

Currently the SampleLogs widget does not support filtering of keys.

### Platforms affected
workbench

### PR DESCRIPTION
**Pull request by darominski**
**Description of work.**

Added the possibility of filtering SampleLogs using an added QLineEdit. When editing is finished, the model is recreated and only the keys that match (case-insensitive) the given string are displayed. 

**To test:**

1. In the Workbench, load any data with logs you would like, e.g. ILL/D22/192068.nxs from the UnitTest data
2. Right-click on the created workspace and choose Show Sample Logs
3. Notice there is a new QLineEdit widget at the bottom of the SampleLogs dialog window.
4. Type-in a keyword, e.g. 'beam' for ILL/D22/192068.nxs, press Enter and check whether all the shown logs contain this keyword. Please notice that the matching is case-insensitive.
5. Repeat with a couple of different keywords and check if the shown logs match the typed-in keyword. 

Fixes #30090 . 

*Release notes* added.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by clayton-tom — COMMENTED** [review]
The code looks good and search function works well, however the LineEdit isn't very prominent and it's function may not necessarily be obvious to a new user. Could be worth setting some placeholder text e.g. `Search logs` to make it clearer

**Comment by darominski** [comment]
> The code looks good and search function works well, however the LineEdit isn't very prominent and it's function may not necessarily be obvious to a new user. Could be worth setting some placeholder text e.g. `Search logs` to make it clearer

Good point, I added a placeholder text on top of a tool tip. In addition, to make it more consistent with Workspaces and Algorithms widgets, I moved the QLineEdit to the top of the left frame rather than leaving it at the bottom. Also, I replaced the SampleLogs.png image of the widget with a screenshot that contains the implemented feature.

**Comment by clayton-tom** [comment]
Nice changes, looks much clearer. I've got one more small nitpick - could you connect the signal from the LineEdit clear button to the `search_key_changed` slot also, as currently when the box is cleared the table doesn't immediately update, but rather only when the user then clicks on the table again emitting the `editingFinished` signal

**Comment by darominski** [comment]
> Nice changes, looks much clearer. I've got one more small nitpick - could you connect the signal from the LineEdit clear button to the `search_key_changed` slot also, as currently when the box is cleared the table doesn't immediately update, but rather only when the user then clicks on the table again emitting the `editingFinished` signal

This is a valid point. Perhaps a better signal to connect would be then 'textEdited' rather than `editingFinished`. Then, there's no need to ever press enter and the feedback on the filtering is immediate.

**Review by clayton-tom — APPROVED** [review]
Good point on the `editingFinished` signal. Nice work 👍

**Comment by gvardany** [comment]
👍  filtering should happen as you type.

**Pull request merged**
