### PR TITLE
Add Workspace to Scale Option to the ISIS Reflectometry GUI

### LINKED ISSUE #14846: Reflectometry GUI should have a scale option
Sub issue for #14787

Where Stitch1D is run in Max's Reflectometry GUI, we need to be able to specify that scaling should be left-hand side or right-hand side. Currently where stitching is performed [here](https://github.com/mantidproject/mantid/blob/master/scripts/Reflectometry/isis_reflectometry/combineMulti.py#L79:L82) The `ScaleRHSWorkspace` property is not specified so will default to True (see [here](http://docs.mantidproject.org/nightly/algorithms/Stitch1D-v3.html)). We need a way to allow the user to specify which workspace RHS or LHS will be scaled as part of the Stitch operation from the GUI.

### PR DESCRIPTION
**Pull request by OwenArnold**
Fixes #14846

**Tester**

Code review the changes, then set about exercising the functionality via the MantidPlot ->Interface->Reflectometry->ISIS [Reflectometry GUI](http://www.mantidproject.org/ISIS_Reflectometry_GUI)

To do this, get the files listed here http://www.mantidproject.org/Testing_ISIS_Reflectometry_GUI#Requirements

Checking the Menu Options
1. Open the UI
2. Go to Options->Refl GUI Options
3. The option _Scale Right Workspace When Stitching_ should be checked
4. Close the options

Run the UI in the default mode
1.  Open the table (*.tbl file listed above) via the File->Open Table Option.
2.  Select the first row in the table. Select the 'Stitch' checkbox on that row.
3. Hit 'Process'
4. You'll get a workspace called '13460_62' created. Rename it to  '13460_62_left'

Change the Options and Re-run
1. Now change the option _Scale Right Workspace When Stitching_  to be deslected.
2. Rerun the same row in the same way as above
3. Rename the output Rename the output '13460_62' to '13460_62_left'
4. Plot both and you should get something like this.
   screen shot 2015-12-23 at 10 39 38

TODO:
Release notes and online documentation for this interface will need updating

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
@OwenArnold is this still `In Progress`?

**Comment by OwenArnold** [comment]
@raquelalvarezbanos Yes it is. I'll forward you some correspondence. Could you please follow up with Mario.

**Comment by raquelalvarezbanos** [comment]
@OwenArnold: OK, I've sent you an email

**Comment by OwenArnold** [comment]
@raquelalvarezbanos. As Mario has tested this and is happy. I've removed the in progress flag.

**Comment by raquelalvarezbanos** [comment]
OK, Matt will resolve the conflicts and test this.

**Comment by raquelalvarezbanos** [comment]
Just to confirm that Mario seems to be happy with the changes. He sent the following plot he used for testing:

fig

**Pull request merged**
