### PR TITLE
Add Breadcrumb to user docs

### PR DESCRIPTION
**Pull request by DanielMurphy22**
**Description of work.**

**To test:**

- Build the docs-html target
- check that the breadcrumb (just below the top navbar) can help you navigate the docs More quickly. The root (master_doc) page is labelled as Documentation (is there a better name???). The current page is in the breadcrumb, with a clickable link. 
- Any comments on its formatting?? Ive added it to the nav bar at the top but this is a design choice that I could easily change!
- Ive not tested what this looks like in the built in qthelp docs, but we should check it works there too!

*This does not require release notes* because **documentation update**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by SilkeSchomann — CHANGES_REQUESTED** [review]
It works fine in the user docs in docs-html, but there are no breadcrumbs available in qthelp.

**Review by SilkeSchomann — DISMISSED** [review]
Qt-help now has next and previous buttons in the navigation bar which is the qt-help equivalent to breadcrumbs.

**Comment by martyngigg** [comment]
@DanielMurphy22 Thanks for this. It's marked in milestone 6.3 but is merging to `main`. Shall we be safe and leave this in 6.4?

**Comment by DanielMurphy22** [comment]
> Qt-help now has next and previous buttons in the navigation bar which is the qt-help equivalent to breadcrumbs.

@SilkeSchomann can I just check what you actually see on the qthelp docs? At the top of the page I don't get a next/previous, but I do actually get the breadcrumb! Can you send a screenshot of what you see?? 

Screenshot 2022-01-27 at 09 57 49

**Comment by SilkeSchomann** [comment]
On a Windows PC it looks like this:
image

**Comment by DanielMurphy22** [comment]
> On a Windows PC it looks like this: image

Interesting, I'll try to build on my Windows machine and figure this out!

**Comment by DanielMurphy22** [comment]
@SilkeSchomann can you install and check qthelp docs on the package build of this PR at this link. It seems to work for me on Windows.  https://builds.mantidproject.org/job/pull_requests-windows/48821/artifact/build/mantidunstable-6.2.20220128.725-win64.exe

I'm sorry my test instructions were so poor: I should have told you to build the targets `docs-html` and `docs-qthelp` (and possibly `docs-qtassisstant`)

**Comment by SilkeSchomann** [comment]
Interesting, that works. I had only compiled 'docs-html' and 'docs-qthelp', not 'docs-qtassisstant'.

**Review by SilkeSchomann — APPROVED** [review]
Breadcrumbs are visible for qt-help as well, therefore approved.

**Comment by DanielMurphy22** [comment]
> Interesting, that works. I had only compiled 'docs-html' and 'docs-qthelp', not 'docs-qtassisstant'.

doc-html and docs-qthelp was enough on Ubuntu, but maybe another step is needed on Windows!?! Glad we're both seeing the same thing now!

**Pull request merged**
