### PR TITLE
Test the doc tests from mediawiki examples nightly

### LINKED ISSUE #13355: Test the mediawiki doctests nightly
issue #13310 an pull request #13311 added doctests for mediawiki pages

This is to add them to the ?nightly automated build

It involves running the script 
``` 
python.exe TestWikiPython.py -o C:\Mantid\Code\Mantid\docs\source\mwTests
```

and then running the doctests job as normal.the path in C:\Mantid\Code\Mantid\docs\source\mwTests must be within the source directories of the sphinx help, but does not need to exist in advance.

Feel free to move the TestWikiPython.py script to another location if it makes more sense for it to be there, it is a standalone script, and should be ignorant of it's location.

The build servers will need there HTTP_Proxy environment setting set if necessary to get a network connection out to the mediawiki site.

### PR DESCRIPTION
**Pull request by FedeMPouzols**
Fixes #13355.

**To test**:
- Check the Jenkins job: http://builds.mantidproject.org/view/All/job/master_doctests_wikitests. The build has been working well for a few days.
- Initially we had one failure in one of the SliceViewer examples (outdated expected output). Currently all tests pass.
- Check that it is actually testing the special mediawiki tests (the ones `mwTests/mwTest_...`). There should be >=1004 tests in total.
- I think the current location of TestWikiPython.py is fine. An alternative could be to move it to `docs/` where you also find the scripts that build and test the documentation.
- As discussed in #13311, the "mwTests" take less than a minute to generate and ~2 minutes to run, so it should be safe to have them included in this job.

Note: when this is merged, the job configuration needs to be updated to execute the modified `buildconfig/Jenkins/doctests` instead of the temporary shell text.

### CODE REVIEW

**Comment by martyngigg** [comment]
@FedeMPouzols Sorry it has taken so long to look at this. It appears now that some tests are failing: http://builds.mantidproject.org/view/All/job/master_doctests_wikitests/16/#showFailuresLink

**Comment by FedeMPouzols** [comment]
Yes, four tests have been failing for the last few days. These have to do with the reorganization of the instrument viewer. The new Qt widget for the instrument vieew is being exposed to Python (#15336). The Mantid-Python course examples (http://www.mantidproject.org/Instrument_View_Control) and exercises will need an update. I'm not sure if the old way of manipulating the instrument window will be still supported. @LamarMoore ? @OwenArnold ?

**Comment by martyngigg** [comment]
I think we should keep supporting the old commands and deprecate them when we come up with a consistent api design.

**Comment by martyngigg** [comment]
I think we should merge this to remind us they need fixing. Does that sound reasonable?

**Comment by martyngigg** [comment]
I'm going to merge this as these changes actually work and the actual failures need to be more visible.

**Pull request merged**
