### PR TITLE
Add algorithm GSASIIRefineFitPeaks

### LINKED ISSUE #10630: Interface with GSAS-II from Engg GUI for EnginX analysis
This issue was originally [TRAC 9788](http://trac.mantidproject.org/mantid/ticket/9788)

This ticket is blocks :  [TRAC8368](http://trac.mantidproject.org/mantid/ticket/8368)

From discussion with Saurabh Kabra.

Now http://trac.mantidproject.org/mantid/ticket/8760 has been done the next bigger task is to provide EnginX Python scripts that make external calls to GSAS, replicating existing typcial GSAS analysis on EnginX.

Note the main output of http://trac.mantidproject.org/mantid/ticket/8760 are two parameters Difc and Zero, which can be feed into GSAS input file. In addition from Mantid GSAS *.gss can be generated, and where necessary *.prm. Also, EnginX has a collection of GSAS phaseinformation (*.exp) files and GSAS sequence command files. The script will takes such inputs and returned a GSAS output that can be viewed with GSAS GUI.

Currently EnginX make calls to GSAS from OpenGenie scripts. Replicate these to python scripts that makes calls to GSAS. 

For this ticket assume that GSAS is pre-installed on the computer. If the script detect that this is not the case then the user should be pointed at a web-site explaning how to install GSAS so that the script can be used.

These scripts may be located in https://github.com/mantidproject/mantid/tree/master/Code/Mantid/scripts/Engineering or some subfolder of https://github.com/mantidproject/scriptrepository

### LINKED ISSUE #15771: Add algorithm GSASIIFitPeaks
To enable #10630 and #15552. Uses GSASII assuming that it is installed on the system. 
Requires a patched version of GSASII.
Uses the powder diffraction module (`GSASIIpwd`), and from there the `DoPeakFit()` function and related code.

This is a first experimental version. It should work for ENGIN-X.
- Assume the peak shape back to back exponential convolved with a pseudo-Voigt: http://www.mantidproject.org/BackToBackExponentialPV
- Assume the (default) Chebyshev polynomial background

Inputs:
- Histogram data 
- Instrument parameters file (a modified version of the traditional ENGIN-X .par files is required)
- Whether to refine each of the parameters (for all peaks): position, intensity, alpha, beta, sigma, gamma
- Whether to use the "auto search" to find initial guesses. Otherwise you need to provide an input table with as many rows as expected peaks, and initial parameter values in the columns.

Outputs:
- goodness of fit estimations: `Rwp` and `GOF`
- dictionary of parameter values (this can be produced in a table workspace that would resemble the table shown by the GSASII GUI).
Further outputs to consider now or in future improvements:
- list of parameters/variables / list of "bad" parameters/variables
- the esd estimate for the parameters fitted correctly

This will be implemented as a Python algorithm, as it uses/imports the GSASII python package.

### PR DESCRIPTION
**Pull request by FedeMPouzols**
Implements an algorithm that uses GSAS-II to refine lattice parameters and fit peaks. Supports Pawley and Rietveld refinement. Uses GSAS-II modules for powder diffraction and structure. 
Not ready for testing. It's missing proper test data.

**To test:**
- Check the documentation of the algorithm
- There's a too simple unit test that just checks that the algorithm is there. No hope of having proper unit/system tests as this requires GSAS-II.
- You need to install a patched version of GSAS-II (ask me for details).
- Requires a GSAS-II instrument parameter file (.par/.prm/.iparm) and a phase information file (.cif), in addition to histogram data.
- Usage example (you can run this script - it will require changing the paths to your local ones, or run the algorithm though its interface where you can browse... for the files):

```
import mantid
from mantid.simpleapi import *
wks_focused = Load('focused_bank1_ENGINX00256663.nxs')
inst_file = 'ENGINX_255924_254854_North_bank.par'
phase_file = 'FE_ALPHA.cif'
gsas_path = '/path/to/gsas/' # replace as needed
GoF, Rwp, lattice_tbl = GSASIIRefineFitPeaks(InputWorkspace=wks_focused,
                                             InstrumentFile=inst_file,
                                             PhaseInfoFile=phase_file,
                                             PathToGSASII=gsas_path,
                                             SaveGSASIIProjectFile='example_gsas2_project',
                                             LatticeParameters='lattice_tbl')

print "Goodness of fit coefficient: {0:.5f}".format(GoF)
print "Weighted profile R-factor (Rwp): {0:.5f}".format(Rwp)
print ("Lattice parameters, a: {a}, b: {b}, c: {c}, alpha: {alpha}, beta: {beta}, gamma: {gamma}, "
       "Volume: {volume:.3f}".format(**lattice_tbl.row(0)))

```
- See also the usage examples in the algorithm documentation page.
- The three required files (phase information, instrument, and focused data) can be found here (ISIS network): `\\olympic\Babylon5\Public\fedemp\ENGINX-X\GSASII_Mantid`
- For the original data files (at ISIS): `\\olympic\babylon5\public\fedemp\ENGINX-X\GSASII_docstests_data`
- If you have installed GSASII, update it it to the latest version from the server: Main menu / Help / Check for updates. This is just to make sure that we're up to date. Then copy the files found in `\\olympic\babylon5\public\fedemp\ENGINX-X\GSASII_Mantid\modified_files` directly to the top level of your GSASII installation (Something like C:... or D:\GSASII). You should see that all these files overwrite existing files. Alternatively, you could apply the patch found in `\\olympic\babylon5\public\fedemp\ENGINX-X\GSASII_Mantid\`.
- If you haven't installed GSASII, for the patched version of GSASII as a whole: `\\olympic\babylon5\public\fedemp\ENGINX-X\GSASII_Mantid\gsas`

Fixes #15771.
Fixes #10630 (an older ticket superseded by this).

Release notes:  https://github.com/mantidproject/mantid/commit/75eb23d98d306ac382e3cfb61c2d270d6d68a859

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
Current status: this still needs some work to add proper support for phase information, and additional outputs, discussed in todays meeting with Saurabh.

**Comment by FedeMPouzols** [comment]
Current status: this is now fully developed and includes all the last features discussed with instrument scientists recently. It is ready for testing. The only remaining detail is that the usage examples use not so great data. If we get nicer examples from Saurabh we could still add them in this PR, or we could do that later on. Let's see, maybe it's worth waiting until next Wednesday.

**Comment by shahrozahmed1** [comment]
@FedeMPouzols wasn't there a meeting this week too in which he wanted to test few recent files with us as well as provide us with data we need?

**Comment by FedeMPouzols** [comment]
@shahrozahmed1 : not that I know. The next meeting in my calendar is for next week (Wed).

**Comment by shahrozahmed1** [comment]
Might need your help setting up the correct GSAS-II version... Also even though pylint passed, `GSASIIRefineFitPeaks.py` seems to be producing few additional pylint violations.

**Comment by FedeMPouzols** [comment]
@shahrozahmed1 Yes I have to prepare a "custom distribution" for windows. Thanks for noticing the pylint issues. I just fixed them, hopefully. My local pylint (1.5.2) doesn't give me those messages even if I use the same cfg file. Hum.

**Comment by shahrozahmed1** [comment]
@FedeMPouzols some conflicts produced here, I think it might just be the diffraction release notes.

**Comment by FedeMPouzols** [comment]
@shahrozahmed1 : Yes, there was a conflict in the release notes. It should be fixed now. So for the testing let's wait if we get nicer example data within a few days (by next Wed). And if not, let's go ahead with the current examples which are not nice but enough as a usage example.

**Comment by shahrozahmed1** [comment]
@FedeMPouzols now that we have manage to grab the data from Saurabh, this can be tested. I have noted down the test data for 2016 but kindly send me the test data for 2015 as well; I can look for the files myself on the network. Also if you can please send me the link of the `GSAS-2` patch version so I can begin testing this PR.

**Comment by FedeMPouzols** [comment]
Yes, I have to update the examples in the docs-tests and see how they work with the "reference" run files that we got.

**Comment by FedeMPouzols** [comment]
@shahrozahmed1 : I've now updated the usage examples and the testing instructions for the "neutron training course" example data. The fit is not good at all, but we can go ahead with this for now. We'll have to double-check with instrument scientists what might be wrong/very inaccurate here.

With the last changes, this is ready for testing, assuming all builds pass.

**Comment by shahrozahmed1** [comment]
`GSASIIRefineFitPeaks` algorithm enables `GSAS-II` to be utilised with Mantid to refine lattice parameters and fit peaks. Certain steps during installation are required to be followed in order to successfully process the algorithm; correct modified files are also required within in `GSAS` and `wxPython` is required to be imported within Mantid.
Even though `GSASIIRefineFitPeaks` algorithm is not fully stable yet but looks to be a good starting point and something which could be a really useful feature for the scientists in future.

:shipit:

**Comment by FedeMPouzols** [comment]
On non-windows systems this is working quite smoothly. On windows it seems that from the at least three alternative ways of installing GSAS-II, besides the quite cumbersome installation process, they all have stability issues. The Mantid algorithm itself is reliable I think, but we cannot do much about the GSAS-II stability issues.

**Comment by shahrozahmed1** [comment]
@FedeMPouzols isn't there a way around getting these conflicts in release notes ?

**Comment by shahrozahmed1** [comment]
:shipit:

**Pull request merged**
