### PR TITLE
Python algorithm to calculate Q-E trajectories for direct spectrometers

### LINKED ISSUE #14883: Q-E Coverage graphs for direct geometry instruments
To aid planning experiments it would be useful to have plots of the detector trajectories (in Q-E space) for a given incident energy for a given instrument. Assuming powder averaging, this would require only knowledge of the minimum and maximum detector angles (and any detector gaps).

We'd like to contribute a python algorithm which does this calculation and produces a workspace with the required Q- and E-data and plots it.

### PR DESCRIPTION
**Pull request by mducle**
Fixes #14883 

Added QECoverage.py algorithm to calculate the trajectory and plots the graph.

### CODE REVIEW

**Comment by stuartcampbell** [comment]
@AndreiSavici how does this fit in with the planning tools that you have already done.

**Comment by AndreiSavici** [comment]
A few comments:
1. Fix pylint
2. HYSPEC coverage depends on s2 log value. To incorporate this fact in the algorithm, you need to add an s2 input parameter. In MantidPlot you can set that parameter to be visible only if instrument is HYSPEC. You can safely assume that the angle varies between s2-30 and s2+30. You need to consider the case |s2|<30 and s2 is positive or negative
3. Plotting using pymantidplot should not be done inside an algorithm. Create an interface if you want, or even better, use matplotlib.
4. It seems to me that there are several unrelated issues in this PR (mlzutils, FitGaussian). Make them as separate PRs

**Comment by mducle** [comment]
Yes... sorry I'll get back to this one tomorrow - I've been side tracked by Horace. The pylint problem is a space at the end of a line, and I wanted to incorporate all the indirect instruments before pushing.

This little project has blown up enough (with the indirect instruments) that maybe an interface is better...

**Comment by mducle** [comment]
Andrei, it seems I don't know how to run git... I've decided to rewrite everything as an interface but I can't revert changes already made... Can we start again on another branch?

**Comment by AndreiSavici** [comment]
Sure. That's fine by me

**Comment by AndreiSavici** [comment]
Please use the following procedure to calculate tt limits for HYSPEC:
-if abs(s2)<=30, then the angle goes from 0 to abs(s2)+30
-if abs(s2)>30, the angle goes from abs(s2)-30 to abs(s2)+30

**Comment by mducle** [comment]
Reimplemented as an interface, and made a new pull request: #14997

**Pull request closed without merging**
