### PR TITLE
Update mantidpython for python3

### PR DESCRIPTION
**Pull request by quantumsteve**
Description of work.

This updates the `mantidpython` script to work when Mantid is build with python3

**To test:**

http://builds.mantidproject.org/job/master_clean-osx-10.11-python3/102/

There is no GitHub issue associated with this pull request

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by quantumsteve** [comment]
@gvardany @samueljackson92 Would you test this?

**Comment by quantumsteve** [comment]
@samueljackson92 Have you had a chance to look at this?

**Comment by samueljackson92** [comment]
@quantumsteve Sorry I've been slow to look at this. I was actually just in the process of building this before you commented.

**Comment by samueljackson92** [comment]
Mantid python now finds ipython3 when Mantid is built with python3. :shipit:

**Pull request merged**
