### PR TITLE
Added google analytics to doxygen.

### LINKED ISSUE #158: Add site tracking to doxygen
The tracking information is
```javascript
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-59110517-2', 'auto');
  ga('send', 'pageview');

</script>
```

### PR DESCRIPTION
**Pull request by peterfpeterson**
This fixes #158.

**To test:** Build the doxygen and see that `GoogleAnalyticsObject` is in the `<head>` of the resulting html documents.

### CODE REVIEW

**Comment by martyngigg** [comment]
Building locally I can see that this is fine.

We have a problem on the build servers though. They are running v1.8.3 and it looks like there is a bug where it doesn't expand the path to the static files properly. See [here](http://builds.mantidproject.org/job/doxygen_develop/ws/build/doxygen/html/index.html/*view*/) and look at `<link href="$relpath^doxygen.css" rel="stylesheet" type="text/css" />`.

I think we'll have to upgrade the packages on the builders to at least doxygen v1.8.6

**Comment by peterfpeterson** [comment]
@martyngigg unfortunately that is part of the html header that I got directly from doxygen. I have access to 1.8.6 and 1.6.1. Which build server is running 1.8.3?

**Comment by martyngigg** [comment]
It looks to be `ornl-rhel6-builder3` that ran the job that produced the bad output.

**Comment by martyngigg** [comment]
This looks fine now. The header appears on the broken doxygen version and my newer one that worked originally.

**Pull request merged**
