### PR TITLE
Frequency domain analysis FFT default values

### LINKED ISSUE #31150: FFT bug
If you run the below script, the discrete fourier transform and numpy fourier transform give the same result. However, Mantid's FFT gives a different result and has more noise.

```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 0.5, 500)
y = np.sin(40 * 2 * np.pi * x) + 0.5 * np.sin(90 * 2 * np.pi * x)

ws = CreateWorkspace(x,y)

def DFT(x):
    """
    Compute the discrete Fourier Transform of the 1D array x
    :param x: (array)
    """

    N = x.size
    n = np.arange(N)
    k = n.reshape((N, 1))
    e = np.exp(-2j * np.pi * k * n / N)
    return np.dot(e, x)
    

ft = DFT(y)

np_fft = np.fft.fft(y)

mantid = FFT(ws)
FT = CreateWorkspace(mantid.readX(0), ft)
num = CreateWorkspace(mantid.readX(0), np_fft)

def y_data(y):
    norm = np.sqrt(np.max(y)*np.max(y))
    print(norm)
    return y/norm

plt.plot(mantid.readX(3), y_data(mantid.readY(3)), label="Mantid")
plt.plot(FT.readX(0),y_data(FT.readY(0)), label="discrete FT", linestyle="-")
plt.plot(num.readX(0), y_data(num.readY(0)), label="numpy FFT", linestyle="--")
plt.xlim(0,120)
plt.legend()
plt.show()
```

### PR DESCRIPTION
**Pull request by AnthonyLim23**
**Description of work.**
The think that the reason for the complaints about FFT's was because the default values were not helpful. 

I have made the FFT pure real by default and hidden the auto shift option. This is technically a regression in functionality. However, I do not think the shift was being set manually by users and I have not found an example where you would want to set it manually. I have just hidden it for now, so we can put it back in if the users want it.

**To test:**

Open frequency domain analysis
Load EMU 113083
Go to the transform tab
Click calculate - you should get a nice sharp peak around 20 Gauss
Tick the imaginary option and try a few different imaginary workspaces, when you press calculate the FFT should change
The imaginary workspace selector should only be visible when the imaginary option is ticked

Fixes #31150 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Harrietbrown** [comment]
I ran a couple of the scripts in the associated issues and the missmatch between our fft and numpy is still there.

**Comment by AnthonyLim23** [comment]
I found a few errors in the scripts I wrote. For example the first one, should use `np.imag` on the output from numpy, otherwise its plotting the real part. 

The other thing is that we need to use AutoShift as the data is not symmetric on 0. 

Which scripts are you getting a mismatch on?

**Comment by Harrietbrown** [comment]
this: https://github.com/mantidproject/mantid/issues/31150#issue-859855172
and this: https://github.com/mantidproject/mantid/issues/31150#issuecomment-823315274

**Comment by AnthonyLim23** [comment]
the first one should be (its an odd function so the real part is small and we can ignore it)
```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 0.5, 500)
y = np.sin(40 * 2 * np.pi * x) + 0.5 * np.sin(90 * 2 * np.pi * x)

ws = CreateWorkspace(x,y)

def DFT(x):
    """
    Compute the discrete Fourier Transform of the 1D array x
    :param x: (array)
    """

    N = x.size
    n = np.arange(N)
    k = n.reshape((N, 1))
    e = np.exp(-2j * np.pi * k * n / N)
    return np.dot(e, x)
    

ft = DFT(y)

np_fft = np.fft.fft(y)

mantid = FFT(ws, AutoShift=True)
FT = CreateWorkspace(mantid.readX(0), np.imag(ft))
num = CreateWorkspace(mantid.readX(0), np.imag(np_fft))

def y_data(y):
    norm = np.sqrt(np.max(y)*np.max(y))
    print(norm)
    return y/norm

plt.plot(mantid.readX(4), y_data(mantid.readY(4)), label="Mantid")
plt.plot(FT.readX(0),y_data(FT.readY(0)), label="discrete FT", linestyle="-")
plt.plot(num.readX(0), y_data(num.readY(0)), label="numpy FFT", linestyle="--")
plt.xlim(0,120)
plt.legend()
plt.show()
```

**Comment by AnthonyLim23** [comment]
for the second one, the function should be
```
def doMantidFFT(x,y):
    ws = CreateWorkspace(x,y)
    wsFFT = FFT(InputWorkspace='ws', OutputWorkspace='wsFFT', Transform="Forward", AutoShift=True)
    scale = max(wsFFT.readY(2))
    return wsFFT.readX(2), wsFFT.readY(2)/scale, \
        wsFFT.readY(0)/scale, wsFFT.readY(1)/scale 
```

**Review by Harrietbrown — APPROVED** [review]
That seems to be all in order, good job I recall there had been issues with that for a while now.

**Pull request merged**
