### PR TITLE
Indirect - Absorption Corrections - Calculate Monte Carlo Absorption Corrections Interface

### LINKED ISSUE #20458: Indirect - Absorption Corrections - Modify Absorption interface to use CalculateMonteCarloAbsorption
The  Absorption interface currently uses the old Indirect Absorption Correction algorithms (IndirectSHAPEAbsorption).

This interface needs to be updated to use the new, generalised algorithm - CalculateMonteCarloAbsorption.

### PR DESCRIPTION
**Pull request by brandonhewer**
The Absorption Corrections interface, currently uses and is designed for the old absorption correction algorithms. This PR replaces this interface with a Calculate Monte Carlo Absorption interface, which uses the new CalculateMonteCarloAbsorption algorithm. This interface will only calculate and not apply the corrections.

PR #20373 must be merged before this one.

**To test:**
1. Navigate to Interfaces > Indirect > Corrections > Calculate Monte Carlo Absorptions.
2. Supply the sample field with a reduced (\*\_red) file; test files provided below.
3. Supply the container field with a reduced (\*\_red) file; test files provided below.
4. Fill in the remaining fields with one of the following set of properties:
    - **FlatPlate**
        - _BeamHeight_: 3.5
        - _BeamWidth_: 4.0
        - _EventsPerPoint_: 200
        - _SampleChemicalFormula_: H2-0
        - _SampleDensityType_: Mass Density
        - _SampleDensity_: 1.0
        - _ContainerChemicalFormula_: Al
        - _ContainerDensityType_: Mass Density
        - _ContainerDensity_: 1.0
        - _Height_: 2.0
        - _SampleWidth_: 2.0
        - _SampleThickness_: 2.0
        - _ContainerFrontThickness_: 1.5
        - _ContainerBackThickness_: 1.5
    - **Cylinder**
        - _BeamHeight_: 3.5
        - _BeamWidth_: 4.0
        - _EventsPerPoint_: 200
        - _SampleChemicalFormula_: H2-0
        - _SampleDensityType_: Mass Density
        - _SampleDensity_: 1.0
        - _ContainerChemicalFormula_: Al
        - _ContainerDensityType_: Mass Density
        - _ContainerDensity_: 1.0
        - _Height_: 2.0
        - _SampleRadius_: 0.5
        - _ContainerInnerRadius_: 1.0
        - _ContainerOuterRadius_: 2.0
    - **Annulus**
        - _BeamHeight_: 3.5
        - _BeamWidth_: 4.0
        - _EventsPerPoint_: 200
        - _SampleChemicalFormula_: H2-0
        - _SampleDensityType_: Mass Density
        - _SampleDensity_: 1.0
        - _ContainerChemicalFormula_: Al
        - _ContainerDensityType_: Mass Density
        - _ContainerDensity_: 1.0
        - _Height_: 2.0
        - _SampleInnerRadius_: 1.2
        - _SampleOuterRadius_: 1.8
        - _ContainerInnerRadius_: 1.0
        - _ContainerOuterRadius_: 2.0
5. Run the algorithm and ensure an \*\_acc and \*\_ass workspace are created and grouped in a WorkspaceGroup.

**Test files:**
[test-files.zip](https://github.com/mantidproject/mantid/files/1305819/test-files.zip)

Fixes #20458. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
@gvardany You assigned this PR to yourself to test 11 days ago, could you test it ASAP, or release it to the pool for someone else to pick up.

**Comment by gvardany** [comment]
@NickDraper I have unassigned myself. The thing is that this depends on PR #20373, that I have been reviewing, which is not finalised yet.

**Comment by soininen** [comment]
@brandonhewer The supplied test data don't contain `_red.nxs` files. Should I just rename them or perform a reduction step before the absorption calculation?

**Comment by brandonhewer** [comment]
@soininen This is a mistake on my behalf - the sample file is the reduced file and the container is the resolution file.

**Comment by soininen** [comment]
I get the following output:
```
Invalid value for Height: Please enter a non-zero number for height
Error in execution of algorithm CalculateMonteCarloAbsorption
Some invalid Properties found
  at line 269 in '/home/cs/soininen/Sources/mantid/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/CalculateMonteCarloAbsorption.py'
Got error from algorithm "CalculateMonteCarloAbsorption"
Stopping batch algorithm because of execution error
```
when running the calculation with the following setup:
indirect-calculate-monte-carlo-failing-setup

**Comment by SpencerHowells** [comment]
@brandonhewer @soininen Do we have a number format problem? The screen shot shows a value  1,00 when we Brits use 1.00!

**Comment by soininen** [comment]
@SpencerHowells I did run the interface successfully with flat plate sample shape so I don't think it is about locales.

**Comment by SpencerHowells** [comment]
@soininen What happens with Annulus option? The same value should be used for all 3 options.

**Comment by SpencerHowells** [comment]
@soininen Oops! Should have said Cylinder.

**Comment by soininen** [comment]
@SpencerHowells Cylinder works fine, as well.

**Comment by soininen** [comment]
With 'Cylinder' as shape, and no container given, the 'Container Outer Radius' field is still enabled. I think it should be disabled just as 'Container inner radius is'

**Comment by soininen** [comment]
I'll be out-of-office until Wednesday next week. If the review needs to be finished before that, feel free to unassign me.

**Comment by NickDraper** [comment]
I've unassigned Antti so someone else can have a look at this one.

**Comment by NickDraper** [comment]
For Cylinder:
1. I Think somewhere the container inner radius is not wired up correctly - I had the text but at 1 but the Algorithm was given 2.
image
CalculateMonteCarloAbsorption started
Algorithm: CalculateMonteCarloAbsorption v1
Execution Date: 2017-Oct-02 14:46:03
Execution Duration: -1 seconds
Parameters:
  Name: SampleWorkspace, Value: sample, Default?: No, Direction: Input
  Name: SampleChemicalFormula, Value: H2-O, Default?: No, Direction: Input
  Name: SampleDensityType, Value: Mass Density, Default?: Yes, Direction: Input
  Name: SampleDensity, Value: 0.10000000000000001, Default?: No, Direction: Input
  Name: BeamHeight, Value: 3.5, Default?: No, Direction: Input
  Name: BeamWidth, Value: 4.0000000000000027, Default?: No, Direction: Input
  Name: NumberOfWavelengthPoints, Value: 10, Default?: Yes, Direction: Input
  Name: EventsPerPoint, Value: 200, Default?: No, Direction: Input
  Name: Interpolation, Value: Linear, Default?: Yes, Direction: Input
  Name: ContainerWorkspace, Value: container, Default?: No, Direction: Input
  Name: ContainerChemicalFormula, Value: Al, Default?: No, Direction: Input
  Name: ContainerDensityType, Value: Mass Density, Default?: Yes, Direction: Input
  Name: ContainerDensity, Value: 0.10000000000000001, Default?: No, Direction: Input
  Name: Shape, Value: Cylinder, Default?: No, Direction: Input
  Name: Height, Value: 0, Default?: Yes, Direction: Input
  Name: SampleWidth, Value: 0, Default?: Yes, Direction: Input
  Name: SampleThickness, Value: 0, Default?: Yes, Direction: Input
  Name: SampleCenter, Value: 0, Default?: Yes, Direction: Input
  Name: SampleAngle, Value: 0, Default?: Yes, Direction: Input
  Name: SampleRadius, Value: 0.5, Default?: No, Direction: Input
  Name: SampleInnerRadius, Value: 0, Default?: Yes, Direction: Input
  Name: SampleOuterRadius, Value: 0, Default?: Yes, Direction: Input
  Name: ContainerFrontThickness, Value: 0, Default?: Yes, Direction: Input
  Name: ContainerBackThickness, Value: 0, Default?: Yes, Direction: Input
  Name: ContainerInnerRadius, Value: 2, Default?: No, Direction: Input
  Name: ContainerOuterRadius, Value: 2, Default?: No, Direction: Input
  Name: CorrectionsWorkspace, Value: sample_Cylinder_Corrections, Default?: No, Direction: Output
Input X-unit is DeltaE

**Comment by NickDraper** [comment]
Annulus:

1. Same problem for ContainerInnerRadius, it seems to get the value of ContainerOuterRadius.
image

**Comment by NickDraper** [comment]
works for flat plate

**Review by NickDraper — CHANGES_REQUESTED** [review]
Some mapping problems for properties in Cylinder and Annulus

**Comment by NickDraper** [comment]
Output options:

1. Plot result - Leads to an unhandled exception

```
Unexpected exception: Unknown property search object CanWorkspace
```

**Comment by NickDraper** [comment]
Py button:

1. Does not work until after a successful "Run", but it is still enabled and active

**Review by NickDraper — CHANGES_REQUESTED** [review]
resolved the property mapping problems, Still have an unhanded exception, and a button that needs to be disabled until after a successful run.

**Comment by NickDraper** [comment]
Bug:

Steps:
1. run a failure on an empty form, So enter the sample and container files, select Clyinder and hit run with no details added
1. This fails validataion - good, and them fill in the form properly
1. This gives you the following error, it seems that height is not passed on for some reason.


image
Algorithm: CalculateMonteCarloAbsorption v1
Execution Date: 2017-Oct-02 15:27:49
Execution Duration: -1 seconds
Parameters:
  Name: SampleWorkspace, Value: sample, Default?: No, Direction: Input
  Name: SampleChemicalFormula, Value: H2-O, Default?: No, Direction: Input
  Name: SampleDensityType, Value: Mass Density, Default?: Yes, Direction: Input
  Name: SampleDensity, Value: 0.10000000000000001, Default?: No, Direction: Input
  Name: BeamHeight, Value: 1, Default?: Yes, Direction: Input
  Name: BeamWidth, Value: 1, Default?: Yes, Direction: Input
  Name: NumberOfWavelengthPoints, Value: 10, Default?: Yes, Direction: Input
  Name: EventsPerPoint, Value: 5000, Default?: No, Direction: Input
  Name: Interpolation, Value: Linear, Default?: Yes, Direction: Input
  Name: ContainerWorkspace, Value: container, Default?: No, Direction: Input
  Name: ContainerChemicalFormula, Value: Al, Default?: No, Direction: Input
  Name: ContainerDensityType, Value: Mass Density, Default?: Yes, Direction: Input
  Name: ContainerDensity, Value: 0.10000000000000001, Default?: No, Direction: Input
  Name: Shape, Value: Cylinder, Default?: No, Direction: Input
  Name: Height, Value: 0, Default?: Yes, Direction: Input
  Name: SampleWidth, Value: 0, Default?: Yes, Direction: Input
  Name: SampleThickness, Value: 0, Default?: Yes, Direction: Input
  Name: SampleCenter, Value: 0, Default?: Yes, Direction: Input
  Name: SampleAngle, Value: 0, Default?: Yes, Direction: Input
  Name: SampleRadius, Value: 1, Default?: No, Direction: Input
  Name: SampleInnerRadius, Value: 0, Default?: Yes, Direction: Input
  Name: SampleOuterRadius, Value: 0, Default?: Yes, Direction: Input
  Name: ContainerFrontThickness, Value: 0, Default?: Yes, Direction: Input
  Name: ContainerBackThickness, Value: 0, Default?: Yes, Direction: Input
  Name: ContainerInnerRadius, Value: 1.1000000000000001, Default?: No, Direction: Input
  Name: ContainerOuterRadius, Value: 2, Default?: No, Direction: Input
  Name: CorrectionsWorkspace, Value: sample_Cylinder_Corrections, Default?: No, Direction: Output
Input X-unit is DeltaE
Invalid value for Height: Please enter a non-zero number for height

**Comment by NickDraper** [comment]
Usage:

1. Tab order is wrong for all of the shape options

**Comment by NickDraper** [comment]
Input:

1. Workspace options for both sample and contianer do not list any workspaces. ?is it expecting _red after the workspace name?

**Comment by NickDraper** [comment]
Usage:

When you unselect container the following options should be disabled and are not:

Cylinder
- Container Outer Radius

**Comment by NickDraper** [comment]
@ElliotAOram Has kindly stepped into the developer role on this one as @brandonhewer is busy with other PRs

**Comment by ElliotAOram** [comment]
To Do:
* [ ] Workspaces not correctly identified
* [ ] Incorrect Tab order
* [ ] Disable `Container Outer Radius` option
* [ ] Height not propagated to algorithm after failed valiadtion
* [ ] Plot result gives exception

**Comment by brandonhewer** [comment]
@ElliotAOram The fix for the Flake8 Warning requires simply merging the `20184_calculate_mc_absorption` branch. The issue comes from a recently invalidated import in the CalculateMonteCarloAbsorption algorithm.

**Review by NickDraper — CHANGES_REQUESTED** [review]
Tab order: still a mess for cylinder and annulus (starting from beam width box)
Also some weird ordering from input file boxes to outer form buttons

**Comment by NickDraper** [comment]
everything else ok

**Comment by NickDraper** [comment]
Solved the Cylinder and Annlus tabbing issues

**GATEKEEPER:
PR #20373 must be merged before this one.**

**Review by NickDraper — APPROVED** [review]

**Comment by brandonhewer** [comment]
Merge conflicts arrived on this PR and have been fixed.

**Comment by NickDraper** [comment]
windows failure is unrealated (PhaseQuad)

**Pull request merged**
