### PR TITLE
Fix Beam Centre Only Working on LAB

### LINKED ISSUE #28122: SANS Beam Centre Finder only working on LAB
**Original reporter:** ISIS/Steve

### Expected behavior
- The main-detector and HAB selection should be respected and iterate over the respective banks

### Actual behavior
- Converging on the beam centre on the main-detector then selecting the HAB will result in the same result, without any iterations. This is because it is re-centring the main-detector, not HAB

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**
Fixes the BeamCentreFinder only working on Low Angle Banks. Additionally clarifies in the UI what various tick boxes do.

**Report to:** ISIS/Steve

**To test:**
- Download the ISIS Training Data
- Open the SANS GUI 
- Load the userfile `Maskfile.txt` in the `loqdemo` folder 
- Load the batch file in the `loqdemo` folder
- Hit load
- Switch to beam centre
- Take a quick note of the centres for the HAB and LAB, they should be the same
- Hit run, after it finises only the LAB value should be updated
- Change the bank to HAB, hit run again
- Check the LAB value hasn't changed, but the HAB value has
- Do the checkbox descriptions ("Update...") make sense to you?

Fixes #28122 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Harrietbrown** [comment]
What is the beam centre core? I do not see it in the been center tab.

**Comment by DavidFair** [comment]
It's the algorithm beam centre runs multiple times to process a workspace, then split it into 4 quarters on each iteration

The call can be seen in `BeamCentreFinder.py:328`

**Comment by Harrietbrown** [comment]
Your test instructions say "Switch the beam centre core" I mean where in the gui is it.

**Comment by DavidFair** [comment]
🤦‍♂ sorry that's completely my fault as I was working on the core so instinctively wrote that in the testing instructions

I'll update the instructions now

**Comment by DavidFair** [comment]
I'd hang off doing a code review of this PR till #28141 is merged, since I'm going to have to rebase

**Review by Harrietbrown — CHANGES_REQUESTED** [review]
The options on Detector are `main-detector` and `Hab`, is `main-detector` the same as LAB?
Hab should also be HAB like in the checkbox.

**Comment by DavidFair** [comment]
> The options on Detector are main-detector and Hab, is main-detector the same as LAB?

Unfortunately this is an historical difference between LOQ and other instruments, we are gradually moving towards a cohesive naming scheme. However, which name is in the air so we can't fix it at this point.

> Hab should also be HAB like in the checkbox.

This comes from an existing enum and is tied (for implementation reasons) to the way they write it in their user files. I could fix it by converting case as we convert to/from the enum. 
However, I have concerns this could regress for a minor aesthetic since `HAB` != `Hab` as far as the enum is concerned.

For these reasons I would like to, but can't really fix these this close to the release unless you strongly disagree? However, thanks for pointing them out.

**Comment by DavidFair** [comment]
No code changes, simply a rebase from `master` -> `release-next` to fix release notes

**Review by Harrietbrown — APPROVED** [review]
With the dropdown names still not beeing concreate on the best way of writing them (`main-detector` vs `LAB` and `Hab` vs `HAB`) and us being so close to release it will be acceptable to leave those for now as the initial purpose of the PR is fufilled.  Good job

**Pull request merged**
