### PR TITLE
Remove SANS Calculate Transmission Wrkflw

### LINKED ISSUE #26957: Remove SANS ConvertToQ Workflow Algorithm

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**
Converts SANSCalculateTransmission into a Python class as part of the
ISIS SANS history fix

**To test:**

Run the system and unit tests as following
- ctest -R SANS
- systemtest -R SANS

Process some SANS data:
- Download the ISIS training data from the project site
- Open the ISIS SANS GUI
- Open the LOQ folder and select the Mask file as the user file
- Open the batch file and select the CSV
- Hit process all

Fixes #26957  .

*This does not require release notes* because this is part of an epic #26960 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by giovannidisiena** [comment]
@DavidFair, I got the following error messages when trying to run tests.

`The following tests FAILED: 
        760 - python.WorkflowAlgorithms.SANSILLIntegrationTest.SANSILLIntegrationTest (Failed)`

`systemtest: command not found`

**Comment by giovannidisiena** [comment]
> @DavidFair, I got the following error messages when trying to run tests.
> 
> `The following tests FAILED: 760 - python.WorkflowAlgorithms.SANSILLIntegrationTest.SANSILLIntegrationTest (Failed)`
> 
> `systemtest: command not found`

Same here

**Comment by giovannidisiena** [comment]
Should be requested to merge into `26960_Fix_SANS_Workflow_history`

**Comment by giovannidisiena** [comment]
I get this error when running ctest

```The following tests FAILED:
	760 - python.WorkflowAlgorithms.SANSILLIntegrationTest.SANSILLIntegrationTest (Failed)```

**Comment by DavidFair** [comment]
Could you re-run with `ctest -R python.WorkflowAlgorithms.SANSILLIntegrationTest.SANSILLIntegrationTest -VV`

I find that this test sometimes gets flaky locally with file not function errors?

**Comment by giovannidisiena** [comment]
Now have the following: 
```
ValueError: Invalid value for property Run (list of str lists) from string "010569": Unable to find file matching the string "LOQ10569", even after appending suggested file extensions.
```

**Comment by DavidFair** [comment]
Connor has opened an issue for this #27022 , could you ask him how he resolved it offline?

**Review by giovannidisiena — APPROVED** [review]
All now passes :+1:

**Pull request merged**
