### PR TITLE
Bug fixes for new Muon GUI

### LINKED ISSUE #25015: New muon GUI bugs
1. If you load multi period data and then click in and out of the various period boxes, without changing anything, it will reload. Could we make it check if it has changed?

2. We can edit the alpha box from home. Should we disable this?

3. The pre processing box on the home tab should be called Instrument

### PR DESCRIPTION
**Pull request by Matthew-Andrew**
**Description of work.**

This corrects the bugs from #25015 

**Report to:** Anthony 

**To test:**

* In mantidplot open the Frequency Domain Analysis GUI
* Select HIFI as the instrument and load run 84447 (This should be in the ISIS data archive, if not at ISIS slack me and I can send you some appropriate data.)
* Check that on the home tab the first grouping box is called instrument.
* Check that if you select long from the combo-box the alpha text edit is disabled.
* Try changeing the period boxes whilst keeping an eye on the results log. Check that a recalculation occurs only if the values have changed. 

Fixes #25015  

*This does not require release notes* because this fixes issues users have never seen as interface is new.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by TTitcombe — COMMENTED** [review]
Works as expected during testing - "Alpha" text book appears and is disabled when selecting `long` (I assume it's intentional for alpha to disappear if you change to `fwd` or `bwd`?). Does not recalculate if you retype the same periods.

A couple of things I noticed when testing which are possibly already known/are outside the score of this PR anyway:
1. Clicking and un-clicking `co-add` seems to raise an uncaught runtime error
2. In the first period box, type "3" and let that calculate. Then type "36" and let it calculate. You will see two consecutive error boxes and - `The following periods are invalid: 36` and then `Some invalid Properties found`. If you type "36" again in the now blank box, you will only see the first error box.

**Comment by Mantid-Matthew** [comment]
These sound like they should be fixed here, I'll have a look now.

**Comment by Mantid-Matthew** [comment]
I have dealt with point 2 above. I could not exactly replicate 1 but I did see strange behaviour to do with threading when multiple things were changed at once. I have therefore updated the GUI enabling/disabling signals.

Have also corrected an issue where the GUI was appearing in workbench despite not being Qt 5 compatable.

**Review by TTitcombe — APPROVED** [review]
This PR fixes a few bugs in the Muon gui :+1: Code changes look good

**Pull request merged**
