### PR TITLE
Introduce Pawley function and algorithm for using it

### PR DESCRIPTION
**Pull request by MichaelWedel**
This fixes [#11043](http://trac.mantidproject.org/mantid/ticket/11043).

### CODE REVIEW

**Comment by MichaelWedel** [comment]
Jenkins retest this please

**Comment by MichaelWedel** [comment]
Jenkins retest this please

**Comment by MichaelWedel** [comment]
**Testing information**
Code review. There is a [design document](https://github.com/mantidproject/documents/blob/9e0539b5d8c93614de17a7e252d078414a9db861/Design/Design-PawleyFunction.md) that explains the implementation a bit, especially the "Update" section.

In the unit tests for PawleyFunction and PawleyFit there are some basic examples for what the algorithm can do. In the documentation for PawleyFit there is a usage example. The algorithm should work on any MatrixWorkspace which contains a spectrum in terms of d-spacing or momentum transfer - if you know a good example from a powder diffraction beamline that would be something to try.

**Comment by MichaelWedel** [comment]
The Test `SystemTests.ISISDirectInelastic.MERLINReduction` failed, but it don't know how that could be caused by these changes. I tried running it locally, but I don't have 16 GB of free memory to run it. I will try again on the build server.

**Comment by MichaelWedel** [comment]
Jenkins retest this please

**Comment by MichaelWedel** [comment]
The same test failed again and it failed on other pull request builds as well, so it seems that this has nothing to do with the changes.

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by wdzhou** [comment]
In testing script, you used a property named 'MillerIndicies' to input peaks of algorithm PawleyFit.  But it does not exist in the final code.  Did you removed it later?

**Comment by MichaelWedel** [comment]
Yes, sorry for not updating the script, I forgot about that. It turned out that some reasonable guesses for peak height/fwhm were required, so the list of HKLs was not enough to provide in some cases. That's why I made the TableWorkspace mandatory and removed the MillerIndices property.

So in case one does not want to use the POLDI algorithms, a TableWorkspace would have to be obtained some other way, I guess it could be done through Python.

**Comment by wdzhou** [comment]
The structure of the codes is clear.  All tests are passed.  Failed pull request is due to other irrelevant reason.  

I tried to fit the attached silicon data and the result is very good.  

The ticket is then closed.

**Comment by MichaelWedel** [comment]
I've thought about running `PoldiPeakSearch` inside the algorithm when only calculated peaks are supplied, but the algorithm also has some parameters and the default ones don't always work, so I think for now it's better to keep this out of the algorithm.

**Comment by wdzhou** [comment]
Everything looks find.  Ticket is thus closed.

**Pull request merged**
