### PR TITLE
Exclude and IgnoreInvalidData Properties for PlotPeakByLogValue and QENSFitSequential

### LINKED ISSUE #22387: Indirect/Fitting - 'Exclude' not available in PlotPeakByLogValue and QENSFitSequential
PlotPeakByLogValue and as a result, QENSFitSequential, do not provide an option 'Exclude' for excluding a region from the fit.

This value of a new 'Exclude' property should be passed to the Exclude property of the 'Fit' algorithm.

### PR DESCRIPTION
**Pull request by brandonhewer**
The PlotPeakByLogValue (and as a result the QENSFitSequential algorithm) does not have an 'Exclude' or 'IgnoreInvalidData' property for excluding a region from the fit and ignoring NaNs, 0s and Infinite values.

This PR adds the 'Exclude' and 'IgnoreInvalidData' properties to the PlotPeakByLogValue algorithm.

**To test:**
1. Run the PlotPeakByLogValue unit tests and ensure they pass.

Fixes #22387. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by josephframsay — CHANGES_REQUESTED** [review]
Nice changes, and tests pass fine. Do we also need to include the change in the test for QENSFitSequential?

Also for forwarding `Exclude` and `IgnoreInvalidData`, could you use `Property.setValueFromProperty`? I don't really know if this would be advantageous or not - I suppose it would maybe make it make it a bit clearer that the property is just being forwarded, and possibly save the parent algorithm having to extract the value from the property?

Might it also be worth declaring these with `copyProperty` a la [this](https://github.com/mantidproject/mantid/blob/master/Framework/WorkflowAlgorithms/src/LoadEventAndCompress.cpp#L55), so that if they ever change in `Fit`, the change applies to your algorithm also?

**Comment by brandonhewer** [comment]
@josephframsay 
I'm not sure setValueFromProperty makes sense from the context of a PropertyManager (since Property objects are inaccessible -- encapsulated).

The copyProperty may be a reasonable option to add to QENSFitSequential, however will not be possible to do within PlotPeakByLogValue for the Exclude property. This is because this property is actually created dynamically after the InputWorkspace property is set and not at the point the init() method is called.

**Comment by josephframsay** [comment]
@brandonhewer ah yes, right you are. in that case, this looks good to go

**Review by josephframsay — APPROVED** [review]

**Comment by josephframsay** [comment]
@brandonhewer ah yes, right you are. in that case, this looks good to go

**Pull request merged**
