### PR TITLE
Pin jemalloc to v5.2.0 for install package

### PR DESCRIPTION
**Pull request by peterfpeterson**
This makes the `mantid` package installer match the version of jemalloc that the developers are using.

Refs #36220 .

#### Further detail of work

The main change is to pin the version of jemalloc for the package to v5.2.0. It is unclear what is wrong with the newer versions, but comparing the [recipe from v5.2.0](https://github.com/conda-forge/jemalloc-feedstock/blob/54b2b91d8c5ac4df203d8c6d9f9e322f6aa9bb82/recipe/meta.yaml) and [recipe from v5.3.0](https://github.com/conda-forge/jemalloc-feedstock/blob/5e0cb55e668089c6ce730e449536585dd98752b8/recipe/meta.yaml) one will immediately discover that v5.3.0 reworked the packages so there is now a `jemalloc` package `libjemalloc` package where v5.2.0 only has `jemalloc` package. More investigation will need to be done to figure out how to move forward from v5.2.0.

The oddity is that both v5.2.0 and v5.3.0 work on rhel7, but only v5.2.0 works on rocky8 and rhel9.

There is some extra cleanup of the developer dependencies so they can more easily be compared using `diff` (sorting), removing duplicate dependencies (`conda-wrappers` twice in windows), removing unused osx dependency (`jemalloc` is not runtime for mac).

Bonus information: The [abi compatibility chart for jemalloc](https://abi-laboratory.pro/index.php?view=timeline&l=jemalloc) doesn't go all the way to v5.3.0.

### To test:

Install the built linux package on newer rhel and see that it can start and show the instrument view with opengl.

*This does not require release notes* because it is fixing a bug within the release cycle discovered when moving from rhel7.

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by sf1919** [comment]
Can we point this at `release-next`?

**Comment by peterfpeterson** [comment]
[Build 1860](https://builds.mantidproject.org/job/pull_requests-conda-packaging/1860/) is resubmitted against `release-next`

**Review by thomashampson — CHANGES_REQUESTED** [review]
There's a small typo that will probably affect macOS packaging

**Review by thomashampson — APPROVED** [review]
I'm happy for this go in to resolve issues on rhel9, and work on a rocky8 fix separately

**Pull request merged**
