### PR TITLE
Flake8 issues inelastic direct

### PR DESCRIPTION
**Pull request by ElliotAOram**
Flake8 Warnings have been resolved in the scripts/Inelastic/Direct tab.
In addition, so cleanup and improvement has been made to naming and coding standards were appropriate.

**To test:**

* Review code changes
* Ensure `ISISDirectInelastic` tests pass
* Ensure all Flake8 warnings have been removed from changed files

Resolves part of #20508

**Release Notes** 
*Internal code change - does not need to be added to the Release notes

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by josephframsay** [comment]
I think the way to get rid of [this](http://builds.mantidproject.org/job/pull_requests-flake8/6438/warnings6Result/package.-1117210230/] warning is to just delete to relevant file, after speaking to Sanghamitra and Spencer about it. Would it be OK if I put that change in this PR, as it seems the right place for changes to inelastic stuff?

**Comment by ElliotAOram** [comment]
@josephframsay that's fine with me 👍

**Comment by ElliotAOram** [comment]
@josephframsay actually based on the change you've just added (considering it is fixing flake 8 warnings) it is probably fine to be here

**Comment by josephframsay** [comment]
Oh whoops, I somehow didn't see the change to your comment. I'll put the file back in and just put this with all the miscellaneous stuff if you think that'd be better

**Comment by josephframsay** [comment]
Or not - I'll leave it, then!

**Review by peterfpeterson — APPROVED** [review]
LGTM

**Pull request merged**
