### PR TITLE
Fix PYTHONPATH to xmlrunner on OS X for a clean build

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work**

#19886 removed the internal `xmlrunner` in favour of an external project but it broke the clean OS X build as its `PYTHONPATH` was set differently for the MantidPlot tests and needed updating. This change does that.

The previous pull request passed testing as the `.pyc` files remained and were still importable. The clean build would not have these available.

**To test:**

A proper test would be to run `git clean -fdx` in the repository, build the code & run the MantidPlot tests.

*No issue*

**Release Notes** 

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gvardany** [comment]
After git clean, I get an error on start:
```
Error running init file "/Users/vardanyan/build-mantid-default/bin/mantidplotrc.py"
Previous initialization of Python failed, cannot retry.
```

**Comment by martyngigg** [comment]
Did you rebuild?

**Comment by gvardany** [comment]
Yes, after second start MantidPlot started. Should I run all the tests?

**Comment by martyngigg** [comment]
Cool, thanks. 

Just running `ctest -R MantidPlot` should suffice.

**Review by gvardany — APPROVED** [review]
MantidPlot starts fine, it's tests pass.

**Pull request merged**
