### PR TITLE
Remove unncessary options for TOSCA/TFXA in ISIS Energy Transfer tab

### PR DESCRIPTION
**Pull request by MohamedAlmaki**
### Description of work
This PR removes unnecessary options for TOSCA/TFXA in the ISIS Energy Transfer tab. It has been agreed with the scientists that these options are not relevant to TOSCA/TFXA and should be removed from the UI.

Fixes #34641. 

### To test:
1- Go to Interfaces->Indirect->Data Reduction->ISIS Energy Transfer
2- Change the instrument to TOSCA/TFXA
3- Check if the options are the current ones

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by robertapplin** [comment]
It looks like the "Scale factor by" option is no longer used by any of the instruments. Can we remove this and all references to it from the GUI? I have also checked it is not used for the ILL Energy Transfer tab

**Review by robertapplin — CHANGES_REQUESTED** [review]
Good work here - the relevant options are only shown for relevant instruments. Can the "Plotting options" be hidden for the TFXA and TOSCA instruments?

Do we need release notes, or have these already been added?

**Comment by MohamedAlmaki** [comment]
> It looks like the "Scale factor by" option is no longer used by any of the instruments. Can we remove this and all references to it from the GUI? I have also checked it is not used for the ILL Energy Transfer tab

Ok, I'll remove it

**Comment by MohamedAlmaki** [comment]
> Good work here - the relevant options are only shown for relevant instruments. Can the "Plotting options" be hidden for the TFXA and TOSCA instruments?
> 
> Do we need release notes, or have these already been added?

Spencer said that it is better to keep the "Plotting Options". Ok, I will add release note

**Comment by MohamedAlmaki** [comment]
> > It looks like the "Scale factor by" option is no longer used by any of the instruments. Can we remove this and all references to it from the GUI? I have also checked it is not used for the ILL Energy Transfer tab
> 
> Ok, I'll remove it

@SpencerHowells Do you mean the "Plotting Options" or "Scale By Factor"

**Comment by SpencerHowells** [comment]
@MohamedAlmaki Remove 'Scale by factor'

**Review by robertapplin — APPROVED** [review]
Thanks for the changes, looks good

**Pull request merged**
