### PR TITLE
Remove deprecated algorithms

### LINKED ISSUE #18314: Remove Deprecated algorithms
Remove the following algorithms version

CorrectFlightPaths	1
LoadAscii	1
LoadEventPreNexus	1
LoadLogsForSNSPulsedMagnet	1
Lorentzian1D	1
ProcessDasNexusLog	1
LoadILL	1 -> may already be in pr #18718
SANSDirectBeamScaling	1

### PR DESCRIPTION
**Pull request by NickDraper**
Remove the following deprecated algorithms versions

CorrectFlightPaths	1
LoadAscii	1 (later returned as SaveAscii 1 is still in use)
LoadEventPreNexus	1
LoadLogsForSNSPulsedMagnet	1
Lorentzian1D	1
ProcessDasNexusLog	1
LoadILL	1 
SANSDirectBeamScaling	1

**To test:**

Ensure all unit tests and system tests pass

Fixes #18314.

### RELEASE NOTES

in framework.rst

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
@ianbush,  I was removing the algorithms that were deprecated that we discussed, LoadILL in particular and I have some system tests that use it.


SystemTests.ILLIN4Test.LoadILLIN4Test
SystemTests.ILLIN5Test.LoadILLIN5Test

Are these current or historic?
If they are historic then I could remove them, but not if they are adding any value.

**Comment by ianbush** [comment]
@NickDraper These tests should work fine if they use `LoadILLTOF` instead of `LoadILL`.

**Comment by ianbush** [comment]
This all looks good to me. @NickDraper can you fix the merge conflicts in the release notes?

**Comment by NickDraper** [comment]
merged master, just a release note clash, no need to wait for the builds again

**Comment by ianbush** [comment]
:shipit:

**Pull request merged**
