### PR TITLE
Add importance sampling according to DiscusMultipleScatteringCorrection

### LINKED ISSUE #32208: Add importance sampling on S(Q) to multiple scattering correction
I've recently done some tests of the CalculateMultipleScattering algorithm on S(Q) profiles consisting of spikes (~delta functions) to see if I can reproduce some published results (eg Mayers - A MONTE CARLO EVALUATION OF ANALYTICAL MULTIPLE SCATTERING CORRECTIONS FOR UNPOLARISED NEUTRON SCATTERING AND POLARISATION ANALYSIS DATA). This is part of the current efforts to validate the results on diffraction instruments. The algorithm does reproduce the results but it requires a lot of scenarios (1,000,000+) in order for the features to be visible above the noise of the general background in the output scattering weight.

The Mancinelli paper that describes the algorithm used in CalculateMultipleScattering samples the q values at each scatter using a importance sampling approach ie more q values at the peaks in S(Q). The current code in CalculateMultipleScattering just samples q evenly between 0 and 2k. The importance sampling method should be added to the algorithm to support its used on diffraction instruments where the S(Q) contains sharp peaks.

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

Add importance sampling option to DiscusMultipleScatteringCorrection so that it converges more quickly for situations where S(Q) contains spikes eg diffraction

The previous gaussian interpolation that was used to interpolate the S(Q) distribution has been removed because it didn't work very nicely with the importance sampling. It has been replaced by a more simple "flat" interpolation from the previous point in the distribution. This also removes the need to insist on the S(Q) distribution being >0 at all points and having equally spaced points

**To test:**

The following script calculates a multiple scattering correction that uses an S(Q) profile consisting of a single spike at Q=7. The input workspace has detectors spread over a two theta range 0 to 180 degrees, each spectrum has a single bin centred on wavelength=1 angstrom. The wavelength and the spike position corresponds to a two theta angle of 67.7 degrees.

This should give a multiple scattering correction with a peak at two theta=0 and two theta=2*67.7=135.4 degrees corresponding to two scatters with a smooth U shaped curve in between. The detector with two theta=135.4 degrees is attached to spectrum ~680

If you run the script twice with ImportanceSampling set to True and False you should see that the result with "True" is much cleaner and the peaks at 0 and 135.4 degrees are visible with the U shape in between. If you change the peak width to be x10 narrower the result without importance sampling degenerates further.

I suggest you run it on a release build to save a bit of time.

image

The correction is stored in the Scatter_2 workspace that sits inside a workspace group called MSResults.

```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np
from testhelpers import WorkspaceCreationHelper

test_ws = WorkspaceCreationHelper.create2DWorkspaceWithGeographicalDetectors(1, 900, 0.2, 1)
ws_name = "test"
AnalysisDataService.addOrReplace(ws_name, test_ws)

X=[6.9,7.0,7.1]
Y=[0.,1000,0.]
Sofq=CreateWorkspace(DataX=X,DataY=Y,UnitX="MomentumTransfer")

SetSample(InputWorkspace=test_ws,
          Geometry={'Shape': 'FlatPlate', 'Height': 4.0,
                  'Width': 4.0, 'Thick': 1.0,
                  'Center': [0.,0.,0.]},
          Material={'ChemicalFormula': 'Ni'})

DiscusMultipleScatteringCorrection(InputWorkspace=test_ws, SofqWorkspace=Sofq, OutputWorkspace="MSResults",
                                   NeutronPathsSingle=1, NeutronPathsMultiple=10000, NumberScatterings=2,
                                   ImportanceSampling=True)
```

Fixes #32208.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DavidFair — COMMENTED** [review]
Initial PR review
The readability could be improved for the maths heavy components, but I'm trying to figure out how since it's fundamentally calculating a lot. Since it takes a significant time to follow through what's happening I'm wondering if we can chunk some steps down with intermediate calculations

**Comment by DannyHindson** [comment]
@DavidFair - just back from my week off. Do you have any time to take another look at this PR? No problem if you're busy - I can ask one of the diffraction team to take a look

**Comment by DavidFair** [comment]
I've just got back today too, I can get this review by end of play today no problem

**Review by DavidFair — APPROVED** [review]
Just retested, this still works correctly
LGTM, lets :shipit:

**Comment by DannyHindson** [comment]
@DavidFair - I've just realised that I forgot to push a commit I made against this PR where I addressed your review comments. So from your end it probably appeared as though I ignored your suggestions and then chased you to approve the PR. Sorry about that! I noticed this just now because I'm just starting a new change on the same algorithm. I'll create a new PR for the "lost" changes. They don't have any functional impact but just improve the readability of the code.

**Comment by DavidFair** [comment]
No worries, since you'd just got back from leave and I was just about to go on mine I decided getting it in was more important than absolute correctness. That way you / your users could actually test it in the nightlies...etc.

Thanks for following it up though, I'd completely forgotten about it

**Pull request merged**
