### PR TITLE
Add a checkbox to freeze the rotation

### LINKED ISSUE #30481: Allow the user to freeze the rotation in full 3d mode
In the instrument viewer, in the Full3D projection, the user should be able to freeze the rotation part, that is being only able to translate or zoom in.
 This is useful for the feature added in #30463 , where the user must stay in the z = 0 plan, which is hard to achieve for Mac users.

### PR DESCRIPTION
**Pull request by MathieuTillet**
**Description of work.**

Add a checkbox to freeze the rotation in the instrument view, when in Full3D. This is useful for the feature added in #30343 , where the user can draw sectors for integration, but those sectors must be drawn with the viewport in the z = 0 plane, which can be difficult to achieve for mac users.
Thus checking this box makes left click behave like right click, ie manage the translation.

**To test:**
- Load a file, open the instrument view, and check that when the checkbox is unticked, it behaves as usual, whereas when it is ticked, the left-click translate the view.
- Save to project with the view opened and the checkbox ticked, and check the checkbox is correctly ticked when the project is loaded.

Fixes #30481 .

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by darominski — COMMENTED** [review]
The code is good and works as promised. I checked with a couple of different instruments and whether the checked box is preserved through a save-load cycle of a project. The new feature works well. Could you just fix the conflict in the docs?

**Review by darominski — DISMISSED** [review]
Thanks for fixing the conflict. This is good to go now.

**Review by gvardany — CHANGES_REQUESTED** [review]
There is an issue with this, try:
1. Freeze the rotation > works
2. Change the projection to something else than 3D
3. Change back to 3D, the checkbox is still checked, but you can rotate now

**Review by darominski — APPROVED** [review]
Thank you @gvardany for spotting the issue with changing view and the checkbox remaining checked while no longer taking effect and @MathieuTillet  for fixing it. Now, each time one changes the view to Full3D the checkbox is unset and the feature works as expected.

**Review by gvardany — APPROVED** [review]

**Pull request merged**
