### PR TITLE
ContainerSubtraction scaleX for off centre peaks

### LINKED ISSUE #13993: ContainerSubtraction ScaleX and Minus for Shifted peaks
Alexander O'Malley reports:

> When subtracting 'empty' (the empty zeolite) from 'loaded' (dosed with ammonia) there is a negative  peak in the middle of the signal.

> This is not because 'empty' is more intense that 'loaded', but because there is a very small shift in the  peak center. which you can see when you plot groups on top of each other (group 5 shows this quite  well). The step I took was to use ScaleX (adding function to shift the peak along the X axis), and then subtract the shifted peak. however this does not appear to work. Upon using minus, it seems like it takes on the old values of the X axis, so the subtracted graph looks identical.

> This is illustrated best when subtracting the same peak from itself.. which should leave a very 
negative peak when shifted by 0.1 meV. But just gives a flat line, suggesting that something in the 
algorithm only uses one X axis. (even if i save a file and load it in as a new file the minus function still  ignores it..)

> Is there anything possible to change so I can subtract a shifted peak? 

This can be fixed with the following: 
* [x] Add a shift option to the ContainerSubtraction interface.
* [x] Scale the container in the x axis with the shift value (using ScaleX algorithm) 
* [x] Rebin the container to have the same number of bins as the Sample (using RebinToWorkspace algorithm) 
* [x] Then run the container subtraction algorithm with the adapted container workspace

### PR DESCRIPTION
**Pull request by ElliotAOram**
Fixes #13993

An additional Container shift option has been added to the interface to allow for containers that do not match the peak of the sample to be shifted into position.
# To Test
- Open ContainerSubtraction (Interfaces > Indirect > Corrections > ContainerSubtraction)
- irs26176_graphite002_red.nxs for the sample
- irs26174_graphite002_red.nxs for the container
  - Please get these files from `\\olympic\babylon5\Public\ElliotOram\Corrections\ContainerSubtraction\-0.2 shifted can` as the can has already been shifted -0.2 in x for testing
- Check the container (irs26174) is off zero by -0.2 
  - plot one of the spectrum and check the peak centre = -0.2
- Check the `Shift x-values of container by adding` option and set the shift to `+0.20`
- Click Run, you may be prompted with a warning saying the binning does not match and asking if you would like to rebin, click `yes`
  Ensure that the plot now show the aligned Container and Sample with the Subtraction and it looks correct.

### CODE REVIEW

**Comment by shahrozahmed1** [comment]
Unfortunately when I click `Run` after the files have been loaded, the following information box is displayed `Indirect Corrections : Unable to apply corrections. See Results Log for more detials` 

Followed by this error message on Results Log;
```
Minus started (child)
Error in execution of algorithm Minus:
X arrays must match when performing this operation on a 2D workspaces.
Error in execution of algorithm ApplyPaalmanPingsCorrection
X arrays must match when performing this operation on a 2D workspaces.
  at line 89 in 'C:/MantidInstall/plugins/python/algorithms\WorkflowAlgorithms\ApplyPaalmanPingsCorrection.py'
  caused by line 254 in 'C:/MantidInstall/plugins/python/algorithms\WorkflowAlgorithms\ApplyPaalmanPingsCorrection.py'
  caused by line 756 in 'C:/MantidInstall/bin\mantid\simpleapi.py'
Got error from algorithm "ApplyPaalmanPingsCorrection"
Stopping batch algorithm because of execution error
```

**Comment by ElliotAOram** [comment]
@shahrozahmed1 Thanks for letting me know, I'll look into it.

**Comment by SpencerHowells** [comment]
MUST do RebinToWorkspace sample before Minus

**Comment by SpencerHowells** [comment]
When testing, plot the high spectra which have a sharp elastic peak at the origin and is more visible.

**Comment by shahrozahmed1** [comment]
The `Container Subtraction` tab under `Indirect Correction` GUI does what it says, also tested it with `high spectra`. No more errors messages displayed when changing around the `Shift x-values of container by adding ... `. Hence this can be merged.

**Pull request merged**
