### PR TITLE
SmoothMD algorithm

### PR DESCRIPTION
**Pull request by OwenArnold**
See [design document​](https://github.com/mantidproject/documents/blob/master/Design/VATES/MantidHorace/syntax-proposal.md) for the requirements for this new Algorithm.

Trac ticket [11393](http://trac.mantidproject.org/mantid/ticket/11393)

**Tester**: The unit tests and performance tests should give you confidence that this is working. Please check out the usage example too.

### CODE REVIEW

**Comment by OwenArnold** [comment]
Jenkins test this please

**Comment by AndreiSavici** [comment]
Is it possible to add a second input workspace (optional) as the weight? One should not create smoothed points where the weight is 0. For example, weight is:
1-0-0
1-1-0
1-1-1
Data should not haveany non-zero elements in the upper right corner, and neither should the output result.

**Comment by OwenArnold** [comment]
Jenkins retest this please

**Comment by AndreiSavici** [comment]
Jenkins test this please

**Comment by AndreiSavici** [comment]
There are still several cases of MDEvents instead of MantidDataObjects. Look for MDEvents in your code, in the include sections and in "using namespace Mantid::MDEvents;"

**Comment by OwenArnold** [comment]
Jenkins retest this please

**Comment by OwenArnold** [comment]
Jenkins retest this please

**Pull request merged**
