### PR TITLE
Connect grouping options for OSIRIS Diffonly Diffraction reduction

### LINKED ISSUE #37026: Connect OSIRISDiffractionReduction grouping methods to diffraction interface

### PR DESCRIPTION
**Pull request by robertapplin**
### Description of work
This PR connects the Grouping detector options widget to the OSIRISDiffractionReduction algorithm on the Indirect Diffraction interface.

Fixes #37026 

### To test:
1. Open `Indirect`->`Diffraction` interface
2. Set Instrument to OSIRIS
3. Set Analyser to Diffonly
4. Load 89813 as sample
5. Load 89757 as vanadium
6. Select 'All' detector grouping. Run. The output workspaces should have 1 spectra
6. Select 'Groups' detector grouping, and 5 groups. Run. The output workspaces should have 5 spectra
6. Select 'Custom' detector grouping, and `3-500,501-962`. Run. The output workspaces should have 2 spectra

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by warunawickramasingha — COMMENTED** [review]
1. Can I assume that what is meant by test step 3 is to set Set `Reflection` to Diffonly and not `Analyser`?

image

3. Since the tooltip for `Cal file` suggests that it will not be used for grouping options other than for `File` option, I have tried to use some random .cal file as below and Ran with `Groups` groping option to observed below error. Is it a real issue or am I doing something not expected here? Please note the error does not come if I select a cal file like osiris_041_RES10.cal and gives the expected results as given in testing instructions.

image
```
Error in execution of algorithm OSIRISDiffractionReduction
No selected Detectors found in .cal file for input range.
  at line 581 in 'C:/Codes/mantid_for_Testing/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/OSIRISDiffractionReduction.py'
  caused by line 133 in 'C:/Codes/mantid_for_Testing/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/OSIRISDiffractionReduction.py'
  caused by line 133 in 'C:/Codes/mantid_for_Testing/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/OSIRISDiffractionReduction.py'
  caused by line 705 in 'C:/Codes/mantid_for_Testing/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/OSIRISDiffractionReduction.py'
  caused by line 1102 in 'C:\Codes\mantid_for_Testing\scripts\Inelastic\IndirectReductionCommon.py'
Got error from algorithm "OSIRISDiffractionReduction"
Stopping batch algorithm because of execution error
```

**Comment by robertapplin** [comment]
> 1. Can I assume that what is meant by test step 3 is to set Set `Reflection` to Diffonly and not `Analyser`?
> 

Ah yes that is a typo, it should say Reflection in the instructions!

**Comment by robertapplin** [comment]
> ```
> Error in execution of algorithm OSIRISDiffractionReduction
> No selected Detectors found in .cal file for input range.
>   at line 581 in 'C:/Codes/mantid_for_Testing/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/OSIRISDiffractionReduction.py'
>   caused by line 133 in 'C:/Codes/mantid_for_Testing/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/OSIRISDiffractionReduction.py'
>   caused by line 133 in 'C:/Codes/mantid_for_Testing/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/OSIRISDiffractionReduction.py'
>   caused by line 705 in 'C:/Codes/mantid_for_Testing/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/OSIRISDiffractionReduction.py'
>   caused by line 1102 in 'C:\Codes\mantid_for_Testing\scripts\Inelastic\IndirectReductionCommon.py'
> Got error from algorithm "OSIRISDiffractionReduction"
> Stopping batch algorithm because of execution error
> ```

I think this is an expected error because this calibration file looks to be for a different instrument, so the selected detectors in the *.cal file will not line up with those on OSIRIS. The same error occurs on `main` so I happy we can ignore this

**Review by warunawickramasingha — COMMENTED** [review]
Working well as explained and I am happy to approve!

**Review by warunawickramasingha — APPROVED** [review]

**Pull request merged**
