### PR TITLE
Remove custom dialog for CreateSampleShape

### LINKED ISSUE #23620: CreateSampleShpe can cause build docs-html to fail
CreateSampleShape.rst can cause `build docs-html` to fail with 
```
InterfaceManager-[Debug] Creating a specialised dialog for CreateSampleShape
X Error: GLXBadContext 173
  Extension:    156 (Uknown extension)
  Minor opcode: 6 (Unknown request)
  Resource id:  0x50000d0
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
```

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Removes the custom dialog for `CreateSampleShape`. The dialog is old and not used enough to warrant existence given the issues it causes.

**To test:**

Build MantidPlot and Workbench. Run the `CreateSampleShape` algorithm and see that the generic dialog with a simple text entry for the shape XML is offered.

Fixes #23620

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by PhilColebrooke — CHANGES_REQUESTED** [review]
Works as intended, the custom dialog is no more, and now the documentation builds on Ubuntu. The help documentation has a screenshot of the old dialog so should this be updated?

**Comment by martyngigg** [comment]
@PhilColebrooke Thanks for testing this. You are correct in that the screenshot should be the generic one now. I thought these were automatically generated so that it would just update. I'll double check what has happened there.

**Comment by PhilColebrooke** [comment]
@martyngigg I didn't realise the screenshots were automatically updated, I was just looking at the old version of the help documentation. So this is all good 👍

**Review by PhilColebrooke — APPROVED** [review]

**Comment by martyngigg** [comment]
@PhilColebrooke Thanks for checking. Glad it looks as we expected :+1:

**Pull request merged**
