### PR TITLE
Fix V20 Source chopper position

### LINKED ISSUE #22855: Fix Errors in V20 IDFs
After consulting Robin Woracek, we discovered some errors in the V20 IDFs where the `source-chopper` position was erroneously set to the `cold-source` position.

### PR DESCRIPTION
**Pull request by LamarMoore**
**Description of work.**

The position of the v20 source-chopper positions have been updated as per the requests of Robin Woracek.

Fixes #22855. 

Does this update require release notes?
- [ ] Yes
- [ ] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by OwenArnold** [comment]
@LamarMoore presumably you have already sent him these changes so that he can analyse his running experiment and the changes in `master` are just a formality for future use?

**Review by OwenArnold — CHANGES_REQUESTED** [review]
Fix looks correct according to `V20_idfconfigurations_v05` I think we should also add that Presentation into the `mantidproject/documents` repo and put a comment in both IDFs including a description of where that presentation is located. If you do not agree, then I'll approve this anyway.

**Comment by LamarMoore** [comment]
@OwenArnold the changes here will indeed be a formality.

**Comment by LamarMoore** [comment]
@OwenArnold Regarding the comments to the IDFs, are these configurations not subject to frequent changes? I think we could get confused by adding links to the documents repo especially if things get out of sync. What are your thoughts?

**Comment by OwenArnold** [comment]
@LamarMoore its a good point, especially if we started to imply that this IDF should absolutely definitely be like this document. However at present, we have no way of tracking where the values come from even though they are encoded in the document. Maybe we could create some kind of weak association. Maybe put the presentation into a folder in the `documents` repo, and put a comment in the idf along the lines of `<!-- See MantidProject/documents/configuration/V20 for user provided geometry layout ->`

Another suggestion would be to use MantidProject/geometry to create version scripts to generate the IDF?

**Comment by LamarMoore** [comment]
@OwenArnold  I added the configuration file to the docs repo. I also included an IDF for the transmission beam monitor reduction tests which they are currently using at V20.

**Comment by SimonHeybrock** [comment]
Is this ready now?

**Review by OwenArnold — APPROVED** [review]

**Pull request merged**
