### PR TITLE
Remove threaded use of (Spectrum|Detector)Info::setMasked.

### LINKED ISSUE #18281: Do not use threading with SpectrumInfo::setMasked and DetectorInfo::setMasked.
Masking information will be stored in `DetectorInfo`. Write access will not be thread-safe (at least in the initial implementation, but it is likely that threading would not actually provide a performance benefit -- it may actually be a drawback).

Go through client code using these methods and refactor where necessary.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Masking information will be stored in `DetectorInfo`. Write access will not be thread-safe (at least in the initial implementation, but it is likely that threading would not actually provide a performance benefit -- it may actually be a drawback).

Very few cases did actually require changes. I chose the simplest solution (adding a critical region) in most cases. I cannot exclude that this may cause slowdowns, but typically the critical region is in an `if` statement, so it will not be hit a lot by default. If the performance tests show issues (`BinaryOperation` may be a candidate) we can try to find a better solution.

Note that `DetectorInfo` will store a vector of mask flags. As long as the flag is a `bool` there will always be threading issues (writes to different elements of `std::vector<bool>` are not thread safe). Eventually we might consider moving to another flag type to get around this issue, but in any case this is beyond the scope of this PR.

**To test:**

- Code review.
- @reviewers: For this PR it is NOT sufficient to look at my changes. Rather, all uses of `SpectrumInfo::setMasked` and `DetectorInfo::setMasked` should be checked, to make sure that I did not overlook any cases that require changes.

Fixes #18281 .

No release notes, internal change.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by OwenArnold** [comment]
Looking through `DetectorInfo` I find this comment in the class doxygen
```
This class is thread safe with OpenMP BUT NOT WITH ANY OTHER THREADING LIBRARY
  such as Poco threads or Intel TBB.
```

**Comment by OwenArnold** [comment]
@SimonHeybrock There's a comment in `ConvertUnits` about making `convertViaTOF` run in parallel (line 558) but as far as I can tell it's actually not running in parallel.

**Comment by OwenArnold** [comment]
@SimonHeybrock. I manually checked the codebase of this branch - as far as I can tell, you missed nothing. I didn't check all the `..Test.h` files. I assume that no one would be thoughtless enough to mix threading up in unit tests with masking. So everything looks good.

I am a little concerned that someone might try to parallelise some of this at a later date. Should we add comments to all usage about thread safety, or do you think it's enough to see that it's clearly a write operation and developers would be cautious?

**Comment by SimonHeybrock** [comment]
@OwenArnold I agree with all your points, this update should address them.

**Comment by OwenArnold** [comment]
@SimonHeybrock. If we get all green. I think this will be good to merge.

**Comment by SimonHeybrock** [comment]
@OwenArnold All green. :)

**Comment by OwenArnold** [comment]
:shipit:

**Pull request merged**
