### PR TITLE
Use package suffixes properly for macOS builds

### LINKED ISSUE #27453: Nightly on MacOS Overrides the current install
### Expected behavior
Nightly Releases of Mantid Install as MantidPlotNightly/MantidWorkbenchNightly so as to not override an installed normal release. 
### Actual behavior
On MacOS this is not the case. Nightly versions install as MantidPlot/MantidWorkbench
### Steps to reproduce the behavior
Download and try to install a nightly version on MacOS. It is possible to rename the version you already have installed but a user won't think to do this, so it should not be the default!
### Platforms affected
MacOS Plot and WB

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

This brings the macOS packaging inline with Windows/Linux where the nightly package is a separately
installable entitity to the main release packages. Both the package itself and program name are suffixed
along with using different icons in the launcher menus.

**To test:**

* Run `cmake -DENABLE_CPACK=ON -DCPACK_PACKAGE_SUFFIX=nightly` on your build to enable packaging
* Build with `ninja`
* Build a package `ninja package`. Note that on catalina you may have to remove PyCifRW from [requirements.txt](https://github.com/mantidproject/mantid/blob/55fe471b6514443fcd35a8e1b3e7b59e7696455d/installers/MacInstaller/requirements.txt) due to a bug in packaging. This issue has been fixed upstream but no release as come through yet.
* Install mantidnightly and see it can be used separate to a normal release without interference.

Fixes #27453 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DanielMurphy22** [comment]
I forgot to disable MantidPlot so got this mess in the installer. WorkbenchNightly worked as expected and installed separate to a normal release. Both MantidPlot and MantidPlotNightly didn't work, but is that okay for this PR and Plot will be removed later?? 
Screenshot 2020-11-23 at 12 28 33

**Comment by martyngigg** [comment]
Thanks for testing this. As MantidPlot is not disabled yet we shouldn't let it through in that state. I'll take look.

**Review by DanielMurphy22 — CHANGES_REQUESTED** [review]
Correct the behaviour of Mantidplot

**Comment by martyngigg** [comment]
I'm going to delay this until we can disable mantidplot which is hopefully within a week.

**Comment by DanielMurphy22** [comment]
Screenshot 2020-12-14 at 16 13 55

This mostly works, but I seem to have this plugins folder, which is maybe linked to the the Windows build fail.

**Comment by martyngigg** [comment]
Thanks for testing this @DanielMurphy22. I think I've fixed that issue now.

**Comment by martyngigg** [comment]
The merge conflict should now be gone too.

**Review by DanielMurphy22 — CHANGES_REQUESTED** [review]
Screenshot 2020-12-18 at 14 07 57
Sorry, in fixing the conflict you've gone back to having this extra plugins folder again.

**Comment by martyngigg** [comment]
Ah damn. I think I force pushed the wrong branch 🤦

**Comment by martyngigg** [comment]
Thanks for catching that @DanielMurphy22. It should be fixed now.

**Review by DanielMurphy22 — CHANGES_REQUESTED** [review]
Well done. This works correctly now, but you're attracting conflicts today!

**Review by DanielMurphy22 — CHANGES_REQUESTED** [review]
I really want to approve this, but it's not quite right. See image for the extra lib folder. 

Screenshot 2020-12-18 at 18 32 07

I'll un-assign myself so someone else with a Mac can test next week.

**Comment by martyngigg** [comment]
Thanks, Daniel. Another rebase artifact I think. Thanks for getting it this far.

**Comment by martyngigg** [comment]
I have also realised that the system test installer script will not find the new package now.

**Comment by DanielMurphy22** [comment]
This now works well, and I'll double check after you fix the conflict (yet again 😆 ).

**Comment by martyngigg** [comment]
Thanks! Looks like just a release notes conflict this time thankfully!

**Comment by martyngigg** [comment]
Hopefully this is good now. 🤞🏻

**Review by DanielMurphy22 — APPROVED** [review]
Well done, looks good to me!

**Comment by martyngigg** [comment]
@mantidproject/gatekeepers Could we get this in for the nightly build?

**Review by DavidFair — APPROVED** [review]
CMake looks good, only one nit (which isn't worth holding this up):

We have moved a lot of our package suffix naming into our CMake files, in my view they should be agnostic to the release process (so that anyone compiling / modifying CMake code shouldn't have to concern themselves) as per separation of concerns

Instead it would be nice for Jenkins / Associated scripts to figure out `package_suffix`, then append that directly rather than have it look for `master` or `ornl-x` etc.

**Pull request merged**
