### PR TITLE
add python-sphinx-bootstrap-theme to debian dev requirements metapackage

### PR DESCRIPTION
**Pull request by zjttoefs**
Otherwise cmake isn't happy.

That would require a version bump of the package, but I've yet to understand this versioned directory hierarchy.

### CODE REVIEW

**Comment by zjttoefs** [comment]
It's probably pointless, but to be sure, Jenkins, could you test this please?

**Comment by zjttoefs** [comment]
test this please

**Comment by zjttoefs** [comment]
Jenkins, I beg you: test this please!

**Comment by zjttoefs** [comment]
test this please

**Comment by zjttoefs** [comment]
Jenkins, I need you to test this please. Now!

**Comment by AndreiSavici** [comment]
Should there be a version change?

**Pull request merged**
