### PR TITLE
Add pin for llvm-openmp for host environments on osx

### PR DESCRIPTION
**Pull request by sf1919**
**Description of work**
A pin has been added to the conda recipes for the host environment for `llvm-openmp`. This has been done for osx only.

**Purpose of work**
Both the release-next nightly pipeline and the main nightly pipeline are failing for osx on build and test. We think the issue is a recent upgrade of the `llvm-openmp` package. The package is already pinned for build environments for osx but we have not pinned it for our host environments. This change pins it for the host environment in an effort to fix the pipelines.

**Summary of work**
Pins have been added to the host environments for mantid, mantidqt and mantidworkbench for osx only.

**To test:**
Code review and make sure all the tests pass.

I have also got a build package from branch open - https://builds.mantidproject.org/job/build_packages_from_branch/395/. This needs to successfully complete also.

*There is no associated issue.*

*This does not require release notes* because **it is a pipeline fix**

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by robertapplin — COMMENTED** [review]
Code looks good and the pull request tests are passing. I am just waiting for the `build_package_from_branch` job to complete and then I'll approve

**Comment by robertapplin** [comment]
Unfortunately the build package from branch stopped at 98%, so I have aborted it

**Comment by gemmaguest** [comment]
Should this be going to `release-next`?

**Comment by sf1919** [comment]
This as not resolved the issue with the nightly and is on the wrong branch anyway - thanks for spotting that @gemmaguest . So I am closing this PR.

**Pull request closed without merging**
