### PR TITLE
Unit tests of QuasiElastic functions

### LINKED ISSUE #16482: Reorganize unit tests of functions, category "QuasiElastic"
This is one chunk of #16267.
Move the test cases that use the algorithm Fit to the unit test file of Fit (FitTest). Add tests to test the function itself when necessary. Tidy up the includes wherever possible, as for example in #16470.

QuasiElastic functions:
- ~~ChudleyElliot,~~ 
- ~~DiffRotDiscreteCircle~~
- ~~DiffSphere~~
- ~~ElasticDiffRotDiscreteCircle~~ 
- ~~ElasticDiffSphere~~
- ~~FickDiffusion,~~ 
- ~~HallRoss,~~ 
- ~~InelasticDiffRotDiscreteCircle~~
- ~~InelasticDiffSphere~~
- ~~StretchedExpFT~~
- TeixeiraWater

### PR DESCRIPTION
**Pull request by raquelalvarezbanos**
Reorganizes unit tests of functions under category `QuasiElastic`.

**To test:**

Code review. 
- Unit tests for `ChudleyElliot`, `FickDiffusion`, `HallRoss` and `TeixeiraWater` have been added (were missing before)
- Some unit tests for `DiffRotDiscreteCircle`, `DiffSphere`, `ElasticDiffRotDiscreteCircle`, `ElasticDiffSphere`, `InelasticRotDiscreteCircle`, `InelasticDiffSphere` have been moved to `FitTest`.
- `StretchedExpFTTest` is testing fitting results, but I haven't found the equivalent of `FitTest` for python functions, hence I am leaving the test as it is.

Fixes #16482.

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by mantid-roman** [comment]
The issue doesn't seem right to me. FitTest was supposed to test Fit algorithm and not all the functions that may use it. Maybe those tests should become to system tests?

**Comment by martyngigg** [comment]
I can see this marked as 3.9 but it's a maintenance issue. Can it be pushed back to `3.10`?

**Comment by raquelalvarezbanos** [comment]
Yes, I guess we can push it back to 3.10. The only problem I may have is more conflicts arising, but I deal with those.

@mantid-roman The reason why these tests were added to `FitTest` is because that's what we did for other categories of functions, see https://github.com/mantidproject/mantid/issues/16267 and sub-issues there. Perhaps a system test is a better idea, which means we'll need to move everything that was added to `FitTest` to a system test.

**Comment by NickDraper** [comment]
@DanNixon Can you pick this up as the developer

**Comment by SpencerHowells** [comment]
@NickDraper @DanNixon The function TeixeiraWater was written by Jose using a better/proper way of dealing with Q dependence. All the other functions should be modified to use this new method. Jose says he does not have the time to do it.

**Pull request closed without merging**
