### PR TITLE
Add fit output status to Indirect Data Analysis fitting tabs

### LINKED ISSUE #28964: Add fit output status to indirect analysis tabs
Currently the indirect analysis tabs do not show the output status of the fit, e.g. success to the user. This issue is to add this information to each tab of the GUI

**Original reporter:** Spencer Howells

### PR DESCRIPTION
**Pull request by StephenSmith25**
**Description of work.**
This PR adds the fit output information (algorithm status and chi squared) to each fitting tab within the Indirect Data Analysis Interface. In order to break the existing API, these two outputs are optional, which is controlled through an additional flag to the PlotPeaksByLogValue Algorithm (and the QENSFit algorithms).

**Report to:** ISIS/Spencer

**To test:**
Data to test each tab of the Indirect Data Analysis GUI can be found in #26631.

1. Open the Indirect Data Analysis GUI.
2. Go to the ``Conv fit`` tab
3. Load in data
4. Add the ``One Lorentzian`` function
5. Do a fit - A fit success and chi squared value should be shown.
6. You can cycle through the chi squared values and fit status using the ``Plot Spectrum`` spinbox 
7. Change the ``Max Iterations`` to 1 and run the fit - A fit failed message should be shown

Lastly, check that the functionally works on the other fitting tabs.

Fixes #28964

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by alicerussell1 — CHANGES_REQUESTED** [review]
This works well, just a small comment below

**Review by alicerussell1 — APPROVED** [review]
Thanks for the changes - looks good to me 👍

**Comment by gemmaguest** [comment]
Just wondering if declaring properties in `exec` is the best way to do this? I know this is done sometimes, but I think there are issues (e.g. I don't think they appear in the documentation). Would it be better to declare them in `init` and disable them if `OutputFitStatus` is not set? I can point you to an example of how to do that if you're not sure...

**Comment by StephenSmith25** [comment]
> Just wondering if declaring properties in `exec` is the best way to do this? I know this is done sometimes, but I think there are issues (e.g. I don't think they appear in the documentation). Would it be better to declare them in `init` and disable them if `OutputFitStatus` is not set? I can point you to an example of how to do that if you're not sure...

I agree properties in the `exec` are not great, but I couldn't see a way to make sure they didn't appear in the output, but if you could point me to a place that would be great. I'm wondering if they are disabled does that omit them from the outputs? The issue I had was python calls such as the following need to work.

`peakWs = PlotPeakByLogValue()` 

I found that if I defined two additional output properties in the `init()`, then the original call was broken (so the API was broken), as the new way to call it would be 

`peakWs, fit_status, chi2 = PlotPeakByLogValue()`

So that's why I defined them as` Exec properties, to make sure that by default the original API was unchanged. Would disabling them exclude them from the output as well?

**Comment by gemmaguest** [comment]
Hmm, so this has always confused me so I'm not sure of the best solution, but I thought you could have a variable number of outputs. Here is an example where it "works" with either 1 or 3 outputs, depending on whether `Debug` is set or not:
```
run1=Load('INTER13463')
run2=Load('INTER13464')
trans=CreateTransmissionWorkspace(run1, run2, Debug=0, WavelengthMin=1.5, WavelengthMax=17, ProcessingInstructions='4')
trans, t1, t2=CreateTransmissionWorkspace(run1, run2, Debug=1, WavelengthMin=1.5, WavelengthMax=17, ProcessingInstructions='4')
```

This algorithm has some "quirks" though so may not be the best example. It disables the properties when Debug is false but I don't think that affects anything other than their appearance in the algorithm dialog.

I'll have a dig around to see if I can find a better example...

**Comment by StephenSmith25** [comment]
> 
> 
> Hmm, so this has always confused me so I'm not sure of the best solution, but I thought you could have a variable number of outputs. Here is an example where it "works" with either 1 or 3 outputs, depending on whether `Debug` is set or not:
> 
> ```
> run1=Load('INTER13463')
> run2=Load('INTER13464')
> trans=CreateTransmissionWorkspace(run1, run2, Debug=0, WavelengthMin=1.5, WavelengthMax=17, ProcessingInstructions='4')
> trans, t1, t2=CreateTransmissionWorkspace(run1, run2, Debug=1, WavelengthMin=1.5, WavelengthMax=17, ProcessingInstructions='4')
> ```
> 
> This algorithm has some "quirks" though so may not be the best example. It disables the properties when Debug is false but I don't think that affects anything other than their appearance in the algorithm dialog.
> 
> I'll have a dig around to see if I can find a better example...

This example looks good, it’s exactly how I want it to behave. But looking at the Algorithm cpp file, I think its relying on the `PropertyMode::Optional` to be able to do this, which for me wasn't working (/ may not be implemented) for the `ArrayProperty` type when I tried. Maybe I got something wrong. Its quite hard to decipher the working of the property classes as it’s so highly templated!

**Comment by gemmaguest** [comment]
Are the new properties only likely to be used by the GUI (i.e. not directly by users)? If so maybe it's less of a problem that they're not documented.... Might be worth a bit more digging but if `Optional` is not supported maybe it's not worth the effort...

**Comment by StephenSmith25** [comment]
> Are the new properties only likely to be used by the GUI (i.e. not directly by users)? If so maybe it's less of a problem that they're not documented.... Might be worth a bit more digging but if `Optional` is not supported maybe it's not worth the effort...

I'd say the present intention is this to be GUI only, but I guess there's the option there if the user wants to have this information from a script. I think this information `('OutputStatus', 'chi2')` should by default be an output (as it is in the `Fit` algorithm) from the 'PlotPeaksByLogValue' and 'QENSFit' algorithms, as its valuable/necessary information, but I was wary of breaking the API.

**Comment by StephenSmith25** [comment]
So I tried with `std::make_unique<Kernel::EnabledWhenProperty>())` but it still appears in the output if its disabled. I think this relies on `PropertyMode::Optional`, but the `ArrayProperty` class doesn't have a constructor which takes a `PropertyMode` object and therefore cannot have the same functionality workspaces have. Maybe this would be something nice to add in the future.

**Comment by gemmaguest** [comment]
Agreed - it's not worth holding up this PR so I'll go ahead and merge it. Thanks for checking that out :+1:

**Comment by gemmaguest** [comment]
@StephenSmith25 It was requested to report this to Spencer when merged

**Pull request merged**
