### PR TITLE
Fix recently introduced python3 errors

### PR DESCRIPTION
**Pull request by rosswhitfield**
There have been python3 issues introduced recently, most of which was from #18157

[See here](http://builds.mantidproject.org/job/python3/)

**To Test:**
 * Compile with [python3](https://www.mantidproject.org/Python_3) and check that the unit tests pass.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by peterfpeterson** [comment]
I tried this out on fedora 25 with python 3.5.2 and everything worked up through running the unit tests **except** `MantidPlotPVPythonTest.py`.

**Comment by rosswhitfield** [comment]
Don't build with paraview then. That's a problem for @quantumsteve 😃

**Comment by peterfpeterson** [comment]
Similar fix to a different file `MantidPlot/test/MantidPlotPVPythonTest.py`
```python
"""
Test one can import paraview.simple in MantidPlot
"""
import mantidplottests
from mantidplottests import *
from paraview.simple import *


class MantidPlotPVPythonTest(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_PVPython(self):
        self.assertEqual(GetParaViewVersion().major, 5)

# Run the unit tests
mantidplottests.runTests(MantidPlotPVPythonTest)
```
It just needs to be tested by someone that doesn't build with paraview. ;)

**Comment by peterfpeterson** [comment]
All good now :shipit:

**Pull request merged**
