### PR TITLE
Add f2py fortran modules as a fetch content module

### LINKED ISSUE #6645: [Indirect] - Complete OS Support for F2Py Routines
This issue was originally [TRAC 5799](http://trac.mantidproject.org/mantid/ticket/5799)

This ticket was spawned from http://trac.mantidproject.org/mantid/ticket/5411.

Currently, the [http://www.scipy.org/F2py F2Py] routines currently being used by the Indirect users are only supported on the 32bit Windows builds of Mantid.  (Do a grep for "`is_supported_f2py_platform()`" to find the relevant Python files.  `IndirectImport` contains the code responsible for only importing the F2Py libs if Win32 is the current platform.)

The goal here is that the various F2Py routines we have should be available on ''all'' OS's supported by Mantid, and this should be done without having to manually compile and package the libraries along with Mantid each time a change or new OS is needed.  Talk to Martyn for more info on this, but essentially this should be achieved by having the Mantid build process include compiling the F2Py libraries from their Fortran source code.

Up to this point Spencer Howells has been solely responsible for compiling the F2Py code, so I'm sure a chat with him at some point would be useful.  In the meantime he has advised that the relevant files are mounted at `\\Britannic\modes3\MIDAS` and `ftp://ftp.nd.rl.ac.uk/pub/ida/MIDAS/F2Py/`

Finally, see attached for two DLLs that may help to get the Win64 version of the libs to work on machines that were not used to compile them.

---

Keywords: Indirect

### PR DESCRIPTION
**Pull request by StephenSmith25**
**Description of work.**
This PR enables the f2py fortran modules (used in Indirect and AbsCorrection) to be built as part of the main mantid build (if you have gfortran). This is currently just a developer facing change, but should enable us to support the fortran code on all platforms in the near future.

- [x] Do not merge before I've changed the fetch content link from my fork to the mantid repo.

**To test:**
- Probably easiest to test on linux and osx
- Make sure you have gfortran, e.g type gfortran in the terminal
- You should then be able to build the modules with the following: 
```
cmake .. -DF2PY_ROUTINES=True
make / ninja
```
- They should be built in build/_deps/3rdpartysources-build/bin
- You can then test they are all importable using something like:

```
import sys

path_to_f2py = '/Users/MyUser/Documents/mantid/build/_deps/3rdpartysources-build/bin'

class add_path():
    def __init__(self, path):
        self.path = path
    def __enter__(self):
        sys.path.insert(0, self.path)
    def __exit__(self, exc_type, exc_value, traceback):
        try:
            sys.path.remove(self.path)
        except ValueError:
            pass
            
            
with add_path(path_to_f2py):
    Quest = __import__('Quest')
    print(dir(Quest))
    # .. and so on
```

Partially fixes #6645. Integrating this change into our package builds will come later. 

This does not require release notes because this is currently just a developer facing change.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — CHANGES_REQUESTED** [review]

**Review by martyngigg — CHANGES_REQUESTED** [review]
Just a couple of comments inline plus, I tried to compile this on Ubuntu and I think it has found the python 2.7 copy of f2py:
```
$ PYTHONPATH=_deps/3rdpartysources-build/bin python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Quest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/xxxxx/Code/mantidproject/mantid-nightly/builds/debug/_deps/3rdpartysources-build/bin/Quest.so: undefined symbol: PyCObject_Type
>>>
```

If I look back at the the CMakeCache:

```
$ grep f2py CMakeCache.txt
F2PY_EXECUTABLE:FILEPATH=/usr/bin/f2py
F2PY_INCLUDE_DIR:STRING=/usr/lib/python3/dist-packages/numpy/f2py/src
FIND_PACKAGE_MESSAGE_DETAILS_F2PY:INTERNAL=[/usr/bin/f2py][v2()]
```

and then `f2py`:
```
$ head /usr/bin/f2py
#!/usr/bin/python
# See http://cens.ioc.ee/projects/f2py2e/
from __future__ import division, print_function

import os
import sys
for mode in ["g3-numpy", "2e-numeric", "2e-numarray", "2e-numpy"]:
    try:
        i = sys.argv.index("--" + mode)
        del sys.argv[i]
```
it shows that it uses `/usr/bin/python` which on Ubuntu 18.04 links to Python 2.

This quite often happens these days with the mix of these program scripts called `f2py` & `f2py3` where the latter is the Python 3 version. One option would be to use `${Python_EXECUTABLE} -m f2py` as the runner so that it gurantees the correct version of Python is used. Or we just look for `f2py3` first in the finder...

**Comment by StephenSmith25** [comment]
I wonder if the issue is in the find_program call here:

https://github.com/mantidproject/3rdpartysources/blob/7021b778a1d799c56376d6cbf67522c859026136/cmake/FindF2PY.cmake#L69

I think `PYTHON_VERSION_MAJOR` should be `Python_VERSION_MAJOR`, another mistake with character case 🤦. I wonder if that would fix it though, maybe I should only give it the ability to search for f2py3 or as you say do `${Python_EXECUTABLE} -m f2py`

**Comment by martyngigg** [comment]
> I wonder if the issue is in the find_program call here:
> 
> https://github.com/mantidproject/3rdpartysources/blob/7021b778a1d799c56376d6cbf67522c859026136/cmake/FindF2PY.cmake#L69
> 
> I think `PYTHON_VERSION_MAJOR` should be `Python_VERSION_MAJOR`, another mistake with character case 🤦. I wonder if that would fix it though, maybe I should only give it the ability to search for f2py3 or as you say do `${Python_EXECUTABLE} -m f2py`

I must admit on the commandline now I solely do `python -m ...`. Maybe this would be slightly more robust for the future so that it only depends on `Python_EXECUTABLE` pointing at the right thing?

> As a side note I've realised I can run `cmake .. --warn-uninitialized ` to try catch empty variables.

That's a nice feature, especially in cases where we've changed finders.

**Review by martyngigg — APPROVED** [review]
This looks good to me. Enabling the option now builds the modules as part of our build. There are loads of warnings from them but that's something that is more of an issue we'll need to address when we consider taking this as part of the standard build.

**Comment by DannyHindson** [comment]
Is this PR OK to merge now? I guess the "tick" indicates that but thought I'd double check

**Comment by martyngigg** [comment]
Yeah this should be good now - thanks.

**Pull request merged**
