### PR TITLE
Change IDF name mangling to use SHA1 rather than last modified date

### PR DESCRIPTION
**Pull request by NickDraper**
http://trac.mantidproject.org/mantid/ticket/11569
## To test
1. Start with a code review, and ensure that all unit and system tests pass
2. Manually load a RAW file (use Load, not LoadEmptyInstrument).
3. Look to see where the instrument file was loaded from by dropping down the details of the workspace.
   image
4. Go into the instrument directory and  make a visible change (like move a bank vertically). Do not change the last-modified date.
5. without closing mantid, reload the same file into a different workspace.
6. look at the instrument views of both workspaces, check the 2nd one got the updated image.
7. MAKE SURE YOU DO NOT COMMIT THE CHANGE TO THE IDF.

### CODE REVIEW

**Comment by NickDraper** [comment]
This is a purely internal issue, there is no need to contain details about this in the release notes.

**Comment by KarlPalmen** [comment]
Test failed on LET instrument. Instrument view is unchanged even if a door is removed.

The only difference I noticed was that if the instrument definition file is updated, it took just as long to load as it did first time, but if the file is not updated loading is quicker.

**Comment by NickDraper** [comment]
I think the problem was that the test was run with a nexus file with an embedded xml definition.

This is a known problem I'm fixing in #11818.

Could you try again with a raw file.

**Comment by KarlPalmen** [comment]
Yes the file is used to test this does have an embedded xml definition.

**Comment by KarlPalmen** [comment]
I've tested again with a Nexus file without embedded IDF and a raw file. I both cases, I saw part of the instrument move when loading after modifying the IDF file as described.

**Pull request merged**
