### PR TITLE
Whitelist dlls for Windows package

### PR DESCRIPTION
**Pull request by martyngigg**
Fixes trac issue [#11857](http://trac.mantidproject.org/mantid/ticket/11857)

**Tester**
This only affects the Windows installer. Please download the built package and test that it installs successfully and MantidPlot runs. You should see that it is now ~40Mb smaller.

The release notes were updated [here](http://www.mantidproject.org/ReleaseNotes_3_5_UI_Changes#Setup_and_installation)

### CODE REVIEW

**Comment by martyngigg** [comment]
The doc tests failure is just the unreliable `DownloadFile` failure and not related to these changes.

**Comment by FedeMPouzols** [comment]
DownloadFileTest strikes back, but the package has been built successfully on isis-ndw1490 and should be there (unless it is removed after the doc-test failure). Is there any way to get it? I can't find anything through the Jenkins Workspace etc.

I noticed that CPack is taking over 10 minutes even after these changes.

**Comment by FedeMPouzols** [comment]
Oh sorry, now I can see it. But it seems to be around 181 MB.

**Comment by martyngigg** [comment]
I see what has happened now. My test build didn't include the documentation, which actually accounts for the 40Mb :(
Despite this, I think the changes are still worthwhile as it will prevent new dlls that are added the the Third Party from being included unless they are specifically requested.

**Comment by FedeMPouzols** [comment]
The win64 package installs well, and I could not see any issues that should have been obvious if there was anything wrong with the dlls. So let's merge it in. This should produce cleaner installations and also a smaller package even if the gain cannot be that big.

The release notes will need an update if it's not feasible to shrink the package that much.

**Comment by martyngigg** [comment]
Good point. I'll update the notes to remove the entry as it's now more of a maintenance.

**Pull request merged**
