### PR TITLE
Update documentation on how to write algorithms

### PR DESCRIPTION
**Pull request by peterfpeterson**
With an influx of new people involved in mantid, it was time to edit the documentation for creating mantid algorithms. This is done by editing the existing user tutorial for extending mantid with python, and heavily editing the documentation for writing algorithms in C++. 

* Move to [semantic line breaks](https://sembr.org/)
* Add/update links between documents. This reduces the amount of hunting through the documentation for further information.
* Remove reference in C++ docs to old build-system and utility for creating classes
* Split out C++ into separate example files that the user can download the complete example of. In this PR, they were passed through clang-format so they will look like the rest of the codebase
* Modify the C++ example to use input/output workspaces

**To test:**

Build both the user docs and the developer docs and read through them.
```sh
ninja docs-html dev-docs-html
```

*There is no associated issue,* but the work is captured in [EWM1878](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=1878)

*This does not require release notes* because it is a change in the documentation for how to write algorithms and does not affect the functionality of mantid itself.

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by darshdinger** [comment]
It looks good and seems to include some updates. I am curious if diagrams are included anywhere or could be included? If not already included somewhere and if not to complex to create, incorporating a workflow diagram would be useful but mostly for developers.

For example, here is a simple workflow diagram I create for SNAPRed to allow for visual interpretation of the "under the hood" processes:

image

 Typically, for a dev, we learn this pattern through pursuing the process of creating a new algorithm. This and reading a few pages of documentation allows us to learn the process of how a new feature is formatted to be written and then incorporated.  A diagram would act as a good 'TLDR' in some sense. That would be my feedback. It may be somewhat redundant as we will be reading the documentation already but that is an area in which I find the documentation lacks in still.

**Review by darshdinger — COMMENTED** [review]
It looks good and seems to include some updates. I am curious if diagrams are included anywhere or could be included? If not already included somewhere and if not to complex to create, incorporating a workflow diagram would be useful but mostly for developers.

For example, here is a simple workflow diagram I created for SNAPRed to allow for visual interpretation of the "under the hood" processes:

image

Typically, for a dev, we learn this pattern through pursuing the process of creating a new algorithm. This and reading a few pages of documentation allows us to learn the process of how a new feature is formatted, to be written, and then incorporated. A diagram would act as a good reminder but also at first glance, a good overview of the architecture and the interactions in some sense. That would be my feedback. It may be somewhat redundant as we will be reading the documentation already but that is an area in which I find the documentation lacks in still.

**Comment by peterfpeterson** [comment]
I'm happy to include diagrams. However, "Service" and "Recipe" are concepts in SNAPRed that don't exist in mantid.

**Review by darshdinger — APPROVED** [review]
Looks good!

**Pull request merged**
