### PR TITLE
Update HB3A IDF, correct 2theta direction and panel positions

### PR DESCRIPTION
**Pull request by rosswhitfield**
**Description of work.**

This is to fix the direction the detector moves with 2theta, it should move to the right of the beam as 2theta increases as seen from the sample. I also moved the panels so that the bottom panel is at `[0,0,z]` instead of the middle panel, this is actually what the instrument is.

**To Test:**

Code review should suffice, but you can run the following to check.

Run this and check instrument view. This should now rotate right and be centered on the bottom panel
```
wksp = CreateWorkspace(
    NSpec=1,
    DataX=[0],
    DataY=[0])

log_names = [
    'cal::diffx1', 'cal::diffy1', 'cal::diffz1',
    'cal::diffx2', 'cal::diffy2', 'cal::diffz2',
    'cal::diffx3', 'cal::diffy3', 'cal::diffz3',
    'cal::rotx1', 'cal::roty1', 'cal::rotz1',
    'cal::rotx2', 'cal::roty2', 'cal::rotz2',
    'cal::rotx3', 'cal::roty3', 'cal::rotz3']

for log_name in log_names:
    AddSampleLog(
        Workspace=wksp,
        LogName=log_name,
        LogText='0.0',
        LogType='Number Series')

AddSampleLog(
    Workspace=wksp,
    LogName='2theta',
    LogText='30.0',
    LogType='Number Series')
LoadInstrument(
    Workspace=wksp,
    InstrumentName='HB3A',
    RewriteSpectraMap=False)
```
*There is no associated issue.*

*This does not require release notes* because it was only added this release.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Harrietbrown** [comment]
I am struggling to find any difference between the show instrument for `release-next` and this PR

**Comment by rosswhitfield** [comment]
If you run the script, and setting Axis View to Z+ I see

for `release-next`

HB3A_release_next

this branch
HB3A_new

**Comment by Harrietbrown** [comment]
on this branch I am getting 
image

**Comment by rosswhitfield** [comment]
Strange, try clearing your instrument cache.

**Comment by Harrietbrown** [comment]
How is that done?

**Comment by rosswhitfield** [comment]
Remove `~/.mantid/instrument/`, I don't know where it is if you are using windows.

Also check in the workspace info that it's pulling the instrument from the correct place

2019-11-07-085456_1260x366_scrot

**Comment by rosswhitfield** [comment]
The is also the algorithm `ClearCache`

**Comment by Harrietbrown** [comment]
that's got it.

**Review by Harrietbrown — APPROVED** [review]
Once I managed to clear the cache it was working fine. The instrument layout is changed as described.

**Pull request merged**
