### PR TITLE
28927 ill d7 signed two theta

### LINKED ISSUE #28927: Using signed twoTheta in ILL D7
### Expected behavior

During YIG scans, the instrument crosses the beam axis and thus it is of importance to take into account that twoTheta of detectors can be negative. After invoking ConvertSpectrumAxis, the spectrum axis should properly reflect on which side of the beam axis the pixel is located.

### Actual behavior

After invoking ConvertSpectrumAxis, the spectrum axis contains only the absolute value of the twoTheta, thus the information about pixel location with regard to the beam axis is lost.

### Steps to reproduce the behavior

Load YIG scan data, e.g. 394458.nxs from YIG scan taken on 28.08.2019 with the option 'ConvertToScatteringAngle' ticked and observe that twoTheta is always positive leading to overlapping intensity distribution as a function of twoTheta.

### Platforms affected
all

### PR DESCRIPTION
**Pull request by darominski**
**Description of work.**

Changed the target for ConvertSpectrumAxis algorithm invoked by ticking 'ConvertToSpectrumAxis' box from 'Theta' to 'signedTheta'. Now, the algorithm should return the signed twoTheta value, which is required to properly take into account that detectors can be located on either side of the beam axis, for example during YIG scans. 

**To test:**

Load ILL D7 data from a YIG scan, for example 394458.nxs from run 193 taken on 28.08.2019 and tick the 'ConvertToScatteringAngle'.  Observe the labels of the spectrum axis, the value for index 0 spectrum should be -88.88 (degrees).

Fixes #28927. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DannyHindson** [comment]
@darominski - please could you attach the 394458.nxs file to this PR so I can test\review it?
Also I see there's a bit of new code to flip the sign of the signedtwotheta values once the spectrum axis has been converted to signedtheta. Is this sign flip required for all instruments or just D7? If it's all instruments then perhaps the Mantid code to return signedtwotheta is wrong? If it's just D7 then would it better to achieve the same effect by changing the D7 instrument definition file? 
I've seen that you've set up a signed-theta to "x" for D7 but I guess this didn't give the correct sign

**Comment by darominski** [comment]
> @darominski - please could you attach the 394458.nxs file to this PR so I can test\review it?
> Also I see there's a bit of new code to flip the sign of the signedtwotheta values once the spectrum axis has been converted to signedtheta. Is this sign flip required for all instruments or just D7? If it's all instruments then perhaps the Mantid code to return signedtwotheta is wrong? If it's just D7 then would it better to achieve the same effect by changing the D7 instrument definition file?
> I've seen that you've set up a signed-theta to "x" for D7 but I guess this didn't give the correct sign

Thank your for your comments. I have added a unit test for the signed TwoTheta value that also simultaneously checks if the sign inversion is done correctly. The test uses file 394458.nxs from YIG calibration that is added to test data, so you should be able to access it from there.

The sign flip is required only by D7 at the moment. This is caused by the definition of the theta sign axis, where the only options are 'x', 'y', or 'z' but not '-x', '-y', or '-z'. In the D7 loader, we associated the positive twoTheta values with '-x' direction to maintain the right-handness of the reference frame. The normal experimental conditions in the right-handed coordinate system put the instrument in the negative 'x' axis values. Unfortunately, it is not possible to choose '-x' as the theta axis and I believe it would be good to avoid left-handed coordinate system or using negative twoTheta values for normal instrument conditions could be confusing for future users.

**Review by DannyHindson — APPROVED** [review]
Thanks for your explanation and the data file to support the test. I've tested it and I see the negative two theta values as required.
Your approach re the sign of the two theta values sounds fine. I guess if there are further cases such as this we could look at implementing support for -x in the instrument definition file but your approach seems fine for now.
Also I hadn't noticed that the LoaddILLPolarizedDiffraction algorithm was specifically built for the D7 instrument so no need to worry if the same -x convention applies to other instruments.

**Comment by gemmaguest** [comment]
@darominski Is it worth adding release notes for this?

**Pull request merged**
