### PR TITLE
Add Scaled Background Subtraction to ISIS SANS Interface

### LINKED ISSUE #35446: Allow can scaling factor to be specified in SANS GUI
The SANS group would like a way of performing a background subtraction on their normalised data in the GUI. 

This is currently performed by:
- Running the reduction twice to get two workspaces. One main workspace (created from Scatter, Transmission, and Direct runs for both Sample and Can, with the can subtracted from the sample), and a "solution" workspace (also created from  Scatter, Trans, and Direct with the can subtracted). 
- The `Scale` algorithm is then run on the Solution workspace. 
- The `Minus` algorithm is run to subtract the Solution workspace from the Sample Workspace. 
- The output from `Minus` is saved using `SANSSave`. 

**Requirements:**
- The shape of the Batch files should not be changed. I.e: no new columns, the scale factor & workspace value should be included as part of the existing `Options` column on the GUI.

**Improvement Steps:**
- [x] Add `BackgroundWorkspace` to `Options`
- [x] Add `ScaleFactor` to `Options`
- [x] Require that both are given if one is given. Throw an error otherwise.
  - [x] Add a state class to validate the background subtraction
  - [x] Validate the BackgroundSubtraction state before running the reduction. 
- [x] Load the scale workspace
- [x] Scale the workspace by the `ScalingFactor`
- [x] Subtract the scaled workspace from the output of the reduction
- [x] Create the outputs of the reduction (see below)

**Existing Questions:**
- What output is wanted? 
  - Do we save just the scaled subtracted workspace, or do we want the normal reduction output as well?
  - Should the outputted files and workspaces have different names if they've been scaled?
  - **Answer: Workspaces should be named something new when they've been scaled and be saved in addition to the usual output.**
- What if the given workspace is missing?
  - Should we do a check to see if the creation of it will be done in another row of the table?
  - This might be best as a future improvements element. After the basic functionality is added.

### PR DESCRIPTION
**Pull request by cailafinn**
**Description of work**

**Purpose of work**
SANS scientists currently do this after their main reduction by running a couple of algorithms in post. Namely Scale and Minus. They want to be able to do this in the Interface instead automatically, so that the saving can be done at the same time (which is much less error prone). 

**Summary of work**
Added BackgroundWorkspace and ScaleFactor options to the Options column of the ISIS SANS interface.

**Further detail of work**
Providing these two values allows the background subtraction to take place. The BackgroundWorkspace represents a "Solution" reduction which is a run where the sample was just the solution that would normally have the sample dissolved/suspended in it. This BackgroundWorkspace is the result of a separate full reduction, and must be in the ADS prior to using it in a Scaled Background Subtraction reduction. 

The BackgroundWorkspace is multiplied by the given ScaleFactor and then subtracted from the output workspace (defined by ReductionMode (HAB, LAB, or Merged). It is expected that the Reduction Mode will be the same across both reductions). 

The result of this subtraction is then saved *in addition* to the normal output of the reduction.

**To test:**
1. Boot up workbench and the ISIS SANS interface. 
2. Load the user file and the batch file from the LOQ Demo in the TrainingCourseData
3. Process All (this will produce your "background" workspaces, something like `first_time_merged_1D_2.2_10.0` or `first_time_HAB_1D_2.2_10.0`)
4. Change the output name and add `BackgroundWorkspace=<nameOfBackgroundWorkspaceFromStep3>, ScaleFactor=0.9` to the options cell of the row. 
5. Run the reduction again (if it fails, you may need to change the value of the toml user file for the reduction mode from "All" to "Merged", but this is a good chance to check the error message shows properly.)
  5a. If you've had to make the all -> merged change, you'll need to run steps 3 and 4 again from scratch as the workspace names will be different, as will the number of spectra in the workspace. Which will throw errors from the Minus algorithm. Make sure that the workspace you select as the `BackgroundWorkspace` has `merged` in the title. 
7. Check the two output workspaces you should now have. If it has worked properly, the subtracted one's values should be 10% of the unsubtracted one's. 

Fixes #35446 

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by sf1919** [comment]
I have tried to follow the test instructions but have come across an error. After making a new MaskFile with it changed to Merged and re-running the processing I get

```The two workspaces are not compatible because they have different units for the data (Y).
The two workspaces are not compatible for algorithm Minus
Error in execution of algorithm Minus:
The two workspaces are not compatible for algorithm Minus```

**Comment by ConorMFinn** [comment]
> ```
> The two workspaces are not compatible because they have different units for the data (Y).
> The two workspaces are not compatible for algorithm Minus
> Error in execution of algorithm Minus:
> The two workspaces are not compatible for algorithm Minus
> ```

I've done some checking and it was due to us using the old non-merged output workspaces as the inputs. Merged workspaces are a combination of both banks so have additional spectra. I've updated the instructions to make the process more clear. What we were seeing were expected errors.

**Comment by sf1919** [comment]
When I select the option Plot Results I don't seem to get the background subtraction as part of the plots. Is that what we expect to happen? Below is an image of what I do get after following all the steps (I've done it as a waterfall plot so you can see the different lines plotted).
Screenshot (308)

**Review by sf1919 — APPROVED** [review]
I have now completed my review. Thank you for adding the plotting for the background subtraction output and testing instructions for Manual testing for release.

The changes look good and do what is expected. The code looks good (thank you for changing the variable names) and there are suitable tests.

**Pull request merged**
