### PR TITLE
Fix Sliceviewer grids cannot be enabled with lineplots

### LINKED ISSUE #34083: Sliceviewer grids cannot be enabled with lineplots
Found in Smoke testing: https://github.com/mantidproject/mantid/issues/34075#issuecomment-1154952406
Regression
**Describe the bug**
On Sliceviewer grid lines cannot be enabled while lineplots are

**To Reproduce**
Open Sliceviewer on any data, 
enable lineplots in the toolbar options
try to enable gridlines

**Expected behavior**
Gridlines and lineplots work and do not affect eachother

**Platform/Version (please complete the following information):**
 - OS: all
 - Mantid Version 6.4 release candidate

### PR DESCRIPTION
**Pull request by MialLewis**
**Description of work.**
As part of a previous PR a regression was introduced that prevented grid lines from showing when line plots were active on SliceViewer.

This was caused by the image axes x and y axis being set `visible = False` entirely. For grid lines to show, the relevant tick markers must be active.

This PR individually hides axis and marker labels, leaving the ticks visible (though in reality obscured by the line plots as intended). 

**To test:**

Follow the test instructions on the following Issue and PR:
https://github.com/mantidproject/mantid/issues/34083
https://github.com/mantidproject/mantid/pull/33363

Fixes #34083

*This does not require release notes* because its a regression identified in smoke testing not by a user.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by robertapplin** [comment]
When I enable lineplots, I get these warning messages in the logger:
image

Is this expected?

**Comment by MialLewis** [comment]
> When I enable lineplots, I get these warning messages in the logger: image
> 
> Is this expected?

No - I've just checked and I don't get these. Can you double check your version of `matplotlib`?

**Comment by robertapplin** [comment]
> No - I've just checked and I don't get these. Can you double check your version of `matplotlib`?

I was using a non-conda build. I've just tested on a conda build with `matplotlib=3.5.2` and the warning message no longer appears, so I think this is good

**Review by robertapplin — APPROVED** [review]
Code looks good and works as expected

**Pull request merged**
