### PR TITLE
Update algorithms for Python3 - Group 3

### PR DESCRIPTION
**Pull request by rosswhitfield**
This is Group 3 of #16739 

**To test:**
- Code review
- Make sure the unittests still pass with python2.

Does not need to be in the release notes.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by rosswhitfield** [comment]
LoadCIF and GetEiT0atSNS unittests still fail when using python3. I will fix these.

**Comment by rosswhitfield** [comment]
I don't currently have a good solution to the two failing unittests. `LoadCIFTest` fails because `str(float)` converts a float to a string with different precision. _e.g._ `python -c 'from numpy import pi; print(pi)'` gives different results for python 2 and 3.

`GetEiT0atSNSTest` fails because for some reason in python 3 the exception message create [here](https://github.com/mantidproject/mantid/blob/master/Framework/PythonInterface/plugins/algorithms/GetEiT0atSNS.py#L82) is not being passed to the unittest [here](https://github.com/mantidproject/mantid/blob/master/Framework/PythonInterface/test/python/plugins/algorithms/GetEiT0atSNSTest.py#L22).

**Comment by peterfpeterson** [comment]
Currently the failing tests (with python2) is:
```
469 - PythonInterfaceAPI_MultipleFilePropertyTest (Failed)
539 - PythonAlgorithms_LoadLogPropertyTableTest (Failed)
```
Are these related to this PR?

**Comment by peterfpeterson** [comment]
With python3 the list is
```
521 - PythonAlgorithms_GetEiT0atSNSTest (Failed)
539 - PythonAlgorithms_LoadLogPropertyTableTest (Failed)
```

**Comment by rosswhitfield** [comment]
Related to [this](https://github.com/mantidproject/mantid/issues/17001).

I was unable to fix `GetEiT0atSNSTest` as explained above, the exception message being raise gets lost.

**Comment by peterfpeterson** [comment]
You are right. :shipit:

**Pull request merged**
