### PR TITLE
Fix leaks in ComputeResourceInfo (XML parsing and test)

### PR DESCRIPTION
**Pull request by FedeMPouzols**
This fixes [#11467](http://trac.mantidproject.org/mantid/ticket/11467), memory leaks that valgrid detected.

**To test**:
- double check that tests passed
- code review

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
In the last build everything went fine, except that `SystemTests.CodeConventions` complains about an unrelated algorithm. So despite the red cross I'd say this is ready for testing.

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, wake up and retest this please

**Comment by stuartcampbell** [comment]
@FedeMPouzols I presume you haven't seen @rosswhitfield comments on slack - the old plugin is now disabled so the retest this type comments won't work anymore.  You can either restart the job on jenkins directly or they will trigger with any new code changes.

**Comment by peterfpeterson** [comment]
I merged master back into the branch to kick off a new round of builds

**Comment by FedeMPouzols** [comment]
Good, thanks! One of them was definitely stuck since yesterday.

**Comment by eXeC64** [comment]
The only change has been to the `ComputeResourceInfo` unit test, which has no passed on all platforms. I'm not going to bother to wait for RHEL7 or Windows to finish as any failures that occur can only be random and unrelated.

Reviewed the code and it looks good to me.

**Pull request merged**
