### PR TITLE
Fix PreviewPlot for mpl3

### PR DESCRIPTION
**Pull request by Matthew-Andrew**
Draggable was deprecated in mpl2.2 and removed in 3.1. As we have versions spanning this range we need to check and then use the correct api.

**To test:**
  * On windows or a build using matplotlib 3.1
  * Open Indirect Data Analysis, Go to the IQt tab and try and load irs26176_graphite002_red.nxs which can be found in the unittest directory.
  * The file should load succesfully

*There is no associated issue.*

*This does not require release notes* because this issue was introduced this release

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — COMMENTED** [review]
I'm happy with this. Just the clang format errors need fixing.

**Review by martyngigg — DISMISSED** [review]
Changes look good and the crash no longer happens.

**Review by martyngigg — APPROVED** [review]
Good to go now.

**Comment by Mantid-Matthew** [comment]
@mantidproject/gatekeepers could we get this merged please as it is currently holding up several other Pr's for me.

**Pull request merged**
