### PR TITLE
Add option to FileFinder::getFullPath to skip directories

### PR DESCRIPTION
**Pull request by martyngigg**
Fixes issue [#11395](http://trac.mantidproject.org/mantid/ticket/11395)

**Tester**
Check the unit test does something sensible and try out the `FileFinder.getFullPath` from Python to see that it performs as expected.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
It worked well for me. I tried to fool it with LET and MAR without any success.

I only noticed a couple of unrelated nitpicky issues with LoadMask:
- It can be slowish for what it does (with LET and LET_hard, I guess that the problem is the large number of histograms), 
- If you try to LoadMask with a wrong combination as for example in `LoadMask('MAR', 'LET_hard.msk')` you'll get a cryptic error message `RuntimeError: Logic error`.

**Comment by martyngigg** [comment]
Those are fair points. Could you raise a ticket about them? This fix was primarily about fixing some functionality that had been broken in the last release.

**Comment by FedeMPouzols** [comment]
Sure, there is now a trac ticket for those couple of issues: [#11420](http://trac.mantidproject.org/mantid/ticket/11420).

**Comment by martyngigg** [comment]
Thanks

**Pull request merged**
