### PR TITLE
Copy spectra-detector mapping algorithm

### PR DESCRIPTION
**Pull request by DanNixon**
Fixes [#11125](http://trac.mantidproject.org/mantid/ticket/11125).

To test: review documentation, try the algorithm with some actual data based on the usage example.

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
Code and unit test look nice, well documented as well. I have just noticed an issue: when dealing with workspace groups Mantid crashes. This is confusing when you only have one workspace group loaded in Mantid and then you execute the algorithm, as it crashes without information. Given the purpose of the algorithm I may not make much sense trying to use workspace groups, but an error message would be useful.

**Comment by DanNixon** [comment]
Understandably, it should only be used with matrix workspaces.
Will change the properties to workspace properties instead.

**Comment by DanNixon** [comment]
Jenkins, retest this please.

**Comment by abuts** [comment]
Jenkins, retest this please

**Comment by DanNixon** [comment]
Jenkins, retest this please.

**Pull request merged**
