### PR TITLE
Fix crash when reloading a deleted peaks workspace in splatterplot mode in the VSI

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Fixes issue [#11045](http://trac.mantidproject.org/mantid/ticket/11045)

For testing:

Please find sample data sets attached to the original ticket.
- Load the sample data set MDEventWS into the VSI and switch into the splatterplot mode
- Load the sample data set PeaksWS into the VSI
- Delete the peak source from the pipline browser
- Load the sample data set PeaksWS again into the VSI
- Confirm that Mantid is not crashing.

### CODE REVIEW

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by OwenArnold** [comment]
Code reviewed and working ok now.

**Pull request merged**
