### PR TITLE
Clean up after documentation tests

### LINKED ISSUE #29867: Clean up after documentation tests
### Expected behavior
When building docs and running doctests, I expect that tests clean up after being run

### Actual behavior
I get the following extra files in the build `docs` folder:
```
b3lyp.hdf5
benzene.hdf5
benzene_wrk_C.dat
benzene_wrk_C_total.dat
benzene_wrk_H.dat
benzene_wrk_H_total.dat
ColCalcvsTheor.nxs
ConvertMultipleRunsToSingleCrystalMDTest.mat
experimental_wrk.dat
fittedpeaks.dat
myplot.json
RowCalcvsTheor.nxs
Test.DetCal
test_intermediateWavelength.xml
TofCalcvsTheor.nxs
wrk_C.dat
wrk_C_total.dat
wrk_H.dat
wrk_H_total.dat
wrk_Na.dat
wrk_Na_total.dat
wrk_N.dat
wrk_N_total.dat
wrk_O.dat
wrk_O_total.dat
wrk_verbose_atom_1.dat
wrk_verbose_atom_1_total.dat
wrk_verbose_atom_2.dat
wrk_verbose_atom_2_total.dat
wrk_verbose_H.dat
wrk_verbose_H_total.dat
wrk_verbose_total.dat
ZODS.h5
```
### Steps to reproduce the behavior
Build `docs-html` and `docs-doctests`

### Platforms affected
All

### PR DESCRIPTION
**Pull request by AndreiSavici**
**Description of work**

Clean up after documentation tests

**To test:**
Run the documentation test. No output data files should be produced in the Build docs/ or docs/doctest/ folders.

Fixes #29867 

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by jhaigh0** [comment]
Cleaned up all the temp files etc nicely, good job.

I did however have some test failures
```
Doctest summary
===============
1293 tests
18 failures in tests
0 failures in setup code
2 failures in cleanup code
build finished with problems, 19 warnings.
```
The relevant ones would be the clean-up code failures,
`techniques\ReflectometryILL.rst`
- `D17UserAngleQuartz`
- `FIGARODetectorAngleGravityCorrection`
```
File "techniques\ReflectometryILL.rst", line 514, in FIGARODetectorAngleGravityCorrection (cleanup code)
Failed example:
    mtd.clear()
    import os
    for index in range(2):
        os.remove(f'{name}_{index}.out')
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\bya67386\AppData\Local\mambaforge\envs\mantid-developer\lib\doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest FIGARODetectorAngleGravityCorrection (cleanup code)[0]>", line 4, in <module>
        os.remove(f'{name}_{index}.out')
    FileNotFoundError: [WinError 2] The system cannot find the file specified: 'Cell_d2O_0.out'
```
I think this one is because the test itself failed, so there was no file to remove. You could add a check to see if the file exists, but maybe overkill if the test is failing anyway.
```
File "techniques\ReflectometryILL.rst", line 933, in FIGARODetectorAngleGravityCorrection
Failed example:
    # reduction based on data from cycle 212, exp_EASY-952
    name = 'Cell_d2O'
    runs = '743465,743466'
    direct_run = '732252+732254,732255'
    ReflectometryILLAutoProcess(
          Run=runs,
          DirectRun=direct_run,
          OutputWorkspace=name,
          AngleOption='DetectorAngle',
          SummationType='Incoherent',
          WavelengthLowerBound=[3.5, 2.5],
          WavelengthUpperBound=[20, 19],
          DeltaQFractionBinning=0.5,
          GlobalScaleFactor=0.0484221,
          Cleanup='Cleanup ON',
          ReflFitStartWorkspaceIndex=25,
          ReflFitEndWorkspaceIndex=230,
          DirectFitStartWorkspaceIndex=25,
          DirectFitEndWorkspaceIndex=230,
          DirectLowAngleFrgHalfWidth=[3, 7],
          DirectHighAngleFrgHalfWidth=[3, 7],
          ReflLowAngleFrgHalfWidth=[3, 7],
          ReflHighAngleFrgHalfWidth=[3, 7],
          DirectLowAngleBkgOffset=5,
          DirectLowAngleBkgWidth=5,
          DirectHighAngleBkgOffset=5,
          DirectHighAngleBkgWidth=5,
          ReflLowAngleBkgOffset=5,
          ReflLowAngleBkgWidth=5,
          ReflHighAngleBkgOffset=5,
          ReflHighAngleBkgWidth=5,
          ReflFlatBackground='Background Average',
          DirectFlatBackground='Background Average',
          CorrectGravity=True
    )
    print("Number of output workspaces: {}".format(mtd[name].getNumberOfEntries()))
    print("Momentum exchange ranges: {:.4f}, {:.4f}".format(mtd[name][2].readX(0)[0], mtd[name][2].readX(0)[-1]))
    print('X unit: ' + mtd[name][2].getAxis(0).getUnit().unitID())
Exception raised:
    Traceback (most recent call last):
      File "c:\users\bya67386\work\mantid\framework\pythoninterface\mantid\simpleapi.py", line 936, in do_set_property
        alg_object.setProperty(key, new_value)
    ValueError: Invalid value for property Run (list of str lists) from string "743465,743466": Unable to find file matching the string "743465", please check the data search directories.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "C:\Users\bya67386\AppData\Local\mambaforge\envs\mantid-developer\lib\doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest FIGARODetectorAngleGravityCorrection[0]>", line 5, in <module>
        ReflectometryILLAutoProcess(
      File "c:\users\bya67386\work\mantid\framework\pythoninterface\mantid\simpleapi.py", line 1068, in __call__
        set_properties(algm, *args, **final_keywords)
      File "c:\users\bya67386\work\mantid\framework\pythoninterface\mantid\simpleapi.py", line 956, in set_properties
        do_set_property(key, value)
      File "c:\users\bya67386\work\mantid\framework\pythoninterface\mantid\simpleapi.py", line 939, in do_set_property
        raise e.__class__(msg) from e
    ValueError: Problem setting "Run" in ReflectometryILLAutoProcess-v1: Invalid value for property Run (list of str lists) from string "743465,743466": Unable to find file matching the string "743465", please check the data search directories.
```
And looking at it, maybe that's something on my end, since it couldn't find the data.

As a site note, quite a lot of the other failure are simple syntax errors, which could pretty quickly I think.

**Comment by AndreiSavici** [comment]
The following files have failing tests (some of them more than one). 
```
algorithms/ReflectometrySliceEventWorkspace-v1.rst
algorithms/SANSILLParameterScan-v1.rst
algorithms/LoadILLReflectometry-v1.rst
algorithms/Abins2D-v1.rst
algorithms/SaveHKL-v1.rst
techniques/ReflectometryILL.rst
algorithms/PolarizationCorrectionWildes-v1.rst
algorithms/GeneratePythonFitScript-v1.rst
algorithms/SaveHKLCW-v1.rst
concepts/calibration/PowderDiffractionCalibration.rst
algorithms/FitPeaks-v1.rst
tutorials/python_in_mantid/further_alg_ws/04_run_logs.rst
```
I suggest that failing cleanup tests should not be modified with a 
```
try:
     ...
except:
    pass
```
This just hide the issue, and might leave unwanted files on the disk

**Comment by sf1919** [comment]
The base branch for this needs to be main rather than release-next

**Comment by perenon** [comment]
Dear Andrei,
we spent some time with @eurydice76 on this today. We did not see any error for the `techniques/ReflectometryILL.rst` or `algorithms/LoadILLReflectometry-v1.rst` files. We guess the changes you made are sufficient.

Considering the `algorithms/SANSILLParameterScan-v1.rst` file, we suspect the data format has changed between the algorithm setting and the data file generation. Using the input file `025786.nxs` instead of the `066321.nxs` would solve the test failure. Do you think that could be an acceptable solution ?

Regards,
Eric & Remi

**Comment by AndreiSavici** [comment]
Thanks. The new file is fine. I will push the fix.
Andrei
________________________________
From: Remi Perenon ***@***.***>
Sent: Wednesday, June 21, 2023 12:31 PM
To: mantidproject/mantid ***@***.***>
Cc: Savici, Andrei T. ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [mantidproject/mantid] Clean up after documentation tests (PR #35679)


Dear Andrei,
we spent some time with @eurydice76<https://urldefense.us/v2/url?u=https-3A__github.com_eurydice76&d=DwMCaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=vL38KJy-33BfedqXfLtmvImGokNEWqz9ObWoTkPmvp8&m=eZ6aC4OL0_9W8zg_O9LRT54TREpFjFZcrdIWnmvWRYZHyJJf43lAggTEWwc3vfMj&s=Rgn-amAK1ovfa17Ka0sEjV8I4hHbyf404vYLcj1mYrU&e=> on this today. We did not see any error for the techniques/ReflectometryILL.rst or algorithms/LoadILLReflectometry-v1.rst files. We guess the changes you made are sufficient.

Considering the algorithms/SANSILLParameterScan-v1.rst file, we suspect the data format has changed between the algorithm setting and the data file generation. Using the input file 025786.nxs instead of the 066321.nxs would solve the test failure. Do you think that could be an acceptable solution ?

Regards,
Eric & Remi

**Comment by AndreiSavici** [comment]
@perenon and @eurydice76 Can you also take a look at `algorithms/PolarizationCorrectionWildes-v1.rst`?
```
Expected:
    Ratio of corrected and original 'up' intensity at 15A: 1.038
    Ratio of corrected and original 'down' intensity at 15A: 1.062
Got:
    Ratio of corrected and original 'up' intensity at 15A: 0.1062
    Ratio of corrected and original 'down' intensity at 15A: 10.38
```

**Comment by sf1919** [comment]
`PolarizationCorrectionWildes` is one that @rbauststfc is looking at

**Comment by rbauststfc** [comment]
@AndreiSavici for `algorithms/PolarizationCorrectionWildes-v1.rst`, the result from the example has changed because of the fix for issue #34940. Apologies, I didn't notice this would need updating in the documentation. If you would like me to do anything to help get this updated then just let me know.

**Comment by AndreiSavici** [comment]
One more test is fixed in https://github.com/mantidproject/mantid/pull/35767

**Comment by sf1919** [comment]
This PR is blocked by #35511 . 

We need to merge in the cross compilation work to get the new MacOS machines online first before we re-enable the docs tests. It is urgent to get these machines onto the pipeline as it should nearly double our capacity and cause fewer bottlenecks in the CI pipeline. The cross compilation work just needs reviewing now so its very close!

**Comment by AndreiSavici** [comment]
Down to 2 failing tests: `algorithms/ReflectometrySliceEventWorkspace-v1.rst` and `algorithms/PolarizationCorrectionWildes-v1.rst`

**Comment by jhaigh0** [comment]
Now tests are passing, I will do another doc test run and check there is no leftover output.

**Comment by jhaigh0** [comment]
I got a failure on the `ViewBOA` doc test (not one that has been modified here).

When I run `ViewBOA(2014, 61, 6)` in Mantid it fails at the new assert statement which @peterfpeterson added a couple of days ago [here](https://github.com/mantidproject/mantid/blob/main/Framework/API/src/MatrixWorkspace.cpp#L636) (257 != 256).

Unsure if this is a revealed bug in `ViewBOA` or an incorrect assumption when making the assert statement.

**Comment by peterfpeterson** [comment]
@jhaigh0 That is very interesting. That assert is only run in debug mode, but from looking at what that file was back in v6.6 it seemed like a useful thing to check.

**Review by jhaigh0 — APPROVED** [review]
Approved and raised issue about that algorithm [here](https://github.com/mantidproject/mantid/issues/35847). You're right that it isn't relevant to this PR and should be looked into separately.

**Pull request merged**
