### PR TITLE
Fix bugs with restoring defaults on the reflectometry GUI

### LINKED ISSUE #28429: Loaded Batch settings are overridden if instrument changes
### Expected behavior
If you load a batch file in the ISIS Reflectometry GUI then the Experiment and Instrument settings should reflect what is in the file.

### Actual behavior
If the batch file is for a different instrument to the original instrument displayed in the GUI, then the Experiment and Instrument settings are overridden with default values for that instrument.

There is a related bug where Doing Batch->new resets the Experiment/Instrument defaults in ALL batches, not just the new one.

### Steps to reproduce the behavior
- Open the ISIS Reflectometry interface
- Go to Batch->Load and select the INTER_NR_test.json file from the ISIS Sample data
- Modify some settings on the Experiment and Instrument tabs.
- Go to Batch->Save and save the settings to a new file.
- Change the instrument and then re-load the settings you saved. Note that the changes to Experiment and Instrument tabs are not included.
- Change some settings in the Instrument/Experiment tabs. Click Batch->New. Note that your settings are overridden.

### Platforms affected
All

### Implementation notes
I think the problem is likely to be that we are restoring defaults after the instrument is changed. We could do either of the following (I don't have a strong preference):
1. Change to the new instrument first, restore defaults, then load the data from the file.
2. Skip the restore-defaults step altogether when loading a file. This would be quicker because it wouldn't need to access properties from the instrument. However the speed is not a big impact. This would also mean all settings will need to be in the file, which they currently are, but this may mean we're less flexible going forward.

### PR DESCRIPTION
**Pull request by gemmaguest**
**Report to:** Max at ISIS

This PR fixes a couple of bugs on the ISIS Reflectometry interface to do with settings being overridden:
- The Experiment/Instrument settings were being overridden by defaults if the instrument changed as part of a load.
- The Experiment/Instrument settings on all tabs were being overridden by defaults when you create a new batch. This was due to the instrument being updated when it gets set on the new batch.
- The Experiment/Instrument settings on all batches/tabs were also being overridden when you click Restore Defaults on a single tab. This was due to the instrument being updated before loading defaults, which is fine, but then it was issuing a notification to all batches that an update had happened.

This PR also contains some minor tidying and improvements to unit tests (particularly the decoder) and removes an unused function declaration.

**To test:**

- Open the `ISIS Reflectometry` interface
- From the Batch->Load menu, load the `INTER_NR_test.json` file from the ISIS sample data
- Edit some settings on the Experiment and Instrument tab
- From the Batch->Save menu, save the settings to a new file
- Change the instrument to something other than INTER and re-load the file you saved
- Check that the settings you changed are restored
- Select Batch->New to create a new batch
- Check that the settings you changed in the original batch are not affected
- Click Restore Defaults on an Experiment/Instrument tab and check that only that tab is affected (and no other batches are changed).

Fixes #28429 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by giovannidisiena — APPROVED** [review]
Nice refactoring of the decoder and code comments, loading settings and restoring defaults now works as described :shipit:

**Comment by martyngigg** [comment]
This still has the "Not Ready" label on it. Just before I merge can I assume that no longer applies?

**Comment by gemmaguest** [comment]
> 
> 
> This still has the "Not Ready" label on it. Just before I merge can I assume that no longer applies?

@martyngigg Yes, sorry - I've removed it. Just retrying the OSX build which had failed due to the known fitpropertybrowser unreliable test.

**Comment by martyngigg** [comment]
No problem. Just wanted to check.

**Pull request merged**
