### PR TITLE
Fix an integer overflow issue in LoadBankFromDiskTask

### LINKED ISSUE #22889: LoadEventNeXus fails to load VULCAN's high angle bank of run 163113
SNS/Yan Chen reported that there was signal in reduced GSAS file from /SNS/VULCAN/IPTS-21357/nexus/VULCAN_163113.nxs.h5.

### Expected behavior

Run 163113 lasted for more than 10 hours.  There shall be a regular diffraction pattern on high angle bank.

### Actual behavior

The reduced data shows nothing on high angle bank.

### PR DESCRIPTION
**Pull request by wdzhou**
There is an integer overflow issue in LoadBankFromDiskTask.  This causes a negative number of events to stop the loading process.  Changing the data type to int64_t shall resolve the issue.

**Report to:** Yan Chen of SNS

**To test:**

Load /SNS/VULCAN/IPTS-21357/nexus/VULCAN_163113.nxs.h5.  Check number of events in the high angle bank (from spectrum 6469). 

Fixes #22889. 

Does this update require release notes?
- [ ] Yes
- [ ] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by peterfpeterson — CHANGES_REQUESTED** [review]
The code would be a little cleaner if `start_event` and `stop_event` were both `int64_t` as well. It looks like it is all hiding in private data/methods so changes would stay in the file.

**Review by peterfpeterson — APPROVED** [review]
LGTM

**Comment by wdzhou** [comment]
It is closed as it was based on master such that it couldn't be merged to release-next.
A new PR #22902 is created instead.

**Comment by peterfpeterson** [comment]
This has been re-created with the right parents in #22902.

**Pull request closed without merging**
