### PR TITLE
Label Tool adding Log Values to a plot improved

### LINKED ISSUE #13624: Adding log values to a plot with the text tool need improving
Problems:

1. It takes a long time to generate the list of logs to display (much longer than bringing up the sample logs dialog)
1. Picking a time series log print each time step value onto the graph (we should give options available from the log statistics)

### PR DESCRIPTION
**Pull request by dtasev**
## Description of work.

The [LabelTool](https://github.com/mantidproject/mantid/blob/master/MantidPlot/src/LabelTool.cpp) currently in Mantid uses a context menu to show the information for each available log, and depending on the information in the log can hide the whole screen.

This is now done via a Dialog, very similar to the _Sample Logs_ dialog when right-clicking a Workspace.

When left clicking on a plot using the **Label Tool**, the _Log Values_ button now shows the same context menu as _Workspaces_
6_with_multiple_ws

and when the button is clicked the Sample Log Dialog appears **for the selected workspace**.
It contains the new functionality described in the issue, a specific log statistic can be selected. If the log has no statistics, instead the Value and Units columns will be displayed

UML of the current structure of the classes (without methods):
uml

SampleLogDialogBase provides common functionality used by the child classes. The [void init(void)](https://github.com/mantidproject/mantid/commit/c3d3d2db1d79a99b43b7142e4eae7227d03dd4e1#diff-c0430e482e94c7ce3c7ee188231c87b0R86) is not virtual because the functionality should be common to child classes, it initialises the information into the QTreeWidget and loads the Log Statistics.
Derived classes have to implement their own [**ImportItem(QTreeWidgetItem)**](https://github.com/mantidproject/mantid/blob/6e4daf37057a177e9eef1d647bc4ffe6d0730bf1/MantidPlot/src/Mantid/SampleLogDialogBase.h#L78). 
## To test:

1. Functionality of the old Sample Dialog from the Workspaces Right Click Context Menu (picture 2), as the class was refactored. The functionality should **not** be changed.
   - How to test this: 
   - Use the Sample Dialog on any workspace, try importing different logs and see if they look correct/the same as the one from the Mantid Master branch or latest release version
   - Try importing multiple logs, with different filters, and see if they are correct
   - Try importing by using the button, double click, right click -> import, or any other ways that I haven't discovered
2. Functionality of the new Log Values Sample Dialog can be reached by plotting a spectrum of any workspace that has logs
   - How/What to test:
   - Use the Sample Dialog to import different logs' statistics, logs without statistics should have their value and units (if available) imported
   - Try importing multiple logs, you should not be allowed to select more than one, and it is intended
   - Try importing by using the button, double click, right click -> import, etc
   - Try importing a log from a plot that has 2 or more workspaces in it, Log Values will display all different workspaces in the plot and you can select the one you want
   - Make sure the logs displayed are _correct_ for the selected workspace

Fixes #13624 

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
When I load a dataset, right-click on the workspace and select `Sample Logs...` I get an unexpected exception. I am not sure where `m_tree` is initialized (see [this](https://github.com/mantidproject/mantid/pull/16982/files#diff-97f7cbbec15aa026a8a1ecc899c4049fL46) change, in `LabelToolLogValuesDialog` it is done [here](https://github.com/mantidproject/mantid/pull/16982/files#diff-930e77e758b77673802452100cf06479R51))

**Comment by DimitarTasev** [comment]
@raquelalvarezbanos This should fix the issue, the `QTreeWidget` was only initialised in one of the derived classes

**Comment by DimitarTasev** [comment]
Restarted build on Windows as this one had an unrelated crash http://builds.mantidproject.org/job/pull_requests-win7/10108/console

**Comment by raquelalvarezbanos** [comment]
Works as described.

Common functionality has been moved to the base class `SampleLogDialogBase`. I wonder if there's still common functionality that could be moved to the base class (for instance see [this](https://github.com/mantidproject/mantid/blob/756706b847bece4732fe91eb691800746ff14595/MantidPlot/src/Mantid/MantidSampleLogDialog.cpp#L72-L83) and [this](https://github.com/mantidproject/mantid/blob/756706b847bece4732fe91eb691800746ff14595/MantidPlot/src/Mantid/LabelToolLogValuesDialog.cpp#L65-L80) or  [this](https://github.com/mantidproject/mantid/blob/756706b847bece4732fe91eb691800746ff14595/MantidPlot/src/Mantid/MantidSampleLogDialog.cpp#L85-L95) and [this](https://github.com/mantidproject/mantid/blob/756706b847bece4732fe91eb691800746ff14595/MantidPlot/src/Mantid/LabelToolLogValuesDialog.cpp#L82-L92)). @DimitarTasev Please create a maintenance issue for this if you agree.

Also, do you want to mention this in the release notes?

**Comment by DimitarTasev** [comment]
@raquelalvarezbanos I agree about the refactoring, I've opened a new issue [here](https://github.com/mantidproject/mantid/issues/17566) 
About the release notes I couldn't find a section to add it to, but if it needs to be I can do that quickly

**Comment by raquelalvarezbanos** [comment]
Perfect, thanks for opening a new issue.

Regarding the release notes, I would probably mention this change, as it is an improvement to the GUI. I think a note could be added to `mantid\docs\source\release\v3.8.0\ui.rst`

**Comment by DimitarTasev** [comment]
@raquelalvarezbanos Done, it's added to the release notes under the Plotting Improvements section

**Comment by raquelalvarezbanos** [comment]
:shipit:

**Comment by DimitarTasev** [comment]
Rebuilding on OSX because of unrelated crash: http://builds.mantidproject.org/job/pull_requests-osx/9325/

**Pull request merged**
