### PR TITLE
SpectrumInfo: add Detector access

### LINKED ISSUE #17771: Add access to Detector to SpectrumInfo
See https://github.com/mantidproject/documents/blob/master/Design/Instrument-2.0/SpectrumInfo-rollout.md for details.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
`SpectrumInfo` now provides access to the underlying detector or detector group. This allows for refactoring algorithms that require more than basic information from the instrument for a spectrum, such as computing the solid angle as seen from the sample, which we are not supporting in `SpectrumInfo` (at least for now).

**To test:**

Thorough code review.

Fixes #17771.
No release notes, internal change (there might be a speedup for certain algorithms).

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
@reviewers: I had to fix an issue in `EstimateResolutionDiffraction`: Previously this algorithm computed L2 and theta for monitors (in a wrong way, as far as I can judge). `SpectrumInfo` sets `twotheta = 0` for monitors and defined `L1 + L2` as the source-detector distance, i.e., L2 is negative for monitors.

This way of defining things changes the resolution result for monitors, and breaks a unit test. I chose to define resolution as `0.0` for monitors. Does that make sense?

**Review by ianbush — COMMENTED** [review]
All the code changes look good.

**Comment by ianbush** [comment]
The code changes look good to me. I do not fully understand the implications of having the resolution defined as 0 for monitors, is it worth asking someone else to confirm if that is a good idea?

Ditto for defining twotheta as always being 0 for monitors, this seems like it should be good in most cases, but I am not sure if there are any exceptions?

**Comment by SimonHeybrock** [comment]
@ianbush I agree. I'll see if I can get a more definite statement regarding the monitors on slack today, otherwise I'll revert those changes.

**Comment by ianbush** [comment]
I think this is safe to go now :shipit:.

**Pull request merged**
