### PR TITLE
Fix string quote for NSIS v>=3

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

CMake >= 3.17 requires NSIS v3 to be able to generate the Windows package but our current NSIS template is not compatible with NSIS v3. This change ensures the package can build with NSIS v3.

**To test:**

On Windows:
* download and install [NSIS v3](https://sourceforge.net/projects/nsis/files/NSIS%203/) 
* run cmake, setting `ENABLE_CPACK` to `ON`
* in Visual Studio build the `ALL_BUILD` target followed by the `package` target
* a `.exe` file should be generated in the build directory.

*There is no associated issue.*

*This does not require release notes* because **it fixes an internal issue.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
I've kicked off a build with a package on windows to make sure this still works with NSIS v2 but the build is in a queue.

**Comment by martyngigg** [comment]
Build with package wit NSIS v2 has worked but with warnings that are on master apparently: https://builds.mantidproject.org/job/pull_requests-windows/36728/console.

**Review by alicerussell1 — COMMENTED** [review]
I don't know if this is just me, the package builds successfully but I then installed it and I am not able to open workbench (plot opens fine). I just get the error reporter appearing. If I open it from command line I get the following: 
```
Traceback (most recent call last):
  File "D:\MantidUnstableInstall\bin\mantid\utils.py", line 35, in import_mantid_cext
    lib = import_module(modulename, package)
  File "D:\mantidTestingPRs\external\src\ThirdParty\lib\python3.8\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed while importing _kernel: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MantidUnstableInstall\bin\mantid\utils.py", line 39, in import_mantid_cext
    lib = import_module(modulename.lstrip('.'))
  File "D:\mantidTestingPRs\external\src\ThirdParty\lib\python3.8\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '_kernel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MantidUnstableInstall\bin\launch_workbench.pyw", line 3, in <module>
    import workbench.app.start
  File "D:\MantidUnstableInstall\bin\workbench\app\start.py", line 15, in <module>
    from mantid.api import FrameworkManagerImpl
  File "D:\MantidUnstableInstall\bin\mantid\__init__.py", line 105, in <module>
    from mantid import kernel as _kernel
  File "D:\MantidUnstableInstall\bin\mantid\kernel\__init__.py", line 36, in <module>
    import_mantid_cext('._kernel', 'mantid.kernel', globals())
  File "D:\MantidUnstableInstall\bin\mantid\utils.py", line 44, in import_mantid_cext
    raise ImportError(msg)
ImportError: First import of "._kernel" failed with "DLL load failed while importing _kernel: The specified module could not be found.". Second import of "_kernel" failed with "No module named '_kernel'"
```

**Comment by martyngigg** [comment]
@alicerussell1 Thanks for testing. Is it a debug build by any chance?

**Comment by alicerussell1** [comment]
No I'm on a release build

**Comment by alicerussell1** [comment]
@martyngigg I just tried downloading the installer from the windows build you did with v2 and I have the same issue

**Review by alicerussell1 — APPROVED** [review]
This works correctly, the above issue is unrelated and will be fixed separately.

**Pull request merged**
