### PR TITLE
Updated documentation for CrystalField interface

### LINKED ISSUE #31887: Update documentation for CrystalField Python interface
The CrystalField interface uses the Mantid fit function. This means that properties of the fit function (for example `Exclude` 
https://docs.mantidproject.org/nightly/algorithms/Fit-v1.html#excluding-data-from-fit) are available. It would be good to mention this in the CrystalField interface documentation and also include a link to the page about the fit function.

### PR DESCRIPTION
**Pull request by SilkeSchomann**
**Description of work.**

Added a reference to the Mantid fit function as the crystal field fit function is essentially just a fit function and can use the same properties.

**To test:**

Check that reference makes sense and leads to the page for Fit v1.

Fixes #[31887](https://github.com/mantidproject/mantid/issues/31887).

*This does not require release notes* because it is only a small addition to existing documentation.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by Pasarus — DISMISSED** [review]

**Comment by gemmaguest** [comment]
@SilkeSchomann Could you squash these 3 commits into a single commit, seeing as they are all part of the same change? Give me a shout if you're not sure how to do that (probably easier to show than to explain!)

(Not a big deal if you're super busy right now but it's good practice to keep the commit history concise.)

**Comment by SilkeSchomann** [comment]
@gemmaguest It should be a single commit now

**Comment by gemmaguest** [comment]
@Pasarus could you re-approve?

**Review by Pasarus — APPROVED** [review]

**Comment by SilkeSchomann** [comment]
@mantidproject/gatekeepers Would be great to merge this. Formatting + Static Analysis got stuck after this was approved and I cannot trigger it again. It definitely passed before.

**Comment by DannyHindson** [comment]
Merging despite Formatting + Static Analysis job showing pending - I believe this was caused by a GitHub outage last week somehow. Job had previously run successfully on this PR

**Pull request merged**
