### PR TITLE
Set recursion depth for top level split to 1

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Original ticket [here](http://trac.mantidproject.org/mantid/ticket/11814)

**For testing:**
You can find the necessary python script [here](http://trac.mantidproject.org/mantid/attachment/ticket/11814/splitNaCl%20%282%29.py)

You need the data set SXD23767.nxs which can be found in the trainging pack.
Run the script. This should produce the workspaces _Split_ and _No_Split_. 

**Test for workspace with top level splitting**
1. Open the data set _Split_ into the VSI.
   - Confirm that the recursion depth entry of the source shows 1
   - Confirm that the recursion depth is actually 1. Change it to 5 - you should see a difference (finer granularity)

**Test for workspace without top level splitting**
1. Open the data set _No_Split_ into the VSI.
   - Confirm that the recursion depth entry of the source shows 5
   - Confirm that the recursion depth is actually 5. Change it to 1 - you should see a difference (coarser granularity).

### CODE REVIEW

**Comment by OwenArnold** [comment]
Could you please add something to the release notes about these changes. Probably to bug fixes http://www.mantidproject.org/ReleaseNotes_3_5_UI_Changes

**Comment by picatess** [comment]
Added information regarding these changes to the release notes

**Comment by OwenArnold** [comment]
Functionally correct. Some refactoring changes proposed.

**Comment by picatess** [comment]
Refactored the check for top level splitting. The refactored function is directly called from within [MDEWSource](https://github.com/mantidproject/mantid/blob/feature/11814_set_recursion_depth_for_top_level_split_to_1/Code/Mantid/Vates/ParaviewPlugins/ParaViewSources/MDEWSource/vtkMDEWSource.cxx#L237:L239) and [ViewBase](https://github.com/mantidproject/mantid/blob/feature/11814_set_recursion_depth_for_top_level_split_to_1/Code/Mantid/Vates/VatesSimpleGui/ViewWidgets/src/ViewBase.cpp#L302:L305). In the former case we are not going through the presenter, as this is a generic interface for both MDEvent- and MDHisto-based sources, whereas the recursion depth is only applicable for MDEvent-based sources.

**Comment by picatess** [comment]
* Changed the include guards
* Changed the unit test for MDEvent data with top level splitting

**Comment by picatess** [comment]
RHEL6 build seems to be a gcc4 [issue](https://bugzilla.redhat.com/show_bug.cgi?id=531483)

**Pull request merged**
