### PR TITLE
Add usage report to fitting minimizers and cost functions

### LINKED ISSUE #35813: Add usage reporting to fitting

### PR DESCRIPTION
**Pull request by jhaigh0**
**Description of work**

Added usage report to report what minimizers are being used. This is important data to collect for the potential replacement of the fitting engine.

**To test:**

Will need to have / get admin access to the usage reports site.

Make sure you have usage reporting switched on (may have to edit in your `mantid.properties` file)

 - Load in some data
 - Open a spectrum in the fitting window
 - Add a curve and remember / what minimizer is set
 - Run the fit
 - Check that a report has appeared under 'Functions'
 - You can try a few times with a few different minimizers (also try just running the Fit algorithm in the script editor).

Fixes #35813 

*This does not require release notes* because **it's not a user facing change**

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
I just had a go with the 'simplex', 'trust region' and 'BFGS' but they are not showing up on the usage reporting site. I think its updated once per day, so I wont be able to see today. So I will unassigne myself as I will be away next week. 

Is the plan to do cost function separately?

**Comment by jhaigh0** [comment]
That's interesting, I was able to see it update very quickly. Possibly you have to close Mantid to make it send the reports?

Ah I didn't know we wanted to cost function too but I can add that into this PR

**Comment by AnthonyLim23** [comment]
what script did you use to see it? Maybe mine is wrong, I cant even see any from you testing

**Comment by AnthonyLim23** [comment]
> 

The cost function is because I am not convinced we need to worry about implementing the Poisson cost function. If we do it will limit are options for new packages.

**Comment by jhaigh0** [comment]
I deleted the entries from my tests.
I just did a fit in the fitting GUI, closed Mantid, and refreshed the usage features query page.

No problem, I'll add that in now.

**Comment by jhaigh0** [comment]
Ah, I can see your tests in there now 👍
After this is approved, we'll have to remember to go and delete those, but I'll leave for now.

**Review by AnthonyLim23 — APPROVED** [review]
Looks good and after a short wait I can see the minimizer/cost function as a function name in usage stats.

**Pull request merged**
