### PR TITLE
Assign resolution properly on bin boundaries

### LINKED ISSUE #16119: TOFSANSResolution does not deal with uncertainty of the last bin edge?
In `TOFSANSResolution.cpp` line 114 we have:
```cpp 
  // Initialize Dq
  MantidVec &DxOut = iqWS->dataDx(0);
  for (int i = 0; i < xLength - 1; i++)
    DxOut[i] = 0.0;
```

For some reason the algorithm does not deal with the `Dx` of the last bin edge, and I don't understand if there is a reason for this, or if it is an oversight. This continues throughout the exec method of that algorithm.

@mdoucet Have a look at this, this might be relevant for you.

### PR DESCRIPTION
**Pull request by mdoucet**
This PR deals with two issues:
 1- The Q resolution values were not assigned properly, according to #16119.
     I changed my mind on this one. Playing around with the values at bin boundaries creates artifacts in the Dx array. It's preferable to leave it as it is so that both the workspace and the saved I(q) file can safely be used. The original problem only affects the last point of the distribution, only when you move to point data. That point has a dQ that is underestimated. It's best to deal with this in the refactor mentioned in #16119.
 2- The instrument scientists would like to update the EQSANS TOF resolution function.

**To test:**
- Make sure the system tests pass.
- Inspect the code.

Fixes #16119.

No release notes needed.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by ricleal** [comment]
If this is not urgent do you want to follow "The Boy Scout Rule" ?

> Leave your code better than you found it.

The TOFSANSResolution::exec is pretty big... Lizard gave me a CC of 21 and NLOC 122

Otherwise I'll merge it and we clean it any other time...

```
$ lizard Algorithms/src/TOFSANSResolution.cpp
================================================
  NLOC    CCN   token  PARAM  length  location
------------------------------------------------
       2      1     16      0       2 Mantid::Algorithms::TOFSANSResolution::TOFSANSResolution@30-31@Algorithms/src/TOFSANSResolution.cpp
      26      1    207      0      29 Mantid::Algorithms::TOFSANSResolution::init@33-61@Algorithms/src/TOFSANSResolution.cpp
       4      1     17      1       4 Mantid::Algorithms::TOFSANSResolution::getTOFResolution@66-69@Algorithms/src/TOFSANSResolution.cpp
     122     21   1256      0     167 Mantid::Algorithms::TOFSANSResolution::exec@71-237@Algorithms/src/TOFSANSResolution.cpp
--------------------------------------------------------------
1 file analyzed.
==============================================================
NLOC    Avg.NLOC  AvgCCN  Avg.token  function_cnt    file
--------------------------------------------------------------
    176      38.5     6.0      374.0         4     Algorithms/src/TOFSANSResolution.cpp

=========================================================================================
!!!! Warnings (cyclomatic_complexity > 15 or parameter_count > 100 or length > 1000) !!!!
================================================
  NLOC    CCN   token  PARAM  length  location
------------------------------------------------
     122     21   1256      0     167 Mantid::Algorithms::TOFSANSResolution::exec@71-237@Algorithms/src/TOFSANSResolution.cpp
==========================================================================================
Total nloc   Avg.NLOC  AvgCCN  Avg.token   Fun Cnt  Warning cnt   Fun Rt   nloc Rt
------------------------------------------------------------------------------------------
       176      38.5     6.0      374.0        4            1      0.25    0.79
```

**Comment by mdoucet** [comment]
We're talking about refactoring the way we track dQ in #16119. It's probably best to do this work then.

**Comment by ricleal** [comment]
OK then. I'm happy with the edits. I'll ship it once checks are completed.

**Comment by ricleal** [comment]
@mdoucet : Can you check the system tests errors? Is it related to your changes?

**Comment by ricleal** [comment]
Minor changes. The code will be refactored as part of ticket #16119. Tests OK.
:shipit:

**Pull request merged**
