### PR TITLE
Documentation for Powder ISIS Script

### LINKED ISSUE #14656: Create a documentation for Powder ISIS script
The `PowderISIS` script has been integrated with previous mantid release and now that there are working system tests with `Polaris`, `Hrpd` &` Gem`. It would be useful to create a detail documentation to update the scientists with the recent changes that have been made and also a summary on how to utilise the pref file.

### PR DESCRIPTION
**Pull request by shahrozahmed1**
Fixes  #14656 

Documentation for `\scripts\PowderISIS`

**To Test**
General review - if it all makes sense and able to follow the provided steps
By following the steps, the same structure of the folders and files is also produced
@FedeMPouzols as you are slightly familiar with the script; anything else which I could also include?

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
Only one image displays on the doc page: docs/source/images/PowderISIS_pre_structure.png.
The other ones are not found by sphinx. I think that the problem is that their extension is PNG (uppercase). You have to use the same capitalization in the file name and the link to the image/file, otherwise the images are not displayed on platforms other than windows.

**Comment by FedeMPouzols** [comment]
Oh, also with scale 20% the images look tiny with my browser. Have you tried on your browser?

**Comment by shahrozahmed1** [comment]
@FedeMPouzols yes I built it locally and it worked fine for me on chrome, however ill fix the capital .PNG issue now

**Comment by FedeMPouzols** [comment]
The documentation reads very good and exhaustive! There's just an issue with the paths/index. If you open mantid, an go to help->Python API->Techniques, you don't see ISIS powder there. And the same happens with the html pages. So this documentation can be found as an individual page, but it is not linked from the index pages. I think we need to add it to the index, in [this index.rst file](https://github.com/mantidproject/mantid/blob/master/docs/source/api/python/index.rst), similarly as with the calibration page. Then it should become visible from Python API.

**Comment by FedeMPouzols** [comment]
Works well, both the html and qthelp documentation.

**Pull request merged**
