### PR TITLE
Improvements to ICat path replacements

### PR DESCRIPTION
**Pull request by gemmaguest**
**Description of work.**
This PR adds the following improvements related to ICat paths:
- Fix a bug where the replacement prefix in `Facilities.xml` was being overridden with an empty path when the user property `icatDownload.mountPoint` is not set.
- Enable path replacement for Windows. Previously the code was always using the original path from ICat.
- Add a replacement string in the config for Windows. This is the fully qualified path for the ISIS archive.
- Update the regex in the config file so that it will match either the short (`\\isis\inst$`) or fully qualified (`\\isis.cclrc.ac.uk\inst$`) path so we don't need to worry about which one ICat returns (it actually still returns the short path).

Note that this relates to a recent change where [this script](https://github.com/mantidproject/mantid/blob/master/Framework/DataHandling/src/ISISDataArchive.cpp#L33) has been updated to return the fully qualified path.

**Report to:** Jos

**To test:**
Should be tested by someone at ISIS, ideally on both Windows and Linux/Mac.
- From the `Catalog` menu select `Login` and enter your credentials
- From the same mentu select `Search` and perform a search. You can just click `Search` on the dialog to search for all investigations for the default instrument.
- Double click on a result and then select one of the run files and click `Load` (you may need to try a different investigation if you choose one that doesn't have any runs).
- Check the history of the loaded run - the Filename path should start with `/archive` for linux/mac or `\\isis.cclrc.ac.uk\inst$` for Windows.
- Try setting `icatDownload.mountPoint=/bad/path` to a path that doesn't exist and restart Mantid. Re-run the above instructions and you should find that the Filename path is now your local Mantid save directory. This is because the file was not found at the replaced path and was downloaded locally instead.

*There is no associated issue.*

*Release notes to follow*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
I've tested this on Linux and everything appears to work as expected. @DTasev @keeeto Any chance you could check Windows/Mac?

**Comment by DTasev** [comment]
👍 I'll try out Windows

**Comment by gemmaguest** [comment]
@DTasev Sorry for the multiple commits. My windows machine is down so I'm attempting to fix the test by guesswork!

**Comment by DTasev** [comment]
No worries I was just enjoying the number of `\` in the current string 😄

**Comment by DTasev** [comment]
👍 Added some more `\` and now the archive is being searched successfully

**Review by dtasev — APPROVED** [review]

**Pull request merged**
