### PR TITLE
EnggDiffraction::fixes red symbol displayed when run number given

### LINKED ISSUE #14006: EnggDiffraction: fix paths issue with the MWRun, and use EnginX paths for calibration
At the moment, after #13934, if you type a run number that is in the EnginX specific data folder the MWRun doesn't see it in the Mantid path and shows the red symbol.

To fix this we need to add the ENGIN-X folder to the Mantid path whenever the EnggDiffraction interface is open. Then, on close event, remove it from the path.

The place where the path is added currently is:
https://github.com/mantidproject/mantid/blob/master/MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffractionPresenter.cpp#L452-L463
and
https://github.com/mantidproject/mantid/blob/master/MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffractionPresenter.cpp#L478-L479

Together with this, the calibration folder and data folder (in the settings tab) should follow the conventions described in the last point of #13376:
- `C:\EnginX_Mantid\Calibration`
 - `C:\EnginX_Mantid\Data`
 - `C:\EnginX_Mantid\User`
 - `C:\EnginX_Mantid\User\<RBNumber>\Calibration` (where all the files that go to `C:\EnginX_Mantid\Calibration` for a particular user/RBNumber should also go.)

(this is already working for focusing output files from #13934).

### PR DESCRIPTION
**Pull request by shahrozahmed1**
Fixes #14006

Go to: `Interface/Diffraction/Engineering Diffraction`

When a EnginX specific run number is given to `Calibration/Vanadium #:` or  `Calibration/Calibration sample #:` or any `Run #:` under `Focus` tab, it should not display red `*` symbol next to the text-box.
Make sure the file is within the path provided to `Manage User Directories` or  `Engineering Diffraction Analysis/Settings` and `Search Data Archive` is **not** checked

### CODE REVIEW

**Comment by mantid-roman** [comment]
Is this still in progress?

**Comment by shahrozahmed1** [comment]
@mantid-roman yes, there are other small changes that I am thinking of included on this branch which should be implemented soon

**Comment by mantid-roman** [comment]
What is the range of good run numbers?

**Comment by mantid-roman** [comment]
It only works if the run number is prefixed with ENGINX

**Comment by shahrozahmed1** [comment]
@mantid-roman I'v slacked you the full settings required, please let me know if you're still having trouble with this

**Comment by mantid-roman** [comment]
Still the same

**Comment by shahrozahmed1** [comment]
@mantid-roman:: MWRunFiles does not seem to like '-' characters hence it was not finding the instrument `ENGIN-X`, but the previous commit should fix the problem

**Pull request merged**
