### PR TITLE
Pass custom axes properties to workbench plotting

### LINKED ISSUE #24767: Workbench plotting doesn't allow for log axes
SANS' use of the matplotlib plotting functions (for workbench) requires loglog axes. Currently this requirement cannot be passed into `plot` in the mantidqt plotting functions, so a fig must be created and passed into `plot`. Assuming other interfaces will require log axes, this functionality should be moved to mantidqt plotting functions to reduce code repetition.

### LINKED ISSUE #24768: Workbench plotting can't accept workspace names without user selection
With MantidPlot plotting, one could pass in workspace names and the workspace indices to plot into a function. Currently, passing in workspace names to the matplotlib plotting functions produces a dialog box for users to select the spectra they wish to plot.

SANS has a case where plotting of workspaces from workspace names is only required for certain spectra, so no user dialog should occur.

Mantidqt plotting functions should be changed so that if the workspaces passed into the function are names, the ADS is called to retrieve the workspaces (rather than doing this on the interface side)

### PR DESCRIPTION
**Pull request by TTitcombe**
**Description of work.**
This PR changes how matplotlib fig and axes objects are created in the plotting functions to allow passing in of axes properties (e.g. to set the scale of the axes) and the title of the window created when showing the plot.

This PR also allows workspace names to be passed into the main matplotlib `plot` function. (This functionality is currently available but it requires the user to select workspace indices)

Finally, it changes the way SANS plots in Workbench to make use of the new functionality

**Report to:** nobody

**To test:**
In workbench...
1. Interfaces -> SANS -> SANS v2 experimental
2. Load the attached user file and batch file
3. In the Beam Centre tab, click run.
4. A plot should be produced with log axes and a window title "74044_beam_centre_finder"
5. Once that has finished running (it can be a couple of minutes), in the Runs tab select the "Plot results" button in the bottom right corner and then press "process all" at the top
6. An empty plot should be created. As each set of data is successfully reduced the data should be plotted onto the graph without overwriting the graph's current data. N.b. for the data provided the data should look the same, but the legend should still show 4 lines.

Fixes #24767 
Fixes #24768 

*This does not require release notes* because **internal change to the way matplotlib plotting is done.**

**Data**
[loqPRData.zip](https://github.com/mantidproject/mantid/files/2875100/loqPRData.zip)

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by Pasarus — DISMISSED** [review]
I like how this is a nice utility change, allowing the passage of both string and workspace objects to the plotting functions. Code works as described. :+1:

**Review by AndreiSavici — CHANGES_REQUESTED** [review]
I have two questions: 
 1. why do we restrict ourselves to plotting matrix workspaces from the workbench? The plotting functions also accept MDHistoWorkspaces.
 2. Why do we restrict the sequence types? Is there a reason why I can't have a numpy array of workspaces? We should check instead if it's iterable, and not a string

**Comment by TTitcombe** [comment]
@AndreiSavici In general, I'm not sure why current workbench plotting checks for MatrixWorkspaces. This PR is merely an extension on workbench plotting functionality - it's not restricting plotting to lists or MatrixWorkspaces.
I would imagine that both 1. and 2. boil down to not needing to as of yet - for example, the functionality to accept workspaces names is necessary for ISIS SANS in workbench, and we will only ever pass in a list of workspace names.
I feel these changes should be implemented if and when an interface which requires them gets ported over to workbench.

**Comment by martyngigg** [comment]
@AndreiSavici I originally put that `MatrixWorkspace` check in and it was probably overly restrictive. I wanted a `plot` function at a higher level that the `mantid` one to contain most of the common functionality for creating a figure etc but I see no reason that it should be able to handle `MDHistoWorkspaces` too. I'd suggest a new PR for that though.

**Review by AndreiSavici — APPROVED** [review]

**Pull request merged**
