### PR TITLE
Upgrade to Qt 5.15

### LINKED ISSUE #34265: Upgrade conda to require qt 5.15
**Describe the outcome that is desired.**
By the end of this work the codebase should be able to run with Qt 5.15. This should hopefully solve #34081 without us needing to change our code.

**Describe any solutions you are considering**
Update the developer and package conda-recipes to require Qt 5.15 as a minimum. 

**Additional context**
5.15 is the final Qt 5 release. It is in support mode and still receiving bugfixes. We cannot yet move to Qt 6 until conda-forge make it available.

### PR DESCRIPTION
**Pull request by martyngigg**
**Note to gatekeepers. Please merge mantidproject/conda-recipes#84 when this is merged.**

**Description of work.**

Updates Qt on all platforms to 5.15. This is the last release of the 5.x series.

**To test:**

* This should be test on all platforms ideally. Packages have been built to facilitate testing:
  * macOS/Linux: https://builds.mantidproject.org/job/build_packages_from_branch/154/
  * Windows: https://builds.mantidproject.org/job/build_packages_from_branch/158/
* Build and check workbench starts.
* Have a play to see if anything obvious is broken. 

Fixes #34265 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
I have a test package build at https://builds.mantidproject.org/job/build_packages_from_branch/136/ so I'm deliberately leaving the build warnings/failures here until I can confirm the packages look okay.

**Comment by ConorMFinn** [comment]
Tested on macOS, works well 👍

**Comment by peterfpeterson** [comment]
Does this require changes to the runtime requirements in [`mantidqt` conda recipe](https://github.com/mantidproject/conda-recipes/)?

**Comment by martyngigg** [comment]
> Does this require changes to the runtime requirements in [`mantidqt` conda recipe](https://github.com/mantidproject/conda-recipes/)?

Thanks. I had the branch on the repo but I hadn't created a PR. I've added a note to the instructions now.

**Comment by sf1919** [comment]
Tested on Windows and seems to work as normal

**Comment by martyngigg** [comment]
@peterfpeterson Any chance you could give this a quick check on Linux?

**Comment by DanielMurphy22** [comment]
I'll test on Ubuntu 18.04

**Review by DanielMurphy22 — APPROVED** [review]
Works for me on Ubuntu 18.04 and Sarah and Conor have checked Windows and MacOS. Good job!

**Comment by peterfpeterson** [comment]
The new package in `thomashampson/label/qt515_test` worked and even fixed a bug we were seeing related with the help.

**Pull request merged**
