### PR TITLE
Remove the RebinningCutter from the VSI

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
See original ticket [#10883](http://trac.mantidproject.org/mantid/ticket/10883)

### CODE REVIEW

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by picatess** [comment]
Jenkins, retest this please.

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by mantid-roman** [comment]
@picatess Could you merge master and resolve the conflicts please?

**Comment by picatess** [comment]
@mantid-roman Master is merged and the conflicts are resolved.

**Comment by mantid-roman** [comment]
Found issues:
1. Select the 'builtin' node. BinMD/SliceMD are enabled but do nothing when clicked. 
2. SliceMD. The dataset is red. Deselect then re-select autoscaling. The dataset gets the correct colours.
3. SliceMD then Scale. Remove binning. Crash.
4. BinMD. Delete the source workspace in the mantid workspace dock. Remove binning. Error windows and dialogs pop up. Re-load the workspace and try to display it in VSI. Crash.
5. BinMD. Delete the temp workspace in mantid dock. VSI hides. Open the original workspace in the VSI again. There are 2 source nodes instead of 1 now.
6. Open a histo workspace in the VSI. The minimum and maximum controls are empty. The dataset is red.

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by picatess** [comment]
@mantid-roman 
1-5 are handled, 6 I could not reproduce

**Pull request merged**
