### PR TITLE
LoadILLTOF monitor numbering

### LINKED ISSUE #17954: LoadILLTOF Monitor Numbering
Some changes introduced in the histogram roll, #17808, out have meant the monitors are not loaded correctly in `LoadILLTOF`.

This ticket should include some better unit tests for the loaders to catch such issues.

### Expected behavior

The numbering for the monitors when running LoadILLTOF for IN5 data gives something like the following:

```
Index Spec No Det ID Monitor
0      1      1001   True
1      2      1002   True
2      3      1003   True
3      4      1      False
```

### Actual behavior

Actual numbering involves since changes in #17808 

```
Index Spec No Det ID Monitor
0      1      1      True
1      2      2      True
2      3      3      True
3      4      1      False
```

### Steps to reproduce the behavior

Load data for IN4/5/6. Check the detector IDs for monitors. They have the same detector IDs as some of the detectors.

### Platforms affected

All.

### PR DESCRIPTION
**Pull request by ianbush**
Fixes issue with monitor not being loaded correctly for ILL ToF data.

**To test:**

Load a data file such as ILL/IN6/164192.nxs or ILL/IN5/104007.nxs. After loading check the detector table, to see that the monitors do not have the same detector IDs as any detectors.

Check the unit test additional now makes sense.  Can also check it fails if the line `m_localWorkspace->getSpectrum(spec).setDetectorID(monitorIDs[spec]);` (line 554) is commented out in `LoadILLTOF.cpp`

Fixes #17954 .

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
I tried loading suggested files from the unit test data without the fix and could not find any monitors on 'show data' or 'show detectors'. Is this because they have the same numbers as detectors?

**Comment by ianbush** [comment]
@KarlPalmen Yes, that is correct, they stop showing up as monitors in 'show data' due to the numbering. I might have been wrong in what I put in the original ticket, and in show detectors they also show up as not being monitors.

For IN6 if see detector IDs 1, 2, and 3 repeated then you are seeing the bug.

**Comment by KarlPalmen** [comment]
Thank you for clarifying. I also see the duplicate numbers in the first 6 detectors of the IN6 example. I'll go ahead and test it.

**Comment by KarlPalmen** [comment]
Test shows monitors and gives them unique detector ID. :shipit:

**Pull request merged**
