### PR TITLE
Rearange Elwin Layout

### LINKED ISSUE #32475: Adjust Elwin layout to better accomidate smaller screens
**Describe the outcome that is desired.**
The recent changes to the Elwin tab have made the data input section quite large and with a significant minimum size that makes it difficult to use on low resolution screens.

This will require some changing in the UI file so that everything scales correctly like in the fit tabs.

### PR DESCRIPTION
**Pull request by Harrietbrown**
**Description of work.**

This PR makes changes to the Elwin tab to make it more user friendly.

There is currently a bug in master that has been fixed in release next, loading data in the file tab will not work until that is incorperated into master.

**To test:**

1. Open Indirect Data Analysis.
2. In the Elwin tab check that you can resize the data input section.
3. check that you can load data in the file input tab and run.
4. check that you can load data in the workspace tab and run.

Fixes #32475

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by sf1919** [comment]
I don't think this has the changes I made in #32550 integrated yet as it crashed when I tried to load a file.

**Comment by Harrietbrown** [comment]
> I don't think this has the changes I made in #32550 integrated yet as it crashed when I tried to load a file.

That should be working now

**Review by sf1919 — DISMISSED** [review]
I have tested this PR and it works well. I have reviewed the code and its looks like a good change to the ui.

I'm not sure why it's failed the cppcheck but hopefully this is just a case of an issue with the server rather than the code. Therefore I am happy to approve.

**Comment by DavidFair** [comment]
@Harrietbrown You'll want to rebase this on main, as the cppcheck count went down by 1. This should be solved by next week as we're in the process of setting our count to 0

**Review by sf1919 — APPROVED** [review]
I have re-tested this and re-reviewed the code and everything still works as it did before and I am happy to approve it. 

There is currently a problem with loading workspaces (as opposed to loading files through the add workspace dialog). This has been caused by another PR and is raised for fixing elsewhere (#32677). In fact that issue is blocked by this one so once this is merged it can be tackled.

**Pull request merged**
