### PR TITLE
16762 biosans trap gravity

### LINKED ISSUE #16762: HFIR BioSANS Trap and Gravity features
Issues:

- [ ] 1. Beam Center Determination:
 - Use gravity for wing detector.
 - Must be calculated after the sensitivity correction: 
   - Note: Tests show that a hole appears at the maximum???

- [x] 2. Beam Trap:
 - 25.4 is now 76.2
 - Default 50.8
 - If 2 traps in use, use the largest one.

- [x] 3. Sensitivity Correction Implementation:
 - The problem is in the Solid Angle correction. Need the change the `cos^2` term (?).
https://github.com/mantidproject/mantid/blob/master/Framework/WorkflowAlgorithms/src/SANSSolidAngleCorrection.cpp#L151
 - Ryan?

- [x] 4. `MaskDetectorSide(‘Front’)` and `MaskDetectorSide(‘Back’)` are not working for Wing detector.

- [x] 5. `wavelength_spread` metadata is now in `%`. Need to change the loader:
https://github.com/mantidproject/mantid/blob/master/Framework/DataHandling/src/LoadSpice2D.cpp#L28
- [x] 6. Carry transmission from the main detector and feed it into the wing detector reduction (2 values):
 - Sample transmission
 - Background transmission

- [x] 7. Sensitivity Correction. Stripping pattern after the correction.

- [x] 8. Code in python a new general `EQSANSPatchSensitivity.cpp` using an arbitrary degree polynomial (default 6?).

- [x] 9. Tranmission issue (Mathieu):
```Python
SANSSensitivityCorrection(Filename=flood_field_file_raw,
                                                  UseSampleDC=False,   DarkCurrentFile=dark_curr_file_main,
                                                  MinEfficiency=0.3, MaxEfficiency=1.7,
                                                  FloodTransmissionValue=0.5,
                                                  FloodTransmissionError=0.05,
                                                  MaskedFullComponent="wing_detector",
                                                  OutputSensitivityWorkspace="sensitivity_raw",
                                                  ReductionProperties=ReductionSingleton().property_manager)
```
Just add `FloodTransmissionValue` and `FloodTransmissionError` to the algorithm call.

______________

# Test version:

`/SNS/users/rhf/mantid/Build/bin/MantidPlot`
___________________

6.

After running the reduction for the main detector, see all generated workspaces:
```
mtd.getObjectNames()
['__transmission_sample',
#  '__transmission_raw_BioSANS_exp318_scan0024_0001.xml',
#  '__transmission_empty',
#  'BioSANS_exp318_scan0024_0001_main_Iq',
#  'BioSANS_exp318_scan0024_0001_main_Iq_wedge_90',
#  'BioSANS_exp318_scan0024_0001_main_Iq_wedge_0',
#  '__dark_current_BioSANS_exp318_scan0009_0001',
#  'BioSANS_exp318_scan0024_0001_main',
#  '__TMP0x7f97ac48aa70',
#  'BioSANS_exp318_scan0024_0001_main_Iqxy',
#  '__beam_finder_BioSANS_exp318_scan0021_0001',
#  '__flood_data_BioSANS_exp318_scan0008_0001',
#  '__sensitivity_BioSANS_exp318_scan0008_0001']
```

The `__transmission_raw_<filename>` is the transmission value + error for the corresponding file.

Retrieve those values as:

```
ws = mtd['__transmission_raw_BioSANS_exp318_scan0024_0001.xml']
sample_trans_value = ws.readY(0)[0]
sample_trans_error = ws.readE(0)[0]
```

In the wing detector reduction, use the command below to set the transmission values:

```python
# Scattering
SetTransmission(sample_trans_value, sample_trans_error)

#Background
SetBckTransmission(sample_trans_value, sample_trans_error)
```

### PR DESCRIPTION
**Pull request by ricleal**
Description of work.

See #16762 .

**To test:**
- All tests must pass (including system tests!)
- Run: `/HFIR/samba/cg3/IPTS-15781/exp332/Shared/shuo_test335.py`

This file has all the new options. Reduces both main and wing detectors.

This has been incrementally changed for weeks...

Fixes #16762 .

No release notes for now.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by ricleal** [comment]
@mdoucet : Can you make sure this doesn't break any EQSANS stuff?
Not sure if you can be the "oficial" tester as you participated on this...

**Comment by mdoucet** [comment]
@ricleal I tested a reduction for EQSANS. I also checked that the patch sensitivity still works for EQSANS.

**Comment by ricleal** [comment]
@AndreiSavici : Can you test this for me?
Mathieu tested it (He can not be the official tester as he also participated on this), Beamline scientists also tested this. It looks good to us.

**Comment by AndreiSavici** [comment]
It does not crash. It has some output :grinning: Since instrument scientists are OK, I would say :shipit:
The failed build is fixed in master

**Pull request merged**
