### PR TITLE
Make I0MonitorIndex Optional

### LINKED ISSUE #15075: ReflectometryReductionOne and ReflectometryReductionOneAuto should not need I0MonitorIndex
Request from Tim Charlton. Refm is missing the monitor, but we want to be able to proceed with the reduction anyway.

### PR DESCRIPTION
**Pull request by OwenArnold**
Fixes #15075.

**Tester**
- Unit tests and System tests should pass
- Tim Charlton should be given the opportunity to test this out

### CODE REVIEW

**Comment by OwenArnold** [comment]
@AndreiSavici @quantumsteve This should fix one of Tim Charlton's problems. I'll get one of the PR packages to him so that he can test it out.

**Comment by FedeMPouzols** [comment]
Does this need a bit of testin?  Did Tim Charlton cheked this yet?

**Comment by MattKing06** [comment]
@FedeMPouzols I've sent the installer to Tim, I'm just waiting on his response.

The only thing that I can think to test is whether the algorithms still crash when you don't supply the monitor related parameters either via the algorithm properties or the parameter file of the instrument.
This is the script that Tim reported to give errors:
```python
TransRaw = LoadEventNexus(Filename='REF_M_22355_event.nxs')
Ref = LoadEventNexus(Filename='REF_M_22376_event.nxs')
Trans = CreateTransmissionWorkspaceAuto(TransRaw,AnalysisMode='MultiDetectorAnalysis')
IvsQ, IvsLam, thetaOut = ReflectometryReductionOneAuto(Ref,AnalysisMode='MultiDetectorAnalysis', SampleComponentName='sample-position')
```

Apart from that, perhaps testing that other reflectometry scripts are still producing the same results.

Otherwise I think it's necessary that Tim validates that the changes are correct.

**Comment by FedeMPouzols** [comment]
Ah ok, good. @MattKing06 : It just showed up in my list of PRs ready but without a tester, as you had unassigned yourself. All good then. Just go ahead when Tim takes a look at it if everything looks good.

**Comment by OwenArnold** [comment]
@MattKing06 This is currently not merging cleanly with Master. Could you please take a look?
@raquelalvarezbanos Do you know how Tim got on with this fix?

**Comment by raquelalvarezbanos** [comment]
@OwenArnold: @MattKing06 hasn't heard back from Tim yet. I'll tell him to ask Tim about this when he is back.

**Pull request closed without merging**
