### PR TITLE
Create python algorithm SelectNexusFilesByMetadata

### LINKED ISSUE #17272: Create algorithm for selecting nexus files based on metadata criteria
At ILL, a new algorithm is needed to select the nexus files from the given file list, which satisfy given metadata criteria, without loading the data itself.

### PR DESCRIPTION
**Pull request by gvardany**
This PR adds a new python algorithm for filtering of multiple nexus files by metadata without loading.

**To test:**

1. Collect some set of files.
2. Pick some nexus metadata entries, and build some criteria from them.
3. Run the algorithm following the example in docs.
4. Check in the returned files, that the criterion is indeed satisfactory.
5. Try more edge cases you can think of.

Fixes #17272 .

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AndreiSavici** [comment]
The algorithm works nicely with SNS event nexus files.
You disabled `consider-using-enumerate`. You should use enumerate instead of the range of len.

```
for i in range(len(splitted)):
    if i%2==1:
        print splitted[i]
```

could be replaced by:

```
for i,s in enumerate(splitted):
    if i%2==1:
        print s
```

In the help file you should mention that if your Nexus entry is an array, it will use the first value (some people would probably want to use the average) 

**The main problem with this algorithm is the name.** `FindFiles` should be replaced with something like `SelectHDFFilesByCriteria` or something like that. You don't need to find files, you select them. And not all files, only hdf ones, that meet a certain condition.  Your current name is too general, and does not explain what the algorithm does

**Comment by gvardany** [comment]
@AndreiSavici Thanks for the review, I will change to enumerate in the loop and add a note about the first value in array. Regarding the name, I was first thinking about `FilterNexusFilesByMetadata` what do you think?

**Comment by AndreiSavici** [comment]
@gvardany `Filter` might mean that you do some event filtering. I would use `SelectNexusFilesByMetadata`

**Comment by gvardany** [comment]
PR was closed due to renaming of branch. See #17300.

**Pull request closed without merging**
