### PR TITLE
Fix zeropadding for IMAT in Facilities.XML

### PR DESCRIPTION
**Pull request by dtasev**
A quick change that fixes being able to load IMAT workspaces through the data archive.

No related issue.

### CODE REVIEW

**Comment by DavidFair** [comment]
Tested locally and it now correctly picks up IMAT filenames :shipit:

**Comment by martyngigg** [comment]
@DavidFair Have their filenames always been padded to 8 digits or is it a recent change?

**Comment by martyngigg** [comment]
I've just checked the runs in cycle 15_1 and they are all padded to 8 digits.

**Comment by DavidFair** [comment]
Sorry - yes they have always had 8 digits as it is a (relatively) new instrument.

**Pull request merged**
