### PR TITLE
Sphinx 9 deprecations

### LINKED ISSUE #37804: Fix sphinx file path deprecation warning
**Describe the outcome that is desired.**
Fix this deprecation warning in the doc tests:

```
RemovedInSphinx90Warning: Sphinx 9 will drop support for representing paths as strings. Use "pathlib.Path" or "os.fspath" instead
```

**Describe any solutions you are considering**
Using `pathlib.Path` or `os.fspath` to represent paths instead of strings

### PR DESCRIPTION
**Pull request by jclarkeSTFC**
At the time of writing we are using Sphinx 8, but generating the docs gives warnings about the use of strings to represent file paths not being allowed in Sphinx 9. 
- Replaced strings representing file paths with `pathlib.Path` objects
- Replaces `tags.tags` with `tags`

Fixes #37804. 

### To test:
- Build docs, no warnings
- Should be no warnings in the doc test build either (see #37804 for the message you get when the warnings are present)
- Check that the docs look correct and the links work
- Check release note generation (I changed `amalgamate.py`)

*This does not require release notes* because **it has no effect on the user.**

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by sf1919** [comment]
Given you are putting this in now is it likely to be merged into main before code freeze? Thats still about 2 weeks away.

**Comment by jclarkeSTFC** [comment]
> Given you are putting this in now is it likely to be merged into main before code freeze? Thats still about 2 weeks away.

Yes should be done by then

**Comment by sf1919** [comment]
Maybe change the milestone?

**Review by jhaigh0 — COMMENTED** [review]
Unfortunately when viewing the index pages for, Algorithms, Concepts, etc. I'm not seeting any css
image

I did get a failure when building the docs `43>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'C:\Users\bya67386\work\mantid\build\CMakeFiles\a174ffb83d39874e18c7afe905d635e0\docs-html.rule;C:\Users\bya67386\work\mantid\docs\CMakeLists.txt' exited with code 1.` 
And some warnings (although not the deprecation warnings.) but this might be to do with my weird build problems.

**Comment by jclarkeSTFC** [comment]
> Unfortunately when viewing the index pages for, Algorithms, Concepts, etc. I'm not seeting any css image
> 
> I did get a failure when building the docs `43>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'C:\Users\bya67386\work\mantid\build\CMakeFiles\a174ffb83d39874e18c7afe905d635e0\docs-html.rule;C:\Users\bya67386\work\mantid\docs\CMakeLists.txt' exited with code 1.` And some warnings (although not the deprecation warnings.) but this might be to do with my weird build problems.

This should be fixed now

**Review by jhaigh0 — APPROVED** [review]
All checks look okay, amalgamated release notes are working fine.

No more warnings when building.

**Pull request merged**
