### PR TITLE
Add new GenerateGoniometerIndependentBackground algorithm

### PR DESCRIPTION
**Pull request by rosswhitfield**
**Description of work**

Extract background from multi-angle dataset

[899](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=899)

**Purpose of work**

**Summary of work**

**Further detail of work**

**To test:**

Requires SNS data

```python
from mantid.simpleapi import *
inputdir='/SNS/SEQ/IPTS-22120/nexus/'
outputdir='/tmp/'
runs=range(263341,263518+1)    # SEQ 5 K @ 100 meV, 0 Tesla

# Load run numbers to group
for r in runs:
    LoadEventNexus(Filename=inputdir+f'SEQ_{r}.nxs.h5',OutputWorkspace=f'SEQ_{r}.nxs')
ws_ev = GroupWorkspaces(GlobExpression='SEQ_[0-9]*.nxs')

Ei=99.30775803401971
T0=29.72685640862497

ws,_=DgsReduction(SampleInputWorkspace=ws_ev,
                              SampleInputMonitorWorkspace=ws_ev,
                              IncidentEnergyGuess=Ei,
                              TimeZeroGuess=T0,
                              UseIncidentEnergyGuess=True,
                              IncidentBeamNormalisation='None',
                              EnergyTransferRange='{0},{1},{2}'.format(-0.51*Ei,0.02*Ei,0.95*Ei),
                              TimeIndepBackgroundSub=False,
                              CorrectKiKf=True,
                              SofPhiEIsDistribution=False)
# Generate grouping #
wsg=PreprocessDetectorsToMD(ws[0])
tt=np.degrees(wsg.column('TwoTheta'))
phi=np.degrees(wsg.column('Azimuthal'))
detID=wsg.column('DetectorID')

tt_step=5
phi_step=10

tt_nsteps=int(np.ceil((tt.max()-tt.min())/tt_step))
phi_nsteps=int(np.ceil((phi.max()-phi.min())/phi_step))


det_group_list=[[[] for i in range(phi_nsteps)] for j in range(tt_nsteps)]
for t,p,d in zip(tt,phi,detID):
    ind_tt=int(np.floor((t-tt.min())/tt_step))
    ind_phi=int(np.floor((p-phi.min())/phi_step))
    det_group_list[ind_tt][ind_phi].append(d)

# Save a .xml for the grouping and use only groups with detector pixels
detlist=[]
with open(outputdir+'SEQ_group_{0}x{1}.xml'.format(tt_step,phi_step),'wt+') as f:
    f.write('<?xml version="1.0" encoding="UTF-8" ?>\n<detector-grouping instrument="SEQUOIA">\n')
    det_group=-1
    for i in range(tt_nsteps):
        for j in range(phi_nsteps):
            dets=det_group_list[i][j]
            if len(dets)>0:
                detlist.append(dets)
                det_group+=1
                f.write('<group name="{}"><detids val="{}"/> </group>\n'.format(det_group,str(dets).lstrip('[').rstrip(']')))
    f.write('</detector-grouping>')

wsbkg = GenerateGoniometerIndependentBackground(ws,
                                                GroupingFile=outputdir+'SEQ_group_{0}x{1}.xml'.format(tt_step,phi_step),
                                                PercentMax=17 # this equals 30 workspace
)

#SaveNexus(InputWorkspace=wsbkg,Filename='bkg.nxs')
```

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by AndreiSavici — DISMISSED** [review]
Works as expected

**Comment by zjmorgan** [comment]
Talking with Andrei and working with only a single bank of CORELLI data, it was clear that the number of groups is one higher than expected when taking total groups from the grouping workspace. Therefore, it will be better to use
`numGroups = grouped_inputs.front()->getNumberHistograms()`

to prevent an exception being thrown with the single bank. This is because the grouping workspace contains zeros which gets counted as an additional group.

**Comment by rosswhitfield** [comment]
Thanks @zjmorgan I made the change, can you take another look?

**Comment by zjmorgan** [comment]
Seems to be working nicely now. Thanks @rosswhitfield Approved

**Review by zjmorgan — APPROVED** [review]
This works well as expected.

**Pull request merged**
