### PR TITLE
Unified color maps and settings for Vsi

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
See original ticket [#10656](http://trac.mantidproject.org/mantid/ticket/10656)

### CODE REVIEW

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by picatess** [comment]
Jenkins, restest this please

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by martyngigg** [comment]
It looks like this can no longer be merged cleanly to master. Could you merge master to your branch, please?

**Comment by martyngigg** [comment]
Some nice test instructions here. They seem to have covered all bases.

The functionality seems to make sense as far as I can tell. In future we may want to consider "importing" ParaView's colour map selector widget as we simply have a list of names that don't mean much to users but that is a future improvement.

**Pull request merged**
