### PR TITLE
MD coordinate as separate field

### PR DESCRIPTION
**Pull request by martyngigg**
Fixes issue [#11359](trac.mantidproject.org/mantid/ticket/11359)

**Tester**
The following script produces an MD workspace with a non-default coordinate system

``` python
CreateSimulationWorkspace(Instrument='MARI', BinParams='-11,0.05,11', OutputWorkspace='mari')
AddSampleLog(Workspace='mari', LogName='Ei', LogText='12.1', LogType='Number')
ConvertToMD(InputWorkspace='mari', QDimensions='Q3D', OutputWorkspace='mdws',Q3DFrames='Q_lab')
```

Try saving this with `SaveMD` and reloading the workspace with `LoadMD` and then check that the coordinate has survived with

``` python
print mtd[loadedws].getSpecialCoordinateSystem()
```

It should print `QLab`

### CODE REVIEW

**Comment by OwenArnold** [comment]
jenkins retest this please

**Comment by martyngigg** [comment]
Jenkins, retest this please

**Comment by martyngigg** [comment]
Jenkins, retest this please

**Comment by martyngigg** [comment]
Jenkins, retest this please

**Comment by OwenArnold** [comment]
Code looks good, and I've tested this for both Peaks and MDWorkspaces.

**Pull request merged**
