### PR TITLE
Windows compile without precompiled headers

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR does a small bit of code refactoring to ensure mantid can be compiled on windows with precompiled headers turned off. Some of the refactoring includes:
- Adding missing includes
- Using forward declarations in header files
- Avoid the use of 'using namespace', especially in header files!

Note that `NeXusFile.hpp` must be included before `NeXusException.hpp` as described here https://github.com/nexusformat/code/issues/457

**To test:**
From a conda build of mantid:
1. Delete your old build directory and create a new one
2. Activate your conda environment in git bash
3. Cd to your source directory, and configure/generate (assuming your build directory is outside your source):
```
cmake --preset=win -B ../build -DUSE_PRECOMPILED_HEADERS=OFF
```
4. Cd into your build directory, and then build:
```
cmake --build . --config Release
```
3. When it finishes building, open VS from the `.bat` file in the build folder
5. Build the `ALL_BUILD` target. There should be no errors

Part of #33801

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DanielMurphy22 — COMMENTED** [review]
Build succeeds but there is one small warning I see. What do you think of this @robertapplin 

```
  Finished processing dependencies for mantidqt==6.3.20220609.1036
  Copying debug PyQt5 to bin/Debug
  Generating ../../../bin/Release/mantidqtinterfaces.egg-link
  running develop
  running egg_info
  writing mantidqtinterfaces.egg-info\PKG-INFO
  writing dependency_links to mantidqtinterfaces.egg-info\dependency_links.txt
  writing top-level names to mantidqtinterfaces.egg-info\top_level.txt
  reading manifest file 'mantidqtinterfaces.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
CUSTOMBUILD : warning : no files found matching '*' under directory 'mantidqtinterfaces\Engineering\calib' [C:\Users\username\source\repos\mantid\build\qt\python\mantidqtinterfaces\mantidqtinterfaces.vcxproj]
  writing manifest file 'mantidqtinterfaces.egg-info\SOURCES.txt'
  running build_ext
  Creating c:\users\username\source\repos\mantid\build\bin\release\mantidqtinterfaces.egg-link (link to .)
  mantidqtinterfaces 6.3.20220609.1036 is already the active version in easy-install.pth

  Installed c:\users\username\source\repos\mantid\qt\python\mantidqtinterfaces
  Processing dependencies for mantidqtinterfaces==6.3.20220609.1036
  Finished processing dependencies for mantidqtinterfaces==6.3.20220609.1036
```

**Comment by robertapplin** [comment]
> Build succeeds but there is one small warning I see. What do you think of this @robertapplin

Could you try removing this line from `MANIFEST.in` and build it again?
https://github.com/mantidproject/mantid/blob/487b6ee1cd1a108ad9559bb35117288d7b128a9d/qt/python/mantidqtinterfaces/MANIFEST.in#L2

I think the folder `qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/calib` no longer exists and so this line isn't doing anything

**Comment by robertapplin** [comment]
Also I'm not sure why this is stuck on scheduling the `Formatting + Static Analysis` job ...

**Comment by robertapplin** [comment]
> > I think the folder `qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/calib` no longer exists and so this line isn't doing anything
> 
> Looks like it's been moved to `mantid/scripts/Engineering/calib`
> 
> So maybe we should do `recursive-include mantid/scripts/Engineering/calib * `

@DannyHindson Do you know if the xml files in `mantid/scripts/Engineering/calib` are still needed in the packaging?

I'm not too sure how this would be packaged now that they are outside the `mantidqtinterfaces` directory

**Comment by robertapplin** [comment]
Ok, thanks for taking a look. In that case we will just remove that line from the MANIFEST.in

**Review by DanielMurphy22 — APPROVED** [review]
Builds without errors or warnings (apart from this deprecation which isn't worth fixing here: https://github.com/mantidproject/mantid/issues/33801#issuecomment-1149758007)

**Pull request merged**
