### PR TITLE
Fix documentation warning

### PR DESCRIPTION
**Pull request by martyngigg**
Fixes the remaining documentation warning: http://builds.mantidproject.org/job/master_doctests/439/warnings3Result/

**To test:**

Review the change.

No issue

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by soininen** [comment]
@martyngigg Please, resolve the merge conflicts.

**Comment by martyngigg** [comment]
@soininen Thanks. The conflicts have been resolved.

**Comment by soininen** [comment]
I think is is good to go :shipit:

**Comment by SimonHeybrock** [comment]
@martyngigg Github is showing an empty change set?

**Comment by martyngigg** [comment]
@SimonHeybrock It looks like they were fixed at the same time as a recent update to the same document: in #18205

**Pull request closed without merging**
