### PR TITLE
macOS: source environment before running executables

### LINKED ISSUE #23540: macOS launcher does not pick up the environment
When starting MantidPlot by opening the MantidPlot.app from finder or Applications, it does not pick up the environment. However starting the executable from terminal does.
Because of this, the latex path, for example, is not in the path, so plotting a matplotlib plot with latex labels fails. The same applies also to MantidPython and MantidNotebook executables.

The solution would be to source ```/etc/profile``` and ```~/.profile``` if they exist.

**Original reporter:** ILL/Bjorn. 

### Expected behavior

Environment should be picked up regardless on the manner of starting mantid.

### Actual behavior

It is not picked up when launching the app.

### Steps to reproduce the behavior

1. Build mantid on macOS
2. Run from terminal ```./$BUILD_DIR/bin/MantidPlot/Contents/MacOS/MantidPlot```
3. Execute in mantid:
```
import os
os.environ["PATH"]
```
4. Open finder and run MantidPlot.app from there. Repeat 3 and you will see a different result, if you have some additional paths defined in your `.profile`. 

The ultimate test is to do this instead of 3:
```
import matplotlib
import matplotlib.pyplot as plt
matplotlib.rcParams.update({'text.usetex':True})
fig, ax = plt.subplots()
ax.plot([0,1], [2, -3])
ax.set_xlabel('$a$')
fig.show()
```
### Platforms affected

macOS

### PR DESCRIPTION
**Pull request by gvardany**
**Description of work.**

This PR adds a script that sources the system and user defined environments in the host machine when starting the macOS applications (MantidPlot, MantidPython, MantidNotebook) from launcher, and not from terminal. See the issue for more details.

**To test:**

1. Build MantidPlot on macOS
2. Start MantidPlot.app from finder, not from terminal
3. In mantid, run 
```
import os
os.environ['PATH']
```
This should have the full PATH that you set up in your `.profile`. 
This should also include `/Library/TeX/texbin` from system wide path.
4. This should run without errors.:
```
import matplotlib
import matplotlib.pyplot as plt
matplotlib.rcParams.update({'text.usetex':True})
fig, ax = plt.subplots()
ax.plot([0,1], [2, -3])
ax.set_xlabel('$a$')
fig.show()
```
5. Build the package (or download from the macOS build artefacts)
6. Install the package
7. Repeat 1-4 also for the installed MantidPlot
8. Repeat 1-4 also for MantidNotebook and MantidPython apps.

Fixes #23540 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by quantumsteve** [comment]
What are you trying to do that cannot be done with Matplotlib's built-in math text?
Is bundling a BasicTeX (78 MB) a superior or inferior option?

Would you add user instructions including a link to MacTex?
Can we provide the user a warning before he or she received an error from Matplotlib & LaTeX?

**Comment by gvardany** [comment]
Thanks for pointing this out, we were not aware of built-in math in mpl. 
The issue originally comes from direct tools plotting module.
We will try to see if we can get everything we need without latex.
Seems simply switching latex off causes some glitches, e.g. for angstrom symbol etc. but we will see, maybe there are just some syntax differences.

**Comment by soininen** [comment]
I think I got `directtools` to work without LaTeX. The needed changes are now part of PR #23482. I think we could close this PR if there is no other need for the extended PATH on macOS.

**Comment by gvardany** [comment]
Agreed. We should keep this trick in mind though, if later turns out we need some other things from the PATH.

**Pull request closed without merging**
