### PR TITLE
Fixed fitting range in muon

### PR DESCRIPTION
**Pull request by AnthonyLim23**
Fixed the default fitting range in the muon analysis interface. 

To test:
In the muon analysis interface the default fitting range should match the start and finish values in the settings tab (with Time axis set to "Start at First Good Data"). 

This addresses one of the issues from https://github.com/mantidproject/mantid/issues/18195

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@AnthonyLim23 Just a minor point for future pull requests. When opening them GitHub populates it with [this](https://github.com/mantidproject/mantid/blob/master/.github/PULL_REQUEST_TEMPLATE.md) template. The parts surrounded by `<!-- -->` are html comments and so don't get rendered in the output. For the testing section please leave the **To test:** title in place so it slightly easier to read for the reviewer.

**Comment by AnthonyLim23** [comment]
Thank you. I have fixed it now.

**Comment by martyngigg** [comment]
It looks like there has been a subtle change in behaviour here.

If I try the following:

* Select search data archive in "View->Preferences" 
* open Muon interface
* select `HIFI`
* enter `113041` in the load run box
* switch to the "Data Analysis" tab

I get an error in the results log:
```
The X range given lies entirely within a single bin
Error in execution of algorithm ExtractSpectra:
The X range given lies entirely within a single bin
Error in execution of algorithm CropWorkspace:
The X range given lies entirely within a single bin
Error in execution of algorithm MuonProcess:
The X range given lies entirely within a single bin
Failed to create analysis workspace HIFI00113041; Pair; long; Asym; #1: The X range given lies entirely within a single bin
```

I presume this is because the range is now not set before `selectMultiPeakFit` is called.

Do you know if this is vital to fix for `3.9` as I think it could be quite involved to fix it.

**Comment by martyngigg** [comment]
An unfortunate repetition of setting the range but it is unavoidable with the current design.

I retested the functionality and I no longer get the error and the tab remembers the range that was entered when I flip between other tabs and come back.

:shipit: when the builds pass.

**Pull request merged**
