### PR TITLE
Restructure directories for mantid 4

### PR DESCRIPTION
**Pull request by mantid-roman**
Moved files according to the design doc https://github.com/mantidproject/documents/blob/b23a28044f2f22054f234c9e17577c64c706518d/Design/Workbench/design-layout.md

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@mantidproject/gatekeepers We would like to get this merged ASAP as it just keeps accumulating merge conflicts. Please offer thoughts today.

**Comment by martyngigg** [comment]
@roman. This generally looks great to me.

I've got one thing that I think we probably should change now I've seen & built it in real life. For clarity I think the library names for the widgets need to have Mantid in them, e.g. ` libqtwidgetscommon.dll` --> `libmantidqtwidgetscommon.dll`. The same with the scientific interfaces.

There is also the question then of CamelCase vs lowercase. Looking at the built `bin` directory I actually find it easier to read the CamelCase ones like `libMantidScientificInterfacesDynamicPDF.so` now I've seen them in the flesh. @mantidproject/gatekeepers Thoughts on the whole CamelCase vs lowercase situation?

**Comment by martyngigg** [comment]
@mantid-roman I also think I've got the reflectometry interfaces mixed up. The C++ one is the new one and we've labelled the C++ library old. Let's remove that from there.

Also, the `Interfaces->Reflectometry->ISIS Reflectometry Old` interface does not work any more. It currently works in `master`.

**Comment by martyngigg** [comment]
In addition to the previous comment, it looks like none of the Python interfaces work. For example, `Interfaces->Diffraction->HFIRPowderReduction` does not work either. You get an error:

```
ImportError: No module named ui_MainWindow
  at line 7 in '<Interface>'
  caused by line 10 in '/media/data1/source/github/mantidproject/mantid4/scripts/HFIRPowderReduction/HfirPDReductionGUI.py'
```

It looks like the `.ui` compile step has not happened.

**Comment by mantid-roman** [comment]
@martyngigg The interfaces start on my machine. `Diffraction->HFIR Powder Diffraction Reduction` gives me this instead:
```
ImportError: No module named request
  at line 7 in '<Interface>'
  caused by line 20 in 'D:/Work/mantid-1/scripts\HFIRPowderReduction\HfirPDReductionGUI.py'
  caused by line 9 in 'D:/Work/mantid-1/scripts\HFIRPowderReduction\HfirPDReductionControl.py'
```

**Comment by martyngigg** [comment]
@mantid-roman I wonder if you still have the `ui_` files from an older build? I cloned the repo fresh and then built that. Could try deleting all `ui_*.py` files and seeing if they regenerate properly?

**Comment by martyngigg** [comment]
@mantid-roman I think `HFIRPowderReduction` might be broken anyway: https://github.com/mantidproject/mantid/commit/b62388f5fc90f52b57be261606cbefbefb4d4ebe#diff-63210350e1b05452b2f908af1ce269e4R9. `request` is only available in Python 3.

**Comment by mantid-roman** [comment]
@martyngigg I deleted my `build` directory and rebuilt clean. Still works

**Comment by mantid-roman** [comment]
They are not in `buld`. I deleted the `ui_`s of 4Circle reduction, then rebuilt VS solution. The files get created and the interface works again.

**Comment by martyngigg** [comment]
@mantid-roman I think the only thing left from me was to address the library naming that I mentioned above. I think we should prefix everything with `mantidqt` so that the origin of the libraries is clear.

**Comment by mantid-roman** [comment]
@martyngigg What about the CamelCase?

**Comment by martyngigg** [comment]
Let's go with that too.

**Comment by peterfpeterson** [comment]
I preferred the names in all lowercase, but not strongly enough to make you change it again.

**Review by martyngigg — APPROVED** [review]

**Pull request merged**
