### PR TITLE
Fix NMoldyn4InterpolationTest on master

### PR DESCRIPTION
**Pull request by martyngigg**
A bug crept on to master that is causing this to fail for every build.

**To test:**

Builds should pass.

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@AntonPiccardoSelg The builds have all run through the unit tests successful (from looking at the console log). Could we push this through? All the other builds will be failing at the moment.

**Comment by AntonPiccardoSelg** [comment]
:shipit:

**Comment by AntonPiccardoSelg** [comment]
@martyngigg  Do we know why this happened?

**Comment by martyngigg** [comment]
@AntonPiccardoSelg Thanks. It was a "quick" fix on master - https://github.com/mantidproject/mantid/commit/3b2bc49cf5cc69a3bda2019898c82aa309926e1d#diff-36d9df39c8bc6ec74cae08bc8b171228

**Pull request merged**
