### PR TITLE
Remove old Tomography files

### PR DESCRIPTION
**Pull request by dtasev**
Description of work.

Remove all related files to the Tomography Reconstruction interface.

I don't want to delete [SCARFLSFJobManager.h](https://github.com/mantidproject/mantid/blob/master/Framework/RemoteJobManagers/inc/MantidRemoteJobManagers/SCARFLSFJobManager.h), [SCARFLSFJobManager.cpp](https://github.com/mantidproject/mantid/blob/master/Framework/RemoteJobManagers/src/SCARFLSFJobManager.cpp), [SCARFLSFJobManagerTest.h](https://github.com/mantidproject/mantid/blob/master/Framework/RemoteJobManagers/test/SCARFLSFJobManagerTest.h), as although they have hard coded values, they might provide useful if anyone needs to connect to such a system

**To test:**

See if I've missed any files

No associated issue.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DTasev** [comment]
I don't want to delete [SCARFLSFJobManager.h](https://github.com/mantidproject/mantid/blob/master/Framework/RemoteJobManagers/inc/MantidRemoteJobManagers/SCARFLSFJobManager.h), [SCARFLSFJobManager.cpp](https://github.com/mantidproject/mantid/blob/master/Framework/RemoteJobManagers/src/SCARFLSFJobManager.cpp), [SCARFLSFJobManagerTest.h](https://github.com/mantidproject/mantid/blob/master/Framework/RemoteJobManagers/test/SCARFLSFJobManagerTest.h), as although they have hard coded values, they might provide useful if anyone needs to connect to such a system

**Comment by soininen** [comment]
Could the test file `savu_test_data_process03.nxs` be removed as well?

**Comment by DTasev** [comment]
@soininen Done

**Comment by AndreiSavici** [comment]
Is it supposed to be in this release?

**Comment by DTasev** [comment]
@AndreiSavici If you consider it a high risk change it could be left off for the next one

**Comment by AndreiSavici** [comment]
I'm fine to remove it in this release. I assume that tomography people are ok with it as well. I've just noticed that it had no milestone.

**Comment by DTasev** [comment]
Yes the work has been moved to https://github.com/mantidproject/isis_imaging

**Pull request merged**
