### PR TITLE
Updated MSlice SHA for Mantid release 6.10

### PR DESCRIPTION
**Pull request by SilkeSchomann**
### Description of work

Replaced MSlice SHA for Mantid with SHA of current MSlice main branch.

Added release notes for all changes since the last SHA update.

### To test:

Double-check SHA with SHA of current MSlice main branch.

_There is no associated issue._

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by jclarkeSTFC** [comment]
From cmake docs [here](https://cmake.org/cmake/help/latest/module/ExternalProject.html):

> Changed in version 3.27: When UPDATE_DISCONNECTED is true, the update step will be executed if any details about the update or download step are changed. Furthermore, if using the git download/update method, the update logic will be modified to skip attempts to contact the remote. If the GIT_TAG mentions a ref that is not known locally, the update step will halt with a fatal error.

Seems like something related to that change must be causing the problem

**Review by MohamedAlmaki — COMMENTED** [review]
Before the build finishes, is the base branch correct? I guess it should be release-next. 
Also, I would prefer squashing the commits but it is not a blocking issue

**Comment by SilkeSchomann** [comment]
Yes, they had tried to change this in 3.20 without success.

**Comment by SilkeSchomann** [comment]
I think I better open a new branch based on release-next now!

**Pull request closed without merging**
