### PR TITLE
Fix SavePlot1D algorithm not working in Workbench

### LINKED ISSUE #28357: SavePlot1D algorithm does not work in Workbench
```
ws = CreateSampleWorkspace()
SavePlot1D(ws, *put your own output file here*)
```

```
Error in execution of algorithm SavePlot1D:
'FigureManagerBase' object has no attribute 'window'
  at line 92 in 'C:/Users/ilb25526/mantid/Framework/PythonInterface/plugins/algorithms\WorkflowAlgorithms\SavePlot1D.py'
  caused by line 239 in 'C:/Users/ilb25526/mantid/Framework/PythonInterface/plugins/algorithms\WorkflowAlgorithms\SavePlot1D.py'
  caused by line 1202 in 'C:\Users\ilb25526\mantid\external\src\ThirdParty\lib\python3.8\lib\site-packages\matplotlib\pyplot.py'
  caused by line 558 in 'C:\Users\ilb25526\mantid\external\src\ThirdParty\lib\python3.8\lib\site-packages\matplotlib\pyplot.py'
  caused by line 192 in 'c:\users\ilb25526\mantid\qt\applications\workbench\workbench\plotting\globalfiguremanager.py'
  caused by line 50 in 'c:\users\ilb25526\mantid\qt\applications\workbench\workbench\plotting\observabledictionary.py'
  caused by line 41 in 'c:\users\ilb25526\mantid\qt\applications\workbench\workbench\plotting\observabledictionary.py'
  caused by line 50 in 'c:\users\ilb25526\mantid\qt\applications\workbench\workbench\plotting\globalfiguremanager.py'
  caused by line 260 in 'c:\users\ilb25526\mantid\qt\applications\workbench\workbench\plotting\globalfiguremanager.py'
  caused by line 74 in 'c:\users\ilb25526\mantid\qt\applications\workbench\workbench\widgets\plotselector\model.py'
  caused by line 68 in 'c:\users\ilb25526\mantid\qt\applications\workbench\workbench\widgets\plotselector\presenter.py'
  caused by line 116 in 'c:\users\ilb25526\mantid\qt\applications\workbench\workbench\widgets\plotselector\model.py'
```

Works okay if you do it outside of Workbench, i.e. in a command line.

### PR DESCRIPTION
**Pull request by PhilColebrooke**
**Description of work.**
See title. Previously the algorithm would cause an error.

**To test:**
```
ws = CreateSampleWorkspace()
SavePlot1D(ws, *put your own output file here*)
```
Check that the plot image has been saved correctly.

Fixes #28357 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DanielMurphy22 — APPROVED** [review]
Tested on Mac and Windows. 
A little annoying that there's no legend (this should really be an option parameter), especially because you CAN set the names of each spectrum (which is therefore useless). This has been the case since 4.0 for Plot and WB so happy for this change to go ahead!

**Comment by martyngigg** [comment]
Can I just check, does the `PopCanvas` option still work?

Also, does the `plotly` image type still work? It requires [plotly](https://pypi.org/project/plotly/) to be installed separately.

**Comment by PhilColebrooke** [comment]
> Can I just check, does the `PopCanvas` option still work?
It still worked for me.

> Also, does the `plotly` image type still work? It requires [plotly](https://pypi.org/project/plotly/) to be installed separately.
I haven't checked this directly but my changes are only in the `saveImage` function which is only called when the standard 'image' plot type is chosen. So if it worked previously it should still work.

**Comment by martyngigg** [comment]
Thanks for confirming.

**Pull request merged**
