### PR TITLE
Add Full Calibration Saving and Loading to Eng Diff GUI

### LINKED ISSUE #27659: Unhide Option to Set Full Calibration File
### Expected behavior
The user is able to select the Full EnginX calibration file that they wish to use. 
### Actual behavior
The file cannot be loaded as a table workspace due to the fomat not being supported and the option being hidden. 
### Steps to reproduce the behavior
Open Engineering Diffraction 2 GUI, Open settings, there is no option for Full Calibration
### Platforms affected
All

The functionality is written into the GUI, it is just not visible to users yet as it is waiting on the ability to load saved table workspaces back into mantid to be used.

### PR DESCRIPTION
**Pull request by cailafinn**
**Description of work.**
- Makes `EnggCalibrateFull` make use of the new `SaveAscii` algorithm to create its output files so that they can be loaded back into mantid. 
- Shows the full calibration selection functionality from the Engineering Diffraction 2 GUI.
**To test:**
1. Load CeO2: ENGINX193749 and V: ENGNIX194547 (cycle_12_4)
1. Run EnggCalibrateFull, making sure to specify an output file (OutDetPosFilename), Expected peaks = [0.855618487, 0.956610, 1.104599, 1.352852, 1.562138, 1.631600, 1.913221, 2.705702376, 3.124277511]
2. Open the engineering diffraction 2 GUI.
3. Click the settings button. 
4. Set the Full Calibration to the generated file. 
5. Run a new calibration using V: 307521 and CeO2: 305738
6. A workspace called det_pos should be output if it worked as expected. 

Fixes #27659

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DannyHindson — COMMENTED** [review]
Ran the test and it worked fine.

I've added two comments against the individual units. One doesn't require any action and the other is v minor about the path_handling unit change - just let me know and I may approve as is.

Two other general things I noticed:
- the SaveAscii algorithm seems to insert spaces before and after each column name in addition to the tab separator. Not sure why but doesn't cause any problems here
- the tab order of the Vanadium # and calibration sample # edit boxes isn't right on the Calibration tab but that looks like it's unrelated to these changes

**Comment by ConorMFinn** [comment]
> the tab order of the Vanadium # and calibration sample # edit boxes isn't right on the Calibration tab but that looks like it's unrelated to these changes

I'll fix this in the general improvements PR that I'm working on at the moment.

**Comment by DannyHindson** [comment]
As discussed it seems to be occasionally possible to run the Calibrate in the engineering GUI without the det_pos workspace being generated. Not 100% sure of the conditions but this perhaps happens if you open up Workbench and go to the Engineering GUI settings menu and find the full calibration file path pre-populated with a previous filepath but still has the red star next to it. Seems like Workbench remembers the path from a previous time it's been opened. You are still able to OK the settings screen and run the calibrate in this situation

**Review by DannyHindson — APPROVED** [review]
Thanks for making the changes. Looks good. I did the final test on Windows and I noticed the tab order on the Vanadium\Calibration Sample edit boxes works. Not sure if you've fixed this - possible the order just doesn't work on Linux (I did my initial testing on an Ubuntu VM)

**Pull request merged**
