### PR TITLE
Changes to work with NeXus 4.4.1

### LINKED ISSUE #14843: Changes to work with NeXus 4.4.1
Ticket to cover the changes required to get mantid working with NeXus API v4.4.1

### PR DESCRIPTION
**Pull request by stuartcampbell**
A senior developer should probably look at this.  

We are silently swallowing all the output from the NeXus API, I'm not sure why ?

This PR contains all the changes required to make Mantid compile with the version 4.4.1 of the NeXus API.  It mainly deals with functions that have been removed.  I have raised a question to upstream as to whether these are intentional removals, so this ticket should probably not be merged until they have responded - but I wanted to see if these changes worked on other platforms.

fixes #14843

### CODE REVIEW

**Comment by peterfpeterson** [comment]
I think that we would be better off changing the messages to debug logging.

**Comment by stuartcampbell** [comment]
I just heard back from NeXus (Eugen) and he didn't intend to make any breaking changes, so we might not need to alter anything.

**Comment by stuartcampbell** [comment]
Here is the link to the NeXus Issue https://github.com/nexusformat/code/issues/414

**Comment by stuartcampbell** [comment]
The NeXus change that caused this issue is https://github.com/nexusformat/code/pull/391

**Comment by martyngigg** [comment]
Should we move this back to `3.8`?

**Comment by peterfpeterson** [comment]
I think it won't be an issue in 4.4.2 (or 4.5). Perhaps we just wait until a newer new version of nexus before we upgrade.

**Comment by peterfpeterson** [comment]
The fix *is* to move to the next release of nexus. See #17001.

**Pull request closed without merging**
