### PR TITLE
SANS - Wav loops speedup

### LINKED ISSUE #28987: Speed up looping over wavelengths for SANS
At the moment reductions iterating over multiple wavelength slices are very slow because the looping is performed _outside_ of Q1D. As there is an increased operational need at ISIS to perform more regular wavelength overlap checks (eg, for signs of multiple scattering, but also for future autovalidation), and to facilitate the simulation of the ESS Loki instrument, this looping should be moved _inside_ Q1D.

This will not be a simple task and, because it touches the heart of the ISIS SANS data reduction, it will need very careful testing and validation to ensure that the new procedure replicates the existing output.

This now a quite urgent task.

### PR DESCRIPTION
**Pull request by DavidFair**
Re-creating this PR as the many rebases have seemingly borked the CI in #29939 

----------

**Description of work.**

The final part of the wavelength loops work. In this PR we:
- Move wavelength information into a simpler format (list of pairs)
- Rework the core SANS Reduction loop to process n wavelength slices during one pass, rather than n passes
- "Re-plumb" the properties to get the expected workspaces back, in the expected order
- Simplified the output bundles data structure and how to iterate over it significantly

One victim of these changes was the SANSReductionCore V2 workflow which will no longer work. However this is not used in the group as there is a small unexplained difference in results.
The development effort for the small performance gain on event workspaces to both explain or fix the differences / switch over and now fix-up is not a priority based on the sprint planning.

**To test:**
- Download the ISIS Training data set
- Open Mantid and SANS->ISIS SANS
- Point the user file to either the toml or .txt file called MaskFile in LoqDemo
- Open the CSV file in the same folder
- Select the first row and hit process
- Go to settings, Q, Wavelength
- Under Wavelength change `Log` to `RangeLog`
- Enter `1:1:15` to process wavelength slice 1-15 in 1 Angstrom slices
- It should be noticeably faster than master, data validity has been checked by running the same system tests (unmodified) before and after these changes

Fixes #28987 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DavidFair** [comment]
@gemmaguest from my testing that's fixed the bug: I've tried re-running the same reduction, a different once and changing the number of slices (and that it correctly re-slices the cache can). 
Thanks for noticing that

**Comment by gemmaguest** [comment]
@DavidFair I'm still seeing an error re-running the reduction. It might not have updated due to conflicts. Could you fix them? Also there are additions to the v6.0.0 release notes - should that be moved to v6.1.0?

**Comment by gemmaguest** [comment]
Actually it seems to be a different error now, which is confusing!
```
  File "C:\Users\mhb52947\work\checkout\mantid\scripts\SANS\sans\gui_logic\models\batch_process_runner.py", line 80, in _process_states_on_thread
    self.batch_processor([state.all_states], use_optimizations, output_mode, plot_results, output_graph, save_can)
  File "C:\Users\mhb52947\work\checkout\mantid\scripts\SANS\sans\sans_batch.py", line 33, in __call__
    return self._execute(states, use_optimizations, output_mode, plot_results, output_graph, save_can=save_can)
  File "C:\Users\mhb52947\work\checkout\mantid\scripts\SANS\sans\sans_batch.py", line 42, in _execute
    single_reduction_for_batch(state, use_optimizations, output_mode, plot_results, output_graph,
  File "C:\Users\mhb52947\work\checkout\mantid\scripts\SANS\sans\algorithm_detail\batch_execution.py", line 173, in single_reduction_for_batch
    save_to_file(reduction_packages, save_can, additional_run_numbers, event_slice_optimisation=event_slice_optimisation)
  File "C:\Users\mhb52947\work\checkout\mantid\scripts\SANS\sans\algorithm_detail\batch_execution.py", line 1133, in save_to_file
    transmission = to_save[1][i] if to_save[1] else ''

list index out of range
```

**Comment by gemmaguest** [comment]
I've resolved the conflicts and moved the release notes to v6.1. I'm not seeing the bug when I build on the branch so I think it was due to the conflicts

**Comment by gemmaguest** [comment]
Ok actually I am still getting the error. It's only on Windows and it actually happens the first time, so is not related to re-running the reduction. It only happens when the step type is Log/Lin (it seems ok with ranges). It's working on Ubuntu. Again, the error is:

```
  File "C:\Users\mhb52947\work\checkout\mantid\scripts\SANS\sans\gui_logic\models\batch_process_runner.py", line 80, in _process_states_on_thread
    self.batch_processor([state.all_states], use_optimizations, output_mode, plot_results, output_graph, save_can)
  File "C:\Users\mhb52947\work\checkout\mantid\scripts\SANS\sans\sans_batch.py", line 33, in __call__
    return self._execute(states, use_optimizations, output_mode, plot_results, output_graph, save_can=save_can)
  File "C:\Users\mhb52947\work\checkout\mantid\scripts\SANS\sans\sans_batch.py", line 42, in _execute
    single_reduction_for_batch(state, use_optimizations, output_mode, plot_results, output_graph,
  File "C:\Users\mhb52947\work\checkout\mantid\scripts\SANS\sans\algorithm_detail\batch_execution.py", line 173, in single_reduction_for_batch
    save_to_file(reduction_packages, save_can, additional_run_numbers, event_slice_optimisation=event_slice_optimisation)
  File "C:\Users\mhb52947\work\checkout\mantid\scripts\SANS\sans\algorithm_detail\batch_execution.py", line 1133, in save_to_file
    transmission = to_save[1][i] if to_save[1] else ''

list index out of range
```

**Comment by DavidFair** [comment]
So I've also fixed an issue where we couldn't switch between range lin / lin - to test this:

- Run a reduction with Settings -> Wavelength -> Lin
- Switch to RangeLin and enter a range (e.g. `2, 4, 6, 8`), reprocess and make sure n/2 workspaces appear
- Clean the ADS again and try reprocessing with Lin to get the same workspaces as step 1
- Switch back to RangeLin, the value should be preserved

I've also fixed the saving issue described, it so happened I tested saving with 2 workspace slices, which avoids the bug :man_facepalming:

**Review by gemmaguest — APPROVED** [review]
Looks good. All the bugs we found are fixed and I can't find any more ways to break it :+1:

**Pull request merged**
