### PR TITLE
Updated SHA for MSlice and also release note

### PR DESCRIPTION
**Pull request by SilkeSchomann**
Description of work.

Replaced MSlice SHA for Mantid with SHA of current MSlice release-next branch.

Added release note in mslice_direct_geometry.rst with all changes in MSlice since last MSlice SHA update in Mantid.

To test:

Double-check SHA with SHA of current MSlice release-next branch.

There is no associated issue.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by mducle** [comment]
@SilkeSchomann @martyngigg sorry... is there still time to fix one more issue ([MSlice#695](https://github.com/mantidproject/mslice/issues/695)) before inclusion in Mantid? It's because although we've introduced the option for "Rebin (averaged counts)" and "Integration (summed counts)" in the `Cut` tab, this has no effect when the workspace is of "PSD" type since the [algorithm there](https://github.com/mantidproject/mslice/blob/release-next/mslice/models/cut/cut_algorithm.py#L61-L71) ignores these flags.

**Review by martyngigg — APPROVED** [review]
Confirmed the new sha matches the `release-next` on mslice.

**Comment by martyngigg** [comment]
@mducle Yeah we've still got time. The release is currently scheduled for next week and we have a couple of other outstanding issues.

**Comment by DannyHindson** [comment]
Should I merge this PR? Wasn't sure if Duc's comment meant we should wait

**Comment by mducle** [comment]
@DannyHindson There's another PR #33425 for the changes I was talking about...

**Comment by SilkeSchomann** [comment]
This can be merged. There is another PR for a SHA update for this last change.

**Pull request merged**
