### PR TITLE
Convert developer documentation to sphinx

### PR DESCRIPTION
**Pull request by peterfpeterson**
Convert another wiki page to sphinx. Was in the wiki as
https://www.mantidproject.org/Individual_Ticket_Testing

**Report to:** @martyngigg to add the server side redirects

**To test:**

Build it and see that it is formatted ok.

*There is no associated issue.*

*This does not require release notes* because it is developer documentation.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by AndreiSavici — COMMENTED** [review]
I've got the following warning:
```
checking consistency... /home/3y9/Mantid/mantid/dev-docs/source/IndividualTicketTesting.rst: WARNING: document isn't included in any toctree
```
 You might want to include at line 6
 ```
.. contents::
  :local:
```

**Review by AndreiSavici — CHANGES_REQUESTED** [review]
See my comment

**Review by AndreiSavici — APPROVED** [review]

**Comment by martyngigg** [comment]
Not waiting for the system test build as there is no need.

**Comment by martyngigg** [comment]
I have reported this to myself to add the server redirect once the site rebuilds.

**Pull request merged**
