### PR TITLE
EnggDiffractionGUI::Fixes crashes when run number given for Pre-processing Rebin

### LINKED ISSUE #14886: EnggDiffractionGUI::Mantid crashes on valid and invalid run-num when Rebinning
`Interfaces/Engineering Diffraction/Pre-processing`
When Run number for Pre-processing tab is accessed by browse button, the run number seems to be accepts and the `Rebin` carries out how it should. However when a valid or an invalid run number is given, Mantid seems to be crashes. Being able to provide a run-number for Pre-processing could be rather useful for the next release.

### PR DESCRIPTION
**Pull request by shahrozahmed1**
fixes #14886 

This branch should disable Mantid from crash when a valid or an invalid run number is given to `Interfaces/Engineering Diffraction/Pre-processing`.

**To Test**
- Go to `Interfaces/Engineering Diffraction/`
- Enter anything for RB Number `e.g: 13245` (used for files output)
- Go to `Pre-proceessing tab`
- Enter valid run number (make sure the directory is found in `Manage User Directories`) 
  
  > - error on invalid or empty run number
- Click `Rebin`
- One of the valid run number that could be tested is `197019`, you can find the file `ENGINX00197019` in the system test data. 

_For any initial setting or having any trouble setting up, please slack me._

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
@LamarMoore : sorry for the disturbance, when merging other branches I introduced a conflict here. I'm now fixing it (it's a very small conflict in one method where two branches have introduced new code in the same place) and will push the branch again with the updates from master merged into it. It should work all fine, as the changes from the other branches do not interfere with this pre-processing tab.

**Comment by FedeMPouzols** [comment]
@shahrozahmed1 , @LamarMoore : beware there might be a subtle issue in this branch. It now works well when you give a run number, but if you use "browse" and select a file *that is not in the Mantid path* you'll get an unhandled exception and crash. At least I saw that on debian. So please check that you can run rebin both with a run number, and with a file selected with "browse".

**Comment by LamarMoore** [comment]
I can confirm the same crash happens on my machine.

**Comment by LamarMoore** [comment]
Looks good. Those fixes worked. I am happy to commit

**Pull request merged**
