### PR TITLE
ISIS Powder Diffraction system test

### LINKED ISSUE #13407: Add ISIS powder diffraction system test
For the scripts added in #13405. It would in principle test what the CRY_example.py script runs.

### PR DESCRIPTION
**Pull request by shahrozahmed1**
Fixes #13407 

System Test for recently integrated ISIS Powder Diffraction scripts #13405

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
The new test looks good. Did you forget to add t`hrp3he file 39191.raw`? It seems that it is not found on the build servers workspace. In the files added I can see run 43022 but not 9191

From http://builds.mantidproject.org/job/pull_requests-rhel7/2200/testReport/:

```
ValueError: Invalid value for property Filename (string) "/home/builder/jenkins-linode/workspace/pull_requests-rhel7/build/ExternalData/Testing/Data/SystemTest/hrp39191.raw": File "/home/builder/jenkins-linode/workspace/pull_requests-rhel7/build/ExternalData/Testing/Data/SystemTest/hrp39191.raw" not found
```

**Comment by FedeMPouzols** [comment]
Looking at the "Files changed" It seems that the test looks for `hrp39191.raw` (all lowercase) but the file has been added/moved as `HRP39187.raw` (HRP uppercase). And same for 39191 and 43022?

**Comment by shahrozahmed1** [comment]
@FedeMPouzols It seems to find 43022 so I assumed that it will find 39191 too, but I'll try change that around now

**Comment by FedeMPouzols** [comment]
By the way, I just checked what other system tests would be using those HRPD files and noticed that we have this system test: https://github.com/mantidproject/mantid/blob/master/Code/Mantid/Testing/SystemTests/tests/analysis/HRPDPowderDiffraction.py. @martyngigg : I see that you added this test a few months ago. Is it related to the "Aziz" scripts or a different or more recent variant?

**Comment by martyngigg** [comment]
@FedeMPouzols: The history on the system test files is now a bit misleading since they were moved from the old repository. That test is actually one of the oldest tests in the system, see https://github.com/mantidproject/systemtests/blob/master/SystemTests/AnalysisTests/HRPDPowderDiffraction.py  and I don't think it's that accurate a reflection of what they do or need anymore

**Comment by FedeMPouzols** [comment]
This looks good in principle. Only after we merge it into master we'll know if it goes well on all the CI plaforms.
My only concern would be: is this really running `_cleanup_files()`? Before the last commit, `cleanup()` (which is always called) was calling `_cleanup_files()` but that doesn't seem to be the case anymore, as `cleanup()` is not there.

**Comment by FedeMPouzols** [comment]
It is behaving well and it's great to have this full workflow test already in the system tests loop.
More checks and improvements will follow in another issue.

**Pull request merged**
