### PR TITLE
TOFTOF GUI: add temperature fields

### LINKED ISSUE #22588: TOFTOF GUI: add fields for temperature
Request from the instrument scientist. Sometimes the temperature is not present in the data files, but is required for the data reduction. GUI should provide an oportunity to input the temperature manually.

[ ] For data runs: the column `T [K]` should be added to the table
[ ] For Vanadium runs: the text input field `T [K]` should be added
[ ] For EC runs:  the text input field `T [K]` should be added

The input of temperature is optional.

If the temperature is not given, the data reduction script should not change. 

If the temperature is given, it should be used while adding a sample log:
```python
AddSampleLog(newVan, LogName='temperature', LogText=str(temperature), LogType='Number', LogUnit='K')
```
The `temperature` must be float.

JoachimCoenen will work on it.

### PR DESCRIPTION
**Pull request by JoachimCoenen**
**Description of work.**
added: 
 - temperature input fields for Vanadium runs and empty-can runs (optional)
 - a temperature input column to the data-runs table (optional)

changed:
 - moved `DataTableModel` and `DataTableView` classes from `TOFTOFSetupWidget` class to their own file.
 - Script generator sets `temperature` to ca constant value if the temperature for a run is set, otherwise it calculates it from the run log data

**To test:**
Start the TOFTOF data reduction GUI: Interfaces->Direct->DGS Reduction. Choose facility MLZ and instrument TOFTOF.

Get the test data
[testdata.zip](https://github.com/mantidproject/mantid/files/1356265/testdata.zip)

and make sure that the sample-log for 'temperature' is added to the Vanadium runs workspace is set to a the value set in the `T (K)`field, if (and only if) the field is not empty. Otherwise it should get the temperature from the runs own LogData.
For empty-can runs (EC-Runs) and each row of data-runs it should behave accordingly.

Fixes #22588. 

Does this update require release notes?
- [ ] Yes
- [ ] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by mganeva** [comment]
Bug: empty temperstures are saved to xml as a string  'None':
```xml
<van_temperature>None</van_temperature>
<ec_temp>None</ec_temp>
<data_temperature>None</data_temperature>
```
This causes then an error during loading of the last reduction settings:
```
mantid/scripts/Interface/reduction_gui/reduction/scripter.py", line 157, in getFloatList
    return map(float, value.split(','))
ValueError: could not convert string to float: None
```

**Comment by mganeva** [comment]
Bug:  All temperatures for the multiple data runs are saved to the xml file (`.mantid_last_toftof_reduction.xml`), but only the first one is loaded.

**Comment by JoachimCoenen** [comment]
the failed checks do seem to have nothing to do with the changed files.

**Comment by mganeva** [comment]
Now there is a problem with empty temperatures for Vanadium and empty can. The generated script looks like:
```python
wsVan = MergeRuns(wsRawVan)
wsVan.setComment('Van_res')
temperature = 
AddSampleLog(wsVan, LogName='temperature', LogText=str(temperature), LogType='Number', LogUnit='K')
# skip
wsEC = MergeRuns(wsRawEC)
wsEC.setComment('EC')
temperature = 
AddSampleLog(wsEC, LogName='temperature', LogText=str(temperature), LogType='Number', LogUnit='K')
DeleteWorkspace(wsRawEC)
```
empty temperatures for sample runs have no problem.

**Review by soininen — APPROVED** [review]
I tested this with the test data provided in the description. Different combinations of temperatures and empty fields seem to work as expected and I couldn't find any obvious way to inject garbage numbers to the system. This looks good to go.

**Comment by soininen** [comment]
Filling the reviewer checkboxes above reminded me that there should be some release notes regarding the recent changes in the interface.

**Pull request merged**
