### PR TITLE
Indirect - ConvFit - Incorrect plotting in Miniplot

### LINKED ISSUE #20697: Indirect - ConvFit - Miniplot - Incorrect Plotting
The mini-plot in the ConvFit interface is incorrectly plotting the fit function and the fitting range is being reverted when changing the spectrum, even after manually setting the range.

### PR DESCRIPTION
**Pull request by brandonhewer**
The output of running a convolution fit from the Indirect ConvFit interface was not correctly been used to update the miniplot in the interface, however, the main plot (and the plot obtained from clicking 'Plot Current Preview') was correct.

The fitting range (blue fit selectors) was also always defaulting back to it's original position when changing spectra, even if manually altered.

**Must be merged after #20642**

**To test:**
1. Navigate to Interfaces > Indirect > Data Analysis > ConvFit.
2. Supply the given Sample (\*\_red) workspace in the 'Sample' field.
3. Supply the given Resolution (\*\_res) workspace in the 'Resolution' field.
4. Select 'One Lorentzian' in the 'Fit Type' drop-down menu.
5. Select 'Fit Flat' in the 'Background' drop-down menu.
6. Click 'Run'.
7. Navigate through each spectra and ensure a reasonable fit was made and matches the plot created by clicking 'Plot Current Preview'.
8. Click and drag the blue dotted lines in the mini-plot and change the 'Plot Spectrum' spinner, ensuring they remain in their new location.

**Test Files:**
[ConvFit-TestFiles.zip](https://github.com/mantidproject/mantid/files/1353254/ConvFit-TestFiles.zip)

Fixes #20697. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@brandonhewer Is this supposed to be based off `release-v3.11`?

**Comment by brandonhewer** [comment]
@martyngigg No it isn't, thanks for the spot!

**Comment by martyngigg** [comment]
@brandonhewer Can we get this moving?

**Comment by martyngigg** [comment]
@brandonhewer There's a new cppcheck warning that has cropped up.

**Review by jmborr — APPROVED** [review]
Corrections work as intended

**Pull request merged**
