### PR TITLE
Fix unstable RemoveExpDecay test

### PR DESCRIPTION
**Pull request by eXeC64**
This is for trac ticket [#11142](http://trac.mantidproject.org/mantid/ticket/11142).

The RemoveExpDecay test is failing irregularly. This pull request simplifies the test, attempting to make it more robust, and removes the need to load data from disk, which should also improve performance.

**Testing**: Let this branch build and its tests run, and retest it at least another four times to see if the issue has been resolved.

### CODE REVIEW

**Comment by martyngigg** [comment]
This is a great start but it would be great if all of the references to the `AnalysisDataService` are removed. They should not longer be necessary. The algorithms can be set as a child and then the output workspace can be retrieved with `alg->getProperty("OutputWorkspace")`

**Comment by DanNixon** [comment]
Jenkins, retest this please.

**Comment by DanNixon** [comment]
There is a compile error on RHEL6.

**Comment by martyngigg** [comment]
Jenkins, retest this please.

**Comment by martyngigg** [comment]
The changes look good now, let's hope that it makes some difference.

**Pull request merged**
