### PR TITLE
Engg GUI: move RB number field

### LINKED ISSUE #14109: EnggDiffraction GUI: move RB number field to general widget
It is not anymore specific to the calibration tab, so move it from there to the general widget.

### PR DESCRIPTION
**Pull request by FedeMPouzols**
Fixes #14109.

**To test**: 
- Check that the RB number is now visible on top, not only for calibration. 
- If it's empty all the tabs should be disabled / you should not be allowed to do anything
- It should be remembered from previous sessions, as usual

### CODE REVIEW

**Comment by shahrozahmed1** [comment]
The GUI does what it says, interesting feature which only enables GUI to be utilised when the user has provided a RB number and also remembers the RB-number from the previous session. Maybe a valid check (of 6 digits) for RB-number could be included? As for now RB-number seems to accept everything really.. including symbols.

**Comment by FedeMPouzols** [comment]
Yes, this currently accepts any non-empty string as an RB number. We have to check with Saurabh what strings would be acceptable and what constraints they'd like to enforce. We could for example add the RB prefix and then expect a certain number of digis or alphanumeric characters, but that's not fixed for now.
Later on we might add something that retrieves the possible RB numbers from the catalog (that could be an RB number widget eventually), although it might be needed to leave the possibility for the user to type in any string manually, for special use cases.

**Comment by shahrozahmed1** [comment]
In that case this branch is ready to be merged.

**Comment by FedeMPouzols** [comment]
Yep, let's keep that point about accepted/acceptable RB numbers in the list of points to discuss with Saurabh.

**Pull request merged**
