### PR TITLE
Start removing raw owning pointers from Mantid::Geometry

### PR DESCRIPTION
**Pull request by quantumsteve**
This replaces the owning raw pointer `Surface *` with `boost::shared_ptr<Surface>` and `std::unique_ptr<Surface>`. 

The primary goal is to help developers by clarifying ownership. There were some cloning of surfaces that shouldn't be necessary with shared ownership. I added this to the [release notes](http://www.mantidproject.org/index.php?title=ReleaseNotes_3_6_Framework_Changes&diff=25442&oldid=25416). 

I left `SurfPoint::getKey()` returning a raw non-owning(?) pointer. Is this correct?

testing: code review

### CODE REVIEW

**Comment by quantumsteve** [comment]
RHEL6 build fails because of a bug in gcc 4.4

http://stackoverflow.com/questions/7342703/gcc-4-4-4-5-unique-ptr-not-work-for-unordered-set-unordered-map

**Comment by SimonHeybrock** [comment]
Regarding the `clone()` method of various subclasses: They used to have covariant return types, but now they all return `std::unique_ptr<Surface>`. I think we should preserve the covariant return types, which is unfortunately extra work when it is a smart pointer.
Maybe I would not have noticed if I had not done the same recently for `Workspace::clone()`, see https://github.com/mantidproject/mantid/pull/12951 for an example how to do it.

**Comment by SimonHeybrock** [comment]
To clean up a little further: You have some destructors that are now empty due to the use of smart pointers. Maybe it makes sense to remove them altogether?

**Comment by quantumsteve** [comment]
I updated `clone()` so that it preserves the covariant return types and also deleted empty destructors in derived classes.

**Comment by quantumsteve** [comment]
I added the missing clone function and updated doClone() to look more like the doClone() member function in Workspace. 

I also created a separate ticket #14321 for making the copy constructor and assignment operator private.

**Comment by SimonHeybrock** [comment]
Thanks for fixing all these small bits!

SystemTest `LoadLotsOfInstruments` passes for me, so I think this is ready for merging.

**Pull request merged**
