### PR TITLE
Remove First Last From ALC Interface And Replace With Single Runs Box

### LINKED ISSUE #24839: ALC to use MDW run box
In the ALC interface we want to replace the to and from boxes with the generic MDW run widget.

### PR DESCRIPTION
**Pull request by Matt-Cumber**
**Description of work.**
Updated the ALC interface to now only have a single input box for runs instead of a first and a last one. In doing, the auto checkbox has been changed to now only find the last run if possible and no longer watches for files to be added and removed from the data directory. This has been confirmed to be an okay change from Stephen Cottrell, if the feature is requested again it can be added back in as a separate issue.

**NOTE:** This work was rebased off this other pull request #29185 which has been reviewed separately so ignore changes made from before **Aug 26**

**To test:**

1. Set default instrument to **MUSR**
2. Open the ALC Interface (Interfaces->Muon->ALC)
3. Enter into runs `15189-15191` and hit enter. Log combo box should be updated and you can now press load
4. Try checking auto. With the same input as before auto should change runs to `15189-15193,15195`. It is changed to this as it has found 15195 to be the most recent run in the directory of 15189, and run number 15194 does not exist in this directory so it has been excluded. 
5. Try pressing load again now
6. Hopefully no errors have come up so far, feel free to try different variations as input into runs. There are mocking tests which try to test it fully.

Fixes #24839  

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
this depends on #29185, however it has been approved and should be in the code base soon

**Comment by gemmaguest** [comment]
@Matt-Cumber Could you rebase this onto master now that the other PR is merged? It will really help me to see what changes are included in this PR :) It might be good to squash some commits at the same time. If you're not sure how/why on either of those let me know and I can talk you through it.

**Review by gemmaguest — CHANGES_REQUESTED** [review]
I managed to extract the changes related to this PR so no hurry for rebasing on master.

- Functional testing is all good - works as described and handles invalid input well (e.g. incorrect run numbers and bad strings) :+1:
- Code quality is very good :+1:
- I've added some in-line comments mostly to do with moving a bit of the logic from the view into the presenter if that's possible (but let me know if there was a reason for doing it this way!).
- The documentation [here](https://docs.mantidproject.org/nightly/interfaces/Muon%20ALC.html#data-loading) needs updating.
- The release notes could be more brief - it's good to keep these as concise as possible so that users can quickly scan through them. You can always link to the docs if more detail is required.

**Comment by AnthonyLim23** [comment]
@gemmaguest some of these changes require a developer environment. @Matt-Cumber is currently unable to connect to his. Could he make the smaller changes using the `suggestion` button on here and then do the other things as maintenance later?

**Comment by gemmaguest** [comment]
> 
> 
> @gemmaguest some of these changes require a developer environment. @Matt-Cumber is currently unable to connect to his. Could he make the smaller changes using the `suggestion` button on here and then do the other things as maintenance later?

I think he's back in now but also these are suggestions not hard requirements so it's somewhat Matt's/your call how much you want to tidy this - there's a lot that could be tidied up in these files so I don't think it's worth a maintenance task to tidy up some small parts and not others. I'm making the suggestions because if it can be done easily now it would save some potential technical debt, but I don't want to hold up the PR.

**Comment by Matt-Cumber** [comment]
> > @gemmaguest some of these changes require a developer environment. @Matt-Cumber is currently unable to connect to his. Could he make the smaller changes using the `suggestion` button on here and then do the other things as maintenance later?
> 
> I think he's back in now but also these are suggestions not hard requirements so it's somewhat Matt's/your call how much you want to tidy this - there's a lot that could be tidied up in these files so I don't think it's worth a maintenance task to tidy up some small parts and not others. I'm making the suggestions because if it can be done easily now it would save some potential technical debt, but I don't want to hold up the PR.

I am back to working and I can do some small tidy ups of separating things as functions. In terms of moving things from the view to the presenter I'm not sure if will have time today as I also have another PR that needs some final tweaks

**Comment by gemmaguest** [comment]
Ok, thanks Matt. I think it _should_ just be a straightforward cut and paste to move `extractRunNumber` and `m_oldInput` and related functions to the presenter, but your call.

I forgot to ask - are the changes in the test results expected? It wasn't obvious to me why those values have changed?

**Comment by gemmaguest** [comment]
Don't worry about squashing the commits, but a rebase onto master would still be useful.

**Comment by AnthonyLim23** [comment]
The tests have changed because the settings for the analysis are different. Before it was not setting the integration range

**Review by gemmaguest — APPROVED** [review]
Thanks for the changes, and well done for getting them all done so quickly! This all looks good now and still works as expected. Happy to merge when tests pass :+1:

**Pull request merged**
