### PR TITLE
Engg: implement first GUI

### LINKED ISSUE #9213: Engin-X - Umbrella Issue/ticket - up to a first basic GUI
This issue was originally [TRAC 8368](http://trac.mantidproject.org/mantid/ticket/8368)

This ticket is blocked by : 
 - [X] [TRAC8760](http://trac.mantidproject.org/mantid/ticket/8760)
 - [X] [TRAC9783](http://trac.mantidproject.org/mantid/ticket/9783)
 - [X] [TRAC9784](http://trac.mantidproject.org/mantid/ticket/9784)
 - [X] [TRAC9789](http://trac.mantidproject.org/mantid/ticket/9789)
 - [X] [TRAC9790](http://trac.mantidproject.org/mantid/ticket/9790)
 - [X] [TRAC9791](http://trac.mantidproject.org/mantid/ticket/9791)
 - [X] [TRAC10587](http://trac.mantidproject.org/mantid/ticket/10587)- Issue #11429 - use ConvertUnits wherever possible
 - [X] [TRAC10589](http://trac.mantidproject.org/mantid/ticket/10589) - became duplicate
 - [x] [TRAC10907](http://trac.mantidproject.org/mantid/ticket/10907) - Issue #11746 - FindPeaks behavior with expected peaks
 - [X] [TRAC10909](http://trac.mantidproject.org/mantid/ticket/10909) - Issue #11748 - EnginXFitPeaks output table
 - [x] [TRAC10910](http://trac.mantidproject.org/mantid/ticket/10910) - Issue #11749 - expected peaks loading
 - [X] [TRAC10921](http://trac.mantidproject.org/mantid/ticket/10921) - Issue  #11760 - unit tests
 - [X] [TRAC10967](http://trac.mantidproject.org/mantid/ticket/10967) - Issue #11806 - EnginXCalibrate output table
 - [X] [TRAC10968](http://trac.mantidproject.org/mantid/ticket/10968) - Issue  #11807 - bank interpretation (dupl).
 - [x] [TRAC10969](http://trac.mantidproject.org/mantid/ticket/10969) - Issue  #11808 - bank interpretation
 - [x] [TRAC11588](http://trac.mantidproject.org/mantid/ticket/11588) - Issue #12426 - add Vanadium
 - [x] [TRAC11770](http://trac.mantidproject.org/mantid/ticket/11770) - Issue #12608 - mock up for first GUI
 - [x] [TRAC11771](http://trac.mantidproject.org/mantid/ticket/11771) - Issue #12609 - save calibration file
 - [ ] [TRAC11772](http://trac.mantidproject.org/mantid/ticket/11772) - Issue #12610 - first GUI
 - [x] [TRAC11773](http://trac.mantidproject.org/mantid/ticket/11773) - Issue #12611 - save .par files as needed
 - [x] [TRAC11862](http://trac.mantidproject.org/mantid/ticket/11862) - Issue #12700 - apply calibration from EnginXCalibrate full to input workspace detector positions.
 - [x] Issue #12926, use `InputWorkspace` input properties in all EnginX algorithms.
 - [x] issue #13184, add EnggVanadiumCorrections algorithm.

An "umbrella" ticket for any work to be done for Engin-X.

2015/06/22: edited with new github issue numbers and current status.

### LINKED ISSUE #12610: Make first version of ENGIN-X GUI
This issue was originally [TRAC 11772](http://trac.mantidproject.org/mantid/ticket/11772)

Original Reporter: @FedeMPouzols 

This ticket is blocked by : 
 - [x] [TRAC11771](http://trac.mantidproject.org/mantid/ticket/11771)
 - [x] [TRAC11773](http://trac.mantidproject.org/mantid/ticket/11773)
 - [x] Issue #13184 (EnggVanadiumCorrections algorithm)

This ticket is blocks :  [TRAC8368](http://trac.mantidproject.org/mantid/ticket/8368)

Following the mock up from http://trac.mantidproject.org/mantid/ticket/11770.

This should cover the steps that produce a .par file (which contains at least the `Difc` and `zero` outputs from algorithm ``.

### PR DESCRIPTION
**Pull request by FedeMPouzols**
Fixes #12610, and closes #9213 (initial ENGIN-X umbrella ticket). This introduces a first version of the Engg/ENGIN-X GUI. You can open it from the main menu bar: Interfaces -> Diffraction -> Engineering Diffraction

**To test**:
- Code review. this comes with a few tests on the GUI presenter which should be good enough to cover basic functionality and most error cases.
- A relatively simple manual test could be done following the steps given below.

Steps to use the interface:
- You need to set some parameters in the tab "Settings":
  - "Input directories", "Raw files": set the folder '\olympic\Babylon5\Public\fedemp\ENGIN-X\GUI_calib_folder` (or a copy of this folder with the same ENGINX run files included in it).
  - For a first time setup: you need to generate the 'pixel calibration' that is done every several years (full calibration). You can use the file included with the test data: '\olympic\Babylon5\Public\fedemp\ENGIN-X\GUI_calib_folder\ENGINX_full_pixel_calibration.csv`. In the "Settings" tab, "Pixel calibration", click browse and select that file.
  - Leave other options as defaults:
    - The template GSAS file should be automatically found in the sources (or where the EnggUtils script is found).
- Then you can use the Calibrate tab to make a calibration:
  - You can put anything in "RB Number", or leave it empty, as it is not effectively used at the moment.
  - Make new calibration box: enter Vanadium #: 236516, and Ceria #: 241391 (these values are provided by default on startup at the moment).
  - Click Calibrate.
  - The calibration should be generated and it should become the current calibration.
  - You can also load it using the button "Load existing calibration" in "Current Calibration"

Please consider this as a starting point. There are several points to improve in follow-up (and smaller) pull requests. In particular these need short-term improvement for sure:
- The documentation would need several clarifications and additions, but the current version at least describes the main actions and parameters.
- Vanadium and Ceria run numbers are entered as run numbers as in the initial plan - but I think this could work better with the MWRunFiles widget. We have to check this with Saurabh. Related to this, in this current version if you enter a wrong Ceria or Vanadium number and the file is not found you will see the error at the time you try to generate the new calibration, and not as soon as you enter the wrong (unavailable) number which I think is preferable. This needs improvement (or if we finally use the MWRunFiles widget this issue would be fixed for free).
- It follows an MVP pattern but without the M for model, as for now a handful of workspaces play the role of the model. It's probably a good idea to create a model class as it grows.
- The settings (settings tab) are persistent between Mantid sessions. In addition, some of the parameters of the calibration tab (example: current vanadium and ceria run numbers) should be made persistent as well, unless it could create confusion. We have to clarify this with scientists.
- A few more tests should be added (there are some comments about this in the code).

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
@Anders-Markvardsen : after this morning's meeting with Saurabh I'm going to make a few small cosmetic changes in this branch, so I'm leaving it as "In progress" for now.

There will be more changes and additions but I'll add those in new issues/pull requests, as this one got already quite big.

**Comment by Anders-Markvardsen** [comment]
Hi Federico,

OK just let me know, and unless you hear otherwise I will aim to test within a day.

Anders

**Comment by FedeMPouzols** [comment]
@Anders-Markvardsen : I just re-assigned this PR to @shahrozahmed1. @shahrozahmed1 : this is "In progress" so not quite ready to test. As soon as it is ready I'll explain to you what this is about and how to test/validated pull requests.

**Comment by FedeMPouzols** [comment]
@shahrozahmed1 : good catch on the issue with network drives. I think that the last commit fixes that issue. See the commit comments for what was happening.

**Comment by shahrozahmed1** [comment]
This fixes the issue #12610 . The first version of ENGIN-X GUI seems to run smooth on Windows, no more path issues with network drives now and the documentation looks decent too, thus it is closed.

**Pull request merged**
