### PR TITLE
Feature/10878 peak shape

### PR DESCRIPTION
**Pull request by OwenArnold**
Build PeakShape functionality into the PeaksWorkspaces of Mantid.

The ISAW peak format will not be updated, but the NeXus format should be.
Saving routines for PeaksWorkspaces should include the new shape information
For persistence, remember that changes to Loading routines following file format changes should be robust to loading existing PeaksWorkspaces.
This ticket is not yet concerned with using PeakShape objects as part of the the integration algorithms. That is an additional step.

[#10878](http://trac.mantidproject.org/mantid/ticket/10878)

### CODE REVIEW

**Comment by OwenArnold** [comment]
test this please

**Comment by OwenArnold** [comment]
test this please

**Comment by FedeMPouzols** [comment]
Tests have been passing, including the sys test LoadLotsOfFiles.
It comes with new tests/test cases and the code looks well organized and documented.

The only irregularity that I could spot is that some of the data members of the Peak class don't have the 'm_' prefix, but that's not related to this ticket and could be fixed in follow-up tickets, if we want to be fussy about it.

**Comment by FedeMPouzols** [comment]
Oops, it seems that valgrind has detected some leaks in PeakShapeSpherical, etc. (http://builds.mantidproject.org/job/valgrind_develop_core_packages/308/valgrindResult/pid=17860/).

**Pull request merged**
