### PR TITLE
Improve documentation for some fitting functions

### LINKED ISSUE #16447: Muon fitting functions: improve documentation
The documentation of the following fitting functions:

- http://docs.mantidproject.org/nightly/fitfunctions/Abragam
- http://docs.mantidproject.org/nightly/fitfunctions/ExpDecayMuon
- http://docs.mantidproject.org/nightly/fitfunctions/ExpDecayOsc
- http://docs.mantidproject.org/nightly/fitfunctions/GausDecay
- http://docs.mantidproject.org/nightly/fitfunctions/GausOsc
- http://docs.mantidproject.org/nightly/fitfunctions/StaticKuboToyabe
- http://docs.mantidproject.org/nightly/fitfunctions/StaticKuboToyabeTimesExpDecay
- http://docs.mantidproject.org/nightly/fitfunctions/StaticKuboToyabeTimesGausDecay
- http://docs.mantidproject.org/nightly/fitfunctions/StaticKuboToyabeTimesStretchExp
- http://docs.mantidproject.org/nightly/fitfunctions/StretchExpMuon

could be improved. In particular, formulas could use greek letters and math symbols. See [here](http://docs.mantidproject.org/nightly/fitfunctions/Keren) for an example. Descriptions of fitting parameters can be improved too.

### LINKED ISSUE #16529: "Calibrate" fitting functions: improve documentation
Improve documentation for the following fitting functions:

- [EndErfc](http://docs.mantidproject.org/nightly/fitfunctions/EndErfc.html)
- [ProductLinearExp](http://docs.mantidproject.org/nightly/fitfunctions/ProductLinearExp.html)
- [ProductQuadraticExp](http://docs.mantidproject.org/nightly/fitfunctions/ProductQuadraticExp.html)

See [here](http://docs.mantidproject.org/nightly/fitfunctions/SCDPanelErrors) and [here](http://docs.mantidproject.org/nightly/fitfunctions/PeakHKLErrors) for examples.

### PR DESCRIPTION
**Pull request by raquelalvarezbanos**
Sulaimaan, a work experience student at ISIS, has improved the equations for some fitting functions. I am creating this PR with his changes.

**To test:**

Build the documentation and make sure that the new expressions are equivalent to those in http://docs.mantidproject.org/nightly/fitfunctions/

Fixes #16447.
Fixes #16529.

I don't think this needs to be in the release notes.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by ElliotAOram** [comment]
All the documentation change look good. However, in the `Abragam` fit function one of the property (fitting parameter) descriptions is just a `?` this can be seen in the [c++ code](https://github.com/mantidproject/mantid/blob/87309b9c758ce42653a1672c34dc6e66c6fe2a16/Framework/CurveFitting/src/Functions/Abragam.cpp#L25) @raquelalvarezbanos should we update this as part of this issue?

**Comment by raquelalvarezbanos** [comment]
Yes, that should be updated too. The problem is that I haven't been able to find the original article where the Abragam function was first introduced. I've found similar expressions but they do not match exactly what muon scientists are using in Mantid. Therefore, I can't be sure what `tau` refers to. For instance I would think that tau is the muon mean lifetime, but whoever wrote the function thought that `sigma` was the decay rate. Both are related as `tau` = 1/`sigma`, so it does not make sense to have the same thing as two different fitting parameters, hence one of us must be wrong. As it could be me, I've decided to leave the documentation for the fitting parameters as it is now.

**Comment by ElliotAOram** [comment]
That makes sense and in which case I think we can leave this to be solved at a later date. Everything else works as expected :shipit:

**Comment by FedeMPouzols** [comment]
Pretty disturbing that the interpretation of the `tau` and `sigma` is not clear!

It seems that this function was added some years ago by @KarlPalmen? https://github.com/mantidproject/mantid/blame/master/Framework/CurveFitting/src/Functions/Abragam.cpp
Karl could you provide any feedback on this, or if it was someone else would you have any idea?

**Comment by tom-perkins** [comment]
@FedeMPouzols @raquelalvarezbanos I've opened an issue to confirm with the scientists what the parameters represent at the next meeting we have. Once we have this information, the documentation can be updated with the correct information.

**Comment by KarlPalmen** [comment]
I have no idea about these parameters.

**Comment by KarlPalmen** [comment]
Which issue did @tom-perkins open?

**Comment by raquelalvarezbanos** [comment]
He opened this issue: https://github.com/mantidproject/mantid/issues/17108

**Comment by KarlPalmen** [comment]
Thank you @raquelalvarezbanos .

**Pull request merged**
