### PR TITLE
share normalization between runs in muon analysis

### LINKED ISSUE #19715: Muon TFAsymmetry share normalization between runs
The muon group would like to be able to fix the normalization and then have it applied to a new run.

### PR DESCRIPTION
**Pull request by AnthonyLim23**
~~To be merged after #19706~~

The normalization can now be shared between runs in TF asymmetry mode of muon analysis. 
**To test:**

To test load some muon data (e.g. MUSR00064748 ) and go to the data analysis tab. The normalization should be shown in the data table. The row below (fix normalization) should be false. 

If you add a function to fit to. Then look in the fit menu, TF Asymmetry fit should be enabled. 

If you then click the tick box for fix normalization (so its true) then look in the fit menu, TF asymmetry fit should be disabled. Ticking the box again should enable the TF asymmetry fit. 

Make a note of your normalization. Make sure that keep normalization is ticked. Go to the home tab and load some different data (e.g. MUSR00064728). Then go to the data analysis tab. The normalization should be the same as the one you noted down. 

The plot will probably not be centered on zero. As a final check untick the keep normalization box and then reload the data (you will have to load something else then reload the data). The normalization should be different and the plot centered on zero. 

Fixes #19715 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
The only problem seems to be that it cannot archive the data.

**Comment by NickDraper** [comment]
Agreed, the RHEL build passed and all the tests, but failed when archiving the artefacts.  This is ready for testing.

**Comment by NickDraper** [comment]
All good, functional tests are fine, but where's the release notes?

**Comment by NickDraper** [comment]
All good :shipit:

**Pull request merged**
