### PR TITLE
Rename v4.3.0 release notes to v5.0.0

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Rename release notes for v5.0.0 release

**To test:**

4.3.0 references should now be 5.0.0
Docs build should have no warnings.

Refs #27754

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by cailafinn — APPROVED** [review]
Docs building without warnings. All evidence of 4.3 removed.

**Comment by martyngigg** [comment]
@mantidproject/gatekeepers Could we get this merged soonish, please?

**Comment by SimonHeybrock** [comment]
I cannot, it is restricted.

**Comment by martyngigg** [comment]
@SimonHeybrock You weren't on the `release-next` access list for some reason. I've added you.

**Pull request merged**
