### PR TITLE
Allow user to manually specify merge point

### LINKED ISSUE #21027: Allow user to manually specify merge point.
For a merged reduction of sans data, allow the user to manually specify the crossover point between the high and low angle banks.

### PR DESCRIPTION
**Pull request by Matthew-Andrew**
This work, adds the ability to specify the cross-over point between the LAB, merged data and the HAB in SANS reduction. It is currently implemented only for the new GUI. 

**To test:**
- Get the SANS data from http://download.mantidproject.org/. The ISIS sample data has some SANS data in a folder called loqdemo.
- Add this folder to your directories
- Open mantid, go to interfaces->SANS->ISIS SANS V2
- Load the maskfile.txt from the folder as a user file.
- Load the batch_mode_reduction.csv as the batch file
- Deletes the output name from the row
- Go to Settings-> General and select All reduction
- Go to runs and click Process, Wait
- Go to Settings->General and select merged reduction
- Tick Use Range Box, put 0.1 and 0.2 in the two boxes below.
- Go to runs and click Process, Wait
- Plot all three output workspaces
- Confirm that the merged reduction matches LAB below 0.1, HAB above 0.2 and is an average of the two between these two values.

Code review

Fixes #21027 . 

**Release Notes** 
Has been added to release notes.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by NickDraper — CHANGES_REQUESTED** [review]
Ran through the example (with my default instrument set to LARMOR).

I got this error message in the log when loading the batch file.

```
Loading of the batch file failed. Ensure that the path to your files has been added to the Mantid search directories! See here for more details: Unable to find file: search object 74044
```

If I changed my default instrument to LOQ it worked fine

**Comment by NickDraper** [comment]
Tab order is a mess on the settings tab, specifically in the Q range merge it goes to, from, use merge

**Comment by NickDraper** [comment]
Other than that all is good.

**Comment by Mantid-Matthew** [comment]
I have created the issues #21231 to deal with changing how the instrument is used to search for files.

**Comment by NickDraper** [comment]
The tab order is fixed, this is good to go

**Review by NickDraper — APPROVED** [review]

**Pull request merged**
