### PR TITLE
Ensure DeadTime resets on Muon GUIs when instrument changes

### LINKED ISSUE #29412: Reset the Muon GUI
When the user changes instrument the GUI should fully reset.

good starting place:
https://github.com/mantidproject/mantid/blob/9fb3dca5d87f92b72f68ec366078e9da7d083332/scripts/Muon/GUI/MuonAnalysis/muon_analysis_2.py#L280

e.g.
If you load some data, set dead time table to from table workspace. Then change instrument the deadtime table still points at the old instrument

MA and FDA doesnt reset properly after changing instrument or pressing clear

### PR DESCRIPTION
**Pull request by Pasarus**
**Description of work.**
Force the Muon GUIs to reset the DeadTime property in the Instrument Widget when the instrument is changed.

**To test:**
- Open Workbench
- Open Interfaces->Muon Analysis
- Load in an EMU nexus file
- Set dead time to `from table workspace`
- Then change instrument 
- It should be reset to `from file`

Fixes #29412 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by AnthonyLim23 — APPROVED** [review]
Looks good to me and it resets when the instrument is changed but not the run. I like the new test.

**Comment by martyngigg** [comment]
I've just realised this was targeted at master but has the release 5.1 milestone. I assume it should be on the release branch?

**Comment by martyngigg** [comment]
I can merge this manually if needs be.

**Comment by AnthonyLim23** [comment]
yes please

**Comment by martyngigg** [comment]
:+1: Done.

**Pull request merged**
