### PR TITLE
Re #21134: Fixed incorrect title when transfering runs with th in their name.

### LINKED ISSUE #19260: Some runs are not transferred properly to the processing table
In the new Reflectometry GUI, select investigation ID=1620342 (INTER) and transfer the following runs:

42704 - Sample 2 PCE11 1-chloronaphthalene pre-annealed after very short drying th = 0.5
42705 - Sample 2 PCE11 1-chloronaphthalene pre-annealed after very short drying th = 2.3
42671 - Sample 4 3% 1-chloronaphthalene th=0.5
42672 - Sample 4 3% 1-chloronaphthalene th=2.3
42673 – Sample 4 3% 1-chloronaphthalene Heating up to 100C th=0.5
42674 – Sample 4 3% 1-chloronaphthalene annealing at 100C th=0.5
42675 – Sample 4 3% 1-chloronaphthalene annealing at 100C th=2.3

to the processing table. The first two are put in a group with incomplete name “Sample 2 PCE11 1-chloronap”. The last five are put in the same group, named "Sample 4 3% 1-chloronaph", but they should be under different groups:

-	Sample 4 3% 1-chloronaphthalene
	42671, 0.5
	42672, 2.3
-	Sample 4 3% 1-chloronaphthalene Heating up to 100C
	42673, 0.5
-	Sample 4 3% 1-chloronaphthalene annealing at 100C
	42674, 0.5
	42675, 2.3

I believe the problem is when parsing the run title, because it contains a **th** the interface gets confused and takes only the first part of the name. I believe it is safe to assume that theta will be always specified like **th=** but this is something we have to check first with instrument scientists.

### LINKED ISSUE #21134: ReflLegacyTransferStrategy broken for runs with 'th' in the name.
### Expected behavior
Loading runs with `th` in the title before `th=1.5` (for theta of 1.5) should transfer the entire title into the table on the reflectometry GUI. e.g. `Tether th=1.5 -> Tether`

### Actual behavior
Transfering such runs only copies the title up to the character before the first occurence of `th`. e.g. `T`

### Steps to reproduce the behavior
1. Open the reflectometry GUI.
2. Set the instrument to `OFFSPEC`
3. Enter the investigation id: `1720380` and click search.
4. Transfer the runs with tether in their names into the table.

### Platforms affected
All

### PR DESCRIPTION
**Pull request by edwardb96**
#### Description Of Work ####
- Minor refactoring on `ReflLegacyTransferStrategy`
- Uses additional capturing groups to capture text before and after the theta value eliminating the need for the `find("th")` hack.
- Removes support for `in {angle} theta` style descriptions.
- Switches to `std::regex` over `boost::regex` now that named capture groups are no longer required.

**To test:**
1. Open the reflectometry GUI.
2. Set the instrument to `OFFSPEC`
3. Enter the investigation id: `1720380` and click search.
4. Transfer all the runs into the table and ensure that: 
    - The the titles match the descriptions with the `th=..` trimmed.
    - The the runs where the descriptions only differ by their theta value have been grouped with the run numbers separated by a `+`.
5. Follow the instructions in #19260 and ensure that the bug is no longer present.
6. Code review

Fixes #21134 and fixes #19260. 

**Release Notes** 
*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gemmaguest** [comment]
I think this also fixes #19260 so we should test that too.

**Comment by gemmaguest** [comment]
Good question on whether `Trim.h/cpp` belong somewhere else. Seems like they should but I'm not sure where. Could you ask on Slack?

**Comment by edwardb96** [comment]
@gemmaguest I believe this is ready to go again.

**Review by gemmaguest — APPROVED** [review]
All looks good now :+1:

**Pull request merged**
