### PR TITLE
Set min length and adjust policy for algorthm combo box

### LINKED ISSUE #28827: Dialog Size assumes short WS name
**Original reporter:** Stephen King @smk78 
The Algorithm Dialog box currently assumes that Workspace names are less than a certain length and does not resize horizontally for particularly long ws names. We should not make this assumption.
### Expected behavior
The algorithm Dialog appears large enough to show all functionality 
### Actual behavior
In this case, the user had a rather long ws name, so the "Replace InputWorkspace name as Output WS name" button was not visible, as the Dialog did not horizontally resize. 
### Steps to reproduce the behavior
run `SupercalifragilisticexpialidociousSomethingQuiteAtrocious = CreateSampleWorkspace()`
Right-click on the workspace and select Rename. Can you see the 
Screenshot 2020-06-11 at 09 27 54 button? 
This issue may manifest itself differently for different screens / OSs.
Basically, the extent of the InputWorkspace box is going beyond the dialog edge.
### Platforms affected
Plot and WB all, noticed in Plot 5.0 on Windows

### PR DESCRIPTION
**Pull request by samtygier-stfc**
OptionsPropertyWidget, use setSizeAdjustPolicy() and setMinimumContentsLength()

Fixes 28827

**Description of work.**

OptionsPropertyWidget, use setSizeAdjustPolicy() and setMinimumContentsLength()

**To test:**

See  

Fixes #28827

*This does not require release notes* because **small change?**

Before and after:
Screenshot at 2020-11-23 12-21-31

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by Matt-Cumber — CHANGES_REQUESTED** [review]
For me the dialog still opens as shown below. I am using Windows. Also as a reminder, remember to connect PR's to ZenHub which can be found at the bottom of the PR.

**Comment by samtygier-stfc** [comment]
Thanks. I guess UI work needs checking on each OS.

Would it be possible to check if my patch has any effect on the size of the input field? I think on master you should see that the input field tries to grow to the length of the workspace name, and so can be huge. With this patch it should stay a reasonable size, even if you have to drag the dialog wider to see it.

If that's the case, then I just need to make sure that the dialog is wide enough to see it.

**Comment by Matt-Cumber** [comment]
Yes it does force the combo box to be a sensible size, it's just the dialog needs a small resize when it pops up to fit the missing button in. Maybe have a try and see if you can get an easy fix so it resizes on pop up, otherwise I still think this is a nice small non-mantid-breaking PR that can go in. Nice work

**Comment by samtygier-stfc** [comment]
Just got my windows build set up, and the above patch does seem to help for me. Do you have a hidpi screen?

windows

**Comment by Matt-Cumber** [comment]
> Just got my windows build set up, and the above patch does seem to help for me. Do you have a hidpi screen?
> 
> windows

If I'm honest I don't really know

**Comment by samtygier-stfc** [comment]
So i think there are 2 required parts to fixing this.

1) Making sure that the OptionsPropertyWidget stays a reasonable size, i.e. does not grow huge for long workspace names
2) Make the dialog wide enough to fit a reasonable sized OptionsPropertyWidget. 

The current patch only did the first part. The second part is complicated by the use of the QScrollArea set to only have vertical scrolling. And maybe the difference between lengths measured in character length and in pixels. WIP

**Comment by Matt-Cumber** [comment]
> So i think there are 2 required parts to fixing this.
> 
> 1. Making sure that the OptionsPropertyWidget stays a reasonable size, i.e. does not grow huge for long workspace names
> 2. Make the dialog wide enough to fit a reasonable sized OptionsPropertyWidget.
> 
> The current patch only did the first part. The second part is complicated by the use of the QScrollArea set to only have vertical scrolling. And maybe the difference between lengths measured in character length and in pixels. WIP

By the sounds of it, it seems like it's too much work for such a small benefit, and your time might be better spent somewhere else? If you agree we can get this one in as is

**Comment by samtygier-stfc** [comment]
Just as a quick test, does this help at all? Might be a simple way to force the outside of the scroll area to be wide enough.

**Comment by Matt-Cumber** [comment]
> Just as a quick test, does this help at all? Might be a simple way to force the outside of the scroll area to be wide enough.

It's still the same for me, that doesn't seem to have changed anything (at least with the renaming window)

**Comment by samtygier-stfc** [comment]
If you change the value in qt/widgets/common/src/AlgorithmPropertiesWidget.cpp line 75. E.g. `setMinimumWidth(1000);` does it do anything?

**Comment by Matt-Cumber** [comment]
> If you change the value in qt/widgets/common/src/AlgorithmPropertiesWidget.cpp line 75. E.g. `setMinimumWidth(1000);` does it do anything?

Did a bit of testing 800 width seems to be about the minimum size for the window to fit everything on, but this is for me, might be worth getting some over people to check this too

**Comment by samtygier-stfc** [comment]
And if you replace the `setMinimumWidth` line with:

```C++
setObjectName("AlgorithmPropertiesWidget");
setStyleSheet("#AlgorithmPropertiesWidget {min-width: 30em;}"
```

**Comment by Matt-Cumber** [comment]
> And if you replace the `setMinimumWidth` line with:
> 
> ```c++
> setObjectName("AlgorithmPropertiesWidget");
> setStyleSheet("#AlgorithmPropertiesWidget {min-width: 30em;}"
> ```

30 is a bit much, just trying over values now

**Comment by samtygier-stfc** [comment]
25em looks good on standard DPI linux.

**Review by Matt-Cumber — APPROVED** [review]
Going to approve now as I have tested the changes already and nothing else should break. Good to go when all checks pass. Good job 👍

**Comment by Matt-Cumber** [comment]
We can still get someone to test on OSX but it will most likely be fine

**Review by DanielMurphy22 — COMMENTED** [review]
I can confirm this works well on MacOS! (ignoring the ? button in the bottom left that's always been a problem on Mac...)
Screenshot 2020-12-02 at 14 10 13

**Comment by Matt-Cumber** [comment]
> I can confirm this works well on MacOS! (ignoring the ? button in the bottom left that's always been a problem on Mac...)
> Screenshot 2020-12-02 at 14 10 13

Great thanks! @DanielMurphy22

**Pull request merged**
