### PR TITLE
Fix Slice Viewer spin box for peaks when outside of data range

### LINKED ISSUE #33952: Slicepoint spin box not updated when select peak outside data extent in sliceviewer
**Describe the bug**
When the user selects a peak in the peak viewer table in sliceviewer the colorfill plot updates to show the region of the peak - at the slicepoint corresponding to the peak position along the integrated dimension. However, if a peak with a position outside the extent of the data along the integrated dimension, the slicepoint in the view (the spin-boxes of the dimension widget) is not updated. Though the call to BinMD uses the correct slicepoint of the peak.

**To Reproduce**
(1) Make some data

```
ws_4D = CreateMDWorkspace(Dimensions=4, Extents=[-1, 1, -1, 1, -1, 1, -1, 1], Names="H,K,L,E",
                              Frames='HKL,HKL,HKL,General Frame', Units='r.l.u.,r.l.u.,r.l.u.,meV')
FakeMDEventData(ws_4D, UniformParams=1e6)
expt_info_4D = CreateSampleWorkspace()
ws_4D.addExperimentInfo(expt_info_4D)
SetUB(ws_4D, 1, 1, 2, 90, 90, 120)
CreatePeaksWorkspace(InstrumentWorkspace='ws_4D', NumberOfPeaks=0, OutputWorkspace='peaks')
CopySample(InputWorkspace='ws_4D', OutputWorkspace='peaks', CopyName=False, CopyMaterial=False, CopyEnvironment=False, CopyShape=False)
AddPeakHKL(Workspace='peaks', HKL='1,2,3')

```

(2) Open `ws_4D` in sliceviewer
(3) Overlay `peaks`
(4) Select the peak row in the table 
- the plot should go green (previously showed random fake data)
- the slicepoint in the spin box in the dimensions above the colorfill still reads -0.99
- the history of `ws_4D_svrebinned` shows that `BinMD` was called with extents [2.95,3.05] along L
- 
(5) In the peak actions above the table click `Add Peaks`
(6) Click on the colorfill plot 
- This should add a peak, the slicepoint will be the same as the peak row above (i.e. 3)

**Expected behavior**
The slicepoint in the spinbox in the view would read 3 (the slicepoint of the peak selected) - it looks like the spin box just isn't being updated.

**Screenshots**

**Platform/Version (please complete the following information):**
 - Seen in mantid 6.2 and mantid 6.3 nightly from 19th May

**Additional context**

### PR DESCRIPTION
**Pull request by jclarkeSTFC**
Overlaying a peak in Slice Viewer will now always result in the corresponding spin boxes at the top of the interface showing the value of that dimension that corresponds to the peak, even if the peak is outside the range of the data. Previously these boxed were clipped to the min/max of the data.

#### Summary of work

- Extended range of spin box to cover peak when necessary

Fixes #33952. 

### To test:
See #33952 for original issue. Other peak overlaying and dimension-changing behaviour in Slice Viewer should be unaffected.

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by RichardWaiteSTFC — CHANGES_REQUESTED** [review]
Nice fix, works well! Thanks for adding the integration test, is there a reason not to add a unit test in `mantidqt/mantidqt/widgets/sliceviewer/test/test_dimensions.py`?

**Comment by jclarkeSTFC** [comment]
> Nice fix, works well! Thanks for adding the integration test, is there a reason not to add a unit test in `mantidqt/mantidqt/widgets/sliceviewer/test/test_dimensions.py`?

Thanks, I've added a unit test in a new file, because it looked like `test_dimensions.py` is for the `Dimensions` class in the model, but not the dimension widget.

**Comment by RichardWaiteSTFC** [comment]
> > Nice fix, works well! Thanks for adding the integration test, is there a reason not to add a unit test in `mantidqt/mantidqt/widgets/sliceviewer/test/test_dimensions.py`?
> 
> Thanks, I've added a unit test in a new file, because it looked like `test_dimensions.py` is for the `Dimensions` class in the model, but not the dimension widget.

Good spot there's no unit test for that bit! Thanks for adding the file. Will approve when CI passes

**Review by RichardWaiteSTFC — APPROVED** [review]
Thanks!

**Pull request merged**
