### PR TITLE
Increase # of cols and rows above which surface plot sampling occurs

### LINKED ISSUE #34397: Surface\Wireframe plots not rendering ridges correctly
Matplotlib seems to be subsampling the data before plotting in some cases meaning that surface\wireframe plots don't always display ridges correctly. The ridge gets displayed instead as a set of spikes.

For example this workspace has 9 histograms and 79 bins and contains data that should have a ridge along energy transfer=0 but it's actually shown as 2-3 spikes:

```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np
import math

# parameterised Lorentzian S(Q,w)
# wavelength = 4 Angstroms, k=1.57
X,Y, SpecAxis =[],[],[]
qmin, qmax = 0.,4.0
nqpts = 9
wmin, wmax = -5.85, 5.85 # meV
nwpts = 79 # helpful if odd number so point at w=0
D = 0.15 # Angstom-2 meV -1 = 2.3E-05 cm2 s-1
TEMP=300
HOVERT = 11.6087/TEMP
for iq in range(nqpts):
   q = iq * (qmax-qmin)/(nqpts-1) + qmin
   SpecAxis.append(q)
   for iw in range(nwpts):
     w = iw * (wmax-wmin)/(nwpts-1) + wmin
     X.append(w)
     if (w*w + (D*q*q)**2==0.):
        # Discus S(Q,w) has zero here so do likewise
        print("Denominator zero so outputting S(q,w)=0")
        Y.append(0.)
     else:
        Sqw = D*q*q/(math.pi*(w*w + (D*q*q)**2))
        # Apply detailed balance, neutrons more likely to lose energy in each scatter
        # Mantid has w = Ei-Ef
        if (w > 0.):
           Sqw = Sqw * math.exp(HOVERT * w)
        # S(Q,w) is capped at exactly 4.0 for some reason in Discus example
        Y.append(min(Sqw,4.0))

sqw = CreateWorkspace(DataX=X,DataY=Y,UnitX="DeltaE",
                      VerticalAxisUnit="MomentumTransfer",
                      VerticalAxisValues=SpecAxis, NSpec=nqpts)
```

image

I've tracked this down to the rstride and cstride parameters that Matplotlib uses to subsample the data. When they're not explicitly supplied matplotlib calculates them as `int(max(np.ceil(rows/50),1)` and `int(max(np.ceil(rcols/50),1)`. On this example rstride=1 and cstride=2 which I think triggers some subsampling. If I reduce the number of w bins to 49 then rstride=cstride=1 and the function does get plotted correctly without any sampling:

image

Perhaps the subsampling is useful on very large workspaces but it feels like it should only kick in at larger bin numbers than the example here. The rstride and cstride parameters get set to 2 or more as soon as the number of bins or histograms goes above 50 at the moment.

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

Increase number of cols and rows above which sampling occurs. Had choice about whether to supply default for rstride\cstride or rcount\ccount. Went for rcount\ccount because leaves code path closest to previous code where rstride and cstride are calculated based on number of rows\cols in dataset

Can't just remove sampling in all cases because performance of rotating a surface plot is poor above ~100x100 rows

**To test:**

Run script on linked issue and observe that peak in plot isn't distorted any more
Increase number of rows and columns by factor of 10 and observe that surface plot can still be rotated without major slowness

Fixes #34397.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by SpencerHowells** [comment]
@DannyHindson And I care as well!

**Comment by jhaigh0** [comment]
> Increase number of rows and columns by factor of 10 and observe that surface plot can still be rotated without major slowness

@DannyHindson Could you show me where to change this in the script / interface? Not something I'm too familiar with yet.

**Comment by DannyHindson** [comment]
Yes sure. Wasn't very obvious now I look at it again.

There are two variables called `nqpts` and `nwpts` and you just need to make these 10x bigger ie `nqpts = 90`, `nwpts=790`. I seem to have commented that nwpts needs to be an odd number so perhaps `nqpts = 90`, `nwpts=789`

**Review by jhaigh0 — APPROVED** [review]
Happy that testing instructions produce the expected results 👍

**Pull request merged**
