### PR TITLE
Will Ross approve?

### PR DESCRIPTION
**Pull request by peterfpeterson**
**Report to:** @rosswhitfield 

**To test:**

All the builds should pass.

*There is no associated issue.*

*This does not require release notes* because ...

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by rosswhitfield — APPROVED** [review]
∅

**Comment by peterfpeterson** [comment]
There is literally nothing to see here.

**Comment by martyngigg** [comment]
Then I have nothing to approve!

**Comment by SimonHeybrock** [comment]
I think this PR is too large and should be split into multiple parts. I am closing this, please resubmit each change as a separate PR.

**Pull request closed without merging**
