### PR TITLE
Added DPDFreduction algorithm.

### LINKED ISSUE #13438: Add Dynamic PDF reduction algorithm
Add the DPDF reduction algorithm that has been developed into Mantid.

### PR DESCRIPTION
**Pull request by stuartcampbell**
I have run @jmborr test cases and they all seem ok.  One problem with adding tests to the repository at the moment is that all the data we have for testing is unpublished so cannot be put into our repo.

I will create a new issue for @jmborr to create the documentation! :smile: 

fixes #13438

### CODE REVIEW

**Comment by peterfpeterson** [comment]
You need to add this to the release notes. If it is a "preview version," mention it.

**Comment by AndreiSavici** [comment]
Note that grouping and then converting to MD will get rid of the correct statistical weight

**Comment by peterfpeterson** [comment]
@AndreiSavici Please create a ticket on the next release with your requests and assign it to @jmborr.

**Comment by peterfpeterson** [comment]
I created #13760 for the first pass of making this pretty.

**Pull request merged**
