### PR TITLE
GSASIIRefineFitPeaks XMin and XMax parameters added

### LINKED ISSUE #21600: GSASIIRefineFitPeaks should have limit parameters
As in the [old version](http://docs.mantidproject.org/v3.7.2/algorithms/GSASIIRefineFitPeaks-v1.html), `GSASIIRefineFitPeaks` should support `XMin` and `XMax` parameters to only perform refinement within a given range

### PR DESCRIPTION
**Pull request by josephframsay**
Parameters for specifying a range of x values in which to do refinement were added to `GSASIIRefineFitPeaks`.

**To test:**

**Make sure the GSASIIRefineFitPeaks system test passes locally - this is not currently run on the build server**

You'll need GSAS-II installed. Either install it using one of the scripts in `scripts/GSAS-II` or follow the instructions [here](https://subversion.xray.aps.anl.gov/trac/pyGSAS).

Sample data is at `\\olympic\Babylon5\Public\JoeRamsay\GSASIIRefineFitPeaks`.

Run the following script:
```
import os
path_to_gsas = "/path/to/directory/containing/GSASIIscriptable.py"

data_dir = r"\\olympic\Babylon5\Public\JoeRamsay\GSASIIRefineFitPeaks"
# or wherever you've put it

ws_path = os.path.join(data_dir, "focused_bank1_ENGINX00256663.nxs")
spectrum = Load(Filename=ws_path)

gsas_proj_file = "/somewhere/local/Test.gpx"
phase_file = os.path.join(data_dir, "FE_ALPHA.cif")
iparams_file = os.path.join(data_dir, "template_ENGINX_241391_236516_North_bank.prm"

GSASIIRefineFitPeaks(PathToGSASII=path_to_gsas, 
                     InputWorkspace=spectrum,
                     SaveGSASIIProjectFile=gsas_proj_file,
                     PhaseInfoFile=phase_file,
                     InstrumentFile=iparams_file,
                     RefinementMethod="Pawley refinement",
                     XMin=10000, XMax=40000),
```

Open up `Test.gpx` in GSAS-II and have a look at it - make sure that `TMin` and `TMax` are set correctly in the `Limits` tab, and that fitted data is only visible between 10000 and 40000 us. Try varying `XMin` and `XMax` to see if anything unexpected happens.

Fixes #21600 

**Release Notes** 
This was a feature of the old version of the algorithm, so doesn't need to be in the release notes

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by ElliotAOram — CHANGES_REQUESTED** [review]
If you set XMin > XMax you get the following:
```
RuntimeError: index -1 is out of bounds for axis 0 with size 0
  at line 118 in
```
followed by a huge stack trace. Could we add some validation to check for this. (or to switch XMin/XMax if they are the wrong way round)

**Review by ElliotAOram — COMMENTED** [review]
The tests passed, but I got several `RuntimeWarnings`:
```
C:\Users\hvq65228\AppData\Roaming\Python\Python27\site-packages\g2conda\GSASII\GSASIIstrMath.py:4269: RuntimeWarning: invalid value encountered in double_scalars
  Histogram['Residuals']['Rb'] = min(100.,100.*sumYB/sumYmB)
C:\Users\hvq65228\AppData\Roaming\Python\Python27\site-packages\g2conda\GSASII\GSASIIstrMath.py:4270: RuntimeWarning: invalid value encountered in double_scalars
  Histogram['Residuals']['wRb'] = min(100.,100.*ma.sqrt(sumwYB2/sumwYmB2))
C:\Users\hvq65228\Documents\git\mantid\external\src\ThirdParty\lib\python2.7\lib\site-packages\numpy\ma\core.py:814: RuntimeWarning: invalid value encountered in less
  return umath.less(x, self.critical_value)
```
Is this expected/issue with GSAS?

**Comment by josephframsay** [comment]
@ElliotAOram The runtime warnings are to be expected - they seem to crop up all over the place in GSASIIscriptable

**Review by ElliotAOram — APPROVED** [review]
Warning now displayed in the Result log if XMin > XMax. Good to merge now!

**Pull request merged**
