### PR TITLE
EISFDiffSphere function

### LINKED ISSUE #21361: EISFDiffSphere function
A fit function modeling the elastic incoherent intensity for a particle undergoing continuous diffusion but confined to a spherical volume.

```
EISF(Q,R) = (j_1(QR)/QR)^2
```

Fit parameter `R` and domain `Q`

### PR DESCRIPTION
**Pull request by jmborr**
- Fit function class
- documentation
- release notes

Please review the code and run the doctest in your machine.

Fixes #21361

[Release Notes](https://github.com/mantidproject/mantid/blob/717fbf6729bc6b95d0320f7a18e0cf50eb344bd0/docs/source/release/v3.12.0/framework.rst#fitting)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [x] Are the unit tests small and test the class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DanNixon — CHANGES_REQUESTED** [review]
All looks good, however there should ideally be a unit test to go with the new function.

**Comment by DanNixon** [comment]
The test needs to be added to the appropriate `CMakeLists.txt` to be picked up by ctest

**Comment by jmborr** [comment]
@DanNixon Ouch, I didn't know this one :blush:

**Review by DanNixon — APPROVED** [review]

**Comment by DanNixon** [comment]
Looks good now, once the failing build is addressed (that does look unrelated though).

**Comment by martyngigg** [comment]
@jmborr I think the failing test is real under Python 3. Could you look into it?

**Comment by jmborr** [comment]
@DanNixon @quantumsteve  :notes: thanks :notes:

**Pull request merged**
