### PR TITLE
Engineering Diffraction GUI now supports fitting multiple runs

### LINKED ISSUE #21247: Engineering Diffraction GUI should support fitting multiple runs
The ED GUI should support multi-run fitting, in which the user clicks **Fit all**, and the Engg fitting algorithms are applied to every loaded run.

Currently this feature is not supported. Several PRs have come before this whose purpose was to enable this feature, but they all got bogged down in the extensive refactoring jobs which needed doing to the GUI.

Maybe this ticket will finally be the one...

### PR DESCRIPTION
**Pull request by josephframsay**
Multi-run fitting from the ED GUI was wired up properly, and a large amount of refactoring was done, including the removal of a **lot** of dead code from the view and the presenter (this was mainly code related to making sure files exist, which is now taken care of in the model). Users should now be able to load several workspaces and apply Engg fitting algorithms to them all in one go.

**To test:**

Some sample data is [here](https://github.com/mantidproject/mantid/files/1460806/ENGINX_focused_runs.zip).

Load a few of the other runs by clicking the first **Browse** button, selecting the focused runs you want and then hitting **Load**.

Press **Fit all**. A table workspaces with fit parameters for all runs should appear in the workspaces area, and a matrix workspaces with all the fitted peaks should also appear.

Check that fitting information was saved (as `.csv`). On Windows this will be in `C:\EnginX_Mantid\User`, on Linux `~/EnginX_Mantid/User`.

When you select a different run from the list widget, the fit results should be plotted over it - make sure this works nicely.

Fixes #21247 

**Release Notes** 
[Here](https://github.com/mantidproject/mantid/commit/c2b9dffae50f214d0fbb912517e3cbd5f5138c3d)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by ElliotAOram — CHANGES_REQUESTED** [review]
After running the fit all I get workspaces with no name in the ADS. I'm guessing these were the original data workspaces?
image

**Comment by ElliotAOram** [comment]
Should it be possible to clear the fitting information and revert to the mini plot without any of the fitting on it?

**Comment by ElliotAOram** [comment]
When I load in multiple runs, is there a way to remove them from the list, or clear the list entirely?

**Comment by josephframsay** [comment]
WRT removing workspaces from the list (and I guess the model), there's not a way to do that at the moment, but there should be. I think that might be a case for another PR though - we now can at least do multi-run fitting. I'll put it on the list

**Review by ElliotAOram — APPROVED** [review]
The changes look good now 👍

**Pull request merged**
