### PR TITLE
16291 eqsans gui bug

### LINKED ISSUE #16291: EQSANS GUI BUG
After adding BIOSANS / GPSANS new distances, the XML is not well exported.

1. When Loading 
`Detector distance offset``` loads a property, not a value: `<property object at 0x7fc3b27a91b0>`

2. When reducing the data, I have the error
```
Reduction could not be executed:

Traceback (most recent call last):
  File "/home/rhf/git/mantid/scripts/Interface/reduction_gui/instruments/interface.py", line 207, in reduce
    self.scripter.apply()
  File "/home/rhf/git/mantid/scripts/Interface/reduction_gui/reduction/scripter.py", line 494, in apply
    raise RuntimeError, sys.exc_value
RuntimeError: cannot import name PropertyManagerDataService
```
3. SaveCanSAS1D incorrectly saves SASprocess as SASProcess (typo).

4. The SANS reduction info in the cansas xml file should be in
```
<SASprocess><SASprocessnote> ... </SASprocessnote></SASprocess>
```

Point 2 can be solved by correcting: `from mantid import PropertyManagerDataService`

Test opening the file in the EQSANS GUI (Debug Mode On): `/SNS/EQSANS/IPTS-15454/shared/67315_Iq.xml`.

### PR DESCRIPTION
**Pull request by ricleal**
Bug Fix. Minimal changes to correct a bad import and field in the GUI rendered as property not number.

No release Notes needed or documentation.

**To test:**

Fixes #16291.

1- Test opening the file in the EQSANS GUI (Debug Mode On): /SNS/EQSANS/IPTS-15454/shared/67315_Iq.xml.

The Detector off set should show 0.
Reduce shouldn't throw any errors.

2- Re-reduce that file, and check that you can reload the new xml file.

3- Check that it also works with the HFIR UI.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [ ] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AndreiSavici** [comment]
That's an ugly way to "fix" pylint. You should fix the warnings. If that is too hard, disable it locally, and use the full explanation why it was disabled, not just the code. That is especially important if you use the old-style `raise`, since we'll have problems when transitioning to newer Python

**Comment by mdoucet** [comment]
@AndreiSavici Only pylint warnings that don't make sense were skipped. The raise wasn't fixed in all files but were not skipped. Code style warnings from code that wasn't touched shouldn't fail the build.

**Comment by LamarMoore** [comment]
Is someone testing this?

**Comment by ricleal** [comment]
@LamarMoore I am. Need 30 mins more.

**Comment by ricleal** [comment]
@mdoucet : 
There's an error in GUI 
```
Traceback (most recent call last):
  File "/home/rhf/git/mantid/scripts/Interface/reduction_gui/instruments/interface.py", line 207, in reduce
    self.scripter.apply()
  File "/home/rhf/git/mantid/scripts/Interface/reduction_gui/reduction/scripter.py", line 494, in apply
    raise RuntimeError, sys.exc_value
RuntimeError: "'__reduction_parameters_Wlp49' does not exist."
```

Open `/SNS/EQSANS/IPTS-15454/shared/67315_Iq.xml` and click Reduce.

**Comment by ricleal** [comment]
Mantid Log:
```
Script execution started.

Unable to find instrumentName in the properties file
getFullPath(/SNS/EQSANS/shared/NeXusFiles/EQSANS/2016A_mp/EQSANS_61380_event.nxs)
getFullPath(/SNS/EQSANS/IPTS-15454/0/67137/NeXus/EQSANS_67137_event.nxs)
getFullPath(/SNS/EQSANS/shared/NeXusFiles/EQSANS/2016A_mp/Sensitivity_patched_thinPMMA_4m_61379_event.nxs)
getFullPath(/SNS/EQSANS/IPTS-15454/0/67201/NeXus/EQSANS_67201_event.nxs)
getFullPath(/SNS/EQSANS/IPTS-15454/0/67137/NeXus/EQSANS_67137_event.nxs)
getFullPath(67314)
findRuns hint = EQSANS67314
vector findRun('EQSANS67314', exts[0])
Looking for EQSANS at HFIR.
Instrument EQSANS not found in facility HFIR
Looking for EQSANS at ISIS.
Instrument EQSANS not found in facility ISIS
Looking for EQSANS at HFIR.
Instrument EQSANS not found in facility HFIR
Looking for EQSANS at SNS.
Instrument 'EQSANS' found as EQ-SANS at SNS.
Add facility extensions defined in the Facility.xml file
getExtension(EQSANS67314, exts[6])
Failed to find extension. Just using last '.'
Looking for EQSANS at HFIR.
Instrument EQSANS not found in facility HFIR
Looking for EQSANS at ISIS.
Instrument EQSANS not found in facility ISIS
Looking for EQSANS at HFIR.
Instrument EQSANS not found in facility HFIR
Looking for EQSANS at SNS.
Instrument 'EQSANS' found as EQ-SANS at SNS.
getFullPath(EQSANS_67314.nxs.h5)
getFullPath(EQSANS_67314_event.nxs)
getFullPath(EQSANS_67314.nxs)
getFullPath(EQSANS_67314.dat)
getFullPath(EQSANS_67314_runinfo.xml)
getFullPath(EQSANS_67314_histo.nxs)
Unable to find run with hint EQSANS67314
Unable to find file path for EQSANS67314
findRuns hint = 67314
vector findRun('67314', exts[0])
Looking for  at HFIR.
Blank instrument specified, using default instrument of BIOSANS.
Instrument 'BIOSANS' found as BIOSANS at HFIR.
Add facility extensions defined in the Facility.xml file
getExtension(67314, exts[3])
Failed to find extension. Just using last '.'
Looking for  at HFIR.
Blank instrument specified, using default instrument of BIOSANS.
Instrument 'BIOSANS' found as BIOSANS at HFIR.
Looking for BIOSANS at HFIR.
Instrument 'BIOSANS' found as BIOSANS at HFIR.
getFullPath(BIOSANS67314.nxs)
getFullPath(BIOSANS67314.dat)
getFullPath(BIOSANS67314.xml)
Unable to find run with hint 67314
Unable to find file path for 67314


Could not find a file for 67314: check your reduction parameters


RuntimeError: Could not find a file for 67314
  at line 32 in '<Interface>'
  caused by line 201 in '/home/rhf/git/mantid/scripts/reduction_workflow/instruments/sans/hfir_command_interface.py'
  caused by line 108 in '/home/rhf/git/mantid/scripts/reduction_workflow/find_data.py'

```

GUI:
```
Reduction could not be executed:

Traceback (most recent call last):
  File "/home/rhf/git/mantid/scripts/Interface/reduction_gui/instruments/interface.py", line 207, in reduce
    self.scripter.apply()
  File "/home/rhf/git/mantid/scripts/Interface/reduction_gui/reduction/scripter.py", line 532, in apply
    raise RuntimeError(str(sys.exc_value))
RuntimeError: "'__reduction_parameters_3KCuv' does not exist."
```

**Comment by ricleal** [comment]
I tested the GUI for both EQSANS and HFIR SANS.
I did not have problems reducing data. It looks good then!
:shipit:

**Comment by martyngigg** [comment]
I've also merged this to `release-v.7`.

**Pull request merged**
