### PR TITLE
Fix for issue 33508 gridlines turn on unexpectedly

### LINKED ISSUE #33508: Grid lines turn on unexpectedly on 3D plots when changing axis format.
**Describe the bug**
When changing the axis tick format in a 3D plot with gridlines switched off, the gridlines will turn back on again.

**To Reproduce**
1. Load a workspace and plot a 3D surface plot
2. Turn off gridlines using the toolbar button
3. Double click an axis value to bring up the "Edit axis" dialog
4. Change the tick format to Scientific Format and click OK.
Grid lines will turn back on (and the toolbar button will have an incorrect state).

**Expected behavior**
Grid lines should stay off.

**Platform/Version (please complete the following information):**
 - OS: All
 - Mantid Version: 6.1 onwards confirmed

### PR DESCRIPTION
**Pull request by DonaldChung-HK**
**Description of work.**
Fixes #33508.  Gridline turn on after updating axis scale. This inconsistency is caused by the `change_accepted` function in `AxisEditor`.

**Report to:** thomashampson

**To test:**
Test if gridline remain off
1. Load a workspace and plot a 3D surface plot
2. Turn off gridlines using the toolbar button
3. Double click an axis value to bring up the "Edit axis" dialog
4. Change the tick format to Scientific Format and click OK.
5. Grid lines will remain invisible.

Test if gridline will turn on
1. Load a workspace and plot a 3D surface plot
2. Turn on gridlines using the toolbar button
3. Double click an axis value to bring up the "Edit axis" dialog
4. Change the tick format to Scientific Format and click OK.
5. Grid lines will be visible.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by jhaigh0 — CHANGES_REQUESTED** [review]
Works as intended and code is nice and simple.

Could add a release note to Workbench/Bugfixes

**Review by jhaigh0 — DISMISSED** [review]

**Review by thomashampson — CHANGES_REQUESTED** [review]
Can the release note be more specific about it being related to 3D plots?

**Review by thomashampson — APPROVED** [review]
Thanks for updating the release notes.

**Comment by thomashampson** [comment]
Changes since all checks passed are only to the release notes file.

**Pull request merged**
