### PR TITLE
Set default number density units as formula units/Ang^3 in single crystal reduction classes

### PR DESCRIPTION
**Pull request by RichardWaiteSTFC**
**Description of work**

Set default number density units as formula units/Ang^3 as opposed to the default in `SetMaterial` and `SetSample` which is atoms/Ang^3 (which is quite an unusual choice of unit for example when chemical formula has multiple atom species).

I found out the default unit was atoms/Ang^3 when writing the test documentation for the Sample Transmission Calculator #36188

**To test:**

(1) Run this script
```
from Diffraction.single_crystal.sxd import SXD

sxd = SXD(vanadium_runno=32857, empty_runno=32856)
                   
sxd.set_sample(Geometry={'Shape': 'CSG', 'Value': sxd.sphere_shape}, 
               Material={'ChemicalFormula': 'C2 H4', 'SampleNumberDensity': 0.02})
sxd.process_vanadium()
sxd.process_data([32863]) # 0 gonio rotation

print(mtd["SXD32863"].sample().getMaterial().numberDensity)
```

it should print out `0.12` (i.e. the original number density multiplied by the number of atoms in a unit cell i.e. 6)

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by jhaigh0 — COMMENTED** [review]
Looks good and tests works, do any algorithm / user docs need to change?

**Comment by RichardWaiteSTFC** [comment]
> Looks good and tests works, do any algorithm / user docs need to change?

Thanks for having a look - no docs exist as this is a work in progress (I'm currently writing some!)

**Comment by jhaigh0** [comment]
> > Looks good and tests works, do any algorithm / user docs need to change?
> 
> Thanks for having a look - no docs exist as this is a work in progress (I'm currently writing some!)

oh whoops, I thought it was read for review. Feel free to request a re-review when it's ready (:

**Comment by RichardWaiteSTFC** [comment]
> > > Looks good and tests works, do any algorithm / user docs need to change?
> > 
> > 
> > Thanks for having a look - no docs exist as this is a work in progress (I'm currently writing some!)
> 
> oh whoops, I thought it was ready for review. Feel free to request a re-review when it's ready (:

This is ready for review, the docs will come in a separate PR - sorry for the confusion!

**Review by jhaigh0 — APPROVED** [review]

**Pull request merged**
