### PR TITLE
IndirectDataReduction - Moments - bugfixes

### LINKED ISSUE #17573: Indirect Data Reduction - Moments
_Found during unscripted testing of indirect interfaces on 3.7.20160919.1516 (using Windows 7)_

In the Indirect < Data Reduction < Moments tab:

- When the data is input to the interface, the bars on the preview plot don't match up with Emin and Emax
- The lines on the result plot are incorrectly labelled 
- When the plot button is clicked, the M0 & M2 graphs are plotted, should be M2 & M4

### PR DESCRIPTION
**Pull request by louisemccann**
- Fixed preview plot bars being at wrong position when data is initially loaded
- Labels on the results graph now match the lines plotted
- Pressing "plot" when the algorithm is complete plots M0, then M2 & M4 on a seperate graph

**To test:**
Interfaces > Indirect > Data Reduction > Moments
//olympic/babylon5/Public/Louise McCann/DataReduction/Moments/ws_sqw.nxs
Scale factor: 0.0001
Check that results graph labels match lines by right-clicking group workspace "ws_Moments" -> "Plot Spectrum" and comparing plots.
Fixes #17573 .

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
Looks good.

When plotting from the interface I get two plots, one is `M0` and the other contains both `M2` and `M4` in the same plot. Graphs, including labels, look the same.

:shipit:

**Comment by SimonHeybrock** [comment]
Just to be sure (since it says bugfix): This was not supposed to be in 3.8?

**Comment by louisemccann** [comment]
@SimonHeybrock It was, I must have marked it incorrectly. Is it still possible to put it in?

**Comment by raquelalvarezbanos** [comment]
@louisemccann I think it should be possible as beta testing ends today.

**Comment by SimonHeybrock** [comment]
@louisemccann Should be. I changed the base branch, but the builds did not restart automatically.

**Comment by SimonHeybrock** [comment]
(Ross restarted the builds, will merge once green)

**Pull request merged**
