### PR TITLE
Add common workbench launcher executable to harmonise startup code.

### LINKED ISSUE #28861: Set Application bundle name on Mac
The app appears as Python, now Workbench on the mac
image

So this is a special mac feature,  it looks like there may be a way to change the bundle name, but it needs another python dependency.
https://stackoverflow.com/questions/5047734/in-osx-change-application-name-from-python

### LINKED ISSUE #28871: Windows: Command line arguments not passed through packaged workbench launch script
# Expected behavior

On Windows running `C:\MantidInstall\bin\launch_workbench.exe --profile %USERPROFILE%\workbench-profile.cprof` should produce a cProfile script.

### Actual behavior

No profile is created.

### Steps to reproduce the behavior

Run the above command.

### Platforms affected

Windows.

### LINKED ISSUE #29080: McAfee flags launch_workbench.exe in nightly as a threat and quarantines it
**Original reporter:** Spencer/ISIS

### Expected behavior
Antivirus software should not flag anything as a threat.

### Actual behavior
McAfee sees `C:\MantidNightlyInstall\bin\launch_workbench.exe` as a threat and quarantines it.

### Steps to reproduce the behavior
Install nightly windows build on machine with McAfee installed and try to start workbench.

### Platforms affected
Windows

### PR DESCRIPTION
**Pull request by martyngigg**
:warning: Requires testing on all operating systems :warning: 

**Description of work.**

Introduces a common workbench launcher for macOS/Windows written in C++. The original driver was to move away from the executable generated by [PS1-To-Exe](https://gallery.technet.microsoft.com/PS1-To-EXE-Generator-d39e8be2) as

* it can get trapped by some virus scanners, e.g. McAfee 
* it requires the .NET framework and this does not really make sense as a dependency for us

It was discovered that the startup launcher for macOS/Windows were nearly identical so this introduces this executable for macOS too. Harmonizing them should reduce the maintenance burden of having to remember to update multiple locations. Linux has not yet been included as it's launcher is more complicated.

As part of this work the errorreport GUI code has been moved to the `mantidqt` package so that it could be more easily accessible without additional `sys.path` updates within the launcher.

**To test:**

Requires testing on all OSes to confirm nothing is broken.

For both development build and a package:

* Build and test workbench starts as it used to do for that environment. Also start the new `MantidWorkbench` executable in the `bin` directory and check this works.
* Check the error reporter starts on a crash using the `Segfault` algorithm. You'll need to check the `usagereports.enabled=1` setting in the properties file.
* Also check the error reporter pops up for an unhandled exception. 

**Additionally for Visual Studio only.**

The Visual studio build should now run without need for the `visual-studio.bat` file. Run cmake on this branch and then open the solution by opening `Mantid.sln` and **not** `visual-studio.bat`. Build and run workbench.

Fixes #28871 
Fixes #28861
Fixes #29080
Refs #28263

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DanielMurphy22** [comment]
On MacOS: 
- `bin/MantidWorkbench` + Segfault gives the error reporter, but `bin/workbench` + Segfault gives no error reporter [double checked I've got usage reporting enabled].
- Unhandled exceptions in both give an error reporter, but both with No Sad Mantid
Screenshot 2020-08-03 at 12 05 56
- For the package: Segfaults give the error reporter and unhandled exceptions give the error reporter without the Sad Mantid like above. The Application is nicely renamed to `MantidWorkbench` for the package! 😃

**Comment by martyngigg** [comment]
> On MacOS:
> 
>     * `bin/MantidWorkbench` + Segfault gives the error reporter, but `bin/workbench` + Segfault gives no error reporter [double checked I've got usage reporting enabled].

This is what I would expect. `bin/workbench` is the bare executable.

> 
>     * Unhandled exceptions in both give an error reporter, but both with No Sad Mantid
>       Screenshot 2020-08-03 at 12 05 56

Thanks for spotting this. I thought it showed for me but I will double check and find out where it has gone.

> 
>     * For the package: Segfaults give the error reporter and unhandled exceptions give the error reporter without the Sad Mantid like above. The Application is nicely renamed to `MantidWorkbench` for the package! smiley

**Comment by martyngigg** [comment]
Thanks for pointing out the issues here. I think I have fixed all of those problems now. I also fixed an issue with the error reporter from MantidPlot.

**Review by DanielMurphy22 — COMMENTED** [review]
I'm happy with these latest fixes on Mac now. I can always see the Sad mantid. Good job!

**Comment by martyngigg** [comment]
@DanielMurphy22 I'm just assigning you so that it's then not in the list of things to review.

**Review by DannyHindson — COMMENTED** [review]
I've tested this on Windows on Debug, Release builds plus I also built an installer and ran it from there. The various tests worked in all cases (could start up Workbench, error reporter on SegFault, error reporter on unhandled exception). I think it's all fine but just a few minor comments\questions:

- in order to get the error reporter screen to appear after running SegFault I had to run the mantidworkbench.exe from a cmd prompt created via command-prompt.bat. I guess this is perhaps expected because it needs paths. If I just ran mantidworkbench.exe from a windows explorer window it started up fine but on crashing it gave me an error about not finding qwindows.dll
- When Mantid crashes after running SegFault I get a "Python Stopped Working" screen with Debug\Close options and I have to click Close before getting the error reporter. Seems like it was like this on a recent nightly build also
- I wasn't sure what to do for the part of the test where you say "test workbench starts as it used to do". On Windows, the start menu item used to run launch_workbench.exe but that has been deleted I think? ~~When running workbench from PyCharm I used to run launch_workbench.pyw but that has also been deleted~~ I was looking at the wrong pyw file. I can start workbench up in PyCharm using workbench-script.pyw as before
- when I ran workbench from the installer for the first time I got an error about "is" and "==" but this went away when I ran workbench 2nd/3rd time etc:
image

**Comment by martyngigg** [comment]
Thanks for testing this.

> I've tested this on Windows on Debug, Release builds plus I also built an installer and ran it from there. The various tests worked in all cases (could start up Workbench, error reporter on SegFault, error reporter on unhandled exception). I think it's all fine but just a few minor comments\questions:
> 
>     * in order to get the error reporter screen to appear after running SegFault I had to run the mantidworkbench.exe from a cmd prompt created via command-prompt.bat. I guess this is perhaps expected because it needs paths. If I just ran mantidworkbench.exe from a windows explorer window it started up fine but on crashing it gave me an error about not finding qwindows.dll

You are correct that this is a `PATH` issue. I think I can do better here as the build knows where the libraries are so I should be able hardcode the `PATH` for the developer executable. 

>     * When Mantid crashes after running SegFault I get a "Python Stopped Working" screen with Debug\Close options and I have to click Close before getting the error reporter. Seems like it was like this on a recent nightly build also

I'm not sure we can avoid this. Its' the same on Mac where you get the Apple report dialog too. If it's too irritating then we can investigate disabling. I'm not sure it pops up on a machine without Visual Studio on it so it could just be a developer issue.

> 
>     * I wasn't sure what to do for the part of the test where you say "test workbench starts as it used to do". On Windows, the start menu item used to run launch_workbench.exe but that has been deleted I think? ~When running workbench from PyCharm I used to run launch_workbench.pyw but that has also been deleted~ I was looking at the wrong pyw file. I can start workbench up in PyCharm using workbench-script.pyw as before

Sorry for not being clearer here. I did just mean check that PyCharm configs still work as they did with the `workbench-script.pyw` script for developers and that the desktop shortcuts work for users. :+1: 

>     * when I ran workbench from the installer for the first time I got an error about "is" and "==" but this went away when I ran workbench 2nd/3rd time etc:
>       image

This is a known issue with a dependency. Python 3.8 deprecated using `is` in cases like `x is 3` where developers should write `x == 3`. It only complains once as it then "compiles" to code to `.pyc` and doesn't show the warning again.

**Comment by DavidFair** [comment]
Tested on Windows, we can build and launch `MantidWorkbench` from the .sln correctly:

Some questions from review / testing
- We don't need `visual_studio.bat` anymore but we are still generating it, is it worth removing it as part of this PR to get people used to using the .sln file instead (plus we can post in announce)
- I notice we now have `MantidWorkbench`, `MantidWorkbenchInstalled`, `workbench` and `workbench_resources` on Windows. I'm trying to think of a way to consolidate this somehow - renaming `workbench` means you can't do `ninja workbench` on Linux anymore, and we cannot add the executable target to workbench.
Alternatively, we could move `workbench` and `workbench_resources` into a folder with `check`, `CompileUiBatchWidgetInterface`, `mantidqt[_resources]` and `ScriptsDotPth` since this won't mess up the targets for command line builders, but will declutter for VS IDE users?

**Comment by tolu28-coder** [comment]
The test worked for me on windows.

**Comment by martyngigg** [comment]
> Tested on Windows, we can build and launch `MantidWorkbench` from the .sln correctly:
> 
> Some questions from review / testing
> 
>     * We don't need `visual_studio.bat` anymore but we are still generating it, is it worth removing it as part of this PR to get people used to using the .sln file instead (plus we can post in announce)

I thought about this and noted in the commit message that I left it just in case something wasn't working properly and it was an easy fallback. If you think we're okay then I'm happy to remove it?

> 
>     * I notice we now have `MantidWorkbench`, `MantidWorkbenchInstalled`, `workbench` and `workbench_resources` on Windows. I'm trying to think of a way to consolidate this somehow - renaming `workbench` means you can't do `ninja workbench` on Linux anymore, and we cannot add the executable target to workbench.
> 
> 
> Alternatively, we could move `workbench` and `workbench_resources` into a folder with `check`, `CompileUiBatchWidgetInterface`, `mantidqt[_resources]` and `ScriptsDotPth` since this won't mess up the targets for command line builders, but will declutter for VS IDE users?

Yeah I like this idea. It's helpful having `MantidWorkbench` & `workbench` together as for debugging most of the time you just want workbench without the outer wrapper that spawns a subprocess. We could consider following the source tree folder structure although it gets messy with the Qt4 stuff at the moment. Could we revisit this once we've dropped MantidPlot? We can then have think without having to worry about a load of things we will delete soon.

**Comment by DavidFair** [comment]
> I thought about this and noted in the commit message that I left it just in case something wasn't working properly and it was an easy fallback. If you think we're okay then I'm happy to remove it?

Let's try dropping it as a standalone commit and we can back it out if anyone shouts, otherwise I suspect most people will use the .bat out of habit
@tolu28-coder showed that the unit tests work from the .sln so I'm a lot more comfortable now to go ahead

> Could we revisit this once we've dropped MantidPlot?

Agreed, I suspect there will be a large cleanup

I want to double check that shortcuts work correctly with the installer, then I'm happy to give this the go ahead for testing / code review

**Comment by DavidFair** [comment]
@martyngigg Having some problems on Linux:
- Build package
- Cpack / install with gdebi
- Launch using icon / `/opt/mantidunstable/bin/mantidworkbench`
Gives the following stderr message:
/usr/bin/python3.6: can't open file '/opt/mantidunstable/bin/workbench-script': [Errno 2] No such file or directory

And the Mantid error reporter appears. Can you reproduce anything similar?

**Comment by martyngigg** [comment]
Thanks @DavidFair. I'll take a look.

**Comment by martyngigg** [comment]
Good catch on the Linux packaging. I backed some changes out of Linux in the end but must have missed this. I've rebased the fix in but you can see the changes that happened between the old HEAD and new HEAD [here](https://github.com/mantidproject/mantid/compare/c842e41f37ee206ffabd7b831094ccb56996cf78..947715730e5828bbd3965157c960db4ef930dd30)

**Comment by martyngigg** [comment]
Rebase again to fix release notes conflict :facepalm:

**Review by DavidFair — APPROVED** [review]
Retest with both Linux and Windows, that fixes the issues we were seeing on Linux too thanks

I've done a code review on this and I'm happy, unless there's any platforms we've missed testing that I can't see lets :shipit:

**Comment by martyngigg** [comment]
@mantidproject/gatekeepers Could I get this merged today as I'm away for week from today?

**Pull request merged**
