### PR TITLE
Set Workbench's DPI awareness to 1 on Windows

### LINKED ISSUE #23922: Workbench Font scaling issues when remoting from PC on 4k to PC on 1080p
### Expected behavior
Fonts should be scaled correctly.

### Actual behavior
Picture of the issue:
image

As can be seen, some fonts are scaled, some (text on buttons) are not. This does not seem to be Workbench specific issue, as it also happens on CMake (also Qt based GUI).

Hopefuly there is a Qt configuration to select or manually set the font scaling.

### Steps to reproduce the behavior
Current crude way of reproducing:
- Log into a PC with 4k resolution
- Remote into another PC with 1080p
- Launch the workbench

### Platforms affected
Only Windows has been tested.

### LINKED ISSUE #24520: Script rendering in Workbench
**Original reporter:** [Lamar Moore ISIS]. 
### Actual behavior
Scripts loaded into the workbench end up with strange rendering of the text. Does not seem to happen for the script template (new scripts created in Mantid).

### Steps to reproduce the behavior
**File->Open Script** open any script.

### Platforms affected
Tested on Windows 10 with a 4K monitor.

### PR DESCRIPTION
**Pull request by ghost**
**Description of work.**
This PR sets Workbench's DPI awareness to 1 on Windows.

This means Windows will calculate a scaling suitable for all connected monitors, rather than calculating it per monitor. This solves problems with text scaling in Workbench when using different resolution monitors or remoting into another PC.

Having the DPI awareness set to 1 sets the resoulution of the Workbench to a constant and essentially zooms in and out when the window is moved to a monitor with a different resolution. This can cause some blurriness in the text. 

Ideally we would like to set the DPI awareness to 2 and have the resolution set on a per-monitor basis. Qt does much of the rescaling for us in this case but Scintilla doesn't respond well to changes in resolution. A solution could be to find a way to "refresh" the Scintilla editor if a rescaling event occurs, since opening a new script or running a script seems to fix the scaling problems. However I haven't found an easy way to do this. I'll raise a further issue to find a solution usinig per-monitor DPI awareness, but for the coming release the current solution should be fine.

**To test:**
- You should do the below with a package and developer build on Windows.
    - Open workbench on a computer with two monitors with different resolutions. Move the workbench window between the monitors and check the scaling is sensible.
    - Open workbench in one computer. On a different computer with a different resolution remote into the first computer. Check the workbench scales sensibly.
    - Check the scaling behaves itself under normal use, e.g. plotting
    - Check the Help Window opens

Fixes #23922. 

*Edit:*
Fixes #24520

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@hsautessella Do you think this also fixes #24520?

**Comment by hsautessella** [comment]
@martyngigg Yep, it should fix that too.

**Comment by martyngigg** [comment]
Great. Could you add another `Fixes #` line for that one?

**Review by martyngigg — APPROVED** [review]
This looks good. As the comments states it's not ideal but the workbench is now actually usable on a remote machine with a different resolution and does not look "broken" any more.

**Pull request merged**
