### PR TITLE
override label() in bin edge axis

### LINKED ISSUE #30969: Wrong spectrum axis value in legend for BinEdgeAxis
When the vertical axis is a bin edge axis, the matrix view shows correctly the midpoints.
However the plot legend shows the first edge of the bin and not the center.
Run below, check the data in matrix view, see the vertical axis values.
Now plot one of the spectra, and you will see that it's wrong in the legend.
```
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np
from mantid.api import BinEdgeAxis

dataX = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
dataY = [1,2,3,4,5,6,7,8,9,10,11,12]
ws = CreateWorkspace(DataX=dataX, DataY=dataY, NSpec=4)

beax = BinEdgeAxis.create(5)
beax.setValue(0,1.4)
beax.setValue(1,1.5)
beax.setValue(2,1.6)
beax.setValue(3,1.7)
beax.setValue(4,1.8)
ws.replaceAxis(1,beax)
```

### PR DESCRIPTION
**Pull request by gvardany**
**Description of work.**
Overrides label() in `BinEdgeAxis` to return the bin center and not the edge.

**To test:**
Run the script in the issue.
Open the matrix view (Show Data in context menu).
Observe the vertical axis values.
Plot all the spectra.
Make sure the labels of the curves in the legend match what you see in the matrix view.

Fixes #30969 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by SilkeSchomann** [comment]
Does this branch need to be rebased onto master?

**Review by SilkeSchomann — DISMISSED** [review]
The plot legend now shows the centre of the bin as intended.

**Comment by gvardany** [comment]
Had to rebase and resolve the conflicts, can you have a quick look again?

**Review by SilkeSchomann — APPROVED** [review]
Works as described with legends showing the centre instead of the first edge of a bin for bin edge axis.

**Pull request merged**
