### PR TITLE
Fixed muon thread model so it no longer crashes

### LINKED ISSUE #23760: thread model (muon broken)
The thread model crashes on linux when using the muon GUIs

### PR DESCRIPTION
**Pull request by AnthonyLim23**
The muon thread model crashed instead of giving a nice error message. To fix this I have just reverted the code back and disabled the tests.

**To test:**

On linux open muon analysis and load some data
The open the frequency domain analysis GUI
change to maxent
Tick the use phases box in the table
click the calculate button - it should give a warning box and not crash
Fixes #23760. 

does not need to be in release notes
---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by Pasarus — APPROVED** [review]
Works on Ubuntu 18.04 now :+1: approved when the builds finish properly.

**Comment by AnthonyLim23** [comment]
the build failure is unrelated. @mantidproject/gatekeepers could we please get this merged as it fixes a full mantid crash in ubuntu

**Comment by martyngigg** [comment]
Is there an issue to address the crash properly?

**Comment by AnthonyLim23** [comment]
Not yet, my priority was to stop nightly crashing as I know users who run off of it. I will create one this morning

**Pull request merged**
