### PR TITLE
Re #17557 - added check for mpl in PyChop/__init__.py

### LINKED ISSUE #17557: Change matplotlib import in PyChop
Unit tests for PyChop fails on machines without matplotlib. The tests themselves act only on the CLI part of PyChop, but there is an `import` at the start of the `ISISDisk` module because a method of the `ISISDisk` class is to plot the distance-time diagram. This is not needed on for the unit tests, so the `import` should be moved into the plotting function.

### PR DESCRIPTION
**Pull request by mducle**
Adds an additional test to not load Matplotlib on systems that don't have it - e.g. the build servers for running unit tests which doesn't test the GUI.

**To test:**

Check that unit tests run cleanly on systems without mpl.

Fixes #17557 .

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — CHANGES_REQUESTED** [review]
This looks fine.

Is it worth defining a `showGUI` in the except case that just prints a warning when called? This avoids a user having to check if `showGUI` is defined?

**Comment by martyngigg** [comment]
@mducle The pylint build has failed

**Comment by mducle** [comment]
ooops. Sorry... added more ignores. I should probably fix it rather tell pylint to ignore it, but a bit late now.

**Review by martyngigg — APPROVED** [review]
Thanks. This looks good now.

:shipit:

**Pull request merged**
