### PR TITLE
Fix bug in ikeda carpenter pv

### LINKED ISSUE #24808: Bug in IkedaCarpenterPV
**Original reporter:** [Jack Mingde Jiangy]. 

### Expected behavior
    std::complex<double> zu = (1 - k) * zs;
    std::complex<double> zv = (1 + k) * zs;

### Actual behavior (sign wrong)
    std::complex<double> zu = (1 - k) * zs;
    std::complex<double> zv = (1 - k) * zs;

### Steps to reproduce the behavior
IkedaCarpenterPV of peak does not fit as well at Matlab implementation and user found this difference.

### PR DESCRIPTION
**Pull request by VickieLynch**
**Description of work.**
Mantid coding does not match http://www.ccp14.ac.uk/ccp/web-mirrors/plotr/Tutorials&Documents/TOF_FullProf.pdf. zx and zy were defined to be the same. See equations on page 5

[ProfilesData.nxs.txt](https://github.com/mantidproject/mantid/files/2877332/ProfilesData.nxs.txt)

**Report to:** [Jack Mingde Jiang]. 

**To test:**
````python
LoadNexusProcessed(Filename='ProfilesData.nxs.txt', OutputWorkspace='ProfilesData')
Fit(Function='name=IkedaCarpenterPV,I=115763,Alpha0=6.06599e-05,Alpha1=0.417254,Beta0=251.931,Kappa=5.36998,SigmaSquared=3.66251,Gamma=0.878518,X0=49.2529;name=LinearBackground,A0=0,A1=-0', InputWorkspace='ProfilesData', Output='ProfilesData', OutputCompositeMembers=True, StartX=0, EndX=99)

````

Fixes #24808 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by VickieLynch** [comment]
Hi Anders,
I think you originally wrote this so I hope you will test. SNS user found the bug in code and I think this is right now since the I input is now close to the intensity at the peak. The test does have error flag 18 from gsl about a rounding error so I removed the check. You will see from my data above that the fit is better now with the change, but the results will change for anyone using this function.

**Comment by Anders-Markvardsen** [comment]
Hi Vickie, Apologies but I don't have availablity before Thursday. Would it be OK if I test then?

**Comment by VickieLynch** [comment]
Hi Anders,
Thursday is fine.

Vickie

________________________________

**Review by Anders-Markvardsen — DISMISSED** [review]
Functionally tested and thanks for spotting this sign error

**Comment by Anders-Markvardsen** [comment]
Gatekeeper please wait with merging this PR yet. Driving into work this morning thought it would be worth also just checking how the use of this func with this modification performs against the mantid tutorial examples using this fitting func

**Comment by NickDraper** [comment]
Conflicts - A Haiku

```
To resolve conflicts
developer must merge
in the master branch
```

**Comment by Anders-Markvardsen** [comment]
For sanity also just tested against Exercise 2 in http://www.mantidproject.org/MBC_Exercise_Intelligent_Fitting and the results comes out looking the same when viewed by eye:

With plot guess:
plotguess

And after fitting:
fitted

This means no need to change the tutorials pages.

I confirm that I approve this PR, which makes the Mantid implementation sutbly closer to the implementation of this function in Fullprof. 

Thanks to the SNS user and Vicky for identifying this subtle mismatch

@VickieLynch are you OK to fix conflict?

**Review by Anders-Markvardsen — APPROVED** [review]
Here re-approve

**Pull request merged**
