### PR TITLE
Workbench: Update plots if the workspace data changes

### LINKED ISSUE #24000: Connect plot manager to ADS
Plots should update when the workspace they are showing updates its values.

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Adds an ADS observer to the FigureManager in the workbench. The line and color plots now respond appropriately when workspaces are replaced or deleted.

**Report to:** [nobody]. 

**To test:**

Data: 
  - `ISIS_Powder/input/HRPD66063_focused.nxs` in the `Testing/Data/SystemTest` directory
  - `tests/analysis/reference/MARIReductionSum.nxs` in the `Testing/SystemTest` directory

Use the following script to produce some test workspaces:

```python
focussed = Load('ExternalData/Testing/Data/SystemTest/ISIS_Powder/input/HRPD66063_focused.nxs')
non_common_bins = CloneWorkspace('66063.raw-ResultD-1')
ConjoinWorkspaces(non_common_bins, '66063.raw-ResultD-2')
ConjoinWorkspaces(non_common_bins, '66063.raw-ResultD-3')

common_bins = Load('ExternalData/Testing/SystemTests/tests/analysis/reference/MARIReductionSum.nxs')
```

Use the produced workspaces to test various plots still work:
* use the items in `focussed` to test line plots
* use the both `non_common_bins` and `common_bins` to test colorfill plots

When each of the plots of displayed try deleting workspaces and ensure that the relevant plots are closed when the linked workspace is deleted. For the line plots add multiple curves from different workspaces to the same plot and check that deleting a single workspace only deletes the curves from that workspace.

Try replacing the workspaces using, e.g. `Rebin`, and confirm that the data on any attached plots is updated as expected. 

Fixes #24000 

*This does not require release notes* because **it is part of the unreleased workbench**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DanNixon** [comment]
The following does not work:
- Plot a colour fill
- Replace the workspace (using `Rebin` in my case)
- (at this point the plot is updated as expected)
- Delete the workspace form the ADS
- (expecting the plot to be closed here but the following error is produced)

```
Error occurred in handler:
Traceback (most recent call last):
  File "/mantid_src/qt/applications/workbench/workbench/plotting/figuremanager.py", line 39, in wrapper
    func(*args, **kwargs)
  File "/mantid_src/qt/applications/workbench/workbench/plotting/figuremanager.py", line 83, in deleteHandle
    empty_axes = empty_axes & ax.remove_workspace_artists(name)
  File "/mantid_build/bin/mantid/plots/__init__.py", line 117, in remove_workspace_artists
    artist.remove()
  File "/usr/lib/python2.7/dist-packages/matplotlib/artist.py", line 151, in remove
    self._remove_method(self)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 1764, in <lambda>
    image._remove_method = lambda h: self.images.remove(h)
ValueError: list.remove(x): x not in list
```

**Comment by martyngigg** [comment]
Thanks, Dan. That should be fixed now.

**Comment by DanNixon** [comment]
This is still not quite working for me.

I now have the following failure case:
- Conjoin several workspaces
- Color fill plot the conjoined workspace
- Remove the plotted worksapce
- (only part of the color fill plot is removed, all but one "chunk" remain)

**Review by rosswhitfield — CHANGES_REQUESTED** [review]
It all seems to work except when plotting logs. Deleting the workspace closes the plot but updating (the Rebin below) causes an error _.e.g_

```python
w = LoadEventNexus(Filename='CNCS_7860_event.nxs')
fig, ax = plt.subplots(subplot_kw={'projection': 'mantid'})
ax.plot(w, LogName='SampleTemp')
plt.show()
w=Rebin(w,10)
```

results in

```
Error occurred in handler:
Traceback (most recent call last):
  File "/home/rwp/mantid/qt/applications/workbench/workbench/plotting/figuremanager.py", line 39, in wrapper
    func(*args, **kwargs)
  File "/home/rwp/mantid/qt/applications/workbench/workbench/plotting/figuremanager.py", line 100, in replaceHandle
    redraw_this = ax.replace_workspace_artists(name, workspace)
  File "/home/rwp/build/mantid/bin/mantid/plots/__init__.py", line 145, in replace_workspace_artists
    handler(artist, workspace)
  File "/home/rwp/build/mantid/bin/mantid/plots/__init__.py", line 199, in _data_update
    x, y, _ = plotfunctions._plot_impl(self, workspace, kwargs)
  File "/home/rwp/build/mantid/bin/mantid/plots/plotfunctions.py", line 76, in _plot_impl
    x, y, _, _, kwargs = _get_data_for_plot(axes, workspace, kwargs)
  File "/home/rwp/build/mantid/bin/mantid/plots/plotfunctions.py", line 54, in _get_data_for_plot
    workspace_index, distribution, kwargs = get_wksp_index_dist_and_label(workspace, axis, **kwargs)
  File "/home/rwp/build/mantid/bin/mantid/plots/helperfunctions.py", line 100, in get_wksp_index_dist_and_label
    workspace_index, spectrum_number, kwargs = _get_wksp_index_and_spec_num(workspace, axis, **kwargs)
  File "/home/rwp/build/mantid/bin/mantid/plots/helperfunctions.py", line 144, in _get_wksp_index_and_spec_num
    raise RuntimeError('Must specify either specNum or wkspIndex')
RuntimeError: Must specify either specNum or wkspIndex
```

**Review by rosswhitfield — DISMISSED** [review]

**Comment by martyngigg** [comment]
There now seems to be a bad interaction with the new fitting stuff that has gone in - I'll have to investigate that before this can go in I think.

**Comment by martyngigg** [comment]
This is finally ready for testing again.

**Review by rosswhitfield — APPROVED** [review]

**Pull request merged**
