### PR TITLE
Fix scaling on LARMOR - ISIS Sans

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**

    Fix LARMOR trying to scale LAB fields into mm. This was changed in 5.10
    but was only picked up recently. One of the fields is used as an angle
    input, so cannot be sensibly scaled by 1000.

    In this case we will leave the tolerance...etc. as mm as they are
    unaffected and instead tweak the LAB (and HAB) values specifically

**Report to:** ISIS SANS/Rob + @smk78 

**To test:**
- Download the system test data
- Open the ISIS SANS GUI
- Select user file
- Go to External Data/Data/System Tests/ISIS SANS/LARMOR
- Change from .toml to .txt
- Pick the file with 163 in the name (the newer one)
- Go to beam centre finder
- The values should be -0.14 and -0.002 at the top, not 140 and 2

There is no associated issue. - Genuinely forgot to write one after bisecting the issue

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DavidFair** [comment]
Note to self noticed whilst opening this PR:
- Scaling is not applied when an existing user file is pre-populated. Likely due to us not updating the view after setting inst

**Comment by DavidFair** [comment]
Checking in with the reporting group, they are happy as this doesn't convert existing user files but maintains consistency with values (such as tolerance) that are not included in the user files

**Comment by Harrietbrown** [comment]
I think there may be a step missing in your instructions. the beam center values seem to be on default.

image
image

**Comment by DavidFair** [comment]
There should be defaults associated to an instrument, so this looks like something isn't quite correct
I'll try resetting my Mantid instance and using 163F to see if I get zeros too, this could be a long-standing bug where you need to have loaded data at least once, or something introduced by these changes (likely the GUI not being asked to refresh when it needs to)

**Comment by DavidFair** [comment]
> Yes that now has values in beam centre finder apropriate to meters for LARMOR and mm for Zoom. but the label in the gui always says `Centre Position LAB (mm)` regardless. Can you make that change to refelct the propper value.

I checked with the LARMOR group yesterday and pointed out we don't update it from mm to m. However, this has been true since early Mantid 5.x (as this is a regression fix from 6.0), so they are happy to simply gloss over the fact it says mm in the GUI as that's what they are used to. At least until the group agrees on unified unit prefixes as part of the TOML work

**Comment by DannyHindson** [comment]
@Harrietbrown - are you OK if I assign this to you so it drops out of my "needs reviewing list"? Looks like you've tested this and were just waiting for the tests to pass

**Review by Harrietbrown — APPROVED** [review]
Good job. all the tests are passing and the functionality is working. Well done.

**Pull request merged**
