### PR TITLE
Transmission Correction properties enabled in RRO Dialog

### LINKED ISSUE #15498: Transmission corrections in RRO
In `ReflectometryReductionOne`, there's a section, `Analysis Mode` in the documentation that reads:

> The default analysis mode is PointDetectorAnalysis. Only this modes supports transmission corrections.

When this mode is selected, the input properties related to the transmission run are disabled in the algorithm's dialog. However, if you run the algorithm from a script, providing a transmission run and setting the analysis model to `MultiDetectorAnalysis`, you won't get any error. 

I talked to Jos and Owen about this, and we should be able to apply transmission corrections for MultiDetectorAnalysis too. The user documentation should be updated.

### PR DESCRIPTION
**Pull request by MattKing06**
It was found that if the property for `AnalysisMode` was set to `MultiDetectorAnalysis` in the algorithm dialog for ReflectometryReductionOne then all of the properties associated with Transmission corrections became disabled. A user should be able to apply transmission corrections regardless of what analysis mode they are using however they must provide at least one Transmission run to perform these corrections.

**To test:**
- Load the ReflectometryReductionOne algorithm dialog
- Change the `AnalysisMode` to `PointDetectorAnalysis` and see that the property for `FirstTransmissionRun` is enabled and the rest are disabled within `Transmission` box.
- See that `RegionOfDirectBeam` property is disabled.
- Change the `AnalysisMode` to `MultiDetectorAnalysis` and see that the property for `FirstTransmissionRun` is enabled and the rest are disabled within `Transmission` box.
- See that `RegionOfDirectBeam` property is enabled.
- Close the algorithm dialog.
- Load any MatrixWorkspace into mantid.
- Open the algorithm dialog again.
- Choose an AnalysisMode.
- Select the `FirstTransmissionRun` property to be set to the workspace you previously loaded.
- See that the remaining properties associated with Transmission corrections are now enabled.

Fixes #15498

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
I think this is how the algorithm's dialog should behave. An example script scientists use to reduce the data is:

```
dref=s.OurLoad(r[36688])
dtrans=s.OurLoad(r[36689])

Trans=CreateTransmissionWorkspaceAuto(dtrans,AnalysisMode="MultiDetectorAnalysis",ProcessingInstructions="380-428",WavelengthMin=2.0)
IvsQ, IvsLam, thetaOut=ReflectometryReductionOneAuto(dref,AnalysisMode="MultiDetectorAnalysis",ProcessingInstructions=','.join(map(str, range(250, 557))), FirstTransmissionRun=Trans, ThetaIn="0.6",WavelengthMin=2.0,CorrectionAlgorithm='None',StrictSpectrumChecking=False)#,NormalizeByIntegratedMonitors=False

TvL = ConvertSpectrumAxis(IvsLam,'SignedTheta')
ConvertToReflectometryQ(TvL,IncidentTheta=0.6 ,DumpVertexes=True,OverrideIncidentTheta=True, OutputWorkspace="Qmap",OutputVertexes="Qtable",Extents=[-5e-4,2e-4,0.008,0.1],NumberBinsQz=500,NumberBinsQx=500,Method='NormalisedPolygon',OutputAsMDWorkspace=False)
```
So, from python, it is possible to apply transmission corrections in `MultiDetectorAnalysis` mode, but it was not possible from the algorithm's dialog. This PR fixes this.

@MattKing06 could you update the documentation? Specifically the sections "Analysis Modes" and "Trasmission Runs"

**Comment by raquelalvarezbanos** [comment]
:shipit:

**Comment by MattKing06** [comment]
I will update the release notes with the changes now

**Comment by martyngigg** [comment]
:+1:

**Pull request merged**
