### PR TITLE
SaveAscii support for table workspaces

### LINKED ISSUE #27406: Expand SaveAscii to save Tableworkspaces
**Original reporter:** [James Lord]/[ISIS] Worth also reporting to [Fabio Orlandi]/[ISIS]

### Expected behavior
Should be able to save a TableWorkspace as an ASCII file (and maybe other types of Workspaces!)

Also add a right click option to workbench for tables

### Actual behavior
Only MatrixWorkspaces can be saved as ASCII files currently.
### Platforms affected
All, its a SaveAscii algorithm update that is required. Probably worth double checking that this proposed update works from the Workspace Toolbox as mentioned here: refs #27363

### PR DESCRIPTION
**Pull request by NickDraper**
**Description of work.**
Extended SaveAscii2 to be able to save table workspaces.

**Report to:** James Lord

**To test:**
1. create some table workspaces (handy scripts)
``` python 
from mantid.kernel import V3D

# Create PositionTable
tableWS = CreateEmptyTableWorkspace()

# Add some columns, Recognized types are: int,float,double,bool,str,V3D,long64
tableWS.addColumn(type="int",name="Detector ID")
tableWS.addColumn(type="str",name="Detector Name")
tableWS.addColumn(type="V3D",name="Detector Position")

# Populate the columns for three detectors
detIDList = range(1,4)
detPosList = [ V3D(9.0,0.0,0.0), V3D(10.0,3.0,0.0), V3D(12.0,3.0,6.0)]
for j in range(len(detIDList)):
    nextRow = { 'Detector ID': detIDList[j],
                'Detector Name': "Detector {0}".format(detIDList[j]),
                'Detector Position': detPosList[j] }
    tableWS.addRow ( nextRow )
```
```python 
my_table = CreateEmptyTableWorkspace()

my_table.setTitle("My Data List")

my_table.addColumn("str", "Instrument Name")
my_table.addColumn("int", "Run Number")

my_table.addRow(["MUSR", 10245])
my_table.addRow(["IRIS", 8465])
my_table.addRow(["SANS2D", 20462])
```
1. Save them using SaveAscii, or the save button and the ascii option in the workspaces toolbox
1. look at the file
1. play with the header, and append options and check that they work well.

1. check the behaviour for MDWorkspaces is sensisble.

Fixes #27406

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DanielMurphy22 — COMMENTED** [review]
It seems to work as it should. When making a csv file from your first example TableWS it opened differently in Excel compared to the tableworkspace but I assume there's nothing can be done about this? Table

From the drop-down save button in the Workspaces Toolbox, why are there 2 versions (ASCII and ASCII V1)? Both seem to have your fix in and the dialogs look identical.

I think in the SaveAscii dialog the WorkspaceIndexMax and Min, SpectrumList and WriteSpectrumID and WriteSpectrumAxisNumber are ignored. If this is what we want to impose, is there a way to grey out these options when a TableWorkspace is chosen as the Input

Should [ExampleSaveAscii](https://docs.mantidproject.org/v4.0.0/algorithms/ExampleSaveAscii-v1.html) be able to support Tableworkspaces as well??

**Comment by NickDraper** [comment]
so fr importing into excel, this is due to the commas used inside the V3D (which is a pretty unusual column type outside of peaks workspaces.  In this case just using tabs or semicolons as the separator would solve this.

The save Ascii v1 is a separate issue that we should resolve once we know if SaveAscii v1 is needed anymore.

We don't currently have a way to grey out items based on the ws type selected, but this is a trade off with having a single SaveAscii algorithms compared to different ones for different ws types.

**Comment by NickDraper** [comment]
It is however worth looking at adding LoadAscii support for these files.

**Review by cailafinn — APPROVED** [review]
Code looks good and functions well. Automatic separator detection seems not to work for the saved tables but (as discussed offline) this is something to do later.

**Pull request merged**
