### PR TITLE
Add power and square axis scaling to mantid.plots

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Adds a `PowerScale` and `SquareScale` to the known `matplotlib` scale types for `set_xscale` and `set_yscale`. Some interfaces use squared-axis scaling but it seemed sensible to implement a general power and then a specific square case.

The scale is registered in `mantid.plots` so is available wherever `MantidAxes` is available.

**To test:**

This can be used standalone without MantidPlot or Workbench. The following shows a quadratic curve mapped to a square and power scale (exponent=2) such that it produces a straight line.

```python
import mantid.plots
import numpy as np
import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 3)

x = np.arange(-5, 6, 1.)
s = np.power(x, 2)

titles = ('Linear X Scale', 'Square X Scale', 'Power 2 X Scale')
for ax in axes:
    ax.plot(x, s, '-', lw=2)
    ax.set_xlabel('X')
    ax.set_ylabel('X^2')
    ax.grid(True)

# 0 is linear
axes[0].set_title('Linear X Scale')
# 1 is square
axes[1].set_title('Square X Scale')
axes[1].set_xscale('square')
# 2 is power
axes[2].set_title('Power gamma=2 X Scale')
axes[2].set_xscale('power', gamma=2)

plt.show()
```

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AndreiSavici** [comment]
I've tried the script in mantid workbech. This is what I get 
Figure_1

```python
matplotlib.__version__
2.1.1

a1=axes[1]
a1.get_xscale()
'square'

a1.get_xlim()
(0.0, 9.9999999999999998e-13)
```

I am running on Ubuntu, built with python3

**Comment by martyngigg** [comment]
Thanks for testing it. Something must be acting differently in `matplotlib >= 2`. I'll take a look.

**Comment by martyngigg** [comment]
It turns out matplotlib >= v2 adds a margin to the plots that extended the scale to negative values and the scale was not accounting for the fact that (-x)^(1/2) is not a real value. This should be fixed now. I also fixed an issue with odd powers so the following should work too:
```python
import mantid.plots
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(-100, 100, 0.1)
s = np.power(x, 3)

titles = ()
fig, ax = plt.subplots(1, 1)
ax.plot(x, s, '-', lw=2)
ax.set_title('Cubic X Scale')
ax.set_xlabel('X')
ax.set_ylabel('X^3')
ax.grid(True)
ax.set_xscale('power', gamma=3)
plt.show()
```

**Review by AndreiSavici — APPROVED** [review]
Works with the new matplotlib

**Pull request merged**
