### PR TITLE
Indirect - Modify ApplyPaalmanPings to work with corrections from CalculateMonteCarloAbsorption

### LINKED ISSUE #21316: Indirect - Absorption Corrections - Apply Monte Carlo Corrections Interface
There is currently no interface for applying the absorption corrections created from within the Calculate Monte Carlo Absorption interface.

The ApplyPaalmanPings interface should be changed to a more general interface for applying absorption corrections.

### PR DESCRIPTION
**Pull request by brandonhewer**
Currently, the ApplyPaalmanPings interface (and by extension the Apply Paalman Pings interface), will not work when supplied the output from the CalculateMonteCarloAbsorption algorithm (alternatively the Calculate Monte Carlo Absorption interface). This is as a result of four of the Paalman Pings factors being required in the ApplyPaalmanPings algorithm.

This PR adds a two-factor approximation to the ApplyPaalmanPings algorithm (used when only two correction factors are provided) and changes the name of the Apply Paalman Pings interface to Apply Absorption Corrections.

Unit Tests and documentation changes (including workflow diagram) have been included.

**To test:**
1. Navigate to Interfaces > Indirect > Corrections > Calculate Monte Carlo Absorption.
2. Provide the supplied sample and container files.
3. Set 'Sample Width' to `0.3`.
4. Set 'Sample Thickness' to `0.1`.
5. Set 'Sample Height' to `0.5`.
6. Set 'Container Front Thickness' to `0.1`.
7. Set 'Container Back Thickness' to `0.1`.
8. Enter `H2-0` as the chemical formula under 'Sample Details'
9. Enter `Al` as the chemical formula under 'Container Details'
10. Click 'Run'.
11. Navigate to the Apply Absorption Corrections tab.
12. Provide the sample file into the Input field.
13. Check the 'Use Container' check-box and provide the container file.
14. Check the 'Use Corrections' check-box, change the drop-down menu to 'Workspace' and select the created `*_Corrections` workspace group.
15. Click 'Run'.
16. Ensure the algorithm is run successfully, a corrected workspace is added to the ADS and a plot of the sample, container and corrected data are shown in the interface.

**Test Files**
[test-files.zip](https://github.com/mantidproject/mantid/files/1528245/test-files.zip)

Fixes #21316. 

**Release Notes** 

#### Changes have been added to the release notes.
---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [x] Are the unit tests small and test the class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] Do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by soininen** [comment]
`H2O` is not recognized as a chemical formula. I guess it should be written with a space between the elementes, i.e. `H2 O` but the text field doesn't accept spaces.

**Comment by SpencerHowells** [comment]
@soininen @brandonhewer The correct chemical formula is H2-O

**Comment by brandonhewer** [comment]
@soininen @SpencerHowells Yes, that was my mistake, I forgot to add the hyphen.

**Comment by soininen** [comment]
Hyphen worked with the chemical formula but now I'm stuck with applying the corrections. When I click on 'Run', I get the message: "Please correct the following: Sample and can workspaces must contain the same type of data." I'm using the sample.nxs and container.nxs files provided in the PR.

**Comment by brandonhewer** [comment]
@soininen A check occurs between the types of the sample and container, which uses their prefix. This is an unnecessary check, since both are converted to units of wavelength. Similar to container subtraction, this check has been removed.

**Review by soininen — APPROVED** [review]
The interface seems to work as expected. A small glitch is that in the file browser dialog, I had to choose 'All Files' instead of 'Data Files' to see the provided test files. I assume this is due to the filenames missing proper suffices. Code-wise I have no comments, the changes look good to me. However, it might be nice to break changesets like this into two parts in the future: one PR for the algorithm and a second one for the interface to keep the PRs smaller. Anyway, nice work!

**Pull request merged**
