### PR TITLE
Revert removal of cmake COMPONENT installs 

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Originally added in #32903, in order to make a package of just runtime components, the changes were reverted by #32996 as they broken the current bundling on Windows/macOS.

These changes add the necessary cpack flags to disable the component installs/prefixes in non-conda mode.

**To test:**

These changes need to be tested on all 3 operating systems for the non-conda package build and in addition using the instructions in the original issue to build a standalone bundle based on conda on macOS. See #32903.

Refs #33024 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by thomashampson — APPROVED** [review]
Packaging on Windows is working correctly.

**Comment by martyngigg** [comment]
@DanielMurphy22 @DavidFair @Pasarus 
I think it would be good to just verify this is okay on mac & linux for the current packaging so we know we have fixed it everywhere.

**Comment by martyngigg** [comment]
Oh blast! I went to add additional comment and somehow managed to click the merge button 🤕 I need to leave my computer now...

**Comment by DanielMurphy22** [comment]
I'm running a non-conda package build of main on MacOS

**Pull request merged**
