### PR TITLE
Removed the LoadAscii Custom Dialog, it was out of date with the alg

### LINKED ISSUE #22872: Specialized algorithm dialog for LoadAscii doesn't have the correct properties
There is a specialized dialog for `LoadAscii`:

loadasciidialog

The dialog does not correspond to the algorithm, however. *Workspace* should be *InputWorkspace* and the *SkipNumLines* property is missing.

### PR DESCRIPTION
**Pull request by NickDraper**
**Description of work.**

The custom dialog was out of date with the algorithm, and was not useful 
because:
1. it only selected the , seperator if the file extension was csv (and the algorithm has automatic seperator detection by default anyway)
1. If used via Load the custom dialog was skipped anyway

So I've removed it as the default one is fine, and stays up to date with the alg.

**Report to:** nobody

**To test:**

1. Just use the LoadAscii algorithm from the default dialog and check you are happy

Fixes #22872. 

Does this update require release notes?
- [ ] Yes
- [x] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
Unable to obtain suitable ASCII files. Even those I created with SaveAscii failed to be read.

**Comment by NickDraper** [comment]
[aatestascii.txt](https://github.com/mantidproject/mantid/files/2254006/aatestascii.txt)


This is just saved using SaveAscii from the monitors workspace of OFFSPEC00042712 (a random workspace I picked).

**Comment by NickDraper** [comment]
There is also the example on the alg doc page.

http://docs.mantidproject.org/nightly/algorithms/LoadAscii-v2.html

**Review by martyngigg — APPROVED** [review]
Confirmed removal of outdated custom dialog. It will now revert to the automatically-generated one.

**Pull request merged**
