### PR TITLE
Create algorithm that loads, checks and merges multiple POLDI data files

### PR DESCRIPTION
**Pull request by MichaelWedel**
This addresses [#11285](http://trac.mantidproject.org/mantid/ticket/11285).

**Testing information**
Make sure the system- and doc-tests pass on all platforms. A documentation page has been added where some usage examples for the algorithm are given. They work with the usage example test data.

### CODE REVIEW

**Comment by MichaelWedel** [comment]
Jenkins retest this please

**Comment by MichaelWedel** [comment]
Jenkins retest this please

**Comment by MichaelWedel** [comment]
The fail on windows was unrelated, but it's important to see that the doctests work also on that platform.

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by MichaelWedel** [comment]
Jenkins retest this please

**Comment by FedeMPouzols** [comment]
All looks good and this new algorithm will be very convenient. All tests passed on the CI servers and also locally. The documentation reads well and It comes with fairly exhaustive tests and doc tests.

The only thing that occurred to me, which is not really specific to this ticket, is that maybe in PoldiLoadRuns-v1.rst and similar doc tests that create several workspaces you could use `testcleanup` sections to do a `DeleteWorkspace` on a few or all of them. Otherwise all the workspaces remain in the ADS. As the doc tests are run sequentially, some of the subsequent tests can be confused if a name conflict arises at some point. I guess in this case the chances are very low, as the workspace names include the run numbers. Last time I run the doc tests interactively I could see lots of workspaces  being accumulated throughout the doc tests, using all sorts of funny names, and we could run into trouble at some point with this. On the other hand, that can be seen as a kind of convenient stress testing!

**Comment by MichaelWedel** [comment]
Yes that is actually something I have not considered so far. I just created a ticket to deal with it for all POLDI documentation ([#11364](http://trac.mantidproject.org/mantid/ticket/11364)).

**Pull request merged**
