### PR TITLE
ISIS SANS Manual Test Script Updates

### LINKED ISSUE #24728: Updates to ISIS SANS Unscripted Test
**Original reporter:**  @Pasarus 

* "A plot window will open; initially empty, then with a red line". Line colour should not be specified as it is different for workbench due to matplotlib backend
* Another reference to line colour further down in script
* "6 additional rows should appear in the table" -> Columns, not rows
* In section 6, "Reduction Type" should be changed to "Reduction Mode"

### PR DESCRIPTION
**Pull request by TTitcombe**
**Description of work.**
Updates to the ISIS SANS manual test script

**Report to:** nobody

**To test:**
Run through the test script edited in this PR

Fixes #24728 

*This does not require release notes* because **small change to internal manual testing script**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by soininen — CHANGES_REQUESTED** [review]
Is there an entry to this document anywhere in `dev-docs`? Can I suggest adding a reference in `dev-docs/source/Testing/index.rst`?

Other issues:
- line 32: I get 4 group workspaces and a fifth hidden `Workspace2D` (`__sans_mak_display_dummy_workspace`)
- line 33: there is no 'process' to click. Process Selected?
- line 45: the first icon button is called `Insert` not `Add`
- line 48: Within the Setting tab there are several subtabs. `General, Scale, Event Slice, Sample` could be referenced here
- line 68: typo: `you r` -> `your`

**Comment by TTitcombe** [comment]
@soininen I've fixed your requested changes.
I've opened #24847 to address the extra scope of the test script. I'm currently not sure how best to test this area of the GUI at the moment. While this change would be useful it's outside the scope of this PR which aims to address some minor mistakes in the current script
I don't believe there should be a hidden workspace, so I will open up an issue to deal with this separately. However I don't see any hidden workspaces when I process - can I check that you're seeing this the first time you click Process All?

**Comment by soininen** [comment]
What I meant with the comment about line 48 was that it would be clearer if that particular set of instructions within the Settings tab would specify exactly which subtab the listed operations should be found in. Just like, say, in items 4 and 5. Sorry for not being very clear about it. Anyway, it is always good to have better coverage for the testing so the new issue is a nice addition.

The hidden workspace appears when clicking the Display Mask button.

**Comment by TTitcombe** [comment]
Ah okay that makes sense, I've pushed a commit to make it clearer where we should find the various options.
I see the hidden workspace, I'll address that in a separate issue. Thanks for pointing it out

**Review by soininen — APPROVED** [review]

**Pull request merged**
