### PR TITLE
Fix crash reported in ALC interface with "Auto"

### LINKED ISSUE #15662: ALC interface freezes with "Auto" mode
Crash reported by James Lord, Mantid 3.6 on instrument analysis PC
> I'm looking at current HIFI data in the ALC interface. With runs 98160 to 98164, log value "Laser_Delay", dead time from file, periods 2-1, all works well. But if I tick "Auto" last file, and then Load, Mantid stops responding.

> Is it related to the temporary files not having the numbers of good frames in period mode? Or that the values of Laser_Delay are not in an increasing sequence, and some are negative?

### PR DESCRIPTION
**Pull request by tom-perkins**
Fix a crash reported in the ALC interface

The interface froze when used with the "Auto" checkbox ticked in a network drive with lots of instrument data in it. The "Auto" function had been tested on directories of .nxs files, but this contained many different file types and other directories - the non-NeXus files weren't being ignored correctly, causing an infinite loop when trying to find the most recently modified file. 

Fixed the bug and moved the function into its own class so that it could be tested.
Added a test to prevent regression.

**To test:**

A new unit test is intended to cover the "finding most recent file in the directory" functionality.
_Functional testing:_
Create a directory with some muon data files and also other (non-NeXus) files in it. 
(The crash was seen in `\\hifi\data` which contains nxs, raw, txt, log...)
Launch the ALC interface (Interfaces/Muon/ALC) and select one of the muon files as the first run. Check "Auto" by the last run box and try to load the data.
- Interface should not crash or freeze
- Should pick up new files added/removed automatically
- Should deal with the case where the newest file is not a NeXus file
- Try generating a crash with bad input

Fixes #15662.

The [release notes](https://github.com/mantidproject/mantid/blob/fc485521e39f96cdbd13a23962da31a636b9fc5b/docs/source/release/v3.7.0/muon.rst) have been updated.

**To do:** update James when fix is in place

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
I tried the following cases:

In a directory with some HIFI files (HIFI00083077.nxs to HIFI00083077.nxs):

- Added a .txt file, nothing happend (OK)
- Added an ENGINX file, nothing happend (OK)
- Added a file called "ALCResults.nxs". I got an error message saying: "File name must end with a number. in D:<path>\ALCResults"
- Added CHRONUS00003420.nxs. The interface shows an error message saying "Find and last runs are not in the same directory".

The problem in the last two cases is that if new valid files (valid = same instrument) are loaded, you keep getting the same error message every time a new file is added. I think we should just ignore files which come from a different instrument (also files that are not named as expected: INSTR000XXXX.nxs). Maybe this could be done by our `ALCLatestFileFinder` (this could then be tested too). What do you think?

**Comment by tom-perkins** [comment]
Yes, I agree - it should find the latest valid file and ignore any that are not valid. 
At the moment it just finds the most recently modified NeXus file, so this should be changed to the most recently modified *valid* NeXus file.
I'll change this and add a test.

**Comment by tom-perkins** [comment]
Added tests for NeXus files from other instruments and invalid names. The finder should now find the most recent valid NeXus file.

**Comment by raquelalvarezbanos** [comment]
Thanks Tom, I tried again the same cases, all of them behaved as expected. Excellent unit tests.

:shipit:

**Pull request merged**
