### PR TITLE
Expose MultipleFileProperty constructor to python

### PR DESCRIPTION
**Pull request by peterfpeterson**
As part of the continuing effort to make things easier to do in python, expose the constructor for `MultipleFileProperty`. This also simplifies client code by always returning a `list` of `str`.

**To test:**

This can be verified by a simple code review.

_There is no associated issue_

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

Also changed the return to always be a list of strings. This
required changing the unit tests.

### CODE REVIEW

**Comment by rosswhitfield** [comment]
LGTM :shipit:

**Comment by AndreiSavici** [comment]
https://github.com/mantidproject/mantid/blob/aeb269d5c61754eaaaf6d10c492fc7ef2cb84ebd/scripts/Interface/reduction_gui/reduction/inelastic/dgs_reduction_script.py#L184-L185 should be changed as well, since you always return a list

**Comment by AndreiSavici** [comment]
Also check https://github.com/mantidproject/mantid/blob/dce42e09778bfd879c263038297fd29c6349dc6a/scripts/SANS/SANSUtility.py#L230

**Comment by peterfpeterson** [comment]
`SANSUtility.py` does not need to be altered since `getPropertyValue` returns a `str` rather than a first python object.

**Comment by rosswhitfield** [comment]
LGTM :shipit:

**Pull request merged**
