### PR TITLE
Remove FindReflectometryLines version 1

### LINKED ISSUE #23345: Remove FindReflectometryLines version 1
`FindReflectometryLines-v1` should be removed in a future release as it has been deprecated in PR #23328.

### PR DESCRIPTION
**Pull request by soininen**
Remove the deprecated version 1 of the `FindReflectometryLines` algorithm.

**To test:**

Check that there are no traces of the algorithm version left.

Fixes #23345.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by soininen** [comment]
@gemmaguest Version 1 of `FindReflectometryLines` is still used by the POLREF system test causing the builds to fail. Can you confirm if the test can be updated or if it is too early to remove the deprecated version?

**Comment by gemmaguest** [comment]
@soininen Sorry I forgot to get back to you on this. V1 is not used at ISIS so it's fine to remove it. I'm not sure what to do about the test - I think we can replace it with v2 if we use `RangeLower` instead of `StartWavelength`?

**Comment by soininen** [comment]
@gemmaguest Actually, to me it looks like the failing part is just testing if `FindReflectometryLines` works. The result is not used for anything else and the test passes if the lines are removed. If V1 is not used at ISIS, perhaps it is sufficient to just remove this part of the test?

**Comment by gemmaguest** [comment]
@soininen Yes, that sounds sensible :+1:

**Review by martyngigg — APPROVED** [review]

**Pull request merged**
