### PR TITLE
Disable unreliable test on macOS

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Disable unreliable `ScalesTest` on macOS until it is investigated.

**To test:**

Code review and see the mac tests pass.

*There is no associated issue.*

*This does not require release notes* because **it is a developer change.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by dtasev — APPROVED** [review]
Test has failed two times (that I could see) today:
https://builds.mantidproject.org/job/pull_requests-osx/30990/
https://builds.mantidproject.org/job/pull_requests-osx/30996/

This will prevent random build failures until it is further investigated. This test was added to CMake in #26418 as it was noticed missing and was never ran until then

**Review by DanNixon — COMMENTED** [review]
It may be worth adding a `TODO` or `FIXME` next to the test in the `CMakeLists.txt` (with the number of a follow up issue if created).

**Comment by martyngigg** [comment]
I've found the proper fix. I'll close this.

**Comment by martyngigg** [comment]
Real fix: #26469

**Pull request closed without merging**
