### PR TITLE
Fix for sequential and Serial fit buttons in Eng Diff interface

### LINKED ISSUE #35595: Error when serial or sequential fit when no data plotted and no fit function defined in EngDiff UI
**Describe the bug**
Found during manual testing #35541 
Error when serial or sequential fit when no data plotted or loaded in EngDiff UI - this is a regression

For Sequential fit it throws this error:

```
Traceback (most recent call last):
  File "/home/mlc47243/mambaforge/envs/manualtesting/lib/python3.8/site-packages/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/plot_presenter.py", line 103, in do_seq_fit
    self.fit_all_started_notifier.notify_subscribers(True)
  File "/home/mlc47243/mambaforge/envs/manualtesting/lib/python3.8/site-packages/mantidqt/utils/observer_pattern.py", line 101, in notify_subscribers
    Observable.notify_subscribers(self, *args)
  File "/home/mlc47243/mambaforge/envs/manualtesting/lib/python3.8/site-packages/mantidqt/utils/observer_pattern.py", line 56, in notify_subscribers
    self.thread_safe_update_call(arg, **kwargs)
  File "/home/mlc47243/mambaforge/envs/manualtesting/lib/python3.8/site-packages/mantidqt/utils/qt/qappthreadcall.py", line 69, in __call__
    return self._callable(*args)
  File "/home/mlc47243/mambaforge/envs/manualtesting/lib/python3.8/site-packages/mantidqt/utils/observer_pattern.py", line 60, in _notify_subscribers_impl
    observer.update(self, arg, **kwargs)
  File "/home/mlc47243/mambaforge/envs/manualtesting/lib/python3.8/site-packages/mantidqt/utils/observer_pattern.py", line 93, in update
    self.callback(arg)
  File "/home/mlc47243/mambaforge/envs/manualtesting/lib/python3.8/site-packages/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/presenter.py", line 41, in fit_all_started
    ws_name_list = self.data_widget.get_sorted_active_ws_list()
  File "/home/mlc47243/mambaforge/envs/manualtesting/lib/python3.8/site-packages/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/common/data_handling/data_widget.py", line 30, in get_sorted_active_ws_list
    return self.presenter.get_sorted_active_ws_list()
  File "/home/mlc47243/mambaforge/envs/manualtesting/lib/python3.8/site-packages/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/common/data_handling/data_presenter.py", line 43, in get_sorted_active_ws_list
    return self.model.get_active_ws_sorted_by_primary_log()
  File "/home/mlc47243/mambaforge/envs/manualtesting/lib/python3.8/site-packages/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/common/data_handling/data_model.py", line 270, in get_active_ws_sorted_by_primary_log
    log_table = ADS.retrieve(primary_log + self._suffix)
KeyError: "'strain_Fitting' does not exist."
```

For serial fits this error:
```
TypeError on line 142 of '/home/mlc47243/mambaforge/envs/manualtesting/lib/python3.8/site-packages/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/plot_presenter.py': 'NoneType' object is not subscriptable
```

**To Reproduce**
Test 7 and 9 of manual testing instructions
https://developer.mantidproject.org/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.html

**Expected behavior**
Buttons should be greyed out or at least not produce an error

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: [e.g. Windows, RHEL 7, Ubuntu, macOS]
 - OS Version:
 - Mantid Version [e.g. 6.0.0]

**Additional context**

### PR DESCRIPTION
**Pull request by jhaigh0**
**Description of work**

Fix bug highlighted in manual testing where clicking the sequential or serial fit buttons in the Engineering Diffraction interface fitting tab would result in an unhandled error if data was not loaded or if a fitting model was not set.

The buttons are now disabled until it is possible to fit (there is data loaded and there is a model).

**To test:**

- Open the Engineering Diffraction interfaces and go to the fitting tab
- [ ] With no data loaded, the `Sequential Fit` and `Serial Fit` buttons should be disabled
- Follow the steps [here](https://developer.mantidproject.org/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.html#focus) to get some focused data (skip if you have some)
- Load that data into the fit tab with `Add to plot` checked
- [ ] Once again, click on the `Sequential Fit` and `Serial Fit` buttons should be disabled since there is no model set
- Click the `Fit` button to bring up the fit property browser interface
- Right click and add a peak to the plot (so there is now a model)
- [ ] `Sequential Fit` and `Serial Fit` should now both run when their corresponding buttons are clicked

Test other scenarios that you can think of if you are more familiar with this interface than me

Fixes #35595

*This does not require release notes* because **it's a regression fixed before release**

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by RichardWaiteSTFC — CHANGES_REQUESTED** [review]
Thanks for looking into this, I think instead of checking for "No fitting model set" it would be better to use the fit_enabled notifier
https://github.com/mantidproject/mantid/blob/323b4633100e5ecfec66cdd6e91ebc6790408032/qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/EngDiff_fitpropertybrowser.py#L104
This will only be true if the fit property browser is shown (which can only happen if there is data plotted) and there is a valid function

**Comment by jhaigh0** [comment]
> Thanks for looking into this, I think instead of checking for "No fitting model set" it would be better to use the fit_enabled notifier
> 
> https://github.com/mantidproject/mantid/blob/323b4633100e5ecfec66cdd6e91ebc6790408032/qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/EngDiff_fitpropertybrowser.py#L104
> 
> This will only be true if the fit property browser is shown (which can only happen if there is data plotted) and there is a valid function

What about in the case where the fit property browser is enabled, but there is no model? I chose `read_fitprop_from_browser` since it calls `fit_browser.read_current_fitprop()` which returns none if there is no function string.

**Comment by RichardWaiteSTFC** [comment]
> > Thanks for looking into this, I think instead of checking for "No fitting model set" it would be better to use the fit_enabled notifier
> > https://github.com/mantidproject/mantid/blob/323b4633100e5ecfec66cdd6e91ebc6790408032/qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/EngDiff_fitpropertybrowser.py#L104
> > 
> > This will only be true if the fit property browser is shown (which can only happen if there is data plotted) and there is a valid function
> 
> What about in the case where the fit property browser is enabled, but there is no model? I chose `read_fitprop_from_browser` since it calls `fit_browser.read_current_fitprop()` which returns none if there is no function string.

I believe `isEnabled` will only return `True` if there is a function string (this is done here I think)
https://github.com/mantidproject/mantid/blob/323b4633100e5ecfec66cdd6e91ebc6790408032/qt/widgets/common/src/FitPropertyBrowser.cpp#L771

**Comment by RichardWaiteSTFC** [comment]
> > > Thanks for looking into this, I think instead of checking for "No fitting model set" it would be better to use the fit_enabled notifier
> > > https://github.com/mantidproject/mantid/blob/323b4633100e5ecfec66cdd6e91ebc6790408032/qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/EngDiff_fitpropertybrowser.py#L104
> > > 
> > > This will only be true if the fit property browser is shown (which can only happen if there is data plotted) and there is a valid function
> > 
> > 
> > What about in the case where the fit property browser is enabled, but there is no model? I chose `read_fitprop_from_browser` since it calls `fit_browser.read_current_fitprop()` which returns none if there is no function string.
> 
> I believe `isEnabled` will only return `True` if there is a function string (this is done here I think)
> 
> https://github.com/mantidproject/mantid/blob/323b4633100e5ecfec66cdd6e91ebc6790408032/qt/widgets/common/src/FitPropertyBrowser.cpp#L771

Also you could use the notifier to enable/disable the Serial and Sequential Fit buttons rather than print a warning to the log

**Comment by jhaigh0** [comment]
> 

Okay thank you for explaining, I think that makes more sense yeah. I'll have a go at all that tomorrow 👍

**Review by RichardWaiteSTFC — APPROVED** [review]
Looks great, thanks for using the fit_enabled notifier and for the fix! Everything works as expected, buttons are greyed out until data is plotted, the fit browser is open and a valid function is defined.

**Comment by jhaigh0** [comment]
Thanks for showing me the observers, much neater way of doing it.

**Comment by sf1919** [comment]
@mantidproject/gatekeepers please can this be reviewed? We'd like it in before Beta testing begins

**Pull request merged**
