### PR TITLE
Fix clang-tidy misc-unused-using-decls

### PR DESCRIPTION
**Pull request by samueljackson92**
**Description of work.**
Fixes a bunch of clang-tidy warnings for `misc-unused-using-decls`
**To test:**

 - Code review
 - Builds pass

_No associated issue_

Does this update require release notes?
- [ ] Yes
- [x] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — APPROVED** [review]
LGTM

**Review by peterfpeterson — CHANGES_REQUESTED** [review]
Please add this as one of the flags turned on in [CommonSetup.cmake](https://github.com/mantidproject/mantid/blob/master/buildconfig/CMake/CommonSetup.cmake#L263)

**Comment by samueljackson92** [comment]
@peterfpeterson I think it is already? Looking at that line 263 we have `misc-*` which I assume includes all warnings prefixed with `misc`?

https://github.com/mantidproject/mantid/blob/cedc8326d16df1a42bd33b21855f60a228565072/buildconfig/CMake/CommonSetup.cmake#L255-L265

**Review by peterfpeterson — APPROVED** [review]

**Comment by peterfpeterson** [comment]
You are right.

**Pull request merged**
