### PR TITLE
Export tick formatter commands to plot script

### LINKED ISSUE #31374: Scientific formatting option not written to plot script
**Original reporter:** @sf1919 
As seen in Manual testing #31111 
Relates to #31259 

### Expected behavior
When changing the tick format on the axis of a plot to "Scientific Format" this should still be set when the plot is created from a script that was generated from that changed plot.

### Actual behavior
Unless the "Log" checkbox is ticked then the plot axis is defaulting to Decimal format when doing one of the following:-
- copy script to clipboard and then running it in script editor
- save script to file and then load & run script from file

### Steps to reproduce the behavior
- Load a file
- Plot one or more of the spectra from it. 
- Double click on either the x or y axis to edit the axis. 
- In the dialog that appears change Tick Format to Scientific Format. Plot axis will then change to Scientific Format. 
- Copy script to clipboard and then run it in script editor
The tick labels will revert to decimal format.

### Platforms affected
All

### PR DESCRIPTION
**Pull request by srikanthravipati**
**Description of work.**
Commands for settings axis tick label formats are now generated by the plot script generator. They will be omitted if they are default values.

**To test:**
- Load a workspace and plot a spectrum.
- Double click an axis to bring up the "Edit axis" dialog.
- Change the "Tick Format" to "Scientfic Format".
- Click the script button and select "Script to clipboard".
- Close the plot.
- Paste the script in the Editor.
- You should see a line containing "set_major_formatter" for the axis that you changed the format for.
- Run the script and it should reproduce the plot, including the tick formatting.

The script commands should only appear for non-default formatters for each axis. There are unit tests that enforce this, but you can check by performing similar steps to above. The defaults are:
- Decimal format (ScalarFormatter) for a linear axis.
- Scientific format (LogFormatterSciNotation) for a log axis.

Fixes #31374 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by SilkeSchomann — DISMISSED** [review]
Code looks good and works as expected

**Comment by SilkeSchomann** [comment]
@srikanthravipati This branch has also conflicts

**Review by SilkeSchomann — DISMISSED** [review]
Conflicts resolved, good to go.

**Comment by gemmaguest** [comment]
@srikanthravipati Sorry, more conflicts!

**Comment by srikanthravipati** [comment]
> @srikanthravipati Sorry, more conflicts!

@gemmaguest No worries. I was prepared for that. Resolved now.

**Review by SilkeSchomann — APPROVED** [review]
Changes approved.

**Pull request merged**
