### PR TITLE
Increase BinWidth precision in Dynamic Kubo Toyabe Fit function

### LINKED ISSUE #31890: bin width bug in dynamic Kubo Toyabe
The Dynamic Kubo Toyabe function's BinWidth parameter is only shown to 2 d.p. Since the smallest valid bin width is 0.001 this isn’t ideal

https://github.com/mantidproject/mantid/blob/master/Framework/CurveFitting/src/Functions/DynamicKuboToyabe.cpp#L286

### PR DESCRIPTION
**Pull request by sf1919**
**Description of work.**
Changed the precision of the QtDoublePropertyManager so that the BinWidth for Dynamic Kubo Toyabe Algorithm will display to 3 d.p. rather than just two. Previously it would display to 2 d.p. which wasn't suitable, especially as minimum value is 0.001.

**To test:**
1. Open Muon Analysis GUI
2. Load a run
3. Open the fitting tab
4. Right click in empty Property/Value table to add a function
5. Search for DynamicKuboToyabe and select
6. The Bin Width should show as 0.050. 
7. Change the bin width to any 3 decimal number between 0.001 and 0.100 . It should continue to show as a number to 3 d.p.

Fixes #31890 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Harrietbrown** [comment]
If I try to set the value to something outside of the range it crashes workbench when it should propperly just raise an error message.

**Comment by sf1919** [comment]
> 
> 
> If I try to set the value to something outside of the range it crashes workbench when it should propperly just raise an error message.

I'm surprised by this as it should be raising an error (see https://github.com/mantidproject/mantid/blob/7d925b9547bc98235c739200a876e23509eaf492/Framework/CurveFitting/src/Functions/DynamicKuboToyabe.cpp#L324 on to line 334). Looks like it's possibly not calling this as it should so will investigate.

**Comment by AnthonyLim23** [comment]
> > If I try to set the value to something outside of the range it crashes workbench when it should propperly just raise an error message.
> 
> I'm surprised by this as it should be raising an error
> https://github.com/mantidproject/mantid/blob/7d925b9547bc98235c739200a876e23509eaf492/Framework/CurveFitting/src/Functions/DynamicKuboToyabe.cpp#L324-L334
> 
> 
> Looks like it's possibly not calling this as it should so will investigate.

I think it works in master

**Comment by Harrietbrown** [comment]
I will make an unstable and test it there

**Comment by Harrietbrown** [comment]
So this does seem to be a pre existing issue. Sarah can you make an issue for it and have a look into fixing that? outside of that this works.

**Review by Harrietbrown — DISMISSED** [review]
This does expand the accepted range. the issue with entering values outside of the range can be addressed in it's own issue.

**Comment by sf1919** [comment]
Ok so I've set up a new issue for the crashing #31926

**Review by Harrietbrown — DISMISSED** [review]
A mistaken push removed my previous review. still good to merge.

**Review by Harrietbrown — APPROVED** [review]

**Pull request merged**
