### PR TITLE
Indirect Python refactoring

### PR DESCRIPTION
**Pull request by DanNixon**
Ticket [#10706](http://trac.mantidproject.org/mantid/ticket/10706).

To test, code review and ensure all tests pass (including Windows system tests).

### CODE REVIEW

**Comment by DanNixon** [comment]
Jenkins, retest this please.

**Comment by martyngigg** [comment]
I've merged the branch to develop so I can check the system tests on Windows.

**Comment by martyngigg** [comment]
All of the indirect tests passed, with the exception of the current OSIRIS OS X failure that is a different issue.

**Comment by DanNixon** [comment]
This had a very disappointing effect on the number of violations, I think a lot of the fixes must have overlapped with Andrei's.

**Pull request merged**
