### PR TITLE
Asymmetry algorithms sphinx errors fix

### PR DESCRIPTION
**Pull request by AnthonyLim23**
The new asymmetry algorithms were producing sphinx errors. I have corrected the documentation. 

**To test:**
Compiles with no sphinx errors. 

Does not need to be in the release notes

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AndreiSavici** [comment]
Need to print with formatting, so you don't have problems with rounding errors or whitespaces

**Comment by AnthonyLim23** [comment]
that should fix the issue. I have also added python 3 formatting to the scripts

**Comment by martyngigg** [comment]
@AndreiSavici I was going to merge this on the command line and resolve the conflict at the same time if that's okay with you?

**Comment by AnthonyLim23** [comment]
:+1:

**Comment by AndreiSavici** [comment]
@martyngigg Sure. That's fine with me. :shipit:

**Pull request merged**
