### PR TITLE
Indirect Bayes - Add plot Current Preview

### LINKED ISSUE #17262: Indirect Bayes - Add plot current preview
Add an option to plot the spectrum currently shown on the miniPlot preview window. Also tidy up GUI surrounding miniPlot window.

- [ ] Resnorm
- [ ] Quasi
- [ ]  Stretch

### PR DESCRIPTION
**Pull request by louisemccann**
Added functionality for creating a plot of the current miniplot for Indirect>Bayes interfaces.

**To test:**

Input Files:
[ResNorm.zip](https://github.com/mantidproject/mantid/files/827784/ResNorm.zip)
[Quasi - Stretch.zip](https://github.com/mantidproject/mantid/files/827783/Quasi.-.Stretch.zip)

Interfaces>Indirect>Bayes

For each interface check that the "current spectrum" spin box changes the miniplot.
Click "Plot Current Preview" button and ensure that plot produced matches the current spectrum on the miniplot.
Try plotting both before and after pressing `Run`

ResNorm:
Vanadium: `iris26173_graphite002_red`
Resolution: `iris26173_graphite002_res`

Quasi & Stretch:
Sample: `iris26176_graphite002_red`
Resolution: `iris26173_graphite002_res`

Note that Stretch doesn't actually fit anything so the miniplot should only display the sample data.

Fixes #17262.

Release Notes have been updated

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by samueljackson92** [comment]
[Hello](https://trello.com/c/FamFkOsI/96-hello)

**Comment by martyngigg** [comment]
I've tested this a little bit. A few observations:

* we are accumulating a few of "plot" buttons on the interfaces and it's not clear at a glance what the difference is - can we think of a way to amalgamate these? @SpencerHowells any thoughts here?
* the "preview spectrum" number could be misleading. On Quasi if I click preview when index `0` is selected the label on the plot suggests it plots spectrum `3`.

**Comment by martyngigg** [comment]
This looks good now. The embedded plots still work as expected when switching files and the removal of the additional plot button reduces the confusion around these options.

:shipit: when the builds pass.

**Comment by martyngigg** [comment]
@mantidproject/gatekeepers The RHEL7 failure is just the current problem with the warnings.

It should be fine to merge.

**Pull request merged**
