### PR TITLE
Upgrade numpy, scipy, matplotlib, pip

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

As the title suggests...

**Report to:** [nobody]. 

**To test:**

Check both MantidPlot and MantidWorkbench compile and run.

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DTasev** [comment]
Windows fails because of [this numpy version check](https://github.com/mantidproject/mantid/blob/master/scripts/Inelastic/IndirectImport.py#L79)

**Comment by martyngigg** [comment]
I'm glad that check is there as those modules *might* need to be recompiled. I'll check.

**Comment by martyngigg** [comment]
I've checked and the C ABI for numpy has not changed since 1.6 so given that the f2py modules were compiled with 1.9 we don't need to recompiled them. I've made the check more robust so it will only fail in the future if the numpy ABI changes.

**Comment by martyngigg** [comment]
@DTasev Does this need to go in before your MatrixViewer changes?

**Comment by DTasev** [comment]
@martyngigg I believe so as #23987 needs MPL 2.2.3 for the Qt5 fix

**Comment by martyngigg** [comment]
I made a mistake with the numpy ABI version. I've just corrected it and force pushed my change. Hopefully the windows builds are good now.

**Comment by martyngigg** [comment]
I've just realised I need to update the `mslice` interface here too.

**Comment by martyngigg** [comment]
@DTasev This should be ready to test again now.

**Review by dtasev — APPROVED** [review]
Workbench and MantidPlot both build and run successfully without warnings/errors. All tests pass locally and on buildservers. LGTM

**Comment by martyngigg** [comment]
Thanks, @DTasev.

@mantidproject/gatekeepers Could we get this merged? It's holding up #23987.

**Pull request merged**
