### PR TITLE
Hb3a reduction script 12122

### LINKED ISSUE #12122: Create GUI-based script in Mantid to process HB3A data
This issue was originally [TRAC 11283](http://trac.mantidproject.org/mantid/ticket/11283)

Create a graphic user interface in Mantid for HB3A of HFIR.  The feature should include (1) downloading the data files (SPICE text file and XML file) from a server via http link, (2) Load the data into a TableWorkspace, a MatrixWorkspace for log information and a workspace group containing MatrixWorkspaces, each of which corresponds to one measurement (Pt) of a scan. (3) Provide some convenience for user to visualize the data on 2D anger camera. (4) Calculate UB matrix; (5) Refine UB matrix; (6) Calculate lattice parameters from refined UB matrix; (7) Integrate peaks;

### PR DESCRIPTION
**Pull request by wdzhou**
Fixes #12122.

### CODE REVIEW

**Comment by wdzhou** [comment]
This pull request depends on issue #13724 and #13614.

**Comment by wdzhou** [comment]
This PR is replaced by a new pull request #13910 (https://github.com/mantidproject/mantid/pull/13910).

**Comment by stuartcampbell** [comment]
@wdzhou Can this branch be deleted now then ?

**Comment by stuartcampbell** [comment]
@wdzhou Can this branch be deleted now then ?

**Pull request closed without merging**
