### PR TITLE
Workflow diagram added for SANSStitch Algorithm

### LINKED ISSUE #14870: Add workflow diagram to SANSStitch
The documentation for the ***SANSStitch*** algorithm should include a workflow diagram.

Examples of workflow diagrams:

* [DgsReduction](http://docs.mantidproject.org/nightly/algorithms/DgsReduction-v1.html#workflow)
* [LoadEventAndCompress](http://docs.mantidproject.org/nightly/algorithms/LoadEventAndCompress-v1.html#workflow)
* [IndirectILLReduction](http://docs.mantidproject.org/nightly/algorithms/IndirectILLReduction-v1.html#workflow)

### PR DESCRIPTION
**Pull request by OwenArnold**
Fixes #14870

Previously no workflow diagram for this DataProcessor algorithm.

**Tester** a.k.a Anton: Check the generated workflow diagram.

### CODE REVIEW

**Comment by LamarMoore** [comment]
Hi Owen, are you finished with this PR? Can I assign myself and merge?

**Comment by OwenArnold** [comment]
@LamarMoore. Many thanks for the offer, but It might be better if Anton takes a look at it as he's more familiar with that technique area. Thanks again for volunteering though.

**Comment by OwenArnold** [comment]
workflow

**Comment by picatess** [comment]
Looking at the posted diagram it appears that the merged can is not being taken into account.
See (here)[https://github.com/mantidproject/mantid/blob/master/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSStitch.py#L262:L273]

**Comment by picatess** [comment]
sansstitch-v1_wkflw

**Pull request merged**
