### PR TITLE
Algorithm to control remote jobs on the SCARF cluster (for tomography reconstruction - IMAT)

### PR DESCRIPTION
**Pull request by FedeMPouzols**
This Implements the new algorithm described in ticket [#10591](http://trac.mantidproject.org/mantid/ticket/10591).

Tester (only possible at ISIS):
- Note that this algorithm is not really meant to be used directly by users, but from (a) forthcoming GUI(s)
- Check that the documentation is understandable and consistent
- Code review
- Unit tests (there's a new one, SCARFTomoReconstructionTest) and (a very simple) doc test should pass
- To test that it works in the real world you need my help (username and password are required, without credentials you can only ping the server). This manual test should include logging in, submitting jobs, querying their status, canceling some, uploading/downloading a file, etc.
- There's more to do following on this (see details on trac, for example  ticket [#11064](http://trac.mantidproject.org/mantid/ticket/11064)). Feedback is very welcome.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
Dear and tireless Jenkins could you retest this please?

**Comment by FedeMPouzols** [comment]
Jenkins could you retest this please?

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please.

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please.

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please.

**Comment by FedeMPouzols** [comment]
Jenkins, could you retest this please?

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please?

**Comment by FedeMPouzols** [comment]
Good morning Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
Jenkins retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please...

**Comment by FedeMPouzols** [comment]
Jenkins, be goode and retest this please.

**Comment by AndreiSavici** [comment]
Unused variable shows up in cppcheck

**Pull request merged**
