### PR TITLE
Neatening up of release notes

### LINKED ISSUE #16301: Finish release notes
This issue is to polish and complete the release notes for R3.7.

This should not contain any code changes

### PR DESCRIPTION
**Pull request by NickDraper**
Neatening up of release notes, in addition many (although not all) sphinx warnings corrected

**To test:**

Look over the release notes for obvious errors

Fixes #16301.
## RELEASE NOTES

Circular reference

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
The changes appear to be for release documentation rather than release notes.

**Comment by NickDraper** [comment]
As I mentioned there are also quite a lot of sphinx warnings corrected

**Comment by KarlPalmen** [comment]
Given that it is only document changes, the RHEL failures may be overlooked. :shipit:

**Comment by KarlPalmen** [comment]
:smile: :shipit:

**Comment by AndreiSavici** [comment]
There are conflicts

**Comment by martyngigg** [comment]
Merging while builds are going to avoid further merge conflicts. The merge changeset will cause no problems on the servers.

**Pull request merged**
