### PR TITLE
Set font on non-ubuntu linux

### LINKED ISSUE #35681: Workbench editor font appear with strange spacing
In Mantid Workbench, the fonts in the editor appear with strange spacing. This appears in our nightly build of Mantid which is currently the release candidate for v6.7.

image

This is being observed on RHEL7 but unaware of other affected platforms.

A temporary fix is to switch the default font in Mantid Workbench to a monospaced font then restart.

Last PR mentioning fonts.
https://github.com/mantidproject/mantid/pull/33138

Also tracked in [EWM1754](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=1754)

**Describe the bug**

Odd, non-monospaced fonts appear in the editor

**To Reproduce**

Open Mantid Workbench, and open a new script with text in it. Look at the text for odd font spacings.

**Expected behavior**

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: RHEL 7
 - Mantid Version 6.7.0 release candidate

### PR DESCRIPTION
**Pull request by peterfpeterson**
On linuxes other than ubuntu, the fall through behavior for default font produced a non-monospace font on RHEL7. This fixes that by setting font options that are available on RHEL.

Additionally, the os inspection behavior was a repeat of functionality in `mantid.kernel.environment` and was changed to use that central version.

**To test:**

On the ornl analysis cluster, connect via thinlinc and bring up mantidworkbench. Before this patch, any file will have very strange spacing, after this one, everything should be spaced reasonably.

Fixes #35681. 

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by jhaigh0** [comment]
Just to avoid any conflicts, could you include the release note in a separate file as normal. So it would be in `docs/release/v6.7.0/Workbench/Bugfixes/35681.rst`

Currently its in the Framework/Algorithms sections which I don't think is quite right.

**Comment by jhaigh0** [comment]
> Just to avoid any conflicts, could you include the release note in a separate file as normal. So it would be in `docs/release/v6.7.0/Workbench/Bugfixes/35681.rst`
> 
> Currently its in the Framework/Algorithms sections which I don't think is quite right.

Thanks for moving the note to the right place 👍

**Comment by zjmorgan** [comment]
The problem has been fixed. Thanks for this:
image

**Review by zjmorgan — APPROVED** [review]
Fixes the problem and also places the burden on the environment package.

**Pull request merged**
