### PR TITLE
Overlay peaks when slicepoint doesn't change to fix crash when peak ws replaced and representations cleared

### LINKED ISSUE #31362: Changing overlaid peaks table causes crash in sliceviewer if peak already selected
### Expected behavior
When an overlaid peak table is changed the table would be re-loaded and all the peaks re-plotted  - this doesn't appear to be the case, or at least it's not happening correctly.

### Actual behavior

Having overlaid a peak table  **AND SELECTED/CLICKED ON A PEAK**   (otherwise no error) then re-integrating or renaming that table there is an out-of index crash if you then try to click on a peak in the sliceviewer table (note that post-rename the name at the top of the sliceviewer table is updated).
```
Traceback (most recent call last):
  File "/opt/mantidnightly/lib/mantidqt/widgets/sliceviewer/peaksviewer/view.py", line 171, in _on_row_clicked
    self._row_selected()
  File "/opt/mantidnightly/lib/mantidqt/widgets/sliceviewer/peaksviewer/view.py", line 177, in _row_selected
    self._presenter.notify(self._presenter.Event.PeakSelected)
  File "/opt/mantidnightly/lib/mantidqt/widgets/sliceviewer/peaksviewer/presenter.py", line 90, in notify
    self._peak_selected()
  File "/opt/mantidnightly/lib/mantidqt/widgets/sliceviewer/peaksviewer/presenter.py", line 125, in _peak_selected
    self._view.set_axes_limits(*self.model.viewlimits(selected_index), auto_transform=False)
  File "/opt/mantidnightly/lib/mantidqt/widgets/sliceviewer/peaksviewer/model.py", line 102, in viewlimits
    rep = self._representations[index]
IndexError: list index out of range
```

### Steps to reproduce the behavior
(1) Run this script
```
ws = CreateMDWorkspace(Dimensions='3', Extents='-5,5,-5,5,-5,5',
                       Names='Q_lab_x,Q_lab_y,Q_lab_z', Units='U,U,U',
                       Frames='QLab,QLab,QLab',
                       SplitInto='2', SplitThreshold='50')
expt_info = CreateSampleWorkspace()
ws.addExperimentInfo(expt_info)
# add peak
p = CreatePeaksWorkspace(InstrumentWorkspace='ws', NumberOfPeaks=0, OutputWorkspace='peaks')
pk = p.createPeak([1,1,1]) # axes aligned with viewing axes
p.addPeak(pk)
IntegratePeaksMD(InputWorkspace='ws', PeakRadius=0.6, BackgroundInnerRadius=0.6,
    BackgroundOuterRadius=1, PeaksWorkspace='peaks', OutputWorkspace='peaks_int', 
    Ellipsoid=False, UseOnePercentBackgroundCorrection=False)
```
(2) open sliceviewer overlay one of the peaks table
(3) Select a peak in the peaks table
(4) Rename the peak table 
(5) Click the peak again - this should cause a crash
(6) Can also try re-integrating by overlaying `peaks_int` and then repeating the above step but instead of step 4 call IntegratePEaksMD again in the script.

### PR DESCRIPTION
**Pull request by RichardWaiteSTFC**
**Description of work.**

When a peak is selected in the peaksviewer, the current code sets the new slicepoint and if the slicepoint changed then this would cause the peak shapes to be re-plotted. If the peaks workspace is replaced (e.g. because it was renamed or reintegrated) all the shapes are cleared, then selecting the same peak will cause a crash because the slicepoint hasn't changed and no shapes have been drawn (the axes limits are determined using a method of the shape representations plotted).

This fix always ensures the shapes are plotted when a peak is selected by overlaying the peaks workspace on replace and rename handles (the function that overlays peaks also appends the presenter - thanks for pointing this out @DannyHindson ).

Also added code to undo table selection when the peak shapes are cleared (which also happens when the table is altered) - I am not aware of this causing any bugs, but if the table is changed then the selection is outdated (it made sense to me to clear it).

**To test:**
(1) Run this code 
```
ws = CreateMDWorkspace(Dimensions='3', Extents='-5,5,-5,5,-5,5',
                       Names='Q_lab_x,Q_lab_y,Q_lab_z', Units='U,U,U',
                       Frames='QLab,QLab,QLab',
                       SplitInto='2', SplitThreshold='50')
expt_info = CreateSampleWorkspace()
ws.addExperimentInfo(expt_info)
# add peak
p = CreatePeaksWorkspace(InstrumentWorkspace='ws', NumberOfPeaks=0, OutputWorkspace='peaks')
pk = p.createPeak([1,1,1]) # axes aligned with viewing axes
p.addPeak(pk)
```
(2) Open sliceviewer, overlay `peaks` and select the peak in the table (it should change the slicepoint, axes and plot a cross)
(3) Rename the peaks workspace
`RenameWorkspace(InputWorkspace='peaks', OutputWorkspace='peaks2')`
(4) Select the peak again - there should be no crash!

Fixes #31362 

*This does not require release notes* because **small bug not reported by user**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DannyHindson — COMMENTED** [review]
The fix works fine but I'm wondering if tackling this at the point where the user tries to select a peak isn't quite the right place to fix it - it feels a bit late.

There is some code in the functions replace_handle, delete_handle, clear_handle and rename_handle at the bottom of the presenter unit which should manage the workspace actions. It seems better to make sure these fix everything up at the point the workspace is renamed. This way any new code written in future that doesn't go through _peak_selected will be guaranteed to work following a workspace rename.

Replacing the calls to append_peakworkspace in these xxx_handle methods with overlay_workspaces might do it - what do you think?

**Comment by RichardWaiteSTFC** [comment]
> The fix works fine but I'm wondering if tackling this at the point where the user tries to select a peak isn't quite the right place to fix it - it feels a bit late.
> 
> There is some code in the functions replace_handle, delete_handle, clear_handle and rename_handle at the bottom of the presenter unit which should manage the workspace actions. It seems better to make sure these fix everything up at the point the workspace is renamed. This way any new code written in future that doesn't go through _peak_selected will be guaranteed to work following a workspace rename.
> 
> Replacing the calls to append_peakworkspace in these xxx_handle methods with overlay_workspaces might do it - what do you think?

Yeh I was a bit wary of changing the handles as it was more likely to have unintended consequences (model and view stuff getting out of sync etc.) - whereas this fix just re-plots the representations (which I thought was fairly harmless). The relevant handle is the `replace_handle`, it removes the table and then re-adds it. When the table is removed the representations are cleared, one option is to not do this on replace, but then what you then show on the plot is wrong. Another option is to not remove the table, but just refresh the data in the view, I can try this if you like?

**Comment by RichardWaiteSTFC** [comment]
Ah I think it would perhaps be better to overlay_peaks() after appending in the replace_handle itself - is this what you were suggesting? I think keeping the removing and appending is safer than trying to recreate all the signals and events manually but without clearing the representations.

**Comment by DannyHindson** [comment]
I meant do something like the following. overlay_peaksworkspaces calls append_peaksworkspace so it's not a big change. For me replace_handle and rename_handle both get called when a workspace is renamed so I updated both.

There are probably some other variations of this where you keep the call to append_workspaces in place and then do something extra like "self.notify(PeaksViewerPresenter.Event.OverlayPeaks)"

```
    def replace_handle(self, ws_name, _):
        if ws_name in self.workspace_names():
            self.remove_peaksworkspace(ws_name)
            self.overlay_peaksworkspaces(self.workspace_names() + [ws_name])
            #self.append_peaksworkspace(ws_name)

    def delete_handle(self, ws_name):
        if ws_name in self.workspace_names():
            self.remove_peaksworkspace(ws_name)

    def clear_handle(self):
        # This is likely handled at a higher level anyway, because SliceViewer closes given a clear all on the ADS.
        for ws_name in self.workspace_names():
            self.remove_peaksworkspace(ws_name)

    def rename_handle(self, ws_name, new_name):
        if ws_name in self.workspace_names():
            self.remove_peaksworkspace(ws_name)
            self.overlay_peaksworkspaces(self.workspace_names() + [new_name])
            #self.append_peaksworkspace(new_name)

**Comment by RichardWaiteSTFC** [comment]
> ariations of this where you keep the call to append_workspaces in place and then do something extra like "self.notify(PeaksViewerPresenter.Event.OverlayPeaks)"

I think that's close to what I'm changing it to 
```
    def replace_handle(self, ws_name, _):
        if ws_name in self.workspace_names():
            self.remove_peaksworkspace(ws_name)
            self.append_peaksworkspace(ws_name)
            self.overlay_peaksworkspaces(ws_name)

    def delete_handle(self, ws_name):
        if ws_name in self.workspace_names():
            self.remove_peaksworkspace(ws_name)

    def clear_handle(self):
        # This is likely handled at a higher level anyway, because SliceViewer closes given a clear all on the ADS.
        for ws_name in self.workspace_names():
            self.remove_peaksworkspace(ws_name)

    def rename_handle(self, ws_name, new_name):
        if ws_name in self.workspace_names():
            self.remove_peaksworkspace(ws_name)
            self.append_peaksworkspace(new_name)
            self.overlay_peaksworkspaces(new_name)
```
You have to append the workspace though for the new workspace otherwise you don't create a new PeaksViewerPresenter and ADS observer for that workspace

**Comment by RichardWaiteSTFC** [comment]
@DannyHindson pointed out the function that overlays the peaks workspace also appends the workspace, so a better fix was to replace the call to append with overlay in the replace and rename handles. This has now been implemented.

**Review by DannyHindson — CHANGES_REQUESTED** [review]
Thanks for adjusting this on Friday. Please could you add a release note to this? I saw your comment about this not being raised by a user but I think it's still helpful to have it in the release notes eg if we end up breaking something it's helpful to have a line describing the fact something's changed

**Review by DannyHindson — APPROVED** [review]
Retested and all looks good thanks

**Pull request merged**
