### PR TITLE
Muon Sample log copying

### LINKED ISSUE #21885: sample logs and algorithms
The phaseQuad algorithm does not save the sample log to the output. This should be changed. 

MuonMaxent should also save the sample log to the output(s). See the version from the script repository for recent  changes.

### PR DESCRIPTION
**Pull request by ElliotAOram**
Ensure that the sample logs are copied from the MuonPhaseQuad input to the output.

**To test:**

* Load some data into muon analysis (MUSR 68389)
* Open the frequency domain anlysis GUI
* Change the workspace to phaseQuad
* Press the calculate button
* In the grouped workspace a PhaseQuad;FTT output has been added.
* Ensure this workspace has the same sample logs as the `MuonAnalysis` workspace.

Fixes #21885 

**Release Notes** 
*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by ElliotAOram** [comment]
@AnthonyLim23 @NickDraper 
After investigating this further, this is caused by the reference file not having the instrument data - which it ideally should. Using a parent workspace on creation copies the instrument as well as the logs - hence the mismatch occuring.
The system test output also references a data-mismatch. This is misleading and is caused by this check in the system test:
```
# FFT of offset should have different phase
FFT(offset, Real=0, Imaginary=1, AcceptXRoundingErrors=True, AutoShift=True, 
    OutputWorkspace='OffsetFFTResults')
(result, _messages) = CompareWorkspaces('MuonFFTResults', 'OffsetFFTResults')
self.assertEqual(result, False)
```
I recommend we update the system test to increase the tolerance to actually ensure we catch errors! In addition, the data matches for all points (within a 1e-8, with the exception of the new 0 frequency reduced peak - a change that was added that slipped through the system tests a while back due to tolerance) tolerance so I suggest we update the reference file to include the instrument data and the new value at 0 Frequency.

**Comment by NickDraper** [comment]
This works, although I ran into fit errors with the suggested data set

**Review by NickDraper — APPROVED** [review]

**Comment by NickDraper** [comment]
Good to merge if the builds pass

**Comment by martyngigg** [comment]
I realised after merging that this was marked for `3.12` but the target was set to `master`. I've cherry picked the commits on to the release branch.

**Comment by ElliotAOram** [comment]
Thanks @martyngigg , that was an oversight on my part!

**Pull request merged**
