### PR TITLE
Resolve issues with WAND^2 workflow

### PR DESCRIPTION
**Pull request by zjmorgan**
### Description of work

1. LoadWANDSCD changes EPICS UB: users don't prefer this
2. ConvertWANDSCD: rework confusing code.

#### Summary of work

WAND^2 applies the goniometer tilts to the UB matrix.

image

*There is no associated issue.*

### To test:

Run all system tests and unit tests.

Simple test:
```python
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

IPTS = 7776
runs = range(26640, 27944)[0::10]
### -------------------- ###

filename = '/HFIR/HB2C/IPTS-{}/nexus/HB2C_{}.nxs.h5'
filenames = ','.join([filename.format(IPTS, run) for run in runs])

LoadWANDSCD(Filename=filenames,
            Grouping='4x4',
            OutputWorkspace='data')
            
LoadWANDSCD(IPTS=7776, RunNumbers=26509, OutputWorkspace='norm',Grouping='4x4') # Vanadium
ConvertWANDSCDtoQ(InputWorkspace='data',
                  NormalisationWorkspace='norm',
                  OutputWorkspace='Q',
                  BinningDim1='-1,1,1')

IntegrateMDHistoWorkspace(InputWorkspace='Q', P1Bin='2.08522,2.30691', P2Bin='-1,1', P3Bin='-0.491608,0,5.61035', OutputWorkspace='Q_roi')
```

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by sf1919** [comment]
@zjmorgan please ignore the 200+ test failures on OSX. Problem with a machine rather than your PR. When you push a fix for the failing test on Linux it will run on a different machine.

**Review by rosswhitfield — COMMENTED** [review]
This change has caused `ConvertWANDSCDtoQ` to be significantly slower.

I used your script but included every data file and repeated `ConvertWANDSCDtoQ` to make sure I get consistent results.

Comparing to the 6.10 release on analysis-node01, I see `ConvertWANDSCDtoQ` going from ~6 seconds to ~17 seconds. And on my laptop it goes from ~7 seconds to ~25 seconds.

Do you see the same thing?

```python
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

IPTS = 7776
runs = range(26640, 27944)
### -------------------- ###

filename = '/HFIR/HB2C/IPTS-{}/nexus/HB2C_{}.nxs.h5'
filenames = ','.join([filename.format(IPTS, run) for run in runs])

LoadWANDSCD(Filename=filenames,
            Grouping='4x4',
            OutputWorkspace='data')
            
LoadWANDSCD(IPTS=7776, RunNumbers=26509, OutputWorkspace='norm',Grouping='4x4') # Vanadium
ConvertWANDSCDtoQ(InputWorkspace='data',
                  NormalisationWorkspace='norm',
                  OutputWorkspace='Q',
                  BinningDim1='-1,1,1')
ConvertWANDSCDtoQ(InputWorkspace='data',
                  NormalisationWorkspace='norm',
                  OutputWorkspace='Q',
                  BinningDim1='-1,1,1')
ConvertWANDSCDtoQ(InputWorkspace='data',
                  NormalisationWorkspace='norm',
                  OutputWorkspace='Q',
                  BinningDim1='-1,1,1')
```

**Comment by zjmorgan** [comment]
> Do you see the same thing?
Thank you for pointing this out. I worked out a slightly faster method at 4 seconds on Andrei's old HP box.

**Comment by rosswhitfield** [comment]
> > Do you see the same thing?
> Thank you for pointing this out. I worked out a slightly faster method at 4 seconds on Andrei's old HP box.

I'm really not seeing any improvement with your most recent changes. Did you do a before and after test on the same computer?

**Comment by zjmorgan** [comment]
I made an attempt merging to improve the speed and essentially consolidate toward the original implementation

**Comment by zjmorgan** [comment]
Provides the same I/sig whether using normalization or not.

image

**Comment by zjmorgan** [comment]
Old method gives the same I/sig ratio, but not correct scale:
image

**Review by rosswhitfield — APPROVED** [review]

**Pull request merged**
