### PR TITLE
EQSANSLoad fix coverity scan control flow issue

### LINKED ISSUE #18727: EQSANSLoad fix coverity scan control flow issue
The Coverity Scan of this algorithm found a control flow defect within. This is a quick fix for this issue.

### PR DESCRIPTION
**Pull request by PranavBahuguna**
As described in the issue, this fixes a control flow issue discovered by Coverity.

Fixes #18727.

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AndreiSavici** [comment]
Make sure the branch you want this to merge into is `release-v3.9` and not `master`

**Comment by martyngigg** [comment]
@PranavBahuguna It looks like this branch has been started from  `master` rather than `release-v3.9`. Please take a look at http://www.mantidproject.org/Git_Workflow#New_branches for how to start new branches based off the release branch.

To fix this please run:

```
To fix up this branch you can run:

git fetch -p
git checkout 18727_EQSANSLoad_coverity_scan_fix
git rebase --onto origin/release-v3.9 origin/master 18727_EQSANSLoad_coverity_scan_fix
git push -f origin ￼18727_EQSANSLoad_coverity_scan_fix
```

**Comment by martyngigg** [comment]
@PranavBahuguna There's not need to close the PR. If you run the above fix the PR will update automatically

**Comment by PranavBahuguna** [comment]
It closed automatically when I ran the above though.

**Comment by martyngigg** [comment]
@PranavBahuguna I think I understand what has happened now.

The problem was never introduced into the `release-v3.9` branch in the first place. It came in via [b401a737c04f2085e384ff34f22781180e66a48d](https://github.com/mantidproject/mantid/commit/b401a737c04f2085e384ff34f22781180e66a48d) with some other refactorings and so was on `master` and coverity picked it up.

When we run the above command rebased on to the release branch `git` saw that the change was unnecessary so didn't commit anything and left this branch with nothing on it and the number of changes=0 so it closed the PR. So actually you were correct with the base branch in the first place but the milestone should have been set to `3.10`.

I'll put this all back in the right state for you now. If you could just update the milestone to `3.10`.

**Comment by PranavBahuguna** [comment]
Very well, changing it now.

**Comment by martyngigg** [comment]
@PranavBahuguna GitHub has got confused with the sate of this now so I'll think we should just abandon this PR and open a fresh one.

**Pull request closed without merging**
