### PR TITLE
Abins: Correct setting numerical zero for b_tensors.

### PR DESCRIPTION
**Pull request by dymkowsk**
1) Fix bug with setting up b_tensors. 

**To test:**

Code review

No issue number.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by samueljackson92** [comment]
@martyngigg Might possibly want to take a look at this for the patch release.

**Comment by martyngigg** [comment]
@dymkowsk Thanks for the fixes.

There has been a system test failure for [AbinsTest.AbinsCASTEPTestScale](http://builds.mantidproject.org/job/pull_requests-rhel7/12233/)

Could you also include a note in the release notes for indirect?

**Comment by dymkowsk** [comment]
@martyngigg, @samueljackson92 I just pushed changes you requested. Let me know if more modifications are needed.

**Comment by martyngigg** [comment]
@dymkowsk Thanks. Can you remove the note in `docs/source/release/v3.9.1.rst` and just leave the one in `3.10.0`. Sorry for not being clear.

If I pull this change into a patch then I will add that note myself. Removing that change will also remove the merge conflict.

**Comment by dymkowsk** [comment]
@martyngigg I updated documentation as you wanted. I saw that one system test is still crushing. I changed  the way reference data is compared (now .nxs vs workspace as for other tests). I can't reproduce this crushing on my Ubuntu.

**Comment by martyngigg** [comment]
@dymkowsk We have a test on Ubuntu that keeps sporadically failing even if you don't touch those files. We have not yet tracked these problems down however they are certainly not to do with these changes.

Code changes are acceptable and account for B-tensor-elements that are too small to be useful.

:shipit:

**Comment by martyngigg** [comment]
This has now been merged to master via merging the release branch so we may as well merge this now.

**Pull request merged**
