### PR TITLE
Set bin errors in CreateSimulationWorkspace

### PR DESCRIPTION
**Pull request by ckendrick**
**Description of work.**

Sets the bin errors in `CreateSimulationWorkspace` to prevent an issue where workspace bin errors would be zero when used later in `IntegrateEllipsoids`. An option was added to `CreateSimulationWorkspace` to revert to the original behavior of having zero errors.

**To test:**

Unit tests for `CreateSimulationWorkspace` should pass.

Version into  `ornl-next`: #33148 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by zjmorgan** [comment]
This resolves issue. See the following test script:

```python
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

from mantid import config
config['Q.convention'] = "Inelastic"
                       
ws = CreateSimulationWorkspace(Instrument='TOPAZ',
                               BinParams='1,100,10000',
                               UnitX='TOF')
                               
SetGoniometer(Workspace=ws, Axis0='30,0,1,0,1')      

# add peak
pws = CreatePeaksWorkspace(InstrumentWorkspace=ws, 
                           NumberOfPeaks=0, 
                           OutputWorkspace='peaks')
                           
SetUB('peaks', 2*np.pi, 2*np.pi, 2*np.pi, 90, 90, 90)

p = pws.createPeak([5,1,6]) 
pws.addPeak(p)

p = pws.createPeak([4,2,1]) 
pws.addPeak(p)

p = pws.createPeak([2,3,1]) 
pws.addPeak(p)

IndexPeaks(pws, Tolerance=1)

PredictSatellitePeaks(pws, SatellitePeaks=pws, ModVector1='0.15,0,0', ModVector2='0,0.15,0', CrossTerms=False, MaxOrder=1) 

# integrate              
IntegrateEllipsoids(InputWorkspace=ws, 
                    PeaksWorkspace=pws, 
                    RegionRadius=0.14, 
                    SpecifySize=True,
                    PeakSize=0.07, 
                    BackgroundInnerSize=0.09,
                    BackgroundOuterSize=0.11,
                    SatellitePeakSize=0.05, 
                    SatelliteBackgroundInnerSize=0.08,
                    SatelliteBackgroundOuterSize=0.10,
                    OutputWorkspace=pws)
                    
IndexPeaks('peaks', Tolerance=1, ToleranceForSatellite=0, RoundHKLs=True, ModVector1='0.15,0,0', ModVector2='0,0.15,0', CrossTerms=False, MaxOrder=1)

IntegrateEllipsoids(InputWorkspace=ws, 
                    PeaksWorkspace='peaks', 
                    RegionRadius=0.14, 
                    SpecifySize=True,
                    PeakSize=0.07, 
                    BackgroundInnerSize=0.09,
                    BackgroundOuterSize=0.11,
                    SatellitePeakSize=0.05, 
                    SatelliteBackgroundInnerSize=0.08,
                    SatelliteBackgroundOuterSize=0.10,
                    OutputWorkspace='unindexed')
```

**Review by zjmorgan — CHANGES_REQUESTED** [review]
Just need the builds to pass. Then I will be happy to approve.

**Review by zjmorgan — DISMISSED** [review]

**Review by sf1919 — CHANGES_REQUESTED** [review]
Please can you change the release notes? This appears to be being merged into main so will be in v6.4. In that case the release note needs to be moved to 6.4 skeleton release notes. These were created last week and you may need to rebase to get them.

If this is intended for v6.3 you will need to change the branch to release-next and move the release notes into a separate file. For more information about changes to release notes during this release please see the Announcement channel on Slack or the message on the Mantid Forum.

**Review by sf1919 — APPROVED** [review]
Many thanks for changing the release note.

**Pull request merged**
