### PR TITLE
Simple loader for DNS ascii data format

### PR DESCRIPTION
**Pull request by mganeva**
Simple loader for DNS ascii data format. Loader supports only the old DNS configuration (1 detector bank with 24 single-pixel detectors). Loader creates the workspace with data and rotates the detector bank to the position specified in the data file.

To test and for the unittest, please, ask me to email you the data file (3kb), I cannot upload it.

I have one issue with phi angles: in the IDF I specify p=0.0, but in Mantid I see phi=180 degree.

### CODE REVIEW

**Comment by rosswhitfield** [comment]
Jenkins, test this please

**Comment by rosswhitfield** [comment]
Jenkins, retest this please

**Comment by rosswhitfield** [comment]
Have a look at [RefLReduction.py](https://github.com/mantidproject/mantid/blob/master/Code/Mantid/Framework/PythonInterface/plugins/algorithms/RefLReduction.py#L8-10) import of sfCalculator for an example of how to import something from the current file path in Linux.

**Comment by rosswhitfield** [comment]
Jenkins, test this please

**Comment by rosswhitfield** [comment]
Jenkins, retest this please

**Comment by jcns** [comment]
Thanks, I hope, I've fixed it.

**Comment by rosswhitfield** [comment]
Jenkins, retest this please

**Comment by AndreiSavici** [comment]
The phi=180 occurs because you rotate the detectors around y axis with a negative value. If you look at the detector positions, these are not theta=-8.54 and phi=0 but theta=+8.54 and phi=180

**Comment by AndreiSavici** [comment]
The incident energy is in eV. Mantid uses mostly meV.

**Comment by jcns** [comment]
How I can get negative theta angles and phi=0? (in IDF theta angles are also negative)
I will correct the incident energy on Monday.

**Comment by AndreiSavici** [comment]
You cannot get negative theta angles. Theta is always between 0 and 180. So in a horizontal plane, all angles to the left are positive theta, 0 phi, and all angles to the right are positive theta and phi=180. That's just the definition of polar angles. As for Ei, I don't know how to set the units in python.

**Comment by AndreiSavici** [comment]
Also, I think the incident energy is written in your file, you don't need to calculate it

**Pull request merged**
