### PR TITLE
Fixed instrument view title upon renaming workspace

### LINKED ISSUE #36733: Instrument view title doesn't update when workspace is renamed
**Describe the bug**
Instrument view title doesn't update when workspace is renamed

**To Reproduce**
Open the instrument view and rename the associated workspace.

**Expected behavior**
Title of window should change, as with slice viewer.

### PR DESCRIPTION
**Pull request by GuiMacielPereira**
### Description of work
Fixed bug where renaming a workspace with the instrument view opened did not update the title of the InstrumentView window.

#### Summary of work
- Fixed title of window when InstrumentView is initialised
- Fixed renaming bug
- Removed unused call to resize() of window

Fixes #36733 .

#### Further detail of work

The instrument view widget is written in C++ but the window is controlled by a Python wrapper. The title upon initialisation is set on the python wrapper side. The rename is handled on the C++ side by including a call to `nativeParentWidget()`. Finally, I removed a call to resize() on the C++ since it was already being ignored.

### To test:
- Load a workspace
- Open InstrumentView
- Check title is of form `Instrument - <INSTRUMENTNAME>`
- Rename workspace
- Check window title is correctly updated

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by GuiMacielPereira** [comment]
If the size of the window when InstrumentView is opened is too small, it's easy to fix by calling resize() on the Python wrapper side. @jhaigh0 What do you think?

**Comment by jhaigh0** [comment]
did you try changing it to `nativeParaentWidget()->resize(...)` to see if it makes a huge difference?

**Review by jhaigh0 — CHANGES_REQUESTED** [review]
Works well, just needs a release note

**Comment by GuiMacielPereira** [comment]
> did you try changing it to `nativeParaentWidget()->resize(...)` to see if it makes a huge difference?

Unfortunately when that is used in the constructor mantid crashes with no error messages

**Review by jhaigh0 — APPROVED** [review]

**Pull request merged**
