### PR TITLE
Indirect Data Analysis IqtFitMultiple - Remove temporary workspace

### LINKED ISSUE #15342: ProcessIndirectFitParameters producing __TMP workspace
ProcessIndirectFitParameters is producing a temporary workspace upon execution. This was noticed in `IqtFitMultple` but not in other places it is in use.

### PR DESCRIPTION
**Pull request by ElliotAOram**
IqtFitMultiple no longer produces an unwanted temporary workspace when it is run. _This was originally thought to be caused by ProcessIndirectFitParameters_ but is actually caused by IqtFitMultiple.

**To test:**
- Turn on show invisible workspaces (View > Preferences > Mantid > options > `Show Invisible Workspaces`)
- Run the following script:

```
#Load in iqt data
input_ws = Load(Filename='iris26176_graphite002_iqt.nxs')
function = r'name=LinearBackground,A0=0.027668,A1=0,ties=(A1=0);name=UserFunction,Formula=Intensity*exp(-(x/Tau)^Beta),Intensity=0.972332,Tau=0.0247558,Beta=1;ties=(f1.Intensity=1-f0.A0)'

#run IqtFitMultiple
result, params, fit_group = IqtFitMultiple(InputWorkspace=input_ws, Function=function, FitType='1S_s', StartX=0, EndX=0.2, SpecMin=0, SpecMax=16)
```
- Ensure no `__TMP` workspaces are created in the in the ADS
- 5 workspaces should be in the ADS:

image
- input_ws is the loaded data
- The additional 4 are generated by the algorithm and are expected

Fixes #15342

[RELEASE NOTES](https://github.com/mantidproject/mantid/blob/7b5fd0c57af694ea40af4ef5abf5a1581b3d0236/docs/source/release/v3.8.0/indirect_inelastic.rst#bugfixes)

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
I see some temporary workspaces when running the script. After the script has been run, 5 workspaces remain. None are invisible (begin with '_').

**Comment by ElliotAOram** [comment]
By temporary workspaces I am referring to the automatically generated workspaces created by Mantid if a workspace is unnamed and added to the ADS (e.g. `__TMP` followed by a memory address). The 5 workspaces you are seeing are most likely expected. I'll update the PR to be more clear. Apologies

**Comment by KarlPalmen** [comment]
Please do so. I need to know which workspaces can remain after the script and which workspaces can appear through the course of the script's execution, but must not remain afterwards.

**Comment by KarlPalmen** [comment]
When running the script, no workspaces with names beginning with ``__TMP`` appeared and the five workspaces after execution are as shown in the test instructions.

**Pull request merged**
