### PR TITLE
D2B load single point scans

### LINKED ISSUE #25981: LoadILLDiffraction to load single count (no scan) files
The nexus files for single-shot count measurements are slightly different from the scans on D2B.

LoadILLDiffraction should host some logic to be able to load both as scans; a single shot can be processed just as a scan with one single time index.

### PR DESCRIPTION
**Pull request by gvardany**
**Description of work.**
Fixes `LoadILLDiffraction` to load also scans with single time index.

**Report to:** [ILL/G. Cuello]

**To test:**
```
ws = Load(Filename='ILL/D2B/543614.nxs')
```
Should load with no error, the data file is in unit tests data.

Fixes #25981 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
Last build is just a conflict resolution in the release notes, the previous build passed just fine.

**Review by NickDraper — APPROVED** [review]
Data Loads fine, code ok, unit test added, release notes updated.

The data looks like this! Time bin plot

image

**Comment by NickDraper** [comment]
For the gatekeeper, no need to wait for these builds to complete, the last change was just conflict resolution on the release notes.

**Comment by martyngigg** [comment]
It was requested that it be reported to ILL/G. Cuello when merged.

**Pull request merged**
