### PR TITLE
CrystalField Multi-spectrum resolution model segfault

### LINKED ISSUE #22142: Crystal field fitting segfaults Mantid
Trying to do a simultaneous fit of multiple spectra with the `CrystalField` module with a `ResolutionModel` defined will segfault Mantid.

### Expected behavior

That the fit runs.

### Actual behavior

Segfault

### Steps to reproduce the behavior

```
from CrystalField import CrystalField, CrystalFieldFit
import numpy as np
ws1 = CreateWorkspace(np.linspace(0,10,100), np.linspace(0,10,100))
ws2 = CreateWorkspace(np.linspace(0,10,100), np.linspace(0,10,100))
cf = CrystalField('Ce', 'C2', Temperature=[100,200], FWHM=0.1, B20=0.1)
cf.ResolutionModel = [ ( [-10, 0, 10], [1, 1, 1] ), ( [-10, 0, 10], [2, 2, 2] ) ]
fit = CrystalFieldFit(Model=cf, InputWorkspace=[ws1, ws2])
fit.fit()
```

### Platforms affected

All

### PR DESCRIPTION
**Pull request by mducle**
Fixes a bug in the `CrystalFieldMultiSpectrum` function which can cause a segmentation fault when using a resolution model. The parameter `Temperatures` which define the number of spectra (workspaces) to fit has to be specified before any of the parameters `PhysicalProperties`, `FWHM` or `FWHMX`/`FWHMY` which depend on the number of spectra. Previously checks were made for `PhysicalProperties` and `FWHM` but an error thrown if they were defined before `Temperature`. No such check was made for `FWHMX` and `FWHMY` which are used to specify a resolution model. Thus when the function is used with a resolution model, sometimes a segmentation fault can occur if the either of these parameters are specified before `Temperature` and the code tries to access an empty vector. The code now throws an exception if `FWHMX` or `FWHMY` is specified before `Temperature`.

The PR also fixes the Python code which caused `FWHMX` / `FWHMY` to be given before `Temperature`, and extends the Python code so that users can specify a list of `ResolutionModel` objects rather than a list of tuples of `x`- and `y`-values for the resolution function.

**To test:**

Run the following

```
from CrystalField import CrystalField, CrystalFieldFit
import numpy as np
ws1 = CreateWorkspace(np.linspace(0,10,100), np.linspace(0,10,100))
ws2 = CreateWorkspace(np.linspace(0,10,100), np.linspace(0,10,100))
cf = CrystalField('Ce', 'C2', Temperature=[100,200], FWHM=0.1, B20=0.1)
cf.ResolutionModel = [ ( [-10, 0, 10], [1, 1, 1] ), ( [-10, 0, 10], [2, 2, 2] ) ]
fit = CrystalFieldFit(Model=cf, InputWorkspace=[ws1, ws2])
fit.fit()
```

And check that the segmentation fault does not occur.

Fixes #22142. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by mantid-roman — CHANGES_REQUESTED** [review]
There is no crash any more. But could you add a C++ unit test for this case please?

**Comment by mantid-roman** [comment]
I think a patch candidate needs to be branched from `release-v3.12`

**Comment by mducle** [comment]
@mantid-roman The code itself is branched from `release-v3.12` but basing it off `release-v3.12` on github causes the Ubuntu builds to fail the reflectometry unit tests because some instrument definition files have changed between the release and `master` and for some reason the Ubuntu builds download these files... Martyn told me that some one would manually `cherry-pick` the commits to put into the patch and that it was ok to merge to `master` on github...

**Review by mantid-roman — APPROVED** [review]

**Comment by martyngigg** [comment]
@mducle Now that most of the builds are through let's leave it as it is and the release manager can just cherry-pick them off to `release-v3.12`.

**Comment by martyngigg** [comment]
They'll sort out the release notes too.

**Comment by martyngigg** [comment]
Build failures are unrelated

**Pull request merged**
