### PR TITLE
Bug superplot tight layout

### PR DESCRIPTION
**Pull request by gui-co**
**Description of work.**

This is a continuation of #34885.

I realized that the fix provided by #34885 only applies to plot updates. But the bug is still present when the plot is freshly opened on data with a long name.

Because the issue was related to the plot legend, I took advantage of this PR to set the legend visibility according to the plot context menu option.

**To test:**

To reproduce the issue:
* create a workspace with a long name
```python
from mantid.simpleapi import CreateSampleWorkspace
CreateSampleWorkspace(OutputWorkspace="verrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrryLonnnnnnnnnnnnnnnnnnnnnnnnnnngNaaaaaaaaaaaaaaaaaaaaaaaame")
```
* and open the superplot widget on it (right click -> plot -> superplot)
* the plot area should be displayed properly

And check that the legend visibility respects the checkbox state in the right click menu of the plot.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by darominski — CHANGES_REQUESTED** [review]
Thank you for fixing the issue with long workspace names. The proposed solution works and now the log names are handled in a much nicer way, and cause no issue to the layout. I have a couple of comments about the current functionality of which I added one in the relevant place in the code and two are in this comment:  

1. At workbench startup, I now always get `plotSpectrum not available` message at the warning log level. This is not the case for commits before your changes. Could you have a look at that?
2. Redrawing of the plot seems to not be catching exceptions in the same way as the spectrum plot does. I stumbled upon this while testing the size of the text buffer, so if you create a workspace the following way:
```
from mantid.simpleapi import CreateSampleWorkspace
CreateSampleWorkspace(OutputWorkspace="a"*1927)
```
it will create an overflow to the title drawing buffer. If you plot such created workspace with plot spectrum, a sanitized error message appears, while if you superplot it, the same error is visible but with the entire traceback as well. Do you think it would be possible to wrap the redrawing in a try-except to be consistent with plot spectrum behaviour?

**Comment by gui-co** [comment]
The warning message "plotSpectrum not available" disappeared with a merge with main.

I tried to solve the problem with the different exceptions/error messages. I inhibited the exceptions in the superplot layer and let the mantid plot layer dealing with them. The examples you provided should report proper error now.

**Review by darominski — DISMISSED** [review]
Thank you for the changes, the errors are now caught and clearly communicated to the user.

**Comment by gui-co** [comment]
One test was failing due to the different call to matplotlib API (`draw_idle()` -> `draw()`)

**Review by darominski — APPROVED** [review]
Yes, missed that one! Re-approved.

**Pull request merged**
