### PR TITLE
find_path for OPENCASCADE_LIBRARY_DIR

### PR DESCRIPTION
**Pull request by chatcannon**
For when the OpenCascade libraries are not in /opt/OpenCascade/lib64

### CODE REVIEW

**Comment by martyngigg** [comment]
test this please

**Comment by peterfpeterson** [comment]
I prefer the `option(NO_OPENCASCADE ...` better. Better still is if you would switch the logic so the option is `ENABLE_OPENCASCADE_3D`

**Comment by FedeMPouzols** [comment]
I just merged a pull request (#263) about fixing the cmake check for Open Cascade (in FindOpenCascade.cmake). Then I saw that this one has been around for a few days.

What is the status of this PR?

**Comment by peterfpeterson** [comment]
It would be nice if @chatcannon would make the suggested changes and before it is merged in.

**Comment by peterfpeterson** [comment]
This is being merged in as #406.

**Pull request closed without merging**
