### PR TITLE
Ensure the correct generator is used for eigen & xmlrunner

### PR DESCRIPTION
**Pull request by martyngigg**
Description of work.

Passes the `-G ${CMAKE_GENERATOR}` argument to the `cmake` command that processes the external project configure commands for eigen and xmlrunner.

This is required on Windows where Visual Studio 2015 & 2017 are installed along with more cmake > 3.7. Without these changes the eigen & xmlrunner steps use the 2017 generator regardless of the generator chosen by the caller.

**To test:**

Code review.

*No issue*

**Release Notes** 

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by ianbush** [comment]
Tested on Ubuntu 14.04 and it looks good to me. When this is merged you might want to warn people that clearing out the build directory is a good idea - I had an error when just checking out and building as `Eigen` was building with `Make` and Mantid with `ninja`.

**Comment by martyngigg** [comment]
It looks like that was what the build error on Windows was too.

**Comment by martyngigg** [comment]
We're going to have to be careful when merging this as I think we'll need to clean the build servers out too.

**Comment by martyngigg** [comment]
I think I've figured out a check to put in the buildscript to avoid having to manually clean stuff.

**Comment by martyngigg** [comment]
The builds seem to pass now so I think we're good. We'll still need to tell developers to clean their builds though. Maybe I should have put that check in the cmake directly?

**Comment by ianbush** [comment]
I am not sure I understand the last commit - for me it seems like I still need clean the build directory out. Although you do say developers still need to clean their builds out?

**Review by peterfpeterson — APPROVED** [review]
The `cmake` changes are reasonable. I'm not sure that your "temporary" fix for build servers will help builds that happen *after* this one.

**Comment by martyngigg** [comment]
@ianbush The `buildscript` changes check whether the generators match and clean the external projects if they don't. Developers will still need to do that manually.

The `buildscript` changes will get it through the incremental builds too but nothing after that.

**Review by ianbush — APPROVED** [review]
Thanks for the clarification, looks good to me.

**Pull request merged**
