### PR TITLE
SpecularReflectionCalculateTheta now output TwoTheta 

### LINKED ISSUE #14757: SpecularReflectionCalculateTheta returns Theta instead of TwoTheta
After working with the ReflectometryReductionOne algorithm we found that if we have a basic instrument set up with:

`source_position` = `[0,0,-1]`
`sample_position` = `[0,0,0]`
`detector_position` = `[0,1,1]`

identitytriangle

It will make an indentity triangle and Theta (right hand side) should be 45 degrees, meaning that TwoTheta (returned from SpecfularReflectionCalculateTheta) should be 90 degrees. However, SpecularReflectionCalculateTheta was returning 45 degrees as TwoTheta. 

It should be a simple fix, just multiplying the output by a factor of 2 and adjusting any unit tests.

### PR DESCRIPTION
**Pull request by MattKing06**
Changes involved multiplying the output of SpecularReflectionCalculateTheta by a factor of 2 before it is set as the output property.

**To Test**:
This might be difficult to test, as we can't add detectors into an instrument using python and I don't think there are any instruments that have the setup displayed in the issue description.
- Code Review to make sure this change makes sense
- Make sure that the reflectometry algorithms that use this calculation still function properly
  and display the right results.

**Release Notes**: //todo

Fixes #14757

### CODE REVIEW

**Comment by OwenArnold** [comment]
Your changes are correct. And this is pretty obvious from my knowledge of the problem and the fixes made. Assuming the system tests pass. I'm going to be OK to merge this.

I am however worried that we silently 'fix' this behaviour without the reflectometry team understanding the changes, because this WILL affect real results. Can you please create a section on 'Momentum Transfer Calculation Fixes' in the release notes under Reflectometry and add  a section about this particular fix under that.

**Comment by MattKing06** [comment]
I was also thinking that this needs to be explained somewhere, as it is such a minor fix but it will impact the results as you say. I'll be sure to show why this fix was applied in the release notes.

**Comment by OwenArnold** [comment]
@MattKing06 Can you add the section asap. I'd like to point users at it if they grab future nightly builds.

**Comment by MattKing06** [comment]
here is the change to the release notes http://www.mantidproject.org/Release_Notes_3_6_Reflectometry. I can give a more in depth explanation if needed.

**Pull request merged**
