### PR TITLE
LoadFITS: change and add header keys, and other improvements

### PR DESCRIPTION
**Pull request by FedeMPouzols**
This addresses issue [#10231](http://trac.mantidproject.org/mantid/ticket/10231) and brings up-to-date the fits loader in various aspects. Documentation and a doc test have been added in PR #471.

**To test**:
- Tests still pass
- Review code changes
- Open the LoadFITS dialog: the old fields 'ImageKey', 'BitDepthName',  'RotationName', 'AxisNames' and 'ImageKeyName' should not be there anymore.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
It seems that the system test MERLINReduction is failing on auriga because of a missing/broken file `MER11060.raw`. Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, I'm begging you... retest this please

**Comment by FedeMPouzols** [comment]
Jenkins retest this please

**Comment by FedeMPouzols** [comment]
Jenkins retest this please

**Comment by KarlPalmen** [comment]
Only Filename & OutputWorkspace should remain on the LoadFITS dialog box, when I test. Please let me know if I'm wrong.

**Comment by FedeMPouzols** [comment]
There is one more (optional) field with the name of a "headers map" file. This is still there, as we will need to play with non-standard and changeable headers for a while. Not sure at this point if it will stay there or die when the tomography code stabilizes. It doesn't hurt anyway, and most users will never need to care about it.

**Comment by FedeMPouzols** [comment]
Oh, and also note that there is another PR with documentation for this algorithm: #471.

**Comment by FedeMPouzols** [comment]
Both are open at the moment, and there could be merge conflicts (they shouldn't be really important). Let me know if something happens.

**Comment by KarlPalmen** [comment]
When I test it, the LoadFITS algorithm is not available for selection and so I can't access the dialog box.

**Comment by FedeMPouzols** [comment]
There's a merge conflict after another PR was merged. So probably in your test branch you didn't get the new code or an inconsistent version. I'll sort it out and let you know.

**Comment by FedeMPouzols** [comment]
I just fixed the merge conflict. Unless there's any unexpected issue this should be ready for testing again when the CI builds finish (crossing all fingers and toes).

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
Oops, the builds failed on osx and rhel6 for unrelated random CI issues, but there's actually an issue in the LoadFITS doc test where I forgot to update after the merger of another branch. It's now or never...

**Pull request merged**
