### PR TITLE
Update CHESS geometry

### PR DESCRIPTION
**Pull request by AndreiSavici**
Re-ordered banks in CHESS

*There is no associated issue.*

*This does not require release notes* because **already have an entry for new CHESS geometry**

@GabrielHawk 
---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by StephenSmith25** [comment]
Is it intended for this PR to make it into the 6.1 release?

**Comment by AndreiSavici** [comment]
@StephenSmith25 yes

**Review by wdzhou — DISMISSED** [review]
It looks good to me.

:shipit:

**Comment by StephenSmith25** [comment]
We should change the base branch of this to release-next then right?

**Review by wdzhou — APPROVED** [review]

**Pull request merged**
