### PR TITLE
Dynamically resize wb splash screen image based on screen resolution

### PR DESCRIPTION
**Pull request by NickDraper**
This should resolve some of the Huge splash screens we get with the workbench sometimes.

It also means we only have to maintain one splash screen image and not two resolutions of the same thing.

**Description of work.**
It sets the splash screen size to be 20% of the available window size.

**To test:**
1. start workbench check that the size of the splash screen is reasonable
1. Change your screen resolution and repeat

*There is no associated issue.*

*This does not require release notes* because *this is a very minor improvement*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gvardany** [comment]
Nick, I remember that when having 2 displays, it was appearing in the middle, so half on each screen. I do not have 2 displays now, but can you check what happens in that case?

**Comment by NickDraper** [comment]
So I've done this on a computer with two displays, and the screen appears in the centre of the primary screen.

**Comment by NickDraper** [comment]
The change in this PR does not alter the positioning though, just the size of the image.

**Review by cailafinn — COMMENTED** [review]
Code looks good, just a note that when the resolution is quite low, the text on the bottom of the splash screen covers up the set of logos. Is this a concern?

**Comment by NickDraper** [comment]
How low?, I tested 1920 by 1080 and that seemed fine

**Comment by NickDraper** [comment]
Ok I see it at about 800px wide, but it is not much of a problem, but it is fine at 1024 wide.
Workbench itself would be a challenge to use on a screen 800px wide, so I don't think this is something to worry about.

**Comment by gvardany** [comment]
I think nowadays it is safe to say the minimum we support is HD, so 1,280 x 720.

**Review by cailafinn — APPROVED** [review]
Resolution concerns addressed, code and functionality looks good to me, nice work 👍

**Pull request merged**
