### PR TITLE
Fix qt3 support warnings group 2

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
This is group 2 of #16128.

This fixes the Qt3Support warnings for group 2.
## To test:

The changes in this PR have touched many areas of MantidPlot.  Below is a list of items which should be checked.

**Items for testing**

Areas that need thorough testing:
- Exporting Graphs
- QtSettings
- Scripting
  - Make sure that a Python script can run
- Projects
  - Make sure that you can open projects
  - Make sure that there is a list of recent projects and that you can select a recent project
- Files
  - Make sure that you can open files
  - Make sure that there is a list of recent files and that you can select a recent files
- Import ASCII
- ConfigDialg
  *Graph Default Settings
  - Make sure that everything is ok when applying changes
- Switch between Window-types (Table, Matrix, Note, Multilayer, Graph3D)
- Matrix
  - Run Fit 
  - Play with matrices
- Table
  - Play with tables
- MultilayerPlot
- File->`Open Image File`
- Export Matrix
- Plot 3D
- Plot Parametric Surface

Note that you might see funny stuff when transferring curves between layers. A bug on Ubuntu has been reported [here](https://github.com/mantidproject/mantid/issues/16310)

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [ ] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AntonPiccardoSelg** [comment]
just found some issues with recent files. Settting back to ` in Progress`

**Comment by KarlPalmen** [comment]
Branch name is long and with significant information (group 2) at end this makes it difficult to pick correct branch from tortoise git. I'll try again and advise shorter branch names in future.

**Comment by KarlPalmen** [comment]
Dear Anton

I’ve moved to group 6, but will test as you advised.

Karl

**Comment by AntonPiccardoSelg** [comment]
@KarlPalmen The errors were fixed and this ticket is ready for testing. Thanks.

**Comment by KarlPalmen** [comment]
Import ASCII has no obvious faults, but I do not know it well enough to be sure whether it is working OK. I wasn't able to access help for import ASCII.

**Comment by KarlPalmen** [comment]
Set Matrix Values does not appear to work.

**Comment by AntonPiccardoSelg** [comment]
@KarlPalmen  I don't really know it either. But I would suggest to:
1. Create a Matrix (File->New -> New Matrix)
2. Populate it (Matrix->Set Values-> for example i*j)
3. Export as Ascii (File->Export Ascii)
4. Reload the ascii file (File-> Import Ascii)
5. Compare the original Matrix with the loaded table/matrix

**Comment by AntonPiccardoSelg** [comment]
Ok, will check what is going on with `Set Values`

**Comment by KarlPalmen** [comment]
I tried exporting matrix as ASCII then importing and it worked OK.

**Comment by KarlPalmen** [comment]
I take Load Image to mean Open Image File. Load does not work with image files.

**Comment by KarlPalmen** [comment]
I take Load Image to mean Open Image File. Load does not work with image files.

**Comment by AntonPiccardoSelg** [comment]
@KarlPalmen You are right, the test instructions were actually referring to File->`Open Image File`. Thanks.

**Comment by KarlPalmen** [comment]
The setting of the matrix values worked today.

**Comment by KarlPalmen** [comment]
Ok today :shipit:

**Pull request merged**
