### PR TITLE
Design for HKLs

### PR DESCRIPTION
**Pull request by MichaelWedel**
This is meant for discussions around the design document for HKLs for which a [PR](https://github.com/mantidproject/documents/pull/18) is open in the documents repo.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
@samueljackson92 can you take a look at this

**Comment by gvardany** [comment]
@samueljackson92 What is the status of this? Is this still relevant?

**Comment by samueljackson92** [comment]
@gvardany I'd love to start moving towards using Mike's implementation but honestly all my time has been sucked up by other things and it's always been pushed to the back of the queue. I feel the strong types presented here would really improve the quality of some parts of the code base, but it's finding time to do the migration.

Also there are a couple of unresolved questions about for example, file serialisation (particularly to text formats such as ISAW), that need to be agreed on (see the corresponding design doc) before proceeding.

**Comment by NickDraper** [comment]
@martyngigg I suggest that once you've taken on single crystal then you spend a day or so evaluating if this is worth progressing or abandoning.

**Comment by NickDraper** [comment]
This PR is being closed as it is over a year old and has not been recently progressed.
The underlying branch will be removed at the next cleanup along with the next release unless it is progressed further.

**Pull request closed without merging**
