### PR TITLE
ISIS SANS improvements to batch processing and beam centre finder

### LINKED ISSUE #16863: ISIS SANS GUI improvements
Rob has found that some users trip over several issues in the SANS GUI.

They are:
* reporting service of the Beam Centre Finder seems to be not correct for LARMOR
* when the hardware fails to provide a BENCH_ROT entry in the sample logs SANS does not warn the users but fails much later. (see run 10351)
*  in batch mode users have speficied outputworkspace names with semi-colons which are then used for the file name to be saved out. This causes a crash of Mantid

Expected solution:
* Correction of reporting service
* catch the missing BENCH_ROT when file is being loaded. Note that BENCH_ROT is only expected for new-style SANS runs.
* convert illegal characters to some default.

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Fixes #16863 

The improvements address a list of items that Rob mentioned:
1.  output names in batch mode with illegal characters will have them renamed. 
2.  If a workspace does not contain a BENCH_ROT entry, then the process will fail early on
3.  The original reporting for the beam centre finder for LARMOR  was fixed

**To test:**

**Test missing Bench_Rot entry**

The test data can be found here: \olympic\Babylon5\Scratch\Anton\Testing\ISIS_Improvement\MissingBenchRot
- Add the sample data path to the data search directories.
- Start up the ISIS SANS GUI
- Set the instrument to LARMOR
- Set the user file to USER_Pappas_RB1569004_162B_ISISStat_r9818.txt
- Set the file LARMOR00010351 as the sample scatter input
- Press load
  - Confirm that an exception is thrown
  - Confirm that the error message in the log terminal mentions a missing Bench_Rot entry

**Test bad output name in Batch Process**

The test data can be found here: \olympic\Babylon5\Scratch\Anton\Testing\ISIS_Improvement\BadBatchName
- Add the sample data path to the data search directories.
- Start up the ISIS SANS GUI
- Set the instrument to SANS2DTUBES
- Select Batch Mode on the Run Numbers tab
- In the CSV file browser widget, select SANS2DTUBES_BadName.csv. This contains the output name zero_f:ee_out which has the illegal colon
- Run 1D Reduce
  - Confirm that Mantid does not crash
  - Once the reduction is done, check your output directory for a new file called zero_fee_out, ie the invalid character was removed

**Test for beam centre finder for LARMOR**

The test data can be found here: \olympic\Babylon5\Scratch\Anton\Testing\ISIS_Improvement\BeamCentreFinder
- Add the sample data path to the data search directories.
- Set the instrument to LARMOR
- Set the user file to USER_Pappas_RB1569004_162B_ISISStat_r9818.txt
- Set the file LARMOR00009839 as the sample scatter input and press load
- Switch to the Geometry tab
- Set Max.iterations to 0
- Set Current-Beta-Rear to 1
- Set Current-Y-Rear to 12
- Go to your log window and set the log level to Notice
- Press Run
  - Confirm that the output on the Geometry tab output ouputs 1 and 12 as the starting point
- Do the same thing again for Current-Beta-Rear = -1 and Current-Y-Rear = 12
  - Confirm that the output on the Geometry tab output ouputs -1 and -12 as the starting point
## Release Notes

See [here](https://github.com/mantidproject/mantid/pull/16875/commits/645a94c2a0705da3ef482e5ddf0493c937443a83)

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
I'm just testing the missing Bench_Rot entry. It works as described but what would a user be expected to do next?

**Comment by AntonPiccardoSelg** [comment]
@martyngigg 
Regarding the tests:
* Part of the bench_rot issue can be isolated and tested in a unit test.
* The batch reduction issue could be tested in a system test. 
* The first report of the beam centre finder is not easily testable by itself. But I can create a unit test for the quaternion extraction

Regarding the exception message: 
* A missing bench rotation is in a way equivalent to a missing proton charge. The data acquisition is flawed.

Moving forward:
* I will add more text to the excpetion, along the lines: "Check your machine"
* I  will add a unit test for the quaternion conversion. 
* I will isolate the bench_rot logic further and create a unit test.
* I think that a system test for the batch issue is not justified.

**Comment by martyngigg** [comment]
@AntonPiccardoSelg I understand now, thanks for the clarification.

I've functionally tested all of the changes and they work as expected. I assume that as this is high priority Rob needs the fixes soon?

**Comment by AntonPiccardoSelg** [comment]
Yes, they are high priority. Once they are in master, I will give the changes to the SANS scientists to make sure it is what they are 100% happy with the changes. Then we can use them for the patch release. 

I am writing the unit tests now, that shouldn't take me long. I don't think that we would gain much from the system test, hence I will not concentrate on that for now.

I will let you know once I have pushed the tests.

**Comment by martyngigg** [comment]
@AntonPiccardoSelg Sounds good.

**Comment by martyngigg** [comment]
@AntonPiccardoSelg There is a failure of the `SANSUtilityTest` on Windows (the other builds didn't get that far but I assume would show the same)

**Comment by AntonPiccardoSelg** [comment]
@martyngigg The builds are passing now.

**Comment by martyngigg** [comment]
Final commits have only added tests unit tests so no further functional testing is required. I think this is ready to go.

:shipit:

**Pull request merged**
