### PR TITLE
Fix custom interface help links

### PR DESCRIPTION
**Pull request by martyngigg**
Description of work.

Updates the interface page names embedded in the interface help buttons to match those in the docs.

**To test:**

* build the code
* build the docs-qthelp target
* try all help buttons - they should point to a valid page on all interfaces

*No issue*

**Release Notes** 
*Does not need to be in the release notes as we broke it in the dev cycle*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
scd event data reduction redirects to online help but returns http://www.mantidproject.org/SCD_Event_Data_Reduction_Interface_(MantidEV)

**Comment by martyngigg** [comment]
Thanks. It does the same in `3.10.1` but it's worth fixing it now while we are looking at it.

**Comment by AnthonyLim23** [comment]
some of the interfaces are hanging a bit. I assume this is because of the build and not installed. I have also noticed that some open the offline help and others the online help (probably not important for now but in the future we should look at making it all offline help)

**Comment by AnthonyLim23** [comment]
ISIS SANS goes to online help and the page is not complete (maybe sort this for next release)

**Comment by AnthonyLim23** [comment]
all of the interfaces direct to the relevant help page (online or offline)

**Review by AnthonyLim23 — APPROVED** [review]
looks good and all help icons go to a help page

**Comment by AnthonyLim23** [comment]
The redirects to online help (and not offline help) will be fixed in #20888

**Comment by AnthonyLim23** [comment]
@mantidproject/gatekeepers could we get this merged please?

**Pull request merged**
