### PR TITLE
Fix Quasi-type Python algorithms

### LINKED ISSUE #13545: QLines and Quest algorithms are broken
The example at https://github.com/mantidproject/mantid/blob/master/Code/Mantid/docs/source/algorithms/QLines-v1.rst no longer works because the internal `Main.QLRun` call fails. The verbose argument seems to have been removed [here](https://github.com/mantidproject/mantid/commit/4bfe0730d57db06ca262be57234cce678bea7e43#diff-ecd01b03d3248a8abb45e14d3970e901R154).

The same is true for `Quest`

### PR DESCRIPTION
**Pull request by martyngigg**
Fixes #13545

**Tester**
Try out the usage examples for `QLines` & `Quest` in the updated `.rst` files in this branch.

No release note updates required.

### CODE REVIEW

**Comment by MichaelWedel** [comment]
Sorry, took me a while to realize that I can't test this yet (lack of Windows machine).

**Comment by KarlPalmen** [comment]
Neither script works for me on Windows 7. The error messages are different.

**Comment by KarlPalmen** [comment]
It seems to be failing, because of some problem with f2py.

**Comment by KarlPalmen** [comment]
Scripts worked after some files were copied to a place, where the mantid installer, but not the development build puts them.

**Pull request merged**
