### PR TITLE
Generate workflow diagrams with graphviz

### PR DESCRIPTION
**Pull request by eXeC64**
This is for trac ticket [#11054](http://trac.mantidproject.org/mantid/ticket/11054)

For reasons I'll now explain, the original design for the implementation had to be deviated from.

The diagrams were going to be generated as a custom build step, but actually including the generated images turns out to be non-trivial. All previous instances of it happen accomplish it through a custom sphinx directive, so that's what I've done. Now instead of using a script to generate the diagrams all in one go, they're generated as they're asked for, and the links are inserted correctly.

**TODO**:
- [x] Write wiki page documenting how to construct new diagrams with dot
- [x] Verify the new dependency on `dot` is handled correctly on all platforms

### CODE REVIEW

**Comment by peterfpeterson** [comment]
`FindDoxygen.cmake` hands out the variable `DOXYGEN_DOT_EXECUTABLE`.

**Comment by peterfpeterson** [comment]
I tried your latest changes on my system and it works quite well. I think that the workflows should have a canonical name like `ReflectometryReductionOne-v1_wkflw.dot` (which becomes `ReflectometryReductionOne-v1_wkflw.dot`) so they are more parallel to the generated dialog boxes `ReflectometryReductionOne-v1_dlg.png`. The naming would be on the dot files rather than done by the sphinx extension.

If you want an extra challenge, `AlignAndFocusPowder` is already in (not your convention) dot.

**Comment by eXeC64** [comment]
@peterfpeterson I've made the suggested changes, and another slight alteration. In the `.. diagram::` directive the author now includes the `.dot` extension in the diagram name, making it more explicit that it's a filename, rather than a special name in a table somewhere.

```rst
.. diagram:: ReflectometryReductionOne-v1_wkflw.dot
.. diagram:: ReflectometryReductionOneAuto-v1-Groups_wkflw.dot
.. diagram:: ReflectometryReductionOneAuto-v1-PolarizationCorrection_wkflw.dot
```

It seems less confusing this way. I'm now writing the wiki page to document the new functionality.

**Comment by eXeC64** [comment]
The wiki page http://www.mantidproject.org/Documenting_Workflow_Algorithms has been updated to reflect the new approach. Some of the links are dead currently, but will come alive when this is merged.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Pull request merged**
