### PR TITLE
Reflectometry interface: Introduce autoreduction button

### LINKED ISSUE #19453: Reflectometry Interface: Autoreduce a set of runs given an investigation ID
A button to autoreduce data should be added to the interface. When clicked, this button will do the following:
- Check if an investigation ID has been entered (and request user to log into catalog and enter an ID if not).
- Obtain runs from the investigation ID.
- Transfer runs to the table.
- Reduce all rows in the table.
- Be able to pause and restart autoreduction

Part of umbrella #17029.

### PR DESCRIPTION
**Pull request by PranavBahuguna**
As described in the attached issue, this PR adds a button to perform autoreduction. When supplied an investigation id and the button is clicked, the following occurs:

- Obtain runs that are part of the investigation the id was supplied for.
- Transfer all runs to the processing table.
- Select all runs and process them.

When autoreduction is running, the button is disabled. Pausing reduction will re-enable the button. If the instrument, investigation id or transfer strategy is changed while paused before clicking 'autoreduce' again, a new autoreduction (including searching for runs and transfer) will be started. Otherwise it simply resumes reducing runs just like `Process` would.

~_Wait for PR #19977 to be merged first before merging this._~

**To test:**
- Code review.
- Ensure documentation is updated and sensible.
- Manual testing steps:
  - Login into the ICAT catalog.
  - The interface can be accessed from Interfaces->Reflectometry->ISIS Reflectometry.
  - Select `POLREF`, enter investigation id `1520249` and click on the `autoreduce` button to begin autoreduction.
  - Ensure that changing id, instrument or transfer strategy causes a new autoreduction to be started.
  - Currently it is possible to cause critical errors by clicking on buttons such as `delete row` while reduction is in progress. These will be dealt with in #19951.

Fixes #19453.

**Release Notes** 

*Release notes have been updated.*

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gemmaguest** [comment]
Some initial observations:

### Highlighting
The green highlighting of completed rows is a nice feature but I'm noticing a few inconsistencies with it on Windows 10:
- If a parent row only has a single child row, the child row gets highlighted but the parent row doesn't. (If it has more than one child row, then the parent is highlighted when all child rows are complete, as you'd expect.)
- The highlighting is sometimes not done until I force a redraw e.g. by moving the mouse over the rows.
- When you click on a green row, the selected row colour is only marginally different to the non-selected row colour, so it's hard to see which rows are selected.

### Transmission run
The reduced runs include the transmission run, which gives an error because the angle is 0.0. This should probably be excluded, and maybe the 'Alignment check' run too - we should ask Max about how we can find out which runs to exclude.

### Progress bar
- When you pause the autoreduction, the progress bar and %complete number stop where they were, which is great, but the bar still animates. Would it be better if it stopped animating to be clear that nothing is currently happening?
- I wasn't sure how to re-start autoreduction - I assume you hit the `Autoreduce` button again? It might be nice to have a resume button next to the pause button to make this clearer, even if it just does the same thing. It could use the same Play icon as the Autoreduce button.
- The Pause icon looks more like a Stop icon - is there a better Pause icon available?
- When resuming autoreduction, the progress bar and %complete number start from 0 again. Would it make more sense for them to continue from where they were? I guess this might not make sense if changes have been made, though?

**Comment by PranavBahuguna** [comment]
@gemmaguest Thanks for reviewing my PR. Regarding your observations:

###Highlighting

- 1 - This is actually deliberate - the parent highlighting is supposed to be done only if post-processing is done with all child rows. With one child, no post-processing is done, so the parent is un-highlighted. We can change this of course, but I felt that doing it this way made more sense.

- 2 - There is nothing I can do about this unfortunately.

- 3 - Probably something to discuss with scientists, that is if they want selected rows to be highlighted. Will handle this in a separate issue.

###Transmission run

- Agreed, we should bring this up in the meeting with them

###Progress bar

- 1 - I'll see what I can do about this, probably in a separate issue

- 2 - Agreed. I think it might be nicer to somehow to have a single autoreduction button whose icon changes from a 'play' to a 'pause' icon.

- 3 - I had a design for one, probably won't be hard to implement.

- 4 - While it could be possible to not reset it to zero, this could potentially get very messy quickly it requires storing the progress and accounting for adding/deleting rows, changing data in processed rows and or changing the selection. Meanwhile, simply resetting progress isn't too bad an alternative as it can still show the progress of reduction of the remaining unprocessed rows, which is still helpful. Trying to change it would probably be far more effort than its worth, considering all the other possible things that can be done with the interface.

**Comment by gemmaguest** [comment]
:+1: That all sounds good. Nothing here's a showstopper so it's fine to deal with them in separate issues.

**Review by gemmaguest — APPROVED** [review]
The code changes look good and behave as described :+1:

A very minor thing which could be fixed later: if you are not logged in to ICat and you enter incorrect login details, you get the message "Error Logging in: Please press 'Search' to try again.". This is slightly misleading now this is not just specific to the `Search` button.

**Comment by PranavBahuguna** [comment]
@gemmaguest Thanks, I'll just throw those extra things into some other PR.

**Pull request merged**
