### PR TITLE
Highlight failed measurement transfers in Reflectometry GUI (Polref)

### LINKED ISSUE #14370: Highlight failed transfer runs in Reflectometry GUI
This is a sub-issue of #14193 

If a run has invalid/failed transfer then the row associated with that run should be highlighted in orange
and a tooltip should be implemented to explain why there was a failed transfer.

### PR DESCRIPTION
**Pull request by MattKing06**
There were some changes added to the GUI in #14051 that allowed the user to search the ICAT service by `Measurement` as well as `Description`.

Some of the runs that were retrieving by the `Measurement` search could not be successfully transferred into the processing table of the GUI.

These runs are now highlighted in Orange and a tooltip is set describing why they could not be transferred into the processing table.
- [ ] **Documentation**: needs to explain the new transfer methods and what the highlighted rows mean.

**To Test**:
 You will need access to the ICAT service to perform this test.
- Go to Interfaces > Reflectometry > ISIS Reflectometry (Polref)
- In `Search Runs` change the `Instrument` to POLREF
- Enter the investigation ID: `1520249`
- Change transfer method from `Description` to `Measurement`
- Run Search
- Select any run before 14490, as they will fail
- Select any run after 14490, as they will transfer succesfully
- click Transfer
- Once the processing table is populated, click back on the Search Table
- See that any failed transfers will be orange and the tooltip (hover over cell) should explain why they failed

**Release notes**: to do.

Fixes #14370

### CODE REVIEW

**Comment by MattKing06** [comment]
I have not adapted any of the unit tests (hence the build failures). This PR is just for reviewing the code at the moment and the unit tests will be patched up once the main code changes have been approved.

**Comment by OwenArnold** [comment]
@MattKing06 . Can you please fix the unit tests anyway. It's good practice to always keep unit tests in step with the code.

**Comment by OwenArnold** [comment]
Several additions needed. New issue for this:
1. We should have a button to 'Clear' the transfer information. 
2. We should think of a way to show the failed rows but keep the selection used for the transfer.
3. Did you try unplugging your network cable and doing the transfer. When I did the files didn't load (as you would expect) but no failure was reported.

**Comment by MattKing06** [comment]
The ICAT service just threw a `FileNotFound` exception which came up with the `Terminate` or `Continue` pop up when I unplugged the network cable. I'm not sure if this could be avoided.

**Pull request merged**
