### PR TITLE
Powder ISIS script fails when ExistingV is no

### LINKED ISSUE #14433: Powder Diff::The PowderISIS script fails when ExistingV equals 'no'
While running the PowderISIS script, when the variable `ExistingV` in preference file of any instrument is changed to `no` from `yes`, the script ends up failing.

```
 => VANADIUM FOCUSED
ValueError: Invalid value for property Filename (string) "": No file specified.
  at line 16 in 'C:/Users/RYQ25391/Documents/OwnCodes/Powder Diffraction Files/python_mantid_hrpd_running_Script.py'
  caused by line 32 in 'C:/MantidInstall/scripts/PowderISIS\cry_focus.py'
  caused by line 63 in 'C:/MantidInstall/scripts/PowderISIS\cry_vana.py'
  caused by line 77 in 'C:/MantidInstall/scripts/PowderISIS\cry_vana.py'
  caused by line 754 in 'C:/MantidInstall/bin\mantid\simpleapi.py'
  caused by line 717 in 'C:/MantidInstall/bin\mantid\simpleapi.py'
```

Once fixed, update the `ISISPowderDiffractionHrpdTest` system test with a test case which uses a preference file that as variable `ExistingV` set as `no`

### PR DESCRIPTION
**Pull request by shahrozahmed1**
fixes #14433 

> - [x] merge #14426 before this

**To Test**
- Run `ISISPowderDiffractionHrpdTest.py` system test locally
- Check all tests pass
- Once the system test has passed, make sure the value of `ExistingV` in the pref file `mtd2.pref` hasn't changed to `yes` from `no`
- You could also run the python script manually via Mantid using the system test script which is utilising  `mtd2.pref` preference file. 
- New parameter `Write_ExtV` has been included for `cry_focus.focus_all(..)` with default value of `True`, this will enable the user to disable the script to auto replace `ExistingV` value in pref file.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
Ah I see the problem that is making the rhel7 build fail. The file `hrpd/test/cycle_09_2/tester/mtd2.pref` has been added but directly as a file, not added in the "SystemTestData" cmake infrastructure. You'll need to add it with `git add-test-data`, as the other input files, and then upload it with the web form.

**Comment by FedeMPouzols** [comment]
@shahrozahmed1: Pylint complains about `global DIFF_PLACES` in `ISISPowderDiffractionHrpdTest.py`. Do you need that variable as a global?

**Comment by FedeMPouzols** [comment]
@shahrozahmed1 : beware that even though the tests passed on the build server, when I run it locally for a second time it fails, and my `mtd2.pref` file is changed to `ExistingV                 yes`. Strange, cause you're passing  this new `Write_ExtV=False` parameter. Could it be that you don't pass that parameter here: https://github.com/mantidproject/mantid/blob/14433_powderISIS_script_fails_when_existingV_is_no/Testing/SystemTests/tests/analysis/ISISPowderDiffractionHrpdTest.py#L38 and here https://github.com/mantidproject/mantid/blob/14433_powderISIS_script_fails_when_existingV_is_no/Testing/SystemTests/tests/analysis/ISISPowderDiffractionHrpdTest.py#L103, or something else not working as expected?
The GEM tests work well no matter how many times I run them.

**Comment by shahrozahmed1** [comment]
@FedeMPouzols it seems that you cannot run the mantid test script inside the `unittest.TestCase`, which makes sense. I could have written  the script which uses the `mtd2.pref` [here](https://github.com/mantidproject/mantid/blob/14433_powderISIS_script_fails_when_existingV_is_no/Testing/SystemTests/tests/analysis/ISISPowderDiffractionHrpdTest.py#L40), but it would confuse things and also overwrite certain files. Hence I created a second `MantidStressTest` which is using a different pref file and in the end you should also get details on which `MantidStressTest` failed out of  the two. (*if it does fail*)

**Comment by FedeMPouzols** [comment]
Ah I see. Yes, when you use a system test ala Mantid (subclass of stresstesting.MantidStressTest) the test is expected in `runTest()`. It makes perfect sense to have two system tests, as they represent two variants of the workflow that are substantially different.

**Comment by FedeMPouzols** [comment]
I just tested the updated branch locally on debian and it is working well. @shahrozahmed1 : let me know if you want to make any final modifications, otherwise I'll merge this in as soon as the rhel7 tests pass.

**Comment by shahrozahmed1** [comment]
@FedeMPouzols no further modifications are required on this branch and thanks

**Comment by FedeMPouzols** [comment]
All working well even when run multiple times. The .pref files are preserved correctly. This adds tests for the longer runs that usually take place at the beginning of the cycles, and for the shorter runs that re-use some files.

**Pull request merged**
