### PR TITLE
Fix Symmetrise failing on workspaces with different bin width

### LINKED ISSUE #33339: Unhandled exception in Symmetrise algorithm
**Original reporter:** Sanghamitra

**Describe the bug**
Giving invalid data to the Symmetrise causes an unhandled exception, bad parameters should be caught in validation.

**To Reproduce**
see #33338

### PR DESCRIPTION
**Pull request by Harrietbrown**
**Description of work.**

This PR fixes a bug in Symmetrise where if a workspace had different bin widths it would sometimes be unable to find the correct minimum values.

**To test:**

See associated issue, following the steps should not rsult in an unhandled exception, and the algoithm should run correctly.

Fixes #33339

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by SilkeSchomann — DISMISSED** [review]
Works as expected and code looks good :-)

**Comment by sf1919** [comment]
There seems to be a leftover release note about Vesuvio documentation still in this PR that going into the main release notes for indirect geometry. This can be removed as it's already in that file.

**Comment by Harrietbrown** [comment]
> There seems to be a leftover release note about Vesuvio documentation still in this PR that going into the main release notes for indirect geometry. This can be removed as it's already in that file.

I realsied there was an extra whitespace before the full stop. It's not adding a new line to the propper release notes.

**Comment by sf1919** [comment]
I've now sorted this in the release note PR I'm working on so it doesn't need to be in here. If you spot anything else like this let me know or comment on an open PR for the release notes. I'm trying to avoid anyone adding direct to the release note files to avoid merge conflicts.

**Comment by sf1919** [comment]
Just to confirm the whitespace has been dealt with in #33348

**Review by SilkeSchomann — APPROVED** [review]
As this was only a small modification of the release note I am happy to approve again.

**Pull request merged**
