### PR TITLE
PDToGUDRUN

### PR DESCRIPTION
**Pull request by peterfpeterson**
This algorithm allows for "simple" conversion of nexus files to files that will load into GUDRUN. There are no tests as it is a very thing layer on top of other algorithms.

**Note:** This requires #16239 to be merged first as it was merged into this branch.

**To test:**

Try running it similar to [PDToPDFgetN](http://docs.mantidproject.org/nightly/algorithms/PDToPDFgetN-v1.html).

_There is no associated issue._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [ ] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
After merging #16239 this has developed a merge conflict.

**Comment by peterfpeterson** [comment]
This can be tested now and approved, pending all of the builds passing.

**Comment by peterfpeterson** [comment]
This was branched from `master` long before `release-v3.7` was created.

**Comment by AndreiSavici** [comment]
```Error in execution of algorithm PDToGUDRUN:
Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.
  at line 180 in '/home/3y9/Mantid/mantid/Framework/PythonInterface/plugins/algorithms/PDToGUDRUN.py'
  caused by line 1140 in '/home/3y9/Mantid/Build/bin/mantid/simpleapi.py'```

I don't have SaveNexusPD

**Comment by AndreiSavici** [comment]
It relies on h5py (otherwise SaveNexusPD is not registered). It would be nice to register the algorithm only if h5py is present (not required to build Mantid, but it's there in the packaging dependencies). It is shipped with windows and osx
:shipit:

**Comment by FedeMPouzols** [comment]
@peterfpeterson: I understand that this new algorithm wants to be in `release-v3.7`? If so I'll do the dual merge.

**Comment by peterfpeterson** [comment]
It needs to get into v3.7.

**Comment by FedeMPouzols** [comment]
I've picked the range of first 4 commits and merged them onto `release-v3.7`
- the first two come from #16239 
- the next two are from this PR specifically

Let's merge into master as well, but beware that in `release-v3.7` git didn't like commit 39b504e7ff7b6d61a054338307239c46515d54d2 (the first picked, changes between lines 832-841) so I chose those in the conflict resolution. The next three commits were picked cleanly. This may produce a spurious conflict when merging `release-v3.7` into `master`? If so just keep what commit 39b504e7ff7b6d61a054338307239c46515d54d2 says.

It all looked fine locally.

**Pull request merged**
