### PR TITLE
Fix colorbar scale so numbers appear on scale on log scale

### LINKED ISSUE #27379: Numbers not shown on Colourfill Plot scale bar when change to Logarithmic
During the smoke testing I noticed that changing the scale to logarithmic on a colour fill plot causes the numbers to disappear on the colour scale (in Workbench). I observe this on the Windows nightly builds but not on IDAaaS. Haven't tried on other platforms.

The default Min. value on the dataset I'm using is zero. If you change the Min. value or Max. value to something different the numbers on the scale re-appear eg changing the Min.value to a small positive number rather than zero in the example below.

Not quite the same, but similar to https://github.com/mantidproject/mantid/issues/27151

Investigate using the symmetric log in MatPlotLib as slice viewer uses this and that seems to handle zero better

### Expected behavior

Load MAR11060
Create Colour Fill plot
Open up Figure Options
Go to Images tab and change Scale to Logarithmic
Colour scale bar should have numbers

### Actual behavior

Colour scale bar doesn't have numbers:

image

### Steps to reproduce the behavior

See above

### Platforms affected

Windows, IDAaaS

### PR DESCRIPTION
**Pull request by alicerussell1**
**Description of work.**

When the scale on a colorfill plot was changed to log with a large gap between xmin and xmax the number of the scale disappeared. 
The issue occurred because of the minor ticks on the plot. The only around this seems to be to do the plot without the minor ticks if the range is too large. Any attempt made to plot them otherwise resulted in the same error.

**To test:**
1. Load MAR11060
2. Create Colour Fill plot
3. Open up Figure Options
4. Go to Images tab and change Scale to Logarithmic
5. Press ok or apply, the colour scale bar should have numbers.

Fixes #27379

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by PhilColebrooke — DISMISSED** [review]
Yep

image

**Review by NickDraper — CHANGES_REQUESTED** [review]
If the range is small enough we should try to include the minor ticks and only exclude them if it is going to cause a problem.

**Review by NickDraper — DISMISSED** [review]
Really nice now, good to go as soon as the builds are happy

**Review by PhilColebrooke — CHANGES_REQUESTED** [review]
It's broken on RHEL7 😞

**Review by PhilColebrooke — CHANGES_REQUESTED** [review]
The fix works for the figure options but not when you edit the axis limits by double clicking on the colorbar axis 😭

**Comment by alicerussell1** [comment]
I've fixed the issue with changing the values from the edit axis limit in the same way it was done in figure options - this should now be ready for another review

**Review by PhilColebrooke — APPROVED** [review]
Hopefully it's okay for me to review a PR that I've made changes to (all I did was remove a blank line). This is good to go now as long as the checks pass 👍

**Pull request merged**
