### PR TITLE
Add gridlines and increase font size on DPW

### LINKED ISSUE #21312: Update ISIS SANS Interface v2 to increase font size and add grids
There has been feedback that the font sizes in the ISIS SANS GUI are too small and that it is unclear where to insert data. To improve this issue the font sizes should be increased and a grid added around the data insertion boxes.

### PR DESCRIPTION
**Pull request by Matthew-Andrew**
**To test:**
Open the sans gui V2 confirm that the text is larger and that gridlines are present
Open the reflectometry gui confirm that the text is larger that gridlines are present and that you can expand into the sub trees.
Also test that the correct rows are highlighted green on process.

Fixes #21312 . 

**Release Notes** 

TODO

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [x] Are the unit tests small and test the class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by gemmaguest — CHANGES_REQUESTED** [review]
The gridlines are a big improvement and the code changes on the whole look ok :+1:. However, the green highlighting that indicates when a row has been processed is lost, perhaps due to setting the background-color to blue?

Note that the green highlighting is not ideal because it's only visible when a row is unselected, but this is better than nothing. I don't mind what the colour scheme is here, but we do need to be able to distinguish between processed/unprocessed rows and groups.

Also, note there are conflicts to resolve

**Comment by Mantid-Matthew** [comment]
This seems to be because the style-sheet overwrites the highlighting of processed groups and rows which is done with roles in the model. I can't find an easy fix for this but will look into it more.

**Comment by gemmaguest** [comment]
The code changes look good and as far as I can tell should do the right thing, however on Ubuntu the gridlines and highlighting are not displaying correctly:

gridlines

**Review by gemmaguest — APPROVED** [review]

**Comment by gemmaguest** [comment]
This looks good now and works well on Ubuntu :+1:
- Reflectometry, SANS v2 and the toy DataProcessorWidget interface all work well.
- Highlighting of processed rows is done and (for reflectometry) cleared correctly when settings change.
- Adding and deleting rows and groups works as expected.
- Loading a table file works as expected.
- Expanding/collapsing groups works as expected.

**Pull request merged**
