### PR TITLE
Rename Qt derived classes

### PR DESCRIPTION
**Pull request by gemmaguest**
Great care has been taken in the restructuring of the ISIS Reflectometry GUI to ensure that anything related to Qt is kept out of all classes except those that  deliberately inherit from QObject. This PR renames Qt-derived classes to start with `Q` to make it obvious which classes are QObjects.

**To test:**

- Code review and ensure unit tests pass
- Check that the ISIS Reflectometry GUI opens ok in MantidPlot and Workbench

Refs #26535 

*This does not require release notes* because **it involves file renaming only**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by cailafinn — CHANGES_REQUESTED** [review]
Much clearer which classes inherit from QObject, unit tests pass and GUI opens properly on Plot and Workbench. Just some small comments on the code.

**Review by cailafinn — DISMISSED** [review]
GUI and Unit Tests still working as expected, looks good to me 👍

**Comment by DanNixon** [comment]
I like why this is being done, but not how it has been done. IMO this naming is too close to "standard" Qt objects and without consulting the Qt manual or knowing the reflectometery interface is it not obvious they are not.

Could the same not be achieved with a dedicated `Qt` directory in each relevant directory?

**Comment by gemmaguest** [comment]
> I like why this is being done, but not how it has been done. IMO this naming is too close to "standard" Qt objects and without consulting the Qt manual or knowing the reflectometery interface is it not obvious they are not.
> 
> Could the same not be achieved with a dedicated `Qt` directory in each relevant directory?

@DanNixon Good point. I like having it in the name though as it's more visible when developers are working on it (the directory might not be obvious in some IDEs). How about a different prefix, say `Qt`?

**Comment by DanNixon** [comment]
> @DanNixon Good point. I like having it in the name though as it's more visible when developers are working on it (the directory might not be obvious in some IDEs). How about a different prefix, say `Qt`?

Yes `Qt` as a prefix would be fine.

**Review by DanNixon — DISMISSED** [review]

**Comment by gemmaguest** [comment]
The force push is just to revert the change to reorder the include statements. According to clang-format ISearchModel is before ISearcher (it must sort capitals before lowercase letters).

**Review by DanNixon — APPROVED** [review]

**Pull request merged**
