### PR TITLE
Fix error when running Engineering diffraction calibration

### LINKED ISSUE #32165: Error at end of calibration relating to ENGINX instrument parameters file
When a calibration is run in the Engineering Diffraction user interface there is an error logged near the end of the process saying that a parameter is of the incorrect type.
This relates to these calls to getNumberParameter in calibration\model.py:
```
        for param_name in ["alpha", "beta_0", "beta_1", "sigma_0_sq", "sigma_1_sq", "sigma_2_sq"]:
            params_north += [NorthBank.getNumberParameter(param_name)[0]]
            params_south += [SouthBank.getNumberParameter(param_name)[0]]
```

Having debugged this a bit, it seems like the changes in https://github.com/mantidproject/mantid/pull/31888 mean that the parameter alpha is no longer of type "number". It looks like the code thinks it's of type FittingParameter instead. Not sure if the parameter "Bk2BkExpConvPV:Alpha" is being picked up instead

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

Fix "parameter of incorrect type" error when running a calibration from the engineering diffraction UI

Reinstate the alpha value as an instrument parameter so it can be retrieved at the end of the calibration and written out to the prm file.

Also rename alpha to alpha_0 to avoid name clash with new Bk2BkExpConvPV alpha parameter

**To test:**

Open the engineering diffraction user interface (Interfaces, Diffraction menu)
Go to the Calibration tab
Run a calibration by selecting the "Create New Calibration" radio button and use Vanadium 236516, Calibration Sample 193749 (note these are in the local test data files in case the ISIS data archive isn't accessible - it's been quite slow in the last few days)
Check it completes without any errors

Fixes #32165.

*This does not require release notes* because **the problem was introduced in this release in https://github.com/mantidproject/mantid/pull/31888**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DannyHindson** [comment]
@RichardWaiteSTFC - not one for this afternoon perhaps, but would be interested to discuss whether this problem needs to be covered by a system test. This wasn't caught by the engineering diffraction unit tests because the sample workspace is mocked. I remember Tom was talking about consolidating the EnginX.py unit and the workflow in the calibration model (if I remember correctly). Perhaps that would do it?

**Comment by RichardWaiteSTFC** [comment]
@DannyHindson Yes it sounds like a systems test is required for this (it's sometimes awkward to test this sort of thing in a gui as it's often necessary to mock things). Was this caught by the` EnginXScriptTest.py` - I would have thought  it would write .prm? Long term the  plan is to have EnginX.py call the code in the UI (or I suppose vice-versa) so that we don't maintain near-duplicate code, as you point out this will also give us more certainty that the code in the UI will work for real data.

**Comment by DannyHindson** [comment]
> @DannyHindson Yes it sounds like a systems test is required for this (it's sometimes awkward to test this sort of thing in a gui as it's often necessary to mock things). Was this caught by the` EnginXScriptTest.py` - I would have thought it would write .prm? Long term the plan is to have EnginX.py call the code in the UI (or I suppose vice-versa) so that we don't maintain near-duplicate code, as you point out this will also give us more certainty that the code in the UI will work for real data.

That test does write a prm file but it doesn't output the back to back exponential parameters. So just a small difference between the UI model and the EnginX script. I'll perhaps align the two for now by duplicating the method that reads the instrument parameters off the ceria workspace. Longer term, yes would be best to get the UI\script calling the same code if possible

**Review by RichardWaiteSTFC — COMMENTED** [review]
Changes look good thanks for fixing this. Calibration on UI executes without error and instructions in PR#31888 still work, BackToBackExponential and Bk2BkConvPV functions working as expected for Engin-X data. Thanks for making EnginX script consistent with UI wrt writing B2B coefficients into prm - looks good to approve after systems test passes (note I haven't tested this on windows). I will be off on A/L next week so will un-assign myself now.

**Comment by DannyHindson** [comment]
@DanielMurphy22 - if you have a bit of time today please can you review this PR? Richard got 95% of the way through reviewing\approving this on Friday ahead of his holiday this week but the PR hadn't completed its Jenkins jobs. One of the review comments he had (sent on Slack) was that the system tests weren't passing so we thought it best to wait rather than him just approve it ahead of the jobs finishing.

The jobs have now all succeeded so I think this is fine to just have a look over the changes and approve - if you're uncomfortable doing that then no problem to give it the full test\review yourself.

**Comment by DanielMurphy22** [comment]
> @DanielMurphy22 - if you have a bit of time today please can you review this PR? Richard got 95% of the way through reviewing\approving this on Friday ahead of his holiday this week but the PR hadn't completed its Jenkins jobs. One of the review comments he had (sent on Slack) was that the system tests weren't passing so we thought it best to wait rather than him just approve it ahead of the jobs finishing.
> 
> The jobs have now all succeeded so I think this is fine to just have a look over the changes and approve - if you're uncomfortable doing that then no problem to give it the full test\review yourself.

I'll take a quick look!

**Review by DanielMurphy22 — APPROVED** [review]
I tested the PR quickly myself and it looks good to me!

**Pull request merged**
