### PR TITLE
Upgrade Poco to 1.6.1 on Windows

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

All other platforms have Poco 1.6.x. #25684 requires `RecursiveDirectoryIterator` that appeared in v1.5.

**To test:**

If Windows builds pass then this is good as Poco is linked at a very low level.

*There is no associated issue.*

*This does not require release notes* because **it is a buildconfig change.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by hsautessella** [comment]
I'm just building with the latest change, I'll let you know when that's done. 

Before your last commit however everything built fine, but I was getting some `ddl load failed` errors when trying to launch both MantidPlot and Workbench. When starting MantidPlot I get that the following dlls couldn't be found:

- `PocoFoundation64.dll`
- `gsl.dll`
- `boost_regex-mt.dll`
- `QtOpenGL.dll`

Running a dependency walker also threw up that `POCOXML64.DLL` was missing

**Comment by hsautessella** [comment]
This builds and appears to run fine on my Windows machine. I'm not sure why the test is failing

**Comment by martyngigg** [comment]
@hsautessella I think I have fixed the test build problem.

**Review by ghost — APPROVED** [review]
Builds and runs fine on Windows 👍

**Comment by OwenArnold** [comment]
This brings in an unsatisfied requirement for `PocoJSON64.dll` on windows. The packages are currently broken.

**Comment by hsautessella** [comment]
I think Martyn's at the conference today. I'll have a look into it

**Comment by martyngigg** [comment]
I think @mantid-roman is looking at this?

**Pull request merged**
