### PR TITLE
Refs #11020 Create projection type

### PR DESCRIPTION
**Pull request by eXeC64**
This is for trac ticket: http://trac.mantidproject.org/mantid/ticket/11020

In this pull request we:
- Add a new class, `Projection`
- Add a unit test for the class
- Add python bindings to the class
- Add a unit test for the python bindings
- Update the `CutMD-v1` usage example.
- Fix some indentation in `Geometry/CMakeLists.txt`

### CODE REVIEW

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
Jenkins, test this please.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
Jenkins, test this please.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
Jenkins, test this please.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by AndreiSavici** [comment]
15:25:54 /home/builder/jenkins-linode/workspace/pull_requests/label/rhel6-build/Code/Mantid/Framework/PythonInterface/mantid/api/src/Exports/Projection.cpp: In function ‘void export_Projection()’:
15:25:54 /home/builder/jenkins-linode/workspace/pull_requests/label/rhel6-build/Code/Mantid/Framework/PythonInterface/mantid/api/src/Exports/Projection.cpp:63: error: #pragma GCC diagnostic not allowed inside functions
15:25:54 /home/builder/jenkins-linode/workspace/pull_requests/label/rhel6-build/Code/Mantid/Framework/PythonInterface/mantid/api/src/Exports/Projection.cpp:92: error: #pragma GCC diagnostic not allowed inside functions

**Comment by martyngigg** [comment]
The `GCC_DIAG` calls need to be outside the function.

**Comment by AndreiSavici** [comment]
Here are a few problems:
1. In Horace, people are used to have only two projections, each of them a 3D vector. So you give u=VMD(1.,0,0.) and v=VMD(0.,1.,0.). The w projection is calculated automatically
2. I am in mantidplot, I generated py projection p=Projection(u,v), and I want to convert it to a table workspace, so I run x=p.toWorkspace(). The table workspace does not show up. I need to explicitly add it to the ADS with AnalysisDataService.add('x',x)
3. The table is confusing. The u and v vectors are shown as columns. The type is also shown as a column, but each componnent is ligned up with a compoinent of u or v. The type corresponds to the entire u vector or entire v vector, not to one component. Maybe it should look like

Name | Value
--------|---------
u     |  1 , 0 , 0
v     |  0 , 1 , 0 
type|  r   r  r

Obviously I lost the third components of u and v when I defined only two 3D vectors

**Comment by eXeC64** [comment]
@AndreiSavici Ah, I was following these while creating the type:
* https://github.com/mantidproject/documents/blob/master/Design/VATES/MantidHorace/syntax-proposal.md#examples
* http://horace.isis.rl.ac.uk/Manipulating_and_extracting_data_from_SQW_files_and_objects

The format of the table itself is as expected by the `CutMD` algorithm: http://docs.mantidproject.org/nightly/algorithms/CutMD-v1.html (see the usage example specifically)

Changing the format of the table will require changing the format expected by CutMD, which is backwards incompatible.

Any ideas on how to proceed?

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
**Notable changes**:
* The table's schema has changed. `CutMD` has been updated in a backwards incompatible way to reflect this.
* `Projection` in python now has `.u`, `.v`, and `.w` accessors, and accepts python lists as well as VMDs in all relevant methods and constructors.
* The initial value of the projection is now an identity matrix, i.e. for 3 dimensions: `u = [1,0,0]`, `v = [0,1,0]`, `w = [0,0,1]`.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by abuts** [comment]
Jenkins retest this please

**Comment by AndreiSavici** [comment]
I still want to create a projection based on 2 3D vectors
```
a=Projection(VMD(2,2,2),VMD(1,0,0))
```
This will not give me a.w (ValueError: invalid axis), which is wrong, and I cannot change the value of the type for the third axis. 

In all cases, the number of vectors has to be equal to the number of dimensions. So if I use VMDs of dimension 3, I need to get u,v,w, even if I initialize it with only 2 vectors. In that case w=u x v, where x is the cross product

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

Ubuntu and OSX succeeded on the first build. Fedora, RHEL6 and Win7 failed to checkout.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Pull request merged**
