### PR TITLE
Fixing usability issues for reducing HFIR data from SPICE file

### PR DESCRIPTION
**Pull request by wdzhou**
This is originally ticket #11282(http://trac.mantidproject.org/mantid/ticket/11282).

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by wdzhou** [comment]
Retest please.

**Comment by wdzhou** [comment]
Jenkins, retest this please

**Comment by wdzhou** [comment]
Tester: 

Here is the list of item that you can check against the requests for this ticket:

1.  LoadSpiceAscii should not require date time format: 
  - A default value is set to property DateAndTimeLog. The default value is of current HFIR's standard;
2. ConvertSpiceDataToRealSpace creates an MD workspace with Y min and max limits both 0:
  - This issue will be resolved in ticket [#11288](http://trac.mantidproject.org/mantid/ticket/11288). 
3. ConvertCWPDMDToSpectra is a weird name. It should at least be explained in the documentation: 
  - Check the documentation and this algorithm's summary.  The issue is addressed
4.Binning parameters must contain 3 numbers. People might be used to Rebin, that can also use one value. Minimum and maximum can be calculated:
  - Minimum value and maximum value can be determined automatically.  To test, you can run the script attached in the next comment.  The difference between the diffraction pattern with min/max given or not should have very small difference.
5. There is a weird warning message "Unable to set unit to an Unit::Empty object." The reason is that the "Degrees" unit is not registered:
  - 'Degree' is added.  You can check unit test and the result in the script next.

**Comment by wdzhou** [comment]
Test script:  test file 'HB2A_exp0231_scan0001.dat' can be found in unit test. 

LoadSpiceAscii(Filename='HB2A_exp0231_scan0001.dat', DateAndTimeLog='date,MM/DD/YYYY,time,HH:MM:SS AM', OutputWorkspace='HB2A_exp0231_scan0001_DataTable', RunInfoWorkspace='HB2A_exp0231_scan0001_Log')

ConvertSpiceDataToRealSpace(InputWorkspace='HB2A_exp0231_scan0001_DataTable', RunInfoWorkspace='HB2A_exp0231_scan0001_Log', OutputWorkspace='HB2A_exp0231_scan0001_DataMD', OutputMonitorWorkspace='HB2A_exp0231_scan0001_MonitorMD')

ConvertCWPDMDToSpectra(InputWorkspace='HB2A_exp0231_scan0001_DataMD', InputMonitorWorkspace='HB2A_exp0231_scan0001_MonitorMD', 
    BinningParams='5,0.1,150', OutputWorkspace='TTheta', NeutronWaveLength=2.4100000000000001)

ConvertCWPDMDToSpectra(InputWorkspace='HB2A_exp0231_scan0001_DataMD', InputMonitorWorkspace='HB2A_exp0231_scan0001_MonitorMD', 
    BinningParams='0.1', OutputWorkspace='TTheta2', NeutronWaveLength=2.4100000000000001)

    
ConvertCWPDMDToSpectra(InputWorkspace='HB2A_exp0231_scan0001_DataMD', InputMonitorWorkspace='HB2A_exp0231_scan0001_MonitorMD', 
    BinningParams='0.5,0.01, 30.0', OutputWorkspace='Dspace', NeutronWaveLength=2.4100000000000001, UnitOutput='dSpacing')

ConvertCWPDMDToSpectra(InputWorkspace='HB2A_exp0231_scan0001_DataMD', InputMonitorWorkspace='HB2A_exp0231_scan0001_MonitorMD', 
    BinningParams='0.01', OutputWorkspace='Dspace2', NeutronWaveLength=2.4100000000000001, UnitOutput='dSpacing')
    
ConvertCWPDMDToSpectra(InputWorkspace='HB2A_exp0231_scan0001_DataMD', InputMonitorWorkspace='HB2A_exp0231_scan0001_MonitorMD', 
    BinningParams='0.5,0.01, 30.0', OutputWorkspace='Q', NeutronWaveLength=2.4100000000000001, UnitOutput='Momentum Transfer (Q)')

ConvertCWPDMDToSpectra(InputWorkspace='HB2A_exp0231_scan0001_DataMD', InputMonitorWorkspace='HB2A_exp0231_scan0001_MonitorMD', 
    BinningParams='0.01', OutputWorkspace='Q2', NeutronWaveLength=2.4100000000000001, UnitOutput='Momentum Transfer (Q)')

**Comment by wdzhou** [comment]
Retest this please.

**Comment by AndreiSavici** [comment]
The code is very complicated. It reimplements Rebin, InterpolatingRebin, Scale. It can be reduced by at least a factor of 3, and made more readable. I have created ticket [#11399] (http://trac.mantidproject.org/mantid/ticket/11399) to deal with this issue

**Pull request merged**
