### PR TITLE
Add Project Serialisation Tests

### LINKED ISSUE #16719: Add some tests for existing project loading & saving.
Had a quick discussion with Martyn. We're pretty limited with what we can do as things in this section of the project depend too much on GUI components. 

The plan is to expose some additional methods to Python (such as what has already been done with saveProjectAs) and test it that way. Then we can at least check that the .mantid file is written out correctly and that workspaces etc. are loaded back in correctly.

### PR DESCRIPTION
**Pull request by samueljackson92**
Added some automated Python tests for saving and loading Mantid project files. These tests are far from perfect and comprehensive, but they are a start. We are limited by the current project save/loading code being tightly mixed with the application window class. Until that code is refactored we cannot do a huge amount more.

**To test:**
Build the project and run the new suite of tests using the following command. Be sure that they all pass.

```
ctest -R MantidPlotProject -V
```

Closes #16719.

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
It now works for me.

**Comment by ElliotAOram** [comment]
This also works for me (all tests pass). Code changes look good and the tests are extensive and well documented.  :shipit:

**Comment by FedeMPouzols** [comment]
Great to see those tests in place! @samueljackson92: if when you're working on this you see the chance to move some stuff out of `ApplicationWindow.cpp` I'd say just go ahead. That file is seriously bloated and there's no need to keep the old approach of "everything goes into ApplicationWindow.cpp".

**Comment by samueljackson92** [comment]
@FedeMPouzols Agreed! The next ticket for this (ready to go now the tests are in place!) is #16769 which pulls out much of the project load/save code into a new class with some light refactoring.

**Pull request merged**
