### PR TITLE
Project Recovery: Use a counter to save workspaces instead of name

### LINKED ISSUE #23258: Project Recovery: Instead of using the ws namessz, we should save them using a counter
### Expected behavior
Every workspace saved by project recovery should save using a counter and not the workspace name.

### Actual behavior
It saves using the workspace name

### PR DESCRIPTION
**Pull request by Pasarus**
**Description of work.**
Replaced workspace names when saving with a counter for the number of workspaces that have already been saved

**To test:**
- Load a workspace
- Wait for workspace to be saved
- Check .mantid/recovery/computername/mostrecentcheckpoint/ and see that there should be a 0.py instead of the workspace name
- Retry with multiple workspaces

Fixes #23258  

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by keeeto — CHANGES_REQUESTED** [review]
This issue seems to contain some commits from PR #23252, which is still under review.

**Comment by Pasarus** [comment]
@keeeto Legacy commits are now no longer in this PR

**Comment by DanNixon** [comment]
@Pasarus Could you remove the old commits with an interactive rebase rather than generating more commits, this will help keep the commit history clean.

**Comment by DanNixon** [comment]
Why was the previous behavior an issue?

**Comment by Pasarus** [comment]
The previous behavior is an issue as with saving project recovery, it will save over if two workspaces have the same name, say Group and other name would have saved in the same file and thus overwrote. Also with planned changes to project recovery with regards to running mantid in multiple instances and potentially with gracefully handling live data, basically it was a design decision made before I took over but I understand why it is being made.

**Review by DanNixon — CHANGES_REQUESTED** [review]
Looks good.

Just a merge conflict to resolve and ideally squash to a single commit.

**Comment by Pasarus** [comment]
Merge conflict resolved, why would I squash it to a single commit?

**Comment by DanNixon** [comment]
- This is one logical unit of work that does not require being split into multiple commits
- The multiple commits you do have are iterations of this piece of work that hold no value after this branch is merged

Also your commit messages give no insight into why you are doing the change.

**Comment by Pasarus** [comment]
Squashed and resolved

**Review by keeeto — APPROVED** [review]

**Comment by Pasarus** [comment]
@DanNixon Is there anything else you want handled for this?

**Review by DanNixon — APPROVED** [review]

**Pull request merged**
