### PR TITLE
Abins minor fixes

### PR DESCRIPTION
**Pull request by dymkowsk**
Changes in AbINS GUI
1) Temperature -> TemperatureInKelvin
2) Add field BinWidthInWavenumber, add system test for it.

Systemtest: AbinsBinWidth

Fixes #xxxx. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — COMMENTED** [review]
@dymkowsk As far as I can tell the default values for temperature and bin width have not change. If this is the case why did some of the system tests need updating?

**Comment by dymkowsk** [comment]
@martyngigg  that's true I haven't changed bin width and temperature for currently existing tests. I have removed   bin_width from scripts/AbinsModules/AbinsParameters.py. Since it is accessible now from GUI it should not be accessible any longer from AbinsParameters.py. While reading ab initio parameters every ab initio loader calculates hash of AbinsParameters.py. In case there is any data in hdf file and previous hash is the same as the current hash data from hdf file are re-used in the calculations. 

During the tests hash for AbinsParameters.py from reference and current calculations is compared. If they are different the test fails. By modifying AbinsParameters.py I broke my tests for ab initio loaders. For each test I have to update corresponding *_data.txt file.

**Comment by dymkowsk** [comment]
@martyngigg  I have also added one system test for bin width different than default:  AbinsBinWidth.

**Comment by martyngigg** [comment]
@dymkowsk I see. Thanks for the explanation.

**Comment by martyngigg** [comment]
@dymkowsk One final question is whether we are okay to break scripts that are using the `Abins` command and specifying `Temperature` as a keyword?

**Comment by dymkowsk** [comment]
@martyngigg Sanghamitra said that it is Ok (see email for more details).

**Comment by martyngigg** [comment]
Thanks, @dymkowsk

**Review by martyngigg — APPROVED** [review]
This is good to go.

A set of minor changes and mostly test updates.

**Pull request merged**
