### PR TITLE
Remove change to histogram in IqtFit

### LINKED ISSUE #32478: IDA fitting tabs do not use the first point when fitting
In the Indirect Data Analysis fitting tabs the fit results do not cover the first point in the data even is startX is equal to the start value in the data. this can also happen with the last point as well.

### PR DESCRIPTION
**Pull request by Harrietbrown**
**Description of work.**
This commit removes the conversion to histogram in IqtFit. It is not clear why this is done as all it ends up doing is stopping the fit from using the first value.
It also adds rounding to the ranges given to QENSFitSequential in IDA to stop the same issue in other tabs

**Report to:** @SpencerHowells

**To test:**

1. open Indirect Data Analysis Iqtfit tab
2. Load irs26176_graphite002_iqt spectra 0
3. set Exponentials to 1 and endX to 0.20
4. click run
5. show data on workspace `irs26176_graphite002_iqt_IQt_seq_1E_0_0_Workspace`
6. check that the first X value is the same as on workspace `irs26176_graphite002_iqt`

As well as this, in the other fit tabs, load data and attempt to fit using the default ranges, check that it includes the first and last data points.

Fixes #32478

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by sf1919** [comment]
There seems to be a lot of code removed from IqFit algorithm. Is this because the work is being done elsewhere?

**Comment by SpencerHowells** [comment]
@sf1919 If I remember correctly, when we upgraded the 4 Fit guis IqtFit was not finished. So this may be left over from that.

**Comment by Harrietbrown** [comment]
> There seems to be a lot of code removed from IqFit algorithm. Is this because the work is being done elsewhere?

The code thaty was removed does not seem to serve any function and it introduces the issue with the missing startX

**Review by sf1919 — APPROVED** [review]
I have undertaken a functional test of this PR and confirms it all works and the other fitting tabs also work as expected. 

Whilst I was concerned about the quantity of code being removed @Harrietbrown has confirmed that it served no purpose and was actually causing the problem seen in the original issue. As I have confirmed through a functional test that the IqtFit still works I'm happy to approve.

**Comment by gemmaguest** [comment]
@Harrietbrown It was requested to report this to @SpencerHowells when merged

**Pull request merged**
