### PR TITLE
Space group systematic absences

### LINKED ISSUE #12749: Extend SpaceGroup to check if a reflection is systematically absent
Symmetry operations with translational components result in systematic absences in certain groups of reflections. While it's possible to check this using knowledge of the crystal structure (atoms in the unit cell) to calculate structure factors, it's also possible to use the symmetry operations of a space group to check if a reflection is compatible with this group. This would also be a first step on a way towards space group determination from a list of reflections and information about their intensities.

The following teaching pamphlet from the IUCr-Website explains how to check for allowed reflections in section 5: http://www.iucr.org/education/pamphlets/9/full-text.

### PR DESCRIPTION
**Pull request by MichaelWedel**
This fixes #12749.

**Testing information**
Code review. Documentation has been updated with a new usage example at the end - please check the new paragraphs and new examples. If you want to play with different space groups, the following script produces a list that can replace the `reflections` variable in the usage example:

```
# Arbitrary parameters, lattice parameters are corrected by the algorithm, i.e. only a is used for cubic etc.
parameters = {
   'Atoms': 'Fe 0.3421 0.5312 0.7222',
   'a': 5.632, 'b': 6.121, 'c': 7.832,
   'Alpha': 101.5, 'Beta': 102.3, 'Gamma': 100.75,
   'LatticeSpacingMin': 0.75
}

spaceGroup = 'P 42/n n m'
spaceGroupWithoutTranslations = 'P 4/m m m'

allReflectionsWs = PoldiCreatePeaksFromCell(SpaceGroup=spaceGroupWithoutTranslations, **parameters)
sgReflectionsWs = PoldiCreatePeaksFromCell(SpaceGroup=spaceGroup, **parameters)

allHKLs = [[int(m) for m in x.split()] for x in allReflectionsWs.column(0)]
sgHKLs = [[int(m) for m in x.split()] for x in sgReflectionsWs.column(0)]

reflections = []
for hkl in allHKLs:
   reflections.append((hkl, hkl in sgHKLs))

# Adjust space group range in usage example, for above example it would be range(123, 143)
```

This script can be adjusted to be used with all space groups registered in Mantid. You have to supply the space group for which you would like to generate the "observed status" list, in the above example `P 42/n n m`. Then you need to supply the corresponding space group with no translations (replace all screw axes by rotation axes, all glide planes by mirror planes, select primitive centering). Adjust the range of checked space groups to include all those that belong to the same point group (I realize that there should be an easier way to do this using the factory, I'll make a ticket for that later).

Other examples would be (`F d d d` or `P b c a` or `C m c m`) and `P m m m` with range `47-75`. 

If you modify the atom position to `0 0 0`, many pairs will stop working, because that is a special position in many space groups and having the atom on that position introduces additional reflection conditions, which can be mistaken as different space group. One such space group is `P b c a`, where an atom on `0 0 0` adds the condition `h+k, h+l, k+l=2n`, which is the same as for an F-centering, so the algorithm finds `F m m m` instead.

### CODE REVIEW

**Comment by MichaelWedel** [comment]
Just discovered a last thing I would like to verify.

**Comment by MichaelWedel** [comment]
International Tables were more clear than the teaching document in that the reduced translation operation has to be used. Code to derive that was in SymmetryElementFactory, but was simple to move over to SymmetryOperation. This is covered by the unit tests for both.

**Comment by FedeMPouzols** [comment]
All looks good and the examples behave well locally too. I'd just suggest adding the practical tips and explanations given here in the tester info somewhere in the documentation, if that's not already included elsewhere.

**Comment by MichaelWedel** [comment]
Yes, that may be useful. For now I just thought it could be a bit overwhelming.

I'm planning on making point and space group playing together in a better way, so that one could for example write `SpaceGroupFactory.subscribedSpaceGroupsWithPointGroup('m-3m')` and get back a list of all space groups which belong to that point group. Then the need to specify a range for the space groups to test would disappear and the usage example would get simpler. Similar story with the space group without translations, it should be possible to do that automatically.

Once these things are done, I will expand the usage example. It could also be a good idea to use real, measured reflections for an example at some point - unfortunately I don't have anything available...maybe something from a single crystal beamline?

**Pull request merged**
