### PR TITLE
Add weighted ls fitting system tests.

### LINKED ISSUE #13348: Add Fit systemtest
Add further Fit systemtest to expose the level of fitting we want to support within Mantid. This is systemtests in addition to those already provided by specific instrument workflows, i.e. generic systemtest of the kind provided already provided by `UnweightedLeastSquaresTest.py`. 

Here suggest to do this in systemtest `WeightedLeastSquaresTest.py` to complement those in `UnweightedLeastSquaresTest.py`

Either test in these two systemtests may also include not-happy path examples, i.e. example where fitting current is not supported

### PR DESCRIPTION
**Pull request by Anders-Markvardsen**
Fixes #13348
### To test
- check that systemtest pass
- check that text in systemtest reads well and is clear
- check 1st good example added to this test

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
@Anders-Markvardsen : pylint has found a few issues: http://builds.mantidproject.org/job/pull_requests-pylint/2964/violations/file/WeightedLeastSquaresTest.py/

- pylint doesn't like variable names as short as two characters.
- Also, in python methods the naming convention ([PEP 8](https://www.python.org/dev/peps/pep-0008/))  is to use lowercase and  `_ `to separate words, which is a bit confusing when compared to C++ Mantid code.
- There's also a "too few public methods" absurd warning that you can fix with a line like this:
`#pylint: disable=too-few-public-methods` (you can put it at the beginning of the file or right before the class that has "too few public methods").

There's this wiki page to help with pylint issues: http://www.mantidproject.org/How_to_fix_Pylint_Warnings

**Comment by Anders-Markvardsen** [comment]
@FedeMPouzols thanks for pointing out about the pylint warnings

**Comment by FedeMPouzols** [comment]
@Anders-Markvardsen : the system test fails on rhel7. This looks like another case of the issue of the platform dependency/sensitivity of the fitting results. This assert fails: https://github.com/mantidproject/mantid/pull/14278/files#diff-43d846c33dc35792217d0d3924f03cd9R101 because "Exception: Expected 0.016129 == 0 within +- 0.01."
This would be similar to what I've seen also with some EnginX system tests. Fitting results can easily differ by ~5% between windows and linux. Worryingly, the difference from osx results can be much bigger if we get unlucky.

**Comment by FedeMPouzols** [comment]
@Anders-Markvardsen : The test fails this comparison (line 101): `Exception: Expected 0.016129 == 0 within +- 0.01.` and it seems that we just get slightly different fitted curve and errors. The `f0` `sigma` is `3.0277910994217546e-07` on windows but `3.07662643974e-07` on linux. I think that as you suggested we could just add this different value as an exception when the platform is linux. Alternatively the delta of the assert could be increased. See pasted down here the fit that I get on linux. It looks acceptable but the solution is different from what you get on windows.
systest_gaussians_fit

These are the output parameters on linux (from the MantidPlot table):
```
f0.Height	0.117909	0.0065566
f0.PeakCentre	0.000373336	3.02155e-07
f0.Sigma	4.75098e-06	3.07663e-07
f1.A0	0.00272567	0.00238358
f1.A1	-4.49458	5.99646
f2.Height	0.129863	0.00305933
f2.PeakCentre	0.000166466	6.63275e-07
f2.Sigma	2.61623e-05	7.70707e-07
Cost function value	1.02614	0
```

Which seems almost identical. The only non negligible difference that I could spot is in the `sigma` of `f0`. And looking at the numbers in detail:
```
for i in range(0, out4.rowCount()):
    print "{0} {1} {2}".format(out4.cell(i, 0), out4.cell(i,1), out4.cell(i,2))

f0.Height 0.117909282703 0.00655660314596
f0.PeakCentre 0.000373335595991 3.02154605841e-07
f0.Sigma 4.75098350333e-06 3.07662643974e-07
f1.A0 0.00272566650403 0.00238358279546
f1.A1 -4.49458001081 5.99646342045
f2.Height 0.129862991665 0.00305932888338
f2.PeakCentre 0.00016646632366 6.63275253126e-07
f2.Sigma 2.61623001901e-05 7.70707080501e-07
Cost function value 1.02613981924 0.0
```


I run this manually to get these fitting results:
```
wks = Load(Filename='EVS14188-90_processed.txt')
Fit(Function='name=Gaussian,Height=0.0271028,PeakCentre=0.000371946,Sigma=1e-05;name=LinearBackground,A0=0,A1=0;name=Gaussian,Height=0.0979798,PeakCentre=0.000167,Sigma=1.7267e-05', InputWorkspace=wks, Minimizer='Levenberg-Marquardt', CostFunction="Least squares", CreateOuptut=True, Output='out_')
```

**Comment by FedeMPouzols** [comment]
Here are some interesting observations on what are the differences on osx (compared against windows and rhel7) for this simple fitting of a couple of Gaussian peaks.

I run this on an osx machine and as we could expect there are some numerical differences which make both tests fail like this:

```
Fit-[Notice] Fit successful, Duration 0.03 seconds
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/builder/Jenkins/workspace/master_clean-osx/Testing/SystemTests/lib/systemtests/stresstesting.py", line 200, in execute
    self.runTest()
  File "WeightedLeastSquaresTest.py", line 76, in runTest
    self.assertDelta(err / expected - 1.0, 0.0, 1e-2)
  File "/Users/builder/Jenkins/workspace/master_clean-osx/Testing/SystemTests/lib/systemtests/stresstesting.py", line 403, in assertDelta
    raise Exception(msg)
Exception: Expected 0.0117647 == 0 within +- 0.01.
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/builder/Jenkins/workspace/master_clean-osx/Testing/SystemTests/lib/systemtests/stresstesting.py", line 200, in execute
    self.runTest()
  File "WeightedLeastSquaresTest.py", line 99, in runTest
    self.assertDelta(err / expected - 1.0, 0.0, 1e-2)
  File "/Users/builder/Jenkins/workspace/master_clean-osx/Testing/SystemTests/lib/systemtests/stresstesting.py", line 403, in assertDelta
    raise Exception(msg)
Exception: Expected -0.015873 == 0 within +- 0.01.
```

So both tests go slightly above the 1% tolerance.
The differences are very small (after digits 5, 6 or more), except for a few values in the expected errors.

- For test 1 the expected values based on windows (and working on linux too) are: 
```
expected_params = [-0.02830944965319149, 0.0003966626475232753, 3.2690103473132937e-06, 0.04283560333422615,
    -82.49982468272542, 0.13971885301153036, 0.00016591941312628293, 9.132514633819799e-06]
expected_errors = [0.007480178355054269, 9.93278345856534e-07, 9.960514853350883e-07, 0.0017945463077016224,
     4.9824412855830404, 0.004955791268590802, 3.695975249653185e-07, 3.8197105944596216e-07]
```
But what you get on osx is:
```
Test1 On osx, params: [-0.028309449653191505, 0.0003966626475232753, 3.269010347313293e-06, 0.04283560333422614, -82.4998246827254, 0.13971885301153036, 0.00016591941312628293, 9.1325146338198e-06]
Test1 On osx, errors: [0.007480178355054263, 9.932783458565333e-07, 1.0077697381037357e-06, 0.0017945463077016228, 4.9824412855830404, 0.0049557912685908, 3.6959752496531844e-07, 3.8197105944596205e-07]
```
Where the only relatively large difference is in the 3rd error val: 1.0077697381037357e-06 on osx,  elsewhere 9.960514853350883e-07. **That is the error in the A0 parameter of the linear background**.

- For test 2, the expected values based on windows (and working on linux too) are:
```
expected_params = [0.117909282702681, 0.0003733355959906781, 4.750983503334754e-06, 0.002725666504029797,
     -4.494580010809393, 0.12986299166539694, 0.00016646632365980064, 2.616230019006275e-05]
expected_errors = [0.00655660314595665, 3.021546058414827e-07, 3.0766264397350073e-07, 0.0023835827954566415,
     5.996463420450547, 0.003059328883379551, 6.632752531256318e-07, 7.707070805005832e-07]
```
But what you get on osx:

```
Test2 On osx, params: [0.11790928270268092, 0.0003733355959906781, 4.750983503334757e-06, 0.0027256665040297796, -4.494580010809386, 0.129862991665397, 0.00016646632365980064, 2.6162300190062943e-05]
Test2 On osx, errors: [0.006556603145956653, 3.0215460584148305e-07, 3.027791099421756e-07, 0.002383582795456668, 5.9964634204505805, 0.0030593288833795453, 6.632752531256348e-07, 7.797742226241165e-07]
```
There are only two relatively large different error values:
3rd error val: 3.027791099421756e-07 osx,  3.0766264397350073e-07elsewhere,
8th error val: 7.797742226241165e-07 osx,  7.707070805005832e-07 elsewhere.
**That is the errors in the sigma parameters of both peaks**.

**Comment by FedeMPouzols** [comment]
@Anders-Markvardsen : I've pushed a commit with exceptions for three expected values which change on osx. The aim is to prevent the usual failure of the osx nightly build from happening this time.

@martyngigg : interestingly @Anders-Markvardsen found that after upgrading to MSVC 2015 the win7 results are closer to those of linux. This checks a simple fitting of a couple of Gaussian peaks. There are two tests: the first is a bad fit because of poor initial values, the second fit works better.
osx still disagrees, but the disagreement is only in the error estimates not in the parameters fitted. All the parameters are fitted exactly the same up to 1e-5, whereas we have >1e-2 errors in the error estimates of three parameters (A0 of a linear background in the first failed fit, and the sigmas of two peaks in the good fit).

**Comment by FedeMPouzols** [comment]
Well, being strict I shouldn't merge this as I added a commit, but it definitely looks safe to merge. It is good to have this type of tests on the basics of fitting functionality rather sooner than later. Let's see if it finally runs correctly on all platforms tonight.

**Pull request merged**
