### PR TITLE
ISIS SANS Usability Fixes

### LINKED ISSUE #26808: SANS GUI Usability Problems
**Original reporter:** ISIS/Richard

Multiple usability regressions from the previous SANS GUI has been noted in the new one. This can make it clunky to use in comparison.

- [x] Run number boxes require multiple clicks (especially when entering a number then clicking the next box
- [x] Opening the load user file with one already selected does not pre-select that file in the dialogue box
- [x] Q range values such as 1,2,3,4,5,6 should do 1-2, 2-3, 3-4 ...etc. this was previously supported and I can't see a good reason to take it away
- [x] Q range values drop down gives an example of `12:2:16` without an explanation of what the various terms do or control

Unsure how to tackle these, but still problems
- [x] Boxes are stretched over the screen, forcing users to scan left to right over large amounts of dead space
- [ ]

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**
Contains a number of usability fixes for the ISIS SANS Interface, as described in the testing section

**To test:**

- Open the SANS interface
- Single click any box in the table to edit it
- Attempt to tab over
- Downloading the ISIS Sample data, and extract the LOQ folder
- Open the masking file
- Re-Open the masking file and check your previous file was selected
- Do the same for the batch file

----

- Check settings -> General and Q, Wavelength tabs visually look correct 
- Check fields are still populated correctly (it would throw a runtime error if a field on the view is broken)
- Change the wavelength box to RangeLin or RangeLog
- Enter something comma separated such as `1,4,5,6` 
- Rerun using the batch file to see if these are now accepted

Fixes #26808 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DavidFair** [comment]
Also we noticed if a box is already selected, you cannot re-select it to edit it

**Comment by gemmaguest** [comment]
Some more observations:
- Up/down arrows start editing, whereas they should move the selection to the prev/next row.
- Numberpad numbers don't start editing when NumLock is on (but the arrows do navigate up/down correctly when NumLock is off)
- The numberpad Return key now stops editing the current row but does not progress to the next row, which is different to Enter - previously they did the same
- `Esc` and `Backspace` both start editing and insert a special character!
- Special keys like `Insert`, `Home`/`End`, `PgUp`/`PgDown` and `NumLock` all start editing. Maybe `Insert` is ok but I don't think the others should, nor any `F` keys except `F2`.

**Comment by DavidFair** [comment]
This still has an issue where entering a number then hitting enter will cause it to vanish, as there is an interaction between the default row JobTreeView gives us, and one the UI creates

**Review by gemmaguest — APPROVED** [review]
- Code changes look good.
- All the bugs I found are fixed.
- The rest of the new functionality works as described.
- The reflectometry GUI still works well and the type-to-edit feature is a welcome addition there too.
- The background job to validate the run and set the sample thickness has been removed. This seems sensible as it has caused us a lot of grief in the past and removing it has solved a number of issues with this PR. It does mean that it now requires 2 clicks to Load or Process rather than one which is something we could potentially look at fixing in a future PR. However, for now we think that the usability improvements in this PR outweigh that disadvantage so I'm happy for this to go in. We should seek early feedback on this during beta testing.

**Pull request merged**
