### PR TITLE
Upgrade Qt to 5.15.8

### LINKED ISSUE #34820: IDAaaS Freeze and crash when Browsing to Directory with lots of files
**Original reporter:** Sarah Rogers, Adhip Rahman

**Describe the bug**
Browsing to a directory from the Manage User Directories dialog on IDAaaS can sometimes freeze Mantid. Then clicking on the X of the dialog causes Mantid to crash. This seems to happen when browsing to directories that contain a large number of files.

**To Reproduce**

For example
1. Create a Mantid workspace on IDAaaS here https://dev.analysis.stfc.ac.uk/
1. Open ISIS SANS interface
2. Click `Manage User Directories`
3. Click `Browse To Directory`
4. Browse to the following directory `/archive/NDXLARMOR/Instrument/data/cycle_22_3/`. Or another directory containing a large number of files
5. Mantid should freeze.
6. Click on the `X` for the Browse dialog and Mantid will crash

**Expected behavior**
There should be no freeze if possible, and no crash.

**Platform/Version (please complete the following information):**
 - IDAaaS

### LINKED ISSUE #35029: Unhandled exception on QPaintEvent
This is a hard to reproduce bug, but very possible to stumble across. 

The rough steps are:
- Load data and plot one spectrum. 
- Click the Fit toolbar button to open the FitPropertyBrowser
- Resize the plot window by dragging it to larger/smaller
- Then move the cursor over the plot and off and on the plot
- Eventually a mouse move event will cause the following error 

```

Traceback (most recent call last):
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\backends\backend_qt.py", line 272, in enterEvent
    *self.mouseEventCoords(event),
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\backends\backend_qt.py", line 265, in mouseEventCoords
    x = pos.x()
AttributeError: 'QPaintEvent' object has no attribute 'x'

Maybe related to this:
https://github.com/matplotlib/matplotlib/issues/11607
```
Only appears to happen on Windows 10, and not in 6.5.0. Possibly could be related to the Pyqt5.15.14 upgrade so interesting to see if the potential downgrade to 5.15.12 will solve this too!

_Originally posted by @thomashampson in https://github.com/mantidproject/mantid/issues/34945#issuecomment-1384260104_

### LINKED ISSUE #35194: Upgrade OpenSSL to 3.0.8
**Describe the outcome that is desired.**
All versions of OpenSSL v1.1.1 are being deprecated in September 2023. We need to move to a newer version of OpenSSL that is supported - v3.0.8 potentially.

**Additional context**
This may need considerable work to make code base compatible with upgraded version of OpenSSL

### LINKED ISSUE #35268: Upgrade qt version
Attempt to update qt-main to 5.15.8 and see if our tab widget rendering issues are solved. This might allow us to move to a later version of OpenSSL.

### PR DESCRIPTION
**Pull request by thomashampson**
**Description of work.**
Upgrade Qt version from 5.15.4 to 5.15.8. It was previously pinned to 5.15.4 to avoid GUI rendering problems, but these seem to have been resolved now. This is required before #34820 can be addressed.
Moving to 5.15.8 has meant that #35029 has become a problem again.

Other changes:
- Old Poco pin was holding back Qt (I think), so this has been updated. It has been restricted to avoid v1.12.2 to 1.12.4 because they added an unguarded `#define NOMINMAX` that introduced a compiler warning because we define it ourselves in WindowsSetup.cmake. They've added a guard around it on their devel branch, so it should be fine in later versions.
- Remove pin for OpenSSL. This was also required to resolve the conda environment.
- Another compiler warning cropped up on Windows to do with `strstream` depreciation, which should be fixed now.

**To test:**
This pipeline build passed all stages with no issues:
https://builds.mantidproject.org/job/build_packages_from_branch/335/
Install and test the packages from this build, see #34964 and #35029 for details about how the GUI was broken when Qt moved to 5.15.6. Check that those two issues are OK and try to break it in other ways.

Fixes #35194 
Fixes #35268 
Fixes #35029 

*This does not require release notes* because **it's a dependency update that should be invisible to the user.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by thomashampson** [comment]
> I'm not sure that this solves #35194 as I still think we have to upgrade to v3 as earlier versions will stop being supported later this year.

I think Qt 5.15.8 is forcing it above 3.0.8 anyway so we don't need to explicitly pin it ourselves.

**Review by cailafinn — COMMENTED** [review]
Seems to be working well on macOS and on Ubuntu. 

Doesn't appear to have fixed the refl resizing issue in #35354 @rbauststfc

**Comment by thomashampson** [comment]
I'm just building a new set of linux packages to check that conda build is happy after I've merged the qtconsole pinning into this branch:
https://builds.mantidproject.org/job/build_packages_from_branch/349/

**Review by sf1919 — APPROVED** [review]
This has been tested on all three operating systems and works well. The changes from #35463 have been merged in. I confirm the relevant packages have been built successfully.

Looks good to go to me.

**Comment by thomashampson** [comment]
@mantidproject/gatekeepers Can we have this merged soon. It's a pre-requisite for #34820

**Pull request merged**
