### PR TITLE
Engg fixing the unit  test settings and cover previous changes

### LINKED ISSUE #14007: Unit tests: cover last changes in EnggDiffraction GUI
Changes introduced in #13934.
For example 
- the methods that generated output focusing dir/file names.
- the logic to decide whether to use a "replacing" plot or a waterfall plot.
- I'd consider stripping an example ENGINX run file to just a few spectra and add a couple of positive tests for that small run. In these we should also test the plot actions.

### PR DESCRIPTION
**Pull request by shahrozahmed1**
Fixes #14007
- Included settings which will enable all focus tests to run where as right now they are not being carried out at all
- Cover previous changes made in focus tab

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
I've re-started the RHEL6 build which had apparently failed for unrelated reasons.

When I was checking the console output I saw this warning from the compiler on that platform:
```
15:03:12 /home/builder/jenkins-linode/workspace/pull_requests-rhel6/MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffractionPresenter.cpp: In member function ‘virtual void MantidQt::CustomInterfaces::EnggDiffractionPresenter::notify(MantidQt::CustomInterfaces::IEnggDiffractionPresenter::Notification)’:
15:03:12 /home/builder/jenkins-linode/workspace/pull_requests-rhel6/MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffractionPresenter.cpp:75: warning: enumeration value ‘PlotType’ not handled in switch
```

**Comment by shahrozahmed1** [comment]
@FedeMPouzols there are many of changes that are required here, `PlotType` is not defined in the presenter, I think that is why it is complaining but however I dont even need PlotType as a notification. I shall let you know when the branch is ready to be test.

**Comment by shahrozahmed1** [comment]
@FedeMPouzols should this pull request be deleted as all the changes that were in this branch have been covered in #14191

**Comment by FedeMPouzols** [comment]
@shahrozahmed1 : I see, all the changes were included in #14191, so I'd just close this PR saying that it's been fixed elsewhere.

**Comment by shahrozahmed1** [comment]
This issue has been fixed else where #14191

**Pull request closed without merging**
