### PR TITLE
Enable StringContainsValidator to be used in Python

### LINKED ISSUE #13316: Python Export for StringContainsValidator
The StringContainsValidator doesn't have a matching Python export. It would nice to implement this so that the validator can also be used in Python.

### PR DESCRIPTION
**Pull request by KarlPalmen**
Expose StringContainsValidator to python so it can be used in a python algorithm. This validator checks that the input string contains a certain string or all the strings in a certain list of strings as substrings.

**To test:**

Write a very simple python algorithm that uses this validator on an string property. The unit test may help you with writing this algorithm. Then run it with various values of this string property and check it fails or succeeds as expected.

Fixes #13316 . 

**Release Notes** 
To do.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by gvardany — COMMENTED** [review]
Looks good and works as expected.
I have one general suggestion, I think it would be nice also to make an overloaded constructor that accepts the string list directly, and export it to python too.

**Comment by martyngigg** [comment]
What's the state of this? @KarlPalmen Are you working on @gvardany's suggestion - I think it would be a good improvement and wouldn't be too hard to add.

**Comment by KarlPalmen** [comment]
I'm not working on @gvardany suggestion.

**Comment by martyngigg** [comment]
@KarlPalmen Do you have time to look at that now? It shouldn't require much code and as this is brand new it would be good to release it in the best state possible.

**Comment by KarlPalmen** [comment]
@martyngigg I do have a little time this afternoon for which I can work on it with your help. I'll build it over lunchtime.

**Comment by KarlPalmen** [comment]
I've attempted to make the changes, but can't quite figure out how to bind it to python. I don't understand how to bind a constructor and this is further complicated by the binding of the python strings.

**Comment by NickDraper** [comment]
@KarlPalmen This has failed on Clangformat, could you apply the patch and commit again

**Review by gvardany — APPROVED** [review]
New constructor works as nicely.

**Pull request merged**
