### PR TITLE
Ability to set load algorithm properties in DataSelector widget

### PR DESCRIPTION
**Pull request by robertapplin**
### Description of work
This PR speeds up the loading on the FqFit tab of Inelastic Data Analysis by approximately 30% by not loading the workspace history which is often unused.

This only partly fixes 36769. I have identified that the algorithm search process can be sped up - giving an additional speed improvement of approximately 60%. I will do this in separate PRs.

Part of #36769

### To test:
1. Open `Inelastic`->`QENS Fitting`
2. Open the FqFit tab
3. Click `Add Workspace`. Browse for the following dataset

```
//olympic/Babylon5/Public/RobApplin/loading/irs26176_graphite002_red_Conv_seq_2L_0-50__Result.nxs
```

5. Loading the workspace into the dialog will still take a long time, but it should be approximately 30% faster when compared to `main`

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by warunawickramasingha** [comment]
At `step 1`  `Data Analysis` option is not visible under `Inelastic` 
image

**Comment by robertapplin** [comment]
> At `step 1` `Data Analysis` option is not visible under `Inelastic` 

Ah sorry, its now called QENS Fitting!

**Comment by warunawickramasingha** [comment]
- I repeated fresh loading a couple of times and each time after browsing the file(which I have copied from //olympic/Babylon5... location into my windows machine), below UI was unresponsive for ~30 seconds. Hope that is the slowness you have mentioned to still be there under the instructions. 
image


- In addition, I randomly observed below warnings after clicking on `Add`. Hope those are not related to the changes done in this PR.

1 
image

2 
image

When I followed the same steps in `main` branch, `Data Selection` UI still got unresponsive for ~30s and seemed to give the last warning all the time.

**Comment by robertapplin** [comment]
> * I repeated fresh loading a couple of times and each time after browsing the file(which I have copied from //olympic/Babylon5... location into my windows machine), below UI was unresponsive for ~30 seconds. Hope that is the slowness you have mentioned to still be there under the instructions.

I think this slowness is expected. It should be fixed when this PR gets merged 
https://github.com/mantidproject/mantid/pull/37170

**Comment by robertapplin** [comment]
> * In addition, I randomly observed below warnings after clicking on `Add`. Hope those are not related to the changes done in this PR.

Those are some strange warnings I haven't seen before! How do you replicate them?

**Comment by warunawickramasingha** [comment]
> > * In addition, I randomly observed below warnings after clicking on `Add`. Hope those are not related to the changes done in this PR.
> 
> Those are some strange warnings I haven't seen before! How do you replicate them?

I could replicate the first warning as follows
1. click `Add Workspace`
2. browse the file
3. click `Add`
4. close the `Data Selection` UI 
5. repeat again from step 1

**Comment by robertapplin** [comment]
> * click `Add Workspace`
> * browse the file
> * click `Add`
> * close the `Data Selection` UI
> * repeat again from step 1

Thanks Waruna, this is something we definitely want to fix. It seems to happen on `main` also, so I have opened an issue to look into this problem separately #37185

Also I have opened a second issue to try improve the interface usability when it freezes #37184

**Review by warunawickramasingha — APPROVED** [review]
Given that separate issues are raised to address the issues identified during testing, I am happy to approve this!

**Pull request merged**
