### PR TITLE
Upgrade bundled version of IPython on Windows

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

This now ships the most recent version of IPython 5.x as this is the last version to support Python 2. We also include the `qtconsole` package that is now required to provide the Qt console widget.

This was requested by the Reflectometry group at ISIS in order to access the latest and greatest features possible from the IPython notebooks.

When this is merged please also merge mantidproject/thirdparty-msvc2015#42.

**Report to:** [user name]/[nobody]. 

**To test:**

Build on Windows and ensure the IPython console in MantidPlot and workbench still works.

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
Conflicts - A Haiku

```
To resolve conflicts
developer must merge
in the master branch
```

**Comment by DTasev** [comment]
Not sure if this is still going in 4.0, need an update from @martyngigg

**Comment by martyngigg** [comment]
There is currently a segfault in MantidPlot that is proving hard to track down so at the moment it is not looking good.

**Comment by martyngigg** [comment]
@DTasev This should be ready to review now.

**Review by dtasev — APPROVED** [review]
Work for me on MantidPlot and Workbench!

**Pull request merged**
