### PR TITLE
Revert "Revert "Merge release next into main""

### PR DESCRIPTION
**Pull request by robertapplin**
Reverts mantidproject/mantid#37598

### CODE REVIEW

**Review by SilkeSchomann — APPROVED** [review]
I can confirm that these changes were necessary on release-next and should also go into main.

**Comment by sf1919** [comment]
We may have to include the SciPy pin as part of this PR too. I am assuming that when #37607 gets merged in `release-next` still won't merge into main.

**Comment by robertapplin** [comment]
Did a rebase to pull in the scipy pin change

**Review by SilkeSchomann — APPROVED** [review]
I am still happy to approve these changes.

**Comment by robertapplin** [comment]
Thank you @rbauststfc !

**Pull request merged**
