### PR TITLE
Disable multiple autoprocessing processes

### PR DESCRIPTION
**Pull request by gemmaguest**
This PR adds coordination via the top level MainWindowPresenter to avoid multiple autoprocessing processes running simultaneously, which could cause errors if the user autoprocesses e.g. the same thing at the same time as workspaces would be overwritten.

**To test:**

- Open the ISIS Reflectometry interface
- Enter instrument INTER and investigation 1120015 and click Autoprocess
- Go to Batch 2 and check the Autoprocess button is disabled.
- Check that Batch 1 tab cannot be closed
- Go to the Batch menu and click New. Check that Autoprocess is disabled in the new batch.
- Pause the running autoprocessing and check that the Autoprocess buttons are all re-enabled and Batch 1 tab can now be closed.

Refs #26025

*This does not require release notes* because **it implements behaviour which was in the original GUI**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by alicerussell1 — CHANGES_REQUESTED** [review]
This is looking good, just one thing. If you are autoprocessing in Batch 0 and then switch to Batch 1 the process button in the bottom right corner is still enabled so you can have both batches processing at the same time.

**Comment by gemmaguest** [comment]
> This is looking good, just one thing. If you are autoprocessing in Batch 0 and then switch to Batch 1 the process button in the bottom right corner is still enabled so you can have both batches processing at the same time.

It's intentional that you can still process in the second batch while processing or autoprocessing is running in another batch. This is what the old GUI did. It can cause confusing results if processing the same runs in two batches but that should be ok (users are unlikely to do this) as long as it doesn't crash. @Pasarus - can you see any problems with this based on the problems you saw with autoprocessing the same thing in two different batches?

**Comment by Pasarus** [comment]
I will have a look to see if this is an issue now. @gemmaguest

**Comment by Pasarus** [comment]
With the first batch running auto process on workbench, and the second batch processing the GUI has frozen and won't process anything more, however it has not crashed:
image

This does not happen with MantidPlot:
image

This is likely an extension of the problem in workbench caused by the Python GlobalInterpreterLock (GIL). So it is not a Reflectometry issue, but a wider Mantid Workbench problem.

**Comment by gemmaguest** [comment]
Instead of the frozen GUI in workbench, I got a crash doing the same thing in MantidPlot. However, this is an existing issue and is reproducible in v4.0.0. It's actually a problem with the algorithm and I've raised issue #26070 to deal with it. I don't think this needs to be done for this release.

**Review by alicerussell1 — APPROVED** [review]

**Pull request merged**
