### PR TITLE
Crystal fields bugfixes

### LINKED ISSUE #18490: Crystal Fields bugfixes
This is a general issue for quick bugfixes to the Crystal Field calculations in Mantid, in preparation for release 3.9.

Identified issues from user testing are: (more issues will be added as they are identified).

1. No way to set `Lambda` parameter for `CrystalFieldSusceptibility` in Python.

2. Cannot remove ties previously set using the Python interface. [see also #18518 ]

3. Change Doctests to be more robust.

### PR DESCRIPTION
**Pull request by mducle**
Fixes some bugs found in testing of the new crystal field functionalities. In particular it fixes a bug in the doctests which uses a fitting example, but gave too exact output of the fitted variables.

**To test:**

Fixes #18490 .

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@mducle Unfortunately 3 of the other tests have failed: http://builds.mantidproject.org/job/pull_requests-ubuntu/11869/

**Comment by martyngigg** [comment]
@mducle I wonder if it might be better to not expect exact answers here and say something more like we did with `EstimateFitParameters` and accept anything and tell users that their output should look similar but not exactly the same: https://raw.githubusercontent.com/mantidproject/mantid/master/docs/source/algorithms/EstimateFitParameters-v1.rst

The doc tests are not there to verify numbers really more that the workflow still works.

**Comment by mducle** [comment]
@martyngigg Yes. I think you're right. I'll make the changes.

**Comment by martyngigg** [comment]
@mducle The last run of the doctests seems to give a different sign for one of the values: http://builds.mantidproject.org/job/pull_requests-ubuntu/11886/testReport/docs/fitfunctions_CrystalFieldHeatCapacity/ExampleCrystalFieldHeatCapacity/

**Comment by mducle** [comment]
@martyngigg Yes. I was hopping that it would get the sign the same... The problem is that the heat capacity only depends on the energy levels, but in this case only two energy levels really contribute to the heat capacity below 300K, whilst there are three energy levels in total. So the position of the third energy level can vary by anything, which means the crystal field parameters which affects that energy level but not the one contributing to the heat capacity can vary wildly. I've just changed it so there's no more output to compare to. So as long as the code runs without error it will pass the test.

**Comment by martyngigg** [comment]
@mducle Unfortunately now the tests fail because there is no output!

I think we'll either have to specify that absolutely any output is acceptable (using the ellipsis) or remove the print statements from the example.

**Comment by mducle** [comment]
@martyngigg Doh! Sorry. I'll use the ellipsis.

**Comment by martyngigg** [comment]
LGTM to fix the failing PR builds.

:shipit:

**Pull request merged**
