### PR TITLE
fix scd calib issues

### LINKED ISSUE #16199: SCD calibration issues
Fix issues found by instrument scientists testing SCDCalibratePanels

- [x] - When lattice parameters are entered, the calibration is worse.

- [ ] - Lattice should also be optimized and match input to 3-4 decimal places

- [ ] - Fix width, height, and t0 on first pass (t0 and l0 are correlated)

- [ ] - Label Row, Col and Tof spectra with # peaks and RMSD in mm

- [x] - Ignore peaks on edges

- [ ] - Check how depth and detd are used and if they are correct after optimization

- [ ] - Slow (4-5 minutes) for MANDI 

- [x] - XML output not correct from parallel region

### PR DESCRIPTION
**Pull request by VickieLynch**
Description of work.
Fixes the following problems found by instrument scientist:
When lattice parameters are entered, the calibration is worse.
Ignore peaks on edges with parameter EdgePixels.
XML output not correct from parallel region (XmlFilename)

**To test:**
https://www.dropbox.com/s/uv3c4t6pddch458/Si2mm_Cubic_F_I_20.integrate?dl=0
https://www.dropbox.com/s/ozciwztjyig7rm7/Si2mm_Cubic_F.mat?dl=0

``` Python
LoadIsawPeaks(Filename='Si2mm_Cubic_F_I_20.integrate', OutputWorkspace='Si2mm_orig')
LoadIsawUB(Filename='Si2mm_Cubic_F.mat', InputWorkspace='Si2mm_orig')
num,err=IndexPeaks(PeaksWorkspace='Si2mm_orig',RoundHKLs=False)
print "Original peaks file: number indexed, error indexing = ", num,err
wksp=mtd['Si2mm_orig']
lattice = wksp.sample().getOrientedLattice()
print "lattice, errors = ", lattice.a(),lattice.b(),lattice.c(),lattice.alpha(),lattice.beta(),lattice.gamma(),lattice.errora(),lattice.errorb(),lattice.errorc(),lattice.erroralpha(),lattice.errorbeta(),lattice.errorgamma()
print "U = ",lattice.getU()
print "B = ", lattice.getB()
LoadIsawPeaks(Filename='Si2mm_Cubic_F_I_20.integrate', OutputWorkspace='Si2mm')
SCDCalibratePanels(PeakWorkspace='Si2mm', a=5.430710,b=5.430710,c=5.430710,alpha=90,beta=90,gamma=90,
    useL0=True, usetimeOffset=True,usePanelWidth=True, usePanelHeight=True, usePanelPosition=True, usePanelOrientation=True, RotateCenters=False,
    AllowSampleShift=False, DetCalFilename='TOPAZ_Si2mm.DetCal', ResultWorkspace='LMResults', XmlFilename='TOPAZ_Si2mm.xml', 
    ColWorkspace='LMCol', RowWorkspace='LMRow', TofWorkspace='LMTof', NumIterations=20,EdgePixels=20,CellType="Cubic")
num,err=IndexPeaks(PeaksWorkspace='Si2mm',RoundHKLs=False)
print "MANTID optimized peaks file: number indexed, error indexing = ", num,err
wksp=mtd['Si2mm']
lattice = wksp.sample().getOrientedLattice()
print "lattice, errors = ", lattice.a(),lattice.b(),lattice.c(),lattice.alpha(),lattice.beta(),lattice.gamma(),lattice.errora(),lattice.errorb(),lattice.errorc(),lattice.erroralpha(),lattice.errorbeta(),lattice.errorgamma()
print "U = ",lattice.getU()
print "B = ", lattice.getB()
```

Refs #16199 since all problems in issue were not fixed.

Algorithm changes already in release notes since these are bug fixes from previous ticket.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by VickieLynch** [comment]
Want this to go in Release 3.7 if possible

**Comment by VickieLynch** [comment]
new #16527 from release 3.7

**Comment by AndreiSavici** [comment]
I did not see in the list of fixes the additional CellType parameter

**Comment by VickieLynch** [comment]
I only added the CellType parameter to see if it would help with optimizing to the requested lattice parameters.  The default is triclinic. Maybe this should be mentioned somewhere.

**Comment by AndreiSavici** [comment]
:shipit:

**Comment by FedeMPouzols** [comment]
When we merge #16527 this PR should probably be closed.

**Comment by FedeMPouzols** [comment]
Closing this for now to see if that fixes the issue with the re-builds.

**Pull request closed without merging**
