### PR TITLE
Fix ApplyFloodWorkspace algorithm not preserving values in missing spectra

### LINKED ISSUE #38393: ApplyFloodWorkspace does not always preserve values in missing spectra
**Describe the bug**

The `ApplyFloodWorkspace` algorithm can take a flood workspace that does not contain values for all the spectra that are in the input workspace. In this case, the algorithm identifies which spectra are missing (by matching based on detector ID) and then creates a new flood workspace that adds them in with Y values all set to 1. The flood correction is then performed by dividing the input workspace by the new flood workspace, and this preserves values in the input workspace that we did not have flood data for. The rationale for this approach is described in [this PR comment](https://github.com/mantidproject/mantid/pull/23549#discussion_r239455999).

For the case where the flood workspace has a single bin, this works correctly. However, when the flood workspace has more than one bin then there is a step before the divide where we rebin the flood workspace to match the input workspace. If there are some spectra in the flood workspace that we have deliberately set to a Y value of 1 then these may be changed after the rebin. The divide that follows will then change the input workspace spectra that we were trying to preserve.

**To Reproduce**

**Expected behavior**

Input workspace spectra that we do not have data for in the flood workspace should be unchanged after the correction, regardless of the number of bins in the flood workspace.

**Platform/Version (please complete the following information):**
 - Mantid Version: since 4.0

### PR DESCRIPTION
**Pull request by adriazalvarez**
### Description of work
The origin of this issue is very well documented in #38393. 
In summary, scientist assign a value of 1 to spectra in a Flood Workspace which are not to be corrected; most Flood Workspace spectra are a single bin (one data point) factor correction per spectra that is to be applied to the input data. For some instruments like POLREF, the flood workspace may not be a single data point, but a multiple bin spectrum. This time, the spectra which are not to be modified are assigned a vector of 1 in the Flood Workspace, but this value of 1 is changed as the Flood workspace must be rebin prior to applying the flood correction to the input workspace. This operation modifies those Flood spectrum with constant flood value of 1.

#### Summary of work

The algorithm first equalizes the sizes of the input workspace and the flood workspace by generating a map of compatible indexes between the two spectra, incompatible indexes are labelled with the values of -1. I have taken these indexes and used them to refactor the missing spectra back to one after rebinning. The changes only affects multiple bin workspaces. 
Additionally, I have added a test that covers this case. 

Other modifications: 
- Doxygen style comments on algorithm file. 
- Add helper functions in the test to apply the algorithms 
- Modify access to workspaces using non-deprecated methods. 

Fixes #38393. 

### To test:
- Test should pass. 
- The example script in #38393 should not modify input workspace on cropped flood workspace indexes.

*Added release notes*

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by rbauststfc — COMMENTED** [review]
This solution looks really good and has definitely fixed the problem - I've tested both with the example code on the issue and some real POLREF flood and run files, and everything is working well. There are also some really good tidy ups in the code, which is great.

I've added a few comments on some minor things, just in case you're interested in any of the suggestions.

You mentioned that you felt this solution might not be the most efficient way of achieving this. I did a bit of testing when I first opened the issue in case we could simply move resizing the flood workspace to after the rebin step, however it didn't seem to work as the new flood workspace didn't have the correct X values, so I can see why you've done what you have here. I had another look today, though, and I'm wondering if it may be possible to get this approach to work if you set the X values as part of creating the new flood workspace. I edited `makeEqualSizes` as follows:

```
 if (missingSpectrum) {
   newFlood->getSpectrum(i).copyDataFrom(*missingSpectrum);
   newFlood->mutableX(i) = flood->mutableX(i); // This might not be necessary actually, but I haven't tested that
 } else {
   newFlood->mutableX(i) = flood->mutableX(i);
   newFlood->dataY(i).assign(floodBlocksize, 1.0);
   newFlood->dataE(i).assign(floodBlocksize, 0.0);
   missingSpectrum = &newFlood->getSpectrum(i);
 }
```
And with this I seemed to be able to just move the resize to after the rebin step. My testing has been very light-touch, and I'm still building knowledge with C++ so would need to properly check/think through whether there are some unintended consequences from setting the `newFlood` X values in this way (i.e. it might be better to copy the X values across), but I just thought I'd mention it in case you hadn't already ruled this out and were curious to investigate any further. My thinking is that if this method is supposed to be creating a copy of the old flood workspace that just has some new spectra added to it then in theory we should just be able to move it to after the rebin, so it would be interesting to get to the bottom of why that doesn't seem to be possible. No need to do this if you'd rather not, though, (or if you've already looked into it, of course!) as the solution you've found is working nicely.

**Comment by adriazalvarez** [comment]
Thanks for reviewing this so fast. I have added all your suggestions. 
Regarding the change you propose initially (move the `makeEqualSize`) function after the rebin step, I initially think about doing that, I have discarded it because the rebinning is doing a `rebinToWorkspace`, so it tries to rebin the two workspaces matching index by index, but if they have uneven sizes, it uses the first spectra to rebin all the other spectra (at least according to description). So it can be the case that the input file has different binning in different spectrum (although its probably very unlikely, but I'm not sure), which would fail the divide operation after the rebinning step.

**Comment by rbauststfc** [comment]
Ah, that's a very good spot. Sounds like it's definitely a better idea to do the rebin after the resize then, just in case. 👍

**Review by rbauststfc — APPROVED** [review]
The changes have fixed the issue well, using a good solution that takes all considerations into account. This PR also includes some really nice improvements/updates to the original algorithm and test code. Test coverage of the original issue is looking good. All PR comments have been addressed. 👍

**Pull request merged**
