### PR TITLE
Add git pre-push hook to check and confirm before pushing to master

### PR DESCRIPTION
**Pull request by DavidFair**
Description of work.
This PR asks you if you are sure you want to push directly to master for those times you forgot to checkout the branch you were meant to be working on.
It may require someone with more experience of the hooks in git to check that this will work correctly as I have tested it on a private project with `.git/hooks/pre-push` but not in Mantid with `.githooks/pre-push`

**To test:**
On attempting to push to Mantid it should prompt the user saying they are about to push directly to master are they sure. 

Go to the .githooks folder and execute the script as follows
`bash -x ./pre-push` it should perform exactly as described (prompt if on Master/Release) and exit with `0` if it was meant to push or `1` if not. Checkout various branches with protected names and ensure it correctly selects between 0 and 1

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
As I happened to push to a release branch by accident recently, could we also add those to the list of protected branches?

**Comment by martyngigg** [comment]
Can we have them linked to `.git/hooks` in cmake like the others: https://github.com/mantidproject/mantid/blob/master/buildconfig/CMake/CommonSetup.cmake#L172?

**Comment by martyngigg** [comment]
I agree with @SimonHeybrock about the release branch. I would put a regex in for anything starting `release-`

**Comment by DavidFair** [comment]
I've changed it to (ab)use grep to perform regex on a list of protected branches. To add more just simple add them to the array list at the top of the file.

Currently it matches
`master`
`release` and `release.*` where `.*` can be zero/one/more of any characters (e.g. `release-3.8`)

**Comment by peterfpeterson** [comment]
What if I think this doesn't belong in mantid?

**Comment by rosswhitfield** [comment]
@peterfpeterson `git config --add core.hooksPath /dev/null`

**Comment by martyngigg** [comment]
@peterfpeterson Can you elaborate as to why?

**Comment by peterfpeterson** [comment]
Mostly because I think that C++ developers should be capable to know what branch they are messing with. The other big reason is that if people (e.g. gatekeepers) are going to merge onto master and push back to github, they are going to have this little nag asking if they really mean it. Additionally, I changed `master` to only allow gatekeepers to push. Also, no hooks happen when you edit in browser (FYI).

**Comment by martyngigg** [comment]
I saw this is preventing *accidental* pushes; which could happen regardless how much of an expert you are in anything. Is the `y/n` really in the way that much given that we don't push to `master` directly that frequently?

**Comment by DavidFair** [comment]
So I have been thinking what is the best way to go about this. Since the branch is protected for most developers perspective this issue is resolved however some senior developers sound like they may have a use for this.

Why don't we make it opt in for those who do work directly on `master` or `release` from time to time by making it an advanced option under cmake? If the option is ticked the hook is added, if it is unticked the hook is removed. This way developers who like the extra safety net can opt in for it without forcing it on all.

**Comment by SimonHeybrock** [comment]
I am with @martyngigg on this. I don't see any reason why this should not be enabled by default for everyone. Pressing 'y' once every three months isn't too much to ask.

**Comment by rosswhitfield** [comment]
Can this be made to only apply when pushing to `mantidproject/mantid`

I work off a fork and I frequently push to `master` on my fork to catch up with upstream.

**Comment by DavidFair** [comment]
I'm closing this PR due to it gradually becoming stale. With the recent changes on GitHub it affects only senior developers. 
Those who want this functionality can get this without affecting the main repository can get it by putting [this](https://raw.githubusercontent.com/mantidproject/mantid/9cef56c5f0fccd79a8439e214a26d639ddefe02c/.githooks/pre-push) into `.git/hooks/pre-push`.

**Pull request closed without merging**
