### PR TITLE
Workbench: monitor algorithm progress

### LINKED ISSUE #21507: Add a widget that reports algorithm progress
The widget has a progress bar and the `Details` button. The button opens a dialog that report progress of all running algorithms.

### PR DESCRIPTION
**Pull request by mantid-roman**
Added a progress monitoring widget to the algorithm selector.

**To test:**

* Start mantid command prompt.
* Change to folder in the source directory: `qt/python`
* Add the path to the mantid executables (`bin\Release` on Windows) to `PATH` environment variable.
* Open the algorithm selector by running `python -m mantidqt.utils.qt.testing.run_test_app mantidqt.widgets.algorithmselector.AlgorithmSelectorWidget`
* Run some algorithms
* Open the details dialog

Fixes #21507

**Release Notes** 

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
I'm unable make a satisfactory build of the workbench nor get a non-empty details dialog. I'll leave it to someone else.

**Comment by KarlPalmen** [comment]
Do the Jenkins builds actually build this workbench?

**Comment by martyngigg** [comment]
@mantid-roman Looks like there's a segfault on OSX. Maybe @samueljackson92 could help diagnose it?

**Comment by samueljackson92** [comment]
Building it over lunch.

**Comment by ElliotAOram** [comment]
Sorry didn't see above conversation before I jumped into testing! Functionality works as expected on **windows** currently.

**Comment by martyngigg** [comment]
@ElliotAOram No problem. Would you be willing to mark this as good to go?

**Comment by martyngigg** [comment]
As Elliot as marked this good to go in comment form I'm going to merge it.

**Comment by martyngigg** [comment]
Python 3 failure is unrelated and has been noted in the unreliable build failures sheet.

**Pull request merged**
