### PR TITLE
sliceviewer Icon update and usability

### PR DESCRIPTION
**Pull request by NickDraper**
Ticket http://trac.mantidproject.org/mantid/ticket/11341

Update icons and (slightly improve usability)
### To test
1. I suggest that Owen at least should give his opinion on this
2. The documentation still needs to be updated, but it is wiki pages that only really want updating once this has passed.  The majority of the updates are images only for the new look.
3. This looks fine on windows, but should be checked on at least one different platform.

### CODE REVIEW

**Comment by NickDraper** [comment]
I've also asked for feedback from the VATES group, Jon Taylor has given it a thumbs up so far
.

**Comment by NickDraper** [comment]
Jenkins, two passed environments, the other two failed on different tests that are both unrelated to these changes and lower in the package tree than any change.  I'm sorry but I don't believe these results.

**Comment by NickDraper** [comment]
retest this please.

**Comment by OwenArnold** [comment]
Nick, Is this ready to go in?

**Comment by NickDraper** [comment]
Yes this is ready to go

**Comment by OwenArnold** [comment]
Functionally this looks to be working Ok. I'm going to create another follow up ticket with some clean-up tasks.

**Pull request merged**
