### PR TITLE
Rename Concepts names to be more user friendly

### PR DESCRIPTION
**Pull request by dtasev**
Description of work.

Filenames in the `docs/source/concepts` folder have been changed to look friendlier to users.

How it looks before the changes: http://docs.mantidproject.org/nightly/concepts/index.html
How it looks after the changes:
image

**To test:**
Look over the names. Add suggestions for improvements

Fixes #xxxx.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DTasev** [comment]
`MultipleFileProperty` seems to be put into the `.. categories:: Concepts`, however it is not in the `docs/source/concepts` folder. Should it be moved to concepts folder, or removed from the category?

**Comment by martyngigg** [comment]
Let's leave it where it is for now while some of the other changes are being made.

**Review by martyngigg — APPROVED** [review]

**Comment by SimonHeybrock** [comment]
I would really dislike having spaces in actual class names. This makes this part of the documentation much harder to navigate for actual developers, and arguably many of the pages documenting classes are probably used mostly by (newer) developers...?

**Comment by DTasev** [comment]
I am not sure how to proceed, I both agree that class names should be the same, but also I don't think it will hinder anyone from finding the information. 

Especially when the same name is written with a space in the title. For example `EventWorkspace` is written as `Event Workspace` in the title of its page. And searching for `EventWorkspace` doesn't bring the actual concept page as a result, before or after the change.

**Comment by DTasev** [comment]
Adding in progress as further feedback is required

**Comment by martyngigg** [comment]
This has gotten old and now we're moving some things to the `dev-docs` it's likely this won't get resurrected.

**Pull request closed without merging**
