### PR TITLE
Changed name and return type of isDistribution setter in matrix workspace

### LINKED ISSUE #15827: isDistribution is a setter on MatrixWorkspace
Look at isDistrubution [here](https://github.com/mantidproject/mantid/blob/master/Framework/API/inc/MantidAPI/MatrixWorkspace.h#L359)

1. Major point: This is clearly as setter. calling it `isDistribution` makes no sense, particularly since there is a `isDistribution` that is a getter!
1. Minor point: There is no danger that it doesn't actually perform the set, so one might consider not making it return the set value. 

This is a simple maintenance task. since the `void set...(arg)` signature is used everywhere else on this `MatrixWorkspace` interface, I think we should make a consistent `setDistribution`.

### PR DESCRIPTION
**Pull request by ianbush**
Change name of isDistribution setter to setDistribution on matrix workspace, and removed return type for the setter.

**To test:**

Check the refactoring is sensible and address the problems listed in #15827. Verify all tests pass.

Fixes #15827 .

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@ianbush The changes look good. The new method signature is far clearer than before.

Can you update the title of the pull request so that it is not the auto generated one? There are a few details around the worklow at http://www.mantidproject.org/Git_Workflow#Pull_Requests that may help.

The `clang-format` failure can be fixed by applying the patch file that is generated by the build job. I usually does this with curl from the root directory of the repository:
```
curl -s http://builds.mantidproject.org/job/pull_requests-clang-format/4143/artifact/0001-clang-format-PR16061-db3a751.patch | git apply
```

**Comment by martyngigg** [comment]
@ianbush This looks good now apart from the fact that the branch has developed merge conflicts. Can you merge in master, please?

**Comment by martyngigg** [comment]
This is good now.

Happy to :shipit:

**Comment by FedeMPouzols** [comment]
Good that when this was exposed to Python it was as `setDistribution()`.

**Comment by FedeMPouzols** [comment]
I'm afraid this has introduced a compilation error in files that were added after this was built by the servers. See for example: http://builds.mantidproject.org/job/pull_requests-pylint/6467/console
So the Pylint builds are failing. I'm now creating a quick fix branch.

**Comment by martyngigg** [comment]
Ah. That was my fault for leaving the PR open for so long. The green tick is not necessarily always valid

**Comment by FedeMPouzols** [comment]
Well I didn't notice. And there's been many additions in the last few days, so I should have tried a rebuild or two just to make sure that no effective conflicts had sneaked in.
It seems that it was simple to fix: #16276.

**Pull request merged**
