### PR TITLE
Update doctest runner for better compatability across sphinx versions

### PR DESCRIPTION
**Pull request by martyngigg**
Internal change for running the documentation checks.

The new Windows libraries contain a newer Sphinx version that has a refactored `Sphinx.main` method. It now calls `sys.exit` directly whereas we would like to get the return value, perform some cleanup and then call `sys.exit` ourselves.

These changes call the `sphinx.cmdline.main` method directly and are compatible with Sphinx >= 1.2, which is required by check in the cmake files.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
I'm testing this with our current setup and third party libraries on windows/linux. @martyngigg : please let me know if this needs testing with some different libraries/sphinx version. In principle I'll merge it as soon as I see that the doc tests run normally.

**Comment by martyngigg** [comment]
@FedeMPouzols That's the best test as it should still work with the current setup.

**Comment by FedeMPouzols** [comment]
In principle unrelated to these changes, but just noting here in case this becomes an issue. On debian I'm getting errors from `FakeISISHistoDAE:`:
```
FakeISISHistoDAE-[Fatal] FakeISISHistoDAE: Execution terminated by user.
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "<doctest exStartLiveDataEvent[0]>", line 9, in startFakeDAE
    FakeISISEventDAE(NPeriods=1,NSpectra=100,Rate=20,NEvents=1000)
  File "/home/fedemp/test/build-mantid/bin/mantid/simpleapi.py", line 756, in algorithm_wrapper
    algm.execute()
KeyboardInterrupt

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "<doctest exStartLiveDataHisto[0]>", line 8, in startFakeDAE
    FakeISISHistoDAE(NPeriods=5,NSpectra=10,NBins=100)
  File "/home/fedemp/test/build-mantid/bin/mantid/simpleapi.py", line 756, in algorithm_wrapper
    algm.execute()
KeyboardInterrupt
```.
Regardless of this run_sphinx seems to run correctly.

**Comment by martyngigg** [comment]
That will be due to the new cancellation mechanism. The test uses a separate thread to run fake ISIS histo data producer and then cancels it at the end. As long as it doesn't take anything else down then the output looks normal

**Comment by FedeMPouzols** [comment]
Oh now I found in the Ubuntu build server log the same errors from the FakeISISHistoDAE threads. It seems harmless. This test runs successfully (also if you run it as a single test with `-R`).

The doc-tests run normally and pass, and you get the usual output. Checked on debian and windows in both debug and release modes. It seems totally safe to merge this in.

**Pull request merged**
