### PR TITLE
Port Indirect Bayes to the Workbench

### LINKED ISSUE #25984: Port Indirect Bayes Interface
### Description
Port the Indirect Bayes GUI to the Workbench. 
Most of the requirements needed to do this should now have been fulfilled.

### Platforms affected
All

### PR DESCRIPTION
**Pull request by robertapplin**
~~Preferably merge after #26522~~
Only review on windows
-----------------------------------
**Description of work.**
This PR ports the Indirect Bayes interface to the workbench. 

**Release notes will follow in the PR which ports Data Analysis**

**To test:**
Workbench and MantidPlot:
1. `Interfaces`->`Indirect`->`Bayes`
2. Load the data below
3. Click `Run` and wait.
4. Click `Plot` and external plots should appear.

**Data Files**

**ResNorm**
[irs26173_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2491289/irs26173_graphite002_red.zip)
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2491290/irs26173_graphite002_res.zip)

**Quasi**
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2491291/irs26176_graphite002_red.zip)
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2491292/irs26173_graphite002_res.zip)

**Stretch**
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2491291/irs26176_graphite002_red.zip)
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2491292/irs26173_graphite002_res.zip)

Fixes #25984

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
Resnorm, I'm getting this when I click plot
image

**Comment by NickDraper** [comment]
Quasi,

When running I get ths
image

with this log message
```
Load started
Load successful, Duration 0.07 seconds
Load started
Load successful, Duration 0.12 seconds
BayesQuasi started
Sample workspace contains trailing zeros within the energy range.
Updating eMax: eMax = 0.5432174241643366
Property deltaE-mode not found

Property deltaE-mode not found

GroupWorkspaces started (child)
GroupWorkspaces successful, Duration 0.00 seconds
invalid value encountered in greater_equal
Error in execution of algorithm BayesQuasi
index 0 is out of bounds for axis 0 with size 0
  at line 374 in 'C:/Mantid/Code/Framework/PythonInterface/plugins/algorithms\WorkflowAlgorithms\BayesQuasi.py'
  caused by line 1129 in 'c:\mantid\code\framework\pythoninterface\mantid\simpleapi.py'
  caused by line 437 in 'C:\Mantid\Code\external\src\ThirdParty\lib\python2.7\lib\site-packages\matplotlib\backends\backend_agg.py'
  caused by line 55 in 'C:\Mantid\Code\external\src\ThirdParty\lib\python2.7\lib\site-packages\matplotlib\artist.py'
  caused by line 1484 in 'C:\Mantid\Code\external\src\ThirdParty\lib\python2.7\lib\site-packages\matplotlib\figure.py'
  caused by line 2307 in 'C:\Mantid\Code\external\src\ThirdParty\lib\python2.7\lib\site-packages\matplotlib\figure.py'
  caused by line 349 in 'C:\Mantid\Code\external\src\ThirdParty\lib\python2.7\lib\site-packages\matplotlib\tight_layout.py'
  caused by line 115 in 'C:\Mantid\Code\external\src\ThirdParty\lib\python2.7\lib\site-packages\matplotlib\tight_layout.py'
  caused by line 4198 in 'C:\Mantid\Code\external\src\ThirdParty\lib\python2.7\lib\site-packages\matplotlib\axes\_base.py'
  caused by line 1145 in 'C:\Mantid\Code\external\src\ThirdParty\lib\python2.7\lib\site-packages\matplotlib\axis.py'
  caused by line 1028 in 'C:\Mantid\Code\external\src\ThirdParty\lib\python2.7\lib\site-packages\matplotlib\axis.py'
  caused by line 971 in 'C:\Mantid\Code\external\src\ThirdParty\lib\python2.7\lib\site-packages\matplotlib\axis.py'
  caused by line 1954 in 'C:\Mantid\Code\external\src\ThirdParty\lib\python2.7\lib\site-packages\matplotlib\ticker.py'
  caused by line 1962 in 'C:\Mantid\Code\external\src\ThirdParty\lib\python2.7\lib\site-packages\matplotlib\ticker.py'
  caused by line 1925 in 'C:\Mantid\Code\external\src\ThirdParty\lib\python2.7\lib\site-packages\matplotlib\ticker.py'
Got error from algorithm "BayesQuasi"
Stopping batch algorithm because of execution error

```

image

**Comment by NickDraper** [comment]
Stretch same plot error as ResNorm
image

**Review by NickDraper — DISMISSED** [review]
See the comments I've added about testing failures.
Tested standalone - without #26522

**Comment by NickDraper** [comment]
Deassigning myself as I go on holiday soon, and don't want to prevent progress on this PR

**Comment by robertapplin** [comment]
After merging #26522 I can not replicate any of the problems mentioned above

**Review by giovannidisiena — APPROVED** [review]
Looks good and code is well-written. All functional tests passed.

**Pull request merged**
