### PR TITLE
Nexus Loader Documentation Improvements

### LINKED ISSUE #14561: Document what Mantid reads from Nexus files
Add documentation which explains what information Mantid is reading as part of loading Nexus files. Perhaps most importantly the ISIS and SNS Nexus files.

This includes documenting LoadNexus and how it chooses which load algorithms to use. 

Add this documentation in the rst of the loaders.

### PR DESCRIPTION
**Pull request by KarlPalmen**
Improve Nexus Loading Documentation, showing how various types of data are copied from Nexus file to Workspace or other Output properties.

**To test:**

Check the release notes and that all work for this issue has been completed.

Fixes #14561 .

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
This needs a small change, because Version 1 of LoadMuonNexus has been improved.

**Comment by NickDraper** [comment]
The documentation section should be with the other documentation section in ui.rst, not framework

**Comment by NickDraper** [comment]
Other than that, this is ok, once you move it over this will be a quick retest.

**Comment by NickDraper** [comment]
These are rst only changes, no need to wait for the builds.  All is good :shipit:

**Comment by FedeMPouzols** [comment]
No need to wait for the builds as this is a release notes/documentation only PR.

**Pull request merged**
