### PR TITLE
Fix Instrument Window segfaulting when the instrument changes

### LINKED ISSUE #16957: Segfault after reloading empty instrument while InstrumentWindow is open
### Steps to reproduce the behavior
1. Run `LoadEmptyInstrument` loading, for example, IN4_Definition.xml.
2. Open the instrument window.
3. Click on 'Pick' tab.
4. Rerun `LoadEmptyInstrument` with the same parameters.
5. Move the mouse pointer over any detector in the instrument window.
   There's a good chance Mantid will crash.

By a quick investigation with a debugger, this seems to be due to some dangling pointers, for example `MantidQt::MantidWidgets::InstrumentWidgetPickTab::m_infoController` and `MantidQt::MantidWidgets::ComponentInfoController::m_instrActor` look suspicious.
### Platforms affected

This happened on Ubuntu 14.04 but may be reproducible on all supported platforms.

### PR DESCRIPTION
**Pull request by soininen**
Changing a workspace's instrument while the Instrument Window is open would invalidate some pointers pointing to an `InstrumentActor` object. This could lead to segmentation fault later when user tried to use the Instrument Window. This PR fixes the segfault by forcing a single point access to the `InstrumentActor` object.

**To test:**

Try to reproduce the segfault first on master, then repeat on this branch to check that the segfault is really gone.
1. Use for instance [`LoadEmptyInstrument`](http://docs.mantidproject.org/nightly/algorithms/LoadEmptyInstrument-v1.html) to get a workspace with instrument.
2. Open Instrument Window for the workspace.
3. Choose the 'Pick' tab.
4. Execute `LoadEmptyInstrument` again with the same OutputWorkspace.
5. Try pointing the instrument's components in the Instrument Window. There is a change that MantidPlot segfaults if these changes are not applied. You might need to go back to step 4.

Fixes #16957.

*Release notes were updated accordingly.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by mantid-roman** [comment]
Tested on Ubuntu. Works well. :shipit:

**Comment by martyngigg** [comment]
@soininen How vital is this for the release? Is it easy to reproduce? As a lot of testing has been done so far I'd be a little nervous of larger changes at this point, especially if users have not spotted them.

**Comment by KarlPalmen** [comment]
Did it fail on Ubuntu without the fix?

**Comment by mantid-roman** [comment]
@KarlPalmen It did as described in the issue.

**Comment by soininen** [comment]
@martyngigg It is easy to reproduce on my Ubuntu 14.04: the Pick tab crashes almost always if I reload the workspace whose instrument is shown on the window. Nowadays, when I debug an IDF, I automatically close the window intermittently. I don't know how often the real users run into this bug, though. I guess quite rarely as it hasn't nagging anyone else... Anyway, I'm OK with postponing this to 3.11 as I agree with the "testing needed" statement.

**Pull request merged**
