### PR TITLE
 BayesQuasi Progress Tracking

### LINKED ISSUE #13944: Indirect Bayes Quasi GUI requires Progress tracking
Indirect Bayes GUI for Quasi requires progress tracking. In order to do this, the script must first be changed into a Mantid algorithm. 
**Blocked By #13826**
* [x] #13826

### PR DESCRIPTION
**Pull request by ElliotAOram**
Fixes #13944

Added Progress Tracking to Bayes Quasi.
# Note to testers

**This can only be tested on windows due to the platform dependency of f2py**
**If running this test from the source code you must do the following**
- **Run in Release mode**
- **Add `<path to mantid repo>\Third_Party\lib\win64\mingw` to your PATH variable**
# To Test
- Open BayesQuasi (Interfaces > Indirect > Bayes > Quasi)
- Load in data:
  - Sample = `irs26176_graphite002_red`
  - Resolution = `irs26173_graphite002_res`
- Run Algorithm (all default values should be fine)
- Ensure that progress tracking runs smoothly with labels of current activities in the bottom right

### CODE REVIEW

**Comment by KarlPalmen** [comment]
Add  mantid\Third_Party\lib\win64\mingw  to what?

**Comment by ElliotAOram** [comment]
Sorry, that should be added to your PATH variable.
I'll amend that in the PR now, thanks.

**Comment by KarlPalmen** [comment]
Thanks

**Comment by KarlPalmen** [comment]
It worked after a good night's sleep/logoff. Progress was good, but reached 100% before the end. The adding of the logs takes a significant time and needs including in the progress.

**Comment by ElliotAOram** [comment]
@KarlPalmen Glad it's finally working, apologies again for the confusion! 

I'll go through and make sure tracking takes place right up until the end. I'll change the PR to state: in progress and let you know when I've made the changes. Thanks

**Pull request merged**
