### PR TITLE
Refactor loadeventnext try2 17304

### LINKED ISSUE #17304: Refactor LoadEventNexus and its auxiliary classes

### PR DESCRIPTION
**Pull request by wdzhou**
Description of work.

Refactor LoadEventNexus and related classes to improve readability.

**To test:**

Load

PG3_29571 - 974MB
NOM_77533 - 5.9GB for a couple of times.

Fixes #17304.

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
No progress on this during this release, and as such a whole collection of conflicts.  Moved to R3.11

**Comment by NickDraper** [comment]
@SimonHeybrock Is this complementary or conflicting with the changes you recently made?

**Comment by SimonHeybrock** [comment]
@NickDraper It seems a large part of this is *not* complementary (extracting `LoadBankFromDiskTask` from `LoadEventNexus.cpp`). @wdzhou Do you think this PR is now redundant, or are there other relevant changes in here?

**Comment by wdzhou** [comment]
Simon split out the files. This PR is thus closed without merging

**Pull request closed without merging**
