### PR TITLE
Reducers qt5 compatibility

### PR DESCRIPTION
**Pull request by peterfpeterson**
**Description of work.**

**To test:**

The reducer based guis need to be tried in both `mantidplot` and `mantidworkbench`. Before compiling this, run `find scripts -name ui_\*.py -delete` to get rid of previously compiled ui files. Ones that need to be created will be.

Part of #23762.

**Do not merge before #24024**

*This does not require release notes* because it is part of the workbench.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by mganeva** [comment]
@peterfpeterson There is one thing got broken in the TOFTOF reduction (MantidPlot, Qt4, Ubuntu 16.04): switching between the reduction settings (see screenshot below)

screen shot 2018-11-08 at 11 29 58


It still works via File->Open, but does not work any more just by click on the earlier opened/created file as shown in screenshot.

I attach for you a couple of xml files with settings for testing.
[reduction_settings.zip](https://github.com/mantidproject/mantid/files/2561322/reduction_settings.zip)

**Comment by mganeva** [comment]
@peterfpeterson The **Reduce** button is missed in all reducers in the workbench:

**Workbench**
screenshot_20181109_075646

**MantidPlot**
screenshot_20181109_104525

**Comment by peterfpeterson** [comment]
The issue is that in `scripts/reduction_application.py` there is a check for `IS_IN_MANTIDPLOT` which hides the `Reduce` button. I need to find @mdoucet to find out what else is assumed by that variable before I have the workbench set the variable to `True`.

**Comment by peterfpeterson** [comment]
The current version "works" except that it runs the reduction inside the gui thread.

**Comment by mganeva** [comment]
@peterfpeterson In a first approximation it works :+1: . The first issue I've mentioned (settings loading, only for **Mantidplot**) is still there. At least for my linux systems.

Another issue is that **workbench** requires now at least  following line in the script to execute it:
```python
from mantid.simpleapi import *
```
but **Mantidplot** don't.
Thus, all scripts generated by reducers should be updated to include this line. Otherwise they will not run in the **workbench**. However, I suppose it should be a separate PR for that.

**Comment by peterfpeterson** [comment]
I thought I had fixed all of the load issues. For imports, please be explicit rather than using wildcard `import *` as it helps out the static analysis tools.

**Comment by mganeva** [comment]
@peterfpeterson The load via File->Open works, but load by switching between recent files doesn't. I get this error on ubuntu 16.04+python2:
```
Traceback (most recent call last):
  File "/.../mantid/scripts/Interface/reduction_application.py", line 419, in open_file
    if not os.path.exists(file_path):
  File "/usr/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, bool found
```
In the Workbench interface the recent files do not appear at all.

The import I've copy-pasted from the workbench `Editor` window, but I am agree, the scripter should contain explicit imports rather than wildcard.

**Comment by mganeva** [comment]
@peterfpeterson Now the reduction does not run in the workbench at all. If I click **Reduce**, all I get is the message
```
USING PythonCodeExecution
```
but nothing else happens.

**Review by mganeva — APPROVED** [review]
In the first approximation it works for both, Python 2 and Python3. The reducers appear and work also for both, **MantidPlot** and **Workbench**.
I've tested mainly the TOFTOF data reduction and only on linux. I think, it can be merged :shipit:

**Pull request merged**
