### PR TITLE
Add Bk2BkExpConvPV documentation

### LINKED ISSUE #15353: There is no documentation page for the fit function Bk2BkExpConvPV
I can't find the RST page for this function: https://github.com/mantidproject/mantid/blob/master/Framework/CurveFitting/src/Functions/Bk2BkExpConvPV.cpp
But there is this old wiki page for it: http://www.mantidproject.org/BackToBackExponentialPV

There is an RST page for `NeutronBk2BkExpConvPVoigt`, which should not be confused with `Bk2BkExpConvPV`.

### PR DESCRIPTION
**Pull request by alicerussell1**
**Description of work.**
This PR adds documentation for Bk2BkExpConvPV 

**To test:**
Build the docs
Check it makes sense

Refs #16480
Fixes #15353

*This does not require release notes* because **it is documentation**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by RichardWaiteSTFC — COMMENTED** [review]
The documentation now matches the fullprof documentation but not the code. On L166  Bk2BkExPConvPV.cpp there is a sign different in the definition of Omega (the lorentzian part is added not subtracted - this does not appear to be because the imaginary parts is defined with opposite sign). This needs further investigation.

**Comment by RichardWaiteSTFC** [comment]
The - sign is also there in the GSAS documentation http://www.ccp14.ac.uk/ccp/ccp14/ftp-mirror/gsas/public/gsas/manual/GSASManual.pdf p155

**Comment by martyngigg** [comment]
@RichardWaiteSTFC Is this ready do you think?

**Comment by RichardWaiteSTFC** [comment]
@martyngigg The documentation here is 'correct' in that is matches fullprof, but I don't know if the sign change has been amended in the code (@alicerussell1 might know?). I actually played around with this last week changing the sign in the .cpp file but it still didn't give sensible results and the lorentzian component always refined to zero...

**Comment by martyngigg** [comment]
@RichardWaiteSTFC Thanks. We can wait until Alice is back. I just wanted to check nothing else was holding it up.

**Comment by alicerussell1** [comment]
The sign change hasn't been amended in the code yet but I can change it if you are certain it is wrong in the code - I cannot see a reason myself why the sign would be different to all the other documentation.

**Comment by martyngigg** [comment]
If the code is wrong then I think we should fix the code.

**Comment by RichardWaiteSTFC** [comment]
Yeh I think the sign is wrong in the code - but there might be other problems as well. I don't think the function behaves properly with either sign but it's difficult to get realistic parameters to test with...

**Comment by alicerussell1** [comment]
Sorry - I hadn't noticed this PR was still open. I fixed the sign error in the code as part of #28700 so this documentation should be correct and I have resolved the merge conflict.

**Review by RichardWaiteSTFC — APPROVED** [review]
I forgot about it too! Looks good

**Pull request merged**
