### PR TITLE
Disable MantidPlot in the CI scripts

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Packages produced by the clean CI builds will now no longer contain MantidPlot.
The code will be removed at a later date once stability without MantidPlot
is verified.

**To test:**

* Code review
* Separate CI jobs were defined to build packages for testing in https://builds.mantidproject.org/job/disableplotclean/ and https://builds.mantidproject.org/job/noplotclean-win/
* They have been tested on all four platforms by developers.

Refs #28650 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by peterfpeterson — DISMISSED** [review]
The changes look correct, but I fail to understand why the builds do not pass. 

I would like another reviewer to approve this as well since the effect on nightly builds is rather large.

**Comment by peterfpeterson** [comment]
Apparently there is a function that only exists when VATES is around
```
qt/widgets/common/qt5/inc/MantidQtWidgets/Common/moc_MantidTreeModel.cpp:333:34: error: ‘class MantidQt::MantidWidgets::MantidTreeModel’ has no member named ‘doesVatesSupportOpenGL’
```
However, I build on fedora with `-DENABLE_MANTIDPLOT=off` without this issue

**Comment by martyngigg** [comment]
You're right it's `MAKE_VATES` but I think it's actually an incremental build issue rather than an issue with the flag per-se. I think when the flag changes it's definition `moc` is not being rerun on that header so `moc_MantidTreeModel.cpp` is not regenerated and still contains a reference to the method.

**Comment by martyngigg** [comment]
I've added a workaround to the buildscript that can be removed at a later date.

**Review by peterfpeterson — APPROVED** [review]

**Review by DavidFair — APPROVED** [review]
The only thing I've noticed is any Windows builders which do not have grep in their Path will fail to delete the moc file, but we can tackle any faulty builders as and when they come up - as they are misconfigured if this fires anyway.

Looking through the build logs on Windows and Ubuntu I can see both platforms correctly didn't build Plot without warnings or errors.

I'm happy to :shipit: as we can always revert if the sky falls in, and I'm a fan of letting big changes bake for a while

**Pull request merged**
