### PR TITLE
Add basic plotting to workbench

### LINKED ISSUE #21567: Workbench: Basic Plotting
This needs to cover:
  * workspace context-menu actions for:
    * 1D plots with and without errors
    * 2D plots
  * a new `matplotlib` backend for Qt
  * a custom toolbar
  * basic plot config options

### PR DESCRIPTION
**Pull request by martyngigg**
Description of work.

Adds spectrum plotting functionality to workspace tree context menu.

**To test:**

* Build the workbench
* Test drive the plotting as much as you can
* Pay particular attention to how the "Hold"/"Active" buttons work

Fixes #21567 

**Release Notes** 

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by peterfpeterson** [comment]
One bug with the legend (my colors listed):
1. Plot a spectrum (blue plot with blue legend)
2. Close that window
3. Plot a different spectrum (orange plot with blue legend)

**Comment by ElliotAOram** [comment]
Weird plot combinations:
*n.b. I've only been able to replicate this with a data file (not my tiny 3 point minimum test file). You can find the data file that I used here: `\\olympic\babylon5\Public\ElliotOram\polaris\input\calibration\16_5\Van_97942_cycle_16_5_silicon_all_spectra.cal.nxs`*
* load file, plot spectrum and go to properties
* set min Y to be outside out of data range
* set max Y to be less than min Y and also outside data range (e.g. if data is between 0,10 Y set range to -5, -10)
* Hit apply = crash workbench

**Comment by martyngigg** [comment]
Thanks for the feedback!

@peterfpeterson On reflection "hold" is probably a better default but you're right I can see a user-configurable property coming...

@ElliotAOram Thanks for the more through testing!

**Comment by ElliotAOram** [comment]
Additional point (expansion on Pete's point):
* When plotting with error bars for multiple curves, none of the error bars colours match those stated in the legend

**Comment by martyngigg** [comment]
Closing in favour of a new branch so the name reflects the more general plotting not just 1D.

**Pull request closed without merging**
