### PR TITLE
New ISIS indirect diffraction reduction algorithm

### PR DESCRIPTION
**Pull request by DanNixon**
Fixes [#10855](http://trac.mantidproject.org/mantid/ticket/10855).

To test:
- See that system tests are passing
- Ensure both Indirect Diffraction and Data Reduction (Energy Transfer) interfaces still work
  - Run ISIS Calibration with IRS26173
  - Run ISIS Energy Transfer with IRS26173 and calibration workspace, plot contour enabled
  - Should get a nice, straight energy transfer over all Q
  - Run Indirect Diffraction with IRS26176, diffspec
- Review documentation changes.

### CODE REVIEW

**Comment by DanNixon** [comment]
Did not account for VESUVIO on diffraction.

**Comment by FedeMPouzols** [comment]
All looks fine and the documentation makes perfect sense. But pylint has a different opinion... IndirectReductionCommon.py comes with 42 warnings: http://builds.mantidproject.org/job/pull_requests-pylint/439/violations/file/IndirectReductionCommon.py/, and ISISIndirectDiffractionReduction.py introduces 15. Some of them make sense and seem esay to fix (like an unused import). Then there is also the annoying issue with mantid.simpleapi where `from mantid.simpleapi import ...`  will produce a warning for every function name that you use (https://github.com/mantidproject/mantid/pull/806#issuecomment-106856824). I'm running the system and doc tests locally just in case, but otherwise everything seems fine.

**Comment by DanNixon** [comment]
I'm assuming ```no-name-in-module``` was the right thing to disable to fix those errors, I'm slightly reluctant to have to change the use of those algorithms since there is actually nothing wrong with the way it was already done.

Considering I do this in pretty much every Python algorithm I write (as do a fair few other developers) this should just be ignored globally.

**Comment by FedeMPouzols** [comment]
The only (spurious) issue is the failed windows doc-test. I passed them locally and it went fine. The doc-test issues are totally unrelated to this PR.

**Pull request merged**
