### PR TITLE
Add custom interface: tomographic reconstruction for IMAT

### PR DESCRIPTION
**Pull request by FedeMPouzols**
Addresses [#10564](http://trac.mantidproject.org/mantid/ticket/10564).

For a real test, you need to be at ISIS and you need my help with the username/password. I'm also trying to define a simple toy dataset for testing.

**Points to be tested**:
- we'll do a test session with the IMAT scientists. This will actually cover the following points.
-  you should be able to open this new custom interface from "Diffraction -> IMAT tomographic reconstruction"
- In compute resource, SCARF should be enabled but "local" disabled (tools not figured out yet and anyway not testable here)
- browse not too non-standard FITS and TIFF images (I can provide example files and there are some included in the unit tests data)
- submit a test/toy reconstruction job to SCARF (to login you need an scarf account and or enabled federal account (in practice my help)
- check that the automatic update of the status of remote jobs works well
- this is an early interface. Comments on style, usability, etc. are very welcome

### CODE REVIEW

**Comment by NickDraper** [comment]
The interface could really do with a ? help button to link to some help documentation to explain the interface.

The Local compute section appear to be enabled in the setup section, could we disable it here as well if it does not work?

The default username and password for scarf do not work.  We should not provide a default if it is wrong.

**Comment by rosswhitfield** [comment]
:fire: The most recent changes caused all the build servers to get stuck on
> reading sources... [ 99%] interfaces/Tomographic_Reconstruction
> QObject::connect: Cannot connect QPushButton::released() to (null)::close()

and I had to manually kill the jobs. I think they were waiting for a user to press a button during exit but the build servers aren't sentient enough to realised that. Make sure your next commit fixes this else the build servers will get stuck again. :worried:

**Comment by FedeMPouzols** [comment]
Aha, thanks for fixing it. I guess that's why the queue was growing so wildly yesterday evening. I had no idea that this could happen. I'll make a temp fix for it.

**Comment by FedeMPouzols** [comment]
We found a crash in the Astra setup dialog, and also the TomoPy setup wasn't working well.  It should be fixed now. This just emphasizes that tests should be added asap ([#11193](http://trac.mantidproject.org/mantid/ticket/11193)). To reproduce follow these steps:

- Go to 'Setup' and Log in (needs my username/password)
- Put something in the three 'base directories' in the 'Setup' tab
- Go to 'Run', select different tools, and do 'setup' before clicking on 'reconstruct'. Default values are ok for testing.
- Run jobs with them. All the tools available should behave now (with the exceptions noted below).

Notes:
- You should be able to submit TomoPy and 'Custom' jobs successfully (they should show up in the table of jobs).
- Astra is enabled in this custom interface but at the moment it won't work on SCARF. You should see a warning log message about this, and Astra jobs won't start. This might get fixed on SCARF soon.
- The savu setup dialog is enabled (I just changed this in the last commit), but savu is not yet available on SCARF. So in practice you cannot run jobs for savu (the dialog is enabled now so it can be shown to the IMAT scientists in our demos/chats) but you are not allowed to submit savu jobs.

- I've noticed that the cancel button doesn't work well at the moment. We get an error "Permission denied. Contact your administrator", this in principle is not a Mantid issue.

**Comment by OwenArnold** [comment]
We've discussed the future direction of this interface, and I understand that a beta version is required now. The functionality we tried on it all worked. The code looks OK, but is lacking in separation and automated testing (another ticket for this). A wizard type approach would be better than the tab based system.

**Pull request merged**
