### PR TITLE
Reflectometry Interface (Polref): Various improvements to GUI

### LINKED ISSUE #18186: Improvements to Reflectometry GUI
This issue is to try to make the interface look nicer. Two things that could be improved are:

- Reduce the space between "columns" of widgets in the "Save ASCII" tab.
- With changes in https://github.com/mantidproject/mantid/issues/18119, in the "Settings" tab only the "Experiment Settings" is shown when you open the interface. You have to scroll down to see "Instrument Settings". It would be good if we could resize the tab so that both of them are visible.

### PR DESCRIPTION
**Pull request by PranavBahuguna**
As stated in the issue, this PR fixes the following two issues:
- Reducing the space between widgets in the "Save ASCII" tab.
- Following the changes in #18119, resizing the tab to ensure that both "Experiment" and "Instrument" sections in the "Settings" tab can be seen (without use of scrollbar).

**To test:**
- The GUI can be opened from Interfaces->Reflectometry->ISIS Reflectometry (Polref)
- Verify that the height of the window has increased and that both sections in the "Settings" tab can be seen (and that the vertical scrollbar is no longer there).
- Verify that there is less space between widgets in the "Save ASCII" tab.

Fixes #18186.

*Does not need to be in the release notes.*

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by reimundILL** [comment]
There is a segfault in the tests that might be related to your work?

When I open the ISIS reflectometry (Polref) interface I noticed two things:
- the window is not aligned to the upper left corner of the main window (other interfaces look (align) better)
- the window is too wide: the two buttons `Get Defaults` can be moved a little bit to the left and are in general not wide enough to contain its texts

**Comment by PranavBahuguna** [comment]
Regarding your comments on my PR, can you tell me what platform you tested this on? On Windows, I do not see any either of these issues of:
- Window not being aligned to upper left corner of the main window.
- `Get Defaults` not wide enough to contain tests
- Window being too wide - it is the same width as the original.

In addition I should also add that none of the issues you mentioned are within the scope of what this PR is meant to fix. If you feel these issues you raised need addressing, you can create a separate PR to fix such issues.

**Comment by reimundILL** [comment]
I am on Ubuntu and it looks initially like this:

pr18267main
pr18267settings
pr18267saveascii

**Comment by reimundILL** [comment]
After trying out the interface several times, the window is located correctly (upper left corner issue).

I still need to scroll to see the Instrument Settings. Of course, when I increase the height of the window I can see both, Experiment Settings and Instrument Settings. I do not know how it should look or how it looks like on Windows.

**Comment by reimundILL** [comment]
All changes make sense and look good, all tests passed. :shipit:

**Comment by OwenArnold** [comment]
I notice that the release notes have not been updated. I'm going to assume that was deliberate.

**Pull request merged**
