### PR TITLE
Project Recovery - Sanitise filename characters

### LINKED ISSUE #22780: Project Recovery - Sanitise filesystem characters
A workspace with a name containing `: * ?` characters cannot be saved. This should be sanitised

For example a workspace named after a file path would fail to save.

### PR DESCRIPTION
**Pull request by DavidFair**
Cannot be merged before #22781 

**Description of work.**
Removes any invalid characters that can exist in workspace names, such as `?` or `:`

**To test:**
- Create a sample workspace with any of the following characters: `? : \ / *`
- Check project recovery strips these characters out and saves .py file
- For example 123\abc -> 123abc

Fixes #22780 .

Does this update require release notes?
- [ ] Yes
- [x] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by keeeto — APPROVED** [review]
This works as described.
There are a few edge case issues, these have been added to #22715

**Comment by ianbush** [comment]
The same problems fixed for the project recovery in this PR also exist in the project saving 😞 . I wonder if it is a good idea to be more restrictive of our workspace names so we don't run into these issues? That is a bigger and potentially breaking change so not for 3.13 in any case.

**Comment by keeeto** [comment]
@ianbush I think that this is a good idea longer term. I hit some other edge case issues yesterday. eg the project recovery falls over if there is a `#` in the workspace name.

**Comment by ianbush** [comment]
Lots of fun to be had with this, with a `'` in the name the project recovery gives you a recovery script, but it cannot be used:
```python
Load(Filename='/home/cs/bush/Mantid/mantid_data/SampleData-ISIS/loqdemo/LOQ74014.nxs', OutputWorkspace='LOQ74014')  # 2018-07-05 09:05:35.539253 
RenameWorkspace(InputWorkspace='LOQ74014', OutputWorkspace=''Oops')  # 2018-07-05 09:05:43.003120 
```
Restricting a the workspace level should put a stop to these issues, hopefully no-one has a genuine need to use special characters like these.

**Pull request merged**
