### PR TITLE
Add BackToBackExponential coefficients for A,B,S to WISH parameters.xml

### PR DESCRIPTION
**Pull request by RichardWaiteSTFC**
**Description of work.**

Added BackToBackExponential coefficients to automatically guess A,B,S when a peak is added at a given d-spacing in a spectrum to WISH parameters.xml

**To test:**
No test required, check no builds fail.

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DannyHindson** [comment]
I noticed this PR failed some system tests late on Friday. You could turn off the instrument check for the tests in the complexShapeAbsorptionsTest suite by adding this to validate method:

self.disableChecking.append('Instrument')

It's probably not that helpful for complexShapeAbsorptionsTest to care about the WISH parameters. As for the WISHxxx tests perhaps their ref files do need updating.

Since this is a small change we might be able to squeeze this in the release if you can make this change this morning

**Comment by martyngigg** [comment]
Yes I think we should include this as changes in the instrument directory get updated to users computers anyway when they are merged with master so we might as well get it in the release itself.

**Review by martyngigg — APPROVED** [review]
This is a low impact change that will improve the fitting behaviour for WISH.

**Comment by martyngigg** [comment]
@mantidproject/gatekeepers Could we get this in the nightly?

**Pull request merged**
