### PR TITLE
Indirect - Unit Tests - Ensure all Indirect Unit Tests run at non-ISIS facilities

### LINKED ISSUE #21508: Default facility assumed in unit tests
The following tests give an error about not finding the `osiris` instrument in the default facility.
- python.WorkflowAlgorithms.EnergyWindowScanTest.EnergyWindowScanTest
- python.WorkflowAlgorithms.IndirectDiffScanTest.IndirectDiffScanTest
- python.WorkflowAlgorithms.IndirectSampleChangerTest.IndirectSampleChangerTest
- python.WorkflowAlgorithms.ISISIndirectDiffractionReductionTest.ISISIndirectDiffractionReductionTest  
- python.WorkflowAlgorithms.SofQWMomentsScanTest.SofQWMomentsScanTest
- python.WorkflowAlgorithms.VesuvioDiffractionReductionTest.VesuvioDiffractionReductionTest

### Expected behavior

That the unit tests work no matter what facility is set in the `Mantid.user.properties`. Some of the code can switch from `config.getFacility().getInstrument('osiris')` to `config.getInstrument('osiris')`. Since the instrument name is unique, there won't be a problem.

### Steps to reproduce the behavior

Set the default facility to something other than `ISIS` (`ILL` should work) and run the tests.

### Platforms affected

All.

### PR DESCRIPTION
**Pull request by brandonhewer**
This PR ensures that all Indirect unit tests run in the circumstance that the default facility is not set to ISIS (unit tests should not be dependant on default facility).

Specifically, the following tests were previously failing:
- python.WorkflowAlgorithms.EnergyWindowScanTest.EnergyWindowScanTest
- python.WorkflowAlgorithms.IndirectDiffScanTest.IndirectDiffScanTest
- python.WorkflowAlgorithms.IndirectSampleChangerTest.IndirectSampleChangerTest
- python.WorkflowAlgorithms.ISISIndirectDiffractionReductionTest.ISISIndirectDiffractionReductionTest
- python.WorkflowAlgorithms.SofQWMomentsScanTest.SofQWMomentsScanTest
- python.WorkflowAlgorithms.VesuvioDiffractionReductionTest.VesuvioDiffractionReductionTest

**To test:**
1. Change the default facility to a non-ISIS facility.
2. Run each of the outlined tests, ensuring they pass.

Fixes #21508. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by ianbush — DISMISSED** [review]
I still get two failing tests:
```
The following tests FAILED:
	718 - python.WorkflowAlgorithms.ISISIndirectDiffractionReductionTest.ISISIndirectDiffractionReductionTest (Failed)
	738 - python.WorkflowAlgorithms.VesuvioDiffractionReductionTest.VesuvioDiffractionReductionTest (Failed)
```

Everything passes when I have ISIS as my facility, but the above fail when it is ILL.

**Comment by brandonhewer** [comment]
@ianbush It seems as though the issue, is that the VESUVIO data (used in both of the failing tests), is not in the UnitTest folder, which is fine when ISIS is set as the facility, but not when another facility is set.

**Comment by ianbush** [comment]
I am away for some time so I can not easily test this again - I will remove myself as a reviewer and let someone else pick this up.

**Comment by soininen** [comment]
The two unit test reported by @ianbush still fail. Would it be possible to add `setUp()` method to the unit tests, and set the default facility temporarily for the duration of the test there? Would be nice if the corresponding `tearDown()` would set the original facility back. Something like this:

```python
def setUp(self):
    self._oldFacility = mantid.config['default.facility']
    mantid.config.setFacility('ISIS')

def tearDown(self):
    mantid.config.setFacility(self._oldFacility)
```

**Review by rosswhitfield — APPROVED** [review]
LGTM. Tests now pass with different facility.

**Pull request merged**
