### PR TITLE
Added log copying in TF asymmetry mode

### PR DESCRIPTION
**Pull request by Matthew-Andrew**
**Description of work.**

Currently the logs are not copied into the fitted workspace in TF asymmetry mode. This leads to the results tab not working for fits performed in TF asymmetry mode. This adds the required lines to copy these logs forward.

**To test:**

These changes affect TF asymmetry mode fits and how they interact with the results table. IN addition to code review I would reccomend trying the following things. If the below doesn't make sense please come and talk to me.
  * Perform a single fit in TF asymmetry mode go to the results tab and try to produce a results table from this fit containing all the logs
  * Do the same for a sequential and simultaneous fit.

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by Harrietbrown — APPROVED** [review]
Very good.

**Comment by Mantid-Matthew** [comment]
@mantidproject/gatekeepers It would be good to get this PR merged today if possible

**Comment by Mantid-Matthew** [comment]
Actually there is one more thing I want to check regarding this PR so please hold off on mergeing this PR for now.

**Comment by Mantid-Matthew** [comment]
This is now good to go

**Pull request merged**
