### PR TITLE
Added deltaE-mode detection to LoadNXSPE

### LINKED ISSUE #17417: LoadNXSPE does not set the correct Emode
### Expected behavior

LoadNXSPE with a file from an indirect geometry instrument (e.g. IRIS, OSIRIS, TOSCA, BASIS) will set the energy analysis mode to `Indirect` whilst using LoadNXSPE with a file from a direct geometry spectrometer (e.g. ARCS, CNCS, LET, MAPS, MARI, MERLIN, SEQUOIA) will set `Emode` to `Direct`
### Actual behavior

LoadNXSPE sets Emode to `Elastic` regardless of data type. This is because the energy analysis mode is not actually defined in the `nxspe` file. The instrument name, however is, so we can use that to guess Emode.

The correct Emode is needed for some conversion algorithms, such as `SofQW` and `ConvertToMD`. This could be set manually in these algorithms after loading files (which is what has been done up to now), but for MSlice, we would like to make this more automatic.
### Steps to reproduce the behavior

Load any `nxspe` file, then `getEMode`, e.g.:

```
ws = Load('MAR21335_Ei60.00meV.nxspe')
print ws.getEMode().name
```
### Platforms affected

All

### PR DESCRIPTION
**Pull request by mducle**
Modifies `LoadNXSPE` to get the instrument name from the file to be loaded, run `LoadInstrument` and get whether the instrument is `Direct` or `Indirect` geometry. If the instrument name is not recognised, continues with previous default (`Elastic`).

This is mainly to fix loading of NXSPE files (especially for `Indirect` instruments) in `mslice`.

**To test:**

Load an `nxspe` file, and check (`print ws.getEMode()`) that the correct energy analysis mode is returned (e.g. for Arcs / CNCS / LET / Mari / Maps / Merlin / Sequoia it should be `Direct` and for Basis / Iris / Osiris it should be `Indirect`).

Fixes #17417.

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AndreiSavici** [comment]
If you just need `DeltaE` mode, you could just load the parameter file. You won't get the moderator to sample distance, but it might be faster, especially if you load many files

**Comment by mducle** [comment]
Ah right... I didn't realise that `LoadParameterFile` existed... I'll change the code now.

**Comment by mducle** [comment]
@AndreiSavici - for some reason `LoadParameterFile` doesn't work for me... it doesn't populate the instrument fields.

Both in Python

```
ws = CreateWorkspace([0],[0]); 
LoadParameterFile(ws, '~/mantid/instrument/MARI_Parameters.xml'); 
inst = ws.getInstrument(); 
print inst.getParameterNames()
```

and C++

```
MatrixWorkspace_sptr instrumentWS = outputWS->clone();
IAlgorithm_sptr loadParamAlg = createChildAlgorithm("LoadParameterFile");
loadParamAlg->setProperty("Filename", instrument_parfile);
loadParamAlg->setProperty("Workspace", instrumentWS);
loadParamAlg->execute();
const Geometry::ParameterMap &paramMap = instrumentWS->instrumentParameters();
std::cout << paramMap.asString() << "\n";
```

I only get empty strings, even though both report that `LoadParameterFile` succeeded. Does the workspace for `LoadParameterFile` have to have some particular property already?

**Comment by mducle** [comment]
Actually... figured it out. The workspace must have an instrument already defined for `LoadParameterFile` to work.

**Comment by AndreiSavici** [comment]
The changes look ok. Do you want to add a unit test? And do you want to add documentation to LoadNXSPE algorithm?

**Comment by AndreiSavici** [comment]
Looks OK. :shipit:

**Pull request merged**
