### PR TITLE
Validate input and output parameters for Direct reduction 

### PR DESCRIPTION
**Pull request by abuts**
This is repeated pull request made in attempt to avoid mysterious problems with git

descented from request #221  and refers to ticket:
https://github.com/mantidproject/mantid/pull/221

http://trac.mantidproject.org/mantid/ticket/11063#comment:12
changes are unit/system tested

### CODE REVIEW

**Comment by abuts** [comment]
Jenkins retest this please

**Comment by DanNixon** [comment]
I'm now getting this error when trying to run ```MariReduction.py```:
```
TypeError: unbound method reduce() must be called with ReductionWrapper instance as first argument (got NoneType instance instead)
  at line 120 in '/home/dan/testing-builds/test1/Code/Mantid/scripts/test/MariReduction.py'
  caused by line 317 in '/home/dan/testing-builds/test1/Code/Mantid/scripts/Inelastic/Direct/ReductionWrapper.py'
  caused by line 50 in '/home/dan/testing-builds/test1/Code/Mantid/scripts/test/MariReduction.py'
```

Other than that system tests seem to be happy.

**Comment by abuts** [comment]
It never run from there, and probably will not, as all files, necessary for reduction are currently not in the Mantid directory. It is used for decorator testing -- this is why it runs. But it is worth to make it right (in accordance with the version in the system tests in case if somebody decides to use it as an example. When system tests become part of Mantid it should go anyway.

**Comment by abuts** [comment]
Jenkins, retest this please

I am asking for retest but without big hope -- this build fails in 99% of runs for a reason not related to the code at all. I believe it can be merged as soon as one OS passes (and one does) and no other suggestions to the code identified.

**Comment by abuts** [comment]
Jenkins, retest this please

**Comment by abuts** [comment]
jenkins, retest this please

**Pull request merged**
