### PR TITLE
Switch to https for external data

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**

Switches external data to use https, this avoids some issues with having
to downgrade the latest version of git lfs.

This should also resolve issues with slowdowns over http as various
edge-devices would choke on larger (> 300MB) files.

**To test:**

Ensure you are *not* connected to the ISIS VPN / on a work machine (else it will pull from one of our cache servers)

 - Go to https://testdata.mantidproject.org/ftp/external-data/MD5/4fdb9e8db88934f2acb4d4dd900da0b1 in a browser and check it downloads
- Go to builds directory, delete a random (large-ish) file and rebuild Standard / System test data, make a note of the hash
- Go to MantidExternalData and delete that hash file, and the file above again. Re-run System / Standard Test data target and check the URL it downloads from is above

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Harrietbrown** [comment]
The url is a https, I'm still running into timeout isses with a 84mb file. that's mostly my own poor conection but it does not seem like the speed has been increased.

**Comment by DavidFair** [comment]
Is this with or without the VPN?
I do know that the upstream server has something wrong with its TCP scaling, so won't speed up to full bandwidth after the speed drops, causing dropouts. However, we were seeing additional timeouts on the VPN where the download would completely stall

**Comment by Harrietbrown** [comment]
It was without the VPN

**Comment by DavidFair** [comment]
If you try to do it without the VPN in a browser does it completely stall or just plod along at a low speed?

**Comment by Harrietbrown** [comment]
it just plods along at slow speed. my internet here has never been great, I just not no differene in speed from with vs without the PR

**Comment by DavidFair** [comment]
Ahh thanks, yes that's expected as the SSL certificate won't help with the TCP stack (it's a layer underneath HTTPS) not being aggressive enough

Were hoping the upcoming LTS upgrade will fix this issue (or a reinstall) as I can't see any custom tuning, yet our instance is significantly slower uploading than an "out of the box" install

**Comment by Harrietbrown** [comment]
In that case given it does download and this is expected I am happy to ok it.

**Review by Harrietbrown — APPROVED** [review]
The test data downloads from the https url wiout vps without issue. good job

**Pull request merged**
