### PR TITLE
Support sub dirs in System Tests

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**

- Supports arbitrary subdirs in the system tests folder, so future developers can sort tests into folders as required
- Replace deprecated `imp` with `importlib`
- Cache OS env function, this was calling `lsb_release` for every test which was causing the system tests to take ~16s to get going locally. Removing this brings the time <1s.
- Does a coarse move of ISIS SANS files into sub-dirs

**To test:**
- Check that system tests still run (best to check on Windows esp.)
- Check that one of the moved files still ran on the CI job

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by robertapplin — DISMISSED** [review]
Looks good 👍 Allows some nice organization of the system test folders

**Review by martyngigg — COMMENTED** [review]
+💯 for improving the test organization here.

What would you think of `.../framework/ISIS/SANS/...` instead of underscore separated?

**Comment by DavidFair** [comment]
Actually that's a good shout, I hadn't thought beyond technique to facility.

It would make it clear when a system test fails on Master too which facility should start to look their recent changes too.
It will take me a little while, as I need to fix #29908 and rebase it on this, but I'm more than happy to do it

**Review by martyngigg — APPROVED** [review]
Looks good to me.

**Pull request merged**
