### PR TITLE
Sliceviewer: Capture arrow keys to move cursor while line plotting

### LINKED ISSUE #29235: Sliceviewer: Move the selection cursor using the arrow keys
Instrument scientists want to be able to move the cursor by one pixel at a time to get it onto the right spot.

Add in cursor key control to move the selection point (and therefore side graphs) by one pixel at a time as well as just mouse control.

Some sensible auto repeat for long presses on the arrow would be good as well.

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

For images with small pixels it can be difficult to move the mouse cursor to the required pixel. This work adds key handlers to process the keyboard arrow keys to move the cursor in the requested direction by a single pixel. 

**To test:**

* Load a workspace, e.g. `DocTest/MAR11015.raw`
* Show the sliceviewer and activate the lineplots
* Move the mouse and the lines should update as normal
* Leave the mouse over the image and use the arrow keys to move - the plots should update. 

Fixes #29235

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by Matt-Cumber — CHANGES_REQUESTED** [review]
The code looks good, very neat and easy to read. The line plots update as the arrow keys are pressed. I just have a few comments/questions about the functionality. 

Is the purpose to simply get the right spot and note the relevant information down as one slight move of the mouse and you lose the position obtained from using the arrow keys. 

Also this might not be possible but is there a way to indicate where a user is moving to using the arrow keys as it is almost impossible to tell on the image once you have used the arrow keys. 

I've noticed if you have the cursor at the edge of the image and use the arrow keys to move towards the edge you, in other words, fall off the image and can no longer use the arrow keys and need to reset by moving your mouse again. Is it possible for some edge checking to be done so a user can go to the edge and no further?

**Comment by martyngigg** [comment]
Thanks for reviewing this, Matt.

> Is the purpose to simply get the right spot and note the relevant information down as one slight move of the mouse and you lose the position obtained from using the arrow keys.

The primary purpose of this is so the cursor can be moved over small pixels without having to try and get to the right place with the mouse. For this I think it's fine that moving the mouse loses the position and I don't really want to interfere with the mouse handling anymore as it's not clear what a user would expect here. 

> Also this might not be possible but is there a way to indicate where a user is moving to using the arrow keys as it is almost impossible to tell on the image once you have used the arrow keys. 

Given the use case and the fact that you have to press an arrow key then I'm hoping a user would see the line plots update and trust the direction is correct. It doesn't look too simple to have some type of arrow marker to indicate that so I'd be tempted to say can we leave this as a first cut to get feedback on?

> Finally I've noticed if you have the cursor at the edge of the image and use the arrow keys to move towards the edge you, in other words, fall off the image and can no longer use the arrow keys and need to reset by moving your mouse again. Is it possible for some edge checking to be done so a user can go to the edge and no further?

I must admit this is my least favourite part of the implementation. Let me think if there is something simple that can be done. If I can't get anything by tomorrow lunchtime I'll probably suggest we get this out to users and improve it in the future it they find it to be a particular issue.

**Comment by martyngigg** [comment]
@Matt-Cumber I've improved the edge handling here so it should now be the case that it's much harder to get the mouse pointer stuck. I'd like to leave the other comments if that's okay so we can get some feedback on this.

**Review by Matt-Cumber — DISMISSED** [review]
Looks good 👍  in the interest of getting this out to users for their feedback ignoring earlier comments for now.

**Comment by gemmaguest** [comment]
@martyngigg there are conflicts

**Comment by martyngigg** [comment]
@gemmaguest Thanks. Those should be sorted now.

**Comment by martyngigg** [comment]
@Matt-Cumber Would you be able to re-approve?

**Review by Matt-Cumber — APPROVED** [review]

**Pull request merged**
