### PR TITLE
Remove unused legacy REFL code

### LINKED ISSUE #21883: Remove old unused REFL code
We still have old REFL code from before we rewrote this instrument's reduction.
We should remove it.

At a minimum there is:
 - `RefLReduction`
 - The `RefLReduction` system test
 - `Framework/PythonInterface/plugins/algorithms/sfCalculator.py`
 - The old REFL reduction UI code should be removed too

### PR DESCRIPTION
**Pull request by mdoucet**
Reflectometry reduction at ORNL has gone through several iterations over the past 8 years.
Unused reduction algorithms for MR and LR should be removed.
ORNL no longer uses the reduction UI that were part of Mantid. Those have been taken off the list of reduction interfaces but the code is still in the repo. Unused UI code should be removed.

**To test:**
- Inspect the changes carefully.
- Make sure tests pass.

Fixes #21883.

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by peterfpeterson — APPROVED** [review]
Lots less unused code to maintain. LGTM.

**Comment by martyngigg** [comment]
This has unfortunately broken the ISIS Reflectometry interface as they share some of the code. The ISIS Reflectometry (old) one has been deprecated (#22171) but cannot be removed yet. To reproduce simply go to Interfaces->Reflectometry->ISIS Reflectometry (Old)

I had to resurrect the following files to get the ISIS one to start:
```
 git co origin/master -- scripts/Interface/ui/reflectometer/__init__.py scripts/Interface/ui/reflectometer/refl_choose_col.py scripts/Interface/ui/reflectometer/refl_gui.py scripts/Interface/ui/reflectometer/refl_options.py scripts/Interface/ui/reflectometer/refl_save.py
```

@edwardb96 Could you check whether this is enough for it to work properly?

**Comment by mdoucet** [comment]
@martyngigg  @edwardb96 I know what happened. Let me fix that.

**Review by martyngigg — APPROVED** [review]
Build problems are unrelated. Old ISIS Reflectometry GUI looks good.

**Pull request merged**
