### PR TITLE
Allow loading ILL data into S(Q,w) tab of Data Processor

### LINKED ISSUE #38038: Ability to process ILL data in Sqw when y axis is units of Degrees
**Description**
We want to be able to load some ILL data into the Sqw tab of the Inelastic Data Processor interface and process this data. The data we have been sent has a Y axis with units of "Degrees", and this currently will not be accepted by the GUI.

**To Replicate**
1. Interfaces->Inelastic->Data Processor
2. Sqw tab
3. Load the data below
[243489-243506ElwinHeat_H2O-HSA-stw.zip](https://github.com/user-attachments/files/17059181/243489-243506ElwinHeat_H2O-HSA-stw.zip)

6. There is an error about the workspace having unexpected units

**Other details**
Happens on all operating systems. Not a regression since the last release.

### PR DESCRIPTION
**Pull request by robertapplin**
### Description of work
This PR makes it possible to load ILL data into the S(Q,w) tab of the Inelastic Data Processor interface for processing. Previously this was not possible because the ILL data had a non-spectrum axis, whereas this interface is designed to work for reduced files produced in Indirect Data Reduction. These reduced files always have a spectrum axis.

Fixes #38038

### To test:
Follow the test instructions in the updated `DataProcessorTests` file for the S(Q,w) tab.

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by mpatrou** [comment]
It looks good!! It does not seem to change the results with the basis data.

**Comment by robertapplin** [comment]
> It looks good!! It does not seem to change the results with the basis data.

Thanks for the testing! I'll find someone on our side to also do some testing/review

**Review by warunawickramasingha — COMMENTED** [review]
Followed the tests and working as described. Code changes looks good, a small suggestion was added to update the Time required for testing S(Q,W) tab.

**Review by warunawickramasingha — APPROVED** [review]
Thanks for the changes and happy to approve!

**Pull request merged**
