### PR TITLE
Move to cmake 2.8.12

### PR DESCRIPTION
**Pull request by peterfpeterson**
This was originally [trac #11000](http://trac.mantidproject.org/mantid/ticket/11000).

**To test:** See that the clean builds still work and try it on your own. I could not remove `FindCxxTest.cmake` because our version is tangled up with other work. We should probably upgrade to the newly alive [cxxtest](https://github.com/CxxTest/cxxtest) project and get rid of our fork.

### CODE REVIEW

**Comment by peterfpeterson** [comment]
test this please

**Comment by peterfpeterson** [comment]
`FindPythonLibs.cmake` doesn't appear to find what it wants automatically on ubuntu.

**Comment by peterfpeterson** [comment]
jenkins, retest this please

**Comment by peterfpeterson** [comment]
Comment from @martyngigg on slack: We need to make sure we keep the version of `macro(CXXTEST_ADD_TEST)` that is in our finder though as it's modified from the original (I'm not sure why)

**Comment by peterfpeterson** [comment]
jenkins, retest this please

**Comment by peterfpeterson** [comment]
It worked!!!!!!! Most of the work was cleaning out cmake cache from the build servers.

Same testing rules as mentioned in the original description.

**Comment by martyngigg** [comment]
I tried a quick build of the Python layer in debug mode under Windows as that's not covered by the builds and it looks fine so it's good to go I say.

**Pull request merged**
