### PR TITLE
Clean up line breaks

### PR DESCRIPTION
**Pull request by rgmiller**
At some point, an automated tool was used to limit line lengths to 80
characters.  This tool made some less-than-optimal choices about where
to break the lines.  This change cleans that up.  No actual code or
functionality changes.

Refs #11314

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
Jenkins, test this please

**Comment by peterfpeterson** [comment]
Jenkins, Test this please

**Comment by peterfpeterson** [comment]
Test this please

**Comment by peterfpeterson** [comment]
test this please

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by eXeC64** [comment]
I've reviewed the changes and only the following hunks touch lines that actually have code on:

* [Hunk 1](https://github.com/mantidproject/mantid/pull/376/files#diff-b22bae527be86fcb9d3d26819e88bd33L66)
* [Hunk 2](https://github.com/mantidproject/mantid/pull/376/files#diff-b22bae527be86fcb9d3d26819e88bd33L143)
* [Hunk 3](https://github.com/mantidproject/mantid/pull/376/files#diff-b22bae527be86fcb9d3d26819e88bd33L156)
* [Hunk 4](https://github.com/mantidproject/mantid/pull/376/files#diff-32fa11a74793b7920dff433681722488L112)

These are all obviously correct (i.e. have no effect), so I'm going to disregard the unrelated build failure and merge.

**Pull request merged**
