### PR TITLE
Unit tests for `Stitch1DMany`

### LINKED ISSUE #17494: `Stitch1DMany` is missing unit tests
Add unit tests for `Stitch1DMany`.

### PR DESCRIPTION
**Pull request by raquelalvarezbanos**
Adds unit tests for `Stitch1DMany`. 

Scientists have requested that a new property is added to this algorithm. To make sure that it will not break existing functionality we need to have unit tests in place.

**To test:**

Code review, new tests should pass.

Fixes #17494.

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DimitarTasev** [comment]
@raquelalvarezbanos Do we still need the `Stitch1DManyTest.py` if there's a `cpp` test implemented?

**Comment by raquelalvarezbanos** [comment]
Thanks @DimitarTasev ! I thought the algorithm was missing unit tests as I couldn't find a `Stitch1DManyTest.h` file. I would say if there's already a test file, that's the one we should be using. I'll review the tests I wrote and if functionality is already covered in `Stitch1DManyTest.py` I will close this PR. If any of the tests I wrote are not covered, I'll move them to the Python test file.

**Comment by DimitarTasev** [comment]
@raquelalvarezbanos The python unit test is very slow, it takes something like 50 seconds to complete, so if you've covered the same functionality I think it's a better idea to leave yours as it's significantly faster (about 3s)

**Comment by raquelalvarezbanos** [comment]
I agree. I'll have a look

**Comment by DimitarTasev** [comment]
Ran rebuild for `RHEL7 + System Tests` and `Windows` as failures seem unrelated

**Comment by raquelalvarezbanos** [comment]
@DimitarTasev is this ready to be merged or do you have any other suggestions?

**Review by dtasev — APPROVED** [review]
The tests run and pass successfully. All of the old tests from the python script are converted to C++, and run a lot faster. There are also new tests added! Overall a great improvement over the python test :shipit:

**Pull request merged**
