### PR TITLE
Add Indirect note in the SaveAscii v1 Docs

### PR DESCRIPTION
**Pull request by DanielMurphy22**
**Description of work.**
Add in note in the SaveAscii v1 docs to mention that this algorithm is exclusively used by the ISIS indirect group

**To test:**
Build docs.html if you wish, just a small change.

*There is no associated issue.*

*This does not require release notes* because **it is Documentation**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by cailafinn — APPROVED** [review]
Looks good to go :+1:

**Comment by gvardany** [comment]
What is the reason the indirect group cannot use the v2?

**Comment by DanielMurphy22** [comment]
We're pretty sure that direct use of SaveAscii v1 is close to null. Save Ascii v1 remains built-in to the ISIS Indirect diffraction GUI and the ISIS Indirect group were highlighted as the last group that potentially still use SaveAscii v1.

**Comment by gvardany** [comment]
What I meant is why not to deprecate it straight?

**Comment by DanielMurphy22** [comment]
We are looking into deprecating this at some stage, but in the mean time I've added this comment in the Docs, partly as a reminder to ourselves what we need to check before fully deprecating it!

**Pull request merged**
