### PR TITLE
Abins: Fix order of isotopes.

### PR DESCRIPTION
**Pull request by dymkowsk**
This PR fixes AbinsCASTEPIsotopes on Python3

screenshot from 2017-10-25 17-09-55

**To test:**
Run AbinsTest.AbinsCASTEPIsotopes system test for Mantid compiled against Python3 and Python2. 

Fixes #xxxx. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by rosswhitfield** [comment]
@dymkowsk Do you need help adding the new data file to external data? It can't be tested until it's there.

**Comment by dymkowsk** [comment]
@rosswhitfield  sorry,  I forgot to add test file to the server. I will add it.

**Comment by dymkowsk** [comment]
@rosswhitfield  I updated LiOH_H2O_2D2O_CASTEP.nxs.md5. The corresponding file should be on the server.

**Review by rosswhitfield — APPROVED** [review]
👍 The test now passes with python 2 and 3 on my computer.

**Pull request merged**
