### PR TITLE
Fix monitors information in detectors table

### LINKED ISSUE #18904: Monitor information does not show correctly in detectors table
Some cells for monitors do not show up correctly in the detectors table:

detector_table

In the image above, *R* for the first monitor should be positive, and the last should show 'yes' to all monitors.

### PR DESCRIPTION
**Pull request by soininen**
This PR fixes an issue in MantidPlot's detectors table where monitor information did not show up correctly:
- The *R* column would have an negative distance if monitor's *theta* was 180 degrees
- While calculating *q*, DetectorInfo would throw an uncaught exception preventing the remaining columns to be filled.

**To test:**

Load a workspace with monitors into MantidPlot. View the detector table by right-clicking the workspace and selecting 'Show Detectors'. Before these changes are applied, monitors before the sample have a negative *R*, and the *Monitor* column shows zero instead of 'yes'.

Fixes #18904.

*Release notes were updated accordingly.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
In master, if I load LOQ49886 (from training data)then the Monitor says yes instead of 1 as described above. If R=0 then the Monitor says 0

**Comment by AnthonyLim23** [comment]
These changes are already in master.

**Comment by soininen** [comment]
@AnthonyLim23 Could you try testing again with `<mantid-build-directory>/ExternalData/Testing/Data/UnitTest/ILL/IN4/084446.nxs`? The LOQ49886 file doesn't trigger the calculation of the *Q* column in the detectors table and thus the Monitor column is correct. Sorry for the confusion, I should have given more detailed testing instructions in the first place.

Anyway, the *R* column for the LOQ49886 might still show negative values even when these changes are applied. I'll look into it.

**Comment by AnthonyLim23** [comment]
I have loaded the file you suggested. Am I right in saying that it is only the last entry on the table that is affected?

**Comment by AnthonyLim23** [comment]
The Monitor column now says yes for the last entry in the table (only one with a negative R).

**Comment by soininen** [comment]
Phi is the off-plane angle and for monitors which are on the beam axis, it is zero.

The calculation of the Q value for monitors would fail before these changes causing the rest of the monitor row (the *Monitor* column) to show zeros. This is due to `DetectorInfo::twoTheta()` throwing `std::logic_error` for monitors. Since `DetectorInfo` says that the scattering angle is not defined for monitors, I decided to set Q to not-a-number for monitors.

**Comment by AnthonyLim23** [comment]
Ok, so it should do that. Once the merge conflict and test have passed :shipit:

**Pull request merged**
