### PR TITLE
Improve handling of TableColumns with non-numerical entries

### LINKED ISSUE #22394: TableWorkspace deletes comma separated entries of the form 1,2,3,4
### Expected behavior

A TableWorkspace is created using comma separation to denote several items (in this case detectors). i.e.

[1,2,3,4]

The cells of the table should not change their values. This syntax is used for example in the MuonGroupDetectors (v1) algorithm.

### Actual behavior

When 'Show Data' is run on the TableWorkspace the first time the data appears as entered. Showing the data a second time causes the comma separated values to be replaced by zero.

### Steps to reproduce the behavior

In the Python Script Window : 

`grouping = CreateEmptyTableWorkspace()`
`grouping.addColumn('vector_int', 'detectors')`
`grouping.addRow([[1,2,3,4]])`

### PR DESCRIPTION
**Pull request by josephframsay**
Fixes a bug where the cell values of a VectorColumn were reset to 0 if the table was viewed. The check that column data is numerical in the handler `MantidTable::cellEdited` was improved to cover all column types. This means the handler doesn't try to interpret the text value as a number (which it was doing before), and instead just reads it as a string

**To test:**

```
t = CreateEmptyTableWorkspace()
t.addColumn("vector_int", "r")
t.addRow([[1,2,3]])
```

Double-click on `t` to view it, then close the table view. Double-click to view again, and the row should still be `1,2,3`, not 0.

Fixes #22394 

**Release Notes** 

[Here](https://github.com/mantidproject/mantid/commit/4c6b211b96a1c127836085041ab5f0ed1b5a6e8f#diff-d41279afe39cfbf234c3ca92983d1c5c)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by reimundILL** [comment]
On master I received an unhandled exception when running the test script and viewing `t` (Ubuntu). With the changes it works now!

**Comment by reimundILL** [comment]
Please consider to update the documentation of TableWorkspaces (Concepts). For example, I do not see the `vector_int` description.
I tried for example with `vector_double`:
```Python
t = CreateEmptyTableWorkspace()
t.addColumn("vector_double", "r")
t.addRow([[1.,2.2,3.3]])
```
result is 1,1,2,2,3,3.

**Comment by josephframsay** [comment]
@reimundILL could you describe the steps you went through to get the problem with `vector_double`? I can't replicate this on either Ubuntu or Windows

**Comment by reimundILL** [comment]
Thanks for the documentation update!
I only executed the lines from my last comment in the script interpreter. This may be a different issue since the result is on master as well. When I click on `t` the second time, I get `1,2`. The first view showed `1,2,2,3,3`. (Maybe I reported this wrong in the previous comment)

Here is the script:
```Python
t = CreateEmptyTableWorkspace()
t.addColumn("vector_double", "r")
t.addRow([[1.,2.2,3.3]])
```
If you can replicate this, it may be worth opening a new issue for this case. If only I see this behavior, this would be really strange ...

**Comment by reimundILL** [comment]
Well, maybe it's our French dots and comma uses which are different. @soininen spend some time fixing related issues.

**Review by vreimund — APPROVED** [review]
This fixes a bug for `vector_int` table values cleanly and nicely. Tests and documentation were added. I tested on Ubuntu 16.04 where the original behavior for this issue was an unhandled exception.

I think there is still a related issue for `vector_double` table columns:
With the changes applied here, the script
```Python
t = CreateEmptyTableWorkspace()
t.addColumn("vector_double", "r")
t.addRow([[1.,2.2,3.3]])
```
produces now stable `1,2,2,3,3` and the reason may be or not misinterpretation of dots and commas on French machines. On master, I got first `1,2,2,3,3` and then stable `1,2`.

Something about locale : https://github.com/mantidproject/mantid/pull/18315 but likely unrelated.

**Comment by josephframsay** [comment]
Ah yes, I can reproduce this if I change my number format to French!

**Pull request merged**
