### PR TITLE
Remove Qt3 support requirement

### PR DESCRIPTION
**Pull request by martyngigg**
Removes usage of the Qt3 support library from CMake and fixes up the remaining problems that occur.

**To test:**

Code review mainly but it would be wise to double check the label tool still works as expected as some of the code was improved.

Refs  #16509

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by quantumsteve** [comment]
I noticed that `QObject::tr()` was removed in a few places. Was this intentional?

**Comment by martyngigg** [comment]
I removed it in a few places where it was not wrapping a string literal as allowing the translation mechanism doesn't seem to make sense there.

**Comment by AndreiSavici** [comment]
I've looked at some plots, tables, instrument view. Tested some of the menus, fitting dialog, colormaps, docking/undocking windows, custom dialog (BinMD, Fit), script window, history.
The fit dialog is giving me some problems, but that's not related to Qt3: ```MantidApplication-[Fatal] Unexpected exception: MultiDomainCreator expected, found N6Mantid12CurveFitting5FitMWE```
OS tested: Ubuntu 15.10
:shipit:

**Comment by martyngigg** [comment]
Thanks, Andrei!

**Pull request merged**
