### PR TITLE
Add NormalisationSpectra algorithm

### LINKED ISSUE #15481: Add IndirectNormSpectra Algorithm
Vicky has requested a simple algorithm that is designed to normalise each spectrum in a workspace so that the peak maximum is 1. 
Spencer has provided a suitable algorithm to do this however it does require a unit test to be written as well as documentation.

### PR DESCRIPTION
**Pull request by ElliotAOram**
The new NormaliseSpectra Algorithm has been added along with a unit test and documentation
# To Test
- This can be tested with the following script:

```
  # Create Workspace
  data = '1,2,3,4,5'
  ws = CreateWorkspace(DataX=data, DataY=data, DataE=data, Nspec=1)

  # Execute algorithm
  out_ws = NormaliseSpectra(InputWorkspace=ws)
```
- After running this, ensure that the workspace has no y values larger than 1 and less than 0.
- It would be good to test this with negative data and data containing zeros
  - This can be done by changing the input data for the `CreateWorkspace` algorithm in the script above

Fixes #15481

**[Release notes](http://www.mantidproject.org/Release_Notes_3_7_Indirect_Inelastic#Algorithms)**

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [ ] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AndreiSavici** [comment]
Here are a couple of scenarios that are not covered in your code:
* for a particular spectrum, all y values are negative. All new values will become positive, with the minimum y to be 1
* for a particular spectrum, all y values are negative, except one that is 0. All new y values will be NANs

Is there a reason to just have this algorithm working for indirect?

**Comment by ElliotAOram** [comment]
@AndreiSavici thanks, I'll look into addressing those issues.
This is not my code originally. However, I don't see a reason for to only be Indirect as it's functionality is pretty general. I will double check with the author, but I can't imagine it would be a problem for it to be general.

**Comment by AndreiSavici** [comment]
A spectrum from 0.3 to 1 is left unchanged (minimum is 0.3), but a spectrum from -0.3 to 1 is transformed such as the minimum is 0. This behaviour is not the only choice, so it should be documented. I would have expected that the first case is also transformed such as minimum is 0

**Comment by AndreiSavici** [comment]
:shipit:

**Pull request merged**
