### PR TITLE
Indirect - Vesuvio - Add option to calculate Cumulative Angle-Averaged Data within driver script

### LINKED ISSUE #21787: Indirect - Vesuvio - Add option to calculate Cumulative Angle-Averaged Data in driver script
The VESUVIO instrument scientists have requested for a method by which to increase the information content of NCS data, by providing an option within the VESUVIO driver script to compute Cumulative Angle-Averaged Data (CAAD).

CAAD is calculated by computing the sum of each fit normalised by its integral. Each component of this num (i.e. each fit normalised by its integral), should also be output as a workspace group.

### PR DESCRIPTION
**Pull request by brandonhewer**
The VESUVIO instrument scientists have requested for a method by which to increase the information content of NCS data, by providing an option within the VESUVIO driver script to compute Cumulative Angle-Averaged Data (CAAD).

CAAD is calculated by computing the sum of each fit normalised by its integral. Each component of this num (i.e. each fit normalised by its integral), should also be output as a workspace group.

This PR adds the CAAD method to the Vesuvio Driver Script along with a new boolean flag, ```calculate_caad```, which provides users a manner by which to enable/disable the computation of the Cumulative Angle-Averaged Data.

**To test:**
1. Ensure the directory containing the provided IP file is included in the directories MANTID will search.
2. Load the provided script within MANTID's script window.
3. Execute the script.
4. Ensure two group workspaces named ```23271-23263_CAAD_normalised_iteration_1``` and ```23271-23263_CAAD_normalised_iteration_2``` can be found in the ADS.
5. Within these group workspaces, ensure there are three workspaces with the same name of the group preceded by ```_Calc```, ```_GaussianComptonProfile```, ```_GaussianComptionProfile2```.
6. Ensure each of these workspaces has 3 spectra.
7. Ensure two group workspaces named ```23271-23263_CAAD_sum_iteration_1``` and ```23271-23263_CAAD_sum_iteration_2``` can be found in the ADS.
8. Within these group workspaces, ensure there are three workspaces with the same name of the group preceded by ```_Calc```, ```_GaussianComptonProfile```, ```_GaussianComptionProfile2```.
9. Ensure of of these workspaces has a single spectrum.

**Test Data**
[vesuvio_test_files.zip](https://github.com/mantidproject/mantid/files/1745114/vesuvio_test_files.zip)

Fixes #21787. 

**Release Notes** 
Change added to the release notes.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by ElliotAOram — COMMENTED** [review]
Changes work as described.  @brandonhewer is there anyway we can get the new functionality under testing? I must admit I can't remember the structure of Vesuvio testing!

**Comment by brandonhewer** [comment]
@ElliotAOram Yes, I'll add some additional testing of the script. Tests for the vesuvio commands script can be found in Testing > SystemTests > tests > analysis > VesuvioCommandsTest.py

**Comment by ElliotAOram** [comment]
Thanks, just let me know when you'd like me to give it another look.

**Review by ElliotAOram — CHANGES_REQUESTED** [review]
If you give `flags['calculate_caad'] = "string"` rather than True/False, this still runs to completion without error. The other properties in the driver script appear to have validation, so we should add some validation to this also.

**Comment by brandonhewer** [comment]
This is a great point, I'll add this check in to the script.

**Review by ElliotAOram — APPROVED** [review]
Thanks for the changes @brandonhewer . This now works well and the validation is good. Ready to be merged when it passes the build servers.

**Comment by SimonHeybrock** [comment]
Failed doctest is due to unrelated sphinx warning (see #jenkins on Slack, fixed in master), merging.

**Pull request merged**
