### PR TITLE
IN16B instrument configuration

### PR DESCRIPTION
**Pull request by gvardany**
**Description of work.**
This PR implements for IN16B:

- secondary PSD configuration, with the first tube angle at 33.1 degree (plus its test)
- fixes the analyser distance for the single detectors through IDF (system test reference updated)
- flips the entire detector to the correct side wrt the beam (this has no real effect)
- removes .map grouping file, changes .xml grouping file to use `detids` instead of `ids`
- adds more rules in run merging behaviour through parameters file

**To test:**

1. Load the run 247933.nxs in the unit tests data, under ILL/IN16B.
2. Right click > show detectors.
3. Scroll down to the pixel with ID=65, two theta should be 33.1 degrees.
4. Scroll down further, the pixels with ID=2049 and 2050 should have R = 4 meters.

*There is no associated issue.*

*Release notes have been updated.*

The IDF change is done with the updated generator script, so

**Merge also PR [#140](https://github.com/mantidproject/mantidgeometry/pull/140) in mantidgeometry.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by dtasev — CHANGES_REQUESTED** [review]
I'm seeing detector id 65 with Theta of 17.1, and det id 2049 with R of 4.1, which are different from the ones expected in the "To test" section

**Comment by gvardany** [comment]
@DTasev Could you wipe out the `.mantid/instrument`?

**Comment by DTasev** [comment]
Wiping `.mantid/instrument` fixed the numbers, but I am not sure how that would work to other users in production if the cache is not manually deleted

**Comment by gvardany** [comment]
When it downloads the updated instrument on production, does it not discard the corresponding cache? If not, then it's a general problem with any IDF update.

**Comment by DTasev** [comment]
Possibly, I am not sure, maybe @martyngigg or @NickDraper would know

**Comment by gvardany** [comment]
This update should have a retroactive effect, so I cannot make a new IDF with newer valid-from date; this must override the old one. In the contrary, the `last-modified` date is updated, so the caching mechanism could check on this and wipe-out the cache if it is newer?

**Comment by martyngigg** [comment]
So I think this is hitting the fact that `last-modified` is actually not used to determine the correct IDF - it's purely the `valid-from` date and it the order it looks in is user downloaded cache followed by install. I think we just assumed that the `valid-from` date would always be changed so that we could pick purely on that. 

Is this a case where the old one was "wrong" and this just wants to replace it for all time?

**Comment by gvardany** [comment]
Yes, but of course I can bump up 1900 to 1901 if you think that would help.

**Comment by martyngigg** [comment]
@gvardany It should do (https://github.com/mantidproject/mantid/blob/master/Framework/API/src/ExperimentInfo.cpp#L992). This would be the easiest solution rather than modifying the instrument file searching code. It probably depends on whether you feel this is likely to be an issue quite a lot?

**Comment by gvardany** [comment]
I don't expect this kind of situations too often, but neither too rare. This could potentially be improved in future. For the moment will augment the `valid-from`.

**Review by dtasev — APPROVED** [review]
That did it, changing the `valid-from` forced the instrument cache to be rebuilt, without me deleting the instrument folder manually.

**Pull request merged**
