### PR TITLE
Fix performance regressions caused by regex matches 

### LINKED ISSUE #15856: Performance test LoadEventNexusTestPerformance affected by StructuredDetector
Looking at the performance test, I can see a significant jump in the execution time for these tests following the introduction of #15744 

screen shot 2016-04-07 at 09 24 52

**Also Affected**
x3 slowdown in DataHandlingTest.LoadEventPreNexusTestPerformance.testDefaultLoad

screen shot 2016-04-07 at 09 32 09

### Steps to reproduce the behaviour

You should run the performance tests yourself before and after merge commit dc9168cc48abd3f5689c8371c0d7949dba674438 to see the timings for yourself and then identify and fix the issue.

### Platforms affected

Likely all platforms

### PR DESCRIPTION
**Pull request by MikeHart85**
This addresses #15856 by optimizing the regex matches introduced in #15744.

Originally, regex matches introduced a significant slowdown. 

Reverting to string comparisons was explored as an option, but ultimately it turned out that the regex code could easily be optimized to nearly the same performance levels. 

Just making the regex expression definition `static` had a profound effect. Should be considered for other usages as well, where the expression is constant.

**To test:**

Run `DataHandlingTest LoadEventNexusTestPerformance` and `DataHandlingTest LoadEventPreNexusTestPerformance` and observe differences before and after this PR. 

It would be best to compare performance against dc9168c, to avoid other changes influencing test results.

Fixes #15856.

_Does not need to be in the release notes. (Addresses regression that was never released)_

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by MikeHart85** [comment]
After testing an alternative approach, I've switched back to using regex again instead of string comparisons.

Simply adding a `static` keyword in front of the `boost::regex exp` definition improved performance by almost the same amount as using string comparisons, since this way the expression is only parsed once. Removing the capture groups around individual terms shaved it down a little more, bringing it even closer.

Overall, the regex matches are still a tiny bit slower than string comparisons, but the difference is so tiny that it should be negligible. Thus regex is preferred as being a bit cleaner and more flexible.

Updating PR description to match new approach.

**Comment by MikeHart85** [comment]
It looks like Lamar checked everything but hasn't tagged it for shipping yet.

Since he's off sick and a code freeze is imminent, I'll go ahead and tag it.

:shipit:

**Comment by OwenArnold** [comment]
@LamarMoore I've asked Michael to add the :shipit: since I don't know why you would approve the checklist and not raise a comment about any further problems. I therefore assume that you forgot to add :shipit:

**Comment by OwenArnold** [comment]
Looks good to me.

**Pull request merged**
