### PR TITLE
Include python qtawesome as a dependency

### PR DESCRIPTION
**Pull request by martyngigg**
Description of work.

Adds `qtawesome` to `.deb` & `.rpm` dependencies along with shipping packages for macOS.

Required for mslice.

**To test:**

* Code review.

*No issue*

**Release Notes** 
*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by soininen** [comment]
On Ubuntu 14.04, when I build the package and try installing it, I get the error:
```
mantid depends on python-qtawesome; however:
  Package python-qtawesome is not installed.
```

The standard fix is to `apt-get update` and `apt-get -f install`, but this time it didn't work because python-qtawesome is not available in any repository, including the Mantid ppas. Or maybe I'm doing something wrong here?

**Comment by martyngigg** [comment]
@soininen Thanks for spotting that. It looks like I neglected to build `qtawesome` for 14.04. That shouldn't be too hard.

**Comment by martyngigg** [comment]
@gvardany @OwenArnold @keeeto I've built a macOS package and placed it at http://files.mantidproject.org/kits/testing/pr-22072/mantid-3.11.20180314.907-Yosemite.dmg. Would you be able to check that you can open MantidPlot and run `import qtawesome` in the script window?

**Comment by keeeto** [comment]
Works for me.

**Comment by martyngigg** [comment]
Thanks @keeeto.

@soininen There should be a version of `python-qtawesome` for 14.04 in the mantid ppa now. Could you try again?

**Comment by soininen** [comment]
`python-qtawesome` is now found from the ppas and the package installs without issues.

**Review by soininen — APPROVED** [review]
Works now on Ubuntu 14.04 and reportedly on macOS as well.

**Comment by LamarMoore** [comment]
Works on Centos 7.

**Pull request merged**
