### PR TITLE
Configure black in pre-commit

### PR DESCRIPTION
**Pull request by peterfpeterson**
**Description of work.**

This removes the yapf configuration in favor of black.

**To test:**

Try out using black from an IDE on a file (don't commit it) and see that the instructions are correct. The only thing non-standard is that we have 140 character line length.

*There is no associated issue.*

*This does not require release notes* because it is a change that developers can opt into and does not affect end users.

---

**Notes about splitting up refactor** this is a count of `.py` files in the subtrees (early Dec 2022)
* 13 - buildconfig
* 18 - dev-docs
* 27 - docs
* 878 - Framework
  * 870 - PythonInterface
    * 52 - mantid
    * 381 - plugins
    * 436 - test
  * 8 everything else
* 1489 - qt
  * 428 - python/mantidqt
  * 912 - python/mantidqtinterfaces
  * 149 - everything else
* 635 - scripts
* 332 - Testing
  * 10 PerformanceTests
  * 299 - SystemTests
  * 23 - Tools

My recommendation for reformatting the repository is to
1. exclude `Framework`, `qt`, `scripts`, and `Testing` will format 58 files
2. include `Testing` will add 332 files
3. include `scripts` will add 635 files
4. change from `Framework` to `Framework/plugins` will add 497 files
5. include `Framework/plugins` will add 381
6. change from `qt` to `python/mantidqtinterfaces` will add 577 files
7. remove all excludes

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
is it worth leaving this until after the code freeze? We can then update the Python files for maintenance. Should give us a cleaner history.

**Comment by peterfpeterson** [comment]
Would it be good to add a `pyproject.toml` with correct configuration for black to get people moving in the right direction? It'd be a new PR without the pre-commit changes.

**Comment by martyngigg** [comment]
It is nice to avoid code-base wide formatting change commits as it makes the whole history harder to navigate and makes merge conflict resolution difficult for those with un-merged code. The downside of the format as we go is then reviewing becomes more difficult for people to complete without missing something. Can we figure out a way to have both without having to wait 2 months to try and doing things like this? The waiting just means we don't end up doing them...

How can we make reviews simple when potentially large formatting changes have been made?

**Comment by peterfpeterson** [comment]
Unfortunately, there is no "easy" solution. At some point there is going to be a  place in history where `git blame` is going to say everything has changed. I'm leaning towards adding appropriate configuration to a `pyproject.toml` and advertise it so people can start reformatting their code early.

There are 3 options for moving forward from there (no order):
1. Split out the auto-formatting into a couple of PRs based on parts of the directory-tree. Then we can have pre-commit configured to only look at the sub-directories that have been formatted. The transition could be spread out that way over the whole dev-cycle.
2. Set pre-commit up to enforce black on all changed files, but not on the repository as a whole. During maintenance change the configuration to hit everything.
3. Do the big change all at once "now" and communicate with the dev team it is happening.

**Review by martyngigg — APPROVED** [review]
I'm happy with this now in that it's not actually doing anything in pre-commit itself - just adding the configuration to get the formatters setup.

**Pull request merged**
