### PR TITLE
New CHESS IDF file and Parameter file

### PR DESCRIPTION
**Pull request by GabrielHawk**
**Description of work.**

New CHESS IDF file
Changed MaskBTP algorithm
Changed Q/E coverage and DGSPlanner interfaces to work with CHESS

**To test:**

Make sure that `LoadEmptyInstrument` with CHESS works fine.
Make sure that MaskBTP, Q/e coverage and DGSPlanner work fine.

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by AndreiSavici — APPROVED** [review]
Work as expected

**Comment by martyngigg** [comment]
This only came to mind after I merged it. Should `CHESS` be added to the `Facilities.xml` file too?

**Comment by AndreiSavici** [comment]
@martyngigg Pete added it to the `Facilities.xml` in a previous PR

**Comment by martyngigg** [comment]
@AndreiSavici Cool. Thanks for confirming!

**Pull request merged**
