### PR TITLE
Serialise the Instrument View to Mantid project files

### LINKED ISSUE #16962: Better serialisation for the instrument window
This is a sub issue for #15602.

Currently this is saved to the project file, but none of the options etc. that the user may have applied are stored.

### PR DESCRIPTION
**Pull request by samueljackson92**
Saving a Mantid project file should now also include all of the necessary information for an instrument window to recreate itself afterwards

**To test:**
- Open the instrument view on a workspace with an instrument and play around with the different options. 
- Save the instrument view by saving to a Mantid project file.
- Close and reopen Mantid and reload the project. 
- The window should be recreated (along with any workspaces) exactly as it was before.

There are quite a lot of options on this interface so please try to be thorough and check as much as you can. One idea would be to run through the guide below and save the project periodically:

http://www.mantidproject.org/MantidPlot:_Instrument_View

Fixes #16962.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
Works as expected having tested multiple times, but when I changed the range of values in the colour map (in Render tab), this was not preserved.  Also the opening of the tree in the instrument tab was not preserved, but the selected component was preserved and the tree left open far enough to show it.

Also another issue beyond the scope of this issue, the default folder for saving the project is the folder made by the previous save project rather than the folder that contains it.

Looks good :shipit:

**Comment by samueljackson92** [comment]
@KarlPalmen This should not be shipped until those issues are fixed as both of those points should be serialised.

Yes the default folder thing is an issue, but beyond scope here.

**Comment by samueljackson92** [comment]
This was merged before I could make the changes suggested by @KarlPalmen. Please see #17269 for those fixes. @KarlPalmen could you kindly test that one?

**Comment by peterfpeterson** [comment]
Sorry about that. In the future, delete the squirrel if it shouldn't be shipped.

**Pull request merged**
