### PR TITLE
Allow packaging on macOS when ENABLE_MANTIDPLOT=OFF

### LINKED ISSUE #28833: Cannot properly package on OSX with only ENABLE_WORKBENCH and not ENABLE_MANTIDPLOT
These lines are offenders. Note they are under `ENABLE_MANTIDPLOT` condition

https://github.com/mantidproject/mantid/blob/master/buildconfig/CMake/DarwinSetup.cmake#L239-L273

Note that it is also assumed that `MantidPlot` will be created here https://github.com/mantidproject/mantid/blob/master/installers/MacInstaller/CMakeDMGSetup.scpt#L42-L46

Should be easy enough to refactor.

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Ensures that if MantidPlot is disabled in cmake with `-DENABLE_MANTIDPLOT` then the macOS package only contains the MantidWorkbench bundle and not other stray directories.

**To test:**

* First build with cmake flags `-DENABLE_CPACK=ON -DENABLE_MANTIDPLOT=ON -DENABLE_WORKBENCH=ON` and run the `package` target. The package should still contain both MantidPlot & Workbench.
* Now try disabling MantidPlot and check the package on contains workbench.
* A package without either is not yet supported nor is a package with only MantidPlot.

Fixes #28833
Refs #28650

*This does not require release notes* because **it is an internal issue.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DavidFair** [comment]
I'm running into the following with Mantid Plot off:
```
dyld: Library not loaded: @rpath/libcodedirectory.dylib
  Referenced from: /Library/Developer/CommandLineTools/usr/bin/install_name_tool
  Reason: image not found

CMake Error at /Users/<snip>/mantid_build/qt/applications/workbench/cmake_install.cmake:69 (message):
  Package script failed!!!

Call Stack (most recent call first):
  /Users/<snip>/mantid_build/qt/applications/cmake_install.cmake:42 (include)
  /Users/<snip>/mantid_build/qt/cmake_install.cmake:62 (include)
  /Users/<snip>/mantid_build/cmake_install.cmake:55 (include)

CPack Error: Error when generating package: mantidunstable
```

That being said I can't test with Mantid Plot enabled so can't tell if were referencing a library which gets left around from building Mantid Plot or a local issue

**Comment by martyngigg** [comment]
Thanks. That's weird.

The script runs the tool `install_name_tool` to change the RPATHS in all of the shipped libraries. It looks like that is failing to start. Does `install_name_tool -h` work for you?

**Comment by martyngigg** [comment]
@DavidFair Did you get anywhere with fixing `install_name_tool`?

**Comment by DavidFair** [comment]
I'm currently blocked by: https://bitbucket.org/jamesrhester/pycifrw/pull-requests/11

As CPack tries to pull in the upstream version and locally the compiler doesn't pull in the right headers

**Review by DanielMurphy22 — APPROVED** [review]
Test instructions work well for me. I'm not sure if the problem @DavidFair is seeing needs resolved here or not.

**Comment by DavidFair** [comment]
No, it's a system issue I'm seeing unrelated (as master has the same). Thanks for approving in the mean time

**Pull request merged**
