### PR TITLE
Indirect - QENS Fitting - Fix the output format of the QENS fitting algorithms

### LINKED ISSUE #22672: Indirect - QENSFit(Simultaneous/Sequential) - Separate result table required per data-set.
The QENSFitSimultaneous and QENSFitSequential algorithms are appending the parameter values to one in the result workspace -- each data-set result is appended to the right of the last.

As a result of this formatting of the output, it is not possible to extract reasonable plots for the parameters across each individual data-set and the current result is particularly hard to interpret.

### PR DESCRIPTION
**Pull request by brandonhewer**
The output format of the QENS fitting algorithms is currently incorrect; the result parameters for each data-set are appended next to one another in a single workspace.

This PR modifies the existing QENS fitting routines, such that a workspace group is output with the parameters of each data-set.

**This PR must be merged after #22624**

**To test:**
1. Navigate to Interfaces > Indirect > Data Analysis > ConvFit.
2. Click on the 'Multiple Input' tab button.
3. Use the 'Add Workspace' button to add the provided test data (irs26173 and irs26176, both with resolution irs26173). Any option may be used in the spectra input.
4. Select 'One Lorentzian' in the 'Fit Type' drop-down menu.
5. Check the check-box labelled 'Use Delta Function'.
6. Select 'Flat Background' in the 'Background Type' drop-down menu.
7. Click 'Run' and wait for the fit to complete.
8. Ensure a '*_Result' workspace group has been created and it contains a result for irs26173 and irs26176, both of which contain FWHM, Amplitude, Height and EISF parameter values.

Fixes #22672. 

Does this update require release notes?
- [ ] Yes
- [x] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by mantid-roman** [comment]
The workspaces are created as described but I can see a few of Qt error messages when I work with the interface:

```
Object::connect: No such slot MantidQt::CustomInterfaces::IDA::ConvFitDataPresenter::updateTableFromSingleData()
Object::connect:  (sender name:   'fitDataView')
Object::connect: No such slot MantidQt::CustomInterfaces::IDA::MSDFit::plotClicked()
Object::connect:  (sender name:   'pbPlot')
Object::connect: No such signal MantidQt::CustomInterfaces::IDA::IndirectFitDataPresenter::singleResolutionLoaded()
Object::connect: No such signal MantidQt::CustomInterfaces::IDA::IndirectFitDataPresenter::singleResolutionLoaded()
Object::connect: No such signal MantidQt::CustomInterfaces::IDA::IndirectFitDataPresenter::singleResolutionLoaded()
Object::connect: No such slot MantidQt::CustomInterfaces::IDA::IqtFit::parameterUpdated(const Mantid::API::IFunction *)
Object::connect: No such signal MantidQt::CustomInterfaces::IDA::IndirectFitDataPresenter::singleResolutionLoaded()
Object::connect: No such signal MantidQt::CustomInterfaces::IDA::IndirectFitDataPresenter::singleResolutionLoaded()
Object::connect: No such signal MantidQt::CustomInterfaces::IDA::IndirectFitDataPresenter::singleResolutionLoaded()
Object::connect: No such signal MantidQt::CustomInterfaces::IDA::JumpFitDataPresenter::singleResolutionLoaded()
Object::connect: No such signal MantidQt::CustomInterfaces::IDA::JumpFitDataPresenter::singleResolutionLoaded()
Object::connect: No such signal MantidQt::CustomInterfaces::IDA::JumpFitDataPresenter::singleResolutionLoaded()
```

```
QTableWidget: cannot insert an item that is already owned by another QTableWidget
```

```
Object::connect: No such slot MantidQt::CustomInterfaces::IDA::ConvFit::updateGuessPlots()
Object::connect:  (sender name:   'fitPropertyBrowser')
```

**Review by mantid-roman — CHANGES_REQUESTED** [review]
I have unexpected exceptions in Indirect Data Selection dialog if I 
* Tick All Spectra before selecting the files
* Put garbage in Workspace Indices box

**Comment by mantid-roman** [comment]
Putting spaces around the `-` in Workspace Indices also gives an exception.

**Comment by mantid-roman** [comment]
Mantid crashes when I remove the last workspace from the table.

**Comment by mantid-roman** [comment]
Mantid stops responding if I hit Run multiple times.

**Comment by brandonhewer** [comment]
@mantid-roman Could you explain the steps you took before mantid crashed after removing from the table?

**Comment by mantid-roman** [comment]
* I load the three workspaces: 2 reds and a res.
* I go to Multiple Input and add one spectrum from each red workspace (I change to `Workspace` in the drop-box).
* Then I remove the inputs from the  table one by one. On the last one Mantid crashes.

I am doing this on Windows.

**Comment by brandonhewer** [comment]
@mantid-roman The issue with the run button being disabled is a pre-existing issue and is true across all Indirect interfaces -- I have created another issue for this #22844.

**Comment by mantid-roman** [comment]
@brandonhewer It's not the issue I am seeing. I click Run after fit finishes. The second time I click Run processing finishes but new workspaces get created. After fit finishes I click Run again and this time Mantid freezes.

**Comment by mantid-roman** [comment]
I have one more error:

* Add the first workspace. Set workspace index to 0.
* Add the second workspace but don't set any index. The dialog lets you do it.
* Set the function and click Run.

Unexpected exception:
```
WorkspaceGroup - index out of range. Requested=1, current size=1
```

**Comment by brandonhewer** [comment]
The issues mentioned above should now be fixed.

**Comment by mantid-roman** [comment]
Those issues are fixed. I have two more:
1. The spectrum index control (both in the dialog and on the main page) let you enter spaces after commas. Those spaces go into the workspace names: 1,2 and 1,   2 make different workspaces. It is also possible to copy and paste tabs and new line symbols.
2. Load the data table then delete the workspaces in the workspace dock widget. Click Run. Mantid crashes.

**Comment by brandonhewer** [comment]
@mantid-roman 
For 2:
If I remove the workspaces from the ADS, I get a crash before I'm ever able to click 'Run'. What are the steps you are taking to reach the crash in issue 2? If it's the same error -- then as this is pre-existing (and an issue across all Indirect interfaces) -- this is perhaps best solved in a separate PR.

**Comment by brandonhewer** [comment]
Issue of deleting workspaces created here: https://github.com/mantidproject/mantid/issues/22893

**Comment by brandonhewer** [comment]
@mantid-roman The issue with spectra selection should now be fixed.

**Review by mantid-roman — APPROVED** [review]
Cannot break it any more.

**Pull request merged**
