### PR TITLE
Fix SimulatedDensityOfStates doc test

### PR DESCRIPTION
**Pull request by DanNixon**
Run doc test for `SimulatedDensityOfStates`, it should work.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
The code change addresses the test complain and all doc tests already passed on ubuntu, so not waiting for all the builds to finish.

**Comment by DanNixon** [comment]
Worth noting though, all tests also passed on the PR that introduced the issue (#13454).

**Comment by FedeMPouzols** [comment]
Yes, @martyngigg is this a new attack from the strange issue with the doc tests?

**Comment by martyngigg** [comment]
I think so. For some reason new doc tests on the nightly version always run all tests but the pull requests are skipping any new (and in this case renamed) tests for the first time. Subsequent runs seem to be okay.

**Comment by DanNixon** [comment]
So would have manually rebuilding the Ubuntu build have picked the error up?

**Comment by martyngigg** [comment]
I think so. Checking a couple of newer pull requests seems to suggest that they are run. To try and mitigate this I've put some code in the build script to try and force a complete reparse of all of the documentation for tests. Hopefully this will help...

**Pull request merged**
