### PR TITLE
mark DSFInterp and DSFInterp1DFit  for deprecation

### LINKED ISSUE #36292: Deprecate DSFInterp1DFit fit function and DSFInterp algorithm
Mark `DSFInterp1DFit` and `DSFInterp` to be deprecated and warn they will be removed in Mantid 6.10.There should at least be a stable release (in this case, 6.9) where the deprecated warnings are implemented. 

Files to be removed in 6.10
```
./docs/source/images/DSFinterp_fig3.png
./docs/source/images/DSFinterp_fig4.png
./docs/source/images/DSFinterp_local_regression.png
./docs/source/algorithms/DSFinterp-v1.rst
./Framework/PythonInterface/test/python/plugins/functions/DSFinterp1DFitTest.py
./Framework/PythonInterface/test/python/plugins/algorithms/DSFinterpTest.py
./Framework/PythonInterface/plugins/functions/DSFinterp1DFit.py
./Framework/PythonInterface/plugins/algorithms/DSFinterp.py
```

### PR DESCRIPTION
**Pull request by jmborr**
**Description of work**
Mark `DSFInterp` and `DSFInterp1DFit` as deprecated for next release (and to be removed in the subsequent release).

**Purpose of work**
`DSFInterp` and `DSFInterp1DFit` are not being used, they're not even registered since they try to import a python package not listed as a dependency. Furthermore, support for the dependency has been discontinued.

**To test:**
No need to test as this is only a deprecation warning and both `DSFInterp` and `DSFInterp1DFit` are never registered

Fixes #36292

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by AndreiSavici — APPROVED** [review]

**Review by AndreiSavici — CHANGES_REQUESTED** [review]
In the release notes, there are no references to the algorithm or the fit function, since the library is not available on the build servers. Don't use :ref:

**Review by AndreiSavici — APPROVED** [review]

**Comment by jmborr** [comment]
@AndreiSavici I don't know why but it's taking JENKINS forever to pass the conda (linux and osk) to pass 😢

**Comment by peterfpeterson** [comment]
I think it is because you are the first pull request to run on this server (ornl-mantid-agent04) so it is taking a long time to download the test data.

**Comment by jmborr** [comment]
> I think it is because you are the first pull request to run on this server (ornl-mantid-agent04) so it is taking a long time to download the test data.

🤞 let's drink to that

**Comment by jmborr** [comment]
👯‍♀️ it was a long wait but finally paid off

**Pull request merged**
