### PR TITLE
Indirect Data Analysis I(Q, t)Fit - Ensure sample logs are correctly copied

### LINKED ISSUE #16431: Indirect Data Analysis I(Q, t) Fit - Sample logs are incorrect
**Found by Spencer Howells in Beta Testing**

### Expected behavior
* The sample logs from the original workspace should be copied to the result workspaces

### Actual behavior
* The sample logs of the results workspaces contain incorrect values

### Steps to reproduce the behavior
* Run IqtFitSequential
* See Sample logs are incorrect in the `_Result` and `_Workspaces` workspace

### Platforms affected
* All

### PR DESCRIPTION
**Pull request by ElliotAOram**
The sample logs for both `IqtFitMultiple` and `IqtFitSequential` are now copied correctly from the input workspace to the outputworkspaces. Additional sample logs are also added correctly.

**To test:**
- Run the following script ensuring you uncomment the tests to run them:

```
#### TEST IqtFitSequential ####

'''
mtd.clear()

iris26176_graphite002_iqt = Load(Filename='iris26176_graphite002_iqt.nxs')
function = r'name=LinearBackground,A0=0,A1=0,ties=(A1=0);name=UserFunction,Formula=Intensity*exp(-(x/Tau)),Intensity=1,Tau=0.0247558;ties=(f1.Intensity=1-f0.A0)'

result, params, fit_group = IqtFitSequential(InputWorkspace=iris26176_graphite002_iqt,
                                                           Function=function,
                                                           FitType='1E_s',
                                                           StartX=0,
                                                           EndX=0.24,
                                                           SpecMin=0,
                                                           SpecMax=16,
                                                           ConstrainIntensities=True)'''
#### TEST IqtFitMultiple ####                                                      
'''
mtd.clear()

iris26176_graphite002_iqt = Load(Filename='iris26176_graphite002_iqt.nxs')
function = r'name=LinearBackground,A0=0.027668,A1=0,ties=(A1=0);name=UserFunction,Formula=Intensity*exp(-(x/Tau)^Beta),Intensity=0.972332,Tau=0.0247558,Beta=1;ties=(f1.Intensity=1-f0.A0)'

result, params, fit_group = IqtFitMultiple(InputWorkspace=iris26176_graphite002_iqt,
                                                    Function=function,
                                                    FitType='1S_s',
                                                    StartX=0,
                                                    EndX=0.2,
                                                    SpecMin=0,
                                                    SpecMax=16,
                                                    ConstrainIntensities=True)'''
```
- For each test ensure that:
  - The sample logs from the original `iris26176_graphite002_iqt` workspace are copied to the `result` and `fit_group` workspace
  - These workspaces also contain entries for `fit_type, intensities_constrained, beta_constrained, end_x, start_x`

Fixes #16431 

[RELEASE NOTES](https://github.com/mantidproject/mantid/blob/5ab2b1359ea0441a1fc5d15dd0757784791245f5/docs/source/release/v3.7.0/indirect_inelastic.rst#bugfixes)

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by LamarMoore** [comment]
Works as described. :shipit:

image

**Comment by FedeMPouzols** [comment]
@LamarMoore : did you mean to put the squirrel?

**Comment by LamarMoore** [comment]
@FedeMPouzols I put the squirrel before but there was a merge conflict. I am waiting for the build to finish before I put the squirrel again.

**Comment by LamarMoore** [comment]
:shipit:

**Pull request merged**
