### PR TITLE
Muon analysis opens to home tab

### PR DESCRIPTION
**Pull request by AnthonyLim23**
The muon analysis GUI should now always open to the home tab (in master it opens to the settings tab). 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
Opens at Home tab.

**Comment by martyngigg** [comment]
The failing test is unrelated to the changes. It is on the list of unreliable tests.

**Comment by martyngigg** [comment]
@KarlPalmen If you are happy could you attach the squirrel, please?

**Comment by KarlPalmen** [comment]
Yes :shipit:

**Pull request merged**
