### PR TITLE
Muon analysis GUI bugs

### PR DESCRIPTION
**Pull request by AnthonyLim23**
Some bug fixes to remove messages from the terminal window when using muon analysis. 

The master branch currently produces the following messages when muon analysis is started: ``QObject::connect: Cannot connect (null)::currentItemChanged(QtBrowserItem *) to MantidQt::MantidWidgets::MuonFitPropertyBrowser::currentItemChanged(QtBrowserItem *)
Object::connect: No such signal MantidQt::MantidWidgets::MuonFitDataSelector::selectedGroupsChanged() in ../../MantidQt/CustomInterfaces/src/Muon/MuonAnalysis.cpp:2134
Object::connect:  (sender name:   'MuonFitDataSelector')
Object::connect:  (receiver name: 'MuonAnalysis')
Object::connect: No such signal MantidQt::MantidWidgets::MuonFitDataSelector::selectedPeriodsChanged() in ../../MantidQt/CustomInterfaces/src/Muon/MuonAnalysis.cpp:2136
Object::connect:  (sender name:   'MuonFitDataSelector')
Object::connect:  (receiver name: 'MuonAnalysis')
Object::connect: No such signal MantidQt::CustomInterfaces::MuonAnalysis::setChosenGroupSignal(QString &) in ../../MantidQt/CustomInterfaces/src/Muon/MuonAnalysis.cpp:321
Object::connect:  (sender name:   'MuonAnalysis')
Object::connect:  (receiver name: 'MuonAnalysis')
Object::connect: No such signal MantidQt::CustomInterfaces::MuonAnalysis::setChosenPeriodSignal(QString &) in ../../MantidQt/CustomInterfaces/src/Muon/MuonAnalysis.cpp:323
Object::connect:  (sender name:   'MuonAnalysis')
Object::connect:  (receiver name: 'MuonAnalysis')
``

This new branch should not produce these messages.

- Load some data (I suggest into HIFI 84447) muon analysis
- go to the settings tab and make sure multiple fitting is selected. 
- Go to the data analysis tab and change the selected groups and selected periods to custom. This should produce some pop ups. 
- Click the Reselect Data buttons (Groups/Pairs and Periods). In master this would produce messages about the layout already being set. In this version that should not happen. 

- In the Grouping Options tab add a group and/or pair. 
- Make sure it is in multiple fitting mode.
- In data analysis press custom for the Groups/Pairs and the added data should be included in the pop up. 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DavidFair** [comment]
I removed the `Leave Me in this release` tag as that is for issues with a PR (and it was confusing me slightly).

**Comment by DavidFair** [comment]
From testing:
Must be fixed:
- Creating a new group and not giving spectrum numbers will cause Mantid to crash

Can be fixed in the future
- The ndet field (from above) is not read only, whilst the number of detectors is calculated correctly a user can still change it to an incorrect value.

**Comment by AnthonyLim23** [comment]
The crash has been added by these changes. I will look into it

**Comment by DavidFair** [comment]
Still get a CTD
Load 84447 from HIFI
Go to Grouping Options

- In box 3 enter a group name.
- Immediately double click row 4 to add a detector ID. This will crash Mantid
I can see this happening if the user misclicks (like I did)

**Comment by AnthonyLim23** [comment]
This bug is in the current release (3.9.2) and I have created a separate issue #19701

**Comment by DavidFair** [comment]
Ok apart from that it addresses the issues described. :shipit:

**Pull request merged**
