### PR TITLE
Improve MC absorption algorithm by refactoring code to use vectors.

### PR DESCRIPTION
**Pull request by aybamidele**
**Description of work.**
Improved code efficiency by refactoring from lists to vector in the MersenneTwister module.
Running `LETReduction_annular_abs_corr_test.py` within [data.zip](https://github.com/mantidproject/mantid/files/3130631/data.zip), this PR took 11 minutes 7.76 seconds while Mantid 4.0 took 13 minutes 25.60 seconds, which is a _19%_ improvement in efficiency.

Refs #25149 . 

*This does not require release notes* because **it is an internal change**.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by peterfpeterson** [comment]
What is the difference between a `Line` (you updated) and a `Track` (used in numerical integration methods)?

**Comment by aybamidele** [comment]
I've had a look at them and it looks as though they're doing similar things. `Track` in addition to manipulating a vector (which is what `Line` does) also caches information about the path between two points that the vector passes through. I've spoken to @martyngigg and we've agreed to merge the two concepts to reduce code duplication.

**Comment by peterfpeterson** [comment]
That should be a separate PR from this.

**Comment by aybamidele** [comment]
Yes. I have created one

**Comment by NickDraper** [comment]
@Pasarus Can you pick up the developer role for this PR to try to get it through?

**Review by martyngigg — APPROVED** [review]
I think the speed improvement here is worth including and we can consider a `small_vector`-based implementation in the future.

**Pull request merged**
