### PR TITLE
Keren function: fix and test with real data

### LINKED ISSUE #16212: Add test for Keren function with real data
The Keren fitting function was added in PR #16210.
When data is available, add a test with this as well as the existing test with fake data.

### PR DESCRIPTION
**Pull request by tom-perkins**
The [Keren](http://docs.mantidproject.org/nightly/fitfunctions/Keren.html) fit function was added new in release 3.7 so that scientists could try it out when data became available.

Now that data is available, fixed a problem that arose from these tests where the field came out with the wrong units. Mantid now gives results within the errors of those from WiMDA - added a system test to confirm this.

Also fixed some small errors in the documentation and added units to the parameter description strings.

**To test:**

The new system test compares Mantid's results to those obtained independently with another program (WiMDA). If you want to test manually as well, the data is available at `\\olympic\babylon5\Scratch\TomPerkins\Data\keren_data`.
- Load a data file into the Muon Analysis interface
- Go to "Data Analysis" tab
- Set up a function of `FlatBackground + Keren`
- Fit the data and compare the results to those in the `kerentest.dat` file, which are the WiMDA results. The results from Mantid should be close to those from WiMDA, though there may be some small differences.
  - In this file "a-baselin" corresponds to _f0.A0_ from the `FlatBackground` and "a-relaxin" is _f1.A_ from `Keren`. Both are x100 because WiMDA uses % asymmetry. "C1 Delta" and "C1 Fluct" are the _Delta_ and _Fluct_ parameters from Keren, and the Field was fixed in the WiMDA fits.

Fixes #16212.

[Release notes](https://github.com/mantidproject/mantid/blob/0c895db330eac562ebd25ea023b304aeae510e78/docs/source/release/v3.8.0/muon.rst#fit-functions) have been updated.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by mantid-roman** [comment]
@tom-perkins Could you correct the doc page for the function?
* In the definition of the relaxation rate the LHS has variable t while the RHS has x. It should be one variable: either t or x.
* In the next sentence Delta should be \Delta (backslash is missing).

**Comment by tom-perkins** [comment]
That should have already been done in commit [b44263](https://github.com/mantidproject/mantid/pull/16645/commits/b44263a7e1386703f8f53f45fbed530062730c49) - do you see any places I've missed?

**Comment by mantid-roman** [comment]
Sorry, I didn't see that.

**Comment by mantid-roman** [comment]
:shipit:

**Pull request merged**
