### PR TITLE
Better formatting for arrays of values in the sample logs

### PR DESCRIPTION
**Pull request by gui-co**
**Description of work.**

This PR changes the way the list of values are displayed in the samples logs.

The generation of the string in the sample logs relies on the `__str__()` function of the numpy arrays. The defaults options split the line every 75 characters and this prevents the string to be properly extended when the size of the window is changed.

**To test:**

Run the following script,
```python
from mantid.simpleapi import CreateSampleWorkspace

CreateSampleWorkspace(OutputWorkspace="ws")
run = mtd["ws"].getRun()
run.addProperty("test", [9999]*30, True)
```

and check the samples logs.

Without the fix, the list cannot be extended to display all the numbers:
sample_logs

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by sf1919** [comment]
Missing test is running here - https://builds.mantidproject.org/job/pull_requests-conda-linux/2292/

**Review by darominski — COMMENTED** [review]
Thanks for the change, this definitely improves the ability to inspect a list of numbers property in the `SampleLogs` widget. The functionality works well, the only downside I can see is that when one copies the values by hand, they are not formatted as they were previously with line-breaks every 75 characters.

 Could you add a mention to the release note about this formatting change?

**Comment by gui-co** [comment]
Thanks for your review.

I added a comment in the code and a release note.

**Review by darominski — APPROVED** [review]
Thank you for the changes, LGTM.

**Pull request merged**
