### PR TITLE
Stop the peaks viewer overwriting all tables with last loaded

### LINKED ISSUE #31358: Deleting peak in workspace causes sliceviewer to delete peak in view of both tables when plotting integrated and non-integrated peaks
### Expected behavior
When plotting two peak tables (e.g. one integrate one not), if you delete a peak in one workspace (delete row in peaks workspace of table in ADS) then the table in sliceviewer will be updated and will no longer have that peak, the other table will not be effected.

### Actual behavior
Despite the peak still existing in one of the tables, sliceviewer doesn't display it (i.e. it is removed from both tables in the sliceviewer).

### Steps to reproduce the behavior
(1) Run this script to get some data and peaks
```
ws = CreateMDWorkspace(Dimensions='3', Extents='-5,5,-5,5,-5,5',
                       Names='Q_lab_x,Q_lab_y,Q_lab_z', Units='U,U,U',
                       Frames='QLab,QLab,QLab',
                       SplitInto='2', SplitThreshold='50')
expt_info = CreateSampleWorkspace()
ws.addExperimentInfo(expt_info)
# add peak
p = CreatePeaksWorkspace(InstrumentWorkspace='ws', NumberOfPeaks=0, OutputWorkspace='peaks')
pk = p.createPeak([1,1,1]) # axes aligned with viewing axes
p.addPeak(pk)
IntegratePeaksMD(InputWorkspace='ws', PeakRadius=0.6, BackgroundInnerRadius=0.6,
    BackgroundOuterRadius=1, PeaksWorkspace='peaks', OutputWorkspace='peaks_int', 
    Ellipsoid=False, UseOnePercentBackgroundCorrection=False)
```
(2) In the sliceviewer overlay both `peaks `and `peaks_int` tables
(3) Open up one table (e.g. `peaks`) from the ADS, right-click the first row and delete
(4) In sliceviewer the peak will have been removed from both tables

### Platforms affected
Tested on IDAaaS

### PR DESCRIPTION
**Pull request by RichardWaiteSTFC**
**Description of work.**

When multiple peak tables were overlaid in the sliceviewer, the tables would be overwritten with the last table loaded, this was because the constructor of the table view would use the same model for all views if none was explicitly provided.
This bug was introduced in #30791 - thanks @StephenSmith25 who found this fix.

To-Do
- Will add release notes when PRs #31388 and #31391 are merged

**To test:**

(1) Run this script

```
ws = CreateMDWorkspace(Dimensions='3', Extents='-5,5,-5,5,-5,5',
                       Names='Q_lab_x,Q_lab_y,Q_lab_z', Units='U,U,U',
                       Frames='QLab,QLab,QLab',
                       SplitInto='2', SplitThreshold='50')
expt_info = CreateSampleWorkspace()
ws.addExperimentInfo(expt_info)
# add peak
p = CreatePeaksWorkspace(InstrumentWorkspace='ws', NumberOfPeaks=0, OutputWorkspace='peaks')
pk = p.createPeak([1,1,1]) # axes aligned with viewing axes
p.addPeak(pk)
CloneWorkspace(InputWorkspace=p, OutputWorkspace='peaks2')
# delete peak
DeleteTableRows(TableWorkspace='peaks', Rows='0')
```

(2) Open ws in the sliceviewer and overlay both peaks tables - one will be empty, the other will have a single peak.
(3) Follow instructions in #30791 and check that (normal table viewing) still works.

Fixes #31358 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by clayton-tom — DISMISSED** [review]
Fix works as described, approving pending release notes :+1:

**Comment by martyngigg** [comment]
Yeah absolutely. I always like to check rather than just merging when the branch doesn't match what I'd expect. Thanks for clarifying.

**Comment by RichardWaiteSTFC** [comment]
> Yeah absolutely. I always like to check rather than just merging when the branch doesn't match what I'd expect. Thanks for clarifying.

Thanks for catching it!

**Comment by RichardWaiteSTFC** [comment]
Just realised this bug was introduced this release so don't need release notes anyway!

**Pull request merged**
