### PR TITLE
Update algorithms for Python3 - Group 10

### LINKED ISSUE #16739: Update Python algorithms & functions for compatibility with both Python 2 & 3
A cheat sheet is available at http://python-future.org/compatible_idioms.html that details the differences between Python 2 & 3 code. Most of our incompatibilities fall in to one of three categories:

* `print` is now a function and requires parentheses in Python 3
* commas not allowed in `except` clauses.
* `dict.iteritems()` no longer exists 

We need to maintain compatibility with Python 2. See the [Python 3](http://www.mantidproject.org/Python_3) page on the wiki for more detail.

This is an umbrella issue. Please add your username to the list below and include this ticket number in your PR.

1. ~~@martyngigg #16814~~
2. ~~@FedeMPouzols #16993~~
3. ~~@rosswhitfield #16952~~
4. ~~@rosswhitfield #16953~~
5. ~~@MichaelWedel #17052~~
6. ~~@DavidFair #17575~~
7. ~~@DavidFair #17579~~
8. ~~@DavidFair #17595~~
9.  ~~@rosswhitfield #16976~~
10. @rosswhitfield

**Group 1**
PythonInterface/plugins/algorithms/AlignComponents.py
PythonInterface/plugins/algorithms/ApplyNegMuCorrection.py
PythonInterface/plugins/algorithms/BASISReduction311.py
PythonInterface/plugins/algorithms/BASISReduction.py
PythonInterface/plugins/algorithms/CalculateSampleTransmission.py
PythonInterface/plugins/algorithms/CalibrateRectangularDetectors.py
PythonInterface/plugins/algorithms/CheckForSampleLogs.py
PythonInterface/plugins/algorithms/CleanFileCache.py
PythonInterface/plugins/algorithms/CollectHB3AExperimentInfo.py
PythonInterface/plugins/algorithms/CompareSampleLogs.py
PythonInterface/plugins/algorithms/ComputeCalibrationCoefVan.py
PythonInterface/plugins/algorithms/ComputeIncoherentDOS.py
PythonInterface/plugins/algorithms/ConjoinFiles.py
PythonInterface/plugins/algorithms/ConjoinSpectra.py
PythonInterface/plugins/algorithms/ConvertSnsRoiFileToMask.py
PythonInterface/plugins/algorithms/CorrectLogTimes.py
PythonInterface/plugins/algorithms/CorrectTOF.py
PythonInterface/plugins/algorithms/CreateCacheFilename.py
PythonInterface/plugins/algorithms/CreateEmptyTableWorkspace.py
PythonInterface/plugins/algorithms/CreateLeBailFitInput.py
PythonInterface/plugins/algorithms/CylinderPaalmanPingsCorrection2.py
PythonInterface/plugins/algorithms/LoadFullprofFile.py

**Group 2**
PythonInterface/plugins/algorithms/DakotaChiSquared.py
PythonInterface/plugins/algorithms/DNSComputeDetEffCorrCoefs.py
PythonInterface/plugins/algorithms/DNSFlippingRatioCorr.py
PythonInterface/plugins/algorithms/DNSMergeRuns.py
PythonInterface/plugins/algorithms/DPDFreduction.py
PythonInterface/plugins/algorithms/DSFinterp.py
PythonInterface/plugins/algorithms/EnggCalibrateFull.py
PythonInterface/plugins/algorithms/EnggCalibrate.py
PythonInterface/plugins/algorithms/EnggFitDIFCFromPeaks.py
PythonInterface/plugins/algorithms/EnggFitPeaks.py
PythonInterface/plugins/algorithms/EnggFocus.py
PythonInterface/plugins/algorithms/EnggVanadiumCorrections.py
PythonInterface/plugins/algorithms/ExaminePowderDiffProfile.py
PythonInterface/plugins/algorithms/Examples/ExampleSaveAscii.py
PythonInterface/plugins/algorithms/Examples/Squares.py
PythonInterface/plugins/algorithms/ExportExperimentLog.py
PythonInterface/plugins/algorithms/ExportGeometry.py
PythonInterface/plugins/algorithms/ExportSampleLogsToCSVFile.py
PythonInterface/plugins/algorithms/FilterLogByTime.py
PythonInterface/plugins/algorithms/FindEPP.py

**Group 3**
PythonInterface/plugins/algorithms/FindReflectometryLines.py
PythonInterface/plugins/algorithms/FitGaussian.py
PythonInterface/plugins/algorithms/GenerateGroupingSNSInelastic.py
PythonInterface/plugins/algorithms/GetEiMonDet.py
PythonInterface/plugins/algorithms/GetEiT0atSNS.py
PythonInterface/plugins/algorithms/GetIPTS.py
PythonInterface/plugins/algorithms/GetNegMuMuonicXRD.py
PythonInterface/plugins/algorithms/GSASIIRefineFitPeaks.py
PythonInterface/plugins/algorithms/IndirectTransmission.py
PythonInterface/plugins/algorithms/LiquidsReflectometryReduction.py
PythonInterface/plugins/algorithms/LoadCIF.py
PythonInterface/plugins/algorithms/LoadDNSLegacy.py
PythonInterface/plugins/algorithms/dnsdata.py
PythonInterface/plugins/algorithms/LoadEmptyVesuvio.py
PythonInterface/plugins/algorithms/LoadLogPropertyTable.py
PythonInterface/plugins/algorithms/LoadMultipleGSS.py
PythonInterface/plugins/algorithms/LoadNMoldyn3Ascii.py
PythonInterface/plugins/algorithms/LoadNMoldyn4Ascii.py
PythonInterface/plugins/algorithms/LoadSINQFile.py
PythonInterface/plugins/algorithms/LoadSINQ.py
PythonInterface/plugins/algorithms/LoadVesuvio.py

**Group 4**
PythonInterface/plugins/algorithms/LoadVisionElasticBS.py
PythonInterface/plugins/algorithms/LoadVisionElasticEQ.py
PythonInterface/plugins/algorithms/LoadVisionInelastic.py
PythonInterface/plugins/algorithms/LRAutoReduction.py
PythonInterface/plugins/algorithms/LRDirectBeamSort.py
PythonInterface/plugins/algorithms/LRPeakSelection.py
PythonInterface/plugins/algorithms/LRPrimaryFraction.py
PythonInterface/plugins/algorithms/LRReflectivityOutput.py
PythonInterface/plugins/algorithms/LRScalingFactors.py
PythonInterface/plugins/algorithms/LRSubtractAverageBackground.py
PythonInterface/plugins/algorithms/MaskAngle.py
PythonInterface/plugins/algorithms/MaskBTP.py
PythonInterface/plugins/algorithms/MaskWorkspaceToCalFile.py
PythonInterface/plugins/algorithms/Mean.py
PythonInterface/plugins/algorithms/MergeCalFiles.py
PythonInterface/plugins/algorithms/MSDFit.py
PythonInterface/plugins/algorithms/MuscatSofQW.py
PythonInterface/plugins/algorithms/NormaliseSpectra.py
PythonInterface/plugins/algorithms/PDToGUDRUN.py
PythonInterface/plugins/algorithms/PDToPDFgetN.py
PythonInterface/plugins/algorithms/PearlMCAbsorption.py

**Group 5**
PythonInterface/plugins/algorithms/PoldiCreatePeaksFromFile.py
PythonInterface/plugins/algorithms/PoldiLoadRuns.py
PythonInterface/plugins/algorithms/PoldiMerge.py
PythonInterface/plugins/algorithms/RefinePowderDiffProfileSeq.py
PythonInterface/plugins/algorithms/RefLReduction.py
PythonInterface/plugins/algorithms/ResNorm.py
PythonInterface/plugins/algorithms/RetrieveRunInfo.py
PythonInterface/plugins/algorithms/SANSSubtract.py
PythonInterface/plugins/algorithms/SANSWideAngleCorrection.py
PythonInterface/plugins/algorithms/SaveNexusPD.py
PythonInterface/plugins/algorithms/SavePlot1DAsJson.py
PythonInterface/plugins/algorithms/SaveVulcanGSS.py
PythonInterface/plugins/algorithms/SelectPowderDiffPeaks.py
PythonInterface/plugins/algorithms/sfCalculator.py
PythonInterface/plugins/algorithms/SNSPowderReduction.py
PythonInterface/plugins/algorithms/SortByQVectors.py
PythonInterface/plugins/algorithms/SortDetectors.py
PythonInterface/plugins/algorithms/SortXAxis.py
PythonInterface/plugins/algorithms/StatisticsOfTableWorkspace.py
PythonInterface/plugins/algorithms/StringToPng.py
PythonInterface/plugins/algorithms/SuggestTibCNCS.py

**Group 6**
PythonInterface/plugins/algorithms/SuggestTibHYSPEC.py
PythonInterface/plugins/algorithms/Symmetrise.py
PythonInterface/plugins/algorithms/TestWorkspaceGroupProperty.py
PythonInterface/plugins/algorithms/TOFTOFConvertTofToDeltaE.py
PythonInterface/plugins/algorithms/TOFTOFCropWorkspace.py
PythonInterface/plugins/algorithms/TOFTOFMergeRuns.py
PythonInterface/plugins/algorithms/UpdatePeakParameterTableValue.py
PythonInterface/plugins/algorithms/USANSSimulation.py
PythonInterface/plugins/algorithms/VesuvioCorrections.py
PythonInterface/plugins/algorithms/VesuvioPreFit.py
PythonInterface/plugins/algorithms/VesuvioResolution.py
PythonInterface/plugins/algorithms/VesuvioThickness.py
PythonInterface/plugins/algorithms/VesuvioTOFFit.py
PythonInterface/plugins/algorithms/ViewBOA.py
PythonInterface/plugins/algorithms/VisionLoadDetectorTable.py
PythonInterface/plugins/algorithms/VisionReduction.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/AddSampleLogMultiple.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/ApplyPaalmanPingsCorrection.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/BayesQuasi.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/DetectorFloodWeighting.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/ElasticWindowMultiple.py

**Group 7**
PythonInterface/plugins/algorithms/WorkflowAlgorithms/EQSANSAzimuthalAverage1D.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/EQSANSDirectBeamTransmission.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/EQSANSNormalise.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/FlatPlatePaalmanPingsCorrection.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/HFIRSANSReduction.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/ILLIN16BCalibration.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectAnnulusAbsorption.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectCalibration.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectCylinderAbsorption.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectFlatPlateAbsorption.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectILLReduction.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectResolution.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectTransmissionMonitor.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/IqtFitMultiple.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/IqtFitSequential.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/ISISIndirectDiffractionReduction.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/ISISIndirectEnergyTransfer.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/MolDyn.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/MuscatData.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/MuscatFunc.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/NormaliseByThickness.py

**Group 8**
PythonInterface/plugins/algorithms/WorkflowAlgorithms/OSIRISDiffractionReduction.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/PoldiDataAnalysis.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/Quest.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/ReactorSANSResolution.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/REFLReprocess.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/ResNorm2.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSAbsoluteScale.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSAzimuthalAverage1D.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSBeamSpreaderTransmission.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSDarkRunBackgroundCorrection.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSDirectBeamTransmission.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSFitShiftScale.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSMask.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSReduction.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSStitch.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SavePlot1D.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SimulatedDensityOfStates.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SofQWMoments.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SwapWidths.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/TimeSlice.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/TOSCABankCorrection.py

**Group 9**
PythonInterface/plugins/algorithms/WorkflowAlgorithms/TransformToIqt.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/TransmissionUtils.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/USANSReduction.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/VesuvioDiffractionReduction.py
PythonInterface/plugins/functions/ChudleyElliot.py
PythonInterface/plugins/functions/DSFinterp1DFit.py
PythonInterface/plugins/functions/Examples/Example1DFunction.py
PythonInterface/plugins/functions/Examples/ExamplePeakFunction.py
PythonInterface/plugins/functions/FickDiffusion.py
PythonInterface/plugins/functions/GuinierPorod.py
PythonInterface/plugins/functions/Guinier.py
PythonInterface/plugins/functions/HallRoss.py
PythonInterface/plugins/functions/Lorentz.py
PythonInterface/plugins/functions/Porod.py
PythonInterface/plugins/functions/StretchedExpFT.py
PythonInterface/plugins/functions/TeixeiraWater.py

### PR DESCRIPTION
**Pull request by rosswhitfield**
This is Group 10 of #16739 and with this I think we should close #16739 

**To test:**
- Code review
- Compile with python3 and check that the related unit tests pass 

After this we still have some sporadically failing unit tests with python 3. With this PR you should find all `PythonAlgorithms` test passing with the occasional exception of the following.

```
    514 - PythonAlgorithms_EnggCalibrateFullTest (Failed)
    576 - PythonAlgorithms_StatisticsOfTableWorkspaceTest (Failed)
    598 - PythonAlgorithms_VesuvioResolutionTest (Failed)
    600 - PythonAlgorithms_VesuvioTOFFitTest (Failed)
```

I created an issues for these #17876

Does not need to be in the release notes.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by rosswhitfield** [comment]
@martyngigg @peterfpeterson

**Comment by rosswhitfield** [comment]
I just got ExportExperimentLog to work with python 3. It's a hack but the entire `_orderRecordFile` is terrible and should probability be rewritten without using dictionary's at all.

**Comment by rosswhitfield** [comment]
I believe the last four tests are failing for the same reason, the properties are getting mixed up, something to do with the way `simpleapi.py` is handling the `*args, **kwargs` in `set_properties`, and maybe to do with `mandatoryProperties`. I can't figure it out.

They can sometimes take a bit of encouragement to fail, but you can almost guarantee it with:
```
ctest -j4 --output-on-failure --repeat-until-fail 100 -R 'EnggCalibrateFullTest|StatisticsOfTableWorkspaceTest|PythonAlgorithms_VesuvioResolutionTest|VesuvioTOFFitTest'
```
Then you get messages like
```RuntimeError: WorkspaceProperty doesn't point to a workspace```

```
VesuvioResolution-[Error] Error in execution of algorithm VesuvioResolution:
VesuvioResolution-[Error] Unknown property search object WorkspaceIndex
VesuvioResolution-[Error]   at line 82 in '/home/rwp/mantid/Framework/PythonInterface/plugins/algorithms/VesuvioResolution.py'
VesuvioResolution-[Error]   caused by line 119 in '/home/rwp/mantid/Framework/PythonInterface/plugins/algorithms/VesuvioResolution.py'
VesuvioResolution-[Error]   caused by line 810 in '/home/rwp/mantid/Release/py3/bin/mantid/simpleapi.py'
VesuvioResolution-[Error]   caused by line 829 in '/home/rwp/mantid/Release/py3/bin/mantid/simpleapi.py'
```

```
VesuvioTOFFit-[Error] Unknown property search object WorkspaceIndex
VesuvioTOFFit-[Error]   at line 75 in '/home/rwp/mantid/Framework/PythonInterface/plugins/algorithms/VesuvioTOFFit.py'
VesuvioTOFFit-[Error]   caused by line 89 in '/home/rwp/mantid/Framework/PythonInterface/plugins/algorithms/VesuvioTOFFit.py'
VesuvioTOFFit-[Error]   caused by line 102 in '/home/rwp/mantid/Framework/PythonInterface/plugins/algorithms/VesuvioTOFFit.py'
VesuvioTOFFit-[Error]   caused by line 126 in '/home/rwp/mantid/Framework/PythonInterface/plugins/algorithms/VesuvioTOFFit.py'
VesuvioTOFFit-[Error]   caused by line 163 in '/home/rwp/mantid/Framework/PythonInterface/plugins/algorithms/VesuvioTOFFit.py'
VesuvioTOFFit-[Error]   caused by line 25 in '/home/rwp/mantid/scripts/Inelastic/vesuvio/base.py'
```

```
Traceback (most recent call last):
  File "/home/rwp/mantid/Framework/PythonInterface/test/python/plugins/algorithms/EnggCalibrateFullTest.py", line 61, in test_issues_with_properties
    Bank='2')
  File "/usr/lib/python3.5/unittest/case.py", line 727, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib/python3.5/unittest/case.py", line 176, in handle
    callable_obj(*args, **kwargs)
  File "/home/rwp/mantid/Release/py3/bin/mantid/simpleapi.py", line 876, in algorithm_wrapper
    set_properties(algm, *args, **final_keywords)
  File "/home/rwp/mantid/Release/py3/bin/mantid/simpleapi.py", line 810, in set_properties
    _set_alg_properties(arguments=kwargs, algorithm=alg_object)
  File "/home/rwp/mantid/Release/py3/bin/mantid/simpleapi.py", line 829, in _set_alg_properties
    algorithm.setProperty(key, value)
TypeError: No registered converter was able to produce a C++ rvalue of type std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > from this Python object of type list
```

@martyngigg any chance you can take a look?

**Comment by martyngigg** [comment]
@rosswhitfield Will do. It may be a couple of days before I have some time though.

**Comment by rosswhitfield** [comment]
I will create an issue for you and move my comment above to it.

**Comment by peterfpeterson** [comment]
All tests that should work with `ctest -R PythonAlg` do (ignoring sporadic failures) under python3.

:shipit:

**Pull request merged**
