### PR TITLE
Better increment filling in DrILL

### PR DESCRIPTION
**Pull request by gui-co**
**Description of work.**

This PR improves the automatic increment fill function in DrILL. The purpose of that function was to reduce manual filling of the table. It was already present in the previous version of DrILL, this is only an amelioration. It was designed first to handle experiment numbers, this PR adds the support for text.

The increment fill is used through the tool bar menu of the DrILL interface: a spin box is used to set the increment value and a tool button activate the automatic filling on the selected cells. The filling is made along columns or row (only if a single row is selected). If the increment value is 0 or if the cell value can not be incremented, the filling acts as a copy paste. Since DrILL's underlying algorithms often accept comma separated values for some parameters, the increment filling will work on these types of values as well.

**To test:**

* open the DrILL interface
* add some rows
* fill the first row with different values
* select some columns and use the increment fill function from the tool bar

Here are some examples of what you can obtain with a increment value of 2:

| 1 | 10,100,1000 | sample1,sample10 | sample |
|--|--|--|--|
| 3 | 12,102,1002 | sample3,sample12 | sample |
| 5 | 14,104,1004 | sample5,sample14 | sample |
| 7 | 16,106,1006 | sample7,sample16 | sample |

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by darominski — COMMENTED** [review]
The increment examples work as promised with different increment steps for both column and row incrementation. 
There are two issues I spotted, however they are probably going beyond the usual workflow:
1. When using negative increment, everything works as expected until the 0 is reached, and beyond that point the behaviour is less so: the minus sign is appended to the string and the remainder is treated as a positive number and the increment is subtracted from it for the next cell. E.g. if the number is 1 and the increment is -9, the next cell will be -8, and the following --1. Perhaps the decrementation should stop just before the numbers cross zero?
2. Incrementing ranges containing strings, e.g. sample_1:sample_10 (and other combinations of string+number) does not increment the number. Is this case not foreseen in the workflow?

**Comment by gui-co** [comment]
The issue with negative increment is solved:
* `<number>`: values are decremented beyond 0.
* `<str+number>`: the number is decremented until 0 and then 0 is propagated.

With a increment value of -1:

| 2 | sample2 |
|---|-------------|
| 1 | sample1|
| 0 | sample0|
| -1 | sample0|
| -2 | sample0|

For the ranges `<str+number>:<str+number>`. There is not real use case, the current behavior is fine.

**Review by darominski — COMMENTED** [review]
Apologies for the review delay and thanks for implementing the comments. Understood about the lack of use case for `<str+number>:<str+number> `. 
The change works as promised for single numbers and `<str+number>` combinations. I am a little surprised though by the change in behaviour of ranges incrementation. Namely, everything is as expected when one increments the ranges from, e.g. 10:15, going by +2: the next range is going to be 17:22. When this increment is changed to -2, one does not get a decrementation in ranges (3:8), but rather incrementing ranges with overlap (13:18). This may be as well the expected use-case for incrementing ranges using negative increments, so I am not requesting a change here, but please do let me know if that is intended behaviour.

**Comment by gui-co** [comment]
I made the correction. I do not know if there is really a use case for the negative increment of ranges but, you're right, the behavior should be coherent with the positive increment.
There was also a problem with 0 increment of range which should behave well now.

This is the current behavior with a increment of -1:
|100:101|100:101:2|
|--|--|
|98:99|98:99:2|
|96:97|96:97:2|
|94:95|94:95:2|

**Review by darominski — APPROVED** [review]
Thanks for the change. I am not certain what would be the use case for that (angular range scan perhaps?). Nonetheless, all seems to work well now.

**Pull request merged**
