### PR TITLE
Disable fit button for tiled plots

### LINKED ISSUE #26768: Remove the fit button from the plot toolbar when more than one curve is plotted
Fitting isn't possible when multiple curves are plotted so the fit button should only be shown when the figure has one curve. Make sure that the button is added if all but one curve is removed via the figure options.

### PR DESCRIPTION
**Pull request by alicerussell1**
**Description of work.**
This PR disables the fit button for tiled plots in workbench as the fit property browser does not know how to handle them.

**To test:**
Load a workspace with more than one spectra
Plot a few spectra as a tiled plot
Press the fit button
The fit property browser should not appear and a message should be given

Fixes #26768 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by RichardWaiteSTFC — DISMISSED** [review]
Passes the test, producing a warning "Cannot fit tiled plots",  but if the log-level is set to Error, obviously no message appears (presumably this is a deliberate choice?).

**Comment by DanNixon** [comment]
Would it be much more effort to actually disable the button so that it couldn't be clicked? If so it may be worth emitting the message at error level to guarantee it is seen.

**Review by martyngigg — CHANGES_REQUESTED** [review]
As Dan says, can we update the check in [figuremanager](https://github.com/mantidproject/mantid/blob/master/qt/applications/workbench/workbench/plotting/figuremanager.py#L281) to keep it all in one place?

**Comment by alicerussell1** [comment]
Ah yes, I hadn't seen it was done there, I've changed it.

**Review by martyngigg — APPROVED** [review]
Thanks for moving that check.

This still works as expected. :+1:

**Review by RichardWaiteSTFC — APPROVED** [review]
The fit button is now absent/greyed-out in workbench/mantidplot for tiled plots as required.

**Pull request merged**
