### PR TITLE
Changes to SliceViewer view to enable Cursor widget to size properly

### LINKED ISSUE #31214: Sliceviewer Cursor widget not properly sized for MD workspaces
**Original reporter:** [On the forum](https://forum.mantidproject.org/t/mantid-sliceviewer-cursor-position-unreadable/729)

### Expected behavior
The widget has enough space to display the x,y and signal values. On _my_ Windows machine, this works well.
image

### Actual behavior
On _my_ Ubuntu and MacOS machines I found the problem and as you can see the values aren't visibnle as the widget isn't correctly sized. The user found this problem on Windows, so this isn't OS specific, but should be tested on all OS!
Screenshot 2021-04-26 at 15 06 56
Screenshot 2021-04-26 at 15 07 16

### Steps to reproduce the behavior
Run this script to create an MD workspace:
```
ws=CreateMDHistoWorkspace(Dimensionality=2,Extents='-3,3,-10,10', \
SignalInput=range(0,100),ErrorInput=range(0,100),\
NumberOfBins='10,10',Names='Dim1,Dim2',Units='MomentumTransfer,EnergyTransfer')
```
Right-click on the workspace and show sliceviewer. Check if the widget is sized correctly when you hover the cursor over the image.
### Platforms affected
All

Note to developers: Worth investigating how drastic the fix for this widget would be and deciding whether it is worth including in release 6.1 or not.

### PR DESCRIPTION
**Pull request by sf1919**
**Description of work.**
Removal of special view for MD workspaces and resizing of colorbar column so that SliceViewer can be used on different operating systems, regardless of display setup.

**To test:**
Test 1 (2D workspace)
Run this script to create an 2D MD workspace
```
ws=CreateMDHistoWorkspace(Dimensionality=2,Extents='-3,3,-10,10', \
SignalInput=range(0,100),ErrorInput=range(0,100),\
NumberOfBins='10,10',Names='Dim1,Dim2',Units='MomentumTransfer,EnergyTransfer') 
```
Right-click on the workspace and show sliceviewer. Check if the cursor widget (x, y, signal table on right hand side) is sized correctly when you hover the cursor over the image.

Test 2 (4D workspace)
Run this script to create an 4D MD workspace
```
mdWS = CreateMDWorkspace(Dimensions=4, Extents=[-1,1,-1,1,-1,1,-10,10], Names="H,K,L,E", Units="U,U,U,V")
```
Right-click on the workspace and show sliceviewer. Check if the cursor widget (x, y, signal table on right hand side) is sized correctly when you hover the cursor over the image. Also check that the automatic resizing of the cursor widget does not make the slider widgets too small.

Test 3 (Overlaying peaks)
1) Run this script
```
# SXD23767.raw is available in the TrainingCourseData from the downloads page
SXD23767 = Load(Filename='SXD23767.raw', LoadMonitors='Exclude')
# Set some UB with angles we can play with
SetUB(SXD23767, 1,1,2,90,90,120)
md_non_ortho = ConvertToDiffractionMDWorkspace(InputWorkspace='SXD23767', OutputDimensions='HKL')
```

2) Create a Peaks workspace by doing the following

- Open instrument viewer by right-clicking on the workspace``SXD23767``.
- On the Pick tab, select the PickTabAddPeakButton.png “Add a single crystal peak” button.
- Click on an intense bragg peak on the detectors, and then click on one or many of the intense peaks in the produced mini-plot.
- Repeat for a few different bragg peaks across the detectors.
- Notice that this has produced a SingleCrystalPeakTable.
- Rename the above workspace to peaks and in instrument viewer, select more peaks for a second peaksworkspace.

3) Create an integrated peaks workspace using the following script
```
peaks = mtd['peaks']
integrated_peaks = IntegratePeaksMD(InputWorkspace='md_non_ortho', PeaksWorkspace='peaks',\
     PeakRadius=0.12, BackgroundOuterRadius=0.2, BackgroundInnerRadius=0.16)
```

4) Right click on the md_non_ortho workspace and show sliceviewer. 
5) Click on the 'Add peaks overlay' button and select one or more peak workspaces to open
6) This will open one or more peak overlay tables to the right of the screen. Resize these and check that it does not obscure the cursor widget box (x, y, signal table on right hand side).

This needs to be tested on
- ~~Windows~~ (~~2k~~✔ and ~~4K~~ ✔ displays)
- ~~Mac~~ ✔
- ~~Ubuntu~~ ✔
- CentOS Linux
- Redhat Enterprise Linux

Please specify with OS and display settings used when testing.

Fixes #31214
Also fixes some of the view issues reported in #31276

*This does not require release notes* because it fixes a display issue.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DanielMurphy22** [comment]
The cursor widget is much improved now, especially for MD data! Well done! tested on MacOS and Ubuntu.

**Comment by AnthonyLim23** [comment]
Tested using Windows 10 with a 4K screen. Looks good except for the peak overlay, the tables that have been added are very narrow

image

**Comment by RichardWaiteSTFC** [comment]
> Tested using Windows 10 with a 4K screen. Looks good except for the peak overlay, the tables that have been added are very narrow

That's unfortunately always the case - even prior to this change and even on non 4K screen (although the text is bigger you still only see one column)

**Comment by AnthonyLim23** [comment]
> > Tested using Windows 10 with a 4K screen. Looks good except for the peak overlay, the tables that have been added are very narrow
> 
> That's unfortunately always the case - even prior to this change and even on non 4K screen (although the text is bigger you still only see one column)
Can we have an issue to make it a bit easier to read? Have 2 columns show at a time?

**Comment by RichardWaiteSTFC** [comment]
> > > Tested using Windows 10 with a 4K screen. Looks good except for the peak overlay, the tables that have been added are very narrow
> > 
> > 
> > That's unfortunately always the case - even prior to this change and even on non 4K screen (although the text is bigger you still only see one column)

> Can we have an issue to make it a bit easier to read? Have 2 columns show at a time?

Agreed, I raised a related thing in my manual testing though I haven't created an issue yet. The table isn't' very well laid out, although we could make it a bit wider there isn't really any point atm as you're not able to make it wide enough to see the columns that actually matter (Run, H, K, L, Intens, Sig, Intens/Sig) because they are not adjacent, (the HKL are separated by ~5 columns from the Intens etc.). So a higher priority is to re-order the columns in the view and at then in the same PR we can make it wider.

**Comment by RichardWaiteSTFC** [comment]
Just tested this on windows 10 - no 4K screen. Code looks good and this is a nice solution (alwyas good to keep things consistent where possible between md and none md workspaces as well). One small thing is that as you move the cursor to a negative position in one dimension (i.e. add another character `-` to one cell in the table) or to a bin with a different order of magnitude signal the widget width changes rapidly which causes the rest of the dimension widget to flicker (you might not get this problem in 4K as all the text looks smaller). I wonder if it's possible to have constant width of string in the cell (i.e. pad positive numbers with a leading space?) or something like this - though I'm not sure what we would do about the signal. Or maybe an invisible widget that adds a bit of padding between the dimension widget and ImageInfoWidget that would change size instead?

**Comment by AnthonyLim23** [comment]
a constant width can often be tricky to read (e.g. 00000043.273), this might annoy users. I think the flickering is unlikely enough that it might be worth calling it an issue for another day

**Comment by RichardWaiteSTFC** [comment]
> a constant width can often be tricky to read (e.g. 00000043.273), this might annoy users. I think the flickering is unlikely enough that it might be worth calling it an issue for another day

Yeh I was only suggesting padding with spaces rather than 0s  for that reason - though that may be difficult. I agree though, the flickering is a minor point and it shouldn't hold up this fix that allows the user can see the whole table. I'm happy to approve.

**Comment by sf1919** [comment]
We still need to get this tested on Linux - @RichardWaiteSTFC @DanielMurphy22 @AnthonyLim23 any suggestions who I could ask?

**Comment by RichardWaiteSTFC** [comment]
> We still need to get this tested on Linux - @RichardWaiteSTFC @DanielMurphy22 @AnthonyLim23 any suggestions who I could ask?

@DannyHindson do you have CentOS? It would be good to test this on something as close to IDAaaS as possible

**Comment by AnthonyLim23** [comment]
It would be annoying but we could make an installer and then download it in IDAaas for testing

**Comment by AnthonyLim23** [comment]
whats the difference between the top and bottom picture?

**Comment by RichardWaiteSTFC** [comment]
> This is really good as it seems like the cursor widgte doesn't compete with the sliders for space anymore. On IDAaaS (and even Ubuntu actually) the cursor widget still competes with the peak tables, when you first open sliceviewer and then overlay peaks. It is possible to expand sliceviewer and reduce the space for the peaks to stop the cursor widget and peak tables competing.
> 
> How important do people think this is?? @sf1919 @RichardWaiteSTFC @AnthonyLim23

I think it's possible to be in this situation on windows as well - I suppose optimally the dimension widget would shrink so that the horizontal scroll-bar (which is what you mean by competing for space?) would never be necessary. That said, I don't think it's hugely important, I don't know how much the cursor info is used in practice and when it is, it's likely to be the x/y coord that are more important than the signal, and they seem to be pretty visible for all reasonable window sizes at least on windows 10 non-4K. What does everyone else think?

**Review by DanielMurphy22 — APPROVED** [review]
I think this solves the original issue and any competing for space with the peaks table should be sorted with more major peaks table changes in the future. Well done!! @sf1919 I'll leave it to you to decide if it is worth closing #31276 now!

**Comment by sf1919** [comment]
> 
> 
> > This is really good as it seems like the cursor widgte doesn't compete with the sliders for space anymore. On IDAaaS (and even Ubuntu actually) the cursor widget still competes with the peak tables, when you first open sliceviewer and then overlay peaks. It is possible to expand sliceviewer and reduce the space for the peaks to stop the cursor widget and peak tables competing.
> > How important do people think this is?? @sf1919 @RichardWaiteSTFC @AnthonyLim23
> 
> I think it's possible to be in this situation on windows as well - I suppose optimally the dimension widget would shrink so that the horizontal scroll-bar (which is what you mean by competing for space?) would never be necessary. That said, I don't think it's hugely important, I don't know how much the cursor info is used in practice (the only use case I can think of is looking for an approx. modulation vector in an HKL MD workspace). It's likely to be the x/y coord that are more important than the signal, and they seem to be pretty visible for all reasonable window sizes at least on windows 10 non-4K. What does everyone else think?

I think there is a separate issue here about how much we're trying to cram into one GUI. It's making it harder to use and harder to make it work sensibly on the multiude of different operating systems and display options that we're encountering. That is a much bigger project and arguably needs to be tackled in a sprint rather than as a bug fix prior to release.

If the x & y are more important than the Signal and with a bit of manual resizing you can see them all anyway then I think perhaps we've solved the issue as far as we can in terms of a bug fix.

**Comment by DavidFair** [comment]
> I think there is a separate issue here about how much we're trying to cram into one GUI. It's making it harder to use and harder to make it work sensibly on the multiude of different operating systems and display options that we're encountering. That is a much bigger project and arguably needs to be tackled in a sprint rather than as a bug fix prior to release.

*Some off topic from PR notes*

Just my 2 cents. I agree completely, users won't directly ask for UX improvements but it will add to their frustration using it if they aren't fixed. So whilst you may not have scientists clamouring for it (as Stockholm syndrome can be powerful) your user base is suffering from the stereotypical scientific software look.

I've put together a mock in GIMP whilst the docs where building showing how a bit of tidying will help. For reference the grey over the display would be an arrow the completely collapses everything on the right, allowing sliceviewer to completely fill the screen

**Review by DavidFair — APPROVED** [review]

**Pull request merged**
