### PR TITLE
Add Mass as a parameter rather than attribute

### LINKED ISSUE #15669: Make mass a fitted parameter in Compton fit functions
This is required for incorporation of Bayesian analysis.

All current uses should replace use of the attribute with a fixed parameter.

### PR DESCRIPTION
**Pull request by DanNixon**
This moves the `Mass`attribute of the `ComptonProfile` fit function (which bases `GaussianComptonProfile` and `GramCharlierComptonProfile`) from being an attribute to a fitted parameter.

Existing usage is replaced with the parameter being tied.

**To test:**

Run a Vesuvio fitting script and see that the correct masses are used (log output from `VesuvioResolution` function is a good indicator).

Fixes #15669.

Does not need to be in the release notes.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@DanNixon This looks good. The only thing I'm concerned about at the moment is that now the Mass is going to come out in the `_Parameters` table and I don't know if that will cause confusion. Do you know if Matthew is expecting this? Should we manually remove it from the table in the `VesuvioTOFFit` algorithm?

**Comment by DanNixon** [comment]
@martyngigg Good point, I'll check with Matthew if he wants it removed from that table.
I hadn't given it much though as it would be appearing as a parameter elsewhere.

**Comment by DanNixon** [comment]
Matthew says it would be good to leave Mass in the parameter table.

**Comment by martyngigg** [comment]
Okay. I'll just do a few more checks but I think it's good to go.

**Comment by martyngigg** [comment]
Looks good. The reference files have not changed by a substantial enough amount to be worried about (although I'm not 100% sure why they change at all)

:shipit:

**Pull request merged**
