### PR TITLE
Add Python Profiling to Workbench

### PR DESCRIPTION
**Pull request by cailafinn**
**Description of work.**

Adds the option to run workbench with python's `cProfile` module.

**To test:**
1. Run workbench from the command line with a `--profile path/to/output.prof` parameter with a path to where you would like the output of the profiling to be placed. 
2. Install the `snakeviz` module from pip and run it with the output file, by doing something like ` python3 -m snakeviz ~/path/to/output/file.prof `
3. `snakeviz` should use the profile and open a browser window that allows the profile to be analysed in a graphical format. 
3. Check the state of the profile is reasonable.

Refs #28499 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Harrietbrown** [comment]
what sort of prof files are useable, are they generated normaly, and if so where are they located?

**Comment by ConorMFinn** [comment]
> what sort of prof files are useable, are they generated normaly, and if so where are they located?

Ah, should have been clearer in the instructions. The `.prof` files are just what is generated by the profiling. You supply the location of the file output.

**Comment by Harrietbrown** [comment]
ok, and how do I run snakeviz with it?

**Comment by ConorMFinn** [comment]
> ok, and how do I run snakeviz with it?

You run it as a python module supplying the path to it: ` python3 -m snakeviz ~/profile_output/proof.prof`

**Comment by Harrietbrown** [comment]
again, I'm not sure what output I am expecting, there is no output from running snakeviz.

**Comment by ConorMFinn** [comment]
> again, I'm not sure what output I am expecting, there is no output from running snakeviz.

`snakevis` should start a web service that allows you to browse the profile in a graphical format, is this not happening for you?

**Comment by Harrietbrown** [comment]
no, nothing is opened.

**Comment by Harrietbrown** [comment]
Why was a large block of code moved from `main.py` to `start.py`?

**Comment by ConorMFinn** [comment]
> Why was a large block of code moved from `main.py` to `start.py`?

This ensures that as few imports as possible are made before the profiling begins. So that as many lines as possible are covered.

**Review by Harrietbrown — APPROVED** [review]
The only change since the last approval was fixing merge conflicts.

**Review by martyngigg — COMMENTED** [review]
There's a small issue that it doesn't work from the Windows installer package. I think we can create a separate issue about this as none of the code here is actually incorrect it's just the windows launcher wrapper that is not passing the arguments through correctly.

**Pull request merged**
