### PR TITLE
Fix Flake8 warning associated with WorkflowAlgorithms

### PR DESCRIPTION
**Pull request by josephframsay**
**IN PROGRESS**

As part of #20508, four files from `WorkflowAlgorithms` have been refactored to reduce cyclomatic complexity

**To test:**
Make sure all unit and system tests pass, and code review. In addition, if this is your area, feel free to throw some data at me to test the affected scripts with, to make sure I haven't broken anything.

Note: it was deemed acceptable to just bury the warnings associated with SANS under the rug with a `noqa` flag, as these scripts are soon to be deprecated, and a lack of unit tests makes refactoring them needlessly risky

Address part of #20508 . 

**Release Notes** 
*Does not need to be in the release notes as the change is internal*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
Should a maintenance issue have milestone 3.11 after the code freeze for such?

**Comment by josephframsay** [comment]
Oh that's a good point - I'm not sure. It's maintenance for this release?

**Comment by KarlPalmen** [comment]
Maintenance is normally done early in a release cycle, because it could have effects that are not observed for some time.

**Comment by josephframsay** [comment]
Oh, I see. I picked this particular issue from the list of maintenance tasks - in that case, does that mean it's actually maintenance for next release?

**Comment by KarlPalmen** [comment]
I'd expect so.

**Comment by KarlPalmen** [comment]
Maintenance used to be done after the release work was completed, but is now done earlier to overlap with release work.

**Comment by josephframsay** [comment]
Wicked - thanks for clearing that up! I've changed the milestones accordingly

**Comment by josephframsay** [comment]
Closed, as all issues taken care of elsewhere

**Pull request closed without merging**
