### PR TITLE
Find latest TBB

### PR DESCRIPTION
**Pull request by OwenArnold**
Should fix broken conda builds

* version 2021 does not have "tbb/tbb_stddef.h" but now has a "tbb/version.h" with the same information. https://anaconda.org/conda-forge/tbb. The former file was expected in FindTBB.cmake
* https://software.intel.com/content/www/us/en/develop/articles/intel-oneapi-threading-building-blocks-release-notes.html `tbb_task_scheduler` is gone.

There are two alternative approaches I considered:
* `find_package(tbb CONFIG)`, I'm not sure how portable this is at present.
*  fix the recipe only (meta.yaml) set `tbb 2020.*` simpliest solution, but is just delaying and creating other problems

In order to test these changes, fetch `tbb` and `tbb-devel` (channel = conda-forge) from conda and build

### CODE REVIEW

**Comment by quantumsteve** [comment]
`TBBConfig.cmake` is available starting from TBB 2017 U7, which comes with Ubuntu 18.04+. We ship more recent versions of TBB on Windows and MacOS and are already backporting TBB on RHEL 7. Might be worth trying to backport a newer RPM (Fedora 26 is 2017_U7, RHEL 8 is 2018_U2) and see if we can remove FindTBB.cmake.

https://github.com/oneapi-src/oneTBB/tree/tbb_2020/cmake#binary-package-integration

**Comment by martyngigg** [comment]
I'll see if I can get a newer one built on copr

**Comment by OwenArnold** [comment]
> `TBBConfig.cmake` is available starting from TBB 2017 U7, which comes with Ubuntu 18.04+. We ship more recent versions of TBB on Windows and MacOS and are already backporting TBB on RHEL 7. Might be worth trying to backport a newer RPM (Fedora 26 is 2017_U7, RHEL 8 is 2018_U2) and see if we can remove FindTBB.cmake.
> 
> https://github.com/oneapi-src/oneTBB/tree/tbb_2020/cmake#binary-package-integration

That would be nice. That would allow us to do `find_package(tbb CONFIG)` as I describe above.

**Comment by martyngigg** [comment]
It looks like TBB 2017 U7 needs the compiler to understand `-std=c++14` flag and the stock RHEL7 compiler doesn't. I don't know if copr can make use of `scl` compilers/devtools packages? @quantumsteve @peterfpeterson Do you know?

**Comment by OwenArnold** [comment]
> It looks like TBB 2017 U7 needs the compiler to understand `-std=c++14` flag and the stock RHEL7 compiler doesn't. I don't know if copr can make use of `scl` compilers/devtools packages? @quantumsteve @peterfpeterson Do you know?

It might be easier to stick with `FindTBB.cmake` for now and dispose of it when the move to conda happens.

**Comment by peterfpeterson** [comment]
We've been `scl enable devtoolset-7` [for some time now](https://github.com/mantidproject/mantid/blob/master/buildconfig/Jenkins/buildscript#L67-L72). ubuntu has our oldest compiler.

**Comment by martyngigg** [comment]
> We've been `scl enable devtoolset-7` [for some time now](https://github.com/mantidproject/mantid/blob/master/buildconfig/Jenkins/buildscript#L67-L72). ubuntu has our oldest compiler.

Sorry I didn't mean for our developer setup I meant in the `copr` environments where we build the dependencies - they seem to use the stock compilers.

**Comment by martyngigg** [comment]
> > It looks like TBB 2017 U7 needs the compiler to understand `-std=c++14` flag and the stock RHEL7 compiler doesn't. I don't know if copr can make use of `scl` compilers/devtools packages? @quantumsteve @peterfpeterson Do you know?
> 
> It might be easier to stick with `FindTBB.cmake` for now and dispose of it when the move to conda happens.

Agreed.

**Comment by peterfpeterson** [comment]
I'm not sure how rpms deal with using software collections. That is something we'd need to research.

**Comment by quantumsteve** [comment]
@martyngigg Maybe try changing the standard to `c++1y` or `c++11`? TBB supports GCC 4.8 as recently as 2020, possibly later.

https://software.intel.com/sites/default/files/managed/86/bb/Release_Notes_2020.txt

**Comment by martyngigg** [comment]
> @martyngigg Maybe try changing the standard to `c++1y` or `c++11`? TBB supports GCC 4.8 as recently as 2020, possibly later.
> 
> https://software.intel.com/sites/default/files/managed/86/bb/Release_Notes_2020.txt

Thanks for the suggestion. As Owen as a solution that means no patching of tbb then I think we'll leave it to we move to conda to upgrade.

**Review by martyngigg — APPROVED** [review]
I can confirm this compiles inside a conda build on macOS with SDK v11.1.

**Pull request merged**
