### PR TITLE
Add system test for opening the algorithm dialogs

### LINKED ISSUE #34032: Create integration test that opens up algorithm dialog for all algorithms
During the 6.4 release sprintI fixed a bug where Mantid crashed while opening the dialog for the algorithm DiscusMultipleScatteringCorrection (https://github.com/mantidproject/mantid/pull/33973). This happened specifically when there was a group workspace in the ADS that got used as a default value for one the workspace properties. I think there have been other similar crashes fixed on an ad hoc basis eg https://github.com/mantidproject/mantid/pull/33800. ValidateInputs seems a bit of a weak spot because it can get called with workspace values that seemingly don't pass the validators that have been set up in Init().

Based on this it would be useful to have a system test\integration test that loops through all of the algorithms and opens up the dialog and checks it succeeds. The test would mimic what workbench does when opening up an algorithm dialog which is to call InterfaceManager::createDialogFromName. This gets called in qt/python/mantidqt/mantidqt/widgets/algorithmselector/widget.py in the function execute_algorithm. 

It would be nice if it were possible to open up each dialog multiple times where there's different workspaces present in the ADS:
- a matrix workspace
- a group workspace
- an MD workspace

...but don't know how long this kind of test will actually take so might need to find a balance between the run time and the fullness of the test

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR adds a system test that checks that all the different algorithm dialogs open ok with different workspaces in the ADS.

As mentioned in the issue, this test could take quite a long time if we are not careful. I have tried to reduce its run time in two ways:
    - The test will only open the most recent version of an algorithm (so 1000 algorithm dialogs are opened instead of 1300)
    - The tests for each workspace is in a different module to allow for the tests to be run concurrently

It would be good to hear from the reviewer if they think this second point is a good/bad idea. Not sure if its an ideal solution, so any other suggestions are welcome

Some algorithms have been excluded in the `self._exclude_algorithm` variables because they cause errors or crashes when opened. These algorithm dialogs will be fixed, and the variable removed, in a separate PR. See issue #34114

**To test:**
Check the test passes on each of the workspace type. (Re-run the test until you see that it has run on each of the workspace tests.

Fixes #34032 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DannyHindson — COMMENTED** [review]
Nice work on this. The test is nice and simple and runs in a reasonable time.

I had a go at reverting a change in a PR that fixed a crash on opening up an algorithm dialog (this  one https://github.com/mantidproject/mantid/pull/33973) and the test didn't pick it up

Having looked into this a bit it's because the "OutputWorkspace" property is blank on all the algorithms in this test so the algorithm's validateInputs method never gets called. When a user is working in the workbench UI the OutputWorkspace might not be blank if there are some previously used values in the workbench.ini file

Would it be possible to set up a value for OutputWorkspace on all the algorithms eg "testws" or similar? The call to createDialogName reads the history in from the .ini file in this function in AlgorithmDialog.cpp:
```
QString AlgorithmDialog::getPreviousValue(const QString &propName) const {
  QString value;

  if (!isForScript()) {
    value = m_propertyValueMap.value(propName);
    if (value.isEmpty())
      value = AlgorithmInputHistory::Instance().previousInput(m_algName, propName);
  } else if (getAlgorithmProperty(propName)) {
    value = m_propertyValueMap.value(propName);
  }

  return value;
}
```
Not sure if it's possible to fill up an AlgorithmHistory instance with fake\dummy stuff but would be a nice addition to this test if it were possible. As discussed there's also a presetValues parameter on createDialogFromName that perhaps achieves something similar

**Review by DannyHindson — CHANGES_REQUESTED** [review]
Looking good now. I reverted the fix I'd put in DiscusMultipleScatteringCorrection and the test now catches that. Just a few other things:

1) MaskBinsIf is failing on a MatrixWorkspace for me on my Windows conda build - in addition to the workspace group case you've already dealt with
2) it would be nice to write out a message listing the algorithms that are ignored
3) re the randomness on the ws type - it opens up the possibility of a PR going through and then the nightly builds might fail. So on that basis I wonder if it's better just to run the whole test set on each workspace type. The run time isn't huge on my laptop at the moment (maybe ~40 secs) so if it were three times this that would still be OK I think

**Comment by robertapplin** [comment]
Decided to add a system test for TableWorkspace in this PR because it was quick to do so

**Review by DannyHindson — APPROVED** [review]
Looks good, thanks for doing the changes

**Pull request merged**
