### PR TITLE
37376  texts on the mantid workbench main menu could not be seen on osx dark mode 

### LINKED ISSUE #37376: Texts on the Mantid Workbench Main Menu could not be seen on OSX Dark mode
**Describe the bug**
Texts on the Mantid main menu turns white and becomes invisible on OSX when the device display is in dark mode.

**To Reproduce**

For example
1. Change Mac OSX Display to Dark mode
2. Launch the mantid Workbench

**Expected behavior**
Texts should be visible on the main menu when device display is on dark mode.

**Screenshots**
Screenshot 2024-05-15 at 20 14 00

**Platform/Version:**
 - OS:  macOS
 - OS Version: 14.0
 - Mantid Version: 6.9.1

### PR DESCRIPTION
**Pull request by Despiix**
#### Summary of work
 The text on the mantid workbench main menu could not be seen on osx dark mode. The fix includes the QComboBoxes in the starting page.

 Make text visible on OSX Dark mode.

Fixes #37376. 

  **Report to:** @yusufjimoh, @jhaigh0

### To test:

1.  Run Mantid workbench using MacOS on Dark Mode, and make all text is visible. 
2. Check that the drop down boxes appear to have a white background and black text when viewed.
Preferably: Test on MacOs with Dark Mode off as well.

 Adding release notes after this PR

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by yusufjimoh** [comment]
Code looks good, and most items on the main menu can now be seen in dark mode, I noticed a few items that might require some adjustments:

The 'Tutorial' text between 'Sample Datasets' and 'Mantid Introduction'
The right arrow of the 'Default Facility' QComboBox
The right arrow of the 'ALF' QComboBox
I have attached images of both the light and dark mode for reference.

darkmode

Screenshot 2024-08-07 at 11 15 06

**Comment by sf1919** [comment]
All tests are passing now so @yusufjimoh can finish reviewing

**Comment by yusufjimoh** [comment]
All the text is now visible in dark mode, which is great, 
I’ve observed that the colors of the right arrows on both the QComboBoxes still remains white when Mantid is not in focus.

You can test this by clicking on an empty space outside of the Mantid window, ensuring Mantid isn’t selected.
From the recent changes in the file, it seems there were attempts to update the arrows to black, but they haven’t taken effect

Screenshot 2024-08-20 at 20 29 15

**Comment by jhaigh0** [comment]
I think that this is good to go in. The issue with the arrows is not mentioned in the original issue, nor is it particularly important. This affect very few people, the main problem is to make sure all the text is visible, which is now the case.

**Review by yusufjimoh — APPROVED** [review]
The QComboBoxes arrow color remains white when Mantid isn't in focus, though it displays correctly when it is. It's a minor detail and likely not noticeable. All texts is visible, code looks good, and release note is adequate, so I'm happy to approve the pull request.

**Pull request merged**
