### PR TITLE
Use Native Enums In ISIS SANS

### LINKED ISSUE #25358: SANS enums to use py3compat enum
ISIS SANS has implemented its own enums in `scripts/SANS/sans/common/enums.py` for instruments, detectors, facilities etc.

It should be investigated if python3 enums have all the functionality required by SANS and, if so, they should be used instead

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**
Converts all of the SANS scripts to use native Python enums, this:
- Improves readability / debugging 
- Removes custom enum handling we currently do
- ~~Improves performance~~ Only by 1%
- Clears some edge cases around the serializer

**Note to the reviewer(s):** The only significant code changes are in the commits which do not follow the "Convert x to Py Enum" pattern. All other commits are done with automatic tooling

**To test:**
- Run some data through the GUI and click the various tabs
- Check that tests build

Fixes #25358.

Does not require release notes as it's a long standing maintenance job

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by Matthew-Andrew — COMMENTED** [review]
On python3 GUI fails to open.

**Review by Matthew-Andrew — DISMISSED** [review]
This seems to work for me and code changes look good :+1:

**Comment by martyngigg** [comment]
@DavidFair The python 2 build on RHEL 7 does not seem to have the enum module. Is that something you are aware of?

**Comment by DavidFair** [comment]
Yes, I created the following issue and PR : #27541 to add the enum-34 to the builder dependencies to work-around this issue.

However, I think that I need to ask developers administrating RHEL-7 machines to update their machines to pull in the new dependency?

**Comment by martyngigg** [comment]
Ah I see. If there's a new spec file then we need to build it in [copr](https://copr.fedorainfracloud.org/coprs/mantid/mantid/) and then have it deployed to the machines. Unfortunately the RHEL ones are not managed by docker. I'll kick off the copr build now.

**Comment by DavidFair** [comment]
Thanks, interestingly the RHEL-7 build passed for this PR before the copr build has finished 🤔

**Comment by martyngigg** [comment]
Sorry I should have been clearer. The new `mantid-developer` is *not* deployed automatically. It just means that machine happens to have `python-enum34` installed for some reason.

**Comment by martyngigg** [comment]
Could you post a message to #jenkins asking for the RHEL builders to be updated? The RAL ones are done.

**Comment by martyngigg** [comment]
Just to double check. Has `python-enum34` been added to the user-dependency list for the shipped rpm?

**Comment by DavidFair** [comment]
No, where would I find the user-dependency list as I can only see the developer one?

**Comment by martyngigg** [comment]
It starts in the root [CMakeLists.txt](/mantidproject/mantid/blob/master/CMakeLists.txt#L383)

**Review by martyngigg — APPROVED** [review]

**Pull request merged**
