### PR TITLE
Abins algorithm: overhaul AbinsParameters

### PR DESCRIPTION
**Pull request by ajjackson**
~**Do not merge before #26635**~

**Description of work.**
NB this work is based on top of another pull request #26635 which should be considered for merging before this is reviewed. At that point this branch can be rebased to a more focused set of changes relative to Master. This PR has been opened slightly prematurely to check that the test data updates are behaving correctly.

The Abins python modules include an _AbinsParameters.py_ file which sets "advanced" options that are not exposed through the main Algorithm interface. Essentially it is a set of global variables for Abins modules, with the intent that users modify this source file to make advanced changes.

It is preferable for such variables to be manipulated directly through the Python API, as is done in the tests for this module. If there is user interest in accessing these variables they would ideally be exposed through Algorithms, but there is some value in using this structure while developing that interface. However, the caching infrastructure strongly assumes that these variables would be set by modifying the _AbinsParameters.py_ file; a hash of the file is attached to MD5 results caches, and if the hash changes then results must be re-calculated. There are several significant problems with this approach:
- unimportant changes to the file (e.g. comments, parallelism settings) will trigger a needless recalculation
- significant changes made to parameters through the Python API (e.g. `AbinsParams.fwhm = 5`) will _not_ trigger a re-calculation and the stale cache will be accepted as the file hash is unchanged
- any changes to the file in the code repository will require an update to numerous test data files
- information about _what_ has changed between the files is destroyed when working with hashes

AbinsParameters is here refactored to group related parameters into dictionaries; this should make it easier to explore and manipulate them with the Python API compared to module-level variables. The context provided by the groupings allows for slightly clearer naming which should also aid in using them without opening the .py file.

In the long run I can see some of these parameters being moved away from this file into function arguments or attached to relevant objects.

**To test:**

This should be covered adequately by the unit tests;
```
ctest -R Abins --output-on-failure
```
is a useful diagnostic tool.

**Release notes**
~This might need a release note as it involves an API change (within scripts/AbinsModules).~
Added under indirect/simulation "improvements".

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by ajjackson** [comment]
The broken tests for CASTEP, DMOL3 and GAUSSIAN are not a surprise: waiting to see if CRYSTAL test data was adapted correctly before rolling this out to the others.

**Comment by AnthonyLim23** [comment]
we have conflicts and does this have an issue?

**Comment by ajjackson** [comment]
I'll sort out the conflicts. There isn't a specific issue for AbinsParameters but it's in support of https://github.com/mantidproject/mantid/issues/26423 . I can open an Issue if that helps with book-keeping? The content would literally be the "description of work" above, though.

**Comment by ajjackson** [comment]
I think this is ready to go now. When/if it is accepted I will open an Issue and PR addressing file management for Abins data.

**Comment by ajjackson** [comment]
Merge conflict sorted!

**Comment by ajjackson** [comment]
I don't think those Ubuntu test failures are related to Abins

**Comment by ajjackson** [comment]
The Python3 test failure "KafkaHistoStreamDecoderTest" is a known unreliable test. The workbench/Jupyter console failure on Ubuntu+Doc is an odd one, the traceback doesn't really give anything useful?

**Review by alicerussell1 — APPROVED** [review]
This looks good to me, refactoring of AbinsParameters makes it much easier to use 👍

**Pull request merged**
