### PR TITLE
Ensure correct units of the workspace that is the output of DPDFReduction

### LINKED ISSUE #15588: Ensure correct units of the workspace that is the output of DPDFReduction
DPDFReduction outputs a MatrixWorkspace but its axes are not correctly labeled. `Axis(0)` is "MomentumTransfer" and `Axis(1)` is "DeltaE"

### PR DESCRIPTION
**Pull request by jmborr**
Description of work.

**To test:**

1.Download vanadium file [van56293.nxs](https://www.dropbox.com/s/tjkw8zwet3lvl8k/van56293.nxs?dl=0) and python script [reduction_test.py](https://www.dropbox.com/s/2wg3013a5nycyh0/reduction_test.py?dl=0).
2. Edit script to change the path of the directory where you saved the vanadium file.
3. Load and execute the python script in the python window of MantidPlot.
4. Verify the units of output workspace `slice_QE`.

Fixes #15588.

No release notes are necessary
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by jmborr** [comment]
@AndreiSavici :raising_hand:   Would you test this pull request for me, please? :

**Comment by AndreiSavici** [comment]
The code works as expected. No unit tests, but ,as stated in the help, this is an experimental algorithm. Same for documentation. Code could be cleaned a little bit more.

**Comment by AndreiSavici** [comment]
ignore the OSX build failure. MantidPlot timeout

**Comment by AndreiSavici** [comment]
:shipit:

**Comment by FedeMPouzols** [comment]
:+1:  For when this is developed further I'd strongly suggest splitting the current `pyExec()` into smaller steps/functions. At the moment is a bit too long.

**Pull request merged**
