### PR TITLE
Fix track calculation

### PR DESCRIPTION
**Pull request by peterfpeterson**
The existing code an an issue (highlighted in a code comment of `AbsorptionCorrection`) about it only "needing" the first `Link::distFromStart` rather than the values of `Link::distInsideObject()` for the whole `Track`. For hollow objects, like vanadium containers or chocolate bunnies, this is incorrect and under-reports the distance traveled in the sample. This PR adds a method `Track::distInsideObject()` which does the accumulation.

The change that affected more lines of code was changing `int Track::count()` to `size_t Track::size()` so the class would be more like a stl container.

**To test:**

This is mostly a code review, but you can calculate the absorption for a container and see that the results are "wacky."

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
Hi, if this wants to make this release then it will need to be ready for testing in the next day or so or we will have to push it out to the next release.

**Comment by DTasev** [comment]
The milestone seems to have been changed to 4.2 so I'll remove this from "Release 4.1" project

**Comment by NickDraper** [comment]
Last commit was in june and this is becoming a conflict magnet.

Is this a dead pr?  Removing the milestone for now, but should this be closed?

**Comment by martyngigg** [comment]
@peterfpeterson Can we close this as I think anything related to this will now need a fresh look?

**Comment by peterfpeterson** [comment]
Since there is a fresh investigation, this can be closed.

**Pull request closed without merging**
