### PR TITLE
BASIS definition broken/inefficient

### LINKED ISSUE #19258: BASIS definition broken/inefficient
This issue has been discovered after I added sanity checks for #19015

For the basis definition 20160 (8 banks x 2520) detectors have conflicting IDs. This means that only 4 banks for the BASIS definition are actually loaded out of the possible 8. 

This is at least a serious performance problem. Since the full Detector objects are still created an added to the instrument. That leaves **10080** effectively orphaned detectors attached to the instrument. The only looks normal because the duplicate ids to not get added to the detectorid list [see here](https://github.com/mantidproject/mantid/blob/master/Framework/Geometry/src/Instrument.cpp#L701-L704). It would be better IMHO if the BASIS definition only contained detectors that were actually supplied with a valid ID.

### PR DESCRIPTION
**Pull request by jmborr**
**To test:** Donwload [BSS_66008_sqw.nxs.zip](https://github.com/mantidproject/mantid/files/883445/BSS_66008_sqw.nxs.zip), unzip, and run the following script to verify reduction has not been broken
```
from collections import namedtuple
nt = namedtuple('nt', 'run refl eb mt, old')
i111 = nt(run='66008', refl='silicon111', eb=[-120,0.4,120], mt=[0.3, 0.2, 1.9],
old=LoadNexus(Filename="BSS_66008_sqw.nxs"))
i311 = nt(run='56740', refl='silicon311', eb=[-740, 1.6, 740], mt=[0.4, 0.2, 3.8],
old=LoadDaveGrp(Filename="BASIS_56748.dat", IsMicroEV=True, XAxisUnits="DeltaE"))

for i in (i111, i311):
   BASISReduction(RunNumbers=i.run, ReflectionType=i.refl, EnergyBins=i.eb, MomentumTransferBins=i.mt)
   ratio =
i111={'run': ', 'refl': 'silicon111', 'eb': [-120,0.4,120]
}
# Reduction with 111 analyzers
BASISReduction(RunNumbers="66008", ReflectionType="silicon111", EnergyBins=[-120,0.4,120], MomentumTransferBins=[0.3, 0.2, 1.9])
old = LoadNexus(Filename="BSS_66008_sqw.nxs")
ratio111 = (mtd["BSS_66008_sqw"]-old)/old
plotSpectrum(ratio111, range(ratio.getNumberHistograms()))
# Reduction with 311 analyzers
BASISReduction(RunNumbers="56740", ReflectionType="silicon311", EnergyBins=[-740, 1.6, 740], MomentumTransferBins=[0.4, 0.2, 3.8])
old = LoadDaveGrp(Filename="BASIS_56748.dat", IsMicroEV=True, XAxisUnits="DeltaE")
ratio311 = (mtd["BSS_56740_sqw"]-old)/old
plotSpectrum(ratio311, range(ratio311.getNumberHistograms()))
```
Values in `ratio` should not be bigger than ~10^(-5)

Fixes #19258.

[release notes](https://github.com/mantidproject/mantid/blob/8eb24e45eeb936b1c8b0955dfa9fc60e765542f6/docs/source/release/v3.10.0/indirect_inelastic.rst) updated.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by peterfpeterson** [comment]
Another improvement to the IDF is a change of
```xml
<idlist idname="bank1">
  <id val="5"/>
   ...
</idlist>
```
to
```xml
<idlist idname="bank1">
    <id start="5" end="3569"/>
</idlist>
```
This will make the file thousands of lines smaller and faster to parse.

**Comment by peterfpeterson** [comment]
You forgot to update `docs/source/release/v3.10.0/indirect_inelastic.rst` with a mention about the new IDF. I also like the fact that the IDF lost ~10k of code. Once the release notes are update I'll mark it to merge.

**Comment by jmborr** [comment]
@peterfpeterson Well, technically I did not forget since I was not planning on updating the notes  :bowtie:

**Comment by peterfpeterson** [comment]
LGTM :shipit:

**Review by peterfpeterson — APPROVED** [review]

**Pull request merged**
