### PR TITLE
FunctionBrowser crash editing Convolution

### LINKED ISSUE #26144: FunctionBrowser crash editing Convolution
### Steps to reproduce the bug

1. Open Multi-Dataset Interface
1. Add Convolution to FunctionBrowser
1. Add another Convolution.
1. Remove the last Convolution
2. Crash or Unhandled exception popup

### Platforms affected
All

### PR DESCRIPTION
**Pull request by mantid-roman**
**Description of work.**
Throw and catch exception to make sure the GUI is in a correct state.

**To test:**
1. Open Multi-Dataset Interface
1. Add Convolution to FunctionBrowser
1. Add another Convolution.
You should see a dialog with an error message. The second Convolution not added.

Fixes #26144

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by dtasev — CHANGES_REQUESTED** [review]
Adding Convolution, then trying to add another Convolution on it is now correctly prevented. 

However if I add Convolution, then add something else - e.g. Composite Function, and then add a Convolution to that, the `Nested convolutions are not allowed` exception is still thrown, but because it is not caught by anything the "Uncaught exception" MantidPlot dialog pops up.

This is how it looks:
image

Do you think it's possible to catch that exception for any add function, regardless of where it was thrown?

**Comment by mantid-roman** [comment]
I'll have a look. The problem is that that exception is thrown too late, after the browser has got itself into a wrong state.

**Review by dtasev — CHANGES_REQUESTED** [review]
This works better now, but is it possible not to clear all the functions when showing the error for the second Convolution in this flow: `Convolution > Composite Function > Convolution`? It would be better if only the last Convolution was removed, but I do not know if that is possible.

I also found that if I add Convolution > ExpDecay, then right click remove function, that removes everything. I don't think this should remove the top-level Convolution. Also trying to add a Convolution after everything has been removed shows the `Nested convolutions are not allowed` uncaught exception. Clicking continue and trying again works though

**Review by dtasev — APPROVED** [review]
Tried locally and the fore-found issues have been resolved

**Pull request merged**
