### PR TITLE
Indirect Improve Release Notes

### LINKED ISSUE #24922: Indirect Improve release notes
### Description
Read through the Indirect release notes and check for spelling and grammer. Also include links to algorithms etc. where necessary and just in general tidy them up.

### Platforms affected
All

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR improves the indirect release notes by adding several images.
This PR also fixes a bug on Sqw where you select the TOSCA instrument and click `Run`. This would cause an unexpected error as the TOSCA instrument doesn't have an EFixed.

**To test:**
Read through the documentation and check the new images.

1.`Interfaces`->`Indirect`->`Data Reduction`->`Sqw` tab
2. Select `TOSCA` as the instrument.
3. Load the file below.
4. Q-Low Q-Width Q-High: 0.5-0.05-1.8
5. Click `Run`. A meaningful error message should appear.

**Data Files**
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2977929/irs26176_graphite002_red.zip)

Fixes #24922 #24225 

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by robertapplin** [comment]
@SamJenkins1 Yes your right, thank you!

**Comment by NickDraper** [comment]
I can see a number of cpp changes that are not explained in the description of this PR.  What are they doing?

**Comment by robertapplin** [comment]
@NickDraper When clicking Run on the Sqw interface when the TOSCA instrument is selected there was an unexpected error because the TOSCA instrument does not have an EFixed. I could move these changes to a separate PR?

**Comment by NickDraper** [comment]
That's fine, just update the PR with details of the change and how to test it.

**Review by NickDraper — APPROVED** [review]
So this PR contains 2 peices of work, but as we are busy at the moment I'm not going to suggest they are split up.

I've reviewed each seperately.
1) the release notes are definately better,
2) the error message for TOSCA SQW works and does not appear for other intsruments.

**Pull request merged**
