### PR TITLE
Allow the option for Python interfaces to save the MantidPlot project

### LINKED ISSUE #23234: Project saving and python
To save python interfaces we need to add some code to the project saving to make it check the python interfaces.

As part of this we will also implement some basic save project. 

part of umbrella #19150

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Adds a mechanism for pure-Python interfaces to save to the MantidPlot project file.

Note that no interface is currently set up to save. This simply implements the hooks to allow this to be possible.

**Report to:** [nobody]. 

**To test:**

* Code review
* Optionally, replace the `scripts/Frequency_Domain_Analysis.py` file with the following content:

```python
#pylint: disable=invalid-name
from __future__ import (absolute_import, division, print_function)

import sys

import PyQt4.QtGui as QtGui

from Muon.GUI.FrequencyDomainAnalysis.Transform.transform_widget import TransformWidget
from Muon.GUI.Common import load_utils
from Muon.GUI.Common import message_box


class FrequencyDomainAnalysisGui(QtGui.QMainWindow):
    def __init__(self,parent=None):
        super(FrequencyDomainAnalysisGui,self).__init__(parent)

        load = load_utils.LoadUtils()
        if not load.MuonAnalysisExists:
            return
        self.transform = TransformWidget(load = load, parent = self)

        self.setCentralWidget(self.transform.widget)
        self.setWindowTitle("Frequency Domain Analysis")

    # cancel algs if window is closed
    def closeEvent(self,event):
        self.transform.closeEvent(event)


QAPP = None

def qapp():
    global QAPP
    if QAPP is None:
        QAPP = QtGui.QApplication(sys.argv)
    return QAPP


def main():
    app = qapp()
    try:
        ex= FrequencyDomainAnalysisGui()
        ex.resize(700, 700)
        ex.show()
        app.exec_()
    except RuntimeError as error:
        message_box.warning(str(error))


def saveToProject():
    return "state from interface"


def loadFromProject(section):
    print("Loading FDA")
    print(section)


if __name__ == '__main__':
    main()
```

and add `Frequency_Domain_Analysis` to the [list](https://github.com/mantidproject/mantid/compare/master...martyngigg:project-save-python-interfaces?expand=1#diff-6bd08622a7fd56fd11bc014ef19d0a66R121) and recompile. See then that project save and load prints the values from the functions.

Fixes #23234 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
I replaced https://github.com/mantidproject/mantid/compare/master...martyngigg:project-save-python-interfaces?expand=1#diff-6bd08622a7fd56fd11bc014ef19d0a66R124 with the line` QStringList SAVED_PY_INTERFACES = { "Frequency_Domain_Analysis" };
`

I used the code sample above in the frequency GUI.

After it compiled I opened muon analysis and load MUSR 62260. Then I went to open the frequency domain analysis and got the crash below:

image

**Comment by martyngigg** [comment]
I think that is my bad example code. Can you replace the `qapp` function definition with
```python
def qapp():
    global QAPP
    if  QtGui.QApplication.instance() is None:
        QAPP = QtGui.QApplication(sys.argv)
    else:
        QAPP = QtGui.QApplication.instance()
    return QAPP
```
and try again?

**Comment by AnthonyLim23** [comment]
The code below worked. However, when I did save project, the Frequency GUI did not show up in any of the boxes and after clicking save Mantid crashed. 

```
from __future__ import (absolute_import, division, print_function)

import sys

import PyQt4.QtGui as QtGui

from Muon.GUI.FrequencyDomainAnalysis.Transform.transform_widget import TransformWidget
from Muon.GUI.Common import load_utils
from Muon.GUI.Common import message_box


class FrequencyDomainAnalysisGui(QtGui.QMainWindow):
    def __init__(self,parent=None):
        super(FrequencyDomainAnalysisGui,self).__init__(parent)

        load = load_utils.LoadUtils()
        if not load.MuonAnalysisExists:
            return
        self.transform = TransformWidget(load = load, parent = self)

        self.setCentralWidget(self.transform.widget)
        self.setWindowTitle("Frequency Domain Analysis")

    # cancel algs if window is closed
    def closeEvent(self,event):
        self.transform.closeEvent(event)


QAPP = None

def qapp():
    global QAPP
    if  QtGui.QApplication.instance() is None:
        QAPP = QtGui.QApplication(sys.argv)
    else:
        QAPP = QtGui.QApplication.instance()
    return QAPP

def main():
    app = qapp()
    try:
        ex= FrequencyDomainAnalysisGui()
        ex.resize(700, 700)
        ex.show()
        app.exec_()
        return ex
    except RuntimeError as error:
        message_box.warning(str(error))
        return ex

def saveToProject():
    return "state from interface"


def loadFromProject(section):
    print("Loading FDA")
    print(section)


if __name__ == '__main__':
    gui = main()
```

**Comment by martyngigg** [comment]
Which boxes are you referring to? Do you have a stack trace from the crash?

**Comment by AnthonyLim23** [comment]
the dialogs from the project saving, so it was not listed as an open window. I no longer have the stack trace

**Comment by AnthonyLim23** [comment]
just had another go and it works, it just crashes after saving. The call stack is below:

```>	MantidQtWidgetsCommonQt4.dll!PythonInterpreter::finalize() Line 23	C++
 	MantidPlot.exe!PythonScripting::shutdown() Line 225	C++
 	MantidPlot.exe!ScriptingEnv::finalize() Line 74	C++
 	MantidPlot.exe!ApplicationWindow::closeEvent(QCloseEvent * ce) Line 9838	C++
 	QtGuid4.dll!000000005f638cac()	Unknown
 	QtGuid4.dll!000000005fce70a0()	Unknown
 	MantidPlot.exe!ApplicationWindow::event(QEvent * e) Line 16484	C++
 	QtGuid4.dll!000000005f5917b6()	Unknown
 	QtGuid4.dll!000000005f58eae2()	Unknown
 	MantidPlot.exe!MantidApplication::notify(QObject * receiver, QEvent * event) Line 64	C++
 	QtCored4.dll!000000005f0fb92a()	Unknown
 	QtCored4.dll!000000005f1cb6fc()	Unknown
 	QtGuid4.dll!000000005f643061()	Unknown
 	QtGuid4.dll!000000005f686c55()	Unknown
 	QtGuid4.dll!000000005f682319()	Unknown
 	[External Code]	
 	QtGuid4.dll!000000005ffbe2e8()	Unknown
 	QtGuid4.dll!000000005f6840e4()	Unknown
 	[External Code]	
 	QtGuid4.dll!000000005ffbe2e8()	Unknown
 	QtGuid4.dll!000000005f6840e4()	Unknown
 	[External Code]	
 	QtCored4.dll!000000005f1529c8()	Unknown
 	QtGuid4.dll!000000005f6898a5()	Unknown
 	QtCored4.dll!000000005f0f7474()	Unknown
 	QtCored4.dll!000000005f0f774e()	Unknown
 	QtCored4.dll!000000005f0f97dc()	Unknown
 	QtGuid4.dll!000000005f58bb98()	Unknown
 	MantidPlot.exe!main(int argc, char * * argv) Line 242	C++
```

**Comment by martyngigg** [comment]
@AnthonyLim23 I think I have fixed all of the issues here now.

It requires a slightly modified launcher script. The `setProperty` line (near the bottom) is now required. I have also chosen to remove the `main()` function as I think it actually only causes confusion because we have to return a value and assign it to something that is never used. Let's just keep that part protected by the `__name__` check for now. 

```python
from __future__ import (absolute_import, division, print_function)

import sys

import PyQt4.QtGui as QtGui

from Muon.GUI.FrequencyDomainAnalysis.Transform.transform_widget import TransformWidget
from Muon.GUI.Common import load_utils
from Muon.GUI.Common import message_box


class FrequencyDomainAnalysisGui(QtGui.QMainWindow):
    def __init__(self,parent=None):
        super(FrequencyDomainAnalysisGui,self).__init__(parent)

        load = load_utils.LoadUtils()
        if not load.MuonAnalysisExists:
            return
        self.transform = TransformWidget(load = load, parent = self)

        self.setCentralWidget(self.transform.widget)
        self.setWindowTitle("Frequency Domain Analysis")

    # cancel algs if window is closed
    def closeEvent(self,event):
        self.transform.closeEvent(event)


def qapp():
    if  QtGui.QApplication.instance() is None:
        return QtGui.QApplication(sys.argv)
    else:
        return QtGui.QApplication.instance()


def saveToProject():
    return "state from interface"


def loadFromProject(section):
    print("Loading FDA")
    print(section)


if __name__ == '__main__':
    app = qapp()
    try:
        ex = FrequencyDomainAnalysisGui()
        # Tie the GUI to this launcher script. Required for project saving
        # in MantidPlot.
        ex.setProperty("launcher", "Frequency_Domain_Analysis")
        ex.resize(700, 700)
        ex.show()
        app.exec_()
    except RuntimeError as error:
        message_box.warning(str(error))
```

**Review by AnthonyLim23 — APPROVED** [review]
all works

**Pull request merged**
