### PR TITLE
Fix index peaks crash

### LINKED ISSUE #29429: Issue with IndexPeaks
**Original reporter:** Xiaoping Wang

There is a blocking issue for indexing satellite peaks using IndexPeaks using the current version of mantidplot and mantidworkbench (5.0 and nightly).

Running IndexPeaks when SaveModulationInfo will crash mantidplot and mantidworkbench. We cannot index satellite peaks for TOPAZ users because of this problem.

Please see the screenshot and the error message highlighted below.

Attached are the .integrate file used in the test

test_index_satellite_peaks.integrate

 

The expected (correct) output with ModVector1=’0,0,0.33333’.

satellite_peaks_indexed.integrate

 

and the corresponding UB matrix:

 

0.01918798  0.01886947  0.20883907

-0.13482013 -0.09906334  0.12772788

 0.06733971 -0.08893243  0.00192303

ModUB:

 0.02225731 -0.02948890  0.00058098

 0.00000000  0.00000000  0.00000000

 0.00000000  0.00000000  0.00000000

     5.4886      5.4907      8.9632     89.9126     90.0768    120.0863    233.7216

     0.0004      0.0002      0.0004      0.0035      0.0047      0.0037      0.0212

 

Modulation Vector 1:        -0.0004      0.0003      0.3312

Modulation Vector 1 error:   0.0033      0.0036      0.0053

 

Max Order:        1

Cross Terms:      0

 

The above matrix is the Transpose of the UB Matrix and the Transpose of ModUB. The UB matrix together with ModUB maps the column vector (h,k,l,m,n,p)

to the column vector (q'x,q'y,q'z).

The columns of ModUB are the coordinates of modulation vectors in Qlab.

|Q'|=1/dspacing and its coordinates are a right-hand coordinate system where x is the beam direction and z is vertically upward.(IPNS convention)

### PR DESCRIPTION
**Pull request by KedoKudo**
**Description of work.**

This is the same bug fix migrated from PR #29583.

> below is the original description

As described in #29429, the `IndexPeaks` function will leads to a segmentation fault when invoked with 

```python
IndexPeaks(
    PeaksWorkspace="data", 
    Tolerance=0.12, 
    RoundHKLs=False,
    SaveModulationInfo=True,
)
``` 

This is because the function `validModulationVectors` will return an empty `std::vector` with the default `modVector` values.
Trying to access these non-existing/empty `modVector` at any point in code will lead to the aforementioned segmentation fault.
This patch adjusted the order of the input property assignment to avoid empty `modVectors`, ensuring the internal representation matches the description in the documentation (default modVectors are `(0,0,0)`, not `()`).

**To test:**
Using the data provided in the linked issue, the following Python script can be used to perform the required test
```Python
#!/usr/bin/bash

from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

# load data
Load(
    Filename="test_index_satellite_peaks.integrate",
    OutputWorkspace="test",
    )

FindUBUsingIndexedPeaks(PeaksWorkspace="test")

print("testing default input")
IndexPeaks(
    PeaksWorkspace="test", Tolerance=0.12,
)

print("testing zero (default) modVec with maxOrder=1")
IndexPeaks(
    PeaksWorkspace="test", Tolerance=0.12, 
    RoundHKLs=False,
    SaveModulationInfo=True,
    MaxOrder=1,
    # ModVector1='0,0,0.33333',
    # ModVector2='0,0,0',
    # ModVector3='0,0,0',
    )

print("testing one non-zero modVec with maxOrder=1")
IndexPeaks(
    PeaksWorkspace="test", Tolerance=0.12, 
    RoundHKLs=False,
    SaveModulationInfo=True,
    MaxOrder=1,
    ModVector1='0,0,0.33333',
    # ModVector2='0,0,0',
    # ModVector3='0,0,0',
    )

print("testing one non-zero modVec with maxOrder=0")
IndexPeaks(
    PeaksWorkspace="test", Tolerance=0.12, 
    RoundHKLs=False,
    SaveModulationInfo=True,
    # MaxOrder=1,
    ModVector1='0,0,0.33333',
    # ModVector2='0,0,0',
    # ModVector3='0,0,0',
    )
```

Fixes #29429. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Harrietbrown** [comment]
Running the script I can't get the load to work.

```
Load started
Failed to read as ASCII this file: 'C:\Users\wey38795\Documents\pr_test_files\test_index_satellite_peaks.integrate.txt, error description: Failed to create a Workspace2D from the data found in this file. Error: All arguments to init must be positive and non-zero
Error in execution of algorithm LoadAscii:
Failed to recognize this file as an ASCII file, cannot continue.
Error in execution of algorithm Load:
Failed to recognize this file as an ASCII file, cannot continue.
RuntimeError: Failed to recognize this file as an ASCII file, cannot continue.
  File "<string>", line 11, in <module>
  File "c:\users\wey38795\documents\mantid_builds\master\raw\mantid\framework\pythoninterface\mantid\simpleapi.py", line 174, in Load
    algm.execute()
```

**Comment by RichardWaiteSTFC** [comment]
> Running the script I can't get the load to work.
> 
> ```
> Load started
> Failed to read as ASCII this file: 'C:\Users\wey38795\Documents\pr_test_files\test_index_satellite_peaks.integrate.txt, error description: Failed to create a Workspace2D from the data found in this file. Error: All arguments to init must be positive and non-zero
> Error in execution of algorithm LoadAscii:
> Failed to recognize this file as an ASCII file, cannot continue.
> Error in execution of algorithm Load:
> Failed to recognize this file as an ASCII file, cannot continue.
> RuntimeError: Failed to recognize this file as an ASCII file, cannot continue.
>   File "<string>", line 11, in <module>
>   File "c:\users\wey38795\documents\mantid_builds\master\raw\mantid\framework\pythoninterface\mantid\simpleapi.py", line 174, in Load
>     algm.execute()
> ```

That's because it thinks it's a text file I think - you need to remove the .txt extension

**Comment by RichardWaiteSTFC** [comment]
I'm still getting the assertion error from the original PR - #29583 - I'm looking into it

**Comment by RichardWaiteSTFC** [comment]
The problem this time is on line 463 - it doesn't look like the args.satellites.modVectors container has been pre-allocated/reserved and so you get another out of range when you try accessing the second element. The code works as expected if you Load the data/fingUb and then index peaks in the last block (i.e. skip the other index peak calls)

**Comment by Harrietbrown** [comment]
I'm getting a runtime error with vector out of range.

**Comment by RichardWaiteSTFC** [comment]
> I'm getting a runtime error with vector out of range.

Yeh I think that's the same issue I found above  (and see previous PR #29583)

**Comment by KedoKudo** [comment]
> > Running the script I can't get the load to work.
> > ```
> > Load started
> > Failed to read as ASCII this file: 'C:\Users\wey38795\Documents\pr_test_files\test_index_satellite_peaks.integrate.txt, error description: Failed to create a Workspace2D from the data found in this file. Error: All arguments to init must be positive and non-zero
> > Error in execution of algorithm LoadAscii:
> > Failed to recognize this file as an ASCII file, cannot continue.
> > Error in execution of algorithm Load:
> > Failed to recognize this file as an ASCII file, cannot continue.
> > RuntimeError: Failed to recognize this file as an ASCII file, cannot continue.
> >   File "<string>", line 11, in <module>
> >   File "c:\users\wey38795\documents\mantid_builds\master\raw\mantid\framework\pythoninterface\mantid\simpleapi.py", line 174, in Load
> >     algm.execute()
> > ```
> 
> That's because it thinks it's a text file I think - you need to remove the .txt extension - or use LoadISawPeaks should work

I am a little bit confused here, why is the Runtime Error still referencing the python file from the master branch?

>File "c:\users\wey38795\documents\mantid_builds\__master__\raw\mantid\framework\pythoninterface\mantid\simpleapi.py", line 174, in Load

**Comment by KedoKudo** [comment]
> 463

[Line 463](https://github.com/mantidproject/mantid/blob/015f135e7524efd6af649fefd826154691ed2ff2/Framework/Crystal/src/IndexPeaks.cpp#L463) in the new branch is a `else` statement.   Could you confirm whether the correct branch is being pulled?  This branch is different from the yesterday one as I need to make sure the changes are based on release-next, not master.

**Comment by RichardWaiteSTFC** [comment]
> > 463
> 
> [Line 463](https://github.com/mantidproject/mantid/blob/015f135e7524efd6af649fefd826154691ed2ff2/Framework/Crystal/src/IndexPeaks.cpp#L463) in the new branch is a `else` statement. Could you confirm whether the correct branch is being pulled? This branch is different from the yesterday one as I need to make sure the changes are based on release-next, not master.

I have this on line 473  `if (args.satellites.modVectors[2].nullVector()) {`

**Comment by KedoKudo** [comment]
> > > 463
> > 
> > 
> > [Line 463](https://github.com/mantidproject/mantid/blob/015f135e7524efd6af649fefd826154691ed2ff2/Framework/Crystal/src/IndexPeaks.cpp#L463) in the new branch is a `else` statement. Could you confirm whether the correct branch is being pulled? This branch is different from the yesterday one as I need to make sure the changes are based on release-next, not master.
> 
> I have this on line 467 `if (args.satellites.modVectors[2].nullVector()) {`

what I saw is `if (args.satellites.modVectors[1].nullVector())`

**Comment by RichardWaiteSTFC** [comment]
> > > > 463
> > > 
> > > 
> > > [Line 463](https://github.com/mantidproject/mantid/blob/015f135e7524efd6af649fefd826154691ed2ff2/Framework/Crystal/src/IndexPeaks.cpp#L463) in the new branch is a `else` statement. Could you confirm whether the correct branch is being pulled? This branch is different from the yesterday one as I need to make sure the changes are based on release-next, not master.
> > 
> > 
> > I have this on line 467 `if (args.satellites.modVectors[2].nullVector()) {`
> 
> what I saw is `if (args.satellites.modVectors[1].nullVector())`

yes sorry I then really helped things by copying the wrong line as well! Sorry

**Review by RichardWaiteSTFC — APPROVED** [review]
Looks good as a temporary fix - there is no error when running the test script and it fixes the issue. Specifying a modulation vector with no max order does not result in satellite peaks being indexed which is believed to be expected behaviour.

**Pull request merged**
