### PR TITLE
Fix remaining Coverity issues in ApplicationWindow

### PR DESCRIPTION
**Pull request by eXeC64**
This is for trac ticket [#11305](http://trac.mantidproject.org/mantid/ticket/11305).

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
Related to this, we now seem to have a build with a more picky ccpcheck (1.68) which has found a few more issues in ApplicationWindow: http://builds.mantidproject.org/view/All/job/cppcheck-1.68/34/cppcheckResult/

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by eXeC64** [comment]
Jenkins, retest this please.

**Comment by FedeMPouzols** [comment]
All looks good. A few less remaining coverity issues...

**Pull request merged**
