### PR TITLE
Tidy Code & Functionality in the Reflectometry GUI

### LINKED ISSUE #26539: Minor reflectometry GUI tidying
- Make notification function names more clear/consistent: e.g. notifyReductionPaused is actually a request so should be, say notifyPauseReductionRequested, and reductionPaused is the notification that it's done, so should be notifyReductionPaused.
- Check if uses of AlgorithmManager could be cleaned up more
- Remove hard-coded indices in per-theta defaults table code and tests. Also it looks like there's some duplication between ValidatePerThetaDefaultsTest and PerThetaDefaultsTableValidatorTest - can this be consolidated?
- Remove direct use of RowPath and use RowLocation instead.
- Remove use of m_presenter in MainWindowView::closeEvent

### PR DESCRIPTION
**Pull request by cailafinn**
**Description of work.**
- Increaced the size of the Runs column by default.
- Switched hard coded indecies for use of the `Column` enum for maintainability.
- Removed uses of the presenter member variable in `MainWindowView`
- Globally defined colours used in the GUI tables
- Removed unused methods from `InstrumentView`
- Moved implementation out of `JobsViewUpdater` header file
- Fixed validation of ExperimentView when loading batches
- Disabled Add Row button in Experiment tab when processing
- Improved naming of notification functions in Save, Event, Experiment, and Instrument components
- Removed uses of `RowPath`, replacing them with `RowLocation`

**To test:**
 I know it's a cop-out to not write proper testing instructions, but given so many parts of the GUI code have been touched it's probably worth just going through the manual testing: https://developer.mantidproject.org/Testing/ReflectometryGUI/ReflectometryGUITests.html

Otherwise: 
1. Check that on opening the GUI the Runs column is wide enough that you can click inside the *second* row. 
2. Check that when processing runs in the runs tab the Add Row button is disabled in the Experiment Settings tab. 
3. Put some invalid values into the Experiment Settings -> Per-angle defaults table and save the batch. Reloading the batch should still show these invalid values as errors. 

Fixes #26539 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by gemmaguest — CHANGES_REQUESTED** [review]
Code changes look really good and it's great to finally get all this tidying up done. It should make things a lot easier going forward :+1: :tada: Great work on figuring out the items we hadn't got round to discussing, too! Just a couple of minor in-line comments.

I'm also not sure about the new naming of the notify functions. I probably didn't explain it too well :sweat_smile: I think the resume ones probably make sense and the pause ones maybe not, because the resume notification happens before any processing is actually started (to prevent race conditions with clicking on things), but the pause notifications happen after pausing has finished. I think the notify functions in the batch may need renaming to match too. We need to pinpoint where the action actually takes place; before this it is just "requested" and afterwards it is notifying that it has actually happened. Note for autoreduce this might be in the main window.

It might be worth extracting those commits to a separate branch and we can talk them through and do them as a separate PR (although not a problem to leave them in this PR if that's going to cause conflicts!).

**Review by gemmaguest — DISMISSED** [review]
Looks good now, thanks for the changes :+1:

The Add Row button is not disabled when processing (I think this change was just missed) but the behaviour is the same as previously so no need to hold up the PR. Let's get the rest of these changes in :shipit:

**Review by DavidFair — CHANGES_REQUESTED** [review]
Some minor readability nits

**Review by DavidFair — APPROVED** [review]
LGTM, thanks for doing those changes

**Pull request merged**
