### PR TITLE
Abins: fix scaling of quantum orders

### PR DESCRIPTION
**Pull request by ajjackson**
**Description of work**
The relative scaling of quantum orders from Abins has been adjusted. A partially-cancelling combination of bugs in the intended behaviour has been removed; the net result of this is
- When using QuantumOrderEvents=1 or QuantumOrderEvents=2 _without_ autoconvolution, there is no change
- When using QuantumOrderEvents=1 with autoconvolution, order 2 was exaggerated by a factor of 2; this is fixed
- When using QuantumOrderEvents=2 with autoconvolution, orders 3+ were underestimated by a factor of 0.5; this is fixed

**Purpose of work**
The implementation of higher-order events in Abins was careful not to change the existing implementation of orders 1, 2. (https://github.com/mantidproject/mantid/pull/30895, https://github.com/mantidproject/mantid/pull/33064). However, this added complexity to the implementation of a 1/n! scaling term (where n is quantum order), and with this complexity came a few bugs.

A recent review of Abins results compared to experimental data (with @DonaldChung-HK ) revealed a systematic under-estimate of "phonon wings" (which are composed of high-order terms) in simulated TOSCA spectra. As a result of this I examined the implementation more carefully and found these bugs.

**Summary of work**
The revised implementation is simpler: a factor 0.5 (i.e. 1/2!) is extracted from the detail order-2 calculation, and then 1/n! factors are applied consistently regardless of calculation mode.

This gives more consistent behaviour between different approximations of order 2, and better agreement with experiment.

Raised by / report to: @sanghamitra-mukhopadhyay

**To test:**

Unit tests that include quantum orders 3+ need updating. The results are unchanged for other unit tests.

Systemtests probably need updating, we'll see.

*Release note will be required*

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by ajjackson** [comment]
(Actually that experimental data is TXFA which may explain some of disagreement)

**Comment by AnthonyLim23** [comment]
In the tests I looked at the quantum order 3+ was insignificant. However, the analytic and numeric values for quantum order 2 were similar. 

This PR needs some tests and a release note.

**Comment by AnthonyLim23** [comment]
This bug was noticed and reported by a user at the beta testing workshop. This fixes the data as it was numerically incorrect before. 

Since the fix is small and will not impact any other areas we should put into the upcoming release.

**Comment by ajjackson** [comment]
Test data has been updated for the structure factor order 1-10 calculation, where results were expected to change.

Here is a plot of orders 1-5 for atom 0 in this data set: as expected, orders 3+ have doubled in intensity.

abins-scaling-data-update

and the script used to generate it:

```python
#! /usr/bin/env python3

from argparse import ArgumentParser
import json
from pathlib import Path
from typing import List

from matplotlib.axes import Axes
import matplotlib.pyplot as plt


max_order = 5


def main():
    parser = ArgumentParser()
    parser.add_argument(
        "filenames",
        nargs="+",
        type=Path,
        help=".txt file(s) from Abins CalculateSPowder_1d unit tests",
    )

    args = parser.parse_args()

    fig, axes = plt.subplots(nrows=max_order)

    for filename in args.filenames:
        with open(filename, 'r') as fp:
            data = json.load(fp)

        plot_spectra(data, axes.flatten().tolist(), str(filename))

    for i, ax in enumerate(axes.flatten()):
        ax.set_title(f"Quantum order {i + 1}")
    axes[-1].legend()

    fig.tight_layout()
    fig.subplots_adjust(hspace=0.4)
    plt.show()

def plot_spectra(data: dict, axes: List[Axes], label: str):
    freqs = data["frequencies"]

    for order in range(1, max_order + 1):
        axes[order - 1].plot(freqs,
                             data["atom_0"]["s"][f"order_{order}"],
                             label=label)

if __name__ == "__main__":
    main()
```

(Perhaps that should go in the Script Repository or something...)

**Review by AnthonyLim23 — APPROVED** [review]
The code looks good and it behaves as expected (no more double counting)

**Pull request merged**
