### PR TITLE
Fix multi-period event data loading bug for LARMOR

### LINKED ISSUE #17787: Multiperiod Event Data Bug for LARMOR
Rob wrote:

> I’m finding that the reduction of multi-period data has an error.
> The first period is reduced correctly but subsequent ones do not have the appropriate bench rotation applied.
> 
> I’m not sure if this is a general error or one specific to the Larmor implementation
> 
> As an  example please try
> Sample SANS 13038
> Sample Trans 13039
> Sample Direct Beam 13041
> Can SANS 13040
> Can Trans 13041
> Can Direct Beam 13041
> 
> The user file is
> \isis\inst$\ndxlarmor\user\users\masks\ USER_Larmor_163F_HePATest_r13038.txt
> There are a couple of extra mask files in there.
> 
> I’m trying to get this working for November 15th

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Fixes #17787

Loading multiperiod event files for LARMOR was producing incorrect results. Only the first child workspace was rotated correctly. The other child workspaces were not rotated but translated. LARMOR decided if the workspaces should be moved or translated based on the run number. There was a bug in how this is extracted from the workspaces name is it cannot be found in the logs.

**To test:**

Find the test data here: \olympic\Babylon5\Scratch\Anton\LARMOR_MULTIPERIOD_BUG
1. Open the ISIS SANS GUI
2. Set the instrument to LARMOR
3. Load the User File : USER_Larmor_163F_HePATest_r13038.txt
4. Set the scatter sample to LARMOR00013038
5. Press Load
6. Run the script below

``` python
base_name = "13038_sans_nxs_"
for index in range(1, 5):
    ws_name = base_name + str(index)
    ws = mtd.retrieve(ws_name)
    instrument = ws.getInstrument()
    component =  instrument.getComponentByName("DetectorBench")
    print "Workspace {0} has a position of {1} and rotation of {2}".format(index,  component.getPos(), component.getRotation())
```

Confirm that all positions and rotations are the same.

#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by lottiegreenwood** [comment]
works as described :shipit:

**Comment by martyngigg** [comment]
@AntonPiccardoSelg Unfortunately there is a merge conflict in the release notes after merging the other 2 SANS-related pull requests.

**Comment by AntonPiccardoSelg** [comment]
@martyngigg The merge conflict has been sorted out.

**Comment by martyngigg** [comment]
Yep, good to :shipit: again now.

**Pull request merged**
