### PR TITLE
script editor output window to match zoom with window

### LINKED ISSUE #9566: Script window output change font size
This issue was originally [TRAC 8722](http://trac.mantidproject.org/mantid/ticket/8722)

In the script window, changing font size affects only the script part, not the output. In case you want to show on a projector, this might be very unfortunate, since people cannot read the output (lesson learned from Mantid courses)

### PR DESCRIPTION
**Pull request by NickDraper**
zooming in the output and script parts of the script editor should now be linked

fixes #9566
### Release notes

Added
- The text size is now linked between the script and output parts of the window, so if you zoom into or out of one the other follows.  You can zoom using ctrl+the mouse scroll wheel, or the font size options under the window menu.
### to test
1. open the script editor with at least two tabs both with some code (print statements) and output
2. zoom 
   1. with the mouse wheel both on the script and output windows
   2. with the menu options
   3. with the reset zoom menu option
3. check that the zoom is linked, both within the tab and across all tabs

### CODE REVIEW

**Comment by DanNixon** [comment]
Executing a script after setting the font size causes the output to be printed in the default size.
2015-08-12-123349_2480x1920_scrot

**Comment by FedeMPouzols** [comment]
@NickDraper, @DanNixon  : are the many .rst files from the wiki examples meant to be included in this PR?

**Comment by NickDraper** [comment]
@DanNixon I've fixed the font size reset problem
@FedeMPouzols thanks for the spot on the rst files, I've removed these now.

**Comment by DanNixon** [comment]
This is what happens when I open the interface and run a script.
2015-08-17-142814_2480x1920_scrot

I thought this may be some weirdness with old Qt preferences but after clearing them the behaviour is the same.

It makes no difference what I do with the font options, the output is always at this size.

Also just found that Ctrl+- only affects the code window, not the output.

**Comment by NickDraper** [comment]
The ubuntu failure is unrelated.

I've fixed the varying font size issues.
The ctrl+- work flawlessly on windows, please retest

**Pull request merged**
