### PR TITLE
Peak table in splatterplot in vsi

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Implements feature [#11053](http://trac.mantidproject.org/mantid/ticket/11053#comment:17)

The original ticket contains test instructions. The relevant data can be dowloaded from

[EllipsoidalPeakWS1]​(https://www.dropbox.com/s/gerthrvkipj8mwl/ellipse_peaks2.nxs?dl=0)
​[EllipsoidalPeakWS2]​(https://www.dropbox.com/s/4bq0d7glbbdj03w/ellipse_peaks1.nxs?dl=0)
[EllipsoidalWS]​(​https://www.dropbox.com/s/r0c81njiif154z5/ellipseWS.nxs?dl=0)

### CODE REVIEW

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by picatess** [comment]
Jenkins, retest this please

**Comment by OwenArnold** [comment]
jenkins retest this please

**Comment by OwenArnold** [comment]
Jenkins retest this please

**Comment by OwenArnold** [comment]
jenkins retest this please

**Comment by OwenArnold** [comment]
I've made some minor changes to kill one of the warnings on RHEL6, but other than that all the code is Antons. This is working the way I would expect it to. I also have some minor comments about the code.

**Pull request merged**
