### PR TITLE
Add option to specify reflection type to PredictFractionalPeaks

### LINKED ISSUE #26690: Add option to specify lattice type in PredictFractionalPeaks
`PredictPeaks` has the option to specify the lattice type of the crystal so it can use this information to predict peaks that _should_ be there. `PredictFractionalPeaks` needs something similar for satellite peaks to know when a peak is expected vs measured.

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

**To test:**

Download the data from #26910. You'll need to NeXus from the .zip file. The following script gives an idea of how to use the algorithm.

```python
Load(Filename='unindexed-peaks.nxs', OutputWorkspace='sx_peaks')
LoadIsawUB(InputWorkspace='sx_peaks', Filename='pr-26807.txt')
PredictFractionalPeaks(Peaks='sx_peaks', Hmin=-1, Hmax=1, Kmin=-1, Kmax=1, Lmin=-1, Lmax=1, ReflectionCondition='All-face centred', RequirePeaksOnDetector=False, FracPeaks='fractional')
LoadEmptyInstrument(InstrumentName='WISH', OutputWorkspace='wish')
```

Once the `fractional` workspace has been created open the instrument view on the `wish` workspace and drag the `fractional` workspace on to it. In this example, because `RequirePeaksOnDetector=False` then you should see peaks not on a detector bank. Flip this option to `True` and the peaks should all be on a detector.

Play with the ranges and if you expand them more peaks should be found and vice versa. Selecting the another reflection type should change the peaks found. 

Fixes #26690

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by RichardWaiteSTFC — CHANGES_REQUESTED** [review]
Tested the PredictFractionalPeak with/without flag to require the peak on the detector. In the peak table returned when the flag to require the peak to be on the detector is false (i.e allow peaks to be off the detector) the detector column is -1 for all peaks (i.e. unassigned). When the peaks are viewed on instrument view the peaks are not randomly assigned a detector (see attached) it is as if the out of plane angle is wrong. When the flag is True (i.e peaks must be on the detector) the algorithm behaves as expected).
image

**Comment by martyngigg** [comment]
@RichardWaiteSTFC Thank you for testing this. I believe I have found the problem. You were correct in such as it was to do with the out of plane angle. When the code failed to find a detector it set the expected detector position to a unit vector in the direction of the expected position rather than the absolute position. This should be fixed now.

Would you mind retesting this when you get a chance?

**Comment by RichardWaiteSTFC** [comment]
Hi Martyn,


Thanks for keeping me updated, I'm very happy to test it but I'm actually out of the office all this week. I'm having trouble getting the VPN to work on my computer so I can't remote desktop yet... If I get it working I will test it tomorrow, but if not it might have to wait until next week, sorry! I'll let you know tomorrow.


Thanks,

Richard

________________________________

**Comment by martyngigg** [comment]
@RichardWaiteSTFC Yes no problem. Thanks.

**Comment by RichardWaiteSTFC** [comment]
Testing the PredictFractionalPeaks with the following command

PredictFractionalPeaks(Peaks='sx_peaks', Hoffset='-0.135,0.135', Koffset='-0.135,0.135', 
    Hmin=-1, Hmax=1, Kmin=-1, Kmax=1, Lmin=-3, Lmax=3, ReflectionCondition='Primitive', 
    RequirePeaksOnDetector=False, FracPeaks='frac')

I get the following error message in a pop-up box when the progress bar shows 78% finished (error occurs at same % every time). Error occurs regardless of whether flag RequirePeaksOnDetector is True or False.

image

A screenshot of the call stack

image

**Review by RichardWaiteSTFC — DISMISSED** [review]
Tested and the additional flag works as expected.

**Comment by martyngigg** [comment]
@RichardWaiteSTFC I had to push some changes to fix some build failures on macOS. Would you mind re-approving this?

**Review by RichardWaiteSTFC — APPROVED** [review]
PredictFractionalPeaks with flag to require peaks to be on/off detector still works as expected (on windows)

**Pull request merged**
