### PR TITLE
TOFTOF GUI: add progress report status message

### LINKED ISSUE #22600: TOFTOF GUI: progress report and status message
Requested by instrument scientist.

1. TOFTOF GUI should show the progress bar while running the data reduction.
2. After the end of the data reduction a message should appear. The message should be either `Reduction successfully finished` or `An error has happened during the data reduction. See the results log.`

JoachimCoenen will work on it.

### PR DESCRIPTION
**Pull request by JoachimCoenen**
**Description of work.**
Added a progress bar to the TOFTOF reduction GUI, that appears when 
TOFTOF GUI now shows a progress bar while running the data reduction and After the end of the data reduction a status message appears, indicating the success or failure of the reduction

**To test:**

Start the TOFTOF data reduction GUI: `Interfaces`&rarr;`Direct`&rarr;`DGS Reduction`. Choose facility MLZ and instrument TOFTOF.

Get the test data
[testdata.zip](https://github.com/mantidproject/mantid/files/1356265/testdata.zip)

and make sure, that:
 - the progress bar appears at the bottom of the form when pressing `Reduce`
 - and gets updated during the reduction process
 - and displays a success message, once the reduction has finished
 - or displays a failure message, if the reduction was attempted, but failed (eg. because of invalid data-/vanadium-runs...)

Fixes #22600. 

Does this update require release notes?
- [ ] Yes
- [ ] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by mganeva** [comment]
Bug: the SQW workspaces are not renamed (group `g{prefix}DataSQW`)

**Comment by peterfpeterson** [comment]
@JoachimCoenen Please merge `master` into your branch and resolve the conflicts.

**Comment by JoachimCoenen** [comment]
I have tried to, but I couldn't reproduce the test failures on Ubuntu+Python 3, and on windows i cant get mantid to even build... :( (neither VS, nor QtCreator...)

**Comment by JoachimCoenen** [comment]
@mantid-builder the Windows build? The CMake step fails. It either: can't find the compiler, or can't find the qt libraries, or fails to find (download?) google-test... etc, depending on how I try to build Mantid.

**Comment by mganeva** [comment]
I will take it over next week.

**Comment by NickDraper** [comment]
@mganeva Could you update me on the state of this stale PR?

**Comment by NickDraper** [comment]
@mganeva Does this PR need to stay open?  It doesn't seem to be getting any attention.  Could we perhaps close the PR, and open a new one once the code is in a better state?

**Comment by JoachimCoenen** [comment]
still missing release notes...

**Comment by JoachimCoenen** [comment]
release notes added. No longer "in progress".

**Comment by NickDraper** [comment]
This PR is being closed as it is over a year old and has not been recently progressed. If it is important to progress this work reopen the PR and prioritise the work.
Otherwise, the underlying branch will be removed at the next cleanup along with the next release unless it is progressed further.

**Pull request closed without merging**
