### PR TITLE
Remove Qt3Support Warnings in all other files Group No. 3

### PR DESCRIPTION
**Pull request by shahrozahmed1**
This is group 3 of #16129

This fixes the Qt3Support Warnings in all other files Group No. 3

Folder.cpp bd84b1d
FunctionCurve.cpp   a8b81bf
FunctionDialog.cpp bd84b1d
Graph.cpp a8b81bf, d9d2b8c

**To Test:**

Code Review
Check MantidPlot builds successfully
Check all builds pass successfully

**Further Tests**

The changes in this PR have touched many areas of MantidPlot. Below is a list of some of the items which should be checked:

Load a workspace and Plot
- Graph plotted well and functioning as it should
- Title and labels correctly displayed
- Zoom in/out
- Click right and select `Add Function` _(help: http://www.mantidproject.org/MantidPlot:_Add_Function)_
- Create a function and make sure its plotted
- Click RIght on Plot & Select `Analyze/Fit Wizard..` 
- Play around Function Dialog with http://www.mantidproject.org/MantidPlot:_User_Function_Dialog

Save project and load project
- File/Save/Project (Ctrl+Shift+S)
- restart Mantid
- File/Load/Project

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
Looks good :shipit:

**Comment by shahrozahmed1** [comment]
Sorry @KarlPalmen , I had a [commit](https://github.com/mantidproject/mantid/pull/16355/commits/d9d2b8c101ba39aa583e6d92a0452e4bcc1f6ca6) which I forgot to push earlier but essentially it doesn't change much.

**Comment by FedeMPouzols** [comment]
Is the clang-format really needed here?
It is planned somewhere else, and it could cause conflicts with changes in other PRs.

**Comment by shahrozahmed1** [comment]
@FedeMPouzols Noticed other users applying clang-format and also as we are fixing individual files I just imaged no one really would be touching these qt files during maintenance period especially, however it would be a bad idea clang-formatting to `ApplicationWindow.cpp` file.

**Comment by KarlPalmen** [comment]
Some of the clang changes are sufficiently great to require a retest.

**Comment by martyngigg** [comment]
Is this ready to go or does it need further testing?

**Comment by KarlPalmen** [comment]
I'm about to do a cursory retest.

**Comment by KarlPalmen** [comment]
Retest was OK :shipit:

**Comment by martyngigg** [comment]
Thanks!

**Pull request merged**
