### PR TITLE
Peaks and DetCal files for instruments with tubes

### LINKED ISSUE #13021: SaveIsawPeaks save banks for CORELLI
Peaks table should display bank numbers and files should have correct heading for tubes.

### PR DESCRIPTION
**Pull request by VickieLynch**
fixes #13021 Peaks file and detcal file needed for anvred created for CORELLI.  Also got this working for WISH.  To test:

``` python
Load(Filename='corPeaks.nxs', OutputWorkspace='corPeaks')
SaveIsawPeaks(InputWorkspace='corPeaks',Filename="corPeaks.peaks")
SaveIsawDetCal(InputWorkspace='corPeaks',Filename="corPeaks.DetCal")
LoadIsawPeaks(Filename='corPeaks.peaks',OutputWorkspace='readCorPeaks')
Load(Filename='wishPeaks.nxs', OutputWorkspace='wishPeaks')
SaveIsawPeaks(InputWorkspace='wishPeaks',Filename="wishPeaks.peaks")
SaveIsawDetCal(InputWorkspace='wishPeaks',Filename="wishPeaks.DetCal")
LoadIsawPeaks(Filename='wishPeaks.peaks',OutputWorkspace='readWishPeaks')
LoadEmptyInstrument(Filename='CORELLI_Definition.xml', OutputWorkspace='corelli')
LoadEmptyInstrument(Filename='WISH_Definition_10Panels.xml', OutputWorkspace='wish')

#Show instrument before and after the next 2 algorithms
LoadIsawDetCal(InputWorkspace='corelli', Filename='corPeaks.DetCal')
LoadIsawDetCal(InputWorkspace='wish', Filename='wishPeaks.DetCal')

```

Link for corPeaks.nxs:
https://drive.google.com/open?id=0B74Stt5AQ4w5LVJaZzFqYURzUzg
Link for wishPeaks.nxs
https://drive.google.com/open?id=0B74Stt5AQ4w5bzFSN3A2S2ljV3M

### CODE REVIEW

**Comment by VickieLynch** [comment]
WISH detectors have problem after LoadIsawDetCal in 3D view.

**Comment by rosswhitfield** [comment]
With the SaveIsawDetCal, should the Base and Up Vectors be the negative of what they are here. I would think that the Up vector would be (0,1,0) and not (0,-1,0). 

```
4 DETNUM  NROWS  NCOLS   WIDTH   HEIGHT   DEPTH   DETD   CenterX   CenterY   CenterZ    BaseX    BaseY    BaseZ      UpX      UpY      UpZ
5      1     16    256 20.9550 83.5922   0.2000 254.80  127.4295  -80.4864 -205.4427 -0.84980  0.00000 -0.52710  0.00000 -1.00000  0.00000 
5      2     16    256 20.9550 83.5922   0.2000 254.80  146.2650  -80.4864 -192.4877 -0.79621  0.00000 -0.60502  0.00000 -1.00000  0.00000 
...
```
Also does Isaw have a particular definition for rows and cols? I always thought of Corelli as having 256 rows and 16 columns.

**Comment by VickieLynch** [comment]
I did change the sign of the base and up vectors to get WISH looking the same, but maybe the error was in the rotations. The peaks have COL, ROW by your definition, so will change NROWS, NCOLS.

**Comment by rosswhitfield** [comment]
Running the following, bank1 on Corelli isn't placed correctly.
```python
LoadEmptyInstrument(Filename='CORELLI_Definition.xml', OutputWorkspace='corelli')
LoadIsawDetCal(InputWorkspace='corelli', Filename='corPeaks.DetCal')
```
There should be a bank where the arrow is.
corintrbank01

Bank1 has moved to same place as the last bank, bank91. It has the correct rotation just wrong centre.
corbank01

**Pull request merged**
