### PR TITLE
Use Mantidlibs software collection on RHEL7

### PR DESCRIPTION
**Pull request by stuartcampbell**
This is to enable RHEL7 to use the mantidlibs software collection

### CODE REVIEW

**Comment by martyngigg** [comment]
Was this based off `next`? It has the commit that fixes the patch number to 3.3.0 so we shouldn't merge this to master.

**Comment by martyngigg** [comment]
I guess the easiest way to deal with this would just be to revert `1385fe4` that fixed the patch number.

**Comment by sic** [comment]
But it looks like it also has the change to undo it as well.  Looking at the diff with master it looks ok

**Comment by martyngigg** [comment]
Oh yes, you're right. I should have looked further down. Sorry about that.

It's good to go then.

**Pull request merged**
