### PR TITLE
D16 logbook update

### PR DESCRIPTION
**Pull request by darominski**
**Description of work.**

The default parameters proposed for algorithmic logbook generation for D16 instrument at the ILL, modeled after SANS instruments, has been found insufficient and not very well adapted for most modes of operation of D16. Therefore, an update changing order of multiple parameters, and enabling `Gamma` parameter is proposed. 

The contents of this logbook parameters update have been requested and are approved by scientists responsible for D16 instrument.  

**To test:**

1. Tests should be passing
2. Generate logbook using UnitTest or SystemTest data:
- with no optional headers specified, columns should be the following, in order: 
`file_name, SampleDescription, StartTime, Gamma, TotalTime, Attenuator`.

*There is no associated issue.*

*This does not require release notes* because it does not add any new feature but only re-orders currently present parameters that should be added to the logbook for D16 instrument.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gemmaguest** [comment]
I can't get this to work - it still uses the original column headings. Looks like it's still using the original parameter file but I can't see how - if I load a D16 file it uses the correct one.

**Comment by darominski** [comment]
> I can't get this to work - it still uses the original column headings. Looks like it's still using the original parameter file but I can't see how - if I load a D16 file it uses the correct one. The changes look fine though. I've unassigned myself because this might just be me not using it correctly.

Thanks for looking into this. i guess what you see could be if you have a cache with some earlier version of D16 IPF, perhaps in your $HOME/.mantid/instrument/geometryCache? If you still wanted to retry, cleaning up the cache should help fix it.

**Comment by gemmaguest** [comment]
> 
> Thanks for looking into this. i guess what you see could be if you have a cache with some earlier version of D16 IPF, perhaps in your $HOME/.mantid/instrument/geometryCache? If you still wanted to retry, cleaning up the cache should help fix it.

No, it's still not working. Very confusing!!

**Review by gui-co — APPROVED** [review]
This is properly working on unit test data on my computer. The header of the output table workspace corresponds to the specifications.

**Comment by DannyHindson** [comment]
I've just merged this - I noted Gemma's comments that it wasn't working for her but the risk of breaking anything else seems low looking at the changes so happy to go with the ILL team's approval

**Pull request merged**
