### PR TITLE
Run *.png through zopfli lossless compression

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**
Runs all png files through zopfli lossless compression with the most
intense settings:
find -iname *.png -print0 | xargs -0 -n 1 -P12 -I{} zopflipng -y --iterations=500 --filters=01234mepb --lossy_transparent {} {}

This reduced the size of the repo from 106MB for 63MB as determined by:
find . -type f -iname '*.png' -exec du -ch {} + | grep total$

This will directly reduce the package size by this amount too, as LZMA
and similar compression methods don't attempt to re-compress png usually

**To test:**
- Build docs locally / open Mantid
- Check that a random selection of icons / screenshots and images open correctly

There is no associated issue - Completed as I already had the script to hand for a personal project

*This does not require release notes* because the compression is lossless and therefore transparent

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by sf1919 — DISMISSED** [review]
To be honest I think this is squashing the information into ever smaller areas and creating lots of whitespace. Below is an example of a page from a recent Nightly (23/09/21).
Screenshot (44)
 
Compare this with the same page when viewed on this PR
Screenshot (43)

It's especially bad where images are embedded in with text around like this.

For reference these images are taken from a Windows 10, non-4k laptop screen. I haven't had a chance to try this on a 4K laptop but there are already issues with the help pages that have been raised before (I don't think #29979 was ever resolved & just went stale). I will therefore also try and get this tested on 4k.

**Comment by DavidFair** [comment]
Locally these render correctly, and checking the metadata with exiftool we've preserved the height and width :confused: 
@sf1919 Could you try a local build of master (not this branch) to see if it lays out correctly? I'm trying to determine if it's a local issue or some tag is being used by Sphinx in Windows

**Comment by sf1919** [comment]
@DavidFair Building on master also produced the squashed look (see second image above) so perhaps it is just local settings?

**Review by StephenSmith25 — APPROVED** [review]
Looks good to me. Tested the docs-html and qt helps docs and everything looks fine.

**Pull request merged**
