### PR TITLE
Update to C++ 20 standard

### LINKED ISSUE #37841: Update to C++20
Update to the current version of the C++ standard (C++20). This will enable us to use newer features and allow us to remove some dependencies that have now been implemented in C++.

### PR DESCRIPTION
**Pull request by jclarkeSTFC**
Update to C++ 20

A few things needed fixing to remove compilation errors and warnings:

- `requires` is now a keyword so we can't use it as a variable name
- The function in `Plot.cpp` that used `std::move` to return generated a warning for an unnecessary move
- The accumulate functions in `MultiFileNameParser.cpp` didn't compile unless they returned by value
- Ambiguous overload for `==` operator (`bool == Mantid::API::Boolean`) in `FindClusterFacesTest`
- Ambiguous == (`WeightedEvent == TofEvent`) in `EventListTest`
- Stricter class template checking meant remove `<T>` in `TableWorkspaceTest`
- `constexpr char*` now needs to be `constexpr const char*`
- Made `HKL` namespace explicit to avoid ambiguity
- `shared_ptr::unique` no longer exists, `use_count()==1` is closest equivalent
- Stricter rules around templated classes resulted in the need to make equality comparisons clearer for the compiler
- Changed some `char*` to `std::string` in a couple of methods

For the `cmake` variable see [here](https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html)

For more C++ 20 info see [here](https://en.cppreference.com/w/cpp/20)

Fixes #37841

### To test:

*This does not require release notes* because **it should have no effect on the user**

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by jclarkeSTFC** [comment]
I think this is good to go, but the Windows build machines need updating in order to compile C++ 20. E.g. on my laptop I can compile with `msbuild` no problem.

**Comment by peterfpeterson** [comment]
[`git cherry-pick 7cca3f1a7c58dceb3cef674a633e55a385e44bbc`](https://github.com/mantidproject/mantid/pull/37870/commits/7cca3f1a7c58dceb3cef674a633e55a385e44bbc) will fix your windows build issue

**Comment by jclarkeSTFC** [comment]
> [`git cherry-pick 7cca3f1a7c58dceb3cef674a633e55a385e44bbc`](https://github.com/mantidproject/mantid/pull/37870/commits/7cca3f1a7c58dceb3cef674a633e55a385e44bbc) will fix your windows build issue

Thanks!

**Comment by jclarkeSTFC** [comment]
Looks like there are more instances of Windows unhappy with missing headers, I'll go through and add them

**Review by jhaigh0 — APPROVED** [review]
Builds with no problems on my linux machine. CI test show it is working on all operating systems

**Pull request merged**
