### PR TITLE
Fixing property name that violates the standards

### PR DESCRIPTION
**Pull request by raquelalvarezbanos**
Fixes trac issue [#11087](http://trac.mantidproject.org/mantid/ticket/11087).

For tester: check that code follows standards now and that system tests pass

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
Jenkins, retest this please

**Comment by martyngigg** [comment]
The *fedora-20-build* failed due to a git error that is most likely a problem on the machine. The other builds/tests are happy and the changes look fine. I will run the system tests locally to be sure.

**Comment by martyngigg** [comment]
The system tests are happy now :+1:

**Comment by raquelalvarezbanos** [comment]
Ok, thanks Martyn

**Pull request merged**
