### PR TITLE
Give up data search early when the isis archive service is unavailable.

### LINKED ISSUE #12520: Mantid becomes unresponsive if data archive service is unavailable
To reproduce:

Start MantidPlot and make sure that the "Search Data Archive" box is ticket in "Manage User Directories" and remove all other paths. Click Load and type SANS2D28584 into the box. While it is trying to find the file click the browse button and select another file. MantidPlot will then become unresponsive.

Anton was also seeing something similar with the SANS interface and understands how to recreate it.

### PR DESCRIPTION
**Pull request by mantid-roman**
Fixes #12520 

It not that easy to test the fix as the service is OK at the moment. For development I set up a fake service on localhost.

### CODE REVIEW

**Comment by mantid-roman** [comment]
It's not working on linux.

**Comment by martyngigg** [comment]
@mantid-roman This has been open for a long time. Is it still relevant?

**Comment by mantid-roman** [comment]
@martyngigg Probably not any more.

**Comment by martyngigg** [comment]
Okay, please close it leaving it unmerged.

**Pull request closed without merging**
