### PR TITLE
Indirect - Fitting - ExtractQENSMembers Algorithm

### LINKED ISSUE #21648: Indirect - ConvolutionFitSequential - ExtractMembers cannot be used for functions which aren't 1 or 2 Lorentzian
The routine for extracting members from a fit in the ConvolutionFitSequential algorithm, produces the following error when attempting to extract members from any fit, excluding 1 and 2 Lorentzian fits:
```
Error in execution of algorithm ConvolutionFitSequential
Number of members is incorrect.
Got error from algorithm "ConvolutionFitSequential"
Stopping batch algorithm because of execution error
```

### PR DESCRIPTION
**Pull request by brandonhewer**
Currently, the routine for extracting the fit members from QENS fitting is done within the ConvolutionFitSequential algorithm. This routine only accounts for a delta function and 1/2 Lorentzian fits and is only accessible within the ConvolutionFitSequential algorithm.

This PR moves this routine into a separate algorithm 'ExtractQENSMembers', which extracts the members from a QENS fit (once processed with the ProcessIndirectFitParameters algorithm). This algorithm will extract fit members from any fit type and can also be used with the output of other Indirect Fitting algorithms (e.g. IqtFit).

**To test:**
1. Navigate to Interfaces > Indirect > Data Analysis > ConvFit
2. Provide the supplied \*\_red file into the Sample field.
3. Provide the supplied \*\_res file into the Resolution field.
4. In the drop-down menu select 'One Lorentzian'.
5. Check the check-box labelled 'Delta Function'.
6. Ensure the check-box labelled 'Extract Members' is checked.
7. Click 'Run'.
8. Ensure a group workspace labelled '_Members' is created.
9. Ensure '\*\_Data', '\*\_Calc', '\*\_Diff',  '\*\_DeltaFunction' and '\*\_Lorentzian' workspaces are contained within the members group workspace.
10. Run the unit tests in ExtractQENSMembersTest and ensure they pass.

**Test Files:**
[ConvFit.zip](https://github.com/mantidproject/mantid/files/1678824/ConvFit.zip)

Fixes #21648. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by MatthewBowles — APPROVED** [review]
Works as described, looks fine. Should be good to go once the tests pass.

**Comment by martyngigg** [comment]
@brandonhewer There seems to be a consistent unit test failure.

**Comment by brandonhewer** [comment]
@martyngigg Thanks for the update Martyn, this issue now appears to be fixed

**Review by martyngigg — COMMENTED** [review]
Can I ask whether there was a request for a separate algorithm to do this? This seems highly tied to how ConvolutionSequentialFit works?

**Comment by SpencerHowells** [comment]
@martyngigg  It will be used by ConvFit & IqtFit in the first instance. It could potentially be used by any fitting routine using more then 1 component.

**Comment by SpencerHowells** [comment]
@martyngigg The user who suggested extracting members would also want to run the algo independent of the gui

**Comment by martyngigg** [comment]
@SpencerHowells Thanks.

**Pull request merged**
