### PR TITLE
Basic documents of fitting function minimizers

### LINKED ISSUE #15014: Documentation for fitting minimizer
Add code to allow adding rst document for fitting minimizers, in the same way to as is done for rst documentation for fitting functions. 

For this issue it is sufficient to include rst pages for 

Simplex
SteepestDescent
Conjugate gradient (Fletcher-Reeves imp.)
Conjugate gradient (Polak-Ribiere imp.)
BFGS (Broyden-Fletcher-Goldfarb-Shanno)
Levenberg-Marquardt (default)

borrowing e.g. text from http://docs.mantidproject.org/nightly/concepts/FittingMinimizers.html. Note the above listed minimizers are all from GSL, hence these minimizers have to reference this fact.

Have rst minimizer documentation show up below 'Fit Functions' on http://www.mantidproject.org/Documentation

Further minimizer rst pages may be created in seperate issues

### PR DESCRIPTION
**Pull request by KarlPalmen**
A new folder has been created for fitting function minimizer documents and some short documents for minimizers have been added

**To test:**

Build the HTML documents. The go to the FittingMinimizers in Concepts. Verify that seven of the minimizers list there link to short documents in a new folder for fitting function minimizers.
Check that each of these documents links to a Wikipedia page describing the algorithm.
Also check that all links are OK.

Build QTHELP and test the Mantid help for the information already described.

Fixes #15014 .

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
In the description of the issue, there is a sentence:

"Note the above listed minimizers are all from GSL, hence these minimizers have to reference this fact."

Could we add this sentence to each rst file to reflect the fact that the implementation of these algorithms is based on the GSL (GNU Scientific Library) library?

Also, in each .rst file, could we add a link to http://docs.mantidproject.org/nightly/concepts/FittingMinimizers.html saying that a comparison of the different minimizers can be found?

**Comment by KarlPalmen** [comment]
While adding the further information, I checked the code of each minimizer to see whether it uses GSL and that I have documented do. The code for GaussNewton was hard to find. Thank you @mantid-roman for telling me it has the name of DampingMinimizer.

**Comment by raquelalvarezbanos** [comment]
I am building the documentation like this:

```
./bin/MantidPlot -xq docs/runsphinx_qthelp.py
```

and I can see the new entry in the index page:

index

However, when I click on `Fit Minimizers` the new page is empty and there is no list with the seven minimizers. If I open each individual file, for instance `/home/raquel/mantid/mantid-build/docs/qthelp/fitminimizers/BFGS.html` I can see the link to Wikipedia, the link to GNU and the link to the comparison of minimizers. All the links work.

**Comment by raquelalvarezbanos** [comment]
Looks good. All links are working now.
:shipit:

**Pull request merged**
