### PR TITLE
Optimise handling of locations tag in IDF parsing

### LINKED ISSUE #10904: Improve handling of locations tag in IDF parsing
This ticket is blocks :  [TRAC10063](http://trac.mantidproject.org/mantid/ticket/10063)

In http://trac.mantidproject.org/mantid/ticket/9860 I had a look at profiling the instrument loading code as it's never been done and I was curious as to what it spends a lot of its time doing.

I came across the ```InstrumentDefinitionParser::convertLocationsElement``` function and found that it seems as if the implementation first creates the XML that would have been in the file without the ```locations``` tag and then parses this.

Can we improve this by simply creating the new elements directly in C++ rather than converting to and from XML again?

 - - - - 
Keywords: Maintenance

### PR DESCRIPTION
**Pull request by eXeC64**
Fixes #10904

Loading `LET00014305` went from 21.92s to 12.98s on my machine for these changes.

**Testing**: There should be no change in behaviour, only performance.

### CODE REVIEW

**Comment by eXeC64** [comment]
Loading LET could in theory become much quicker, but not without discarding POCO::XML. Internally, `appendChild` calls `insertBefore`, which creates and dispatches an event every time it is called. The event is created on the heap using `new`, and placed inside a `Poco::AutoPtr`. Lots of time is wasted on the allocation & dellocation of thousands of these events when inserting thousands of new elements, such as is done with a `<locations>` tag.

The more I use Poco's XML library, the more dubious I am of its performance. It simply does not seem to provide an efficient way to create thousands of nodes in one go.

**Comment by martyngigg** [comment]
I think we'd have to prototype another library to see what it can do rather than just dumping it straight out of the box without any idea of what benefit we will get from moving, given the work it would entail.

I'll discuss this with Nick and the TSC to see what people think.

**Comment by martyngigg** [comment]
Could you merge master in to the branch. I think the failing system test is fixed there but I want to be sure.

**Comment by martyngigg** [comment]
@eXeC64 The changes look good - all of the definitions using `<locations>` elements have seen a speed up. Could you add a small piece to the [release notes](http://www.mantidproject.org/ReleaseNotes_3_5_Framework_Changes) under performance?

**Pull request merged**
