### PR TITLE
Tidy 6.6 Release Notes Index

### LINKED ISSUE #35158: Finish off 6.6 `index.rst`

### PR DESCRIPTION
**Pull request by cailafinn**
**Description of work.**
Adjusted the formatting and the grammar of the 6.6 release notes. 

**To test:**
1. Build the docs and check the notes look right in the html files and in qthelp within workbench. 

Fixes #35158 

*This does not require release notes* because **recursion error**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by MialLewis** [comment]
Should you remove the "still under construction" warning here?

**Review by MialLewis — CHANGES_REQUESTED** [review]
LGTM, provided we don't get want to remove the "in progress" warning.

**Comment by gemmaguest** [comment]
Should this be going into `release-next`?

**Comment by ConorMFinn** [comment]
> LGTM, provided we don't get want to remove the "in progress" warning.

I think we want to keep it around for now. [The website posts the notes from `main`](https://docs.mantidproject.org/nightly/release/), so this one appears at the top. We want to keep the warning until the release is properly out.

**Review by MialLewis — APPROVED** [review]

**Pull request merged**
