### PR TITLE
Indirect - Calculate Monte Carlo Absorption - Ensure Plot Result functions in the same manner as Calculate Paalman Pings

### LINKED ISSUE #22026: Indirect - Absorption Corrections - Plot Result option in Calculate Monte Carlo Absorption inconsistent with Calculate Paalman Pings
In the ```Interfaces > Indirect > Corrections Calculate Monte Carlo Absorption``` interface, the ```Plot Result``` option does not function as intended (should provide the option to plot Result in Wavelength, Angle or Both). This is currently inconsistent with the existing result plotting in the Calculate Paalman Pings interface.

### PR DESCRIPTION
**Pull request by brandonhewer**
In the Interfaces > Indirect > Corrections Calculate Monte Carlo Absorption interface, the Plot Result option does not function as intended (should provide the option to plot Result in Wavelength, Angle or Both). This is currently inconsistent with the existing result plotting in the Calculate Paalman Pings interface.

This PR modified the Calculate Monte Carlo Absorption interface, such that the Plot Result feature functions in the same manner as the Calculate Paalman Pings interface.

**To test:**
1. Navigate to ```Interfaces > Indirect > Corrections > Calculate Monte Carlo Absorption```.
2. Provide the supplied irs26176* file into the ```Sample``` field.
3. Check the check-box labelled ```Use Container``` and provide the supplied irs26173* file.
4. Change the ```Sample Height```, ```Sample Width```, ```Sample Thickness```, ```Container Front Thickness``` and ```Container Back Thickness``` spinners to 0.1.
5. Enter ```H20``` into the ```Sample Details > Chemical Formula``` field.
6. Enter ```Al``` into the ```Can Details > Chemical Formula``` field.
7. Click ```Run```.
8. Select the ```Wavelength``` in the ```Plot Result``` drop-down menu and click ```Plot```, ensure the output is plot and then close the plot.
9. Select ```Angle``` in the ```Plot Result``` drop-down menu and click ```Plot```, ensure a time bin plot of the output is created and then close the plot.
10. Select ```Both``` in the ```Plot Result``` drop-down menu and click ```Plot```, ensure both of the two previous plots are created.

Fixes #22026. 

**Release Notes** 
Changes have been added to the release notes.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by LamarMoore — CHANGES_REQUESTED** [review]
The DeltaE plot option doesn't seem to be working. I am testing on Windows 10.

**Comment by SpencerHowells** [comment]
@brandonhewer @LamarMoore There shouldn't be a deltaE plot

**Comment by brandonhewer** [comment]
@SpencerHowells The output of the Calculate Monte Carlo Absorption is in the same units as the input - the workspaces in this example are in ```DeltaE``` - the produced corrections are also output in ```DeltaE```. Should this plot type still be ```Wavelength```?

**Comment by NickDraper** [comment]
Yes, I see the same thing on Windows 7 with DeltaE not working, Also I see no Wavelength option (just DeltaE, Angle or Both).

When you plot angle the window of the plot is named, but if you plot both they are graph 1 and graph 2

Also a point on the instructions "H20" is 20 Hydrogens, a previously unknown structure of Hydrogen, there could be a nature paper in this!

**Comment by SpencerHowells** [comment]
@brandonhewer PP is in wavelength which is what I want for both

**Comment by brandonhewer** [comment]
@LamarMoore Test outline updated (H20 was a mistake -- thanks for spotting this @NickDraper!) and necessary changes have been been.

**Comment by brandonhewer** [comment]
@LamarMoore After clarifying with @SpencerHowells, the workspace in fact needs to be converted into units of wavelength before plotting -- I will implement this conversion.

**Comment by LamarMoore** [comment]
The option to plot the wavelength now appears and I am able to plot a the graph, however it seems like the expected sample chemical formula is `H20` (H-Twenty) as opposed to `H20`- H two O. Also seeing the issues @NickDraper mentioned, if both plots are shown separately they have specific window titles, however when both are plot at the same time the second graph has the window title `Graph 1`. Finally, the graph of Angle and Wavelength plotting options yield graphs with identical titles, is that supposed to be the case?

**Comment by brandonhewer** [comment]
@LamarMoore 

- For the first issue, I've updated the PR instructions (which were incorrect previously) to specify H2-O in order to enter H two O.
-  I cannot seem to replicate the issue by which the second graph is given the name "Graph 2" (on Windows 10).
- Control over plotting from C++ doesn't seem to allow for controlling the names of the plots - they are simply given the name of the plotted workspace. Currently plots from C++ are created by executing a string containing python code.

**Review by LamarMoore — APPROVED** [review]

**Pull request merged**
