### PR TITLE
Fix end run time for GenerateEventsFilter

### PR DESCRIPTION
**Pull request by ghost**
**Description of work**

This is to address an issue where `GenerateEventsFilter` was unable to determine the correct run end time. 
The run end time will now correctly be determined by 
1. `Run.endTime()`
2.  Last proton charge log time
3.  Last event time

**To test:**
New tests have been added to `GenerateEventsFilterTest.h` these test can be ran
``` ctest -R GenerateEventsFilterTest```

All other existing tests should pass. 

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by peterfpeterson — CHANGES_REQUESTED** [review]
You forgot to [add release notes](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html). This is a bugfix in my opinion.

Otherwise I think this is good to go.

**Comment by sf1919** [comment]
pre-commit.ci run

**Comment by thomashampson** [comment]
pre-commit.ci run

**Comment by thomashampson** [comment]
pre-commit.ci run

**Comment by bolotovskyr** [comment]
Can [this clause](https://github.com/mantidproject/mantid/blob/ewm1482_correctEndTime/Framework/Algorithms/src/GenerateEventsFilter.cpp#L1800-L1807) be moved to [LogManager::endTime()](https://github.com/mantidproject/mantid/blob/ewm1482_correctEndTime/Framework/API/src/LogManager.cpp#L163)? Then both `FilterByTime` and `GenerateEventsFilter` could use it.

**Review by peterfpeterson — APPROVED** [review]

**Review by peterfpeterson — APPROVED** [review]

**Pull request merged**
