### PR TITLE
Minor bugs and enhancements in Direct inelastic reuction

### PR DESCRIPTION
**Pull request by abuts**
This addresses issues mentioned in http://trac.mantidproject.org/mantid/ticket/11397

### CODE REVIEW

**Comment by abuts** [comment]
it is certainly the failure not related to the ticket. But...

**Comment by abuts** [comment]
Jenkins, retest this please

**Comment by abuts** [comment]
java errors are irrelevant

**Comment by abuts** [comment]
Jenkins, retest this please

**Comment by abuts** [comment]
now it is something with the data

**Comment by abuts** [comment]
Jenkins, retest this please

**Comment by abuts** [comment]
Something strange happening with this build. It looks finished on Jenkins and all builds finished but it is shown as running in here.

**Comment by abuts** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
All looks fine. I also run all the ISIS system tests locally and there were no issues.

**Comment by FedeMPouzols** [comment]
Related to this, the option to FileFinder to skip directories has just been merged: #435

**Pull request merged**
