### PR TITLE
Add a CMakeLists.txt to the repository root

### PR DESCRIPTION
**Pull request by martyngigg**
This fixes trac [#10898](http://trac.mantidproject.org/mantid/ticket/10898)

**Tester**
The changes here are to prepare for adding in support for CMake's ExternalData mechanism. This requires that the test data be underneath a top-level CMakeLists within the project. It is also helps when building the project as a developer isn't confused as to where cmake should point. 

This was a big enough piece of work to warrant it being done standalone before making changes to the data.

**Note**: It will require that the build directory be deleted and created from scratch as the layout is different to before.

### CODE REVIEW

**Comment by martyngigg** [comment]
retest this please

**Comment by martyngigg** [comment]
retest this please

**Comment by eXeC64** [comment]
retest this please

**Comment by eXeC64** [comment]
There appears to be a conflict in `Code/Mantid/Build/Jenkins/buildscript`.

**Comment by martyngigg** [comment]
This turned out not to be viable for the current build structure. Building the visual studio solution with some directory layouts will not work as the paths are too long. Another approach will be taken in http://trac.mantidproject.org/mantid/ticket/10869

**Pull request closed without merging**
