### PR TITLE
Move interfaces out of scripts folder

### LINKED ISSUE #32369: Investigate moving interfaces out of the scripts folder
## Describe the outcome that is desired.

Move the scientific interfaces out of the scripts folder into a folder within the qt directory.

## Does the outcome relate directly to a problem? Please describe.

It doesn't make sense to have interfaces in the scripts folder. The scripts folder is part of a framework build, which doesn't include mantidqt. The interfaces are dependent on mantidqt, so shouldn't be bundled into a framework build or install of mantid. 

## Describe any solutions you are considering

Move the interfaces into a python package defined in `qt/scientific_interfaces/python/NAME_OF_PACKAGE`

```
├── qt/scientific_interfaces/python
│   ├── scientific_interfaces (name of the python package)
│          └── __init__.py
│          └── Muon
│          └── ..
│   └── setup.py
```
Contents of setup.py
```
setup(
    name='scientific_interfaces',  # This is likely not a good name for a python package unless we are restricted to internal usage. 
    install_requires=['mantidqt'],
    version=os.environ['MANTID_VERSION_STR'],
    packages=find_packages(exclude=['*.test']),
    package_data={'': ['*.ui']},
)
```

Imports from a scientific interface are changed to
`from Muon.GUI.` goes to  `from scientific_interfaces.Muon.GUI`

We'll have to add `qt/scientific_interfaces/python` to the python path, e.g. through one of the .pth files.

## Questions:

1) Does the structure make sense?
2) Is scientific_interfaces a good package name? For internal use it makes sense, but if somebody conda installed or pip installed mantid a package called scientific_interfaces feels a bit ambiguous.
3) Where do we install the interfaces as they are no longer in the installed scripts folder. Do they go in `plugins/python`?

### PR DESCRIPTION
**Pull request by StephenSmith25**
**Description of work.**
This PR moves the interfaces out the scripts folder. There are too many changes to look at with the file changed view, so it will be easier to check the commits.
Implements the design from #32369 
```
├── qt/python
│   ├── mantidqt (this folder contains our mantidqt python package the folder name is not important)
│          └── setup.py # setup file for our mantidqt project
│          └── mantidqt # folder containing mantdqt sources
|                  └── __init__.py 
|                  └── ....
│   ├── mantidqtinterfaces (this folder contains our mantid interfaces python package - the folder name is not important)
│          └── setup.py # setup file for our mantidqtinterfaces project
│          └── mantidqtinterfaces  # folder containing mantid_interfaces sources
│                  └── __init__.py 
|                  └── ....
```

Another change is the mantid.properties file no longer has the location to the interface launch scripts. Instead it is found by checking the module path (to mantidqtinterfaces).

Currently there are two interfaces which haven't been moved:

- Sans (More complex folder structure, not straightforward which things should be pulled out). I don't want to move things about and have the changes un-reviewable (due to how many changes are already in this PR).

**To test:**

- Builds and tests pass
- Checkout the PR. The folders of interest are:
  - qt/python/mantidqtinterfaces
  - scripts/
  - qt/python/mantidqt
- Check the files in these folders seem logical
- Check interfaces open.

Fixes #32369  

*This does not require release notes* because it is an internal change

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gvardany** [comment]
Just to let you know, there is currently a PR open https://github.com/mantidproject/mantid/pull/32059 which does a large refactor of the drill interface. We should coordinate the move, as otherwise it will result in a huge conflict. Unfortunately, that PR has still one issue, if we manage to solve it quickly, it would be better if you merge it in before moving the folder.

**Comment by StephenSmith25** [comment]
Thanks for letting me know, I'll wait for those changes before moving the drill interface then

**Comment by gvardany** [comment]
After further investigation, I decided to unblock #32059.  It is merged now, you can go ahead and move that.

**Comment by StephenSmith25** [comment]
Great, thanks for letting me know.

**Comment by gvardany** [comment]
Drill is OK.

**Comment by sf1919** [comment]
The Muon Analysis GUI has had a tab disabled. The PR for that was merged in this morning - https://github.com/mantidproject/mantid/pull/32411

**Comment by RichardWaiteSTFC** [comment]
Engineering Diffraction UI looks OK

**Comment by StephenSmith25** [comment]
> The Muon Analysis GUI has had a tab disabled. The PR for that was merged in this morning - #32411

This change won't be reflected here yet, as this is on master. Be we may need to be careful once we merge this and try merge in release-next.

**Comment by StephenSmith25** [comment]
@AnthonyLim23 / @robertapplin / @sf1919 could one of you verify that EA, FDA and Muon Analysis open as expected. I haven't encountered any issues, it would just be good to have confirmation. @peterfpeterson could you verify the ORNL guis. Then that should be everything covered.

**Comment by sf1919** [comment]
I've checked
- Muon Analysis
- Frequency Domain Analysis
- Elemental Analysis
- ALC

And all seem to work fine.

**Comment by AndreiSavici** [comment]
PyChop, DgsPlanner, Q-E coverage, TofConverter look OK

**Review by martyngigg — APPROVED** [review]

**Comment by gvardany** [comment]
I still observe this 2 directories with identical content, is this expected ?
```qt/python/mantidqt/widgets``` and ```qt/python/mantidqt/mantidqt/widgets/```

**Comment by StephenSmith25** [comment]
> I still observe these 2 directories with identical content, is this expected ?
> `qt/python/mantidqt/widgets` and `qt/python/mantidqt/mantidqt/widgets/`

Are you sure these aren't empty folders containing just the __pycache__ files? If not I'll have to have another look, as I thought I solved this.

**Comment by gvardany** [comment]
Right, those in `qt/python/mantidqt/widgets/` were indeed empty folders with just pycache files. Those in ` qt/python/mantidqt/mantidqt/widgets` seem to be the actual ones. But the widgets were not supposed to be moved, right?

**Comment by StephenSmith25** [comment]
Correct, the mantidqt package is identical to what it was before. Just moved up one directory so we can define two python packages in the qt/python folder.

**Pull request merged**
