### PR TITLE
Stop StartX and EndX Going Beyond Limits Of The Data In ALC Baseline Modelling

### LINKED ISSUE #30442: ALC Baseline Modelling Interface StartX/EndX Bug
**Original reporter:** Stephen Cottrell / ISIS

### Expected behavior
You should not be able to move startx/endx beyond first and last good data limits, which is the current case for the general fitting window in workbench

### Actual behavior
You can move the limits beyond first and last which doesn't make sense for the fit and can result it not being able to drag them anymore without manually resetting them

### Steps to reproduce the behavior
1. Open ALC
2. Load some data (HIFI71480-500)*
3. Change log to field_main
4. Change max time to 12
5. Load data
6. Go to baseline modelling interface
7. Add polynomial fit function n=2
8. Add a section
9. Drag startx and endx beyond the first and last data values
10. This should not be possible
11. Click fit
12. You might now have one of the markers not be able to be dragged anymore

*Reduced amount of data used in beta test

### Platforms affected
all

### PR DESCRIPTION
**Pull request by Matt-Cumber**
**Description of work.**
In the baseline modelling interface of the ALC, prevent the section markers from going beyond the limits of the data

**To test:**
1. open ALC
2. Load some data
3. Go to baseline modelling
4. Add a section
5. Drag section markers and check they stay within limits of the data

Fixes #30442 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
make sure it passes the workflow from this PR https://github.com/mantidproject/mantid/pull/23381

**Comment by Matt-Cumber** [comment]
> make sure it passes the workflow from this PR #23381

Thanks will have a look now

**Comment by DannyHindson** [comment]
@Matt-Cumber - I just noticed this PR says "not actually ready for review" in the description. Is that still true? I'll unassign myself if yes

**Comment by Matt-Cumber** [comment]
> @Matt-Cumber - I just noticed this PR says "not actually ready for review" in the description. Is that still true? I'll unassign myself if yes

Sorry Danny, yes it is ready for review. I accidentally left that in, thanks for pointing it out

**Review by DannyHindson — DISMISSED** [review]
Have tested and works as described. Looks good

**Comment by Matt-Cumber** [comment]
> Have tested and works as described. Looks good

I've fixed the merge conflict and reworded the release note

**Review by DannyHindson — APPROVED** [review]

**Comment by martyngigg** [comment]
Can I just double check that the workflow in #23381 has been checked?

**Comment by Matt-Cumber** [comment]
> Can I just double check that the workflow in #23381 has been checked?

I did check this, which is what led to the confusion of the PR not being ready. It looked okay to me

**Pull request merged**
