### PR TITLE
Reflectivity rework

### PR DESCRIPTION
**Pull request by mdoucet**
To test: check that the system tests pass for both RefLReduction and LiquidsReflectometryReduction.

### CODE REVIEW

**Comment by peterfpeterson** [comment]
retest this please

**Comment by mdoucet** [comment]
retest this please

**Comment by mdoucet** [comment]
retest this please

**Comment by peterfpeterson** [comment]
This new algorithm makes me wonder if we should expose `WorkflowAlgorithm` to python so more abilities are available.

**Pull request merged**
