### PR TITLE
Add sub groups to fit sequential output in Muon Analysis

### LINKED ISSUE #21826: Grouping of sequential multiple fits
The Muon users want different grouping for the output of sequential multiple fits. I have asked if they want: 

1. The outputs to be added to the relevant grouped workspace (so you will not get a sequential workspace)
2. A sequential group workspace with multiple group workspaces inside, containing only the outputs of the fit (covarience matrix, parameters and workspace)

personally I think 1 is the better solution

### PR DESCRIPTION
**Pull request by ElliotAOram**
This issue covers a reorganisation of the output of Muon Analysis fit sequential functionality.
The output workspaces should now be organised into sub group workspaces.

**To test:**

* Open the Muon Analysis interface (Interfaces > Muon > Muon Analysis)
* Select the instrument as `EMU` from the drop down menu
* Use input of `20717` as the run number in the `Load run` box (the run should load automatically)
* Select the `Data Analysis` tab from the top of the interface
* Right click the FitFunction property tree and select `Add function`
* Select any function
* Click the `Fit` drop down menu and select `Sequential fit`
* Add `20` to runs field so it reads `20717-20`
* Click start 
* Close the Sequential Fitting dialog
* Expand the MounSeqFit_Label workspace group
  * Ensure this is populated by 4 workspace groups
  * Each of these groups should consist of a:
     * `..._NormalisedCovarianceMatrix`
     * `..._Parameters`
     * `..._Workspace` 

Fixes #21826

**Release Notes** 
*Small change - no need for release notes*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by AnthonyLim23 — CHANGES_REQUESTED** [review]
code looks good. But I found 2 bugs. 

1. If you do a sequential fit with multi fitting turned off, then the label name is ignored

2. If you do a sequential fit in multi fitting mode (on MUSR 68389) then only the covariance matrix is stored correctly

**Comment by ElliotAOram** [comment]
@AnthonyLim23 thanks I'll look into that now

**Comment by ElliotAOram** [comment]
@AnthonyLim23 I think this is now working for the cases I know about. Would you be able to check other use cases as I'm not sure if my changes have had knock on affects to other modes of operation I don't know about!

**Comment by AnthonyLim23** [comment]
behaves as expected. Just need to fix the failing tests and add to the release notes

**Comment by ElliotAOram** [comment]
@AnthonyLim23 I've removed the renaming of the workspaces for now and just left in the original grouping change. Given how the unit tests are written currently, I would have to change quite a few tests which it is probably unwise to do so close to a release! Perhaps this is a good job for maintenance (providing its require by users)

**Comment by AnthonyLim23** [comment]
it no longer works for multiple fits as some of the workspaces are not grouped

image

**Comment by ElliotAOram** [comment]
@AnthonyLim23 I think this is working now!

**Review by AnthonyLim23 — APPROVED** [review]

**Comment by AnthonyLim23** [comment]
all works now

**Pull request merged**
