### PR TITLE
Fix goniometer to use time average instead of mean

### LINKED ISSUE #23666: Investigate time series filtering for goniometer angle for WISH
Pascal has noted that setting the goniometer angle using the `SetGoniometer` algorithm using the time series log in workspace gives him the wrong value. 

Our working hypothesis is that it is taking the average of the time series, but what WISH want is the last value of the angle. 

I have some data files for testing with for this which I can put on the ISIS shared network.

### PR DESCRIPTION
**Pull request by samueljackson92**
**Description of work.**
WISH users reported that they were seeing a slight discrepancy in angle reported by `SetGoniometer` where they were expecting it to use the time averaged value of the angle rather than the mean of log entries.

Basically they have one huge value where they moved it at the beginning or end of the run and using the mean skews the resulting angle value. See screenshot below for an example:

screen shot 2018-10-08 at 17 35 11

**Report to:** Pascal Manuel

**To test:**
 - There is a new test case that reproduces the issue.
 - Check that this now sets the correct angle. A good example for WISH is 41612 from cycle_18_1.

Fixes #23666 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by peterfpeterson — DISMISSED** [review]
Time-average makes more sense for lots of logs.

**Comment by VickieLynch** [comment]
Do not merge yet. With SNS data we only have goniometer logs at the beginning of the run when the goniometer may still be moving. Usually the last setting is the most reliable which is not what I got with time-averaged.

**Comment by peterfpeterson** [comment]
@VickieLynch Please comment on an example (TOPAZ) run that shows the issue with `omega`. It is something that needs to be solved in either `LoadNexusLogs` or the math for calculating the time average.

**Comment by samueljackson92** [comment]
Looks like this is also affects the results of `HYSPECReductionTest`
http://builds.mantidproject.org/job/pull_requests-rhel7/24021/

**Review by VickieLynch — COMMENTED** [review]
This looks right for TOPAZ data with the log added at end of run.  Please remove the warnings "To set to last angle, replace omega with -99.058999999999997: SetGoniometer(Workspace='workspace',Axis0=omega,0,1,0,1',Axis1='chi,0,0,1,1',Axis2='phi,0,1,0,1')"

**Comment by samueljackson92** [comment]
@VickieLynch great. I'm not so sure about removing the warnings though. They still seem informative if you actually meant to set it to the last angle?

**Review by AndreiSavici — APPROVED** [review]
Looks OK

**Comment by VickieLynch** [comment]
phi_topaz-32377

**Review by VickieLynch — APPROVED** [review]
Works well for TOPAZ data

**Pull request merged**
