### PR TITLE
Fix some issues with FABADA minimizer

### LINKED ISSUE #17258: Fix minor issues with FABADAMinimizer
Some points about the algorithm should be modified to:
- Ensure the output PDFs resemble the real ones (ensure Algorithm ergodicity)
- Avoid false convergences (all parameters should converge in the same iteration)
- Implement ties

This has been written by BartomeuLlopis

### PR DESCRIPTION
**Pull request by raquelalvarezbanos**
Code implemented by Bartomeu Llopis.

**To test:**

Tests should pass. This will be tested by scientists.

Fixes #17258

Release notes have been updated.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
How will the testing be done by the scientists? Will it be part of the beta testing after merger or will it be done before this PR is recommended for shipping?

**Comment by raquelalvarezbanos** [comment]
@KarlPalmen It will be part of the beta testing

**Comment by KarlPalmen** [comment]
Code review shows three functions have more than 100 lines: `initialize` has 177 lines,  `iterate` has 110 lines and `finalize` has 306 lines.

**Comment by KarlPalmen** [comment]
I'd have it shipped for beta testing, if a maintenance issue to clean the code is created and mentioned here.

**Comment by KarlPalmen** [comment]
I've created issue #17509 to clean up the code and so please :shipit: for beta testing.

**Review by martyngigg — APPROVED** [review]
Given the maintenance issue has been created I'll accept these changes as they stand so they can be beta tested.

**Pull request merged**
