### PR TITLE
Indirect - Bayes - Remove Fit option from plot result menu in Bayes ResNorm interface

### LINKED ISSUE #20063: Indirect - Bayes ResNorm - Fit option no longer needed in plot options
In the Bayes ResNorm indirect interface, the plot options drop-down menu no longer requires 'Fit. This has been moved to plot current preview.

### PR DESCRIPTION
**Pull request by brandonhewer**
The fit option has been remove from the plot result drop-down menu in the indirect Bayes ResNorm interface.

**To test:**
1. Navigate to Interfaces > Indirect > Bayes.
2. Ensure the ResNorm tab is open in the Bayes interface.
3. Click on the 'Plot Result' drop-down menu.
4. Ensure there is no 'Fit' option in the drop-down menu.

Test File:
[irs26173_graphite002_red.zip](https://github.com/mantidproject/mantid/files/1189966/irs26173_graphite002_red.zip)

Fixes #20063. 

**Release Notes** 

Added the change to the release notes.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by AnthonyLim23 — COMMENTED** [review]
I need to check that the doc compiles correctly but otherwise looks good.

I will test everything tomorrow morning.

**Comment by AnthonyLim23** [comment]
Could you please suggest some data to load? The data have trued has the output options greyed out, I assume its because it is the wrong kind of data.

**Comment by SpencerHowells** [comment]
@AnthonyLim23 @brandonhewer Data for this is iris26173_graphite002_red. Should be in the system.

**Comment by brandonhewer** [comment]
@AnthonyLim23 I have added a test file in the description.

**Review by AnthonyLim23 — APPROVED** [review]
fit is not present as described. :shipit:

**Pull request merged**
