### PR TITLE
Cleanup reflectometry release notes

### PR DESCRIPTION
**Pull request by backmari**
### Description of work

This PR does some cleanup for the Reflectometry release notes so they are ready for the release of Mantid v6.9.

### To test:

Read through the Reflectometry release notes to make sure they make sense/no typos.

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by rbauststfc** [comment]
Sorry, I know this isn't ready for review yet as there are still failing tests, but in case it hasn't been noticed yet, these notes don't seem to include the release note from PR #36400.

**Comment by backmari** [comment]
@rbauststfc Hmm do you mean the release note about adding SaveISISReflectometryORSO? If you expand the whole file you can see it under "New Features". But if something is missing please let me know!

**Comment by rbauststfc** [comment]
Ah, sorry, I hadn't spotted that - that looks good then, thanks @backmari!

**Comment by robertapplin** [comment]
Thanks Marie, looks good to me! @rbauststfc @cailafinn @jclarkeSTFC is there any image you think would be good to add to the Reflectometry release notes?

**Comment by rbauststfc** [comment]
Thanks @robertapplin and @backmari, feel free to use this image to demonstrate where to find the new ORSO file format in the ISIS Reflectometry GUI, if you think it would help:

refl_save_orso_option

Otherwise the GUI changes for Reflectometry are minimal this time.

**Comment by backmari** [comment]
@rbauststfc Thank you! I think this is very helpful. I will add it under the release note for the algorithm.

**Review by rbauststfc — APPROVED** [review]
All looks good to me, thanks very much for pulling these together!

**Pull request merged**
