### PR TITLE
Patch hb2a gss out

### PR DESCRIPTION
**Pull request by Kvieta1990**
**Description of work.**

This is to solve the issue with `HB2AReduce` algorithm, when trying to save the reduced data into GSAS format. Without this fix, the `HB2AReduce` GUI will crash, complaining about not being able to find the `OutputWorkspace` name.

**To test:**

Launch `HB2AReduce` algorithm and put in an example run as shown below,

110495184-43891480-80c2-11eb-9616-36203d05c1fe

Click on the `Run` button and check the specified output directory to see whether the data is saved properly.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by jmborr** [comment]
Can you also open another PR against `ornl-next`?

**Comment by jmborr** [comment]
One question: did your branch `Kvieta1990:patch-hb2a-gss-out` branched off `mantidproject:master` or `mantidproject:ornl-next`?

**Comment by Kvieta1990** [comment]
> One question: did your branch `Kvieta1990:patch-hb2a-gss-out` branched off `mantidproject:master` or `mantidproject:ornl-next`?

ornl-next

**Comment by Kvieta1990** [comment]
> Can you also open another PR against `ornl-next`?

sure, but I see one of the tests failed. Not sure whether this is caused by my new implementation, though. Any thoughts?

**Comment by Kvieta1990** [comment]
> Can you also open another PR against `ornl-next`?

PR to `ornl-next` opened:

https://github.com/mantidproject/mantid/pull/31155

**Comment by jmborr** [comment]
> > Can you also open another PR against `ornl-next`?
> 
> sure, but I see one of the tests failed. Not sure whether this is caused by my new implementation, though. Any thoughts?

[this failure](https://builds.mantidproject.org/job/pull_requests-rhel7/43002/) is unrelated to your changes. Sometimes the builds fail and in that chance one just "retries" the builds. In order to retry, one must login to the Jenkins build servers:



If you don't have an account, I can take retry any failing build.

**Review by jmborr — APPROVED** [review]
Workbench test works as expected

**Comment by jmborr** [comment]
@rosswhitfield @peterfpeterson Can any of you merge this?

**Comment by Kvieta1990** [comment]
> > > Can you also open another PR against `ornl-next`?
> > 
> > 
> > sure, but I see one of the tests failed. Not sure whether this is caused by my new implementation, though. Any thoughts?
> 
> [this failure](https://builds.mantidproject.org/job/pull_requests-rhel7/43002/) is unrelated to your changes. Sometimes the builds fail and in that chance one just "retries" the builds. In order to retry, one must login to the Jenkins build servers:
> 
> 
> 
> If you don't have an account, I can retry any failing build.

I don't have an account for that, so it will be very nice of you if you can help with that @jmborr

**Comment by Kvieta1990** [comment]
> @rosswhitfield @peterfpeterson Can any of you merge this?

@jmborr @peterfpeterson @rosswhitfield It will be very nice if any of you can help reviewing the same PR to `ornl-next` and merge that. Thank you so much for that! Here is the PR to `ornl-next`: [https://github.com/mantidproject/mantid/pull/31155](https://github.com/mantidproject/mantid/pull/31155)

**Pull request merged**
