### PR TITLE
11315 topaz live listener

### PR DESCRIPTION
**Pull request by rgmiller**
This was originally [trac ticket 11315](http://trac.mantidproject.org/mantid/ticket/11315).

Adds a new live listener class useful for the TOPAZ beamline at SNS.  Minor changes to the StartLiveListener GUI dialog and Facilities.xml.

### CODE REVIEW

**Comment by peterfpeterson** [comment]
The OSX one is an actual issue. You increased the number of llvm compiler warnings.

**Comment by VickieLynch** [comment]
Just tested at the TOPAZ hutch running ConvertToMD and it works well

**Comment by peterfpeterson** [comment]
The windows warning got stale enough for the build details to go away. I merged master into the branch to see the message again (and fix it).

**Comment by peterfpeterson** [comment]
I'm merging based on Vickie's testing.

**Pull request merged**
