### PR TITLE
Lock aspect ratios

### LINKED ISSUE #13466: Aspect ratios
Leads on from #12185. When that is done, we can then use the isQUnit query on each `MDUnit` via the `MDFrame` to set the SliceViewer up correctly.

Looks like the QwtPlotRescaler is the correct thing to use for this. You need to use the setReferenceAxis call to pick the first (and track) the qDimension of the plot. For other qDimensions can then set the aspect ratios via the QwtPlotRescaler. When dimensions are remapped in the SliceViewer, we must update the QwtPlotRescaler::setReferenceFrame accordingly. 

To keep things simple, for the time being, we will not distinguish between q dimensions represented in r.l.u vs those in A^-1.

**Running the example from ConvertToMD (below) we should find that the output workspace when viewed in the SliceViewer has fixed aspect ratios for any combination of the first 3 dimensions, and variable aspect ratios if the Energy axis is plotted with any other.**
```python
import os
# set up target ws name and remove target workspace with the same name which can occasionally exist.
# list of MD files (workspaces) to combine into target MD workspace
MD_FilesList='';

# define convetr to MD parameters
pars = dict();
pars['InputWorkspace']=''
pars['QDimensions']='Q3D'
pars['dEAnalysisMode']='Direct'
pars['Q3DFrames']='HKL'
pars['QConversionScales']='HKL'
pars['PreprocDetectorsWS']='preprDetMantid'
pars['MinValues']='-3,-3,-3.,-50.0'
pars['MaxValues']='3.,3.,3.,50.0'
pars['SplitInto']=50
pars['MaxRecursionDepth']=1
pars['MinRecursionDepth']=1
pars['OverwriteExisting']=1  # Change this to false, if the files should/can be added in memory
# test script combines all contributed files in memory
pars['OverwriteExisting']=0  # Change this to false, if the files should/can be added in memory
#
#---> Start loop over contributing files
for n in xrange(0,5,1):
     source_file = 'MER19566_22.0meV_one2one125.nxspe'; # redefine source files list as function of loop number
     target  = 'MDMAP_T1'+str(n)+'.nxs';
     # check if the file already been converted to MD and is there
     if not(os.path.exists(target )):
         print 'Converting ',source_file
         #current_ws=LoadNXSPE(Filename=source)
         #### For the sample script, simulate load operation above
         current_ws = CreateSimulationWorkspace(Instrument='MAR',BinParams=[-3,1,3],UnitX='DeltaE',OutputWorkspace=source_file)
         AddSampleLog(Workspace=current_ws,LogName='Ei',LogText='3.0',LogType='Number')

         #### Add iformation which is not stored in the nxspe file
         # Add UB matrix (lattice and the beam direction)
         SetUB(Workspace=current_ws,a='1.4165',b='1.4165',c='1.4165',u='1,0,0',v='0,1,0')
         # Add crystal rotation (assume rotation abgle Psi=5*n where n is file number. Define list of angles if this is not correct
         AddSampleLog(Workspace=current_ws,LogName='Psi',LogText=str(5*n)+'.',LogType='Number')  # --correct Psi value may be already in nxspe file. This operation is then unnecessary
         # set crystal rotation
         SetGoniometer(Workspace=current_ws,Axis0='Psi,0,1,0,1')

         # Convert to MD
         pars['InputWorkspace']=current_ws;
         md_ws=ConvertToMD(**pars)

         # save MD for further usage -- disabled in test script
         #SaveMD(md_ws,Filename=target);
         #DeleteWorkspace(md_ws);  # delete intermediate workspace to save memory
         DeleteWorkspace(current_ws);

     # add the file name of the file to combine
     if (len(MD_FilesList) == 0):
         MD_FilesList = target;
     else:
         MD_FilesList=MD_FilesList+','+target;
#---> End loop

# merge md files into file-based MD workspace
#md_ws = MergeMDFiles(MD_FilesList,OutputFilename='TestSQW_1.nxs',Parallel='0');
# plot results using sliceviewer
#plotSlice(md_ws)
# produce some test output
print "Resulting MD workspace contains {0} events and {1} dimensions".format(md_ws.getNEvents(),md_ws.getNumDims())
#print "MD workspace ID is:\n",md_ws.id
print "--------------------------------------------"
```

### PR DESCRIPTION
**Pull request by OwenArnold**
Fixes #13466. 

Aspect ratios can be locked in the SliceViewer.
- Run the script in #13466
- open the SliceViewer with the output md_ws
- Go to the View menu of the SliceViewer, and ensure that `Lock Aspect Ratios` is selected
- Now if you plot any Q dimension in the plot (i.e x = H,0,0 and y = 0,L,0) the aspect ratios should be fixed.
- Now change one of the dimensions (either x, or y) to be the dE axis. The aspect ratios are now not fixed.
- Unselect the menu option for locking the aspect ratios. All aspect ratios should be unfixed. (This is what the SliceViewer used to do by default). 
- Open and close the SliceViewer, the menu option previously selected should be remembered.

### CODE REVIEW

**Comment by OwenArnold** [comment]
The RHEL6 build is breaking because there is no QwtPlotRescaler in the 5.0 version of Qwt. This PR cannot be merged until that problem is fixed. @stuartcampbell  is looking into that problem.

**Comment by martyngigg** [comment]
What's the reason we don't lock the aspect ratio regardless of the dimension selection? Naively it seems counter intuitive that the *Lock Aspect Ratios* option is selected but for the case of `DeltaE` as an axis then that doesn't apply.

Also a minor point about the menu option - if I unselect the aspect ratio option then resize the plot so that aspect ratio is wrong and reselect the *Lock Aspect Ratios* option the plot is not updated automatically, I have to interact with it. Should we force an update of the image in this case?

**Comment by OwenArnold** [comment]
@martyngigg : I've updated this Issue as per your comment above.

**Comment by martyngigg** [comment]
This looks better now.

There still seems to be a slight issue with the image not updating after an aspect ratio change but I've opened another #13580 to look into that.

**Pull request merged**
