### PR TITLE
Make all FqFit functions available in FqFitTab

### PR DESCRIPTION
**Pull request by Harrietbrown**
Previously when in single fit FqFit tab would change the avialable functions based on if EISF or width was loaded, now with only multiple we want all functions available regardless.

**To test:**

1. Open Indirect Data Analysis FqFit
2. Check that the fit functions available contain EISF functions as well as width functions.
3. load width data.
4. check that width funtions fit to the data
5. load EISF data.
6. check that EISF function fit to the data.
7. load both types and check that all functions are still available and can run even if the fit is not good.

*There is no associated issue.*

*This does not require release notes* because **It fixes an issue introduced in this release**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by SpencerHowells** [comment]
@Harrietbrow Single input had lists dependent on Width or Eisf.

**Comment by SpencerHowells** [comment]
@Harrietbrown Single input had lists dependent on Width or EISF

**Comment by Harrietbrown** [comment]
We have talked about this Spencer, in single input there was a combo box that switched between Width and EISF, multiple does not. we agreed that implementing that into multiple inputs would be an inefficient use of develping time.

**Comment by sf1919** [comment]
So I loaded the file ```IN16B_125878_QLd_Result.nxs``` and selected ```EISF``` and ```f3.f3.EISF```. I performed an ```EISFDIffCylinder``` fit - should it look like this?

Screenshot (7)

**Comment by SpencerHowells** [comment]
@sf1919 That may not be an appropriate file for testing - I don't recognise it.. Try this one
[iris26176_graphite002_red_Conv_seq_1LDelta_0-17__Result.zip](https://github.com/mantidproject/mantid/files/6862885/iris26176_graphite002_red_Conv_seq_1LDelta_0-17__Result.zip)
Load FWHM & Fit type TeixieraWater - should give good fit. Load EISF & Fit type EISFDiffCyliner - it will not be a good fit because it is the wrong model.

**Review by sf1919 — APPROVED** [review]
I have now tested this with several files and an satisfied the changes work as expected and the Fits do work on the appropriate files. I have also looked at the code and can see no issues. I therefore approve this PR.

**Pull request merged**
