### PR TITLE
Loader for ILL's reflectometer polarization efficiencies

### PR DESCRIPTION
**Pull request by soininen**
This PR adds a new loader `LoadILLPolarizationFactors` to Mantid's data handling algorithms. The loader can parse the IDL-formatted polarization efficiency files used at the D17 instrument at ILL.

**To test:**

The branch includes a single efficiency file which can be used for testing: `<mantid-build-directory>/ExternalData/Testing/Data/UnitTest/ILL/D17/PolarizationFactors.txt`. The loader also needs a reference workspace for the X axis. The following script might help getting started:

```python
ws = CreateSampleWorkspace()
ws_in_wavelength = ConvertUnits(ws, Target='Wavelength')
f = LoadILLPolarizationFactors('ILL/D17/PolarizationFactors.txt', ws_in_wavelength)
```

This is the first step towards closing #20962.

**Release Notes** 

A *Reflectometry* page was added to the release notes and updated accordingly.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
image
 workspace seems to load ok, although it is not particularly interesting.

**Comment by NickDraper** [comment]
The Loader seems to not be filling out a number of things that we would expect to be completed.

- Title
- X Axis & unit
- Y axis
- Instrument
- Run Start
- Run End

You will know more than me about what if anything would best be put into these fields, but currently they are all blank.

**Review by NickDraper — CHANGES_REQUESTED** [review]
See my comment about missing fields in the workspace

**Comment by NickDraper** [comment]
image

**Comment by soininen** [comment]
@NickDraper I assume you have normalization to bin width turned on in your plots. The four factors loaded from the file are ideally 1 (F1 and F2) or 0. There is something going on with P1 and P2 for X > 15, if you want to see more than flat lines.

Adding X and Y units is a good idea, as well as the workspace title. The efficiencies are measured for D17 instrument. However, by themselves, they are instrument agnostic so I left the instrument field blank. Further, run start and end are not stored anywhere.

**Review by NickDraper — APPROVED** [review]

**Pull request merged**
