### PR TITLE
Fix calibration bug in LoadIsawPeaks for CORELLI

### LINKED ISSUE #19297: calibration input/output for CORELLI
### Expected behavior
LoadIsawPeaks should load calibration for CORELLI
### Actual behavior
LoadIsawPeaks has default instrument for CORELLI
### Steps to reproduce the behavior
LoadIsawPeaks for CORELLI peaks that used LoadIsawDetCal

### PR DESCRIPTION
**Pull request by VickieLynch**
Description of work.
Calibration for peaks file is now is applied correctly for CORELLI geometry.
**To test:**
```python
LoadIsawPeaks(Filename='42357_Niggli.integrate', OutputWorkspace='test')
SaveIsawPeaks(InputWorkspace="test",Filename='42357.integrate')
```
https://www.dropbox.com/s/bt6qsox7xxq1lph/42357_Niggli.integrate?dl=0
Compare input and output files
Fixes #19297

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by VickieLynch** [comment]
When the peaks are combined, the calibration information from the first orientation is used for the merged peaks file.  There could be banks that have no peaks in the first orientation, but have peaks in the others.  I made the change to include the calibration information for all banks in instrument instead of banks containing peaks so there may be more lines in the header information of the files.

**Comment by rosswhitfield** [comment]
Just in case you missed it the `SaveIsawPeaks` doctest failed.

**Comment by rosswhitfield** [comment]
LGTM :shipit: once the builds pass.

**Comment by VickieLynch** [comment]
Feng just tested and extra calibration lines cause problems in anvred3.py. Will rollback SaveIsawPeaks changes or remove unused banks.

**Comment by rosswhitfield** [comment]
Still good. :shipit:

**Pull request merged**
