### PR TITLE
Fixing compiler warning in gcc>4.4

### PR DESCRIPTION
**Pull request by peterfpeterson**
**To test:** If it builds, then it is tested.

This does not need to be in the release notes.

### CODE REVIEW

**Comment by rosswhitfield** [comment]
clang-format isn't enforced on `*.tcc` files but can you please add the `\\ clang-format off/on` [e.g](https://github.com/mantidproject/mantid/blob/master/Framework/PythonInterface/mantid/api/src/Exports/IMaskWorkspace.cpp#L8-L10) to prevent this happening in the future.

**Comment by peterfpeterson** [comment]
@rosswhitfield: Why isn't it needed on https://github.com/mantidproject/mantid/blob/master/Vates/VatesAPI/test/BoxInfoTest.h#L51 ?

**Comment by rosswhitfield** [comment]
It is but clang-format has never been run on those files. Only the '.h|.cpp' files in Framework do we enforce it. Maybe we should extend it to the rest of Mantid.

**Comment by peterfpeterson** [comment]
Maintenance task!

**Pull request merged**
