### PR TITLE
fix issue in load wand data caused by deprecated h5py syntax

### PR DESCRIPTION
**Pull request by Kvieta1990**
**Description of work.**

Fixing deprecation warnings in `LoadWAND`  from h5py syntax `.value` and replace with `[()]`.

Run this test. Ensure that no `.value` warnings are printed. Test on Python 3.11.`
**To test:**
```python
silicon = LoadWAND(IPTS=7776,RunNumbers='26506,26507') # silicon
```

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by zjmorgan** [comment]
I just made a couple changes. Your fixed worked perfectly fine, I just made the syntax slightly simpler and now it is just like `LoadWANDSCD`.

**Comment by Kvieta1990** [comment]
> I just made a couple changes. Your fixed worked perfectly fine, I just made the syntax slightly simpler and now it is just like `LoadWANDSCD`.

Thank you so much for the change!

I realized that my other PR to `release-next` was originated from the wrong branch (the `main` branch as in current PR). I will submit another one and will let you know the link to that new PR. Thank you!

**Review by zjmorgan — APPROVED** [review]
Works as expected.

**Comment by martyngigg** [comment]
#34436 has the same set of changes for `release-next` so it's fine that the release notes are in the 6.5 section.

**Pull request merged**
