### PR TITLE
Concepts file names normalised

### PR DESCRIPTION
**Pull request by NickDraper**
ticket

http://trac.mantidproject.org/mantid/ticket/11321
## To test
1. check that the file names now are PascalCase universally
2. check that links between the concepts still work
3. Check that the index still works and looks good

### CODE REVIEW

**Comment by NickDraper** [comment]
Changed files are available as a list on the ticket, with old and new file names

**Comment by NickDraper** [comment]
jenkins test this please

**Comment by NickDraper** [comment]
jenkins wake up and test this please

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please.

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please.

**Comment by FedeMPouzols** [comment]
I just saw by chance a warning from sphinx/LaTeX:

`12:45:42 WARNING: inline latex u"\\mathbf{h}' = \\mathbf{W}_i^{-1}^T \\cdot \\mathbf{h}\n\n": latex exited with error`

`12:45:42 ! Double superscript.
12:45:42 <argument> ...t}\mathbf {h}' = \mathbf {W}_i^{-1}^
12:45:42                                                   T \cdot \mathbf {h}\end {s...
12:45:42 l.16 \end{gather}
12:45:42                  
12:45:42 ! Double superscript.
12:45:42 <argument> ...t}\mathbf {h}' = \mathbf {W}_i^{-1}^
12:45:42                                                   T \cdot \mathbf {h}\end {s...
12:45:42 l.16 \end{gather}
12:45:42                  `

I think this was there before http://docs.mantidproject.org/nightly/concepts/Point_groups.html), but it could be fixed as part of this ticket.

**Comment by NickDraper** [comment]
Yes I saw that too, it is nothing to do with this change.

**Comment by NickDraper** [comment]
But I put a fix in for the latex math error anyway, the error was in point groups, and gave a huge error box on the page, you couldn't miss it.

**Comment by martyngigg** [comment]
This looks much better now.

**Pull request merged**
