### PR TITLE
35798 remove importlib_resources pin, simplify SimulatedDensityOfStates - Euphonic systemtest

### LINKED ISSUE #35798: Remove importlib_resources pin
**Describe the outcome that is desired.**

To fix a failing `euphonic` system test, `Testing/SystemTests/tests/framework/SimulatedDensityOfStatesEuphonicPackaging.py`, `importlib_resources` has been pinned to `5.12.0`.

Given that `euphonic` is now on `conda-forge`, it is thought that this system test could no longer be needed.

If @ajjackson agrees, the test and pin needs to be removed.

### PR DESCRIPTION
**Pull request by ajjackson**
**Description of work**

Closes #35798

**Purpose of work**
When Euphonic was an optional dependency, a systemtest was used to temporarily install the library and check it was integrated correctly. The machinery for this seems to have caused some CI failures, which were  temporarily fixed by pinning the version of `importlib_resources`.

As Euphonic is now a "proper" dependency this machinery is not needed and we can simply run a normal systemtest. In turn this allows the pin to be removed.

**Summary of work**
Remove temporary installation of Euphonic from relevant systemtest, rename accordingly, remove unnecessary libarary version pin

**To test:**

Systemtests should run succesfully

*This does not require release notes* because **there is no direct impact on end-users**

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by sf1919** [comment]
pre-commit.ci run

**Comment by thomashampson** [comment]
pre-commit.ci run

**Comment by ajjackson** [comment]
Strange error. The input validation for ForceConstantsFile is failing, presumably because `not euphonic_available()`. It passes locally, but of course that is on my dev setup. I'll need to put some hacks into the test to get more information back from the CI.

**Comment by ajjackson** [comment]
Aha! The issue is not the test itself; the old version of Euphonic pinned for Mantid really does need to use an old version of `importlib_resources`. This bit of code has been modernised in newer Euphonic releases.

I could add this pin to the conda-forge package for Euphonic 0.6.5, which is where it should really live.

It feels like time better-spent bringing a newer Euphonic version to Mantid, though!

**Comment by ajjackson** [comment]
Closing this PR as not the right approach, another one to follow.

**Pull request closed without merging**
