### PR TITLE
GSASIIRefineFitPeaks use multiple phase files

### LINKED ISSUE #21521: GSASIIRefineFitPeaks needs to handle multiple phase files
The algorithm `GSASIIRefineFitPeaks` is only set up to use one phase (`.cif`) file for refinement. However, it turns out that it is often useful to use multiple phase files, so this should be allowed in the algorithm

### PR DESCRIPTION
**Pull request by josephframsay**
`GASIIRefineFitPeaks` has been updated to be able to use multiple phase files during refinement.

**To test:**

**Make sure GSASIIRefineFitPeaks system test passes**

You'll need GSAS-II installed. Install it using one of the scripts in `scripts/GSAS-II` or follow the instructions [here](https://subversion.xray.aps.anl.gov/trac/pyGSAS).

Run the following script (replace the marked variables with your GSAS-II installation directory and the name of a new GSAS-II project file, which will be created by the algorithm)
```
import os

# Replace this
path_to_gsas = "path/to/directory/containing/GSASIIscriptable.py"

data_dir = r"\\olympic\Babylon5\Public\JoeRamsay\GSASIIRefineFitPeaks"

ws_path = os.path.join(data_dir, "ENGINX_280625_focused_bank_1.nxs")
spectrum = Load(Filename=ws_path, OutputWorkspace="ENGINX_280625_1")

# Replace this
gsas_proj_file = "somewhere/local/MultiPhaseTest.gpx"

phase_files = ",".join(os.path.join(data_dir, "Fe", "Fe-{}.cif".format(phase)) 
                       for phase in ["alpha", "epsilon", "gamma"])

iparams_file = os.path.join(data_dir, "template_ENGINX_241391_236516_North_bank.prm")

GSASIIRefineFitPeaks(RefinementMethod='Rietveld refinement',
                     InputWorkspace=spectrum,
                     InstrumentFile=iparams_file,
                     PhaseInfoFiles=phase_files,
                     PathToGSASII=path_to_gsas, 
                     LatticeParameters='params', 
                     SaveGSASIIProjectFile=gsas_proj_file, 
                     OutputWorkspace="FittedPeaks",
                     XMin=10000, XMax=40000)
```

Overplottng `FittedPeaks` on `ENGINX_280625_1` should give you a reasonable fit:
capture

Fixes #21521 

**Release Notes** 
No scientists were aware that this feature was missing, and it should have been in there from the start, so not added to the release notes

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by ElliotAOram** [comment]
@josephframsay the change we made in the previous PR re. `xmin > xmax` validation breaks this script as (assuming because xmin/xmax are not specified) .
Can you have a look what's behind this?

**Comment by ElliotAOram** [comment]
image

**Comment by josephframsay** [comment]
@ElliotAOram apologies for that: add `XMin=10000, XMax=40000` to the parameters list (a la the updated script in the instructions), and crack on as normal

**Review by ElliotAOram — COMMENTED** [review]
Looks good and I get a pretty good fit - just going to check the tests run okay locally then we're good to go!

image

**Review by ElliotAOram — APPROVED** [review]
After a bit of prodding GSAS, tests pass locally 👍

**Pull request merged**
