### PR TITLE
New LoadSavuTomoConfig algorithm

### PR DESCRIPTION
**Pull request by FedeMPouzols**
This addresses ticket [#10889](http://trac.mantidproject.org/mantid/ticket/10889).

This algorithm loads a 'tomography reconstruction pipeline' configuration/settings file in the format used by the savu tool (https://github.com/DiamondLightSource/Savu) and produces a table workspace with a row per plugin/processing step.

Tester:
- Review code.
- The algorithm comes with a unit test and a doc test, make sure that those are fine.
- You can also test it manually/interactively, using the example file used for the tests, or any of the process??.nxs files found from here https://github.com/DiamondLightSource/Savu/tree/master/test_data.
- The input files are NeXus files. So if you really want to check all the details, you can compare what this algorithm loads with what you see with tools like hdfview or similar.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
Jenkins retest this please

**Comment by FedeMPouzols** [comment]
Jenkins retest this please

**Comment by FedeMPouzols** [comment]
Jenkins retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please.

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please.

**Comment by FedeMPouzols** [comment]
Jenkins, could you retest this please?

**Comment by FedeMPouzols** [comment]
Jenkins, could you test this please?

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please

**Comment by FedeMPouzols** [comment]
Jenkins, retest this please.

**Comment by raquelalvarezbanos** [comment]
Works as expected. Code, unit tests and user example well documented. Still some TODOs that will be addressed in future work.

**Pull request merged**
