### PR TITLE
Merge Changes From Rob and Richard for ISIS SANS

### PR DESCRIPTION
**Pull request by PeterParker**
Fixes trac issue [#11360](http://trac.mantidproject.org/mantid/ticket/11360).

**To tester**

These are changes given to us by Rob Dalgliesh and Richard Heenan, which I'm merging for them almost completely "as is".  I have:
- given the code a manual inspection to see that it is sensible;
- fixed a couple of issues that cropped up with the fact that they were using slightly outdated versions of files; and
- fixed broken system tests.

I am submitting this pull request so that I may provide them both with a build which they can use to give the changes a final "once-over" before the cycle starts this week.

For testing purposes, I'd recommend waiting until we hear back from the scientists that the changes are working as they intended, then simply do a code review.

Rob has said that he would like to provide us with system test data / reduction scripts so that we may have LARMOR covered with adequate test coverage.  Having said that, they are very keen on getting something they can use into the nightly builds ASAP, so we will have to do this in a separate ticket at a later date.

### CODE REVIEW

**Comment by PeterParker** [comment]
Jenkins, retest this please.

Win7 build failed with the following:

```
19:36:54 ApplicationWindow-[Notice] Script execution finished.
19:36:54 MantidUI-[Notice] MantidPlot is shutting down...
19:36:56 C:\Jenkins\workspace\pull_requests\label\win7-build\build
19:36:56 Removing package 'C:\Jenkins\workspace\pull_requests\label\win7-build\build\mantid-3.3.20150315.1903-win64.exe'
19:36:56 Traceback (most recent call last):
19:36:56   File "C:\Jenkins\workspace\pull_requests\label\win7-build\Code\Mantid\Testing\SystemTests\scripts\mantidinstaller.py", line 274, in <module>
19:36:56     installer.uninstall()
19:36:56   File "C:\Jenkins\workspace\pull_requests\label\win7-build\Code\Mantid\Testing\SystemTests\scripts\mantidinstaller.py", line 136, in uninstall
19:36:56     self.do_uninstall()
19:36:56   File "C:\Jenkins\workspace\pull_requests\label\win7-build\Code\Mantid\Testing\SystemTests\scripts\mantidinstaller.py", line 165, in do_uninstall
19:36:56     run('start "Uninstaller" /wait ' + uninstall_path + ' /S')
19:36:56   File "C:\Jenkins\workspace\pull_requests\label\win7-build\Code\Mantid\Testing\SystemTests\scripts\mantidinstaller.py", line 87, in run
19:36:56     raise Exception('Returned with code '+str(p.returncode)+'\n'+out)
19:36:56 Exception: Returned with code 1
19:36:56 Access is denied.
```

Which looks very much like an intermittent problem with the builder rather than an issue with the changes made as part of this ticket.

**Comment by PeterParker** [comment]
Jenkins, retest this please

**Comment by PeterParker** [comment]
Jenkins, retest this please

**Comment by PeterParker** [comment]
Jenkins, retest this please.

**Comment by PeterParker** [comment]
This failed again, but now because of RHEL 6 being flaky!.  Pushed a revert of the last two commits to set off yet another build.

**Comment by Anders-Markvardsen** [comment]
Looks good to me

**Pull request merged**
