### PR TITLE
Engg algorithms: Add default values with new list of ceria peaks + other improvements

### LINKED ISSUE #14600: EnggCalibrateFull: set default value for ExpectedPeaks - and other improvements in in/out properties
Set default of `ExpectedPeaks` to the Ceria peaks. This is a tiny change that could be done together with other changes in the Engg algorithms or GUI.
This was requested for EnggCalibrateFull, but the same can be applied to EnggCalibrate as well.

### PR DESCRIPTION
**Pull request by FedeMPouzols**
Fixes #14600.

Adds new default values for the calibration algorithms + a few more improvements listed in the issue.

**To test**:
- Check code and If all tests pass, including new ones.
- See that the properties of the following algorithms are grouped, in their algorithm dialogs: `EnggVanadiumCorrection`, `EnggCalibrate`, `EnggCalibrateFull`, `EnggFocus`, `EnggFitPeaks`. This should make it easier to understand what the algorithms do and how to use them(with the help of their documentation).

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
@shahrozahmed1 : this is a good chance to have a first contact with Engg calibration algorithms so I assigned this to you for testing. It implements several of the small changes that came up in our discussions with Saurabh a couple of weeks ago.

**Comment by FedeMPouzols** [comment]
Current status: fixing issues in a system test.

**Comment by FedeMPouzols** [comment]
I think that after the last commit everything should work well. There was a mismatch between the number of break points used to fit the Vanadium curves in the test and the new (higher) default value.

**Comment by shahrozahmed1** [comment]
New default values have been updated for all calibration algorithms with also detailed documentation provided which should be come in hand for anyone that would utilise these algorithm in future. Tests have also been updated, all tests passes locally on Windows, including `EnggCalibrationTest` system test. This branch is ready to be merged.

**Pull request merged**
