### PR TITLE
ResNorm error with sqw files

### LINKED ISSUE #13620: ResNorm errors with _sqw files as vanadium input
ResNorm should not be able to run with _sqw files which it is currently able to do so in the interface. This needs to be removed from the possible extension options.

### PR DESCRIPTION
**Pull request by ElliotAOram**
Fixes #13620 

ResNorm should no longer accept non `_red` files as input for vanadium and non `_res` files resolution.
# To Test
- Open ResNorm (Interfaces > Indirect > Bayes > ResNorm)
- Attempt to add a file for either the Vanadium or Resolution run
- Ensure that:
  - only `_red` files are valid for Vanadium runs
  - only `_res` files are valid for Resolution runs
    - These files should match e.g. `irs26173_graphite002_red.nxs` and `irs26173_graphite002_res.nxs`
- Run the ResNorm Algorithm (click run in the interface) 
- Ensure that the files validate when run

### CODE REVIEW

**Comment by KarlPalmen** [comment]
I need to know where I can find some _red and _res files.

**Comment by ElliotAOram** [comment]
You can find these in `ExternalData\Testing\Data\SystemTest`
There are 3 `_res` files there (`irs26173`,`irs53664`,`osi97935`)
And these should all have matching `_red` files in the same file location.

**Comment by KarlPalmen** [comment]
Thank you, but owing to a bug in CMAKE, the system test data files are a pain to build (can't be done automatically). So please e-mail me the files or make them available, where I can find them.

**Comment by KarlPalmen** [comment]
I eventually got the system test file built. Test went OK, till I decided to do something stupid and for Vanadium selected all files and then it happily loaded an Event Nexus file.  I then ran it and it did nothing. Then I went back to a _red file, then it crashed when I ran. This I think is outside the scope of this issue, so I pass the testing.

**Comment by ElliotAOram** [comment]
Apologies @KarlPalmen I just this second sent you some files on slack (feel free to now ignore them!)
Thanks for testing this, I will look into the issue you mentioned above. Although I agree it is out of scope it's worth ensuring users can't do the same thing!

**Comment by KarlPalmen** [comment]
I see you've decided to do unscripted testing on the Indirect interface. I suggest you try that in the test when you try to crash it.

**Pull request merged**
