### PR TITLE
Fix transient imports, destroy toolbar on widgetclosed

### LINKED ISSUE #24537: Workbench plot toolbar bug
### Expected behavior
The user must always be able to access the toolbar in the plot window. 

### Actual behavior
The toolbar can be lost forever or detached from the plot and live on its own.

### Steps to reproduce the behavior
1. Right click on an empty space of the toolbar and untick the tick-box with an empty label. The toolbar hides and there is no way (an obvious one at least) to get it back.
2. Grab the toolbar by the handle at its left and drag it out. Then close the plot window. The toolbar remains floating.

### Platforms affected
Observed on windows but it's probably the same for all.

### PR DESCRIPTION
**Pull request by dtasev**
**Description of work.**
A couple of transient imports were detected (draw_if_interactive and show) they were imported in `workbench.plotting.figuremanager` but not used.

The `figuremanager` now destroys the toolbar in the `widgetclose` event, which is called both when user clicks `X`, and when it is `Deleted` from the plot manager. Previously if the user clicked X, the `widgetclose` event was never called, and the toolbar never destroyed, because [this would throw the exception as the comment describes](https://github.com/DTasev/mantid/blob/24537_workbench_plot_toolbar_bug/qt/applications/workbench/workbench/plotting/figuremanager.py#L234), so `Gcf.destroy()` never got executed -> and the toolbar was being deleted in the `destroy` event.

**To test:**
Open a plot, move the toolbar outside the window, close the plot via:
- Clicking X
- Selecting in plot manager and clicking delete

Fixes #24537 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by mantid-roman — CHANGES_REQUESTED** [review]
It crashes for me when I drag out the toolbar then close the plot then trying to close the workbench.

**Comment by martyngigg** [comment]
Interestingly I get a hang for the same set of operations as Roman has described above rather than a crash. This is on Ubuntu 16.04.

**Comment by DTasev** [comment]
👍 I can replicate the issue now, I will have a look

**Comment by DTasev** [comment]
After a brief discussion it was decided that floating the toolbar everywhere was probably not a useful feature, and has been disabled. 

The toolbar can still be moved around the window though.

21f08f7 also merges `_windowclosing` and `destroy` functions, making closing from `X` or via plot list `Delete` (or the X there), always go through the same function `destroy`.

**Comment by mantid-roman** [comment]
Pressing `x` doesn't close the plot any more, just hides it.

**Comment by DTasev** [comment]
I'd missed the call to the global figure manager to destroy the plot - it should work now

**Comment by mantid-roman** [comment]
It is working now.

**Review by mantid-roman — APPROVED** [review]

**Comment by DTasev** [comment]
Found a crash if the workspace is deleted, the plot window's close event is called from the c++ thread, causing a Qt exception, will look into i

**Pull request merged**
