### PR TITLE
Convert elemental analysis to qtpy

### LINKED ISSUE #25333: elemental analysis to pyqt
convert elemental analysis to pyqt

### PR DESCRIPTION
**Pull request by AnthonyLim23**
Convert elemental analysis to qtpy

**To test:**
play with the GUI

Fixes #25333 . 

Does not need to be in release notes
---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Mantid-Matthew** [comment]
This mostly seems to just work :+1:

I do find that if I plot all 4 graphs and then click the home button in the top left one graph is made full size and the others very small. This may be a pre-existing issue however.

**Comment by AnthonyLim23** [comment]
I cannot reproduce it, even on the same branch. Could you please provide more detailed instructions?

**Comment by Mantid-Matthew** [comment]
I can replicate the issue on master on Ubuntu 18 but not on the release build of Mantid on windows so may be an OS specific issue. 

To reproduce on Ubuntu all you need to do is open four plots and then click on the home button

**Comment by AnthonyLim23** [comment]
made an issue #25497

**Review by Matthew-Andrew — APPROVED** [review]

**Pull request merged**
