### PR TITLE
Fix error reporter

### LINKED ISSUE #33219: Soft Crash Error Report does not send
Found in #33200 

**Describe the bug**
The error reporter, generated on a soft crash (workbench doesn't close), will not send with "Yes, share info". This maybe related to the problem stopping the "Show More details" button in the bottom right of the Error Reporter from working.

**To Reproduce**
- Open Workbench
- Load the file Training_Exercise3a_SNS.nxs from the Trainingcoursedata
- Execute the algorithm NormaliseToMonitor
- The error reporter will appear. Try to click Show more details (a pop-up window should appear, but now does not)
- Click "Yes, Share info". It will fail reporting a bad request 400

**Expected behavior**
-Show more details pop-up works and sending error reports with "Yes, Share Info" works too!

**Screenshots**
Screenshot 2022-01-06 at 11 46 47 (2)
 explain your problem. -->

**Platform/Version (please complete the following information):**
 - OS: IDAaaS Centos7 (also found on nightly on Windows)
 - Mantid Version  6.2.20220103.659

### PR DESCRIPTION
**Pull request by thomashampson**
Co-authored-by: Daniel Murphy <DanielMurphy22@users.noreply.github.com>

**Description of work.**

The error reporter was broken because escape characters were being removed from quotes in json strings, so the json parsing failed. This meant that both:
- stack traces (which normally contain `"`s)
- entering a quotation mark in any other fields  (name, email, decription box)
would result in a problem when either:
- clicking the "Show more details" button, or
- clicking the "Yes, share information" button.

We've added tests to ensure that strings with escaped quotes are preserved when converting to json, as well as removing the seemingly unused code that caused the problem.

The lines that we've removed were added in #33056.

**To test:**

1. Soft crash mantid to bring up the error reporter e.g. by doing this:
Load the file Training_Exercise3a_SNS.nxs from the training course data and execute the algorithm `NormaliseToMonitor`
2. Check that the "show more details" button works and displays the stack trace.
3. Check that the error report can be sent by clicking "Yes, share information".
4. Try to send an error report after entering quotation marks in some of the fields.

Fixes #33219 

*This does not require release notes* because it is a bug that was introduced since the last release.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by thomashampson** [comment]
@Kvieta1990 We've removed some changes you made to the JSON helper functions because they broke the error reporter. We couldn't find anywhere in your PR #33056 where the changes were actually being used, and no tests failed when we made the changes.

**Review by martyngigg — APPROVED** [review]
Confirmed that the error report now goes through when sent with additional information. I checked the error reporter admin console and saw the report

**Comment by Kvieta1990** [comment]
@thomashampson `SNSPowderReduction` will break without that part of codes. This has serious effect on data reduction for POWGEN beamline. I have no idea about how it breaks the error reporter but I think simply deleting that part is probably not the best solution.

**Comment by Kvieta1990** [comment]
@thomashampson Here is a bit more context. With that part of codes deleted in the Json helper, when running `SNSPowderReduction` multiple times, it will crash, giving the following error message,

```
Error in execution of algorithm SNSPowderReduction:
Could not create algorithm from history. Is this a child algorithm whose workspaces are not in the ADS?
  at line 515 in '/SNS/NOM/shared/Dev/mantid_zyp/mantid/Framework/PythonInterface/plugins/algorithms/SNSPowderReduction.py'
Failed to execute script: RuntimeError on line 1065 of '/SNS/snfs1/instruments/NOM/shared/Dev/mantid_zyp/mantid/Framework/PythonInterface/mantid/simpleapi.py': SNSPowderReduction-v1: Could not create algorithm from history. Is this a child algorithm whose workspaces are not in the ADS?
  at line 515 in '/SNS/NOM/shared/Dev/mantid_zyp/mantid/Framework/PythonInterface/plugins/algorithms/SNSPowderReduction.py'
Traceback (most recent call last):
  File "/SNS/NOM/shared/Dev/mantid_zyp/mantid/scripts/reduction_gui/reduction/scripter.py", line 665, in on_error
    raise RuntimeError(str(arg))
RuntimeError: RuntimeError on line 1065 of '/SNS/snfs1/instruments/NOM/shared/Dev/mantid_zyp/mantid/Framework/PythonInterface/mantid/simpleapi.py': SNSPowderReduction-v1: Could not create algorithm from history. Is this a child algorithm whose workspaces are not in the ADS?
  at line 515 in '/SNS/NOM/shared/Dev/mantid_zyp/mantid/Framework/PythonInterface/plugins/algorithms/SNSPowderReduction.py'
```

The fundamental reason is that the json history looks like this (without my added codes),

```
{"name":"SNSPowderReduction","properties":{"BackgroundSmoothParams":"5.2","BinInDspace":"0","Binning":"-0.0001","CacheDir":"/SNS/users/y8z/Temp/POWGEN_GUI_Test,/SNS/users/y8z/Temp/POWGEN_GUI_Test,/SNS/users/y8z/Temp/POWGEN_GUI_Test","CalibrationFile":"/SNS/PG3/shared/CALIBRATION/2021_2_11A_CAL/PG3_50338_2021_07_13_PAC_10h_YP.h5","CharacterizationRunsFile":"/SNS/PG3/shared/CALIBRATION/2021_2_11A_CAL/PG3_char_2021_07_16_PAC_limit_1.4MW.txt,/SNS/PG3/shared/CALIBRATION/2021_2_11A_CAL/PG3_char_2021_07_16-HighRes_PAC_1.4MW_newPAC6.txt","Filename":"/SNS/PG3/IPTS-27787/nexus/PG3_51580.nxs.h5","MeasuredMassDensity":"4","OutputDirectory":"/SNS/users/y8z/Temp/POWGEN_GUI_Test","RemovePromptPulseWidth":"50","SampleFormula":"In2-V-O5","SampleGeometry":"{\"Height\":2}","SaveAs":"gsas and fullprof and pdfgetn and topas","TypeOfCorrection":"FullPaalmanPings"},"version":1}
```

where you can see that the `SampleGeometry` part is a nested dictionary, The above history cannot be processed properly and therefore Mantid will crash. With my codes, the above history looks like this,

```
{"name":"SNSPowderReduction","properties":{"BackgroundSmoothParams":"5.2","BinInDspace":"0","Binning":"-0.0001","CacheDir":"/SNS/users/y8z/Temp/POWGEN_GUI_Test,/SNS/users/y8z/Temp/POWGEN_GUI_Test,/SNS/users/y8z/Temp/POWGEN_GUI_Test","CalibrationFile":"/SNS/PG3/shared/CALIBRATION/2021_2_11A_CAL/PG3_50338_2021_07_13_PAC_10h_YP.h5","CharacterizationRunsFile":"/SNS/PG3/shared/CALIBRATION/2021_2_11A_CAL/PG3_char_2021_07_16_PAC_limit_1.4MW.txt,/SNS/PG3/shared/CALIBRATION/2021_2_11A_CAL/PG3_char_2021_07_16-HighRes_PAC_1.4MW_newPAC6.txt","Filename":"/SNS/PG3/IPTS-27787/nexus/PG3_51580.nxs.h5","MeasuredMassDensity":"4","OutputDirectory":"/SNS/users/y8z/Temp/POWGEN_GUI_Test","RemovePromptPulseWidth":"50","SampleFormula":"In2-V-O5","SampleGeometry":{"Height":2},"SaveAs":"gsas and fullprof and pdfgetn and topas","TypeOfCorrection":"FullPaalmanPings"},"version":1}
```

which can then be processed properly.

**Comment by thomashampson** [comment]
@Kvieta1990 I see your problem now. I think in that case it would be good if you could write a test that reproduces it, and attempt to find a solution that doesn't impact on the JsonHelpers. The error reporter needs to be able to have strings that contain double quotes, otherwise the Json parser will fail and it won't be able to deliver any error reports - which is vital. There may be other areas of the code that rely on this too that we're unaware of.

From looking at your json snippet (I've expanded it to help readability), it looks like all of the Json values have been converted to strings. I wonder if this is a wider issue that needs to be looked at?

```
{"name":"SNSPowderReduction"
"properties":{"BackgroundSmoothParams":"5.2"
"BinInDspace":"0"
"Binning":"-0.0001"
"CacheDir":"/SNS/users/y8z/Temp/POWGEN_GUI_Test,/SNS/users/y8z/Temp/POWGEN_GUI_Test,/SNS/users/y8z/Temp/POWGEN_GUI_Test"
"CalibrationFile":"/SNS/PG3/shared/CALIBRATION/2021_2_11A_CAL/PG3_50338_2021_07_13_PAC_10h_YP.h5"
"CharacterizationRunsFile":"/SNS/PG3/shared/CALIBRATION/2021_2_11A_CAL/PG3_char_2021_07_16_PAC_limit_1.4MW.txt,/SNS/PG3/shared/CALIBRATION/2021_2_11A_CAL/PG3_char_2021_07_16-HighRes_PAC_1.4MW_newPAC6.txt"
"Filename":"/SNS/PG3/IPTS-27787/nexus/PG3_51580.nxs.h5"
"MeasuredMassDensity":"4"
"OutputDirectory":"/SNS/users/y8z/Temp/POWGEN_GUI_Test"
"RemovePromptPulseWidth":"50"
"SampleFormula":"In2-V-O5"
"SampleGeometry":"{\"Height\":2}"
"SaveAs":"gsas and fullprof and pdfgetn and topas"
"TypeOfCorrection":"FullPaalmanPings"}
"version":1}
```

**Pull request merged**
