### PR TITLE
Create Stitching tab in Options Dialog for Reflectometry Polref interface 

### LINKED ISSUE #14848: Upgrade Reflectometry Reduction (Polref) Interface for Scaling of LHS Workspace
See the original PR and Issue #14847, whereby a fix has been made to the old UI.

We would like to do the same thing to the new UI. The nice way to do this would be to allow the user to provide the override in the options column, however, the options column is only for the ReflectometryReductionOneAuto properties. Stitching is an optional post-processing step. We need to adapt the UI so that the options column also includes any of the options used for stitching. That way users can specify *ScaleRHSWorkspace=False* in the options column and the LHS workspace will be scaled instead.

### PR DESCRIPTION
**Pull request by MattKing06**
The user can now specify their own Start/End overlaps and Params through the stitching tab as well as choosing to scale the LHS workspace when using Stitch1DMany.

**To test:**
There is a `.tbl` file containing SURF runs [here](https://slack-files.com/T02J4MMEW-F0ST0CPQA-6cf6dbdaf1) which should be used for testing.

**_No Changes**_
- Open the reflectometry interface (`Interfaces > Reflectometry > ISIS Reflectometry (Polref)`)
- Load the SURF nxs file into Mantid
- Load the SURF file into the interface (`Reflectometry > Open Table`)
- Go to the stitching tab (`Reflectometry > Options > Stitching`)
- Ensure that all checkboxes are disabled by default and leave them.
- Click Process and ensure that the stitched workspace has extents that are similar to the QMin and QMax found in the table.

**_Change StartOverlaps**_
- Open the reflectometry interface (`Interfaces > Reflectometry > ISIS Reflectometry (Polref)`)
- Load the SURF .tbl file into the interface (`Reflectometry > Import Table`)
- Go to the stitching tab (`Reflectometry > Options > Stitching`)
- Enable the `StartOverlaps` checkbox and ensure that the LineEdit beneath it is enabled now.
- Enter some 2 startOverlaps, you can base these from the QMin found in the table from the previous case
- Ensure that the stitched workspace has the minimum extent value of the first start overlap you provided.

**_Change EndOverlaps**_
- Open the reflectometry interface (`Interfaces > Reflectometry > ISIS Reflectometry (Polref)`)
- Load the SURF .tbl file into the interface (`Reflectometry > Import Table`)
- Go to the stitching tab (`Reflectometry > Options > Stitching`)
- Disable the `StartOverlaps` checkbox and ensure that the LineEdit beneath it is disabled now.
- Enable the `EndOverlaps` checkbox and ensure that the LineEdit beneath it is enabled now.
- Enter some 2 EndOverlaps, you can base these from the QMax found in the table from the previous case
- Ensure that the stitched workspace has the maximum extent value of the last end overlap you provided.

**_Change Params**_
- Open the reflectometry interface (`Interfaces > Reflectometry > ISIS Reflectometry (Polref)`)
- Load the SURF .tbl file into the interface (`Reflectometry > Import Table`)
- Go to the stitching tab (`Reflectometry > Options > Stitching`)
- Disable the `EndOverlaps` checkbox and ensure that the LineEdit beneath it is disabled now.
- Enable the `Params` checkbox and ensure that the LineEdit beneath it is enabled now.
- Enter some 3 comma separated values e.g "1.0,0.5,2.0", you can base these from the QMin, QMax and DQ/q found in the table from the previous case.
- Ensure that the stitched workspace has the extents value of the first and last values that you entered for your Params.

Fixes #14848 .

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
Matt, now that PR #15670 has been merged, you'll need to resolve the merge conflicts, I can help you with this.

**Comment by raquelalvarezbanos** [comment]
Something seems to be wrong with the interface: when I try to transfer runs to the table the latter is not populated. I think it is because there is a line missing in `ReflMainViewPresenter::transfer()`, the last line should be:

```
m_tablePresenter->transfer(results.getTransferRun());
```

but this line was removed for some reason, maybe when merging master into this branch or when resolving the conflicts.

**Comment by raquelalvarezbanos** [comment]
Just a minor comment: I can't use the surf table because the interface won't accept it as a valid table workspace, it is missing the `Options` column.

If I populate the table manually and save it as a workspace, the saved workspace has this column, and I can load it back into the interface. However, when saving the table workspace as a nexus file, the last column does not seem to be saved, for some reason (maybe because it is empty?)

**Comment by MattKing06** [comment]
This change is no longer needed as we have decided to go with a different approach. see [here](https://github.com/mantidproject/mantid/pull/15943)

**Pull request closed without merging**
