### PR TITLE
35076 q e coverage input validation

### LINKED ISSUE #35076: Q-E coverage input validation
**Describe the bug**
Wrong inputs in Q-E coverage interface can either result in wrong answer or can cause unhandled Mantid error

**To Reproduce**
1. Go to Interfaces->Utility->QECoverage
2. Select instrument HYSPEC. Set s2 to 50 and plot
3. Set s2 to some string, say `test` and plot. This yields the same answer as setting s2 to 0
4. Set Ei to a string. This raises an error message box, but also the Mantid Error report

**Expected behavior**
Just an error message box for steps 3 and 4

**Screenshots**

image

**Platform/Version (please complete the following information):**
 - OS: RHEL 7
 - Mantid Version 6.5.20230123.1825

### PR DESCRIPTION
**Pull request by GuiMacielPereira**
**Description of work**
- Implemented input validation on QECoverage GUI and handled exceptions in a sane way.
- Fixes #35076 

**Purpose of work**
- Avoid Mantid crashing and displaying multiple error windows  due to nonsensical input fields.
- Easily taken care of by setting a Validator to QLineEdit fields.

**Summary of work**
- There are three input fields:
  - Ei, Emin and s2:
  -  image
  - Set a QDoubleValidator for Emin and s2 (to only accept floats)
  - Set a QRegExpValidator to Ei, to personalise input to accept only positive floats separated by commas

**Further detail of work**
- Went over the functions `onClickDirectPlot` and `direct_input_check` and realised the rules for the allowed inputs:
    - Ei must be one or more floats separated by commas
    - All floats in Ei must be positive
    - Emin must be a float (positive or negative)
    - s2 must be a float (positive or negative)
    - If any value of Ei is less than Emin, show warning window and update Emin to `min(Ei)-1`
    - If a value for Emin is not provided, set `Emin = -max(Ei) / 2`
        - Actually, the original version had `Emin = -Ei[0] / 2`, but my version is more universal
        - Emin sets the minimum limit for the QE curves, so the choice is arbitrary anyway
- Added general handling of exceptions
   - If the input of Ei or s2 is invalid (empty space or `+`), nothing happens when clicking to plot. 
   - In the case of invalid s2, when plotting the value will update to the last valid input used.
   - If Emin is invalid, the value will update to `Emin = -max(Ei) / 2`

**To test:**
- Try the default settings first
- Leave the Ei field empty or with just `+` and click to plot. Check that nothing happens
- Add a list of floats to Ei and empty the field Emin. Click to plot and check that Emin gets updated.
- Edit Emin to be bigger than one of the values in Ei. Check that you get a message and the value gets updated.
- Change s2 to an empty field. Click to plot and check that it reverts back to the previous value.
- Change s2 to a different value and check plot changes.
- Try to write letters or other characters in any of the fields. Check this is not possible.
- There are no unit tests for this fix.
- There are not release notes for this fix.

edit:
**Release Notes**
- Added two release notes under Direct and Indirect Geometry
- Built the target `docs-html` and confirmed that links are working and structure looks good

Fixes #35076.
---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by sf1919** [comment]
Looking at this PR I think it will need a release note as it's a bugfix. We have documentation on how release notes work at https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html which should help you write one. Also have a look at some of the other PRs that have release notes for examples of how the separate release notes are stored.

**Comment by GuiMacielPereira** [comment]
The QECoverage tool covers both direct and indirect geometry, so I added the same note under the two directories.
Not sure if this is good practice?

**Review by sf1919 — CHANGES_REQUESTED** [review]
Thank you for making these changes. I have undertaken a functional test and the changes work as expected.  

I have built the release notes and the documentation without errors. All reads well and is in the correct place.

However, whilst this is an excellent way of making sure Mantid doesn't crash from multiple confusing pop ups, I do wonder if we have gone too far the other way. Would it possible to add some logging to replace the pop ups? I think it might be useful for users to understand why the changes they tried to make have not been actioned.

**Comment by GuiMacielPereira** [comment]
I agree, I have now added two warnings to replace the previous pop-up windows.
I also made a slight change to the behaviour of setting Emin when an invalid input is passed, I believe now the default behaviour is better and the warning messages alert the user every time an automatic change has been made when dealing with an invalid input.

**Review by sf1919 — APPROVED** [review]
Thank you for making those changes @GuiMacielPereira . I think this is a nice piece of work. Happy to approve.

**Pull request merged**
