### PR TITLE
PyChop update

### LINKED ISSUE #29965: Extend PyChop GUI to handle arbitrary number of chopper phases
**Original reporter:** G. Sala / SNS

### Actual behavior

Currently, although the PyChop engine supports an arbitary number of choppers with arbitrary number of independent phases, the GUI only supports the user setting _one_ independent phase, with the phases of the other choppers set by the desired incident energy. This behaviour has up to now been acceptable for current instruments but several new instruments proposed for the Second Target Station (STS) of the SNS will have multiple choppers whose phases should be set independently of Ei. 

So, the PyChop GUI should be modified to allow this.

### Platforms affected

All

### PR DESCRIPTION
**Pull request by mducle**
**Description of work.**

Adds handling for arbitrary number of independently phased choppers (issue #29965). This is mostly a GUI issue as the calculation code should have been able to handle this already (although there was a small issue here in parsing the input `yaml` file as it was assuming only a single chopper would be phased independently of the source).

Also some code clean up:

* Add GUI test for the independent phases.
* Remove `raise` exceptions which are not explicitly caught in the code and replace them with error messages
* Refactor some of the code for special handling for Merlin and added a test for this
* Add GUI test for the "enter an Ei value to automatically replot" mode.

**To test:**

Checks that the test passes.

Open PyChop with this instrument (a modification of CNCS):
[cncs_indep.zip](https://github.com/mantidproject/mantid/files/7591307/cncs_indep.zip)

And check that there are labels and edit boxes for "Chopper 1 Phase delay time" and "Chopper 3 Phase delay time" compared with normal CNCS.

Fixes #29965 and #30716 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DanielMurphy22 — CHANGES_REQUESTED** [review]
The new multiple chopper labels and edit boxes work well! 

I've just a few questions, but these are maybe related to the testing cncs_indep.yml file rather than your code change:

- I open PyChop, change instrument to CNCS2 and immediately change either the Resolution disk or Fermi Frequency, then I get an error reporter and PyChop closes. This seems to be due to the `None` default value in the chopper delay times. Maybe these defaults can be set nicely in the yml file!
- Does multi-reps work for this new configuration? I seem to get this error when I try to:
```
Attempting to set identical left==right results
in singular transformations; automatically expanding.
left=0, right=0

WARNING:matplotlib.legend:No handles with labels found to put in legend.
```

**Comment by mducle** [comment]
@DanielMurphy22 Are right... thanks for checking. Yes, I think the issue is converting `None` to string for the edit box and then the guard doesn't work so it tries to convert it to `float`. I should change the code for this. Sorry I was actually testing with a different instrument rather than the CNCS hack but it's good to fix this.

Multirep should work but the problem is that in setting arbitrary phases you might not get any reps through. I'll check what are good values and update.

**Comment by DanielMurphy22** [comment]
> Multirep should work but the problem is that in setting arbitrary phases you might not get any reps through. I'll check what are good values and update.

Do you have good values for multirep to work? Your recent changes look good otherwise!

**Comment by mducle** [comment]
> Do you have good values for multirep to work? Your recent changes look good otherwise!

Ah sorry... for Ei=2 meV, Chopper 1 delay of 12000 us and Chopper 3 delay of 3000 us should work. You can then change it by small amounts and see in the Time-Distance plot that the opening moves along a bit... (the cut off is for Chopper 1 delay less than 11000us and greater than 14000 [ish], and Chopper 2 delay less than 2500 and greater than 3500 [ish]).

**Review by DanielMurphy22 — APPROVED** [review]
Well done, all seems to work for me!

**Pull request merged**
