### PR TITLE
Fix offset problem in CreateSampleWorkspace

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

The code in CreateSampleWorkspace evaluates the user-specified function at the left hand edge of each bin and then writes the resulting y value into the bin. This is misleading and results in functions which are symmetric about 0 appearing slightly asymmetric in the resulting workspace

The unit test\system tests runs in Jenkins have highlighted the fact that the FindEPP algorithm included some logic which was perhaps driven by the old code in CreateSampleWorkspace. It also used the left hand bin edge of the bin with the maximum y to set the initial fit parameters on a peak fit. I think this was incorrect so have changed it. The algorithm was written by the ILL team so will check with them that they're happy with this change.

**To test:**

Run this script and check that the y values in the first and last bin are the same:
```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

function = "name=Lorentzian,Amplitude=1,PeakCentre=5,FWHM=1"
ws = CreateSampleWorkspace("Histogram", Function="User Defined", UserDefinedFunction=function, 
                            XMin=-5, XMax=5, BinWidth=0.01, XUnit="DeltaE")
```

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DannyHindson** [comment]
@darominski - I've created this PR to fix a problem in the CreateSampleWorkspace algorithm where the function specified was being evaluated at the left hand bin edge instead of the bin centre. It's affected a few more things than I originally planned though...

The change caused some of the FindEPP unit tests to fail and I decided in the end that the FindEPP algorithm needed a small change as well. I think there was a similar problem in FindEPP that was hidden by the bug in CreateSampleWorkspace. The FindEPP change then caused a couple of ILL system tests to fail which I also fixed up.

Please can you have a look and see if you're OK with this from an ILL perspective? I think the FindEPP algorithm was created by the ILL team. If you prefer me to remove the FindEPP changes from this PR that's fine.

**Review by darominski — APPROVED** [review]
The code looks good and on the ILL side there seems to be no issues created by the change of behaviour of the FindEPP algorithm.

Regarding the test provided, I do not see that the Y values are the same for both ends of the distribution, but since the distribution is asymmetric, would we actually expect that?

When I plug in a symmetric function, e.g. a Gaussian, then the new behaviour is as expected (and written in the test), while it was a bit confusing prior to the fix. Based on this test I could say that the fix works as intended.

**Comment by DannyHindson** [comment]
Thanks for testing. There's a typo in my script sorry - it should read:
``function = "name=Lorentzian,Amplitude=1,PeakCentre=0,FWHM=1"``
...but since you have tested on a Gaussian that demonstrates it's working OK

**Comment by martyngigg** [comment]
Nice catch!

**Pull request merged**
