### PR TITLE
Fix Crash when incorrect credentials are used when logging into ICAT in Refl GUI

### LINKED ISSUE #15400: Crash when using wrong credentials
Open the reflectometry GUI (Polref) and try logging in using wrong credentials. Mantid crashes. This seems to be a problem related to the interface only, as if I do "Catalog" > "Loging" it just gives an error message but Mantid does not crash.

I also noticed that if you just close the "CatalogLogin input dialog" (i.e., open the interface, choose an investigation ID and click on "Search", then click on "Cancel" in the new dialog) it also crashes. The same happens if you close the dialog using the "x".

### PR DESCRIPTION
**Pull request by MattKing06**
There were no checks being performed when the GUI attempts to grab the sessionID of the ICAT active sessions. The check has now been added to see if there are any active sessions before attempting to retrieve the ID of that session. 

**To Test**
- Make sure you have an ICAT login (to check what happens when the correct credentials are entered)
- Load up the ISIS Reflectometry (Polref) interface (`Interfaces > Reflectometry > ISIS Reflectometry (Polref)`)
- In the search table (to the right hand side) change the search instrument to `Polref`
- Change the type from Description to Measurement 
- Enter the Investigation ID `1520249`
- When the ICAT login dialog pops up:
- Enter the wrong credentials and make sure mantid does not crash
- Press `Cancel` and ensure there is no crash
- Close the dialog use the `X` window button and make sure there is no crash
- Enter the correct credentials and search, make sure the search table is populated.

[Release Notes](http://www.mantidproject.org/Release_Notes_3_7_Reflectometry#ISIS_Reflectometry_.28Polref.29)

Fixes #15400

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
Thanks for the fix Matt, would it be possible to test this? (I'm just asking, maybe it not so easy to test...)

**Comment by MattKing06** [comment]
@raquelalvarezbanos I believe that testing it would require a bit more investigation and possibly some refactoring of ReflMainViewPresenter so I have made an issue for this [here](https://github.com/mantidproject/mantid/issues/15415)

**Comment by raquelalvarezbanos** [comment]
OK, thanks @MattKing06 then this is ready to be reviewed by the second tester. Please mention this in the release notes.

:shipit:

**Comment by FedeMPouzols** [comment]
Issue fixed :+1: 

It would be good to have a regression test for this (as planned in #15415). The design of this interface should make it possible. It seems that for the catalog there are mock objects already in place in other tests. Those might come in handy.

**Pull request merged**
