### PR TITLE
RenameWorkspace algo should rename attached workspace too.

### PR DESCRIPTION
**Pull request by abuts**
resolves issue #14071 

Ticket's  commits become a bit convoluted as I've done number of rebases splitting one big ticket into parts but the changes here are pretty simple. 

RenameWorkspace algorithm renames monitor workspace too, if one is attached to the workspace being renamed. Unit test for algorithm and python function overload verifies that this indeed happens and doctest for RenameWorkspace modified to reflect the changes.  I believe, unit tests for algorithm clearly shows what changes intended to do. To maintain compatibility with old python interface I have to add the algorithm wrapper to simple API. Python unit test for that verifies wrapper and shows that the changes work as expected. [Release notes](http://www.mantidproject.org/Release_Notes_3_6_Direct_Inelastic) have been modified accordingly. 

I had to modify a bit of python due to Pylint going mad + simple modification to LoadRaw with was not setting monitor workspace pointer while loading workspace separately (some previous version used to), but these are minor deviations.

### CODE REVIEW

**Comment by FedeMPouzols** [comment]
All looks fine. The new option has unit tests and there's an example / doc test in the rst page.
Incidentally this also fixes a good bunch of pylint issues.
Maybe the last block of code of `RenameWorkspace::exec()` which is all about renaming the `_monitors` workspace could be moved into a method of its own, just to keep `exec()` short.

**Comment by FedeMPouzols** [comment]
Oh, sorry, just before closing my test Mantid build I found now a minor issue? with the python documentation of RenameWorkspace. I'm not sure if this is the intended behavior: If you type `RenameWorkspace(` in the script interpreter it won't show you the new option (RenameMonitors), just the help string that comes from https://github.com/mantidproject/mantid/pull/14098/files#diff-21e1642a0ce7da9cc69e0c7542489c39R473, and the Input/Ouput Workspace options.

**Comment by abuts** [comment]
Yes, it shows it as part of **kwargs.  I was thinking about adding it to options, but was not sure if [outputWorkspace],[RenameMonitors],**kwargs) is confusing. Now, thinking about it again and seeing that is is not only my opinion, I would rather add it there.

**Comment by abuts** [comment]
As for separate procedure, for RenameMonitors, ... its on the limits... Let's leave it alone for the time being. If it has 10 more rows, I would certainly take it away....

**Pull request merged**
