### PR TITLE
Fix error when removing constraints

### LINKED ISSUE #27997: Error when removing constraints in analysis gui's
### Expected behavior
The constraints still there should be correctly applied and the removed constraint should not be there

### Actual behavior
When the constraints is removed it is replaced by a number close to 0.

### Steps to reproduce the behavior
Note: This occurs in multiple gui's (all using the same code)
Open the  Muon frequency domain analysis and load a run.
Go to the fitting tab, right-click on the function browser and add a function
Click on the Value box of one of the parameters and click the `...` box that appears.
Click `set` then `set constraint`.
Enter a value for the constraint e.g. `0<Height<10` and press ok then ok again.
Right-click on one of the bounds and remove it.
Click on the `...` button again and the constraint will have changed to something incorrect.
If you do a fit it uses the incorrect constraint.

### Platforms affected
All

### PR DESCRIPTION
**Pull request by alicerussell1**
**Description of work.**
This PR fixes the issue where if a constraint was removed from the gui or only one constraint was set, the empty constraint was set to a value near 0.

**To test:**
Open the Muon frequency domain analysis and load a run.
Go to the fitting tab, right-click on the function browser and add a function
Click on the Value box of one of the parameters and click the ... box that appears.
Click set then set constraint.
Enter a value for the constraint e.g. `0<Height<10` and press ok. You will see the set constraint in the `Role` column. Press ok.
Right-click on the lower bound and remove it.
Click on the ... button again and the constraint should be correct e.g. `Height<10`
Press `Fit` and this constraint should be used i.e. the height should be less than 10

Fixes #27997 

*This does not require release notes* because **it was not in the last release**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by giovannidisiena — COMMENTED** [review]
Code changes look good, will remove my assignment to allow someone else to do the functional testing because Ubuntu :cry:

**Comment by Harrietbrown** [comment]
After following the steps in your test instruction if you go back in and set the lower bound again so that the fitted value is outside of the range then if you try to fit again the new fit will not obey the constraint. Although looking at the code it doesn't look like that is an issue caused by this PR. can you confirm that?

**Comment by alicerussell1** [comment]
That isn't caused by this PR, it is in master - although it wasn't in 4.2. By the looks of it I think that is because if you have done a fit and not changed the parameters then it doesn't redo the fit, if you change any of the parameters it should redo it and be within the constraints.

**Review by Harrietbrown — APPROVED** [review]
The constraint set in the function settings is updated when the lower or upper bound is removed from the fit browser as described. Good Job.

**Pull request merged**
