### PR TITLE
Indirect data reduction transmission crash fix

### LINKED ISSUE #25191: Indirect data reduction transmission crash
Go to the interfaces and select `data reduction` from `indirect`
Change to the transmission tab
Change the instrument to IRIS
Enter the sample file as 26184
Enter 26179 as the background file - it may now hard crash at any point
Press run - will definitely crash

### PR DESCRIPTION
**Pull request by LowriJenkins**
**Description of work.**
changed preview window to not run the entire algorithm on loading data which led to attempting to load the same data multiple times while the previous load was still running, the preview window now displays a preview of the plot when run is clicked and not before, preventing both this issue, and preventing the algorithm from being ran twice by the gui.

**Testing**

Follow instructions for reproducing issue, no crash should occur, also attempt inputting the background then hitting enter twice, this should also not cause the preview to attempt to run twice, which could also cause a crash.

Fixes #25191 
---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by TTitcombe — DISMISSED** [review]
Crash fixed for me :+1: 
code change minimal - primarily removing unnecessary code

**Comment by NickDraper** [comment]
This needs release notes @SamJenkins1

**Review by TTitcombe — APPROVED** [review]

**Comment by martyngigg** [comment]
@SpencerHowells Is the intention of the preview tab to show a preview from the file *before* clicking run?

**Comment by robertapplin** [comment]
@martyngigg @SpencerHowells It previously would run the `IndirectTransmissionMonitor` algorithm and show a preview upon loading, and then when run is clicked it would do exactly the same.
@SamJenkins1 It might be worth making sure the run button is disabled until the files have been loaded.  This is what the ISIS Energy Transfer tab does so their should be an example in there to follow.

**Comment by SpencerHowells** [comment]
@martyngigg @SamJenkins1 @robertapplin There is no need to plot the data before running.

**Comment by martyngigg** [comment]
Thanks all. I just wanted to check my understanding what was expected as the word preview meant something different to me.

**Pull request merged**
