### PR TITLE
Feature/8840 python algorithms category

### LINKED ISSUE #8840: PythonAlgorithms category to remove?
This issue was originally [TRAC 7995](http://trac.mantidproject.org/mantid/ticket/7995)

I can't ever imagine a user searching for an algorithm and looking for a python one via the categories. Don't see what use the programming language of implementation is for the end user. Does anyone have a use-case for this, or can we remove this category?

### PR DESCRIPTION
**Pull request by NickDraper**
- Removed PythonAlgorithms category
- Added a warning should any algorithm use the default "PythonAlgorithms" alone
- Neatened up all of the other categories, mainly by sorting algorithms into sub categories

closes #8840 
### Release Notes

http://www.mantidproject.org/ReleaseNotes_3_6_UI_Changes#Algorithm_Toolbox
http://www.mantidproject.org/ReleaseNotes_3_6_Framework_Changes#Python_Algorithms
Also
http://www.mantidproject.org/Basic_PythonAlgorithm_Structure
and the solutions in 
http://www.mantidproject.org/Extending_Mantid_With_Python_Solutions
### To Test
1. Start up mantidplot
2. Look at the algorithm categories in the algorithm toolbox
   1. There should not be a PythonAlgorithms category
   2. The other categories should be neater than before
3. Look at the offiline docs for a few of the algorithms, the categories for the algs should match.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
When I view online help algorithm descriptions, the contents pane is empty. Should this be so?

**Comment by KarlPalmen** [comment]
I'll leave it to someone else to resolve the merge conflicts.

**Comment by KarlPalmen** [comment]
When I used online help for algorithm descriptions, I saw the contents pane was blank. Should it be so?

**Comment by KarlPalmen** [comment]
Code review is OK.

**Comment by NickDraper** [comment]
@KarlPalmen This is all merged now with no conflcts, and VS 2015 ready

**Comment by KarlPalmen** [comment]
I checked LoadDiffCal, which has an unusual categorisation of Diffraction/DataHandling. This causes the category DataHandling to appear twice in the offline Help both seem to link to the same place.

I then also find LoadDiffCal in category DataHandling/Instrument.

**Comment by KarlPalmen** [comment]
The issue just mentioned will be dealt with separately.

**Pull request merged**
