### PR TITLE
Enforce the associative property for ProductFunction

### LINKED ISSUE #20250: Enforce the associative property for ProductFunction
Given functions `f`, `g`, and `h`, enforce that the three expressions `(f * g) * h`,  `f * (g * h)`, and `f * g * h` result in the same `ProductFunction` object.

### PR DESCRIPTION
**Pull request by jmborr**
Base class for composite functions that are associative, and implementation for `ProductFunction`.

Fixes #20250

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by jmborr** [comment]
@mantid-roman @martyngigg I have opened this issue to enforce the associative property in the `ProductFunction` when creating fit functions. For instance, instantiating from string
 ```
(composite=ProductFunction;
   name=ExpDecay;
   composite=ProductFunction;name=Gaussian;name=Lorentzian)
)
```
will result in a function whose string representation is
```
(composite=ProductFunction;name=ExpDecay;name=Gaussian;name=Lorentzian)
```
So functions `f * (g * h)` and `(f * g) * h` will be represented by their "flat" version `f * g * h`.
Please let me know your thoughts about it.

**Comment by KarlPalmen** [comment]
Issue #20279 has been created to enable ``castToComposite`` to be removed. It does so by tackling the root cause of the problem arising from the fact that ``ProductFunction`` etc. are not really exported to python.

This PR request may be worth merging if the above issue cannot be resolved. It might also be worth merging if it would eliminate the need for the ``flatten`` method from ``CompositeFunctionWrapper``, but while this may apply to ``ProductFunction``s, it can't apply to ``CompositeFunction``, because this is a superclass of ``AssociativeCompositeFunction`` and so ``flatten`` must remain.

**Comment by jmborr** [comment]
@KarlPalmen That's why I wrote[ Addition](https://github.com/mantidproject/mantid/blob/e378026b952632c7049cc95ffb356f6ec580e4af/Framework/CurveFitting/inc/MantidCurveFitting/Functions/AdditionFunction.h) funtion. With `Addition` and `ProductFunction`, there should be no need for flatten. :bowtie:

**Comment by jmborr** [comment]
@KarlPalmen  @mantid-roman As of now, the automatic flattening process works as long as the associative function to be added does not have a tie among its component functions.  One example of this case:
```
f = (composite=ProductFunction;name=Linear)
g = (composite=ProductFunction;name=Gauss;name=Cubic;ties=(f1.c0=f0.c))  # a cross-tie
```
Now I want to do `h = f * g`. The current fit framework will result in:
```
h = (composite=ProductFunction;name=Linear;(composite=ProductFunction;name=Gauss;name=Cubic;ties=(f1.c0=f0.c)))
```
But I want the flat version because we have the product of three simple functions:
```
h = (composite=ProductFunction;name=Linear;name=Gauss;name=Cubic;ties=(f2.c0=f1.c)) 
```
The original tie expression `f1.c0=f0.c` makes sense in the context of composite `g`. To promote this tie to the new composite context `h`, the only way I can think of is to construct a mapping between the old and the new function indexes (`g.f1` becomes `h.f2` and `g.f0` becomes `h.f1`) and then recreate all the ties with the new indexes.
Well, do you see other alternatives?

**Comment by KarlPalmen** [comment]
I haven't addressed this issue in my works so far and there are no unit tests for it. 

I think the suggested idea is good and it may occur automatically. I expect this would be the case, if the ties inside the functions refer to parameters by their index within the composite function rather than the parameter name. Flattening does not change the order of the parameters and hence their index.

**Comment by KarlPalmen** [comment]
This fixes a problem that has been fixed in an alternative way. This could be considered in maintenance as a better way to fix this problem. Hence I'm moving it to next release.

**Comment by jmborr** [comment]
@KarlPalmen Thanks, Karl. I had no time as of late to finish this off.
By the way, what is the alternate way you mention? Where can I find the related code.

**Comment by KarlPalmen** [comment]
The alternative way it has been fixed is by properly exposing the curve fitting functions to python as in issue #20279 and retaining the flattening when all add or all multiply.

**Comment by KarlPalmen** [comment]
I'll be away for the next two weeks after today.

**Comment by martyngigg** [comment]
Is this still valid with the Python functionality?

**Comment by KarlPalmen** [comment]
This change is not necessary after the exposure of ``CurveFitting`` to python, but may be desirable.

**Comment by KarlPalmen** [comment]
This issue solves a problem with the binding of fitting functions to python that has been solved by other means.

**Comment by jmborr** [comment]
I'm closing this pull request since the issue was solved in the python API

**Pull request closed without merging**
