### PR TITLE
Add usage reports for Indirect/Inelastic interfaces

### LINKED ISSUE #37418: Report feature usage for Indirect/Inelastic tabs
**Is your feature request related to a problem? Please describe.**
It would be useful to have usage statistics for each of the tabs in the Indirect/Inelastic interfaces. Mantid provides the ability to register the use of a feature, and to store it in our Usage service. If a tab is not being used, we should remove its code to keep the code in indirect/inelastic lean and easier to maintain.

**Describe the solution you'd like**
When the RunWidget has been created and added to each of the tabs, it should be possible to register a feature usage each time the "Run" button is clicked within this widget. I think the only challenge would be how to determine the name of the feature from within the run widget. One option could be to provide a string to the RunWidget which specifies the name of the tab. There might be a nicer way to do this however.

**Additional context**
It has been difficult to remove Calculate Paalman Pings without feature usage statistics.

### PR DESCRIPTION
**Pull request by MohamedAlmaki**
### Description of work
This PR adds usage reports for all indirect/inelastic interfaces. It has been implemented by adding a new name method to the common run widget. After each time the run widget is used, a new usage request will be sent to the usage reports service.

Fixes #37418. 

### To test:
1. Open mantid
2. Make sure the "Report Usage Data" is checked in the starting about screen or go to `Help->About Mantid Workbench`
3. Change the log level in the log to "Debug"
4. Try few different interfaces from the indirect and inelastic features
5. You should see a request has been send with after clicking run in every interface
6. Send a GET request to https://reports.mantidproject.org/api/feature and you will get the usages from the reports service, you can use https://restninja.io/ for that and search for the feature in the response text
7. Make sure the name of each interface is correct 

*This does not require release notes* because **internal usage reporting**

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by adriazalvarez — CHANGES_REQUESTED** [review]
I have tested most of the interfaces. Feature request is working, and the get request fetches the correct number of usages per interface. 
There are two interfaces with the name Iqt, which are registered as `I(Q, t)` (from qens fitting) and `Iqt` (from data processor).  
Should we add a label on the "Iqt" to make the distinction more clear?

**Comment by MohamedAlmaki** [comment]
I have changed the label to "IQT Data Processor"

**Review by adriazalvarez — APPROVED** [review]
Thanks for the changes.

**Comment by robertapplin** [comment]
Test failures are unrelated

**Pull request merged**
