### PR TITLE
Fix workbench hang on clean install

### LINKED ISSUE #31354: Workbench Hang on start after updating facilties.xml
### Expected behavior
Workbench should gracefully handle updating facilities files 

### Actual behavior
Complete hang, followed by crash on a fresh install

```
 File "C:\MantidNightlyInstall\bin\workbench\app\start.py", line 207, in start
   exit_value = start_workbench(app, options)
 File "C:\MantidNightlyInstall\bin\workbench\app\start.py", line 178, in start_workbench
   AboutPresenter(main_window).show()
 File "C:\MantidNightlyInstall\bin\workbench\widgets\about\presenter.py", line 40, in __init__
   self.setup_facilities_group()
 File "C:\MantidNightlyInstall\bin\workbench\widgets\about\presenter.py", line 103, in setup_facilities_group
   self.action_facility_changed(default_facility)
 File "C:\MantidNightlyInstall\bin\workbench\widgets\about\presenter.py", line 111, in action_facility_changed
   current_value = ConfigService.getFacility().name()
RuntimeError: Facilities search object  
```

### Steps to reproduce the behavior
Edit: this is trivially reproducible 
- Ensure that facility and default instrument are blank (like on a fresh install)
- Transplant the files from an older tag such as https://github.com/mantidproject/mantid/tree/v5.1.1/instrument to the %appdata%/instrument folder.
- Delete github.json
- Start workbench, it will freeze immediately

### Platforms affected
Windows, possibly all?

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR fixes a crash by workbench when starting up a clean install of Mantid workbench with an empty facility.

**To test:**
Follow the testing instructions in the issue and make sure mantid opens ok #31354 

Fixes #31354

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DavidFair** [comment]
@clayton-tom I'm happy for you to still review this at the same time as me, then we have a gatekeeper / normal review at the same time

This resolves the problem for me locally at least

**Review by DavidFair — COMMENTED** [review]
LGTM, is there some way we can add a test for this - just simply that the presenter manages to complete if the facility is None so we don't regress? As it's pretty subtle

**Comment by robertapplin** [comment]
> @clayton-tom I'm happy for you to still review this at the same time as me, then we have a gatekeeper / normal review at the same time
> 
> This resolves the problem for me locally at least

Yes sorry, I forgot @clayton-tom was assigned when I requested a review because I didn't refresh my browser 🤦

**Review by clayton-tom — DISMISSED** [review]
Changes work as described for me as well :+1:

**Review by DavidFair — APPROVED** [review]
LGTM, I'm happy to :shipit: once @clayton-tom reviews it, so two of us have looked

**Comment by martyngigg** [comment]
I'm going to merge this to get it in the next build.

**Pull request merged**
