### PR TITLE
Abins thresholding changes

### PR DESCRIPTION
**Pull request by ajjackson**
**Description of work.**

The semi-empirical powder averaging procedure of Abins includes a lot of logic dealing with "stability". This was introduced as part of #19906 with the stated goal

> to avoid non-physically high intensities of higher orders quantum
> events.

It is related to the process of removing small values of S with a
numerical threshold. The thresholding process is a useful time-saver
as it cuts down the N of the slow O(N^4) enumeration of high-order quantum
events. The additional "stability" procedure employed here is to check
if the order N excitations have a higher intensity than order N-1
excitations, and if so to recompute all the excitations using a
_higher_ threshold.

This code is causing several problems and I propose in the short term
to deal with them by simply removing this functionality and
streamlining the module.

- The current maintainer/developer of Abins (myself) does not
  understand how the code is supposed to work. Why does raising the
  threshold help in this situation? How many iterations are typical?
  Without this knowledge the feature cannot safely be adapted to deal
  with new situations.
- The comments within the code generally refer to this procedure as a
  matter of numerical stability; this is quite confusing when it
  appears that the physics is being checked rather than numerical
  convergence.
- It's not clear that removing low-intensity contributions will result
  in better physics, even if it does fix a surprising trend in
  intensity.
- The implementation relies heavily on state; tracking previous values
  of thresholds via object attributes as loops are iterated, and using
  methods to modify these attributes. This makes it difficult to
  change the flow of the program, impeding work on features and
  optimisation.

It seems simpler, faster and more useful to perform checks at the end
of the Abins run and suggest to the user that they may wish to run
again with a different threshold.

The "relative threshold" parameter is retained and re-purposed for something obviously useful: a warning to the user that their S intensities are not very large compared to the "absolute threshold" used to remove low-intensity events. This warning is given through the Mantid logging system.

To do:
- [x] A new test for the threshold warning
- [x] Release note for the threshold check.

**To test:**

No special test procedure. Abins unit tests can be checked with e.g.
```ctest -R Abins```

~~A release note is needed for the new threshold warning. Not clear if the removal of iterative procedure should be mentioned.~~ Removal of the high orders should possibly not be listed under "improvements"? It's part of a larger block of change notes, however, that *does* belong as an "improvement".

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by ajjackson** [comment]
The system test failures seem to be genuine, will need to investigate those.

**Comment by ajjackson** [comment]
I can reproduce the system test failures from the passing commit 380a2291313 by commenting out some logic in `SPowderSemiEmpiricalCalculator._calculate_s_over_threshold()` so am reasonably convinced that this relates to a genuine change in the results associated with this thresholding logic. The next step is to figure out how to compare the actual numbers...

**Comment by ajjackson** [comment]
The results do seem to have changed a bit.

TolueneScratchAbins-comparison

**Comment by ajjackson** [comment]
The results do seem to have changed a bit. This large peak emerges from third- and fourth-order quantum events for H atoms in a range of small molecules when vibrations are computed with CRYSTAL. I am investigating this phenomenon; users are unlikely to be pleased with an "improvement" that leads to this kind of absurd spectrum. However, while the existing thresholding system does hide this behaviour it seems likely that the underlying cause is something else which needs to be addressed.

TolueneScratchAbins-comparison

**Comment by ajjackson** [comment]
A possible contribution to this "hump of doom" has been identified while working on broadening ( #27043 );
the implementation of the Gaussian broadening function includes a normalisation term that gives a consistent peak height:

**Comment by ajjackson** [comment]
A possible contribution to this "hump of doom" has been identified while working on broadening ( #27043 );
the implementation of the Gaussian broadening function includes a normalisation term that gives a consistent peak height:

```python
        two_sigma = 2.0 * sigma
        sigma_factor = two_sigma * sigma
        norm = (AbinsModules.AbinsParameters.sampling['pkt_per_peak']
                / (AbinsModules.AbinsParameters.instruments['fwhm'] * two_sigma))
        return np.exp(-(points - center) ** 2 / sigma_factor) / (np.sqrt(sigma_factor * np.pi) * norm)
```
abins_normalised_gaussian
Such a function has an _area_ than increases with increasing width. The resolution function of TOSCA increases Sigma with frequency, which in this implementation leads to an increased contribution of high-energy terms to the overall histogram. It doesn't seem to be consistent with the expression given in the Abins paper (Eqn 14): https://doi.org/10.1016/j.physb.2018.02.034 which is a more usual area-conserving Gaussian function.

The scale factor was added in 2f77b4f9f7e4608650bb8d03bd7654652547d5b2 so would not be present in Mantid 3.10 or earlier. Removing the *norm* term yields results that appear more reasonable, but the fourth-order contribution is still unexpectedly large.
abins-threshold-denormed-gaussian

**Comment by ajjackson** [comment]
I've performed some benchmarking vs a-CLIMAX and o-CLIMAX (using the CASTEP gamma-point benzene test data) and we see that
- agreement at second order is reassuringly good
- deviation sets in at third order. Deviation from o-CLIMAX is expected as they use a different approximation at this level and above. Deviation from a-CLIMAX is not explained at this point.
- The deviation is _close_ but _not equal_ to a scale factor of 4 from the a-CLIMAX results. There is some frequency-dependent difference in intensity, with a larger ratio at higher frequencies
- The "hump" is not garbage data; it tracks the same features as the a-CLIMAX output but the intensity is different. Either something is happening to the intensity calculations or there is a duplication/double-counting issue and too many peaks are going into the spectrum.

comparison
[comparison.pdf](https://github.com/mantidproject/mantid/files/4035528/comparison.pdf)

**Comment by ajjackson** [comment]
Something very similiar to the high-frequency shelf in a-CLIMAX order-4 is obtained with o-CLIMAX by enabling quantum orders up to 10 (by repeated convolution with the fundamentals spectrum). This suggests that the a-CLIMAX order-4 data may contain some kind of additional phonon wing correction. So we can't expect complete agreement at fourth-order between Abins and either of these codes.

**Comment by ajjackson** [comment]
At this stage the maths for the 3rd and 4th-order terms is not trusted. I am reviewing the literature to find the origin of the prefactor terms (which become small at high order, but evidently not small enough for the data Abins is scaling). Their derivation tends to be handwaved and referred to other papers. The numbers have changed between commits of Abins without reference to an original source.

While investigating the correct implementation of 3rd and 4th-order terms, it is proposed to disable these terms from Abins, and only permit the user to select 1st or 2nd-order. It's technically a regression in features, but we cannot currently recommend that end-users select the other options using any version of Abins.

**Comment by ajjackson** [comment]
Naturally disabling the order 3, 4 contributions breaks all the integration tests which use those terms.

This leaves two broken system tests that only extend to order 1 or 2. Plotting the nexus files reveals very small differences. We shouldn't have to worry _too_ much about replacing those reference files, but it would be good to check if they involved the iterative screening procedure.

threshold_systemtests

**Comment by ajjackson** [comment]
Ok, I can more-or-less reproduce the old system test results by modifying the threshold in SPowderSemiEmpiricalCalculator:

```python
    def _calculate_s_over_threshold(self, s=None, freq=None, coeff=None):
        """
        Discards frequencies for small S.
        :param s: numpy array with S for the given order quantum event and atom
        :param freq: frequencies which correspond to s
        :param coeff: coefficients which correspond to  freq

        :returns: freq, coeff corresponding to S greater than AbinsParameters.sampling['s_absolute_threshold']
        """

        # indices = s > AbinsParameters.sampling['s_absolute_threshold']
        indices = s > 1e-3
...
```

abins-stability-systemtest-thresholds

I don't quite understand why the value has to be set so high, but this at least satisfies me that the problem is related to the somewhat arbitrary matter of screening low values - and the new setup is more conservative than the old one. From here it should be acceptable to update the systemtest data and finish this MR.

I do have one minor complaint about the implementation here which could use fixing, but is low-priority compared to other matters: the thresholding is based on intensity _before_ weighting by atom cross-sections. We would need to pass around a bit more data to account for this, which may impact performance. Still, it would make the process more meaningful and remove what is effectively a bias against high-cross-section atoms in the final spectrum. Happy to defer this for now, given that the threshold has been made quite small and cross sections only span a few orders of magnitude.

**Comment by ajjackson** [comment]
Those test failures don't look related to these changes?

**Review by Matthew-Andrew — APPROVED** [review]
Code changes looks good to me.

Changes to Abins functionality have been checked with relevant scientists.

**Pull request merged**
