### PR TITLE
Enable FilterEvents work with splitters out of time range

### LINKED ISSUE #19140: Enable FilterEvents to work with multiple workspaces with a single splitters workspace
### Expected behavior

The events and sample logs should be correct for the following script
```
# script to test chopping event workspace with slicers outside of event workspace's time range

# split original workspace into continuous workspaces
Load(Filename='/SNS/VULCAN/IPTS-13183/data/VULCAN_68607_event.nxs', OutputWorkspace='ws')
GenerateEventsFilter(InputWorkspace='ws', OutputWorkspace='TimeSlicer', InformationWorkspace='linfo', StartTime='0', TimeInterval='3000', LogValueInterval=100)
FilterEvents(InputWorkspace='ws', SplitterWorkspace='TimeSlicer', OutputWorkspaceBaseName='workspace', InformationWorkspace='linfo', GroupWorkspaces=True,
    OutputWorkspaceIndexedFrom1=True)     
    
# generate a splitters workspace from log value
GenerateEventsFilter(InputWorkspace='ws', OutputWorkspace='LoadFrameSlicer', InformationWorkspace='linfo', StartTime='0', TimeInterval='3000', LogName='loadframe.furnace1', LogValueInterval=100)

# Filter
for index in [1, 2, 3, 4, 5, 6]:
    FilterEvents(InputWorkspace='workspace_{0}'.format(index), SplitterWorkspace='LoadFrameSlicer', OutputWorkspaceBaseName='output{0}'.format(index), InformationWorkspace='linfo', 
        GroupWorkspaces=True, OutputWorkspaceIndexedFrom1=True) 

for target_index in range(1, 8):
    CloneWorkspace(InputWorkspace='output1_{0}'.format(target_index), OutputWorkspace='Final{0}'.format(target_index))
    ws = mtd['Final{0}'.format(target_index)]
    for s_index in range(2, 7):
        ws += mtd['output{0}_{1}'.format(s_index, target_index)
```

### Actual behavior

The run start time and proton charges are not synchronized with each other.

### Platforms affected

All.

### PR DESCRIPTION
**Pull request by wdzhou**
Description of work.

**To test:**

Run the following script, which split a workspace into several ones by time first. And then a splitter workspace is generated from the original workspace, such that for each child workspace, some of the splitters are not in its time range.  The goal of this PR is to make sure that FilterEvents creates the empty child workspace if the corresponding splitter is out of time range of the workspace that it operates on.

```
# split original workspace into continuous workspaces
Load(Filename='/SNS/VULCAN/IPTS-13183/data/VULCAN_68607_event.nxs', OutputWorkspace='ws')
GenerateEventsFilter(InputWorkspace='ws', OutputWorkspace='TimeSlicer', InformationWorkspace='linfo', StartTime='0', TimeInterval='3000', LogValueInterval=500)
FilterEvents(InputWorkspace='ws', SplitterWorkspace='TimeSlicer', OutputWorkspaceBaseName='workspace', InformationWorkspace='linfo', GroupWorkspaces=True,
    OutputWorkspaceIndexedFrom1=True) 
    
ws = mtd['ws']
print 'original workspace: run start = {0}, run end = {1}'.format(ws.run().getProperty('proton_charge').times[0], ws.run().getProperty('proton_charge').times[-1])
ws4 = mtd['workspace_4']
print 'child 1 workspace : run start = {1}, run end = {1}'.format(ws4.run().getProperty('proton_charge').times[0], ws4.run().getProperty('proton_charge').times[-1])
# replace run start
r4 = ws4.run()
run_start = ws4.run().getProperty('proton_charge').times[0]
r4.addProperty('run_start', str(run_start), True)

    
# generate a splitters workspace from log value
is_matrix = False
if False:
    is_matrix = True
    GenerateEventsFilter(InputWorkspace='ws', OutputWorkspace='LoadFrameSlicer', InformationWorkspace='linfo', StartTime='0', TimeInterval='700', LogName='loadframe.furnace1', LogValueInterval=100,
        FastLog=True)
    #FilterEvents(InputWorkspace='workspace_{0}'.format(4), SplitterWorkspace='LoadFrameSlicer', OutputWorkspaceBaseName='matrix_output{0}'.format(4), InformationWorkspace='linfo', 
        #GroupWorkspaces=True, OutputWorkspaceIndexedFrom1=False)
else:
    GenerateEventsFilter(InputWorkspace='ws', OutputWorkspace='LoadFrameSlicer', InformationWorkspace='linfo', StartTime='0', TimeInterval='700', LogName='loadframe.furnace1', LogValueInterval=100,
        FastLog=False)
    #FilterEvents(InputWorkspace='workspace_{0}'.format(4), SplitterWorkspace='LoadFrameSlicer', OutputWorkspaceBaseName='splitter_output{0}'.format(4), InformationWorkspace='linfo', 
     #   GroupWorkspaces=True, OutputWorkspaceIndexedFrom1=False) 


# Filter
for index in  [1, 2, 3, 4, 5, 6]:
    if is_matrix:
        output_base = 'matrix{0}'.format(index)
    else:
        output_base = 'splitter{0}'.format(index)
    FilterEvents(InputWorkspace='workspace_{0}'.format(index), SplitterWorkspace='LoadFrameSlicer', OutputWorkspaceBaseName='output{0}'.format(index), InformationWorkspace='linfo', 
        GroupWorkspaces=True, OutputWorkspaceIndexedFrom1=True) 
```

Fixes #19140.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
@peterfpeterson Pete, Wenduo assigned you as the tester of this PR two days ago, did you know?  Should we remove your assignment so someone else can pick this up?

**Comment by NickDraper** [comment]
Removed Pete as a tester so someone else can step in

**Comment by gemmaguest** [comment]
The code changes look good, but I can't run the test script because I don't have access to the file on `/SNS`. Can I get hold of that file somewhere, or is there another file I could use to test this?

**Comment by gemmaguest** [comment]
I wouldn't hold up the PR for it, but would it be worth adding a unit test for this?

**Comment by gemmaguest** [comment]
The code review is done, but I've unassigned myself so that someone with access to SNS data can test this.

**Comment by granrothge** [comment]
Should the data be added to the test data and the script be turned into a system test?

**Comment by VickieLynch** [comment]
:shipit: Works for VULCAN data

**Pull request merged**
