### PR TITLE
Instrument View Memory Leak Fix

### LINKED ISSUE #23780: Instrument View memory leak with Live Stream
**Original reporter:** Torben Neilsen of the ESS. 

### Expected behavior
Instrument view updates view using workspace data.
### Actual behavior
Instrument view seems to be leaking workspace memory.
### Steps to reproduce the behavior
To be investigated
### Platforms affected
All Platforms

### PR DESCRIPTION
**Pull request by LamarMoore**
**Description of work.**

The texture builder was not manually deleting opengl textures when destroyed which was causing memory to spiral out of control. This is now handled in the destructor.

**Report to:** [Torben Neilsen of the ESS]/[nobody]. 

**To test:**

- Ensure your system is connected to the RAL VPN 
- Run the script below in MantidPlot.
- When the `testout` workspace is created. Right click in the workspace dock and select Show Instrument.
- With the instrument view visible, use a system monitoring tool to see how the memory grows. Memory should stabilise around 1GB. 

```python
StartLiveData(FromNow=False, FromStartOfRun=True, UpdateEvery=2, Instrument='SANS2D', 
                    Listener='KafkaEventListener', Address='sakura:9092', ProcessingAlgorithm='Rebin', 
                    ProcessingProperties='Params=0,1000,100000', AccumulationMethod='Replace',
                    RunTransitionBehavior='Restart', OutputWorkspace='testout')
```

Fixes #23780 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by OwenArnold — APPROVED** [review]
Code changes look reasonable to me, but maybe @mantid-roman would comment as he has more experience. I observed the resource leak before these changes on OSX. The memory usage is stable after these changes.

**Comment by LamarMoore** [comment]
After I test on Linux I will remove the `In Progress` tag.

**Comment by LamarMoore** [comment]
Fix works on Ubuntu 18.04 in a vm (which is how the original issue was discovered).

**Comment by mantid-roman** [comment]
It seems OK to me. `BankTextureBuilder` has the same lifetime as `InstrumentActor` and is destroyed with it freeing the memory.

**Pull request merged**
