### PR TITLE
Scanning workspace construction (new branch)

### LINKED ISSUE #19198: Scanning Workspace Construction Helper
Time indexing is now available in Mantid such that scanning workspaces can be constructed - see https://github.com/mantidproject/mantid/pull/19119. Example of the construction can be seen in the `MatrixWorkspaceTest.h`.

This PR will add a helper class to construct scanning workspaces in the typical ILL case - where every detector has the same set of time indexes. The class will take:
* A `start_time` and a vector of durations or a vector of start and end times
* A vector of positions and rotations
* The corresponding spectra for every detector and monitor for each scan index
* A way to create sample logs with the same start and end times

The class will then be able to return a workspace in a consistent state with the correct number of scan intervals. Any issues with mismatched sizes etc. should throw a suitable error.

### PR DESCRIPTION
**Pull request by ianbush**
Please see PR #19565. This is a new PR for a new branch due to to some unintended pushes on the other branch leaving it in a messy state.

Fixes #19198.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — CHANGES_REQUESTED** [review]
I was just about to merge this but I realised that the `StartLiveData-v1.rst` file has been deleted. I assume that was accidental?

**Comment by ianbush** [comment]
Ah, good catch! Yes, this was accidental, the building the docs fail on this file if your facility is not ISIS or SNS, so I deleted it for the test and accidentally committed.

**Comment by martyngigg** [comment]
It sounds like we should fix that problem with the facility...

**Comment by ianbush** [comment]
Yes, we should. I will write a ticket and see if we can add it to the list of maintenance tasks.

**Review by martyngigg — APPROVED** [review]

**Comment by martyngigg** [comment]
These changes will not impact any current workflows so are safe to merge for `3.10`. :shipit: when the builds pass.

**Pull request merged**
