### PR TITLE
Indirect Data Analysis - Adjustable plot sizes

### LINKED ISSUE #25520: Indirect Data Analysis - Fit and Difference plot sizes not adjustable
### Expected behavior
It should be possible to adjust the sizes of the Fit and Difference plots in MSDFit, IqtFit, ConvFit and FQFit. This can be done using a splitter.

### Actual behavior
They cannot ave their sizes adjusted.

### Steps to reproduce the behavior
1.`Interfaces`->`Indirect`->`Data Analysis`->`ConvFit`
2. Try to adjust the size of the plots

### Platforms affected
All

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR allows you to adjust the sizes of the Fit and Difference plots in MSDFit, IqtFit, ConvFit and JumpFit. Their sizes can be adjusted by dragging the handle of the QSplitter layout.

The decision to make the handle transparent was made as it makes the interface look less cluttered.

**To test:**
1. `Interfaces`->`Indirect`->`Data Analysis`->`ConvFit` tab (or one of the other tabs listed above)
2. Find the handle of the QSplitter (between the two plots) and then drag it up or down to adjust the plot sizes.
3. The Plots should also be collapsible by dragging the slider all the way up or all the way down.

Fixes #25520

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by TTitcombe** [comment]
On Ubuntu 18 there is barely any movement when moving the QSplitter. Moving slightly up or down will just snap the bottom/top plot into full size. Is this intended behaviour or does it work differently on Windows?

**Comment by robertapplin** [comment]
@TTitcombe by the sounds of it, it works differently on windows. Is there any extra movability if you undock the miniplots first and then try adjust them?

**Comment by TTitcombe** [comment]
You don't get extra mobility if you undock them, but I just checked again and I can get smooth varying plot sizes, provided the GUI is fullscreen, so this PR is gtg

**Review by TTitcombe — APPROVED** [review]
The indirect GUIs now have the ability to smoothly change the size of miniplots. Release notes have been updated appropriately

**Pull request merged**
