### PR TITLE
Fix simple flake 8 warnings

### LINKED ISSUE #20908: Flake 8 clean up
Get rid of as many flake 8 warnings as possible.

### PR DESCRIPTION
**Pull request by AnthonyLim23**
This is a fix of simple flake 8 warnings. The Muon warnings are fixed in #20890 and Reflectometry are fixed in 20663.

The remaining warnings are about the complexity of the functions. 

**To test:**
Code review and check that the Mean algorithm works. 

Fixes #20908. 

**Release Notes** 

---
Does not need to be in release notes 
#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AndreiSavici** [comment]
@AnthonyLim23 it seems to be a numpy issue: ```import numpy as np
a=np.arange(3)
b=np.arange(3)
b[1]=4
print(np.allclose(a,b) == False)
print(np.allclose(a,b) is False)``` gives different answers, depending on the numpy version. The last two lines give the same answer in numpy versions >1.10

**Comment by AnthonyLim23** [comment]
I will look at fixing this in the morning. I am going to try

` if not condition:`

**Comment by AnthonyLim23** [comment]
I have had a look into this and I found the following script:
```

import numpy

a=np.arange(3)
b=np.arange(3)
b[1]=4
print(np.allclose(a,b) == False)
print(not np.allclose(a,b))
print numpy.version.version
```

gives the results:
```
Fri 13. Oct 07:54:09 2017: Script execution started.
---------------------------------------------------------------------------
True
True
1.9.3
```

**Comment by AnthonyLim23** [comment]
I have also made the same change to #20890, however is not None seems to work fine in numpy 1.9

**Comment by AndreiSavici** [comment]
The new syntax works with numpy 1.7.1 that we have on our analysis servers at SNS

**Review by AndreiSavici — APPROVED** [review]

**Pull request merged**
