### PR TITLE
Add a Historgram validation check to Indirect Absorption Corrections

### LINKED ISSUE #33384: Mantid crashes when running an absorbption correction in Indirect
**Original reporter:** Spencer Howells

**Describe the bug**
In the Apply Absorption Corrections tab in the Indirect Corrections GUI, pressing the run button after loading a sample and corrections makes Mantid disappear (when using Windows). When using Ubuntu the same action causes a segmentation fault.

**To Reproduce**
1. Open Indirect -> Corrections
2. Open the Apply Absorptions Corrections Tab
3. Load a sample file
4. Load a corrections file
5. Press Run
6. Windows users will see Mantid close, Ubuntu users will get a segmentation fault.

**Expected behavior**
Pressing the run button should not crash Mantid or cause a segmentation fault.

**Platform/Version (please complete the following information):**
Tested by user on Windows and Ubuntu (versions not supplied)

Tested by @sf1919 on Windows 10 using Mantid v6.2.20220124.1600

### PR DESCRIPTION
**Pull request by sf1919**
**Description of work.**
In the process of trying to fix #33384 it was suggested that this might be resolved by adding a check to the number of histograms in the sample and corrections workspaces (they need to be the same). This check is already used in other tabs in the Indirect Corrections GUI.

Whilst this did not fix the fault that occurred the addition of this check is sensible and has been done using this PR.

**Report to:** Spencer Howells

**To test:**
1. Using #33395 make changes to lines 183 and 189 of the ApplyAbsorptionCorrections.cpp file (otherwise you cannot load any files without it crashing).
1. Open Indirect -> Corrections
2. Open the Apply Absorptions Corrections Tab
3. Load a sample file (ask for file if you don't have anything suitable)
4. Load a corrections file with the same number of histograms (ask for file if you don't have anything suitable)
5. Press Run. It should complete successfully
6. Change the corrections file to one with a different number of histograms (ask if you don't have anything suitable)
7. Press run. You should get a pop up explaining the number of histograms doesn't match and it will not proceed with applying the corrections.

Partially Fixes #33384 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by Harrietbrown — APPROVED** [review]
Good job the error pop up appears as expected, however In testing I have found another crash where if you rebin the corrections workspace so it has a different number of bins it will ask if you want to interpolate the workspace to match the sample, clicking yes will cause mantid to crash, I will write up nother issue for that.

**Comment by ConorMFinn** [comment]
> if you rebin the corrections workspace so it has a different number of bins it will ask if you want to interpolate the workspace to match the sample, clicking yes will cause mantid to crash, I will write up nother issue for that.

This was the actual crash I found in #33395. Seems to be a combo of the two that was causing the crash

**Comment by Harrietbrown** [comment]
> > if you rebin the corrections workspace so it has a different number of bins it will ask if you want to interpolate the workspace to match the sample, clicking yes will cause mantid to crash, I will write up nother issue for that.
> 
> This was the actual crash I found in #33395. Seems to be a combo of the two that was causing the crash

I see, so this PR did not actually fix the issue you found. In that case we should hold off on merging and sort out the origional bug.

**Comment by sf1919** [comment]
This one wasn't designed to fix the bug @ConorMFinn encountered in testing another PR. This was additional work requested by the user when investigating the fix for #33384 . Therefore I don't see why it shouldn't be merged in.

**Comment by Harrietbrown** [comment]
Ah I see That was a missread on my part. ignore that last comment. this is fine.

**Pull request merged**
