### PR TITLE
Refactor PoldiSpectrumDomainFunction to use arbitrary peak profile functions

### PR DESCRIPTION
**Pull request by MichaelWedel**
This fixes [#10996](http://trac.mantidproject.org/mantid/ticket/10996).

### CODE REVIEW

**Comment by MichaelWedel** [comment]
Jenkins retest this please

**Comment by MichaelWedel** [comment]
Jenkins retest this please

**Comment by MichaelWedel** [comment]
**Testing information**
Make sure the modified system test for PoldiFitPeaks2D passes. For manual testing you can try the usage examples of PoldiFitPeaks2D to see if they give reasonable results. To test the new feature, you could add the `PeakProfilFunction`-parameter to the algorithm call, for example with Lorentzian (assuming you already executed the usage example):

```
PoldiFitPeaks2D(InputWorkspace=truncated_6904,
                         PoldiPeakWorkspace="peaks_refined_6904",
                         PeakProfileFunction="Lorentzian",
                         OutputWorkspace="simulated_6904",
                         RefinedPoldiPeakWorkspace="peaks_fit_2d_6904",
                         Calculated1DSpectrum="simulated_1d_6904",
                         LinearBackgroundParameter=0.01)
```

In this case the spectrum has much higher values and in the 1D spectrum the Lorentzian peaks are nicely visible.

**Comment by FedeMPouzols** [comment]
All looks perfect to me and the examples seem to work well. But I found an issue in one POLDI system test. POLDIFitPeaks2DTest fails with this error:

```
  File "<string>", line 1, in <module>
  File "/home/fedemp/mantid-repos/systemtests/StressTestFramework/stresstesting.py", line 194, in execute
    self.runTest()
  File "/home/fedemp/mantid-repos/systemtests/SystemTests/AnalysisTests/POLDIFitPeaks2DTest.py", line 15, in runTest
    self.analyseResults(dataFiles)
  File "/home/fedemp/mantid-repos/systemtests/SystemTests/AnalysisTests/POLDIFitPeaks2DTest.py", line 56, in analyseResults
    self.assertTrue(np.all(absDiff < 7e-4))
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
```

Can you check if you also get this issue. It looks like a small numerical difference could have broken the test, but it could be something local here. For me, there are values in absDiff that are definitely bigger than the 7e-4, and one of them is as big as 0.42630710526.

Otherwise I think this is ready to be merged.

**Comment by MichaelWedel** [comment]
This is still the old system test. I modified it, because the intensity calculation is a bit different now and it simply does not give the same intensities anymore. For the new system test there is also a pull request, it's this one: https://github.com/mantidproject/systemtests/pull/16. Sorry for not making it more prominent in the testing comment.

**Comment by MichaelWedel** [comment]
Jenkins retest this please

**Comment by MichaelWedel** [comment]
Jenkins retest this please

**Comment by MichaelWedel** [comment]
PoldiSpectrumDomainFunction has been updated to use changes from ticket [#11102](http://trac.mantidproject.org/mantid/ticket/11102), so that wrapping of the peak function is simpler. This is just an implementation detail, it does not change the testing information.

Additionally, the system test has been updated, so the systemtests pull request is obsolete.

**Comment by MichaelWedel** [comment]
Jenkins retest this please

**Comment by FedeMPouzols** [comment]
All is good after the system tests transition to the main repo.

**Pull request merged**
