### PR TITLE
Update tools dialogs in tomographic reconstruction GUI for new versions

### LINKED ISSUE #12898: Update the tomo GUI documentation
Between mid-June and mid/end-of-July many of the question marks that had to be left in the Tomography GUI help, concerning paths, machines, tools, etc. should be answered, as expected in several milestones of the ULTRA2 project. Update the documentation with all these details (at least tentative).

As part of this, a "what's this" button could be added as well.

In any case, it would be good to have a round of updates to the doc (as much as possible) well in time for commissioning (September/Oct/Nov).

### LINKED ISSUE #12900: Update the tool specific configuration dialogs for tomography tools
The updated versions should become available soonish:
- Tomopy 0.1.9
- Astra 1.6
Update the tool specific dialogs with the list of methods available and/or usable now.
This could be a good chance to advance a bit towards the more generic "tool configuration" mechanism, depending on deadlines.

And this could also be a good chance to add save/reload capability for the settings of the set of reconstruction tools.

This is related to #12790 .

### PR DESCRIPTION
**Pull request by FedeMPouzols**
Fixes #12900.

Also fixes #12898 for now, with more up-to-date documentation.
Uses the newer scripts and versions of the tools introduced in #14708.

**To test**:
- Code review. There are still issues with the savu related code, but this is not under our control.
- The tests of ImageROIPresenter and TomographyIfacePresenter have been updated and should pass.
- The documentation should read acceptable, and the new screenshots should display correctly (note there are several warnings and TODOs and this is growing/work in progress).
- In the run tab, local runs won't work (unless you're on the special machine "imat analysis"). There's no proper error detection/reporting for this, and this needs fixing. Remote runs should work well regardless of your local machine (assuming you have credentials for SCARF). All other tabs should behave normally.
- For a simple remote job submission you can use the "custom" tool. Set the runnable to `/work/imat/phase_commissioning/scripts/Imaging/IMAT/tomo_reconstruct.py`, and options to: `--help`
  -Remote job submissions can be double-checked at https://portal.scarf.rl.ac.uk. For astra/tomopy submissions, the scripts should get to the poin that they report that no data could be loaded if you give an inexistent input path for sample images.
- Perform few steps of an interactive session. Example:
  - open a stack of images in the "ROI, etc." tab. There is an example (from ISIS): babylon5\Public\fedemp\test_stack_larmor_summed_101510. Play with the parameters.
  - In the "Visualize" tab, explore folders, and check that you get informative error messages if you try to send files to tools that are not setup.
  - In the "Run" tab submit a few different jobs (tools, custom, etc.). I can give more examples/details.

### CODE REVIEW

**Comment by martyngigg** [comment]
Is this going to make it in to 3.6 or should it be pushed back to 3.7?

**Comment by FedeMPouzols** [comment]
@martyngigg : there are some last minute updates that need to be done this week, and I have to update the documentation with the current status of these tools.

**Comment by martyngigg** [comment]
Okay, thanks. @raquelalvarezbanos when you merge this can you keep the branch around, it can then be merged into the `release-v3.6.0` branch.

**Comment by raquelalvarezbanos** [comment]
Ok @martyngigg

**Comment by martyngigg** [comment]
I'm concious that the release is getting closer. How is this coming along?

**Comment by FedeMPouzols** [comment]
It is now ready for testing this evening / tomorrow morning.

**Comment by raquelalvarezbanos** [comment]
Thanks @FedeMPouzols can you update the testing instructions?

**Comment by martyngigg** [comment]
:+1:, thanks.

**Comment by raquelalvarezbanos** [comment]
Tested with Federico. We followed the testing instructions (submitted some jobs using different tools, ROI tab, etc) and everything works properly. Very well documented (although still in progress).

**Pull request merged**
