### PR TITLE
Fix crashing on opening interfaces in Workbench

### PR DESCRIPTION
**Pull request by dtasev**
**Description of work.**
Removes, or makes Qt4 only, the `mantidqtpython` import attempts. Doing so pulls in Qt4 libraries and seems to cause a crash when running on the Workbench.

Not 100% sure what exposed this issue, but the crashes are happening now.

**To test:**
- Open Workbench
- From `Interfaces` open:
  - `Diffraction` > `HFIR`
  - `Diffraction` > `Powder`
  - `Direct` > `DGS Reduction`
  - `SANS` > `ORNL SANS`

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@Mantid-Matthew @AnthonyLim23 Would you be able to help confirm that we haven't broken the Muon interface in MantidPlot here? I know they are not in workbench yet but only 3 files came up that had these problematic imports so we thought we should just fix them.

**Comment by martyngigg** [comment]
@peterfpeterson The SNS `reduction_gui` based python GUIs had started to crash in workbench. Could some there just confirm they are now okay?

**Review by peterfpeterson — DISMISSED** [review]
This fixes the segfault issue. However, none of the muon interfaces are available in the workbench (still).

**Comment by AnthonyLim23** [comment]
I can look tomorrow

**Review by martyngigg — APPROVED** [review]

**Comment by AnthonyLim23** [comment]
Looking at the changes the only possible break is in the frequency domain GUI and its link to the help pages. However, I cannot test it on MantidPlot as it has the CMake error I discussed last week with @martyngigg 

```
ImportError: No module named mantidqt.widgets.manageuserdirectories
  at line 10 in '<Interface>'
  caused by line 22 in 'C:\Users\BTR75544\work\SecondDev\mantid\scripts\Muon\GUI\FrequencyDomainAnalysis\frequency_domain_analysis_2.py'
  caused by line 2 in 'C:\Users\BTR75544\work\SecondDev\mantid\scripts\Muon\GUI\Common\help_widget\help_widget_presenter.py'
  caused by line 5 in 'C:\Users\BTR75544\work\SecondDev\mantid\scripts\Muon\GUI\Common\help_widget\help_widget_view.py
'```

**Comment by martyngigg** [comment]
I've just tried it locally with MantidPlot and both the help button and manager user directories buttons work on the FDA interface. Is that all I need to test?

(I will have a look at committing that patch we came up with last week today)

**Comment by AnthonyLim23** [comment]
yep

**Pull request merged**
