### PR TITLE
Abins: support "high precision" GAUSSIAN frequency calculations

### PR DESCRIPTION
**Pull request by ajjackson**
#### Summary of work
Fixes error loading GAUSSIAN calculations computed with `freq(HPModes)` option

#### Further detail of work
Some GAUSSIAN files give the phonon mode data used by Abins in two formats: a low-precision
format with X Y Z columns (which is the usual, supported, output) and a high-precision format with X Y Z components in separate rows. The existing parser is confused by this and winds up reading inconsistent numbers of columns, causing an error when the data is packed into arrays.

- [X] Add a unit test and sample data which trigger the error.
- [X] Make the pattern-matching more precise so that the low-precision format is read correctly. This allows the parser to run and we can create initial reference data for the unit test.
- [X] Add functionality to read the high-precision data if available; the unit test fails as the extra precision leads to a slight difference in results.
- [X] Verify that the difference is small
- [x] Update the test data

### To test:

Unit tests are updated

- [x] Release note is required

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by ajjackson** [comment]
I have improved the GAUSSIAN loader so that it will now read data in the high-precision format if available. As expected, this breaks the test. Unfortunately it is not trivial to compare the numbers with the files because there is a normalisation step. So I plotted spectra calculated before and after this change, and we can see the difference is pretty small as expected:

ethanol_precision

**Comment by ajjackson** [comment]
MacOS and Linux test failures look as expected. On Windows there is some kind of build failure, I will assume all is good there and update the data...

**Comment by ajjackson** [comment]
Not 100% sure this is the right place for the release note but I didn't see a Simulation section.

**Review by robertapplin — APPROVED** [review]
The code changes look really good, test data has been updated and a new test case added. Python typing has been used and each new function has its own documentation. Looks good 👍

**Pull request merged**
