### PR TITLE
Load correct grouping when field direction changes

### LINKED ISSUE #16224: Grouping can be incorrect in MuonAnalysis
**Discovered in unscripted testing #16172**

Verified this bug is *not* new - it was in 3.6 (and before) so is not a regression. 

#### Expected behaviour
When loading a file in MuonAnalysis, the correct grouping should always be loaded.

#### Actual behaviour
When switching between different configurations of the same instrument, the correct grouping for the new configuration is not always loaded.

#### Steps to reproduce the behaviour
MuSR has 2 configurations - longitudinal and transverse field.
There is a different grouping for each.
`MUSR00015190.nxs` has longitudinal field, `MUSR00022725.nxs` has transverse field (both in test data).

- Load `MUSR00015190.nxs` into MuonAnalysis. Default is to plot the `long` pair.
- Now load `MUSR00022725.nxs`. Note that `long` is still plotted, despite this dataset not having any such pair. The new grouping has not been loaded.

#### Source of bug
The check for whether to load new grouping or keep existing:
```c++
if (!noSpectraChanged && !instrChanged && isGroupingSet()) {
    // use existing grouping
} else {
    // load new grouping
}
```
This fails in the case of switching orientations of MuSR, as the instrument is the same and so is the number of spectra, but the grouping is different!

### PR DESCRIPTION
**Pull request by tom-perkins**
Load correct grouping when changing run to one with a different field direction

Fixes a bug found in MuonAnalysis where, if a new run was loaded for the same instrument as previously but a different main field direction, the new grouping was not loaded.
Now checks for main field direction as well.

Refactored out the check for reloading the grouping and added tests.

**To test:**
_Data available in unit/doc test folders_
- Open Interfaces/Muon/Muon Analysis
- Load `MUSR00015189.nxs` (longitudinal field)
- Go to "Grouping Options" tab and edit the table to add another row - for example "other" with detectors 1-3
- Back on the "Home" tab, load `MUSR00015190.nxs` (longitudinal field)
  - Grouping should not be reloaded. The "Grouping Options" tab should be the same, including the new group you just added.
- Now load `MUSR00022725.nxs` (transverse field)
  - Grouping should be reloaded for this new configuration

Fixes #16224.

[Release notes](https://github.com/mantidproject/mantid/blob/065eca5e38c8087d2be23db654e8702729d5f8ab/docs/source/release/v3.7.0/muon.rst#id4) have been updated.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
There are test failures in the MuonAnalysisHelper test.

**Comment by tom-perkins** [comment]
Tests should be fixed now

**Comment by KarlPalmen** [comment]
I've run the test (with grouping 31-64, 1-24 & 25-40) and find the grouping is preserved for both suggested files and find that the description for the MUSR00022725.nxs file in the unit tests is `musr longitudinal`.

**Comment by tom-perkins** [comment]
The grouping should be preserved for the first but not the second - I've had a look with HDFView and MUSR22725 looks transverse to me (has a 't' in `run/instrument/detector/orientation`). I've put another transverse file, `MUSR00057198.nxs`, in `\\olympic\babylon5\Scratch\TomPerkins\Data\MUSR transverse` - could you see if this one works?

**Comment by KarlPalmen** [comment]
I loaded MUSR22725 first and find it now has a transverse description. It appears that the grouping process had changed it to longitudinal.

**Comment by KarlPalmen** [comment]
I then load MUSR15189 and that has the same grouping and is transverse.

**Comment by tom-perkins** [comment]
That sounds the same as the behaviour before the fix. I don't see the same though - I've tried clean builds on Windows and Ubuntu and the fix works for me on both. 
Do your loaded workspaces contain a sample log called `main_field_direction`?

**Comment by KarlPalmen** [comment]
Yes I've found sample log `main_field_direction`.

**Comment by KarlPalmen** [comment]
Oops! I've checked out the wrong branch. I'll test correct branch.

**Comment by KarlPalmen** [comment]
Build delayed because of gmock change.

**Comment by KarlPalmen** [comment]
I'm taking tomorrow off work, so will leave this for someone else to test. If untested by the time I return, I'll test it, if it is still in release 3.7 .

**Comment by tom-perkins** [comment]
(Merged in master to fix conflict with release notes)

**Comment by martyngigg** [comment]
The code changes look sensible and tests have been added for the new reload functionality.

**Comment by martyngigg** [comment]
I've tried the steps suggested and they seem to work as expected.

I also tried a random EMU file, where we don't have a grouping file for each field direction and I didn't see any errors.

Happy to :shipit:

**Pull request merged**
