### PR TITLE
EnggFocus: fix masking of bins - also fix Engg tests for GSL 1 and 2

### LINKED ISSUE #16678: Fix Engg tests that fail with GSL2
Tests failing with GSL2: http://builds.mantidproject.org/view/All/job/master_clean-archlinux/

These two have to do with Engg algorithms:
- docs.algorithms/EnggCalibrate-v1.ExampleCalib
- SystemTests.EnggCalibrationTest.EnginXCalibrateFullThenCalibrateTest

### LINKED ISSUE #16883: Fix masking of bins in EnggFocus
Checked with Saurabh on this. The masking should be done at the beginning of EnggFocus, before applying any calibration or correction, as the default bin ranges used to suppress pulses are adjusted that way.

### PR DESCRIPTION
**Pull request by FedeMPouzols**
The masking is now done at the beginning of the algorithm.

**To test:**
- All tests should pass
- As this requires updates in the tests, I made sure that the doc and system tests now pass with both GSL 1 and 2: http://builds.mantidproject.org/view/All/job/master_clean-archlinux/442/#showFailuresLink. I tested that on Ubuntu 16.04 (xenial).

Fixes #16883.
Also fixes #16678 (which is part of #16680).

There is [a small release note](https://github.com/mantidproject/mantid/commit/13d383fbf0830220c3276ab4109425340fb5cba9) for the change in EnggFocus.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by mantid-roman** [comment]
How can you tell that #16678 is fixed?

**Comment by FedeMPouzols** [comment]
To check #16678 you need to compile and run with GSL 2. I did that on a Ubuntu 16.04 machine.
What would be harder is to make completely sure that it works with GSL 2 on all platforms.

**Comment by mantid-roman** [comment]
OK, thanks. :shipit:

**Comment by FedeMPouzols** [comment]
It seems that recent Arch distributions also come with GSL v2: http://builds.mantidproject.org/view/All/job/master_clean-archlinux/

**Comment by martyngigg** [comment]
@mantid-roman Just to confirm, you tested this with GSL2 as well?

**Comment by mantid-roman** [comment]
No I didn't. I trusted Federico.

**Comment by martyngigg** [comment]
I just ran it on my VM and it looks good.

**Pull request merged**
