### PR TITLE
Fix Muon Results Table Columns Not Updating

### LINKED ISSUE #31257: Muon results table update
The sample log names are not updated when changing them.

Open muon analysis
Load some dat
Do a fit
On the result tab, select `run number`
Click `Output Results`
Open the ResultsTable from the ADS - it should look ok
Untick the `run number` and select `run_start`
Click `Output Results Table`
The ResultsTable will have `run number` as the header but the value will be the start time

### PR DESCRIPTION
**Pull request by Matt-Cumber**
**Description of work.**
Updated column headers in table model

**To test:**
1. Open Muon Analysis
2. load some data
3. Do a fit
4. Go to results table add run_number log and output results table
5. Open the results table produce
6. With this table still open, change the sample log to start time
7. Create a new results table with the same name
8. The previous table should be closed
9. The new table should be updated

Also try running this script:
```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

tab = CreateEmptyTableWorkspace()
tab.addColumn('double', 'norm')
tab.addColumn('str', 'name')
tab.addColumn('str', 'method')

tab.addRow([1.,"Run;;Group;;a;;Asym;;#1","Estimate"])
tab.addRow([2.,"Run;;Group;;b;;Asym;;#1","Estimate"])
tab.addRow([3.,"Run;;Group;;c;;Asym;;#1","Estimate"])
tab.addRow([4.,"Run;;Group;;d;;Asym;;#1","Estimate"])

# tab.addRow([5.,"Run;;Group;;d;;Asym;;#1","Estimate"])
# tab.addColumn('str', 'added')
```

once you have run this script once, open the table tab and then uncomment the last two lines, Then with the table still open run the last two lines

Fixes #31257 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
could we have a couple of tests?

**Review by AnthonyLim23 — DISMISSED** [review]
looks good and it all works as expected :shipit:

**Review by martyngigg — CHANGES_REQUESTED** [review]
Can we add a test for this?

**Comment by Matt-Cumber** [comment]
> Can we add a test for this?

I am not sure how to add a test for this. The `load_method` that has been updated is called from `replace_workspace` here https://github.com/mantidproject/mantid/blob/master/qt/python/mantidqt/widgets/workspacedisplay/table/presenter.py#L134-L143, and the tests for that are here 
https://github.com/mantidproject/mantid/blob/master/qt/python/mantidqt/widgets/workspacedisplay/table/test/test_tableworkspacedisplay_presenter.py#L767-L785. 

However, the tests mock out a different `load_data` method which is from `presenter_standard` and is run during the tests, compared to the `load_data` method in `table_model` which is run when debugging workbench. I can't see how to correctly set up a test that directly tests the new line of code

**Comment by martyngigg** [comment]
Can we not just have an isolated unit test for the model class that knows nothing of the presenter? The method should be callable on it's own regardless of where it's called from.

**Review by martyngigg — APPROVED** [review]
Looks good. Thanks for adding that test.

**Pull request merged**
