### PR TITLE
User file load from batch

### LINKED ISSUE #22374: ISIS Sans GUI V2 does not correctly load usefile from batchfile

### PR DESCRIPTION
**Pull request by Matthew-Andrew**
Merge after #22335

**Description of work**
When specified in a batch file a user file was not being loaded into the table in the new ISIS SANS GUI.
**To test:**

* Get the ISIS test data from downloads.mantidproject.org
* The sans relevant data is in the loqdemo folder.
* Replace the .csv file with the one below
[batch_mode_reduction.csv.zip](https://github.com/mantidproject/mantid/files/1971204/batch_mode_reduction.csv.zip)
* In mantid open the ISIS SANS V2 GUI.
* Select MaskFile.txt as the userfile and batch_mode_reduction.csv as the batch file.
* Confirm that the first row of the table contains MaskFile.txt in the User File column

Fixes #22374 . 

**Release Notes** 
Have updated release notes.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [x] Are the unit tests small and test the class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] Do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by soininen** [comment]
@Mantid-Matthew Could you resolve the merge conflicts, please?

**Review by soininen — CHANGES_REQUESTED** [review]
The user file now appears in the gui. The code changes look good to me as well. I wonder if it is not possible to add a test for this?

**Comment by Mantid-Matthew** [comment]
I have added a unit test to cover the changes made to batch file parsing. I think that the userfile loading into the table is already covered by the changes however. The relevant tests are both in run_tab_presenter.py namely test_that_loads_batch_file_and_places_it_into_table and test_that_loads_batch_file_and_places_it_into_table_when_not_multi_period_enabled which have both been updated to check that the userfile is correctly added to the table. If these are not sifficient though let me know and I will add some more :).

**Comment by soininen** [comment]
Ah, sorry, I missed the test for the userfile-in-table. Anyway, there is never enough tests, so it won't hurt to add a few extra.

**Review by soininen — APPROVED** [review]

**Pull request merged**
