### PR TITLE
Fix crash on adding user function to a plot with guess present

### LINKED ISSUE #33925: Crash on trying to add "UserFunction" to a plot with a guess present
1. Load EMU00020884
2. Plot Spectrum 6
3. Click Fit on toolbar
4. Right click, "Add Other function" : ExpDecayOsc
5. Run Fit
6. Plot Guess
7. Right click, "Add Other function" : UserFunction

Mantid crashes with this stack track:
```
Name: Harriet  Email: Not provided
       Additional text:
       Added UserFunction to a plot which already had a guess plotted.
       Stack Trace:
       Traceback (most recent call last):
 File "/opt/mantidworkbenchnightly/lib/python3.8/site-packages/mantidqt/widgets/fitpropertybrowser/fitpropertybrowser.py", line 541, in function_changed_slot
   self.plot_interaction_manager.update_guess()
 File "/opt/mantidworkbenchnightly/lib/python3.8/site-packages/mantidqt/widgets/fitpropertybrowser/fitpropertybrowserplotinteraction.py", line 195, in update_guess
   self.update_guess_all()
 File "/opt/mantidworkbenchnightly/lib/python3.8/site-packages/mantidqt/widgets/fitpropertybrowser/fitpropertybrowserplotinteraction.py", line 234, in update_guess_all
   line = self._plot_guess_workspace(ws_name, fun, out_ws_name, color=color)
 File "/opt/mantidworkbenchnightly/lib/python3.8/site-packages/mantidqt/widgets/fitpropertybrowser/fitpropertybrowserplotinteraction.py", line 271, in _plot_guess_workspace
   out_ws = self.evaluate_function(workspace_name, function, output_workspace_name)
 File "/opt/mantidworkbenchnightly/lib/python3.8/site-packages/mantidqt/widgets/fitpropertybrowser/fitpropertybrowserplotinteraction.py", line 139, in evaluate_function
   alg.execute()
ValueError: Error evaluating function: Unexpected end of expression at position 0
```

This is done using the right click menu option "Add other function" followed by selecting "UserFunction"

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

Fix crash on adding user function to a plot with guess present. The algorithm EvaluateFunction returns a ValueError and not a RunTimeError if the function is invalid

**To test:**

See attached issue

Fixes #33925. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by MialLewis** [comment]
This handles the error, but it still throws with a pretty obscure error message `EvaluateFunction-[Error] Error in execution of algorithm EvaluateFunction: EvaluateFunction-[Error] Error evaluating function: Unexpected end of expression at position 0`
(I tested with a different dataset, so not sure if its different with the one specified in the issue).

I presume the error is happening as the user function has yet to be defined when added? Could we either stop an attempt to evaluate an undefined user function (and perhaps warn) or throw an error that explicitly states the user function is undefined?

**Comment by DannyHindson** [comment]
Yes that's always the message so not dataset specific and I agree it's a bit obscure. I'll add a special case in the UserFunction class that gives a better message when the formula is blank. I think the user needs some kind of message here to prompt them to go and fill in a formula in the user function because the guess curve would normally be updated automatically when a function is added.
As an aside it seems a bit of a gap in Mantid that you can't call an algorithm and decide in the calling code whether you want any exceptions raised in the algorithm to be written as error messages to the log. In this case the calling code catches and handles the exception so feels like you should be able to stop the log message getting written as well. Not one for the release though - more of a maintenance issue

**Comment by DannyHindson** [comment]
Just pushed the change discussed earlier. I also made a small change to all you to use the "Remove Guess" option after an error has been raised relating to the currently plotted guess. I noticed before that Remove Guess wasn't working in the presence of an invalid user function and it was because the ` self.guess_all_line` property was being updated with None in this scenario when it should have been left alone

**Review by MialLewis — APPROVED** [review]
Fix works well - now clear to the user what's going on. Thanks for making the change.

**Pull request merged**
