### PR TITLE
Run isCommonBins using multiple threads for greater speed

### PR DESCRIPTION
**Pull request by robertapplin**
### Description of work
This PR makes a small change which results in a speed improvement for the `MatrixWorkspace::isCommonBins` function. In turn, this means the `ExtractSpectra` algorithm is sped up by about 40%.

The red scribble square indicates the amount of time that has been shaved off the execution of this algorithm (approximately 40% the original runtime).
image

Its a very small improvement (0.1 seconds), but this algorithm is run multiple times (5) in the ReflectometryISISLoadAndProcess algorithm, which in turn gets run many times when reducing hundreds (100) of files. 0.1 * 5 * 100 = 50 seconds. This is a reduction of around 6% of the runtime of ReflectometryISISLoadAndProcess.

### To test:
Code review with extra attention in the multi-threaded section.

*This does not require release notes* because **speed improvement is minimal it probably won't be noticed on its own**

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by jclarkeSTFC — CHANGES_REQUESTED** [review]
Looks like a winner, but I think the logic in the parallel loop needs adjusting slightly.

Correct me if I'm wrong, but if hypothetically you had two threads, and each thread operated on one half (I mean one on the first half sequentially and the other on the second half) of the histograms, then because the equality comparison is always done with the next histogram in the sequence you could have a workspace with half the histograms equaling one thing, and the other half equaling another. So I'd suggest pulling out the first histogram from the parallel loop, then comparing all the other histograms in parallel with the first one.

If you have one thread, then the sequential comparison works because it's basically checking they're all equal to the first histogram by induction.

**Comment by robertapplin** [comment]
> Looks like a winner, but I think the logic in the parallel loop needs adjusting slightly.
> 
> Correct me if I'm wrong, but if hypothetically you had two threads, and each thread operated on one half (I mean one on the first half sequentially and the other on the second half) of the histograms, then because the equality comparison is always done with the next histogram in the sequence you could have a workspace with half the histograms equaling one thing, and the other half equaling another. So I'd suggest pulling out the first histogram from the parallel loop, then comparing all the other histograms in parallel with the first one.
> 
> If you have one thread, then the sequential comparison works because it's basically checking they're all equal to the first histogram by induction.

That's a good point. My only worry is that if I am sharing the first histogram across all the threads, would this cause a read access violation if two or more threads try to read the same memory address at the same time?

Maybe I could read the first histogram separately for each thread rather than pulling the first histogram out of the parallel for loop?

**Comment by jclarkeSTFC** [comment]
> > Looks like a winner, but I think the logic in the parallel loop needs adjusting slightly.
> > Correct me if I'm wrong, but if hypothetically you had two threads, and each thread operated on one half (I mean one on the first half sequentially and the other on the second half) of the histograms, then because the equality comparison is always done with the next histogram in the sequence you could have a workspace with half the histograms equaling one thing, and the other half equaling another. So I'd suggest pulling out the first histogram from the parallel loop, then comparing all the other histograms in parallel with the first one.
> > If you have one thread, then the sequential comparison works because it's basically checking they're all equal to the first histogram by induction.
> 
> That's a good point. My only worry is that if I am sharing the first histogram across all the threads, would this cause a read access violation if two or more threads try to read the same memory address at the same time?
> 
> Maybe I could read the first histogram separately for each thread rather than pulling the first histogram out of the parallel for loop?

I think reading the same memory address is thread safe, as long as no writing is going on. Accessing the first histogram within the loop will still have multiple threads reading the data from the same vector, because I think `x(0)` is going to return a pointer to the same `HistogramX` across all threads. 

But the new logic looks good I think, I'll approve it and if you want to change it then I'll re-approve.

**Review by jclarkeSTFC — DISMISSED** [review]

**Comment by robertapplin** [comment]
Thanks, I have updated it to only get the first histogram once, before the for loop

**Review by jclarkeSTFC — DISMISSED** [review]

**Review by cailafinn — COMMENTED** [review]
Is it worth adding a performance test for this? There's some existing ones in `MatrixWorkspaceTest.h` but not for the common bins check.

**Comment by robertapplin** [comment]
> Is it worth adding a performance test for this? There's some existing ones in `MatrixWorkspaceTest.h` but not for the common bins check.

I think thats a good idea. It seems MatrixWorkspaceTest.h is not being run in our CI currently, so I'll wait for that to be fixed before adding a test!

**Comment by jclarkeSTFC** [comment]
#37819 will get the test running

**Comment by jclarkeSTFC** [comment]
> #37819 will get the test running

Test should be running now

**Review by jclarkeSTFC — APPROVED** [review]

**Pull request merged**
