### PR TITLE
FQ multiple inputs crashes when more than one file is loaded

### LINKED ISSUE #28077: FQFit not working with multiple input
The FQ fit tab is currently not working when you attempt to use the multiple input options. For example:

```
FQ gui does not like reading & displaying in Multiple input.
For example, I read in 2 files - it plots data 1 but when i select data 2 it crashes.
This is on MantidPlot.
```

### PR DESCRIPTION
**Pull request by Matthew-Andrew**
**Description of work.**

The FQ tab was previously handling single and multiple inputs wrong. What is used  to do was:
  * When you loaded some data in single input mode it did a fit on all the relevant spectra from that workspace rather than just the selected one.
  * When you tried to load more than one file in multi-input mode  it crashed.

This has been updated in this PR to the following:
  * When you load a multispectrum file in single input mode it just fits the a single spectrum. This means that simultaneous fits  do nothing in this mode.
  * Multiple data inputs should now work as expected.
  * Note there is an existing issue with multiple input mode whereby it will not let  you add more than one spectrum from a single workspace unless you reload the workspace. As this has existed for some time however and the fix looks relatively  involved I am leaving it for now.

**Report to:** Spencer

**To test:**
There are several variations which should be tested  here. These mainly involve loading both single spectra and multispectra workspaces and combinations thereof in both single and multiple input modes and checking that things behave correctly. 

Example single and multi spectrum files can be found below.
[IndirectData.zip](https://github.com/mantidproject/mantid/files/4262945/IndirectData.zip)

Fixes #28077  

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by alicerussell1 — CHANGES_REQUESTED** [review]
I've found one issue, if you add multiple spectra in the `Multiple Input` tab and then try to change the plot with the drop down, it crashes.

**Review by alicerussell1 — CHANGES_REQUESTED** [review]
This fixes the issue with the drop down and it works as you'd expect. Just one thing: if you click `Fit Single Spectrum` whilst viewing any plot other than the first one loaded it does the fit however it does not update the plot.

**Review by alicerussell1 — CHANGES_REQUESTED** [review]
The `multiple input` tab now works as expected. I've just found one more thing with the `single input` tab, if you try and load in an invalid workspace, it gives the expected error box (`Workspace contains no width or EISF spectra`) but then it hard crashes when you press `ok`.

**Review by alicerussell1 — APPROVED** [review]
This looks good to me, it all now works as expected 👍

**Comment by NickDraper** [comment]
Could you please inform Spencer that this will be included in the next nightly.

**Pull request merged**
