### PR TITLE
Enable OpenMP on OS X

### LINKED ISSUE #14986: Experiment with OpenMP on OS X.
Since Mantid 3.4, the OS X bundle has lacked parallelization via OpenMP. Recently, clang 3.7 was released with OpenMP support and this issue is to see if we can use this to successfully build an OS X app bundle with OpenMP enabled.

### PR DESCRIPTION
**Pull request by quantumsteve**
Description of work.

This updates the buildscript for an experimental [build of Mantid with OpenMP enabled](http://builds.mantidproject.org/job/master_clean-osx-10.10-openmp/). 

To get Mantid to build, I had to rename a parameter. See this [bug report](https://trac.macports.org/ticket/50983) for more information.

I hope Apple will start including OpenMP in Xcode. Otherwise, someone may want to evaluate this as an alternative.

I merged in changes from #17218 so that it would build a working package.

clean build times on the same machine (ornl-mavericks) increased substantially
Xcode 7.2.1 : 44 minutes
clang 3.8.1: 57 minutes

**To test:**

Use homebrew to install and configure clang:

```
$ brew install llvm
$ ln -s /usr/local/opt/llvm/lib/libomp.dylib /usr/local/lib/libomp.dylib`
$ export CC=/usr/local/opt/llvm/bin/clang
$ export CXX=/usr/local/opt/llvm/bin/clang++
```

and build Mantid and it's tests as usual.

Fixes #14986.

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by quantumsteve** [comment]
@gvardany @OwenArnold @samueljackson92

**Comment by gvardany** [comment]
I couldn't follow the first link in the description, can you please fix?

**Comment by quantumsteve** [comment]
@gvardany fixed.

**Comment by gvardany** [comment]
I tested on Mac OS X 10.11.6, and got `-- Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS)` when running `cmake`, with `CC` and `CXX` properly set as instructed.

**Comment by quantumsteve** [comment]
@gvardany What version of CMake are you using?

**Comment by gvardany** [comment]
Had to switch temporarily to linux, can get back on Mac next week.

**Comment by peterfpeterson** [comment]
LGTM :shipit:

**Pull request merged**
