### PR TITLE
Fix SANS GUI wavelength limits bug

### LINKED ISSUE #29441: SANS GUI not recognising valid wavelength limits (and can crash)
**Original reporter:** Richard, @smk78 

### Expected behaviour
Mantid should handle valid wavelength range inputs, and handle errors gracefully.

### Actual behaviour
Valid wavelength ranges are being reported as an error or crashing Mantid.

### Steps to reproduce

- Open the ISIS SANS interface
- Load the user file `Maskfile.toml` and batch file 'batch_mode_reduction.csv' from the loqdemo in the training data
- On the Settings page, `Q, Wavelength, Detector limits` tab, in the Wavelength section, in the dropdown select `RangeLin`
- In the Ranges input, enter `1.75:2.0:16.5`
- Back on the Runs page, select a row and click Process
- You get a crash on Windows, or error `maximum recursion depth exceeded` on Ubuntu
- You get the same problem entering the range in the format e.g. `1.75-3,75,3.75-5.75,5.75-7.75`
- Note that listing wavelengths with just commas, `1.75,3.75,5.75`, etc stops with an unhelpful error message (but note that this is the same as v5.0.0):
```
The provided event slice configuration ['1.75', '3.75', '5.75', '16.5'] cannot be parsed because of 1.75
```

### Platform
Logs an error gracefully on Ubuntu but crashes on windows.

### PR DESCRIPTION
**Pull request by gemmaguest**
**Description of work.**

This PR fixes a couple of issues causing fatal errors with running a sans reduction with a custom format wavelength range (i.e. RangeLin or RangeLog in the drop-down box):
- The first issue was an infinite recursion causing a crash, caused by a setter calling itself
- The second issue was that RangeLin/RangeLog were being passed as input properties to a workflow algorithm that only accepts Lin/Log

**Report to:** @smk78  and Diego

**To test:**

- Open the ISIS SANS interface
- From the training data loqdemo subdirectory, load user file MaskFile.txt and batch file batch_mode_reduction.csv
- On the Settings page, `Q, Wavelength, Detector limits` tab, in the Wavelength section, change the Step Type to RangeLin or RangeLog and enter a range in the Ranges input, e.g. `1.75:2.0:16.5`
- On the Runs page, select a row and click Process Selected
- The reduction should run with no errors

Fixes #29441 

*This does not require release notes* because **it fixes a regression in the current release**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gemmaguest** [comment]
@DavidFair I am not sure how safe it is to change the state objects like this - let me know what you think?

**Comment by DavidFair** [comment]
> @DavidFair I am not sure how safe it is to change the state objects like this - let me know what you think?

This is okay, doing a grep across the whole repo for `RangeStepType.RANGE_LIN` or `LOG` shows that those two enum values are only used for the GUI state or user file. Where you have set it (in the State object) gets passed to the workflow alg. which is unaware of those values (hence this bug happened).

Long-term this should be tweaked around as follows:
- Convert the separate lists to a list of pairs
- Update the alg to understand what RangeLin and RangeLog means, then we get better validation too
- Remove this work-around on the front end.

This isn't the first time I've run into headaches with the wavelength range using a weird data structure, so next time I'll go ahead and change it.

However, for this release these set of changes are much less risky so I think we should stick with them :+1:

**Comment by DavidFair** [comment]
Also there is still an infinite recursion in `state_gui_model: def wavelength_range` calling `self.wavelength_range` infinitely - but I'll get that in #29483 since it requires us to store the users range limit (which we have nowhere to do at the moment) so I'll have to add the field to the state models

**Review by DavidFair — APPROVED** [review]
This works correctly with RangeLin and RangeLog correctly getting turned into Lin/Log by the algorithm and producing the wavelength steps expected

The duplication isn't ideal it's part of an overall larger problem where we have things duplicated 4x across our state objects which is out of scope.

Thanks again for fixing this

**Pull request merged**
