### PR TITLE
Indirect Data Analysis - Result workspace names are wrong

### LINKED ISSUE #24346: Indirect Data Analysis - Result workspace names don't include TeixeiraWater
**Original reporter:** Spencer

### Actual behavior
When using the Teixeira water fit type in Indirect Data Analysis, all of the result workspaces do not include TeixeiraWater in their name.
The _Result group workspace contains workspace names that remove any mention of the fit functions being used.

### Steps to reproduce the behavior
1. `Interfaces`->`Indirect`->`Data Analysis`->`ConvFit` tab
2. Load the data below
3. Select Teixeira Water as fit type
4. Tick Delta function
5. Select Flat background as the background
6. Click Run and wait

There is no mention of TeixeiraWater in the output workspace names.
The _Result workspace group contains workspaces with names that don't mention the fit type, the delta function or Flat background. This should be more like the workspaces within the _workspaces output group.

### Platforms affected
All

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR ensures that the TeixeiraWater Fit type is displayed in the name of the result workspaces as `TxWater`.
It also makes sure that the workspaces in the _Results group have the correct name.

**To test:**
**A.**
1.`Interfaces`->`Indirect`->`Data Analysis`->`ConvFit` interface
2. Load the single input data below
3. Select the One Lorentzian fit type.
4. Click Run and wait. Expand the _Results group. The name inside should be `irs26176_graphite002_conv_1L_s0_to_9_Result`.
5. Select the Multile Input tab and load in the workspaces below by clicking `Add Workspaces` and checking All Spectra.
6. Click Run and wait. The names inside the _Results group should be:
image

**B.**
1. Now go back to single input and load the data below.
2. Select TeixeiraWater as the Fit type
3. Click Run and wait. The names of the output workspaces should contain `TxWater`.

**Data Files**
Single Input: 
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2686430/irs26176_graphite002_red.zip)
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2686431/irs26173_graphite002_res.zip)

Multiple Input:
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2686430/irs26176_graphite002_red.zip)
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2686431/irs26173_graphite002_res.zip)

[irs26173_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2686432/irs26173_graphite002_red.zip)
Same resolution file as for the first workspace.

No release notes required as I believe this was introduced in #23221 

Fixes #24346 

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by reimundILL** [comment]
Ok, maybe I did not check `All Spectra`

**Comment by reimundILL** [comment]
gui

I cannot click `All Spectra`, there seems to be a single spectrum?

**Comment by SpencerHowells** [comment]
@reimundILL In Muliple input try Browsing for a single file for sample & resolution. It should then allow you to select All spectra. Then repeat Add workspace for the second pair of files.

**Comment by reimundILL** [comment]
Thank you for the instructions, I could make it run with multiple data but Mantid crashed

The terminal output:

```
AnalysisDataService-[Information] Data Object 'MultiConvFit_1L_Parameters_54' deleted from data service.
AnalysisDataService-[Information] Data Object 'MultiConvFit_1L_Parameters_55' deleted from data service.
AnalysisDataService-[Information] Data Object 'MultiConvFit_1L_Parameters_56' deleted from data service.
AnalysisDataService-[Information] Data Object 'MultiConvFit_1L_Parameters_57' deleted from data service.
AnalysisDataService-[Information] Data Object 'MultiConvFit_1L_Parameters_58' deleted from data service.
AnalysisDataService-[Information] Data Object 'MultiConvFit_1L_Parameters_59' deleted from data service.
AnalysisDataService-[Information] Data Object 'MultiConvFit_1L_Parameters_60' deleted from data service.
AnalysisDataService-[Information] Data Object 'MultiConvFit_1L_Parameters_61' deleted from data service.
AnalysisDataService-[Information] Data Object 'MultiConvFit_1L_Parameters' deleted from data service.
AnalysisDataService-[Information] Data Object '__ConvolutionFitSequential_ws1' deleted from data service.
AnalysisDataService-[Information] Data Object '__ConvolutionFitSequential_ws2' deleted from data service.
ConvolutionFitSequential-[Notice] ConvolutionFitSequential successful, Duration 17.41 seconds
BatchAlgorithmRunner-[Information] Algorithm "ConvolutionFitSequential" finished
RenameWorkspace-[Notice] RenameWorkspace started
RenameWorkspace-[Information] Algorithm: RenameWorkspace v1
RenameWorkspace-[Information] Execution Date: 2018-12-20 10:15:40.178403000
RenameWorkspace-[Information] Execution Duration: -1 seconds
RenameWorkspace-[Information] UUID: 527ab97c-478b-4276-94e1-18fd1c164f4e
RenameWorkspace-[Information] Parameters:
RenameWorkspace-[Information]   Name: InputWorkspace, Value: MultiConvFit_1L_Results_1, Default?: No, Direction: Input
RenameWorkspace-[Information]   Name: OutputWorkspace, Value: irs26176_graphite002_ConvFit_1L_Result, Default?: No, Direction: Output
RenameWorkspace-[Information]   Name: RenameMonitors, Value: 0, Default?: Yes, Direction: Input
RenameWorkspace-[Information]   Name: OverwriteExisting, Value: 1, Default?: Yes, Direction: Input
AnalysisDataService-[Information] Data Object 'MultiConvFit_1L_Results_1' renamed to 'irs26176_graphite002_ConvFit_1L_Result'
RenameWorkspace-[Notice] RenameWorkspace successful, Duration 0.00 seconds
RenameWorkspace-[Notice] RenameWorkspace started
RenameWorkspace-[Information] Algorithm: RenameWorkspace v1
RenameWorkspace-[Information] Execution Date: 2018-12-20 10:15:40.183751000
RenameWorkspace-[Information] Execution Duration: -1 seconds
RenameWorkspace-[Information] UUID: b4d4a562-bbf9-4c93-9ab8-68ae23caca7a
RenameWorkspace-[Information] Parameters:
RenameWorkspace-[Information]   Name: InputWorkspace, Value: MultiConvFit_1L_Results_2, Default?: No, Direction: Input
RenameWorkspace-[Information]   Name: OutputWorkspace, Value: irs26173_graphite002_ConvFit_1L_Result, Default?: No, Direction: Output
RenameWorkspace-[Information]   Name: RenameMonitors, Value: 0, Default?: Yes, Direction: Input
RenameWorkspace-[Information]   Name: OverwriteExisting, Value: 1, Default?: Yes, Direction: Input
AnalysisDataService-[Information] Data Object 'MultiConvFit_1L_Results_2' renamed to 'irs26173_graphite002_ConvFit_1L_Result'
RenameWorkspace-[Notice] RenameWorkspace successful, Duration 0.00 seconds
MantidPlot: /usr/include/boost/smart_ptr/shared_ptr.hpp:648: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = Mantid::API::MatrixWorkspace; typename boost::detail::sp_member_access<T>::type = Mantid::API::MatrixWorkspace*]: Assertion `px != 0' failed.
Aborted
```

This is not the full output (I can send if required).

**Comment by reimundILL** [comment]
I'll have a look this afternoon.

**Review by vreimund — APPROVED** [review]
Workspace names are corrected, different than in the issue description, but seem to be fine:

workspacenamesa
workspacenamesb

But I could stress Mantid to crash, terminal says:
```
AnalysisDataService-[Information] Data Object 'irs26176_graphite002_conv_TxWater_s0_to_50_Parameters_46' deleted from data service.
AnalysisDataService-[Information] Data Object 'irs26176_graphite002_conv_TxWater_s0_to_50_Parameters_47' deleted from data service.
AnalysisDataService-[Information] Data Object 'irs26176_graphite002_conv_TxWater_s0_to_50_Parameters_48' deleted from data service.
AnalysisDataService-[Information] Data Object 'irs26176_graphite002_conv_TxWater_s0_to_50_Parameters_49' deleted from data service.
AnalysisDataService-[Information] Data Object 'irs26176_graphite002_conv_TxWater_s0_to_50_Parameters_50' deleted from data service.
AnalysisDataService-[Information] Data Object 'irs26176_graphite002_conv_TxWater_s0_to_50_Parameters_51' deleted from data service.
AnalysisDataService-[Information] Data Object 'irs26176_graphite002_conv_TxWater_s0_to_50_Parameters' deleted from data service.
AnalysisDataService-[Information] Data Object '__ConvolutionFitSequential_ws1' deleted from data service.
AnalysisDataService-[Debug] Add Data Object irs26176_graphite002_conv_TxWater_s0_to_50_Parameters successful
AnalysisDataService-[Debug] Data Object 'irs26176_graphite002_conv_TxWater_s0_to_50_Results' replaced in data service.

AnalysisDataService-[Debug] Data Object 'irs26176_graphite002_conv_TxWater_s0_to_50_Workspaces' replaced in data service.

ConvolutionFitSequential-[Debug] Time to validate properties: 0.000059 seconds
Time for other input validation: 0.000049 seconds
Time for other initialization: 0.005428 seconds
Time to run exec: 8.486943 seconds

ConvolutionFitSequential-[Notice] ConvolutionFitSequential successful, Duration 8.49 seconds
ConvolutionFitSequential-[Debug] Unlocking irs26176_graphite002_conv_TxWater_s0_to_50_Results
BatchAlgorithmRunner-[Information] Algorithm "ConvolutionFitSequential" finished
MantidApplication-[Fatal] Unexpected exception: vector::_M_range_check: __n (which is 51) >= this->size() (which is 51)
Segmentation fault
```
This may be unrelated to this issue but should be investigated.

**Comment by robertapplin** [comment]
@reimundILL Ah yes, I forgot to change the description - those workspace names are now correct

**Comment by martyngigg** [comment]
@robertapplin Is the crash related?

**Comment by robertapplin** [comment]
@martyngigg I don't see how this could be related as the only thing I have changed is the output name provided to the RenameWorkspace algorithm, but I will have a closer look.
@reimundILL did you get this crash by following the steps in the description? If not could you send me the workflow you used?

**Comment by reimundILL** [comment]
I followed the instructions for testing first and everything went fine. This is why I believe that this PR is valid. Code changes look good to me.

Generally, for GUI testing, I push all possible buttons and wait and see. Project Recovery failed. I did not change the input data, but changed the fit type (sequential fit, ...) and rerun. I try to generate an example, I believe this can be reproduced easily (with the effort of taking detailed notes).

**Comment by robertapplin** [comment]
Thanks @reimundILL . @martyngigg It looks like this crash is unrelated - I will create an issue for this

**Comment by martyngigg** [comment]
Thanks, @robertapplin

**Pull request merged**
