### PR TITLE
Refs #17412. Minor refactoring of LoadMLZ.

### LINKED ISSUE #17412: LoadMLZ correct metadata types
### Expected behavior
Numeric metadata (monitor counts, temperature, etcetera) must be presented as numeric sample logs and have units if appropriate.

### Actual behavior
Most of numeric metadata are presented as strings.

### Platforms affected
All

I assign myself for this issue.

### PR DESCRIPTION
**Pull request by mganeva**
Minor refactoring of LoadMLZ to fix the mentioned issue.

**To test:**
Load the TOFTOF test data:

``` python
ws = LoadMLZ(Filename='TOFTOFTestdata.nxs')
```

Click 'Sample Logs...' to check that numeric metadata have type 'numeric'.

Fixes #17412.

Does not need to be in the release notes.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
I cannot find branch mganeva:refactor_load_mlz.

**Comment by mganeva** [comment]
@KarlPalmen It should be here, in my fork: https://github.com/mganeva/mantid/tree/refactor_load_mlz

**Comment by KarlPalmen** [comment]
Sorry I don't know how to test that. Please follow Mantid Workflow for GIT http://www.mantidproject.org/Working_with_git

**Comment by mganeva** [comment]
As an external developer, I have no access to create branches directly in Mantid repository.

**Comment by KarlPalmen** [comment]
Thank you for letting me know.

**Comment by peterfpeterson** [comment]
@KarlPalmen look at the `command line instructions` for how to merge the branch into your checkout. Just do "step 1." However, since @mganeva is a frequent contributor, it wouldn't be a bad idea to [add a remote](https://git-scm.com/docs/git-remote).

**Comment by mganeva** [comment]
The RHEL7 build has failed due to the SystemTests.HFIRTestsAPIv2.HFIRTestsAPIv2. May I ask someone to restart it?

**Comment by peterfpeterson** [comment]
Don't bother, that is a known intermittent failure that isn't related to the changes introduced here. Looking things over, I say :shipit: !

**Comment by mganeva** [comment]
@peterfpeterson Thanks!

**Pull request merged**
