### PR TITLE
Re-add Coverage Tooling

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**
- Removes coveralls which has been dead since 2018
- Adds gcov / gcovr support for C++ coverage reports
- New docs for said tooling
- Various minor fixes mostly to docs as we were setting up envs

@StephenSmith25 Could you add `gcovr` to the list of package for Conda OSX too?

**To test:**
- Follow instructions in docs, does it all work

There is no associated issue. - Tooling for #31069 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by gemmaguest — APPROVED** [review]
Looks good, really nice to have coverage again :+1:

**Comment by martyngigg** [comment]
It's definitely a bit premature to add this to the PRs but shall we at least setup a build of master that would run either each merge or at least once a day to start tracking it. We could at least have someone check it to see if there are horrendous dips like when we accidentally stopped running some tests?

**Comment by DavidFair** [comment]
@martyngigg I agree completely

We (myself and Gemma) are planning on using this as part of the work in reflectometry, so I'm going to setup a job that runs this on master in the coming days. That way it's obvious where we have gaps on the widget we're planning on refactoring.

Regarding running on PRs, this is a bit interesting as we need to run in Debug mode for accurate results. On the one hand I want to make it unit tests only if we have a PR (as system tests will quickly bump us up to 100% through using code rather than testing it). On the other hand, we've been gradually getting our turn around times for testing down with cppcheck skipping etc. 
I suspect the debug mode tests will slow PR times down overall and be one of the most likely to fail.

Long-term based on auto reduction it's good to add a check that coverage stays the same or increase. This brought their coverage from ~25% up to ~70% in 2-3 years organically and helps ensure things like interfaces actually get tested (as it can be hard during a review to understand how changes affect it). So I'm on the fence

**Comment by martyngigg** [comment]
I feel this is important enough that having a target of it running on pull requests in some shape of form is a good goal - as you say it really only causes people to think when it is in their faces.

We can work out the exact mechanics later but even a debug build running the unit tests will most probably beat the system tests (?) so as long as that's true it won't actually add extra time for the whole suite of checks.

**Pull request merged**
