### PR TITLE
Update ParaView 

### LINKED ISSUE #12719: Migrate to newer ParaView
This issue was originally [TRAC 11881](http://trac.mantidproject.org/mantid/ticket/11881)

We would like to move VATES from ParaView 4.3.1 to a later snapshot so that we can use the new features from our latest contract and also ease our move to ParaView 5. The SHA1 Utkarsh suggests is `b40280a2f274aa27aac707abf9097317f731dcc1` from May 31, 2015

### PR DESCRIPTION
**Pull request by quantumsteve**
This fixes #12719.

We would like to move VATES from ParaView 4.3.1 to a later snapshot so that we can use the new features from our latest contract and also ease our move to ParaView 5. We chose `SHA1 = b40280a2f274aa27aac707abf9097317f731dcc1` from May 31, 2015. The required changes were quite minor, and I started making a few changes for the new Grid Axes.

The [release notes](http://www.mantidproject.org/ReleaseNotes_3_5_UI_Changes#3D_Visualisation_.28VSI.29) have been updated.

testing: Try loading, viewing and manipulating a few datasets in the VSI and verify that the current (mantid 3.4) functionality remains unaffected. Issues with new functionality will be resolved in separate pull requests. 

Linux and Windows testing is especially useful, as most of my work was done under OS X.

### CODE REVIEW

**Comment by quantumsteve** [comment]
The windows/ubuntu builds seem to fail on the packaging sporadically. Our best guess is that this is because the builds are incremental.

**Comment by AndreiSavici** [comment]
Things are working fine with Ubuntu

**Comment by peterfpeterson** [comment]
Looks like @OwenArnold is verifying on windoze.

**Comment by martyngigg** [comment]
Apart from the Python thing that I'm working on in #13080 then I don't see any problems.

**Comment by OwenArnold** [comment]
Works for me on windows

**Pull request merged**
