### PR TITLE
Fix sans gui catching wrong exception

### LINKED ISSUE #28097: SANS - Variable Q Binning not recognised in enum
**Original reporter:** ISIS/Steve

### Expected behavior
- Open a user file, such as the LOQ dataset
- In Q, Wavelength, Detector Limits change the step type for Q1 to variable and enter
`0.007,-0.05,0.255,0.0125,1.4`
- Attempt to process any data
- A value error is thrown

### Actual behavior
Variable binning is not recognised as an enum

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**
Fixes an incorrectly caught exception for the SANS data processor GUI. This restores the original behaviour or returning None if we couldn't cast to an enum to represent Variable binning (I know....)

**To test:**
- Open the SANS GUI
- Open the LOQ mask file in the ISIS data set
- Open the batch file in the same folder
- Go to settings -> Q, Wavelength.... -> Q Limits
- In the Q1D row change the step type to `Variable`
- Change the Rebin String to `0.007,-0.05,0.255,0.0125,1.4`
- Go back to the main window and hit process all
- It should either succeed or fail with a missing file `DIRECT_LOQ_MAIN_143B.TXT` (which means we fixed the serialisation of the GUI which was failing)

Fixes #28097 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by Harrietbrown — DISMISSED** [review]
Good job. The ISIS SANS gui no longer raises an error when processing with a variable step type. The failing jenkins are unrelated.

**Comment by martyngigg** [comment]
Are the failing tests here real?

**Comment by Harrietbrown** [comment]
Oh you are right the python failures look real. My bad for not spotting that.

**Comment by DavidFair** [comment]
Sigh it's Python 2 incompatibility, I'll wrap this in a Python 3 check since all of our users will be using 3 onwards

**Comment by martyngigg** [comment]
@Harrietbrown Could you give this a quick check again and I'll merge it if you are happy?

**Review by Harrietbrown — APPROVED** [review]
The bug is still fixed with this commit, and the python3 check has fixed the failing jenkins test.

**Pull request merged**
