### PR TITLE
Refl GUI searches ICAT Asynchronously

### LINKED ISSUE #14905: Make ICAT Search run asynchronously to Refl GUI
This is a sub-issue of #14193

Currently the ICAT search is done through [this method](https://github.com/mantidproject/mantid/blob/master/MantidQt/CustomInterfaces/src/Reflectometry/ReflCatalogSearcher.cpp#L14). This is currently done is series, however it may be possible to use the AlgorithmRunner and do this asynchronously.

### PR DESCRIPTION
**Pull request by MattKing06**
Currently it is working and the search table is populated but this is just a scratch way of doing things, hopefully with some review this can be made into a robust solution.

**To test**: 
- Load up Reflectometry (Polref) GUI (`Interfaces > Reflectometry > ISIS Reflectometry (Polref)`)
- Change search instrument from `INTER` to `POLREF`
- Change transfer method from `Description` to `Measurement`
- Enter investigation ID `1520249`
- Press search
- Login into ICAT data service
- Ensure that the search table is now populated with search results.

**Release notes**: 
Functionality has not changed from the user's point of view so no update needed
Fixes #14905

### CODE REVIEW

**Comment by MattKing06** [comment]
Build failures are due to not updated the MockView in the tests. Once the review has been completed and a more robust solution is available these should be updated.

**Comment by MattKing06** [comment]
Console ouput from RHEL6 build

http://builds.mantidproject.org/job/pull_requests-rhel6/4518/consoleFull

**Comment by FedeMPouzols** [comment]
This works well and the code looks good.

But I get this warning from Qt: `QMetaObject::connectSlotsByName: No matching signal for on_icatSearchComplete_triggered()`. This doesn't prevent the code from working correctly, as you are connecting the slot `icatSearchComplete` with `connect()`.
The warning is saying that Qt interprets your slot name as something like `void on_button_clicked();` but it cannot find any widget or object called `icatSearchComplete` with a signal called `triggered`. Note that the other slots that you have in `QtReflMainView.h` are named like `on_actionNewTable_triggered()` but the hidden/underlying assumption is that for them there is an object defined in the `.ui` file named `actionNewTable` which has a signal named `triggered`. To avoid this warning you can simply omit the `on_` prefix. I'd also remove the `_triggered` suffix, as in the Qt world `_triggered()` suggests that it is a "triggered" signal/slot as you would have with Qt QAction objects, while your `icatSearchComplete` is a very custom slot that you're defining and is of a different kind.
This `on_..._triggered()`, `on_.._clicked()` etc. mechanism to connect slots by name can be misleading sometimes:
http://doc.qt.io/qt-4.8/qmetaobject.html#connectSlotsByName
http://stackoverflow.com/questions/24383845/qmetaobjectconnectslotsbyname-no-matching-signal-for-error-when-building-on

**Comment by MattKing06** [comment]
Thanks @FedeMPouzols I've implemented those changes and I no longer see the QMetaObject warning about connecting signals

**Pull request merged**
