### PR TITLE
Build documentation in vanilla Python instead of MantidPlot

### LINKED ISSUE #28647: Build documentation with workbench only
When updating to Ubuntu 20.04, I realized that I cannot build documentation any more (no QT4 means no Mantidplot)

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Switches the `docs-` build targets to use the mantidpython wrappers rather than MantidPlot. This required ensuring the screenshot tools could cope with having to start a QApplication object themselves. There has also been some general clean ups in the directives along with some new CMake options to control the docs build. The aim of these options is to reduce the time it takes to build the documentation. A full build took ~15min on my Ubuntu 18.04 box with decent NVMe drive. The options disable various directives, in particular `:plot:`, so that previewing documentation changes does not require a long build time. With all new options set to off the build time is ~1.5min on the same machine. 

**To test:**

Look at the documentation changes and check they make sense. Try out the new CMake options and make sure you can still build the documentation.

Fixes #28647

*This does not require release notes* because **as it is an internal change.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AndreiSavici** [comment]
I don't see `docs-html` or `docs-qthelp` targets on Ubuntu 20.04, even though I have the `ENABLE_DOCS` checked

**Comment by martyngigg** [comment]
@AndreiSavici Nice catch. I'd missed that `docs` was wrapped in an `ENABLE_MANTIDPLOT` check.

**Comment by AndreiSavici** [comment]
Almost there. In `docs/CMakeLists.txt` it still looks for `QT_QCOLLECTIONGENERATOR_EXECUTABLE`. I was able to build the qthelp if I replace that with `QHELP_EXECUTABLE`

**Comment by martyngigg** [comment]
Thanks, @AndreiSavici. I think this should be fixed now. I've also wrapped that target in an `ENABLE_WORKBENCH` as we probably don't want it if we're not building that.

**Review by AndreiSavici — APPROVED** [review]
The framework for building documentation and running doc tests works. Warnings and failing doc tests should be addressed in a separate issue (#29733)

**Pull request merged**
