### PR TITLE
ITableWorkspace now updates GUI when data changed via Python

### LINKED ISSUE #22917: Running setCell on a TableWorkspace does not update an open view in MantidPlot
**Original reporter:** Lewis Edwards (ISIS)

### Expected behavior
Running `setCell` on a table workspace that has an open view in MantidPlot should update the data in the view.

### Actual behavior
Running `setCell` on a table workspace that has an open view in MantidPlot does not change the data in the view.

### Steps to reproduce the behavior
Here's a script to reproduce the issue
```python
from mantid.api import WorkspaceFactory
tbl = CreateEmptyTableWorkspace()

tbl.addColumn("double", "l")
tbl.addColumn("double", "k")
tbl.addColumn("double", "h")

tbl.addRow([1,1,1])

# Go open table and view data

tbl.setCell(0,0, 100)
```

### Platforms affected
All

### PR DESCRIPTION
**Pull request by Pasarus**
**Description of work.**
Made sure that setCell, addColumn, setPlotType and addRow when used in the script interpreter or the script window, update any open windows, by utilizing ITableWorkspace::modified()

**Report to:** Lewis Edwards (ISIS) 

**To test:**

- Create empty table:
```python
from mantid.api import WorkspaceFactory
tbl = CreateEmptyTableWorkspace()

tbl.addColumn("double", "l")
tbl.addColumn("double", "k")
tbl.addColumn("double", "h")

tbl.addRow([1,1,1])
```
- Open the table as a window first.
- Then Test using the commands:
```python
# test if setCell method updates gui
tbl.setCell(0,0, 100)

# test if the addColumnSimple method updates gui
tbl.addColumn("double", "p")

# test if addColumn method updates gui
tbl.addColumn("double", "tt", 0)

# test if addRow method updates gui
tbl.addRow([0,0,0,0,0])

# test if addRowFromDict updates gui
tbl.addRow({"l" : 0, "k" : 1, "h" : 2, "p" : 3, "tt" : 4})

# test if setPlotType updates gui
tbl.setPlotType("tt", 2)
```

Fixes #22917 

Does this update require release notes?
- [x] Yes
- [ ] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by KarlPalmen — CHANGES_REQUESTED** [review]
Test as described worked, but then I tried removeColumn and that did not update. Removal functions need attention.

**Comment by Pasarus** [comment]
Rebasing onto master

**Comment by Pasarus** [comment]
@KarlPalmen I believe from some basic investigation that it is outside the scope of this PR, this is because it isn't to do with ITableWorkspace, it is an implemented function on each of the things importing from ITableWorkspace, as it is just a virtual function.

**Comment by KarlPalmen** [comment]
In this case, a separate issue needs to be created for this.

**Comment by Pasarus** [comment]
Issue created: #23237

**Review by KarlPalmen — APPROVED** [review]

**Review by martyngigg — COMMENTED** [review]
This is a good usability update.

Is there any reason we couldn't move the modified call in to the C++ `TableWorkspace` object when things like `addColumn` are called. That way we are always covered and we don't have to worry that it won't emit a signal  in some place?

**Comment by Pasarus** [comment]
I was unable to find a way to actually perform the action in the C++ file as it is unable to find the relevant classes for it, if you could recommend a way to do it, I don't see why we can't... but this does seem to do the job.

**Comment by martyngigg** [comment]
My first thought was in places such as just before the return statement in [TableWorkspace::addColumn](https://github.com/mantidproject/mantid/blob/2fb90328222d141e55586cfc8c36f90358047c7e/Framework/DataObjects/src/TableWorkspace.cpp#L89) . Would this work?

**Comment by Pasarus** [comment]
I have moved what I can to C++ more core side, however some still need to be in the exports, because they physically do not exist anywhere else.

**Comment by martyngigg** [comment]
@Pasarus That's great; this is exactly what I meant. Now if we have another wrapper around something that calls addColumn in Python for example we won't have to worry about it calling modified.

**Review by martyngigg — APPROVED** [review]
Functionality still works after the updates. :+1:

**Comment by peterfpeterson** [comment]
Please notify Lewis Edwards that this was merged into `master`.

**Pull request merged**
