### PR TITLE
ConvertSpectrumAxis to support elastic d-spacing

### LINKED ISSUE #19922: ConvertSpectrumAxis to support dSpacing
ConvertSpectrumAxis needs support for dSpacing conversion in Elastic mode.

### PR DESCRIPTION
**Pull request by gvardany**
This PR extends `ConvertSpectrumAxis` algorithm to support a new target `ElasticDSpacing`.

**To test:**
```
ws = CreateSampleWorkspace()
q = ConvertSpectrumAxis(ws, Target="ElasticQ", EMode="Direct", EFixed=20.)
d = ConvertSpectrumAxis(ws, Target="ElasticDSpacing", EMode="Direct", EFixed=20.)
```

Check that the spectrum axis for `d=2*PI/q`. Note that they will be sorted ascending in both.

Fixes #19922 . 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by josephframsay — CHANGES_REQUESTED** [review]
This gets the `Fatal Python error: PyEval_RestoreThread: NULL tstate` error when I try to run MantidPlot from Ubuntu - could you try merging with `master`?

**Comment by gvardany** [comment]
I have merged master, can you please try again?

**Comment by josephframsay** [comment]
Apologies, I didn't realise that I don't actually know what spectrum axis means. I get the following workspaces for `d` and `q`. I can't see anywhere where there is constant of proportionality of `2 * PI`, but I might be looking in the wrong place?
 
convertspectrumaxis

**Comment by gvardany** [comment]
I have highlighted the spectrum axis here. Since one is the reciprocal of the other you should compare in inverse order, i.e. first to last.

30065641-7803e760-924d-11e7-93b1-67c91d4fb767

**Review by josephframsay — APPROVED** [review]

**Comment by josephframsay** [comment]
Ah, I see. In that case, everything looks good to me!

**Comment by SimonHeybrock** [comment]
There is a merge conflict now.

**Pull request merged**
