### PR TITLE
Add librdkafka to RHEL and Ubuntu CPACK dependency list

### LINKED ISSUE #19326: librdkafka dependency missing from Ubuntu and RHEL packages
Add librdkafka dependency to https://github.com/mantidproject/mantid/blob/master/CMakeLists.txt for Ubuntu and RHEL.

### Expected behavior
LiveData to work.
### Actual behavior
LiveData library isn't loading because librdkafka is missing from the package dependency list. MantidPlot displays error messages in the log about LiveData library not being present.
### Steps to reproduce the behavior
Install Mantid package and run MantidPlot.
### Platforms affected
RHEL and Ubuntu

### PR DESCRIPTION
**Pull request by matthew-d-jones**
Added librdkafka to the dependencies for Ubuntu and RHEL packages.

**To test:**

*Needs testing on Ubuntu and RHEL only*
`.deb` and `.rpm` are available here (if at ISIS): smb://olympic/babylon5/Scratch/Matthew%20Jones

Use Mantid installer then launch MantidPlot. If there is still a problem there would be an error message in the log, for example: `Could not open library /opt/mantidnightly/plugins//libMantidLiveData.so: librdkafka++.so.1: cannot open shared object file: No such file or directory`.

Fixes #19326 .

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AntonPiccardoSelg** [comment]
* `Ubuntu 16.04`:  I installed the `.deb` file on and can open it without an errors messages.  LGTM
* `Rhel 7`: ???

**Comment by mducle** [comment]
Installed the rpm on a RHEL 7 machine. It initially complained that `librdkafka` was missing. Manually installing kafka and the rpm and then running mantid-unstable works.

**Comment by AntonPiccardoSelg** [comment]
The PR fixes the issue for Ubuntu 16 and Rhel 7 as described. Please :shipit:

**Comment by peterfpeterson** [comment]
It should be added to the developer packages as well.

**Pull request merged**
