### PR TITLE
Use boost::accumulator_set instead of handwritten functions

### PR DESCRIPTION
**Pull request by quantumsteve**
I tried using the [Boost.Accumulators library](http://www.boost.org/doc/libs/1_60_0/doc/html/accumulators.html) to calculate statistical quantities. I think it is something we should consider using in Mantid.

No release notes

code review: Any significant downsides to using this library?

testing: The current unit tests should be sufficient for double-checking the quantities calculated.

### CODE REVIEW

**Comment by peterfpeterson** [comment]
Did you switch to `HINTS` because of a technical reason?

**Comment by quantumsteve** [comment]
No, just thought environment variables for finding libraries were ugly and currently not used in any buildscript.

**Comment by quantumsteve** [comment]
Unfortunately, we don't check Linux distros until well after finding boost.

**Comment by FedeMPouzols** [comment]
This looks good.

Maybe the accumulator functionality could be considered for the algorithms building blocks, or somehow promoted among algorithms writers, @SimonHeybrock?  I think we have quite a few algorithms that do this kind of cumulative calculations. It seems that this library makes it very easy to calculate quantiles, moments, cdfs, etc.

**Comment by SimonHeybrock** [comment]
@FedeMPouzols Yes, I have thought of things like accumulation. For algorithms, basically we need a way to make it work with threading. Should not be too hard, but there is no out-of-the-box solution in boost, as far as I know.

**Pull request merged**
