### PR TITLE
Workbench: Set QTool flags on figure window and add option to disable

### LINKED ISSUE #27883: Unable to edit script while a plot is open
It has been reported that in workbench, when a plot is open, it is impossible to click and edit the script in the script window. This has been observed on Ubuntu with xfce or XUbuntu.

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Attempts a different method at keeping plots on top of the Workbench window to avoid issues with window managers being confused when we tried to force the figure window to the top of the stack. Some like Xfce did not ever relinquish focus back to the main window.

Ideally this would go on to master at this point in the dev cycle but the problem exist on IDAaaS and is not so esoteric as first thought so we have little choice but to fix it.

**To test:**

A new setting "Plots on Top" has been introduced. This should be testing with both default on and setting it off.

* Create some data and make different types of plot
* By default the plot window should stay on top of the main window.
* Try opening interfaces
* Try moving the plots to separate monitors
* Both with plots open and no plots on the screen try changing the "Plots on Top"  setting in "Settings->Plots" and observe the plots change from "floating" to "on top".

Fixes #27883

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Mantid-Matthew** [comment]
I'm checking this on windows

**Comment by DanielMurphy22** [comment]
On Mac, 
*Bad*: ManageUserDir and Settings show up behind any plots
*Good*: Can minimise and works with Plots Toolbox

**Comment by martyngigg** [comment]
After discussion with @DanielMurphy22 & @Mantid-Matthew we've decided that this behaviour is equally not great and we are going to have to have platform-specific behaviour.

**Comment by martyngigg** [comment]
@DanielMurphy22 @Mantid-Matthew I've made some changes here. I've removed the `Plots on Top` setting as if we are introducing a setting I would rather it applied to all windows equally.

I have also arranged the code in preparation for applying the flags to other windows, i.e. I've moved the functions to get the correct parent and flags to the main workbench `config` window but I have **not** applied those changes to any other windows other than plots.

If you have some time I would appreciate a test drive.

**Comment by martyngigg** [comment]
@DanielMurphy22 I think this should be ready to test again now.

**Comment by DanielMurphy22** [comment]
On Mac, plotting a spectrum then closing the plot window, didn't remove it from the plots toolbox, so you can make mantid try to show it again, even though it no longer exists. Checked and this is not an issue on Windows. This is a Mac only issue.

**Comment by Mantid-Matthew** [comment]
I think Daniels already done this but just to confirm had a quick test and this works nicely for me on windows. Possibly in the future may be worth considering parenting and unparenting the windows when they are maximised and minimised so that the plots collapse into the toolbar but I don't think that is a job for now.

**Comment by martyngigg** [comment]
My last push should have fixed the problem on macOS. We weren't disconnecting signals before destroying the window in the figure manager leading to possibly spurious activation events causing a new plot entry to be added.

**Comment by DanielMurphy22** [comment]
Annoyingly on Mac, Plots stay on top of everything, such as interfaces, settings, MUD, Instrument view, show data...
Also, on Linux minimising a plot window isn't possible.

This close to a release this is a good compromise and the plots existing problem on Mac has been fixed! I've opened an issue for future improvement to this: #28222

**Review by DanielMurphy22 — APPROVED** [review]

**Pull request merged**
