### PR TITLE
Ignore NaNs in NormaliseSpectra

### LINKED ISSUE #32510: NormaliseSpectra changes every values to NaN when spectrum contains a single NaN
**Describe the bug**

`NormaliseSpectra` algorithm changes all values to NaN if a single NaN is present in the spectrum.

This is due to the use of [`numpy.amax`](https://numpy.org/doc/stable/reference/generated/numpy.amax.html) here:
https://github.com/mantidproject/mantid/blob/2dd89c6a52bb0167cebf8d51faac11bc005999bc/Framework/PythonInterface/plugins/algorithms/NormaliseSpectra.py#L47

**Expected behavior and solution**

`NormaliseSpectra` should ignore the NaNs. Switching to [`numpy.nanmax`](https://numpy.org/doc/stable/reference/generated/numpy.nanmax.html) should solve the problem.

**To Reproduce**

* create a workspace
* change one value in each spectrum to NaN
* apply `NormaliseSpectra`
* observe the data

Here is a test script:
```python
from mantid.simpleapi import CreateSampleWorkspace, NormaliseSpectra
import numpy as np

ws = CreateSampleWorkspace()
for sp in range(ws.getNumberHistograms()):
    dataY = ws.dataY(sp)
    dataY[0] = np.nan
    
ws2 = NormaliseSpectra(ws)
```

### PR DESCRIPTION
**Pull request by gui-co**
**Description of work.**

With this PR, the NaNs are now ignored in `NormaliseSpectra`.

**To test:**

Use the script provided in the issue description.

Fixes #32510

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by RichardWaiteSTFC — DISMISSED** [review]
Fixes the issue and test - @martyngigg does this seems low risk enough that it could go in the release?

**Comment by martyngigg** [comment]
Yes I think this is low-risk enough to go in. @gui-co Could you change the target branch and rebase if necessary?

**Comment by gui-co** [comment]
@RichardWaiteSTFC and @martyngigg, I changed the target branch and rebased. Could you re-approve ?

**Review by RichardWaiteSTFC — APPROVED** [review]
Re-approving post rebase

**Pull request merged**
