### PR TITLE
Update to the latest version of mslice

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Brings in the latest fixes for the mslice interface.

**To test:**

Check that [this](https://github.com/mantidproject/mslice/pull/509) fix works in the shipped version of mslice.

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by mducle — CHANGES_REQUESTED** [review]
@martyngigg The linked issue is ok - e.g. running the script within MantidPlot/workbench now does not crash. But in testing I've found a bunch of other issues:

* Plot a cut from the `MD Histo` tab after you've saved it to the ADS (using the `Save to Workbench` / `Save to MantidPlot` button) will cause the sad alien to appear but allows you to continue (soft crash).
* Plot a slice and click the save (floppy) icon but then `Cancel` the dialog also causes a soft crash.
* Plot a series of plots and then enable the `Waterfall` option then save the resulting plot as a script. If you run the script this will cause a hard crash (cannot continue with MantidPlot/Workbench).

Also there is one functionality bug:

* If you plot a slice, save it as a script and run the script. In the plot window created by the script the recoil / Bragg line overplotting functionality no longer works.

I'll make up issues for each of these in the MSlice repository and will try to sort out the crashes soon - I think we should fix them then update the SHA for this PR before merging it to the release branch.

**Comment by NickDraper** [comment]
@mducle The end of Thursday is the latest we could put in a new version for it to make the release.

**Comment by martyngigg** [comment]
@mducle This should bring in the fixes and I've also added some release notes that I thought I added last time but I apparently didn't!

**Review by mducle — APPROVED** [review]
Everything works well for me now. All the identified bugs have been fixed - especially all the crashes.

**Pull request merged**
