### PR TITLE
Load Dialog crash after closing when loading

### LINKED ISSUE #35056: Crash when closing Load dialog after clicking Run
**Describe the bug**
There appears to be a crash when closing the LoadDialog without letting the load finish first. It takes about a minute of waiting for the crash to happen on windows, and it is instant on Ubuntu.

At first glance it seems to be a read access violation due to the LoadDialog being deleted before the finding files is completed.

It is not specific to the instrument. You just need to choose an instrument where it will take a while to find the raw files, or not find them at all.

Exists in Mantid v6.5 too.

**To Reproduce**
Mantid nightly on Windows:

1. I entered 305738, clicked Run and then close.
2. The algorithm dialog closed.
3. I waited for about a minute and did nothing - Mantid then crashed

Mantid nightly on Ubuntu 22:

1. I entered 305738, clicked Run and then close.
2. Mantid crashed immediately.

**Expected behavior**

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: [e.g. Windows, RHEL 7, Ubuntu, macOS]
 - OS Version:
 - Mantid Version [e.g. 6.0.0]

**Additional context**

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR fixes a crash caused by closing the LoadDialog while it was still attempting to load a file.

The code was previously using a while loop to wait for the LoadDialog to search for the specified file before continuing with accepting the dialog. In this while loop it was calling `QApplication->processEvents()` to refresh the GUI. This means you can close the LoadDialog whilst it is still in the while loop, as events are being processed. This is not recommended in the Qt documentation for processEvents https://doc.qt.io/qt-6/qcoreapplication.html#processEvents .

A safer way to handle this is to connect a signal to the FileFinder worker and then do any post-processing in a separate slot function. This means if the LoadDialog is closed while it is still searching for a file, the signal connection is also removed, and this avoids the read access violation.

This has also allowed me to do some cleaning and remove some unnecessary code.

**To test:**
Follow the instructions in the attached issue
Also try load files which should be found successfully

Fixes #35056

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by robertapplin** [comment]
@gemmaguest do you want this moved to the next release? The same crash happens in v6.5

**Comment by gemmaguest** [comment]
> @gemmaguest do you want this moved to the next release? The same crash happens in v6.5

It looks like non-trivial changes to core components so I think that's probably safest, yes, unless we've had reports from users hitting this problem - but I think it was found in developer testing?

**Comment by robertapplin** [comment]
> It looks like non-trivial changes to core components so I think that's probably safest, yes, unless we've had reports from users hitting this problem - but I think it was found in developer testing?

I agree they are non-trivial changes, and yes this was found in developer testing. I have moved it to Release 6.7

**Comment by robertapplin** [comment]
Replaced by #35068

**Pull request closed without merging**
