### PR TITLE
Fixed muon GUI bug that stopped model plot with rebin

### LINKED ISSUE #32809: Model fitting plot not plotting points.
The following steps result in the fitting plot for Model fitting being blank This issue is to find out why it is happening and fix it.

For example
1. Load EMU113007-113012
2. Rebin to 5
3. Fitting range endX 32
6. Flat background + ExpDecayMuon
7. Check fit to raw data
8. Sequential fit all
7. Generate table with sample_temp
8. Go into model fitting set x to sample temp and y to f1.lambda
9. The model fitting plot is empty

### PR DESCRIPTION
**Pull request by AnthonyLim23**
**Description of work.**
When using raw data in the muon GUI, the model plotting would not show anything. This is because it was showing binned data that did not exist. 

A similar bug was found in frequency domain analysis that prevented transformed data being plotted when rebin was used.

**To test:**

Load MUSR62260 into muon analysis
Set Rebin to fixed and enter the value 5
Go to Fitting tab and add an ExpDecayMuon function
Go to the Sequential fit tab and press fit to all
Go tot he results table tab
Select sample_temp from the sample log table (top of the tab)
Click the generate results button
Go to the model tab
The model fitting plot is no longer empty

Open FDA
Load some data
Set Rebin to Fixed and enter 10
Go to transform
Click calculate - you will get a nice plot that fills the x range
Untick the use raw option
Click calculate - the new plot will end at about 200

Fixes #32809 and #32832. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AnthonyLim23** [comment]
unrelated failures

**Comment by AnthonyLim23** [comment]
this also exists in FDA - need to do

**Review by sf1919 — CHANGES_REQUESTED** [review]
The code works as anticipated and it's great to see it is being tested to ensure it works. However I am a little unclear on the purpose of some of the methods as they appear to be empty and return nothing. Could you provide some more information about them and why they work with your solution?

**Review by sf1919 — APPROVED** [review]
I am satisfied with this fix and the explanation of the ```handle_rebin_options_changed``` method.

**Pull request merged**
