### PR TITLE
Fix CMake option call to set expected initial values

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

See commit message for details.

**To test:**

This will require either an empty build directory or removing the CMakeCache.txt and only applies to non-conda builds.

* Run CMake as you would an observe there are not longer warnings related the Qt4.

*There is no associated issue.*

*This does not require release notes* because **it is not a user-facing change.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by DavidFair — COMMENTED** [review]
I'm still getting the same errors locally with this branch:
```
qmake: could not find a Qt installation of ''
-- Found unsuitable Qt version "" from NOTFOUND
```
Unless this resolved different errors?

**Comment by DavidFair** [comment]
> Oh. I got rid of warnings regarding a deprecated automoc macro with Qt4. Did you have a clean build?

I ran `rm -rf build` between each checkout to ensure it was a fresh configuration each time.
Which platform did you see the automoc warning from?

**Comment by martyngigg** [comment]
> > Oh. I got rid of warnings regarding a deprecated automoc macro with Qt4. Did you have a clean build?
> 
> I ran `rm -rf build` between each checkout to ensure it was a fresh configuration each time. Which platform did you see the automoc warning from?

It was on Windows. I was curious as to why those options that were set seem to do nothing and then noticed the wrong number of arguments compared to the CMake documentation.

**Review by DavidFair — APPROVED** [review]
I could reproduce this on Windows, and this fixes the warning I was seeing :+1:

**Comment by martyngigg** [comment]
@mantidproject/gatekeepers Could we get this merged?

**Pull request merged**
