### PR TITLE
Limit progress bar updates to 1000Hz maximum

### LINKED ISSUE #27963: Progress Bar slows down the GUI
**Original reporter:** Jos Cooper / ISIS

### Expected behavior
Executing a Python script in Mantid should be similarly fast to the simple python execution
### Actual behavior
Workbench is much slower if the progress bar is updated too much
### Steps to reproduce the behavior
Ask @DanielMurphy22 for the relevant script and files. It was essentially a script that loaded many ascii files and manipulated them. Timing this execution within the script took 1-2 seconds, but Workbench seems to take more like 10 seconds. 

Workbench is slowed down by having to display things such as messages and most exhaustively, the algorithm progress bar. Simply hiding this Algorithm Toolbox removed the slow down!
The progress bar should be updated less frequently.

### Platforms affected
Workbench all

### PR DESCRIPTION
**Pull request by NickDraper**
**Description of work.**
Filters out progress massages from algorithms that come in less than 1ms since the last one displayed.  This was really slowing down workbench.

The script attached took over 8s in real time to complete before and now 2-3 sec.
[no_misalignment_m1.zip](https://github.com/mantidproject/mantid/files/4220236/no_misalignment_m1.zip)

**Report to:** Jos Cooper

**To test:**
1. You will need a RELEASE BUILD of workbench
1. Run this script and time it with a watch or external timer (don't trust the elapsed times in mantid)
1. It should have completed in about 3 seconds ish.
1. you should still see some progress bar activity.
``` python
from __future__ import (absolute_import, division, print_function, unicode_literals)
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np
import time
#Import all the files into mantid, then run this:
import os

def plotandsave(number, filepathtosave=str("d:/data/no_misalignment/Mcstas_detector_")):
    CloneWorkspace(mtd["TOF_PSD_detector_0_0"], OutputWorkspace="DetectorMcstas")
    for i in range(199,-1,-1):
        AppendSpectra("DetectorMcstas","TOF_PSD_detector_0_"+str(i),OutputWorkspace="DetectorMcstas")
    SaveNexus(mtd["DetectorMcstas"],filepathtosave+"\\McStas_detector_"+str(number)+".nxs")

#plotandsave("Offspec_misaligned")


def loadplotandsave(filepath, detector_name, scan_length):
    if scan_length!=1:
        for i in range(scan_length):
            for j in range(200):
                LoadAscii(str(filepath)+"/"+str(i)+"/"+str(detector_name)+str(j)+".dat",OutputWorkspace=str(detector_name)+str(j))
            plotandsave(str(i),filepathtosave=filepath)
            CloneWorkspace("DetectorMcstas",OutputWorkspace="DetectorMcstas"+str(i))
    else:
        for j in range(200):
            print(str(filepath)+"/"+str(detector_name)+str(j)+".dat")
            LoadAscii(str(filepath)+"/"+str(detector_name)+str(j)+".dat",OutputWorkspace=str(detector_name)+str(j))
        plotandsave("0",filepathtosave=filepath)
        CloneWorkspace("DetectorMcstas",OutputWorkspace="DetectorMcstas")


#Using m=1 plus up at far end not down

start_time = time.time()
filepath = r"d:/data/no_misalignment"
loadplotandsave(filepath, "TOF_PSD_detector_0_",1)
RenameWorkspace("DetectorMcstas","Aligned_Mcstas_m1")
elapsed_time=(time.time() - start_time)
print(elapsed_time)
```
5. Run a long running algorithm, "Pause"? and check you still get progress presented

Fixes #27963.
---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gvardany** [comment]
Would limiting 100Hz speed up the execution further? I don't think human eye can capture more than 100Hz anyhow.

**Comment by gvardany** [comment]
Is this an issue also in MantidPlot?

**Comment by NickDraper** [comment]
@gvardany So I tried 100Hz and 10Hz and did not see any significant performance improvement at those levels above 1000Hz.  If you go up higher to 1MHz which is about the same as before this PR you get the slow down coming back.

If you drop to 10Hz, you see much less activity in the progress bar and it can appear to be idle when it is actually busy.

It doesn't affect Mantidplot, that uses different code for the display, and doesn't seem to suffer from the same problem, perhaps because it is pure C++?

**Comment by Harrietbrown** [comment]
When running this script the progress bar appears idol most the run time, there is a momentary flicker for one frame but only for one frame.

**Comment by DanielMurphy22** [comment]
Could this looking idle (or trying to show progress) depend on Debug vs Release? The 4.2 packaged release shows lots of progress bar activity at the moment (far too much)

**Comment by Harrietbrown** [comment]
In a release build all I get is a flicker of one frame when it doesn't show idle, in a debug build I do get more activity with the script taking longer to run.

**Review by Harrietbrown — APPROVED** [review]
Now that it says running it looks much better. very clear that there is actifity as I can see the bar flicker between running and idle. and the script runs in under 2 seconds
Good Job.

**Pull request merged**
