### PR TITLE
Neaten up the user interface in sliceviewer

### PR DESCRIPTION
**Pull request by NickDraper**
**Description of work.**
Improved layout at the top of the workbench sliceviewer.

Before:
image

After: 
image

**To test:**
1. Start workbench
1. Load TOPAZ_3680_5_sec_MDEW (UNIT TEST)
1. Show the slice viewer, compare it to the images above.  (Ignore the window title)

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — COMMENTED** [review]
I agree the this is better that having the default spacing Qt provides.

While we are fiddling with spacing can we do anything about the marked space around the data widget?
SliceViewerWhiteSpace

**Comment by martyngigg** [comment]
I think we might need a little bit of space around the colorbar as the negative numbers are now chopped off:
SliceViewerWhiteSpaceColorbar

```
SXD23767 = Load(Filename='SXD23767.raw', LoadMonitors='Exclude',
                SpectrumMax=1000)
mdws = ConvertToMD(
        InputWorkspace=SXD23767,
        QDimensions="Q3D",
        dEAnalysisMode="Elastic",
        QConversionScales="Q in A^-1",
        LorentzCorrection='1',
        SplitInto='2',
        SplitThreshold='50',
        MaxRecursionDepth='14')
```
should give something with negative numbers.

**Comment by NickDraper** [comment]
Worth looking at again now.
New after shot:
image

**Comment by NickDraper** [comment]
The plot jumps in size a bit when you change the dimenions, and zooms out a bit when the line plots are added, however it did all of those things before these changes (checked in a recent nightly).

**Review by martyngigg — APPROVED** [review]
This looks much better now and vastly decreases the amount of extraneous whitespace in the sliceviewer.

**Pull request merged**
